### ISSUE TITLE
some error occur when start and message block when edit different file

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#10]
start:

![image](https://user-images.githubusercontent.com/5492542/42920716-bfe0ad24-8b4a-11e8-8895-58e4daeaf6e8.png)

steps:

1. `nvim`
2. `:e test.js`

![image](https://user-images.githubusercontent.com/5492542/42920645-586adfc0-8b4a-11e8-92c2-11106a5405da.png)

**Comment by chemzqm** [comment]
@iamcco Forget to push my code, should be fixed.
