### ISSUE TITLE
ultisnips auto expand

### ISSUE THREAD

**Issue by roberbnd** [neoclide/coc.nvim#1004]
## versions

vim version: NVIM v0.4.0-914-g4841c46e3
node version: v10.16.0
coc.nvim version: 0.0.73-3ce5cabf4c
term: xterm-256color
platform: linux

## Output channel: highlight

[Info  - 12:54:25 PM] Highlight server running in node v10.16.0

## Describe the bug

when I have a snippet and sometimes when expand the pluggin add me a extra line
example here I have this snip
snippet cc "class" bA
class $1
  $2
end
endsnippet

then I type: "cc"  I got: 
class
  |     <- the next with cursor here
end
I type: "cc" I got the image 

![image](https://user-images.githubusercontent.com/4907027/61582286-9594b500-aaee-11e9-94de-bf929903ffe5.png)

Then in this case the first time works perfectly and the second added "endass"

**Comment by chemzqm** [comment]
It was fixed by 46a50885
