### ISSUE TITLE
cygwin doHover action

### ISSUE THREAD

**Issue by cosminadrianpopescu** [neoclide/coc.nvim#1006]
In cygwin, doHover is going to return an empty window. 

If in the `handler/index.ts`, at line 1098 (see below), I add this code after `await this.nvim.command(`pedit coc://document`)`: 

```
const fs = require('fs');
fs.writeFileSync('c:/Users/My/tmp/pwindow', this.documentLines.join("\n"), 'utf8');
await this.nvim.command('pedit c:/Users/My/tmp/pwindow');
```
I will see the correct hover information. To me, this tells me that the info is calculated correctly, the problem is when opening the `coc://document`. So my question is where is this treated, to check out why is not working on cygwin. 

The context that I am talking about:

https://github.com/neoclide/coc.nvim/blob/6c3442061510904d3b2bc02a60d8905bbc79571e/src/handler/index.ts#L1098

**Comment by chemzqm** [comment]
There is autocmd like:
```
autocmd BufReadCmd,FileReadCmd,SourceCmd coc://* call coc#rpc#request('CocAutocmd', ['BufReadCmd','coc', expand('<amatch>')])
```
which should call https://github.com/neoclide/coc.nvim/blob/master/src/workspace.ts#L1217, looks like it's not called.

**Comment by cosminadrianpopescu** [comment]
I'll have a look and try to come up with a PR. Thank you very much.
