### ISSUE TITLE
coc-references preview window only works in nvim

### ISSUE THREAD

**Issue by vedantroy** [neoclide/coc.nvim#1007]
## Result from CocInfo           
                                                                                                                                                                                    
https://pastebin.com/NA8rmd4C

I used a paste because Github formatting wasn't working properly.                 

## Describe the bug
`coc-references` opens a split that shows a preview of the code surrounding each reference. You can navigate the list of references with j and k. Only in neovim, does the preview window update as I press j or k. My neovim and my vim are using the same .vimrc.

Example: Here the preview window is the same even after I press j. This only happens in normal vim.
![Screenshot_1](https://user-images.githubusercontent.com/8407819/61583413-9a189800-ab05-11e9-8017-aea768d5e26b.PNG)
![Screenshot_2](https://user-images.githubusercontent.com/8407819/61583414-9be25b80-ab05-11e9-9587-3fface90459a.PNG)

## Reproduce the bug
I couldn't reproduce it with the minimal .vimrc in vim or neovim. However, one thing I did notice was that with my vim and my .vimrc, when using `coc-reference`, the reference list would would open but the second entry would be selected by default instead of the first. With the minimal .vimrc or neovim using my .vimrc, the first entry in the preview window is selected by default, which I assume is the intended behavior.

I also noticed that with my normal vim, there is a red asterisk next to the entry that is open, while with neovim there is no asterisk.

This picture shows the red asterisk and the fact that the second entry in the reference list is highlighted by default in my vim configuration:
![Screenshot_3](https://user-images.githubusercontent.com/8407819/61583839-d949e780-ab0b-11e9-9fa2-1c6bc3a701e7.PNG)

In Neovim, there is no red asterisk, and the first entry is highlighted, and of course, the preview window works properly:
![Screenshot_4](https://user-images.githubusercontent.com/8407819/61583840-db13ab00-ab0b-11e9-97c7-119daf044388.PNG)

Here is my .vimrc, if that is useful. All the configuration for coc.nvim is at the bottom of the .vimrc in a single section.
https://pastebin.com/GynZGqc7

**Comment by chemzqm** [comment]
> I couldn't reproduce it with the minimal .vimrc in vim or neovim.

I have no idea what happened with your vim plugin/configuration, you need to find it out.

**Comment by vedantroy** [comment]
Alright. I'll work on narrowing down the issue. Do you have any idea what the red asterisk means?

**Comment by chemzqm** [comment]
It means the items is selected, can happen when coc.nvim received `<space>` key on normal mode.

**Comment by vedantroy** [comment]
Ok, I found the issue. When I manually call `call CocAction('jumpReferences')` there is no issue. However, when I use my shortcut `<leader>gr` which is `<space>gr`, then the issue occurs.

Here is the relevant key-binding:
`nmap <silent><leader>gr <Plug>(coc-references)
`

**Comment by vedantroy** [comment]
@chemzqm 

I managed to reproduce the issue with the minimal vimrc.
```vim
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on

" Enable mouse (disables copy-paste to system clipboard): https://stackoverflow.com/questions/4608161/copying-text-outside-of-vim-with-set-mouse-a-enabled
set mouse=a

" don't wrap lines when displaying them
set nowrap

" allow exiting unsaved buffers
set hidden

" Prevent space from moving cursor forward in normal mode
nnoremap <SPACE> <Nop>

" Set the leader key to space
let mapleader=" "

" Disable swap files (swap files allow for recovery if there is a crash
" they also prevent multiple instances of Vim from editing the same file).
set noswapfile

" coc.nvim configuration
" Use ccls for C++ linting, autocomplete, and navigation
" TODO: Figure out why vim language server isn't working
" Some servers have issues with backup files
set nobackup
set nowritebackup

" Causes github issue: https://github.com/neoclide/coc.nvim/issues/1007
" Calling ": call CocAction('jumpReferences') manually does not cause the
" issue
nmap     <silent><leader>gr <Plug>(coc-references)
" Using this key-binding instead of the above keybinding also solves the issue
" nnoremap <silent><leader>gr :Call CocAction('jumpReferences')
" Stuff to make debugging easier--not related to the issue.
" Open split panes to the bottom and right
set splitbelow
set splitright

" Easier switching between splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
```

**Comment by chemzqm** [comment]
What's version of your vim? Your minimal vimrc work as expected for me.

**Comment by vedantroy** [comment]
The issue turned out to be really simple. There was a space at the end of the line that I did not notice. This space caused the space-bar to be pressed after (coc-references) was executed, leading to the first entry being selected (this is why there was an asterisk on the first row). For some reason, nvim ignores the space at the end.
