### ISSUE TITLE
[Feature request] Add a way to reverse the order of results with CocList

### ISSUE THREAD

**Issue by malob** [neoclide/coc.nvim#1008]
**Is your feature request related to a problem? Please describe.**
When searching through lists with `coc.nvim`, I find it a little annoying that the best matchs are placed at the top since it's furthest from where I'm typing (and therefore looking most of the time). Auto-resizing (which I like) adds to the annoyance since the location of the best match moves on the screen as I type. 

**Describe the solution you'd like**
I'd love `:CocList` to have an option like `--reversed` that would reverse the order of the list so that the best matches appear at the bottom. Ideally, there'd also be an easy way to make this the default for all lists (maybe by adding an option to the `coc.nvim` configuration like `list.reversed` which would default to `false`).

**Additional context**
This request is inspired by the same functionality in [`denite.nvim`](https://github.com/Shougo/denite.nvim/blob/3a1b508116652a6c9b4b174ddafaee7852a15fc4/doc/denite.txt#L818).

**Comment by chemzqm** [comment]
PR welcome.

**Comment by vantreeseba** [comment]
I have this started, but I have been busy.

I do plan on finishing and opening PR at some point.

https://github.com/vantreeseba/coc.nvim/tree/list_reverse_items

**Comment by nomasprime** [comment]
Also missing this functionality from denite.

**Comment by snprajwal** [comment]
Will PR for this still be accepted? @chemzqm
