### ISSUE TITLE
No time to read update questions

### ISSUE THREAD

**Issue by gbcreation** [neoclide/coc.nvim#101]
**Describe the bug**

Coc asks "_a new version: 1.0.9 of coc-tsserver detected, update? (y/n)_", but the question has been quickly replaced by the message "_[coc.nvim] service tsserver started_". There is not enough time to read the question (I found it with the `:messages` command). We cannot see that coc is still waiting for the answer. I hit `k` to move cursor, and the message "_Cancelled_" has been displayed. 'k' should have been probably used as the answer for the question.

**Expected behavior**

Suspend start of language servers until updates are processed?

**Comment by chemzqm** [comment]
I would not prefer suspend start of language servers since coc could reactive extension on extension update.
I just need to not echo message when the input is blocked for prompt.
