### ISSUE TITLE
List changes cursor style

### ISSUE THREAD

**Issue by jackielii** [neoclide/coc.nvim#1011]
## versions

vim version: NVIM v0.4.0-dev
node version: v11.15.0
coc.nvim version: 0.0.73-56825890dc
term: screen-256color
platform: linux

## Describe the bug

Adding `set guicursor=a:blinkon1` to minimal configuration and then bring up the CocList will change the cursor style to `|` permanently

workaround is to `set guicursor=n:blinkon1`

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  set guicursor=a:blinkon1

  ```

- Start (neo)vim with command: `vim -u mini.vim`

- `:CocList extensions`

- exit coc list
- cursor style changed to `|`

## Screenshots (optional)

![coc-cursor-bug](https://user-images.githubusercontent.com/360983/61635285-1f798500-ac8b-11e9-97f5-47b74c2bec9d.gif)

**Comment by nbardiuk** [comment]
Can confirm the same behavior
```
vim version: NVIM v0.3.8
node version: v10.16.0
coc.nvim version: 0.0.72-22daa03a7d
term: xterm-256color
platform: linux
```

@jackielii thanks for workaround
> workaround is to set guicursor=n:blinkon1

**Comment by chemzqm** [comment]
`guicursor` reset as expected, should be bug of neovim.

**Comment by chemzqm** [comment]
Can't fix, need neovim support hide cursor https://github.com/neovim/neovim/issues/3688

**Comment by justinmk** [comment]
Since https://github.com/neovim/neovim/pull/11519 cursor can be hidden in TUI now.

**Comment by maricn** [comment]
I still experience this bug on 
```
NVIM v0.5.0-436-ge8269a3ab
linux
node: v12.16.2
```

**Comment by chemzqm** [comment]
Check #1775
