### ISSUE TITLE
Disable autocompletion in the command-line window. 

### ISSUE THREAD

**Issue by shinzui** [neoclide/coc.nvim#1013]
**Is your feature request related to a problem? Please describe.**

I want to disable autocompletion in the command-line-window since it's broken with my setup.

I get the following error:
`E11: Invalid in command-line window; <CR> executes, CTRL-C quits: wincmd k` 

**Describe the solution you'd like**

An option to disable completion in the command-line-window.

**Comment by chemzqm** [comment]
Add `  autocmd FileType vim if bufname('%') == '[Command Line]' | let b:coc_suggest_disable = 1 | endif` in your vimrc

**Comment by againxx** [comment]
Just for a reference, `autocmd CmdwinEnter * let b:coc_suggest_disable = 1` has the same effect for me.
