### ISSUE TITLE
Make triggerCharacters available in vim completion sources

### ISSUE THREAD

**Issue by SevereOverfl0w** [neoclide/coc.nvim#1016]
**Is your feature request related to a problem? Please describe.**

I'm trying to implement a clojure coc.nvim source, and I need to refresh the completions on `/`, etc.

**Describe the solution you'd like**
Returning "triggerCharacters" in the map from `#init()` should make it the triggerCharacters on the source

**Comment by SevereOverfl0w** [comment]
Because this source has built-in fuzziness (e.g. `j.u.D` -> `java.util.Date`) I am using `firstMatch: 0`. But that does mean that sometimes you see out of date results, it might also be useful for me to have access to triggerCompletionWait so that completion will be triggered more regularly.

**Comment by chemzqm** [comment]
`suggest.triggerCompletionWait` is used for wait for server synchronize buffer, I don't think you need to access it. It doesn't affect when the completion should be triggered.

**Comment by SevereOverfl0w** [comment]
what mechanism can I use to ensure that the source is triggered on every key press?

**Comment by chemzqm** [comment]
You have to list each of them in `triggerCharacters`, I'll fix it soon.

**Comment by chemzqm** [comment]
Fixed
