### ISSUE TITLE
CoC Server Failing to Start

### ISSUE THREAD

**Issue by iamrecursion** [neoclide/coc.nvim#1019]
## Result from CocInfo
All I see for running this command is the following in the Neovim command line. There is no further output even if I leave it for some time. 

```
coc.nvim service not started, checking environment...
```

My neovim is a build from HEAD at commit `451f604`, built using homebrew. System is MacOS 10.14.5. 

## Describe the bug
The CoC server appears to fail to start, meaning that I don't get any completion or other facilities. Attempts to use functionality like `:CocList` results in no output, as you'd expect if the server wasn't started.

## Reproduce the bug
1. Create file `mini.vim` with：

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync
endif

let g:plug_shallow=0

call plug#begin('~/.local/share/nvim/plugged')

Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}

call plug#end()

set nocompatible
filetype plugin indent on
syntax on
set hidden
```

2. Start (neo)vim with command: `vim -u mini.vim`
3. Run `:CocInfo` and see that the server hasn't started. 
4. None of the CoC commands will work.

**Comment by chemzqm** [comment]
Run `:messages` or `:CocInfo`

**Comment by iamrecursion** [comment]
As mentioned at the top of the post, `:CocInfo` prints that message and nothing more. Similarly, `:messages` contains nothing relevant.

**Comment by chemzqm** [comment]
Try `yarn install` in folder of coc.nvim.

**Comment by iamrecursion** [comment]
I've done so, and there are no errors. The output is as follows:

```
❯ yarn install                                                                                                                                                                                       ❮ 10:38:40
yarn install v1.17.3
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ npm-run-all clean build
yarn run v1.17.3
$ rimraf lib build
✨  Done in 1.44s.
yarn run v1.17.3
$ tsc -p tsconfig.json
✨  Done in 201.74s.
✨  Done in 212.94s.
```

I still get the `coc.nvim service not started, checking environment...` when I try and run `:CocInfo` however, so I don't think this has made any difference.

**Comment by chemzqm** [comment]
No idea,try release branch out checkout the log file

**Comment by iamrecursion** [comment]
Where does the log file get written to?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim#using-logger-module

**Comment by iamrecursion** [comment]
`:CocOpenLog` doesn't do anything, even with the log level set to maximum. With the release branch head, I see the following in `:CocInfo`:

```
[coc.nvim] javascript file not found, please compile the code or use release branch.
```

**Comment by chemzqm** [comment]
@iamrecursion it means you're not using release branch which have `build/index.js` inside.
Checkout your runtimepath by `:echo &rtp`

**Comment by iamrecursion** [comment]
CoC is on the runtime path, so I'm pretty confused at this point.

**Comment by chemzqm** [comment]
Checkout if `build/index.js` exists, if not, you're not using release branch, also checkout the permision.

**Comment by iamrecursion** [comment]
It does exist, and the permissions on the folder are `rwx` so it should be fine.

**Comment by chemzqm** [comment]
Then you're not using release branch

**Comment by seemethere** [comment]
Pretty sure it has something to do with #1039

**Comment by iamrecursion** [comment]
I was definitely on the release branch, but it looked like a bad clone. I've re-cloned the plugin, and now I'm back to the `coc.nvim service not started, checking environment...` state.

**Comment by chemzqm** [comment]
I think you have `g:coc_start_at_startup = 1` in your vimrc, try command `:CocStart` to start the server, then checkout log of coc.nvim: https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by iamrecursion** [comment]
An explicit `:CocStart` doesn't do anything, and I don't know where the log gets written to. Without the server started, `:CocOpenLog` doesn't do anything, so I don't know where to look for the log.

**Comment by chemzqm** [comment]
You have to use `$NVIM_COC_LOG_LEVEL` then, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim#using-logger-module.

Looks like something killed the node process after on node start.

**Comment by iamrecursion** [comment]
I understand that and have done it, but there's no output. This is very curious.

**Comment by aka830** [comment]
Hi! Have the same problem. Have you found some ways how to solve it

**Comment by chemzqm** [comment]
Reinstall coc.nvim from release branch.

**Comment by aka830** [comment]
Thanks! Its working :)
