### ISSUE TITLE
Create files with CocList

### ISSUE THREAD

**Issue by shtanton** [neoclide/coc.nvim#1022]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, the actions on folders are rename and delete, it would be nice to be able to create a new file in a folder from CocList.

**Describe the solution you'd like**
Select a folder and then action:addfile or something to create the file

**Describe alternatives you've considered**
Currently just :e path/to/new/file.ext which is probably the only file interaction I haven't replaced with lists.

Apologies if this already exists and I just couldn't find it. If it doesn't, I'd be happy to write a PR for it.

**Comment by chemzqm** [comment]
Ok, consider send a PR for it.
