### ISSUE TITLE
Add support for Prolog LSP

### ISSUE THREAD

**Issue by XVilka** [neoclide/coc.nvim#1024]
**Name:** lsp-prolog
**URL:** https://github.com/jamesnvc/lsp_server

Prolog Language server, currently supports showing documentation on hover, go to definition, go to callers, and listing defined symbols in the file. Works with [SWI Prolog](https://www.swi-prolog.org/).

**Comment by chemzqm** [comment]
You should be able to configure it

**Comment by sicr0** [comment]
I actually configured it with Vim as explained in https://github.com/jamesnvc/lsp_server#coc but the documentation doesn't show up. Is there a way to configure it?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
