### ISSUE TITLE
Add tagstack and/or CTRL+T support.

### ISSUE THREAD

**Issue by rantogno** [neoclide/coc.nvim#1026]
When using ctags with CTRL+] to jump to a definition, one can then use CTRL+T to navigate back to the previous position. ":help tagstack" shows what I'm talking about.

I currently can use CTRL+O to go back to the previous jumplist position, but it's not as good as CTRL+T.

Would be nice to have a command that lets you jump back to the point you were before using go to definition.

**Comment by chemzqm** [comment]
You can implement it yourself, checkout `:h CocLocationsChange`.

The definition request could return multiple locations at the same time, the tags feature of vim can't handle it.

**Comment by carltraveler** [comment]
how to config to use ctrl+T and ctrl+]. it's much better than origin vim ctrl+i / ctrl+o

**Comment by chemzqm** [comment]
`:h CocTagFunc()`

**Comment by carltraveler** [comment]
@chemzqm thanks.  perfect.

**Comment by cyniczhi** [comment]
I've been confused by the same issue for over months, thanks god I can get rid or `CTRL-i` and `CTRL-o` finally.

`set tagfunc=CocTagFunc` works perfect for me!
