### ISSUE TITLE
Workspace folder is incorrect when open file using vim-startify

### ISSUE THREAD

**Issue by jackysee** [neoclide/coc.nvim#1027]
The sample file structure:

```
.git\
package.json
package-lock.json
src\App.vue
src\main.js
```
When open a file using [vim-startify](https://github.com/mhinz/vim-startify) start screen,  `CocList folders` always show `/.` even for file in subfolder (e.g. src/App.vue). This would affect other plugins like `coc-eslint` which requires a correct workspace folder to run.

minimal vimrc (with plugins cloned in the folders)
```
set nocompatible 
set runtimepath+=~/.vim/plugged/vim-startify
set runtimepath+=~/.vim/plugged/coc.nvim
```

**Comment by chemzqm** [comment]
What do you mean by `/.` ?
Could be `.git` folder in that directory.

**Comment by jackysee** [comment]
My mistake, the minimial vimrc should be
```
set nocompatible
set runtimepath+=~/.vim/plugged/vim-startify
set runtimepath+=~/.vim/plugged/coc.nvim
let g:startify_change_to_vcs_root = 1
```

When open by vim-startify MRU, `CocList folers` is `/.`
![Screenshot 2019-07-27 at 8 26 34 AM](https://user-images.githubusercontent.com/30516/61987344-77780900-b048-11e9-8b9d-90a8951ea249.png)

When open by fzf
![Screenshot 2019-07-27 at 8 30 26 AM](https://user-images.githubusercontent.com/30516/61987394-d3429200-b048-11e9-904b-36b45de71938.png)

**Comment by chemzqm** [comment]
Still unable to reproduce.

**Comment by jackysee** [comment]
I open vim by `vim -u ~/minimalVimrc`

This only happen when I open file at the start screen, e.g. press [10]
![image](https://user-images.githubusercontent.com/30516/61989926-8de28c80-b069-11e9-92d0-cd84dff7a1c6.png)

The `CocInfo`
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 26 2019 04:36:15)
node version: v10.10.0
coc.nvim version: 0.0.73-56825890dc
term: iTerm.app
platform: darwin

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/Documents/Programs/vueappdemo/src/App.vue" 28L, 516C

```
