### ISSUE TITLE
running yarn install in git repo release checkout fails

### ISSUE THREAD

**Issue by doronbehar** [neoclide/coc.nvim#1029]
This is more of a question rather then a bug report but I do think this is a problem, perhaps it could be only a documentation lack. Also please excuse me for not filling out the bug report template as this is an installation experience issue.

I'm not sure I understand how am I supposed to install the coc.nvim in the release channel. I don't use vim-plug or any other standard plugin manager, I use Neovim 0.3.8 with `~/.config/nvim/pack/*/start/` folders and git clones to manage my plugins.

I noticed that if I clone this repo and run `yarn install` on `master` everything works fine - completion and diagnostics.. But that's not using the stable / release version right?

If on `master` I run `./install.sh`, the plugin seems to do it's job as for some features such as the diagnostic but it doesn't actually suggest to complete words for me.

There is no `./install.sh` script in the tagged checkout and the `release` branch and so I tried running `yarn install` in these checkouts and it always failed with the following error:

```
...
$ tsc -p tsconfig.json
error TS5058: The specified path does not exist: 'tsconfig.json'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Anyway, I'd like to contribute a section for users like me in the [installation page of the wiki](https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim) once I'll figure this out.

Thanks.

**Comment by chemzqm** [comment]
The release branch and latest tag have compiled javascript, no need for yarn install
