### ISSUE TITLE
Jump to next highlighted item

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc.nvim#1038]
**Is your feature request related to a problem? Please describe.**
Currently CoC supports symbols highlighting, but there's no way to jump between highlighted symbols.

**Describe the solution you'd like**
A key combination to jump between highlighted symbols.

**Describe alternatives you've considered**
`#` or `*`

**Comment by chemzqm** [comment]
You can start multiple cursors session and use jump keys https://github.com/neoclide/coc.nvim/wiki/Multiple-cursors-support
