### ISSUE TITLE
v0.0.73 does not include install.sh (also missing a lot of files)

### ISSUE THREAD

**Issue by seemethere** [neoclide/coc.nvim#1039]
## Result from CocInfo

```
coc.nvim service not started, checking environment...  
```

## Describe the bug

There's no `install.sh` inside of the `v0.0.73` tag.

## Reproduce the bug

Not a vim issue, you can check here:

https://github.com/neoclide/coc.nvim/tree/d9f01a6023da4f2186291d32f6a1bf71b47309e6

## Screenshots (optional)

I believe the tag was created on a very old branch.

`v0.0.73`:
<img width="694" alt="Screen Shot 2019-07-29 at 3 07 04 PM" src="https://user-images.githubusercontent.com/1700823/62086259-a04bfa00-b212-11e9-881f-877f97652a0d.png">

`v0.0.72`:
<img width="685" alt="Screen Shot 2019-07-29 at 3 07 12 PM" src="https://user-images.githubusercontent.com/1700823/62086276-a8a43500-b212-11e9-9c06-a98cd0530c5f.png">

CC @chemzqm

**Comment by chemzqm** [comment]
The tag contains bundled javascript https://github.com/neoclide/coc.nvim/blob/v0.0.73/build/index.js
install script not need, you should not use it https://github.com/neoclide/coc.nvim/issues/969

**Comment by seemethere** [comment]
Wait why is that?

What's the reasoning behind having such a big discrepancy between the `release` and `master` branches of this project?

**Comment by chemzqm** [comment]
Most people don't want to compile the code when using tagged release, the install script can be broken for network or other reasons.

**Comment by seemethere** [comment]
Just think there could be a creep in terms of features between the 2 considering they're differentiated now by at least 2k+ commits.

**Comment by chemzqm** [comment]
> Just think there could be a creep in terms of features.

There would always difference between release branch and master.
You can checkout the commits and builtin documentation, it's much more reliable than install script.

**Comment by seemethere** [comment]
You mean this comparison?

https://github.com/neoclide/coc.nvim/compare/master..release

<img width="1010" alt="Screen Shot 2019-07-29 at 3 56 40 PM" src="https://user-images.githubusercontent.com/1700823/62088223-7a762380-b219-11e9-971c-c707ef74a35a.png">

**Comment by chemzqm** [comment]
I mean the difference is not avoidable, it's just harder to figure them out with coc.nvim, so there's a hash tag which can be seen with `:CocInfo`

**Comment by seemethere** [comment]
Did something happen between the last 2 tags?

Appears as though a bunch of committers got removed,

`v0.0.72`
```
❯ git log --oneline v0.0.72 --pretty=format:"%an" | sort -u
Aaron McDaid
Ahmed El Gabri
Amirali Esmaeili
Andy
Andy Lindeman
Avi ד
Bastien Orivel
Brian Embry
chemzqm
Chen Lijun
Chris
Chris DeLuca
Cody Allen
Damien Rajon
Daniel Zhang
daquexian
David Mejorado
depfu[bot]
doza-daniel
Francisco Lopes
Gabriel Sanches
Gavin Sim
Gibson Fahnestock
Giovanni Giordano
Gontran Baerts
greenkeeper[bot]
Heyward Fann
iamcco
Jack Rowlingson
Jasper Poppe
Jean Jordaan
Jonas Holst Damtoft
Joosep Alviste
Josa Gesell
Joshua Rubin
Julio
KabbAmine
karasu
Kevin Rambaud
Kristijan Husak
Lasse Peters
LinArcX
Liu-Cheng Xu
Matthew Evans
Mikaela Szekely
miyanokomiya
naruaway
Nick Hynes
Nicolas Dermine
Paco
Peng Guanwen
PENG Rui
Petter Wahlman
Qiming zhao
Quade Morrison
Ricardo García Vega
Robert Liebowitz
ryantig
sc00ter
Seth Messer
taigacute
Tony Narlock
Vold Notz
X.C.Dong
Yatao Li
Yunzhi Duan
年糕小豆汤
```

`v0.0.73`
```
❯ git log --oneline v0.0.73 --pretty=format:"%an" | sort -u
chemzqm
```

**Comment by chemzqm** [comment]
v0.0.72 is based on master, checkout #969
