### ISSUE TITLE
Diagnostic message still displayed when cursor is moved out of faulty symbol

### ISSUE THREAD

**Issue by gbcreation** [neoclide/coc.nvim#104]
**Describe the bug**

Take for example this simple JavaScript statement: `window.unknownproperty`. When the cursor is on the word `unknownproperty`, the following diagnostic message is displayed: `[tsserver 2339] [E] Property 'unknownproperty' does not exist on type 'Window'`. Then, when moving the cursor on the word `window`, the previous diagnostic message is still displayed.

**Expected behavior**

The previous diagnostic message shouldn't be displayed when cursor is on a non-faulty symbol.

**Comment by chemzqm** [comment]
We can't clear a specified message in vim, if coc clear all messages, it's possible to clear the message from other plugin, it could be resolved when coc use floating window to show the message.

**Comment by chemzqm** [comment]
Fixed
