### ISSUE TITLE
CocList leave an empty buffer, when used with vim-startify

### ISSUE THREAD

**Issue by weirongxu** [neoclide/coc.nvim#1041]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.0-1016-g6f27f5ef9
node version: v10.15.1
coc.nvim version: 0.0.73
term: xterm-256color
platform: linux

## Messages
```

## Describe the bug

CocList leave an empty buffer when first open the CocList.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  set runtimepath^=/path/to/vim-startify
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `nvim -u mini.vim`

- Run `:CocList commands`

- Then press `<esc>` to exit CocList.

## Screenshots

![image](https://user-images.githubusercontent.com/1709861/62103841-43af1480-b2d0-11e9-8487-bd7cdd6100f4.png)

**Comment by voldikss** [comment]
same here

**Comment by chemzqm** [comment]
startify should fix this issue,the list buffer removed as expected

**Comment by weirongxu** [comment]
I found a way to simply reproduce this, just set a `nobuflisted` option

mini.vim
```vim
set nocompatible
set runtimepath^=../coc.nvim
autocmd VimEnter * setlocal nobuflisted
filetype plugin indent on
syntax on
set hidden
```

**Comment by voldikss** [comment]
Just found another method to resolve this problem

https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt#L1044-L1056
