### ISSUE TITLE
WINDOWS: [coc.nvim] javascript file not found, please compile the code or use release branch.

### ISSUE THREAD

**Issue by m5ome** [neoclide/coc.nvim#1043]
Any option how to fix?

**Comment by chemzqm** [comment]
compile the code or use release branch.

**Comment by vincentmader** [comment]
I am getting this error even though I'm importing with 

`Plugin 'neoclide/coc.nvim', {'branch': 'release'}`

**Comment by tavito** [comment]
I resolved this issue by executing this:

    `:call coc#util#install()`

**Comment by chemzqm** [comment]
> I am getting this error even though I'm importing with
> 
> `Plugin 'neoclide/coc.nvim', {'branch': 'release'}`

Vundle doesn't support configure branch like that.
