### ISSUE TITLE
How to change diagnostics color?

### ISSUE THREAD

**Issue by kkoomen** [neoclide/coc.nvim#1045]
The color is `#f00` which hurts my eyes. How can I change the color of the diagnostic signs and the error message balloon? Didn't find anything yet in the default `schema.json`

<img width="669" alt="Screenshot 2019-07-31 at 09 51 33" src="https://user-images.githubusercontent.com/10693490/62177836-03f03780-b379-11e9-8656-26b7bfa49a25.png">

**Comment by chemzqm** [comment]
Please checkout `:h coc-highlights`

**Comment by ultrox** [comment]
I had the same problem, this is what I did:

```
hi! CocErrorSign guifg=#d1666a
" hi! CocInfoSign guibg=#353b45
" hi! CocWarningSign guifg=#d1cd66

```
