### ISSUE TITLE
How to change display of unused variables?

### ISSUE THREAD

**Issue by kkoomen** [neoclide/coc.nvim#1046]
I see that the `$options = array()` gets highlighted with an underline. I've been looking a long time for some plugin that can mimic VSCode behavior by greying-out unused variables. Can I adjust the highlighting of this _specifically_ for unused variables? Would love it if that's an option.

<img width="963" alt="Screenshot 2019-07-31 at 10 20 20" src="https://user-images.githubusercontent.com/10693490/62178805-ec1ab280-b37c-11e9-8c4e-9fc1b71b4218.png">

**Comment by weirongxu** [comment]
Use https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L229-L232

```vim
autocmd ColorScheme *
      \ hi CocErrorHighlight guibg=#904040
      \ | hi CocWarningHighlight guibg=#909040
      \ | hi CocInfoHighlight guibg=#409040
      \ | hi CocHintHighlight guibg=#408090
```

**Comment by chemzqm** [comment]
You overwrite all highlights,checkout doc.

**Comment by krehwell** [comment]
@tomskopek seeing from `:hi`
it seems like you can use `CocUnusedHighlight` to get the unused variable
```vim
highlight CocUnusedHighlight ctermbg=NONE guibg=NONE
```

**Comment by tomskopek** [comment]
Sweet! Thanks @krehwell 
This is exactly what I was looking for

```vimscript
" https://github.com/neoclide/coc.nvim/issues/1046
autocmd ColorScheme *
      \ hi CocUnusedHighlight ctermbg=NONE guibg=NONE guifg=#808080
```

**Comment by NikosAlexandris** [comment]
> Sweet! Thanks @krehwell This is exactly what I was looking for
> 
> ```viml
> " coc.vim
> 
> " https://github.com/neoclide/coc.nvim/issues/1046
> autocmd ColorScheme *
>       \ hi CocUnusedHighlight ctermbg=NONE guibg=NONE guifg=#808080
> ```

Old issue, new "user" here: I've tried you suggestion. I cannot see any difference in terms of unused parameters in a Python function definition, for example. What else do I need to check out?

I use

```
## versions
vim version: NVIM v0.9.2
node version: v20.8.0
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /home/nik/.local/share/nvim/plugged/coc.nvim
term: terminology
platform: linux
```
