### ISSUE TITLE
 E16: Invalid range: call s:Autocmd('Dirchanged', get(v:event,'cmd', ''))

### ISSUE THREAD

**Issue by avriltank** [neoclide/coc.nvim#1047]
Suppose I have two buffers now, /home/chenfa/one.vim and /home/chenfa/two.vim. Now I execute the command in the /home/chenfa/one.vim buffer: cd /home, then execute :bnext, this time vim will report E16: Invalid range: call s:Autocmd('Dirchanged', get(v:event,'cmd', '')), I roughly looked at /coc.nvim/plugin/ The line 170 in coc.vim seems to have an automatic command. Is there a bug here, or is it wrong with me? Thanks！

**Comment by avriltank** [comment]
the autocommand called by  this function coc#rpc#notify('CocAutocmd', a:000) =》s:client['notify'](a:method, a:args)=》s:notify(method, args)。I can not find is there anything wrong。otherwise，if i do not set autochdir in my init.vim,there is no error !

**Comment by chemzqm** [comment]
No idea what happened, it doesn't happens for me on vim8 and neovim.
Need minimal vimrc and vim version.

**Comment by chemzqm** [comment]
From vim's doc `Note: When this option is on some plugins may not work.`

**Comment by MustaphaRashiduddin** [comment]
I also get same error when using neovim-fuzzy

Error detected while processing DirChanged Autocommands for "*":                                                 
E16: Invalid range: call s:Autocmd('DirChanged', get(v:event, 'cwd', ''))

if i do not set autochdir in my init.vim,there is no error.

**Comment by chemzqm** [comment]
Vim or neovim should fix this error, my suggest is avoid `autochdir` option.
