### ISSUE TITLE
format part of code instead of whole buffer

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#105]
**Describe the bug**
format part of code instead of whole buffer when save buffer

**To Reproduce**
https://asciinema.org/a/PazAgOkE88CQpqkWwSOUwpp70

```javascript
function subMultiStr(str = '') {
    let res = new Set();

    str.replace(/(\w{10})(?=\B.*?\1+)/g, (m, one) => {
        res.add(one);
        return '';
    });
    return res.values();
}
```
.eslintrc
```
{
  "extends": "standard"
}
```

**Expected behavior**
format whole buffer

**Comment by chemzqm** [comment]
Looks like your have `eslint.autoFixOnSave` in your settings, but that's not format.
To enable format on save, add the filetype to `coc.preferences.formatOnSaveFiletypes` like:
```
  "coc.preferences.formatOnSaveFiletypes": ["markdown", "javascript"],
```

**Comment by iamcco** [comment]
`eslint.executeAutofix` should fix whole buffer not part of them

**Comment by iamcco** [comment]
have to run `call CocAction('runCommand', 'eslint.executeAutofix')` twice to fix and only enable coc.nvim

**Comment by chemzqm** [comment]
There're overlap of fixes, so they can't be fixed at one time.
This happens in VSCode as well, but VSCode could fire save event even if the file is saved without change

**Comment by chemzqm** [comment]
Fixed, run `:CocInstall coc-eslint` to upgrade eslint extension.
