### ISSUE TITLE
Suggestion only expands after Ctrl-C

### ISSUE THREAD

**Issue by satvikpendem** [neoclide/coc.nvim#1051]
# Result from CocInfo

## versions

vim version: NVIM v0.3.7
node version: v12.7.0
coc.nvim version: 0.0.73-f283b585e3
term: xterm-256color
platform: linux

## Output channel: snippets

# Describe the bug

When using any coc extension such as emmet, the suggestion comes up in the box, then on enter, the suggestion box and the text goes away, elaving me in insert mode. No keys work except Ctrl-C, which then shows the expanded suggestion in select mode. This works in Vim 8.1 but not in Neovim 0.3.7 nor in 0.4.0 dev.

# Reproduce the bug

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden

  call plug#begin('~/.local/share/nvim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

- Use suggestion for anything, for example html:5 in emmet to create the HTML scaffold.

## Screenshots (optional)

[![asciicast](https://asciinema.org/a/260196.svg)](https://asciinema.org/a/260196)

**Comment by chemzqm** [comment]
You have to remap `<CR>` for confirm completion, otherwise it might confirm or not https://github.com/neoclide/coc.nvim/wiki/Using-snippets
