### ISSUE TITLE
Diagnostics floating window breaks vim

### ISSUE THREAD

**Issue by XolotlP** [neoclide/coc.nvim#1053]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  4 2019 23:02:48)
node version: v11.15.0
coc.nvim version: 0.0.73-f283b585e3
term: dumb
platform: linux

## CocConfig

```json
{
    "solargraph.formatting": true,
    "solargraph.diagnostics": true,
    "solargraph.symbols": true
}
```

## Describe the bug

The diagnostics floating window terminates the current vim session if the cursor too close to the righ edge.  

Vim terminates with the following messages:
```
Vim: Caught deadly signal FPE
Vim: Finished.

Floating point exception (core dumped)
```

## Reproduce the bug

  ```vim
  set nocompatible
  filetype plugin indent on
  syntax enable

  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()

  inoremap <expr><Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr><S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
  set updatetime=300
  ```

- Start vim with command: `vim -u mini.vim`

1. Make sure that the editor window is slightly larger that the size of the line
1. Move to a line with an error at the end of the line
1. It should terminate vim with a SIGPFE and a floating point exception (core dumped)

## Screenshots (optional)
The floating window works fine is the window is wider than the text
![working](https://user-images.githubusercontent.com/6028219/62261504-2e72dc80-b3db-11e9-9d91-8db98df0d147.png)

Problems arose when the window is slightly larger than the text
![screencast](https://user-images.githubusercontent.com/6028219/62261826-2cf5e400-b3dc-11e9-82e4-1e73702bb283.gif)

**Comment by chemzqm** [comment]
It's bug of vim8, #1037
