### ISSUE TITLE
The command line is periodically cleaned

### ISSUE THREAD

**Issue by Emigre** [neoclide/coc.nvim#1055]
**EDIT:** I've finally filled in the full bug report template in my next coment below.

Apologies as I don't have time at the moment to create a full bug report. I'll do my best to provide one if I can find the time. Nevertheless, I've thought that it would be good to report the bug.

Bug description:
- After commit 102ca67 the command line of the editor is periodically cleaned
- This happens very quickly, erasing information shown in the command line in less than a second - this includes information messages and messages shown by other plugins

This bug affects the usage of the editor as important information is cleared before the user can read it. I've reproduced the bug in neovim building coc.nvim from source at the mentioned commit with `yarn install --frozen-lockfile`. The bug doesn't occur when building coc.vim from the previous commit.

**Comment by Ende93** [comment]
Can you provide a repo that can reproduce?

**Comment by Emigre** [comment]
I've finally found the time to create the proper bug report with the template, I hope that this will be enough.

## Result from CocInfo
```
## versions

vim version: NVIM v0.3.4
node version: v8.10.0
coc.nvim version: 0.0.73
term: iTerm.app
platform: darwin

## Messages

## Output channel: watchman

[Info  - 10:03:28] watchman watching project: /Users/emigre/code/js/project
[Info  - 10:03:28] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /Users/emigre/code/js/project
[Info  - 10:03:28] subscribing "**/.eslintignore" in /Users/emigre/code/js/project
[Info  - 10:03:28] subscribing "**/package.json" in /Users/emigre/code/js/project
[Info  - 10:03:28] subscribing "**/{.prettierrc,.prettierrc.json,.prettierrc.yaml,.prettierrc.yml,.prettierrc.js,package.json,prettier.config.js}" in /Users/emigre/code/js/project
[Info  - 10:03:28] subscribing "**/[tj]sconfig.json" in /Users/emigre/code/js/project
[Info  - 10:03:28] subscribing "**/package.json" in /Users/emigre/code/js/project
[Info  - 10:03:28] subscribing "**/*.{ts,tsx}" in /Users/emigre/code/js/project
[Info  - 10:03:28] subscribing "**/*.{js,jsx}" in /Users/emigre/code/js/project

## Output channel: prettier


## Output channel: tsserver

[Info  - 10:03:27] Forking TSServer
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/emigre/.node/bin:/Users/emigre/.yarn/bin 
[Info  - 10:03:28] Started TSServer
{
  "path": "/Users/emigre/vim/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.5.1",
    "version": "3.5.1"
  }
}

## Output channel: eslint

[Info  - 10:03:28] ESLint server running in node v8.10.0
[Info  - 10:03:29] ESLint library loaded from: /Users/emigre/.node/lib/node_modules/eslint/lib/api.js
```

## Describe the bug

A clear and concise description of what the bug is.

## Reproduce the bug

- coc.nvim is cloned locally in `/Users/emigre/vim/plugged/coc.nvim`, at commit 102ca67 (the first one that fails)

- Started nvim with `nvim src/model/createModel.js -u ~/code/temp/mini.vim`, with the minimal recommended code in `mini.vim`:

  ```vim
  set nocompatible
  set runtimepath^=/Users/emigre/vim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- `eslint@5.15.1` is installed globally

- the edited file contains the following:

```javascript
// eslint-disable-next-line no-console
console.log("hi");
// eslint-disable-next-line no-console
console.log("bye");
```

- After opening the file, do the following to trigger the bug:

1. `echo 'hello world'`
2. Move the cursor one character to the left by pressing `l` in normal mode

- Expected result: `hello world` remains in the command line

- Actual result: shortly after the movement, `hello world` is cleared from the command line 

## Screenshots (optional)

See here the bug happening. coc.nvim built from commit 102ca67.

![gif showing the bug happening](https://media.giphy.com/media/Q7XvpLTSVqCrIYLZF1/giphy.gif)

And see here the bug not happening. In this case, coc.nvim was built from the previous commit to the one that causes the issue: 371d3878.

![gif showing the bug not happening](https://media.giphy.com/media/kZu6jZ9IA322I8b7uI/giphy.gif)

Finally, here you can see how this issue affects the behaviour of other plugins. While using `git blame` using [fugitive](https://github.com/tpope/vim-fugitive), the information regarding a particular line is hidden quickly and it can't be read.

![example of how the bug affects vim](https://media.giphy.com/media/XcMoHlKRlR4g4DjSh4/giphy.gif)

**Comment by Emigre** [comment]
Thanks @chemzqm 👍
