### ISSUE TITLE
indentline indentLine_leadingSpaceEnabled

### ISSUE THREAD

**Issue by dementor5** [neoclide/coc.nvim#1057]
Is there any news about this problem?
https://github.com/neoclide/coc.nvim/issues/781

**Comment by chemzqm** [comment]
It's not possible to fix since the diagnostic highlight are added using `nvim_buf_add_highlight` which always have lower priority than `matchadd`.

So you have to disable `indentLine_leadingSpaceEnabled` I think.

**Comment by dementor5** [comment]
Whether it is possible to solve this problem in an identline package?

**Comment by chemzqm** [comment]
No, need improve of neovim to allow buffer add highlight have higher priority.
