### ISSUE TITLE
[Feature request] Add a referenceList action

### ISSUE THREAD

**Issue by gbcreation** [neoclide/coc.nvim#106]
Could you please add a new "referenceList" action that would return a list of references for a given symbol (in a similar way to diagnosticList)? It could be used to create sources for plugins like Denite or fzf that offer extended features like preview mode while browsing the source items.
Thank you.

**Comment by gbcreation** [comment]
Thank you for the info. I'm going to try that for fzf.

**Comment by chemzqm** [comment]
I've bundled quickfix source of denite and fzf to coc, you just need some setup:
https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L577
