### ISSUE TITLE
Suggestion: use ctrl+n and ctrl+p to move between list results

### ISSUE THREAD

**Issue by yotamN** [neoclide/coc.nvim#1060]
Currently to move between results in a list I can either use the arrows or ctrl+j and ctrl+k but the standard way to move in a list is with ctrl+n and ctrl+p. Those key bindings are not used in the list so maybe it can be both?

**Comment by chemzqm** [comment]
ctrl+n and ctrl+p are used for navigate history list, just like what shell behavior.

**Comment by chemzqm** [comment]
You can any move command on normal mode, insert mode are mainly used for filter.
