### ISSUE TITLE
:lopen stop working 

### ISSUE THREAD

**Issue by ApolloTang** [neoclide/coc.nvim#1065]
## Result from CocInfo
```
[Info  - 5:13:25 AM] Started TSServer
{
  "path": "/Users/apollotang/1/1-sy/configurations/vim/vim-coc-setting-backup/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.5.1",
    "version": "3.5.1"
  }
}

## Output channel: highlight

[Info  - 5:13:25 AM] Highlight server running in node v12.7.0

```

## Describe the bug

:lopen no longer work

## Reproduce the bug

see:
https://github.com/ApolloTang/coc-bug-report-lopen-doesnot-work

## Screenshots 

the following animation gif show that :lopen window show nothing:

![2019-08-05 05 14 40](https://user-images.githubusercontent.com/1150961/62453439-54ccab00-b740-11e9-8348-6ecd448eea2e.gif)
the above is PlugSnapshot:
```
silent! let g:plugs['coc.nvim'].commit = '9baac0c'
```

Showing below is the expected behaviour (:lopen will populate the location window with coc diagnostics) 

![2019-08-05 04 54 18](https://user-images.githubusercontent.com/1150961/62453623-b4c35180-b740-11e9-8887-8731d9a99ade.gif)
The working version from an early coc version: 
PlugSnapshot: `silent! let g:plugs['coc.nvim'].commit = 'bd19409'`

**Comment by Ende93** [comment]
I tried the repo, `CocList diagnostics` is fine on `9baac0c `.

**Comment by ApolloTang** [comment]
@Ende93 You are correct, it works; but it work only after I `:CocInstall coc-tsserver`
(see animated gif bellow). Note that after I quit vim, I'll have to reinstall coc-tsserver.
The first time when I type `:lopen`, there is a flash of content.

![2019-08-06 00 18 51](https://user-images.githubusercontent.com/1150961/62511092-1090e780-b7e0-11e9-84f2-440dbe3f333c.gif)

**Comment by ApolloTang** [comment]
btw, where the installed location of coc-tsserver ?

**Comment by ApolloTang** [comment]
the bug exist in both macvim (Custom Version 8.1.1722 (157)) and vim (version 8.1.1700)

**Comment by fannheyward** [comment]
extension is installed into `~/.config/coc/extensions/`

**Comment by ApolloTang** [comment]
thanks @fannheyward, so my sandbox is not a sandbox :(

**Comment by atoder** [comment]
I am still having this issue as well

**Comment by chemzqm** [comment]
You have to use :CocDiagnostics command

**Comment by atoder** [comment]
> You have to use :CocDiagnostics command

Thank you! That worked
