### ISSUE TITLE
user configuration for sorting completion items?

### ISSUE THREAD

**Issue by richox** [neoclide/coc.nvim#1070]
**Is your feature request related to a problem? Please describe.**
currently the completion is sorted by text lengths, which is what i dislike. i want them sort in alphabetical ordering. i have to modify `completion.ts` in this way:
`return a.filterText.length - b.filterText.length` =>
`return a.filterText.localeCompare(b.filterText)`

**Describe the solution you'd like**
i think there should be an option to specify which order the completion items are sorted in. for example: let `g:coc_completion_order="alphabetic"` or something similar in coc-settings.json.

**Describe alternatives you've considered**

**Additional context**

**Comment by oblitum** [comment]
Having a way to plug a ranking function would be interesting to have if possible.

**Comment by chemzqm** [comment]
It's not possible, the sort logic for complete items is a bit complex: https://github.com/neoclide/coc.nvim/blob/master/src/completion/complete.ts#L239.
But you can give advice or send PR to improve it.

**Comment by Ende93** [comment]
@richox means just change default behavior `return a.filterText.length - b.filterText.length`, not the full logic.
