### ISSUE TITLE
Using multiple formatters/auto-fixers

### ISSUE THREAD

**Issue by mikker** [neoclide/coc.nvim#1071]
I currently have both Solargraph and the [Sorbet][] language servers running for coding Ruby. Both of them have formatting/auto-fixing features but when I `:call CocAction('format')` nothing happens.

Is there a way to make either both work or choose which one gets precedence over the other?

Thanks!

[Sorbet]: https://sorbet.org

**Comment by fannheyward** [comment]
How do you config the both servers?

**Comment by mikker** [comment]
Solargraph is installed and setup via `coc-solargraph`, Sorbet is run via the custom setting below:

```json
{
  "solargraph.diagnostics": true,
  "languageserver": {
    "sorbet": {
      "command": "srb",
      "args": ["tc", "--lsp", "--enable-all-experimental-lsp-features"],
      "filetypes": ["ruby"],
      "rootPatterns": ["sorbet/config"],
      "initializationOptions": {},
      "settings": {}
    }
  }
}
```

**Comment by chemzqm** [comment]
Checkout your output channel https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
I need make sure format feature is enabled for your solargraph.
To make autofix on save to work, you need coc extension that regist `formatWillSaveUntilHandle` from workspace https://github.com/neoclide/coc.nvim/blob/master/src/workspace.ts#L670
