### ISSUE TITLE
Error while installing extensions 'TypeError: Cannot read property 'latest' of undefined'

### ISSUE THREAD

**Issue by eli-rodriguezperez** [neoclide/coc.nvim#1072]
## Result from CocInfo

```vim
## versions

vim version: NVIM v0.3.8
node version: v10.16.2
coc.nvim version: 0.0.73-6d4508c366
term: iTerm.app
platform: darwin

## Messages
[coc.nvim] Error on install coc-json: TypeError: Cannot read property 'latest' of undefined

```
## Describe the bug

I'm trying to install coc-extensions and getting this error. I'm on a MacBook and it's a fresh install, was using linux before with same `init.vim` and it totally worked. Also have to use a node version manager but tried uninstalling it to see if it was the problem, same behaviour.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- try to `:CocInstall` with whatever extension (EDIT: You can actually put whatever string here. Exception happen before trying to download)

## Screenshots (optional)

![imagen](https://user-images.githubusercontent.com/22303147/62725590-b8432b00-ba15-11e9-83a6-abb904e70390.png)

**Comment by chemzqm** [comment]
check you .npmrc

**Comment by eli-rodriguezperez** [comment]
Thanks, it was that, forgot I was using a custom npmrc at work.
