### ISSUE TITLE
Installation failed / Coc... is not a command

### ISSUE THREAD

**Issue by AndiLeni** [neoclide/coc.nvim#1074]
Hello,
I tried to install coc for gvim, but it seems like coc is not loaded correctly.
````echo executable('yarnpkg')```` echoes 1.
and my ````_vimrc```` file contains the following lines:

````
colorscheme molokai
set guioptions-=T
set guifont=Consolas:h12

call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin
````

:PlugInstall works fine obviously. It says OK after running.
But f.e. :CocInfo or CocInstall somehting just gives me an error, CocInfo is not a comand.

regards
Andi

**Comment by chemzqm** [comment]
check your vim version

**Comment by AndiLeni** [comment]
Hello, vim says it's version 8.1.1830.
