### ISSUE TITLE
How to use results of CocSearch ? 

### ISSUE THREAD

**Issue by ApolloTang** [neoclide/coc.nvim#1080]
After typing `:CocSearch ThemeContext` I am presented with a buffer with match result:

![Screen Shot 2019-08-12 at 3 34 54 AM](https://user-images.githubusercontent.com/1150961/62850886-6539d400-bcb2-11e9-9ea8-7cea5d7b8c76.png)

It said on the top: 
```
Save current buffer to make changes
```
But I don't want to make changes. I want to 'select a match and open the file', but how ? 
```
nmap <silent> gi <Plug>(coc-implementation)
```
does not work.

Didn't  see any documentation entry on CocSearch.

**Comment by chemzqm** [comment]
Press `<cr>`, it's documented in wiki

**Comment by ApolloTang** [comment]
Thanks for quick reply: `<cr>` works !! 

Not sure where this is documented in the wiki though. <--- No worry, I will read the entire wiki

**Comment by your-diary** [comment]
@chemzqm 
In which page of the wiki is `CocSearch` documented?
I'm looking for a way to open the file in a new tab when `<cr>` is pressed.

**Comment by fannheyward** [comment]
@your-diary https://github.com/neoclide/coc.nvim/wiki/Multiple-cursors-support#use-refactor-action

CocSearch is part of `coc-refactor`.

> open the file in a new tab when <cr> is pressed.

No such feature yet, you can't open it in tab.

**Comment by chemzqm** [comment]
I've improved the document.
