### ISSUE TITLE
Debounce and throttle coc-list

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc.nvim#1081]
### Is your feature request related to a problem? Please describe.

I'm frustrated when searches triggered on each key press.

### Describe the solution you'd like

>**Debouncing**
>“Debouncing” is the process of ignoring too frequent events, keeping only the last one in a series of adjacent events. It can be useful to avoid triggering too many search requests, for example when a UI widget is continuously firing updates (e.g. a key press).
>
>**Throttling**
Throttling works in a similar fashion as debouncing, except it ensures a constant throughput. When throttling, calls are delayed no more than a given amount of time before being fired. In other words, at regular intervals, the throttler will fire the latest call. This way, no matter how many calls are made, exactly one per interval is fired.

### Describe alternatives you've considered
Intellij IDEA

**Comment by chemzqm** [comment]
There is debounce already, please be specific of your problem

**Comment by arbitrary-dev** [comment]
>coc-nvim.txt
>Pattern not found: debounce

My problem is when I start interactive session with `:CocList grep`, each key press initiates search and UI/input is lagging in the meanwhile.
