### ISSUE TITLE
CocList resets query on <C-u>

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc.nvim#1082]
## Describe the bug

When scrolling search result for `:CocList grep smth` with <C-d>, everything is fine, but when I want to go up with <C-u>, the query string gets reset.

**Comment by chemzqm** [comment]
What does go up with means?

**Comment by chemzqm** [comment]
It's excepted,please RTFM

**Comment by arbitrary-dev** [comment]
Yep, the FM states:
```
<C-u>       - remove characters before cursor.
```

But it's counter-intuitive for vim users that are accustomed to scroll using `<C-d>` & `<C-u>`, so I propose to change it to something else, `<C-Backspace>` or `<C-H>` for example.

**Comment by chemzqm** [comment]
No, it's same behavior as prompt of shell, you  can remap it.

**Comment by chemzqm** [comment]
or use normal mode for scroll
