### ISSUE TITLE
No cursor in :CocList

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc.nvim#1083]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled May 30 2019 19:25:43)
node version: v12.4.0
coc.nvim version: 0.0.73-1ea838ee4e
term: Apple_Terminal
platform: darwin

## Describe the bug

No cursor in `:CocList`…
```
FUZZY > no_visible_cursor_here
INTERACTIVE > no_visible_cursor_here
```

**Comment by voldikss** [comment]
@arbitrary-dev 

Firstly it's necessary to test on a minimal `vimrc` and see whether you can reproduce the bug. If it still exists, then you'd better provide a screenshot here. Otherwise, you should check your other plugins/configs which led to this bug.

Try a minimal `vimrc` like this.
```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden
```
