### ISSUE TITLE
coc starts regardless of coc_start_at_startup setting

### ISSUE THREAD

**Issue by panders23** [neoclide/coc.nvim#1084]
Hi,

with current Head coc starts, ignoring `let g:coc_start_at_startup = 0` set in vimrc. A quick git bisect showed that this behavior was introduced with 23ed9b8b01280d32cffb9110bd4644c17ba15101
I don't use coc while working on a laptop or edit configurations/markdown and start it explicitly with `:CocStart` when working on projects

**Comment by Ende93** [comment]
Please try `g:coc_start_at_startup`.

**Comment by voldikss** [comment]
I confirm `g:coc_start_at_startup` doesn't work for me, either.  It's possibility a bug.

**Comment by panders23** [comment]
@Ende93 thx, I screwed up. *edit*
