### ISSUE TITLE
CocActionAvailable

### ISSUE THREAD

**Issue by tbodt** [neoclide/coc.nvim#1087]
**Is your feature request related to a problem? Please describe.**
I'd like to map <c-]> to coc-definition but that interferes with using it in vim help files and other projects where I use ctags.

**Describe the solution you'd like**
A function such as `CocActionAvailable` that returns whether the given action is available in the current file. That way I can make a mapping such as
```
nnoremap <expr> <c-]> CocActionAvailable('jumpDefinition') ? CocAction('jumpDefinition') : '\<c-]>'
```

**Comment by fannheyward** [comment]
I've make a function for this case:

```vim
function! s:GoToDefinition()
  if CocAction('jumpDefinition')
    return v:true
  endif

  let ret = execute("silent! normal \<C-]>")
  if ret[:5] =~ "Error"
    call searchdecl(expand('<cword>'))
  endif
endfunction
```
https://github.com/fannheyward/init.vim/blob/7b51d380ead37539b674b233d066096d4319e033/init.vim#L188-L197

```
nmap <silent> gd :call <SID>GoToDefinition()<CR>
```

`gd` for jumping, first use coc's jumpDefinition, then ctags `<C-]>`, finally `searchdecl` in current file.

**Comment by tbodt** [comment]
Thanks for the quick fix!
