### ISSUE TITLE
CTRL-I (to navigate jump list) not working

### ISSUE THREAD

**Issue by andradei** [neoclide/coc.nvim#1089]
Navigation of jump list has keybindings `CTRL-I` and `CTRL-O`. While the latter works, the former doesn't

## Result from CocInfo

```
    1 ## versions
    2
    3 vim version: NVIM v0.3.8
    4 node version: v12.8.0
    5 coc.nvim version: 0.0.73-e9ef666cb5
    6 term: screen-256color
    7 platform: darwin
    8
    9 ## Messages
   10 vim-go: initialized gopls
   11 "app/handlers_***.go" 54L, 1350C written
   12 vim-go: [golangci-lint] SUCCESS
   13
   14 "app/main.go" 85L, 2404C written
   15 vim-go: [golangci-lint] FAIL
   16
   17 "app/handlers_***.go" 54L, 1350C written
   18 vim-go: [golangci-lint] SUCCESS
   19
   20 "app/main.go" 85L, 2404C written
   21 vim-go: [golangci-lint] FAIL
   22 22 lines yanked
   23 22 more lines
   24
   25 4 fewer lines
   26 "app/handlers_***.go" 71L, 1824C written
   27 vim-go: [golangci-lint] SUCCESS
   28
   29
   30
   31
   32
   33 "app/handlers_***.go" 71L, 1824C written
   34 vim-go: [golangci-lint] SUCCESS
   35 "app/handlers_***.go" 69L, 1804C written
   36 vim-go: [golangci-lint] SUCCESS
   37
   38 "app/handlers_***.go" 69L, 1804C written
   39 vim-go: [golangci-lint] FAIL
```

## Describe the bug

`CTRL-I` Is not navigating the Vim jump list as it should. The error shown is:

```
[coc.nvim] Selection range provider not found for current document
```

## Reproduce the bug

- Install coc.nvim
- Install vim-go
- Press `CTRL-I ` to navigate the jump list

**Comment by chemzqm** [comment]
`<C-i>` is tab on vim，it's vim issue

**Comment by deepflame** [comment]
@andradei I had the same issue.

As pointed out <C-i> is mapped to <TAB> in VIM. This cannot be changed (yet) as you can read [here](https://superuser.com/questions/770068/in-vim-how-can-i-remap-tab-without-also-remapping-ctrli).

You probably got this mapping from the [Example VIM configuration](https://github.com/neoclide/coc.nvim#example-vim-configuration) like me where it reads:

```vim
" Use <tab> for select selections ranges, needs server support, like: coc-tsserver, coc-python
nmap <silent> <TAB> <Plug>(coc-range-select)
xmap <silent> <TAB> <Plug>(coc-range-select)
xmap <silent> <S-TAB> <Plug>(coc-range-select-backword)
```

**Comment by andradei** [comment]
Got it. I'll be either deleting the mappings above or remapping <C-i> to something else.
Thanks.

**Comment by andrestone** [comment]
What would be the workaround to jump in?

**Comment by chemzqm** [comment]
Not use `<C-i>`, it's `<tab>`

**Comment by andrestone** [comment]
I understand that `<C-i>` is the same as `<TAB>` and I can't change it.

What I want to know is how to use `<TAB>` / `<C-i>` for completion and still have another key bound to jumping in. 

Isn't there some sort of workaround that can be done to bind some other key to jump to next location?

Thanks.

**Comment by chemzqm** [comment]
> Isn't there some sort of workaround that can be done to bind some other key to jump to next location?

Use `"list.nextKeymap"` and `"list.previousKeymap"` in your coc-settings.json

**Comment by dagadbm** [comment]
a decent key maping for this is Ctrl-l which is just below o!:

```
" Since Tab and Ctrl-I are interchaneable in vim i need to map Ctrl-l to serve as a workaround of ctrl-i
nnoremap <C-l> <C-i>
```

**Comment by dxuehu** [comment]
hm i only have
```
nmap <silent> <TAB> <Plug>(coc-range-select)
xmap <silent> <TAB> <Plug>(coc-range-select)
```
so I remapped them to `<S-TAB>`

**Comment by atomsfat** [comment]
Some guys are remaping c_i in the terminal https://vi.stackexchange.com/questions/9839/how-to-use-jumplists-c-i-which-is-seen-as-a-tab
