### ISSUE TITLE
Floating windows doesn't show documentation/definition on hover

### ISSUE THREAD

**Issue by emrahc** [neoclide/coc.nvim#1095]
## Result from CocInfo

 

 vim version: NVIM v0.4.0-1679-g947bd293c
   node version: v12.8.0
   coc.nvim version: 0.0.73
   term: xterm-256color                                                                                                                  
   platform: linux                                                                                                                       
                   

#A clear and concise description of what the bug is.

I can see suggestions,snippets explaination on floating window. Also linting on hover. But can't see documantation,definition on hover floating.

I have tried  ;

 "coc.prefences.hoverTarget":"echo",     
 "coc.prefences.hoverTarget":"preview",                                                                                               
 "suggest.floatEnable": true,

Not working.

**Comment by Avi-D-coder** [comment]
Have you tried `"coc.preferences.hoverTarget": "float"`?

**Comment by emrahc** [comment]
@Avi-D-coder  yeah i have tried. Not working

**Comment by chemzqm** [comment]
Configuration could be overwritten by your vimrc, try minimal vimrc.

**Comment by hasufell** [comment]
Same here, can reproduce. Setting is ignored in vim.

**Comment by horseinthesky** [comment]
@chemzqm Same for me here. What VIM option can override it?

**Comment by chemzqm** [comment]
Try upgrade your vim8.

**Comment by horseinthesky** [comment]
I'm using NVIM v0.3.8.

Is it what I need?
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-make-preview-window-shown-aside-with-pum

I'm asking cuz Mine `echo has('textprop') && has('patch-8.1.1522')` echos 0.

**Comment by fannheyward** [comment]
You need to use neovim 0.4+ for floating window.

**Comment by horseinthesky** [comment]
Installed `nvim` 0.5.0 from snap. Now it works. Thank you.

**Comment by hasufell** [comment]
> Try upgrade your vim8.

I'm on vim8.

**Comment by chemzqm** [comment]
@hasufell https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-make-preview-window-shown-aside-with-pum make sure your vim meet the requirement.

**Comment by Zeioth** [comment]
I'm on vim8.2 but I can't see documentation/definition on hover.
