### ISSUE TITLE
Watchman and phplsp cause more than cpu usage 100 %  when watchman consider the parent git repository (theory)

### ISSUE THREAD

**Issue by rodrigore** [neoclide/coc.nvim#1097]
## versions

vim version: NVIM v0.4.0-dev
node version: v12.5.0
coc.nvim version: 0.0.74-bc017b02e6
term: iTerm.app
platform: darwin

## Output channel: snippets
[Info  - 23:55:05] watchman watching project: /Users/rodrigore/.config/coc/ultisnips
[Info  - 23:55:05] subscribing "**/*.snippets" in /Users/rodrigore/.config/coc/ultisnips

## Output channel: watchman
[Info  - 23:55:05] watchman watching project: /Users/rodrigore/Homestead/projects/desafio-videos
[Info  - 23:55:05] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /Users/rodrigore/Homestead/projects/desafio-videos
[Info  - 23:55:05] subscribing "**/.eslintignore" in /Users/rodrigore/Homestead/projects/desafio-videos
[Info  - 23:55:05] subscribing "**/package.json" in /Users/rodrigore/Homestead/projects/desafio-videos
[Info  - 23:55:24] watchman watching project: /Users/rodrigore/Homestead
[Info  - 23:55:24] subscribing "**/*.{php,phtml}" in /Users/rodrigore/Homestead

## Output channel: phpls
[Info  - 23:55:24] Initialising intelephense 1.1.6
[Info  - 23:55:24] Reading state from /Users/rodrigore/.config/coc/extensions/coc-phpls-data/b93a13b.
[Info  - 23:55:24] Initialised in 16 ms
[Info  - 23:55:24] Intelephense 1.0.14
[Info  - 23:55:24] {
    "name": "initialised",
    "properties": {
        "version": "1.1.6",
        "machineId": "fec7d13a4889caa430dd2c49ce4573dbac9d6f07997ee5f006cd1db72d3de999",
        "platform": "darwin",
        "clientName": "unknown"
    }
}
[Info  - 23:55:24] Indexing started.
[Info  - 23:55:26] Indexing ended. 98 files indexed in 1s.

## Describe the bug

I have all my project inside the 'Homestead' directory (a lot of Laravel projects), and I noticed that I create a new project called *desafio-videos" but not initialize a 'git'. The result is that if you see the 'CocInfo' the output the directory project is *desafio-videos* is not the root of the watchman output:

([Info  - 23:55:24] watchman watching project: /Users/rodrigore/Homestead
[Info  - 23:55:24] subscribing "**/*.{php,phtml}" in /Users/rodrigore/Homestead)

instead watchman consider the root as 'Homestead', so inteliphense start to indexing a lot of files and I asumme that this start to rise the cpu usage more than 100% percent (checkout the screenshoot) but i'm not sure.

To fix this issue I start a git repository inside my new project and the issue is gone.

## Screenshots (optional)

Before 
![image](https://user-images.githubusercontent.com/1557305/63238320-e396f880-c213-11e9-971b-f661546007fb.png)

This is the new output without issues after doing 'git init'
## versions

vim version: NVIM v0.4.0-dev
node version: v12.5.0
coc.nvim version: 0.0.74-bc017b02e6
term: iTerm.app
platform: darwin

## Messages
[coc.nvim] intelephense indexing ...
## Output channel: snippets

[Info  - 23:58:44] watchman watching project: /Users/rodrigore/.config/coc/ultisnips
[Info  - 23:58:44] subscribing "**/*.snippets" in /Users/rodrigore/.config/coc/ultisnips

## Output channel: watchman

[Info  - 23:58:44] watchman watching project: /Users/rodrigore/Homestead/projects/desafio-videos
[Info  - 23:58:44] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /Users/rodrigore/Homestead/projects/desafio-videos
[Info  - 23:58:44] subscribing "**/.eslintignore" in /Users/rodrigore/Homestead/projects/desafio-videos
[Info  - 23:58:44] subscribing "**/package.json" in /Users/rodrigore/Homestead/projects/desafio-videos
[Info  - 23:58:44] subscribing "**/*.{php,phtml}" in /Users/rodrigore/Homestead/projects/desafio-videos

## Output channel: phpls

[Info  - 23:58:44] Initialising intelephense 1.1.6
[Info  - 23:58:44] Reading state from /Users/rodrigore/.config/coc/extensions/coc-phpls-data/104db30d.
[Info  - 23:58:44] Initialised in 13 ms
[Info  - 23:58:44] Intelephense 1.0.14
[Info  - 23:58:44] {
    "name": "initialised",
    "properties": {
        "version": "1.1.6",
        "machineId": "fec7d13a4889caa430dd2c49ce4573dbac9d6f07997ee5f006cd1db72d3de999",
        "platform": "darwin",
        "clientName": "unknown"
    }
}
[Info  - 23:58:44] Indexing started.
[Info  - 23:58:46] Indexing ended. 190 files indexed in 1s.
[Info  - 23:58:46] Writing state to /Users/rodrigore/.config/coc/extensions/coc-phpls-data/104db30d.
[Info  - 23:58:46] Wrote state in 0.2s.

![image](https://user-images.githubusercontent.com/1557305/63238638-6a000a00-c215-11e9-8cff-f5cc588a9899.png)

**Comment by fannheyward** [comment]
Please provides a minimal vimrc to reproduce this error.

**Comment by rodrigore** [comment]
I try with the same template mini.vim

set nocompatible
set runtimepath^=/Users/rodrigore/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

**Comment by chemzqm** [comment]
You have to use rootPatterns to fix your workspace folder https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

**Comment by rodrigore** [comment]
@chemzqm Thanks for the fast answer, I didn't know about that feature.
Just for curiosity, is normal that the cpu raise too much when the root folder have a lot of files?

**Comment by chemzqm** [comment]
No, it's because your language server have bad performance while index lots of files.
