### ISSUE TITLE
[Feature request] Add a way to perform an operation on a multiple cursors item

### ISSUE THREAD

**Issue by Ironimus** [neoclide/coc.nvim#1098]
**Is your feature request related to a problem? Please describe.**
When using multiple cursors there seem to be no way to perform an operation on a cursors item under cursor (ugh, the terminology sucks, we should create another word for one of them) if it's not something you can just edit with operators like `iw` or `aW`.

**Describe the solution you'd like**
Something similar to `gn` would be great, but `gn` works only with search results and not with cursors. You could map it to `g<C-n>` or even better to just create a function users could map to whatever they want.

**Describe alternatives you've considered**
I tried to use plugin kana/vim-textobj-syntax with no luck. The problem seems to be that the function `synstack` used by the plugin internally doesn't recognize `CocCursorRange` highlight group. I'm not very good at VimScript so I might be wrong though, if it's possible to make a few changes to my init.vim and create an `omap` that would select this range, I'd be happy.

**Comment by chemzqm** [comment]
It's not possible unless vim provide the API to perform the same action with multiple locations.
It could be smarter to detect actions like delete word and delete all.
