### ISSUE TITLE
vim-easymotion disturbs diagnostics

### ISSUE THREAD

**Issue by Gontran-Molotov** [neoclide/coc.nvim#110]
**Describe the bug**
Don't know if this bug should be reported here or on [vim-easymotion](https://github.com/easymotion/vim-easymotion) (or both)? When all possible choices of jump are highlighted by easymotion, diagnostics report a lot of errors.

**Expected behavior**
Diagnostics should not analyze buffer changes when easymotion is waiting for a motion trigger.

**Screenshots**

![screenshot_20181002_135842](https://user-images.githubusercontent.com/25483887/46347276-4e1a6680-c64b-11e8-9a3e-7819b55aa7ff.png)

![screenshot_20181002_135554](https://user-images.githubusercontent.com/25483887/46347200-072c7100-c64b-11e8-83a1-86a44ed31b58.png)

**Comment by chemzqm** [comment]
There is `s:EasyMotion_is_active` but coc could not retrieve that script variable to disable/enable document change event.  To fix this, easymotion should either expose `EasyMotion_is_active` as global variable or trigger `User autocmd` on activate and deactivate.

**Comment by gbcreation** [comment]
Could `EasyMotion#is_active()` be used for that?

See https://github.com/easymotion/vim-easymotion/blob/1a0244c90c3ff46219cf9597bb13662be4232407/autoload/EasyMotion.vim#L775

**Comment by chemzqm** [comment]
It could be used, but could make didChange a bit slower.
I think that easymotion should use conceal feature instead of change the buffer content.

**Comment by chemzqm** [comment]
Looks like that variable can't be used for skip buffer change event. https://github.com/easymotion/vim-easymotion/issues/388

**Comment by keelii** [comment]
I have the same issue for this, I just put `autocmd` to solve this problem temporarily, but it's surely not the best solution, waiting for easy-moation to fix it.

```vim
augroup FixConflict
    autocmd!
    au InsertEnter *.js CocEnable
    au InsertLeave *.js CocDisable
augroup END
```
Maybe the custom event in `multiple_cursors` plugin solve the same problem, if there are `Easymotion_before` and `Easymotion_after` event, everything would be fine.

```vim
function! Multiple_cursors_before()
    " ...
endfunction

function! Multiple_cursors_after()
    " ...
endfunction
```

**Comment by desmap** [comment]
@chemzqm I still get false errors from coc when using easymotion. I loaded easymotion before coc and use <Plug>easymotion-b and <Plug>easymotion-w on <C-h> and <C-l>

**Comment by voldikss** [comment]
@desmap I just replaced vim-easymotion with coc-smartf, which works pretty well. You might as well have a try if you really can not resolve your problem.

**Comment by desmap** [comment]
@voldikss man you are great, thanks, what I like about easymotion is not the easymotion-f feature but the easymotion-w (and easymotion-b) they allow even faster jumping, compare the two workflows.

f-workflow (also coc-smartf):
1. see the target => 2. press f => 3. press the target's letter => 4. see the label => 5. enter the label letter(s)

w-workflow
1. see the target =>2. press w => 3. see the label => 4. enter the label

It's not just one step less but a way more fluid motion. With easymotion you can even restrict it to a specific line to have then one-letter labels.

**Comment by chemzqm** [comment]
Can't fix, easymotion should expose some variable indicate it's activated.

**Comment by desmap** [comment]
@voldikss I tried now smartf for a day or so and it's actually quite ok, so maybe I'll stick with it

@chemzqm thanks for the info and good to know

**Comment by kujohn** [comment]
smartf didn't work well for me. Are there ways to temporarily fix the issue?

**Comment by kujohn** [comment]
For certain type of document like `.go` it doesn't trigger this type of issue. Seems to only trigger using `.js`.

**Comment by chemzqm** [comment]
@kujohn if you have issues with smartf, create issue for it with reproduce steps.

**Comment by kujohn** [comment]
It’s an issue I am having with coc and easy motion, not smartf.

**Comment by chemzqm** [comment]
@kujohn could you provide detail information about the issue?

**Comment by abenz1267** [comment]
I'm facing the same issue. Took at look at smartf, but it doesn't fit my workflow at all. With easymotion i can just press <Space> and it'll allow me to jump to every beginning of a word on the complete file, which works really well and fast for me. smartf is too cumbersome to use in that case sadly.

I hope diagnostics will be able to ignore easymotion characters. It seems to slow down nvim as well. It gets very laggy for me.

Regards

**Comment by Galicarnax** [comment]
The problem is still there, not clear why the issue is closed. It bugs me periodically with python files. Replacing easy-motion with smartf is not a solution as they are too different (e.g., no analog for  easymotion-w).

**Comment by chemzqm** [comment]
@Galicarnax I can't reproduce, you need checkout if this check works https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/util.vim

**Comment by SiNBizkit** [comment]
I have the same issue with the clangd diagnostic.

**Comment by Zeta611** [comment]
@SiNBizkit I'm having the same issue as well...

**Comment by oblitum** [comment]
metoo comments are not helpful, just upvote the issue.

**Comment by chemzqm** [comment]
Can't reproduce

**Comment by elebeaup** [comment]
I have the same issue with coc-json and easymotion using easymotion-sn. If I search a double quote and I jump to the target, I have a false linter error (double quote error because the double quote is replaced by the target key)

**Comment by chinnkarahoi** [comment]
i use TextChanged to disable coc temporarily
```vim
let g:easymotion#is_active = 0
function! EasyMotionCoc() abort
  if EasyMotion#is_active()
    let g:easymotion#is_active = 1
    CocDisable
  else
    if g:easymotion#is_active == 1
      let g:easymotion#is_active = 0
      CocEnable
    endif
  endif
endfunction
autocmd TextChanged * call EasyMotionCoc()
```

**Comment by numToStr** [comment]
> i use TextChanged to disable coc temporarily
> 
> ```viml
> let g:easymotion#is_active = 0
> function! EasyMotionCoc() abort
>   if EasyMotion#is_active()
>     let g:easymotion#is_active = 1
>     CocDisable
>   else
>     if g:easymotion#is_active == 1
>       let g:easymotion#is_active = 0
>       CocEnable
>     endif
>   endif
> endfunction
> autocmd TextChanged,CursorMoved * call EasyMotionCoc()
> ```

This works and is definitely better than those annoying ts error. But enabling/disable is a little bit slow but not deal-breaking.
Is anyone knows how to disable `[coc.vim] Event {enabled, disabled}` message at the bottom?

**Comment by kujbika** [comment]
Im having the exact same issue.

**Comment by frandsoh** [comment]
@numToStr 
> Is anyone knows how to disable `[coc.vim] Event {enabled, disabled}` message at the bottom?

Add `silent!` in front of `CocDisable` and `CocEnable`
e.g. `silent! CocDisable`

**Comment by paraduxos** [comment]
[This PR officially solved.](https://github.com/easymotion/vim-easymotion/pull/440#issuecomment-727844125)

The problem is `diagnostic sign` keep disappearing after jump.
(I tested on `.js` and `.rs` with `line jump`)

**Comment by kujbika** [comment]
> [This PR officially solved.](https://github.com/easymotion/vim-easymotion/pull/440#issuecomment-727844125)
> 
> The problem is `diagnostic sign` keep disappearing after jump.
> (I tested on `.js` and `.rs` with `line jump`)

The issue does not seem to be resolved.

**Comment by zSucrilhos** [comment]
Any updates?

**Comment by vifm9** [comment]
@chemzqm the problem is only occur when easymotion is triggered from a blank line (not a blank character).
im using clangd diagnostics.

**Comment by chemzqm** [comment]
If you want it get fixed, provide full information needed to reproduce.

**Comment by ecogest** [comment]
Solutions above did not work great for me, but this one did : https://github.com/easymotion/vim-easymotion/pull/440#issuecomment-727844125
```vim
autocmd User EasyMotionPromptBegin silent! CocDisable
autocmd User EasyMotionPromptEnd silent! CocEnable
```

**Comment by zSucrilhos** [comment]
> Solutions above did not work great for me, but this one did : [easymotion/vim-easymotion#440 (comment)](https://github.com/easymotion/vim-easymotion/pull/440#issuecomment-727844125)
> 
> ```viml
> autocmd User EasyMotionPromptBegin silent! CocDisable
> autocmd User EasyMotionPromptEnd silent! CocEnable
> ```
> 
> Yet, at the moment, it seems to be working only with single window motions, not the overwin ones. Still, I can finally use vim-easymotion again !

Nice! Going to try it out

**Comment by oblitum** [comment]
CocDisable/CocEnable solutions are not that great as reloading language servers may require source reanalyzes, which may require lots of resource & time. But I can't see a solution either as easymotion changes buffer contents.

**Comment by oblitum** [comment]
For NeoVim users, [hop.nvim](https://github.com/phaazon/hop.nvim) is the easymotion alternative I'm picking, it's really nice and avoids the hacky implementation of vim-easymotion. No problems with coc.nvim.
