### ISSUE TITLE
Installing local development extensions

### ISSUE THREAD

**Issue by amiralies** [neoclide/coc.nvim#1107]
is there docs on how to intall development extensions? i was wondering `:CocInstall file:///<Path>` might work

**Comment by fannheyward** [comment]
Use `set runtimepath^=~/src/coc-test`.

**Comment by amiralies** [comment]
Thanks! It Works,
im going to close this issue

**Comment by eyalk5** [comment]
I tried this on coc-python (my version), and it says

`Skipped extension  "/Users/eyalkarni/vimpy3/plugged/coc-python", please remove "coc-python" from your vim's plugin manager.`

it is not on vim-plug. I tried to rename the folder and it didn't work.

**Comment by chemzqm** [comment]
@eyalk5 it's in your `&rtp`, you have to check it out yourself.

**Comment by weirongxu** [comment]
Do you have try `:CocUninstall coc-python` to remove it?
