### ISSUE TITLE
Weird and unexpected completion behaviour

### ISSUE THREAD

**Issue by svanharmelen** [neoclide/coc.nvim#1112]
## Result from CocInfo

vim version: NVIM v0.4.0-dev
node version: v12.9.0
coc.nvim version: 0.0.74-c97d41aa1e
term: screen-256color
platform: darwin

## Describe the bug

I'm seeing some weird/buggy completion behavior. When trying to debug the issue myself I noticed 3 distinct issues which I think are all related to each other. I'll describe my findings in details below. 

## Reproduce the bug

To reproduce the bugs I used the following `mini.vim`:

```
set nocompatible
set runtimepath^=/Users/svanharmelen/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

For the first 2 bugs I used the following `coc-settings.json`:

```
{
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".git/"],
      "filetypes": ["go"]
    }
  }
}
```

For the last bug I added `"suggest.noselect": false`

All bugs are reproduced by first creating a `main.go` file (in a new directory) and then editing that single file (see the screenshots for the exact content).

## Bug 1

I noticed that when vim looses focus, the first completion suggestion suddenly gets selected (even when `"suggest.noselect": true`). I noticed this behavior as I appear to have a plugin which trigger after x time after making the last change, that then causes this exact same behavior even when I'm not manually switching to another app:

![issue2](https://user-images.githubusercontent.com/4171547/63648346-db1c5180-c72e-11e9-9422-97e4f6a4cf5b.gif)

## Bug 2

When only one suggestion is available it becomes automatically selected, even when `"suggest.noselect": true`:

![issue1](https://user-images.githubusercontent.com/4171547/63648366-25053780-c72f-11e9-9e9f-b955be05a0b9.gif)

## Bug 3

When adding `"suggest.noselect": false` and then trying to select the second completion suggestion by pressing `C-n` once, the text of the second suggestion is inserted by the first suggestion is selected again:

![issue3](https://user-images.githubusercontent.com/4171547/63648399-888f6500-c72f-11e9-9aeb-4680902ab28a.gif)

**Comment by svanharmelen** [comment]
If you want I can of course create 3 separate issues for these, but it seems they are all somewhat related.

**Comment by iamcco** [comment]
maybe you should check `suggest.enablePreselect` option, it's default true.

**Comment by svanharmelen** [comment]
Thanks for your reply @iamcco, that does indeed seem to improve things a little. The docs don't really describe what this options does and/or how it works. Do you have any more info on that?

I'll pay around with it a little to see if its a solution to my findings. Thanks!

**Comment by svanharmelen** [comment]
This seems to fix it, so I'll close this issue even through it's still unclear to me what this feature is supposed to do 😏

**Comment by oblitum** [comment]
I've opened #1127 for the previous behavior.
