### ISSUE TITLE
How to configure commit characters?

### ISSUE THREAD

**Issue by svanharmelen** [neoclide/coc.nvim#1114]
Asked this on Gitter first, but got no response so trying it here as well.

I'm looking at `suggest.acceptSuggestionOnCommitCharacter` and am wondering how to configure commit characters for custom LSP's? Mainly looking at the Rust and Go LSP's which I added directly to my `coc-settings.json`.

I noticed that in the `coc-tsserver` plugin it sets the characters in a variable called `commitCharacters` which seems to be used directly by `coc.nvim`. But is there another way to configure these characters when adding LSP's directly to your config? I.e. is there a field in the `languageserver` block that can be used to configure commit characters per configured LSP?

**Comment by chemzqm** [comment]
You can't, its specified by language server.
