### ISSUE TITLE
highlight autocmd issue

### ISSUE THREAD

**Issue by siddharth99** [neoclide/coc.nvim#1117]
I'm running into a weird issue where the highlight autocmd has dozens of call to CocActionAsync('highlight') causing neovim to get stuck for a while; not sure if it's due to some configuration issue on my end or some bug in coc.nvim; please advise.

```
nvim --version
NVIM v0.4.0-738-g8330cc22a
```

![image](https://user-images.githubusercontent.com/3825449/63710625-9fa18600-c807-11e9-801a-f265e7b1dcca.png)

**Comment by Ende93** [comment]
Can you provide minimal vimrc that could reproduce the issue ? Thank you.

**Comment by chemzqm** [comment]
Can't reproduce

**Comment by chemzqm** [comment]
You have register autocmd multiple times
