### ISSUE TITLE
(minor) CocConfig - doesn't work with relative path

### ISSUE THREAD

**Issue by mikeTWC1984** [neoclide/coc.nvim#1120]
I'm trying to use custom node/npm binaries located in my home directory. Somehow cocnvim can't recognize ~ as home, so I have to concat $HOME 

this works
```
let g:coc_node_path = $HOME . "/custom/node/bin/node"
call coc#config("npm.binPath", ($HOME . "/custom/node/bin/npm"))
```
this will not work
```
let g:coc_node_path =  "$HOME/custom/node/bin/node"
let g:coc_node_path = "~/custom/node/bin/node"
let g:coc_node_path = "\~/custom/node/bin/node"
```

Also, it probably would make sense to have some variable to indicate node bin folder instead of setting node and npm separetly (smth like  g:coc_node_bin)

**Comment by chemzqm** [comment]
> make sense to have some variable to indicate node bin folder instead of setting node and npm separetly

No, I think that would just be more confusing since node and npm work independently.
