### ISSUE TITLE
Feature request: toggling integrated console

### ISSUE THREAD

**Issue by mikeTWC1984** [neoclide/coc.nvim#1121]
It would be very useful to have Toggle/Show/Hide integrated console functionality out of the box. Another good option is to set console background/foreground colors and direction (vertical/horizontal).

**Comment by chemzqm** [comment]
There're vim api to do what you want to, but we can't provide GUI buttons in TUI, so please clarify what you want to do.

**Comment by mikeTWC1984** [comment]
No, it's not about GUI. Something like NERDTreeToggle, but for integrated console as a CocCommand. I'm not sure there is a way to get buffer name of that console in vim script. It's simple update in extension source code, but the author suggest it's better to do it globally.

**Comment by TylerLeonhardt** [comment]
I think @mikeTWC1984's request is to have a CocCommand that fires the show/hide methods on the active terminal:

https://code.visualstudio.com/api/references/vscode-api#Terminal

**Comment by fannheyward** [comment]
I wrapped @chemzqm 's gist https://gist.github.com/chemzqm/e22ddf489ec24c7d21bbcb047f4b3f86 to an extension, https://github.com/fannheyward/coc-terminal, with a command `terminal.Toggle` to show/hide terminal.

**Comment by TylerLeonhardt** [comment]
@fannheyward that doesn't seem to work with any existing terminal. The `coc-powershell` extension creates a terminal using coc's API's and your extension doesn't seem to show or hide that one.

**Comment by chemzqm** [comment]
@TylerLeonhardt coc-powershell can create a command to toggle terminal created by itself.
