### ISSUE TITLE
Autocompletion - might become case sensitive

### ISSUE THREAD

**Issue by mikeTWC1984** [neoclide/coc.nvim#1122]
I noticed that sometimes (sporadically) autocompletion becomes case sensitive and is not returning expected result. However it might work as expected in some cases. Example:

I need to locate class called SqlConnection. If I type "sql" first it works fine
![Screenshot from 2019-08-27 23-24-26](https://user-images.githubusercontent.com/31977106/63823572-5003ad00-c922-11e9-8ed0-28bb831d87e6.png)

If I type "Conn" it works as expected too 
![Screenshot from 2019-08-27 23-22-15](https://user-images.githubusercontent.com/31977106/63823639-88a38680-c922-11e9-8b9d-d47632fa21e5.png)

It stop working properly if I type "co", or "cO
![Screenshot from 2019-08-27 23-31-35](https://user-images.githubusercontent.com/31977106/63823743-e637d300-c922-11e9-98d4-0006aeede4d4.png)
"
![Screenshot from 2019-08-27 23-24-57](https://user-images.githubusercontent.com/31977106/63823751-ec2db400-c922-11e9-85a8-d44dea3980a5.png)

Tested same scenarios in VSCode and it works as expected in all cases.
Using latest coc and nvim 0.4.

**Comment by chemzqm** [comment]
It's expected, the suggest is removed from popup when score is too low.

**Comment by sergei-grechanik** [comment]
I experience a similar problem:
![Screenshot_2019-10-02_11-08-27](https://user-images.githubusercontent.com/1084979/66028446-cc7f4200-e505-11e9-9dec-6368c278c347.png)
Here both matches should be shown, however `var` seems to shadow `Var`. I would consider it a bug.

**Comment by chemzqm** [comment]
@sergei-grechanik the filter of coc.nvim is always case insensitive, you should check output from server first https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by sergei-grechanik** [comment]
@chemzqm Seems like coc-python currently doesn't respect the value of `python.trace.server`, so I'm not sure how to debug it. However I experience the same problem with file path completion as well, so I don't think it is related to jedi.
