### ISSUE TITLE
Support local source changes for rust-analyzer

### ISSUE THREAD

**Issue by JeanMertz** [neoclide/coc.nvim#1124]
I'm looking into making the [rust-analyzer]() LSP work as much as possible with Coc.

Everything _mostly_ works out of the box, except that the server [does not support](https://github.com/rust-analyzer/rust-analyzer/issues/1232) `workspace/executeCommand`, and so code actions don't work.

Instead, the response of a `textDocument/codeAction` request returns a set of actions, each having their `command` set to `rust-analyzer.applySourceChange`, and `arguments` containing the data needed to manipulate the code locally to apply the source change.

I've implemented [something similar before](https://github.com/autozimu/LanguageClient-neovim/pull/815) for LanguageClient-neovim.

Given that this doesn't fit into an "extension" (as far as I know), I suspect support for something like this will have to be hard-coded into coc.nvim itself?

Are you open to such a change, or do you have any pointers for me to make this work as expected?

**Comment by JeanMertz** [comment]
Actually, looking at the code, it seems like this can be handled by registering the `rust-analyzer.applySourceChange` command to the `CommandManager`.

The only question is if there's already shared code that supports easy local text manipulation based on span information and text.

I'll have to dig into this some more sometime this weekend, but if you have any other pointers, feel free to let me know.

**Comment by JeanMertz** [comment]
Okay, that was fairly easy to implement. I'll see about making this into a proper extension, but for starters, this will make sure local edits are applied as expected:

```js
const { commands, workspace } = require('coc.nvim')

exports.activate = context => {
  context.subscriptions.push(commands.registerCommand('rust-analyzer.applySourceChange', async({ _cursorPosition, _label, workspaceEdit }) => {
    await workspace.applyEdit(workspaceEdit)
  }, null, true))
}
```

For anyone finding this issue: add this to a `rust-analyzer.js` file in `$VIMCONFIG/coc-extensions`, and things should work as expected.

**Comment by fannheyward** [comment]
I'm porting rust-analyzer-vscode to a coc extension, https://www.npmjs.com/package/coc-rust-analyzer, give it a try.

`rust-analyzer.applySourceChange` is available now.

**Comment by JeanMertz** [comment]
@fannheyward great! Are you going to host the code somewhere so others can contribute?

**Comment by fannheyward** [comment]
@JeanMertz yes, I'll open it on GitHub later.

**Comment by fannheyward** [comment]
These commands are works!

1. rust-analyzer.analyzerStatus
2. rust-analyzer.applySourceChange
3. rust-analyzer.collectGarbage
4. rust-analyzer.joinLines
5. rust-analyzer.matchingBrace
6. rust-analyzer.parentModule
7. rust-analyzer.reload
8. rust-analyzer.run
9. rust-analyzer.runSingle

**Comment by Avi-D-coder** [comment]
@fannheyward after you have a repo, I'll add a note in [Avi-D-coder/coc-rust-analyzer](https://github.com/Avi-D-coder/coc-rust-analyzer) pointing to it, since I never got around to finishing it.

**Comment by JeanMertz** [comment]
@fannheyward great work so far. Two things I've noticed, but I'm not sure if it's a limitation of the plugin, coc itself, or my configuration:

1. Autocompletion works, but it doesn't expand the method signature with snippet-support enabled, even though this does work in VSCode.
2. Diagnostics (and code lens) only show up once a change is made in a document, not when the document is first loaded.

**Comment by fannheyward** [comment]
@Avi-D-coder @JeanMertz I make it open: https://github.com/fannheyward/coc-rust-analyzer

1. cargo-watch is WIP.
2. method signature is supported by default, also diagnostics/codelens, but in some unknown case, it won't work properly, I'm looking on this.

This issue can be closed, any issue/feature/feedback can be post in coc-rust-analyzer repo, thanks.
