### ISSUE TITLE
Preselect feature is inconsistent

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#1127]
## versions

vim version: NVIM v0.4.0-1860-g0ec80d5f6
node version: v12.9.1
coc.nvim version: 0.0.74-c97d41aa1e
term: tmux-256color
platform: linux

## Output channel: watchman

[Info  - 6:41:59 PM] watchman watching project: /home/francisco/Projects/samples/go
[Info  - 6:41:59 PM] subscribing "\*\*/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /home/francisco/Projects/samples/go
[Info  - 6:41:59 PM] subscribing "\*\*/.eslintignore" in /home/francisco/Projects/samples/go
[Info  - 6:41:59 PM] subscribing "\*\*/package.json" in /home/francisco/Projects/samples/go
[Info  - 6:41:59 PM] subscribing "\*\*/{.prettierrc,.prettierrc.json,.prettierrc.yaml,.prettierrc.yml,.prettierrc.js,package.json,prettier.config.js}" in /home/francisco/Projects/samples/go

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/francisco
> git ls-files -- Projects/samples/go/sample.go
resolved root: /home/francisco
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Output channel: snippets

[Info  - 6:41:59 PM] watchman watching project: /home/francisco/.config/coc/ultisnips
[Info  - 6:41:59 PM] subscribing "**/*.snippets" in /home/francisco/.config/coc/ultisnips

## Output channel: languageserver.go

[Info  - 6:41:59 PM] 2019/08/29 18:41:59 5.239837ms for GOROOT= GOPATH=/home/francisco/.go GO111MODULE= PWD=/home/francisco/Projects/samples/go go "env" "GOMOD", stderr: <<>>

[Info  - 6:41:59 PM] 2019/08/29 18:41:59 7.942945ms for GOROOT= GOPATH=/home/francisco/.go GO111MODULE= PWD=/home/francisco/Projects/samples/go go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "builtin", stderr: <<>>

[Info  - 6:41:59 PM] 2019/08/29 18:41:59 9.905214ms for GOROOT= GOPATH=/home/francisco/.go GO111MODULE= PWD=/home/francisco/Projects/samples/go go "list" "-m" "-json" "all", stderr: <<>>

[Info  - 6:41:59 PM] 2019/08/29 18:41:59 Build info
----------
version v0.1.3-cmd.gopls, built in $GOPATH mode

Go info
-------
go version go1.12.9 linux/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/francisco/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/francisco/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/francisco/Projects/samples/go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build806192521=/tmp/go-build -gno-record-gcc-switches"

[Info  - 6:41:59 PM] 2019/08/29 18:41:59 6.617293ms for GOROOT= GOPATH=/home/francisco/.go GO111MODULE= PWD=/home/francisco/Projects/samples/go go "env" "GOMOD", stderr: <<>>

[Info  - 6:41:59 PM] 2019/08/29 18:41:59 7.048852ms for GOROOT= GOPATH=/home/francisco/.go GO111MODULE= PWD=/home/francisco/Projects/samples/go go "list" "-m" "-json" "all", stderr: <<>>

[Info  - 6:41:59 PM] 2019/08/29 18:41:59 25.485992ms for GOROOT= GOPATH=/home/francisco/.go GO111MODULE= PWD=/home/francisco/Projects/samples/go go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "/home/francisco/Projects/samples/go", stderr: <<>>

[Info  - 6:41:59 PM] 2019/08/29 18:41:59 go/packages.Load
        packages = 1
[Info  - 6:41:59 PM] 2019/08/29 18:41:59 go/packages.Load
        package = github.com/oblitum/samples/go
        files = [/home/francisco/Projects/samples/go/sample.go]

## Describe the bug

Completion preselection is a nice feature, but it doesn't work consistently, depending on what I type, preselection vanishes for no apparent reason.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  augroup vimrc | autocmd! | augroup end
  
  if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd vimrc VimEnter * PlugInstall --sync | source $MYVIMRC
  endif
  
  call plug#begin('~/.vim/plugged')
  Plug 'tpope/vim-sensible'
  call plug#load('vim-sensible')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()
  
  let g:coc_user_config = {
  \   'languageserver': {
  \     'go': {
  \       'command': 'gopls',
  \       'filetypes': ['go'],
  \       'rootPatterns': ['go.mod']
  \     }
  \   }
  \ }
  ```

- Start neovim with command: `nvim -u mini.vim`

- Complete `fmt.P` like in the screenshots.

## Screenshots (optional)

After `.` it works
![imgur-16:17:42_27-08-2019](https://user-images.githubusercontent.com/1269815/63801332-6be95d80-c8e6-11e9-8e85-0173a7c16582.png)

If I type `E` which is part of  the preselection, it still works:
![imgur-16:18:12_27-08-2019](https://user-images.githubusercontent.com/1269815/63801340-6f7ce480-c8e6-11e9-9209-d9b4190001a9.png)

But typing a different char to get another completion, then preselection gets disabled:
![imgur-16:18:29_27-08-2019](https://user-images.githubusercontent.com/1269815/63801350-760b5c00-c8e6-11e9-8c6b-637b53e1bc1a.png)

**Comment by taigacute** [comment]
it works fine  for me .
![git](https://user-images.githubusercontent.com/41671631/64181975-0541e200-ce9a-11e9-9134-ea1377f08017.gif)

**Comment by oblitum** [comment]
@taigacute thanks, you're correct. This is actually a conflict with another plugin I was using, [farmergreg/vim-lastplace](https://github.com/farmergreg/vim-lastplace).

**Comment by oblitum** [comment]
I don't understand why that plugin would affect this though, it's a very small one: https://github.com/farmergreg/vim-lastplace/blob/master/plugin/vim-lastplace.vim.

**Comment by oblitum** [comment]
Well, false alarm, it's not a conflict, for some reason, the issue stopped after I repeated it many times, I don't know how to reproduce it consistently.

**Comment by oblitum** [comment]
Ah, looks like it was a gopls issue, it was happening consistently in another machine, after updating gopls, it was fixed.

**Comment by mskar** [comment]
Is there any way to get the preselect feature to work in vim?
It works great for me in neovim, but I would like the behavior to be the same in both.

**Comment by chemzqm** [comment]
No

**Comment by mskar** [comment]
Thanks for quick reply! Coc is awesome by the way! 😃

**Comment by mskar** [comment]
The first autocomplete option started being preselected in vim after I copied my `coc-settings.json` from `~/.config/nvim/` to `~/.vim/`😅
