### ISSUE TITLE
How to make statusline cowork with spacevim`s statusline

### ISSUE THREAD

**Issue by jidibinlin** [neoclide/coc.nvim#1128]
Hi coc.nvim is so elementory for writing source. But I see coc.nvim can work with statusline in the Doc. I run the command ``` set statusline +=%{coc#status} ``` and just get a blank statusline or just some strange string like E2E2E2. Do you have some solution for me? Thanks.

**Comment by taigacute** [comment]
the spacevim has it own statusline .so i think it not add support for coc.nvim , so if you want see the  coc status in statusline , you can try to disabled the statusline of spacevim .then custom statusline add `set statusline +=%{coc#status}`  or use [spaceline.vim](https://github.com/taigacute/spaceline.vim) lightline etc..

**Comment by jidibinlin** [comment]
OK! Thankyou
