### ISSUE TITLE
Ability to remove suggestions

### ISSUE THREAD

**Issue by Herz3h** [neoclide/coc.nvim#1129]
**Is your feature request related to a problem? Please describe.**
I'm using https://github.com/marlonfan/coc-phpls extension, it works very well. However there is times where autocompletion will suggest me some classes from a Cache (under a folder named __Proxies, these are classes generated by an ORM, doctrine in this case).

I would like to filter suggestions after intelephense sends back suggestions. Is there a way to do this ? I checked help, didn't find anything like this.

**Describe the solution you'd like**
No solution atm.

**Describe alternatives you've considered**
No alternative atm.

**Additional context**
This is happening in a symfony project with doctrine. But the  feature is generic .Basically ability to post-filter suggestions.

**Comment by chemzqm** [comment]
Improve your language or fork coc.nvim

**Comment by Herz3h** [comment]
Okay so it's not possible :(

**Comment by chemzqm** [comment]
You can use middleware feature of language client configuration, for example: https://github.com/neoclide/coc-json/blob/master/src/index.ts#L107
