### ISSUE TITLE
Don't format (or record history) if no change

### ISSUE THREAD

**Issue by JeanMertz** [neoclide/coc.nvim#1131]
Given I have format on save enabled. If I have a (in this case JSON) document, it's already formatted, and I save the document 3 times. Now I have to undo three times before I get to the undo history that actually changed something in the document.

It would be nice if these saves would either a) not trigger a format if nothing changed, or b) those formats would not be added to the undo history.

**Comment by chemzqm** [comment]
There is code to prevent unnecessary edits, checkout https://github.com/neoclide/coc.nvim/blob/master/src/model/document.ts#L298.

I can't reproduce your issue.
