### ISSUE TITLE
coc visual mapping for "i" interferes with typical bindings for COLEMAK users

### ISSUE THREAD

**Issue by ohjames** [neoclide/coc.nvim#1132]
When using coc, `if` in visual mode is mapped to `coc-funcobj-i`. This works great for qwerty users, where `i` will be bound to the entering of insert mode.

colemak and dvorak users usually rebind `i` to other things. For example, in colemak `i` is where `l` is in qwerty. Since we like the `hjkl` bindings, most of us remap `hjkl` to `snei`. The result is that hitting `i` in visual mode no longer works well when using coc. We essentially lose the ability to go right quickly in visual mode, vim pauses for about a second while it waits for the `f` key which creates a pretty bad experience.

I wonder if it would be possible to allow the binding for `i` to be set as an option to `coc`? Or for coc to somehow see what is already bound to `i` and bind that instead? Or to add something to the README to show how to work around it?

**Comment by ohjames** [comment]
For anyone interested, the solution I use is to add this to my neovim/vim config:

```vim
xunmap if
xmap uf <Plug>(coc-funcobj-i)
```

I'm still not actually sure what `if` (`uf`) does though ;)

**Comment by chemzqm** [comment]
> If coc sees that <Plug>(coc-funcobj-i) already has a mapping, it won't take if for that mapping.

It's feature, you can add `xmap if <Plug>(coc-funcobj-i)` to your vimrc if you want to.

**Comment by Aura7988** [comment]
> Default mappings for function text object are removed.

完全没有必要把这个默认映射去掉啊。楼主的问题是自己的i映射为l和默认的if映射有重合造成的，自己重新设置一下映射就可以了啊。
