### ISSUE TITLE
Feature request: rename a file => update all references

### ISSUE THREAD

**Issue by muratg** [neoclide/coc.nvim#1135]
I'd like to be able to rename a file and get all references updated, just like in VSCode. Is this possible?

**Comment by fannheyward** [comment]
Try `:CocCommand workspace.renameCurrentFile`, which will change current filename to a new name and reload it.

**Comment by muratg** [comment]
@fannheyward that's working fine (note that I can also change the filename in NERDTree with mm.)

The problem is that the references to the file (all the import statements) are not updated in _other_ files. VSCode has this support, though I'm not sure if it comes with LSP or not.

**Comment by fannheyward** [comment]
Maybe it's needed to send notification to notify language servers. I'll try to fix it.

**Comment by muratg** [comment]
Thanks so much! I'm hitting this with a TypeScript project, if that helps.

**Comment by fannheyward** [comment]
By now, you can `:CocRestart` after rename file.

**Comment by muratg** [comment]
This did not seem to help. It indeed restarted the connection, but the references did not get udpated. I'll wait for a fix, as this is not really super urgent for me. (I'm keeping VSCode around for debugging at least, and for file renames for now. :)) Thanks for the help!

**Comment by iamcco** [comment]
It works for me. If i change the file name, it will change all files which import that file.

**Comment by muratg** [comment]
@iamcco what language server are you playing with? tsserver?

**Comment by iamcco** [comment]
@muratg I use coc-tsserver

**Comment by chemzqm** [comment]
You need watchman installed, read readme of coc-tsserver

**Comment by muratg** [comment]
@chemzqm thanks, that worked! (Although installing Watchman for the first time was an adventure.) 

Thanks again, all!

**Comment by geoyws** [comment]
@chemzqm Hi! Thanks for the work you do! One complaint:`:CocCommand workspace.renameCurrentFile` is a little annoying to use because you have to type out the entire file path each time and mistakes may be made. Could we have it autofill with the current filepath so that it is easier to work with?

**Comment by chemzqm** [comment]
You don't have to type filepath for that command

**Comment by chemzqm** [comment]
@geoyws you might be using old version of coc.nvim, it does prompt for change of current file path.

**Comment by geoyws** [comment]
I have the latest coc.nvim (0.0.75) though, running on Vim 8.1. 
![no-autocomplete-vim-coc-rename-file](https://user-images.githubusercontent.com/1738396/76077716-38496780-5fdc-11ea-88fc-75fd3fd539d0.gif)
As you can see there's nothing prefilled when it prompts for the new path :(

**Comment by TxHawks** [comment]
Sorry to wake up an old issue that was already closed, but the problem persists for me, though only partially.

Say I have a `b.ts` file, that imports something from `./a.ts`.

If I rename `a.ts` to `c.ts` using `workspace.renameCurrentFile` when `b.ts` is open, everything works fine (though `b.ts` isn't saved). However, if `b.ts` isn't open, the `import a from './a'` line in it will not be refactored.

This is using coc-tsserver and with watchman installed globally.

**Comment by TxHawks** [comment]
Nope, that's still the behavior I get
