### ISSUE TITLE
How do I change the color of the selected option in the menu?

### ISSUE THREAD

**Issue by cubetastic33** [neoclide/coc.nvim#1137]
I'm able to change the background of the entire menu using `hi Pmenu ctermbg=foo`, but I can't figure out how to change the color of the selected option. I tried lots of the highlight groups in the documentation, but I can't seem to be able to get this right. How do I get what's in the gif in the README, for example?

**Comment by taigacute** [comment]
@cubetastic33  try to use `PMenuSel` ?

**Comment by cubetastic33** [comment]
@taigacute thanks a lot, that worked! :grinning:
