### ISSUE TITLE
Fixers for all files (like trim-whitespace)

### ISSUE THREAD

**Issue by MarkGreeny** [neoclide/coc.nvim#1139]
**Describe the solution you'd like**
Does there exist a way for COC to specify fixers for all files, like ALE ?
```
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace']
```
Sorry, if this already exists, and I am unable to find it. If so, please inform me.

**Comment by voldikss** [comment]
It not a native feature of coc, see #731 . You may check your lsp or write a simple VimScript to achieve this.

**Comment by voldikss** [comment]
e.g.

```vim
function! Format() abort
      let curr_pos = getpos('.')
      silent! execute '%s/\s\+$//g'
      call CocAction('format')
      update
      call setpos('.', curr_pos)
endfunction
" 
noremap  <silent> <F6>   :call Format()<CR>
```

**Comment by chemzqm** [comment]
No, it's much easier and flexible by use simple vim function

**Comment by Congee** [comment]
> 
> 
> No, it's much easier and flexible by use simple vim function

can you please give a hint about how to do it?

**Comment by voldikss** [comment]
> > No, it's much easier and flexible by use simple vim function
> 
> can you please give a hint about how to do it?

Hi, this might help you.

```vim
function! RemoveWhiteSpaces()
  if mode() ==# 'n'
    silent! keeppatterns keepjumps execute 'undojoin | %s/[ \t]\+$//g' | update
  endif
endfunc
command! RemoveWhiteSpaces call RemoveWhiteSpaces()

function! BufDo(command)
  let curbuf=bufnr("%")
  execute 'bufdo ' . a:command
  execute 'buffer ' . curbuf
endfunc
command! -nargs=+ -complete=command Bufdo call BufDo(<q-args>)
```

Then if you want to trim whitespaces for all buffers, execute `:Bufdo RemoveWhiteSpaces`.

The same goes for removing blank lines...

**Comment by Congee** [comment]
awwwwwwww, thank you! @voldikss I thought this thread was about trimming the output from the LSP `doHover` output rather than removing trailing whitespaces for the whole buffer. But, thanks anyway

**Comment by chemzqm** [comment]
Checkout `:h CocOpenFloat` if you want to customize float window after opened.

**Comment by Congee** [comment]
Thant's helpful! This might be relevant https://github.com/neovim/neovim/pull/12444
