### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by makmm** [neoclide/coc.nvim#114]

**Comment by makmm** [comment]
this might be useful: https://github.com/rust-lang-nursery/rls

**Comment by chemzqm** [comment]
You can add language server by configure `coc-settings.json`: https://github.com/neoclide/coc.nvim/wiki/Language-servers#rust

**Comment by makmm** [comment]
Oh. sorry.

**Comment by LinArcX** [comment]
Please update the wiki. that link does not exists anymore.

**Comment by chemzqm** [comment]
There is https://github.com/neoclide/coc-rls, you don't need to configure it.
