### ISSUE TITLE
Help using .svelte extensions

### ISSUE THREAD

**Issue by vlad-terin** [neoclide/coc.nvim#1140]
If anybody can help - would appreciate it. New to web dev in general, so there might be an easy way to fix it - just couldn't find it. 

Trying to set up coc.nvim to be used with .svelte extension files (go to definitions, etc) 

So far i was able to have 2 services running inside .svelte files: tsserver and svelteserver (as custom server), but there are no auto-completions of javascript methods and diagnostic highlighting seems off. 

# Example: 

In .js extension files Math object has autocompletions like Math.sin. In .svelte files, even though tsserver and svelteserver are running, there are no auto-completions for this.

**Comment by chemzqm** [comment]
You need checkout verbose output, please read wiki

**Comment by vlad-terin** [comment]
The solution that did fix it for me was enabling completions and definitions of the svelte-language-server in TypescriptPlugin.js

```
var TypeScriptPlugin = /** @class */ (function () {
    function TypeScriptPlugin() {
        this.pluginId = 'typescript';
        this.defaultConfig = {
            completions: { enable: true },
            definitions: { enable: true },
            documentSymbols: { enable: true },
            enable: true,
            diagnostics: { enable: true },
            hover: { enable: true },
        };
    }
```
Thanks!
