### ISSUE TITLE
« Embedded » nvim instances don't seem to be tracked

### ISSUE THREAD

**Issue by svvac** [neoclide/coc.nvim#1144]
Coc seems to leave behind hundreds of `nvim --embedded` processes that need to be killed by means of `kill -9`. This gets bloaty for long running sessions, I think due to a number of `:CocRestart` calls.

A [quick search for the `--embed` flag](https://github.com/neoclide/coc.nvim/search?q=embed&unscoped_q=embed) leads me to [the `highlight` util](https://github.com/neoclide/coc.nvim/blob/cdbcb2064e87910c7ac3e3f39437770e4c7a7f39/src/util/highlight.ts#L78) which unlike [in some test](https://github.com/neoclide/coc.nvim/blob/f3072ec53565b6725504a37f19617ce7d2c8f0ed/src/__tests__/helper.ts#L38), the process doesn't seem to get tracked and end up [`SIGKILL-d`](https://github.com/neoclide/coc.nvim/blob/f3072ec53565b6725504a37f19617ce7d2c8f0ed/src/__tests__/helper.ts#L66). These are the only two occurences for my quick search, but maybe the same thing creeps somewhere else.

```
## versions

vim version: NVIM v0.4.0-1818-gf3cb52977
node version: v10.16.3
coc.nvim version: 0.0.74
term: xterm-256color
platform: linux

## Messages/home/<clip>

## Output channel: prettier


## Output channel: tsserver
[Info  - 9:30:50 PM] Forking TSServer
PATH: <clip>
[Info  - 9:30:50 PM] Started TSServer
{
  "path": "<clip>",
  "_api": {
    "versionString": "3.2.4",
    "version": "3.2.4"
  }
}


## Output channel: angularls
Search path: <clip>
```

**Comment by chemzqm** [comment]
It's used for provide highlights, which should be killed.

**Comment by matthewmazzanti** [comment]
I can confirm that this is happening for Neovim HEAD under MacOS and Linux.

I haven't done much digging into debugging, but https://github.com/neovim/neovim/issues/1808 seems relevant here- seems that the embed flag can occasionally create orphaned processes, and that the issue was never really resolved.
