### ISSUE TITLE
Support vscode pyright extention

### ISSUE THREAD

**Issue by FongHou** [neoclide/coc.nvim#1146]
**Is your feature request related to a problem? Please describe.**
Microsoft put out a type check pyright.  It'll be a great addition to coc.nvim. 

**Describe the solution you'd like**
pyright is implemented in pure typescript (5x faster than mypy), with tight integration in vscode.  It seems fit coc.nvim's design very well.

**Describe alternatives you've considered**
pyright doesn't provide a standalone lsp server. https://github.com/microsoft/pyright/issues/99 has some details.

**Additional context**
https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright

**Comment by fannheyward** [comment]
Try https://github.com/fannheyward/coc-pyright

**Comment by FongHou** [comment]
@fannheyward, thanks for working it so quickly!

I just test it briefly. It works great, however, it seems not picking up pyrightconfig.json.

**Comment by chemzqm** [comment]
You can create issue at https://github.com/fannheyward/coc-pyright/issues
