### ISSUE TITLE
Parameter Decoration

### ISSUE THREAD

**Issue by phatsk** [neoclide/coc.nvim#1148]
**Is your feature request related to a problem? Please describe.**
I've been looking at a coworker's editor and noticed they have some useful parameter hint decorations. Is this possible with CoC?

**Describe the solution you'd like**
Something like this: 
![image](https://user-images.githubusercontent.com/990374/64377504-a21a9180-cff8-11e9-8bd6-ea7b5d67df4e.png)
Note the "delimiter" hint before the first parameter.

**Describe alternatives you've considered**
I'm not aware of this feature in any PHP vim completion or LSP implementations.

**Additional context**
None to add. Thanks for this project, it's amazing!

**Comment by Avi-D-coder** [comment]
Nvim does not yet support virtual text inside real text. The closest we can get is signature help, but many language servers don't support it.

**Comment by chemzqm** [comment]
What does `delimiter` means? Is it some kind of virtual text that indicate the kind of parameter?

**Comment by balta2ar** [comment]
@chemzqm It's simply a parameter name of the function being called.
They rejected the same issue in vscode-python: https://github.com/microsoft/vscode-python/issues/53
But it's still open in the vscode repo: https://github.com/microsoft/vscode/issues/16221#issuecomment-264527520

**Comment by chemzqm** [comment]
Use signature help instead, can't make it work on vim
