### ISSUE TITLE
when I install coc-tabnine nvim very slow

### ISSUE THREAD

**Issue by wuchujiecode** [neoclide/coc.nvim#1151]
I am not sure where is the problem?
Maybe tabnine? or coc-tabnine ? or gopls

Have any way to debug or Have any way to delete coc-tabnine?
I had try to open coc-engine close coc-tabnine. next time I open vim  still have process tabnine.

![image](https://user-images.githubusercontent.com/12055501/64419647-ec227680-d0cf-11e9-8e52-c33a9b660b56.png)

**Comment by voldikss** [comment]
> Have any way to delete coc-tabnine

`:CocUninstall coc-tabnine` 卸载
或者用 `:CocList extensions` 禁用 coc-tabnine

**Comment by wuchujiecode** [comment]
@voldikss  thans . 是 tabnine 的原因吗。。golang 代码补全吃1.45g 内存  有点夸张。

**Comment by voldikss** [comment]
这个不清楚欸，建议搜下 issue 看有没有人遇到过这种情况。

**Comment by fannheyward** [comment]
gopls 是比较吃内存。

**Comment by wuchujiecode** [comment]
@voldikss @fannheyward  我看gopls 是google官方推荐的。。我现在8g内存 用nvim  (本身想用vim + coc-vim 的 但是卡的看雪花一样)。。我现在开一个项目没开其他什么东西 终端开nvim 居然很卡, 代码补全的时候。 请问有coc-vim 有没有什么debug 方式能看到耗时操作在哪里吗

**Comment by taigacute** [comment]
emm 。。你这个很奇怪，我写了这么久go都没遇到过...建议你最小化配置试试看。coc的debug可以看wiki 有写

**Comment by wuchujiecode** [comment]
@taigacute 找到问题了。。我gopls 是使用vscode安装的。。路径上有问题。删除了重新安装就好了
