### ISSUE TITLE
[feature] "Always" and "Never" responses to prompts

### ISSUE THREAD

**Issue by reaysawa** [neoclide/coc.nvim#1156]
**Is your feature request related to a problem? Please describe.**

When I open a Rust file, `coc.nvim` always prompts

```
RLS not installed. Install?
[Y]es, (N)o: 
```

It should have two more options
- **Always** -> always respond Yes to this question, with no prompts in the future
- **Never** -> always respond No to this question, with no prompts in the future

This also should work for extensions' prompts.

**Comment by chemzqm** [comment]
No, prompt only have yes and no.
