### ISSUE TITLE
Is there an option to clean up or suppress the generation of tmp log files - /tmp/coc*log?

### ISSUE THREAD

**Issue by damnskippy** [neoclide/coc.nvim#1159]
Using vim on linux with ccls language server, every time vim is started, a log (/tmp/coc-nvim-pid.log) gets generated.  This is useful when needed, however over time /tmp is getting littered with too many of these logs, and seems not necessary especially if one is not looking at them.

Is there a config option to suppress these logs from getting generated, or clean them up perhaps when vim exits?  Thank you very much.

**Comment by chemzqm** [comment]
You can use `NVIM_COC_LOG_FILE` to make coc.nvim create a single file.
