### ISSUE TITLE
Support scroll popup on vim8

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#1160]
Need use filter to support scroll of popup.

**Comment by andys8** [comment]
@chemzqm I'm using Vim 8.1 and have a floating window. I'm wondering why I can't get scrolling or `<Plug>(coc-float-hide)` to work as expected. Currently the floating window for diagnostics hides the code and I haven't figured out how to hide it temporarily. Is there implementation missing or should I create a new issue for this case?

**Comment by chemzqm** [comment]
It's popup, not floating window

**Comment by chemzqm** [comment]
Check vim's help for functions you can use

**Comment by andys8** [comment]
Ah, thanks for clarification. I didn't know there is a difference between floating and popup. So regarding "floating windows": Are you referring to anything else than `<Plug>(coc-float-hide)` (https://github.com/neoclide/coc.nvim/blob/98ebf00d590e0772bfbfc20a67003ec7935be420/plugin/coc.vim#L364) which is not working to hide a floating diagnostics for me in Vim 8.1.

**Comment by dedowsdi** [comment]
Wrote a temporary solution [here](https://vi.stackexchange.com/questions/21924/how-can-i-hide-and-scroll-popup-window-in-coc-nvim-in-vim/21927#21927) , it scrolls first `popup` (might not belong to `coc`) found around cursor.

**Comment by pvonmoradi** [comment]
Isn't this a Vim limitation?

**Comment by chemzqm** [comment]
Fixed by 624549da
