### ISSUE TITLE
Server golang failed to start with gopls

### ISSUE THREAD

**Issue by phongloihong** [neoclide/coc.nvim#1161]
Hi
I'm tried to use gopls with coc but when open go file I get an error message 
`[coc.nvim] Server golang failed to start: Command "gopls" of languageserver.golang is not   executable: Error: not found: gopls at `

And this is output channel of languageserver.golang when i run :CocInfo:
`## Output channel: languageserver.golang
[Error - 12:45:43] Starting client failed:
Error: Command "gopls" of languageserver.golang is not executable: Error: not found: gopls at LanguageClient.createMessageTransports
`

this is my neovim configuratioin
`let g:go_highlight_build_constraints = 1`
`let g:go_highlight_extra_types = 1`
`let g:go_highlight_fields = 1`
`let g:go_highlight_functions = 1`
`let g:go_highlight_methods = 1`
`let g:go_highlight_operators = 1`
`let g:go_highlight_structs = 1`
`let g:go_highlight_types = 1`
`let g:go_auto_sameids = 1`
`let g:go_fmt_command = "goimports"`
`let g:go_def_mode='gopls'`
`let g:go_info_mode='gopls'`

go version go1.13 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

`GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/loihongphong/Library/Caches/go-build"
GOENV="/Users/loihongphong/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/loihongphong/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xr/540_l89d7snfbw412hj6jm480000gn/T/go-build553916854=/tmp/go-build -gno-record-gcc-switches -fno-common"`
</pre></details>

Please give me some advice for this case I'm stuck in 2 days :(

Thanks for help

**Comment by fannheyward** [comment]
`Command "gopls" of languageserver.golang is not executable`, does your `gopls` works in command line?

**Comment by phongloihong** [comment]
Hi @fannheyward thanks for your help
Yes i have gopls in my GOPATH
![Screen Shot 2019-09-10 at 1 08 04 PM](https://user-images.githubusercontent.com/20653807/64588325-51c27b80-d3cc-11e9-995b-d2953f990e8c.png)
You mean run gopls command in neovim or terminal ?

**Comment by fannheyward** [comment]
Yes, can you run `gopls` in your terminal? And, what's your config of gopls in `coc-settings.json`?

**Comment by phongloihong** [comment]
No, I check my GOBIN and I just see 
![Screen Shot 2019-09-10 at 1 22 12 PM](https://user-images.githubusercontent.com/20653807/64588934-0ad58580-d3ce-11e9-99c7-90616a61f0a0.png)

**Comment by phongloihong** [comment]
My :CocConfig
![Screen Shot 2019-09-10 at 1 23 30 PM](https://user-images.githubusercontent.com/20653807/64588996-3ce6e780-d3ce-11e9-8390-67c1b7b59346.png)

**Comment by fannheyward** [comment]
Your `gopls` is not installed correctly. Check wiki:

https://github.com/golang/go/wiki/gopls
https://github.com/neoclide/coc.nvim/wiki/Language-servers#go

**Comment by phongloihong** [comment]
Hi after reinstall i can run gopls in terminal but error still happen in neovim

**Comment by chemzqm** [comment]
Run `:echo executable('gopls')` in your neovim.

**Comment by phongloihong** [comment]
Hi @chemzqm thanks for your advice
after run this command i get new error: source languageserver.golang timeout after 2000ms

**Comment by fannheyward** [comment]
This error means your gopls is works, but suggestion didn't result in 2000ms, this is gopls's problem. Set `"suggest.timeout": 5000` and try again.

**Comment by phongloihong** [comment]
After setting the timeout to 5000ms  keep show error timeout. I'm tried for couple hour but I can't fix this.

**Comment by phongloihong** [comment]
![Screen Shot 2019-09-10 at 10 36 59 PM](https://user-images.githubusercontent.com/20653807/64628407-8ad60c80-d41b-11e9-9ff6-0356af929257.png)
This is what happens with commend:CocInfo

**Comment by chemzqm** [comment]
Should be problem of gopls.

**Comment by phongloihong** [comment]
Hi 
After change GO111Module="auto" everything works well.
Thanks so much for your help.

**Comment by Kavinjsir** [comment]
Hi folks, Not sure I'm facing with similar issues as my `gopls` does not take effect. Here is the error logs:

```
## versions

vim version: NVIM v0.9.1
node version: v18.17.0
coc.nvim version: 0.0.82-3dc6153a 2023-07-21 00:22:17 -0500
coc.nvim directory: /Users/jintony/pro/nvim/autoload/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2023-07-31T12:42:35.773 INFO (pid:44211) [plugin] - coc.nvim initialized with node: v18.17.0 after 166
2023-07-31T12:42:35.775 INFO (pid:44211) [services] - LanguageClient go state change: stopped => starting
2023-07-31T12:42:35.779 INFO (pid:44211) [language-client-index] - Language server "languageserver.go" started with 44233
2023-07-31T12:42:35.793 INFO (pid:44211) [services] - LanguageClient go state change: starting => stopped
2023-07-31T12:42:35.793 INFO (pid:44211) [services] - LanguageClient go state change: stopped => starting
2023-07-31T12:42:35.794 ERROR (pid:44211) [language-client-client] - Server languageserver.go initialization failed. Lh [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/jintony/pro/nvim/autoload/plugged/coc.nvim/build/index.js:48:4564)
    at Object.dispose (/Users/jintony/pro/nvim/autoload/plugged/coc.nvim/build/index.js:238:6208)
    at jd.handleConnectionClosed (/Users/jintony/pro/nvim/autoload/plugged/coc.nvim/build/index.js:241:15575)
    at jd.handleConnectionClosed (/Users/jintony/pro/nvim/autoload/plugged/coc.nvim/build/index.js:245:3561)
    at t (/Users/jintony/pro/nvim/autoload/plugged/coc.nvim/build/index.js:241:15224)
    at aT.invoke (/Users/jintony/pro/nvim/autoload/plugged/coc.nvim/build/index.js:21:14456)
    at rc.fire (/Users/jintony/pro/nvim/autoload/plugged/coc.nvim/build/index.js:21:15225)
    at Qe (/Users/jintony/pro/nvim/autoload/plugged/coc.nvim/build/index.js:22:6504)
    at aT.invoke (/Users/jintony/pro/nvim/autoload/plugged/coc.nvim/build/index.js:21:14456)
    at rc.fire (/Users/jintony/pro/nvim/autoload/plugged/coc.nvim/build/index.js:21:15225) {
  code: -32097,
  data: undefined
}
```

And this is my os env:
```shell
❯ go version
go version go1.20.6 darwin/arm64
❯ sw_vers
ProductName:            macOS
ProductVersion:         14.0
BuildVersion:           23A5301g
❯ sysctl -n machdep.cpu.brand_string
Apple M2
```

**Comment by PengChaoJay** [comment]
I meet the same question

**Comment by fannheyward** [comment]
@Kavinjsir your `gopls` failed to start.

@PengChaoJay `:CocOpenLog` please.

**Comment by PengChaoJay** [comment]
I've solved it, 
uninstalled coc.nvim and  go install golang.org/x/tools/gopls@latest，this is ok

**Comment by PengChaoJay** [comment]
and install coc.nvim

**Comment by PengChaoJay** [comment]
and install coc.nvim again
