### ISSUE TITLE
ColorColumn in Popup

### ISSUE THREAD

**Issue by SicariusNoctis** [neoclide/coc.nvim#1164]
## Result from CocInfo

```
vim version: NVIM v0.4.0-1545-g2860453c4
node version: v12.10.0
coc.nvim version: 0.0.74-bc017b02e6
term: tmux-256color
platform: linux
```

## Describe the bug

Popup window background is a mixture of `PMenu` and `ColorColumn` past `&colorcolumn=80` characters, provided that the documentation text is wider than 80 characters.

## Reproduce the bug

```vim
hi ColorColumn guibg=#ff5555
set colorcolumn=80
let &colorcolumn=join(range(81,999), ",")
```

## Screenshots

![](https://i.imgur.com/ZUKGm0s.png)

**Comment by chemzqm** [comment]
It's not popup but floating window of neovim, it's highlighted by your neovim since coc.nvim doesn't  specify colorcolumn at all.

You can use `CocOpenFloat` autocmd to disable colorcolumn in floating window.

**Comment by SicariusNoctis** [comment]
Hmm... supposedly, [`highlight` is globally applied](https://stackoverflow.com/questions/15283410/how-do-i-change-the-background-color-of-current-buffer-or-pane-in-vim/15288799#15288799), so this ends up affecting the entire vim instance:

```vim
autocmd User CocOpenFloat
    \   if exists('w:float')
    \ |     hi ColorColumn guibg=None
    \ | endif
```

**Comment by chemzqm** [comment]
I've made floating window to avoid it.

**Comment by SicariusNoctis** [comment]
Thanks, I didn't think of `setl colorcolumn=`!
