### ISSUE TITLE
[coc.nvim] Rename provider not found for current document

### ISSUE THREAD

**Issue by yantao473** [neoclide/coc.nvim#1165]
I can not use coc-rename in any file type

CocInfo: 
  ## versions    
                                                                                              
  vim version: NVIM v0.3.8    
  node version: v10.16.3      
  coc.nvim version: 0.0.74-bc017b02e6    
  term: xterm-256color    
  platform: linux

**Comment by fannheyward** [comment]
1. What's your file type and language server?
2. `CocInfo` please

**Comment by yantao473** [comment]
file type: php
language server:  coc-phpls 2.0.7

CocInfo:
## versions

vim version: NVIM v0.3.8
node version: v10.16.3
coc.nvim version: 0.0.74-bc017b02e6
term: xterm-256color
platform: linux

## Messages

## Output channel: snippets


## Output channel: highlight

[Info  - 4:55:40 PM] Highlight server running in node v10.16.3

## Output channel: phpls

[Info  - 4:55:41 PM] Initialising intelephense 1.2.3
[Info  - 4:55:41 PM] Reading state from /home/yanqing4/.config/coc/extensions/coc-phpls-data/3146b9d0.
[Info  - 4:55:41 PM] Initialised in 196 ms
[Info  - 4:55:41 PM] Intelephense 1.0.14

**Comment by fannheyward** [comment]
phpls doesn't provide rename: https://github.com/bmewburn/intelephense-docs#capabilities

**Comment by yantao473** [comment]
OK
thank you very much

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc.nvim/wiki/Multiple-cursors-support#rename-current-variable for rename variable in current document.

**Comment by sandrodz** [comment]
> phpls doesn't provide rename: https://github.com/bmewburn/intelephense-docs#capabilities

It does now, as a premium featrure. Has anyone used it with coc? does it work?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
