### ISSUE TITLE
Markdown highlighting for "doHover" preview window

### ISSUE THREAD

**Issue by MarkGreeny** [neoclide/coc.nvim#1166]
**Is your feature request related to a problem? Please describe.**
Most times, documentation is written in markdown format. When one uses `CocAction("doHover")`, the window that opens does not use markdown highlighting.

**Describe the solution you'd like**
Provide a way to set markdown highlighting for the documentation preview. Note that we do not need or want markdown highlighting for all preview windows. Just the ones used for documentation displaying.

If this is already available, and I am missing it, please correct me. Thank you.

**Comment by Avi-D-coder** [comment]
Are you using neovim or vim?

**Comment by MarkGreeny** [comment]
Please forgive me, the mistake was my own. Works perfectly after i ceased my foolishness. Amazing product, coc.
