### ISSUE TITLE
Set highlight group for search matches in Fuzzy search

### ISSUE THREAD

**Issue by MarkGreeny** [neoclide/coc.nvim#1172]
Is there a possibility of setting the highligh group for matching characters?

Please note that i did try to add
```json
"list.previewHighlightGroup": "Statement"
```
to the config but it appears not to do what i want.

![image](https://user-images.githubusercontent.com/40479001/64880664-0375dc80-d659-11e9-82b3-604e23cd5ef8.png)

But interestingly, when using the **lines** from `coc-lists`
![image](https://user-images.githubusercontent.com/40479001/64880790-564f9400-d659-11e9-9e71-0d9114027b79.png)

it does use the highlight group **Statement**.

Why is there a difference, and why does only **lines** obey this highlight group, but not other lists?

**Comment by chemzqm** [comment]
`previewHighlightGroup` means highlight group in preview window of list, it uses Statement highlight for interactive highlight
