### ISSUE TITLE
diagnostic.virtualText and suggest.noselect not working

### ISSUE THREAD

**Issue by abenz1267** [neoclide/coc.nvim#1174]
## Result from CocInfo

vim version: NVIM v0.3.8
node version: v12.9.1
coc.nvim version: 0.0.74-bc017b02e6
term: xterm-256color
platform: linux

## Describe the bug
`diagnostic.virtualText: true` and `suggest.noselect: false` aren't working since a few days. 

## Reproduce the bug

Created minimal init.vim for neovim to reproduce the issue. Template used was the one given here.

## Screenshots (optional)
https://drive.google.com/open?id=1B2z4wLwQXzLdzXaXEJaJS88lztFiZtKw

As you can see both of the settings aren't working. They definitely worked before. I've tested this on both my laptop and desktop. Same issue.

Regards

**Comment by chemzqm** [comment]
Can't reproduce.

**Comment by abenz1267** [comment]
Do you have any direction you'd lead me to help debugging? I mean, i can clearly reproduce the issue on 2 different machines. Both running Manjaro KDE. I reproduced the issue with the minimal vim.rc given here and even tested both XTerm and Konsole. I tried looking into :CocOpenLog but there wasn't anything interesting there.

**Comment by abenz1267** [comment]
I have actually tried it at my office machine as well, as i've completely re-installed it. Same issue. Also Manjaro KDE. Manjaro i3 doesn't seem to have this issue, according to another coc user. I will try with a live usb and see if it's related to Manjaro KDE.

I love coc and your work btw. I wish i had the money to donate more. Maybe once I'm done studying.

**Comment by chemzqm** [comment]
Maybe your neovim not support virtualText, checkout `echo exists('*nvim_buf_set_virtual_text()')`

**Comment by abenz1267** [comment]
gives me 1

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by abenz1267** [comment]
I already did that, as i wrote before. I copied the config given here when opening a bug.

I actually just tried:
- download latest Manjaro KDE iso
- boot into live usb
- install neovim
- minimal vimrc
- latest node
- install coc

Same issue. suggest.noselect and diagnostic.virtualtext both dont work. So this definitely isn't my vim config or my system settings. All i can guess is that it's relatded to KDE Plasma somehow? I honestly don't know anymore.

**Comment by abenz1267** [comment]
I also just tried Manjaro i3. Same issue.

**Comment by chemzqm** [comment]
No idea, but you can configure coc.nvim by use `coc#config` function

**Comment by abenz1267** [comment]
Hm, i tried with let g:coc_user_config, which works.

I will try to find out why coc is ignoring the coc-settings.json...

**Comment by abenz1267** [comment]
Ok, so i've reinstalled coc.nvim and tried to debug. At one point i realized that it's reading the config file suddenly. I wasn't sure why. So deleted coc.nvim once again. Installed it via Vundle, went into the coc.nvim folder and did ./install.sh. Same result. Doesn't work. I needed to run yarn install as well. Now it's working again.

**Comment by noboruma** [comment]
@abenz1267 Thank you so much, I was hitting the same issue.
Is there a way to make sure `yarn install --forzen-lockfile` is ran when using `install.sh`?

**Comment by chemzqm** [comment]
`install.sh` is deprecated, use release branch is recommended, but vundle doesn't support that.

**Comment by LockwoodChris** [comment]
I'm having this issue as well on Manjaro (i3), this is definitely a recent Manjaro issue. I had a previous install of Manjaro working perfectly with coc and a few plugins.

I cannot get coc working with a new reinstall I have (same laptop), I can't get any plugins working (I have tested coc-java, coc-python and coc-json). I installed via Plug, I have tried both the following options and neither get a working installation:
`Plug 'neoclide/coc.nvim', {'branch': 'release'}`
`Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}`

So not only is the coc-settings.json being ignored (as in this issue) but I can't get any extensions working, they cannot see any settings and don't remember any initial setup options you provide to them. I haven't tried a full build from source.

**Comment by abenz1267** [comment]
Hm, i just removed coc, reinstalled again. ran yarn install --forzen-lockfile ... no issues.

**Comment by LockwoodChris** [comment]
Did you install via Vim Plug? I'm still having issues with any coc extensions and can not find anything in any related logs as to why they don't work.

**Comment by abenz1267** [comment]
I'm using vundle so i had to install via yarn. No problems on any of my 3 manjaro machines. 2x stable and 1x testing.

**Comment by xayjin** [comment]
I  had this issue, but solved it by `let g:coc_start_at_startup = 1` .  maybe coc-settings.json only works before lsp, so need to let g:coc_start_at_startup = 1.  Anyway I am not so sure about it.

**Comment by Green0wl** [comment]
```lua
return {
  'neoclide/coc.nvim',
  branch = 'release',
  init = function ()
    vim.g.coc_start_at_startup = 1
    vim.g.coc_config_home = 'lua/configurations/plugins/coc/'
    vim.g.coc_global_extensions = require("configurations.plugins.coc.coc_ensure_installed")
  end,
  config = function()
    require("core.mapping").coc_keymap_setup()
  end,
  build = "yarn install --frozen-lockfile",
}
```
with lazy.nvim works fine for me, even though I have had the same problems as you.

**Comment by chemzqm** [comment]
```
vim.g.coc_config_home = 'lua/configurations/plugins/coc/'
```
should be a full path to the folder.

**Comment by Green0wl** [comment]
> ```
> vim.g.coc_config_home = 'lua/configurations/plugins/coc/'
> ```
> should be a full path to the folder.

thanks! already solved.
