### ISSUE TITLE
Cannot open documentation hover in Rust, works in JS

### ISSUE THREAD

**Issue by errantspark** [neoclide/coc.nvim#1175]
# Result from CocInfo

## versions
```
vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 29 2019 20:38:53)
node version: v12.1.0
coc.nvim version: 0.0.74-e8e583c8e0
term: dumb
platform: linux
```
## Messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"test4.rs" 17L, 350C
[coc.nvim] running: rustup run stable-x86_64-unknown-linux-gnu rls, at /xxx/xxx/xxx
[coc.nvim] Setting sysroot to/xxx/xxx/.rustup/toolchains/stable-x86_64-unknown-linux-gnu


"~/.config/coc/ultisnips/rust.snippets" 25L, 625C
[Info  - 11:22:45 PM] Highlight server running in node v12.1.0
```

# Describe the bug

Hitting Shift+K produces a documentation window when working with JS, but not with Rust, normal documentation window shows up as expected when completion is going while typing.

# Reproduce the bug

`$MYVIMRC`

  ```vim
 set backupdir=~/.vimbackup
set directory=~/.vimswap
set noerrorbells
set visualbell
set t_vb=
set nocompatible
set hidden
filetype off

call plug#begin('~/.vim/plugged')
"magic vim plugin management
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()            " required
" Use sd to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
  ```

and then attempt to do the following

# Screenshots
here's what hitting Shift+K does in JS
![Screenshot from 2019-09-14 23-30-03](https://user-images.githubusercontent.com/623916/64917745-8164e100-d748-11e9-80ab-107b537fcac0.png)
here's what completion looks like in Rust
![Screenshot from 2019-09-14 23-31-18](https://user-images.githubusercontent.com/623916/64917744-79a53c80-d748-11e9-992e-7aa5e7712326.png)
if i try to hit Shift+K in rust after having witten `println!` nothing happens at all, there's no output to `:messages`

**Comment by chemzqm** [comment]
You have checkout verbose output from your rls

**Comment by errantspark** [comment]
I'm sorry, I don't understand. The information is clearly available to vim/coc, it just doesn't show up when i `call CocAction('doHover')`, it does show up when i'm typing

**Comment by chemzqm** [comment]
Can't reproduce, it should be problem of your rls

**Comment by errantspark** [comment]
the issue is the same using `coc-rls` and `coc-rust-analyzer`

**Comment by errantspark** [comment]
i found out about `:CocOpenLog`

```
2019-09-15T15:30:54.506 INFO (pid:12245) [services] - registed service "highlight"
2019-09-15T15:30:54.548 INFO (pid:12245) [services] - registed service "rust-client"
2019-09-15T15:30:54.705 INFO (pid:12245) [plugin] - coc 0.0.74-e8e583c8e0 initialized with node: v12.1.0
2019-09-15T15:30:54.712 INFO (pid:12245) [language-client-index] - highlight started with 12262
2019-09-15T15:30:54.727 INFO (pid:12245) [language-client-index] - rust-analyzer started with 12268
2019-09-15T15:30:55.096 INFO (pid:12245) [services] - highlight server state change: starting => running
2019-09-15T15:30:55.296 INFO (pid:12245) [services] - Rust Language Server state change: starting => running
2019-09-15T15:30:57.197 INFO (pid:12245) [completion-complete] - Results from: snippets
2019-09-15T15:30:58.386 INFO (pid:12245) [completion-complete] - Results from: rust-client,snippets
2019-09-15T15:31:03.167 INFO (pid:12245) [completion-complete] - Results from: rust-client,snippets
2019-09-15T15:31:39.076 ERROR (pid:12245) [languages] - getHover timeout after 5s
2019-09-15T15:31:39.094 ERROR (pid:12245) [plugin] - Error: getHover timeout after 5s
    at Timeout._onTimeout (/xxx/xxx/.vim/plugged/coc.nvim/build/index.js:49208:28)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

is the log when i open up a new rust file and attempt to `:call CocAction('doHover')`

**Comment by errantspark** [comment]
@chemzqm 

Just to confirm, you have a configuration of vim+coc where the following works to bring up a documentation popup?

1. open a rust file in vim
1. type `println!`
1. place cursor on `println!`
1. `:call CocAction('doHover')`

This does **NOT** work to create a documentation popup for me. I have been able to replicate the problem using a minimal `$VIMRC` on my default machine and now on a brand new machine, fresh install of everything.

Both machines display documentation as I type, but do **NOT** display documentation when using `:call CocAction('doHover')` when editing a `*.rs` file. The issue persists regardless of `coc-rls` or `coc-rust-analyzer` backends.

Everything works fine when editing `*.js`

**Comment by chemzqm** [comment]
I don't have hover information for `println` as well, but I have documentation for other symbols.
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by fannheyward** [comment]
<img width="570" alt="屏幕快照 2019-09-16 09 27 06" src="https://user-images.githubusercontent.com/345274/64930528-36d88700-d864-11e9-86d3-b36b447be9ae.png">

`coc-rust-analyzer` works.

You can check LS output: 
1. set `"rust-analyzer.trace.server": "verbose"`
2. `:CocCommand workspace.showOutput`
3. You will find something like this:

```
[Trace - 上午9:26:23] Sending request 'textDocument/hover - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fannheyward/src/hello-rust/src/main.rs"
    },
    "position": {
        "line": 1,
        "character": 4
    }
}


[Trace - 上午9:26:23] Received response 'textDocument/hover - (3)' in 5ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```rust\n#[macro_export]\nmacro_rules! println\n```\n\nPrints to the standard output, with a newline.\n\nOn all platforms, the newline is the LINE FEED character (`\\n`/`U+000A`) alone\n(no additional CARRIAGE RETURN (`\\r`/`U+000D`).\n\nUse the [`format!`] syntax to write data to the standard output.\nSee [`std::fmt`] for more information.\n\nUse `println!` only for the primary output of your program. Use\n[`eprintln!`] instead to print error and progress messages.\n\n[`format!`]: ../std/macro.format.html\n[`std::fmt`]: ../std/fmt/index.html\n[`eprintln!`]: ../std/macro.eprintln.html\n# Panics\n\nPanics if writing to `io::stdout` fails.\n\n# Examples\n\n```rust\nprintln!(); // prints just a newline\nprintln!(\"hello there!\");\nprintln!(\"format {} arguments\", \"some\");\n```"
    },
    "range": {
        "end": {
            "character": 11,
            "line": 1
        },
        "start": {
            "character": 4,
            "line": 1
        }
    }
}
```
