### ISSUE TITLE
why must close file, and open again, then can use completion

### ISSUE THREAD

**Issue by smile-kindred** [neoclide/coc.nvim#1176]

**Comment by smile-kindred** [comment]
when write a new file like
import numpy as np

I must save and close the file, then open it again, then I can use  completion. How to skip this step?

**Comment by fannheyward** [comment]
That's because vim doesn't known the filetype, and python extension has not activation. Try `set filetype=python`.

**Comment by chemzqm** [comment]
Because VSCode must create the file on disk before you can type anything, some language server need file exists to work.

**Comment by smile-kindred** [comment]
@chemzqm when open a exists file, and add new packages, also need save and open again. is there anyway to skip this?

**Comment by chemzqm** [comment]
You may need to wait sometime for server, or use `:CocRestart` to restart coc.nvim service.

**Comment by smile-kindred** [comment]
@chemzqm  use :CocRestart work well, can coc automatic restart  when import new package?

**Comment by chemzqm** [comment]
No, but you can write viml to do that.
