### ISSUE TITLE
How do I get coc.nvim working with Swift files? 

### ISSUE THREAD

**Issue by benwoodward** [neoclide/coc.nvim#1178]
I have:
- downloaded the XCode 11 beta (Version 11.0 beta 2 (11M337n))
- Installed Swift v5.1 dev snapshot using `swiftenv`:
```bash
❯ swift -v
Apple Swift version 5.1-dev (LLVM b47beb8a70, Swift 279ca888b5)
Target: x86_64-apple-darwin18.6.0
/Library/Developer/Toolchains/swift-5.1-DEVELOPMENT-SNAPSHOT-2019-09-15-a.xctoolchain/usr/bin/lldb "--repl=-enable-objc-interop -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -color-diagnostics"
Welcome to Apple Swift version 5.1-dev (LLVM b47beb8a70, Swift 279ca888b5)
```
- Downloaded and built `sourcekit-lsp`:
```bash
~/dev/swift/test/test master*
❯ which sourcekit-lsp
/Users/ben/.swiftenv/shims/sourcekit-lsp
```
- set 'command line tools' version to xcode 11 in XCode > prefs > locations
![image](https://user-images.githubusercontent.com/1472981/64955278-2c9da380-d8cb-11e9-92d4-a63c4457e5b8.png)

- Added the following to `coc-settings.json` via `:CocConfig`

```json
{
  "diagnostic.checkCurrentLine": true,
  "languageserver": {
    "swift": {
      "command": "sourcekit-lsp",
      "args": [],
      "filetypes": ["swift"],
      "initializationOptions": {},
      "settings": {
      }
    }
  }
}
```

Things _seem_ to work, but they kind of don't. Some examples: 

`func` expands to nothing:
![image](https://user-images.githubusercontent.com/1472981/64955010-720da100-d8ca-11e9-8429-ae459013ff99.png)

`print` doesn't evoke any completion options at all: 

![image](https://user-images.githubusercontent.com/1472981/64955070-99fd0480-d8ca-11e9-93db-5aecb5a202a9.png)

I also periodically see the following error in the status bar: 

`source languageserver.swift timeout after 2000ms`

Do I have something configured incorrectly, or is this thing just not ready? Thanks.

**Comment by chemzqm** [comment]
You can increase timeout for completion.

**Comment by benwoodward** [comment]
Can you tell me how to do that please?

**Comment by fannheyward** [comment]
Add `"suggest.timeout": 5000` to `coc-settings.json` to increase.

**Comment by benwoodward** [comment]
That fixed the timeout errors, however, `sourcekit-lsp` doesn't seem to be working properly. I tried rebuilding and changed my config to the following: 

```json
{
  "diagnostic.checkCurrentLine": true,
  "suggest.timeout": 2000,
  "languageserver": {
    "swift": {
      "command": "/Users/ben/dev/GitHub/sourcekit-lsp/.build/x86_64-apple-macosx/debug/sourcekit-lsp",
      "args": [],
      "filetypes": ["swift"],
      "initializationOptions": {},
      "settings": {
      }
    }
  }
}
```

I also think it only works on projects that have been compiled with `swift build`. Think I'm gonna forget about this for now and come back when the `sourcekit-lsp` is more mature.

**Comment by chemzqm** [comment]
You can checkout verbose output from language server: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by benwoodward** [comment]
So I updated my lsp config with `"trace.server": "verbose"` and if I view the logs with `:CocCommand workspace.showOutput` I see the following error: 

```json
[Trace - 2:59:42 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "could not find manifest, or not a SwiftPM package: /Users/ben/dev/swift/test"
}
```

Looks like `sourcekit-lsp` doesn't work with XCode projects, because there is currently [no way for it to understand XCode project files](https://forums.swift.org/t/whats-the-plan-for-index/18441/4).
