### ISSUE TITLE
Missing formatting APIs in client

### ISSUE THREAD

**Issue by TylerLeonhardt** [neoclide/coc.nvim#1179]
**Is your feature request related to a problem? Please describe.**
Missing APIs for registering formatters:
`vscode.languages.registerDocumentFormattingEditProvider(`
`vscode.languages.registerDocumentRangeFormattingEditProvider(`
`vscode.languages.registerOnTypeFormattingEditProvider(`

**Describe the solution you'd like**
A similar API to be supported in coc.nvim

**Describe alternatives you've considered**
The alternative would be that a language server would need to be used.

**Additional context**
Opened this because of https://github.com/coc-extensions/coc-powershell/issues/36. Note: The PowerShell language server will eventually handle this... but I suspect a stable version of 2.0 to not release for at least another couple months.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/blob/master/src/languages.ts#L279
https://github.com/neoclide/coc.nvim/blob/master/src/languages.ts#L275
https://github.com/neoclide/coc.nvim/blob/master/src/languages.ts#L177

**Comment by TylerLeonhardt** [comment]
Thank you!
