### ISSUE TITLE
Installing extensions from a script

### ISSUE THREAD

**Issue by elentok** [neoclide/coc.nvim#118]
Hi,

I'm using a [script][1] in my dotfiles to install neovim and all of the plugins I need.

How can I install a Coc extension in a script?

I tried several options:

```
nvim "+CocInstall $extensions"
nvim --headless "+CocInstall $extensions"
nvim --headless "+CocInstall $extensions" +qall
```

The first one works but doesn't close nvim afterwards (so the install script can't run unattended), 
the second one remains blank and the third exits immediately.

For reference to install vim-plug plugins I run:

```
nvim --headless +PlugInstall +UpdateRemotePlugins +qall
```

If I just go to `~/.config/coc/extensions` and run `yarn add $extensions` will that be enough? or does coc register the extensions somewhere else?

Thanks for all the great work you're doing, I love this plugin! 👍 

[1]: https://github.com/elentok/dotfiles/blob/master/nvim/install#L109

**Comment by chemzqm** [comment]
> If I just go to ~/.config/coc/extensions and run yarn add $extensions will that be enough?

Yes, that's all you need to do, except that the location is different on windows.

> does coc register the extensions somewhere else.

Is's possible for a vim plugin to regist custom extension root, then you need to use a plugin manager to install that plugin, but none of current extensions is vim plugin right now.

**Comment by elentok** [comment]
Cool, thanks!

**Comment by ardydavari** [comment]
I wanted to run this in a docker build file, and I found a hack that worked: `RUN timeout 1m nvim --headless +CocInstall; exit'

**Comment by Trainraider** [comment]
I found a good solution: `nvim --headless +"CocInstall -sync $extensions|qa"
`

**Comment by nachovizzo** [comment]
None of the solutions above works in my case. I've defined `coc_global_extensions` and inside vim `:CocInstall` works just fine. The problem is that I'm trying to run an unattended script where yarn is not available (but `npm` is)

Is there anything I'm missing to try?

I wish I could do
```sh
nvim --headless +CocInstall +qall
```

But exits right away

**Comment by nachovizzo** [comment]
In the meantime this is doing the job for me:

```sh
mkdir -p ~/.config/coc/extensions && cd ~/.config/coc/extensions
if [ ! -f package.json ]; then
  echo '{"dependencies":{}}' >package.json
fi
COC_EXTENSIONS=$(nvim --headless -c 'echo coc_global_extensions' +qa 2>&1 | awk -v RS="'" '!(NR%2)')
npm install $(echo $COC_EXTENSIONS) --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
```

**Comment by Freed-Wu** [comment]
if `len(g:coc_global_extensions) > 18`, it will

```
❯ vi --headless -c "call coc#util#install_extension(['-sync'] + g:coc_global_extensions) |qa"
Error on request (installExtensions): Vim(return):E699: Too many arguments%
```

```
❯ vi --headless -c'echo g:coc_global_extensions | quit'
cwd: /home/wzy/.config/coc
['coc-highlight', 'coc-ci', 'coc-pydocstring', 'coc-diagnostic', 'coc-spell-checker', 'coc-markdownlint', 'coc-prettier', 'coc-tasks', 'coc-vimtex', 'coc-emmet', 'coc-snippets', 'coc-translator', 'coc-zi', 'coc-marketplace', 'coc-lists', 'coc-yank', 'coc-git', 'coc-gist', 'coc-gitignore', 'coc-dash-complete', 'coc-dot-complete', 'coc-just-complete', 'coc-bibtex', 'coc-dictionary', 'coc-tag', 'coc-word', 'coc-emoji', 'coc-syntax', '@yaegassy/coc-marksman', 'coc-webview', 'coc-markdown-preview-enhanced', 'coc-json', 'coc-yaml', 'coc-toml', 'coc-xml', 'coc-svg', 'coc-html', 'coc-clang-format-style-options', 'coc-docker', 'coc-sql', 'coc-sh', 'coc-vimlsp', 'coc-texlab', 'coc-jedi', 'coc-pyright', 'coc-lua', 'coc-solargraph', 'coc-clangd', 'coc-tabnine']%
```

So `tail -n1` is needed.

And I prefer sed than awk:

```sh
cd ~/.config/coc/extensions
npm install $(vi --headless -c'echo g:coc_global_extensions | quit' 2>&1 | tail -n1 | sed "s=\(', '\|\['\|']\)=\n=g")
```

works for me.
