### ISSUE TITLE
Enable or disable coc extensions per language

### ISSUE THREAD

**Issue by vitreo12** [neoclide/coc.nvim#1183]
Hello, 
I have been looking in the docs for the possibility of enabling and disabling coc extensions on a per language basis. Is this achievable? If not, I think it would be a nice feature to have.

**Comment by chemzqm** [comment]
You can use api with vim's autocmd.

**Comment by vitreo12** [comment]
Thanks for the prompt answer.
However, I am having some troubles on pairing autocmd with the disabling with a coc extension, which in my case is coc-snippets. What would be the vim command for disabling coc-snippets?

**Comment by chemzqm** [comment]
RTFM

**Comment by jrwrigh** [comment]
I've read through the manual and have been trying to implement a solution for the past 3 or so hours. Would anyone care to help?

Currently, I would like to have `coc-word` disabled for everything except text and markdown documents. I tried using `"coc.source.word.enable": false` in the coc config file, and then doing a `autocmd FileType text call CocAction('toggleExtension', 'coc-word')` to activate the extension. However, the coc config setting doesn't appear to do anything, or the autocmd is activating for all files.

**Comment by jrwrigh** [comment]
For future stragglers, I ended up using `"coc.source.word.filetypes": ["text", "markdown"]` instead of going the `autocmd` route.

**Comment by erahhal** [comment]
I'm in the same situation - after reading the docs for an hour I've not yet figured out how to disable and enable extensions per filetype.  A quick example would help out a lot of people who have landed on this thread.

**Comment by chemzqm** [comment]
You can use vim-plug for coc extensions

**Comment by erahhal** [comment]
@chemzqm thanks for your help, but I'm talking about enabling and disable coc extensions when you enter a buffer, and it detects the file type, during a single vim session.  I will be editing several files, and if I, say, enter a vimscript buffer, I want to disable coc-spell-check.  If I load a markdown file, I want to re-enable it.  vim-plug is for installing and loading plugins at start, and not really for managing whether a plugin is active for a particular buffer.

**Comment by chemzqm** [comment]
@erahhal some coc extensions provide options for enabled filetypes,  you can send feature request to the extension or use autocmd with API `CocAction('toggleExtension', id)`

**Comment by erahhal** [comment]
Thank you!  It looks like coc-spell-checker has language settings.

On a side note, how would the CocAction call look in vimscript?  Isn't CocAction a JS function?  Also, would the id just be the name of the extension, i.e. "coc-spell-checker" in this case?

**Comment by chemzqm** [comment]
Use ':CocList extensions'

**Comment by woshichuanqilz** [comment]
> For future stragglers, I ended up using `"coc.source.word.filetypes": ["text", "markdown"]` instead of going the `autocmd` route.

The config turns to be 

I want `coc-word` enable in filetype `tiddlywiki`.
How to add a new file type into it.Now coc-words works in `josn, markdown`
```

        "coc.source.word.filetypes": {
          "type": [
            "array",
            "null"
          ],
          "default": null,
          "items": {
            "type": "string"
          }
        }
```

**Comment by chemzqm** [comment]
Like `  "coc.source.word.filetypes": ["gitcommit", "markdown", "help", "txt"],`

**Comment by woshichuanqilz** [comment]
> Like ` "coc.source.word.filetypes": ["gitcommit", "markdown", "help", "txt"],`

Thank you it worked, but these code is discarded, will cause other issue? 

```
{
          "type": [
            "array",
            "null"
          ],
          "default": null,
          "items": {
            "type": "string"
          }
        }
```

**Comment by chemzqm** [comment]
No, these code are schema, not value.

**Comment by johnmathews** [comment]
For reference, here is the solution I am using. This scenario turns off the `coc-tag` extension when my current buffer is a markdown file and then activates it again once I go to a different buffer.

```vim
augroup toggleCocExtensions
    autocmd!
    autocmd BufEnter *.md call CocActionAsync('deactivateExtension', 'coc-tag') 
    autocmd BufLeave *.md call CocActionAsync('activeExtension', 'coc-tag') 
augroup END

```

**Comment by chemzqm** [comment]
@johnmathews why not use `"coc.source.tag.filetypes": ["markdown"]` in coc-settings.json?

**Comment by johnmathews** [comment]
@chemzqm thanks for the suggestion! 

I chose to use auto commands because after googling and searching the documentation it wasn't clear to me how to use coc-settings.json. 

Also, I'm already familiar with autocommands and I use the `ftplugin/` dir as well as `.vimrc`. I didn't want to put vim settings in a third place (coc-settings.json) if it could be avoided. It seemed simpler, more intuitive and harder to forget what I'd done.

However, thanks to your example I see that using coc-settings is much more concise. I will use it.
 
Is there an exclusion setting as well? Like `"coc.source.tag.not.filetypes"`? (I know.. rtfm..)

Thanks for a really useful plugin! It's amazing.

**Comment by ElnuDev** [comment]
I couldn't get any of the solutions here to work, so if anyone came here wanting to only have CoC run on a particular language (in my case, Rust `*.rs` files), here is my solution. I'm really new to vim and its configuration and I know this is really awful, but it works for me and hopefully someone finds it helpful.

```VIM
autocmd VimEnter * exe "CocDisable" " disable CoC by default
autocmd VimEnter *.rs exe "CocEnable" " enable CoC when entering vim to Rust file
autocmd BufEnter *.rs exe "CocEnable" " enable CoC when switching buffer to Rust file
autocmd BufLeave *.rs exe "CocDisable" " disable CoC when exiting Rust file buffer
```

**Comment by chemzqm** [comment]
Use `b:coc_enabled` is recommended.
