### ISSUE TITLE
Exclude duplicate entries in completion results

### ISSUE THREAD

**Issue by daveyarwood** [neoclide/coc.nvim#1184]
**Is your feature request related to a problem? Please describe.**

I use two plugins for Clojure that both provide completion results:

* https://github.com/snoe/clojure-lsp - a Clojure LSP server
* https://github.com/Olical/conjure - a REPL client

These are both valuable to have. Conjure works best when I have a REPL running, so that it has runtime context about my program. clojure-lsp is always nice to have because it does static analysis of my code, so that I don't need to have a REPL running in order to get linting and autocompletion.

Because both plugins provide completion results, I end up with duplicate entries in my completion results, as seen in this screenshot:

![2019-09-19-140239_1255x260_scrot](https://user-images.githubusercontent.com/4909079/65268935-2a636100-dae6-11e9-999c-0a31c931342f.png)

**Describe the solution you'd like**
It would be great if I could deduplicate any completion entries where the value is the same (e.g. `with-new-context` in the screenshot above) and the entries come from different sources.

Ideally, if I configure COC to assign higher priority to Conjure vs. clojure-lsp, then when both plugins provide completion entries with the same value, COC removes the clojure-lsp entry from the results altogether instead of sorting it lower.

I'm not sure exactly if it would make sense for this to be the default behavior, or if it should be opt-in. Perhaps this removal behavior could only happen if you opt into it for a particular group of plugins, something like `"coc.source.languageserver.prefer": ["conjure"]`? Or perhaps it could be a global opt-in behavior, like `"suggest.removeDuplicates": true`?

**Describe alternatives you've considered**
I've considered removing one plugin or the other, but they both provide useful functionality independent from one another.

I can't think of any other alternatives.

**Comment by chemzqm** [comment]
> where the value is the same

What does `value` means? The label is not the same at least, it does deduplicate when completion items have exact same word.

**Comment by chemzqm** [comment]
The problem is they're not the same.

**Comment by daveyarwood** [comment]
@chemzqm By "value," i mean that they both auto-complete to the same thing: `with-new-context`. The labels are different, but I'm concerned with completion values, not labels.

**Comment by chemzqm** [comment]
There's no value with complete items.

**Comment by daveyarwood** [comment]
By "value," I mean the text that is inserted when I select a candidate. In this case, it's `with-new-context` for both options, even though the labels are different.

**Comment by daveyarwood** [comment]
@chemzqm https://github.com/neoclide/coc.nvim/commit/2bc8cd8b79d4c588a7088e4d1d6ed07604b01d88 gets me partially there in that it removes duplicates, but the logic for which ones it removes is unclear, and in my case, it happens to remove the wrong one. I added the following to my coc-settings.json:

```json
  "coc.source.conjure.priority": 999999,
  "suggest.removeDuplicateItems": true
```

Is there a way that I can specify that the Conjure candidates should not be removed as duplicates?

**Comment by chemzqm** [comment]
You should make it higher priority then.

**Comment by daveyarwood** [comment]
Whoops -- I think there was something off with the project I was using to test. Conjure actually wasn't providing completions for some reason, so I was seeing the clojure-lsp completions, which is exactly what should happen in that scenario.

I tried it again with a different project where I know Conjure works, and the Conjure completions are preferred, and it looks like the deduplication is removing the clojure-lsp completions.

Thanks for the quick response on this, great stuff! :+1:
