### ISSUE TITLE
`:CocUpdate` fails with error EHOSTUNREACH

### ISSUE THREAD

**Issue by gasuketsu** [neoclide/coc.nvim#1186]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.2
node version: v12.10.0
coc.nvim version: 0.0.74-3aea9c9662
term: screen-256color
platform: linux

## Messages[coc.nvim] Error on update coc-yaml: Error: connect EHOSTUNREACH 104.16.20.35:443
[coc.nvim] Error on update coc-python: Error: connect EHOSTUNREACH 104.16.24.35:443
[coc.nvim] Error on update coc-vimlsp: Error: connect EHOSTUNREACH 104.16.26.35:443
[coc.nvim] Error on update coc-git: Error: connect ETIMEDOUT 104.16.22.35:443
[coc.nvim] Error on update coc-json: Error: connect ETIMEDOUT 104.16.18.35:443
[coc.nvim] Update completed

## Output channel: git
Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /nfs/home1/tharada/.config
resolved root: /nfs/home1/tharada/.config
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /nfs/home1/tharada/.config
resolved root: /nfs/home1/tharada/.config
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /nfs/home1/tharada/.config
resolved root: /nfs/home1/tharada/.config
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
```

## Describe the bug

With latest release branch `:CocUpdate` fails to update extensions with error `EHOSTUNREACH`.
With latest tagged version v0.0.74, `:CocUpdate` works well.

## Reproduce the bug

My environment is behind of the proxy w/ auth. (i.e. I have http proxy configuration like `"http.proxy": "user:passworod@proxy.example.com:8080"` in `coc-settings.json`)
I am not sure if this issue is related to http.proxy configuration but guessing proxy configuration is related since most people should not have proxy configuration no one reports similar issue...

- coc-settings.json with proxy configuration

```
{
  "http.proxy": "user:password@proxy.example.com:8080"
}
```
- Perform `:CocUpdate` (should have one ore more extensions)

**Comment by chemzqm** [comment]
Should be problem of your network or your proxy.

**Comment by gasuketsu** [comment]
As I described in #1209, this issue can be observed when length of one of NO_PROXY/no_proxy entries is one char longer than hostname of URL even if user have right proxy configuration.
