### ISSUE TITLE
coc-tabnine doesn't work as expect

### ISSUE THREAD

**Issue by diartyz** [neoclide/coc.nvim#1187]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.2
node version: v10.16.3
coc.nvim version: 0.0.74-3aea9c9662
term: iTerm.app
platform: darwin

## Messages

## Output channel: prettier


## Output channel: watchman

[Info  - 11:11:09 AM] watchman watching project: /Users/diartyz/Coding/sinopec-fe
[Info  - 11:11:09 AM] subscribing "**/{.prettierrc,.prettierrc.json,.prettierrc.yaml,.prettierrc.yml,.prettierrc.js,package.json,prettier.config.js}" in /Users/diartyz/Coding/sinopec-fe
[Info  - 11:11:09 AM] subscribing "**/[tj]sconfig.json" in /Users/diartyz/Coding/sinopec-fe
[Info  - 11:11:09 AM] subscribing "**/package.json" in /Users/diartyz/Coding/sinopec-fe
[Info  - 11:11:09 AM] subscribing "**/*.{ts,tsx}" in /Users/diartyz/Coding/sinopec-fe
[Info  - 11:11:09 AM] subscribing "**/*.{js,jsx}" in /Users/diartyz/Coding/sinopec-fe

## Output channel: snippets

[Info  - 11:11:09 AM] watchman watching project: /Users/diartyz/.config/coc/ultisnips
[Info  - 11:11:09 AM] subscribing "**/*.snippets" in /Users/diartyz/.config/coc/ultisnips

## Output channel: tsserver

[Info  - 11:11:09 AM] Forking TSServer
PATH: /Users/diartyz/.nvm/versions/node/v10.16.3/bin:/Users/diartyz/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/diartyz/.nvm/versions/node/v10.16.3/bin:/Users/diartyz/.local/bin:/usr/local/sbin 
[Info  - 11:11:09 AM] Started TSServer
{
  "path": "/Users/diartyz/Coding/sinopec-fe/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.6.2",
    "version": "3.6.2"
  }
}
```

## Describe the bug

In vscode, tabnine prompt:

![image](https://user-images.githubusercontent.com/4486152/65296789-3c9dd780-db98-11e9-9950-2f89ffce0575.png)

but in coc, tabnine prompt:

![image](https://user-images.githubusercontent.com/4486152/65296694-cf8a4200-db97-11e9-8723-3173f0bc5874.png)

I expected the same result as vscode like this:

![image](https://user-images.githubusercontent.com/4486152/65296862-7b339200-db98-11e9-88dd-18048e9174e2.png)

## An alternative resolution

I think it's caused by the following hardcode:

https://github.com/neoclide/coc.nvim/blob/d9ac1b15683f5d15bde5d67a9736c204a5db059d/src/completion/complete.ts#L192

**Comment by chemzqm** [comment]
Seems your coc-tabnine is not working at all.

**Comment by diartyz** [comment]
The result from tabnine server is the following, they share the same key `word: container`, so all the rest items are treat as duplicate items and  filtered.

I notice you add `removeDuplicateItems` config, but it will still filter the result from tabnine because the hardcode https://github.com/neoclide/coc.nvim/blob/master/src/completion/complete.ts#L193.

```
  items:
   [ { word: 'container',
       abbr: 'container',
       menu: '53% [TN]',
       kind: '',
       sortText: '0',
       filterText: 'container',
       isSnippet: undefined,
       dup: 1,
       detailShown: 1,
       info: '',
       line: '    <Grid c>',
       index: 0 },
     { word: 'container',
       abbr: 'container spacing',
       menu: '16% [TN]',
       kind: '',
       sortText: '00',
       filterText: 'container spacing',
       isSnippet: undefined,
       dup: 1,
       detailShown: 1,
       info: '',
       line: '    <Grid c>',
       index: 1 },
     { word: 'container',
       abbr: 'container spacing={2}',
       menu: '16% [TN]',
       kind: '',
       sortText: '000',
       filterText: 'container spacing={2}',
       isSnippet: undefined,
       dup: 1,
       detailShown: 1,
       info: '',
       line: '    <Grid c>',
       index: 2 },
     { word: 'container',
       abbr: 'container>',
       menu: ' 7% [TN]',
       kind: '',
       sortText: '0000',
       filterText: 'container>',
       isSnippet: undefined,
       dup: 1,
       detailShown: 1,
       info: '',
       line: '    <Grid c>',
       index: 3 },
     { word: 'container=',
       abbr: 'container=',
       menu: ' 4% [TN]',
       kind: '',
       sortText: '00000',
       filterText: 'container=',
       isSnippet: undefined,
       dup: 1,
       detailShown: 1,
       info: '',
       line: '    <Grid c>',
       index: 4 } ],
  priority: 99,
  source: 'tabnine' }
```

**Comment by chemzqm** [comment]
It's intended since tabnine doesn't give addtional information unless you use lsp for it.

**Comment by diartyz** [comment]
But it does make sense, for example 

```
- container
- container spacing
- container spacing={2}
- container>
```

Their key property is same (`container`), but only the first item is remained in this way.

Maybe use another key to filter duplicate items, such as `abbr ` or `filterText`.

Or combine line https://github.com/neoclide/coc.nvim/blob/master/src/completion/complete.ts#L193
and https://github.com/neoclide/coc.nvim/blob/master/src/completion/complete.ts#L192,
make `removeDuplicateItemd` works with tabnine too, so people can do their own choice.

**Comment by chemzqm** [comment]
They're not inserted text, so the problem is return result from tabnine

**Comment by diartyz** [comment]
I'm confused, is there something wrong with the return result form tabnine?

**Comment by chemzqm** [comment]
They should have different word, could be problem of coc-tabnine

**Comment by diartyz** [comment]
I found the problem is https://github.com/neoclide/coc.nvim/blob/master/src/util/complete.ts#L6, so `getValidWord` return same word.

Do you remember why is config `invalidInsertCharacters` removed?
I can make a pr if you agree to add it back.
