### ISSUE TITLE
Feature: find-all-references and detail doHover

### ISSUE THREAD

**Issue by stkevintan** [neoclide/coc.nvim#1189]
**Is your feature request related to a problem? Please describe.**
1. find-all-references: the action in the context menu (right click some keyword) in vscode
![图片](https://user-images.githubusercontent.com/5887203/65307959-9663c900-dbbb-11e9-8c9a-bc8b26fba51e.png)
2. detail doHover: in vscode , when you hover cusor on some keyword, it will prompt a a brief help message, but if you hover a word while keep press the `Alt` key , vscode will show some additional detail message. (eg: the red rect area in following screenshot)
![图片](https://user-images.githubusercontent.com/5887203/65308174-112ce400-dbbc-11e9-8ab8-7a59e22a3f95.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
Both already implemented

**Comment by chemzqm** [comment]
Except for that additional detail message.

**Comment by stkevintan** [comment]
@chemzqm Sorry it's not `Alt` key, but `Ctrl` or `Command` key. 
but it seems vscode do not support it as an action for now.

related issue : https://github.com/microsoft/vscode/issues/46257
