### ISSUE TITLE
vim8 floating buffer issues

### ISSUE THREAD

**Issue by amiralies** [neoclide/coc.nvim#1192]
There are some issues with floating buffer in vim8. height doesn't set properly and syntax highlighting does'nt work on complex dialogues,
Vim 8:
![image](https://user-images.githubusercontent.com/13261088/65333245-5d385280-dbd5-11e9-8c8f-a5e181396d97.png)

Neovim: 
![image](https://user-images.githubusercontent.com/13261088/65333291-7a6d2100-dbd5-11e9-8c52-522f58b37898.png)

**Comment by fannheyward** [comment]
Yes, there is no highlight on vim 8 popup, check https://github.com/neoclide/coc.nvim/issues/959
