### ISSUE TITLE
Preview jumps through marked items in a location list each time the list selection changes

### ISSUE THREAD

**Issue by kmoschcau** [neoclide/coc.nvim#1193]
## Result from CocInfo

```
vim version: NVIM v0.4.2
node version: v12.6.0
coc.nvim version: 0.0.74
term: tmux-256color
platform: linux
```

## Describe the bug

The preview window for location lists jumps through all marked items in the list whenever the list selection changes.  
If no items are marked, the preview just jumps to the currently selected item. If there is one item marked, the preview does not update. If there are 2 or more items marked, the preview jumps through all marked items each time the cursor in the list moves.  
This is also impacting performance, since this makes (neo)vim open and close buffers in quick succession.

## Reproduce the bug

You need to have a somewhat larger project in order to reproduce this. I mainly encounter this with a Java project at my workplace, so I can not share this project here. I use coc-java and the Eclipse language server on this project. When I open the location list with references for a class or method, then mark some items in the list, the problem above occurs.

## Update

I was just able to reproduce this with a slightly modified mini.vim. The performance impact is a lot lower with this, since not quite as many things need to happen when opening a buffer. But once you have some plugins running, it becomes a really noticeable slowdown.
Here is the mini.vim:
```vim
set nocompatible
set background=light
nmap     <silent>       <C-s>r     <Plug>(coc-references)
set runtimepath^=~/.local/share/nvim/plugged/coc-java/
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim/
filetype plugin indent on
syntax on
set hidden
```
And here is my coc-settings.json for refererence:
```json
{
  "coc.preferences.extensionUpdateCheck": "never",
  "coc.source.file.trimSameExts": [
    ".js",
    ".rb",
    ".ts"
  ],
  "codeLens.enable": true,
  "diagnostic.displayByAle": true,
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "objc", "objcpp"],
      "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
      "initializationOptions": {
        "cache": {
          "directory": "/tmp/ccls"
        }
      }
    }
  },
  "eslint.autoFix": false,
  "java.codeGeneration.useBlocks": true,
  "java.configuration.updateBuildConfiguration": "automatic",
  "java.completion.importOrder": [
    "com",
    "java",
    "javassist",
    "javax",
    "org"
  ],
  "java.errors.incompleteClasspath.severity": "error",
  "java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml",
  "java.home": "/usr/lib/jvm/java-8-openjdk-amd64/",
  "java.implementationsCodeLens.enabled": true,
  "java.referencesCodeLens.enabled": true,
  "java.signatureHelp.enabled": true,
  "python.disableInstallationCheck": true,
  "solargraph.checkGemVersion": false,
  "solargraph.completion": true,
  "solargraph.definitions": true,
  "solargraph.diagnostics": true,
  "solargraph.formatting": true,
  "solargraph.hover": true,
  "solargraph.references": true,
  "solargraph.rename": true,
  "solargraph.symbols": true,
  "solargraph.useBundler": true
}
```

**Comment by chemzqm** [comment]
Sorry, can't understand how to reproduce.

**Comment by kmoschcau** [comment]
I *think* it is possible to reproduce this with the coc.nvim project itself, using coc-tsserver. When you open `src/services.ts` and list the references for the `ServiceManager` class' `dispose` method, you get 89 entries in the list. If you now mark all of them and move the cursor around in the list, the bug seems to happen.
It is just a lot harder to see when opening a buffer like this is quick.
So I tried to construct something with autocommands, but I can't find an event for opening a file in the preview window.
If however I do the same thing with my usual vim setup, where opening a buffer takes a bit longer, I can easily see the preview window going through multiple files in short order. This sometimes becomes so bad, that it causes the editor to randomly switch windows and sometimes even change window sizes.

**Comment by kmoschcau** [comment]
I did two asciinema recordings of the problem.
Here is one with the minimal startup setup: https://asciinema.org/a/270070
And here is one with my usual startup setup: https://asciinema.org/a/270071

**Comment by chemzqm** [comment]
Reproduced
