### ISSUE TITLE
The floating window does not disappear after the <C-c> (Neovim)

### ISSUE THREAD

**Issue by npupko** [neoclide/coc.nvim#1197]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.2
node version: v12.8.1
coc.nvim version: 0.0.74-c97d41aa1e
term: iTerm.app
platform: darwin

## Messages
Type  :qa  and press <Enter> to exit Nvim




[coc.nvim] Solargraph is ready.
[coc.nvim] Successfully updated the Solargraph gem.

Scanning: [Scratch]
Scanning: NERD_tree_1
Scanning: app/assets/javascripts/plugin.js.coffee
Scanning: app/services/fb_token_updater.rb
Scanning tags.

1 change; before #2  3 seconds ago
Lint/Void: Variable `Webshots` used in void context.
Type  :qa!  and press <Enter> to abandon all changes and exit Nvim
1 line less; before #1  11 seconds ago

Lint/Void: Variable `Webshots` used in void context.

Lint/Void: Variable `Webshots` used in void context.
## Output channel: highlight

[Info  - 12:36:33 PM] Highlight server running in node v12.8.1
```

## Describe the bug

The floating window with the documentation does not dissapear after I hit the `<C-c>`.
Everything OK with the `<C-]>`

## Reproduce the bug

Just use plain Neovim config

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start Neovim with command: `vim -u mini.vim`

## Screenshots
![Screen Recording 2019-09-23 at 13 03 00](https://user-images.githubusercontent.com/5938539/65417555-fef0b700-de02-11e9-8f24-71fa071bf77a.gif)

**Comment by npupko** [comment]
I think it cause of <C-c> don't trigger the `InsertLeave` and it can be temporary fixed with 
```
inoremap <C-c> <Esc><Esc>
```
but I think it's not correct behaviour for the coc.nvim, isn't it?

**Comment by fannheyward** [comment]
`inoremap <C-c> <ESC>` works for me.

**Comment by chemzqm** [comment]
It's expected, coc.nvim doesn't create this kind of keymapping for you.
