### ISSUE TITLE
Add vim-go support?

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#12]
COC works great for TS, thanks for your work.

Is there any way to add vim-go support? <C-x><C-o> will popup completion items, but there is no autocompletion.

Thanks.

**Comment by chemzqm** [comment]
There's some bug with omni integration.

**Comment by chemzqm** [comment]
Turns out the omni func not working well, I will add a vim source for gocode.

**Comment by chemzqm** [comment]
I've added gocode source, it should just works, use https://github.com/Shougo/echodoc.vim to get function signature help on completion.
