### ISSUE TITLE
Master branch build, results in wrong root directory for ccls

### ISSUE THREAD

**Issue by MarkGreeny** [neoclide/coc.nvim#1201]
# Result from CocInfo for *release* build

## versions

vim version: NVIM v0.3.8
node version: v10.16.3
coc.nvim version: 0.0.74-bc017b02e6
term: xterm-256color
platform: linux

## Output channel: languageserver.ccls

19:28:43 ccls           initialize.cc:274 I initialize in directory /path/to/xExperiments/walker with uri file:///path/to/xExperiments/walker
19:28:43 ccls           initialize.cc:297 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":"/tmp/ccls","format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":[],"pathMappings":[],"resourceDir":""},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":true,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
19:28:43 ccls           initialize.cc:326 I use -resource-dir=/path/to/ccls/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/clang/8.0.0
19:28:43 ccls           initialize.cc:359 **I workspace folder: /path/to/parentDirectory/actualRoot/**

# Result from CocInfo for *master* build

## versions

vim version: NVIM v0.3.8
node version: v10.16.3
coc.nvim version: 0.0.74
term: xterm-256color
platform: linux

## Output channel: languageserver.ccls

19:27:33 ccls           initialize.cc:274 I initialize in directory /path/to/xExperiments with uri file:///path/to/xExperiments
19:27:33 ccls           initialize.cc:297 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":"/tmp/ccls","format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":[],"pathMappings":[],"resourceDir":""},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":true,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
19:27:33 ccls           initialize.cc:326 I use -resource-dir=/path/to/ccls/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/clang/8.0.0
19:28:43 ccls           initialize.cc:359 **I workspace folder: /path/to/parentDirectory/**

# Describe the bug
### Scenario

We open neovim, and the file **/path/to/parentDirectory/actualRoot/someFile.cpp** in the directory **/path/to/parentDirectory/actualRoot**. Both the **/path/to/parentDirectory/actualRoot** directory and the **/path/to/parentDirectory/** have a **.ccls** files. In other words:

**Existing configs:**
  * /path/to/parentDirectory/actualRoot/.ccls
  * /path/to/parentDirectory/.ccls

**PWD for neovim, vims working directory**:
  * /path/to/parentDirectory/actualRoot

**Opened file**:
  * /path/to/parentDirectory/actualRoot/someFile.cpp

### What happens

Please consult the last lines in each of the **CocInfo** outputs. The *release* build, correctly sets the working directory to **/path/to/parentDirectory/actualRoot/**, while the *master* release sets it to its parent directory **/path/to/parentDirectory/**.

Note that when you delete the **.ccls** file from the **/path/to/parentDirectory**, master branch produces the same **CocInfo** as the release branch.

### What was expected to happen

Because a config file exists in the current working directory **/path/to/parentDirectory/actualRoot**, this is expected to be the working directory for the **CCLS**. Instead, coc seems to recurse deeper to the **/path/to/parentDirectory**, if a config exists there. Note that we do have
```
"rootPatterns": [
        ".ccls", .....
]
```
in the CocConfig (which was taken from the FAQ).

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders you have to start your vim from workspace root then.

**Comment by MarkGreeny** [comment]
@chemzqm I think there was a misunderstanding. I am starting vim from the workspace root. Vim is started in **/path/to/parentDirectory/actualRoot**. But if both **/path/to/parentDirectory/actualRoot** and **/path/to/parentDirectory** contain a `.ccls` file, than the **master** build sets the **/path/to/parentDirectory** as the workspace directory for **ccls**, while the **release** build correctly sets the **/path/to/parentDirectory/actualRoot**.

**Comment by chemzqm** [comment]
Can't reproduce, the release branch is build from master and this logic doesn't have changed.
