### ISSUE TITLE
Support UTF-8 for the LSP protocol

### ISSUE THREAD

**Issue by XVilka** [neoclide/coc.nvim#1204]
See the lengthy discussion here: https://github.com/microsoft/language-server-protocol/issues/376

It seems that CoC is one of a few that uses UTF-16 https://github.com/Avi-D-coder/lsp-range-unit-survey

Would be nice if it will have UTF-8 support as well, at least optionally.

**Comment by chemzqm** [comment]
It's javascript that use UTF-16, it should not be problem for the end users.
