### ISSUE TITLE
Coc cancelling prompt from Command mode during setup

### ISSUE THREAD

**Issue by alvarosevilla95** [neoclide/coc.nvim#1206]
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 27 2019 00:46:03)
node version: v12.6.0
coc.nvim version: 0.0.74-c97d41aa1e
term: iTerm.app
platform: darwin

## Messages
Messages maintainer: Mike Williams <mrw@eandem.co.uk>
"path/to/file.java" 123L, 3807C
[coc.nvim] Using java from /Library/Java/JavaVirtualMachines/openjdk-12.jdk/Contents/Home, version: 12
[coc.nvim] JDT Language Server starting at /path/to/workspace
[coc.nvim] JDT Language Server started

Already at oldest change
"~/.vim/coc-settings.json" 14L, 425C
[coc.nvim] Run :CocInstall coc-json for json intellisense
The only match
The only match
"~/.vim/coc-settings.json" 14L, 423C written

match 1 of 2
match 1 of 2
1 change; before #4  1 second ago
1 line less; before #3  2 seconds ago
"path/to/file.java" 123 lines --23%--
client coc abnormal exit with: -1
client coc stopped!
starting coc.nvim service

[coc.nvim] JDT Language Server started
Entering Ex mode.  Type "visual" to go to Normal mode.
E492: Not an editor command: visul
## Output channel: java

[Info  - 14:38:54] JDT Language Server started
[object Object]

## Describe the bug
When the Coc extension is doing work (for example while starting the server) certain actions in Command Mode that require an input from the user (for instance a list where the user should select an element) get cancelled immediately.

## Reproduce the bug
- Start Coc server (On Java I see "JDT Language Server starting at...")
- Input `:ls` in Command mode
- The list of buffers briefly shows up, but immediatly dissapears.
- Wait for Coc Server to finish starting 
- Inputting `:ls` again the buffer list shows up and stays there.

I am able to reproduce the bug with the default mini.vim, although I'm using the coc-java extension:
  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

**Comment by chemzqm** [comment]
This happens when the server send notification to vim, it's how vim works and I can't see any way to avoid this problem.

**Comment by cosminadrianpopescu** [comment]
Maybe the notifications can be stopped by the node process until the server is ready? And then dump them all?

**Comment by chemzqm** [comment]
Notification won't send when server not ready,  use `let g:coc_start_at_startup = 0` to avoid coc.nvim start on vim start, you have to manually start coc.nvim then.

**Comment by cosminadrianpopescu** [comment]
> Notification won't send when server not ready, use let g:coc_start_at_startup = 0 to avoid coc.nvim start on vim start, you have to manually start coc.nvim then.

The issue is not the coc.nvim starting, but also the language server starting. So starting the coc.nvim server manually won't help either. 

> Maybe the notifications can be stopped by the node process until the server is ready? And then dump them all?

What I mean here is: When a request for start has been sent to one of the lsp servers, disable notifications to vim until the server is ready or it fails. Based on some option maybe...

**Comment by chemzqm** [comment]
For notification I mean notification send to vim, not language server notification.
I think it's vim's bug and I don't the way to detect prompt state of vim when using vim's channel.
