### ISSUE TITLE
Respect diagnostic.level when diagnostic.displayByAle is enabled

### ISSUE THREAD

**Issue by adc17** [neoclide/coc.nvim#1208]
**Is your feature request related to a problem? Please describe.**
When using ale for diagnostics, I'd like to filter out low-severity messages. 

**Describe the solution you'd like**
I'd like `diagnostic.level` from my `coc-settings.json` to decide which messages are passed to ale diagnostics as well.

**Describe alternatives you've considered**
a. Handling this within ale itself—but it looks out of scope for ale based on the issue below.
b. A separate `ale.diagnostic.level` style setting—I don't think this makes sense as you can't use both plugins to display diagnostics at the same time.

**Additional context**
https://github.com/dense-analysis/ale/issues/2610

**Comment by fannheyward** [comment]
When `displayByAle` enabled, diagnostics will be filtered by level if set.
