### ISSUE TITLE
How to install using Vundle

### ISSUE THREAD

**Issue by restagner** [neoclide/coc.nvim#1210]
I'm using Vundle package manager.  How can I install the coc plugin ?

Here's what I see

```
$ vim src/java/GetSystemProperties.java 
[coc.nvim] javascript file not found, please compile the code or use release branch.
```

**Comment by chemzqm** [comment]
We don't support it

**Comment by filbranden** [comment]
One important point to make is that Vundle hasn't been maintained in years.

Also, vim-plug is the effective successor of Vundle, it uses the same model to configure and manage plug-ins, only it's more modern, efficient and featureful.

So, by all means, **upgrade** from Vundle to vim-plug.

See [this question on Vi & Vim StackExchange](https://vi.stackexchange.com/q/22393/18609) for more context and details.
