### ISSUE TITLE
Limiting the lenght of the autocompletion suggestion list

### ISSUE THREAD

**Issue by 4vrel** [neoclide/coc.nvim#1211]
**Is your feature request related to a problem? Please describe.**

When typing a letter, the autocompletion suggestion list is so huge and take all the window height, which is anoying

**Describe the solution you'd like**
Be abble to limite the length of the autocompletion suggestion list with something like
set g:suggestion_list_max_length=5

**Comment by chemzqm** [comment]
Use `suggest.maxCompleteItemCount` in your coc-settings.json
