### ISSUE TITLE
Enoying Warning keep popping out :  "Error detected while processing CursorHold Auto commands for "*":E117: Unknown function: CocActionAsync"

### ISSUE THREAD

**Issue by 4vrel** [neoclide/coc.nvim#1215]
## versions

vim version: NVIM v0.3.1-1-g489d32f2b
node version: v10.16.0
coc.nvim version: 0.0.74-bc017b02e6
term: xterm-256color
platform: linux

## Describe the bug

When opening a README file I the following error message keep popping out in my command line: ( it doesn't happen in a java file )

`Enoying Warning keep popping out :  "Error detected while processing CursorHold Auto commands for "*":E117: Unknown function: CocActionAsync"`
`Press ENTER or type command to continue`

## Reproduce the bug

Could not make coc work with the minimal mini.vim .  I had used:
 `set runtimepath^=/home/user/.config/nvim/plugged/coc.nvim`
/path/to/coc.nvim should point to the coc.nvim folder ? or should it be a file ? in that case I only have a coc.vim file and it doesn't work neither.

## Quick fix
if I remplace README by README.md, then the bug doesn't appear anymore.

**Comment by fannheyward** [comment]
What’s your autocmd with CursorHold?
