### ISSUE TITLE
Do not trigger numberSelect when input length is zero

### ISSUE THREAD

**Issue by CantGetRight82** [neoclide/coc.nvim#1220]
**Is your feature request related to a problem? Please describe.**
When I try to write`width: 100%;` I can complete `width:` by triggering the [width [LS]] completion. At this point I would like to insert `100%` but a new completion menu already popped up, causing my 1 to trigger one of those completions.

**Describe the solution you'd like**
The test for not triggering the numberSelect:
`if (numberSelect && !/^\d/.test(option.input)) {`
might be improved by also testing for a minimum input length. The following fixes it for me:
`if (numberSelect && option.input.length && !/^\d/.test(option.input)) {`

**Describe alternatives you've considered**
No alternatives considered yet.

**Additional context**
Inserting width (by pressing 1, nice!):
<img width="474" alt="Screenshot 2019-09-27 at 06 34 12" src="https://user-images.githubusercontent.com/5507183/65743330-630dc680-e0f4-11e9-924c-076167941b7b.png">

The popup that immediately follows, preventing me from inserting 100%
<img width="461" alt="Screenshot 2019-09-27 at 06 34 16" src="https://user-images.githubusercontent.com/5507183/65743336-6acd6b00-e0f4-11e9-8c3d-56bc34df13bc.png">

**Comment by fannheyward** [comment]
The followed popup will not prevent you to insert `100%`, you can just type to insert. The new popup just shows suggested completion items that maybe you want from LS or other sources.

<img width="233" alt="image" src="https://user-images.githubusercontent.com/345274/65745268-b7816800-e12d-11e9-92b0-1482844b7ed1.png">

**Comment by CantGetRight82** [comment]
@fannheyward thank you for looking into my issue. I do think you missed out on some key information. Because of **numberSelect**, when now typing 1 it will immediately resolve to one of the completion items so in fact the new popup will prevent my from inserting 100 right away.

**Comment by CantGetRight82** [comment]
@fannheyward My proposed solution does in fact work, so I would also be willing to make a pull request out of this myself. It is just that previously I was helped very quickly and it made sense that the authors would pick this up more quickly.

**Comment by fannheyward** [comment]
@CantGetRight82 Thanks for your feedback, I missed your key problem, I reproduced your issue, and fixed it.
