### ISSUE TITLE
 When I fix the code error, the whole code will shake around.

### ISSUE THREAD

**Issue by ChenHuaYou** [neoclide/coc.nvim#1226]
## Reproduce the bug

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
Can't help without any information.

**Comment by jebae** [comment]
If your problem mean some kind of shaking window cuz code error or warning, you could add this option.

`set signcolumn=yes`

Above option will show error `>>` or warn ⚠ sign to independant column.
