### ISSUE TITLE
when i use coc in gvim 8.1 on windows 10 , it always crash, any one know what happen ?

### ISSUE THREAD

**Issue by ChenHuaYou** [neoclide/coc.nvim#1227]
## Reproduce the bug

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
Should be problem of your other extensions or your vim, it works fine on my windows10 gvim.

**Comment by ChenHuaYou** [comment]
it works fine after i reinstall the gvim
