### ISSUE TITLE
Highlight action doesn't work in vim8

### ISSUE THREAD

**Issue by michaelsuo** [neoclide/coc.nvim#123]
**To Reproduce**
```
autocmd CursorHold * silent call CocActionAsync('highlight')
```
then open some file and hold the cursor over a symbol. The following errors are printed:

```
[rpc.vim] method nvim_buf_add_highlight not supported
[coc.nvim] Error on 'highlight': nvim_buf_add_highlight: undefined
```

It looks like you're trying to call a neovim specific function. Is there a vim alternative?

I'm using MacVim 8.1.280 (distributed binary from macvim site)

**Comment by chemzqm** [comment]
>  Is there a vim alternative?

There is, vim-node-rpc module should be improved.
