### ISSUE TITLE
EACCESS Error On Autocomplete In Termux

### ISSUE THREAD

**Issue by azwalzaman** [neoclide/coc.nvim#1231]
Whenever I type the / character for my HTML I get the error:

    Error detected while processing function <lambda>3[1]..<SNR
    >41_execute:
    line    2:
    Complete file error: EACCES: permission denied, scandir '/'     

It appears to have no affect other than being a pain to work with.  I'm using Vim 8.1.

**Comment by chemzqm** [comment]
Should be problem of your other plugin.

**Comment by azwalzaman** [comment]
@chemzqm I've only installed the Coc-vim plugin and used the example configuration on the repository readme. Could it be some other configuration causing this?

**Comment by chemzqm** [comment]
Some of your vim option makes vim scan your `/` directory.

**Comment by azwalzaman** [comment]
@chemzqm Okay thanks, man! I didn't know that. I'll try changing the configuration and see if it fixes it.

**Comment by azwalzaman** [comment]
@chemzqm I couldn't fix it. I uninstalled Vim, deleted .vim directory and deleted .vimrc. Then installed vim and installed only Coc-Vim without any vim configuration. I'm still getting the same error. Is it because I'm not running a rooted device?

**Comment by chemzqm** [comment]
Can't help, please provide needed information or debug the code yourself.

**Comment by azwalzaman** [comment]
@chemzqm Just wanted to inform that I couldn't get it to work or figure out what was wrong. But it works fine in the Ubuntu PR root of Termux.
