### ISSUE TITLE
Pumblend should also affect error floating window

### ISSUE THREAD

**Issue by noomly** [neoclide/coc.nvim#1232]
I'm not sure whether this is intentional/unsupported or if it is a bug but when in neovim I use `set pumbled=20`, the completion menu is effectively semi-transparent but the floating window showing the error where the cursor is positioned isn't.

Is there a way to make it also semi-transparent? Else I think it would be worth investigating.

**Comment by chemzqm** [comment]
`pum` means popup menu, not floating window, you should checkout `:h 'winblend'` with autocmd from coc.nvim
