### ISSUE TITLE
Highlight issues if anything fails within runtimepaths.

### ISSUE THREAD

**Issue by c0r73x** [neoclide/coc.nvim#1235]
## Result from CocInfo
```
## versions

vim version: NVIM v0.5.0-111-g0c1be45ea
node version: v8.12.0
coc.nvim version: 0.0.74
term: xterm-termite
platform: linux

## Messages
Error detected while processing /home/c0r73x/.config/nvim/plugin/_pack.vim:
line  775:
E117: Unknown function: functions#getlsicons
Neotags using ptags
Switching off verbose output.
## Output channel: snippets

[Error 11:52:13 AM] Convert regex error for: li(st)? (?<num>\d+)$
[Error 11:52:13 AM] Convert regex error for: ol(st)? (?<num>\d+)$

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/c0r73x/storage/work/mailadmin
resolved root: /home/c0r73x/storage/work/mailadmin
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Output channel: highlight

[Info  - 11:52:13 AM] Highlight server running in node v8.12.0
```

## Describe the bug

If you have alot of custom stuff in your vim config and use after loading from custom runtimepaths for example and any of these functions don't return success the highlight don't seem to work and it wont give any errors.

if i check the output from the command in highlight.ts/getHighlights i can clearly see the vim errors but it won't report anywhere and since proc won't return error the "highlight error" won't show.

The  only way i've found to fix this is to change highlight.ts line 78 from  `let proc = cp.spawn(prog, ['-u', 'NORC', '-i', 'NONE', '--embed', uuid()], {` to  `let proc = cp.spawn(prog, ['-u', 'NONE', '-i', 'NONE', '--embed', uuid()], {`

However i suspect this will probably remove some syntaxes located in plugins, since it will only use the default runtimepaths.

## Reproduce the bug

I can reproduce the bug with the minimal rc provided just by placing something like this in the vimrc

```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden

let g:vimrc_variable = 1
```

then place this in for example plugin/foobar.vim

```vim
let g:othervariable = g:vimrc_variable
```

Then because of `NORC` it won't load the g:vimrc_variable.. but it will however try to load the foobar.vim file since it exists within the runtimepath.

Atleast thats how it is on my setup. Maybe i'm doing something wrong?

**Comment by chemzqm** [comment]
It's expected unless we use something for code highlighting, maybe tree-sister in the feature.

**Comment by c0r73x** [comment]
Sure, using get would work for my own stuff.. but for other plugins i would have to fork and "fix" them. Anyway I will use -u NONE for now until we get a better alternative.

**Comment by chemzqm** [comment]
It's bad design to depends on custom variable to work for a plugin, vim could provide a highlight only mode or silent ignore plugin error to avoid such kind of issue.
