### ISSUE TITLE
coc function object strange behavior in C++

### ISSUE THREAD

**Issue by j-blasco** [neoclide/coc.nvim#1238]
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 29 2019 22:27:49)
node version: v12.11.0
coc.nvim version: 0.0.74-e04013a8bd
term: dumb
platform: linux

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing /home/woowapdabug/dotfiles/vim/config.vim:
line  122:
E488: Trailing characters: l vacl<CR>
"Interpreter.cpp" 248L, 8437C
6 fewer lines
6 more lines; before #373  1 second ago
9 fewer lines
9 more lines; before #374  2 seconds ago
9 fewer lines
9 more lines; before #375  10 seconds ago
## Output channel: languageserver.clangd

I[21:28:56.305] <-- initialize(0)
I[21:28:56.306] BackgroundIndex: build symbol index periodically every 5000 ms.
I[21:28:56.306] --> reply:initialize(0) 0 ms
I[21:28:56.311] <-- initialized
I[21:28:56.311] unhandled notification initialized
I[21:28:56.316] <-- textDocument/didOpen
I[21:28:56.316] Enqueueing 32 commands for indexing
I[21:28:56.316] Updating file /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp with command [/home/woowapdabug/projects/blog/chip8/build] /usr/bin/g++ -I/home/woowapdabug/projects/blog/chip8/include -I/home/woowapdabug/projects/blog/chip8/src -g -Wall -Wextra -Wpedantic -Wfatal-errors -Werror -std=gnu++17 -o CMakeFiles/CHIP8_CORE_LIB.dir/src/Interpreter.cpp.o -c /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp -resource-dir=/usr/bin/../lib/clang/8.0.1
I[21:28:56.375] Enqueueing 32 commands for indexing
I[21:28:57.454] --> textDocument/publishDiagnostics
I[21:28:57.836] <-- textDocument/documentSymbol(1)
I[21:28:57.837] --> reply:textDocument/documentSymbol(1) 0 ms
I[21:29:00.841] <-- textDocument/documentSymbol(2)
I[21:29:00.841] --> reply:textDocument/documentSymbol(2) 0 ms
I[21:29:00.958] <-- textDocument/didChange
I[21:29:01.458] Updating file /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp with command [/home/woowapdabug/projects/blog/chip8/build] /usr/bin/g++ -I/home/woowapdabug/projects/blog/chip8/include -I/home/woowapdabug/projects/blog/chip8/src -g -Wall -Wextra -Wpedantic -Wfatal-errors -Werror -std=gnu++17 -o CMakeFiles/CHIP8_CORE_LIB.dir/src/Interpreter.cpp.o -c /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp -resource-dir=/usr/bin/../lib/clang/8.0.1
I[21:29:01.478] --> textDocument/publishDiagnostics
I[21:29:01.825] <-- textDocument/didChange
I[21:29:02.125] <-- textDocument/documentHighlight(3)
I[21:29:02.125] Updating file /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp with command [/home/woowapdabug/projects/blog/chip8/build] /usr/bin/g++ -I/home/woowapdabug/projects/blog/chip8/include -I/home/woowapdabug/projects/blog/chip8/src -g -Wall -Wextra -Wpedantic -Wfatal-errors -Werror -std=gnu++17 -o CMakeFiles/CHIP8_CORE_LIB.dir/src/Interpreter.cpp.o -c /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp -resource-dir=/usr/bin/../lib/clang/8.0.1
I[21:29:02.169] --> textDocument/publishDiagnostics
I[21:29:02.170] --> reply:textDocument/documentHighlight(3) 45 ms
I[21:29:04.134] <-- textDocument/documentSymbol(4)
I[21:29:04.135] --> reply:textDocument/documentSymbol(4) 0 ms
I[21:29:04.245] <-- textDocument/didChange
I[21:29:04.745] Updating file /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp with command [/home/woowapdabug/projects/blog/chip8/build] /usr/bin/g++ -I/home/woowapdabug/projects/blog/chip8/include -I/home/woowapdabug/projects/blog/chip8/src -g -Wall -Wextra -Wpedantic -Wfatal-errors -Werror -std=gnu++17 -o CMakeFiles/CHIP8_CORE_LIB.dir/src/Interpreter.cpp.o -c /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp -resource-dir=/usr/bin/../lib/clang/8.0.1
I[21:29:04.775] --> textDocument/publishDiagnostics
I[21:29:06.460] <-- textDocument/didChange
I[21:29:06.960] Updating file /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp with command [/home/woowapdabug/projects/blog/chip8/build] /usr/bin/g++ -I/home/woowapdabug/projects/blog/chip8/include -I/home/woowapdabug/projects/blog/chip8/src -g -Wall -Wextra -Wpedantic -Wfatal-errors -Werror -std=gnu++17 -o CMakeFiles/CHIP8_CORE_LIB.dir/src/Interpreter.cpp.o -c /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp -resource-dir=/usr/bin/../lib/clang/8.0.1
I[21:29:07.004] --> textDocument/publishDiagnostics
I[21:29:08.816] <-- textDocument/documentSymbol(5)
I[21:29:08.817] --> reply:textDocument/documentSymbol(5) 0 ms
I[21:29:08.929] <-- textDocument/didChange
I[21:29:09.430] Updating file /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp with command [/home/woowapdabug/projects/blog/chip8/build] /usr/bin/g++ -I/home/woowapdabug/projects/blog/chip8/include -I/home/woowapdabug/projects/blog/chip8/src -g -Wall -Wextra -Wpedantic -Wfatal-errors -Werror -std=gnu++17 -o CMakeFiles/CHIP8_CORE_LIB.dir/src/Interpreter.cpp.o -c /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp -resource-dir=/usr/bin/../lib/clang/8.0.1
I[21:29:09.459] --> textDocument/publishDiagnostics
I[21:29:18.737] <-- textDocument/didChange
I[21:29:19.237] Updating file /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp with command [/home/woowapdabug/projects/blog/chip8/build] /usr/bin/g++ -I/home/woowapdabug/projects/blog/chip8/include -I/home/woowapdabug/projects/blog/chip8/src -g -Wall -Wextra -Wpedantic -Wfatal-errors -Werror -std=gnu++17 -o CMakeFiles/CHIP8_CORE_LIB.dir/src/Interpreter.cpp.o -c /home/woowapdabug/projects/blog/chip8/src/Interpreter.cpp -resource-dir=/usr/bin/../lib/clang/8.0.1
I[21:29:19.282] --> textDocument/publishDiagnostics
I[21:29:27.648] <-- textDocument/documentSymbol(6)
I[21:29:27.648] --> reply:textDocument/documentSymbol(6) 0 ms

## Describe the bug

The function text object surrounds wrong text. If I do "vif" (visually select in function), this is what I get:

![Screenshot_2019-10-02_21-31-24](https://user-images.githubusercontent.com/3214400/66075534-201c7a80-e55c-11e9-8268-19bea167dec9.png)

around function doesn't work either: "vaf"
![Screenshot_2019-10-02_21-31-56](https://user-images.githubusercontent.com/3214400/66075531-1e52b700-e55c-11e9-8e86-7c38826a856f.png)

**Comment by chemzqm** [comment]
Verbose output required https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by blasco** [comment]
I'll work on the PR, but I don't think this should be closed. I agree that coc-funcobj-i might be 'working' for the case where we use this notation:
```
fun {
...
}
```
but the 'a' modifier is definitely not working, it leaves the '}' out. I'll work on it

**Comment by chemzqm** [comment]
@blasco for 'af' it uses the range from language server, so I think the server should fix this problem.

**Comment by expipiplus1** [comment]
FWIW it's also not working quite right for Haskell.

Given the code with cursor on `multi`

```haskell
foo :: Int
foo = some
        multi
        line
        function
```

`vah` gives
```haskell
foo :: Int
>foo = some
>        multi
>        line
>        function
```

`vih` gives
```haskell
foo :: Int
foo = some
>        multi
>        line
        function
```

I understand that this is not possible to solve in general, so perhaps this functionality could be optionally overridden by any extension?
