### ISSUE TITLE
Invalid literal for int() error with ccls language server

### ISSUE THREAD

**Issue by ryan91** [neoclide/coc.nvim#1240]
### Observed behavior

I'm using ccls backend and get an error message when auto-completing a struct member in a minmal example. Here's a screenshot:

![vim-coc-error](https://user-images.githubusercontent.com/5445185/66208884-7ef60700-e6b6-11e9-9cce-76ad1b83a35c.png)

I'm unsure if this is even coc's fault or something backend-related. The test c file I used is:

``` C
struct S
{
  int a;
  int b;
};

int main()
{
  struct S s;
  s.a = 42; // typing this line causes the error
}
```

The error message is:

```
Error detected while processing function <SNR>39_OnCompleteDone[5]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/nvim/runtime/python/ycm/youcompleteme.py", line 509, in OnCompleteDone
    completion_request.OnCompleteDone()
  File "/usr/share/nvim/runtime/python/ycm/client/completion_request.py", line 87, in OnComple
teDone
    self._OnCompleteDone_FixIt()
  File "/usr/share/nvim/runtime/python/ycm/client/completion_request.py", line 130, in _OnComp
leteDone_FixIt
    completions = self._GetCompletionsUserMayHaveCompleted()
  File "/usr/share/nvim/runtime/python/ycm/client/completion_request.py", line 104, in _GetCom
pletionsUserMayHaveCompleted
    return [ completions[ int( completed_item[ 'user_data' ] ) ] ]
ValueError: invalid literal for int() with base 10: '{"cid":1570191980,"source":"languageserve
r.ccls","index":0}'
```

Here's my `init.vim` (using vim plug)

``` vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

and my coc settings:

``` json
{
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "cuda", "objc", "objcpp"],
      "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
      "initializationOptions": {
         "cache": {
           "directory": ".ccls-cache"
         }
       }
    }
  }
}

```

### Steps to reproduce
Initialize an empty git repository anywhere and copy the c code from the example above, go into the main function and type (after `s` has been defined) `s.` where the popup menu correctly appears suggesting `a` and `b`. Now use `<tab>` to select any member, it works with both. Now press `<space>` and the error message should appear. **Note that if I type anything else, no error message appears**.

### Setup

* ccls version 0.20190823.3-2-g4711fd36
* clang version: 8.0.1
* OS: Manjaro
* Neovim version: NVIM v0.3.8

**Comment by chemzqm** [comment]
It's error from youcompleteme.

**Comment by ryan91** [comment]
Oh God, it even says ycm in the error message I'm so sorry.
