### ISSUE TITLE
Disable completion of arbitrary words

### ISSUE THREAD

**Issue by philippludwig** [neoclide/coc.nvim#1242]
**Is your feature request related to a problem? Please describe.**
I find it annoying when CoC opens the menu for completing „normal” words; e.g. if I type „a“ in a comment, it suggests „app”, „assets“, „article“, etc. I only want language-specific suggestions - for example, variables of the current class.

**Describe the solution you'd like**
I would like a setting to disable this „general” completion. I could not find any in the documentation.

**Additional context**
Screenshot of the problem:
![image](https://user-images.githubusercontent.com/3770792/66240749-d370a500-e6fd-11e9-986a-c2666f827ec2.png)

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#configuring-sources
