### ISSUE TITLE
Request for callbacks of CocActionAsync/CocRequestAsync be called with application specific options passed by caller

### ISSUE THREAD

**Issue by sch0125** [neoclide/coc.nvim#1245]
**Is your feature request related to a problem? Please describe.**

It take longer time to complete some LSP requests like `documentSymbol` occasionally. When the time consuming callback is invoked, the request may already be outdated. 
There is no way to check whether the data returning from the callback is what we want or not.

**Describe the solution you'd like**

Callbacks are called with options which were passed as arguments of CocActionAsync/CocRequestAsync.
With this change we can do something like this:

```vim
  let options = {'path': expand('%:p')}
  call CocActionAsync('documentSymbols', function('s:cb'), options)
```
```vim
  function! s:cb(error, response, options)
    ...
    if a:options.path != expand('%:p')
      echom 'outdated'
      return
    endif
    ...
  endfunction
```

**Comment by chemzqm** [comment]
Use b:changedtick

**Comment by sch0125** [comment]
Consider a case:
  1. A large file size `buffer a` issues CocActionAsync
  2. Switch to `buffer b` with small file size and **without modifying** the content of `buffer a`
  3. `Buffer b` issues CocActionAsync
  4. Callback of caller `buffer b` is back
  5. Callback of caller `buffer a` is back

We already in `buffer b`, however, the information we are interested will be overwritten by those of `buffer a`. `b:changedtick` is useless here.

**Comment by chemzqm** [comment]
So you need to current bufnr for correct result

**Comment by sch0125** [comment]
Yes, if bufnr was either passed by the caller or recorded by coc, the number can be compared with current bufnr in the callback.
Once those two bufnr are different in the callback, following actions can be skipped.

**Comment by chemzqm** [comment]
You can make use of vim's closure function for it
