### ISSUE TITLE
Goto Definition in Vsplit?

### ISSUE THREAD

**Issue by andyl** [neoclide/coc.nvim#1249]
How would I "Goto Definition" in a separate tab?  Here's my `.vimrc` config:
```vim
nmap <silent> \ge <Plug>(coc-definition)
nmap <silent> \gs :split<CR><Plug>(coc-definition)
nmap <silent> \gv :vsplit<CR><Plug>(coc-definition)
nmap <silent> \gt :tabnew<CR><Plug>(coc-definition)
```
The first three options work, (`open`, `open in split`, `open in vsplit`) but not the last.

I see that there is a Config setting ("coc.preferences.jumpCommand") but am hoping there is a way set a keybinding in my `vimrc`.  

Any ideas?

**Comment by andyl** [comment]
OK this seems to work:

```vim
nmap <silent> \ge <Plug>(coc-definition)
nmap <silent> \gs :sp<CR><Plug>(coc-definition)
nmap <silent> \gv :vsp<CR><Plug>(coc-definition)
nmap <silent> \gt :vsp<CR><Plug>(coc-definition)<C-W>T
```

**Comment by chemzqm** [comment]
`:h coc-action-jumpDefinition`

**Comment by andyl** [comment]
@chemzqm thanks for the hint.  I read the docco and unfortunately I'm too dumb to figure out the exact syntax to get it working.  If you spell it out here for me, I'll test it and then send you a PR to add some examples to your docs.

**Comment by rafa-acioly** [comment]
I've tried:

```
nmap <silent> gd <Plug>(coc-action-jumpDefinition)
```
but it does not work, how can i set the "jumpDefinition"  to open on a new "vsplit"?

**Comment by chemzqm** [comment]
@rafa-acioly you need to understand function and key-mapping of vim.

**Comment by befedo** [comment]
Hey @rafa-acioly,

take a look at `:help n_coc-definition@en` I think that's what you are looking for.

**Comment by Mentioum** [comment]
> @rafa-acioly you need to understand function and key-mapping of vim.

[one of many good example url guides](https://medium.com/vim-drops/understand-vim-mappings-and-create-your-own-shortcuts-f52ee4a6b8ed)

**Comment by mitzukodavis** [comment]
> @rafa-acioly you need to understand function and key-mapping of vim.

what is the best video to learn that

**Comment by vrkansagara** [comment]
> @chemzqm thanks for the hint. Here's the syntax that worked for me:
> 
> ```
> :call CocAction('jumpDefinition', 'split')
> :call CocAction('jumpDefinition', 'vsplit')
> :call CocAction('jumpDefinition', 'tabe')
> ```

this is perfectly work for me. thanks
