### ISSUE TITLE
Auto close the Document window when cursor move

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc.nvim#125]
**Is your feature request related to a problem? Please describe.**

When I hover a tag with `gh`, a window appears at the bottom and I have to move the cursor to that window to close it `:close`.

Is there anyway to auto close the preview window when the cursor move?

**Describe the solution you'd like**

I would like when I hover with `gh`, the preview window will be auto closed after a move the cursor off the tag

**Describe alternatives you've considered**

**Additional context**

**Comment by sandangel** [comment]
I think it would be great if the preview window auto close when the cursor move out of the tag.

**Comment by prabirshrestha** [comment]
You can also use default vim mapping to close preview window <c-w><c-z>

**Comment by chemzqm** [comment]
It would be better if you can get the documention by mouse hover, but neovim doesn't support `balloonevalterm`.
You can create CursorMove autocmd for that purpose,  I will consider auto close document window when I got floating window feature works.

**Comment by sandangel** [comment]
So should I leave this issue open until that feature is implemented?
And could you help me with that CursorMoved autocmd? I don't know much about vim script. I did some researchs and look like there will be some performance drop if I do it incorrectly.

http://vim.wikia.com/wiki/Prevent_frequent_commands_from_slowing_things_down

**Comment by chemzqm** [comment]
> So should I leave this issue open until that feature is implemented?

What ever you like.

``` vim
autocmd CursorMoved * if &previewwindow != 1 | pclose | endif
```
It's simple so would not slow your vim.
But it's not working right now, I need to change my vim function to use `pedit` command to prevent addtional CursorMove event, should works on next release.

**Comment by sandangel** [comment]
@chemzqm is it working now? I saw some several releases.

**Comment by chemzqm** [comment]
No, the CursorMoved event always fired after open preview window, I think you can just wait for floating window feature for hover document, or try something else.

**Comment by chemzqm** [comment]
Support for echo hover message is added, add `"coc.preferences.hoverTarget": "echo"` to your `coc-settings.json`, there's no language syntax highlight for echo messages, but it doesn't have close problem.
