### ISSUE TITLE
Showing Number of References for a Function via Virtual Text

### ISSUE THREAD

**Issue by theniceboy** [neoclide/coc.nvim#1250]
**Is your feature request related to a problem? Please describe.**
Is there a coc plugin that displays the number of references of a function via Neovim's Virtual Text feature?

**Describe the solution you'd like**
Something like this:
![img](https://social.msdn.microsoft.com/Forums/getfile/700392)

**Describe alternatives you've considered**
I would assume coc already has this information stored somewhere, and if not, coc is probably the best platform to accomplish this.

**Comment by reergymerej** [comment]
I accidentally turned this on and it drove me crazy.  Here it is.

```
:CocConfig

codeLens.enable: true|false

:CocRestart
```
