### ISSUE TITLE
CocList -I symbols does't work

### ISSUE THREAD

**Issue by aigo-tech** [neoclide/coc.nvim#1252]
```
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod"],
      "filetypes": ["go"]
    }
  }
```
It doesn't works, when configuration is set as above

```
 "languageserver": {
    "golang": {
      "command": "go-langserver",
      "filetypes": ["go"],
      "initializationOptions": {
        "gocodeCompletionEnabled": true,
        "diagnosticsEnabled": true,
        "lintTool": "golint"
      }
    }
  }
```
It  works, when configuration is set as above

I am not sure whether it's a gopls issue or coc issue
## versions

vim version: nvim v0.4.2
node version: v12.9.0
coc.nvim version: 0.0.74-a84f813105
term: iterm.app
platform: darwin

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by aigo-tech** [comment]
I can't find any request like 'textDocument/documentSymbol'.
In vim, just show as below
![image](https://user-images.githubusercontent.com/53333866/66469813-2a3dfc00-eabb-11e9-9342-baca13234705.png)

**Comment by fannheyward** [comment]
gopls did not support `workspace/symbol` yet. https://github.com/golang/tools/blob/master/internal/lsp/server.go#L124

**Comment by aigo-tech** [comment]
> gopls did not support `workspace/symbol` yet. https://github.com/golang/tools/blob/master/internal/lsp/server.go#L124

Hum, Thanks. So awkward, I also found this reason just now. At present, document symbol is supported by [gopls](https://github.com/golang/tools/blob/master/gopls/doc/status.md) , but document/workspace symbol both are supported by[ go-language](https://github.com/sourcegraph/go-langserver)
