### ISSUE TITLE
Issue with reviving saved sessions remapping special characters to 00's with an error

### ISSUE THREAD

**Issue by Teknitix** [neoclide/coc.nvim#1259]
This is not a performance issue, related to a language server, or a general question.

## Result from CocInfo
I don't want to give the entire contents of CocInfo for privacy's sake but it seems as though the contents may be irrelevant. I just see hundreds of lines about CRLF to LF conversions in the git directory and some errors with the bash language server and vimlsp.

## Describe the bug

I have a problem where if I save a session with the Startify plugin, then open that session, when I go to edit a file, I can enter text in Insert mode but when it comes to many right-keyboard-sided special characters, they put 0 into the buffer (i.e., typing [[[ or ]]] inserts 000 into the file in insert mode instead) and an error message pops up in my statusline: `Error on request (doKeymap): undefined is not iterable  (cannot read property Symbol(Symbol.iterator))`. This occurs in files edited for many types of programming languages.

I thought it may be something related to how sessions are saved in Vim and I traced the problem to the following types of lines in the session.vim file: `inoremap <silent> <expr> " coc#_insert_key('request', '097df6sdaf20dfd-dfedff8ca-1dsf1e9-bd9sdf44-fbdsd5f7f7ssc06ddsa2ff7')`

I did add more  coc extensions recently so I'm not sure if this is related to a particular extension. The main ones I added were coc-snippets and coc-pairs.

## Reproduce the bug
The active extensions are:
  ```vim
coc-vimlsp
coc-pairs
coc-snippets
coc-eslint
coc-git
coc-emoji
coc-lists
coc-json
  ```
Remapping some characters like with `imap ] ]` and `imap " "` does fix the problem, but having to do this every time I reopen a new session would be far too intrusive on usability.
I can provide more details if necessary. Is this a known issue? How can I resolve this? Any help is appreciated, thank you!

**Comment by Teknitix** [comment]
I figured out that by setting the following setting to false: `"coc.preferences.formatOnType": false,` ...the problem appears to go away. I tried the debugging wiki but nothing was indicated as being the direct problem. I'm not sure how to come up with a mini.vim to reproduce the problem. However, here are my installed extensions in the mini.vim file I did try: `exe 'normal :CocInstall coc-rust-analyzer coc-rls coc-go coc-solargraph coc-vimlsp coc-vimtex coc-json coc-tsserver coc-eslint coc-emmet coc-prettier coc-html coc-css coc-angular coc-vetur coc-ember coc-java coc-python coc-yaml coc-highlight coc-git coc-snippets coc-pairs coc-lists <CR>'`
I don't know how to get this setting to work properly.

**Comment by Teknitix** [comment]
I was wrong and the problem still persists and I do not yet have a solution.

**Comment by chemzqm** [comment]
You should make your sessionoption not include temporary keymap

**Comment by Teknitix** [comment]
How do I do this, @chemzqm ? When I put `set sessionoptions-=options` in my vimrc the error is still there when I save a session using Startify.
