### ISSUE TITLE
Completing suggestions stops at first space

### ISSUE THREAD

**Issue by wsistyrud** [neoclide/coc.nvim#1260]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
node version: v11.14.0
coc.nvim version: 0.0.74-e04013a8bd
term: dumb
platform: linux

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
```

## Describe the bug
Suggestions with multiple words separated by space only completes the current word.

## Reproduce the bug
Install the tabnine extension, start writing lorem ipsum dol and autocomplete using tab. It will show the whole sentence but only complete the current word.

## mini.vim
  ```vim
  set nocompatible
  set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ coc#refresh()
  inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

  ```

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/25362524/66637837-2671bd00-ec14-11e9-8568-c64f8612ee55.png)

**Comment by wsistyrud** [comment]
Ok, is it possible to add the whole suggestion? Without being able to add it all, I see no reason to even suggest the complete sentence.

**Comment by chemzqm** [comment]
it's suggested by your tabnine, you can just confirm completion by `<C-y>`.
