### ISSUE TITLE
Open location in another open window

### ISSUE THREAD

**Issue by btolsch** [neoclide/coc.nvim#1265]
**Is your feature request related to a problem? Please describe.**
I often want to jump to definition or type-definition when working on related code, but the default behavior uses the current window, which takes me away from what I was working on.  I can then use <c-o>/<c-i> to go back and forth, or open what I was working on in a different window.  However, it would me much easier if the jump could just happen into another window to begin with.  I don't want to use 'drop' because if the definition is in the same file, it won't switch windows, and I don't want to use 'split' or 'tab' because I want to keep my existing window layout.

**Describe the solution you'd like**
I would either like another location action, possibly 'previous', that would switch to the previous window (e.g. wincmd p).  I'd also be okay with getting this to work via the existing callback in CocActionAsync (but adding a function that basically did 'wincmd p' didn't work).

**Describe alternatives you've considered**
I tried adding a callback (e.g. CocActionAsync('jumpDefinition', '', function('SwitchWin')) that basically executed 'wincmd p', but the jump still happened in the first window (and moreover, the window didn't switch at all).

**Additional context**
n/a

**Comment by chemzqm** [comment]
You can create your own command and then just configure workspace.jumpCommand settings to use it.

**Comment by unphased** [comment]
@btolsch hopping back is just built-in vim ctrl+o. 

@chemzqm I'd like to know if it is possible to define two keybinds. One to open the definition in the current window, and one to open the definition in a split (and maybe a third one to open it in a vertical split).

Currently all of the suggestions I have seen involve jumpCommand which is *global* and not useful to me. Either all the jumps are going to generate splits or none of them will...

**Comment by chemzqm** [comment]
Checkout `:h coc-action-jumpDefinition` and others, it's your configuration issue.
