### ISSUE TITLE
Cleanup syntax highlighting on :CocDisable / :CocRestart

### ISSUE THREAD

**Issue by r-bar** [neoclide/coc.nvim#1268]
**Is your feature request related to a problem? Please describe.**
Sometimes a language server can end up with a corrupted view of the world, causing them to highlight large sections of documents with nonsensical errors.

**Describe the solution you'd like**
When attempting to deal with these errors I will try to invoke `:CocDisable` or `:CocRestart`. These commands will clear the gutter marks, but will leave the error syntax highlighting in place. It would be helpful if these commands could cleanup Coc's syntax highlighting when they are run.

**Describe alternatives you've considered**
Alternatively provide a seperate command or function to clear all Coc highlighting.

**Additional context**
None

**Comment by chemzqm** [comment]
You can just use `clearmatches()` and `nvim_buf_clear_namespace(bufnr('%'), -1, 0, -1)` to clear all highlights added by plugins.
