### ISSUE TITLE
how to move the floating window

### ISSUE THREAD

**Issue by wuchujiecode** [neoclide/coc.nvim#1269]
floating window hide my code
![1](https://user-images.githubusercontent.com/12055501/66811021-f05d7180-ef62-11e9-917b-efdaa0936ec8.jpg)
![2](https://user-images.githubusercontent.com/12055501/66811031-f6ebe900-ef62-11e9-9b07-79590b9dbe38.jpg)

**Comment by chemzqm** [comment]
`:h nvim_win_set_config()`

**Comment by wuchujiecode** [comment]
@chemzqm  我看了 doc 和readme.md 文档好像没有针对这个浮动窗口移动到上下左右  的设置。能请教一下吗

**Comment by wuchujiecode** [comment]
@chemzqm  现在情况就是浮动窗口遮住了我的 ()  里面输入的东西

**Comment by chemzqm** [comment]
可能是旧版 bug，我这里无法重现

**Comment by wuchujiecode** [comment]
@chemzqm 我现在nvim是 
VIM v0.4.2
Build type: Release
LuaJIT 2.0.5

- repo: neoclide/coc.nvim
  merge: 0 
  rev: release

**Comment by wuchujiecode** [comment]
@chemzqm  我是在golang 上面出现这种情况。。不管是自己的函数 还是系统函数都出现 浮动窗口 遮住了  ("xx", "xx")  这个括号。。

**Comment by MaxJohnXiang** [comment]
same problem , when i edit go files .
![image](https://user-images.githubusercontent.com/24894004/69950394-4778cf00-152e-11ea-8f1a-a96bb85ef1d6.png)

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/F.A.Q 可以先不使用 floating 窗口
