### ISSUE TITLE
Support null as version of VersionedTextDocumentIdentifier

### ISSUE THREAD

**Issue by janstrohbeck** [neoclide/coc.nvim#127]
**Describe the bug**
If I trigger renaming a C++ class (with the cquery language server) using <Plug>(coc-rename) mapped to a key, I get the following error message:

```ts
[coc.nvim] document change {"textDocument":{"uri":"file:///home/user/workspace/src/testproject/include/source_file_2.h"},"edits":[{"range":{"start":{"line":122,"character":32},"end":{"line":122,"character":57}},"newText":"SomeOtherClass"}]} not supported
```

As far as I inspected the source code, this change does not validate as a TextDocumentEdit because the `version` is missing. Even after I tried to set the version to `null` in `src/workspace.ts` using
```ts
if (change.textDocument && change.textDocument.version === undefined) {
  change.textDocument.version = null
}
```
it complained that it could not find some files which I didn't already have opened in neovim, because `getDocument` only searches for already open buffers and does not open the missing files. 

**To Reproduce**
1. Setup cquery integration
2. Define a C++ Class in a file and use it in multiple files.
3. Open only the header file of the class and trigger a rename on the class name.

**Expected behavior**
Coc should execute the text changes across all relevant files and open these files in the editor if they have not been opened yet. At least that's what LanguageClient-neovim does.

**Screenshots**

**Desktop (please complete the following information):**
 - Terminal: xfce4-terminal
 - Version: neovim: 0.3.1, Coc: Commit be22999

**Additional context**

**Comment by chemzqm** [comment]
Will be fixed in next release.
