### ISSUE TITLE
Enable whole line completion

### ISSUE THREAD

**Issue by purushnayak** [neoclide/coc.nvim#1271]
**Is your feature request related to a problem? Please describe.**
After a long time (n)vim has a decent comprehensive completion solution. Thanks for this.

The completion popup lists word completions as you type and inserts them if selected. But in order to get the whole line completions I still need to use CTRL-X CTRL-L. 

Example:

import { TestModule } from './test-module';

When you start typing "Test" it should show the full line just like it happens when we use CTRL-X CTRL-L.

**Describe the solution you'd like**
There should be an option so that the completion popup shows/inserts whole lines.

**Describe alternatives you've considered**
For now I am just using CTRL-X CTRL-L. 

**Additional context**

**Comment by chemzqm** [comment]
No

**Comment by chemzqm** [comment]
You should use auto import feature provided by coc-tsserver

**Comment by purushnayak** [comment]
This doesn't apply just to imports, that was just an example. It applies to everything. E.g. HTML tags.

Its a very useful feature, not sure why it closed without some more responses from others.

**Comment by chemzqm** [comment]
My suggestion is just use CTRL-X CTRL-L or something smarter like tabnine.

**Comment by oblitum** [comment]
I also think this is something for [coc-sources](https://github.com/neoclide/coc-sources).

**Comment by fannheyward** [comment]
Checkout https://www.npmjs.com/package/coc-lines, I'm working on this, and feedback is welcome.
