### ISSUE TITLE
Option for disabling suggest snippets?

### ISSUE THREAD

**Issue by fsouza** [neoclide/coc.nvim#1275]
Hello hello, thanks for building coc.nvim. It's really great! :D

**Is your feature request related to a problem? Please describe.**

I'm slightly annoyed by completion snippets and would like an option to disable them (something similar to [LanguageClient-neovim's hasSnippetSupport](https://github.com/autozimu/LanguageClient-neovim/blob/0f4a1fcae7faacec1c7438c48b22645f2fd88369/doc/LanguageClient.txt#L274-L284))

**Describe the solution you'd like**

Some sort of global setting for disabling snippets on suggest.

**Describe alternatives you've considered**

Working with language server authors to provide a similar option on their side.

**Additional context**

If you agree that this is a feasible option, I can send a PR.

**Comment by chemzqm** [comment]
No, because it's useful.

**Comment by fsouza** [comment]
@chemzqm no problem, thanks for the quick response! 😁
