### ISSUE TITLE
CocList commands does not advertise the server commands specified in capabilities.executeCommandProvider.commands

### ISSUE THREAD

**Issue by expipiplus1** [neoclide/coc.nvim#1277]
<details>
  <summary>Result from :CocInfo</summary>

```
## versions

vim version: NVIM v0.4.2
node version: v10.16.3
coc.nvim version: 0.0.74-bc017b02e6
term: screen-256color
platform: linux

## Messages
"src/Foo.hs" 6L, 53C

"src/Foo.hs" line 6 of 6 --100%-- col 9
[coc.nvim] 1 buffers changed.
2 changes; before #9  2 seconds ago
## Output channel: languageserver.haskell

Using hie version: Version 1.0.0.0 x86_64 ghc-8.6.5
Loaded package environment from /home/j/projects/coc-test/.ghc.environment.x86_64-linux-8.6.5
Using hoogle db at: /nix/store/hj4i85wq2ffiapb3f15qwbf4mwryx5rc-hoogle-local-0.1/share/doc/hoogle/default.hoo
Loaded package environment from /home/j/projects/coc-test/.ghc.environment.x86_64-linux-8.6.5
```
</details>

## Describe the bug

`CocList commands` does not advertise the server commands specified in
`capabilities.executeCommandProvider.commands`.

This seems related to https://github.com/neoclide/coc.nvim/issues/351, although in this case the list of commands is being sent to coc in the server capabilities response.

<details>
  <summary>The server initialization response.</summary>

  ```json
  {
    "result": {
      "capabilities": {
        "typeDefinitionProvider": true,
        "textDocumentSync": {
          "openClose": true,
          "change": 2,
          "willSave": false,
          "willSaveWaitUntil": false,
          "save": {
            "includeText": false
          }
        },
        "workspace": {},
        "documentRangeFormattingProvider": true,
        "documentHighlightProvider": true,
        "executeCommandProvider": {
          "commands": [
            "10239:applyrefact:applyOne",
            "10239:applyrefact:applyAll",
            "10239:applyrefact:lint",
            "10239:base:version",
            "10239:base:plugins",
            "10239:base:commands",
            "10239:base:commandDetail",
            "10239:bios:check",
            "10239:build:prepare",
            "10239:build:isConfigured",
            "10239:build:configure",
            "10239:build:listTargets",
            "10239:build:listFlags",
            "10239:build:buildDirectory",
            "10239:build:buildTarget",
            "10239:generic:type",
            "10239:hare:demote",
            "10239:hare:dupdef",
            "10239:hare:iftocase",
            "10239:hare:liftonelevel",
            "10239:hare:lifttotoplevel",
            "10239:hare:rename",
            "10239:hare:deletedef",
            "10239:hare:genapplicative",
            "10239:hoogle:info",
            "10239:hoogle:lookup",
            "10239:hsimport:import",
            "10239:liquid:sayHello",
            "10239:liquid:sayHelloTo",
            "10239:package:add",
            "10239:pragmas:addPragma"
          ]
        },
        "definitionProvider": true,
        "hoverProvider": true,
        "completionProvider": {
          "triggerCharacters": [
            "."
          ],
          "resolveProvider": true
        },
        "documentSymbolProvider": true,
        "documentFormattingProvider": true,
        "referencesProvider": true
      }
    },
    "jsonrpc": "2.0",
    "id": 0
  }
  ```
</details>

## Reproduce the bug

To reproduce:

- I'm using haskell-ide-extension from the `hie-bios` branch, although I do not believe that this is specific to a single language server.
- Observe that the command `10239:applyrefact:applyAll` is present in `capabilities.executeCommandProvider.commands`
	- I looked in the languageserver log for this
- Observe that this command is not present in the output of `CocList commands`
- Observe that this command does indeed work: `:CocCommand 10239:applyrefact:applyAll file:///home/j/projects/coc-test/src/Foo.hs 1 1`
- Observe that coc is aware of specific command names by unsuccessfully trying an invalid name: `:CocCommand badCommandName file:///home/j/projects/coc-test/src/Foo.hs 1 1`

I would expect to see all the advertised server commands to be present in `CocList commands`

<details>
  <summary>vimrc</summary>

  ```vim
  set nocompatible
	" Just coc-nvim in here
  set packpath-=~/.vim/after
  set packpath+=/nix/store/y8fi4yy0vgg209vxzwjcb8lv0f5vjr2q-vim-pack-dir
  set packpath+=~/.vim/after

  filetype indent plugin on | syn on
  ```
</details>

<details>
  <summary>coc-setting.json</summary>

  ```json
	{
		"languageserver": {
			"haskell": {
				"args": [ "--vomit", "-l", "hie-log", "-d" ],
				"command": "hie-wrapper",
				"filetypes": [ "hs", "lhs", "haskell" ],
				"initializationOptions": {
					"languageServerHaskell": {}
				},
				"requireRootPattern": true,
				"rootPatterns": [ "hie.yaml" ]
			}
		}
	}
  ```
</details>

<details>
  <summary>The contents of the coc-test directory</summary>

  - `hie.yaml`
  ```yaml
  cradle:
    direct:
      arguments: []
  ```

  - `src/Foo.hs`
  ```haskell
  module Foo
    where
  -- redundant brackets to be removed with applyrefact.applyAll
  bar = (1)
  foo = (2)
  ```
</details>

**Comment by chemzqm** [comment]
It can't, coc extension needed.

**Comment by expipiplus1** [comment]
I see, thanks.

Is it possible to at least make this list available through a vimscript command?

**Comment by chemzqm** [comment]
Sure, checkout `:h coc#add_command()` and `:h coc-action-runCommand`

**Comment by expipiplus1** [comment]
ah, sorry. I meant, is it possible to view the list returned in capabilities in vimscript:

To explain my motivation a bit, the haskell-ide-engine plugin prefixes the commands with its pid, which makes them difficult to track down!

The only way I have to do this is to turn on h-i-e's debug logging and look at the command names in the capabilities object. 

It would be convenient to be able to query this list of commands via coc, and then add the appropriate ones with `coc#add_coammand()`

**Comment by chemzqm** [comment]
It's not possible, the only way is use coc extension.

**Comment by expipiplus1** [comment]
OK, thanks for the quick reply.
