### ISSUE TITLE
File change prompt is show when applying codeaction to current file

### ISSUE THREAD

**Issue by peterhorne** [neoclide/coc.nvim#128]
**Describe the bug**
When applying a codeaction to the current file (e.g. "add missing imports") the user is:
1. Prompted if they wish to make the change
2. Have to `:edit` the file to see the changes

**To Reproduce**
1. Open a file
2. Trigger `coc-codeaction`
3. Select an option that only modifies the current file, e.g. "add missing import"

**Expected behavior**
1. The prompt should not be displayed as it is only the current file that will be affected
2. The changes should be applied to the buffer, rather than written to the file on disk. The user shouldn't need to `:edit` to pick up the change.

**Desktop (please complete the following information):**
 - Terminal: iTerm2 3.2.4beta3
 - Version: v0.0.27

**Comment by chemzqm** [comment]
I need your file path and the language server information, it works as expected on my mac.

**Comment by chemzqm** [comment]
The output from the server would be very much helpful, follow: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel to get the output.

**Comment by peterhorne** [comment]
Sorry for the noise. This turned out to be an issue with fsevents being corrupted.
