### ISSUE TITLE
Move cursor inside floating window

### ISSUE THREAD

**Issue by shinzui** [neoclide/coc.nvim#1281]
**Is your feature request related to a problem? Please describe.**

I currently use the below mapping to scroll inside the floating window, but I feel like the experience is clunky. 

```
nnoremap <expr><C-f> coc#util#has_float() ? coc#util#float_scroll(1) : "\<C-f>"
nnoremap <expr><C-b> coc#util#has_float() ? coc#util#float_scroll(0) : "\<C-b>"
```

**Describe the solution you'd like**

I would like to have the same behavior as [git-messenger](https://github.com/rhysd/git-messenger.vim), where I can focus the floating window and use standard vim navigation commands inside the floating window.

**Comment by monkoose** [comment]
`<Plug>coc-float-jump`

**Comment by chemzqm** [comment]
You can use wincmd api

**Comment by pappasam** [comment]
Current answer: `<C-w><C-p>`. Gets you in and out. And, as far as I know, undocumented.

**Comment by chemzqm** [comment]
There is coc-float-jump provided

**Comment by oblitum** [comment]
There's insert mode scroll now, which should be better anyway than moving inside the floating window for that.

**Comment by shinzui** [comment]
@oblitum can you please elaborate?

**Comment by oblitum** [comment]
@shinzui update to latest and check `:h coc#float#has_scroll()`. Follow PR #2532 if visual mode scroll is also needed.

**Comment by andrevmatos** [comment]
This isn't working for me, even remapping `<C-w><C-p>` explicitly to `<Plug>(coc-float-jump)`. Neovim 0.5 and nightly, latest coc release.
Does anyone have a working map?

**Comment by antonmry** [comment]
This worked well for me:

```
function! s:GotoFirstFloat() abort
  for w in range(1, winnr('$'))
    let c = nvim_win_get_config(win_getid(w))
    if c.focusable && !empty(c.relative)
      execute w . 'wincmd w'
    endif
  endfor
endfunction
noremap <c-w><space> :<c-u>call <sid>GotoFirstFloat()<cr>
```

**Comment by Oleh-Rudko** [comment]
After the popup is opened I can use this
`<C-w><C-w>`
