### ISSUE TITLE
Snippet engine not working with UltiSnips

### ISSUE THREAD

**Issue by blasco** [neoclide/coc.nvim#1283]
I've installed the snippet library from:
https://github.com/honza/vim-snippets

This is what I get for the UltiSnip snippet:

![Screenshot_2019-10-19_20-44-53](https://user-images.githubusercontent.com/3214400/67149918-840ba680-f2b1-11e9-9247-96b078709694.png)

Which expands into the wrong snippet:
![Screenshot_2019-10-19_20-45-15](https://user-images.githubusercontent.com/3214400/67149920-8968f100-f2b1-11e9-9bb9-2c0643850e06.png)

Is this a known issue? If I inspect the snippet with `:CocList snippets` they look correct:

```
snippet def "function with docstrings" b
def ${1:function}(`!p
if snip.indent:
	snip.rv = 'self' + (", " if len(t[2]) else "")`${2:arg1}):
	`!p snip.rv = triple_quotes(snip)`${4:TODO: Docstring for $1.}`!p
write_function_docstring(t, snip) `
	${5:${VISUAL:pass}}
endsnippet
```

**Comment by chemzqm** [comment]
Can't understand

**Comment by blasco** [comment]
The problem is that I have snippets that expand correctly when using UltiSnips, such as the one mentioned: 
```
snippet def "function with docstrings" b
def ${1:function}(`!p
if snip.indent:
	snip.rv = 'self' + (", " if len(t[2]) else "")`${2:arg1}):
	`!p snip.rv = triple_quotes(snip)`${4:TODO: Docstring for $1.}`!p
write_function_docstring(t, snip) `
	${5:${VISUAL:pass}}
endsnippet
```

But with coc they expand to: 
![Screenshot_2019-10-19_20-45-15](https://user-images.githubusercontent.com/3214400/67155481-d203c700-f310-11e9-8296-b903bfccd017.png)

That's the expansion, I haven't written anything. As you can see there are some weird `0` characters.

**Comment by chemzqm** [comment]
I can't reproduce, CocInfo and minimal vimrc required

**Comment by monkoose** [comment]
In the first message there is the same line for `def` snippet you can even see it in the float window, and in the second screenshot it expanded into the same snippet? No?

**Comment by blasco** [comment]
Yes, and both the snippet in the floating window and the expanded snippets are wrong. There is no `0` character in the snippet. With UltiSnips they expand correctly but with coc it seems it cannot understand them and puts for some unknown reason a 0 as you can see (`0ar1` and `0TODO`)

This is the snippet, which works in other engines:

```
snippet def "function with docstrings" b
def ${1:function}(`!p
if snip.indent:
	snip.rv = 'self' + (", " if len(t[2]) else "")`${2:arg1}):
	`!p snip.rv = triple_quotes(snip)`${4:TODO: Docstring for $1.}`!p
write_function_docstring(t, snip) `
	${5:${VISUAL:pass}}
endsnippet
```

**Comment by blasco** [comment]
The filetype needs to be python, and you need to have 'https://github.com/honza/vim-snippets'. The snippet is triggered with `def`

**Comment by chemzqm** [comment]
Can't reproduce, CocInfo and minimal vimrc required

**Comment by monkoose** [comment]
Works fine for me.
![1](https://i.imgur.com/63Ynt1u.png)
![2](https://i.imgur.com/5fqOr5o.png)

**Comment by blasco** [comment]
Found the culprit. This plugin causes that, no clue why:

https://github.com/gu-fan/colorv.vim

It's a really cool plugin, no clue what might be causing the problem. Also, I've noticed that now works, but the engine doesn't update the expansion as it happens with ultisnips (if you give a name to `arg1` the `:param arg1` should update to the new name. Does this also work for you? @monkoose 

An unrelated question, why do you have syntax highlight in the preview window? That also doesn't happen in my configuration. Thank you for the help.

**Comment by monkoose** [comment]
This colorv plugin highly use <Tab> so i guess it is a problem.
And yes seems like changing arg1 doesn't change `:param arg1`. Do not use python lately, but i remember before my switch to `CoC` that it was working fine, and when you adds new arguments it should create new doc line like `:param arg2: TODO` etc.

**Comment by blasco** [comment]
I've noticed that it does change the function name in the docstring too, quite weird. I got the syntax highlighting in the preview box by the way, switching to neovim solved the issue.

**Comment by oblitum** [comment]
> An unrelated question, why do you have syntax highlight in the preview window? That also doesn't happen in my configuration.

It's possible you're using Vim, highlighting on floating windows are only supported on NeoVim.

We can't know that's the reason because you didn't fill the issue template, that asks for Vim/NeoVim version, and also for a minimum reproducible `.vimrc`, which if produced, could have been use to find your issue in the first place.

Please try to fill issue template next time.

**Comment by monkoose** [comment]
Ok found a workaround. You should expand snippet with Ultisnips map for expanding a snippet and then use ultisnippet map to jump to the next location in the snippet, not `coc`s. Seems like `coc` impementation doesn't respect ultisnips jumps.

**Comment by oblitum** [comment]
I prefer coc-snippets as it supports nested snippet placeholder jumps and cycling.

**Comment by monkoose** [comment]
@oblitum You don't use ultisnips at all? Are VSCode snippets enough? Never tested `coc-snippets` without `UltiSnips`. What about multifile snippets like `date`, `time` etc?

**Comment by oblitum** [comment]
@monkoose I do still use ultisnip snippets, but not UltiSnips or coc-ultisnips. You don't need UltiSnips installed with coc-snippets, the only downside is that coc-snippets won't support all UltiSnips features. Another bad aspect of UltiSnips is that it takes reasonable startup time, while coc-snippets takes nothing.

**Comment by oblitum** [comment]
`date`, `time`, etc work fine.

**Comment by monkoose** [comment]
@oblition Can you point to some config (maybe your's one) how to configure `coc-snipets` without `UltiSnips`.
Because i have tested 5 min ago with disabled `UltiSnips` plugin and there is much lesser snippets and no `date`, `time` snippets at all.

**Comment by oblitum** [comment]
This is my configuration, which I do from `.vimrc` instead of `coc-settings.json`:

```vim
call coc#config('snippets', {
\   'extends': {
\     'cpp': ['c'],
\     'javascriptreact': ['javascript'],
\     'typescript': ['javascript']
\   },
\   'ultisnips': {
\     'directories': ['UltiSnips', 'gosnippets/UltiSnips']
\   }
\ })
```

**Comment by monkoose** [comment]
@blasco Seems like `coc-snippets` doesn't support this feature look [](https://github.com/neoclide/coc-snippets#ultisnips-features)
> Automatic reformat snippet after change of placeholder (can't support).

So maybe this issue can be closed?

**Comment by chemzqm** [comment]
We can't track change outside placeholder, so the issue is expected
