### ISSUE TITLE
Difficulty using <C-x><C-n>

### ISSUE THREAD

**Issue by jmriego** [neoclide/coc.nvim#1289]
Hi all,

first of all thanks a lot for this plugin. It really is amazing for developing in Python!

My problem is when trying to use <C-x><C-n> for being able to complete a series of words.
It seems like the autocompletion popup that appears automatically is interfering with this in some way. It can be tested by trying to use that in any buffer. You will see that it needs to be called two or three times to activate. Might have to capture my screen if this is not clear enough.

Thanks in advance!

**Comment by chemzqm** [comment]
Can't reproduce, but you can use `"suggest.autoTrigger": "trigger"` to make completion trigger on trigger characters and patterns only.
