### ISSUE TITLE
Error during vetur initialization

### ISSUE THREAD

**Issue by deathmaz** [neoclide/coc.nvim#129]
**Describe the bug**
When i open `.vue` files neovim opens vertical split with:
```
Vetur initialized
[3  - 12:02:44 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'template' of undefined
```

**To Reproduce**
1. `nvim test.vue`

**Expected behavior**
no error message when opening `.vue` file

**Desktop (please complete the following information):**
Terminal: tilda
Version: 1.4.1-1
tmux 2.8-1
NVIM v0.3.1

**Additional context**
Thank you very much for a nice plugin and help!

**Comment by chemzqm** [comment]
Fixed on master branch, build from source required.

**Comment by deathmaz** [comment]
Works fine now, thank you!
