### ISSUE TITLE
Documentation request: Clarify whether HTTP_PROXY is for SOCKS connections?

### ISSUE THREAD

**Issue by rw** [neoclide/coc.nvim#1291]
This is not a bug report, but it is a documentation request.

Is the `HTTP_PROXY` setting intended to work with SOCKS5? In my local setup, setting that environment variable to the following does work for other neovim-related things, but it does not work for `CocInstall`:

`HTTP_PROXY=socks5h://10.0.0.100:5000`

I've read the source code the JS dependency "tunnel", but that doesn't explain it either.

Thanks!

**Comment by chemzqm** [comment]
It works with http protocol only.

**Comment by rw** [comment]
@chemzqm Sorry, I don't understand how a proxy works in that situation. Is it by using the `Host` header?

**Comment by fannheyward** [comment]
@rw Only HTTP/HTTPS proxy works, that means you can't use SOCK5 type, only `HTTP_PROXY=http://1.2.3.4:5000` works.

**Comment by rw** [comment]
@fannheyward I understand that, I'm asking something different: how does that proxy route requests? If that is documented, people like me can run one myself and connect it to our SOCKS5 proxies. But, I don't understand right now how coc.nvim instructs the `http://1.2.3.4:5000` proxy to fetch a page from github.com or other sites. Do you know how it does that? Thanks!

**Comment by chemzqm** [comment]
It's agent option of http/https module, it there other way to use proxy with nodejs?

**Comment by rw** [comment]
@chemzqm Are you saying it would be something like this? https://github.com/http-party/node-http-proxy :-]

**Comment by chemzqm** [comment]
Not that module, it uses https://github.com/koichik/node-tunnel/, you can read the code https://github.com/neoclide/coc.nvim/blob/master/src/model/fetch.ts#L11

**Comment by rw** [comment]
@chemzqm It looks like that library is just using the `Host` header to determine the upstream endpoint: https://github.com/koichik/node-tunnel/blob/master/lib/tunnel.js#L113

I still suggest documenting this. I'm not the only one who has probably wasted time with getting this to work in a corporate environment with SOCKS proxies. 

Thanks!

**Comment by chemzqm** [comment]
Added check for protocol.
