### ISSUE TITLE
Refresh diagnostics issue with displayByAle

### ISSUE THREAD

**Issue by sQVe** [neoclide/coc.nvim#1296]
## Result from CocInfo
```shell
## versions

vim version: NVIM v0.4.2
node version: v10.16.3
coc.nvim version: 0.0.74
term: alacritty
platform: linux

## Messages

## Output channel: snippets


## Output channel: tsserver

[Info  - 1:12:48 PM] Forking TSServer
PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/home/sqve/.local/bin:/home/sqve/.nvm/versions/node/v10.16.3/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/sqve/.local/bin:/home/sqve/.nvm/versions/node/v10.16.3/bin:/home/sqve/.local/bin:/home/sqve/.nvm/versions/node/v10.16.3/bin 
[Info  - 1:12:48 PM] Started TSServer
{
  "path": "/home/sqve/code/righttp/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.6.4",
    "version": "3.6.4"
  }
}
```

## Describe the bug

There's an issue with diagnostics not being properly refreshed when using the `displayByAle` option. It seems like `coc.nvim` sends the previous diagnostics at times or does not clear when no diagnostics are available. See the below gif for a better explanation:

![Peek 2019-10-23 13-36](https://user-images.githubusercontent.com/2284724/67389209-6df43380-f59a-11e9-9c9a-f23eb457240e.gif)

## Reproduce the bug

Use `coc.nvim` together with `ale` with the `displayByAle` option set to `true`. Create a lint issue like the one in the above gif (in this case a eslint error).

**Comment by chemzqm** [comment]
Fiexed by revert 94ce0392b

**Comment by sQVe** [comment]
@chemzqm Indeed fixed. Thank you for your quick response, as always. :pray:

Closing.
