### ISSUE TITLE
Swallows first letter

### ISSUE THREAD

**Issue by Boelensman1** [neoclide/coc.nvim#13]
Thanks for the awesome plugin!

However I have a problem that makes it very hard to work with.
Right now whenever I start typing something the first letter of whatever I type disappears.
So for example, I go to insert mode, type the letter a. The a goes away and the autocompletion opens. Any subsequent typing while the completion window is open works fine.

It seems to me that the opening of the autocompletion (not sure what to call it, the window that has all the choices), removes whatever you typed.

**Comment by chemzqm** [comment]
Seems like conflict with other plugin, try to filter your plugins to see which one cause the problem.

**Comment by iamcco** [comment]
the `completeopt` option has `longest` will occur this

**Comment by chemzqm** [comment]
I can reproduce it, it happens sometime.
