### ISSUE TITLE
How to know the respective server status?

### ISSUE THREAD

**Issue by liuchengxu** [neoclide/coc.nvim#130]
**Is your feature request related to a problem? Please describe.**

If the language server is busy, e.g., when RLS is doing the initialization or compiling modules, the action of coc normally is not able to get proper results. How can I know the status of server when using coc? In vscode, there is spinner indicating the status of RLS:

![](https://user-images.githubusercontent.com/10340017/32422249-71d34f98-c286-11e7-8226-500cb85cdd7f.png)

**Describe the solution you'd like**

Introduce something like `g:LanguageClient_serverStatus` in https://github.com/autozimu/LanguageClient-neovim.

**Describe alternatives you've considered**

Introduce status for actions of coc. 

Currently I can't tell if the result of action is empty or it's just on the way. For instance, when `jumpDefinition`, if the server is not ready, coc could just say `Language server is busy`, if the returned result is empty, just say `Not found` or something else.

**Additional context**

**Comment by chemzqm** [comment]
I've added `g:coc_status` which contributed by coc extensions https://github.com/neoclide/coc.nvim/commit/58ee4d65a8a6b0ed2e08b749a45122fdc695c845.

I would not hack coc to include status information for RLS, since it's not LSP standard, but that would possbile be implemented in an extension.

> if the server is not ready, coc could just say Language server is busy.

There's no standard way know the server is busy or not, coc just cancel the request after timeout (5s by default), to avoid the timeout message shown again and again, it's simply filtered.  I could add the `not found` message for location requests.

**Comment by chemzqm** [comment]
There's https://github.com/neoclide/coc-rls now, it does what you need.

**Comment by liuchengxu** [comment]
awesome! 

https://github.com/liuchengxu/eleline.vim/commit/8d02de968d0b67b8df57bad96b9ea80fc51cbb7c also adds support for coc.nvim :).

![image](https://user-images.githubusercontent.com/8850248/47595248-ea692c00-d9b1-11e8-9721-b793e21502e3.png)

**Comment by liuchengxu** [comment]
One problem: `g:coc_status` is seemingly not updated when switching to a buffer which doesn't have a relevant LS service. 

![image](https://user-images.githubusercontent.com/8850248/47595816-c1966600-d9b4-11e8-8039-67610742841a.png)

**Comment by chemzqm** [comment]
> One problem: `g:coc_status` is seemingly not updated when switching to a buffer which doesn't have a relevant LS service.
> 
> ![image](https://user-images.githubusercontent.com/8850248/47595816-c1966600-d9b4-11e8-8039-67610742841a.png)

It works as expected on my neovim, I've added `redraws` command after status change, so it could statusline no updated on vim, that might resolve your issue.

**Comment by liuchengxu** [comment]
I don't think `redraws` would help since it's the value of `g:coc_status` does not get updated when it should in coc.nvim, not the status of vim/neovim statusline itself has not been updated.

It's easy to reproduce in my case, edit a random rust file and open another file with different filetype, md, ts, vim or whatever, the info of `:echo g:coc_status` is always from RLS. I think `g:coc_status` should be updated when switching between different filetypes.
