### ISSUE TITLE
Tab key select first option and close popup menu

### ISSUE THREAD

**Issue by rickywu** [neoclide/coc.nvim#1300]
v 0..0.74

inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

It works well before but suddenly <tab> key complete first option and close popup menu
`:imap <tab>` is correct

**Comment by rickywu** [comment]
```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```
use this instead, seems the old map not work after update

**Comment by hakunin** [comment]
This selects the first item, but doesn't accept and close the popover, any ideas?

**Comment by chemzqm** [comment]
>  but doesn't accept and close the popover, any ideas?

https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources
