### ISSUE TITLE
Different background color with some chars on code completion

### ISSUE THREAD

**Issue by phynalle** [neoclide/coc.nvim#1301]
## versions

vim version: NVIM v0.4.2
node version: v12.13.0
coc.nvim version: 0.0.74-b04e619c64
term: xterm-256color
platform: linux

## Messages
"~/.config/nvim/init.vim" 7L, 170C written

## Describe the bug

Some chars have different background color in code completion.
Let's see the screenshot below.  -, =,<, > have black bg.

It's not a critical bug, but annoying me to see them. 

## Reproduce the bug

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create file `mini.vim` with：

```vim
syntax on
filetype plugin indent on
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
colo gruvbox
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/6007810/67461481-6c00a200-f678-11e9-808c-32805a335d4b.png)

**Comment by chemzqm** [comment]
Could be caused by your other vim plugin, I can't reproduce.

**Comment by monkoose** [comment]
It is not because of other plugins it is because of `colorscheme` or `syntax` that set this `operators` background color to your `Normal` background color. You should make them background independent with `ctermbg=NONE` or `guibg=NONE`.
