### ISSUE TITLE
Overlapping floating windows for function arguments

### ISSUE THREAD

**Issue by monkoose** [neoclide/coc.nvim#1302]
Here is short video [https://imgur.com/YHhx0dU](https://imgur.com/YHhx0dU)

Is it possible to better position this window? Why they even overlap? As you can see i have a lot of space over or below this line.
If not, how i can completely disable just this windows for function arguments? But for sure i prefer to better position this type of windows.

**Comment by fannheyward** [comment]
`CocInfo` please, can't reproduce in ts editing.

**Comment by monkoose** [comment]
Here is `CocInfo`
```
## versions

vim version: NVIM v0.4.2
node version: v12.13.0
coc.nvim version: 0.0.74-b04e619c64
term: xterm-kitty
platform: linux

## Messages

## Output channel: snippets


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Error 128 on: 'git rev-parse --show-toplevel' in /home/monkoose
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null
resolved root: null

## Output channel: highlight

[Info  - 12:04:03 PM] Highlight server running in node v12.13.0
```
Let me test with ts too.

**Comment by monkoose** [comment]
Tested with ts files. Same behaviour.

**Comment by fannheyward** [comment]
<img width="404" alt="2019-10-2417 58 04" src="https://user-images.githubusercontent.com/345274/67474928-d705a500-f687-11e9-98f0-868a3fe93926.png">

Please provide a minimal `vimrc` to reproduce this issue.

**Comment by monkoose** [comment]
Ah i get it why it is. As you can see my windows have blank lines it is because i set recently `winheight=10` and `winminheight=10` in my config.

If it is hard to respect this values i have a workaround for my needs for sure. What do you think should this popups respect `winheight` and `winminheight`? If no then this issue can be closed.
Thank you for fast response.

**Comment by chemzqm** [comment]
I think neovim should ignore `winheight` and `winminheight` options when specfic window hight was specified for position the float window.

**Comment by monkoose** [comment]
After some quick test, now i'm actually not sure how to solve my needs.
I want CocList windows always to be specific height and do not autoResize. There is `list.maxHeight` and `"list.autoResize": false` options. But there is no something like `list.minHeight`. So this setting is bad for some windows like `CocList grep` that always start with 1 line, and with `"list.autoResize": false` they always stay at 1 line. Any solutions? For some reason i can't resize them with `autocmd WinEnter,BufWinEnter list:///* resize 10`, but can manually resize them in normal mode with `:resize 10`.

**Comment by niklaas** [comment]
Thanks for mentioning `winheight`. I ran into this too.

**Comment by DenniJensen** [comment]
I had the same issue. Thank you mentioning this issues. I am glad it solves the issue.
