### ISSUE TITLE
Built-in LSP support.

### ISSUE THREAD

**Issue by iago-lito** [neoclide/coc.nvim#1303]
It seems that a new [PR](https://github.com/neovim/neovim/pull/10222) at neovim brings LSP support as a native feature. I am not sure how this impacts coc and whether or how the two could benefit from each other.

What is the overall feeling about this? Should I keep using coc as LSP client or should I try using the new feature instead? Does this question even makes sense?

**Comment by chemzqm** [comment]
That PR was created before coc.nvim exists.

**Comment by iago-lito** [comment]
I guess you mean that it is coc intent to coexist with this new feature of neovim. What I'm still unsure is the way they are supposed to interact:
- Is coc an alternative to native LSP support?
- Does native LSP support benefits to coc in some ways?
- Does native LSP support shadows coc in some ways?

**Comment by chemzqm** [comment]
> Is coc an alternative to native LSP support?

Yes

> Does native LSP support benefits to coc in some ways?

No

> Does native LSP support shadows coc in some ways?

No
