### ISSUE TITLE
diagnostic sign doesn't disappear

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#131]
**Describe the bug**
diagnostic sign doesn't disappear

**To Reproduce**

1: test.ts
```javascript
function test() {
  return 0
}
```
2: delete `}`

```javascript
function test() {
  return 0

```
3: insert `}`
```javascript
function test() {
  return 0
}
```

and diagnostic sign doesn't disappear

**Comment by chemzqm** [comment]
It's feature, diagnostic info would not update in insert mode, that would cause problem on vim, like uncontrolled cursor position.  
I think it's better experience since there's less redraw, you can get the diagnostic immediately after leave insert mode.

**Comment by iamcco** [comment]
it still there when leave insert mode

**Comment by chemzqm** [comment]
> it still there when leave insert mode

Can't reproduce that, but the command for unplace sign did fail sometimes.
