### ISSUE TITLE
What are the drawback of not specifying rootPatterns in LSP configs?

### ISSUE THREAD

**Issue by ahmedelgabri** [neoclide/coc.nvim#1310]
Taking an example from the wiki

```json5
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod"], 
      "filetypes": ["go"]
    }
  }
```

This means that this will run on all `.go` files in any directory under the directory that contains `go.mod`, right?

But what is the drawback if I do something like this instead?

```json5
  "languageserver": {
    "golang": {
      "command": "gopls",
      "filetypes": ["go"]
    }
  }
```

This will mean run the LSP on any `.go` file, right?

The reason I'm asking this is that I have multiple LSPs & sometimes I tend to play with an idea before actually starting a project. Or, I want to write a quick script to automate some task, these things don't necessarily need to be inside of _project_. And I want my editor to always have the LSP support for the filetype I'm currently using. So I wanted to understand what is the drawback (if any) for omitting the `rootPatterns`

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders
Seems gopls requires `go.mod` to work.

**Comment by ahmedelgabri** [comment]
> https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders
> Seems gopls requires `go.mod` to work.

Thanks for the info, but I was just giving an example with `gopls` my talk was more in the general sense. It can be Python, JavaScript, Rust, etc… LSP

Especially dynamic languages (Ruby, Python, JavaScript, etc…) where you can open a file, write some code & run it right away. The idea of only enabling LSP if there is a specific file(s) doesn't make sense.

VSCode will always auto-complete if I'm in a project or not for example & I want to achieve the same thing.

**Comment by chemzqm** [comment]
> I want to achieve the same thing.

The easiest way is use VSCode, vim doesn't work like vscode.
It's problem of language server, some servers like coc-tsserver could just work without resolved workspaceFolder.

**Comment by chemzqm** [comment]
Some VSCode extensions could be smart enough to make the server works with single files (for example, by use some special command line arguments), it's one of reasons that coc support extensions, but you can't expect every VSCode extensions are ported to coc.nvim.

**Comment by ahmedelgabri** [comment]
> It's problem of language server, some servers like coc-tsserver could just work without resolved workspaceFolder.

I just tried writing a `.ts` file inside `/tmp` & it worked fine, so I wonder what is the `workspaceFolder` in that case? 

> The easiest way is use VSCode, vim doesn't work like vscode.

It's not that annoying for me to switch, I just wanted to understand what if I omit the `rootPatterns` config. I found this issue because I was playing with some idea in a `~/foo.py` file & the completion was not working. _I'm using `coc-python`_ so I tried to dig a bit more into my configs & try other files `*.clj`, `*.rs`, `*.ts`, `*.js`, etc… for some,`coc-rls` for example, logged a message about a missing `Cargo.toml` but completion still worked fine. Go LSP didn't work at all, the rest were fine.

What I'm trying to understand is when & when not `rootPatterns` are required, IMO for dynamic languages they should not be required but maybe for compiled one makes more sense. So I can twek my configs accordingly.

**Comment by chemzqm** [comment]
>  I just wanted to understand what if I omit the rootPatterns config

It'a server option, coc.nvim just pass workspaceFolder to server if any. We use rootPatterns since it's bad idea for vim user to open folder before edit files like VSCode.

>  IMO for dynamic languages they should not be required but maybe for compiled one makes more sense. So I can twek my configs accordingly.

My advice is use root patterns when necessary to get better experience and start your vim in workspaceFolder.
