### ISSUE TITLE
How to uninstall extensions?

### ISSUE THREAD

**Issue by kkoomen** [neoclide/coc.nvim#1311]
I have installed coc-highlight by providing the `coc-highlight` in my vimrc using the `g:coc_global_extensions` variable.

I have decided that I want to uninstall this plugin, but I can't uninstall this no matter what. The highlighting is still showing up. I did `:CocUninstall coc-highlight`, removed all its mappings in my vimrc, I removed `~/.config/coc` and `~/.vim/plugged/coc.nvim` and re-installed, but nothing works.

Any idea?

**Comment by chemzqm** [comment]
Check `:CocList extensions`, the highlights could comes from langauge server

**Comment by kkoomen** [comment]
Can you not close an issue immediately? I already tried checking `:CocList extensions` and they list everything but not `coc-highlight`.

**Comment by chemzqm** [comment]
It means coc-highlight was removed.

**Comment by chemzqm** [comment]
It means coc-highlight was removed.

**Comment by kkoomen** [comment]
Yes.... and the highlighting still appears in my Vim, so how do I fix this?

**Comment by chemzqm** [comment]
Check your configuration file

**Comment by kkoomen** [comment]
For what? Can you be more specific?

**Comment by chemzqm** [comment]
You have autocmd like `  autocmd CursorHold * silent! call CocActionAsync('highlight')
`

**Comment by kkoomen** [comment]
> You have autocmd like autocmd CursorHold * silent! call CocActionAsync('highlight')

Are you even reading my issue? I noticed that I already removed everything including corresponding mappings.

> [...] we don't work for you.

I never said you did, but you're being rude at people who ask for help because something does not work as expected with _your_ plugin.

**Comment by iamcco** [comment]
It can't be coc highlight the words since you have uninstall coc-highlight and remove the config relative to highlight of coc. If you think it is coc's issue please reproduce with minimum vimrc.

**Comment by fannheyward** [comment]
1. You did `:CocUninstall coc-highlight`, this will remove highlight extension.
2. `:CocList extensions` did not contains coc-highlight, this means the extension has already removed.

But you still have highlight, this is not expected. Can you provide `:CocInfo` and vimrc that we can reproduce this issue?

**Comment by kkoomen** [comment]
> Can you provide :CocInfo [...]

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 23 2019 15:11:17)
node version: v12.6.0
coc.nvim version: 0.0.74-36e476819f
term: iTerm.app
platform: darwin

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"_variables.scss" 1005L, 26585C

```

> [...] and vimrc

```vim
let g:coc_global_extensions = [
      \ 'coc-tsserver',
      \ 'coc-html',
      \ 'coc-css',
      \ 'coc-python',
      \ 'coc-phpls',
      \ 'coc-yaml',
      \ 'coc-json',
      \ 'coc-vimlsp',
      \ 'coc-emmet',
      \ 'coc-tag',
      \ ]

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'H ' . expand('<cword>')
  else
    call CocActionAsync('doHover')
  endif
endfunction

" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

nmap <silent> gd <Plug>(coc-definition)

hi! CocErrorSign guifg=#d97084
hi! CocWarningSign guifg=#e9cb87
hi! CocInfoSign guifg=#d0d2d2
hi! CocHintSign guifg=#6face4
```

**Comment by oblitum** [comment]
One of the extensions may be doing extra highlighting. Does coc.nvim from scratch, without any extensions, and with all extensions removed (simply nuke `.config/coc`) "highlights"?

I still ignore what highlighting you're talking about, CSS colors?

**Comment by oblitum** [comment]
Check this for example: https://github.com/neoclide/coc-css/issues/3.

**Comment by oblitum** [comment]
And this:

https://github.com/neoclide/coc.nvim/blob/c9cc96e254323f24685ad6df3f0ade632cbac717/data/schema.json#L784-L788

**Comment by oblitum** [comment]
Also notice the first answer by @chemzqm was:

> Check :CocList extensions, **the highlights could comes _from langauge server_**

Emphasis mine.

**Comment by kkoomen** [comment]
> I still ignore what highlighting you're talking about, CSS colors?

Yes, I confirm that its pure css, other languages are not being highlighted.

**Comment by kkoomen** [comment]
`  "coc.preferences.colorSupport": false` fixed it, thanks.

**Comment by chemzqm** [comment]
If you don't have `CocAction('highlight')` with `autocmd`, the highlight won't work at all.
So it's problem of your vim's configuration, provide your minimal vimrc when you want to report bug.

**Comment by rishadbaniya** [comment]
To uninstall an extension, type ":CocList extensions" and then press TAB key and there it will promp you to choose "u" and uninstall the extension you selected

**Comment by amsheehan** [comment]
> You have autocmd like ` autocmd CursorHold * silent! call CocActionAsync('highlight')`
> 
> If you can't figure out such kind of issue yourself, consider use other tools, we don't work for you.

lmao, who tf are ya building for then??

**Comment by KrishnaTheCoder756** [comment]
try :PlugUpdate in vim editor
