### ISSUE TITLE
How to install extensions use coc, for example rcjsuen/dockerfile-language-server-nodejs and mads-hartmann/bash-language-server server?

### ISSUE THREAD

**Issue by smile-kindred** [neoclide/coc.nvim#1315]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by iamcco** [comment]
`rcjsuen/dockerfile-language-server-nodejs` and `mads-hartmann/bash-language-server` are not extension, coc's extension start with `coc-`.

**Comment by smile-kindred** [comment]
@iamcco how to use these server?

**Comment by iamcco** [comment]
read the wiki https://github.com/neoclide/coc.nvim/wiki/Language-servers#register-custom-language-servers

**Comment by chemzqm** [comment]
Use gitter for general questions.
