### ISSUE TITLE
Buffer source takes completion from wrong window/buffer.

### ISSUE THREAD

**Issue by BonaBeavis** [neoclide/coc.nvim#1317]
## Result from CocInfo

vim version: NVIM v0.5.0-dev
node version: v10.16.3
coc.nvim version: 0.0.74-bc017b02e6
term: xterm-256color
platform: linux

## Describe the bug
![image](https://user-images.githubusercontent.com/3330855/67944539-f5662600-fbdc-11e9-99e7-7993e4d763c6.png)

## Reproduce the bug

  ```vim
set nocompatible
filetype off

call plug#begin('~/.vim/bundle')
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
call plug#end()

let g:python_host_prog = '/home/XXX/.virtualenvs/neovim/bin/python'
let g:python3_host_prog = '/home/XXX/.virtualenvs/neovim3/bin/python3'

syntax on
filetype plugin indent on
set hidden
  ```

Thanks a lot for you work!

**Comment by chemzqm** [comment]
It's expected, https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#bundled-sources
