### ISSUE TITLE
coc-languageserver section is missing from the help page

### ISSUE THREAD

**Issue by Alkeryn** [neoclide/coc.nvim#1318]
And also there is no documentation on how to send request to the language server
let's say i wanna jump to a definition or i want the linter to ignore an error or things like that.

**Comment by Alkeryn** [comment]
So there is no way to ask the language server stuff ?

**Comment by fannheyward** [comment]
You can use extension to make requests to language server.

**Comment by chemzqm** [comment]
You can use `CocReqeust()` or `CocReqeustAsync` for sending request to specific language server.

**Comment by Alkeryn** [comment]
Yeah ended up finding it thanks ^
