### ISSUE TITLE
Can't run coc-html on html.twig files is it going to be supported?

### ISSUE THREAD

**Issue by Kazimazi** [neoclide/coc.nvim#132]
I can't run coc-html on html.twig files. I'm not sure what I'm doing wrong, it works on html files.
My CocConfig file looks like that:
`{
  "html.filetypes": ["html", "handlebars", "razor", "html.twig"]
}`

**Comment by chemzqm** [comment]
That's because extension use `activationEvents` which requires filetype match to activate.
You can use autocmd to activate the extension like:

```
  autocmd FileType html.twig :call CocAction('activeExtension', 'coc-html')
```

**Comment by chemzqm** [comment]
It could be improved to match filetype that start with `html.`

**Comment by Kazimazi** [comment]
The combination of CocConfig and autocmd makes it work. Thx.
