### ISSUE TITLE
Absolutely cannot get MPLS to work

### ISSUE THREAD

**Issue by 0xRainy** [neoclide/coc.nvim#1320]
## Result from CocInfo

[CocInfo](https://gist.github.com/0xRainy/1865666a688b01d183d253085c8530a7)

## Describe the bug

I'm having issues with coc-python and mpls. I've tried all I know: upgraded to nightly nvim, fresh plugin install (wiped all cache and directories), built mpls from source, tried every suggestion I could find on google.. and I still can't get ANY features of mpls to work.

I keep getting timeout errors in CocInfo for python and also my client is sending requests to cancel tasks whenever I do anything that triggers completion.

## Reproduce the bug
Created minimal [init.vim](https://gist.github.com/0xRainy/cd09761c0d2e1aeedf52a12811461c02) and [coc-settings.json](https://gist.github.com/0xRainy/5efcb4129b7f86294c8c964df7ebd5e6)

## Screenshots (optional)
Here is my other config files and package list
[checkhealth](https://gist.github.com/0xRainy/f67064bd9153933650f8b9c2c1e6301b)
[installed packages](https://gist.github.com/0xRainy/eb99c73deec654ebdbdc6d96d3818f24)
I think this is the root of the problem.

`[Trace - 9:47:14 AM] Sending notification '$/cancelRequest'.
Params: {
    "id": 8
}

[Trace - 9:47:14 AM] Received notification 'telemetry/event'.
Params: {
    "EventName": "python_language_server/rpc.request",
    "Properties": {
        "method": "textDocument/completion",
        "plsVersion": "0.4.71.0"
    },
    "Measurements": {
        "elapsedMs": 4940.7717
    }
}

[Trace - 9:47:14 AM] Received response 'textDocument/completion - (8)' in 4941ms. Request failed: The task was cancelled. (-32800). `

**Comment by fannheyward** [comment]
Looks like you are use $HOME `Workspace root: /home/rainy` as your workspace, and editing `file:///home/rainy/test.py`. This will make MPLS to index all files in $HOME.

Try make a dir like `$HOME/test` and `git init` it, put your test.py into it.

**Comment by chemzqm** [comment]
It's limitation of language server, we can't help.

**Comment by 0xRainy** [comment]
I tested it in a different directory and yup, it works.. It wasn't working earlier because it's the same file I was testing on before I made the one in $HOME.

Further testing.. it really doesn't like my 2 lilne test.py file.. half the time it breaks or works.
