### ISSUE TITLE
CocList doesn't show color outputs

### ISSUE THREAD

**Issue by rcarriga** [neoclide/coc.nvim#1325]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-135-g90981f586
node version: v12.13.0
coc.nvim version: 0.0.74-a52dec0522
term: xterm-kitty
platform: linux

## Messages

## Output channel: snippets


## Output channel: explorer
```

## Describe the bug

CocList grep/files doesn't show any colors as outputted by ripgrep (also tried ag). I see in the Wiki it says that this is possible but can't figure out how. Rg outputs color as expected when used in terminal.

## Reproduce the bug

`coc-settings.json`
```
{
    "list.source.grep.command": "rg",
    "list.source.grep.args": ["--max-depth=10", "--hidden", "--color", "always", "--follow"],
}
```

Command being used `CocList grep`

Using the `.vimrc` as given:
  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

## Screenshots

![vitest](https://user-images.githubusercontent.com/24252670/68078604-34f56380-fdd1-11e9-9203-2d11af98a200.png)

**Comment by fannheyward** [comment]
Can't reproduce on macOS with iTerm + Neovim 0.5.

**Comment by rcarriga** [comment]
After more debugging, I found the issue was that the highlight groups `CocListFgX` were not defined due to loading Coc after startup with dein. Fixed by adding definitions for these groups
