### ISSUE TITLE
Strikethrough deprecated completion items

### ISSUE THREAD

**Issue by martskins** [neoclide/coc.nvim#1326]
It would be nice to have some visual feedback about completion items that are marked as deprecated. The one that comes to mind is to strikethrough the name of the identifier that is deprecated.

![image](https://user-images.githubusercontent.com/4250565/68078825-23a25c00-fdbd-11e9-977d-f9ec17e7762c.png)

I tried to implement this (the image above is from that implementation) but my implementation is very naive and assumes that the identifier names are just plain ASCII text. Which would not necessarily work for some languages.

**Comment by fannheyward** [comment]
I'm interested in this. How did you make strikethrough on text in vim TUI and GUI? I just find this https://vim.fandom.com/wiki/Create_underlines,_overlines,_and_strikethroughs_using_combining_characters , use Unicode encoded characters, which are not the same as origin text.

**Comment by chemzqm** [comment]
> assumes that the identifier names are just plain ASCII text

They're plain ASCII text most of the time, but you can't expect the escape characters you're using works across TUIs.

**Comment by sigvef** [comment]
Seems strikthrough support recently landed in neovim, perhaps that could be useful for this? https://github.com/neovim/neovim/pull/10971

**Comment by chemzqm** [comment]
But vim doesn't have any support for highlight complete item.

**Comment by oblitum** [comment]
IMHO, coc.nvim shouldn't take the least common denominator route because of Vim. NeoVim is the one that advances faster to offer IDE-like features, so I think coc.nvim should take that one as the basis, as I consider coc.nvim as IDE for the terminal.

**Comment by chemzqm** [comment]
No highlight support of complete item on neovim too.

**Comment by oblitum** [comment]
Ah OK. When I wrote that I was thinking of the strikethrough feature, but I guess it based on highlighting.

**Comment by fannheyward** [comment]
What I have tested:

1. vim/neovim uses highlight group to do strikethrough, `hi default TTStrikethrough  cterm=strikethrough gui=strikethrough`
2. `call matchadd('TTStrikethrough', 'test')` works on vim, but not works on neovim 0.5
3. no highlight support on completion item, yet
