### ISSUE TITLE
Plans for decorations?

### ISSUE THREAD

**Issue by ckipp01** [neoclide/coc.nvim#1329]
**Describe the solution you'd like**
I wasn't able to find any reference to whether or not coc supports decorations apart from this reference to `experimentalDecorators`
https://github.com/neoclide/coc.nvim/blob/3c7fc20f69a42c8dc897b5cbec39e5eab3683c94/tsconfig.json#L16
If my understanding is correct, coc doesn't yet support `decorationProvider`? I also saw a reference to parameter decorations in #1148 which is decorations being used in a different way. If no decoration support currently exists, this would be a fantastic addition. There is an open PR in the Scala Language Server, Metals, https://github.com/scalameta/metals/pull/1041 that implements the ability to use worksheets, which works fantastically in VSCode using decorations, and it would be great if this was also supported by coc.

At first, I thought this was implemented but realized it was code lenses. I'd imagine that the way this could be implemented could be similar to that.

**Comment by fannheyward** [comment]
No. It't not coc support or not, but need vim/neovim support it. Neovim has virtual text support, but you can't put it inside _real_ text.

**Comment by chemzqm** [comment]
It's not possible on vim or neoivm, don't be confused with `experimentalDecorators`  used by tsserver and decoration of LSP.

**Comment by gabro** [comment]
@ckipp01 to clarify, the `decorationProvider` in the linked Metals PR is a custom extension to LSP that we've come up with. It's not in the standard LSP protocol, so any implementation will have to be editor-specific.

**Comment by ckipp01** [comment]
Thanks for the response @chemzqm and ahh, that makes sense @gabro and also probably the reason I had a hard time finding more about it in the LSP documentation. Thanks!
