### ISSUE TITLE
List of all the diagnostic errors

### ISSUE THREAD

**Issue by yml** [neoclide/coc.nvim#133]
**Describe the bug**
Is there a way to list all the diagnostic error? Few weeks ago I could do `:lopen` but now it looks like you are cleaning it up.

**To Reproduce**
1. Open a buffer with diagnostic error 
2. do `:lopen`

**Expected behavior**
I would expect to see all the error from the current buffer instead the location list is empty.

**Comment by chemzqm** [comment]
The `:lopen` can't work with 0.0.28 release, the diagnostic have been reworks, it's fixed on master branch.

**Comment by chemzqm** [comment]
Released v0.0.29

**Comment by yml** [comment]
I might be misunderstanding something but when I do `:lopen` is see a location list window with the list of issues in the current buffer. However when I select a line and `<CR>` the location list is deleted and the window not close. 
Is that the expected behavior ? It makes inspecting the errors very tedious.

btw thank your very much for making such an amazing plugin.

**Comment by chemzqm** [comment]
Looks like location list is cleared by other plugin, checkout https://github.com/neoclide/coc.nvim/wiki/F.A.Q#why-location-list-sometimes-doesnt-work

**Comment by yml** [comment]
I do not use Ale. The list of plugins I am using is rather short and I kind find the one that conflict with coc.
```
"*****************************************************************************
" Plug install packages
"*****************************************************************************
Plug 'tpope/vim-commentary'
Plug 'airblade/vim-gitgutter'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'sheerun/vim-polyglot'
Plug 'Yggdroot/indentLine'
Plug 'tomasiser/vim-code-dark'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
if has("nvim")
    Plug 'vimwiki/vimwiki'
    Plug 'sgur/vim-editorconfig'
    Plug 'fatih/vim-go', {'do': ':GoInstallBinaries'}
endif
if has("nvim-0.3.0") 
    Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
endif
```
My full vimrc can be seen [here](https://github.com/yml/dotfiles/blob/master/_vimrc). Any clue on which plugin has this unexpected side effect with coc would be appreciated.
Thank you

**Comment by chemzqm** [comment]
It's bug of coc, it should not validate quickfix buffer, I've fixed on master branch.

**Comment by yml** [comment]
Thank you I confirm that this is fix in 0.30.

**Comment by mandaputtra** [comment]
Hi I know its closed, but I experience the same thing. Maybe I just don't know how to open the full error message.

```
NVIM v0.5.0-654-g3acfefb63
coc.nvim version: 0.0.80-6e5a2aaeb5
```

1. Open file that has an error
2. Get the cursor to the error line
3. Command `:lopen`

But the terminal says `E776: No Location List `, is it my step by step wrong?

**Comment by chemzqm** [comment]
You,have to CocDiagnostics command instead.

**Comment by mandaputtra** [comment]
@chemzqm thanks it work.
