### ISSUE TITLE
Completion artifacts

### ISSUE THREAD

**Issue by amerov** [neoclide/coc.nvim#1330]
## versions

vim version: NVIM v0.4.2
node version: v10.15.3
coc.nvim version: 0.0.74-a52dec0522
term: xterm-256color
platform: linux

## Describe the bug

Strange artifacts after completion popup closed

## Screenshots (optional)
![Screenshot from 2019-11-05 10-44-18](https://user-images.githubusercontent.com/196747/68181599-cd4e3c80-ffb9-11e9-94c0-459fa054c550.png)
![Screenshot from 2019-10-27 13-25-52](https://user-images.githubusercontent.com/196747/68181605-d3441d80-ffb9-11e9-92d0-be1721835a91.png)

**Comment by fannheyward** [comment]
Please provide minimal vimrc to reproduce this issue.

**Comment by chemzqm** [comment]
Looks like bug with neovim 0.4.2

**Comment by amerov** [comment]
> Please provide minimal vimrc to reproduce this issue.

https://github.com/amerov/dotfiles/blob/e5382fb9937316e0a65cfd31e295bc92a8260c04/.config/nvim/init.vim

**Comment by chemzqm** [comment]
@amerov it's not minimal vimrc, we can't help.

**Comment by amerov** [comment]
minmum vimrc: 
```viml
call plug#begin('~/.local/share/nvim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'honza/vim-snippets'
call plug#end()
filetype indent on
filetype plugin on
```
![Peek 2019-11-30 11-14](https://user-images.githubusercontent.com/196747/69896598-37f95a80-1363-11ea-81fa-e56e6f0898e2.gif)
It does't close completin preview if leave insert mode with <C-c>

**Comment by SOLID-arity** [comment]
Why is this closed? I'm having the same issue.

**Comment by chemzqm** [comment]
It's not possible to detect `Ctrl-c` avoid use it
