### ISSUE TITLE
b:coc_current_function updated on every movement

### ISSUE THREAD

**Issue by ChrisAmelia** [neoclide/coc.nvim#1331]
## Describe the bug

When going through the body of a method, `b:coc_current_function` is updated when moving on every line (horizontally or vertically), making the statusline to be updated as well: it displays the method if the cursor is **exactly** on the method.

I would expect a similar behavior to `vista.vim` where the method's name is displayed if cursor is within the method's body (or on the method's signature).

## Reproduce the bug

- Create file `mini.vim` with：

 ```vim
set nocompatible
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
set updatetime=100
autocmd CursorHold * call CocAction("getCurrentFunctionSymbol")
 ```

- Create java test file `Test.java` with:

```java
public class Test {

    public static boolean containsNone(String query, String invalid) {
        return query.indexOf(invalid) == -1;
    }
}
```

- Start nvim with command: `nvim -u mini.vim Test.java`

- Place cursor anywhere on `containsNone` and type `:echo b:coc_current_function`: returns `containsNone(String, String)`.

- Place cursor something else, `:echo b:coc_current_function` returns an empty string.

**Comment by chemzqm** [comment]
Can't understand, it's working as expected.
