### ISSUE TITLE
Inconvenient location for session file "default.vim" on Windows

### ISSUE THREAD

**Issue by EtiamNullam** [neoclide/coc.nvim#1332]
**Is your feature request related to a problem? Please describe.**
By default session file is created at `~/.vim/sessions/default.vim`.

**Describe the solution you'd like**
I think on Windows it should be located at `~/vimfiles/sessions/default.vim`.

**Additional context**

`sessions` alone in `~/.vim`:
![image](https://user-images.githubusercontent.com/10875340/68306712-547add80-00aa-11ea-82bf-8249c708e3c4.png)

**Comment by fannheyward** [comment]
Change `session.directory` 
You can change the location by `session.directory`, directory for store session files, default to `~/.vim/sessions` when empty.

**Comment by EtiamNullam** [comment]
Thanks for the tip.

I know Windows users might not be the main target, but please reconsider it for the sake of others that desire the best out-of-box experience possible.

There is enough stuff that need configuration to work properly in the Vim ecosystem.

Other plugins do it, maybe its hard but I know its possible.
