### ISSUE TITLE
Pin diagnostic message 

### ISSUE THREAD

**Issue by masaeedu** [neoclide/coc.nvim#1334]
**Is your feature request related to a problem? Please describe.**
Hello. Thanks for a really useful plugin. I'm using coc.nvim for working on Haskell projects, and a frequent need in a Haskell codebase is using typed holes. The idea is that you insert a special symbol in a location that causes an error to be raised that contains information useful for implementing a function.

Here is a screen recording hopefully illustrating the scenario:

https://asciinema.org/a/RodDTcaj0A7pysdOPbw8QGVFy

The problem is that I can't see a way to add multiple typed holes (the errors for each of these usually span several lines), and be able to view them all simultaneously while I work on an implementation. If I use floating errors (which I really like and want to keep enabled), I need to have my cursor situated exactly over the position of the hole in order to be able to see the error, whereas I want to be able to move around and edit the code while consulting the error from time to time.

**Describe the solution you'd like**
I'd like to have "random access" to the full, multiline contents of any diagnostic in the current buffer at any time, without moving my cursor to the location of the diagnostic.

To be honest I'm not sure what the best way to implement this is, here are some approaches that might work:

- Provide some way to open a persistent buffer (preview maybe) with the contents of the diagnostic under the cursor (the loclist can be used to jump around between diagnostics)
- Provide a way to make all error balloons show up simultaneously (and not disappear on cursor movement). I'm not sure whether this is actually possible using the API neovim provides
- Provide a way to just dump the full diagnostics with their line numbers into a single buffer, separated by newlines

There's probably better ways to do it than this, the ultimate goal I have is just a convenient workflow for working with multiple typed holes at once.

**Describe alternatives you've considered**
I have not considered any alternatives; if there's already some alternative that faciliates this workflow, I'd be happy to hear of it :)

**Comment by fannheyward** [comment]
If you are using neovim, you can enable `diagnostic.virtualText`, this will show diagnostic message in virtual text.

**Comment by masaeedu** [comment]
@fannheyward @chemzqm Thanks!
