### ISSUE TITLE
Ability to tab to first option

### ISSUE THREAD

**Issue by taybart** [neoclide/coc.nvim#1339]
**Is your feature request related to a problem? Please describe.**
Ability to make <c-n> select the first option instead of moving to second

**Describe the solution you'd like**
I normally **tab** to fill the first suggestion in and then move to normal mode as an 'accept'. I cannot find online anywhere that shows how I can make this happen. Can I set the inital 'complete_index' as -1?

**Describe alternatives you've considered**
This is how ALE worked.

**Additional context**
.vimrc relevant parts
```vim
" coc.vim
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```
Typing...
<img width="316" alt="image" src="https://user-images.githubusercontent.com/3513897/68520980-a6159a80-0259-11ea-9916-442a00a63530.png">
Hitting tab once.
<img width="342" alt="image" src="https://user-images.githubusercontent.com/3513897/68520918-27b8f880-0259-11ea-8594-ccbc3c68c246.png">

**Comment by afking** [comment]
@taybart do you have a fix for this?

**Comment by taybart** [comment]
Nothing consistent. Maybe I should reopen...I used `set completeopt=menuone,noinsert` with `  "suggest.keepCompleteopt": false,` which kinda works

**Comment by chemzqm** [comment]
Preselect is enabled by default, you have to use `"suggest.enablePreselect": false` in your `coc-settings.json`

**Comment by taybart** [comment]
@chemzqm You are a saint

**Comment by jafinn3** [comment]
This doesn't seem to work, coc.nvim version 0.0.82-b9c208ef. After putting` "suggest.enablePreselect": false` in `coc-settings.json`, the enter key still completes the first option, and tab still jumps to the second item in the list. Maybe it has something to do with coc changing how tab works? 

```
" coc.vim

" <...>
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() \: \"\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>\"
```

```
" coc-settings.json
{
    "suggest.enablePreselect": false,
    "diagnostic.checkCurrentLine": true,
}
```

**Comment by chemzqm** [comment]
Seems you need change suggest.noselect ti true

**Comment by shanur00** [comment]
Which Colorscheme is that?
