### ISSUE TITLE
Setting autoTrigger to none takes no effect in latest version of COC

### ISSUE THREAD

**Issue by tamlok** [neoclide/coc.nvim#1343]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.2
node version: v12.13.0
coc.nvim version: 0.0.74-bc017b02e6
term: undefined
platform: win32

## Messages
Unknown font: 
```

## Describe the bug

Here is my `coc-settings.json` (notice that `autoTrigger` is set to `none`):

```
{
    "languageserver": {
        "ccls": {
            "enable": false,
            "command": "ccls",
            "filetypes": ["c", "cpp", "cuda", "objc", "objcpp"],
            "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
            "initializationOptions": {
                "cache": {
                    "directory": "/tmp/ccls-cache"
                },
                "index": {
                    "threads": 2,
                    "comments": 0
                }
            }
        },
        "clangd": {
            "enable": false,
            "command": "clangd",
            "filetypes": ["c", "cpp", "cuda", "objc", "objcpp"],
            "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"]
        }
    },
    "suggest.autoTrigger": "none"
}
```

However, COC still pop up the completion automatically after I enter one char.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.
    1. Insert a word like `abcdefg`;
    2. Enter a new line and insert `ab`;
    3. Now COC will pop up the completion menu;

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/5763157/68744411-856d8c00-062f-11ea-8bf0-29feefc0c141.png)

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by tamlok** [comment]
@chemzqm The screenshot is produced when running `vim -u mini.vim`.

**Comment by tamlok** [comment]
After changing to release branch, it works as expected now. Thanks!
