### ISSUE TITLE
coc return wrong suggestion list when in a 'if' clause in Go when using gopls as language server

### ISSUE THREAD

**Issue by cjun714** [neoclide/coc.nvim#1344]
## Result from CocInfo
vim version: NVIM v0.4.2
node version: v12.13.0
coc.nvim version: 0.0.74-377c2729b9
term: xterm-256color
platform: linux

## Describe the bug
Autocomplete can't filter correct candidates when it's in `if` clause, coc return a wrong suggestion list. 

## Reproduce the bug
When I use gopls as langserver and in an `if` clause, I input 'db.' can trigger a correct suggestion list as below picture:
![1](https://user-images.githubusercontent.com/12163580/68746153-eba7de00-0632-11ea-8fc4-16ab693568e6.jpg)

But if I continue to input "in", I expect coc can filter 'db.Init()' function as shown in above snapshot, but it returned a wrong filter list:
![2](https://user-images.githubusercontent.com/12163580/68746406-7a1c5f80-0633-11ea-80de-af456174768d.jpg)

Please have a check, thanks a lot!

## My Config
.vimrc
```vim
let g:AutoPairs = {'[':']', '{':'}',"'":"'",'"':'"', '`':'`'}

inoremap <expr> <Esc> pumvisible() ? "\<C-e>" : "\<Esc>"
inoremap <expr> ( pumvisible() ? "\<C-y>" : "("
let g:coc_snippet_next = '<C-f>'
let g:coc_snippet_prev = '<C-h>'

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
nnoremap <silent> <leader>i :call <SID>show_documentation()<CR>
imap <silent><expr> <Tab> <SID>expand_tab()

" show document in preview window
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

function! s:expand_tab()
  if pumvisible()
    return "\<C-y>"
  endif
  let col = col('.') - 1
  if !col || getline('.')[col - 1]  =~# '\s'
    return "\<Tab>"
  endif
  return "\<C-m>\<C-m>"
endfunction
```

CocConfig:
``` json
 {
   "suggest.enablePreselect": true,
   "languageserver": {
     "golang": {
       "command": "gopls",
       "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
       "filetypes": ["go"],
       "initializationOptions": {
         "usePlaceholders": true
       }
     }
   }
 }

**Comment by fannheyward** [comment]
Reproduced. Looks like a gopls issue.

**Comment by fannheyward** [comment]
VSCode + gopls can also reproduce this issue. coc.nvim can't do anything, but wait gopls to fix.
