### ISSUE TITLE
Error spawn EACCES of python

### ISSUE THREAD

**Issue by tkolleh** [neoclide/coc.nvim#1345]
## versions

vim version: NVIM v0.5.0-dev
node version: v10.15.1
coc.nvim version: 0.0.74-a52dec0522
term: iTerm.app
platform: darwin

## Messages

```
[coc.nvim] error: Uncaught exception: Error: spawn /usr/local/lib/python3.7 EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[coc.nvim] error: Uncaught exception: Error: spawn /usr/local/lib/python3.7 EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[coc.nvim] error: Uncaught exception: Error: spawn /usr/local/lib/python3.7 EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[coc.nvim] error: Uncaught exception: Error: spawn /usr/local/lib/python2.7 EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## Shell Environment Details

GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)

## Describe the bug

Error messages at the coc.nvim startup when opening a python file using neovim.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

run ` nvim -u mini.vim workspace/qlearning_robot/QLearner.py` or any valid python file with code in it.

**Comment by chemzqm** [comment]
Sorry, don't know what's wrong whit your python.

**Comment by tkolleh** [comment]
Thanks for looking into this. The path `/usr/local/lib/python3.7` is a directory not containing a python executable. Would changing the startup interpreter path resolve this issue? If so how can I change that path?

Note that setting the python interpreter path after opening a `.py` file in neovim does not resolve the issue. This was done with `python.setInterpreter` command. CoC continues to warn that its using the macOS-installed Python.

### Permissions
<img width="495" alt="permissions" src="https://user-images.githubusercontent.com/3095197/69906120-68092380-138c-11ea-84b3-fbe1b1cd951e.png">

### neovim path
<img width="580" alt="python-path" src="https://user-images.githubusercontent.com/3095197/69906138-aef71900-138c-11ea-8587-fefac4f0564c.png">


```

**Comment by tkolleh** [comment]
Resolved EACCES errors by adding `"python.pythonPath": "/anaconda3/bin/python3",` to CoC config and deleting `/usr/local/lib/python{2,3}.7`

**Comment by axrt** [comment]
Actually, I have the exact same issue.. I am guessing that a very simple guard that checks if a filesystem node is a folder would totally solve this issue.. Thanks!

**Comment by ItsChoudhry** [comment]
Hey, I am having this issue right now. I followed the instructions above I created a coc-settings.json in my `~/.config/nvim` dir with the JSON below and deleted the `/usr/lib/python` for both pythons.

```
{
    "python.pythonPath": "/home/choudhry/anaconda3/bin/python3"
}
```
