### ISSUE TITLE
Using Dart language server with coc shows irrelevant completions, mangles text, does not show diagnostics

### ISSUE THREAD

**Issue by PrestonKnopp** [neoclide/coc.nvim#1347]
## versions

dart version: Dart VM version: 2.6.1 (Mon Nov 11 13:12:24 2019 +0100) on "macos_x64"

vim version: NVIM v0.5.0-570ee5f
node version: v8.15.0
coc.nvim version: 0.0.74
term: Apple_Terminal
platform: darwin

## Messages
/Users/prestonknopp/Desktop/testcocnvim/testdart

49052 more lines
"/tmp/langservdart.log" [New] 49052L, 1352158C written

## Output channel: languageserver.dart

[langservdart.log.zip](https://github.com/neoclide/coc.nvim/files/3848838/langservdart.log.zip)

## Describe the bug

Fails to autocomplete relevant symbols. Diagnostics are no longer displayed or updated until a `:w`.

![coc-completions mov](https://user-images.githubusercontent.com/12477404/68901882-b57a6500-06eb-11ea-9548-82484855c12b.gif)

 Confirming completions from the dart language server mangles text e.g.:

    // completing type symbol Hello, cursor is at |
    Hel|

results in

    Hello H|

![coc-dartls-mangle-completion mov](https://user-images.githubusercontent.com/12477404/68901883-b612fb80-06eb-11ea-892d-e1bfb49539b5.gif)

Possible regression in either Coc.nvim or dart's analysis\_server. A couple days ago coc.nvim and dart worked in harmony.

Here's vim-lsc with vim-lsc-dart for comparison:

![coc-compare-lsc mov](https://user-images.githubusercontent.com/12477404/68901881-b57a6500-06eb-11ea-9d4f-16fe94c5fd2e.gif)

## Reproduce the bug

- Create file `mini.vim` with：

```vim
call plug#begin('$HOME/Desktop/testcocnvim/cocconf')

Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}

call plug#end()
```

With Coc config:

```json
{
  "languageserver": {
    "dart": {
      "command": "dart",
        "args": [
          "/usr/local/opt/dart/libexec/bin/snapshots/analysis_server.dart.snapshot",
          "--lsp"
        ],
        "filetypes": ["dart"],
        "disableDynamicRegister": true,
        "trace.server": "verbose"
    }
  }
}
```

- Start neovim with command: `nvim -u mini.vim`

- `:e test.dart`
- `set filetype=dart`
- Write some dart and
- Try confirming `<c-y>` a completion result.

**Comment by oblitum** [comment]
Works fine for me.

```
Dart VM version: 2.6.0 (Thu Oct 24 17:52:22 2019 +0200) on "linux_x64"
vim version: NVIM v0.4.3
node version: v13.1.0
coc.nvim version: 0.0.74
term: tmux-256color
platform: linux
```

**Comment by PrestonKnopp** [comment]
@oblitum Thanks for checking it out. I'll have to test some more.

The interesting thing is that it was working wonderfully just a couple days ago. The strange thing is that only coc seems to be affected. Lsc, vscode, intellij, etc, work as expected.

**Comment by chemzqm** [comment]
Try latest release branch.

**Comment by chemzqm** [comment]
Try remove `disableDynamicRegister: true` in your configuration, dart language server used to have some bug with it.

**Comment by PrestonKnopp** [comment]
Awesome, it's working now after switching to the latest release branch while having the same minimal configuration as posted above. I haven't removed `disableDynamicRegister: true`. I will remove it now, however.

Thank you very much!
