### ISSUE TITLE
Dart: Missing completions 

### ISSUE THREAD

**Issue by Urfoex** [neoclide/coc.nvim#1353]
I am missing some elements from the completion suggestions, especially those after a .

Fresh project set up with `stagehand console-full`

Missing completion for the function:
![consolesample01](https://user-images.githubusercontent.com/1561354/69091099-e3dca500-0a49-11ea-8307-cc415946eb79.png)

[consolesample01.cocinfo.zip](https://github.com/neoclide/coc.nvim/files/3860524/consolesample01.cocinfo.zip)

Fresh project set up with `stagehand server-shelf`

Missing completion for int:
![serversample01 noint](https://user-images.githubusercontent.com/1561354/69091169-079feb00-0a4a-11ea-9c8b-a7b780dae5f5.png)

Missing completion for list:
![serversample01 nolist](https://user-images.githubusercontent.com/1561354/69091201-15557080-0a4a-11ea-9882-c73577f54bd4.png)

[serversample01.cocinfo.zip](https://github.com/neoclide/coc.nvim/files/3860525/serversample01.cocinfo.zip)

Comparison to VSCode:
![serversample_vscode](https://user-images.githubusercontent.com/1561354/69091226-20a89c00-0a4a-11ea-96a0-46cae3caa1e7.png)

Some completion is working:
![serversample01 int](https://user-images.githubusercontent.com/1561354/69091810-59954080-0a4b-11ea-8d92-c1bd837c3c40.png)

coc-settions part (as found on [wiki](https://github.com/neoclide/coc.nvim/wiki/Language-servers#dart) ):
 ```
  "dart": {
      "command": "dart",
      "args": [
        "/usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot",
        "--lsp"
      ],
      "filetypes": ["dart"],
      "disableDynamicRegister": true,
      "trace.server": "verbose"
    },

```
Dart:
```
$ dart --version
Dart VM version: 2.6.1 (Unknown timestamp) on "linux_x64"
```

**Comment by Urfoex** [comment]
Might be related to [#1347](https://github.com/neoclide/coc.nvim/issues/1347)

**Comment by fannheyward** [comment]
Try latest release https://github.com/neoclide/coc.nvim/issues/1347#issuecomment-555307651

**Comment by Urfoex** [comment]
Yeah, that seems to work.
But now getting: `[Trace - 11:26:16] Received response 'textDocument/completion - (1)' in 15ms. Request failed: Invalid file path (-32003).`
with Dart 2.6.1 stable and 2.7.0 dev. With 2.5.2 stable it works.

Maybe that is related to [https://github.com/dart-lang/sdk/issues/38694](https://github.com/dart-lang/sdk/issues/38694)
But as that is closed, it may be something different.
