### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by lovesegfault** [neoclide/coc.nvim#1354]
**Is your feature request related to a problem? Please describe.**
The current release, 0.0.74, is ancient with over 2000 commits having happened since. On distros like NixOS, that package the release and not some set commit (due to needing the `index.js`) this means the shipped coc is ancient.

**Describe the solution you'd like**
For a new release to be cut. 

**Describe alternatives you've considered**
To figure out how to generate `index.js`, patch the package formula to do it for a tagged commit

**Comment by lovesegfault** [comment]
Actually now I don't know what's going on here, are `release` and `master` just completely divergent branches?

**Comment by chemzqm** [comment]
>  are release and master just completely divergent branches?

Yes.

**Comment by oblitum** [comment]
@lovesegfault release is just to get compiled typescript, so people have no need to compile.

**Comment by lovesegfault** [comment]
Oh, I see, so the currently release is not _as_ old as I thought, but nonetheless it's been a fair amount of time, so perhaps the ticket is still valid?

**Comment by oblitum** [comment]
@lovesegfault I don't think so, release branch lags on master by just a few irrelevant commits most of the time.

**Comment by lovesegfault** [comment]
@oblitum I mean tagging a release so it shows up in https://github.com/neoclide/coc.nvim/releases

**Comment by oblitum** [comment]
@lovesegfault right, but, do you need a tag given there's an up-to-date release branch? Personally I just pick from release branch and don't care for tags anymore.

**Comment by lovesegfault** [comment]
@oblitum We'll see, I'm trying to figure out whether NixOS's update script will screw up the branch to take revisions from or not, I'll update in a bit.

**Comment by lovesegfault** [comment]
Alright, fix enroute

https://github.com/NixOS/nixpkgs/pull/73740

Someone needs to manually update the revision now though, which is the same as before.
