### ISSUE TITLE
Replace mode

### ISSUE THREAD

**Issue by Pgaudreau** [neoclide/coc.nvim#1355]
## versions

vim version: NVIM v0.4.3
node version: v12.12.0
coc.nvim version: 0.0.74-1ff50ec3b0
term: iTerm.app
platform: darwin

## Output channel: highlight

[Info  - 1:10:01 AM] Highlight server running in node v12.12.0

## Describe the bug

When entering REPLACE mode, the numbers can't be typed, except 0. When the first character is typed, the following ones can be numbers. I believe it has to do with the option ->  "suggest.noselect": false <- in coc-settings.json. When I put it to false, the bug disappear.

## Reproduce the bug

Set -> "suggest.noselect": true <- and try typing numbers in replace mode (1-9).

**Comment by fannheyward** [comment]
I've tested with `"suggest.noselect": true`, and can't reproduce.

**Comment by Pgaudreau** [comment]
Oh my! my bad, it's late!
I mean : **"suggest.numberSelect": true**

**Comment by fannheyward** [comment]
The same, I can also type numbers with `"suggest.numberSelect": true`.
