### ISSUE TITLE
Hello, how can I set the highlight of this area?

### ISSUE THREAD

**Issue by wh1le** [neoclide/coc.nvim#1356]
Hello, thank you for the nice tool! 
Is it possible to highlight this area with the black color?

<img width="169" alt="Screen Shot 2019-11-20 at 11 36 11 AM" src="https://user-images.githubusercontent.com/14846508/69222286-345b1c00-0b8a-11ea-9dac-2c90056ce33d.png">

**Comment by chemzqm** [comment]
Checkout vim's help.

**Comment by wh1le** [comment]
Thanks for help.

**Comment by fox-tek** [comment]
Hello,
I don't want to be annoying, but I've been searching vim, CoC's docs, several configuration made by people out there...
And I still can't find how to change the colour of this column, which really doesn't look good on my plain black theme...
![image](https://user-images.githubusercontent.com/5567164/70054601-28367c00-15d8-11ea-97ab-a55355f3abfc.png)

**Comment by fox-tek** [comment]
Never mind I found it. You need to set `highlight SignColumn`. Took me way too long to find this out...
