### ISSUE TITLE
Allow to config multiple workspace folders rootPattern lookup ordering

### ISSUE THREAD

**Issue by jackysee** [neoclide/coc.nvim#1357]
**Is your feature request related to a problem? Please describe.**
Having a subfolder of client side code inside project, plugin like `coc-prettier` would need to resolve a correct workspace.
```
project
├── .git
├── server
│   ├── ...
├── client
│   ├── .pretteric.js
│   ├── package.json
│   ├── node_modules
│   │   ├── prettier
```
We can adopt the multiple workspace setting like,
```
    "coc.preferences.rootPatterns": ["package.json", ".vim", ".git", ".hg"]
```
But it seems that current lookup method would fail on nesting folder, i.e.
open `vim` at `project` (cwd), and then open file `client/src/someFile.js`, it will try:

- `project/package.json` --> not found
- `project/.vim` --> not found
- `project/.git` --> found! set as workspace folder

So plugin like `coc-prettier` won't get the correct config.

**Describe the solution you'd like**
A setting like `coc.preferences.rootPatternLookupFolderFirst: true` so that the look up order is

- `project/package.json` --> not found
- `project/client/package.json` --> found! set as workspace folder

**Comment by chemzqm** [comment]
No, you can start vim in client folder.
