### ISSUE TITLE
Floating documentation window missing

### ISSUE THREAD

**Issue by tbrodbeck** [neoclide/coc.nvim#1358]
## Result from CocInfo
```
## versions

vim version: NVIM v0.4.3
node version: v12.13.1
coc.nvim version: 0.0.74-266a37f273
term: iTerm.app
platform: darwin

## Messages

```

## Describe the bug

I just started using coc. So far I can get everything to work, besides the floating window (in python). 

I tried to put
```
{
"suggest.enablePreview": true,
"suggest.floatEnable": true,
}
```
in my `:CocConf` but it did not help. `:echo exists('##CompleteChanged') && exists('*nvim_open_win') `returns 1. And adding the coc example configuration does not help either.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  call plug#begin('~/.config/nvim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()
  ```

## Screenshots (optional)
![Screenshot 2019-11-20 at 21 32 01](https://user-images.githubusercontent.com/24418160/69275734-44501b80-0bdd-11ea-812f-c53a7e2b660e.jpg)

**Comment by fannheyward** [comment]
Do you installed `coc-python`?

**Comment by chemzqm** [comment]
We don't have AI support for completion which just works yet, you have to configure language servers.

**Comment by tbrodbeck** [comment]
> Do you installed `coc-python`?

Thank you. This was the missing piece. Now I got it :)
