### ISSUE TITLE
Cannot use iskeyword in around completion source

### ISSUE THREAD

**Issue by nekowasabi** [neoclide/coc.nvim#1360]
## versions

vim version: NVIM v0.5.0-dev
node version: v10.8.0
coc.nvim version: 0.0.74-266a37f273
term: screen-256color
platform: linux

## Describe the bug
I want to completion by alphabet only.

But completion list shows Japanese(Multibyte) character candidates.

So, I set iskeyword like this.

`set iskeyword=@`

But this cannot work.

## minimal vimrc
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
messages   autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/plugged')
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
call plug#end()

# screenshot

![sc](https://user-images.githubusercontent.com/3657473/69320463-99933800-0c84-11ea-8dae-a2658042cd24.jpg)

**Comment by chemzqm** [comment]
It's expected because we consider multi byte characters as keywords, just like vim.
