### ISSUE TITLE
No completion with ccls for cpp filetype set through autocmd

### ISSUE THREAD

**Issue by Nelyah** [neoclide/coc.nvim#1362]
## versions

vim version: NVIM v0.4.2
node version: v12.12.0
coc.nvim version: 0.0.74-3a7f1335ae
term: iTerm.app
platform: darwin

## Messages
1
## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /Users/Mia/testDir
fatal: not a git repository (or any of the parent directories): .git

## Output channel: languageserver.ccls

22:20:42                initialize.cc:274 I initialize in directory /Users/Mia/testDir with uri file:///Users/Mia/testDir
22:20:42                initialize.cc:297 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":"/tmp/ccls","format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":["-I","Common/","-I","Command/","-I","json_cpp_code/","-isystem","/Library/Developer/CommandLineTools/usr/include/c++/v1","-isystem","/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include","-isystem","/Library/Developer/CommandLineTools/usr/include","-isystem","/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include","-isystem","/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"],"pathMappings":[],"resourceDir":"/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1"},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":false,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
22:20:42                initialize.cc:326 I use -resource-dir=/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1
22:20:42                initialize.cc:359 I workspace folder: /Users/Mia/testDir/
22:20:42                initialize.cc:384 I start 12 indexers
22:20:42                initialize.cc:392 I dispatch initial index requests
22:20:42                  pipeline.cc:485 I loaded project. Refresh semantic highlight for all working file.
22:20:42                  pipeline.cc:351 I parse /Users/Mia/testDir/test.ter
22:20:42              sema_manager.cc:744 I create session for /Users/Mia/testDir/test.ter

## Issue

I have CoC working perfectly with ccls for `cpp` and `h` files. However if I set `autocmd! BufNewFile,BufRead *.bar set filetype=cpp` in my init.vim, I don't get any completion or linting from CoC. Is there something I'm missing?

Also, if I open a file `foo.cpp` then rename it (without leaving vim) to `foo.bar`, the completion engine will work.

**Comment by chemzqm** [comment]
It's problem of your ccls, you can chekcout output channel https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
