### ISSUE TITLE
premium features for intelephense lsp

### ISSUE THREAD

**Issue by fabiosal** [neoclide/coc.nvim#1368]
Is Coc.nvim supporting premium features from [intelephense](https://intelephense.com/) lsp ?

> Premium features:
> Easily rename a symbol within a document or across the entire workspace.
> Fold definitions, blocks, use declarations, heredoc strings, comments and custom regions.
> Quickly find all implementations of an interface or abstract symbol.
> Quickly navigate to interface and abstract method declarations.
> Quickly navigate to variable type definitions.

if yes how can i configure it ?
is there any parameter to handle the license key ?

Thank you

**Comment by fannheyward** [comment]
There is No premium support.

**Comment by fannheyward** [comment]
FYI https://github.com/marlonfan/coc-phpls/issues/29

**Comment by AW3i** [comment]
Is there something we could implement to make it work?
Also relevant bmewburn/intelephense-docs#12

**Comment by marlonfan** [comment]
[coc-phpls](https://github.com/marlonfan/coc-phpls/releases/tag/2.1.0) It's supported now
