### ISSUE TITLE
coc-rename doesn't seem to do anything

### ISSUE THREAD

**Issue by thisisrandy** [neoclide/coc.nvim#1369]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.2
node version: v12.13.0
coc.nvim version: 0.0.74-dc888b4a6e
term: xterm-256color
platform: linux

## Messages

## Output channel: prettier


## Output channel: snippets


## Output channel: tsserver

[Info  - 1:11:47 PM] Forking TSServer
PATH: /home/randy/.pyenv/plugins/pyenv-virtualenv/shims:/home/randy/.pyenv/shims:/home/randy/.pyenv/bin:/usr/local/go/bin:/home/randy/go/bin:/home/randy/.yarn/bin:/home/randy/.local/bin/:/home/randy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/randy/.fzf/bin 
[Info  - 1:11:47 PM] Started TSServer
{                                                                                                                        
  "path": "/home/randy/git/tell-me-a-story/frontend/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.7.2",
    "version": "3.7.2"
  }
}

## Output channel: eslint

[Info  - 1:11:47 PM] ESLint server running in node v12.13.0
[Info  - 1:11:48 PM] ESLint library loaded from: /home/randy/git/tell-me-a-story/frontend/node_modules/eslint/lib/api.js

## Output channel: highlight

[Info  - 1:11:47 PM] Highlight server running in node v12.13.0
```

## Describe the bug

coc-rename appears to do nothing. I've used it successfully before, so this is a regression, though I couldn't say from when.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  nnoremap <F2> <Plug>(coc-rename)
  ```

- Add the following to coc-settings.json
```json
"tsserver.trace.server": "verbose"
```

- Start (neo)vim with command: `vim -u mini.vim`

- Create `test.js` with the following content:
```javascript
let foo = "bar"
foo = "baz"
```
- With the cursor on `foo` at either position, press `<F2>`
- Observe that nothing happens
- `:CocCommand workspace.showOutput`
- Observe that there is no output corresponding to `coc-rename`
- Repeat the same procedure for python and presumably other languages

**Comment by chemzqm** [comment]
Could be problem of your key mapping.

**Comment by atremblay** [comment]
Having similar issue

```
## versions
vim version: NVIM v0.4.2
node version: v13.1.0
coc.nvim version: 0.0.74-266a37f273
term: xterm-256color
platform: linux
```

I have the key mapping set to
`nmap <F6> <Plug>(coc-rename)`

It enters into renaming mode, if I can call it that way and, write a new name, hit enter and nothing is renamed. Just a no op.

**Comment by thisisrandy** [comment]
@chemzqm you are correct, `nmap <F2> <Plug>(coc-rename)` works fine. It looks like I reshuffled my mappings at some point a couple of months back and just hadn't tried to use it since. Thanks for pointing that out.
