### ISSUE TITLE
coc doesn't work with ale

### ISSUE THREAD

**Issue by cvlmtg** [neoclide/coc.nvim#137]
**Describe the bug**
If I install ale, coc stops working. completion doesn't work and `:messages` says

```
[coc.nvim] Error on InsertEnter: Cannot read property 'clearHighlight' of undefined
[coc.nvim] Error on TextChanged: Cannot read property 'filetype' of undefined
[coc.nvim] Error on TextChanged: Cannot read property 'filetype' of undefined
[coc.nvim] Error on TextChanged: Cannot read property 'filetype' of undefined
```

**To Reproduce**
1. Install coc.nvim with coc-tsserver and see that it is working
2. Install ale and now coc.nvim no longer works

**Expected behavior**
coc.nvim should not break when ale is installed

**Desktop (please complete the following information):**
 - Terminal: kitty 0.12.3 and tmux
 - Version: nvim v0.3.2-797-g500345aea

**Comment by chemzqm** [comment]
I'm using coc.nvim and ale as well, but I can't reproduce this problem.

**Comment by cvlmtg** [comment]
I'll try to set up a minimal config with a clean install and see if it depends on some of my configuration, however I'm not sure I'll be able to have some spare time soon. meanwhile thanks for fixing coc-eslint, now this problem is not urgent anymore :)

**Comment by chemzqm** [comment]
When the current document is null you'll get errors like these, it was fixed at https://github.com/neoclide/coc.nvim/commit/d56d961ca2afdfbf2e95a93467a8e7ff02abf270.
Reopen this issue if you still get these messages.
