### ISSUE TITLE
Change SignColumn indicators

### ISSUE THREAD

**Issue by NerdyPepper** [neoclide/coc.nvim#1370]
The default signcolumn indicator for warnings is the Unicode warning sign (`⚠️`), which is not present on all fonts.

Perhaps, this icon/character could be configured by the user in `coc-settings.json` (if there is an option, please feel free to close this issue, I have not been able to find it) like how ALE has an option:
```
let g:ale_sign_error = "!"
let g:ale_sign_warning = ">>"
```

Attached screenshot:  
![screenshot](https://files.nerdypepper.tech/Ju.png).

**Comment by fannheyward** [comment]
You can change `diagnostic.errorSign` in coc-settings.json.
