### ISSUE TITLE
coc#on_enter() not working in vim 8

### ISSUE THREAD

**Issue by kibs** [neoclide/coc.nvim#1372]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 23:05:13)
node version: v13.2.0
coc.nvim version: 0.0.74-dc888b4a6e
term: iTerm.app
platform: darwin

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
## Output channel: prettier


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /Users/sune
fatal: not a git repository (or any of the parent directories): .git

## Output channel: snippets


## Output channel: highlight

[Info  - 09.35.58] Highlight server running in node v13.2.0
```

## Describe the bug

Using the mapping

`inoremap <silent><expr> <CR> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"`

from the readme, and when using the coc-pairs extension, the cursor would automatically be indented correctly in neovim, but not in vim.

## Reproduce the bug

mini.vim
```
set nocompatible
set runtimepath^=/Users/sune/.vim/plugged/coc.nvim
filetype plugin indent on

inoremap <silent><expr> <CR> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

### neovim 4.3

![neovim](https://i.imgur.com/EEPZgzS.gif)

### vim 8.1

![vim](https://i.imgur.com/LtaBEXB.gif)

**Comment by fannheyward** [comment]
Reproduced. After `Enter` event, nvim does some `CursorMovedI` but vim not. Haven't found any reason yet.

**Comment by kibs** [comment]
@fannheyward could you give me some pointers where in the codebase this is implemented, maybe I could take a look, but I can’t find where to start

**Comment by fannheyward** [comment]
1. https://github.com/neoclide/coc.nvim/blob/master/autoload/coc.vim#L38
2. https://github.com/neoclide/coc.nvim/blob/master/src/events.ts#L45

**Comment by kibs** [comment]
This is the log from when pressing Enter in NVIM

```
2019-11-29T11:03:57.765 DEBUG (pid:81534) [events] - Event: Enter [ 1 ]
2019-11-29T11:03:57.766 DEBUG (pid:81534) [events] - Event: CursorMovedI [ 1, [ 2, 2 ] ]
2019-11-29T11:03:57.766 DEBUG (pid:81534) [events] - Event: TextChangedI [ 1 ]
2019-11-29T11:04:01.971 DEBUG (pid:81534) [events] - Event: CursorHoldI [ 1 ]
```

And this is the log from VIM

```
2019-11-29T11:05:32.238 DEBUG (pid:81281) [events] - Event: Enter [ 1 ]
2019-11-29T11:05:32.238 DEBUG (pid:81281) [events] - Event: CursorMovedI [ 1, [ 2, 2 ] ]
2019-11-29T11:05:32.238 DEBUG (pid:81281) [events] - Event: TextChangedI [ 1 ]
2019-11-29T11:05:36.242 DEBUG (pid:81281) [events] - Event: CursorHoldI [ 1 ]
```

It looks like it receives the same events, so I guess the problem lies further down in the code. From looking at your pointers it seems to call some handlers. Which handler would this be in this case?

**Comment by kibs** [comment]
@fannheyward got the node debugger up and running. If i set a breakpoint at 

https://github.com/neoclide/coc.nvim/blob/master/src/handler/index.ts#L152

and have coc-pairs installed, then in neovim the prevChar variable is "{" but in vim it is "}" eg. the nextChar. If i don't have coc-pairs installed and it doesn't automatically inserts a } then the on_enter works nicely

**Comment by kibs** [comment]
So to sum up, in Vim when calling workspace.getDocument(bufnr) the result will be with lines from before the "enter" and in Neovim the doc has lines from after the "enter" and the following code assumes what happens in Neovim. I have no idea how to detect og even handle that. But I hope my debugging will help you.
