### ISSUE TITLE
Yank diagnostic string for current line

### ISSUE THREAD

**Issue by Rom888** [neoclide/coc.nvim#1374]
Great plugin!

I am using coc.nvim with coc-tsserver and coc-eslint.
It would be helpful to yank the current diagnostic string (same as in statusline) to the clipboard and after that to use it for searching a rule description in browser. 

For example for this message from statusline:
[eslint no-use-before-define] [E] ....
it would be helpful to find:
https://github.com/eslint/eslint/blob/master/docs/rules/no-use-before-define.md

I found function StatusDiagnostic() in 'coc-status-manual' and tried to use it, but instead of a full message that I see in the statusline, I got 'E16 W2  TSC' string.
Do you have any idea, how could I yank full diagnostic message to clipboard for current line in vimscript?

```
.vimrc:

nnoremap <silent> <leader>diag :call StatusDiagnosticToClipboard()<CR>
function! StatusDiagnosticToClipboard() abort
  let info = get(b:, 'coc_diagnostic_info', {})
  if empty(info) | return '' | endif
  let msgs = []
  if get(info, 'error', 0)
    call add(msgs, 'E' . info['error'])
  endif
  if get(info, 'warning', 0)
    call add(msgs, 'W' . info['warning'])
  endif

  call setreg('+', join(msgs, ' ') . ' ' . get(g:, 'coc_status', ''))

endfunction
```

**Comment by chemzqm** [comment]
`b: coc_diagnostic_info` contains count only, checkout `:h coc-action-diagnosticList`

**Comment by Rom888** [comment]
Ok, thank you, it helped me find CocAction('diagnosticList') and eventually I created this function to yank diagnostic string into clipboard:
```
nnoremap <silent> <leader>diag :call StatusDiagnosticToClipboard()<CR>
function! StatusDiagnosticToClipboard()
  call setreg('+','')
  let diagList=CocAction('diagnosticList')
  let line=line('.') 
  for diagItem in diagList
    if line == diagItem['lnum']
      let str=diagItem['message']
      call setreg('+',str)
      return
    endif
  endfor 
endfunction
```

**Comment by SolaWing** [comment]
I find the float window can use <Ctrl-W><Ctrl-W> jump into.
so just jump into the window, select all,  yank, and jump back is ok.
for wrong press, it should guard float window popup.

**Comment by jqhr** [comment]
@SolaWing 
> 
> 
> I find the float window can use jump into.
> so just jump into the window, select all, yank, and jump back is ok.
> for wrong press, it should guard float window popup.


For neovim, use <kbd>ctrl</kbd> and <kbd>p</kbd> could move cursor into float window. BUT for vim, you can't do it because vim' popup window  is not common window, 

> https://github.com/vim/vim/pull/7555#issuecomment-752564777
