### ISSUE TITLE
Triggering a specific completion source

### ISSUE THREAD

**Issue by jeysal** [neoclide/coc.nvim#1376]
**Is your feature request related to a problem? Please describe.**
When writing code in TypeScript I use both `coc-tsserver` and `coc-tabnine` because they are good at completing different things (e.g. tsserver knows all available properties after `obj.`, while tabnine can sometimes write a whole line like `import React from 'react';` for you).
However, often I cannot easily access tabnine's completion options when I want to, because tsserver's options push them down too far or fill the menu, displacing them completely.

**Describe the solution you'd like**
I would like to create a key binding similar to my <C-space> coc#refresh() binding that opens a completion menu with items only from a specific source, like tabnine.
I've looked through the code a bit, and it seems like there is already a `source?: string` completion option, but I don't see a way to do this from vimscript at the moment.

**Describe alternatives you've considered**
I presume at some point coc.nvim's completion could become sophisticated enough that this will not be necessary, because it will always offer you the most relevant items from a combination of sources, but I'm not sure how feasible this is short-term.
To achieve this, we would need things like
* Interleaving completion items so that all sources are represented in the first few entries (afaik this might already be possible with scores, but tsserver does not implement them)
* Prioritizing a completion item that is suggested by multiple sources (not sure if coc.nvim can already do this)

**Additional context**
-

**Comment by chemzqm** [comment]
It's supported
https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L1062

**Comment by jeysal** [comment]
Must have missed that because I was looking for something called 'refresh' or 'complete' - thanks for adding this to the docs, will make it a lot easier to find!
