### ISSUE TITLE
floating window 挡住了光标

### ISSUE THREAD

**Issue by MaxJohnXiang** [neoclide/coc.nvim#1377]
vim version: NVIM v0.5.0-dev
node version: v12.12.0
coc.nvim version: 0.0.74
term: iTerm.app
platform: darwin

## Messages
vim-go: initialized gopls
1 line less
"0022.generate-parentheses/generate-parentheses.go" 11L, 180C [w]
1 line less
"0022.generate-parentheses/generate-parentheses.go" 11L, 180C [w]
[coc.nvim] Disabled
1 line less
"0022.generate-parentheses/generate-parentheses.go" 11L, 180C [w]
1 line less
1 line less
"0022.generate-parentheses/generate-parentheses.go" 9L, 130C [w]
1 line less
"0022.generate-parentheses/generate-parentheses.go" 9L, 130C [w]
1 line less
"0022.generate-parentheses/generate-parentheses.go" 9L, 130C [w]
"0022.generate-parentheses/generate-parentheses.go" 9L, 130C [w]
"~/.config/nvim/coc-settings.json" 28L, 798C [w]
1 line less
1 line less
"0022.generate-parentheses/generate-parentheses.go" 9L, 130C [w]
1 line less
"0022.generate-parentheses/generate-parentheses.go" 9L, 130C [w]
"0022.generate-parentheses/generate-parentheses.go" 9L, 130C [w]
## Output channel: languageserver.golang

[Info  - 6:06:16 PM] 2019/12/02 18:06:16 Build info
----------
golang.org/x/tools/gopls 0.2.0
    golang.org/x/tools/gopls@v0.2.1 h1:qXHEqJw4CqROYvoDXinY1ZOkyAFS+jcPOvLRK76dvwY=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20191108194844-46f05828f2fe h1:FNzasIzfY1IIdyTs/+o3Qv1b7YdffPbBXyjZ5VJJdIA=
    golang.org/x/xerrors@v0.0.0-20190717185122-a985d3407aa7 h1:9zdDQZ7Thm29KFXgAX/+yaf3eVbP7djjWp/dXAppNCc=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=

Go info
-------
go version go1.12.6 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xiangyun/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xiangyun/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/34/ljbmqv_n3_55nm9xk90ym6n80000gn/T/go-build616341989=/tmp/go-build -gno-record-gcc-switches -fno-common"

[Info  - 6:06:16 PM] 2019/12/02 18:06:16 24.545279ms for GOROOT=/usr/local/opt/go/libexec GOPATH=/Users/xiangyun/.go GO111MODULE=off PWD=/Users/xiangyun/.go/src/github.com/MaxJohnXiang/LeetCode go "list" "-m" "-json" "all", stderr: <<go list -m: not using modules
>> stdout: <<>>

[Info  - 6:06:16 PM] 2019/12/02 18:06:16 27.430016ms for GOROOT=/usr/local/opt/go/libexec GOPATH=/Users/xiangyun/.go GO111MODULE=off PWD=/Users/xiangyun/.go/src/github.com/MaxJohnXiang/LeetCode go "env" "GOMOD", stderr: <<>> stdout: <<
>>

[Info  - 6:06:16 PM] 2019/12/02 18:06:16 32.486486ms for GOROOT=/usr/local/opt/go/libexec GOPATH=/Users/xiangyun/.go GO111MODULE=off PWD=/Users/xiangyun/.go/src/github.com/MaxJohnXiang/LeetCode go "list" "-e" "-json" "-compiled=true" "-test=true" "-export=false" "-deps=true" "-find=false" "--" "builtin", stderr: <<>> stdout: <<{
	"Dir": "/usr/local/opt/go/libexec/src/builtin",
	"ImportPath": "builtin",
	"Name": "builtin",
	"Doc": "Package builtin provides documentation for Go's predeclared identifiers.",
	"Target": "/usr/local/opt/go/libexec/pkg/darwin_amd64/builtin.a",
	"Root": "/usr/local/opt/go/libexec",
	"Match": [
		"builtin"
	],
	"Goroot": true,
	"Standard": true,
	"GoFiles": [
		"builtin.go"
	]
}
>>

**Comment by MaxJohnXiang** [comment]
## 如何复现这个问题
 编辑Golang 文件(其他文件不会出现这个问题)
![image](https://user-images.githubusercontent.com/24894004/69951443-392bb280-1530-11ea-9ed9-0986fc45d7d2.png)
选择这个补全。

然后发现floating window 挡住了光标
![image](https://user-images.githubusercontent.com/24894004/69951486-4d6faf80-1530-11ea-850e-3eca85c14932.png)

![image](https://user-images.githubusercontent.com/24894004/69951503-552f5400-1530-11ea-951f-195aa77db559.png)

**Comment by fannheyward** [comment]
没办法复现，我的信息

```
vim version: NVIM v0.5.0-218-g70b606166
node version: v13.2.0
coc.nvim version: 0.0.74
term: iTerm.app
platform: darwin

❯ go get golang.org/x/tools/gopls@latest
go: finding golang.org/x/tools latest
```

**Comment by fannheyward** [comment]
```
    "gopls": {
      "command": "gopls",
      "filetypes": ["go"],
      "rootPatterns": ["go.mod", ".git/"],
      "initializationOptions": {
        "usePlaceholders": true,
        "completeUnimported": true
      }
    },
```

**Comment by fannheyward** [comment]
建议更新一下 gopls，看起来是返回的 method signature 有问题。
