### ISSUE TITLE
CocList and mouse

### ISSUE THREAD

**Issue by unphased** [neoclide/coc.nvim#1378]
## Describe the bug

Using the mouse wheel on a CocList window kills it and leaves garbage mouse values in the command line

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=~/.vim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Run `:CocList` or use go to references on some code that results in a Coc List with multiple references to navigate
- Note that is mouse wheel is used or arrow keys are used with key repeat (repeatedly pressed), the list gets killed and garbage ends up in the command line or in the buffer. 

The only safe way to navigate the CocList is with j/k bindings, which is fine generally, and allows the plugin to be usable, but if there's a way to make it not (what is essentially) bug out and crash on other methods of input, that would be very nice.

**Comment by chemzqm** [comment]
It works as expected on neovim and I can't fix it on vim8 because CocList use channel feature for comunication.

**Comment by unphased** [comment]
OK. I will check it out in neovim. Thanks for the feedback! Anyway, at least I can report that main essential functionality works great in vim8!
