### ISSUE TITLE
Twig file bug

### ISSUE THREAD

**Issue by Kazimazi** [neoclide/coc.nvim#138]
In a .html.twig file the linter shows an error for the 2. row that [css css-rparentexpected] [E] ) expected
```
<div class="ref-img gallery-folder"
        style="background-image: url({% path firstPhoto , 'reference' %})">
  <div class="gallery-overlay">
    <h3 class="gallery-title">{{ gallery.getName() }}</h3>
  </div>
</div>
```

**Comment by chemzqm** [comment]
It's expected, since coc-html (or html extension of VSCode) doesn't understand twig syntax.
I'm no familiar with swig, help needed to fix this problem.
