### ISSUE TITLE
Haskell lsp code action doesn't work

### ISSUE THREAD

**Issue by monkoose** [neoclide/coc.nvim#1381]
## Result from CocInfo

I have verbose for trace.server so CocInfo is long there is some parts
```
## versions

vim version: NVIM v0.4.3
node version: v13.2.0
coc.nvim version: 0.0.74-d83536aa4e
term: xterm-kitty
platform: linux

## Messages"src/Lib.hs" 61L, 2654C written
```
and 
```
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },

```

## Describe the bug

In haskell files with haskell-ide-engine enabled `CocList actions` shows only `convert to snippet` action, when there is actually some other possible actions.
Other vim lsp clients show possible actions (tested with vim-lsp and neovim-languageclient).

## Reproduce the bug
Here is sample Main.hs from any stack init project
```haskell
module Main where

import           Lib

main :: IO ()
main = print ("hello")
```
There is redundant brackets around "hello", and diagnostics shows it. But there is no action to automatically remove them.

- Create file `mini.vim` with：

You just need to have coc.nvim in your runtime and this settings in `coc-settings.json`
```json
{
  "languageserver": {
    "haskell": {
      "command": "hie-wrapper",
      "rootPatterns": [
        "stack.yaml",
        "cabal.config",
        "package.yaml"
      ],
      "filetypes": [
        "hs",
        "lhs",
        "haskell"
      ]
    }
  }
}
```

I can add screenshots with result of `CocList actions` and other lsp clients actions if you need them.

**Comment by chemzqm** [comment]
Should be problem of your language server, you can checkout output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by monkoose** [comment]
@chemzqm Yes, seems you are right. Tested in vscode itself and it doesn't have this actions too, it is weird that other lsp plugins have them.
Sorry for false alarm.
