### ISSUE TITLE
Cannot download mpls behind proxy

### ISSUE THREAD

**Issue by kcajf** [neoclide/coc.nvim#1382]
# Result from CocInfo

```
## versions

vim version: NVIM v0.3.8
node version: v10.16.3
coc.nvim version: 0.0.74-d83536aa4e
term: xterm-256color
platform: linux

## Messages
[coc.nvim] We encountered an issue downloading the Language Server. Reverting to the alternative, Jedi. Check the Python output panel for details. checkout output for detail.
5 lines yanked
## Output channel: Python

Starting Microsoft Python language server.
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.4.127.nupkg... download failed
Error: tunneling socket could not be established, cause=connect EINVAL 0.0.12.56:80 - Local (0.0.0.0:0)
Starting Jedi Python language engine.
```

## Describe the bug

Issue downloading mpls behind proxy. I have environment variables HTTP_PROXY, HTTPS_PROXY, http_proxy, https_proxy all set, and also "http.proxy" defined in coc config.

## Reproduce the bug

  ```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden

call plug#begin('~/.local/share/nvim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
  ```

CocConfig:
```
{
    "http.proxy": "proxyurl:port",
    "python.jediEnabled": false
}
```

then open any .py file

**Comment by fannheyward** [comment]
> connect EINVAL

`EINVAL` means invalid argument, please make sure your proxy set correctly in env.

**Comment by kcajf** [comment]
Thanks. They have the format `http://subdomain.domain.com:3128/`. Is that incorrect? They've used for years with all other tools

**Comment by fannheyward** [comment]
Set `"http.proxy": "subdomain.domain.com:3128"` in coc-settings.json. https://github.com/neoclide/coc.nvim/blob/master/data/schema.json#L255

**Comment by fannheyward** [comment]
The proxy format is only support `domain:port`, I'll add a fix for more format.

**Comment by kcajf** [comment]
Ok, I think I'd prefer to keep the `http://` since that's much more common, and other applications might expect it. A fix would be great please!

**Comment by kcajf** [comment]
And I tried setting it in coc settings in the format you describe (not modifying the env vars), but the error persists.

**Comment by fannheyward** [comment]
Can you get `Using proxy from...` log message from `:CocInfo`?

**Comment by kcajf** [comment]
No, doesn't seem like it.

**Comment by fannheyward** [comment]
No `Using proxy from...` means your proxy setting, both `coc-settings.json` and env are not working.

I've added proxy format check in https://github.com/neoclide/coc.nvim/commit/ce2cebccc94b52e7cd8f36770ffb8bbb539433a6 , you can try it on master branch.

**Comment by fannheyward** [comment]
Do you have `NO_PROXY` in your env?

**Comment by kcajf** [comment]
yep, I have a `no_proxy` define but it's only got localhost and internal services

**Comment by kcajf** [comment]
What's the easiest way to use master? I tried changing branch in my vim plug but now I get:
```
[coc.nvim] javascript file not found, please compile the code or use release branch.
```

**Comment by fannheyward** [comment]
`Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}` to build master.

**Comment by kcajf** [comment]
Built from master, same issue

`no_proxy`: 

```
10.0.0.0/8,company.com,*.company.com,local,*.local,127.0.0.1,localhost
```

**Comment by fannheyward** [comment]
After some debug, here are what I found:

1. It's not related coc.nvim built in downloader, `coc-python` has its own downloader with proxy support https://github.com/neoclide/coc-python/blob/62a54c0305/src/common/net/httpClient.ts#L15, so no `Using proxy from...` message is ok.
2. `coc-python`'s downloader uses https://github.com/request/request to do HTTP requests https://github.com/neoclide/coc-python/blob/62a54c0305/src/common/net/httpClient.ts#L20 , and  request supports env proxy: https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

Try to empty `http.proxy` in `coc-settings.json` and try again.

**Comment by kcajf** [comment]
ok, removed `http.proxy`, now getting
```
Starting Microsoft Python language server.
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.4.127.nupkg... download failed
Error: connect ECONNREFUSED 13.107.246.10:443
```

**Comment by kcajf** [comment]
javascript library issues aside, is there a way to manually download the requisite files as a temporary workaround?

**Comment by fannheyward** [comment]
@kcajf I didn't use coc-python, it looks that you can download it manually and put it at `~/.config/coc/extensions/coc-python-data/languageServer.x.x.xx` https://github.com/neoclide/coc-python/issues/80

@chemzqm plz transfer this issue to `coc-python`, it's coc-python issue.

**Comment by GianniGi** [comment]
still have the bug behind a proxy
