### ISSUE TITLE
Two neovim open the same file, quit the second crashed

### ISSUE THREAD

**Issue by chrisniael** [neoclide/coc.nvim#1383]
##  Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v13.2.0
coc.nvim version: 0.0.74-d83536aa4e
term: xterm-256color
platform: linux

## Messages
```

## Describe the bug

when I use two neovim open the same file, the second neovim will prompt me the file has been opened, then I press `q` to quit, the second neovim `core dumped`.

## Reproduce the bug

  ```vim
call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()
  ```

- Start (neo)vim with command: `nvim -u mini.vim`
- Operate vim, it's ok.

And I have try `nvim -u NONE -N`, it's ok too.

**Comment by chrisniael** [comment]
@chemzqm I have emailed you with the account of the machine, you can login and dubug.

**Comment by chemzqm** [comment]
It's because the prompt for swap file interfere with neovim's channel, try add `set noswapfile` to your vimrc or use `let g:coc_start_at_startup = 0` to disable coc.nvim start on vim start.
