### ISSUE TITLE
Provide an action to stop language server

### ISSUE THREAD

**Issue by kchibisov** [neoclide/coc.nvim#1384]
Some language servers are heavy on system resources (e.g. rls), that being said if you are working on a low powered system (e.g. notebook) or you just want to  quickly preview files it'll be nice to have an option to prevent server from running and burning system resources on such systems. Ideally an option like `CocStop` to pair with existing `CocStart` should make more sense.

I'm aware that there is `variable` to prevent auto start, however you usually don't mind from running coc on a small projects, and want to prevent it only on a large ones.

**Comment by chemzqm** [comment]
`:h coc-action-toggleService`
