### ISSUE TITLE
Warn about older node versions

### ISSUE THREAD

**Issue by dbalatero** [neoclide/coc.nvim#1388]
**Is your feature request related to a problem? Please describe.**

I had a bunch of mysterious 100% cpu spikes on my last laptop when running coc.nvim and I had to constantly `:CocRestart` and kill node from Activity Monitor.

I found this comment on Reddit: https://www.reddit.com/r/neovim/comments/ducnym/cocnvim_performance_is_brutal_on_large_projects/f74fex8/

Apparently running older Node versions can cause this lockup. This might explain why I don't have this problem after getting a new laptop from work.

**Describe the solution you'd like**

I can see two improvements:

* Call out clearly in README.md that you should run the latest Node
* Run `node -v` and get the Node version and warn about it, either in `:healthcheck` or in the status line output as a red warning?

**Comment by chemzqm** [comment]
You can specify node path, read the doc. Some nodejs version could be buggy.
