### ISSUE TITLE
Allow use of --strict when --interactive 

### ISSUE THREAD

**Issue by phcerdan** [neoclide/coc.nvim#1389]
**Is your feature request related to a problem? Please describe.**
I want to use:
```
:CocList --interactive symbols
```
 without the fuzzy behavior.

I though, reading the docs that:
```
:CocList --strict --interactive symbols
```
would work, but it doesn't. The fuzzy matcher is still on.

**Describe the solution you'd like**
```
:CocList --strict --interactive symbols
```
is interactive with the input but match the string strictly.

The motivation is that symbols can be huge and the fuzziness does not really help.

**Comment by chemzqm** [comment]
For symbols from language server, it's filtered by language server and LSP doesn't provide such kinds of options for filter by now/

**Comment by vvhitedog** [comment]
Just want to say, that I also found this confusing. It seems that there should be some documentation somewhere that says options may or may not be supported by the language server -- and this is a prime example to use. I also don't find the fuzzy search particularly helpful, but I can make it work for me for now.

**Comment by chemzqm** [comment]
It is documented
