### ISSUE TITLE
Unable to get createStatusBarItem to ever work or display

### ISSUE THREAD

**Issue by ckipp01** [neoclide/coc.nvim#1391]
Hello! We're currently in the process of converting the [Metals VS Code Extension](https://marketplace.visualstudio.com/items?itemName=scalameta.metals#overview) to a [coc extension](https://github.com/ckipp01/coc-metals). One of the issues we are running into is that we haven't been able to get the  `workspace.createStatusBarItem(0, { progress: true })` to work at all when using the coc api. 

We looked at some of the implementations that you have where this is used, for example in coc-java.

https://github.com/neoclide/coc-java/blob/796297d4a7df0e3761b682ecea9a00884ecaea52/src/downloader.ts#L7

And while using it locally, I've been unable to ever actually see these messages or spinner appear. If we create a very very basic activate function with the only purpose of opening a `statusBarItem`, I'm unable to ever get it to appear.

```
export async function activate(context: ExtensionContext) {
  const progressStatus = workspace.createStatusBarItem(0, { progress: true })
  progressStatus.text = "This will never appear
  progressStatus.show()
}
```
However, having the status bar item replace with just a `workspace.showMessage("This will appear")` will work just fine. Is there something I'm missing with `workspace.createStatusBarItem`? I'm unable to see them work correctly in other projects such as coc-java, and unable to implement them at all. Any advice would be greatly appreciated. Keep up the good work!

**Comment by fannheyward** [comment]
Can't reproduce. My usage is same as you: https://github.com/fannheyward/coc-texlab/blob/master/src/downloader.ts#L42

Maybe the status item has been covered by another status bar item or showMessage. Please make sure there is no more showMessage after `progressStatus.show()`.

**Comment by ckipp01** [comment]
Thanks for the quick reply. I'm a bit baffled if you have this working on your end. Once we are connected and the server is talking to coc.nvim, everything is working just fine like so, and the spinner works great.

<img width="487" alt="Screenshot 2019-12-10 at 07 13 14" src="https://user-images.githubusercontent.com/13974112/70500854-cec0d680-1b1c-11ea-9d20-5dc1b1cc0859.png">

However, any time before that, I'm unable to manually call a status bar item at all. I've actually made a minimal reproduction that you can just load up that will be triggered on any file with the above code snippet, just the way you said that you did as well in coc-java.

https://github.com/ckipp01/coc-progress-test

The only thing the extension does is this.
```ts
import {ExtensionContext, workspace} from 'coc.nvim'

export async function activate(context: ExtensionContext) {
  workspace.showMessage('Hello, this will appear')
  let statusItem = workspace.createStatusBarItem(0, {progress: true});
  statusItem.text = 'This will never appear...';
  statusItem.show();
}
```
When it loads it, you'll see the `Hello, this will appear` message that comes from `showMessage`, but the `statusItem` will never appear. Then if you remove the first `showMessage`, you won't see anything at all. I've tried on multiple machines, with vim and nvim, and with different terminals. Are you able to confirm that if you load this, you get a statusItem to appear and you see `This will never appear...`?

**Comment by fannheyward** [comment]
<img width="721" alt="2019-12-1014 41 28" src="https://user-images.githubusercontent.com/345274/70502282-50cff000-1b5b-11ea-95e4-62f5e90bcaf3.png">

Just clone your repo and `yarn`, everything works as expect.

**Comment by ckipp01** [comment]
Ahhhh of course, if you don't have the coc integration enabled in your status line it won't appear, which was happening to me. Is there a way in the coc api to easily get a spinner like it appears in the image here where the `workpace.showMessage` appears?
![image](https://user-images.githubusercontent.com/13974112/70502901-5bba5e80-1b22-11ea-93de-3353cd5b7cff.png)
My main concern is being able to display progress to the users that don't have any statusline integration enabled.

**Comment by fannheyward** [comment]
AFAIK, you can't.

**Comment by ckipp01** [comment]
Alright, thanks. I appreciate it!
