### ISSUE TITLE
Improve control over header auto-inclusion (C / C++)

### ISSUE THREAD

**Issue by fox-tek** [neoclide/coc.nvim#1394]
Hi
I've been searching the documentations and issues but couldn't find anything about this so here I am.
I mainly code in C, and I've noticed some annoying behaviour from CoC ─ or is it just clangd ? I don't know
This annoying behaviour comes in two flavours but is always about header auto-inclusion on completions.

- For both examples, I'll just refer to the repo I'm working on as **`.`**.
- I'm using a `compile_commands.json` generated using `compiledb` with the command `compiledb -no compile_commands.json make -ki -C .`.
- I'm using a `tags` file generated using `universal-ctags` with the command `ctags -R .`.

**First issue:**
Let's say I made a macro in `./lib/libfox/extra/include/define/fox_macro.h` like `__Anonnull` for  `__attribute__((nonnull))`.
`fox_macro.h` and a bunch of other preprocessor headers are in included in `./lib/libfox/extra/include/fox_define.h`
During compilation, I use `gcc [...] -iquote ./lib/libfox/extra/include`.
Now say I have included `fox_define.h` in a source, and I start typing `__Anon...`, I'm prompted with a snippet that completes  `__Anonnnull` but *forces* the inclusion of `define/fox_macro.h` even though it's already included via `fox_define.h`.
**First question:**
Is there any way to prevent that ? Maybe a variable to set to disable it ? Or a keymap/command to complete without including the header ?

**Second issue:**
Now let's say I want to use the `bool` type instead of int for convenience and clarity.
This type, for C projects, is defined in `<stdbool.h>` (mainly just a `_Bool` typedef).
Problem is, when I type `bool` without preemptively including `<stbool.h>`, the snippet  that includes something I don't want strikes again, and include C++'s `<cstdbool>`.
And it doesn't even propose me the `.h` version !
**Second question:**
Is it possible to prevent CoC or the language server from looking into C++ headers when I'm working on C files ?

If needed, these are the extensions I have installed:
- coc-tabnine 1.2.2
- coc-snippets 2.1.14
- coc-pairs 1.2.19
- coc-marketplace 1.5.0 
- coc-highlight
- coc-git 1.6.16
- coc-vimlsp 0.4.3
- coc-markdownlint 0.6.2
- coc-json 1.2.4
- coc-fish 1.0.10

I'm at your disposition for any complementary information, screenshots/gifs you would need to better understand the issue.
Thanks in advance.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout output channel https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
