### ISSUE TITLE
Delete . or -> after auto-completion (C++)

### ISSUE THREAD

**Issue by ColinKennedy** [neoclide/coc.nvim#1396]
**Is your feature request related to a problem? Please describe.**
When I get use type-completion, sometimes I forget if the object that I'm working with is a pointer or not. For example

```cpp
#include <vector>

int main() {
    std::vector<int>* foo;
    foo.|cursor|
}
```

Using ccls, I can get type-completion. And once I press enter to confirm "begin" as the method to select during auto-completion, my code looks like this

```cpp
#include <vector>

int main() {
    std::vector<int>* foo;
    foo.->begin|cursor|
}
```

**Describe the solution you'd like**
Instead of auto-expanding to

```cpp
#include <vector>

int main() {
    std::vector<int>* foo;
    foo.->begin|cursor|
}
```

I want it to know to remove the prefix dot

```cpp
#include <vector>

int main() {
    std::vector<int>* foo;
    foo->begin|cursor|
}
```

ccls was smart enough to know it's actually a pointer so it know to change the . into ->, too.

**Additional context**
This is a feature in YouCompleteMe that I've grown apparently too accustomed to :) . But it'd be great if this could be supported, as well.

My example configuration coc-settings.json looks like this:

```json
{
    "languageserver": {
        "ccls": {
            "command": "ccls",
            "filetypes": [
                "c",
                "cpp",
                "objc",
                "objcpp"
            ],
            "rootPatterns": [
                ".ccls",
                "compile_commands.json",
                ".vim/",
                ".git/",
                ".hg/"
            ],
            "initializationOptions": {
                "cache": {
                    "directory": "/tmp/ccls"
                }
            }
        }
    }
}
```

I wasn't sure if this is a feature request for coc.nvim or ccls itself. Feel free to re-direct me as needed.

**Comment by chemzqm** [comment]
Should be done by ccls or ccls extension.

**Comment by ColinKennedy** [comment]
I don't use coc-ccls if that's what you mean by ccls extension. I'll file an issue with ccls. Thanks!

**Comment by ele828** [comment]
It seems like its something to do with `additionalTextEdits`, which is mentioned in ccls release log.
@chemzqm 

![image](https://user-images.githubusercontent.com/8534639/74082473-49628f80-4a95-11ea-8675-f837df9155e5.png)
