### ISSUE TITLE
Autocomplete does not work when `set paste` is set

### ISSUE THREAD

**Issue by zoechi** [neoclide/coc.nvim#1397]
I copied from someone's dotfiles
```
" Leave paste mode when leaving insert mode
autocmd InsertLeave * set nopaste
```
and thought why not always enable paste because it annoyed me every time when it broke formatting when pasting from somewhere, so I added
```
autocmd InsertEnter * set paste
```
Now while I tried to make coc.nvim work for an Angular project,
after incrementally reducing `.vimrc` it turned out that this line broke autocomplete.
It's easily reproducible with this https://github.com/neoclide/coc.nvim#example-vim-configuration config and `:set paste`
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)                                                                                   │  syntax   √
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401 
```

I'm a VIm beginner and have no idea if this is a bug or working as intended,
but it might at least help others.

Thanks for all your great plugins!

**Comment by chemzqm** [comment]
You should remove `autocmd InsertEnter * set paste` and configure to vim's indent options.
It's expected behavior.
