### ISSUE TITLE
[NOOB Question] Python Language Server added in the plugin

### ISSUE THREAD

**Issue by r-learner** [neoclide/coc.nvim#14]
Thank you for creating the wonderful neovim plugin coc.nvim.

Per this news, https://blogs.msdn.microsoft.com/pythonengineering/2018/07/18/introducing-the-python-language-server/ , Python language server is officially added to vscode.

* It seems that Python Language Server already been added (https://github.com/neoclide/coc.nvim/blob/master/src/extensions/pyls/index.ts), which is same as the one mentioned in the news?

* In the doc, https://github.com/neoclide/coc.nvim/wiki/Language-servers, Python Language Server is not listed as the buildin server extensions.

Thank you very much.

**Comment by chemzqm** [comment]
1. No, pyls is not the one that VSCode offically plugin, it's easy to integrate with COC, but less featured compare to the official one of VSCode.
2. It should be listed there.

**Comment by r-learner** [comment]
@chemzqm, Thank you.

Closing the issue.
