### ISSUE TITLE
coc-pyls is not working

### ISSUE THREAD

**Issue by yardnsm** [neoclide/coc.nvim#140]
First of all - great plugin! It works really well for JavaScript / TypeScript files.

**Describe the bug**

It seems that `coc-pyls` is not working, as I'm getting an error the second I open a python file:

```
[3  - 1:09:16 PM] Starting client failed
TypeError: value.toLowerCase is not a function
    at Object.fromString (/Users/yardensm/dotfiles/nvim/nvim.conf/plugged/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:75:23)
    at LanguageClient.refreshTrace (/Users/yardensm/dotfiles/nvim/nvim.conf/plugged/coc.nvim/lib/language-client/client.js:2224:64)
    at LanguageClient.initialize (/Users/yardensm/dotfiles/nvim/nvim.conf/plugged/coc.nvim/lib/language-client/client.js:1974:14)
    at resolveConnection.then.connection (/Users/yardensm/dotfiles/nvim/nvim.conf/plugged/coc.nvim/lib/language-client/client.js:1954:25)

2018-10-31 13:09:16,985 UTC - INFO - pyls.python_ls - Starting PythonLanguageServer IO language server
```

Also, LSP features such as code completion and jump to definition are not working (completion is working very rarely).

I use Neovim.

**To Reproduce**
1. Install `coc-pyls`:
	
	```
	:CocInstall coc-pyls
	```
	
2. Create a python file in vim. I tried the following:

	```python
	import math

	def hello(num=5):
    	return math.cos(num)

	print(hello())
	```

3. Try to edit the file and use code completion, or jump to definition.

**Desktop (please complete the following information):**
 - Terminal: iTerm 2
 - Version: v3.1.7

**Additional context**

Part of the output of `:version`:

```
:version
NVIM v0.3.0
Build type: Release
```

`coc-settings.json`:

```jsonc
// vim:ft=jsonc

{
  // COC preferences
  "coc.preferences.diagnostic.enable": false,
  "coc.preferences.timeout": 200,

  // Pyls source
  "pyls.trace.server": false
}
```

**Comment by chemzqm** [comment]
You will get a warning about it after install coc-json by command `:CocInstall coc-json`.

pyls is not well maintained, a better one would be available soon.

**Comment by yardnsm** [comment]
Setting

```json
"pyls.trace.server": "off"
```

Works, but I still get the trace from the server in a split. Could it be a bug?

**Comment by chemzqm** [comment]
`"pyls.trace.server": "off"` only exclude LSP commucation for some language server, so you can receive other information that send by server in the output channel.

**Comment by chemzqm** [comment]
Got the issue:
>  ResourceNotFoundError: Resource </test.py> does not exist
[3  - 10:23:18 AM] Request textDocument/completion failed.
Message: ResourceNotFoundError: Resource </test.py> does not exist
Code: -32602
[object Object]

Does it happen with all your python files or some of them?

**Comment by yardnsm** [comment]
If the file is saved to disk (since I got `ResourceNotFoundError`) I don't get the new split with the trace, so that's probably the problem.

**Comment by chemzqm** [comment]
I can confirm is a bug of https://github.com/palantir/python-language-server, it doesn't works with file not saved to disk.

I've changed the `revealOutputChannelOn` option to `never` for coc-pyls, so you would not bothered.
