### ISSUE TITLE
How to force full document sync?

### ISSUE THREAD

**Issue by resolritter** [neoclide/coc.nvim#1401]
**Is your feature request related to a problem? Please describe.**

In commit `56c1a0deabdb19657c3e7ee5b3235a1b9a42ba8f` the option "forceFullSync" was removed.

You can see that by

`git diff 56c1a0deabdb19657c3e7ee5b3235a1b9a42ba8f~1..56c1a0deabdb19657c3e7ee5b3235a1b9a42ba8f`

**Describe the solution you'd like**

Please describe a way to force full document sync through the configuration.

**Comment by chemzqm** [comment]
You can't, but your language server should provide such kind of option if it can't handle document changes correctly.
