### ISSUE TITLE
CodeAction hangs upon being received in Vim 8.2

### ISSUE THREAD

**Issue by ckipp01** [neoclide/coc.nvim#1404]
## Result from CocInfo
```
vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 16:51:54)
node version: v10.16.3
coc.nvim version: 0.0.74-d83536aa4e
term: iTerm.app
platform: darwin
```

## Describe the bug

I've noticed that upon switching to VIM 8.2 there is a very large lag between coc receiving the response from the server to execute a code action vs the time it takes while using nvim. In nvim, it happens basically immediately. I've posted a gif below to show what is meant to happen. In the gif I'm using nvim.

![2019-12-15 09 57 31](https://user-images.githubusercontent.com/13974112/70860391-7117fa00-1f21-11ea-9132-b0ce808d039f.gif)

When I switch to the latest vim to test this, it will just hang. Right after I execute the `<leader> a` it gets stuck before I can do anything else. I've posted a gif below showing this activity. In the gif I'm using a minimal `.vimrc` that I've also posted below in the steps to reproduce.

![2019-12-15 10 02 02](https://user-images.githubusercontent.com/13974112/70860444-ff8c7b80-1f21-11ea-88e8-91d811f25b1d.gif)

It will sit and hang like this for around 45 seconds until the option for the code action appears.

## Reproduce the bug
Minimal `.vimrc`
```vim
set nocompatible

set runtimepath^=/Users/ckipp/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

let mapleader = ","

" Remap for do codeAction of selected region, ex: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap for do codeAction of current line
nmap <leader>ac  <Plug>(coc-codeaction)
" Fix autofix problem of current line
nmap <leader>qf  <Plug>(coc-fix-current)
```
This issue is while using Metals. You can install with `:CocInstall coc-metals` which will install Metals.

I've created a minimal project to illustrate this [here](https://github.com/ckipp01/code-action-test). Open the project in vim at the root of the project using the minimal vimrc. Navigate to Main.scala, import the build, and then you should see diagnostics appear letting you know that `Instant` is not found. Trigger a code action on top of Instant to import `Instant`.

## Extra Details

I've also looked at the trace, and in both nvim and vim, the same thing is being sent back from the server within the second, so it's not hanging because it's waiting on the server.

```
[Trace - 09:08:35 AM] Received request 'textDocument/codeAction - (3)'
Params: {
  "textDocument": {
    "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/src/main/scala/example/Hello.scala"
  },
  "range": {
    "start": {
      "line": 6,
      "character": 12
    },
    "end": {
      "line": 6,
      "character": 12
    }
  },
  "context": {
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 6,
            "character": 10
          },
          "end": {
            "line": 6,
            "character": 17
          }
        },
        "severity": 1,
        "code": "  val x \u003d Instant.now()",
        "source": "bloop",
        "message": "not found: value Instant"
      }
    ]
  }
}


[Trace - 09:08:36 AM] Sending response 'textDocument/codeAction - (3)'. Processing request took 270ms
Result: [
  {
    "title": "Import \u0027Instant\u0027 from package \u0027java.time\u0027",
    "kind": "quickfix",
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 6,
            "character": 10
          },
          "end": {
            "line": 6,
            "character": 17
          }
        },
        "severity": 1,
        "code": "  val x \u003d Instant.now()",
        "source": "bloop",
        "message": "not found: value Instant"
      }
    ],
    "edit": {
      "changes": {
        "file:///Users/ckipp/Documents/scala-workspace/test-project/src/main/scala/example/Hello.scala": [
          {
            "range": {
              "start": {
                "line": 6,
                "character": 10
              },
              "end": {
                "line": 6,
                "character": 17
              }
            },
            "newText": "Instant"
          },
          {
            "range": {
              "start": {
                "line": 3,
                "character": 0
              },
              "end": {
                "line": 3,
                "character": 0
              }
            },
            "newText": "import java.time.Instant\n"
          }
        ]
      }
    }
  }
]
```

Let me know if you need any further details or examples.

Thanks!

EDIT: It may be easier for you to just look at this with the tss-server instead. I just confirmed that the behavior is the same with the minimal `.vimrc` and a typescript project.

**Comment by fannheyward** [comment]
I've tested with mini.vim and tsserver, but can't reproduce this issue.

```vim
set nocompatible

set runtimepath^=~/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

nmap <leader>ac  <Plug>(coc-codeaction)
```

```ts
path.join('a','b')
```

This line shows error from tsserver `Cannot find name 'path'`, and `<leader>ac` on error to invoke code action, no hangs for vim.

```
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 16:52:17)
node version: v13.5.0
coc.nvim version: 0.0.74
term: iTerm.app
platform: darwin
```

**Comment by ckipp01** [comment]
I just tried this out again, and it seems that it is no longer hanging like it did when I first tried. I'm not sure if it was a change in `coc.nvim` or a patch in Vim, but the issue seems to be fixed.

Thanks for taking a look at this!
