### ISSUE TITLE
How to scroll Documentation that opened with SHIFT+K

### ISSUE THREAD

**Issue by knighht** [neoclide/coc.nvim#1405]
![Screenshot from 2019-12-15 20-12-50](https://user-images.githubusercontent.com/51082837/70863133-86b80e80-1f77-11ea-9cbc-c5785ba0bd84.png)
im trying to scroll the documentation but i don't know how to scroll it. Would you be able to help to do so.

im using vim 8.1

Many Thanks.

**Comment by OkanEsen** [comment]
Related(?): #1160

**Comment by knighht** [comment]
> Related(?): #1160

so you mean there is no options to do that ?

**Comment by chemzqm** [comment]
You have to write filter for the popup created by coc.nvim by now, you can scroll with mouse if you have mouse enabled.

**Comment by knighht** [comment]
> for

much oblige sir!, it helps me a lot.

**Comment by knighht** [comment]
> You have to write filter for the popup created by coc.nvim by now, you can scroll with mouse if you have mouse enabled.

how can I write filter created by coc.nvim ? If you wouldn't mind to give the code so that I could just copying in.

**Comment by fannheyward** [comment]
I'm using this function to scroll floating window: 

```vim
function! FloatScroll(forward) abort
  let float = coc#util#get_float()
  if !float | return '' | endif
  let buf = nvim_win_get_buf(float)
  let buf_height = nvim_buf_line_count(buf)
  let win_height = nvim_win_get_height(float)
  if buf_height < win_height | return '' | endif
  let pos = nvim_win_get_cursor(float)
  if a:forward
    if pos[0] == 1
      let pos[0] += 3 * win_height / 4
    elseif pos[0] + win_height / 2 + 1 < buf_height
      let pos[0] += win_height / 2 + 1
    else
      let pos[0] = buf_height
    endif
  else
    if pos[0] == buf_height
      let pos[0] -= 3 * win_height / 4
    elseif pos[0] - win_height / 2 + 1  > 1
      let pos[0] -= win_height / 2 + 1
    else
      let pos[0] = 1
    endif
  endif
  call nvim_win_set_cursor(float, pos)
  return ''
endfunction


inoremap <silent><expr> <down> coc#util#has_float() ? FloatScroll(1) : "\<down>"
inoremap <silent><expr>  <up>  coc#util#has_float() ? FloatScroll(0) :  "\<up>"
```

You can use `<up/down>` to scroll. Just tested with Neovim.

**Comment by oblitum** [comment]
I'm using this function for scrolling any floating window with arrow keys without exiting insert mode:

```vim
function! FloatScroll(forward) abort
  let float = coc#util#get_float()
  if !float | return '' | endif
  let buf = nvim_win_get_buf(float)
  let buf_height = nvim_buf_line_count(buf)
  let win_height = nvim_win_get_height(float)
  if buf_height < win_height | return '' | endif
  let pos = nvim_win_get_cursor(float)
  if a:forward
    if pos[0] == 1
      let pos[0] += 3 * win_height / 4
    elseif pos[0] + win_height / 2 + 1 < buf_height
      let pos[0] += win_height / 2 + 1
    else
      let pos[0] = buf_height
    endif
  else
    if pos[0] == buf_height
      let pos[0] -= 3 * win_height / 4
    elseif pos[0] - win_height / 2 + 1  > 1
      let pos[0] -= win_height / 2 + 1
    else
      let pos[0] = 1
    endif
  endif
  call nvim_win_set_cursor(float, pos)
  return ''
endfunction

inoremap <silent><expr> <down> coc#util#has_float() ? FloatScroll(1) : "\<down>"
inoremap <silent><expr>  <up>  coc#util#has_float() ? FloatScroll(0) :  "\<up>"
```

**Comment by knighht** [comment]
> I'm using this function for scrolling any floating window with arrow keys without exiting insert mode:
> 
> ```viml
> function! FloatScroll(forward) abort
>   let float = coc#util#get_float()
>   if !float | return '' | endif
>   let buf = nvim_win_get_buf(float)
>   let buf_height = nvim_buf_line_count(buf)
>   let win_height = nvim_win_get_height(float)
>   if buf_height < win_height | return '' | endif
>   let pos = nvim_win_get_cursor(float)
>   if a:forward
>     if pos[0] == 1
>       let pos[0] += 3 * win_height / 4
>     elseif pos[0] + win_height / 2 + 1 < buf_height
>       let pos[0] += win_height / 2 + 1
>     else
>       let pos[0] = buf_height
>     endif
>   else
>     if pos[0] == buf_height
>       let pos[0] -= 3 * win_height / 4
>     elseif pos[0] - win_height / 2 + 1  > 1
>       let pos[0] -= win_height / 2 + 1
>     else
>       let pos[0] = 1
>     endif
>   endif
>   call nvim_win_set_cursor(float, pos)
>   return ''
> endfunction
> 
> inoremap <silent><expr> <down> coc#util#has_float() ? FloatScroll(1) : "\<down>"
> inoremap <silent><expr>  <up>  coc#util#has_float() ? FloatScroll(0) :  "\<up>"
> ```
> 
> ![](https://camo.githubusercontent.com/01206d6e90f331cad3981ceeb61e6943d084d14d/68747470733a2f2f66696c65732e6769747465722e696d2f6e656f636c6964652f636f632e6e76696d2f6231514e2f73637265656e636173742e676966)

thanks for the help. but, i can only open the docs with shift+k key in normal mode (does'nt work in insert mode). so, it doesn't work to me.

**Comment by knighht** [comment]
thanks for the help everyone and finally i found the very solution. i write code like this :
`
    function FindCursorPopUp()                                                                                                                                                                                            
      let radius = get(a:000, 0, 2)
      let srow = screenrow()
      let scol = screencol()
    
      " it's necessary to test entire rect, as some popup might be quite small
      for r in range(srow - radius, srow + radius)
        for c in range(scol - radius, scol + radius)
          let winid = popup_locate(r, c)
          if winid != 0
            return winid
          endif
        endfor
      endfor
    
      return 0
    endfunction
    
    function ScrollPopUp(down)
      let winid = FindCursorPopUp()
      if winid == 0
        return 0
      endif
    
      let pp = popup_getpos(winid)
      call popup_setoptions( winid,
            \ {'firstline' : pp.firstline + ( a:down ? 1 : -1 ) } )
    
      return 1
    endfunction
    
    
    nnoremap <expr> <c-d> ScrollPopUp(1) ? '<esc>' : '<c-d>'
    nnoremap <expr> <c-u> ScrollPopUp(0) ? '<esc>' : '<c-u>'
`
thanks again for https://vi.stackexchange.com/questions/21924/how-can-i-hide-and-scroll-popup-window-in-coc-nvim-in-vim/21927#21927.

**Comment by ArifRoktim** [comment]
@oblitum 

> I'm using this function for scrolling any floating window with arrow keys without exiting insert mode:
> 
> ```viml
> function! FloatScroll(forward) abort
> .
> .
> .
> ```

This works great for me, with 1 bug fix:
```viml
elseif pos[0] - win_height / 2 + 1 > 1
  let pos[0] -= win_height / 2 + 1
```
should be:
```viml
elseif pos[0] - (win_height / 2 + 1) > 1
  let pos[0] -= win_height / 2 + 1
```
I was getting an `E5555: API call: Cursor position outside buffer` because it kept trying to set the cursor to `[0, 0]`.

**Comment by oblitum** [comment]
@ArifRoktim I noticed the bug and had actually fixed it already, but I couldn't get why putting parentheses in this cause would fix it, I actually fixed it another way and simplified the code:

```vim
function! s:coc_float_scroll(forward) abort
  let float = coc#util#get_float()
  if !float | return '' | endif
  let buf = nvim_win_get_buf(float)
  let buf_height = nvim_buf_line_count(buf)
  let win_height = nvim_win_get_height(float)
  if buf_height < win_height | return '' | endif
  let pos = nvim_win_get_cursor(float)
  if a:forward
    if pos[0] == 1
      let pos[0] += 3 * win_height / 4
    elseif pos[0] + win_height / 2 + 1 < buf_height
      let pos[0] += win_height / 2 + 1
    endif
    let pos[0] = pos[0] < buf_height ? pos[0] : buf_height
  else
    if pos[0] == buf_height
      let pos[0] -= 3 * win_height / 4
    elseif pos[0] - win_height / 2 + 1  > 1
      let pos[0] -= win_height / 2 + 1
    endif
    let pos[0] = pos[0] > 1 ? pos[0] : 1
  endif
  call nvim_win_set_cursor(float, pos)
  return ''
endfunction
```

**Comment by jc00ke** [comment]
> @ArifRoktim I noticed the bug and had actually fixed it already, but I couldn't get why putting parentheses in this case would fix it, I actually fixed it another way and simplified the code:

Not sure why, but this is the only one suggested here that worked for me :man_shrugging: 
Thanks @oblitum!

**Comment by sharksforarms** [comment]
An alternative I recently discovered was to open the documentation popup with `shift+k` then I switch to the window using `ctrl+w, w` then use normal vim bindings to navigate. Then `ctrl+w, q` to exit the popup.

**Comment by jc00ke** [comment]
@sharksforarms I don't know how you figured that out, but it works and it's beautiful and thank you!

**Comment by oblitum** [comment]
That's well known, but I guess I've seen it only mentioned on gitter channel, not in this thread. For what is worth, the above code had the assumption that one doesn't want to actually move inside the window to scroll it, and be able to scroll it while not leaving insert mode.

**Comment by oblitum** [comment]
For anyone interested, I've improved the code for [insert mode scrolling above](https://github.com/neoclide/coc.nvim/issues/1405#issuecomment-626998607). For anyone that used it before, the "weird scroll jumps" that happened before have been completely removed, it's now smooth, also, the `s:coc_float_scroll` function now accepts the amount of scroll, so you can scroll line by line, or how many lines you wish, at each step.

**Comment by oblitum** [comment]
`coc#util#float_scroll_i` is now on `master`/`release` -> https://github.com/neoclide/coc.nvim/pull/2425

**Comment by you-n-g** [comment]
I'm on  `origin/release` branch.
It seems the `coc#util#get_float()` is lost.
`coc#float#get_float_win()`  looks provdes similar function. But it doesn't work when I replace `get_float`  with it 
![image](https://user-images.githubusercontent.com/465606/108586634-c1db7c00-738a-11eb-9087-64574b5f3904.png)

**Comment by you-n-g** [comment]
Besides,  I can't find the `float_scroll_i ` function.

**Comment by you-n-g** [comment]
The solution in #2902   works for me.

**Comment by gabrielgrover** [comment]
> An alternative I recently discovered was to open the documentation popup with `shift+k` then I switch to the window using `ctrl+w, w` then use normal vim bindings to navigate. Then `ctrl+w, q` to exit the popup.

This works for the most part.  However, when I have a vertical split and I am opening the popup on the left side, the aforementioned key combination moves the cursor to the right pane of the split.

**Comment by ilia-tsyplenkov** [comment]
> An alternative I recently discovered was to open the documentation popup with `shift+k` then I switch to the window using `ctrl+w, w` then use normal vim bindings to navigate. Then `ctrl+w, q` to exit the popup.

That is an awesome advice! Many thanks, dude

**Comment by diandian18** [comment]
No need to config anything:

1. `shift + k`: popup documentation
2. `shift + k`: move cursor to documentation
3. `ctrl + d/u`: scroll
4. `q`: quit documentation and move cursor back to word
