### ISSUE TITLE
Normalize bindings for next and previous

### ISSUE THREAD

**Issue by cprn** [neoclide/coc.nvim#1406]
**Is your feature request related to a problem? Please describe.**
Usual VIM bindings for next and previous are `<c-n>` and `<c-p>`. CoC seems to sometimes use those and sometimes it uses `<c-j>` and `<c-k>`, e.g.:
* calling `<Plug>(coc-references)` opens buffer that uses ctrl + n/p
* calling `:CocList diagnostics` opens buffer that uses ctrl + j/k

It seems to be related to fuzzy search.

**Describe the solution you'd like**
I'd prefer all lists to use the same bindings for next and previous: `<c-n>` and `<c-p>`.

**Describe alternatives you've considered**
I did try to learn when to use which set of bindings but my fingers are way too stubborn.

**Comment by chemzqm** [comment]
Please use `list.nextKeymap` and `list.previousKeymap` configuration.
