### ISSUE TITLE
No syntax highlighting on hover window at first try

### ISSUE THREAD

**Issue by otreblan** [neoclide/coc.nvim#1408]
## Result from CocInfo

[CocInfo.txt](https://github.com/neoclide/coc.nvim/files/3969406/CocInfo.txt)

## Describe the bug

So I fixed #911 with mads-hartmann/bash-language-server#162 and added syntax highlighting to the man pages that the server returns.

But the colors only appear at the second try.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**
- Add the configuration for bash-language-server from the [wiki](https://github.com/neoclide/coc.nvim/wiki/Language-servers#bash).

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=~/.config/nvim/plugs/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  set updatetime=300
  set filetype=sh

  " Documentation on hover
  autocmd CursorHold * silent if ! coc#util#has_float()
	\| call CocActionAsync('doHover')
  \| endif

  " Makes the floating window more readable
  highlight Pmenu ctermbg=237 ctermfg=white
  highlight PmenuSel ctermbg=220 ctermfg=black
  highlight PmenuSbar ctermbg=233
  highlight PmenuThumb ctermbg=7

  ```

- Start neovim with command: `nvim -u mini.vim`

- Write a bash command.

- Hover on the command.

- Unhover.

- Hover on the same command again.

## Screenshots (optional)

![Peek 16-12-2019 12-22](https://user-images.githubusercontent.com/39320840/70928361-e3124100-1ffe-11ea-9381-ed2ef07cf74e.gif)

**Comment by chemzqm** [comment]
Could be your syntax plugin too slow at the first time and reach the timeout for highlight, try improve the performance.

**Comment by chemzqm** [comment]
Use `coc.preferences.highlightTimeout` to increase timeout.

**Comment by otreblan** [comment]
It doesn't work, even with `"coc.preferences.highlightTimeout": 5000`.

Also it uses the man syntax file from the default man plugin from neovim.

**Comment by chemzqm** [comment]
No idea, it works as expected for me.

**Comment by otreblan** [comment]
> No idea, it works as expected for me.

It works. I was using the nightly release. Thanks.
