### ISSUE TITLE
Add `smart` option for `coc.preferences.jumpCommand`。

### ISSUE THREAD

**Issue by zuoxinyu** [neoclide/coc.nvim#1409]
**Is your feature request related to a problem? Please describe.**
Usually when jump to definition of a symbol,  the behavior which I want is:
1. If the definition is in the same file as the symbol, just move cursor there.
2. If it's in a different file, open a new horizon/vertical  window/tab.

**Describe the solution you'd like**
Add a new option for the configure `coc.preferences.jumpCommand` like `smart`.

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
Not necessary, use `drop` or `tab drop` or you can define your own command.

**Comment by ramsgoli** [comment]
How would we define our own command?

**Comment by chemzqm** [comment]
In your vimrc, you have to learn viml.
