### ISSUE TITLE
tslint doesn't recognize final newline

### ISSUE THREAD

**Issue by tbo** [neoclide/coc.nvim#141]
coc-tslint doesn't recognize the final newline and shows a warning:
```
[tslint eofline] [W] file should end with a newline (eofline)
```
**To Reproduce**

Open any Typescript-file with the `eofline`-rule set to true. Example project: https://github.com/tbo/barebone-typescript-react-express

**Expected behavior**

coc-tslint shouldn't display a warning message

**Screenshots**

<img width="661" alt="screen shot 2018-10-31 at 17 05 36" src="https://user-images.githubusercontent.com/264745/47801878-63101580-dd2f-11e8-88b0-aa4f436949d1.png">

**Comment by chemzqm** [comment]
Loos like it's issue of vim, it doesn't consider there's a new line when file ends with `lf`, but VSCode does.

**Comment by tbo** [comment]
I don't see how vim is involved in this. Isn't the content of the buffer or the whole file passed to tslint? Other tslint plugins for vim don't have this issue. Could it be, that the content is trimmed before it gets to tslint?

**Comment by chemzqm** [comment]
> . Isn't the content of the buffer or the whole file passed to tslint? 

No, plugin could only get lines from vim, so there's no last empty line.

**Comment by chemzqm** [comment]
Fixed, LSP should respect `eol` option to add extra '\n' for document content.
