### ISSUE TITLE
coc.nvim breaks undopoints in NeoVim

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#1412]
## versions

vim version: NVIM v0.4.3
node version: v13.3.0
coc.nvim version: 0.0.74
term: tmux-256color
platform: linux

## Output channel: snippets

[Info  - 12:33:12 PM] watchman watching project: /home/francisco/.config/coc/ultisnips
[Info  - 12:33:12 PM] subscribing "**/*.snippets" in /home/francisco/.config/coc/ultisnips

## Describe the bug

When coc.nvim is enabled together with snippets in vim code, it breaks undo points when typing `\`. There's no way to undo all that has been inserted. Check gif at the bottom.

## Reproduce the bug

- Create file `mini.vim` with:
  ```vim
  augroup vimrc | autocmd! | augroup end

  if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd vimrc VimEnter * PlugInstall --sync | source $MYVIMRC
  endif

  set nocompatible

  call plug#begin('~/.vim/plugged')
  Plug 'tpope/vim-sensible'
  call plug#load('vim-sensible')
  let g:coc_global_extensions = ['coc-snippets']
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'honza/vim-snippets'
  call plug#end()

  set expandtab shiftwidth=4 tabstop=4 softtabstop=4
  ```

- Create file `foo.vim` with: 
  ```vim
  " Foo {{{
  " }}}
  ```

- Start neovim with command: `neovim -u mini.vim foo.vim` (only happens in neovim)

- Trigger automatic indentation when typing `\` (check gif bellow).

- Undo text changes

## Screenshots (optional)

Here I typed `u` many times before closing the file, but it didn't revert all changes. When reopening the file, the changes have actually been reverted.

![screencast](https://user-images.githubusercontent.com/1269815/71008924-33a1a100-20c8-11ea-8c2e-80134cee685f.gif)

**Comment by fannheyward** [comment]
Can't reproduce.

```
let $NVIM_COC_LOG_LEVEL = 'debug'
set expandtab shiftwidth=4 tabstop=4 softtabstop=4
set runtimepath=$HOME/.config/nvim/plugged/vim-snippets
set runtimepath=$HOME/.config/nvim/plugged/coc.nvim
filetype plugin indent off

let g:coc_global_extensions = ['coc-snippets']
```

```
vim version: NVIM v0.5.0-241-g9f3d483c7
node version: v13.3.0
coc.nvim version: 0.0.74
term: iTerm.app
platform: darwin
```

**Comment by oblitum** [comment]
@fannheyward I can reproduce with a minimal vim similar to yours either, it has completely different behavior, I don't get any auto indent and coc completion with it.

**Comment by oblitum** [comment]
I have edited your minimal file to the following, now it works, it was important to use `+=`:

```vim
let $NVIM_COC_LOG_LEVEL = 'debug'
set expandtab shiftwidth=4 tabstop=4 softtabstop=4
set runtimepath+=$HOME/.vim/plugged/vim-snippets
set runtimepath+=$HOME/.vim/plugged/coc.nvim
filetype plugin indent off

let g:coc_global_extensions = ['coc-snippets']
```

**Comment by chemzqm** [comment]
Unable to reproduce on neovim 0.5.0

**Comment by fannheyward** [comment]
![11111](https://user-images.githubusercontent.com/345274/71139635-b69e3500-2249-11ea-96f7-e2bebb37d922.gif)

mini.vim

```
let $NVIM_COC_LOG_LEVEL = 'debug'
set expandtab shiftwidth=4 tabstop=4 softtabstop=4
set runtimepath+=$HOME/.vim/plugged/vim-snippets
set runtimepath+=$HOME/.vim/plugged/coc.nvim
filetype plugin indent off

let g:coc_global_extensions = ['coc-snippets']
```

**Comment by oblitum** [comment]
@fannheyward your gif is not right, it's not presenting any snippet. To reproduce the issue it's necessary that `coc.nvim` popups shows up. You have set `set runtimepath+=$HOME/.vim/plugged/vim-snippets`, which should have had the honza snippets.

**Comment by oblitum** [comment]
I just tested the issue on latest master of NeoVim.

**Comment by fannheyward** [comment]
![1](https://user-images.githubusercontent.com/345274/71147956-4b625c00-2265-11ea-994d-fd7cc9615920.gif)

Reproduced.

**Comment by fannheyward** [comment]
After some debug and `git bisect`, this issue is caused by `preselect` feature on Neovim. When disable `suggest.enablePreselect`, the issue is gone.

https://github.com/neoclide/coc.nvim/commit/ca3e3892596a40451b6c2016dab8c6b794c19b4c is the first broken commit.

**Comment by chemzqm** [comment]
I've made suggest.enablePreselect default to false
