### ISSUE TITLE
Diagnostic List

### ISSUE THREAD

**Issue by ovidius72** [neoclide/coc.nvim#1413]
Because I'm having problem with ALE in large projects that slows down switching between normal and insert mode, I would like to use the coc.nvim diagnostic feature. 
Using Coc List/Diagnostic all issues are displayed at the bottom (like a location list) with fuzzy search.
Is it possible to show up this windows automatically when there are errors in the current buffer, without the need to manually open coc-list ?

Thanks.

**Comment by chemzqm** [comment]
Use autocmd `CocDiagnosticChange`
