### ISSUE TITLE
Priority of doHover?

### ISSUE THREAD

**Issue by dianlujitao** [neoclide/coc.nvim#1417]
both documentation and [coc-ecdict](https://github.com/fannheyward/coc-ecdict)  employ the api, and if the name of a function happens to be a sane English word, the popup window shows both its documentation and meaning.

It turns out coc-ecdict has higher priority and it always comes before the documentation. This is annoying, in most cases we just want to know the usage rather than it's meaning in chinese. Is it possible to adjust the priority when there're multiple doHover providers?

**Comment by chemzqm** [comment]
No, I think that coc-ecdict should provide it's own command for documentation instead of use `doHover` feature.

**Comment by dianlujitao** [comment]
Thanks for the clarification
