### ISSUE TITLE
node use cpu high when run :h getpos() command in neovim

### ISSUE THREAD

**Issue by pangchol** [neoclide/coc.nvim#1418]
node process use cpu high when use :help command to see some function help manual (such as :h getpos()). this problam only see in neovim(version is 0.5.0-dev), vim8.2 not has this problam. the coc.nvim is newest dev version.

**Comment by fannheyward** [comment]
Can't reproduce with `NVIM v0.5.0-250-g416de695f` + coc.nvim master. Please provide more info/steps or mini.vim that can reproduce this issue.

**Comment by pangchol** [comment]
this maybe couse by my self compuer env.  I  delecte the ~/.config/coc dir, and then reinstall some my coc extensions this problam disappear.  so I close it now. thanks very mach.
