### ISSUE TITLE
Installing extension with minpac

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [neoclide/coc.nvim#1420]
I'm using [minpac](https://github.com/k-takata/minpac) to install coc.nvim extensions so that I can set up my own autocmds to lazily load extensions on filetype.

Right now I'm doing this . . .
```vim
call minpac#add('neoclide/coc.nvim', {'branch': 'release'})
call minpac#add('fannheyward/coc-marketplace', {'do': 'silent !yarn install --frozen-lockfile'})
call minpac#add('neoclide/coc-git', {'do': 'silent !(yarn install --frozen-lockfile)'})
call minpac#add('neoclide/coc-tsserver', {'type': 'opt'}, {'do': 'silent !(yarn install --frozen-lockfile)'})
call minpac#add('neoclide/coc-html', {'type': 'opt'}, {'do': 'silent !(yarn install --frozen-lockfile)'})
call minpac#add('neoclide/coc-json', {'type': 'opt'}, {'do': 'silent !(yarn install --frozen-lockfile)'})
if executable('ra_lsp_server')
	call minpac#add('fannheyward/coc-rust-analyzer', {'type': 'opt'}, {'do': 'silent !(yarn install --frozen-lockfile)'})
elseif executable('rls')
	call minpac#add('neoclide/coc-rls', {'type': 'opt'}, {'do': 'silent !(yarn install --frozen-lockfile)'})
endif
```

minpac is telling me it's installed but it's not. Any ideas?

**Comment by chemzqm** [comment]
They doesn't exists in $runtimepath

**Comment by Th3Whit3Wolf** [comment]
Why not and how do I change that?

**Comment by Th3Whit3Wolf** [comment]
I believe I have installed the extensions as the [wiki](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions) says I can.

**Comment by Th3Whit3Wolf** [comment]
Running `:CocList extensions` it show me all off my extensions that should be loaded followed by [RTP], then version, then their runtimepath. 

I have set the as enabled but I am still unable to use coc-marketplace.
