### ISSUE TITLE
Autocomplete works but documentation not showing up

### ISSUE THREAD

**Issue by dirodriguezm** [neoclide/coc.nvim#1424]
## versions

  vim version: NVIM v0.3.8
  node version: v12.13.1
  coc.nvim version: 0.0.74-cd348f4905
  term: st-256color
  platform: linux

  ## Messages[coc.nvim] No ESLint configuration (e.g .eslintrc) found for file: /home/diego/test.js

  ## Output channel: prettier

  ## Output channel: snippets

  ## Output channel: tsserver
  [Info  - 6:46:03 PM] Forking TSServer
  PATH: /home/diego/anaconda3/bin:/home/diego/anaconda3/condabin:/home/diego/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  [Info  - 6:46:03 PM] Started TSServer
  {
    "path": "/home/diego/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
    "_pathLabel": "",
    "_api": {
      "versionString": "3.7.3",
      "version": "3.7.3"
    }
  }

  ## Output channel: eslint
  [Info  - 6:46:03 PM] ESLint server running in node v12.13.1
  [Info  - 6:46:03 PM] ESLint library loaded from: /usr/local/lib/node_modules/eslint/lib/api.js

## Describe the bug

When I start typing I can see suggestions from functions and autocomplete works fine, but documentation from functions is not showing like in the readme page.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/.vim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim test.js`
- Run `:CocInstall coc-tsserver`
- Write and try to get autocomplete popups for example: `document.getElement`
    This should pop autocompletion for document.getElementBy functions but no documentation is shown

## Screenshots (optional)

![Screenshot from 2019-12-24 19-05-37](https://user-images.githubusercontent.com/18015991/71425841-7216fd00-2680-11ea-9803-ae76d8c0dbbb.png)

**Comment by fannheyward** [comment]
You need to upgrade to neovim version 0.4+ to use floating window.
