### ISSUE TITLE
"client coc abnormal exit with: 1" in Windows 10

### ISSUE THREAD

**Issue by K-Nick** [neoclide/coc.nvim#1428]
Here is messages shown when type in :messages in Neovim

`[coc.nvim] error: internal/modules/cjs/loader.js:800^M                                                                                                                                            throw err;^M                                                                                                                                                                                  ^^M                                                                                                                                                                                       ^M                                                                                                                                                                                            Error: Cannot                                                                                                                                                                                 [coc.nvim] error: find module '../package.json'^M                                                                                                                                             Require stack:^M                                                                                                                                                                              - C:\Users\Administrator\AppData\Local\nvim\build\index.js^M                                                                                                                                      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)^M                                                                                                                 at Function.Module._load (internal                                                                                                                                                        [coc.nvim] error: /modules/cjs/loader.js:690:27)^M                                                                                                                                                at Module.require (internal/modules/cjs/loader.js:852:19)^M                                                                                                                                   at require (internal/modules/cjs/helpers.js:74:18)^M                                                                                                                                          at new Workspace (C:\Users\Administrator\AppData\Local\nvim                                                                                                                               [coc.nvim] error: \build\index.js:21877:20)^M                                                                                                                                                     at Object.<anonymous> (C:\Users\Administrator\AppData\Local\nvim\build\index.js:23427:19)^M                                                                                                   at __webpack_require__ (C:\Users\Administrator\AppData\Local\nvim\build\index.js:20:30)^M                                                                                                     at                                                                                                                                                                                        [coc.nvim] error:  Object.<anonymous> (C:\Users\Administrator\AppData\Local\nvim\build\index.js:15222:45)^M                                                                                       at __webpack_require__ (C:\Users\Administrator\AppData\Local\nvim\buil                                                                                                                    [coc.nvim] error: d\index.js:20:30)^M                                                                                                                                                             at Object.<anonymous> (C:\Users\Administrator\AppData\Lo                                                                                                                                  [coc.nvim] error: cal\nvim\build\index.js:10292:42) {^M                                                                                                                                         code: 'MODULE_NOT_FOUND',^M                                                                                                                                                                   requireStack: [ 'C:\\Users\\Administrator\\AppData                                                                                                                                          [coc.nvim] error: \\Local\\nvim\\build\\index.js' ]^M                                                                                                                                         }^M                                                                                                                                                                                           client coc abnormal exit with: 1  `

I used dein.nvim to install coc.nvim by adding this line
`call dein#add('neoclide/coc.nvim', {'merged':0, 'rev': 'release'}) `
into init.vim
after run dein#install(), it seems that coc.nvim is built in my "nvim" folder.

However, "client coc abnormal exit with: 1" keeps popping up.
Is this caused by windows or have I done something wrong during installation

**Comment by chemzqm** [comment]
Looks like the installation is broken, try cleanup your vim plugins and reinstall.
