### ISSUE TITLE
Alt+ keybinds not working mid-completion

### ISSUE THREAD

**Issue by Kazimazi** [neoclide/coc.nvim#143]
Using keybinds like Alt+Shift+a in insert mode should jump to the end of the line and stay in insert mode, instead it prints an 'A' if I was in mid-completion with coc.
Perhaps I'm in a ruby file and I type: `5.cl` I press tab or ctrl+n for the completion to `5.class` and I want to get to the previous line and stay in insert mode so I press Alt+Shift+o and it won't happen: `5.classO`.
For context these keybinds without the shift work perfectly, so getting to the next line with Alt+o wouldn't be a problem.
To resolve this problem, before pressing Alt+Shift+a pressing Enter to finish the completion makes it work properly, considering you have it bound like: `inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
` in your vimrc.

**Comment by chemzqm** [comment]
> Using keybinds like Alt+Shift+a in insert mode should jump to the end of the line and stay in insert mode, instead it prints an 'A' if I was in mid-completion with coc.

That's not vim's default mapping and it's related to coc.nvim, try `:verbose imap <A-S-A>` to get the definition.

**Comment by Kazimazi** [comment]
I don't think so for example :verbose nmap <C-u> won't find any mappings either. It just shows user defined mappings.

**Comment by Kazimazi** [comment]
Vim and nvim comes with these Alt mappings, that's why I prefer them over vim emulators in other IDEs.

**Comment by chemzqm** [comment]
It should be added by one of your plugin, does the mapping works for you with `vim -u NORC`?

**Comment by Kazimazi** [comment]
Yes it does work without any configuration.

**Comment by chemzqm** [comment]
>  if I was in mid-completion with coc.

It should be also happens when you use vim's default omni completion, like `<C-n>`

**Comment by chemzqm** [comment]
What's result from command `:verbose imap <A-S-A>`?

**Comment by Kazimazi** [comment]
`No mapping found`

**Comment by chemzqm** [comment]
Does the keybinds works when the popupmenu opened by vim's omni completion (like `<C-n>`)?

**Comment by chemzqm** [comment]
Perhaps that your terminal send other keystrokes to vim when you type `Alt+Shift+a`, there should be no default keymapping in vim for that.

**Comment by Kazimazi** [comment]
It works with omnicompletion, but not with deoplete.

**Comment by Kazimazi** [comment]
I use Alacritty as terminal emulator and sometimes Urxvt it works in both of them, but no in Xterm.

**Comment by chemzqm** [comment]
I tried to add
```
  inoremap <A-S-A> <End>
```
in my vimrc, and it could work for me when popup menu is shown by coc.

**Comment by chemzqm** [comment]
Coc should not interfere with your alt keybinds, reopen the issue if you find it still exists with only coc.nvim enabled.
