### ISSUE TITLE
Neovim fails to start coc with `set regexpengine=1` in init.vim

### ISSUE THREAD

**Issue by teddyhwang** [neoclide/coc.nvim#1432]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v13.5.0
coc.nvim version: 0.0.74
term: iTerm.app
platform: darwin

## Messages
[coc.nvim] error: Error on initialize: TypeError: Invalid Version: 0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang 
    at new SemVer (/Users/teddyhwang/.vim/plugged/coc.nvim/node_modules/semver/semver.js:332:11)
    at compare (/Users/teddyhwang/.vim/plugged/coc.nvim/node_modules/semver/semver.js:647:10)
    at Function.gte (/Users/teddyhwang/.vim/plugged/coc.nvim/node_modules/semver/semver.js:703:10)
    at ListManager.init (/Users/teddyhwang/.vim/plugged/coc.nvim/lib/list/manager.js:51:60)
    at Plugin.init (/Users/teddyhwang/.vim/plugged/coc.nvim/lib/plugin.js:168:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/teddyhwang/.vim/plugged/coc.nvim/lib/attach.js:91:13
E492: Not an editor command: CocIN

```

## Describe the bug

Neovim fails to start Coc with `set regexpengine=1` in `init.vim`

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
set regexpengine=1
```

- Start neo vim with command: `nvim -u mini.vim`

**Comment by fannheyward** [comment]
Reproduced.

https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/util.vim#L148

```
function! coc#util#version()
  let c = execute('silent version')
  return matchstr(c, 'NVIM v\zs[^\n-]*')
endfunction
```

1. when `set regexpengine=1`, this function on nvim v0.4.3 returns 

```
0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode
```

this is not valid version string used in `semver`.

on nvim v0.5.0-258-g9e9dcd4bd, returns `0.5.0`

2. when `set regexpengine=0` or `set regexpengine=2`, nvim v0.4.3 returns `0.4.3`, and nvim v0.5.0-258-g9e9dcd4bd returns `0.5.0`

In https://github.com/neoclide/coc.nvim/commit/d068462fc99fe0acb7858c11b1094a19df5cf27e, I just make a check on nvim.version before used in semver to ignore this error, but this is not a good solution. The better is to correct `coc#util#version()`

**Comment by teddyhwang** [comment]
That fixed things, thanks!
