### ISSUE TITLE
请教下使用过程中的一些问题

### ISSUE THREAD

**Issue by irreallich** [neoclide/coc.nvim#1433]
您好，我用的是Vim8.2 ,在使用coc插件过程中有几个问题请教：
1. 我在ubuntu中使用ctrl+space来切换中英文，在加载coc.nvim后，insert模式下，输入ctrl+space，在输入法切换到中文的同时，会将vim从insert模式变成narmal模式，我尝试使用 imap <c-space> <nop>， 或者iunmap <c-space>，没有效果。
如果我不加载coc，将没有这个问题

以下是我 imap后的打印信息
i  <C-H>       * coc#refresh()
i  <Plug>CocRefresh * <C-R>=coc#_complete()<CR>
i  <Tab>       * pumvisible() ? "\<C-N>" :  <SNR>54_check_back_space() ? "\<Tab>" :  coc#refresh()

2. :cocconfig 可以用来打开配置文件~/.vim/coc-settings.json，如何修该这个配置文件的位置？
比如说将这个配置文件默认的地址放到~/settings/vimconfg/

谢谢

**Comment by fannheyward** [comment]
1. 没有用 vim 8.2， 暂时未知
2. `:h g:coc_config_home`

**Comment by irreallich** [comment]
@fannheyward 
非常感谢，我尝试了一下vim8,也发现同样的问题，是否在coc中有定义map的行为，改变了<c-space>的行为？
有没有办法可以在vimrc中通过国屏蔽key之类的方式将这个问题处理掉？

**Comment by fannheyward** [comment]
你是设置了 `inoremap <silent><expr> <c-space> coc#refresh()` 吧，和 ctrl+space 切换输入法冲突了，可以更换为其他 mapping。

**Comment by irreallich** [comment]
@fannheyward 
我是用的时<c-h>作为强制弹出补全的功能，并没有使用<c-space>

**Comment by chemzqm** [comment]
不安装 coc.nvim 一样的问题，这个问题去给 vim 提吧，neovim 上面是正常的，coc.nvim 并不会绑定你的 keymap。
