### ISSUE TITLE
typescript-3.7.0 breaks 'Import declaration conflicts with local declaration of 'SpawnOptions'

### ISSUE THREAD

**Issue by dezza** [neoclide/coc.nvim#1436]
I was fiddling with trying to build an example extension when I discovered this compatability break which happened since typescript 3.6.2-3.7.0 change
`node_modules/coc.nvim/lib/language-client/index.d.ts:2:14 - error TS2440: Import declaration conflicts with local declaration of 'SpawnOptions'.` on running `tsc -p tsconfig.json`

Source link to offending line:
https://github.com/neoclide/coc.nvim/blob/master/src/language-client/index.ts#L5

Downgrading to 3.6.2 fixes builds with no errors on `tsc -p tsconfig.json`

Official note on this 3.7.0 change: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#local-and-imported-type-declarations-now-conflict'

**Comment by chemzqm** [comment]
We need fix this.
