### ISSUE TITLE
不能通过 tab 切换补全选项

### ISSUE THREAD

**Issue by sober-wang** [neoclide/coc.nvim#1442]
不能通过 tab 切换补全选项

**Comment by fannheyward** [comment]
请提供最小化 vimrc 来复现问题。

**Comment by sober-wang** [comment]
我仅配置这个。
Plug 'neoclide/coc.nvim', {'branch': 'release'}

**Comment by fannheyward** [comment]
coc.nvim 默认不会添加 mapping，需要自己设置 https://github.com/neoclide/coc.nvim#example-vim-configuration

**Comment by mgdreamingstar** [comment]
在某些文件中，比如 vimwiki 类型的文件里，会有 popup 弹出，但无法用快捷键补全。是需要安装 efm  -languageserver 吗？
