### ISSUE TITLE
Coc override shiftwidth

### ISSUE THREAD

**Issue by alannotnerd** [neoclide/coc.nvim#1443]
## Result from CocInfo
```
## versions

vim version: NVIM v0.3.8
node version: v10.17.0
coc.nvim version: 0.0.74-cd348f4905
term: xterm-256color
platform: linux

## Messages

## Output channel: Python

Starting Jedi Python language engine.
```
## Describe the bug

Coc override `softtabstop` , `shiftwidth` and so on in .vimrc with some plugin

## Reproduce the bug
* install `coc-python`
* set softtabstop to 2 in vimrc
* open a python buffer, softtabstop has overrided to 4

**Comment by cathyzhyi** [comment]
@alannotnerd I am having the same issue. I am wondering if you have figured it out?

**Comment by oblitum** [comment]
@cathyzhyi I can reproduce it due to coc, must be other plugin, check output for `:verbose set softtabstop?`, and other settings.

**Comment by cathyzhyi** [comment]
@oblitum thanks a lot for pointing me to the command! and yes, you are right. it's because of ftplugin rather than coc.
