### ISSUE TITLE
signatureHelp on CocJumpPlaceholder fails for some servers

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#1444]
## versions

vim version: NVIM v0.4.3
node version: v13.5.0
coc.nvim version: 0.0.74
term: tmux-256color
platform: linux

## Messages
[coc.nvim] workspace loaded, 16 rust packages
## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/francisco
> git ls-files -- Projects/samples/rust/src/main.rs
resolved root: /home/francisco
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Trace

https://gist.github.com/oblitum/799a8414fbff349b0bc842b9d99a9e5c

## Describe the bug

`autocmd vimrc User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')` works for some servers, but fail for others, even when manually executing `:call CocActionAsync("showSignatureHelp")` does work for them. rust-analyzer is a server where this always fail, it looks like [clangd is another](https://github.com/neoclide/coc.nvim/issues/1441#issuecomment-570637958).

## Reproduce the bug

- Create file `mini.vim` with:

  ```vim
  augroup vimrc | autocmd! | augroup end

  if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd vimrc VimEnter * PlugInstall --sync | source $MYVIMRC
  endif

  set nocompatible

  call plug#begin('~/.vim/plugged')
  let g:coc_global_extensions = ['coc-rust-analyzer']
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()

  call coc#config('rust-analyzer', {
  \   'trace.server': 'verbose'
  \ })

  autocmd vimrc User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
  ```

- `cargo init foo && cd foo`

- save `src/main.rs` with this:
  ```rust
  fn foo(x: i32) -> i32 {
      x
  }

  fn main() {
  }
  ```

- Open `src/main.rs` with `nvim -u somepath/mini.vim src/main.rs`, write "foo" inside `main` and expand the function with `<c-y>`: signatureHelp is not displayed.

- Finish writing "foo();" inside main, move the cursor before the closing `)`, "inside" `()`, execute `:call CocActionAsync("showSignatureHelp")`: signatureHelp is displayed.

## Related issues

- https://github.com/rust-analyzer/rust-analyzer/issues/2036
- https://github.com/neoclide/coc.nvim/issues/1441#issuecomment-570637958

**Comment by fannheyward** [comment]
Tested with `rust-analyzer` and `gopls`:

```rust
fn foo(x: i32) -> i32 {
    x
}
```

```go
func foo(x int) {
    log.Println(x)
}
```

`signatureHelp` with gopls is works, but RA failed.

RA gives `foo` function snippet as `foo($0)`, after [SnippetParser.parse](https://github.com/neoclide/coc.nvim/blob/master/src/snippets/manager.ts#L86), snippet becomes `foo()`, [snippetManager.isPlainText](https://github.com/neoclide/coc.nvim/blob/master/src/languages.ts#L626) check it as plaintext, which is not a snippet, `CocJumpPlaceholder` will not be fired.

gopls gives `foo` function snippet as `foo(${1:x int})`, after `parse` becomes `foo(x int)`, which is not plaintext, snippetManager treats it as a snippet, and `CocJumpPlaceholder` is fired.

The difference is that language server gives different snippet format, and coc will check it plaintext or not. Maybe we need to check how LSP defines snippet format.

**Comment by fannheyward** [comment]
https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_completion
https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_completion

Searching `The snippet format is as follows` to find:


> Placeholders
> Placeholders are tab stops with values, like ${1:foo}. The placeholder text will be inserted and selected such that it can be easily changed. Placeholders can be nested, like ${1:another ${2:placeholder}}.

**Comment by oblitum** [comment]
Hm, OK. But why does it work when invoked manually? That's the reason I thought it could be a client issue.

**Comment by fannheyward** [comment]
As the mini.vim defines, when `CocJumpPlaceholder` event fired, coc action will run. No event, no action called to run. When you invoked the action manually, it runs.

**Comment by oblitum** [comment]
OK. I'll close this for now and reopen the rust-analyzer issue, linking back to this discussion.
