### ISSUE TITLE
How can I use coc and other go to definition engine as fallback?

### ISSUE THREAD

**Issue by kraml** [neoclide/coc.nvim#1445]
As per the example, I can use:
```
nmap <silent> gd <Plug>(coc-definition)
```
for go to definition. But I also use GNU Global for some smaller projects, and it's like this:
```
nmap <silent>gd :cs find g <C-R>=expand("<cword>")<CR><CR>
```
And there is the dumb VIM built-in `gd`.

So how can I combine them together, in the sequence of coc -> Global -> built-in? In other words, if the coc-definition finds something, jump to it, otherwise try another command and jump to the definition, and finally fallback to the built-in `gq`.

**Comment by fannheyward** [comment]
```vim
function! s:GoToDefinition()
  if CocAction('jumpDefinition')
    return v:true
  endif

  let ret = execute("silent! normal \<C-]>")
  if ret =~ "Error" || ret =~ "错误"
    call searchdecl(expand('<cword>'))
  endif
endfunction

nmap <silent> gd :call <SID>GoToDefinition()<CR>
```

I'm using this function, `gd` will go by coc -> tags -> searchdecl. You can Try something like this.

**Comment by kraml** [comment]
Thank you.

**Comment by GuokaiLiu** [comment]
Is that possible and how can I jump back?
Thank you : )

**Comment by oren0e** [comment]
> ```viml
> function! s:GoToDefinition()
>   if CocAction('jumpDefinition')
>     return v:true
>   endif
> 
>   let ret = execute("silent! normal \<C-]>")
>   if ret =~ "Error" || ret =~ "错误"
>     call searchdecl(expand('<cword>'))
>   endif
> endfunction
> 
> nmap <silent> gd :call <SID>GoToDefinition()<CR>
> ```

Great solution!
Is there a way to also map a key binding to open the definition in a new vertical split?

**Comment by ProgrammingLife** [comment]
> > ```viml
> > function! s:GoToDefinition()
> >   if CocAction('jumpDefinition')
> >     return v:true
> >   endif
> > 
> >   let ret = execute("silent! normal \<C-]>")
> >   if ret =~ "Error" || ret =~ "错误"
> >     call searchdecl(expand('<cword>'))
> >   endif
> > endfunction
> > 
> > nmap <silent> gd :call <SID>GoToDefinition()<CR>
> > ```
> 
> Great solution!
> Is there a way to also map a key binding to open the definition in a new vertical split?

I'm also looking for opening a definition in a vertical split (:vsp).

**Comment by chemzqm** [comment]
`:h CocAction('jumpDefinition')`
