### ISSUE TITLE
Starting vim projects from $HOME "$CWD" in Terminal and significance of ".vim" in default rootPatterns?

### ISSUE THREAD

**Issue by dezza** [neoclide/coc.nvim#1447]
## Describe the bug
_How I discovered this;_
I was trying out `coc-rust-analyzer` and seeing it could not locate `Cargo.toml` by default.

After watching the source a bit it seemed since it automatically starts resolving directories from `$CWD` the only fix is to `cd` to project beforehand, but since most peoples terminal starts in $HOME and I usually then edit a file straight away in `vim src/LANG/PROJECT` this is what I hoped would work ...

The problem is that because `.vim` is default in `coc.preferences.rootPatterns` 
```json
"coc.preferences.rootPatterns": [
  ".vim",
  ".git",
  ".hg",
  ".projections.json"
],
```

This stops the `inDirectory`[util/fs.ts#L68](https://github.com/neoclide/coc.nvim/blob/9c0a1f38668ba609df96a7b585a961f61e4d995e/src/util/fs.ts#L68) function (searching for rootPatterns e.g. `Cargo.toml, package.json, go.mod` for example) at `$HOME` when it finds the `.vim` directory in `$HOME`, regardless of what order the rootPatterns are in, (Cargo.toml before or after .vim)

If I remove ".vim" from `rootPatterns` suddenly all my languageservers start way faster (I wondered about this for a long time, it was a delay upwards of 10-20s, probably I/O), this could also be because WSL (Windows Subsystem for Linux) has relatively slow I/O.

Because I usually start vim from my terminal with current working directory being `$HOME` in most cases, the `.vim` directory is picked up by `inDirectory`[util/fs.ts#L68](https://github.com/neoclide/coc.nvim/blob/9c0a1f38668ba609df96a7b585a961f61e4d995e/src/util/fs.ts#L68) and slows initial startup of languageservers significantly because ".vim" has many directories to be resolved and all these are crawled, but also prevents searching the other `rootPatterns` ? Or did I miss something?

1. So is `.vim` there for resolving $VIMRUNTIME and vim-specific scripts, modules, possibly for VimL languageserver or similar uses?

2. could this first rootPattern "match" of `.vim`, because it is found in $HOME prevent the search of Cargo.toml from the opened buffer?

## Reproduce the bug
1. Default `coc.preferences.rootPatterns` setting

2. Start a terminal with `$CWD` at `$HOME`

3. Edit main.rs inside a subfolder of `$HOME` e.g. `vim src/rust/project/src/main.rs`

**Comment by chemzqm** [comment]
Some servers index all you files from root, try add `"ignoredRootPaths": ["~"]` to your language server configuration.

**Comment by dezza** [comment]
This is `coc-rust-analyzer`, so maybe it should be added to `languageClient.initializationOptions` of `coc-rust-analyzer` ?

Is there a significance to ".vim" in rootPatterns?

**Comment by fannheyward** [comment]
`.vim` is used for local `.vim/coc-settings.json`, https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L102

I'll check whether `ignoredRootPaths` works for `rust-analyzer`.

**Comment by dezza** [comment]
You guys are the best! I'll look forward to it!

**Comment by fannheyward** [comment]
@chemzqm `ignoredRootPaths` doesn't effect [workspace.resolveRoot](https://github.com/neoclide/coc.nvim/blob/master/src/workspace.ts#L1471), so `rootPath` is always resolved to `$HOME` when `vim ~/src/project1` with `.vim` pattern. Is there anything I missed?
