### ISSUE TITLE
coc-eslint not active with filetype `javascript.jsx`

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#145]
**Describe the bug**

coc-eslint not active and can't get  LSP completion item from  coc-tsserver with filetype `javascript.jsx`.

it's confuse about the setting of: 
```
  "eslint.filetypes": [
    "javascript",
    "javascript.jsx"
  ]
```
and `Break change filetype of document would be first part of &filetype split by .`

**Comment by chemzqm** [comment]
`javascript.jsx` is converted to `javascriptreact` to be same as VSCode.

**Comment by chemzqm** [comment]
Fixed at https://github.com/neoclide/coc-eslint/commit/2b449de137a3529e7b65b0ed1caa73c1efc81d99

**Comment by iamcco** [comment]
coc-eslint works when add `javascriptreact` to the setting:

```javascript
"eslint.filetypes": [
    "javascriptreact",
    "javascript",
  ]
```

> `javascript.jsx` is converted to `javascriptreact` to be same as VSCode.

i can't get LSP completion items from coc-tsserver, is there a document about this ?

**Comment by chemzqm** [comment]
The release notes: https://github.com/neoclide/coc.nvim/releases/tag/v0.0.30

**Comment by chemzqm** [comment]
> i can't get LSP completion items from coc-tsserver

The filetype of completion not converted, just fixed that.
