### ISSUE TITLE
metals-vim is not installed

### ISSUE THREAD

**Issue by mrt181** [neoclide/coc.nvim#1451]
## Result from CocInfo

```
## versions                                                                                                                      [0/55]

vim version: NVIM v0.3.8
node version: v12.14.0
coc.nvim version: 0.0.74-cd348f4905
term: screen
platform: linux

## Messages
[coc.nvim] Server metals failed to start: Command "metals-vim" of languageserver.metals is not executable: Error: not found: metals-vim
## Output channel: languageserver.metals

[Error  - 10:03:59 AM] Starting client failed:
Error: Command "metals-vim" of languageserver.metals is not executable: Error: not found: metals-vim
    at LanguageClient.createMessageTransports (/home/r892107/.config/nvim/plugged/coc.nvim/build/index.js:54276:23)
```
## Describe the bug
Followed the instructions for metals-vim (https://scalameta.org/metals/docs/editors/vim.html)
Run `:CocInstall coc-metals` - there is no output or anything else
restart nvim, 
open some `build.sbt`, 
get the `not found: metals-vim` error
## Reproduce the bug

bug happens when using mini.vim

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=~/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Addtional information
platform is linux via WSL1
network is using a corp. proxy

**Comment by chemzqm** [comment]
Add `metals-vim` to your $PAHT or use absolute path.

**Comment by caente** [comment]
@chemzqm why did you close this? I have the exact same issue, can you at least tell us ***where*** metals-vim is when installed with `CocInstall coc-metals`? metals was working fine until I updated metals :/

**Comment by oblitum** [comment]
@caente extensions generally install their assets in coc data directory. Look for it in docs.

**Comment by caente** [comment]
you mean here?
```
❯ ls ~/.config/nvim/bundle/coc.nvim/data
schema.json
```

**Comment by oblitum** [comment]
No. That's the coc.nvim plugin dir, not the data dir. Look for it in docs and you'll find you can even configure it.

**Comment by oblitum** [comment]
> you'll find you can even configure it

My bad on this info, it's not yet possible to configure it, see #1529. But you can find mention for the current fixed location in docs (wiki, etc).

**Comment by oblitum** [comment]
`:h g:coc_extension_root`.

**Comment by caente** [comment]
:man_facepalming: the issue was with an old setting I had in coc-settings.json, from the times before coc-metals
thanks @oblitum and sorry for the extra noise

**Comment by hudengjunai** [comment]
> Add `metals-vim` to your $PATH or use absolute path.

but where is the metals-vim. I can't find this executable file.
