### ISSUE TITLE
Preparing Metals - Failed to download Metals

### ISSUE THREAD

**Issue by mrt181** [neoclide/coc.nvim#1453]
## Result from CocInfo
```
## versions

vim version: NVIM v0.3.8
node version: v12.14.0
coc.nvim version: 0.0.74-e5b05bee4a
term: tmux-256color
platform: linux

## Messages
[coc.nvim] Preparing Metals⠋
[coc.nvim] Preparing Metals⠙
[coc.nvim] Preparing Metals⠹
[coc.nvim] Preparing Metals⠸
[coc.nvim] Preparing Metals⠼
[coc.nvim] Preparing Metals⠴
[coc.nvim] Preparing Metals⠦
[coc.nvim] Preparing Metals⠧
[coc.nvim] Preparing Metals⠇
[coc.nvim] Preparing Metals⠏
[coc.nvim] Preparing Metals⠋
[coc.nvim] Preparing Metals⠙
[coc.nvim] Preparing Metals⠹
[coc.nvim] Preparing Metals⠸
[coc.nvim] Preparing Metals⠼
[coc.nvim] Preparing Metals⠴
[coc.nvim] Preparing Metals⠦
[coc.nvim] Preparing Metals⠧
[coc.nvim] Preparing Metals⠇
[coc.nvim] Preparing Metals⠏
[coc.nvim] Preparing Metals⠋
[coc.nvim] Preparing Metals⠙
[coc.nvim] error: Uncaught exception: Error: Coursier exit: 255
    at ChildProcess.<anonymous> (/home/r892107/.config/coc/extensions/node_modules/coc-metals/lib/index.js:1:7210)
    at ChildProcess.emit (events.js:215:7)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

## Describe the bug

Installing via `:CocInstall coc-metals` seemed to work due to `:CocOpenLog`
Opening some `build.sbt` via `nvim build.sbt ~/.config/nvim/mini.vim`
starts `Preparing Metals` which throws an error
> Failed to download Metals, make sure you have an internet connection and the Java Home '/usr/lib/jvm/java-11-openjdk-amd64/bin/java' is valid. You can configure the Java Home in the settings.See https://scalameta.org/metals/docs/editors/vscode.html#http-proxy for instructions if you are using an HTTP proxy.

## Reproduce the bug
Opening some `build.sbt` via `nvim build.sbt ~/.config/nvim/mini.vim`

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=~/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Addtional information
using a corp. proxy
proxy is set in .jvmopts
```jvmopts
-Dhttp.proxyHost=localhost
-Dhttp.proxyPort=8888
-Dhttp.keepAlive=true
-Dhttps.proxyHost=localhost
-Dhttps.proxyPort=8888
-Dhttps.keepAlive=true
```
proxy is set in .npmrc
```npmrc
proxy=http://localhost:8888/
https-proxy=http://localhost:8888
```
proxy is set in coc-settings.json
```jsonc
{
  "http.proxy": "localhost:8888",
  "metals.javaHome": "/usr/lib/jvm/java-11-openjdk-amd64",
  "coc.preferences.formatOnSaveFiletypes": ["scala"]
}
```

**Comment by chemzqm** [comment]
Looks like coc-metals not using your proxy configuration.

**Comment by mrt181** [comment]
are there any additional logs produced where I can check some error code that might be returned from some connection attempt?

**Comment by chemzqm** [comment]
> [coc.nvim] error: Uncaught exception: Error: Coursier exit: 255

**Comment by mrt181** [comment]
so is coursier ignoring the proxy settings? Or is it possible to see what the proxy is returning, like a 403 or 407 error?

**Comment by ckipp01** [comment]
Hey @mrt181, we actually pull in proxy settings from `metals.serverProperties`, so you'll want to set those flags there so Coursier can use them. This is also pretty specific to `coc-metals`, so if the issue persists, feel free to transfer the issue over there.

**Comment by mrt181** [comment]
@ckipp01 setting proxy like this
```jsonc
 "metals.serverProperties": [    
   "-Dhttp.proxyHost=localhost", 
   "-Dhttp.proxyPort=8888",      
   "-Dhttps.proxyHost=localhost",
   "-Dhttps.proxyPort=8888"      
 ],                              
```
works.

`.jvmopts` which also has those flags is ignored

**Comment by sumew** [comment]
It looks like setting $JAVA_HOME and $JAVA_OPTS is not enough. I had to specify the following settings iin `coc-settings.json`
```
{
  "metals.javaHome": <JAVA_HOME>,
  "metals.serverProperties": [
   "-Dhttp.proxyHost=<proxy_host>",
   "-Dhttp.proxyPort=<port>",
   "-Dhttps.proxyHost=<proxy_host>,
   "-Dhttps.proxyPort=<port>"
 ]


}
```
