### ISSUE TITLE
World readable file created in /tmp/coc-63997.vim

### ISSUE THREAD

**Issue by binaryplease** [neoclide/coc.nvim#1456]
## Result from CocInfo
```
## versions

vim version: NVIM v0.4.3
node version: v13.5.0
coc.nvim version: 0.0.74-dc888b4a6e
term: xterm-termite
platform: linux

## Messages

## Output channel: snippets
```

## Describe the bug

When using coc, vim creates a file under `/tmp/coc-63997.vim` or similar. This file is world-readable:
```
-rw-r--r-- 1 binaryplease    binaryplease    637 Jan  9 13:40 coc-63997.vim
```
I don't know what exactly this file is used for, but this seems like a **security problem**. In case something sensitive is written to it, anyone on the system could read it. 

The current contents of that file are:
```vim
augroup coc_autocmd
  autocmd!
  autocmd BufReadCmd,FileReadCmd,SourceCmd output://* call coc#rpc#request('CocAutocmd', ['BufReadCmd','output', expand('<amatch>')])
autocmd BufReadCmd,FileReadCmd,SourceCmd coc://* call coc#rpc#request('CocAutocmd', ['BufReadCmd','coc', expand('<amatch>')])
autocmd OptionSet runtimepath call coc#rpc#notify('OptionSet',[expand('<amatch>'), v:option_old, v:option_new])
autocmd OptionSet iskeyword call coc#rpc#notify('OptionSet',[expand('<amatch>'), v:option_old, v:option_new])
autocmd OptionSet completeopt call coc#rpc#notify('OptionSet',[expand('<amatch>'), v:option_old, v:option_new])
augroup end
```

Even if the information is not sensitive, I see no reason why this file could not just be readable by the user.

## Reproduce the bug

Just edit a file, look in `/tmp` (linux)

**Comment by fannheyward** [comment]
This file is used for autocmd, and will be removed at next time vim opens.

**Comment by fannheyward** [comment]
I've changed the file mode to 640.
