### ISSUE TITLE
 workspace configuration file can not cover user configuration file

### ISSUE THREAD

**Issue by PLDaily** [neoclide/coc.nvim#1460]
### coc [document](https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file#configuration-file-resolve) 
workspace configuration files is higher priority  than user configuration files

### my config

> use configuration files :cocConfig
```
{
  "git.enableGutters": false
}
```

> workspace configuration files :cocLocalConfig

```
{
  "git.enableGutters": true
}
```
workspace configuration file can not cover user configuration file, coc-git not activated. Other coc plugins has the same problem.

### env

vim version: NVIM v0.4.3
node version: v12.14.0
coc.nvim version: 0.0.74-db5ffd2ff0
term: iTerm.app
platform: darwin

**Comment by fannheyward** [comment]
Do you still have this issue? I've tested with coc-git but can not reproduce this.

**Comment by PLDaily** [comment]
yes, setting use configuration and workspace configuration, then exit neovim and reopen again. issues can be reproduced on my side.

**Comment by fannheyward** [comment]
It's wired. Works for me with this settings:

1. `:CocConfig` set `"git.enableGutters": false`
2. `:CocLocalConfig` set `"git.enableGutters": true`

Restart Neovim and make some changes to doc, gutters sign is shown.

**Comment by fannheyward** [comment]
Global `coc-settings.json` only contains this:

```json
{
  "git.enableGutters": false
}
```

and workspace `.vim/coc-settings.json`:

```json
{
  "git.enableGutters": true
}
```

**Comment by PLDaily** [comment]
Same configuration with you, but not work for me 😂

**Comment by chemzqm** [comment]
>  coc-git not activated.

You can make configuration work as extension not activated.
