### ISSUE TITLE
Add CocCommands as regular command?

### ISSUE THREAD

**Issue by juligreen** [neoclide/coc.nvim#1463]
The fuzzy finder I use (LeaderF) recently added support for fuzzy searching through all available commands. 

Since CocCommands are abstracted by coc.nvim, is it possible to add there as regular commands to be accessed by my fuzzy finder? :)

**Comment by chemzqm** [comment]
Just use `:CocCommand` to open commands list, it does fuzzy match by default.

**Comment by juligreen** [comment]
Yes, I am aware of that, but I would like a single source for all available commands

**Comment by chemzqm** [comment]
> a single source for all available commands

Isn't commands source a single source?

**Comment by chemzqm** [comment]
You have to use `CocAction()` function for other tools.

**Comment by juligreen** [comment]
> Isn't commands source a single source?

Sorry, I don't know what you mean here

**Comment by juligreen** [comment]
To clarify my initial request, my use-case is the following:

I don't know whether a command comes from Coc or from a different plugin, so I'd like to have a single place to look up all available commands.

This means i would either be able to call commands that come from Coc directly in vim command mode, or alternatively I could call native vim commands inside of CocCommand (i think the first scenario would be preferable).

**Comment by chemzqm** [comment]
To run a single command checkout `:h coc-action-runCommand`

**Comment by fannheyward** [comment]
You can get all available coc commands by `:CocList commands` then used in LeaderF.

**Comment by iamcco** [comment]
`echo CocAction('commands')` get all commands

**Comment by juligreen** [comment]
Thank you all, I'm going to try to incoporate this into my workflow and will then share the result here!
