### ISSUE TITLE
[Q] python.sortImports ModuleNotFoundError: No module named 'isort'

### ISSUE THREAD

**Issue by yujinyuz** [neoclide/coc.nvim#1470]
In VSCode, I don't need to do a `pip install isort` in order for the python.sortImports to work.

However, in coc.nvim, I have to install isort on every virtual environment I am working on in order for it to work.

Is it supposed to behave like that?

**Comment by chemzqm** [comment]
No idea

**Comment by yujinyuz** [comment]
Thanks @chemzqm but should the `python.sortImports` work out of the box? I just wanted this to be clarified

**Comment by chemzqm** [comment]
No, coc.nvim doesn't provide that feature out of box.
