### ISSUE TITLE
Filetype for floating windows not being set correctly

### ISSUE THREAD

**Issue by ckipp01** [neoclide/coc.nvim#1473]
It seems that the filetype for floating windows aren't being set correctly in the floatFactory. For example, here is just a snippet in my plugin that creates a flatingWindow
```ts
      await this.floatFactory.create(
        [
          {
            content: hoverText.hoverMessage.value,
            filetype: hoverText.hoverMessage.language
          }
        ],
        true,
        0
      );
```
After checking to make sure that language is set, and then doing a hover, and doing a `set ft?`, I see that it's set to nothing.

<img width="840" alt="Screenshot 2020-01-16 at 15 06 06" src="https://user-images.githubusercontent.com/13974112/72531752-6f1fbe80-3872-11ea-8c3d-fb8e47e2dbf9.png">

After seeing this, I also checked how it reacted to typescript, and it seems to be doing the same thing when I do a hover in a Typescript project. See below:

<img width="840" alt="Screenshot 2020-01-16 at 15 05 02" src="https://user-images.githubusercontent.com/13974112/72531816-8fe81400-3872-11ea-898a-765ac385fb7d.png">

## Result from CocInfo

```vim
vim version: NVIM v0.5.0-3d1531a
node version: v12.13.1
coc.nvim version: 0.0.74
term: iTerm.app
platform: darwin
```

## Reproduce the bug

- Create file `mini.vim` with：
```vim
set runtimepath^=/Users/ckipp/.vim/plugged/coc.nvim,/Users/ckipp/.vim/plugged/onedark.vim
filetype plugin indent on
syntax on
set hidden

set termguicolors
colorscheme onedark

" Use K for show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

" Used to expand decorations in worksheets
nmap <leader>ws <Plug>(coc-metals-expand-decoration)

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```

**Comment by chemzqm** [comment]
It's expected to avoid unnecessary activation of vim plugins, the filetype is used for calculate highlight only.
