### ISSUE TITLE
auto-import not detecting freshly added components until nvim restart

### ISSUE THREAD

**Issue by atsepkov-zaius** [neoclide/coc.nvim#1474]
## versions

vim version: NVIM v0.4.2
node version: v8.11.3
coc.nvim version: 0.0.74-bc017b02e6
term: xterm-256color
platform: darwin

## Output channel: tsserver

[Info  - 12:45:34] Forking TSServer
PATH: /Users/atsepkov/.rvm/gems/ruby-2.3.7/bin:/Users/atsepkov/.rvm/gems/ruby-2.3.7@global/bin:/Users/atsepkov/.rvm/rubies/ruby-2.3.7/bin:/Users/atsepkov/.nvm/versions/node/v8.11.3/bin:/Users/atsepkov/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/atsepkov/.nvm/versions/node/v8.11.3/bin:/Users/atsepkov/bin:/Users/atsepkov/.rvm/bin 
[Info  - 12:45:34] Started TSServer
{
  "path": "/Users/atsepkov/work/zaius/customer-profile-page/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.6.3",
    "version": "3.6.3"
  }
}

## Describe the bug

Context: React + TypeScript

When creating a new component/file, it doesn't make it into coc.nvim auto-import logic until I close and restart nvim. As a result, `coc.nvim` auto-import logic fails to auto-import freshly-created components. I tried restarting tsserver from within nvim but it didn't fix the issue until nvim restart.

## Reproduce the bug

vimrc settings:
  ```vim
  Plug 'neoclide/coc.nvim', {'tag': '*', 'branch': 'release'}
  let g:coc_global_extensions = ['coc-tslint-plugin', 'coc-tsserver', 'coc-emmet', 'coc-css', 'coc-html', 'coc-json', 'coc-yank']
  ```
- open a React/TS project
- start typing a name of component that exists in the project
- auto-completion menu pops up, selecting component auto-imports it as expected
- now create a new file and declare a component, i.e.
  ```
  import * as React from 'react';
  export class MyComponent extends React.Component {
    public render() {
      return (<div></div>);
    }
  }
  ```
- go to any other opened file and attempt to use `MyComponent`, it will trigger auto-completion menu as normal, but will not auto-import the file once the option is picked until vim is closed and restarted

**Comment by chemzqm** [comment]
Use `:CocRestart` or upgrade your coc-tsserver to latest version.

**Comment by chemzqm** [comment]
Should be issue of your tsserver or your project
