### ISSUE TITLE
Add progress bar from extensions installation

### ISSUE THREAD

**Issue by f0s3** [neoclide/coc.nvim#1477]
I have around 15 different coc extensions. I reckon I am not the only one, thus this would be nice if we had an opportunity to see how many plugins were installed in percentages (easier to implement approach) or as a progress bar (a bit more difficult, but still implementable once you have the percentages). I think it might be more user-friendly.

**Comment by fannheyward** [comment]
> how many plugins were installed in percentages

What do you mean? You have 15 extensions installed, and there are 100 extensions available, so the percentage is 15%?

**Comment by yech1990** [comment]
Do you mean reporting the installation progress of each extension in a new window just in the same way as vim-Plug?

**Comment by irrellia** [comment]
This would be a good idea. It would be nice to have a percentage or a progress bar when installing an extension just like vim-plug

**Comment by f0s3** [comment]
Yes, I mean about installation progress. Right now we see something like this: `[coc.nvim] Installing coc-extension` that changes to `[coc.nvim] Installing coc-anotherExtension`.
I suggest that we could see something like a progress bar `[****------]` (* and - are used as an example here). You will see a progress bar only when calling the `:CocInstall` with multiple extensions.

**Comment by chemzqm** [comment]
Using a split window for now, you can get more information.

**Comment by oblitum** [comment]
I find the new split window is nice, but may also be a bit intrusive, for example, when someone starting vim by loading previous session window layout with `vim -S`, the automatic split window may completely destroy the layout the person was expecting.
