### ISSUE TITLE
Switch from fb-watchman to chokidar

### ISSUE THREAD

**Issue by paulmillr** [neoclide/coc.nvim#1482]
Hey! Great plugin you have here.

Have you considered switching from fb-watchman, which is made by Facebook; to Chokidar, which VS Code uses by itself?

The switch will ensure there's one less native dependency, which means less chance of something going wrong during compilation phase. Chokidar uses fsevents macos-native pkg, but it's  n-api-exposed (effectively no compilation).

**Comment by fannheyward** [comment]
Thank you for `Chokidar`.

From https://github.com/microsoft/vscode/blob/master/src/vs/platform/files/node/diskFileSystemProvider.ts#L21-L24, looks like VSCode use Chokidar for `unix` platform, and use <https://github.com/Microsoft/vscode-filewatcher-windows> on Windows. Do you know why? Does Chokidar has any problem on Windows?

**Comment by paulmillr** [comment]
The performance on large file trees is suboptimal on win32 for now — it eats more CPU than other platforms. This is work in progress and should be fixed soon.

How big is a usual directory watched by `watchman` in `coc.nvim`?

**Comment by fannheyward** [comment]
> How big is a usual directory watched by watchman in coc.nvim?

This depends on user's workspace size.

**Comment by paulmillr** [comment]
There may be a performance decrease, and there may be not. VSCode can ship with C# code pre-compiled, many other projects e.g. NPM libraries cannot. So, they can optimize for this case; but even so they've selected chokidar for performance reasons on every other platform.

Other popular tools are using chokidar on windows without huge issues. I think it's worth a try!

**Comment by chemzqm** [comment]
No, chokidar requries rebuild when node version changed, otherwise it would cause high CPU usage.
Chokidar can use lots of CPU and memory, vscode is single instance so it's not big problem but you can have lots of vim instance started in terminal.

**Comment by paulmillr** [comment]
>No, chokidar requries rebuild when node version changed, otherwise it would cause high CPU usage.

Nope.

**Comment by insidewhy** [comment]
At the company I'm working, we had to switch from chokidar to fs-watchman because the performance of chokidar was not so great under Linux, and especially bad inside of a docker-mac container.
