### ISSUE TITLE
(Vim) handle $VIMCONFIG

### ISSUE THREAD

**Issue by KaaJaryi** [neoclide/coc.nvim#1484]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compilé Nov 22 2019 11:10:45)
node version: v8.15.0
coc.nvim version: 0.0.74-6700e7468d
term: dumb
platform: linux

[coc.nvim] Error on install coc-snippets: Error: ENOENT: no such file or directory, open '/home/***/.config/coc/extensions/package.json'
[coc.nvim] Error on install coc-json: Error: ENOENT: no such file or directory, open '/home/***/.config/coc/extensions/package.json'
[coc.nvim] Error on install coc-css: Error: ENOENT: no such file or directory, open '/home/***/.config/coc/extensions/package.json'
[coc.nvim] Error on install coc-javascript: Error: Invalid response from https://registry.npmjs.org/coc-javascript: 404

## Describe the bug

Hi,
I want all my vim stuff to be in ~/.vim (because…). But it seems that Coc still put extensions (and custom snippets via coc-snippets) in ~/.config. I try to bypass that by typing ```export $VIMCONFIG=~/.vim``` and now I can't install extensions. How can I configure coc to have all config files in ~/.vim?
Thanks for everything !

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```export $VIMCONFIG=~/.vim```

  ```vim
  set nocompatible
  "with Plug
  if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  endif
  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start vim with command: `vim -u mini.vim`

- `:PlugInstall`

- `:CocInstall coc-tsserver`

**Comment by fannheyward** [comment]
Check `:h g:coc_config_home`:

> Configure the directory which will be used to look for coc-settings.json and install extensions

**Comment by KaaJaryi** [comment]
Thanks,

I try : ```let g:coc_config_home='/home/***/.vim/coc'``` in my vimrc.

But after reinstalling coc & extentions, ```:CocList extensions``` still gives me:
```* coc-snippets 2.1.17 ~/.config/coc/extensions/node_modules/coc-snippets                             
  + coc-css 1.2.2 ~/.config/coc/extensions/node_modules/coc-css
  + coc-html 1.2.1 ~/.config/coc/extensions/node_modules/coc-html
  + coc-json 1.2.4 ~/.config/coc/extensions/node_modules/coc-json
  + coc-tsserver 1.4.9 ~/.config/coc/extensions/node_modules/coc-tsserver
```

On the other hand, coc-settings.json is in ~/.vim/coc/coc-settings.json (if I do not configure coc_config_home, the path is ~/.vim/coc-settings.json).

**Comment by chemzqm** [comment]
It's excepted.

**Comment by Linerre** [comment]
> 
> 
> Thanks,
> 
> I try : `let g:coc_config_home='/home/***/.vim/coc'` in my vimrc.
> 
> But after reinstalling coc & extentions, `:CocList extensions` still gives me:
> 
> ```
>   + coc-css 1.2.2 ~/.config/coc/extensions/node_modules/coc-css
>   + coc-html 1.2.1 ~/.config/coc/extensions/node_modules/coc-html
>   + coc-json 1.2.4 ~/.config/coc/extensions/node_modules/coc-json
>   + coc-tsserver 1.4.9 ~/.config/coc/extensions/node_modules/coc-tsserver
> ```
> 
> On the other hand, coc-settings.json is in ~/.vim/coc/coc-settings.json (if I do not configure coc_config_home, the path is ~/.vim/coc-settings.json).

Hi  KaaJaryi ,
I think the option you were looking for is indeed `g:coc_data_config`, which you can set to any directory in which you would like all your coc-extensions to be installed. On my Windows machines, I set it to `~/.coc` and it does what I expected.

`g:coc_config_home` is instead used for coc.nvim to look for `coc-settings.json` file. Hope this helps whoever is looking for a solution to similar issues.
