### ISSUE TITLE
Rename run in Floating window

### ISSUE THREAD

**Issue by sluongng** [neoclide/coc.nvim#1485]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
I would like the rename command, instead of having the input in the command line, take input from a small floating window instead. Ideally the floating window should be opened near the current cursor

**Describe alternatives you've considered**
Current solution works, just not that elegant as I have multiple split open, every rename would require me to look at bottom left of the vim window

Thanks :)

**Comment by fannheyward** [comment]
IMO, input in a floating window is not a good experience.

**Comment by sluongng** [comment]
it should be an option for user still

We are already using floating window for completion suggestion (which is response from lsp)

I see no reason why rename action cannot be a floating window that close upon <CR>

**Comment by oblitum** [comment]
Not sure whether it's good or bad, but is a curious request. I've never seen a [neo]vim plugin doing it.

Not specifically this, but related, I think action list should be moved to floating windows builtin. Currently the coc-actions extension works great to provide that, but at this rate it seems like a feature that should be builtin.

**Comment by sluongng** [comment]
https://github.com/junegunn/fzf/commit/4ec403347c803beccffcf7e9f12bacafcb5d24a2

Take a look at the current approach from FZF, which works quite elegantly

**Comment by sluongng** [comment]
as a reference: I am binding FZF.vim `:Commands` to `<leader>a` and it works just like intellij `Cmd + Shift + A`: and omni search for all actions available in editor.

![image](https://user-images.githubusercontent.com/26684313/73285874-fe27c180-41f6-11ea-8fda-01f2529b740e.png)

**Comment by oblitum** [comment]
Ah, I also use something similar with denite. Just didn't connect the dots with that input and a input for rename.

**Comment by chemzqm** [comment]
@sluongng  fzf use terminal buffer for input, but we don't tend like to use that for request user input. It's possible to create a floating window prompt, but not easy and I don't think it's much better than current approach.
