### ISSUE TITLE
bug: Tab completion vs comments is 

### ISSUE THREAD

**Issue by dwmkerr** [neoclide/coc.nvim#1488]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v10.15.3
coc.nvim version: 0.0.74-cd348f4905
term: iTerm.app
platform: darwin

## Messages
no-trailing-spaces: Trailing spaces not allowed.
## Output channel: watchman

[Info  - 1:50:27 PM] watchman watching project: /Users/dwmkerr/repos/github/dwmkerr/crosswords-js
[Info  - 1:50:27 PM] subscribing "**/[tj]sconfig.json" in /Users/dwmkerr/repos/github/dwmkerr/crosswords-js
[Info  - 1:50:27 PM] subscribing "**/package.json" in /Users/dwmkerr/repos/github/dwmkerr/crosswords-js
[Info  - 1:50:27 PM] subscribing "**/*.{ts,tsx}" in /Users/dwmkerr/repos/github/dwmkerr/crosswords-js
[Info  - 1:50:27 PM] subscribing "**/*.{js,jsx}" in /Users/dwmkerr/repos/github/dwmkerr/crosswords-js

## Output channel: tsserver

[Info  - 1:50:27 PM] Forking TSServer
PATH: /Users/dwmkerr/google-cloud-sdk/bin:/Users/dwmkerr/.nvm/versions/node/v10.15.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin:/Users/dwmkerr/.fastlane/bin:/usr/local/share/android-sdk/emulator:/usr/local/share/android-sdk/tools:/Users/dwmkerr/.rvm/gems/ruby-2.6.5/bin:/Users/dwmkerr/.rvm/gems/ruby-2.6.5@global/bin:/Users/dwmkerr/.rvm/rubies/ruby-2.6.5/bin:/Users/dwmkerr/.rvm/bin:/Users/dwmkerr/.rvm/bin 
[Info  - 1:50:27 PM] Started TSServer
{
  "path": "/Users/dwmkerr/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.7.3",
    "version": "3.7.3"
  }
}
```

## Describe the bug

With the configuration set as per the instructions on the homepage, there is an issue with how comments are handled. When coding JavaScript, typing `//` indicates the start of a comment. However, coc.vim will attempt to provide auto-completions for all text in the comment. This means that you cannot strike the `tab` key to create a comment which has two spaces after the final slash, such as this:

```
// This is a comment with slash-slash-tab...
// This is a comment with slash-slash-space...
```

As the auto-complete window pops up. In most other editors (Sublime, Atom, Visual Studio and Code) auto-completion does _not_ occur in comment text, meaning this issue does not occur.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim somefile.js`

- Start writing a comment, attempt to enter two spaces by hitting tab.

```
//<after the second slash, hit 'tab'
```

## Notes

I _think_ that the auto-complete of comments is generally inconsistent with how other editors behave. If it is possible to disable this with configuration that would be awesome, but after searching I've not found out how to do this yet. Any help would be much appreciated!

**Comment by oblitum** [comment]
tab completion is simply a suggested sample configuration in README, it's not even part of codebase, it would be a README code fix.

My personal advice with this is simply ban any of such tab completion, it's not really vim mindset, just stick to default vim keybindings for menu selection (`<c-n>`, `<c-p>`), confirmation/snippet-expansion (`<c-y>`), etc. Leave Tab and Enter alone for their task of insert whitespace, this will avoid a ton of issues. Another problem with confirmation/snippet-expansion on Enter, instead of native `<c-y>`, is that now when you don't want anything from the menu and just want to create a new line, you have to press Enter to close menu, and Enter again to create a new line. You fix the issue by simply not using this map, it's bad.

**Comment by dwmkerr** [comment]
Thanks for the tip @oblitum, makes perfect sense. Do you have a snippet to show how to remap? I've tried adjusting the config from the README but it's still a bit buggy - I like the idea of using the more standard C-N, C-p, C-y bindings, seems logical.

Another question though - do you know if it is possible to disable the popup for comments or languages? It's quite annoying for comments in code and markdown (where the popup just shows words in the document, it's not even using a dictionary, so is kind of just noise).

**Comment by oblitum** [comment]
@dwmkerr you don't need to create any mapping for that, it's already built-in, you just need to remove the tab and enter mappings. Regarding disabling coc, check the schema.json in the sources, it lists all coc.nvim options. Can't give you which now bc I'm on mobile.

**Comment by oblitum** [comment]
Look up "filetype" in `data/schema.json`, you will find how to disable per filetype. For disabling in comments, there's no option in coc.nvim, this is generally an option of the language server, you should look their documentation and pass any flag as parameter in their initialization.
