### ISSUE TITLE
PHP LS fails in large projects

### ISSUE THREAD

**Issue by Kazimazi** [neoclide/coc.nvim#149]
Uppon loading php file I get proper completion for ~10 seconds. After that I won't get any more LS completion. Diagnostics still work, go to definition still work. I have no idea whats wrong , would really be cool if someone who hacked it could help with it.

**Comment by chemzqm** [comment]
Which PHP language server are you using?

**Comment by Kazimazi** [comment]
felixfbecker/php-language-server

**Comment by chemzqm** [comment]
@Kazimazi is there an example of large php project?

**Comment by Kazimazi** [comment]
Just creating a new Symfony project with: `composer create-project symfony/website-skeleton my-project`
And then generating a new controller with `php bin/console make:controller`.
For some weird reason editing felixfbecker/php-language-server project source kept my LS alive.

**Comment by chemzqm** [comment]
I've got the problem, the completion is just too slow.
You need to add
```
  "coc.preferences.timeout": 2000,
```
to your coc-settings.json.

**Comment by chemzqm** [comment]
I can add a warning to the slow souce so user could know what happened.

**Comment by Kazimazi** [comment]
wow that indeed solved it... hopefully felixfbecker/php-language-server gets a speedboost

**Comment by chemzqm** [comment]
I've added a warning message for timeout source.
