### ISSUE TITLE
Keeps spawning lsp server without exhaustion

### ISSUE THREAD

**Issue by hasufell** [neoclide/coc.nvim#1494]
# Result from CocInfo

https://gist.githubusercontent.com/hasufell/0db965347ff9a272b78c3efa0ba881ab/raw/ecd58c0a35a1b0713df5ff3d792dd52ff3467f2c/gistfile2.txt

## Describe the bug

The haskell lsp dies. Coc seems to try re-spawning it indefinitely with no check whatsoever, making my editor unstable and filling up my logs.

## Reproduce the bug

1. install hie
2. install coc.nvim
3. use the following config: https://gist.github.com/hasufell/081cfeb8cc28b314e5d17dc80341ccba
4. hope you run into the same bug

**Comment by oblitum** [comment]
Maybe it's easier to reproduce the issue to simply create a dummy server that writes a message to a file, sleep a second and exit. Could try that to check if it's the same? Because installing haskell tools can be a hassle.

**Comment by hasufell** [comment]
> Could try that to check if it's the same?

Sorry, I don't use coc.nvim anymore, just wanted to let you know that other users might hit the same misbehavior.

> Because installing haskell tools can be a hassle.

:man_shrugging:
