### ISSUE TITLE
[Solved] Error: [coc.nvim] Jedi error: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by clhne** [neoclide/coc.nvim#1496]
## Describe the bug

When my vim(8.0.237) windows os install the coc.nvim(coc-python), it throws an error:
[coc.nvim] Jedi error: Cannot call write after a stream was destroyed.

## Reproduce the bug

- Start (neo)vim with command: `vim *.py`

- Operate vim.       

- Then it will threw the error descripted above.

## Solution

After my in-depth analysis and many attempts. 
The final consideration is the version issue of jedi.
My current version is 0.12.0, when I upgrade the jedi to 0.16.0, it can work normally.
So, I strongly recommend that you write the version of the software it depends on.
Thanks.

**Comment by oblitum** [comment]
Report on coc-python repository, not this.

**Comment by soonoo** [comment]
Changing python interpreter worked for me.
`:CocCommand` -> `python.setInterpreter` command.

**Comment by Nil-Cipher** [comment]
I have the same issue! How did you check the version of Jedi?

**Comment by yamsu** [comment]
On ubuntu 18.04 this was due to Jedi v0.16, updating to 0.17 fixed the issue, I used pip for the upgrade.
```bash
sudo pip3 install -U jedi
```
To update the jedi version restart the vim/nvim session.
To check the existing version
```bash
sudo pip3 search jedi
```
Search for the INSTALLED tag, version follows.

**Comment by thelineover** [comment]
In my case, pip3 not work
~~~bash
pip install -U jedi
~~~
It worked properly pip

**Comment by FilBot3** [comment]
Did that, still not working.

**Comment by gs** [comment]
[this](https://github.com/neoclide/coc.nvim/issues/1496#issuecomment-627201922) fixed my issue ! Thx

**Comment by vince06fr** [comment]
[This](url) fixed the issue for me

**Comment by espijuanjo** [comment]
> Changing python interpreter worked for me.
> `:CocCommand` -> `python.setInterpreter` command.

Is it possible to put it in the .vimrc? How do yo do it?

**Comment by conrad760** [comment]
:CocInstall coc-jedi
