### ISSUE TITLE
Disable completion source from languageserver

### ISSUE THREAD

**Issue by mvcouwen** [neoclide/coc.nvim#1497]
I would like to use the texlab language server together with vimtex. I use the coc extension coc-vimtex. I also enable the texlab language server as follows:
```json
  "languageserver": {
    "latex": {
      "command": "texlab",
      "filetypes": ["tex", "bib", "plaintex", "context"]
    }
  }
```
Using this configuration, I get semantic completion from both vimtex and texlab. Both vimtex and languageserver.latex are listed when I run `:CocList sources`.

Of course, this means that I get every command is suggested twice. Therefore I would like to disable the completion source of the languageserver (as I prefer vimtex's completion). I was thinking that
```json
"coc.source.languageserver.latex.enable": false
```
would solve this issue but apparently there is no such option. Why is this? How can I fix it?

**Comment by fannheyward** [comment]
> "coc.source.languageserver.latex.enable": false

There is no such config option. Why do you want to use both TexLab and vimtex at the same time?

**Comment by mvcouwen** [comment]
They don't have the same features. Vimtex implements a lot of nice features: better syntax highlighting, better indentation, code completion, tex-specific motions and other nice mappings (some things are not supported by the lsp). However, it does not provide e.g. linting or go-to-definition. These features are implemented by TexLab.

**Comment by fannheyward** [comment]
Maybe you can disable completion from Vimtex ? Check `:h g:vimtex_complete_enabled`.

**Comment by mvcouwen** [comment]
Yes, that would be possible, but I think I prefer the completion from vimtex. I can configure vimtex to automatically put closing braces for example. How difficult would it be to implement this config option? Can it be done from the client side or should it be implemented in the texlab server?

**Comment by mvcouwen** [comment]
See also https://github.com/lervag/vimtex/issues/1371#issuecomment-504428415 for a comparison between TexLab and vimtex.

**Comment by oblitum** [comment]
[`disableCompletion`](https://github.com/neoclide/coc.nvim/blob/master/data/schema.json#L33) should work.

I think https://github.com/neoclide/coc.nvim/blob/master/data/schema.json should be mentioned in readme for people to look for available options. To many issues are open just for simple question that can be answered by looking up that file.

**Comment by fannheyward** [comment]
> Can it be done from the client side or should it be implemented in the texlab server?

server side.

**Comment by fannheyward** [comment]
Oh, thanks for @oblitum, `disableCompletion` will ignore completion items form server, this should work.

**Comment by fannheyward** [comment]
Also, you can checkout https://github.com/fannheyward/coc-texlab with build commands support. 😄

**Comment by mvcouwen** [comment]
@oblitum Works like a charm! That file is indeed really useful!

**Comment by przepompownia** [comment]
I have no idea how to use `disableCompletion` with an extension. For example, `"phpactor.disableCompletion": true,` does not work for me (with [coc-phpactor](https://github.com/phpactor/coc-phpactor)) but
```json
    "phpactor": {
      "trace.server": "verbose",
      "disableCompletion": true,
      "filetypes": ["php"],
      "command": "phpactor",
      "args": ["language-server"]
    }
```
works for a standalone LS.

**Comment by oblitum** [comment]
@przepompownia this is problematic indeed, when you pick a coc extension over a raw language server configuration, you lose language server setup options, and are left with the options the coc extension author publishes.

**Comment by przepompownia** [comment]
Isn't it related to choose what is registered by the client on `initialize` (in other words, isn't it a client-specific issue)? I noticed that `initialize` request does not contain `completion` section when `disableCompletion` works.

**Comment by oblitum** [comment]
@przepompownia I'm not sure as I'm not an LSP dev. But to sum it up what happens is that settings available in standalone server setup are settings for coc.nvim to recognize, when you change to a coc extension, those settings cease to exist because a coc extension is not a language server, it's a wrapper for one, so it's responsible for providing its own configuration flags. A coc extension could publish a `disableCompletion` setting, that would set that for the internal language server it wraps, but often that's not done.

**Comment by przepompownia** [comment]
What would have happened if CoC as the client had not registered the `completion` ability even if the extension had not expose such an option? Would such a request (i.e. not containing `completion`) be overridden by the extension?
