### ISSUE TITLE
python

### ISSUE THREAD

**Issue by 1235452356** [neoclide/coc.nvim#1499]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
What's your problem?

**Comment by 1235452356** [comment]
系统是archlinux

**Comment by chemzqm** [comment]
Try `:verbose nmap K`
