### ISSUE TITLE
cpu overload when i move visually selected block

### ISSUE THREAD

**Issue by deathmaz** [neoclide/coc.nvim#150]
**Describe the bug**
i have these mapping in nvim config:
```
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
```
I'm using it to visually select a block of text and move it up and down. I noticed that when i'm doing this coc overloads my cpu and at this point if i do `:w` nvim will freeze.
I recoreded the issue with asciinema. In split i opened htop so you can see the cpu status while the issue happens. Also its not visible in the record but after i `:w` and nvim get freezed i killed coc process in different window, after that you see those red messages in nvim.

**To Reproduce**
1. `nvim test.scss`
2. visualy select few lines of text and use mapping above to move it up and down; 

**Expected behavior**
no cpu overload and no nvim freeze while moving visualy selected text;

**Screenshots**
https://asciinema.org/a/9tXv4aQ2iFRNmuONvrcPQm3AH

**Desktop (please complete the following information):**
 - Terminal: kitty 0.12.3
 - NVIM v0.3.1

**Additional context**
Thank you for the help and nice plugin!

**Comment by chemzqm** [comment]
I've tried your action without any problem.
Maybe your extension need to rebuild, try `:CocRebuild` in your vim.
If you're using node 11 you may still have CPU issue, try the binary version of coc or set `g:coc_node_path` to executable of node 10.
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#not-working-after-upgrade-node

**Comment by deathmaz** [comment]
Indeed the problem is because of node 11, when i set `let g:coc_node_path = '~/.nvm/versions/node/v10.13.0/bin/node'` it doesn't help, i still have the issue. But when i change the version of node with node version manager then it worked. Do you know why `g:coc_node_path` didn't work?

**Comment by chemzqm** [comment]
Might because it doesn't take effect, I use `g:coc_node_path` and it works for me.

**Comment by deathmaz** [comment]
can i check which version of node is currently used by coc?

**Comment by deathmaz** [comment]
now i have this when i start nvim:
```
Error detected while processing function coc#rpc#start_server:
line   25:
[coc.nvim] Failed to start coc service
Press ENTER or type command to continue
```

**Comment by deathmaz** [comment]
also now `echo coc#util#job_command()` returns the correct path to node `['~/.nvm/versions/node/v10.13.0/bin/node', '/home/maz/dotfiles/.config/nvim/plugged/coc.nvim/bin/server.js']`

**Comment by chemzqm** [comment]
You can't use `~` there's no shell to expand it, you can use `$HOME` to replace it.

**Comment by deathmaz** [comment]
i used this `let g:coc_node_path = glob('~/.nvm/versions/node/v10.13.0/bin/node')`
now everything works fine.
Thank you very much for the help!
