### ISSUE TITLE
python查看文档的问题

### ISSUE THREAD

**Issue by 1235452356** [neoclide/coc.nvim#1500]

**Comment by 1235452356** [comment]
我使用nnoremap K :call show_documentation() "查看文档
在python文件中 使用 快捷键 K 时, 光标向后跳跃, 在我把 K 键 改成 M键后, 依旧向后跳跃.
我的 neovim版本是0.4.3

**Comment by 1235452356** [comment]
使用 coc-python

**Comment by 1235452356** [comment]
![深度录屏_deepin-terminal_20200127230612](https://user-images.githubusercontent.com/52132505/73187201-067eee80-415c-11ea-9289-184dd6afca31.gif)

**Comment by fannheyward** [comment]
没办法复现 （macOS），请提供一个最小化 vimrc 来复现这个问题。

**Comment by 1235452356** [comment]
[init.vim.txt](https://github.com/neoclide/coc.nvim/files/4118114/init.vim.txt)

**Comment by 1235452356** [comment]
去掉 .txt

**Comment by 1235452356** [comment]
![深度录屏_选择区域_20200128235107](https://user-images.githubusercontent.com/52132505/73280341-52e43000-4229-11ea-81e5-3025ab783fa5.gif)


可以复现么

**Comment by 1235452356** [comment]
![深度录屏_deepin-terminal_20200129003634](https://user-images.githubusercontent.com/52132505/73284396-78743800-422f-11ea-95c2-6345d84868e4.gif)

bash 文件查看文档也会向后跳跃

**Comment by fannheyward** [comment]
*_最小化_* vimrc

你自己有试过去掉 coc 以外的插件，还会有这种问题吗？

**Comment by 1235452356** [comment]
是的,我去掉了所有的插件,还是有这样的问题

**Comment by 1235452356** [comment]
![深度录屏_deepin-terminal_20200131220240](https://user-images.githubusercontent.com/52132505/73545111-a2b73700-4475-11ea-89eb-1f67ca596c71.gif)

**Comment by iamcco** [comment]
@1235452356 把你映射按键后面的注释和空格删掉

**Comment by 1235452356** [comment]
谢谢, 这解决了我的问题
