### ISSUE TITLE
Double cursors

### ISSUE THREAD

**Issue by nomasprime** [neoclide/coc.nvim#1501]
## Result from CocInfo

vim version: NVIM v0.5.0-nightly
node version: v13.6.0
coc.nvim version: 0.0.74-6700e7468d
term: iTerm.app
platform: darwin

## Describe the bug

After `CocList` command I get two cursors: my normal one at the beginning of the line flashing and another block cursor but solid where the actual input is after the `FUZZY >` prompt.

Actually the reason I stopped using FZF because it uses term emulator.

## Reproduce the bug

Plug 'neoclide/coc.nvim', { 'branch': 'release' }
nnoremap <Leader>f :CocList files<CR>

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by oblitum** [comment]
I confirm there's this issue.

**Comment by fannheyward** [comment]
There is only one cursor with my testing: line flashing at the beginning of the `FUZZY >` line, no block cursor.

```
vim version: NVIM v0.5.0-343-ge956ea767
node version: v13.7.0
coc.nvim version: 0.0.74
term: iTerm.app
platform: darwin
```

mini.vim

```set nocompatible
set runtimepath^=~/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

nnoremap f :CocList files
```

**Comment by oblitum** [comment]
@fannheyward maybe this will depend on the kind of cursor you have enabled in NeoVim (for example, I disable `set guicursor=`, b/c I prefer block cursor in general, which is not the NeoVim default anymore), despite that, there are two, one at the start, and one at the end.

**Comment by oblitum** [comment]
@fannheyward just confirmed it's that, by adding `set guicursor=` to your `mini.vim`.

**Comment by fannheyward** [comment]
@oblitum Could you please add a screenshot? I added `set guicursor=`, now there is still one cursor at the beginning of `FUZZY >` line, with block style.

**Comment by oblitum** [comment]
@fannheyward ah sorry, indeed, I get just one cursor with that minimal conf. Which is at the beginning, over F. Isn't that in the wrong place already? Weirdly enough, I don't get any cursor at end of line, after typing characters, which I think is bad as indication of cursor position.

I get two cursor, one additional at the end, only with my full conf, I still ignore what's the reason the ending cursor is showing up in this case.

**Comment by fannheyward** [comment]
> Isn't that in the wrong place already? 

Yes, wrong place.

**Comment by yatli** [comment]
This is more like a NeoVim problem.
I get this behavior in TERMINAL buffers.
To workaround, use `C-\ C-N` to enter normal mode, and then go back to insert mode.

**Comment by chemzqm** [comment]
Can't fix, don't use `set guicursor=`, it's possible to hide the cursor, but not possible to revert, should be bug of neovim or terminal.

**Comment by oblitum** [comment]
>  don't use `set guicursor=`

coc.nvim should not require this setting to work correctly, many people don't like gui cursor in the terminal.

If using gui cursor is part of a trick attempting to hide the real cursor, it can possibly be set just where it's necessary, like only in `:CocList`, maybe?

This relates with a setting I do on my `.vimrc` for defx buffer, which is a file browser, where the block cursor also isn't great, just on that buffer, actually I wished I could completely hide the cursor there but it doesn't work, so at that buffer I set a gui cursor, but anytime I'm out of defx buffer, it goes back to my preferred cursor. I have to do this:

```vim
autocmd vimrc FileType defx setlocal cursorline | set guicursor=n:ver100
autocmd vimrc BufEnter * if &filetype ==? 'defx' | set guicursor=n:ver100 | endif
autocmd vimrc BufLeave * if &filetype ==? 'defx' | set guicursor=a:block | endif
autocmd vimrc VimLeave * set guicursor=a:block
```

**Comment by chemzqm** [comment]
It's just an extra cursor there which is better than broken cursor.
Need fix of neovim.
