### ISSUE TITLE
what's the difference between disable and deactivate coc.nvim or activate and enable extension?

### ISSUE THREAD

**Issue by 4volodin** [neoclide/coc.nvim#1503]
what's the difference between disable and deactivate coc.nvim or activate and enable extension?

**Comment by oblitum** [comment]
Words depends on context. It can mean have the plugin disabled by the plugin manager or not, called `:CocDisable` or not, called `:CocEnable` or not, disable in `coc-settings.json` by filetype or not, etc.

**Comment by chemzqm** [comment]
Disable means disable extension from load forever, deactivate means deactivate an activated extension which have been loaded.
