### ISSUE TITLE
Confusion about CocCommand

### ISSUE THREAD

**Issue by klaaspieter** [neoclide/coc.nvim#1504]
I'm diving into the world of language servers and trying to figure some things out. I often try things in coc, realize it doesn't work and then see _how_ it works in VSCode. One such example is `textDocument/codeAction`. This may be specific to [sourcekit-lsp](https://github.com/apple/sourcekit-lsp/) so please bear with me.

This is the test file I've been using:

```swift
struct Test {
    var text = "Hello, World!"
}
```

In VSCode when I put my cursor on `Test` and bring up the command palette I see “Refactor”. Selecting it I get “Generate Memberwise Initializer”. This is genuinely useful in Swift and I want the same behavior in coc unfortunately it took a long time to figure out how to trigger it. 

I looked at `CocCommand`, adding it as a custom command, realized the VSCode extension doesn't need a custom command for it, `CocRequest`,  and finally decided coc must not support it.

Whle trying to add it I finally found [`coc-codeaction`](https://github.com/neoclide/coc.nvim/blob/db5ffd2ff0d766c2cfbd711898e8a3f5736e038c/doc/coc.txt#L735) and [`coc-codeaction-selected`](https://github.com/neoclide/coc.nvim/blob/db5ffd2ff0d766c2cfbd711898e8a3f5736e038c/doc/coc.txt#L739). These were not easy to find which leads me to my main point.

It appears coc requires a lot of upfront knowledge about language servers. Perhaps if I had known this is a [`codeAction`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction) this would've been easier to find.

Furthermore the documentation calls the results of `textDocument/codeAction` `Command`s so I still feel `CocCommand` should've been the right thing to use 🤔 

If not `CocCommand` perhaps it's worth considering having some other way to trigger a command palette like VSCode?

**Comment by oblitum** [comment]
`CocCommand` is general purpose for commands, and a codeAction is just one of those. There are many other commands, not even related to LSP, like many extensions provide update commands for their servers.

For me this was all pretty straightforward and there's documentation, it's just that it's not the most comprehensive documentation for those that are completely new to LSP terminology. I guess PR welcome on that.

**Comment by klaaspieter** [comment]
> CocCommand is general purpose for commands, and a codeAction is just one of those

I'm confused. Am I supposed to see `codeActions` in the `CocCommand` list? 

As an aside; I just noticed VSCode doesn't actually exposes code actions directly either. Instead it has a [generic Refactor command](https://code.visualstudio.com/docs/editor/refactoring#_refactoring-actions) than when triggered shows the available `codeActions` for the selected line. So it's a bit like `coc-codeaction-selected` but easier to discover.

Any thoughts about adding a default Refactor command?

**Comment by oblitum** [comment]
IMO coc should follow VSCode in the LSP sense and support, no need to create a replica for Vim. But that's up to the author.

**Comment by klaaspieter** [comment]
@oblitum I don't disagree. If I wanted VSCode I would use VSCode.

In this case however I think VSCode has a much better discovery mechanism than coc does. Not everyone is inimately familiar with language servers and what they can do. I like that VSCode allows for easier exploration and would love if coc could do the same.

I'm happy to look at implementing it myself if it's something coc wants to support.

**Comment by chemzqm** [comment]
When you're using VSCode they have extension which could register custom commands, there's why there's coc extension as well.

**Comment by klaaspieter** [comment]
@chemzqm that's why I'm asking. I made a sourcekit extension (https://github.com/klaaspieter/coc-sourcekit) but I can't figure out if I should be defining custom commands or add documentation on how to use the various `codeActions` sourcekit-lsp supports.

Either way pretty much the same extension for VSCode does not have to [contribute any custom commands](https://github.com/apple/sourcekit-lsp/blob/94585a79fb1f80d73ed218b2af39a0951b53f5a8/Editors/vscode/package.json#L39-L65) for it to work.

I feel like I may not be comparing apples to apples. So far I've seen `CocCommand` as the “coc command palette”. This thing in VSCode:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/98880/73661114-d1adf280-4699-11ea-8568-1ebc5d69cbf0.png">

After reading this, and other issues I'm still not sure if that's the right conclusion. For what it's worth that “Refactor” command is what VSCode adds and it puts all `codeActions` behind it. So if I trigger it in Swift I get the following when a struct name is selected:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/98880/73661267-133e9d80-469a-11ea-8597-8dfcae964d20.png">

_I_ expect `CocCommand` to do the same but my mental modal of `CocCommand` may be completely wrong. I opened this issue to figure that out. And, assuming my mental is wrong, what the right solution would be in coc.

So let's say I _do_ want that member wise initializer code action in coc should I:

1. Add a custom command that triggers it? Can it be context aware; only offering the right command for the currently selected code?
2. Document how to trigger `coc-codeaction-selected`?
3. Add similar functionality to Coc that VSCode has. Basically adding the “Refactor” command to the default `CocCommand` list?

I'm fine with all three (although _I_ would expect 3). I'm just trying to figure out what is expected from a coc perspective.

**Comment by oblitum** [comment]
Have you taken a look at the coc-actions extension?

**Comment by iamcco** [comment]
> Add a custom command that triggers it? Can it be context aware; only offering the right command for the currently selected code?

I think this is depend on the command use situation. CocAction for context aware. CocCommand for common usage.

> Document how to trigger coc-codeaction-selected?

coc.nvim readme have the document of trigger `coc-codeaction-selected`

https://github.com/neoclide/coc.nvim/blob/master/Readme.md#L138

> Add similar functionality to Coc that VSCode has. 

 CocAction is same as VSCode.

https://github.com/neoclide/coc.nvim/blob/master/src/languages.ts#L206

**Comment by chemzqm** [comment]
>  For what it's worth that “Refactor” command is what VSCode adds and it puts all codeActions behind it. 

Yes, we don't have `Refactor` command for list all refactor commands from language server, you have to use codeactions feature for now.
