### ISSUE TITLE
API to get contents of CocList without opening CocList selection window

### ISSUE THREAD

**Issue by wbthomason** [neoclide/coc.nvim#1505]
**Is your feature request related to a problem? Please describe.**
I would like to use the contents of coc.nvim lists in other plugins, without using the `CocList` selection window.

**Describe the solution you'd like**
I'd like there to be (or to learn about if it already exists) an API for getting the contents of a CocList as a Vim list.

**Describe alternatives you've considered**
I've looked through the source to see how the `:CocList` command works, and can't find the correct RPC call to make to just get the list content without triggering the selection window.

**Additional context**
N/A

**Comment by fannheyward** [comment]
[vista.vim](https://github.com/liuchengxu/vista.vim) can list `documentSymbols` provided by coc, you can checkout how vista.vim does:  use `call CocAction()` or `call CocActionAsync()` to get list contents, and parse to vim list.  https://github.com/liuchengxu/vista.vim/blob/master/autoload/vista/executive/coc.vim#L52

`diagnosticList` for diagnostic, `commands` for commands list, `extensionStats` for extensions list, and so on.

Currently, coc have no plan to provide API to get contents of list.

**Comment by wbthomason** [comment]
Alright, taking the vista.vim approach works for me for now. Thanks!

**Comment by chemzqm** [comment]
There're some APIs for specific lists.

**Comment by wbthomason** [comment]
@chemzqm: I'm not sure what those APIs are or which specific lists you mean, but right now this doesn't matter; I've adopted the approach suggested by @fannheyward for my plugin.
