### ISSUE TITLE
Profile problem couple

### ISSUE THREAD

**Issue by Gemo-X** [neoclide/coc.nvim#1509]
Can I migrate my profile to a specific location?
And it will be better to separate the installed plug-ins.

**Comment by fannheyward** [comment]
Please check `:h g:coc_extension_root`.

**Comment by Gemo-X** [comment]
Sorry, maybe I made a mistake.

`g: coc_extension_root` can only set the installation location of the coc plugin and the storage location of node_modules.

If you need to simplify the configuration, you can add a separate file and configure the plug-in (not `package.json`) you need to install.
You can set the plug-in directory file and one-click installation file when migrating the system.

Try to keep `$VIMPATH` simple and avoid redundant configuration.

In addition, the `toml` configuration seems to be better than the `json`.

**Comment by chemzqm** [comment]
`:h g:coc_config_home`
