### ISSUE TITLE
Golang auto complete. Redundant entries in auto completion list 

### ISSUE THREAD

**Issue by ray-x** [neoclide/coc.nvim#1511]
## versions

vim version: NVIM v0.4.3
node version: v8.17.0
coc.nvim version: 0.0.74
term: iTerm.app
platform: darwin

## Messages
NERDTree: CWD is now: /Users/rayx/go/src/github.com/SafetyCulture/iot/cmd/alertmanager
## Output channel: snippets

[Error 09:57:15] Convert regex error for: li(st)? (?<num>\d+)$
[Error 09:57:15] Convert regex error for: ol(st)? (?<num>\d+)$

## Output channel: languageserver.golang

[Info  - 09:57:15] 2020/01/30 09:57:15 Build info
----------
golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
    golang.org/x/tools@v0.0.0-20191206201009-952e2c076240 h1:metzFnqcC0vUPmZX4El8bICiQU9hieZ3L9dXAitxVXQ=
    golang.org/x/xerrors@v0.0.0-20190717185122-a985d3407aa7 h1:9zdDQZ7Thm29KFXgAX/+yaf3eVbP7djjWp/dXAppNCc=
    honnef.co/go/tools@v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXeM=

Go info
-------
Using the mini.vim and run CocInfo

go version go1.13.4 darwin/amd64

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rayx/Library/Caches/go-build"
GOENV="/Users/rayx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="github.com/xxx"
GONOSUMDB="github.com/xxx"
GOOS="darwin"
GOPATH="/Users/rayx/go/"
GOPRIVATE="github.com/xxx"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"

## Describe the bug

As title, each functions in auto completion list appears twice. E.g if I type "fmt."   function Errorf should appear only once 

coc-settings.json: 

  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
  }

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/Users/username/.vim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim  main.go -u mini.vim`

- Operate neovim.

## Screenshots (optional)

<img width="1030" alt="Screen Shot 2020-01-30 at 9 41 49 am" src="https://user-images.githubusercontent.com/1681295/73404473-b2376280-4345-11ea-8496-754f86ce422e.png">

**Comment by oblitum** [comment]
This is in general a server issue, unable to reproduce it. Maybe it's you gopls version/commit?

**Comment by oblitum** [comment]
This happened with Dart language server for example, see: https://github.com/dart-lang/sdk/issues/38911.

**Comment by chemzqm** [comment]
Try add `"disableDynamicRegister": true` in your server configuration.

**Comment by ray-x** [comment]
I added "disableDynamicRegister": true in server config
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"],
      "disableDynamicRegister":true,
      "initializationOptions": {
        "usePlaceholders": true
       }
    }
But see no difference. Also gopls was used in other plugin (e.g youcompleteme) but seems to be working fine

**Comment by chemzqm** [comment]
Checkout `:CocList sources` for all available completion sources.
Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel for verbose output from language server.

**Comment by Ray-Xu-SC** [comment]
I checked the debug server in verbose mode.
It shows that the gopls does not provide duplicate items, Here is part of the logs of output:



textDocument/completion
{
  "isIncomplete": true,
  "items": [
    {
      "label": "Close",
      "kind": 2,
      "detail": "func()",
      "documentation": "Close connection with the db",
      "preselect": true,
      "sortText": "00000",
      "filterText": "Close",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 16,
            "character": 9
          },
          "end": {
            "line": 16,
            "character": 9
          }
        },
        "newText": "Close()"
      },
      "command": {
        "title": "",
        "command": "editor.action.triggerParameterHints"
      }
    },
    {
      "label": "GetExternalUserEmailByID",
      "kind": 2,
      "detail": "func(ctx context.Context, externalUserID uuid.UUID) (string, error)",
      "sortText": "00001",
      "filterText": "Close",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 16,
            "character": 9
          },
          "end": {
            "line": 16,
            "character": 9
          }
        },
        "newText": "GetExternalUserEmailByID(${1:ctx context.Context}, ${2:externalUserID uuid.UUID})"
      },
      "command": {
        "title": "",
        "command": "editor.action.triggerParameterHints"
      }
    },
    {
      "label": "GetExternalUsersByEmail",
      "kind": 2,
      "detail": "func(ctx context.Context, emails []string) ([]store.ExternalUser, error)",
      "sortText": "00002",
      "filterText": "Close",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 16,
            "character": 9
          },
          "end": {
            "line": 16,
            "character": 9
          }
        },
        "newText": "GetExternalUsersByEmail(${1:ctx context.Context}, ${2:emails []string})"
      },
      "command": {
        "title": "",
        "command": "editor.action.triggerParameterHints"
      }
    },
    {
      "label": "GetTaskSnapshot",
      "kind": 2,
      "detail": "func(ctx context.Context, taskID uuid.UUID) (*store.Task, error)",
      "sortText": "00003",
      "filterText": "Close",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 16,
            "character": 9
          },
          "end": {
            "line": 16,
            "character": 9
          }
        },
        "newText": "GetTaskSnapshot(${1:ctx context.Context}, ${2:taskID uuid.UUID})"
      },
      "command": {
        "title": "",
        "command": "editor.action.triggerParameterHints"
      }
    },
    {
      "label": "GetTaskType",
      "kind": 2,
      "detail": "func(ctx context.Context, taskID uuid.UUID) (int32, error)",
      "sortText": "00004",
      "filterText": "Close",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 16,
            "character": 9
          },
          "end": {
            "line": 16,
            "character": 9
          }
        },
        "newText": "GetTaskType(${1:ctx context.Context}, ${2:taskID uuid.UUID})"
      },
      "command": {
        "title": "",
        "command": "editor.action.triggerParameterHints"
      }
    },
    {
      "label": "SaveStateOnTaskActivitiesOrgIDUpdated",
      "kind": 2,
      "detail": "func(ctx context.Context, taskID uuid.UUID, orgID uuid.UUID) error",
      "sortText": "00005",
      "filterText": "Close",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 16,
            "character": 9
          },
          "end": {
            "line": 16,
            "character": 9
          }
        },
        "newText": "SaveStateOnTaskActivitiesOrgIDUpdated(${1:ctx context.Context}, ${2:taskID uuid.UUID}, ${3:orgID uuid.UUID})"
      },
      "command": {
        "title": "",
        "command": "editor.action.triggerParameterHints"
      }
    },
......
]

**Comment by oblitum** [comment]
I'm reopening as you're providing protocol logs showing it's not the server that's sending duplicates. Though I use  gopls and can't experience the same issue.

**Comment by chemzqm** [comment]
Looks like you've configured duplicated sources.
Checkout `:CocList sources` for all available completion sources.

**Comment by ray-x** [comment]
> Looks like you've configured duplicated sources.
> Checkout `:CocList sources` for all available completion sources.

The output is as below:
```
  * languageserver.golang [LS] 99 go,go
  * go [LS] 99 go
  * file [F] 10
  * buffer [B] 1
  * around [A] 1
```

I am using mini.vim and setting.json:
```
{
    "suggest.noselect": false,
    "coc.preferences.formatOnSaveFiletypes": [
      "javascript",
      "typescript",
      "typescriptreact",
      "json",
      "javascriptreact",
      "typescript.tsx",
      "graphql"
    ],
    "languageserver": {
      "golang": {
        "command": "/Users/bane/go/bin/gopls",
        "trace.server":"verbose",
        "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
        "filetypes": ["go"],
        "disableDynamicRegister":true,
        "coc.preferences.colorSupport": false,
        "initializationOptions": {
          "usePlaceholders": true
         }
      }
    }
  }
}
```
It seems that the languageserver setup is not need for golang completion.  If I remove languageserver, the issue gone.

Is it because of coc-go conflicting with languageserver setup?

**Comment by fannheyward** [comment]
@ray-x if you are using `coc-go`, remove gopls config in `coc-settings.json`

**Comment by ifraixedes** [comment]
@fannheyward I use `coc-go` and I removed the `"command": "gopls"` in order of defining a module, however there is a linter complain saying that `"module"` property is required, what value should I set in `"modules"`?

My `coc-settings.json`

```json
  {                                                                                                                                                                              
    "coc.source.gocode.filetypes": [                                                                                      
      "go"                                                                                                                
    ],                                                                                                                    
    "coc.source.gocode.priority": 99,                                                                                     
    "coc.source.gocode.shortcut": "Go",                                                                                     
    "go.goplsOptions": {                                                                                                  
      "analyses": {                                                                                                       
        "fieldalignment": true,                                                                                           
        "shadow": true,                                                                                                   
        "staticcheck": true,                                                                                              
        "unusedparams": true                                                                                              
      },                                                                                                                  
      "gofumpt": true,                                                                                                    
      "usePlaceholders": true                                                                                             
    },                                                                                                                    
    "go.tags": {                                                                                                          
      "transform": "camelcase"                                                                                            
    },                                                                                                                    
    "languageserver":{                                                                                                    
      "go":{                                                                                                                                                                                                           
        "disableDynamicRegister": false,                                                                                  
        "filetypes": ["go"],                                                                                              
        "rootPatterns": ["go.mod"],                                                                                       
        "trace.server": "verbose"                                                                                         
      }                                                                                                                   
    },                                                                                                                    
    "suggest.autoTrigger": "trigger"                                                                                      
  }
```

**Comment by fannheyward** [comment]
@ifraixedes if you're using coc-go, you should remove the `go` section under languageserver in your coc-settings.Jason
