### ISSUE TITLE
Trying to debug highlight

### ISSUE THREAD

**Issue by BonaBeavis** [neoclide/coc.nvim#1512]
I have following issue:

![image](https://user-images.githubusercontent.com/3330855/73550095-40920e00-4444-11ea-90a9-0f397b77d29a.png)

The highlight around `:` are broken, this issue does not exist with a vanilla config. So my question is:
where does this highlight gets set? I like to debug this...

Thanks!

**Comment by chemzqm** [comment]
Create key mapping like:
``` vim
  " show vim highlight group under cursor
  nnoremap <leader>hi :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
    \ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
    \ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
```
move your cursor to float window and use that key mapping.

**Comment by BonaBeavis** [comment]
Thanks, but I forgot to mention, that I already tried this. Showing the highlight only works in the buffer,  but not the float. In the float it always returns `hi<> trans<> lo<>`.

**Comment by chemzqm** [comment]
@BonaBeavis Move your cursor to cover the text.

**Comment by BonaBeavis** [comment]
It works the the regular buffer:
![image](https://user-images.githubusercontent.com/3330855/74839929-62393380-5326-11ea-99d2-f0e4cdde3dae.png)

But not in a floating window:
![image](https://user-images.githubusercontent.com/3330855/74839793-27cf9680-5326-11ea-8c33-f47aa0775d20.png)

**Comment by chemzqm** [comment]
Copy the code to your normal buffer and checkout.

**Comment by oblitum** [comment]
@chemzqm I think in the normal buffer it's not same behavior, only in float.

**Comment by chemzqm** [comment]
It's same highlight group, use transparent background color instead of Normal to fix this problem.

**Comment by oblitum** [comment]
Hmm, guess you're suggesting he should get the highlight group in normal buffer (where it's possible), even though there's no problem there.

**Comment by BonaBeavis** [comment]
Found the issue, see the pull request...

thx a lot!
