### ISSUE TITLE
CocInstall unable to ignore certificate errors

### ISSUE THREAD

**Issue by adanilev** [neoclide/coc.nvim#1514]
**Is your feature request related to a problem? Please describe.**
My work setup is behind a proxy which uses a self-signed certificate. I can't use CocInstall because I get the following error: `Error: self signed certificate in certificate chain`

**Describe the solution you'd like**
Add a setting which lets me ignore certificate errors.

I have set http.proxyStrictSSL to false and am pointing npm.binPath at the correct npm install and have strict-ssl set to false in .npmrc.

**Describe alternatives you've considered**
Allow extensions to be installed in a different way?

**Additional context**
CocInfo:

```
## versions

vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 22 2019 19:03:04)
node version: v10.17.0
coc.nvim version: 0.0.74-6700e7468d
term: iTerm.app
platform: darwin

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/.vim/coc-settings.json" 8L, 132C
[coc.nvim] Error on install coc-json: Error: self signed certificate in certificate chain
```

**Comment by fannheyward** [comment]
`export NODE_TLS_REJECT_UNAUTHORIZED=0` first, and start vim to `:CocInstall`.

**Comment by adanilev** [comment]
Thanks @fannheyward, that did the trick for installing but won't automatic updates still error out? A coc setting for this could fix it for good.

**Comment by fannheyward** [comment]
Try `"https.rejectUnauthorized": false`.

**Comment by jdrouhard** [comment]
@fannheyward I think we need the same change to `model/fetch.ts`. Using this param doesn't actually allow the fetch code to download the list of packages from the repository website. Local testing confirms that adding the same option in `fetch.ts` resolves the issue fully.

**Comment by fannheyward** [comment]
@jdrouhard https://github.com/neoclide/coc.nvim/commit/d36b4101fc305783d513aae351c7ace4d26a91d8

**Comment by chemzqm** [comment]
We should use `http.proxyStrictSSL` which does the same as `https.rejectUnauthorized`

**Comment by tristan957** [comment]
I am currently trying to use CoC behind a corporate proxy. I have setup the proxy settings correctly and disabled strictSSL in my coc config, npm config, and yarn config. I am still seeing TLS client disconnected issues. If I navigate to ~/.config/coc/extensions and no a yarn install, then the extensions are installed correctly. I am not entirely sure what else to do regarding setting this up.

coc-settings.json
```json
{
        "languageserver": {},
        "git.enableGutter": true,
        "http.proxyStrictSSL": false,
        "http.proxy": "ex-proxy.com:80"
}
```

.npmrc
```
https-proxy=http://ex-proxy.com:80
strict-ssl=false
proxy=http://ex-proxy.com:80/
```

.yarnrc
```
https-proxy "http://ex-proxy.com:80"
lastUpdateCheck 1599605316642
proxy "http://ex-proxy.com:80"
strict-ssl false
```

![image](https://user-images.githubusercontent.com/11936772/92611026-f85e8800-f27d-11ea-9ced-a94ae7bc7701.png)

**Comment by fannheyward** [comment]
@tristan957 add http schema part in your proxy url.

**Comment by tristan957** [comment]
🤦 thanks @fannheyward. Thought it would be like VSCode's proxy settings. There I don't have the http://, but it still works.

**Comment by mnik01** [comment]
> Try `"https.rejectUnauthorized": false` with master branch.

In CocConfig file. `:CocConfig` to open it

**Comment by thisinnocence** [comment]
Use command `:CocConfig` to edit coc-settings.json, add
```json
{
    https.rejectUnauthorized": false,
    "http.proxyStrictSSL": false,
}
```
this works.

**Comment by lquinn2015** [comment]
I am having this issue still on release the above for me did not overcome the self-signed cert. I just don't know how to bypass this error

**Comment by eddyli1989** [comment]
> I am having this issue still on release the above for me did not overcome the self-signed cert. I just don't know how to bypass this error

set
 
```
export GIT_SSL_NO_VERIFY=true
yarn config set "strict-ssl" false -g   
```                                                                                                                                                                                         
in your .bashrc 

then use vimplug like this

`Plug 'weirongxu/coc-explorer', {'do': 'yarn install --frozen-lockfile'}`
