### ISSUE TITLE
Help with suggestions scrolling off screen

### ISSUE THREAD

**Issue by chinwobble** [neoclide/coc.nvim#1515]
## Result from CocInfo
```
vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:30:17)
node version: v10.17.0
coc.nvim version: 0.0.74-6700e7468d
term: xterm
platform: win32

```

## Describe the bug
Suggestions go off screen.
I would like to see the suggestions in a preview window so they use the full width of my screen 80 chars. (Suggestions start from the left).
I tried to read through all the coc configuration but couldn't find anything.
![image](https://user-images.githubusercontent.com/18226001/73600097-ed34d280-459f-11ea-9899-96666dc08f56.png)

## Reproduce the bug
1. Set the font size to large
2. Trigger auto-completion when the cursor and symbol is on the right of the file

**Comment by chemzqm** [comment]
It's not possible, the pum is created by vim and we can't change it's position.

**Comment by chinwobble** [comment]
Is it not possible to reposition the popup by using `popup_move()` ?

https://vimhelp.org/popup.txt.html#popup_move%28%29

**Comment by chemzqm** [comment]
You need understand pum and popup of vim first
