### ISSUE TITLE
zsh: abort (core dumped ) when editing the same file in 2 vim instance and pressing "q" to exit on the most recent one

### ISSUE THREAD

**Issue by Alkeryn** [neoclide/coc.nvim#1516]
this problem happens only when doing it with zsh, could not reproduce when launching vim from bash

step to reproduce :

in a zsh shell : vim aa
in another zsh shell : vim aa, then press "q"
what it looks like :
![image](https://user-images.githubusercontent.com/11599075/73601456-4aaa2e80-4562-11ea-9dac-b62cbb749c83.png)

**Comment by Alkeryn** [comment]
My guess would be that maybe some zsh env variable mess with vim or something, legit no idea
disabling coc seemed to fix the issue but well, i want to use coc lol

**Comment by oblitum** [comment]
I use zsh daily, no such issue. Please provide better report and fill issue template for reopening.

**Comment by Alkeryn** [comment]
Well i tried disabling all my plugin except coc and stil had the issue ^
i can share you my vimrc maybe ?
https://github.com/Alkeryn/dotfiles/blob/master/.config/nvim/init.vim
