### ISSUE TITLE
Use line number column instead of signcolumn

### ISSUE THREAD

**Issue by danjenson** [neoclide/coc.nvim#1519]
It looks like neovim now supports multipurpose number column: https://github.com/neovim/neovim/pull/9113. Is there anyway we can get coc to use the number instead of signcolumn for errors? I find that the extra gutter makes it impossible to put 2 80 char panes on my vim windows (it wraps at ~76 chars with the extra gutter on both panes).

**Comment by oblitum** [comment]
Kinda weird request to ask to put stuff where it should not be.

**Comment by oblitum** [comment]
And that feature seems solely about highlighting the line number at the line color, it seems it didn't add anything like you described?

**Comment by danjenson** [comment]
I'd prefer to highlight the line number with errors/warnings rather than add a gutter to every vim pane.

**Comment by oblitum** [comment]
k, that's interesting request, but that neovim feature that was added according to description is tied to a sign being placed. According to discussion there it's just to highlight the line number where a sign was placed.

**Comment by danjenson** [comment]
ok, I guess my question is then, how can we tie that into the coc signs? Looks like we can do `set signcolumn=no`, but then we need something like `numhl={some coc sign group}`

**Comment by oblitum** [comment]
You have to check whether that works first. At the moment none of us knows, so you could check that since you're interested.

**Comment by danjenson** [comment]
Ok, are coc errors a registered sign group? Where can I find information about coc sign definitions?

**Comment by oblitum** [comment]
I meant you should check whether the neovim feature works as you expect by placing it standalone, just using neovim and placing signs/highlights manually.

**Comment by danjenson** [comment]
Here is an example that works as expected:
```
:set nu
:set signcolumn=no
:hi coc_hi ctermfg=1 ctermbg=15
:sign define coc_err numhl=coc_hi
:sign place 1 line=2 name=coc_err
```
You can copy those into a nvim buffer and then run each. You should see line 2 with a highlighted number.

**Comment by oblitum** [comment]
OK. I'm not the author so I have no word further on the matter, I guess PR welcome.

**Comment by danjenson** [comment]
...who is the author? This seems pretty simple if you're familiar with the coc codebase. You're already placing signs, you would just need to make two highlight specs `:hi coc_err_hi ctermfg={x} ctermbg={y}` and `:hi coc_warn_hi ctermfg={x} ctermbg={y}` and the accompanying names `:sign define coc_err numhl=coc_err_hi` and `:sign define coc_warn numhl=coc_warn_hi`. Then when you place the signs, just append `name=coc_{err,warn}` depending on whether it's an error or warning.

**Comment by oblitum** [comment]
@chemzqm is the author. At the moment I just provide some assistance with handling issues. He is a _very_ busy person.

**Comment by danjenson** [comment]
K, PR submitted: https://github.com/neoclide/coc.nvim/pull/1520
