### ISSUE TITLE
PHP language server some completions aren't shown

### ISSUE THREAD

**Issue by Kazimazi** [neoclide/coc.nvim#152]
**To Reproduce**
1. open empty php file
2. start typing `<?php
arr`
you should get a whole bunch of LS completions like (array_push, array_chunk), what you actually get is just array snippet
3. continue typing `array_c` and correct completion list shows

**Comment by chemzqm** [comment]
It works as expected on my mac.
I think it's just because the language server is not ready.

**Comment by Kazimazi** [comment]
How do I make it ready? Waiting doesn't work.

**Comment by chemzqm** [comment]
It's using a cutom notification type to log the message, like:
```
[1  - 4:40:34 PM] Restored laravel/framework:5.7.13 from cache
[Trace - 4:40:34 PM] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "All 5280 PHP files parsed in 2 seconds. 416 MiB allocated."
}
```
but coc don't support it, yet.

**Comment by Kazimazi** [comment]
Wrong completion
![phpcomp1](https://user-images.githubusercontent.com/5616737/48187325-103fea80-e33b-11e8-9fe5-c88a955747b2.png)
Every other completion (or those that I could come up with)
![phpcomp2](https://user-images.githubusercontent.com/5616737/48187366-2fd71300-e33b-11e8-800f-36198630a13f.png)

**Comment by chemzqm** [comment]
It's because ultisnip source have higher priority and the result is limit to 50.
You can set `"coc.preferences.minTriggerInputLength": 2` to have better result on tirgger, and `"coc.source.ultisnips.enable": false,` to disable ultisnip source.

**Comment by chemzqm** [comment]
Or give ultisnip source lower priority by add `  "coc.source.ultisnips.priority": 9,` to your coc-settings.json

**Comment by chemzqm** [comment]
I've improved error message for complete, try build from source by `yarn install`, so you can get feedback when something wrong with complete source.

**Comment by Kazimazi** [comment]
It must be some kind of bug... None of the aboved mentioned options worked out for my case but Ive discovered a "fix". Starting the keyword with an 'a' doesnt give me completion but while it loads the source pressing coc#refresh() mapping domehow makes it work

**Comment by chemzqm** [comment]
Try increase the wait time between TextChangd and completion `"coc.preferences.triggerCompletionWait": 100,`

**Comment by Kazimazi** [comment]
Still no luck with it :(

**Comment by chemzqm** [comment]
I can have the completion items starts with arr by just type `ar`:
<img width="490" alt="screen shot 2018-11-09 at 9 45 28 am" src="https://user-images.githubusercontent.com/251450/48238027-5c0a9680-e404-11e8-8dc0-050b8d42bd62.png">

What exactly problem do you have?

**Comment by Kazimazi** [comment]
I made some testing tho... I get this kind of bad behavior WHEN I have a single php file. 
![php3](https://user-images.githubusercontent.com/5616737/48241559-c78a3f00-e3d7-11e8-8e99-eb0093d027d2.png), so no composer init and nor locally installed php language server (I have it intalled globally I felt that it's irrelevant information at first, it kinda is).

**Comment by Kazimazi** [comment]
I was about to write that if I have composer init-ed and required some packages like symfony/symfony I have correct completion without that coc#refresh() trick, which was the case for a short while. After jumping to another file it does not work anymore for whatever reason.

**Comment by Kazimazi** [comment]
I opened a synmofy project and randomly started writing `ar` somwhere deleting it and writing `ar` again, repeating it. at first I instantly got the full list of completion, for the forth and fifth time it required a few milliseconds for the correct completion to pop up and every completion required more and more time. For the 10th time I've got no LS completion.

**Comment by Kazimazi** [comment]
I don't want to draw conclusions I have no idea how these stuff work, but I hope I could supply you with sufficient information.

**Comment by Kazimazi** [comment]
Very weird I could not reproduce it in a laravel project.

**Comment by Kazimazi** [comment]
I cannot reproduce any of my issues anymore everything works now, don't really know why.

**Comment by chemzqm** [comment]
Could be something related to file events, something like the listener execeed maximium limit.
