### ISSUE TITLE
Language server doesn't start for *.gd files 

### ISSUE THREAD

**Issue by CyanBlob** [neoclide/coc.nvim#1521]
## versions

```
vim version: NVIM v0.4.3
node version: v10.15.2
coc.nvim version: 0.0.74-bc017b02e6
term: xterm-256color
platform: linux

## Messages
```

## Describe the bug

I have a WIP language server running for the Godot game engine. I've configured the language server like so:
```
  "languageserver": {
    "godot": {
      "host": "127.0.0.1",
      "filetypes": ["gd"],
      "port": 6008
    }
  }
```
When I open my .gd file, the coc client does not start. However, if I change the filetype and the allowed filetype in the languageserver config (to, say, .cpp) like so:
```
  "languageserver": {
    "godot": {
      "host": "127.0.0.1",
      "filetypes": ["cpp"],
      "port": 6008
    }
  }
```
and then open my file, renamed to *.cpp, coc connects to my language server.
Is there some kind of whitelist/blacklist that would prevent coc from attempting to connect for a .gd file?

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Configure language server
```
  "languageserver": {
    "godot": {
      "host": "127.0.0.1",
      "filetypes": ["gd", "cpp"],
      "port": 6008
    }
  }
```
- Create and open a file named test.gd
- See that nothing happens
- Create and open a file named test.cpp
- See that coc tries to connect to the language server

**Comment by oblitum** [comment]
Are you not confusing [neo]vim filetype with file extension? They're different concepts. coc.nvim uses the first.

**Comment by CyanBlob** [comment]
Ah, it sounds like I might be. Is there a way to configure a language server based on an extension, then? `set filetype?` in [neo]vim returns `filetype= `, so that might be a dead end for the time being (without manual work)

**Comment by oblitum** [comment]
Not that I know. The correct thing is that you should set the filetype for such extensions through vim settings.

**Comment by CyanBlob** [comment]
Alright, well thanks for the help! I'll go ahead and close this, but I may add an issue to support file extension matching instead of just filetype

**Comment by oblitum** [comment]
@CyanBlob I simply think it's not worth it. It's not expected.

**Comment by oblitum** [comment]
[Neo]Vim is handling this for you already, it's like duplicating work.
