### ISSUE TITLE
colorscheme command clears coc colors

### ISSUE THREAD

**Issue by ephemerr** [neoclide/coc.nvim#1523]
vim version: NVIM v0.4.3
node version: v8.10.0
coc.nvim version: 0.0.74-cd348f4905
term: xterm-256color
platform: linux

Tested with minimum config.
If I run :colorscheme with any scheme and then look at :hi all Coc colors are 'cleared'.

**Comment by ephemerr** [comment]
I think problem could be that I use portable precompiled coc

**Comment by chemzqm** [comment]
You have to redefined custom highlight after change colorsheme, it's expected.
