### ISSUE TITLE
Can't use space as leader after running `:CocList`

### ISSUE THREAD

**Issue by masaeedu** [neoclide/coc.nvim#1524]
**Is your feature request related to a problem? Please describe.**
Hello. I use `<Space>` as a leader in my Vim, and lots of my keybindings (including window navigation) rely on using it as such. When I focus `:CocList` and switch to normal mode, I can't switch back to the window containing the buffer I'm editing without closing the list, since `<Space>` is taken over for selecting items.

I tried disabling the mapping for `<Space>` in `coc-settings.json` using the following two approaches, but neither seemed to work:

```
  "list.normalMappings": {
    "<Space>": ""
  },
```

```
  "list.normalMappings": {
    "<Space>": null
  },
```

**Describe the solution you'd like**
A way to disable keymappings when `CocList` is active.

**Describe alternatives you've considered**
I can change my keybinding scheme so I no longer use `<Space>` as the leader (or at least not to move around between windows), but this is a bit of an adjustment.

**Comment by fannheyward** [comment]
Try this:

```
"list.normalMappings": {
    " ": "do:exit"
  },
```

When you're in normal mode, the first `<Space>` will exit the list window.

**Comment by masaeedu** [comment]
Hi @fannheyward. Thanks, but what I'm actually trying to accomplish is *not* exiting the list (so I can continue to refer to it while I fix errors).

**Comment by oblitum** [comment]
I don't get much what this issue is about... When the `:CocList` is open, aren't forced in a kind of insert mode for the list, so any normal mapping simply won't work, doesn't matter what leader you use?

I also space as leader, but I don't get the issue because when I hit open for `:CocList` I know I'll not move around or anything while it's still open.

**Comment by masaeedu** [comment]
@oblitum There's actually a way to get out of the insert mode and into normal mode. You can press `<C-o>` with the default keybindings to do this. If after this I do `<C-w>k`, I'll end up back in the buffer I'm editing without closing the diagnostic list. I just want to be able to use my normal keybindings to get back into the main buffer instead of `<C-w>k`.

**Comment by oblitum** [comment]
Ok, now I understand the case.

**Comment by chemzqm** [comment]
@masaeedu You have to use
```
  "list.normalMappings": {
    "<space>": "feedkeys:\\<space>",
  },
```
in your coc-settings.json
