### ISSUE TITLE
Setting up g:coc_config_home does nothing

### ISSUE THREAD

**Issue by chrisands** [neoclide/coc.nvim#1528]
## Result from CocInfo
│vim version: NVIM 
│node version: v13.7.0
│coc.nvim version: 0.0.74-27e1b79fa3
│term: iTerm.app
│platform: darwin

## Describe the bug

Setting up `g:coc_config_home` in `init.vim` should change where setting should be found, instead it creates `$HOME/.config/coc/` folder.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
set runtimepath=/path/to/coc.nvim

let g:coc_config_home = '$XDG_CONFIG_HOME/nvim/coc'
" also using /Users/*/Library/Preferences/nvim/coc doesn't help
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
`g:coc_config_home` is used for `coc-settings.json` lookup, has no effects on `$HOME/.config/coc/` for now.

**Comment by chrisands** [comment]
You don't mind if I implement it? Or I should use another global variable for coc folder like `g:coc_data_home`?

**Comment by fannheyward** [comment]
I'm working on this. Change `coc_config_home` directly will be breaking change.

**Comment by chrisands** [comment]
Ok, thank you for response

**Comment by chemzqm** [comment]
Use `g:coc_data_home` variable.
