### ISSUE TITLE
Ctrl-j/k in list buffer ends up triggering custom split navigation mappings

### ISSUE THREAD

**Issue by mechkb** [neoclide/coc.nvim#1531]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
node version: v12.14.1
coc.nvim version: 0.0.74-6700e7468d
term: dumb
platform: linux

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>

1 line less; before #1  4 seconds ago

1 line less; before #2  1 seconds ago
## Output channel: snippets
```

## Describe the bug

I use the following split navigation shortcut mappings in my vimrc (see `mini.vim` below). Now when I execute a command that produces a list buffer, say `:CocList extensions` a list buffer opens that can be navigated using `Ctrl-j` and `Ctrl-k`. In this list buffer if I keep repeatedly pressing `Ctrl-j`, then I end up on the top split as seen in the screenshot. That is, somehow, the split navigation mapping is triggered instead of the list navigation mapping. I've also tried adding this to my vimrc: `autocmd BufEnter,BufWinEnter list://* setlocal nonumber norelativenumber | mapc <buffer>` to make sure the split navigation mappings are disabled in the list buffer but that didn't work. 

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  nnoremap <C-h> <C-w>h
  nnoremap <C-j> <C-w>j
  nnoremap <C-k> <C-w>k
  nnoremap <C-l> <C-w>l
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/35608309/74093488-b7608400-4aa0-11ea-8325-a56ea6791601.png)

**Comment by chemzqm** [comment]
It's bug of vim and we can't see any way to fix since we can't receive your keystroke.
Try neovim or latest vim.
