### ISSUE TITLE
socketserver loading workspace failed

### ISSUE THREAD

**Issue by Peanuttown** [neoclide/coc.nvim#1535]
用socketserver连接gopls的时候:
 [coc.nvim] Error loading workspace folders (expected 1, got 0)
failed to load view for file:///home/tzz/project/tzzGoUtil: err: chdir /home/tzz/project/tzzGoUtil: no such file or directory: stderr:

CocConfig: "socketserver":{
                          "filetypes":["go"],
                          "host":"192.168.43.65",
                          "port":10000,
                          "rootPatterns": ["go.mod"]
                  }
executable的可以正常使用:
"golang": {
                          "command": "gopls",
                          "rootPatterns": ["go.mod"],
                          "filetypes": ["go"]
                 },

**Comment by fannheyward** [comment]
用 socket 模式的时候，需要在 vim 打开前启动 server。

**Comment by Peanuttown** [comment]
> 用 socket 模式的时候，需要在 vim 打开前启动 server。

是在打开vim前 已经启动好了的

**Comment by fannheyward** [comment]
刚测试了一下，我在一个 terminal 下 `gopls -port 10000` 启动 server，然后配置 coc-settings.json:

```
    "gopls": {
      "filetypes": ["go"],
      "host": "127.0.0.1",
      "port": 10000,
      "rootPatterns": ["go.mod", ".git/"]
    }
```

然后在另外一个 terminal 打开 vim，gopls 是可以正常工作的。

**Comment by Peanuttown** [comment]
@fannheyward 
在同一个机器上是没问题，我把language server启动在另一个机器上是不行的么

**Comment by fannheyward** [comment]
> err: chdir /home/tzz/project/tzzGoUtil: no such file or directory

我没有测试过另外一台机器，但是从报错信息来看，gopls 应该是不支持。

**Comment by chemzqm** [comment]
另一个机器它访问不到你本地文件，应该都不可以。
