### ISSUE TITLE
Colorize doHover action popup

### ISSUE THREAD

**Issue by npupko** [neoclide/coc.nvim#1539]
We have colorized output for the Flow types in the VSCode editor: 
![image](https://user-images.githubusercontent.com/5938539/74148284-2d3a2c00-4c16-11ea-950b-881a091439f6.png)

Could we make something similar when doing `doHover` instead of boring one-color ouptut here: 
![image](https://user-images.githubusercontent.com/5938539/74148327-4216bf80-4c16-11ea-9739-3935b1d9a6c4.png)

**Comment by oblitum** [comment]
Are you using Vim or NeoVim?

coc.nvim support colorscheme in floating windows, but only for NeoVim. Not sure it needs to be in Markdown though, but in Rust for example, there's no issue.

**Comment by oblitum** [comment]
Ah, it's highlighted in signatureHelp docs, I think doHover is just plain.

**Comment by npupko** [comment]
@oblitum I'm using Neovim. Yes, I have colored docs but for Flow it does not work

**Comment by npupko** [comment]
@oblitum I can figure out how can I configure the filetype of the popup

**Comment by chemzqm** [comment]
The filetype is detected from response, please checkout verbose output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
