### ISSUE TITLE
How to disable argument autofill?

### ISSUE THREAD

**Issue by tom-james-watson** [neoclide/coc.nvim#154]
Some completions automatically insert the method signature with placeholder variables, like this:

![screenshot 2018-11-08 at 16 39 15](https://user-images.githubusercontent.com/3852719/48209273-ffac6600-e374-11e8-89c0-6b11a4c9a99d.png)

I don't like this functionality and would like to turn it off. I can't see it mentioned in the docs anywhere and can't see any settings that look like they would disable it.

Is there a way to disable this?

Thanks!

**Comment by chemzqm** [comment]
It's placeholder of snippet, when you type any character the placeholder is removed.
You can disable snippet for function call of tsserver by:

```
  "typescript.suggest.completeFunctionCalls": false,
  "javascript.suggest.completeFunctionCalls": false,
```
Same as VSCode.

**Comment by tom-james-watson** [comment]
Thanks! FYI - I (and I presume lots of other vim users) have never used VSCode, so I don't think you should assume that users will know how things work just because it's like that in VSCode.

I think it would be really useful if all of the possible options were listed somewhere with explanations of what they mean.

**Comment by chemzqm** [comment]
It's documented https://github.com/neoclide/coc-tsserver#configuration-options

Have priview in `completeopt` you can have the desciption in preview window.
<img width="529" alt="screen shot 2018-11-09 at 7 45 33 pm" src="https://user-images.githubusercontent.com/251450/48260878-111a6e80-e458-11e8-8032-a73a3601dc48.png">
