### ISSUE TITLE
Manually select language server

### ISSUE THREAD

**Issue by Alkeryn** [neoclide/coc.nvim#1541]
Let's say i have 3 different language server for cpp
there is a default one which will always or almost always be triggered
but it would be nice to be able to do something like
:launchLangServ foo
and i't would use foo instead for that specific session.

An example where that would be useful is that for ex for windows dev i use clangd over ssh
https://github.com/Alkeryn/dotfiles/commit/38bd119b649343566ee7b55cc5256e0f3dc26461

**Comment by oblitum** [comment]
You can pretty sure configure this with `:CocRestart` and `coc#config`.
