### ISSUE TITLE
(diagnostics) Differentiate Style Errors from regular Errors

### ISSUE THREAD

**Issue by rebelot** [neoclide/coc.nvim#1543]
**Is your feature request related to a problem? Please describe.**
Catching serious errors may be difficult if one cannot distinguish at glance between style errors (e.g. line too long / blank line at end of file) from regular ones (e.g. undefined variable, etc.)

**Describe the solution you'd like**
I'm referring to one of ALE features here (https://github.com/dense-analysis/ale/issues/430). Where one can set different highlight groups / symbols for Style errors.

Thank you.

**Comment by fannheyward** [comment]
Diagnostic level is defined in [LSP](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#diagnostic), that only has `Error`, `Warning`, `Information` and `Hint`.  coc just display the diagnostics, and won't modify them.

What you need is to request language server to make style error as a warning or something else.
