### ISSUE TITLE
make client.vim's get_channel() public: coc#client#get_channel()

### ISSUE THREAD

**Issue by antoinemadec** [neoclide/coc.nvim#1544]
**Is your feature request related to a problem? Please describe.**
I am in buffer **B** and want to run ```CocAction()``` in buffer **A** using ```pynvim``` in a script.
I could use ```:buffer```, but it creates issues with floating windows as well as with user input.

**Describe the solution you'd like**
I would like to call CocAction from buffer **B**, like so:
```vim
call rpcrequest(channel_A, 'CocAction', 'getWorkspaceSymbols', query, bufnr_A)
```
To do so, I would need to retrieve ```channel_A``` which is a private function today.
If ```get_channel()``` was available to users, that would make it very simple for me.

**Describe alternatives you've considered**

- ```:buffer``` issues with floating windows and user input
- ```nvim_open_win()```: issues with user input (tried to block it unsuccessfully)

**Additional context**
I cannot use a vim function callback as FZF requires a shell command to act in an interactive way: https://github.com/junegunn/fzf.vim/issues/948#issuecomment-584438425
Thus ```pynvim```: https://github.com/antoinemadec/coc-fzf/commit/77193dee255a65d524bd2f00f12b8839bc9f8cbc#diff-b99507a35b27723b7f75389f38343247

**Comment by fannheyward** [comment]
Give it a try and feedbacks are welcome.

**Comment by antoinemadec** [comment]
@fannheyward thanks a lot, unfortunately I was not precise enough, could it be possible to also have:
```vim
function! coc#client#get_client(name)
  return get(s:clients, a:name, v:null)
endfunction
```
That will allow me to call:
```vim
let channel = coc#client#get_channel(coc#client#get_client('coc'))
```
I tested my plugin with this and it works like a charm, no more user input/buffer issues :smile: 

Thanks,
Antoine

**Comment by fannheyward** [comment]
Does `coc#client#create` work for you?
