### ISSUE TITLE
make CocAction 'getWorkspaceSymbols' kind the same as 'documentSymbols'

### ISSUE THREAD

**Issue by antoinemadec** [neoclide/coc.nvim#1546]
**Is your feature request related to a problem? Please describe.**
```CocAction('getWorkspaceSymbols', query)``` return a dictionary where ```kind``` value is a **number**, whereas ```CocAction('documentSymbols')``` returns a dictionary where ```kind``` is a **string** (Variable, Function etc).

**Describe the solution you'd like**
```getWorkspaceSymbols``` to return a dictionary where ```kind``` value is a **string** like ```documentSymbols```

**Comment by fannheyward** [comment]
`getWorkspaceSymbols` returns `SymbolInformation[]` that defined by LSP, https://github.com/microsoft/vscode-languageserver-node/blob/master/types/src/main.ts#L1938, which kind is number.

`documentSymbols` returns `SymbolInfo` https://github.com/neoclide/coc.nvim/blob/master/src/handler/index.ts#L35 , which kind is string.

I'll check whether we can change `SymbolInfo.kind` to number, whether any breaking change or not.

**Comment by antoinemadec** [comment]
@fannheyward got it, thanks! Otherwise, if there is a map number->string, I can use it too.
Cheers,
Antoine

**Comment by fannheyward** [comment]
Here it is: https://github.com/neoclide/coc.nvim/blob/master/src/util/convert.ts#L3 , and we will not change SymbolInfo.kind to avoid more change.
