### ISSUE TITLE
On Vim, coc.nvim tries to install vim-node-rpc through NPM

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#155]
**Describe the bug**

On first use in Vim, `coc.nvim` reports it needs `vim-node-rpc` and asks to install it, I opted "yes". I have Yarn in my machice, not NPM, but it tried to install through NPM and failed. I've then manually installed with `yarn global add vim-node-rpc` to fix the issue.

**Comment by chemzqm** [comment]
`npm` is used since it's bundled with node, which required to run vim-node-rpc, I could use a inputlist to improve that.

**Comment by oblitum** [comment]
Serious question: is it? To tell the truth I don't know, but at least on package managers they're independent.

**Comment by oblitum** [comment]
Reason why I moved to Yarn altogether.

**Comment by chemzqm** [comment]
Might because it's not added to your $PATH.

**Comment by oblitum** [comment]
Dunno. I had NPM before, I removed it explicitly with `pacman` but left node installed, node is in my PATH, as well as Yarn, which I also installed.
