### ISSUE TITLE
Disable completion at specific filetype

### ISSUE THREAD

**Issue by PetrusZ** [neoclide/coc.nvim#1550]
**Is your feature request related to a problem? Please describe.**
When I using vimwiki, type chinese, coc completion become really really slow and lag.

**Describe the solution you'd like**
Disable coc comletion at specific filetype

**Describe alternatives you've considered**
Disable coc comletion of chinese, or somehow make completion smooth at vimwiki.

Thanks.

**Comment by fannheyward** [comment]
Check `:h b:coc_suggest_disable`.
