### ISSUE TITLE
need to use coc#config send bool parameter to ccls

### ISSUE THREAD

**Issue by xayjin** [neoclide/coc.nvim#1551]
when i use coc#config to send "initializationOptions":{ "highlight": { "lsRanges" : true }} to ccls, vim tell me it can't learn the keyword true. if i change the keyword true to string "true" such as { "lsRanges" : "true" }, ccls would tell me it expect bool rather than string "true". 

since vim don't have boolean , string "true" be convert in the coc#rpc function before communicating ccls.

**Comment by oblitum** [comment]
Use `v:true`, check `:h v:true`.

**Comment by chemzqm** [comment]
There are `v:true` and `v:false`
