### ISSUE TITLE
diagnostic.enableHighlightLineNumber work without diagnostic.enableSign

### ISSUE THREAD

**Issue by alex-popov-tech** [neoclide/coc.nvim#1553]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/neoclide/coc.nvim/pull/1520 . As a user, I would expect that feature to be separated from column sign, since red line number can be self explanatory without something like `>>` pointing on it.

**Describe the solution you'd like**
I would like to do something like set `diagnostic.enableHighlightLineNumber` to true, set `diagnostic.enableSign` to false, and have only red line number on error.

**Additional context**
Screenshot

![Image+2020-02-15+at+00 03 49](https://user-images.githubusercontent.com/1269815/74576586-3e62a000-4f6a-11ea-8bdd-124eccdbf349.png)

**Comment by nomasprime** [comment]
Looks like this was closed  in a commit but still currently can't highlight line number without signs. Is that correct?
