### ISSUE TITLE
disable signcolumn only for hints

### ISSUE THREAD

**Issue by skylite21** [neoclide/coc.nvim#1554]
**Describe the solution you'd like**
maybe something like this in coc-settings.json:

```
"diagnostic.hintSignColumn": false
```
or
```
"diagnostic.enableHintSign": false
```
as this option currently only available for all kinds of signs with ` "diagnostic.enableSign": false` but maybe I'm missing something.

**Comment by fannheyward** [comment]
Check `diagnostic.level`.

**Comment by skylite21** [comment]
I don't want to disable hint entirely, I just want to disable it in the signcolumn.

**Comment by skylite21** [comment]
In case anyone cares, I found a workaround that works for me.

in init.vim:
```
" always show the signcolumn
autocmd BufRead,BufNewFile * setlocal signcolumn=yes
" remove the color from the signColumn
autocmd BufRead,BufNewFile * highlight clear SignColumn
```

And in coc-settings.json:
```
 "diagnostic.hintSign": ""
```
