### ISSUE TITLE
Integrate clangd with nix and direnv

### ISSUE THREAD

**Issue by LinArcX** [neoclide/coc.nvim#1555]
**Is your feature request related to a problem? Please describe.**
[I'm using clangd](https://github.com/neoclide/coc.nvim/wiki/Language-servers#ccobjective-c) as language server for my c/c++ projects. After integrating [nix](https://github.com/NixOS/nix)+[direnv](https://github.com/direnv/direnv) into my workflow, clangd can't recognize by nix([due to random path](https://nixos.org/nix/manual/#sec-profiles) of installed clangd on my machine) and i don't have LSP right not.

**Describe the solution you'd like**
I thought about changing coc-settings.json file to this:
```
"clangd": {
    "command": "$PATH_CLANGD",
    "args": ["--background-index"],
    "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"],
    "filetypes": ["c", "cpp", "objc", "objcpp"]
},
```
And define that env(PATH_CLANGD) like this in default.nix:
```
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "learning_cmake";
  src = ./.;

  buildInputs = [ cmake clang clang-analyzer ];

  shellHook = ''
    export CMAKE_C_COMPILER=${pkgs.clang}/bin/clang
    export CMAKE_CXX_COMPILER=${pkgs.clang}/bin/clang++
    export PATH_CLANGD=${pkgs.clang}/bin/clangd
  '';
}
```
actually in neovim i can print this env:
```
:!echo $PATH_CLANGD                                                                                                                                    
/nix/store/j7bvsk064lb4ac9sryp1s17i7g0kdb64-clang-wrapper-7.1.0/bin/clangd     
```
But seems that json file can't accept environment variables:

> [coc.nvim] Server clangd failed to start: Command "$PATH_CLANGD" of languageserver.clangd is not executable: Error: not found: $PATH_CLANGD 

**Describe alternatives you've considered**

**Additional context**
nix (Nix) 2.3.2

```
╰ nvim --version              
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.4.3/build/config -I/builddir/neovim-0.4.3/src -I/usr/include -I/builddir/neovim-0.4.3/build/src/nvim/auto -I/builddir/neovim-0.4.3/build/include
Compiled by void-buildslave@a-hel-fi

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by fannheyward** [comment]
Try to use `${PATH_CLANGD}` in command field, does this works?

**Comment by LinArcX** [comment]
@fannheyward You mean without double-quotes? no:

> [coc.nvim] Wrong configuration of LS "clangd", no command or module specified.

**Comment by fannheyward** [comment]
`"command": "${PATH_CLANGD}"`

**Comment by oblitum** [comment]
For more dynamic configuration I recommend you use `coc#config` instead of json file.

**Comment by fannheyward** [comment]
@LinArcX Try the latest master branch with `"command": "${PATH_CLANGD}"`.

**Comment by LinArcX** [comment]
@fannheyward Changing:
Plug 'neoclide/coc.nvim', {'branch': 'release'}
To:
Plug 'neoclide/coc.nvim', {'branch': 'master'}
and run: PlugUpdate.
But when i open files under nix control, i get:

> [coc.nvim] javascript file not found, please compile the code or use release branch.   

Also follow [this](https://github.com/neoclide/coc.nvim/issues/1043#issuecomment-552698752), but nothing changed.
Edit: i have yarn on my machine already installed.

**Comment by fannheyward** [comment]
`Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}` , this will build from source.

**Comment by fannheyward** [comment]
The release has updated, you can still use `Plug 'neoclide/coc.nvim', {'branch': 'release'}`.

**Comment by chemzqm** [comment]
Try upgrade on release branch.

**Comment by LinArcX** [comment]
After updating to latest changes, still get that error:

> [coc.nvim] Server clangd failed to start: Command "${PATH_CLANGD}" of languageserver.clangd is not executable: Error: not found: ${PATH_CLANGD}

**Comment by fannheyward** [comment]
1. Please make sure you have already upgrade coc.nvim to the latest release.
1. Does `PATH_CLANGD` in your env?  Check it by `env | grep PATH_CLANGD`
1. I didn't use clangd, but have tested with `gopls` with this and it works:

```
export GOPLS_BIN=$HOME/bin/gopls

"gopls": {
  "command": "${GOPLS_BIN}",
  "filetypes": ["go"],
  "rootPatterns": ["go.mod", ".git/"]
},
```

**Comment by LinArcX** [comment]
> For more dynamic configuration I recommend you use `coc#config` instead of json file.
How? i didn't find any sample.

@fannheyward Yes, i did all those things. the problem is that (i think) these particular **ENV**s are only accessible when you enter a specific directory. if you leave that directory, these **ENV**s will gone!(This is the nature of direnv actually.)
So when neovim first starts, it looks in `coc-settings.json` file and see an environment variable called:
`"command": "${PATH_CLANGD}"`
And it doesn't have any idea about it.(or how to set it maybe)
Although i can print this **ENV** inside vim:
```
:!echo ${PATH_CLANGD}                                                                                                                                  
/nix/store/j7bvsk064lb4ac9sryp1s17i7g0kdb64-clang-wrapper-7.1.0/bin/clangd    
```  
So i think what happen if i restart coc(maybe it recognize this env!), but nothing changed!
Also i think about putting coc-settings.json file in side my project(and remove it from neovim config directory). surprisingly i didn't see that error message, but when i want for example got to definition of functions, i get:
`[coc.nvim] Definition provider not found for current document  `

**Comment by oblitum** [comment]
duplicate of  #1493.

**Comment by LinArcX** [comment]
I realized that it won't work if i install clang internally via void package manager(instead of installing it via nix) and change coc-settings.json like this:
```
"clangd": {
            "command": "clangd",
            "args": ["--background-index"],
            "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"],
            "filetypes": ["c", "cpp", "objc", "objcpp"]
        },
```
Just for direnv+nix projects i have this issue happens. For normal project i have LSP that working nicely.

**Comment by LinArcX** [comment]
After a while.. finally i figured it out how to solve this issue.
1. Remove settings related to clangd language server from coc-settings.json file.
2. for a project you want to work with create .nvimrc file and past these lines into it:
```
call coc#config('languageserver', {
            \ 'clangd': {
            \   "command": "${CLANGD}",
            \   "args": ["--background-index"],
            \   "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"],
            \   "filetypes": ["c", "cpp", "objc", "objcpp"]
            \ }
            \})
```
