### ISSUE TITLE
Nested snippet expansion breaks initial snippet placeholder navigation

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#156]
**Is your feature request related to a problem? Please describe.**
I'm in general not liking the current implementations for function argument snippets that are being provided by several code completers because they're very limited. For example, for `int foo(int a, int b)`, if I accept the snippet for `foo` call with another snippet completion for a inner `foo` call as argument, this happens: `foo(foo(4, 2), <placeholder jumps of first snippet don't work anymore!>int b)`, which means, I'll have to edit and remove the remaining `int b` by hand, without snippet's jump and selection. That's very bad.

**Describe the solution you'd like**
I can't say whether there's a best solution but I'd like at least to disable these snippets for function arguments so that I can just stick to [echodoc.vim](https://github.com/Shougo/echodoc.vim) for example. LanguageClient-neovim provides `g:LanguageClient_hasSnippetSupport = 0` to help on that, for example.

**Describe alternatives you've considered**
Alternative means of dealing with arguments are described here:

- https://reviews.llvm.org/D38048#889568
- https://github.com/hukeyue/vim-clangd/issues/13
- https://github.com/MaskRay/ccls/issues/110#issuecomment-437559882
- http://nosubstance.me/articles/2015-01-29-better-completion-for-cpp/

**Comment by chemzqm** [comment]
The language server could provide an option to disable snippet feature, but I don't if there's such option for clangd.

There is signature help support with coc, you can use something like:
```
autocmd CursorHoldI,CursorMovedI * silent! call CocActionAsync('showSignatureHelp')
```

**Comment by oblitum** [comment]
> The language server could provide an option to disable snippet feature, but I don't know if there's such option for clangd.

The issue is not the server providing the parameter information but how the client is doing it. The problem I've mentioned is solely related to client implementation, which in this case is coc.

**Comment by oblitum** [comment]
> There is signature help support with coc, you can use something like:
> 
> ```
> autocmd CursorHoldI,CursorMovedI * silent! call CocActionAsync('showSignatureHelp')
> ```

Thanks for this info.

**Comment by chemzqm** [comment]
It's not additionalTextEdit actually, it's snippet returned from language server, coc just expand the snippet on completion confirm.
I think that clangd should not return label with function parameters so that user could just insert function name by use `<C-n>`, and it should return one item for function overloads, it's not possible for neovim/vim to resolve different complete item with same label as expected for now.  And that's how tsserver works like.

**Comment by oblitum** [comment]
> It's not additionalTextEdit actually, it's snippet returned from language server, coc just expand the snippet on completion confirm.

Changed title, I may have used the wrong term.

> I think that clangd should not return label with function parameters so that user could just insert function name by use `<C-n>`, and it should return one item for function overloads, it's not possible for neovim/vim to resolve different complete item with same label as expected for now. And that's how tsserver works like.

In the list of links I've provided at the issue, some of them do that. Clang provides per parameter info and prototypes after `(` and `,`, this is implemented in their `signatureHelp` support. It's an option of the client to insert the whole function prototype with argument placeholders or just the function name and provide the compatible overloads while the user inserts them.

> You can't disable snippet feature of coc, language server like coc-json requires snippet to work.

That's sad, I can use LanguageClient-neovim and vim-lsp fine because I'm not obligated to use snippets. As I proved at my example, they're very limited since the work just for the first expansion, after that they get broken and I have to edit function calls removing the snippet text arguments that come with it.

**Comment by oblitum** [comment]
I've reworded the main issue text a little bit to try be more precise in my example.

**Comment by chemzqm** [comment]
> That's sad, I can use LanguageClient-neovim (g:LanguageClient_hasSnippetSupport = 0)

As I've said, that would break other language server from working, clangd should provide the option to disable snippet or not provide params in label of complete items, they should be exists in `detail` field of completion item.

The signatureHelp could be improved, trigger character is not respected for now, it's a bug.

Another solution is create a coc extension with completion middlewire to fix this issue with clangd, the hack of get function name from label would possibly break other language server used by coc.

**Comment by oblitum** [comment]
> As I've said, that would break other language server from working, clangd should provide the option to disable snippet or not provide params in label of complete items, they should be exists in detail field of completion item.

OK, I didn't verify the source code and implementation of clangd yet to see whether it's providing full prototype where should just be the function name. It's weird though because other LSP completers are working fine at providing just a function name for the insertion text. I've tried with ncm2 both vim-lsp and LanguageClient-neovim, using `clangd` and `ccls`, which is another server. Currently I'm not even using clangd, I'm using `ccls`, but the problem with coc still remains.

**Comment by chemzqm** [comment]
They just spilt the label to get the part of function name, coc not doing that since coc does completion resolve on select change of completion item and it requires the word of vim completion item to be unique (until vim could emit selected complete item on completion item change).

**Comment by oblitum** [comment]
I've changed the title to point to the actual issue. If it can be fixed while still having snippets, then OK.

**Comment by oblitum** [comment]
I'm a long time YouCompleteMe user but I'm looking for options now, hence I'm trying these several new ones, but I'm doing my tests just with a minimal setup just to give the completion plugins a try. That's the reason I've picked just one language for now, c++, and I'm trying with both clangd and ccls.

I've hit this issue with them and I'm assuming you're right about it involving server implementation, so I'm expecting that for other languages I won't experience the same issue of the title?

**Comment by chemzqm** [comment]
You may or may not, there's no guarantee.

Different language server could have different problems when working with vim, and that's why coc support extensions which could use middleware to fix those problems.

**Comment by oblitum** [comment]
Oh well, OK... I suspect I'll hit this for all languages and few will have servers where I can disable this, and it's a bad route in any way  because I would then need to do it (configuration) server per server.

**Comment by chemzqm** [comment]
You don't need to disable snippet as long as the function params not exists in label, which should be in detail field as tsserver.

Or wait for vim/neovim support emit selected completion item, then we can do split for function name.

**Comment by oblitum** [comment]
> They just spilt the label to get the part of function name, coc not doing that since coc does completion resolve on select change of completion item and it requires the word of vim completion item to be unique (until vim could emit selected complete item on completion item change).

> If I do the split, `dup` should be true for vim completion item and it's possible of wrong resolved complete item.

OK. So I'm understanding that it's also a problem due to how coc have its _completion resolve_ dependent upon the (neo)vim limitations on item selection. Due to how (neo)vim is contrived on information on "item emit", I'd rely the design and uniqueness of items on another data and event rather than selection and completion-item `word`. This constrains the core of the completion engine based on a detail of the editor, if I'm understanding it right.

But, anyway, that just an opinion.

**Comment by chemzqm** [comment]
There's no event for completion item select in vim/neovim, so coc have to rely on unique word of complete item for correct completion resolve on select change.

I've just added the option `coc.preferences.splitLabelForWord` which make coc split label to get function name, just like other vim's language client, which also disable completion resolve on completion item change for that source.

**Comment by oblitum** [comment]
OK, thanks. Sadly, has you said, there's an issue when that's `true` now, not all overloads are shown and `signatureHelp` on the command line will just show the prototype for the single overloaded that is shown on menu. I don't have the same problem with echodoc and ncm2, the popup menu show all prototypes and echodoc helps with permanently displaying the signature for the item that was selected (works when nested too), even though the `word` for the overloads being duplicated.

**Comment by chemzqm** [comment]
Just fixed that, forget to add `dup` property.

**Comment by oblitum** [comment]
@chemzqm great! that's almost near echodoc, but still echodoc is doing better because it's showing the correct selected overload, `CocActionAsync('showSignatureHelp')` solution just show the first, not one different I select from the menu when there are multiple overloads for a function.

**Comment by oblitum** [comment]
And another thing is that for C++ what's shown in the command line is a bit strange than echodoc, I get `foo(int x, int y) -> int(int x, int y)` there, where I'd expect just `foo(int x, int y) -> int` or `foo(int x, int y)`.

**Comment by chemzqm** [comment]
echodoc using abbr field of vim's completion item on complete done, but coc using the result from language server, the server should return all overload signatures and coc could show them all.

**Comment by oblitum** [comment]
Could coc remember and associate which overload is the one I've selected in the menu and use that information to just show in the command line the one related with my selection?

**Comment by chemzqm** [comment]
>  I get foo(int x, int y) -> int(int x, int y) there, where I'd expect just foo(int x, int y) -> int or foo(int x, int y).

It should be just the result from language server, checkout the output channel: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by oblitum** [comment]
> It should be just the result from language server, checkout the output channel: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

OK.

**Comment by chemzqm** [comment]
> Could coc remember and associate which overload is the one I've selected in the menu and use that information to just show in the command line the one related with my selection?

I think the answer is no for now, since it's not standard to include function signature in complete item.

**Comment by chemzqm** [comment]
You can ask echodoc to make use fo virtual text feature of neovim, so you can have better experience with it.

**Comment by oblitum** [comment]
> I think the answer is no for now, since it's not standard to include function signature in complete item.

OK. IMO it could be put in the new `user_data` field, maybe.

**Comment by chemzqm** [comment]
It's not related to the fiedl of vim's complete item, it's just not included in specification of LSP: https://microsoft.github.io/language-server-protocol/specification

**Comment by oblitum** [comment]
OK, it was just a confusion, I thought you meant that because Vim's data structure is also called `complete_item`.

**Comment by oblitum** [comment]
> You can ask echodoc to make use fo virtual text feature of neovim, so you can have better experience with it.

Cool, I didn't know [this feature](https://github.com/neovim/neovim/pull/8180) existed. But I think @Shougo should probably be aware of it already. The one related that I'm following but seems to never land is [the one on floating windows](https://github.com/neovim/neovim/pull/6619).

**Comment by oblitum** [comment]
But from the last message on the issue tracker it seems it's almost there :)

**Comment by oblitum** [comment]
> > Could coc remember and associate which overload is the one I've selected in the menu and use that information to just show in the command line the one related with my selection?
> 
> I think the answer is no for now, since it's not standard to include function signature in complete item.

Just to avoid confusion on that, I just noticed that the prototypes I was seeing the command line were coming after trigger character for signatureHelp, the command line is showing signatureHelp (not for chosen item in menu, but ok) that you have just committed and I didn't know it was already available. I thought I was still seeing a result from `autocmd CursorMovedI * silent! call CocActionAsync('showSignatureHelp')`.

**Comment by oblitum** [comment]
Just for anyone interested reading this, to overcome the issues with wrong prototype (meaning non selected and/or exquisite declaration) on the command line, echodoc still works as expected with coc, one just needs now to avoid signatureHelp triggers using `"coc.preferences.triggerSignatureHelp":false`.

**Comment by oblitum** [comment]
I just realized an awesome thing, even with `"coc.preferences.splitLabelForWord": true`, I can still expand the snippet if I want to, with `<c-y>`. I'm trying this with echodoc, it's nice.

**Comment by chemzqm** [comment]
I've removed `coc.preferences.splitLabelForWord`, it's not needed any more, coc could fix insert text after select change.

**Comment by oblitum** [comment]
@chemzqm the current behavior now is that I'm getting a bunch of whitespace inserted when I browse the menu items:

![14 21 25_12-11-18](https://user-images.githubusercontent.com/1269815/48360385-45737200-e686-11e8-90d4-52c425349853.png)

**Comment by oblitum** [comment]
@chemzqm Besides that, I was really like having this behavior for coding:

![session-1](https://user-images.githubusercontent.com/1269815/48361536-dea38800-e688-11e8-8c8a-a0817b9eb88c.gif)
I could expand snippet or not at my option, having it input just the function name was also nice because after inserting parentheses the arguments _for the selected prototype_ would still show up in echodoc (it also shows when using the snippet with `<c-y>`).

I hope the new planned behavior (it's not working for me yet because of whitespace) will not remove that workflow.

**Comment by oblitum** [comment]
In the gif above, I was getting "match 1 of 2", etc, where now I'm just getting `S` (plus no more echodoc).

**Comment by chemzqm** [comment]
>  I don't have whitespaces anymore but now echodoc stopped working

echodoc assumes that function name should be word of complete item, you should disable this line https://github.com/Shougo/echodoc.vim/blob/master/autoload/echodoc/util.vim#L291

**Comment by chemzqm** [comment]
> In the gif above, I was getting "match 1 of 2", etc, where now I'm just getting S

It's expected, `S` is from detail of resolved complete item that echoed by coc.nvim, it should be in preview window when possible.

**Comment by oblitum** [comment]
hmm, ok. Well you may be building future ground, but for now it simply got way more confuse than it was. Doesn't make much sense to have that type there.

**Comment by oblitum** [comment]
I mean, why the type of `s`, the variable being accessed, is useful as detail, dunno. I know it may just be the data that the server sends. If it were at least the type result of the function or member, OK, but the type of the variable being accessed, not useful, there's a specific use for that in hover feature.

**Comment by chemzqm** [comment]
> I mean, why the type of s, the variable being accessed, is useful as detail, dunno. 

Clangd use returns type of function as detail for function complete item, but tsserver would have function signature in detail, which is more useful.

**Comment by chemzqm** [comment]
I think the reason is when using clangd in VSCode, it always expand function as snippet, so they don't think it's necessary to add function nsignature in detail.

**Comment by oblitum** [comment]
Problem is that I'm not getting signature of the function nor the type of its result. I'm getting something that's not useful, they type of the variable for which I'm access their members. Such information is useful generally in "get type" and mouse hover features, when one wants to know the type of `s`, it's not needed when it's being accessed.

**Comment by chemzqm** [comment]
It could be improved by using middleware when there is coc-clangd extension.
You can fix the echodoc and use echodoc to give signature after complete done for now.

**Comment by oblitum** [comment]
cc @MaskRay, Hi!, do you think that^^^ is an issue? It's operating differently than clang at detail data, dunno why I'm seeing the type of the variable being accessed as detail instead of data of the actual members.

**Comment by MaskRay** [comment]
LanguageClient-neovim doesn't really support LSP style snippets. `g:LanguageClient_hasSnippetSupport` should just default to 0.

In [ccls](https://github.com/MaskRay/ccls), there is an initialization option [client.snippetSupport](https://github.com/MaskRay/ccls/wiki/Initialization-options#clientsnippetsupport) designed for such clients: if you set it to false, the server will not enable snippets even if the client announces that it supports it.

**Comment by oblitum** [comment]
hi @MaskRay. The problem here is not LanguageClient, I was referring to the message and discussion just above, not the start of the issue, it's change on Coc here to output the detail data at the command line. For clangd it's displaying the member function return, but for ccls it displays the type of the variable being accessed, which is weird or not useful information in this situation.

**Comment by MaskRay** [comment]
@oblitum Can you upload a screencast?

**Comment by oblitum** [comment]
In case the discussion is too confuse I'll produce a testcase later. To sum it up, Coc is getting LSP detail info from server and showing it. For clangd it shows one thing, for ccls it shows another. For example, for:

```cpp
struct S {
    int foo(int a);
    int foo(int x, int y);
};

int main() {
    S s;
    s.<browse the menu here>
}
```

When browsing the popup their, Coc shows detail data, there are two functions, both return `int`, for clangd, that's what is shown, but for ccls the type `S` is shown for all members.

**Comment by oblitum** [comment]
Relevant previous messages:

- https://github.com/neoclide/coc.nvim/issues/156#issuecomment-438129473
- https://github.com/neoclide/coc.nvim/issues/156#issuecomment-438140621
- https://github.com/neoclide/coc.nvim/issues/156#issuecomment-437949699

**Comment by MaskRay** [comment]
@oblitum I have mentioned in my previous comments: it is irony-mode style completion and I find it useful.

You can set `completion.detailedLabel` to false to disable the behavior.

**Comment by oblitum** [comment]
@MaskRay ah, ok then, I didn't get it. Thanks for the info.

**Comment by oblitum** [comment]
@MaskRay I've made `completion.detailedLabel=false` and I'm now getting full prototype as detail (unsure whether that's OK since the popup already shows it), but now strangely enough that also makes the popup show just one overload of the two in the example code I've given previously.

**Comment by oblitum** [comment]
@MaskRay ok, I just thought the same, that it was client decision... Anyway, that's it. At least you captured what's the situation.

**Comment by oblitum** [comment]
@MaskRay regarding usability, I dunno what's more useful as detail, I think return value is better than the type of the variable I'm accessing, because it's the same detail for all members. I just don't have a formed opinion on what to make out of detail. Just `S` for everything looked weird, for me at least.

**Comment by MaskRay** [comment]
Parent context in `detail`. It is an issue @Sarcasm is also aware of. I hope he can also give some insights here.

**Comment by chemzqm** [comment]
> but now strangely enough that also makes the popup show just one overload of the two in the example code I've given previously.

I've improved coc to extra word for snippet body of snippet complete item at 388294ae9a67cd1da4eb2234af3253543bfada48, so this may not happen any more.

**Comment by oblitum** [comment]
@chemzqm yeah, it shows the two prototypes at the popup now, but the detail for both is the same prototype, if I try snippet expand for both, I just get the same one expanded. So I prefer it with `"detailedLabel": true`.

**Comment by chemzqm** [comment]
The resolve on completion done using abbr, so I think I should add uuid to complete item to avoid this issue.

**Comment by Sarcasm** [comment]
Indeed, the parent information starts to get useful on non-toy examples.
Also, I think I decided to display this information because that's what I saw for some VS Code client for other language AND/OR because this once the detailLabel was enabled, this was the only extra information I could see to be available.

FYI, in my mind, the ideal completion for C++ would look like this:

![ideal_cpp_completion](https://user-images.githubusercontent.com/424046/48472031-9655a880-e7f5-11e8-89b9-cd01d9772df2.png)

With `<f>` being a nicer `Method` icon, instead of displaying the string `Method`.

For this to work, I need the `CompletionItem` fields (https://microsoft.github.io/language-server-protocol/specification#textDocument_completion) to be as follow:

- `label` is detailed `overloaded(int x) -> void`
- `detail` is parent
- `filterText` is `overloaded`
- `insertText` is a snippet, something like `overloaded($1)$0`

There is something special with the Emacs completion backend, which I tried to work around by making the `filterText` be a prefix of `label`.

Not sure if this is of any help.


Another thing, regarding the snippet issue.
I'm not sure I understood all the issue, so sorry if I'm saying gibberish.
Isn't the original issue that the snippet tool you use is not recursive?

With Emacs' yasnippet, it's possible to enter snippet edits recursively.

So you, with current active can do:

```
foo(${1:int a}, ${2:int b})$0
    ~~~~~~~~~~              # initial snippet with expansion 1/2
foo(bar(${1:int x}), ${2:int b})$0
        ~~~~~~~~~~          # recursive snippet expansion 1/1
foo(bar(42), ${2:int b})$0
             ~~~~~~~~~~     # initial snippet with expansion 2/2
foo(bar(42, 42))$0
                ~           # final position of initial snippet
```

**Comment by oblitum** [comment]
@Sarcasm thanks for your input. Yes that's the main theme of this issue, reason why it's still open.

**Comment by oblitum** [comment]
@Sarcasm the issue with snippets for me, even if they were working in nested form, is that they would still break/miss the placeholders if I decide to go about formatting the function call prior to inputting arguments, like displacing args over multiple lines. 99% of implementations of snippets I know of in Vim at least will make the placeholders vanish and the snippet turned into plain text you have to manually patch. I had one very old implementation of snippets once whose placeholders were based on textual marks around formal parameters, the marks were concealed (Vim conceal feature) but used to define placeholder's highlighting. With this I could have Snippets that didn't simply vanish if I pressed <kbd>enter</kbd> or simply jumped placeholders too much hitting end-of-snippet. The drawback is that such markers were actual text that could be left in source or interfere with diagnostics.

![](http://i.imgur.com/mxsq9Yy.gif)

Out of that experience I started to be inclined to like more param hints than snippets because I'd free to edit as I wished.

![](https://s3.amazonaws.com/f.cl.ly/items/1e2F0A123h331c1G0L0R/SadBart.gif)

With Coc at least I'm having the snippets at my confirmation, and I get per param info expanding them or not.

**Comment by oblitum** [comment]
> The drawback is that such markers were actual text that could be left in source or interfere with diagnostics.

I think if I'd implement that today I would use special whitespace chars as delimiters, plus obligatory highlighting: fewer chance of producing any effect to compilation, and still having the placeholders highlighted/present in case they're forgot in source.

**Comment by oblitum** [comment]
> The resolve on completion done using abbr, so I think I should add uuid to complete item to avoid this issue.

Just tested b5827b3, working fine. Only thing is that "[LS]" is glued to the item's text, so it also goes to echodoc.

**Comment by chemzqm** [comment]
echodoc is triky at extracting signature, it may provide hooks so you can fix the wrong signature.

**Comment by oblitum** [comment]
Agreed.

**Comment by oblitum** [comment]
Thanks.

**Comment by oblitum** [comment]
> Just for anyone interested reading this, to overcome the issues with wrong prototype (meaning non selected and/or exquisite declaration) on the command line, echodoc still works as expected with coc, one just needs now to avoid signatureHelp triggers using `"coc.preferences.triggerSignatureHelp":false`.

At tip (I'm on b4a2bb6 currently), this isn't necessary anymore. Even with `"coc.preferences.triggerSignatureHelp":true` all seem to be working fine, I can still chose to expand snippet or not at my option with `<c-y>` and echodoc signature is always correct regardless of this option.
