### ISSUE TITLE
Display diagnostics by each buffer(file), not for all buffer files

### ISSUE THREAD

**Issue by SoPudge** [neoclide/coc.nvim#1560]
**Is your feature request related to a problem? Please describe.**
- When open different files in buffers, the diagnostics list shows all error for all opened files, may be only show current errors in current file better.

- 不同的文件仅显示当前的语法检查信息，会不会比较好些？目前是打开多个文件，共享一个diagnostics窗口，所有的语法检查都显示在这里自行进行筛选。
或者有没有可以配置的地方？

<img width="778" alt="Snipaste_2020-02-17_19-52-56" src="https://user-images.githubusercontent.com/20067852/74651786-9a723200-51bf-11ea-8521-93b885ada429.png">

**Describe the solution you'd like**
- 

**Describe alternatives you've considered**
- 

**Additional context**
-

**Comment by fannheyward** [comment]
Hello,

1. diagnostics list 设计就是展示当前 workspace 所有错误/警告信息
1. 没有这样的配置项
1. 你可以输入文件名来做过滤

个人觉得展示所有文件更好，不然你只能切换到对应文件才能看到是否有 error/warning，容易遗漏。

**Comment by chemzqm** [comment]
查看当前窗口的 locationlist，默认是启用的。
