### ISSUE TITLE
Error: cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by adiatma** [neoclide/coc.nvim#1561]
## Describe the bug

Hi

After install `coc.nvim` with plug manager  https://github.com/junegunn/vim-plug and i found errors while enter `insert` mode on vim, capture error like this `Error detected while processing function <lambda>16[1]`.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `.vimrc` with：

```vim
syntax on

set relativenumber

call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

```

## Screenshots (optional)

<img width="1440" alt="Screen Shot 2020-02-18 at 13 59 01" src="https://user-images.githubusercontent.com/45222198/74711964-ca6d1400-5257-11ea-8b83-ccfc6f432cb5.png">

## Environments

- Darwin 18.7.0 (MacOS: Mojave: 10.14.6)
- iTerm2
- tmux

**Comment by fannheyward** [comment]
Can't reproduce, needs more info. Post `:CocInfo` and `:CocOpenLog` please.

**Comment by adiatma** [comment]
Hi, @fannheyward thanks for your feedback, i just update my issues with my `CocInfo` screenshoot.

Thanks.

**Comment by dzzxjl** [comment]
i meet the same problem. @fannheyward

**Comment by dzzxjl** [comment]
## versions
    1
    2 vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 17 2018 17:24:51)
    3 node version: v12.16.0
    4 coc.nvim version: 0.0.74-bc017b02e6
    5 term: iTerm.app
    6 platform: darwin
    7
    8 ## Messages
    9 Messages maintainer: Bram Moolenaar <Bram@vim.org>
   10 Error detected while processing function <lambda>3[1]..<SNR>67_execute:
   11 line    2:
   12 Complete around error: Cannot read property 'toLowerCase' of null
