### ISSUE TITLE
Regression: nested snippet expansion breaks initial snippet placeholder navigation

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#1562]
## versions

vim version: NVIM v0.4.3
node version: v13.8.0
coc.nvim version: 0.0.74-d57f450e8d
term: tmux-256color
platform: linux

## Output channel: clangd trace

I[00:43:49.836] clangd version 9.0.1
I[00:43:49.836] Working directory: /home/francisco/Projects/samples/c++
I[00:43:49.836] argv[0]: /usr/bin/clangd
I[00:43:49.836] Starting LSP over stdin/stdout
I[00:43:49.837] <-- initialize(0)
I[00:43:49.837] --> reply:initialize(0) 0 ms
I[00:43:49.840] <-- initialized
I[00:43:49.840] unhandled notification initialized
I[00:43:49.841] <-- textDocument/didOpen
I[00:43:49.841] Enqueueing 0 commands for indexing
I[00:43:49.841] --> textDocument/clangd.fileStatus
I[00:43:49.841] Updating file /home/francisco/Projects/samples/c++/sample.cpp with command
[/home/francisco/Projects/samples/c++]
/usr/bin/clang-tool -Wall -Wextra -pedantic -std=c++17 -stdlib=libc++ -I/opt/src/GSL/include -I/opt/src/range-v3/include /home/francisco/Projects/samples/c++/sample.cpp -fsyntax-only -resource-dir=/usr/lib/clang/9.0.1
I[00:43:49.853] --> textDocument/publishDiagnostics
I[00:43:49.853] --> textDocument/clangd.fileStatus

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/francisco
> git ls-files -- Projects/samples/c++/sample.cpp
resolved root: /home/francisco
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Describe the bug

This was implemented on #156, but have stopped working lately, it's not possible to jump placeholder when there's nested snippet expansion involved. This provides a bad experience as the user is forced to patch snippet code and remove placeholders manually.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  let g:coc_global_extensions = ['coc-clangd']
  set runtimepath^=~/.vim/plugged/coc.nvim
  ```
- `touch compile_flags.txt`

- Start (neo)vim with command: `nvim -u mini.vim sample.cpp`

- Set content according to gif.

- Try to switch to next placeholder of outer snippet after finishing filling inner snippet.

## Screenshots (optional)

![screencast](https://user-images.githubusercontent.com/1269815/74801635-0df66b00-52b6-11ea-84fa-ec905edced21.gif)

**Comment by oblitum** [comment]
Former commit fix was /b1ad247b0a9a9a24a552dd4199505cb03bf6cc28.

**Comment by jackielii** [comment]
reproduced the issue with docker. Dockerfile source at: https://github.com/jackielii/coc-debug-docker

![coc-snippet-error-docker-min](https://user-images.githubusercontent.com/360983/75828217-419bbf80-5da3-11ea-8d59-70b2246b37b0.gif)

steps: 
1. `docker run --rm -it tespkg/coc-debug-go bash`
2. `nvim -u /minimal-coc.nvim main.go`
3. `:CocInstall coc-snippets`
4. `:CocCommand snippets.editSnippets`
5. add snippets:
```
snippet fori "for 0..N-1 { ... }"
for ${1:i} := 0; $1 < ${2:N}; $1++ {
	${0:${VISUAL}}
}
endsnippet
```
6. resume edit main.go with source:
```
package main

func main(){
    fori<C-y>
}
```
7. `<C-j>` to jump to 2nd placeholder then type `flag.NArg<C-y>` then `<C-j>` to jump to next placeholder, here inserted line break instead

**Comment by jackielii** [comment]
@oblitum can you try pr #1620 I suspect it'll fix this problem as well

**Comment by oblitum** [comment]
@jackielii I tried. It does not fix this. Also, it causes more issues, it doesn't jump correctly after the second snippet is expanded.

**Comment by chemzqm** [comment]
Hm, it doesn't work sometimes.
