### ISSUE TITLE
isHover documentation hides the diagnostic float

### ISSUE THREAD

**Issue by ungrim97** [neoclide/coc.nvim#1563]
## versions

vim version: NVIM v0.4.3
node version: v12.2.0
coc.nvim version: 0.0.74-d57f450e8d
term: iTerm.app
platform: darwin

## Output channel: tsserver

[Info  - 12:14:41] Forking TSServer
PATH: /Users/mikeeve/.anyenv/envs/nodenv/versions/12.2.0/bin:/Users/mikeeve/.anyenv/envs/nodenv/libexec:/Users/mikeeve/.anyenv/envs/nodenv/plugins/nodenv-vars/bin:/Users/mikeeve/.anyenv/envs/nodenv/plugins/nodenv-default-packages/bin:/Users/mikeeve/.anyenv/envs/nodenv/plugins/node-build/bin:/Users/mikeeve/.anyenv/envs/rbenv/shims:/Users/mikeeve/.anyenv/envs/plenv/shims:/Users/mikeeve/.anyenv/envs/rbenv/bin:/Users/mikeeve/.anyenv/envs/pyenv/shims:/Users/mikeeve/.anyenv/envs/pyenv/bin:/Users/mikeeve/.anyenv/envs/plenv/bin:/Users/mikeeve/.anyenv/envs/nodenv/shims:/Users/mikeeve/.anyenv/envs/nodenv/bin:/Users/mikeeve/.anyenv/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mikeeve/.antigen/bundles/Tarrasch/zsh-colors:/Users/mikeeve/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/mikeeve/.antigen/bundles/zsh-users/zsh-history-substring-search:/Users/mikeeve/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/mikeeve/bin/slack-theme 
[Info  - 12:14:41] Started TSServer
{
  "path": "/Users/mikeeve/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.7.3",
    "version": "3.7.3"
  }
}

## Output channel: highlight

[Info  - 12:14:41] Highlight server running in node v12.2.0

## Output channel: eslint

[Info  - 12:14:41] ESLint server running in node v12.2.0
[Info  - 12:14:42] ESLint library loaded from: /Users/mikeeve/.anyenv/envs/nodenv/versions/12.2.0/lib/node_modules/eslint/lib/api.js

## Describe the bug

I use "autocmd CursorHold * silent :call CocActionAsync('doHover')" do show doc/signature info in a float for the symbol under the cursor.

However if there is also a Diagnostic message (from eslint etc) which also display as a float then the documenation float hides the Diagnostic float rather than showing both. I would expect the diagnostic message to show at the top of the float and then the documentation information after.

## Reproduce the bug

# mini.vim
```
  set nocompatible
  set runtimepath^=~/.config/nvim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden

  " Show docs for symbol under cursor on CursorHold
  autocmd CursorHold * silent :call CocActionAsync('doHover')
  set updatetime=300
```

# Test.js
```
  'use strict'
  function foo() {
     // Unused var
     const var = 'a';
  }

  // Blatent syntax error
  d foo();
```
# Config
{
  "coc.preferences.jumpCommand": "tab drop",
  "diagnostic.checkCurrentLine": true,
  "diagnostic.virtualText": true,
  "diagnostic.virtualTextLines": 1,
  "typescript.suggestionActions.enabled": false,
  "javascript.suggestionActions.enabled": false
}
~

## Screenshots (optional)

<img width="520" alt="image" src="https://user-images.githubusercontent.com/2305584/74834980-652b2880-5314-11ea-8607-eca5d622a8ce.png">

**Comment by chemzqm** [comment]
> I use "autocmd CursorHold * silent :call CocActionAsync('doHover')" do show doc/signature info in a float for the symbol under the cursor.

It's expected, use key-mappings is recommended for doHover action, or your can configure diagnostic to use echo instead of float window.
