### ISSUE TITLE
Some plugin change completeopt on insert mode (but I have no plugin except for coc.nvim itself)

### ISSUE THREAD

**Issue by shanehou** [neoclide/coc.nvim#1566]
## versions

    vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 19 2020 21:05:46)
    node version: v12.2.0
    coc.nvim version: 0.0.74-d57f450e8d
    term: dumb
    platform: linux

    ## Messages
    Messages maintainer: Bram Moolenaar <Bram@vim.org>

    Error detected while processing function <SNR>2_lod_cmd:
    line    3:
    E580: :endif without :if:  endif

    "mmpayinvoicecomm/nonpay_quota/nonpay_quota.cpp" 304L, 13507C
    match 1 of 12
    match 1 of 6
    Pattern not found
    [coc.nvim] error: Some plugin change completeopt on insert mode!
    [coc.nvim] error: Some plugin change completeopt on insert mode!
    ## Output channel: snippets

## Describe the bug

C++ autocomplete keeps saying "Some plugin change completeopt on insert mode!", but I tried removing all my plugins and the problem remains.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  call plug#begin()
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()

  set nocompatible
  set hidden
  set nobackup
  set nowritebackup
  set cmdheight=2
  set updatetime=300
  set shortmess+=c
  set signcolumn=yes
  ```

- Start (neo)vim with command: `vim -u example.cpp`

- Operate vim.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/863379/74856353-f504bd00-537c-11ea-806e-1b31f72afc53.png)

**Comment by fannheyward** [comment]
Check by `:verbose set completeopt?`, this will shows who changes `completeopt`.
`

**Comment by shanehou** [comment]
> Check by `:verbose set completeopt?`, this will shows who changes `completeopt`.
> `

![image](https://user-images.githubusercontent.com/863379/74899494-0cbd5f00-53d8-11ea-9952-f8624ac210ed.png)

Well, looks like it was set by coc itself

**Comment by chemzqm** [comment]
You should try `vim -u mini.vim example.cpp`

**Comment by shanehou** [comment]
> You should try `vim -u mini.vim example.cpp`

Yes I tried it.

`:verbose set completeopt?` firstly only showed `completeopt=preview,menuone` when I just opened the file. If I wrote a variable and hit `.`, the "some plugin" tip would show up, then `:verbose set completeopt?` would show an extra line saying `Last set from ~/.vim/pack/coc/start/coc.nvim-release/autoload/coc/api.vim line 110`.

BTW, `::` behaved well, but `.` and `->` would always shows the tip.

**Comment by oblitum** [comment]
> BTW, `::` behaved well, but `.` and `->` would always shows the tip.

Are you getting c++ server completion? If yes, you're not showing your real configuration, and your mini.vim isn't corresponding.

We can reproduce this, as there's no indication from your report including anything in special that would cause this, and no one else have hit it.

**Comment by chemzqm** [comment]
Try disable coc.nvim and check out `:verbose set completeopt?` after insert some text.

**Comment by shanehou** [comment]
> Try disable coc.nvim and check out `:verbose set completeopt?` after insert some text.

![image](https://user-images.githubusercontent.com/863379/75089883-476df580-5598-11ea-8d9d-69533f6c9d3e.png)

Maybe I loaded coc twice?

**Comment by shanehou** [comment]
And if I rename pack directory, vim would show:
![image](https://user-images.githubusercontent.com/863379/75090007-7173e780-5599-11ea-8ad9-815942d48956.png)

If I also moved omni out of autoload, it'll show: completeopt=menu,preview

**Comment by shanehou** [comment]
Ah I see. I installed `omnicppcomplete` long time ago, and it interferes with other plugins. I deleted related files and it worked like a charm!

**Comment by shanehou** [comment]
What I still don't understand: https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim

Do I have to use `vim-plug` and Automation script (use `pack`) simultaneously?

**Comment by chemzqm** [comment]
Add you need is checkout release branch and add it to rtp of vim, we don't care how

**Comment by jay-khatri** [comment]
`deoplete` was interfering for me.

**Comment by UltiRequiem** [comment]
> `deoplete` was interfering for me.
me too

**Comment by rexagod** [comment]
@jay-khatri @UltiRequiem Sorry for the ping but how did you fix that?
