### ISSUE TITLE
Specify delay

### ISSUE THREAD

**Issue by brandonkal** [neoclide/coc.nvim#1568]
**Is your feature request related to a problem? Please describe.**

Perhaps this is already an option, but I would like to increase the delay for suggestions to display. Specifically, when I enter Goyo mode, I'd like to increase the delay to a few seconds or disable the suggestions completely.

Is this possible?

**Comment by fannheyward** [comment]
Check `:h b:coc_suggest_disable`, you can use with Goyo callback: https://github.com/junegunn/goyo.vim#callbacks, something like `autocmd! User GoyoEnter let b:coc_suggest_disable = 1`.
