### ISSUE TITLE
while using flutter Plug(code-action) is not working ?

### ISSUE THREAD

**Issue by rustiever** [neoclide/coc.nvim#1572]
i referred all similar questions. But no luck
![Screenshot 2020-02-20 at 7 22 33 PM](https://user-images.githubusercontent.com/60929919/74939730-647abb00-5416-11ea-8b0b-2587d8a29fb0.png)

i should get options like wrap with widgets etc... like
![Screenshot 2020-02-20 at 7 24 52 PM](https://user-images.githubusercontent.com/60929919/74939925-b0c5fb00-5416-11ea-8205-386187b086f8.png)

what im missing?
please help me Thanks in advance.....

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by rustiever** [comment]
if so tell me what can i do 
coz i'm new to neovim/coc.nvim

please help me

**Comment by chemzqm** [comment]
Looks like the language server doesn't send code actions to coc.nvim, you need check doc of your language server.
