### ISSUE TITLE
bracketEnterImprove enter inside brackets not working

### ISSUE THREAD

**Issue by rakshans1** [neoclide/coc.nvim#1573]
## versions

vim version: NVIM v0.5.0-360-g1f479fffb
node version: v12.14.1
coc.nvim version: 0.0.74-6700e7468d
term: xterm-256color
platform: linux

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/rakshans1/dotfiles
resolved root: /home/rakshans1/dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Describe the bug
  "coc.preferences.bracketEnterImprove":true is new empty line while pressing enter inside brackets

## Screenshot
![Peek 2020-02-20 21-57](https://user-images.githubusercontent.com/12949352/74956397-0a84f000-542c-11ea-9dc9-eaf4487f7f0e.gif)

**Comment by chemzqm** [comment]
You have to remap your `<CR>`, checkout `:h coc#on_enter()`
