### ISSUE TITLE
diagnostic.enableHighlightLineNumber adds an empty signcolumn

### ISSUE THREAD

**Issue by alex-popov-tech** [neoclide/coc.nvim#1574]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.2
node version: v13.6.0
coc.nvim version: 0.0.74-c57062d0da
term: iTerm.app
platform: darwin

## Messages
Error detected while processing /Users/alexanderpopov/.config/nvim/plugins.vim:
line  200:
E117: Unknown function: coc_explorer#command#generate
E15: Invalid expression: coc_explorer#command#generate({ 'toggle': v:true, 'file-child-template': '[git | 2] [selection | clip | 1] [indent][icon | 1] [filename growRight 1 omitCenter 1][modified]', 'file-child-labeling-template': '[fullpath][size][modified][readonly]', }, '/root/path')
15 fewer lines
"firmware/firmware.ino" 107L, 3764C written

"firmware/firmware.ino" 107L, 3766C written
## Output channel: explorer
```

## Describe the bug

When I turn off sign column for diagnostic in `coc-settings.json` https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/coc-settings.json#L6
And set `signcolumn` to `auto` https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/settings.vim#L58
And I open a file with diagnostic errors/warnings

Expected result - i expect to see no signcolumn And highlighted line numbers for these lines
Actual result - there is empty signcolumn from coc https://share.getcloudapp.com/wbumr2yZ

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

You can use my dotfiles to reproduce, here is coc.nvim part - https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/plugins.vim#L115-L217 and here is coc settings https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/coc-settings.json#L6-L7

Also reproduced by @fannheyward 

Related to https://github.com/neoclide/coc.nvim/issues/1553

**Comment by chemzqm** [comment]
The line number highlight requires signcolumn exists, it's behavior of neovim.
