### ISSUE TITLE
feat&question: specify version of extension

### ISSUE THREAD

**Issue by onichandame** [neoclide/coc.nvim#1576]
**Is your feature request related to a problem? Please describe.**
When that latest commit of an extension is broken, I wish to stick to or rollback to the previous version as a temporary workaround.

**Describe the solution you'd like**
A method to specify a commit of the extension I want. be it a branch, a tag or a commit.

**Describe alternatives you've considered**
the current workaround is manually installing the extensions using Vim-Plug instead of using `CocInstall`. However, this workaround brings another plugin manager into the dependency list. I personally wish to keep everything as simple and dependency-free as possible.

**Additional context**

**Comment by chemzqm** [comment]
Install the extension by vim-plug

**Comment by onichandame** [comment]
is there any plan to natively support it in coc?

**Comment by fannheyward** [comment]
coc.nvim already support installing specify version by `:CocInstall extension@version`, for example `:CocInstall coc-markdownlint@1.0.0`. Currently, only version tag is support.

**Comment by onichandame** [comment]
@fannheyward thx! it works! before closing this issue may I ask further:
- how to disable the automatic update of the extensions? AFAIK, when a new session of nvim starts, coc tries to update all extensions automatically. I would like this function to be disabled for those extensions installed with a specific version.

**Comment by fannheyward** [comment]
Set `"coc.preferences.extensionUpdateCheck":"never"` in your coc-settings.json.

**Comment by onichandame** [comment]
cheers. sorry for being a nuisance. Any suggestions where I can find comprehensive documentation of the preferences? like a user's manual?

**Comment by fannheyward** [comment]
Check `:h coc-nvim.txt` and https://github.com/neoclide/coc.nvim/blob/master/data/schema.json

**Comment by chemzqm** [comment]
> coc.nvim already support installing specify version by `:CocInstall extension@version`, for example `:CocInstall coc-markdownlint@1.0.0`. Currently, only version tag is support.

It doesn't work, I will fix.

**Comment by fannheyward** [comment]
@chemzqm I tested `:CocInstall name@version` and it works, any problem I missed?

**Comment by onichandame** [comment]
FYI, I tested `:CocInstall name@version` using `:CocInstall coc-java@1.4.1`. Before running this command coc-java was not installed. After the command is done, coc-java seems to be functional and asks for a JRE when editing a .java file.

**Comment by chemzqm** [comment]
It could work, I've used wrong version during test.
