### ISSUE TITLE
Add option to use location list instead of quickfix for locations

### ISSUE THREAD

**Issue by Bakudankun** [neoclide/coc.nvim#1579]
**Is your feature request related to a problem? Please describe.**
There is already "coc.preferences.useQuickfixForLocations" option, but I want to use location list (which is window-local) instead of the global quickfix window.
Implementation should be easy (just use `setloclist()` instead of `setqflist()`), but I'm not sure what option is suitable to add.

**Describe the solution you'd like**
Add "coc.preferences.useLocationListForLocations" option.

**Describe alternatives you've considered**
Maybe "coc.preferences.useQuickfixForLocations" should changed to get string like `quickfix` or `locationlist`, and defaults to empty.

**Comment by chemzqm** [comment]
No, you can use autocmd and global variable to achieve this

**Comment by Bakudankun** [comment]
ok, I could actually achieved this by adding these lines to my vimrc:

```vim
let g:coc_enable_locationlist = 0
autocmd User CocLocationsChange call setloclist(0, g:coc_jump_locations) | lwindow
```

It is not clearly documented anywhere, so I write down here.

**Comment by Bakudankun** [comment]
And I think I found an error in the doc.

```
						*CocLocationsChange*

:autocmd User CocLocationsChange {command}

		For building a custom view of locations, set
		|g:coc_enable_locationlist| to 0 and use this autocmd with
		with |g:coc_jump_locations|

		For example, to disable auto preview of location list, use:
>
		let g:coc_enable_locationlist = 0
		autocmd User CocLocationsChange CocList --normal -A location        <-- here
<
```

I bereave `-A` option is to enable auto-preview, so it should be omitted here.

**Comment by chemzqm** [comment]
Yes, it's example configuration.

**Comment by yohanderose** [comment]
> ok, I could actually achieved this by adding these lines to my vimrc:
> 
> ```viml
> let g:coc_enable_locationlist = 0
> autocmd User CocLocationsChange call setloclist(0, g:coc_jump_locations) | lwindow
> ```
> 
> It is not clearly documented anywhere, so I write down here.

For anyone else struggling with why https://github.com/kevinhwang91/nvim-bqf shows quick-fix and diagnostic lists at the bottom of the window BUT references at the top just add this to your vimrc

```viml
autocmd User CocLocationsChange call setloclist(0, g:coc_jump_locations) | lwindow
let g:coc_enable_locationlist = 0
```
