### ISSUE TITLE
Project specific coc-settings

### ISSUE THREAD

**Issue by matheusml** [neoclide/coc.nvim#1580]
**Is your feature request related to a problem? Please describe.**
I'm currently working with two projects with TypeScript. The first one uses ESLint, but the other uses TSLint. I didn't find a clean way for project specific rules using coc-settings.json

**Describe the solution you'd like**
I'd like to be able to change coc-settings based on project specific rules

**Describe alternatives you've considered**
I'm thinking about running :CocUnistall eslint when vim starts under one project, and :CocUnistall tsling-plugin when vim starts in the other. Doesn't seem super clean to me.

**Comment by fannheyward** [comment]
Use `:CocLocalConfig`, this will create `.vim/coc-settings.json` in current workspace, and used as project configuration.
