### ISSUE TITLE
After starting nvim, a folder called '~' will be created in the current directory.

### ISSUE THREAD

**Issue by xuoutput** [neoclide/coc.nvim#1585]
## Describe the bug

- nvim --version: v0.4.3
- vim -u DEFAULTS (version: ) behaves differently? no
- Operating system/version: macOS Mojave 10.14.5 18F132 x86_64
- Terminal name/version: iterms2
- $TERM:xterm-256color

```
Plug 'neoclide/coc.nvim', {'branch': 'release'}
```

After starting nvim,  a folder called '~' was created in the current directory.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

this is my .vimrc file
  ```vim
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
  ```

- Start (neo)vim with command: `vim -u mini.vim`

start with `vim`

![image](https://user-images.githubusercontent.com/16385443/75353260-14a06600-58e6-11ea-8f85-5b3c694806b3.png)

- Operate vim.

```
vim
:q
ls
```

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/16385443/75353379-46b1c800-58e6-11ea-8220-3d34870172a2.png)

**Comment by xuoutput** [comment]
NVIM v0.5.0-404-g49cd750d6 bug

**Comment by xuoutput** [comment]
![image](https://user-images.githubusercontent.com/16385443/78528838-ed0cb980-7812-11ea-9dee-f5a1b43dae9e.png)
$HOME/.config/configstore/update-notifier-npm.json

**Comment by chemzqm** [comment]
coc.nvim doesn't use update notifier at all
