### ISSUE TITLE
CocAction range is never more precise than line range, even with visual mode selection.

### ISSUE THREAD

**Issue by jorisgio** [neoclide/coc.nvim#1587]
**Is your feature request related to a problem? Please describe.**
CodeAction always truncate visual range to line boundaries. 
This is an issue for [ocaml-lsp-server](https://github.com/ocaml/ocaml-lsp) "destruct" action. Destruct action will automatically expand all cases of a "case" switch, based on the type of the expression, and allows refining sub-patterns. Without precise location inside expressions, the destruct action is not working at all.

**Describe the solution you'd like**
CodeAction should send lsp request with character position in range

**Describe alternatives you've considered**

**Additional context**
The following command 
![2020-02-27-102341_3840x2160_scrot](https://user-images.githubusercontent.com/1108145/75406650-e3855d00-5908-11ea-84e1-06e41233fccb.png)
sends the following request : 
```
recv: {
  "jsonrpc": "2.0",
  "id": 5,
  "method": "textDocument/codeAction",
  "params": {
    "textDocument": {
      "uri":
        "file:///home/joris/git/merlin_install/ocaml-lsp/ocaml-lsp-server/src/ocaml_lsp_server.ml"
    },
    "range": {
      "start": { "line": 154, "character": 0 },
      "end": { "line": 155, "character": 0 }
    },
    "context": { "diagnostics": [] }
  }
}
```

**Comment by chemzqm** [comment]
It's because your're using `:<,>` which select lines only. 
Use `<Plug>(coc-codeaction-selected)` instead.
