### ISSUE TITLE
resolveRoot picking incorrect rootPath for lsp project in monorepo (repo root instead of subproject root)

### ISSUE THREAD

**Issue by campbellr** [neoclide/coc.nvim#1588]
I recently using [clojure-lsp](https://github.com/snoe/clojure-lsp/) with `coc.nvim` and noticed that it wasn't working correctly when run from the root of my repo, but worked when I ran from a subproject.

For reference, my project is a clojure monorepo with the following directory structure:

```
└── project
    ├── project.clj
    ├── subprojectA
    │   └── src/
    │   └── project.clj
    └── subprojectB
        └── src/
        └── project.clj

```

My `coc-settings.json` looks like this:

```json
  "languageserver": {
    "clojure-lsp": {
      "command": "bash",
      "args": ["-c", "clojure-lsp"],
      "filetypes": ["clojure"],
      "disableDiagnostics": true,
      "rootPatterns": ["deps.edn", "project.clj"],
      "additionalSchemes": ["jar", "zipfile"],
      "trace.server": "verbose",
      "initializationOptions": {
      }
    }
  }

```

Normally I run `nvim` from the root of the repo (eg: `/home/ryan/project/`)  and when i open (for example) a file `/home/ryan/project/subprojectA/src/subprojectA/main.clj` `resolveRoot` ends up returning that directory because it happens to have a file from `rootPatterns` in it, when it should really return either `/home/ryan/project/subprojectA`  in order for `clojure-lsp` to work correctly.

There seems to be 2 reasons for this:

1. A call to `isParentFolder` that I can't figure out the reason for [util/fs.ts#L62](https://github.com/neoclide/coc.nvim/blob/master/src/util/fs.ts#L62) ends up always returning `cwd` as the root path
2. When the line from (1) is removed, the parent directories are searched from the root *down* instead of from the open file *up* (which seems backwards) and again, ends up finding the `project.clj` in `/home/ryan/project/`

 I made a quick patch that seems to make things work for me. It removes the line from (1) and reverses the directory search order to search from the leaf directory up to the root.

But I feel like I might be missing some context for why this might not be a good idea in the general case, since I assume there was a good reason for the current implementation, so though i would start a discussion in an issue rather than just opening a PR (which i would be happy to do if this turns out to be a valid fix)... For what it's worth, a quick issue search seems to suggest that several people have run into a similar situation that this approach would have handled better (#234, #107, and #1201)

Here's my patch that works in my situation:

```diff
diff --git a/src/util/fs.ts b/src/util/fs.ts
index ddabc41f..cb241837 100644
--- a/src/util/fs.ts
+++ b/src/util/fs.ts
@@ -59,15 +59,13 @@ export async function isGitIgnored(fullpath: string): Promise<boolean> {
 export function resolveRoot(dir: string, subs: string[], cwd?: string): string | null {
   let home = os.homedir()
   if (isParentFolder(dir, home, true)) return null
-  if (cwd && isParentFolder(cwd, dir, true) && inDirectory(cwd, subs)) return cwd
   let parts = dir.split(path.sep)
-  let curr: string[] = [parts.shift()]
-  for (let part of parts) {
-    curr.push(part)
-    let dir = curr.join(path.sep)
+  while (parts.length) {
+    let dir = parts.join(path.sep)
     if (dir != home && inDirectory(dir, subs)) {
       return dir
     }
+    parts.pop()
   }
   return null
 }

```

**Comment by chemzqm** [comment]
It's designed to resovle from cwd first, https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders.

You can use `:CocList folders` with actions to manage resolved workspace folders and persist them by session.
