### ISSUE TITLE
the BufUnload autocommand make nvim switch buffer very slow

### ISSUE THREAD

**Issue by avriltank** [neoclide/coc.nvim#1591]
In the file 'pluing/coc.vim',if i delete the autocommand,there is no problem.

`    
autocmd BufUnload           * call s:SyncAutocmd('BufUnload', +expand('<abuf>'))

`
I find this code make the problem.because when i switch buffer coc will open an git progress everytime,i think this maybe the reason！！

**Comment by chemzqm** [comment]
Should be caused by extension your're using.
