### ISSUE TITLE
Coc doesnt reload config file without re-open vim

### ISSUE THREAD

**Issue by quanlou** [neoclide/coc.nvim#1595]
**Is your feature request related to a problem? Please describe.**
this is about coc-settings.json, I'm experiencing with this behavior: modify the setting by using `:CocConfig`, then use `:CocReload`, should I expected that new config will be affected in place? 
at the moment it isn't.

**Describe the solution you'd like**
It would be great if the config is auto-reloaded or by using a specific command without re-open vim because it's a little inconvenient with mono repo codebase.

**Comment by chemzqm** [comment]
You have to run  CocRestart for some configuration
