### ISSUE TITLE
Warning/Error Messages from pyls

### ISSUE THREAD

**Issue by r-learner** [neoclide/coc.nvim#16]
```
import os
  
print('coc.nvim')
```
The above dummy code will show two warnings:
```
⚠ import os
  
⚠ print('coc.nvim')
```
When the cursor on the first one, the message is shown as `[pyflakes] 'os' imported but unused [W]` on the status, but moving cursor on the second one, there is no message shown (except the previous shown message, which should be cleared after cursor moving), note that using `:lnext` or `:lprevious` will show the warning/error correctly.

`:lopen` shows the second warning: 
```
/tmp/test.py|1 col 1 warning| [pyls] 'os' imported but unused                                                                                  
/tmp/test.py|3 col 18 warning| [pyls W292] W292 no newline at end of file
```
It seems the second one comes from pydocstyle when the file is checked in the nvim buffer. However, directly running `pycodestyle --statistics -qq /tmp/test.py` does not show the warning. If I added a new blank line after that line in the nvim buffer, it will eliminate the warning, but `pylint` will complain the new blank line.

When there is one line in the file,
```
print('coc.nvim')
```
The Warning sign is shown, but the warning message is not shown unless using `:lfirst` or similar commands.

Any thoughts on the issue? Thank you.

By the way, how I could add `pylint` as default linter if I want to use `pylint`? I tried coc-setting.json, but I could not figure it out.

**Comment by chemzqm** [comment]
The error not shown is because the range given by linter is out of your cursor range, you can use
```
set virtualedit=onemore
```
to make the message shown on cursor move. But it's not a good idea, I will find a way to improve it.

Unfortunately pylint is not supported by https://github.com/palantir/python-language-server, it's not a well maintained language server, I will migrate the official one.

**Comment by r-learner** [comment]
@chemzqm Thank you.

Currently I used pyls along with ale.

Please take your time to implement/improve the wonderful neovim plugin, I am looking forward to having a perfect neovim plugin for programming.
