### ISSUE TITLE
Popup menu blinks and hide while completing

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#160]
**Describe the bug**
Vim only issue, in NeoVim there's no problem. In Vim (my version is 8.1.519) when writing code while the completion items are displayed, there's a lot of menu flickering, when typing char by char slowly one can notice the menu gets disabled and then it comes back and then vanishes again, on the event of character insertion (while just writing `std::cout`).

**Expected behavior**
No menu flickering.

**Additional context**
```json
{
    "coc.preferences.splitLabelForWord": true,
    "coc.preferences.triggerCompletionWait": 100,
    "coc.preferences.triggerSignatureHelp": false,
    "languageserver": {
        "ccls": {
            "command": "ccls",
            "filetypes": ["cpp"],
            "initializationOptions": {
                "cacheDirectory": "/tmp/ccls"
            }
        }
    }
}
```

**Comment by chemzqm** [comment]
There would always be flickering unless the items is filtered by vim, you didn't notice it on neovim is because neovim has faster api and coc use buffer events to sync buffer content on neovim.

**Comment by chemzqm** [comment]
I've tried with vim and neovim, and didn't notice too much difference.
Other completion engine could be less flicking since they don't support fuzzy match on TextChangedP, and they can't perform correct fuzzy match.

**Comment by oblitum** [comment]
It seems it's completely fine now, maybe some of the latest changed fixed it 🤔. I'm using the commit prior to 29460af, because that one have [broken stuff for me](https://github.com/neoclide/coc.nvim/issues/156#issuecomment-437941647).
