### ISSUE TITLE
Can we add a symbol `kind` filter to `Symbols::loadItems`?

### ISSUE THREAD

**Issue by lanza** [neoclide/coc.nvim#1600]
The `Symbols` class implements the `CocList symbols` command. It queries the server for all symbols that match a query string and gets an array back of `SymbolInformation`s. `loadItems` then transforms the `SymbolInformation` to a displayable format. This code is used:

```
    for (let s of symbols) {
      let kind = getSymbolKind(s.kind)
      let file = URI.parse(s.location.uri).fsPath
      if (isParentFolder(workspace.cwd, file)) {
        file = path.relative(workspace.cwd, file)
      }
      items.push({
        label: `${s.name} [${kind}]\t${file}`,
        filterText: `${s.name}`,
        location: s.location,
        data: { original: s, kind: s.kind, file, score: score(input, s.name) }
      })
    }
```

I think it would be a nice feature to offer 

```
let kind = getSymbolKind(s.kind)
if (context.options.matchkind !== kind) {
    continue;
}
```

so that the user could do `CocList symbols --kind=class` etc.

**Comment by chemzqm** [comment]
Use `:CocList -I symbols -kind class`

**Comment by lanza** [comment]
Thank you!

**Comment by wolloda** [comment]
I understand that `:CocList -I symbols -kind [method, function]` is not possible -- is there a way to somehow join outputs of 
`:CocList -I symbols -kind method` and `:CocList -I symbols -kind function` and search in both?
