### ISSUE TITLE
ugly `showbreak` on popup vim8

### ISSUE THREAD

**Issue by ndtho8205** [neoclide/coc.nvim#1604]
## Result from CocInfo

```
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/
go-build220909672=/tmp/go-build -gno-record-gcc-switches"

[Info  - 1:19:21 PM] 2020/03/04 13:19:21 go/packages.Load
        snapshot = 0
        query = [./ builtin]
        packages = 2
```

## Describe the bug

Vim8 popup shows the `showbreak` character when the function docstring getting too long. It's ugly.

## Reproduce the bug

- Create file `mini.vim` with：

 ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden

  set showbreak=↪\
```

## Screenshots

![Screenshot from 2020-03-04 13-25-42](https://user-images.githubusercontent.com/11143062/75845234-d04c2300-5e1b-11ea-9ec3-d582597eb8bc.png)

![Screenshot from 2020-03-04 13-26-04](https://user-images.githubusercontent.com/11143062/75845238-d2ae7d00-5e1b-11ea-9b58-a81263b7a73e.png)

## Comment

It seems like the passed value to reset the `showbreak` setting on the local window/buffer does not work (on [floating.ts#L170](https://github.com/neoclide/coc.nvim/blob/bd7b0ecb225ff6ad3d79e518b6bca1a9be958b82/src/completion/floating.ts#L170), [floatFactory.ts#L95](https://github.com/neoclide/coc.nvim/blob/aade9a2616145a7a4eadc56e2c8a69d61aeb6ef1/src/model/floatFactory.ts#L95)).

```javascript
win.setOption('showbreak', '', true)
```

According to [vimdoc](https://github.com/vim/vim/blob/b3f740695a0199d22cd97aee314f06c7ae32d2ea/runtime/doc/options.txt#L6786), it should be:

```javascript
win.setOption('showbreak', 'NONE', true)
```

So I tried to change the two above-mentioned lines and it works as expected:
- On the opened file, keep the `showbreak` character
- On the completion popup, reset `showbreak` to no value

**Comment by chemzqm** [comment]
`win.setOption('showbreak', 'NONE', true)` doesn't work on neovim.

**Comment by chemzqm** [comment]
`showbreak=NONE` is add on vim 8.1.2281 https://github.com/vim/vim/commit/ee85702c10495041791f728e977b86005c4496e8

**Comment by ndtho8205** [comment]
I pulled the latest commit. The problem still exists, but only in the complete docstring as shown below. I also commented on the commit, please have a look. Thank you for your efforts. :D

![Screenshot from 2020-03-06 17-18-06](https://user-images.githubusercontent.com/11143062/76065197-7c357000-5fce-11ea-81e7-47f4ed494c52.png)

![Screenshot from 2020-03-06 17-18-13](https://user-images.githubusercontent.com/11143062/76065201-7e97ca00-5fce-11ea-901a-baa8d3fe1f90.png)

**Comment by chemzqm** [comment]
Fixed now.
