### ISSUE TITLE
Ctrl-C should close Fuzzy> Search

### ISSUE THREAD

**Issue by vito-c** [neoclide/coc.nvim#1605]
## versions

vim version: NVIM v0.4.3
node version: v13.8.0
coc.nvim version: 0.0.75-89c0c2380b
term: iTerm.app
platform: darwin

## Describe the bug
I can press `<Enter>` when there is  nothing in the search box to exit fuzzy search but  `<C-c>` doesn't exit the Fuzzy> search. For example say I type
`:CocCommand`
Fuzzy> 
then I start to type something
Fuzzy>foo.bar.baz
oops I changed my mind `<C-c>` nothing happened `<C-c>` nothing happened mash mash mash oh.. `<ESC>`

**Comment by fannheyward** [comment]
```
  "list.normalMappings": {
    "<C-c>": "do:exit"
  },
  "list.insertMappings": {
    "<C-c>": "do:exit"
  },
```

add to your `coc-settings.json`.

**Comment by vito-c** [comment]
Thanks. It might be a  good default to add as well.

**Comment by chemzqm** [comment]
It's used for stop loading task, checkout `:h coc-list-mappings`, you have to override it you want it to exit list session.

**Comment by vito-c** [comment]
ok thanks
