### ISSUE TITLE
100% CPU usage if a large JSON buffer is open

### ISSUE THREAD

**Issue by jean** [neoclide/coc.nvim#1606]
**Is your feature request related to a problem? Please describe.**
I saved an unrelated wiki buffer, but I had a 60+MB HAR (JSON format) file open in another buffer. 
This takes forever to complete, and `top` shows that the `coc.nvim` Node indexing process is taking up 100% CPU. 

**Describe the solution you'd like**
Notify that some buffer is taking too long to index, and abort indexing on that buffer.

**Comment by chemzqm** [comment]
It's expected, checkout `:h g:coc_start_at_startup` for disable coc.nvim from start on vim startup.
Or use `vim -u NORC` to open large files.

**Comment by jean** [comment]
Hmm `:CocStop` might be useful ... or is that `:CocDisable`? 99% of time I want start at startup, but occasionally I may load an unexpectedly heavy file.

**Comment by oblitum** [comment]
@jean there are plugins to handle this situation, you may check this one from DrChip for example: http://www.drchip.org/astronaut/vim/#LARGEFILE.

**Comment by chemzqm** [comment]
Checkout `:h b:coc_enabled`, you can use autocmd to disable coc.nvim for specific buffer.

**Comment by jean** [comment]
Thanks for the advices! :grin:

**Comment by oblitum** [comment]
@chemzqm for what is worth, I remember when I used YouCompleteMe that it provided large file detection built in and didn't load automatically. You could set maximum file size, there was a default maximum. coc.nvim maybe could provide similar feature.

**Comment by oblitum** [comment]
https://github.com/ycm-core/YouCompleteMe#the-gycm_disable_for_files_larger_than_kb-option

**Comment by hasufell** [comment]
I came here, because I'm also looking for `:CocStop`. I don't want to close my editor, but I also don't want it to waste 4GB of ram.

**Comment by oblitum** [comment]
@hasufell doesn't `:CocDisable` do the job?

**Comment by oblitum** [comment]
You should also check whether it's the node for coc.nvim that's consuming CPU or whether it's the node instance of the language server, if it's the language server node that's stuck, coc.nvim most certainly can't do much about it.

**Comment by hasufell** [comment]
> doesn't :CocDisable do the job?

That doesn't shut down the server.

> if it's the language server node that's full CPU, coc.nvim most certainly can't do much about it.

It manages the process. Why would it not be able to shut it down?

**Comment by oblitum** [comment]
> It manages the process. Why would it not be able to shut it down?

Maybe be convenient service, but seems out of scope of LSP, strictly speaking, no standard on that. IMO, managing processes is job of the system, `kill -STOP`, etc, seems better fit.

**Comment by oblitum** [comment]
FWIW, such kind of processes goodies which go out of scope of LSP is generally provided by the extensions.

**Comment by hasufell** [comment]
> May be convenient service, but seems out of scope of LSP

Why would that be? It's the one that spawns the process. It should be the one to shut it down. Having users figure out kill commands is bad UI.

> FWIW, such kind of processes goodies which go out of scope of LSP is generally provided by the extensions.

I don't run extensions.

**Comment by oblitum** [comment]
> Having users figure out kill commands is bad UI.

Open feature request.
