### ISSUE TITLE
A way to disable language integration when encountering conflict markers

### ISSUE THREAD

**Issue by xylix** [neoclide/coc.nvim#1609]
**Is your feature request related to a problem? Please describe.**
Conflict markers in a file cause a biiig bunch of language server erros (which is understandable, since they aren't legal syntax. This makes the file laggy and makes it hard to see some lines, with the syntax errors blocking my view.
![Screenshot 2020-03-04 at 12 27 15](https://user-images.githubusercontent.com/13387304/75870391-92e39780-5e13-11ea-8747-b146ba67e46f.png)

**Describe the solution you'd like**
A feature to toggle language server functionality automatically off when encountering conflict markers.

**Comment by chemzqm** [comment]
Use `"diagnostic.messageTarget": "echo"` in coc-settings.json if you don't like floating window or you can disable diagnostics from coc.nvim.
