### ISSUE TITLE
Use kind complete-item field to tag snippet items instead of ~ in the end of abbr

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#161]
**Is your feature request related to a problem? Please describe.**
For me personally the `~` being used at the end of completion items looks really weird compared to other completers. They all use the kind field, the one of the middle column, for that. The `~` could be there, or some other more meaningful text, maybe even some utf-8 char.

Besides this, there are other technical issues with adding `~` to the end of signatures:

1.  It may interact badly with other tools. For example, echodoc grabs the `~` to show signatures at the command line, the `~` doesn't make sense there.
2. Programming languages may have `~` in their vocabulary, which can confuse the user when shown as part of a signature, but without the meaning the language have for it. C++ for example has `~` for destructors and bitwise not.

**Describe the solution you'd like**
Something that isn't glued with signatures, to avoid confusion.

**Describe alternatives you've considered**
It should be indicated in the kind field, which is what's generally used for this task.

**Comment by chemzqm** [comment]
The kind field is already used for for kind of complete item, it's the format of complete item, I can't agree use kind is a good idea.

It's not hard to make echodoc not grab the `~` at end of abbr, it could check `user_data` field for `cid` that added by coc.nvim.

**Comment by chemzqm** [comment]
echodoc is full of magic guess for complete item, I won't change the behavior to make coc just better works with echodoc.

**Comment by chemzqm** [comment]
The word of complete item doesn't have `~` at end, it could also be resolved if echodoc prefer use word for signature than abbr.

**Comment by oblitum** [comment]
Thanks for the info. OK, but putting echodoc aside what you think of the other points. For example, it may be not that weird when I see the signature `foo(int a, int b)~` in the popup, it's a bit weird, but when I see `foo(int a, int b)*~`, `foo(int a, int b)&&~`, `foo<int>&*~`, it gets weirder and weirder because `~` near other special characters looks more and more like part of the signature. The thing can get really problematic if you hit a programming language that can in fact use `~` as operator at end of signatures to mean something.

**Comment by chemzqm** [comment]
Ok, I can make that character configurable so user could change it to other character, like a emoji.

**Comment by oblitum** [comment]
Nice.

**Comment by adelarsq** [comment]
Related commit https://github.com/neoclide/coc.nvim/commit/13790cce06fed23520c9215c3df97ebad89eb5cc :smile:

**Comment by oblitum** [comment]
@adelarsq thanks, I hadn't noticed.
