### ISSUE TITLE
[Feature Request] Enhance jumpCommand with "tabeWhenUnopenedFile"

### ISSUE THREAD

**Issue by kirillbobyrev** [neoclide/coc.nvim#1612]
When navigating the code, I really like opening new files in tabs and hence I set `coc.preferences.jumpCommand: tabedit`. However, when the jump happens within the same file, I end up with two tabs containing the same file. I would really love to have an option that would make the jump open new tab for files that are not opened in any buffers right now and simply go to the right buffer if the file I'm jumping to is already opened. Something like `tabeWhenUnopenedFile` would be nice.

**Comment by fannheyward** [comment]
What you want is when you set `coc.preferences.jumpCommand: tabedit`:

1. file not opened, `tabedit` to open in new tab
2. file already opened, maybe same file or in another buffer, just `edit`

Do I understand right?

**Comment by kirillbobyrev** [comment]
Yes, this is correct. I think I might implement some custom Vim command for that, but it would be great if coc.nvim supported this 🙂

**Comment by chemzqm** [comment]
Use custom keymap like `  nmap <silent> gt :call CocAction('jumpDefinition', 'tabe')<CR>`
