### ISSUE TITLE
can't format the complete item

### ISSUE THREAD

**Issue by chenjie199234** [neoclide/coc.nvim#1614]
i hope to show the complete items like this,looks very comfortable
![hope](https://user-images.githubusercontent.com/29348971/75953159-bf6ae280-5eeb-11ea-900e-a66e9cc36554.png)
but i got this,it looks in a mess
![企业微信截图_15833887791385](https://user-images.githubusercontent.com/29348971/75953219-de697480-5eeb-11ea-9c58-f54c0254baf4.png)
how to format this

**Comment by chemzqm** [comment]
Check the document, there's an option to disable gui pum.

**Comment by chenjie199234** [comment]
@chemzqm thx very much,it fix my problem

**Comment by oblitum** [comment]
Didn't even know this weird thing existed.
