### ISSUE TITLE
Can it auto complete for hide file path?

### ISSUE THREAD

**Issue by fcying** [neoclide/coc.nvim#1617]
## Result from CocInfo
```
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 11:19:59)
node version: v13.8.0
coc.nvim version: 0.0.75-db09d34c86
term: dumb
platform: linux

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
## Output channel: snippets
```

## Describe the bug
when I write a file path, it can't auto complete for hide file(dir).
but when I type hide dir's full name , it can complete the files in the hide dir.

## Reproduce the bug
```
vim a.sh
~/.ssh            # after type `.`, I can't see any complete
```

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```
## Screenshots (optional)
ok
![图片](https://user-images.githubusercontent.com/106934/75964426-298e8200-5f02-11ea-81bc-1bde859b83b8.png)
hide file, dir can't complete
![图片](https://user-images.githubusercontent.com/106934/75964467-3ca15200-5f02-11ea-9642-0deca01e3db4.png)
files in hide dir.
![图片](https://user-images.githubusercontent.com/106934/75964483-41fe9c80-5f02-11ea-80e1-7c4a16801eb3.png)

**Comment by chemzqm** [comment]
Add `"coc.source.file.ignoreHidden": false` in coc-settings.json.

**Comment by fcying** [comment]
after add this but still no complete.
```
CocConfig
{
  "coc.source.file.ignoreHidden": false
}
```

**Comment by chemzqm** [comment]
@fcying fixed.

**Comment by yushangakki** [comment]
It works right now! Thanks!
