### ISSUE TITLE
Coc stopped working "internalModuleReadFile is not a function"

### ISSUE THREAD

**Issue by tomaskallup** [neoclide/coc.nvim#162]
**Describe the bug**
Today, I updated my vim & vim plugins and coc stopped working. At first I had no idea why that was, then I opened `:messages` and saw this pop up:
```
[coc.nvim] Error loading extension from /Users/tomaskallup/.config/coc/extensions/node_modules/coc-eslint/lib/index.js: process.binding(...).internalModuleReadFile is not a function
[coc.nvim] Error loading extension from /Users/tomaskallup/.config/coc/extensions/node_modules/coc-html/lib/index.js: process.binding(...).internalModuleReadFile is not a function
[coc.nvim] Error loading extension from /Users/tomaskallup/.config/coc/extensions/node_modules/coc-json/lib/index.js: process.binding(...).internalModuleReadFile is not a function
[coc.nvim] Error loading extension from /Users/tomaskallup/.config/coc/extensions/node_modules/coc-tslint/lib/index.js: process.binding(...).internalModuleReadFile is not a function
[coc.nvim] Error loading extension from /Users/tomaskallup/.config/coc/extensions/node_modules/coc-css/lib/index.js: process.binding(...).internalModuleReadFile is not a function
[coc.nvim] Error loading extension from /Users/tomaskallup/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js: process.binding(...).internalModuleReadFile is not a function
```
I tried running `:CocUpdate`, but that didn't help either. At first I though it could be node related, but my node version is still `8.12.0`.

Any idea what this could be related to or where I should look?

**Desktop (please complete the following information):**
 - Terminal: iTerm2
 - Version: v3.1.0
 - Vim version: 8.1.500

**Comment by adelarsq** [comment]
I noticed the same. This is happening after https://github.com/neoclide/coc.nvim/commit/31b70afae974a0ca656207e9304ae446ad7371ef to use Node 10.

**Comment by adelarsq** [comment]
Found that [internalModuleReadFile was renamed to internalModuleReadJSON](https://github.com/nodejs/node/commit/fea1e05ba5) :cry:

**Comment by adelarsq** [comment]
It's a problem with pkg project I think https://github.com/zeit/pkg/issues/467

**Comment by tomaskallup** [comment]
Yea, seems like it. My current workaround is just `git reset HEAD~1 && yarn install` in coc.nvim folder.

**Comment by chemzqm** [comment]
I've rebuild the binary with node 8 and upload the binary again, it should be fixed after run `:call coc#util#install()`.
Sorry for the unconvience, I changed to use node 10 because I'm not able to download node binary required by pkg yesterday and didn't notice node 10 with pkg not working.
