### ISSUE TITLE
CocList symbols fails to find workspace symbols provider

### ISSUE THREAD

**Issue by jeroen-dhollander** [neoclide/coc.nvim#1621]
# Description

`:CocList symbols` fails with error
    `[coc.nvim] Error on "CocList symbols": Workspace symbols provider not found for current document`

Other actions like `:CocList outline` and `<plug>(coc-definition)` work for the same document.

This started happening after upgrading CoC to the latest released version.

# System:

vim version: NVIM v0.4.2
node version: v10.17.0
coc.nvim version: 0.0.75-027b7a76e9
term: xterm-256color
platform: linux

# LanguageServer:

C++, using clangd

If you need any more information, please let me know.

**Comment by przepompownia** [comment]
I confirm similar problem with the latest version of [bash-language-server](https://github.com/bash-lsp/bash-language-server/issues/197).

**Comment by chemzqm** [comment]
Your have to make your current document have workspace symbols provider register to coc.nvim, could be your language server not ready or you don't have symbols support for current document.

**Comment by jeroen-dhollander** [comment]
Hey Chemzqm,

I am not sure what you mean by that, could you elaborate?
In the mean time I verified the issue is present in v0.0.74 and v0.0.75, but it works in v0.0.73,
so I really think it is an actual bug.

**Comment by fannheyward** [comment]
Fixed on master, please give a test

**Comment by przepompownia** [comment]
Thanks for fixing

**Comment by jeroen-dhollander** [comment]
I verified it now works again. Thanks for the very quick fix!
