### ISSUE TITLE
Fix the workspace to only cwd (or one .git location) and do not collect additional workspaces when browsing around

### ISSUE THREAD

**Issue by jjmurre** [neoclide/coc.nvim#1623]
When I browse through different projects Coc keeps accumulating workspaces. This leads to problems with finding tools like linters and formatters.

I now discovered that I can do a ":CocList folders" and delete the unwanted workspaces.
Would it be possible to just use "cwd" (or just one workspace based on .git location) for the workspace and do not accumulate workspaces when browsing through other projects?

**Comment by chemzqm** [comment]
You can configure how coc.nvim for collect workspace folders https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders
