### ISSUE TITLE
Session directories can be keep in one directory

### ISSUE THREAD

**Issue by przepompownia** [neoclide/coc.nvim#1624]
```
 $ ll /tmp/coc* -d
drwxr-xr-x 2 100 2020-03-05 17:51:56 /tmp/coc.nvim/
drwxr-xr-x 2  60 2020-03-05 17:53:43 /tmp/coc.nvim-161396/
drwxr-xr-x 2  80 2020-03-06 00:02:44 /tmp/coc.nvim-176064/
drwxr-xr-x 2  80 2020-03-06 00:05:35 /tmp/coc.nvim-176269/
drwxr-xr-x 2  80 2020-03-06 00:05:41 /tmp/coc.nvim-176337/
```
Each of `/tmp/coc.nvim-([0-9])+` could be a subdirectory of `/tmp/coc.nvim`. With the current we have again lots coc-specicic things ath the top of tmpdir.

**Comment by chemzqm** [comment]
Yes, but they should be cleaned when process of coc.nvim exited (most likely).
You can clean them by `rm -rf /tmp/coc.nvim-*`.

**Comment by przepompownia** [comment]
They are not cleaned by CoC at nvim exit. 
```
 $ ls -1 /tmp/coc* -d
/tmp/coc.nvim
/tmp/coc.nvim-161396
/tmp/coc.nvim-176064
/tmp/coc.nvim-176269
/tmp/coc.nvim-176337
/tmp/coc.nvim-176697
/tmp/coc.nvim-176912
/tmp/coc.nvim-177088
/tmp/coc.nvim-177295
/tmp/coc.nvim-177403
/tmp/coc.nvim-177474
/tmp/coc.nvim-177714
/tmp/coc.nvim-177783
/tmp/coc.nvim-177860
/tmp/coc.nvim-181083
/tmp/coc.nvim-184365
/tmp/coc.nvim-184475
/tmp/coc.nvim-184606
/tmp/coc.nvim-187601
/tmp/coc.nvim-188056
```

**Comment by chemzqm** [comment]
You can clean them up yourself, they're not using too much disk space.

**Comment by przepompownia** [comment]
What's wrong with keeping all these directories in the one common? Sometimes I have to manually browse tmpdir. A large number of files make a mess.

**Comment by chemzqm** [comment]
I've made a fix for clean the temp directory.

**Comment by przepompownia** [comment]
Thanks, it works.
