### ISSUE TITLE
Type definition provider not found for current document

### ISSUE THREAD

**Issue by monsonjeremy** [neoclide/coc.nvim#1627]
## Result from CocInfo
```
## versions

vim version: NVIM v0.4.3
node version: v12.16.0
coc.nvim version: 0.0.75-d5e12d81b2
term: screen-256color
platform: darwin

## Messages
[coc.nvim] Type definition provider not found for current document
```

## Describe the bug

This feature was previously working in my typescript files (`.ts`) but unexpectedly i'm no longer able to see the documentation hover or go to definitions

I hover over the file path I want to go to and then press <leader>dd which I have mapped as follows:
`nmap <silent> <leader>dt <Plug>(coc-definition)`

```
import express from 'express'
                                     ^ cursor here
```

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

I tried to do the above steps but cannot get it to let me to call the function.

**Comment by Shenmin-Z** [comment]
I'm having the same issue. I was editing some typescript file and suddenly it stopped working.

**Comment by Shenmin-Z** [comment]
I see people are having the same problem at the chat channel: https://gitter.im/neoclide/coc.nvim
Seems to be an issue with `tsserver`, downgrade works for me.

> Rostero @rostero1 04:16
:CocInstall coc-tsserver@1.4.9 did the trick

**Comment by iamcco** [comment]
It seems the latest version does not have build bundle.

**Comment by Abdullah-F** [comment]
same problem is happening with me and I can not navigate my React code and go to code definitions.
downgrading the server did fix it for me also.

I think the problem has to do with then new releases.
I will be watching this issue till a good solution comes.

**Comment by fannheyward** [comment]
Move to https://github.com/neoclide/coc-tsserver/issues/124

**Comment by monsonjeremy** [comment]
The fix is here: https://github.com/neoclide/coc-tsserver/issues/124#issue-576878721

I'm sure this will be fixed permanently soon, but i'm going to close this ticket since it has to do with coc-tsserver not coc.nvim

**Comment by baogiadoan** [comment]
I faced the same issue recently, but I observed that there is Analyzing in the background status, waiting for 1 or 2 minutes then it's working again for me, not sure what's the cause for this and how to fix, since it consumes time

**Comment by chemzqm** [comment]
> I faced the same issue recently, but I observed that there is Analyzing in the background status, waiting for 1 or 2 minutes then it's working again for me, not sure what's the cause for this and how to fix, since it consumes time

Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel, tsserver could be slow to initialize.
