### ISSUE TITLE
Force a specific filetype to use only a specific source?

### ISSUE THREAD

**Issue by 097115** [neoclide/coc.nvim#1629]
Is it possible to force CoC to use only, say, the `coc-tags` source for a specific filetype (like, for files with `.bar` extension)? What do I put in my `~/.vim/coc-settings.json` config?

**Comment by oblitum** [comment]
Use [`coc.source.tag.filetypes`](https://github.com/neoclide/coc-sources/blob/8fbdda7ea46bd423a33f4d0d2c36a53f6596574b/packages/tag/package.json#L43).

**Comment by oblitum** [comment]
Reopening as I got the question wrong.

**Comment by oblitum** [comment]
I suspect the most straightforward solution to this question is to use a custom `g:coc_data_home` (check `:h g:coc_data_home`) that's set on a `FileType` `autocmd`, that will just contain the extensions you need, otherwise you would have to disable the filetype per source in case it's a general source.

**Comment by 097115** [comment]
@oblitum Could you please stop closing my issues without providing anything even remotely close to a solution?

WTF, mate?

Like, with this `:h g:coc_data_home`: I have only `coc-tag` now in my `coc_data_home` but CoC still suggests not only tags but also every word it finds in other open buffers.

**Comment by 097115** [comment]
@oblitum So, I would be grateful if you could re-open this one, too.

**Comment by oblitum** [comment]
>  Could you please stop closing my issues without providing anything even remotely close to a solution?

No. You're not posting issues as you're not filling any templates. Please check README that demands you to ask on gitter if you have a question.

**Comment by 097115** [comment]
@obitum Templates are suggested for bug reports and feature suggestions. These my questions aren't any of those

**Comment by 097115** [comment]
@oblitum And I also DID asked on gitter but haven't received a reply (not even an answer) in 24 hours.

**Comment by oblitum** [comment]
@097115 hence the README demands you to go to gitter first, otherwise the issue tracker can get littered with question. You should be patient, as ask again. @chemzqm for example responds many after several hours have gone by. This is free software, so, stop with ETA expectations.

**Comment by 097115** [comment]
@oblitum I FUCKING DID GO TO GITTER FIRST, how else should I type this out for you?

But I see, you'll just never admit you were wrong (and really just spamming), so it's pointless to discuss. Thanks for the support, mate. You really did best to provide a brilliant impression of CoC team.

**Comment by chemzqm** [comment]
There is an API to invoke completion of specific source, you can also disable auto completion on type.

**Comment by arcnmx** [comment]
Was there ever a usable generic solution to this proposed? For example, you may want to use `around [A]` buffer word completion for text files or documentation, but it's redundant and should be disabled when editing source code with a functional language server providing identifiers for completion. `priority` may help push them to the bottom, but... is there a way to do this properly?

**Comment by chemzqm** [comment]
Checkout `:h CocAction('toggleSource')` for dynamic enable and disable sources.
