### ISSUE TITLE
Cannot get coc.vim working for jsx/javascript projects

### ISSUE THREAD

**Issue by hsheikhali** [neoclide/coc.nvim#1633]
Hey guys, 

So quick background -- I'm new to then vim world. I'm coming from VSCode and wanted to dabble in the world of vim. 

I've got 90% of what I want working however, the arguably the most important feature is giving some real pain. I don't see any intellesense popup for JavaScript files or JSX files. TS and TSX files work just fine and what's even more puzzling is JavaScript intellesense in <script> tags for html projects work as well. Everything BUT JavaScript or JSX files work.

I also got coc-emmet but nothing else.. Can someone help me out? What do I need to add to help diagnose my problem

**Comment by fannheyward** [comment]
Do you use `coc-tsserver`? The latest version of coc-tsserver fails to run, you need to fallback to previous version `:CocInstall coc-tsserver@1.4.9`. Move to https://github.com/neoclide/coc-tsserver/issues/124

**Comment by hsheikhali** [comment]
@fannheyward Thank you !
