### ISSUE TITLE
can't install using vim-plug

### ISSUE THREAD

**Issue by ipsod** [neoclide/coc.nvim#1634]
## versions

vim version: NVIM v0.5.0-317-gfd89ad7bf
node version: v13.10.1
coc.nvim version: 0.0.75-d5e12d81b2
term: xterm-256color
platform: linux

## versions

vim version: NVIM v0.5.0-317-gfd89ad7bf
node version: v13.10.1
coc.nvim version: 0.0.75-9706d69c81
term: xterm-256color
platform: linux

## Messages
"~/.config/nvim/init.vim" 1610L, 63186C written
[coc.nvim] javascript file not found, please compile the code or use release branch.

3 lines yanked into "+
".config/nvim/init.vim" 1610L, 63190C written
1 change; before #73  0 seconds ago

".config/nvim/init.vim" 1610L, 63186C written
coc.nvim service not started, checking environment...

## Describe the bug
I can't install using `Plug 'neoclide/coc.nvim', {'branch': 'release'}`.  After running `PlugInstall` I get the error:

> x coc.nvim:
>     sh: 0: can't access tty; job control turned off
>     fatal: invalid reference: release

I can install if I change it to: `Plug 'neoclide/coc.nvim'`

## Reproduce the bug

I tried the same after disabling all other plugins, and had the same error.
I'm on Linux Mint 19.

**Comment by EternalChildren** [comment]
i have the same problem in centos 7

**Comment by chemzqm** [comment]
Upgrade your vim-plug and try again.
