### ISSUE TITLE
how can i  store result of CocAction('doHover') into a viml variable

### ISSUE THREAD

**Issue by paopaol** [neoclide/coc.nvim#1639]
**Is your feature request related to a problem? Please describe.**
when i call CocAction('doHover') .the Signature displayed, but, sometimes i want use the Signature do something else.like this,

```viml
 let signature = CocAction('doHover')
 echom signature
```

**Describe the solution you'd like**
how can i do this

**Comment by chemzqm** [comment]
You should only use echom for string variable.
If you want to send request in viml, checkout `:h CocRequest()`
