### ISSUE TITLE
coc-list-outline  only show the function name,but can't show the function of namespace/calss

### ISSUE THREAD

**Issue by paopaol** [neoclide/coc.nvim#1640]
## Describe the bug

coc-list-outline  only show the function name,but can't show the namespace/calss of function
```cpp
namespace mysp{
class A{
public:
 void func();
}
}

namespace mysp{
class B{
public:
 void func();
}
}
```

* the out line result is

```cpp
func();
func();
```

* expected:

```cpp
mysp::A::func()
mysp::B::func()
```

**Comment by oblitum** [comment]
I can't reproduce your issue on coc-clangd. Your code also contain errors, missing `;`, which my affect results.

**Comment by chemzqm** [comment]
Yes, it's expected, you can create your own list source by create coc extension.
You can also use like plugin https://github.com/liuchengxu/vista.vim for a good sidebar.

**Comment by chemzqm** [comment]
Yes, it's expected, you can create your own list source by create coc extension.
You can also use like plugin https://github.com/liuchengxu/vista.vim for a good sidebar.

**Comment by oblitum** [comment]
But with clangd I do get outlined hierarchy from `:CocList outline`.

**Comment by chemzqm** [comment]
Could be problem of clangd version.

**Comment by paopaol** [comment]
i im use ccls.here is my Screenshot
![2020-03-09 16-02-56屏幕截图](https://user-images.githubusercontent.com/6983082/76193679-839f8800-621f-11ea-9499-2beaf934b21f.png)

**Comment by chemzqm** [comment]
@paopaol outline list of coc.nvim just show the name, you can ask ccls to improve the name for symbols, you implement yourself.

**Comment by paopaol** [comment]
but why not emacs lsp-mode  works fine by ccls? Isn't coc and emacs lsp-mode  using the same request method?

**Comment by chemzqm** [comment]
I don't know. But you can checkout output from server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by oblitum** [comment]
@paopaol clangd screenshot of your snippet:

![imgur-11:31:47_09-03-2020](https://user-images.githubusercontent.com/1269815/76222769-cfd7d180-61f9-11ea-94b2-6fa1e6d5f30a.png)

**Comment by oblitum** [comment]
Ah,

But it's still the same issue after you type `"f"`,  fuzzy completion makes hierarchy vanish and you just get two `func`s, so it's same problem. It's design issue. I'm not sure whether it's coc.nvim issue or server's issue, may this request was designed to display static hierarchy and not to be used for fuzzy.

**Comment by fannheyward** [comment]
Try `:CocList outline -kind` whether works for you.

**Comment by pvonmoradi** [comment]
@fannheyward 
> :CocList outline **-kind**

Does it mean that the command now supports a tag as argument? (I didn't find info on it in docs)  
 Is it possible to sort `outline` and put methods/functions first? or exclude variables? (In a typical file, it first shows public variables which fills up the already confined space of outline...)
