### ISSUE TITLE
Node.js installation failed

### ISSUE THREAD

**Issue by ct17b7** [neoclide/coc.nvim#1642]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

在aarch64上无法使用一键安装

**Comment by chemzqm** [comment]
没有一键安装支持，你可以看文档或者早点放弃
