### ISSUE TITLE
Support call hierarchies

### ISSUE THREAD

**Issue by MattSPalmer** [neoclide/coc.nvim#1649]
**Is your feature request related to a problem? Please describe.**

No problem other than tracking feature parity with tsserver (here is the companion issue for [coc-tsserver](https://github.com/neoclide/coc-tsserver/issues/128)) and VSCode.

**Describe the solution you'd like**

Support for retrieving call hierarchies in tree form for named callables. 

```
class MainThing {
  static do() {
    utilA();
  }
}

//    X-- cursor 
const doLotsOfThings () => {
  MainThing.do();
  utilB();
}

// 
// :CocList callHierarchy --maxDepth 3

OUTPUT

--------------------------------------------------------------
doLotsOfThings()
  calls
    MainThing.do()
      utilA()
    utilB()
  is called by
    Scheduler.run

```

I believe the minimal required UI would be list-based, similar to the 'outline' list. It could take a "max depth" argument to control the indentation.

Actions on list items might include: 
- go to definition
- get references
- re-request hierarchy using same args but with this callable as the root.

**Describe alternatives you've considered**

I _think_ you could do this with existing LSP features in a coc extension, but without language-server-level support there would likely be a problem with N+1 queries.

**Additional context**

I'm not sure which API the project's maintainers prioritize, that of VSCode, Microsoft's LSP spec, or both. So I'm likewise unsure how important it is that as of this writing, the [proposal issue](https://github.com/microsoft/language-server-protocol/issues/468) has yet to be adopted by Microsoft, though the latest release of VSCode supports it.

**Comment by chemzqm** [comment]
Sure, we will add support for call hierarchies, we need create a module for tree view at first.

**Comment by m-pilia** [comment]
Last year I made a [module for tree view](https://github.com/m-pilia/vim-yggdrasil/blob/master/autoload/yggdrasil/tree.vim) (pure VimL), you can copy it if you think it is useful (it is MIT licensed). I would love to see call hierarchies supported directly in coc.nvim.

**Comment by hoschi** [comment]
https://github.com/lambdalisue/fern.vim is a general purpose tree viewer, but in beta stage.

**Comment by vn-ki** [comment]
It's asynchronous and pure vimscript too. I too vote for fern. I beg to not reinvent the wheel like you did with coc-lists.

**Comment by chemzqm** [comment]
If you want to other plugin for tree view, you can use `CocRequest()` api then feed data to it.

**Comment by chemzqm** [comment]
It's bad idea to bind it with other vim plugin for some feature to work.

**Comment by hoschi** [comment]
> Sure, we will add support for call hierarchies, we need create a module for tree view at first.

Sorry then, I got the quoted part that you want exactly that.

**Comment by m-pilia** [comment]
> It's bad idea to bind it with other vim plugin for some feature to work.

You can copy and reuse the source I linked to implement your internal view module, if you think it can save some work. No external dependency. A copy of that code in used also inside [vim-lsp](https://github.com/prabirshrestha/vim-lsp) to visualise hierarchies [here](https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/utils/tree.vim).

> It's asynchronous and pure vimscript too. I too vote for fern. I beg to not reinvent the wheel like you did with coc-lists.

So it is the code I linked, with the difference that mine is not in alpha stage (it's used in production in two vim plugins) and it is completely standalone, it does not use Vital.

**Comment by ckipp01** [comment]
Having support for this would be great. I know in [coc-metals](https://github.com/scalameta/coc-metals#tree-view-protocol) we ended up building this in from scratch to account for the [Metals Tree View Protocol](https://scalameta.org/metals/docs/editors/tree-view-protocol.html)

**Comment by yyb196** [comment]
look forward to using this feature too, pls support it

**Comment by OmerYe** [comment]
Me too!

**Comment by ssh352** [comment]
yes really need call hierarchy thank you

**Comment by pidgeon777** [comment]
I'm also interested in a call tree viewer, too.
