### ISSUE TITLE
Notice: uncommon builtin sources will be removed from next release.

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#165]
All sources except `buffer` `around` and `file` will be extracted from coc.nvim, you need to install them as coc extension.

# Why?

* Make coc.nvim itself smaller.
* Not everyone needs them.
* Make the test easier.
* Extension can be easier to manage by `CocInstall` and `CocUninstall` command.

**Comment by chemzqm** [comment]
There is `Denite coc-extension`, in denite buffer you can do action to extension(s.)

**Comment by numbcoder** [comment]
Not everyone use Denite, maybe coc need a `CocList` like command for none Denite user?

**Comment by chemzqm** [comment]
You can build the list view by API `:call CocAction('extensionStats')` and other including `activeExtension` `deactivateExtension` `reloadExtension` `toggleExtension` `uninstallExtension`.
Coc is not going to implement another list implementation.

**Comment by chemzqm** [comment]
done
