### ISSUE TITLE
Questions on `CocHighlightText`

### ISSUE THREAD

**Issue by ywpkwon** [neoclide/coc.nvim#1650]
I'm using below to visualize the identical words (i.e., the same variables in python and c/cpp). 
```
    autocmd CursorHold * silent call CocActionAsync('highlight')
    hi CocHighlightText ctermfg=231 guifg=#ffffff ctermbg=60 guibg=#df5f87
```
This works well.

I'm wondering if I can do:
1. Highlight only twin symbols but not the current one (under cursor)
2. I had to save a file to update. Can it be updated before save (e.g., at least when entering normal mode)?
3. Can I use it in insert mode (e.g, when I move cursor to a word during in insert mode)

I would say (1) has lower priority, but I think (2), (3) must be very useful. Please give me some advice.

**Comment by ywpkwon** [comment]
I found that I can do this for insert mode.
````
    autocmd CursorHoldI * silent call CocActionAsync('highlight')
````
But still, if I'm editing a line, it doesn't recognize a word properly anymore before saving (in both insert and normal mode).

**Comment by chemzqm** [comment]
It's designed to work on normal mode only to avoid issues with conflict and performance.

**Comment by ywpkwon** [comment]
I see. But as far as I know, it properly works only when saved, isn't it? Even in normal mode, if a buffer is not saved, new strings doesn't get highlighted. Is my understanding correct?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
