### ISSUE TITLE
Neovim floating windows conflict.

### ISSUE THREAD

**Issue by kierun** [neoclide/coc.nvim#1652]
## Result from CocInfo

vim version: NVIM v0.5.0-416-g2b00d1d09
node version: v12.16.1
coc.nvim version: 0.0.76-f4400f58ef
term: screen-256color
platform: linux

## Describe the bug

The auto completion's windows are confused and one is on top of the other. This is with Python and Go.  Here are some screen shots below.

## Reproduce the bug

Open vim with a  Python or Go file, the error appears.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()
  let g:coc_global_extensions = ["coc-json",
      \ "coc-python",
      \ "coc-go"]
  ```
Now, this _shows the problem for me_, however, I am not convinced the problem is that easy to reproduce. It could be 

## Screenshots (optional)

Note that those screen shots were taken using the above minimal file…

![go](https://user-images.githubusercontent.com/3079575/76517002-643d7080-6454-11ea-934f-bbd93101ef03.png)
![python](https://user-images.githubusercontent.com/3079575/76517006-643d7080-6454-11ea-8786-da676fa52fe1.png)

**Comment by chemzqm** [comment]
You can disable floating window, https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-could-i-disable-floating-window

**Comment by kierun** [comment]
@chemzqm Thank you for the work around but shouldn't that behaviour be a bug?

**Comment by chemzqm** [comment]
@kierun it was fixed and I would suggest disable gui pum.

**Comment by kierun** [comment]
> it was fixed and I would suggest disable gui pum.

Could you kindly point me to the documentation for that?  Many thanks.
