### ISSUE TITLE
Cannot decrease snippets priority

### ISSUE THREAD

**Issue by przepompownia** [neoclide/coc.nvim#1653]
## Result from CocInfo
```
## versions

vim version: NVIM v0.5.0-dev
node version: v13.10.1
coc.nvim version: 0.0.76
term: screen-256color
platform: linux

## Messages

## Output channel: snippets

```
I tried the following settings to make priority lower (some of them does not work as probably non-compliant with schema)
```
  "coc.source.snippets.enable": false,
  "coc.source.snippets.priority": 2, 
  "coc.source.snippets-source.priority": 2,
  "snippets.priority": 3,
```
but I have still 99
```
  * vimlsp [LS] 99 vim                                                                                                                                                        
  * snippets-source [S] 99 snippets                                                                                                                                           
  * snippets [S] 99                                                                                                                                                           
  * json [LS] 99 json,jsonc                                                                                                                                                   
  * file [F] 10                                                                                                                                                               
  * buffer [B] 2                                                                                                                                                              
    around [A] 1                                                                                                                                                              
 b5, w2  +0 ~0 -0 ᚠ master  list:///sources[-] 
```
and snippets results appears on top of suggestions list.

**Comment by chemzqm** [comment]
Fixed on latest master, checkout https://github.com/neoclide/coc-snippets#options for available configurations.

**Comment by przepompownia** [comment]
Thanks!

**Comment by drop-jiarui** [comment]
> ## Result from CocInfo
> ```
> ## versions
> 
> vim version: NVIM v0.5.0-dev
> node version: v13.10.1
> coc.nvim version: 0.0.76
> term: screen-256color
> platform: linux
> 
> ## Messages
> 
> ## Output channel: snippets
> ```
> 
> I tried the following settings to make priority lower (some of them does not work as probably non-compliant with schema)
> 
> ```
>   "coc.source.snippets.enable": false,
>   "coc.source.snippets.priority": 2, 
>   "coc.source.snippets-source.priority": 2,
>   "snippets.priority": 3,
> ```
> 
> but I have still 99
> 
> ```
>   * vimlsp [LS] 99 vim                                                                                                                                                        
>   * snippets-source [S] 99 snippets                                                                                                                                           
>   * snippets [S] 99                                                                                                                                                           
>   * json [LS] 99 json,jsonc                                                                                                                                                   
>   * file [F] 10                                                                                                                                                               
>   * buffer [B] 2                                                                                                                                                              
>     around [A] 1                                                                                                                                                              
>  b5, w2  +0 ~0 -0 ᚠ master  list:///sources[-] 
> ```
> 
> and snippets results appears on top of suggestions list.

Dumb question: how do you get the list of snippets with priority. Thank you

**Comment by jrzhang12** [comment]
> ## Result from CocInfo
> ```
> ## versions
> 
> vim version: NVIM v0.5.0-dev
> node version: v13.10.1
> coc.nvim version: 0.0.76
> term: screen-256color
> platform: linux
> 
> ## Messages
> 
> ## Output channel: snippets
> ```
> 
> I tried the following settings to make priority lower (some of them does not work as probably non-compliant with schema)
> 
> ```
>   "coc.source.snippets.enable": false,
>   "coc.source.snippets.priority": 2, 
>   "coc.source.snippets-source.priority": 2,
>   "snippets.priority": 3,
> ```
> 
> but I have still 99
> 
> ```
>   * vimlsp [LS] 99 vim                                                                                                                                                        
>   * snippets-source [S] 99 snippets                                                                                                                                           
>   * snippets [S] 99                                                                                                                                                           
>   * json [LS] 99 json,jsonc                                                                                                                                                   
>   * file [F] 10                                                                                                                                                               
>   * buffer [B] 2                                                                                                                                                              
>     around [A] 1                                                                                                                                                              
>  b5, w2  +0 ~0 -0 ᚠ master  list:///sources[-] 
> ```
> 
> and snippets results appears on top of suggestions list.

Dumb question: how do you get the list of snippets with priority. Thank you!

**Comment by chemzqm** [comment]
Use `:CocList sources` command
