### ISSUE TITLE
Specific file name error

### ISSUE THREAD

**Issue by Neur1n** [neoclide/coc.nvim#1657]
## Result from CocInfo
Error: Node version  < 8.10.0, please upgrade node.js

## Describe the bug
In a python project folder, when I tried to open a `.py` file with terminal or context menu and there is a file named `node.py` existing in the same folder, an error will occur. However, if I remove the `node.py` file or open any file in this folder with Startify, no error is thrown.

## Reproduce the bug
In **Windows 10**, create a `node.py` file and put it anywhere. Open it (or the other .py file) with terminal or context menu.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/17579247/76674009-ef01a500-65e5-11ea-81b6-9dd7d24307f2.png)

**Comment by oblitum** [comment]
Possibly this is a Windows system issue? `node.py` is being interpreted as the node executable, because files in the current directory as searched first as executables to look up?

**Comment by chemzqm** [comment]
Your vim think it's node executable, should be caused by your other vim plugin

**Comment by Neur1n** [comment]
The error still occur when a minimal vimrc is used:
```vim
set nocompatible
set runtimepath^=<sensored path>\plugged\coc.nvim
filetype plugin indent on
syntax on
set hidden
```
And "Failed to start coc service" is echoed.

If the `set runtimepath` is removed, the error is gone.
