### ISSUE TITLE
E117: Unknown function: CocConfig

### ISSUE THREAD

**Issue by 3fernandez** [neoclide/coc.nvim#1658]
#### versions

vim version: NVIM v0.4.3
node version: v12.16.1
coc.nvim version: 0.0.76-2c7c3417b3
term: iTerm.app
platform: darwin

#### Messages
Error detected while processing /Users/efernandes/.config/nvim/init.vim:
line  148:
E117: Unknown function: CocConfig
line  149:
E117: Unknown function: coc#config
## Describe the bug

Unable to call coc#config. It returns a `E117: Unknown function: CocConfig` message whenever I open my NVIM.

#### Here is how I'm installing it with plug:
Plug 'neoclide/coc.nvim', {'branch': 'release'}

#### Here is how I'm invoking it inside my init.vim file:
call coc#config('elixir', {'command': g:ElixirLS.lsp, 'filetypes': ['elixir', 'eelixir']})
call coc#config('elixir.pathToElixirLS', g:ElixirLS.lsp)

I did read other related issues, tried the recommendations and still couldn't solve it. 😞

**Comment by chemzqm** [comment]
It's not function

**Comment by 3fernandez** [comment]
@chemzqm whether it's function or not, it's what it returns as an error feedback message. Can u help or not?

**Comment by chemzqm** [comment]
It's basic problem of your viml, you should learn it first, instead of waste other's time.

**Comment by oblitum** [comment]
@3fernandez you need to provide a minimal init as requested in issue template, not isolated commands.

**Comment by 3fernandez** [comment]
Hey @oblitum,

First of all, thanks for your time and the tip.

Actually, I managed to solve that issue, and now, I've stumbled into another one. 🤨


Here's the output of `:CocInfo`:

#### versions

vim version: NVIM v0.4.3
node version: v12.16.1
coc.nvim version: 0.0.76
term: iTerm.app
platform: darwin

#### Messages
[coc.nvim] Server elixir failed to start: Cannot read property 'reader' of undefined
#### Output channel: prettier

#### Output channel: elixir
[Error  - 12:57:02 PM] Starting client failed: 
TypeError: Cannot read property 'reader' of undefined
    at /../../.config/nvim/plugged/coc.nvim/lib/language-client/client.js:2363:48

#### Output channel: diagnostic-languageserver
Linter command: mix, args: ["credo","suggest","--format","flycheck","--read-from-stdin"]
stdout: 
stderr: 
match string: 
match result: null
Linter command: mix, args: ["credo","suggest","--format","flycheck","--read-from-stdin"]
stdout: 
stderr: 
match string: 
match result: null
