### ISSUE TITLE
Provide presentation improvements for CocInfo output

### ISSUE THREAD

**Issue by przepompownia** [neoclide/coc.nvim#1659]
The verbose output from `CocInfo` contains lots of large, but disjoint parts. Browsing them would be easier with some improvements. 

- Each part would have a format that allows to create a fold from it and (depending on settings) keep the fold closed by default. Foldtext would be used to present short info (e.g. `[14:31:31] req textDocument/completion`). 
- JSON body contents would have syntax markers. It would be then highlighted and folded (having `foldmethod=syntax`) assumming that syntax folding does not conflict with the one mentioned above.

https://vim.fandom.com/wiki/Different_syntax_highlighting_within_regions_of_a_file

**Comment by chemzqm** [comment]
No, additional markers would make https://microsoft.github.io/language-server-protocol/inspector/ not work at all.
