### ISSUE TITLE
Can't Build The project

### ISSUE THREAD

**Issue by annata83** [neoclide/coc.nvim#1661]
LOG:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'prepare' ]
2 info using npm@6.14.2
3 info using node@v13.11.0
4 verbose run-script [ 'prepare' ]
5 info lifecycle coc-tsserver@1.4.11~prepare: coc-tsserver@1.4.11
6 verbose lifecycle coc-tsserver@1.4.11~prepare: unsafe-perm in lifecycle true
7 verbose lifecycle coc-tsserver@1.4.11~prepare: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/niko/coding/coc-tsserver/node_modules/.bin:/home/niko/.zplugin/polaris/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/niko/.scripts/cron:/home/niko/.scripts/tools:/home/niko/.scripts/apps/fzf:/home/niko/.scripts/apps/tmux:/home/niko/.scripts/apps/dunst:/home/niko/.scripts/apps/taskwarrior:/home/niko/.scripts/apps/polybar/system-bluetooth-bluetoothctl/screenshots:/home/niko/.scripts/apps/polybar/system-bluetooth-bluetoothctl:/home/niko/.scripts/apps/polybar/info-redshift-temp/screenshots:/home/niko/.scripts/apps/polybar/info-redshift-temp:/home/niko/.scripts/apps/polybar/info-trash/screenshots:/home/niko/.scripts/apps/polybar/info-trash:/home/niko/.scripts/apps/polybar:/home/niko/.scripts/apps:/home/niko/.scripts/i3cmds:/home/niko/.scripts/:/home/niko/.npm-global/bin:/home/niko/.local/bin/
8 verbose lifecycle coc-tsserver@1.4.11~prepare: CWD: /home/niko/coding/coc-tsserver
9 silly lifecycle coc-tsserver@1.4.11~prepare: Args: [ '-c', 'npx npm-run-all clean build' ]
10 silly lifecycle coc-tsserver@1.4.11~prepare: Returned: code: 1  signal: null
11 info lifecycle coc-tsserver@1.4.11~prepare: Failed to exec prepare script
12 verbose stack Error: coc-tsserver@1.4.11 prepare: `npx npm-run-all clean build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
12 verbose stack     at EventEmitter.emit (events.js:315:20)
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1026:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose pkgid coc-tsserver@1.4.11
14 verbose cwd /home/niko/coding/coc-tsserver
15 verbose Linux 5.5.8-arch1-1
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "prepare"
17 verbose node v13.11.0
18 verbose npm  v6.14.2
19 error code ELIFECYCLE
20 error errno 1
21 error coc-tsserver@1.4.11 prepare: `npx npm-run-all clean build`
21 error Exit status 1
22 error Failed at the coc-tsserver@1.4.11 prepare script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by chemzqm** [comment]
Your npm is too old.
