### ISSUE TITLE
Loading coc.nvim blocks UI for a bit

### ISSUE THREAD

**Issue by pablopunk** [neoclide/coc.nvim#1662]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v10.18.1
coc.nvim version: 0.0.74-bcdd8cdfca
term: iTerm.app
platform: darwin

## Messages

## Output channel: prettier


## Output channel: snippets


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /Users/pablopunk/src/superdesk-client-core
resolved root: /Users/pablopunk/src/superdesk-client-core
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Output channel: highlight

[Info  - 2:41:21 PM] Highlight server running in node v10.18.1
```

## Describe the bug

When I open vim, I start typing some command and then I notice the UI is blocked (due to coc.nvim being loaded) and it's like that for a split second. Not a big deal but kind of annoying sometimes (for example when I start vim and immediately use CtrlP).

## Reproduce the bug

- Using vim-plug, I create a file `mini.vim`:

  ```vim
  set nocompatible
  filetype plugin indent on
  syntax on
  set ttyfast
  set lazyredraw
  set hidden
  set shortmess+=c
  set updatetime=300
  set signcolumn=yes

  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Immediately start typing something like `:aaaaaaaaaaaaaaa`, you'll notice that the UI is blocked. [See the screencast here](https://asciinema.org/a/WOJ16kWm0PTTT4fjjuvx42xMr).

**Comment by chemzqm** [comment]
There is a bit of delay for screen redraw, your vim is blocked by your viml not coc.nvim, you can profile it https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-could-i-profile-vim

**Comment by chemzqm** [comment]
Or maybe your computer is two slow, it's less than 100ms for me.

**Comment by pablopunk** [comment]
@chemzqm it's weird that I'm having this issue tho, cause I have the new Macbook Pro 16 inches (quite powerful). Maybe node or something is taking a while to start? I'll see what I can find and I'll update this issue 👍

**Comment by pablopunk** [comment]
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   0.372354   0.000017  provider#pythonx#Detect()
    1   0.372337   0.000180  provider#pythonx#DetectByModule()
    4   0.372100   0.040460  provider#pythonx#CheckForModule()
    3   0.331640   0.019976  <SNR>82_import_module()
    1   0.013933   0.000028  <SNR>58_SyncAutocmd()
    1   0.013905   0.000024  coc#rpc#request()
    1   0.013875   0.013843  <SNR>78_request()
    1   0.005193   0.000865  coc#rpc#start_server()
    1   0.001690   0.000666  <SNR>53_mergelists()
    1   0.001359             <SNR>78_start()
    1   0.000848   0.000071  coc#util#vim_info()
    1   0.000764   0.000409  ctrlp#mrufiles#cachefile()
    1   0.000702             coc#util#version()
    1   0.000558   0.000034  <SNR>53_savetofile()
    1   0.000524   0.000494  ctrlp#utils#writecache()
    3   0.000480   0.000116  <SNR>44_CursorHoldUpdate()
    4   0.000441   0.000112  <SNR>58_Autocmd()
    1   0.000429             coc#rpc#stop()
    3   0.000363   0.000051  227()
    2   0.000329   0.000070  coc#rpc#notify()
```

Maybe using `pyenv` is a bottle neck for detecting python provider?

**Comment by chemzqm** [comment]
The server get started in seperate progress, It won't block your vim.

**Comment by pablopunk** [comment]
I uninstalled `pyenv` and reinstalled python from source and it's definitely better. That was for sure the issue (or at least part of it). Thanks for checking anyway @chemzqm

**Comment by chemzqm** [comment]
You should use something like
```
let g:python_host_prog = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'
```
to avoid python detect.

**Comment by pablopunk** [comment]
Definitely better with those options, thanks!
