### ISSUE TITLE
javascript file not found, please compile the code or use release branch

### ISSUE THREAD

**Issue by smile-kindred** [neoclide/coc.nvim#1664]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
How do you install coc.nvim? Checkout https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim
