### ISSUE TITLE
option to show diagnostics virtual text only on current line

### ISSUE THREAD

**Issue by Blacksuan19** [neoclide/coc.nvim#1667]
currently when there are more than one diagnostic all of them are shown on virtual text (if enabled) which makes the whole file looks messy and confusing  

![2020-03-18_16-42](https://user-images.githubusercontent.com/10248473/76941702-74af8880-6937-11ea-825b-8c98d5258b38.png)

I suggest it could be done the way ALE does it, the symbol is shown in the sign column but the virtual text only appears when you are on that specific line

![2020-02-17_07-16_1](https://user-images.githubusercontent.com/10248473/76942334-89d8e700-6938-11ea-8774-45d930309aab.png)
![2020-02-17_07-16](https://user-images.githubusercontent.com/10248473/76942337-8ba2aa80-6938-11ea-989f-6ca0cd67253f.png)

it could be an option, something like diagnostic.virtualTextcurrentLineOnly (could be shorter)

**Comment by chemzqm** [comment]
I would prefer floating window instead of virtual text.

**Comment by oblitum** [comment]
> I would prefer floating window instead of virtual.

Same here, but isn't that being provided already? In that case, then this feature-request is specific for virtualtext behavior.

**Comment by Blacksuan19** [comment]
> then this feature-request is specific for virtualtext behavior.

yes that is what am going for, virtual text makes more sense to me than floating windows

**Comment by fannheyward** [comment]
Does this work for your expected? 

```
"diagnostic.virtualText": false,
"diagnostic.checkCurrentLine": true,
```

Disable diagnostic on virtual text, and when your cursor line has diagnostic, will show in floating window.

**Comment by Blacksuan19** [comment]
@fannheyward This works fine 
The whole point of this is having virtual text per line like ale

**Comment by oblitum** [comment]
@chemzqm Shouldn't this be an option instead of hard-coded?

**Comment by chemzqm** [comment]
I prefer not

**Comment by Avi-D-coder** [comment]
Please don't hard code this. I use virtual text diagnostics extensively.
This breaks my work flow. I floating window diagnostics cover code so I only trigger them when I need to see the whole diagnostic (rarely).

**Comment by Avi-D-coder** [comment]
I'm sending PR

**Comment by expipiplus1** [comment]
@Avi-D-coder Did you open a PR for this?

**Comment by malukenho** [comment]
Is there a way to configure it to show all errors once again?

**Comment by Avi-D-coder** [comment]
@malukenho Does `"diagnostic.virtualTextCurrentLineOnly": false,` not work for you?

**Comment by malukenho** [comment]
Thanks @Avi-D-coder! That worked.

**Comment by vmnog** [comment]
Just add the below code into your `coc-settings.json` (do :CocConfig to open the file in nvim, in case you don't know where the file is)
```
{
  "diagnostic.virtualText": true,
  "diagnostic.virtualTextCurrentLineOnly": false
}
