### ISSUE TITLE
Questions regarding the autoformatting and auto pairs

### ISSUE THREAD

**Issue by stokhos** [neoclide/coc.nvim#1669]
Hi there

It seems that coc supports the auto-formatting and auto-pairs, but I'm not sure how to do it correctly, it there any examples  or documents to look at? 

Best regards
Stokhos

**Comment by fannheyward** [comment]
Formatting feature requires LS to support. For example you are using Python, you need to install `coc-python` for Python support.

You can use `coc-pairs` for auto-pairs support. Checkout [Using coc extensions](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions).

**Comment by chemzqm** [comment]
You can use `coc-pairs` or other vim plugin for auto pairs, it's up to you.

**Comment by stokhos** [comment]
@fannheyward @chemzqm Ok didn't know there is coc-pairs. I'm learning C++ now, and a lot of things i dont know. Please correct me if I'm wrong. According clang website, clang-format is part of clang, which means I'm able to use it with coc-clang, but I'm not sure how to set it up. Is there any places that I can look at?

Best regards
Stokhos
