### ISSUE TITLE
Offline install for Windows?

### ISSUE THREAD

**Issue by gerroon** [neoclide/coc.nvim#167]
Hi

Is it possible to provide a fully offline install of this addon for Vim on Windows 10 x64 including all that node etc stuff which not everyone knows and understands? 

thanks

**Comment by chemzqm** [comment]
There is release for windows https://github.com/neoclide/coc.nvim/releases, you can just download the release and unzip the exe to build folder inside coc.nvim, that's just what `coc#util#install()` doing.

**Comment by gerroon** [comment]
Thanks, I will try it

**Comment by SebastianBehrens** [comment]
@chemzqm 
I think you are no longer including binaries in the releases. Could you please give an updated set of instructions of how to set up coc.vim on an offline windows environment.

I have tried all suggestions of the past issues that mention "offline install" but I am not there yet, unfortunately.

**Comment by fannheyward** [comment]
@SebastianBehrens do you mean you don't have a way to install node too?

For offline install:

1. you need to have node installed already
2. download coc.nvim release branch, save it to your vim runtime path
3. for extensions, some extensions needs to install dependencies from npmjs. You can install it from a _online_ env, then copy them to extension path `~/AppData/Local/coc/extensions`
4. for language server, you need to install them by yourself.

**Comment by SebastianBehrens** [comment]
That worked. Thank you!
