### ISSUE TITLE
[coc.nvim]extension XXXXX doesn't contain main file ~/.vim/bundle/coc-cmake/lib/index.js.

### ISSUE THREAD

**Issue by mellery451** [neoclide/coc.nvim#1670]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v13.11.0
coc.nvim version: 0.0.77-b7a597f7ae
term: tmux-256color
platform: linux
```

## Describe the bug
always get messages at startup:

```
[coc.nvim]extension "coc-json" doesn't contain main file ~/.vim/bundle/coc-json/lib/index.js.
[coc.nvim]extension "coc-highlight" doesn't contain main file ~/.vim/bundle/coc-highlight/lib/index.js.
[coc.nvim]extension "coc-snippets" doesn't contain main file ~/.vim/bundle/coc-snippets/lib/index.js.
[coc.nvim]extension "coc-cmake" doesn't contain main file ~/.vim/bundle/coc-cmake/lib/index.js.
[coc.nvim]extension "coc-clangd" doesn't contain main file ~/.vim/bundle/coc-clangd/lib/index.js.
```

## Reproduce the bug

messages appear at startup. Are plugins no longer able to be installed using a plugin manager ?

- Create file `mini.vim` with：

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/bundle')
  Plug 'neoclide/coc-json'
  Plug 'neoclide/coc-snippets'
  Plug 'neoclide/coc-highlight'
  Plug 'voldikss/coc-cmake'
  Plug 'clangd/coc-clangd'
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'jackguo380/vim-lsp-cxx-highlight'
call plug#end()
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by mellery451** [comment]
if I comment out the `Plug` statements and use `:CocInstall`, it works fine...so it seems like alternate plugin managers are not really supported anymore.

**Comment by fannheyward** [comment]
You are using the wrong way to install extensions. Checkout wiki https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#install-extensions and https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension

**Comment by chemzqm** [comment]
@mellery451 for extensions using typescript, you have to build them yourself when using plugin manager of vim.

**Comment by mellery451** [comment]
@fannheyward: if my example is the "wrong way", what is the right way? I had previously read those links you mention, but it's not clear what specifically is wrong about my Plug statements. Can you please clarify, preferably with the correct vim-plug syntax for managing these plugins?

@chemzqm: I don't know how to "build" these extensions - can you point to docs with build instructions?

**Comment by fannheyward** [comment]
Do you have check https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension, you can use vim-plug to install extensions. Something like this:

> Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile'}

**Comment by mellery451** [comment]
yes, I read that. So, you are saying that the extra `yarn install --frozen-lockfile` is required? If so, is it required for all plugins, or just some? Is there somewhere each plugin documents its own build/install requirements?

**Comment by fannheyward** [comment]
The recommend way to install extensions is by `:CocInstall`. If you prefer to use vim-plug, you need to use `yarn` to build them.

**Comment by mellery451** [comment]
I understand - thanks for the info. I share my init.vim across several machines and it's easier if I can use one plugin manager instead of two (that is my use-case)

**Comment by fannheyward** [comment]
Checkout `:h g:coc_global_extensions`. Something like this:

```
let g:coc_global_extensions = [
      \'coc-clangd',
      \'coc-json'
      \]
```
