### ISSUE TITLE
Unable to send a custom notification to `ccls`

### ISSUE THREAD

**Issue by randrej** [neoclide/coc.nvim#1673]
## versions
    
    vim version: NVIM v0.4.3
    node version: v13.11.0
    coc.nvim version: 0.0.77-7a4f56eb9e
    term: alacritty
    platform: linux
    
    ## Output channel: prettier
    
    
    ## Output channel: snippets
    
    [Error 3/22/2020] parser error: 16
    [Error 3/22/2020] parser error: 16
    
    ## Output channel: languageserver.ccls
    
    10:12:36 ccls           initialize.cc:262 I initialize in directory /home/andrej/Desktop/coc_test with uri file:///home/andrej/Desktop/coc_test
    10:12:36 ccls           initialize.cc:285 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":".ccls-cache","format":"binary","hierarchicalPath":false,"retainInMemory":1},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":[],"pathMappings":[],"resourceDir":""},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":true,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
    10:12:36 ccls           initialize.cc:314 I use -resource-dir=/usr/lib/clang/9.0.1
    10:12:36 ccls           initialize.cc:347 I workspace folder: /home/andrej/Desktop/coc_test/
    10:12:36 ccls           initialize.cc:372 I start 8 indexers
    10:12:36 ccls           initialize.cc:380 I dispatch initial index requests
    10:12:36 ccls             pipeline.cc:474 I loaded project. Refresh semantic highlight for all working file.
    10:12:36 preamble     sema_manager.cc:732 I create session for /home/andrej/Desktop/coc_test/main.c
    10:12:36 indexer1         pipeline.cc:290 I load cache for /home/andrej/Desktop/coc_test/main.c

## Describe the bug

I can't seem to send a custom notification to a Language Server. In my specific case, if I send a custom notification that `ccls` expects, like so:

```vim
:call CocAction('runCommand', '$ccls/reload')
```

I just get this error
```
[coc.nvim] Command: $ccls/reload not found
```

I've asked (MaskRay/ccls#591) on the `ccls` repo and they say it's a `coc.nvim` issue. Am I doing something wrong? Are notifications supposed to be send in a different way or is it a bug?

## Reproduce the bug

The issue is reproducible with the default `mini.vim`:

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

**Comment by fannheyward** [comment]
Try `call CocRequest('ccls', '$ccls/reload')`.

**Comment by randrej** [comment]
This also results in an error:

    Error on request (sendRequest): Vim(return):Error invoking 'sendRequest' on channel 3 (coc):
    unknown request $ccls/reload
