### ISSUE TITLE
How to add types to completion in CoC and tssserver

### ISSUE THREAD

**Issue by vegerot** [neoclide/coc.nvim#1676]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I start typing, get some IntelliSense suggestions, but none of them have types UNTIL I hover over a specific one.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/5297725/77266284-6e8e1480-6c75-11ea-962c-a6f3863863b8.png)
instead of 
![image](https://user-images.githubusercontent.com/5297725/77266301-7b126d00-6c75-11ea-8c95-ff018cd34b72.png)

**Describe alternatives you've considered**
Just tab cycling through everything, switching to YCM
**Additional context**

**Comment by chemzqm** [comment]
Please don't create dulpicate issue.
