### ISSUE TITLE
how to change the diagnosign in lightline?

### ISSUE THREAD

**Issue by physicistgeng** [neoclide/coc.nvim#1680]
how to change the diagnosign in lightline?
<img width="516" alt="截屏2020-03-24下午7 06 08" src="https://user-images.githubusercontent.com/50125230/77418967-9e1e5780-6e02-11ea-8cc5-374eb7e56c16.png">

**Comment by chemzqm** [comment]
Checkout `:h coc-status-manual`

**Comment by physicistgeng** [comment]
fix this by let g:coc_status_error_sign = 'E:'

**Comment by unphased** [comment]
None of these suggestions work. I want the feedback (using lightline, coc#status works in it), however, on the mac these characters use up two widths, causing statusline length calculations to be off by one, and completely breaking neovim rendering.

I will note that regular vim does not break as badly here. This is sorta neovim specific. 

But we need a way to configure this...

**Comment by chemzqm** [comment]
You can create function yourself by make use exported variable

**Comment by unphased** [comment]
I think i complained too soon, sorry about that. It's a bit tough to really get down to what's causing the problem. I will test more without the status showing and also try to make a basic custom status function.
