### ISSUE TITLE
[Feature request] Get coc and extension options

### ISSUE THREAD

**Issue by yutakatay** [neoclide/coc.nvim#1682]
**Is your feature request related to a problem? Please describe.**

I always check GitHub extension's repository or `~/.config/coc/extensions/node_modules/xxx/package.json` when I'm looking for options in coc-settings.json. It contains not only the options I set, but also default options and option descriptions.
In Vim, you can find most options and settings using `:help`
I want such an interface in Coc.

**Describe the solution you'd like**

I think it is better to add options to CocList. Output includes option name, description, and default value.

**Describe alternatives you've considered**

coc-options extension

**Comment by Ferdi265** [comment]
you can install `coc-json` and it will give you autocompletion of options in `coc-settings.json`. (At least for me it enables autocompletion there)

That even contains single-sentence descriptions of what the option does, and the default value is autocompleted

**Comment by yutakatay** [comment]
Yes I know too.

It's really good when typing. But it is not useful when searching for setting properties, I think.

**Comment by yutakatay** [comment]
Thank you very much! 
I'm very happy :smiley:
