### ISSUE TITLE
Create method to get single preference

### ISSUE THREAD

**Issue by przepompownia** [neoclide/coc.nvim#1683]
For example, for some filetypes I would like to extend the list of root patterns obtained from configuration instead of creating it from scratch.

I did not find any function to query configuration (at least from the client side) like `coc#config#get('coc.preferences.rootPatterns')`.

**Comment by chemzqm** [comment]
Use `b:coc_root_patterns` for custmize rootPatterns https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

**Comment by chemzqm** [comment]
Try `:echo coc#util#root_patterns()` for rootPatterns of current project.

**Comment by przepompownia** [comment]
Yes, my goal was to use `autocmd filetype` to change `b:coc_root_patterns` using such missing function. 

Thanks for introducing `coc#util#root_patterns()`. The second, `coc#util#get_config()` does not work, I'm going to create a new issue for it.

**Comment by przepompownia** [comment]
I have a git hook that rebuilds the project and it was not executed so the new method did not not have a chance to exist.
