### ISSUE TITLE
coc prompts an error hint

### ISSUE THREAD

**Issue by blithefeng** [neoclide/coc.nvim#1685]
## Result from CocInfo

coc.nvim service not started, checking environment...Start on startup is disabled, try :CocStart

## Describe the bug

I have a project and inside this project there is a directory named "tmp". When I open the files in dir "tmp" outside the dir, like `vim ~/project/tmp/tmp.go`, It works right. But when I open file in the dir "tmp", like `vim tmp.go`. It prompts an error and coc doesn't start.  

![屏幕快照 2020-03-26 下午7 05 25](https://user-images.githubusercontent.com/26022296/77640471-698ed500-6f95-11ea-9c4d-a8dc2cd0ea1c.png)

The error message is raising from `coc.nvim/autoload/coc/util.vim -> coc#util#job_command`. So I set the `g:coc_node_path = "/usr/local/bin/node"`. The problem is gone.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

I can't reproduce it when using min.vim. I installed coc.nvim through vim-plug  and OS is Mac. The configuration of coc.nvim is copied from README.

## Screenshots (optional)

- open file in "tmp" dir
![屏幕快照 2020-03-26 下午7 05 25](https://user-images.githubusercontent.com/26022296/77641259-b921d080-6f96-11ea-9c00-952ffd51fb64.png)

- cocinfo
![屏幕快照 2020-03-26 下午7 06 24](https://user-images.githubusercontent.com/26022296/77641280-c343cf00-6f96-11ea-8bf4-a69cc84a15a2.png)

**Comment by chemzqm** [comment]
Try `:echo expand(get(g:, 'coc_node_path', 'node'))`

**Comment by MrQubo** [comment]
I have the same error.
For me it's caused by having `*/tmp/*` in `&wildignore`.
Could the issue be reopened?

[This code](https://github.com/neoclide/coc.nvim/blob/d547144/autoload/coc/util.vim#L318) causes the problem. I propose changing that line to:
```
if (has_key(g:, 'coc_node_path'))
  let node = expand(g:coc_node_path)
else
  let node = 'node'
endif
```
