### ISSUE TITLE
coc#util#root_patterns() shows `buffer` part from another buffer

### ISSUE THREAD

**Issue by przepompownia** [neoclide/coc.nvim#1693]
I wanted to change my root patterns for PHP as in #1683.

I have open PHP file, for which I have `set b:coc_root_patterns`:
```vim
augroup CocRootPatterns
  autocmd!
  autocmd FileType php let b:coc_root_patterns = [
        \ "composer.json",
        \ "extensions.json",
        \ ".git",
        \ ".hg",
        \ ".projections.json"
        \ ]
augroup end
```
then I open and switch to the new buffer with the vim file containing the above definition. The result of calling `coc#util#root_patterns()['buffer'])` on the vim file is other than `b:coc_root_patterns`:
```vim
let v:errors=[] | if 1 == assert_equal(get(b:, 'coc_root_patterns', []), coc#util#root_patterns()['buffer']) | echoerr v:errors | endif
['Expected [] but got [''composer.json'', ''extensions.json'', ''.git'', ''.hg'', ''.projections.json'']']  
```
It contains the buffer settings for `php` filetype. 

After start nvim again with each of both files separately the error does not occur. 

Similarily, opening both the above files in the opposite order gives
```
['Expected [''composer.json'', ''extensions.json'', ''.git'', ''.hg'', ''.projections.json''] but got []']
```

**Comment by chemzqm** [comment]
It's expected

**Comment by przepompownia** [comment]
Why the difference between `coc#util#root_patterns()['buffer']` and `b:coc_root_patterns` can be expected (i.e. root pattern can `composer.json` appear in `buffer` section for *.vim file even if it was not set for it)?
