### ISSUE TITLE
Consider adding Github Sponsors

### ISSUE THREAD

**Issue by JoshMcguigan** [neoclide/coc.nvim#1695]
**Is your feature request related to a problem? Please describe.**

I'm a very happy user of `coc.nvim` and I'd like to contribute to the funding of its development.

**Describe the solution you'd like**

I'd like to contribute to the funding of `coc.nvim` via [GitHub Sponsors](https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors).

**Describe alternatives you've considered**

I've reviewed the existing funding options, but they all require providing my billing information to a third party, which I'd prefer not to do. In addition, I'd prefer to manage my open source sponsorships in a single place. Since GitHub already has my billing informatoin, and I already review a monthly invoice from GitHub, contributing to a project via `GitHub Sponsors` feels like the lowest friction option.

Thank you so much for the work you've done on `coc.nvim` :heart:

**Comment by chemzqm** [comment]
The problem is it doesn't have support for China.

**Comment by JoshMcguigan** [comment]
> The problem is it doesn't have support for China.

Thanks for the response. I hope GitHub Sponsors gains support for China soon, but in the mean time I made a one-time contribution via PayPal.

Thanks again for `coc.nvim`!

**Comment by svanharmelen** [comment]
Is it still not possible to support through GitHub Sponsors? I too prefer to sponsor directly through Github instead of through Patreon or Open Collective. Thanks!
