### ISSUE TITLE
Duplicate entries in auto completion window.

### ISSUE THREAD

**Issue by DasOhmoff** [neoclide/coc.nvim#1698]
Hello, first of all, thank you for this awesome plugin, it is really great <3 .

I have a issue when auto completing with coc. Basically, coc shows multiple entries for the same item in the auto completion window (for example it shows multiple times the same member in the window).

For example: 
![image](https://user-images.githubusercontent.com/16063186/77854979-d56b7a80-71ed-11ea-8fe5-36726fb19eba.png)

How can I change this behavior so that it shows me each item only a single time?

**Comment by fannheyward** [comment]
Items end with `[OS]` are not provided by coc. Checkout other plugins.

**Comment by chemzqm** [comment]
Use `:CocList sources` to check activated sources.

**Comment by Congee** [comment]
How can I remove duplicates like this?
![image](https://user-images.githubusercontent.com/2083950/79986493-20d61900-847a-11ea-8ce9-d5332bc655ed.png)

**Comment by Congee** [comment]
Got it `{ "suggest.removeDuplicateItems": true, }`
