### ISSUE TITLE
Can't configure vue-language-server 

### ISSUE THREAD

**Issue by deathmaz** [neoclide/coc.nvim#17]
Hi, I can't make coc to work with vue-language-server
Here the content of my `coc-settings.json`:
```json
{
    "languageserver" : {
        "vue": {
            "command": "vls",
            "filetypes": ["vue"]
        }
    }
}
```
```
$ which vls 
 /usr/bin/vls
```
```
$ nvim -v
NVIM v0.3.1
```
when i open `.vue` file i have this in `:messages`
```
[coc.nvim] Executable vls not found                                                                                                                                                            
[coc.nvim] Service init error: Cannot read property 'catch' of undefined                                                                                                                       
[coc.nvim] service stylelint started                                                                                                                                                           
Press ENTER or type command to continue                                                                                                                                                        
```
Thank you for your work and help.

EDIT: vls works fine with deoplete and https://github.com/autozimu/LanguageClient-neovim

**Comment by chemzqm** [comment]
@deathmaz What the result when you run `:echo executable('vls')` in vim?

Looks like `vls` can't be found on $PATH,  you can change command to `/usr/bin/vls`

**Comment by deathmaz** [comment]
`:echo executable('vls')` return `1`
I already tried before `/usr/bin/vls` as an argument for `command` the result is the same as previous

**Comment by chemzqm** [comment]
I'm looking into it.

**Comment by chemzqm** [comment]
I can fix this, but vls read some configuration from unknown variable.

**Comment by chemzqm** [comment]
It's not reading configuration from `initializationOptions.config` which is not standard and it's not checking the existence of variable.

**Comment by chemzqm** [comment]
@deathmaz You need this
```
    "vue": {
      "command": "vls",
      "args": [],
      "filetypes": ["vue"],
      "initializationOptions": {
        "config": {
          "html": {
            "suggest": true
          },
          "vetur": {
            "validation": {}
          }
        }
      }
    }
```
in `languageserver` section for vls to work.

**Comment by deathmaz** [comment]
is it intended that after i opened `.vue` file nvim opens vertical split with the following content 
```
Vetur initialized
[Error - 12:58:51 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'vetur' of undefined
```
?

**Comment by deathmaz** [comment]
though the vls itself seems works fine

**Comment by chemzqm** [comment]
@deathmaz That's another issue, I have update the configuration.

Now you can use
```
    "vue": {
      "command": "vls",
      "args": [],
      "configSection": "languageserver.vue.initializationOptions.config",
      "filetypes": ["vue"],
      "initializationOptions": {
        "config": {
          "html": {
            "suggest": true
          },
          "vetur": {
            "validation": {}
          }
        }
      }
    }
```
for vls, it's reading configuration from wired position.

**Comment by deathmaz** [comment]
Hm, i still have the same error

**Comment by chemzqm** [comment]
Run `git pull` and then `yarn install`, restart neovim should be fine.

**Comment by chemzqm** [comment]
I should provide a vim command for user to upgrade coc.

**Comment by deathmaz** [comment]
i'm using vim-plug, so `:PlugUpdate` works fine

**Comment by deathmaz** [comment]
The issue has gone, everything woks fine. Thank you very much for the help! Btw autocompletion in you plugin works super fast compared to what i had in deoplete.

**Comment by iamcco** [comment]
it still doesn't work for me

![image](https://user-images.githubusercontent.com/5492542/43072023-35511152-8ea7-11e8-9ba8-450be2c14b04.png)

coc-settings.json:

```json
{
    "languageserver": {
        "sh": {
            "command": "bash-language-server",
            "args": ["start", "--stdio"],
            "filetypes": ["sh"],
            "cwd": "./",
            "initializationOptions": {},
            "settings": {}
        },
        "dart": {
            "command": "dart_language_server",
            "args": [],
            "filetypes": ["dart"],
            "cwd": "./lib",
            "initializationOptions": {},
            "settings": {}
        },
        "vue": {
            "command": "vls",
            "args": [],
            "configSection": "languageserver.vue.initializationOptions.config",
            "filetypes": ["vue"],
            "initializationOptions": {
                "config": {
                    "html": {
                        "suggest": true
                    },
                    "vetur": {
                        "validation": {}
                    }
                }
            }
        }
    }
}
// vim:ft=jsonc
```

**Comment by chemzqm** [comment]
@iamcco add `"completion:{}"` below `validation` should do the trick.

**Comment by chemzqm** [comment]
You can have full configuration here `https://github.com/vuejs/vetur/blob/master/package.json#L131`

**Comment by iamcco** [comment]
it works well now, thanks

**Comment by chemzqm** [comment]
I'm going to add vetur to extensions, it's easier for configuration while have same features as in VSCode.

**Comment by iamcco** [comment]
i update to latest master and  it seems that the vetur extensions doesn't work for me.

when i edit the test.vue file the cpu raise to 100%.

<img width="498" alt="2018-07-23 9 18 59" src="https://user-images.githubusercontent.com/5492542/43078800-0b5c7d2a-8ebe-11e8-80fe-11982801a7a9.png">

<img width="588" alt="2018-07-23 9 19 37" src="https://user-images.githubusercontent.com/5492542/43078830-2192705e-8ebe-11e8-8452-3f93081af7a4.png">

**Comment by chemzqm** [comment]
@iamcco have you installed watchman?

**Comment by iamcco** [comment]
i had installed watchman and it works well if the work directory is not the home directory.

**Comment by chemzqm** [comment]
It get sucks when there're too many files in the directory, I have exclude watching for home on my side.
