### ISSUE TITLE
let g:coc_snippet_next = '<Tab>' break accept completion with '<Tab>'

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc.nvim#170]
**Describe the bug**
I use tab to accept completion with this config:

```sh
" Remap for expand with Tab
let g:user_emmet_leader_key = '<A-e>'
let g:user_emmet_expandabbr_key = '<A-x><A-e>'

let g:closetag_filenames = '*.html,*.jsx,*.tsx'
let g:closetag_xhtml_filenames = '*.xhtml,*.jsx,*.tsx'
let g:closetag_emptyTags_caseSensitive = 1
let g:closetag_shortcut = '>'
let g:closetag_close_shortcut = '<leader>>'

let g:coc_snippet_next = '<Tab>'
let g:coc_snippet_prev = '<S-Tab>'

" Close preview window after completion is done
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif

" Use <Tab> for confirm completion.
" Coc only does snippet and additional edit on confirm.
imap <silent><expr> <Tab> <SID>expand()

function! s:expand()
  if pumvisible()
    return "\<C-y>"
  endif
  let col = col('.') - 1
  if !col || getline('.')[col - 1]  =~# '\s'
    return "\<Tab>"
  endif
  return "\<A-x>\<A-e>"
endfunction

" Use <c-c> for trigger completion.
inoremap <silent><expr> <C-c> coc#refresh()

" Use <C-x><C-o> to complete 'word', 'emoji' and 'include' sources
imap <silent> <C-x><C-o> <Plug>(coc-complete-custom)

" Use `[c` and `]c` for navigate diagnostics
nmap <silent> [c <Plug>(coc-diagnostic-prev)
nmap <silent> ]c <Plug>(coc-diagnostic-next)

" Remap keys for goto
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use gh for show documentation in preview window
nnoremap <silent> gh :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if &filetype == 'vim'
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Show signature help while editing
autocmd CursorHoldI * silent! call CocAction('showSignatureHelp')

" Highlight symbol under cursor on CursorHold
autocmd CursorHold * silent call CocActionAsync('highlight')

" Remap for rename current word
nmap <F2> <Plug>(coc-rename)

" Use `:CocFold` for fold current buffer
command! -nargs=? CocFold :call CocAction('fold', <f-args>)

```

It works as expected when I do not set `l g:coc_snippet_next='<tab>'`.
But if I don't set it, I can not go to the next placeholder in the expanded snippet with `<tab>`

**Expected behavior**

Use `<tab>` to accept completion or go to next placeholder in a snippet should work.

**Screenshots**

![nov-23-2018 22-53-39](https://user-images.githubusercontent.com/22189661/48946966-d560c800-ef72-11e8-8564-bf5ad5961842.gif)

**Desktop (please complete the following information):**
 - Terminal: alacritty
 - Version: 0.2.3

**Additional context**

**Comment by chemzqm** [comment]
It's because mapping for snippet jump is buffer local so it has higher priority, but what you want is the map for completion have higher priority than jump.
Coc could add an option to make it possible, something like `coc.preferences.preferCompleteThanJump`

**Comment by sandangel** [comment]
hi @chemzqm, thanks for your quick response. is there any way we can set a condition for jump in the config like only jump `if !pumvisible()` or in selection mode?

**Comment by chemzqm** [comment]
You can't, since coc create snippet mapping for you.

**Comment by chemzqm** [comment]
Use `"coc.preferences.preferCompleteThanJumpPlaceholder":true`

**Comment by sandangel** [comment]
@chemzqm this is not fixed. When jump to the next placeholder, typing some text, the jump still has high priority over the completion

![nov-24-2018 11-08-26](https://user-images.githubusercontent.com/22189661/48963606-5fdc1280-efd9-11e8-895b-df7119bce8b3.gif)

**Comment by chemzqm** [comment]
OK, I got the problem.

**Comment by sandangel** [comment]
hi @chemzqm thank you for quick fix. but I still see the problem. I have already used the latest commit from master branch.

![nov-25-2018 00-40-38](https://user-images.githubusercontent.com/22189661/48970053-c4838580-f04a-11e8-9338-654dfa41e9ea.gif)

**Comment by chemzqm** [comment]
I've tested it works as expected. Make sure you have:
```
  "coc.preferences.preferCompleteThanJumpPlaceholder": true,
```
in your coc-settings.json

to make sure coc using source code add `  let g:coc_force_debug = 1` in your .vimrc.

**Comment by sandangel** [comment]
Thank you, I rebuild it from source and it works as expected. thank you very much ^^

**Comment by sandangel** [comment]
hi @chemzqm this [commit](https://github.com/fannheyward/coc.nvim/commit/74e4a69fbbf17dfc2e38fbd6b83bb8d2566c262d) is not included in master so the config is not working, could you please review that?
