### ISSUE TITLE
vim-plug PlugUpdate "refusing to merge unrelated histories" error

### ISSUE THREAD

**Issue by elentok** [neoclide/coc.nvim#1701]
Almost everytime I run `:PlugUpdate` (with `vim-plug`) I get a `refusing to merge unrelated histories` error message which requires me to run `:PlugClean` and `:PlugInstall`

### Before PlugClean+PlugInstall

```
Error: javascript bundle not found, run :call coc#util#install() to fix.
```

### After PlugClean+PlugInstall

```
## versions

vim version: NVIM v0.4.3
node version: v11.15.0
coc.nvim version: 0.0.77-817efd5108
term: xterm-256color
platform: linux

## Output channel: prettier


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /usr/local/google/home/elentok/.dotfiles
resolved root: /usr/local/google/home/elentok/.dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

```

## Describe the bug

Using the `vim-plug` package manager, when I run `:PlugUpdate`

## Reproduce the bug

- Created file `mini.vim` with (the issue is related to vim-plug, so I need to load it using vim-plug)：

  ```vim
  set nocompatible
  filetype plugin indent on
  syntax on
  set hidden

  call plug#begin('~/.local/share/nvim-plugins')
  Plug 'neoclide/coc.nvim', { 'branch': 'release' }
  call plug#end()
  ```

- Started neovim with command: `nvim -u mini.vim`

- Ran `:PlugUpdate` and got this output:

  ```
  Updated. Elapsed time: 0.844394 sec.
  [x]
  
  - Finishing ... Done!
  x coc.nvim:
      fatal: refusing to merge unrelated histories
  ```

**Comment by chemzqm** [comment]
It's problem of your vim-plug.

**Comment by elentok** [comment]
Hi @chemzqm ,

- Are you saying it's a problem with my specific installation of vim-plug?
- Is there another recommended plugin manager?
- It's complaining that my local "release" branch has diverged from "origin/release", is it being force pushed?

**Comment by oblitum** [comment]
VIM-PLUG is recommended. I use it and call `:PlugUpdate` daily and never hit this.

**Comment by chemzqm** [comment]
@elentok We don't know what's wrong with your vim-plug or plugin state, please don't ask question in issue list.
Try
* Redownload latest vim-plug from github.
* Remove coc.nvim folder.
* Add `Plug 'neoclide/coc.nvim', { 'branch': 'release' }` and run `:PlugInstall` again

**Comment by JiriChara** [comment]
You can try running `:PlugClean` followed by `:PlugInstall`. It solved the "unrelated histories" issue for me.
