### ISSUE TITLE
Number highlighting in neovim requires semver 0.5, but `numhl` released in 0.3.2

### ISSUE THREAD

**Issue by danjenson** [neoclide/coc.nvim#1702]
`numhl` was released in version 0.3.2:
https://github.com/neovim/neovim/releases/tag/v0.3.2
Most major linux distros don't have v5 yet, including arch linux, which is usually ahead of the curve, so the requirement for semver v5 seems excessive/arbitrary:

https://github.com/neoclide/coc.nvim/blob/1706d236b1d18f83daba769471e6036bbe8fc2fb/src/diagnostic/manager.ts#L146

should be 
```
if (!workspace.isNvim || semver.lt(workspace.env.version, 'v0.3.2')) {
    enableHighlightLineNumber = false
}
```

**Comment by chemzqm** [comment]
Fixed
