### ISSUE TITLE
Jump to next error across whole workspace

### ISSUE THREAD

**Issue by bengolds** [neoclide/coc.nvim#1706]
I'd like to be able to more easily jump-to the next error in my workspace. When trying to make my code compile, I often fix all the errors in one file, and then need to jump to the errors in the next file. 

It'd be nice to be able to do this with a command like `Plug(coc-diagnostic-next-error)` so that I can just consistently jump to the next error without having to worry about what file the error is in.

The current alternative is to fix all the errors in the current file, try to jump, see that it fails, and then open up the diagnostics `CocList`, jump to the first thing there, and fix them that way.

**Comment by chemzqm** [comment]
coc.nvim doesn't provide project compile , but you can use `:lnext` to jump to next location in your quickfix list, which normally used for project errors.

**Comment by KingOfCramers** [comment]
While understanding that you've closed this chemzqm, is there some way that we could perform a workaround?

I'm basically relying on coc-diagnostics rather than the quickfix list and agree that this would be ideal.

**Comment by chemzqm** [comment]
Use `:CocNext` and `:CocPrev` to jump locations of latest CocList.

**Comment by GopherJ** [comment]
Hi, I'm also interested in this feature because sometimes I got too many warnings from linters, I'd like to jum directly to the next error instead of warning.

Is there a way to do this? @chemzqm 

I tried to use it like what you've suggested but it seems requiring opening at least one time `CocList diagnostic` which is not convenient

**Comment by GopherJ** [comment]
Ok we already had it, sorry just checked the doc and find it. Thanks!

**Comment by gibfahn** [comment]
For anyone else who comes across this.

I tried `CocNext` and `CocPrevious`, but didn't want to add another mapping pair for those as I already have next/previous for Quickfix list and for `Plug(coc-diagnostic-{next,prev})`.

Easiest way to get all diagnostics for me was thus:

```vim
:CocList diagnostics
<C-a> " Select all
<C-q> " Save to Quickfix list
```

You can then use your quickfix next and previous (`:cnext` / `:cprev`) mappings to jump between all the errors in the workspace.
