### ISSUE TITLE
A translation table for snippet filetypes (vscode -> neovim)

### ISSUE THREAD

**Issue by randrej** [neoclide/coc.nvim#1708]
**Is your feature request related to a problem? Please describe.**
Using snippets from vscode extensions is great. However, they only work on languages which have the same names in vscode and neovim (say, Python), and not in languages for which the filetype names are different (example: plaintext, (shellscript, sh), ...).

**Describe the solution you'd like**
We could have some sort of built-in translation table for languages, which allows us to use vscode snippets for languages whose names differ between vscode and neovim. For example, I'd like to see `shellscript` vscode snippets used `sh` filetypes in neovim and such. A special case would be to allow  `plaintext` snippets everywhere (or where `filetype` is unset).

**Comment by randrej** [comment]
Partial solution:

Using `snippets.extends` in coc-settings.json **works**:

```json
{
    "snippets.extends": {
        "sh": ["shellscript"],
        "bash": ["shellscript"]
    }
}
```

However, I wouldn't know how to extend snippets for all files or for files with unset `filetype`.

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc-snippets#options
