### ISSUE TITLE
With color theme PaperColor, diagnostics indication missed after executing command "syntax on"

### ISSUE THREAD

**Issue by iiifr** [neoclide/coc.nvim#1709]
## Result from CocInfo
No obvious error message.

## Describe the bug
With color theme *PaperColor* enabled, diagnostics indication underscore is missed and diagnostics sign at sidebar is color-missed after executing command `syntax on`

PaperColor repository: [here](https://github.com/NLKNguyen/papercolor-theme)

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set encoding=utf-8
  let $LANG='en_US.UTF-8'
  
  set runtimepath^=/path/to/papercolor-theme
  set runtimepath^=/path/to/coc.nvim
  
  set termguicolors
  set background=light
  colorscheme PaperColor
  
  set hidden
  set nobackup
  set nowritebackup
  set updatetime=300
  set shortmess+=c
  set signcolumn=yes

  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Open a file which will let coc.nvim show diagnostics indication

- Execute vim command `syntax on`

**Comment by chemzqm** [comment]
Checkout `:h coc-highlights`

**Comment by iiifr** [comment]
According to the `coc-highlights` help page, I add the script below in my `.vimrc`, and the problem solved.

```vim
  autocmd ColorScheme * 
              \ hi CocErrorSign  ctermfg=Red guifg=#ff0000 | 
              \ hi CocWarningSign  ctermfg=Brown guifg=#ff922b |
              \ hi CocInfoSign  ctermfg=Yellow guifg=#fab005 |
              \ hi CocHintSign  ctermfg=Blue guifg=#15aabf |
              \ hi CocUnderline  cterm=underline gui=underline
```
