### ISSUE TITLE
LTS snippet bug

### ISSUE THREAD

**Issue by pacmanzou** [neoclide/coc.nvim#1710]
## Describe the bug
![深度截图_选择区域_20200401211609](https://user-images.githubusercontent.com/56422464/78144409-271c3b00-7462-11ea-9811-682f87fb31f3.png)

When I complete the LTS snippet(block),this warning sometimes appears "clipboard: error: Error: target STRING not available",and sometimes nvim will get stuck,ctrl-c won't work,too.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
What do you mean LTS snippet?

**Comment by pacmanzou** [comment]
LTS own code snippet , such as if~ ,main~ and func~...

**Comment by fannheyward** [comment]
Can't reproduce. Post `:CocInfo` and `:CocOpenLog` when this error occur.

**Comment by pacmanzou** [comment]
The nvim has got stuck , I can't open CocInfo or CocOpenLog. 
This happens most often when I use nvim for more than 6 hours and just now I tried everything right.I think that's probably the reason.

**Comment by pacmanzou** [comment]
Thanks for yout answer.I think it could be my machine problem.

**Comment by oblitum** [comment]
That warning is a long time xclip issue.

**Comment by pacmanzou** [comment]
> That warning is a long time xclip issue.

Thank you very much!
I replaced the xclip with xsel,Fixed the bug.
