### ISSUE TITLE
completeopt `longest` can't be used with coc.nvim

### ISSUE THREAD

**Issue by randrej** [neoclide/coc.nvim#1711]
Is there a way to get completeopt=longest to work with coc.nvim?

By default, coc.nvim sets its own completeopts when completing and reverts them when it's not. However, there is no way to have it use `longest`, and it totally breaks when you set `suggest.keepCompleteopt` along with `set completeopt=longest,noinsert,noselect,menuone,preview`.

Inserting the longest common prefix of all suggestions is extremely useful in many situations, especially when working with C code (and code in other similar languages) that has module functions and variables prefixed with the module's name.

**Comment by chemzqm** [comment]
No, you can't use longest since it won't work at all.

**Comment by Julian** [comment]
Perhaps this is different than what the original post here is about (or perhaps it isn't and it's impossible), but I think I wanted a similar thing to `longest` but via coc's completion and it seems like it should be possible, no?

Meaning, I want `<tab>` to on first hit when `pumvisible`, select the longest match that matches the text that was typed, but not yet select it and close the pum unless it's an exact match, and only do so if I hit tab a second time.

Is that similar to what's considered not possible here?

**Comment by chemzqm** [comment]
> but not yet select it and close the pum unless it's an exact match, and only do so if I hit tab a second time.

Can't understand, you mean first `<tab>` jump to first complete item (longest as well) then second `<tab>` confirm the selection?

**Comment by Julian** [comment]
> Can't understand, you mean first <tab> jump to first complete item (longest as well) then second <tab> confirm the selection?

Yes I think so. Sorry for being unclear, will write an example:.


So if I have:

```
fo<Tab>
```

and there are two possible completions, `foo` and `foot`, I want my first hit of tab to complete to `foo` (which is the shortest match that matches what I've typed so far -- completeopt calls that 'longest', which I guess is since `foo` is the "longest" common prefix to `foo` and `foot`) and leave the pum open for me to keep typing, but if I hit it a second time then it should complete `foo` and close the pum.

Does that make more sense?

**Comment by Julian** [comment]
A second example:

If I have `go<tab>` and there are 2 completions, `good` and `goof`, I want the first hit of tab to complete just *goo*, which is again the longest match across all choices.

**Comment by chemzqm** [comment]
Seems can't make it work with auto completion engine, but should work if we provide completion as `completefunc`, that would be sync and features like fuzzy filter and increment completion would be missing.

**Comment by Julian** [comment]
Got it, understood! Sounds like a pretty heavy tradeoff yeah, but definitely appreciate you having a look!
