### ISSUE TITLE
Code action under cursor (without selecting)

### ISSUE THREAD

**Issue by olalonde** [neoclide/coc.nvim#1712]
Is it possible to show code actions for the word/character under the cursor (without having to select)? Having to select a letter/word can be annoying sometimes... Wouldn't it be possible to have a `coc-codeaction-cursor` that uses the current cursor position? 

```viml
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
```

**Comment by fannheyward** [comment]
Checkout the README:

```
" Remap keys for applying codeAction to the current line.
nmap <leader>ac  <Plug>(coc-codeaction)
```

**Comment by olalonde** [comment]
@fannheyward I saw this but it doesn't work as expected. When I select the letter under my cursor, the code action list is different. I'm using `coc-rust-analyzer`. For current line I get:

```
1. Convert to snippet
```

When I select the letter under my cursor:

```
1. Convert to snippet
2. Import fmt
```

**Comment by fannheyward** [comment]
You don't need to select the letter, just put cursor on error position and fire code action.

**Comment by iamcco** [comment]
Use `<leader>aw` for your mapping

**Comment by chemzqm** [comment]
Code action requires range to work, you can create key-mapping yourself.

**Comment by olalonde** [comment]
@fannheyward what I am saying is this does not work. `coc-codeaction` gives irrelevant code action for the error. `coc-codeaction-selected` gives the right code action (`Import fmt`) but it requires selecting the letter under the cursor.

@chemzqm is it possible to make a key mapping that will automatically set `selected range` as  `letter under cursor`?

**Comment by ninjawithaneedle** [comment]
@olalonde Can you try `nmap <leader>a v<Plug>(coc-codeaction-selected)`
Discussion is here: https://github.com/neoclide/coc.nvim/issues/1981
