### ISSUE TITLE
Ability to disable auto filetype change from javascript.jsx to javascriptreact

### ISSUE THREAD

**Issue by SalTor** [neoclide/coc.nvim#1713]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when coc converts [javascript|typescript].jsx filetypes to [javascript|typescript]react even if I'm not using coc-tsserver and don't have that extension installed. I have had to make a ftplugin for javascriptreact to change to javascript as a catchall.

**Describe the solution you'd like**
I want the ability to disable this automatic changing of the filetype.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chemzqm** [comment]
It doesn't change your the buffer's filetype, just filetype used for coc.nvim.
