### ISSUE TITLE
add shellcheck as an extension

### ISSUE THREAD

**Issue by doums** [neoclide/coc.nvim#1714]
**Is your feature request related to a problem? Please describe.**
Currently it seems that there is no existing coc extension for shellcheck.

**Describe the solution you'd like**
[shellcheck](https://github.com/koalaman/shellcheck) is an analysis tool for shell script. I use it frequently (vi Jetbrains CLion IDE) and it's really good to catch mistake, bad practice etc when I work on shell script.
I suggest adding it as an extension for coc, (if possible). I think it will be a nice added value to coc.
It is already supported by Ale for example.

**Comment by chemzqm** [comment]
Checkout https://github.com/iamcco/coc-diagnostic, coc.nvim is not designed to provide same features of ALE.
