### ISSUE TITLE
References and Renaming doesn't work as expeceted

### ISSUE THREAD

**Issue by janbaer** [neoclide/coc.nvim#1717]
**Is your feature request related to a problem? Please describe.**
Recently I had the problem to find all references (callers) of a function and because of a refactoring also do some renamings of function names. It was working perfectly when the files, in which the renaming should happen was open before. The same with reference (gr). When I opened the other file in a window before, it was going as expected to the caller of a function. But when I never opened the other window before, I just get the info "References not found".

I'm not sure, if this is a problem of the LanguageServer or Coc.

**Describe the solution you'd like**
I think it's clear, how the feature should work. Especially for renaming it's a big problem when it doesn't rename all usages of a function.

**Describe alternatives you've considered**
I tried to load the other file with the **badd** command in the buffer but in the background, but this won't help

**Additional context**
I'm talking about node.js projects with plain Javascript (no Typescript)

**Comment by janbaer** [comment]
Why is this closed without an answer?

**Comment by chemzqm** [comment]
You should create issue according to given template

**Comment by janbaer** [comment]
But I used the template. So what's missing? Which information do you still need?

**Comment by chemzqm** [comment]
You're using template for feature request

**Comment by janbaer** [comment]
Because it wasn't a bug for me. Maybe it's not possible at all, because I realized that in VS-Code it's the same behavior...

**Comment by nicobao** [comment]
https://youtu.be/q7gr6s8skt0
It's due to the ts/js language server.
I think for Java, coc-rename works as expected.
Use CocSearch for project wide symbol renaming as seen in the video above.
