### ISSUE TITLE
Flow and Typescript conflicts

### ISSUE THREAD

**Issue by costerik** [neoclide/coc.nvim#1719]
Hey guys, I've been trying to setup TypeScript in a project but I would like to enable TypeScript autocompletion only for .ts files, for instance, app.ts not for app.js. That's because I have projects with Flow (usually, most of the Flow files are normal .js files) and I installed coc-flow and works perfectly but when I install coc-tssever, crash autocompletion and throwing Linters errors for .js files.
![Screen Shot 2020-04-05 at 12 50 34 AM](https://user-images.githubusercontent.com/8321591/78467907-820a9800-76d7-11ea-8ea2-9a73f62bdda9.png)
coc-config
![Screen Shot 2020-04-05 at 12 51 42 AM](https://user-images.githubusercontent.com/8321591/78467927-ba11db00-76d7-11ea-8707-9bb5205a7ea2.png)

**Comment by chemzqm** [comment]
You can disable javascript or use api to deactivate this extension

**Comment by costerik** [comment]
How can I do that?
