### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by MaskRay** [neoclide/coc.nvim#172]
### Acronym

Should it be `Complete or Conquer`?

### `autocmd CursorHold`

It'd be better to check if coc has been initialized. I'm versed in neither vim nor coc.nvim but my suggestion is like the following:

```vim
augroup coc_config
  au!
  au BufEnter * let b:Plugin_coc_started = 0
  au User CocNvimInit let b:Plugin_coc_started = 1
  au CursorHold * if b:Plugin_coc_started | sil call CocActionAsync('highlight') | endif
  " CursorHoldI does not seem to work
  au CursorHoldI * if b:Plugin_coc_started | sil call CocActionAsync('showSignatureHelp') | endif
augroup END
```

### `call CocAction('doHover')`

It'd be nice to call `textDocument/hover` in the `CursorHold` autocommand event, however, a preview window for a single-line `Hover` information might be overkill. I think that might be the concern that it should not be called automatically. 

### `set cmdheight=2`

My impression is that many people prefer one-line status bar/echo area.

Quoting a comment by twlz0ne in an Emacs forum:

> 也曾考虑过把 mode-line 拿来显示简单的帮助信息。
>
> 如果用 hydra，即便帮助信息只有一行，也要在 echo erea 开辟两行空间，一行用来刷 message，剩下一行才是帮助提示。我特别不喜欢在编辑过程中，底部忽然蹿上一个窗口。多行蹿就罢了，那是无法避免的，单行也蹿，实在是有点烦。
>
> 像 expand-region 直接用 message 也不好，会被其它 message 盖掉，而且在 *Messages* 留下大量无用的信息。
>
> 而 mode-line 显示的那些内容大多数时侯没什么意义，不如腾出空间做他用。

**Comment by chemzqm** [comment]
> au CursorHold * if b:Plugin_coc_started | sil call CocActionAsync('highlight') | endif

No need for that, coc is a single global service, it works on all buffers, `CocActionAsync` already contains check for coc server state.

> a preview window for a single-line Hover information might be overkill

Using floating window is in TODO list.

>  I think that might be the concern that it should not be called automatically.

Show preview window automatically is a good user experience, and neovim doesn't have support for `balloonevalterm` which is true mouse hover, `balloonevalterm` only support plain text, so it's not used at all.

> My impression is that many people prefer one-line status bar/echo area.

`set cmdheight=2` could help to reduce the problem of `press any key to continue` of vim. It's just suggestion, it's ok when it's `1`.

**Comment by chemzqm** [comment]
> It'd be nice to call textDocument/hover in the CursorHold autocommand event

I would prefer `call CocAction('doHover')`, since the result is from hoverProvider which could be not using language server or result is combined from multiply providers.

**Comment by MaskRay** [comment]
How about the Conqure typo (Acronym)

There is `vnoremap <Plug>(coc-format-selected)     :<C-u>call CocAction('formatSelected', visualmode())<CR>`, but it's worth mentioning how to set `formatexpr`

Regarding `textDocument/hover`

```typescript
interface Hover {
	contents: MarkedString | MarkedString[] | MarkupContent;
	range?: Range;
}

// @deprecated use MarkupContent instead.
type MarkedString = string | { language: string; value: string };
```

My thought is that `MarkedString[]` is not worse than `MarkupContent`. Among the `MarkedString[]` list, there is usually just one `MarkedString` having the `language` property. It is oftentimes the most important piece information and a simple `echo` command works really well and is also less distracting.

The other markdown/html stuff is nice if they can be rendered in a separate pop-up window

**Comment by oblitum** [comment]
It's nice as a typo! xD

**Comment by chemzqm** [comment]
> How about the Conqure typo (Acronym)

Fixed.

> but it's worth mentioning how to set formatexpr.

Not supported yet, could be impelmented.

> A simple echo command displaying that message works really well and is also less distracting.

I would prefer to use preview window or floating window when possible (ths support is WIP), change hover behavior depends on content could be confusing and it's harder to add highlight to echo.

**Comment by oblitum** [comment]
https://github.com/neoclide/coc.nvim/commit/e25e750ba4ae06ece54e4caf3ea38b445252eaba

:-(

I thought it was on purpose.

**Comment by chemzqm** [comment]
Closing. `formatexpr` is supported, floating window will be supported on later release.
