### ISSUE TITLE
Showing completion window on "."character

### ISSUE THREAD

**Issue by s0563858** [neoclide/coc.nvim#1720]
I'm trying to do the following thing: if I press "." while coding - a completion window should appear - but apparently it is not possible with your plugin.

**How am I trying to do this:**

```
inoremap <silent><expr> .  
\ pumvisible() ?  coc#_select_confirm().".".coc#refresh():
\  ".".coc#refresh()
```
**->** so if the completion window is visible then first complete the current word, then write an "." character and then open the completion window again and show the available completion-suggestions. 

But my script is just not working - it completes the current word and writes a "." character but it does not open the completion menu.

Is it possible with your plugin? 

(P.S. I'm using OmniSharp together with your plugin)

**Comment by chemzqm** [comment]
No
