### ISSUE TITLE
Choose everything with numbers in completion

### ISSUE THREAD

**Issue by Ni1fheim** [neoclide/coc.nvim#1723]
**Is your feature request related to a problem? Please describe.**
Configure the `suggest.numberSelect` option in the current version so that some completion items can be selected with numbers, but only a part of the items.

**Describe the solution you'd like**
I hope all completion alternative items can be selected with numbers, no matter which source it comes from.

**Describe alternatives you've considered**
There may be a `completion.numberSelect` property in `coc-settings.json` ?

**Comment by voldikss** [comment]
There is `suggest.numberSelect` option

**Comment by chemzqm** [comment]
Can't understand what's your problem with current behavior of `suggest.numberSelect`
