### ISSUE TITLE
Are 'TS/JS refactorings' exposed via CocVim?

### ISSUE THREAD

**Issue by benfrain** [neoclide/coc.nvim#1727]
I have seen this in VSCode: it shows a JS string that gets a 'hint' in VS Code that it can refactor into a template literal.

https://video.twimg.com/tweet_video/EUsxkYdXgAY5SqO.mp4

Is that same functionality exposed in CoC? If so, how?

**Comment by fannheyward** [comment]
Yes, `coc-tsserver` supports this, there is a codeaciton `Convert to template string`.

**Comment by benfrain** [comment]
I highlight the code:

```javascript
const message =
    "This is a " +
    cake.type +
    " cake." +
    "It has " +
    (cake.icing ? "some" : "no") +
    " icing.";
```

choose `CocAction` but only see:

1. Convert to snippet
2. Extract function
3. Extract constant
4. Move to a new file

**Comment by fannheyward** [comment]
Move your cursor on `This` and fire the code action.

**Comment by benfrain** [comment]
Excellent. Thanks. :)

For some reason, my display isn't showing indication this is possible (no highlight under `This`. Does yours?

<img width="475" alt="Screenshot 2020-04-07 at 12 39 22" src="https://user-images.githubusercontent.com/1318466/78664954-f5292f80-78cc-11ea-8928-d39535bd4e0b.png">

**Comment by oblitum** [comment]
It works on my machine, you need to put the cursor at `This` (`">here<This is a "`).

**Comment by benfrain** [comment]
@oblitum yes, works on mine too. But there is no visual indication to show you can do it. For example, VSCode shows a lightbulb above. 

Can Coc show a lightbulb or similar in the gutter and underline ‘This’?

**Comment by chemzqm** [comment]
> no visual indication

Yes, we don't have lightbulb.

**Comment by benfrain** [comment]
So how could user know such refactor is possible?

**Comment by chemzqm** [comment]
We can make use of float window,  don't have time for it for now.

**Comment by benfrain** [comment]
Ok, thanks for feedback and great plugin. Have donated 👍🏻

**Comment by pittcat** [comment]
@benfrain You can check this.
https://github.com/xiyaowong/coc-lightbulb
