### ISSUE TITLE
no "documentSymbols" in Vimscript files

### ISSUE THREAD

**Issue by qsmy41** [neoclide/coc.nvim#1728]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 14:47:07)
node version: v10.16.3
coc.nvim version: 0.0.77-817efd5108
term: iTerm.app
platform: darwin

## Describe the bug

When I run `:echo CocAction('documentSymbols')` in `Path/To/autoload/coc.vim`, the output shows `v:null`. However, in my other files such as latex files, the output has lines of returned symbols. I think the problem is related to how coc extracts 'documentSymbols' in Vimscripts?

The extension coc-vimlsp is installed:
![Screenshot 2020-04-07 at 17 19 31](https://user-images.githubusercontent.com/44122119/78694132-20734500-78f4-11ea-813e-23bc7af5419e.png)

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocp

  call plug#begin('~/.vim/plugged')
  " Use release branch (Recommend)
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- `:e Path/To/autoload/coc.vim`, `:echo CocAction('documentSymbols')`, then the output is produced.

## Screenshots (optional)

![Screenshot 2020-04-07 at 17 17 46](https://user-images.githubusercontent.com/44122119/78693842-b8bcfa00-78f3-11ea-9b26-74758acbc34e.png)

**Comment by iamcco** [comment]
coc-vimlsp does not support documentSymbols yet.
