### ISSUE TITLE
Disabling Auto-Complete on Dot?

### ISSUE THREAD

**Issue by amit-traiana** [neoclide/coc.nvim#1730]
Hello,

I set `suggest.autoTrigger` to `trigger`, and using Tab when I want Auto-complete. However, it seem like `.` (dot) character will always trigger auto-complete. The documentation mentioned `trigger` will get triggered by `triggerCharacters`. Is it possible to modify/remove this list? is that a CoC settings? or it comes from the Language server? (which is my case is Jedi for Python).

Thanks!

**Comment by chemzqm** [comment]
It's configured by language server, you can't change it, you can set `suggest.autoTrigger` to `none`.

**Comment by amit-traiana** [comment]
Thank you for clearing it out.
