### ISSUE TITLE
Why i met this error?

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#1733]
i try to copy some config from <https://github.com/neoclide/coc.nvim/wiki/Language-servers#supported-features>, but

![image](https://user-images.githubusercontent.com/32936898/78808143-9a402700-79f7-11ea-9b45-905a0811b2bb.png)

it maybe due to something i do wrong, but i don't know what it is.

thanks!

**Comment by voldikss** [comment]
Wrap them using curly brackets

```jsonc
{
  "languageserver": {
    "foo": {
      "module": "/usr/local/lib/node_modules/foo/index.js",
      "args": ["--node-ipc"],
      "filetypes": ["foo"],
      "trace.server": "verbose",
      "rootPatterns": ["root.yml"],
      // Used for debugging
      "execArgv": ["--nolazy", "--inspect-brk=6045"],
      "initializationOptions": {},
      "settings": {
        "validate": true
      }
    }
  }
}
```
