### ISSUE TITLE
Abnormal exit with: 132 when trying to install any extension

### ISSUE THREAD

**Issue by JuanPedroGHM** [neoclide/coc.nvim#1734]
## Result from CocInfo

vim version: NVIM v0.4.3
node version: v13.12.0
coc.nvim version: 0.0.77-817efd5108
term: xterm-kitty
platform: linux

## Describe the bug

I installed neovim with coc on a remote server in order to write through ssh/tmux after testing the setup on my own machine. My interest is to use the conda env installed on the server while developing, in a similar way to how VisualStudioCode works. The installation of coc works well, but I am not able to install any extensions afterwards. 
The only message I get is:

> client coc abnormal exit with: 132

Coc has to be started again afterwards. I tried the installing coc-python, coc-json and coc-tsserver, but all of the give the same error. I tried finding the error code in the repository, but found nothing about it.

## Reproduce the bug
```
1. Open neovim
2. :CocInstall coc-python

```
I tried using the minimal vimrc provided in the template, and I got the exact same behavior. 
Here is the output of CocOpenLog for completion, but don't think it has something relevant.

> 2020-04-09T11:35:51.901 INFO (pid:21543) [plugin] - coc 0.0.77-817efd5108 initialized with node: v13.12.0

I don't have any admin rights, so any solution that requieres a package manager or sudo will be hard to try :(
About the system (output from screenfetch):
 ```
OS: Ubuntu 14.04 LTS (Trusty Tahr)
 Kernel: x86_64 Linux 3.19.0-80-generic
 Uptime: 23d 17h 37m
 Packages: 1674
 Shell: bash 4.3.11
 Disk: 55T / 62T (93%)
 CPU: Quad-Core AMD Opteron 2354 @ 4x 2.211GHz
 GPU: Advanced Micro Devices, Inc. [AMD/ATI] ES1000 (rev 02)
 RAM: 2268MiB / 16047MiB
```
Thanks in advance for the help.

**Comment by chemzqm** [comment]
No idea, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by chemzqm** [comment]
You can use vim-plug instead https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions

**Comment by nhartung** [comment]
I encountered this error as well and discovered that it was caused by a bad npm install. a ":healthcheck" showed that I had a bad Node.js provider. I did a:
```
sudo apt-get update
sudo apt-get upgrade
npm install -g neovim
```
and it resolved the issue.
