### ISSUE TITLE
Question: Is it possible to run multiple language servers for different projects on a single nvim instance?

### ISSUE THREAD

**Issue by felippemr** [neoclide/coc.nvim#1737]
**Is your feature request related to a problem? Please describe.**
As an engineer working on multiple software projects, I am constantly switching from different language versions and environments with different dependencies. Currently, in order to work with each project, I open a new nvim instance whenever I need to edit/look files from them. 

 Because of that, sometimes I end up with a lot of tmux tabs, one for each different project. I would like to be able to switch between different language servers and language environments for files belonging to different projects within a single nvim instance.

**Describe the solution you'd like**
Within a single nvim instance I would like to be able to have my python virtual environment switch whenever I open a file from a different project.

Scenario:
Project A has virtualenvironment X
Project B has virtualenvironment Y

nvim path/to-project/A/main.py # using coc-python it will open and select the correct virtualenvironment
:tabedit path/to/project/B/main.py # coc would change the virtualenvironment when opening the file

**Describe alternatives you've considered**
Using `autoCmd` but I don't know how to configure it to achieve such.

**Additional context**
This might be a feature request for coc-python, let me know and I will close it here and open it there.

**Comment by chemzqm** [comment]
No such support,  there is neovim ide that support multiple neovim instance, but I think you should get used to multiple neovim instances
