### ISSUE TITLE
Folding in the error messages

### ISSUE THREAD

**Issue by diskroma** [neoclide/coc.nvim#1738]
**Is your feature request related to a problem? Please describe.**
When foldlevel and foldlevelstart is set to 0 the coc error messages are also folded by default.
Is there a way to disable folding for these ?
Also the foldcolumn is shown.

**Describe the solution you'd like**
Dont have folds at all in the floating window, that shows error messages.
Maybe hide the foldcolumn as well, if possible?

**Describe alternatives you've considered**
Alternatively unfold everything before showing.

**Additional context**
Im using NVIM 0.43 and im using floating windows for hover information.

Here is a screenshot:

![1586502996_grim](https://user-images.githubusercontent.com/58692022/78972267-a28a8600-7b0d-11ea-8e9f-86931a27c585.png)

**Comment by chemzqm** [comment]
Checkout `:h CocOpenFloat`

**Comment by pckilgore** [comment]
For anyone who finds this issue later, I was able to get good results with:
```vim
" Folds {{{
set foldmethod=indent
set foldnextmax=2
set foldlevel=1 " Fold up most things on file open
autocmd User CocOpenFloat :set foldlevel=20 foldcolumn=0
" }}}
```

**Comment by chemzqm** [comment]
My suggest is use setl with fold options instead of change global option.

**Comment by pckilgore** [comment]
Ahh, didn't know about that, thanks!
