### ISSUE TITLE
CocAction('codeLens') => Source id of codelens not found

### ISSUE THREAD

**Issue by MaskRay** [neoclide/coc.nvim#174]
**Describe the bug**
`:call CocAction('codeLens')` displays an error message `[coc.nvim] Source id of codelens not found"`

**To Reproduce**
`~/.config/nvim/coc-settings.json`:
```javascript
{
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "objc", "objcpp"]
    }
  }
}
```
1. `cd /tmp/d; git init`
2. `echo 'int a;' > a.cc`
3. `nvim a.cc`
4. Execute `:call CocAction('codeLens')`

**Expected behavior**
`textDocument/codeLen` result is rendered somewhere

**Additional context**

`sysdig -As9999 --unbuffered -p '%evt.buffer' "proc.exe contains ccls and fd.type=unix"`:

```javascript
Content-Length: 113

{"jsonrpc":"2.0","id":16,"method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///tmp/d/a.cc"}}}

Content-Length: 239

{"jsonrpc":"2.0","id":16,"result":[{"range":{"start":{"line":0,"character":4},"end":{"line":0,"character":5}},"command":{"title":"0 ref","command":"ccls.xref","arguments":["{\"usr\":16721564935990383768,\"kind\":4,\"field\":\"uses\"}"]}}]}
```

Note it encodes a JSON string as the only element of `"arguments"` (to make VSCode happy):
```javascript
"arguments":["{\"usr\":16721564935990383768,\"kind\":4,\"field\":\"uses\"}"]
```

`/tmp/coc-nvim.log` log entry:
```
2018-11-23T21:19:51.601 ERROR (pid:17076) [codelens] - Cannot read property 'command' of null
```

**Comment by chemzqm** [comment]
The command not exists, an extension could help to regist custom command.

**Comment by MaskRay** [comment]
Does it make sense to postpone the error reporting to when the user triggers the command?

My supposed interaction is:

* User invokes `textDocument/codeLens`
* Server returns:
```json
{"jsonrpc":"2.0","id":16,"result":[{"range":{"start":{"line":0,"character":4},"end":{"line":0,"character":5}},"command":{"title":"0 ref","command":"ccls.xref","arguments":["{\"usr\":16721564935990383768,\"kind\":4,\"field\":\"uses\"}"]}}]}
```
* `range` and `command.title` are rendered even if the server does not know the actual `command`. In this particular case, `"title": "0 ref"` means the declaration has 0 references. This is more important than it being a clickable button.
* (Optionally) User clicks the `0 refs` button (code lens). As there is no extension to handle the command `ccls.xref`, coc.nvim can bail out and print an error message in this step, instead of sending

```json
{"title":"0 ref","command":"ccls.xref","arguments":["{\"usr\":16721564935990383768,\"kind\":4,\"field\":\"uses\"}"]}
```

**Comment by chemzqm** [comment]
Coc will use `set_virtual_text` of neovim for codeLenes feature.
