### ISSUE TITLE
Can't update to coc.nvim

### ISSUE THREAD

**Issue by douglas86** [neoclide/coc.nvim#1742]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

Can't seem to update to coc.nvim using PlugUpdate.
I need the latest version of coc.nvim to run coc-explorer.
running coc.nvim version 0.0.74 need 0.0.75 for coc-explorer to work.

**Comment by oblitum** [comment]
It should be issue of your plugin manager, not coc.nvim.
