### ISSUE TITLE
Feature request: Open CocList in vertical split

### ISSUE THREAD

**Issue by JoshMcguigan** [neoclide/coc.nvim#1744]
**Describe the solution you'd like**

I'd like to be able to open CocList in a vertical split (current options are horizontal split or tab). My ideal workflow would involve leaving the CocList open in a vertical split which editing files in the other side of the split.

**Additional context**

Thanks for your work on `coc.nvim`!

**Comment by wookayin** [comment]
You may want to use https://github.com/antoinemadec/coc-fzf instead.

**Comment by chemzqm** [comment]
It's not designed as file explorer, you can use https://github.com/weirongxu/coc-explorer or others.
