### ISSUE TITLE
Support vala langauge server?

### ISSUE THREAD

**Issue by LinArcX** [neoclide/coc.nvim#1746]
**Is your feature request related to a problem? Please describe.**
It should be so nice to have vala support.

**Additional context**
This is vala language server:
https://github.com/benwaffle/vala-language-server

**Comment by oblitum** [comment]
Check the wiki about configuring language servers: https://github.com/neoclide/coc.nvim/wiki/Language-servers

**Comment by LinArcX** [comment]
Ok. I built that repo and have these files after successfull compilation:
```
/usr/bin/vala-language-server
/usr/lib/gnome-builder/plugins/vala_langserv.plugin
/usr/lib/gnome-builder/plugins/vala_langserv.py
```

[This](https://gist.github.com/LinArcX/89225d71ddc7287b8d71976ba86d37d4) is my latest coc-settings.json.

I opened a vala file and start typing.. but nothing happend. Even i can't see the process of vala-langaugage-server in htop.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
