### ISSUE TITLE
Multiple directories - documentation missing

### ISSUE THREAD

**Issue by flavius** [neoclide/coc.nvim#1748]
I have different projects, and each of them uses some shared library among them. Each project uses a different combination of libraries and the libraries are out-of-sourcetree (for reuse).

I can arrange for a .vim file in the root project to be sourced when I first start vim.

The question which remained unanswered from reading the docs: what vimL code helps me add at runtime, in addition to the current root, another root (one or more) to the workspace?

**Comment by chemzqm** [comment]
`:h g:WorkspaceFolders`

**Comment by Minnozz** [comment]
I have the same problem and can't figure out the solution from that wiki page; the supported actions for a folder are `delete`, `edit` and `newfile`, but I can't figure out how to add a second folder to the list.

**Comment by chemzqm** [comment]
>  but I can't figure out how to add a second folder to the list.

No such action, you can edit exists workspaceFolders.
