### ISSUE TITLE
Support custom CocAction in extension

### ISSUE THREAD

**Issue by weirongxu** [neoclide/coc.nvim#1750]
**Is your feature request related to a problem? Please describe.**
I received some requests to add some vim API in `coc-explorer`, https://github.com/weirongxu/coc-explorer/issues/150, https://github.com/weirongxu/coc-explorer/issues/135, but I did not find any way to support custom CocAction in coc.nvim. Or am I missing something?

**Describe the solution you'd like**
support extended the CocAction, or support something like `CocAction('extension', 'coc-explorer', ... args)`

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
You can register command by use command module.
