### ISSUE TITLE
coc-definition : timeout after 30s

### ISSUE THREAD

**Issue by guigui64** [neoclide/coc.nvim#1752]
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 25 2020 13:46:58)
node version: v12.16.2
coc.nvim version: 0.0.78-fc983ce6dd
term: dumb
platform: linux

## Describe the bug

Using the coc-rust-analyzer extension and the `nmap <silent> gd <Plug>(coc-definition)` mapping, in a simple rust file, with the cursor positioned on a use of a local struct, typing gd freezes vim and the error message is raised after 30s.

I'm not sure if the issue is in coc.nvim or the rust-analyzer extension and I don't know how to be sure...

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  nmap <silent> gd <Plug>(coc-definition)
  ```

- Start vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
1. make sure your `rust-ananlyzer` works, tests the same project with VSCode + rust-analyzer
2. try neovim + coc-rust-analyzer

**Comment by guigui64** [comment]
1. rust-analyzer works because I have auto completion for instance (and sometimes the coc-definition works but takes a lot of time !)
2. I'll try but what would that change ?

**Comment by guigui64** [comment]
Is there a way to see the exchanges between coc and the lsp server ? That way I could see on what side is the issue

**Comment by oblitum** [comment]
@guigui64 possibly check https://github.com/neoclide/coc.nvim/wiki/Debug-language-server and https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim.

**Comment by peterszerzo** [comment]
I'm running into the exact same issue with https://github.com/elm-tooling/elm-language-server. Can somebody point me to the `coc-settings.json` field where this 30s interval can be reduced, or at least some shortcut to 'unfreeze' vim so I don't have to wait 30s?

**Comment by chemzqm** [comment]
We need debug log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc.
* Restart your vim/neovim to make the issue happen.
* Open the log file by command `:call coc#client#open_log()`.
* Attach the log file or paste content from the log.

**Comment by peterszerzo** [comment]
Thanks for looking at it @chemzqm, here are the logs:
[1.log](https://github.com/neoclide/coc.nvim/files/4475514/1.log)

**Comment by chemzqm** [comment]
Don't know why your vim get blocked, try use
```
nmap <silent> gd            :<C-u>call       CocActionAsync('jumpDefinition')<CR>
```
instead.

**Comment by peterszerzo** [comment]
Fantastic, this is exactly what I was looking for (I had `nmap <silent> gd <Plug>(coc-definition)` before and therefore turning it into async wasn't intuitive). Appreciate the help @chemzqm!

**Comment by VVKot** [comment]
@chemzqm Thanks for showing how to call the function async! There might be some problem with the code though, see https://github.com/neoclide/coc.nvim/issues/1755#issuecomment-613428943 It was also reported several times on Gitter.

**Comment by chemzqm** [comment]
Yes, I've noticed it several times, but can't reproduce on my vim8, seems the `callAsync` with timers doesn't work https://github.com/neoclide/coc.nvim/blob/master/src/workspace.ts#L881
