### ISSUE TITLE
Can I modify CocAction timeout value? 

### ISSUE THREAD

**Issue by fcying** [neoclide/coc.nvim#1755]
## Describe
I use coc with ccls, I use `nmap <silent> gd <Plug>(coc-definition)` to jump.

if there not found anything, sometime it jump `[coc.nvim] Definition not found`

sometime it block a long time and jump `Error on request (CocAction): timeout after 30s`

Can I modify timeout value? 30s is too long.

## Reproduce
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 14 2020 01:12:43)
Included patches: 1-550
Compiled by Homebrew

test_vimrc 
```
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
set shortmess+=c
nmap <silent> gd <Plug>(coc-definition)
filetype plugin indent on
syntax enable
```
test.h
```
#define test 1
```
vim -u ~/test_vimrc test.h

move cursor on `define`, type `gd`, is `[coc.nvim] Definition not found`
move cursor on `test`, type `gd`, is `Error on request (CocAction): timeout after 30s`

**Comment by keeto** [comment]
I've been having this issues as well, on vim 8.2.0550 on macOS Catalina 10.15.4. Both `<Plug>(coc-definition)` and `<Plug>(coc-type-definition)` were slow resulting in freezes and an eventual timeout.

I did a bisect with 705f94fd (good) to 46614ab (bad) and 705f94f seems to be the commit that introduced the issue.

**Comment by chemzqm** [comment]
Should be fixed on latest release.
