### ISSUE TITLE
Feature request: Add ability to disable language server autoloading

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc.nvim#1759]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when configured language server loads, I'd like to have more control and start services explicitly when I need them.

**Describe the solution you'd like**

An `enable` flag support for language servers:
```
  "languageserver": {
    "metals": {
      "enable": false,
      ...
```

**Describe alternatives you've considered**

Commenting out language servers.

**Comment by fannheyward** [comment]
This is already supported, https://github.com/neoclide/coc.nvim/blob/master/data/schema.json#L9
