### ISSUE TITLE
Provide user_data.signature field with non decorated signature for echodoc.vim support

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#176]
**Is your feature request related to a problem? Please describe.**

echodoc.vim (and possibly other plugin helpers) may need the original signature of completion items to work on. coc.nvim currently has difficult providing them because on `word` it just provides bare completion word (`"coc.preferences.triggerSignatureHelp": false`), and on `abbr` it provides decorated signatures (they are decorated with snippet indicator character).

**Describe the solution you'd like**

@Shougo has provided support for using `user_data.signature` field if it's present, it should be a place where it can grab original signature, currently it seems there's no safe place for that.

- https://github.com/Shougo/echodoc.vim/commit/ad0e745fafc9249c75807d5863ac72b93e0caf17

If coc.nvim fills this field then all should work fine.

**Describe alternatives you've considered**

Currently [I'm patching](https://github.com/oblitum/echodoc.vim/commit/a40c785bd6cb18ab4bbcfe07cccb1bab6344f634) echodoc.vim to strip my indication character from signatures.

**Additional context**

https://github.com/Shougo/echodoc.vim/issues/57

**Comment by chemzqm** [comment]
I've added `coc.preferences.echodocSupport`, it's default to `false` since there's no guarantee that language server provide signature in `insertText` or `label`

**Comment by oblitum** [comment]
Just tried, it's working well but, is it on purpose that return type had been removed too? On echodoc output instead of have just the decoration removed, it also doesn't have return type anymore.

**Comment by chemzqm** [comment]
Where does return type comes from? It's in label?

**Comment by oblitum** [comment]
With `"coc.preferences.echodocSupport": false`, echodoc displays signature just like in the popup menu, with indicator included. With `"coc.preferences.echodocSupport": true`, both indicator and `-> return type` are not present anymore. I'm not sure whether data should come from label or not, I was expecting `user_data.signature` to just contain the signature, including return.

**Comment by oblitum** [comment]
But it seems still OK without return, just `foo(...)`, not `foo(...)-> T`, hence I asked whether it was on purpose.

**Comment by oblitum** [comment]
OK, it's like I was expecting now after https://github.com/neoclide/coc.nvim/commit/b4a2bb6779b490bdee8e9b88e874d8dabea22dfd. Thanks!

**Comment by oblitum** [comment]
Looks like the fix applied in b4a2bb6 to correct return type for signatures is not working for Go even though it fixed for C/C++.

- `coc-settings.json`:
  ```jsonc
  {
    "coc.preferences.messageLevel": "warning",
    "coc.preferences.triggerSignatureHelp": false,
    "coc.preferences.echodocSupport": true,
    "languageserver": {
      "ccls": {
        "command": "ccls",
        "filetypes": ["c", "cpp", "objc", "objcpp"],
        "initializationOptions": {
          "cacheDirectory": "/tmp/ccls"
        }
      },
      "golang": {
        "command": "go-langserver",
        "filetypes": ["go"],
        "revealOutputChannelOn": "never",
        "initializationOptions": {
          "gocodeCompletionEnabled": true,
          "diagnosticsEnabled": true,
          "lintTool": "golint"
        }
      }
    }
  }
  ```

Test code:
```go
package main

func foo(a, b int) int {
	return a + b
}

func main() {
	foo<select from popup>(
}
```

`echodoc` reports just `foo(a int, b int)`, without return type.

**Comment by oblitum** [comment]
But it seems `go-langserver` is putting data in different places, hence the behavior. I get my snippet indicator after the function name in the popup, and the type for `foo` comes after as `func(a int, b int) int`. I can see it can be confusing how to handle this correctly, if it's possible..

**Comment by chemzqm** [comment]
I've improved the logic for detect signature.

**Comment by oblitum** [comment]
@chemzqm OK, it's fixed! (for  c/c++/go at least)
