### ISSUE TITLE
Error popup in coc-texlab during typing after updating coc.nvim

### ISSUE THREAD

**Issue by wrvsrx** [neoclide/coc.nvim#1761]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 4 2020 13:23:00)
node version: v13.12.0
coc.nvim version: 0.0.78-ceb9e47d24
term: dumb
platform: linux

// some other information
texlab version: 1.10.0-1 (install from pacman)
coc-texlab version: 1.10.2 (installed by CocInstall coc-texlab)

## Describe the bug

Yesterday, I update coc.nvim and after that I get such error when I editing tex files.
```
Error detected while processing function <lambda>5[1]..<SNR>108_execute:
line    2:
Complete texlab error: Cannot read property 'newText' of undefined
```

## Reproduce the bug

This can be reproduced in such ways:
1. use minimal vimrc (the problem can also be reproduced without this step)
2. create a tex file
3. write as below
```latex
\documentclass{article}
\begin{document}
    \begin{enumerate}
        \ite% cursor is here
    \end{enumerate}
\end{document}
```
3. When you type "\ite", the error popups.

I can reproduced it in my two PC, using gvim on windows, vim in wsl and vim in wsl2.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/42770726/79287356-1b1a8980-7ef6-11ea-908a-ec6e8adce8a3.png)

## output channel

The log is perhaps incomplete.

[test.tex.log](https://github.com/neoclide/coc.nvim/files/4478558/test.tex.log)

I add "texlab.trace.server" option in coc-setting.json and use "CocCommand workspace.showOutput" after opening file as the wiki says, however the log seems incomplete (https://microsoft.github.io/language-server-protocol/inspector/ can't parse it).

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
