### ISSUE TITLE
Is the ordering of documentChanges respected?

### ISSUE THREAD

**Issue by ckipp01** [neoclide/coc.nvim#1767]
I had someone report some odd behavior in our [coc-metals](https://github.com/scalameta/coc-metals/issues/164) plugin, and I've seemed to have tracked it down to something not working correctly with the way that `DocumentChanges` are processed when inside of a `textDocument/rename`. In Metals, you are able to rename a symbol, and if that symbol for example is a Class, and that filename matches that Class name, the rename will both rename the symbol and also the file name. The response from the server will look like the following if I attempt to do a rename on a Class `Test` in `Test.scala`.

`textDocument/rename`
```json
{
  "documentChanges": [
    {
      "textDocument": {
        "version": null,
        "uri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/Test.scala"
      },
      "edits": [
        {
          "range": {
            "start": {
              "line": 2,
              "character": 7
            },
            "end": {
              "line": 2,
              "character": 11
            }
          },
          "newText": "Hi"
        }
      ]
    },
    {
      "oldUri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/Test.scala",
      "newUri": "file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/Hi.scala",
      "kind": "rename"
    }
  ]
} 
```

As you can see, there are two `documentChanges`. The first will be the edit to rename the actual symbol, and then second will be to rename the file. In VS Code, this works as expected. However, in both Nvim and Vim this will actually do the rename file first, and then attempt to the rename symbol second. This results in the `Hi.scala`file still having the old `Test` Class name and then a new buffer called `Test.scala` having nothing but the new text in it, `Hi`. This makes me assume that the order of the `documentChanges` aren't happening in the order that they are in the array.

## Result from CocInfo
I've tried this on the following:

```
vim version: NVIM v0.5.0-3d1531a
node version: v12.13.1
coc.nvim version: 0.0.78
term: iTerm.app
platform: darwin
```
And also:
```
vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 13 2020 07:47:09)
node version: v12.13.1
coc.nvim version: 0.0.78
term: iTerm.app
platform: darwin
```

## Reproduce the bug
This is sort of hard to mimic probably, but you just need a rename that returns an array of `documentChanges`, and it needs to be asserted that the events in that array are processed in order.

## Screenshots (optional)

I've captured this in a gif to demonstrate the behavior I'm talking about.

![2020-04-15 22 00 48](https://user-images.githubusercontent.com/13974112/79383000-bd715600-7f64-11ea-834d-4e526e072035.gif)

As always, thanks for your hard work and great tool!

**Comment by chemzqm** [comment]
It's not order not respected, but the order could be changed.

**Comment by ckipp01** [comment]
Sorry I'm not sure I understand. Do you mean the order may be changed currently by `coc.nvim`?

**Comment by ckipp01** [comment]
So this for sure still isn't working as expected. Given the exact scenario still that the issue was about, you'll see the following exactly after the rename.

<img width="471" alt="Screenshot 2020-04-16 at 09 08 24" src="https://user-images.githubusercontent.com/13974112/79425631-44085080-7fc2-11ea-8208-ba02f415c8e4.png">

If I select no, nothing happens. If I select yea, then I'm still left inside `Test.scala` with the correct symbol. There are changes to that buffer, but it won't allow you to save since it says that file exists already.

<img width="378" alt="Screenshot 2020-04-16 at 09 12 35" src="https://user-images.githubusercontent.com/13974112/79425813-8af64600-7fc2-11ea-954d-fbd511052a22.png">

If I then do a `:copen`, I see the `Hi.scala`, which if I select, it brings me to `Hi.scala` with changes in the buffer that need saving, but you're also unable to save since it says the file exists.

I really have no idea what's going on now, but this for sure isn't working as expected.

![2020-04-16 09 15 37](https://user-images.githubusercontent.com/13974112/79426070-e9232900-7fc2-11ea-9d6f-4f45af917cf3.gif)

**Comment by chemzqm** [comment]
Looks like you need update coc.nvim.

**Comment by ckipp01** [comment]
Well this is the new behavior that you just added if I'm understanding it correctly? For example the prompt in the top image didn't exist before. I just double checked and I do have it built from the latest master.

**Comment by chemzqm** [comment]
It is bug with rename.

**Comment by ckipp01** [comment]
Hey @chemzqm a bug in rename meaning a bug inside of how `coc.nvim` is handling rename, or somewhere else?

**Comment by ckipp01** [comment]
The changes that you just pushed @chemzqm improve it quite a bit. The only other thing I see is that the old file still remains as an edited open buffer. Would it be possible to remove that?

**Comment by ckipp01** [comment]
Cool, with these latest changes, it seems to work. Thanks a bunch!
