### ISSUE TITLE
Code Actions with Dart / Flutter

### ISSUE THREAD

**Issue by wwwdata** [neoclide/coc.nvim#177]
**Describe the bug**
Code-Actions are not working for me in Flutter Projects with Dart. Auto completion is rock solid now! Thank you very much and it is super fast. Really like it.

**To Reproduce**
Install flutter sdk. 
Currently i am on version
```
╰─ flutter --version
Flutter 0.11.9 • channel beta • https://github.com/flutter/flutter.git
```

Then, install the dart language server with

```
pub global activate dart_language_server
```

Create a test project with `flutter create test_project`. Then cd into that project.

Configured coc like in the readme. Autocompletion works fine.

My config with verbose logging
```
{
  "languageserver": {
    "dart": {
      "command": "dart_language_server",
      "args": [],
      "trace.server": "verbose",
      "filetypes": ["dart"],
      "initializationOptions": {},
      "settings": {
        "dart": {
          "validation": {},
          "completion": {}
        }
      }
    }
  }
}

```

**Expected behavior**
When triggering a code action, I would expect that the text is correctly replaced in the editor. For example wrapping a widget with another one. 

**Additional context**
I enabled the workspace debug output and I could see that the correct replacement text was in there. However it was not replaced within vim..

See my debug output here to add a `Padding` around a widget class:
```
[Trace - 23:22:01] Received response 'textDocument/codeAction - (11)' in 15ms.
Result: [
    {
        "command": null,
        "diagnostics": null,
        "edit": {
            "changes": {
                "file:///Users/bbieker/Development/test_project/lib/main.dart": [
                    {
                        "newText": "Padding(\n        padding: const EdgeInsets.all(8.0),\n        child: FloatingActionButton(\n          onPressed: _incrementCounter,\n          tooltip: 'Increment',\n          child: Icon(Icons.add),\n        ),\n      )",
                        "range": {
                            "end": {
                                "character": 7,
                                "line": 107
                            },
                            "start": {
                                "character": 28,
                                "line": 103
                            }
                        }
                    }
                ]
            }
        },
        "kind": null,
        "title": "Add padding"
    },

```

If I can provide you with any more debug output, please let me know. Would be totally awesome if this plugin works with flutter projects.

**Comment by chemzqm** [comment]
The codeAction looks fine, what happens after you selected the codeAction by type number and enter?

**Comment by oblitum** [comment]
I've hit some (more or less) related problem while using another plugin, text that didn't get saved to disk wasn't updated by the editor: https://github.com/prabirshrestha/vim-lsp/pull/193#issuecomment-437724540.

Just a shot, it may make a difference here or not.

**Comment by wwwdata** [comment]
After selecting the code action by number nothing happened. The selection window closed and the text was unchanged.

**Comment by chemzqm** [comment]
I can reproduce this issue, the dart language server gives me:
```
[Trace - 9:46:55 AM] Received response 'textDocument/codeAction - (2)' in 17ms.
Result: [
    {
        "arguments": [],
        "command": "Ozxg4lFv",
        "title": "Surround with block"
    },
    {
        "arguments": [],
        "command": "0ueOxsW8",
        "title": "Surround with 'if'"
    },
    {
        "arguments": [],
        "command": "HeHkENPC",
        "title": "Surround with 'while'"
    },
    {
        "arguments": [],
        "command": "JDGI+vM+",
        "title": "Surround with 'for-in'"
    },
    {
        "arguments": [],
        "command": "jPZmLr9w",
        "title": "Surround with 'for'"
    },
    {
        "arguments": [],
        "command": "vNupaK2X",
        "title": "Surround with 'do-while'"
    },
    {
        "arguments": [],
        "command": "BMVfRxcx",
        "title": "Surround with 'try-catch'"
    },
    {
        "arguments": [],
        "command": "i+leU2+M",
        "title": "Surround with 'try-finally'"
    },
    {
        "arguments": [],
        "command": "eQuIKmEC",
        "title": "Convert to expression body"
    },
    {
        "arguments": null,
        "command": "XdAzscR/",
        "title": "Organize imports"
    },
    {
        "arguments": null,
        "command": "vK0pk9jP",
        "title": "Sort Members"
    }
]
```
The command is random id, and coc doesn't know how to deal with them.

**Comment by chemzqm** [comment]
Ok, find out there're `workspace/executeCommand` and `workspace/applyEdit` that needs to be implemented.

**Comment by chemzqm** [comment]
It's casued by incorrent merge of codeActions.

**Comment by wwwdata** [comment]
good job, can confirm that it works now on master!
