### ISSUE TITLE
I want Perl coc , coc-perl

### ISSUE THREAD

**Issue by YuseiUeno** [neoclide/coc.nvim#1770]
**Is your feature request related to a problem? Please describe.**
I cant use coc for perl script.
So, I want use `:CocInstall coc-perl`

**Describe the solution you'd like**
I don't know. But I think it's not easy.

**Comment by oblitum** [comment]
There's no coc-perl, but you may [configure](https://github.com/neoclide/coc.nvim/wiki/Language-servers) a language server like [Perl-LanguageServer](https://github.com/richterger/Perl-LanguageServer).

Then, you update the Wiki and add Perl to [the list of configured examples](https://github.com/neoclide/coc.nvim/wiki/Language-servers#example-configuration-for-custom-language-servers), or even [creating the coc-perl extension yourself](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#single-file-extensions) (also check [create-coc-extension](https://github.com/fannheyward/create-coc-extension) as a helper).

I'm closing this as it seems not relevant to the core project and needs to be provider independently.

**Comment by ryuta69** [comment]
@YuseiUeno 
Hi I created coc-perl. It works as same as VSCode.

https://github.com/ryuta69/coc-perl

<img width="1371" alt="ss 6" src="https://user-images.githubusercontent.com/41639488/92985689-f13eb080-f4ef-11ea-8924-8c546ea2f1b3.png">


@oblitum @chemzqm 
I'd like to add my extension into [wiki](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions), but I'm afraid if I need to get permissions from maintainers to edit wiki.

If so, may I edit ...?

**Comment by oblitum** [comment]
@ryantig it's open, you can edit and add it just fine.

**Comment by ryuta69** [comment]
Thank you, I added.
