### ISSUE TITLE
Does Coc.nvim ignore files in Gitignore? Can I tell it to unignore one?

### ISSUE THREAD

**Issue by domi91c** [neoclide/coc.nvim#1772]
**Is your feature request related to a problem? Please describe.**
In my projects, I usually have a scratch/ directory where I put examples and stuff related to my project. I put this directory in my .gitignore, which causes Solargraph to stop working for that directory. Is that a result of Coc.nvim or Solargraph?

**Describe the solution you'd like**
It'd be nice if I could tell Coc.nvim to not ignore a specific file or directory.

**Describe alternatives you've considered**

**Additional context**
I'm still not sure if this problem is related to Solargraph or Coc.nvim.

**Comment by chemzqm** [comment]
checkour available configurations
