### ISSUE TITLE
My cursor disappears after running :CocList if termguicolors is set

### ISSUE THREAD

**Issue by doronbehar** [neoclide/coc.nvim#1775]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-dev
node version: v13.13.0
coc.nvim version: 0.0.78-fc983ce6dd
term: tmux-256color
platform: linux
```

## Describe the bug

If I run `:CocList`, my cursor disappears afterwards and I'm left with no choice other then restarting Neovim.

## Reproduce the bug
 
- Create file `mini.vim` with：

  ```vim
  set termguicolors
  set runtimepath^=/path/to/coc.nvim
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Run:

```
:CocList
```

- Exit the CocList interface and you'll see the cursor is gone.

## Additional Context

I fear this is a change in Neovim-nightly's respect towards tmux + rxvt-unicode terminfo so I'm giving more info here:

I have this:

```
if-shell '[[ $TERM =~ "rxvt" ]]' 'set -g -a terminal-overrides '"'"',*:Ss=\E[%p1%d q:Se=\E[2 q'"'"
```

In my tmux configuration, per https://neovim.io/doc/user/term.html#tui-cursor-tmux but removing this line doesn't help.

Besides that, I'm compiling Neovim nightly my self every once in a while and I had a suspicion, this is related to the terminal related dependencies used for Neovim in my build, but I checked, and both libvterm and libtermkey are updated to the same version as in here: https://github.com/neovim/neovim/blob/master/third-party/CMakeLists.txt#L163

**Comment by doronbehar** [comment]
Now I see that the issue doesn't occur with Neovim 0.4.3 stable.

**Comment by chemzqm** [comment]
It support hide cursor on neovim >= 0.5.0.

Hide cursor:

```
set guicursor+=a:ver1-Cursor/lCursor
let s:saved_cursor = &guicursor
```
Show cursor:

```
set guicursor+=a:ver1-Cursor/lCursor
 let &guicursor = s:saved_cursor
```

**Comment by doronbehar** [comment]
Thanks for replying @chemzqm , I noticed you added the 'Can't reproduce' tag. Just to make sure: This happens only with all of these components used in conjunction:

- Rxvt-unicode
- Tmux
- Neovim unstable

As for that workaround you suggested, I tried to run this after a CocList: 

```vim
set guicursor+=a:ver1-Cursor/lCursor
```

And it didn't help :/. I also tried to run the commands in this order (right after startup):

```vim
set guicursor+=a:ver1-Cursor/lCursor
let s:saved_cursor = &guicursor
CocList
set guicursor+=a:ver1-Cursor/lCursor
let &guicursor = s:saved_cursor
```

And it didn't help either.

**Comment by chemzqm** [comment]
Command for hide cursor should be
``` vim
let s:saved_cursor = &guicursor
set guicursor+=a:ver1-CocCursorTransparent/lCursor
```
it may not work, but I don't know the way to fix

**Comment by doronbehar** [comment]
LOL, I tried it and Neovim crashed when it was inside rxvt+tmux and it made the cursor a horizontal line when it was inside rxvt without tmux. I guess I'll just revert to using Neovim stable.

I'll also close this as I know you don't like open issues and this is for Neovim unstable which is unstable.

**Comment by chemzqm** [comment]
You can disable that feature now.

**Comment by doronbehar** [comment]
Looks Good :). But I'll have to wait for the next release right? I'm using coc via the `release` branch and it doesn't include this change for as far as I can see.

**Comment by fabio-pardo** [comment]
hey @doronbehar did you find a solution for this? I seem to be reproducing the exact same thing.

**Comment by lithammer** [comment]
Try setting `let g:coc_disable_transparent_cursor = 1`.

https://github.com/neoclide/coc.nvim/blob/0a253304fdb0c50cef971fc9090b15b743f32080/doc/coc.txt#L1292-L1298

**Comment by fabio-pardo** [comment]
so far so good.... thanks @lithammer

**Comment by roschaefer** [comment]
> Try setting `let g:coc_disable_transparent_cursor = 1`.
> 
> https://github.com/neoclide/coc.nvim/blob/0a253304fdb0c50cef971fc9090b15b743f32080/doc/coc.txt#L1292-L1298

It took me a while until I found this issue and this fixes the problem for me.

For me, the bug appears every time I use `coc-references` or `CocList` and I exit via `<C-n>` instead of `Esc`.

Maybe it would help people to have `g:coc_disable_transparent_cursor` set to 1 by default?

**Comment by Meuko** [comment]
> Maybe it would help people to have g:coc_disable_transparent_cursor set to 1 by default?

Yes please, super annoying and as of now I'm still running in to this.
