### ISSUE TITLE
Escape backslashes in JS written inside <script> tags

### ISSUE THREAD

**Issue by alnj** [neoclide/coc.nvim#1776]
Same problem as [#752](https://github.com/neoclide/coc.nvim/issues/752)

## versions

vim version: NVIM v0.5.0-436-ge8269a3ab
node version: v13.12.0
coc.nvim version: 0.0.78-312c7c4482
term: xterm-256color
platform: linux

## Output channel: snippets

[Info 6:44:37 PM] Using ultisnips directories: UltiSnips /home/sensei/.config/coc/ultisnips
[Info 6:44:37 PM] Using ultisnips python command: pyx

## Describe the bug
When opening function documentation in preview window for javascript code in <script> tags in a .html or .php file, escape backslashes are often displayed in the doHover window

## Reproduce the bug

mini.vim:
```
set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else 
    call CocAction('doHover')
  endif                                                                                 
endfunction
```

Open .php or .html tag, put functions in <script> tags, open function documentation, escape backslashes appear for most functions (NOT ALL)

## Screenshots (optional)

![Screenshot from 2020-04-16 18-54-56](https://user-images.githubusercontent.com/1331748/79485237-2e704680-8015-11ea-99e5-dd32689ff274.png)

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by flw-cn** [comment]
@alnj You can try `Plug “flw-cn/vim-markdown”` which is a fork for `plasticboy/vim-markdown` and it automatically hides the backslash. see PR plasticboy/vim-markdown#515 to see exactly what it does.
