### ISSUE TITLE
Configuration to hide float not taking effect

### ISSUE THREAD

**Issue by kirsa** [neoclide/coc.nvim#1779]
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 13 2020 07:47:09)
node version: v13.12.0
coc.nvim version: 0.0.78-312c7c4482
term: iTerm.app
platform: darwin

## Output channel: snippets

[Info 22:33:06] Using ultisnips directories: UltiSnips /Users/Home/.config/coc/ultisnips
[Info 22:33:06] Using ultisnips python command: pyx

## Output channel: Python

Starting Jedi Python language engine.

## Describe the bug

Configuration option suggest.floatEnable set to false does not take effect and documentation still shows.

## Reproduce the bug

VIMRC

"COC completion
"" use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
    ▏ \ pumvisible() ? "\<C-n>" :
    ▏ \ <SID>check_back_space() ? "\<Tab>" :
    ▏ \ coc#refresh()
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Use D to show documentation in preview window.
nnoremap <silent> D :call CocAction('doHover')<CR>
" GoTo code navigation.
nmap <silent> <leader>gd <Plug>(coc-definition)
nmap <silent> <leader>gr <Plug>(coc-references)

JSON Config.

{
    "suggest.autoTrigger": "none",
    "suggest.floatEnable": false,
    "python.linting.enabled" : false
}

## Screenshots (optional)

<img width="493" alt="Screenshot 2020-04-16 at 22 49 16" src="https://user-images.githubusercontent.com/20098304/79509994-81a5c180-8034-11ea-9957-a818cb47c384.png">

**Comment by kirsa** [comment]
I would like to configure Coc so that the function documentation float doesn't automatically show up all the time without even triggering it. I would like to trigger it only when needed with my mapping shown in the VIMRC section.

**Comment by chemzqm** [comment]
Please read https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-could-i-disable-floating-window

**Comment by chemzqm** [comment]
> I would like to configure Coc so that the function documentation float doesn't automatically show up all the time without even triggering it.

`"signature.enable": false`

**Comment by kirsa** [comment]
thank you!

**Comment by kirsa** [comment]
Thank you!
