### ISSUE TITLE
Warning about python provider every time I open nvim

### ISSUE THREAD

**Issue by lourenci** [neoclide/coc.nvim#1780]
Every time I open nvim, the error below shows up.

This doesn't have any effect on the coc working, it's just an annoying warning. I noticed that it happens just in recent versions of coc.

Should I install the python provider? I don't want to do that. 

Thanks for this great plugin.

![image](https://user-images.githubusercontent.com/2339362/79513274-cc661000-8019-11ea-9435-02d0579fedb7.png)

**Comment by chemzqm** [comment]
Looks like you're using coc-snippets with ultisnips that use python, so you need python provider for neovim.
