### ISSUE TITLE
Error detected while processing function <SNR>56_AddAnsiGroups

### ISSUE THREAD

**Issue by arashm** [neoclide/coc.nvim#1781]
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 16 2020 21:51:57)
node version: v13.12.0
coc.nvim version: 0.0.78-312c7c4482
term: dumb
platform: linux

## Output channel: snippets

[Info 2:41:37 AM] Using ultisnips directories: UltiSnips /home/arashm/.config/coc/ultisnips
[Info 2:41:37 AM] Using ultisnips python command: pyx

## Describe the bug

Opening VIM throws an error:

```
Error detected while processing function <SNR>56_AddAnsiGroups:
line   18:
E254: Cannot allocate color 0
E254: Cannot allocate color 0
Press ENTER or type command to continue
```

## Reproduce the bug

Just use the latest Coc.nvim and start vim

## Screenshots (optional)

![Peek 2020-04-17 02-45](https://user-images.githubusercontent.com/849640/79523235-9050a080-8055-11ea-9010-e6c132ea6992.gif)

**Comment by chemzqm** [comment]
You have configured invalid colors, checkout `:echo g:terminal_ansi_colors`

**Comment by arashm** [comment]
Seems like an issue with my colorscheme. Thanks.
