### ISSUE TITLE
`coc-settings.json` not honored

### ISSUE THREAD

**Issue by scho7623** [neoclide/coc.nvim#1782]
## versions

vim version: NVIM v0.4.3
node version: v10.16.0
coc.nvim version: 0.0.78-865f3cca4a
term: iTerm.app
platform: darwin

## Output channel: watchman

[Info  - 10:40:59 PM] watchman watching project: /Users/sungho_cho/airlab-shared/repos/airbnb
[Info  - 10:40:59 PM] subscribing "**/[tj]sconfig.json" in /Users/sungho_cho/airlab-shared/repos/airbnb
[Info  - 10:40:59 PM] subscribing "**/package.json" in /Users/sungho_cho/airlab-shared/repos/airbnb
[Info  - 10:40:59 PM] subscribing "**/*.{ts,tsx}" in /Users/sungho_cho/airlab-shared/repos/airbnb
[Info  - 10:40:59 PM] subscribing "**/*.{js,jsx}" in /Users/sungho_cho/airlab-shared/repos/airbnb

## Output channel: tsserver

[Info  - 10:40:59 PM] Forking TSServer
PATH: /Users/sungho_cho/.nvm/versions/node/v10.16.0/bin:/Users/sungho_cho/airlab-shared/runtime_gems/tools/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/bin:/Users/sungho_cho/scripts:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/osquery/bin:/opt/airbnb/bin:/opt/puppetlabs/bin:/usr/local/munki:/usr/local/opt/fzf/bin 
[Info  - 10:40:59 PM] Started TSServer
{
  "path": "/Users/sungho_cho/airlab-shared/repos/airbnb/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.7.5",
    "version": "3.7.5"
  }
}

## Describe the bug
I edited `coc-settings.json` with `:CocConfig` to add custom insert mode key mappings for list like following, but the custom key mapping doesn't look like it's binding. `<C-j>` or `<C-k>` still not navigating the list.

```
{
  "list.insertMappings": {
    "<C-j>": "normal:j",
    "<C-k>": "normal:k"
  }
}
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Open `coc-settings.json` with `:CocConfig`

- Add following config:
```
{
  "list.insertMappings": {
    "<C-j>": "normal:j",
    "<C-k>": "normal:k"
  }
}
```
- Open a new file: `test.js`

- Try navigate auto complete suggestions with `<C-j>` and `<C-k>` and does not work

**Comment by chemzqm** [comment]
It's configuration for CocList, not completion list.

**Comment by scho7623** [comment]
@chemzqm Oh I see... Is there a similar key mapping for the completion list?

**Comment by chemzqm** [comment]
Read doc of vim.

**Comment by scho7623** [comment]
For anyone looking for the same, I had to add these to my init.vim file:
```
" navigate pop up with <C-j> and <C-k>
inoremap <expr> <C-j> pumvisible() ? "\<C-n>" : "\<C-j>"
inoremap <expr> <C-k> pumvisible() ? "\<C-p>" : "\<C-k>"
```
