### ISSUE TITLE
How to make <CR> not complete the suggestion

### ISSUE THREAD

**Issue by alifhughes** [neoclide/coc.nvim#1785]
Hey, this is a general question.

I was wondering how it is possible to make `<CR>` not complete the current suggestion. I know that `<CR>` isn't mapped to anything in `vim`, when I run `:verbose imap <CR>` the result is: `No mapping found`.

When a suggestion comes up like below and I press enter, it will complete that suggestion. Is there a way to stop this behaviour?
<img width="339" alt="Screen Shot 2020-04-17 at 3 12 16 PM" src="https://user-images.githubusercontent.com/9354142/79578231-dd685d00-80bd-11ea-8a6a-59ce401c1be9.png">

Many thanks.

**Comment by chemzqm** [comment]
It's vim's behavior, you can remap `<CR>` yourself.

**Comment by alifhughes** [comment]
I feel like remapping `<CR>` could cause strange behaviour elsewhere, do you have any suggestions how to do this?

**Comment by chemzqm** [comment]
`  inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
`
It's up to you.

**Comment by alifhughes** [comment]
Cool thank you, that was helpful. Sorry for nooby question!
