### ISSUE TITLE
Cannot make Coc work on Python files. Besides, need help with loclist.

### ISSUE THREAD

**Issue by Adityashaw** [neoclide/coc.nvim#1786]
I am trying to shift from ALE to CoC wherever possible.
I have two issues :
1. I can't make coc lint on Python files (py). I have installed `coc-python`, `pylint`, `jedi`, `jedi-lanuage-server`. I don't know if this issue is about _coc_ or _coc-python_ as _coc-java_ seems to work, though not as I want.
:CocConfig shows
```{
    "coc.preferences.extensionUpdateCheck" : "never",
    "diagnostic.refreshOnInsertMode" : "true",
    "python.linting.enabled" : "true",
    "python.linting.pylintArgs" : ["--load-plugins", "pylint-flask", "pylint-flask-sqlalchemy", "pylint-sqlalchemy"]
}
```
:CocOpenLog shows
[CocOpenLog on gist](https://gist.github.com/Adityashaw/ecdaf935762f6b2f1f301afc54fd3412)

:CocInfo shows
```
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2020 17:21:03)
node version: v13.12.0
coc.nvim version: 0.0.78-312c7c4482
term: dumb
platform: linux

## Output channel: Python

Starting Jedi Python language engine.
##########Linting Output - pylint##########
##########Linting Output - pylint##########

```
My `.vimrc` : [vimrc](https://gist.github.com/Adityashaw/8ac76b0a7ab22601a831bdef4dbb126a)
Python Interpreter is shown correctly. ALE is disabled for Python and Java. I want to use CoC. 
`:CocCommand workspace.showOutput` shows a pop-up with two options : _1. Python_ and _2.  info_. 1 opens an empty window while 2 shows the same as :CocInfo (only the last 3 lines).
`:CocList services` does not show any service.

2. I can't make coc show location list automatically whenever there is any diagnostic available (for java files. (In ALE, it was automatic.) Entering `lopen` does show the loclist but vanishes as soon as I press `<Esc>`. Any of these two options will suffice  : 

- Permanently keep loclist open
- Show loclist whenever there is any diagnostic

**Comment by chemzqm** [comment]
Run `:CocLocalConfig` in your project to check local configuration, and check log from coc-python.

> I can't make coc show location list automatically

Location list is used for diagnostic of current window, unless you have disabled it.

> I can't make coc show location list automatically whenever there is any diagnostic available

You have to use autocmd yourself, `:h coc-autocmds`

> Permanently keep loclist open

Won't support that, I don't think it makes any sense since each window have location list.
You can implement it yourself.

> Show loclist whenever there is any diagnostic

Use autocmds.

**Comment by Adityashaw** [comment]
> Run :CocLocalConfig in your project to check local configuration

There's no local configuration file. Entering that command and then pressing **y** results in a new file being created.
> and check log from coc-python.

I have attached CocOpenLog. Is there any extra log file?

> You have to use autocmd yourself, :h coc-autocmds

Sorry, but I honestly do not understand the doc. It gives an example to disable loclist but that is not my intention. I want loclist to show whenever there's any diagnostic. Can you please provide the exact command I need to add to my `.vimrc`?

**Comment by chemzqm** [comment]
No
