### ISSUE TITLE
Support for shell properties in languageserver of type moduel.

### ISSUE THREAD

**Issue by yuki-ycino** [neoclide/coc.nvim#1790]
**Is your feature request related to a problem? Please describe.**

I want to set up apollographql as a langserver with coc-settings.json.
apollographql language server is a MODULE type and cannot be specified by the SHELL property.

Since I need to use an absolute path for module properties, I need to write the setting to coc-sessing.json using a function like `expand`.

**Describe the solution you'd like**

```vim
call coc#config('languageserver', {
\ 'graphql': {
\   'module': expand('~/repos/github.com/apollographql/apollo-tooling/packages/apollo-language-server/lib/server.js'),
\   'args': ['--node-ipc'],
\   'filetypes': ['graphql', 'javascript', 'javascriptreact', 'typescript', 'typescriptreact', 'typescript.tsx'],
\   'rootPatterns': ['apollo.config.js']
\ }
\ })
```

```json
  "languageserver": {
    "graphql": {
      "module": "expand('~/repos/github.com/apollographql/apollo-tooling/packages/apollo-language-server/lib/server.js')",
      "args": ["--node-ipc"],
      "filetypes": [
        "graphql",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "typescript.tsx"
      ],
      "rootPatterns": ["apollo.config.js"],
      "shell": true
    }
  }
```

**Comment by fannheyward** [comment]
Does I miss anything but why can't you use absolute path in `coc-settings.json`?

**Comment by yuki-ycino** [comment]
It's hard to embed absolute paths in JSON because you're using dotfiles on multiple machines.
If I can specify the path from my home directory this problem will be solved.
