### ISSUE TITLE
VSCode supports folder level workspace settings, where CocLocalConfig only supports repo level

### ISSUE THREAD

**Issue by ayroblu** [neoclide/coc.nvim#1792]
**Is your feature request related to a problem? Please describe.**
`CocLocalConfig` creates and uses `$(repo)/.vim/coc-settings.json` ONLY. Where vscode simply takes the current directory. So if I have a `$(repo)/proj1/.vscode/settings.json` and `$(repo)/proj2/.vscode/settings.json` and I open it inside `$(repo)/proj1` then I get `proj1` settings. This is not supported by `coc.nvim`

**Describe the solution you'd like**
Support `$(pwd)/.vim/settings.json`. This means that opening any file while staying in the "workspace" directory will use the workspace settings. It may do traversal upwards for example if you're in a sub directory, but this is a stretch goal.

**Describe alternatives you've considered**
Manually setting things by regexing directories - doesn't scale
Using the same config everywhere - extremely difficult with other stakeholders

**Additional context**

**Comment by chemzqm** [comment]
It doesn't have workspace level configuration, but folder level

**Comment by ayroblu** [comment]
What do you mean?
If `$(pwd)` = `$(repo)/proj1` when opening a file `:CocLocalConfig` creates and opens `$(repo)/.vim/coc-settings.json`

**Comment by chemzqm** [comment]
It's detected workspace folder, you can change it, please read wiki

**Comment by ayroblu** [comment]
Ahhh I see, thanks so much, apologies for not seeing this before! https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders
Solution for anyone else is that to mimic vim's `set exrc` or vscode's workspaces assuming you always open files from the root of your project (cwd), just set:
```
  "coc.preferences.rootPatterns": [],
```
