### ISSUE TITLE
ignoredRootPaths needs to use the realpath of path

### ISSUE THREAD

**Issue by derekschrock** [neoclide/coc.nvim#1798]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 08:33:20)
node version: v13.10.1
coc.nvim version: 0.0.78-2da346d9b3
term: dumb
platform: freebsd

## Describe the bug

When '\~' is used with `ignoredRootPaths` '\~' is replaced with `os.homedir()` https://github.com/neoclide/coc.nvim/blob/713767dc827dd1505a713b9a5d9b8023652af751/src/services.ts#L393 

`os.homedir()` uses the HOME env. var or the passwd database's path, however if either has a symlink when it comes time to compare `ignoredRootPaths` with the file path the root path will be ignored. 

https://github.com/neoclide/coc.nvim/blob/713767dc827dd1505a713b9a5d9b8023652af751/src/language-client/client.ts#L3533

 I believe this would be true for any path not just paths with '\~' so should the `ignoredRootPaths.map(...)` be using `fs.realpathSync(...)` to translate the path at config loading time?

```typescript
ignoredRootPaths.map(s => fs.realpathSync(s.replace(/^~/, os.homedir())))
```

## Reproduce the bug

Have a path in `ignoredRootPaths` for a language server that has a sym. link in the path.
In my case it's `bash-language-server`

`coc-settings.json`
```json
...
        "languageserver": {
                "bash": {
                  "command": "bash-language-server",
                  "args": ["start"],
                  "filetypes": ["sh"],
                  "ignoredRootPaths": ["~"]
                }
          },
...
```

```bash
$ ls -ld "$HOME"
drwxr-xr-x  92 dereks  dereks  19456 Apr 21 00:43 /home/dereks/
$ realpath "$HOME"
/usr/home/dereks
$ ls -ld /home
lrwxr-xr-x  1 root  wheel  8 Nov 21  2012 /home@ -> usr/home

```

- Open a sh/bash file from your home dir `vi ~/.bashrc` and see coc doesn't ignore the file.
- Change the `ignoredRootPaths` to be real path or change HOME and see coc now ignoring with the `[coc.nvim] Ignored rootPath...` message

**Comment by chemzqm** [comment]
You should not use symbol link with `ignoredRootPaths`
