### ISSUE TITLE
Completion and/or snippets that include special characters not working

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#180]
**Describe the bug**
- Completion for header inclusion for C and C++ isn't working.
    - It's a header completion after a UltiSnip snippet expansion
- Completion for template types too.
    - Stripped text as insertion text
    - Only usable if snippet gets expanded

Both involve the presence of the `<` character.

**To Reproduce**

Just try including a header through a UltiSnip snippet expansion, or accepting template type suggestions without expanding snippets.

**Expected behavior**

Inclusion after UltiSnip snippet expansion should simply fill the header, not a new full `#include` directive.

Templates shouldn't come with `<...`, just the name. `<...>` should be included if snippet is expanded solely.

**Screenshots**

Header inclusion behavior:

![include](https://user-images.githubusercontent.com/1269815/48974232-8762c780-f039-11e8-9663-044a7a81e3d4.gif)

Template behavior:

![vector](https://user-images.githubusercontent.com/1269815/48974251-5931b780-f03a-11e8-8bc6-cd034adc5548.gif)

**Desktop (please complete the following information):**
 - Terminal: Termite
 - Version: v14

**Comment by chemzqm** [comment]
Which language server are you using?

**Comment by oblitum** [comment]
ccls, my current conf is:

```json
{
  "coc.preferences.echodocSupport": true,
  "coc.preferences.triggerSignatureHelp": false,
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "objc", "objcpp"],
      "initializationOptions": {
        "cacheDirectory": "/tmp/ccls"
      }
    }
  }
}
```

**Comment by chemzqm** [comment]
Extract for inserted word could be improved.

**Comment by oblitum** [comment]
@chemzqm header inclusion (first gif) is still not working.

**Comment by oblitum** [comment]
@chemzqm yes :)
