### ISSUE TITLE
Support language level settings like vscode

### ISSUE THREAD

**Issue by ayroblu** [neoclide/coc.nvim#1800]
**Is your feature request related to a problem? Please describe.**
Vsocde allows for language level configuration like:
```
{
  "[python]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": false
    }
  }
}
```
This is not possible in coc-settings.json (well the linter complains at least)

**Describe the solution you'd like**
Support vscode like language level configuration

**Describe alternatives you've considered**
Manually changing it by language

**Additional context**

**Comment by chemzqm** [comment]
PR welcome.

**Comment by pedromss** [comment]
I was thinking on picking this up. I've seen where the config gets loaded and adding a language level settings doesn't break that loading process. Example (`suggest.autoTrigger` is overriden for `golang`):


```
{
    "suggest.autoTrigger": "always",
        "golang": {
          "suggest.autoTrigger": "never",
          "command": "gopls",
          "rootPatterns": [
            "go.mod",
            ".vim/",
            ".git/",
            ".hg/"
          ],
          "filetypes": [
            "go"
          ]
        }
}
```

Now I guess I'll check where the config actually takes effect and load different configs depending on the file type (assuming the filetype overrides the root configs)

**Comment by HanleyLee** [comment]
I want this feature, anyone make a PR?
