### ISSUE TITLE
Add Option to Disable setqflist() after WorkspaceEdit or Use Alternative UI to Prompt Users

### ISSUE THREAD

**Issue by chengzeyi** [neoclide/coc.nvim#1804]
**Is your feature request related to a problem? Please describe.**

My workflow when debugging a program is to use `FZF` or `:vimgrep` to search all the related positions in the source file directory. And jump around them using `:cnext` and `:cprevious` to apply fix editing. However, after a latest update of `coc.nvim`, `workspaceEdit` would call `setqflist()` to prompt the user the changes. This behaviour breaks my orignal quickfix list, forcing me to regenerate the quickfix list to continue my work.

**Describe the solution you'd like**

Add an option to disable setqflist() after WorkspaceEdit.
Or user another list interface rather than Quickfix list, as its original usage is important for users to jump to compilation error or grep result positions.

**Describe alternatives you've considered**

Use coc list to provide a better and independent user interface for checking out workspaceEdit.

**Additional context**

No.

**Comment by fannheyward** [comment]
Does `coc.preferences.promptWorkspaceEdit` work for you?

**Comment by chengzeyi** [comment]
> Does `coc.preferences.promptWorkspaceEdit` work for you?

Sorry, setting this has no effect at all. The quickfix list would still be filled by coc.nvim

I have checked the source code in workspace.ts. Seems that the quickfix list would get filled after workspaceEdit under any circumstance.

**Comment by chengzeyi** [comment]
And, often the entries in the Quickfix list cannot provide any useful message. In many situations the entry for each file in the list is always `1 col 1`, the first line and the first column, showing no context information of the change.

**Comment by chemzqm** [comment]
You can use `:colder`

**Comment by chengzeyi** [comment]
> You can use `:colder`

Thank you for providing the workaround., a very useful VIM command omitted by myself. But I still hope there will be an additional option to disable this feature like `coc.preferences.promptWorkspaceEdit` to get rid of bother, thanks.

**Comment by chemzqm** [comment]
PR welcome.
