### ISSUE TITLE
Installing coc extensions with yarn instead of npm

### ISSUE THREAD

**Issue by HassanZahin** [neoclide/coc.nvim#1806]
It seems like Coc.nvim installs the dependencies of the extentions with npm. Npm does not work well with poor internet connection like I have. Is there any ways to replace npm with yarn? Also I request you to swap npm with yarn in the next update.
 
![image](https://user-images.githubusercontent.com/61543143/80084304-827cad00-8578-11ea-857d-bf60340d82d6.png)

**Comment by fannheyward** [comment]
Set `"npm.binPath": "yarn"` to your coc-settings.json.

**Comment by HassanZahin** [comment]
Thanks. But now this error shows:

![image](https://user-images.githubusercontent.com/61543143/80085875-b1941e00-857a-11ea-8ab8-00447adbed43.png)

![image](https://user-images.githubusercontent.com/61543143/80086007-e7d19d80-857a-11ea-8e7e-2cd44d752b69.png)

**Comment by fannheyward** [comment]
Looks like this error https://github.com/yarnpkg/yarn/issues/6029

**Comment by HassanZahin** [comment]
Hmm seems like I can bypass this issue by going to coc-vetur and manually installing with:
`yarn --registry "https://registry.npmjs.org"`

But it returns:
`yarn install v1.22.4
warning ../../package.json: No license field
info No lockfile found.
[1/5] Validating package.json...
warning coc-vetur@1.1.10: The engine "coc" appears to be invalid.
[2/5] Resolving packages...
warning vls > stylus > css-parse > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning vls > stylus > css-parse > css > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning vls > stylus-supremacy > stylint > chokidar@1.5.2: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning vls > @starptech/prettyhtml > unified > @types/vfile > @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
warning vls > stylus > css-parse > css > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning vls > stylus-supremacy > stylint > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack > watchpack > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
[3/5] Fetching packages...
[##################################################################################################################-] 920/928^info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-plugin-vue@6.2.2" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "eslint-plugin-vue > vue-eslint-parser@7.0.0" has unmet peer dependency "eslint@>=5.0.0".
[5/5] Building fresh packages...
success Saved lockfile.
$ npx npm-run-all clean build
npx: installed 60 in 23.455s
yarn run v1.22.4
warning ../../package.json: No license field
warning coc-vetur@1.1.10: The engine "coc" appears to be invalid.
$ rimraf lib
Done in 0.60s.
yarn run v1.22.4
warning ../../package.json: No license field
warning coc-vetur@1.1.10: The engine "coc" appears to be invalid.
$ webpack

Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 8e3e74e5cdc261666b84
Version: webpack 4.43.0
Time: 39ms
Built at: 04/23/2020 5:40:33 PM

ERROR in Entry module not found: Error: Can't resolve './src/index.ts' in '/home/zahin/.config/coc/extensions/node_modules/coc-vetur'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

**Comment by HassanZahin** [comment]
I think it tries to build from the source  code again.

**Comment by HassanZahin** [comment]
Can't build from source

**Comment by HassanZahin** [comment]
reported [https://github.com/neoclide/coc-vetur/issues/31](url)
