### ISSUE TITLE
Strange behavior of coc-definition for local variables

### ISSUE THREAD

**Issue by mlrv** [neoclide/coc.nvim#1808]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 13 2020 07:47:09)
node version: v12.14.1
coc.nvim version: 0.0.78-fc983ce6dd
term: iTerm.app
platform: darwin

## Output channel: tsserver

[Info  - 22:55:20] Forking TSServer
PATH: /Users/marco/.cabal/bin:/Users/marco/.ghcup/bin:/Users/marco/.cabal/bin:/Users/marco/.ghcup/bin:/Users/marco/google-cloud-sdk/bin:/Users/marco/.sdkman/candidates/java/current/bin:/Users/marco/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/marco/.cargo/bin:/Users/marco/.local/bin:/Users/marco/.local/bin:/Users/marco/dotfiles/utils 
[Info  - 22:55:20] Started TSServer
{
  "path": "/Users/marco/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.8.3",
    "version": "3.8.3"
  }
}

## Output channel: eslint

[Info  - 22:55:20] ESLint server running in node v12.14.1
[Info  - 22:55:21] ESLint library loaded from: /Users/marco/dev/permutive-javascript/node_modules/eslint/lib/api.js


```

## Describe the bug

1. Install `coc-tsserver` (I have version 1.5.1)
2. Open a typescript project (I've also reproduced this with a Scala project)
3. Observe that go-to-definition for variables imported from a node_module work properly
4. Instead, go-to-definition for variables defined in other files of the project seem to block vim (as in, the cursor can't be moved anymore). However, cancelling the operation via `<C-c>` correctly takes you to the definition. After that, `coc` reports this error:
```
[coc.nvim] Error on 'jumpDefinition': request error nvim_call_function - Vim:Interrupt
```

## Minimal vimrc

```
execute pathogen#infect()
set hidden
set nobackup
set nowritebackup
set cmdheight=2
set updatetime=300
set shortmess+=c
set signcolumn=yes
nmap <silent> gd <Plug>(coc-definition)
```

**Comment by chemzqm** [comment]
We need debug log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc.
* Restart your vim/neovim to make the issue happen.
* Open the log file by command `:call coc#client#open_log()`.
* Attach the log file or paste content from the log.

**Comment by mlrv** [comment]
Thanks for the quick response @chemzqm , I've pasted the full logs in a [gist](https://gist.github.com/mlrv/f6f8d298c64e1ee801086066013fc909).

**Comment by chemzqm** [comment]
Should be problem of your vim, but it should be fixed now by using notification to vim.
