### ISSUE TITLE
【show_documentation】 内容当中有 "*" 时，显示不正常

### ISSUE THREAD

**Issue by xiaopengli89** [neoclide/coc.nvim#1811]
<img width="554" alt="截屏2020-04-25 下午6 36 53" src="https://user-images.githubusercontent.com/11287532/80277859-88af8c80-8724-11ea-827b-a97ce942da5d.png">
<img width="802" alt="截屏2020-04-25 下午6 37 26" src="https://user-images.githubusercontent.com/11287532/80277862-8a795000-8724-11ea-97b5-485fbafb5e4e.png">

**Comment by xiaopengli89** [comment]
我使用的是  `coc-rust-analyzer` 插件，我不确定是不是该插件的原因

**Comment by chemzqm** [comment]
You should try minimal vimrc

**Comment by xiaopengli89** [comment]
抱歉，这应该是 `coc-rust-analyzer` 插件的原因，`coc-tsserver` 插件显示 typescript 没有此问题

**Comment by chemzqm** [comment]
应该是你 syntax 插件原因
