### ISSUE TITLE
Ability to configure the test runner

### ISSUE THREAD

**Issue by vn-ki** [neoclide/coc.nvim#1812]
**Is your feature request related to a problem? Please describe.**
I would like to configure the way the tests are run (in coc-rust-analyzer).

For example, in code lens, there is run test.

When I do `codelens-action` and run the test, it is run as a split terminal.

I would like to configure how it run. I propose a solution similar to asynctasks, [see here](https://github.com/skywind3000/asynctasks.vim/wiki/Customize-Runner)

**Describe the solution you'd like**
I propose a solution similar to asynctasks, [see here](https://github.com/skywind3000/asynctasks.vim/wiki/Customize-Runner)

**Comment by chemzqm** [comment]
Wrong repo.

**Comment by vn-ki** [comment]
@chemzqm IMO, coc should provide a way for the plugins to open and use terminal so that the process is standardised.
