### ISSUE TITLE
Empty popup leaked through race in floatFactory

### ISSUE THREAD

**Issue by sam-mccall** [neoclide/coc.nvim#1816]
In the regular course of using clangd, coc will eventually "black out" a small 3x1 region in the center of the window:

![square](https://user-images.githubusercontent.com/548993/80323486-eaa6e980-882b-11ea-890d-c36e7c9658f9.gif)

The region is an empty popup created via `floatFactory`, and will **never be cleared** by coc, resulting in "dead cells" in the window.
Because it is never cleared once it occurs, this is a difficult bug to live with despite being rare/flaky/hard to reproduce :-(

I've finally managed to track this down. I don't have a tiny reliable repro but the following help:
 - use vim8, not neovim
 - `autocmd User * sleep 1` to increase the chance of hitting the race
 - perform an edit that generates different diagnostics in sequence as you type

The problem occurs when `FloatFactory.checkFloatBuffer()` is entered twice concurrently. While `await createPopup()` is blocked, we try to process another set of diagnostics, end up back in `checkFloatBuffer()` and call `createPopup()` again. The result of each call is written to `this.popup` so one of the popup window IDs is leaked.
(Confirmed this sequence with logging)

I'm not sure exactly what the best fix is, I'll try to come up with a patch, you might have better ideas.

**Comment by chemzqm** [comment]
Looks like it triggers `CursorHold` event again and again.

**Comment by sam-mccall** [comment]
Yeah, multiple CursorHolds (though just a few, not lots in a tight loop).
The trick to reproduce it is to get the following sequence:

 - diagnostics from LS
 - CursorHold --> show float for diagnostics
 - block on creating popup window 1
 - new diagnostics from LS
 - CursorHold --> show float for diagnostics
 - block on creating popup window 2
 - popup window 1 is created
 - popup window 2 is created (and we lose track of popup window 1)

The trick is getting the diagnostics and CursorHold events to arrive at the right time. I haven't been able to get a nice test for this directly, but in the PR the decorator is tested and hopefully the use of it is clear by inspection.

**Comment by chemzqm** [comment]
Should be fixed now.
