### ISSUE TITLE
Calling Format folds all the file

### ISSUE THREAD

**Issue by romariolopezc** [neoclide/coc.nvim#1817]
## Result from CocInfo
```
<!--Run `:CocInfo` command and paste the content below.-->
[Info  - 8:51:09 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:51:09 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:51:09 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:51:09 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:51:09 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:51:09 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:51:09 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:51:09 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:52:18 PM] A code lens was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:52:18 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:52:18 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:52:18 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:52:18 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:52:18 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
[Info  - 8:52:18 PM] A code lens resolve was requested for file:///home/rlopez/repos/elm/frontend/src/elm/Managers/Page/Calendar/Events.elm
```
## Describe the bug

When calling `:call CocActionAsync('format')`, all of the functions in the file are folded automatically.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
  filetype plugin indent on
  syntax on
  set foldmethod=indent
  set foldnestmax=10
  set nofoldenable
  set foldlevel=2
  set foldopen-=block
```

I don't know how to reproduce it because it doesn't always happen. This is the 3rd time it happens to me. I debugged the `:CocInfo` but didn't find anything weird

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/6199588/80327133-aa7e4180-8800-11ea-874c-57e8ff263848.png)

**Comment by fannheyward** [comment]
`:call CocActionAsync('fold')` will do fold action, do you misspelling it?

**Comment by romariolopezc** [comment]
No, I don't want to fold anything. Calling Format folds the file without me wanting to fold

**Comment by romariolopezc** [comment]
I found this, is reproducible for me, I think? @fannheyward 

![coc-format-folding](https://user-images.githubusercontent.com/6199588/80329774-f339f880-8808-11ea-80f1-7213ec9d617f.gif)

As you can see, I just use the snipper and it becomes folded

**Comment by chemzqm** [comment]
We need debug log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc.
* Restart your vim/neovim to make the issue happen.
* Open the log file by command `:call coc#client#open_log()`.
* Attach the log file or paste content from the log.

**Comment by romariolopezc** [comment]
[coc-debug.log](https://github.com/neoclide/coc.nvim/files/4540179/coc-debug.log)

It's a big file!

**Comment by chemzqm** [comment]
Should be caused by your other vim plugin.

**Comment by romariolopezc** [comment]
What other vim plugin? Can you give me more info to debug?

**Comment by chemzqm** [comment]
Try use minimal vimrc.

**Comment by chemzqm** [comment]
> `:call CocActionAsync('fold')` will do fold action, do you misspelling it?

Consider create new issue and provide reproduce way.
