### ISSUE TITLE
Add the ability to disable :CocLocalConfig

### ISSUE THREAD

**Issue by jlescher** [neoclide/coc.nvim#1818]
**Is your feature request related to a problem? Please describe.**
The feature request is related to a use-case scenario.

I need the concept of a workspace (to list files / symbols / ..).
However by default, when using CocCommand "python.setLinter" , I would like that setting to go into .config/nvim/coc-settings.json instead of the current workspace.

**Describe the solution you'd like**
let workspace_local_config = 'false'

**Comment by chemzqm** [comment]
No
