### ISSUE TITLE
coc.preferences.diagnostic.locationlist setting is ignored

### ISSUE THREAD

**Issue by RobertBuhren** [neoclide/coc.nvim#182]
**Describe the bug**
The setting "coc.preferences.diagnostic.locationlist" is currently ignored. Each of the following settings results in the location list being populated with the current errors/warnings:

- No "coc.preferences.diagnostic.locationlist" entry in CocConfig
- "coc.preferences.diagnostic.locationlist":  true
- "coc.preferences.diagnostic.locationlist ": false

**Expected behavior**
In case of "coc.preferences.diagnostic.locationlist" : false,  the location list should never contain errors/warnings.

My current configuration:
```
{
  "languageserver": {
    "clangd": {
      "command": "clangd",
      "filetypes": ["c", "cpp", "objc", "objcpp"]
    }
  },
  "coc.preferences.diagnostic.errorSign": "✗" ,
  "coc.preferences.diagnostic.warningSign": "⚠",
  "coc.preferences.diagnostic.locationlist": false
}
```
**Additional context**
The language servers in use here were: "clangd" and "coc-pyls"

I guess in the future it would be preferable if the user could specify "quickfix", "locationslist", "none" as options to place the current errors/warnings.

Regards,
Robert

PS: Awesome plugin! Finally good code completion in vim!

**Comment by chemzqm** [comment]
Coc use "quickfix" for jump locations, it will be hard to use if diagnostic also use quickfix.
The recommended list manager is denite, use `Denite coc-diagnostic` to get the list, or user could build their own list by use the API provided by coc.

**Comment by RobertBuhren** [comment]
Thanks for the quick reply. Unfortunately the issue is still there. I'm on 082ba4494bfb11e66a82e92e9089a564df142372 and the location list is still populated.

Regards,
Robert

**Comment by chemzqm** [comment]
New release is not available, try `yarn install` to build from source code.
