### ISSUE TITLE
Increase cmdheight only when needed

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc.nvim#1821]
**Is your feature request related to a problem? Please describe.**
I prefer to have minimalistic Vim interface with `set cmdheight=1`, but when diagnostics encountered this causes troubles and screen flickering which is fixed by using `set cmdheight=2` instead

**Describe the solution you'd like**
Would be nice to have `cmdheight` increased to 2 automatically and then back again, as is already done in case of `signcolumn` when diagnostics for buffer are available.

**Comment by chemzqm** [comment]
No, we don't want to change global vim option as much as possible,  unless it won't work.

**Comment by chemzqm** [comment]
I don't have flicking when cmdheight is `1`,  minimal vimrc needed.
