### ISSUE TITLE
Add pasting support for INTERACTIVE/FUZZY inputs

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc.nvim#1822]
**Is your feature request related to a problem? Please describe.**
When calling `:CocList grep`, for example. I'm presented with `INTERACTIVE` input field, to which I'm unable to paste any text with neither <Alt+Ctrl+V> nor <Shift+Ins>.

**Describe the solution you'd like**
I'd like `INTERACTIVE` & `FUZZY` inputs to have pasting support.

**Describe alternatives you've considered**
Providing text manually or pasting it when typing `:CocList grep <here>`

**Comment by chemzqm** [comment]
Please read help

**Comment by arbitrary-dev** [comment]
Ok, I see, it's <Ctrl+V> and `xsel` available on the system… Thanks
