### ISSUE TITLE
Copied text cleared when :CocList invoked

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc.nvim#1823]
## Result from CocInfo

```
vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar  4 2020 10:55:18)
node version: v12.16.1
coc.nvim version: 0.0.77-817efd5108
term: dumb
platform: linux
```

## Describe the bug

Copied text cleared when any `:CocList` invoked

## Reproduce the bug

1. Copy something
1. Paste it with `p` in Vim
1. Call `:CocList`
1. Close it with Esc
1. Paste with `p` again
1. Empty line pasted instead

**Comment by chemzqm** [comment]
Should be caused by other vim plugin.
