### ISSUE TITLE
Duplicate Suggestions in autocompletion

### ISSUE THREAD

**Issue by saurabh-kushwah** [neoclide/coc.nvim#1824]
## versions

vim version: NVIM v0.5.0-dev
node version: v14.0.0
coc.nvim version: 0.0.78-70aac81740
term: xterm-256color
platform: linux

## Describe the bug

Duplicate Suggestions in autocomplete for C/C++ (clangd) , golang ..etc

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

My `vimrc` and coc-settings 
https://github.com/saurabh-kushwah/DotFiles/tree/master/vim
## Screenshots 
![Screenshot from 2020-04-27 07-00-35](https://user-images.githubusercontent.com/50158675/80390593-40ca6a00-88ca-11ea-9993-2e083231f662.png)

**Comment by chemzqm** [comment]
Check your source list

**Comment by saurabh-kushwah** [comment]
Can you provide with more details??

**Comment by fannheyward** [comment]
`:CocList services`

**Comment by saurabh-kushwah** [comment]
![Screenshot from 2020-04-28 07-27-46](https://user-images.githubusercontent.com/50158675/80438437-d04f3780-8921-11ea-95d2-646626b3aa84.png)

**Comment by fannheyward** [comment]
Open a C/C++ file, and `:CocList services` again, what's the output?

**Comment by fannheyward** [comment]
And what's the `:CocList sources`?

**Comment by saurabh-kushwah** [comment]
![Screenshot from 2020-04-28 07-56-55](https://user-images.githubusercontent.com/50158675/80440195-dc3cf880-8925-11ea-8b8b-5ee28cd2f0a7.png)

**Comment by fannheyward** [comment]
This shouldn't happen to duplicate suggestions for C/C++.

**Comment by saurabh-kushwah** [comment]
I initially intended to give you `golang` screenshot.

I think i does for  `gopls` and language server is running at the same time.
![Screenshot from 2020-04-28 08-21-05](https://user-images.githubusercontent.com/50158675/80441825-59b63800-8929-11ea-989d-613cd8824469.png)

**Comment by fannheyward** [comment]
Are you using `coc-go`? You should choose only one, use `coc-go` or `languageserver.golang` in your `coc-settings.json`.

**Comment by saurabh-kushwah** [comment]
No, I  use `vim-go` which uses on `gopls` .
I followed this article
https://octetz.com/docs/2019/2019-04-24-vim-as-a-go-ide/

**Comment by fannheyward** [comment]
What's your `:CocList extensions`?

**Comment by saurabh-kushwah** [comment]
It listed `coc-go` but I  removed from `init.vim`  a long ago.Seems it wasn't uninstalled.
I removed using `CocUninstall coc-go` .
It's working correctly.

Thanks for the help !!
