### ISSUE TITLE
New install results in "[coc.nvim] Can't find npm or yarn in your $PATH"

### ISSUE THREAD

**Issue by sbromberger** [neoclide/coc.nvim#1826]
## Result from CocInfo
```
  1 ## versions                                                                                                                                       
  2 
  3 vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 27 2020 08:42:31)
  4 node version: v10.15.2
  5 coc.nvim version: 0.0.78-9febe802b3
  6 term: dumb
  7 platform: linux
  8 
```

## Describe the bug

I did an install following the instructions, using Plug: `Plug 'neoclide/coc.nvim', {'branch': 'release'}  `. Immediately after `PlugInstall`, I got this warning in my messages. I also get it every time I start `vim`, and when I try to use `CocInstall`.

## Reproduce the bug

vimrc:
```vim
set nocompatible
filetype plugin indent on
syntax on
set hidden
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

## Screenshots (optional)

demonstration here: https://asciinema.org/a/URaUE14Cch7Hg6Ev4choQGl1C

**Comment by sbromberger** [comment]
setting `"coc.preferences.extensionUpdateCheck": "never"` in coc-settings.json gets rid of the error on startup.

**Comment by fannheyward** [comment]
Updating extensions needs npm/yarn, and some extensions installation also need npm/yarn. I recommend to install npm/yarn, if you really don't like them, you may fail to do `:CocInstall` on some extensions.

**Comment by JDtheGeek** [comment]
Same issue, but have node/npm installed, possibly due to being installed via nvm (node version manager)? 
 
Added `let g:coc_node_path = '/home/jd/.nvm/versions/node/v11.15.0/bin/node'` to the init.vim which got rid of my initial issue with the node path but now I'm getting the same error as OP where it can't find npm or yarn.

`which npm` returns `/home/jd/.nvm/versions/node/v11.15.0/bin/npm`

**Comment by imjasonmiller** [comment]
@JDtheGeek setting the following key in my `coc-settings.json` worked: 
```json
{
    "npm.binPath": "~/.nvm/versions/node/v12.9.1/bin/npm",
}
```

See `:h coc-config-npm` or https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt

**Comment by arilebedey** [comment]
Yes. `:CocConfig` to open `coc-settings.json`.

**Comment by L2AsHdz** [comment]
>but now I'm getting the same error as OP where it can't find npm or yarn.

I have the same problem and have not found a solution, do you have any suggestions?

>setting the following key in my coc-settings.json worked

@imjasonmiller I set the path to the npm binary but it didn't solve the problem.

**Comment by codebam** [comment]
Setting both `g:coc_node_path` and  `npm.binPath` gets rid of the errors on startup, but `:CocUpdate` doesn't work because `npm` can't find `node` in PATH.

**Comment by JoshuaDRose** [comment]
> Setting both `g:coc_node_path` and `npm.binPath` gets rid of the errors on startup, but `:CocUpdate` doesn't work because `npm` can't find `node` in PATH.

This helped me, thank you.
