### ISSUE TITLE
pyhon gbk code 

### ISSUE THREAD

**Issue by WingDust** [neoclide/coc.nvim#1828]
## Result from CocInfo


[Info 3:59:35] Using ultisnips directories: UltiSnips E:\spacemacs\emacs26-3\AppData\Local\coc\ultisnips
[Info 3:59:35] Using ultisnips python command: pyx
Error on execute python script:
request error nvim_command - Vim(return):Error invoking 'python_execute_file' on channel 4 (python3-script-host):
error caught in request handler 'python_execute_file ['C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\coc.nvim-9008\\coc-ultisnips-4qoAnEdyrB.py', 1, 1]':
Traceback (most recent call last):
  File "E:\python\python3.8.1\lib\site-packages\pynvim\plugin\script_host.py", line 106, in python_execute_file
    script = compile(f.read(), file_path, 'exec')
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 18260: illegal multibyte sequence

## Describe the bug

I try to use and install `Ultisnips` for `Coc-snippet` 
in the meantime
I go to try `CocCommand snippet.editSnippets` to edit Cplusplus file , just write a simple example.
but it's don't work 
then i install `Ultisnips` and try again , it show up i con't edit `CocCommand snippet.editSnippets` `No write since last change(add! to override)`

I checkout some docment afterthat i go to uninstall `Ultisnips`

it's burn to screenshots look like.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim

  Plug 'neoclide/coc.nvim',{'branch':'release'}

  inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ coc#refresh()
  inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"



  " Snippet
  " Plug 'SirVer/ultisnips'
  Plug 'honza/vim-snippets'
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/45911286/80533937-f8e23a80-89d0-11ea-9bfe-20a971274c77.png)

**Comment by chemzqm** [comment]
It's problem with your python on your vim, you need make sure `:pyxfile` command could work on your vim.

**Comment by chemzqm** [comment]
Should be some way to make your python to use utf8 decoder as default.

**Comment by fqbqrr** [comment]
见这里:https://blog.csdn.net/fqbqrr/article/details/107950465

**Comment by Verf** [comment]
On macOS and Linux, UTF-8 is the default encoding. But Windows still uses legacy encoding like cp1252 and gbk. Now Python 3.7 introduced the UTF-8 mode can use UTF-8 as the default encoding mode in Windows. Just set the environment variable `PYTHONUTF8=1` or use `-Xutf8` command line options.
