### ISSUE TITLE
Statusline not showing errors/warnings when hovering

### ISSUE THREAD

**Issue by jbowen7** [neoclide/coc.nvim#1832]
## Result from CocInfo
```
## versions

vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 11 2019 19:08:24)
node version: v10.19.0
coc.nvim version: 0.0.78-030aef2f6d
term: dumb
platform: linux

## Output channel: Python

Starting Microsoft Python language server.
```
## Describe the bug
Statusline does not include all errors/warning for ${current line}.
This occurs while using `airline` or `set statusline^=%{coc#status()}`

However, both `airline` and `set statusline^=%{coc#status()}` will properly display
errors/warnings after installing `ale` and using `"diagnostic.displayByAle": true`

The problem persists with javascript files and `coc-tsserver` as well as
python files with `coc-python`.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：
* done
- Start (neo)vim with command: `vim -u mini.vim`
* done

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/1946045/80657891-aab55180-8a39-11ea-8663-fc92c71e1fb9.png)
![image](https://user-images.githubusercontent.com/1946045/80657909-b43eb980-8a39-11ea-9442-f905f16ba277.png)
![image](https://user-images.githubusercontent.com/1946045/80657937-bef94e80-8a39-11ea-835a-ab39429adc5a.png)
![image](https://user-images.githubusercontent.com/1946045/80657953-c4ef2f80-8a39-11ea-87a8-480f29f609b1.png)
![image](https://user-images.githubusercontent.com/1946045/80658068-f962eb80-8a39-11ea-9a32-2465b483e04e.png)
![image](https://user-images.githubusercontent.com/1946045/80658006-dc2e1d00-8a39-11ea-8846-9b05bb3aa59a.png)

**Comment by jbowen7** [comment]
About a minute after I posted this I discovered the pattern. The cursor must be
hovering over the position of the error. Simply hovering over the line is not sufficient.

I'd say this isn't a bug, but a behavioral issue. I will go looking for a variable that probably exists
to change the behavior.

**Comment by jbowen7** [comment]
More info: I had a vanilla install of `gruvbox`. It is not showing the error highlights.
It wasn't until I used a mini.vim (per your instructions) that I noticed where the errors actually were
located.

**Comment by jbowen7** [comment]
Addresses this issue well enough for me. At least it's now obvious where the error is located.
`let g:gruvbox_guisp_fallback = 'bg'`

**Comment by chemzqm** [comment]
Yes, it check cursor position for diagnostics, you have to use `"diagnostic.checkCurrentLine": true` in settings.json

**Comment by jbowen7** [comment]
Excellent. Works beautifully.
Thanks @chemzqm

**Comment by mstaicu** [comment]
@jbowen7 how did you disable the tooltip under the cursor for TS or ESLint error/warnings? I'm trying to disable that tooltip and show the error/warning message in the C section, of airline, of the statusline

**Comment by jbowen7** [comment]
@mstaicu 
The particular one you're probably looking for:
` "diagnostic.messageTarget": "echo"`

The floating window can be disabled for a few different things:
[FAQ: Disable floating window](https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-could-i-disable-floating-window)

**Comment by chemzqm** [comment]
> @jbowen7 how did you disable the tooltip under the cursor for TS or ESLint error/warnings? I'm trying to disable that tooltip and show the error/warning message in the C section, of airline, of the statusline

We don't have support for that purpose since there could be multiple diagnostics at same location and if can be multiple lines.

**Comment by mstaicu** [comment]
@jbowen7 thanks for the answer. As for @chemzqm 's answer, that thing occurred to me right after submitting the answer, thus I will most likely leave the floating windows as is
