### ISSUE TITLE
[coc.nvim] error: Uncaught exception: Error: write EPIPE

### ISSUE THREAD

**Issue by clay-coffman** [neoclide/coc.nvim#1833]
## versions

vim version: NVIM v0.4.3
node version: v13.9.0
coc.nvim version: 0.0.78-9febe802b3
term: iTerm.app
platform: darwin

## Output channel: Python

Starting Jedi Python language engine.
##########Linting Output - pylint##########
************* Module app
155,4,error,E0001:invalid syntax (<unknown>, line 155) (syntax-error)

## Describe the bug

As soon as I start typing in a file, I get this error.

`[coc.nvim] error: Uncaught exception: Error: write EPIPE`

## Reproduce the bug

Open any python file with nvim.

Sorry, not sure what to include from vim files. THis is what the full error from :CocOpenLog

```   307 2020-04-29T21:37:19.716 ERROR (pid:38586) [extension-coc-python] - Python Extension: stderr jediProxy, Error (stderr) Traceback (most recent call last):
   308   File "completion.py", line 698, in <module>
   309
   310 2020-04-29T21:37:19.717 ERROR (pid:38586) [extension-coc-python] - Python Extension: stderr jediProxy, Error (stderr)     raise RuntimeError("Jedi version %s too old, requires >= 0.17.0" % (jedi.__version__))
   311 RuntimeError: Jedi version 0.15.2 too old, requires >= 0.17.0
   312
   313 2020-04-29T21:37:19.735 ERROR (pid:38586) [server] - uncaughtException Error: write EPIPE
   314     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16) 
```

**Comment by fannheyward** [comment]
> Jedi version 0.15.2 too old, requires >= 0.17.0

Upgrade your Jedi.

**Comment by Chenfei-Kang** [comment]
hello，I get set the same problem.But the version of jedi is 0.17.2, which is satisfied for coc-python. But I still get write EPIPE error. Do you have any solution?

**Comment by cube-p** [comment]
@Chenfei-Kang 
I did not find any solution, what I did was install coc-pyright instead of coc-python
