### ISSUE TITLE
Feature request: allow multiple node paths

### ISSUE THREAD

**Issue by serprinss** [neoclide/coc.nvim#1834]
**Is your feature request related to a problem? Please describe.**
it would be useful to be able to provide multiple paths to node so if one node path is not executable it can use a backup
**Describe the solution you'd like**
if g:coc_node_path is a list it would check each item in the list until it found one that was executable
**Describe alternatives you've considered**
alternatively we could have a seperate variable called something like g:coc_node_path_list
**example**
g:coc_node_path = [ "/path/to/node",  "/path/to/node2"]
if  /path/to/node is not executable it will try /path/to/node2

**Comment by chemzqm** [comment]
I don't think it makes sense.
