### ISSUE TITLE
[Windows] [coc.nvim] error: UnhandledRejection: Cannot read property 'reader' of undefined

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [neoclide/coc.nvim#1836]
## Result from CocInfo

```
## versions
vim version: NVIM v0.4.3
node version: v13.12.0
coc.nvim version: 0.0.78-bcb2fe977c
term: vtpcon
platform: win32
```

## Describe the bug

I'm using coc-metals and have raised this issue on the coc-metals repo but have been advised to report it here instead.

Installing coc-metals using `:CocInstall` works well but when it is preparing I receive this error:

```
[coc.nvim] error: UnhandledRejection: Cannot read property 'reader' of undefined
TypeError: Cannot read property 'reader' of undefined
    at C:\Users\Oliver\.nvim\plugged\coc.nvim\build\index.js:57558:48
```

Here are the relevant lines in `index.js`:

```javascript
createConnection() {
    let errorHandler = (error, message, count) => {
        logger.error('connection error:', error, message);
        this.handleConnectionError(error, message, count);
    };
    let closeHandler = () => {
        this.handleConnectionClosed();
    };
    return this.createMessageTransports(this._clientOptions.stdioEncoding || 'utf8').then(transports => {
        return createConnection(transports.reader, transports.writer, errorHandler, closeHandler);
    });
}
```

The problem is that `transports` is undefined.

## Reproduce the bug

On Windows 10 using Windows Terminal and Powershell 7 install coc-metals and open a scala file.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by PaperPlaneSoftware** [comment]
The problem is with a call to `fs.existsSync`. This call is made in order to see if the `cmd` exists. In coc-metals' case that's a call to `java`. The file exists but for some reason it returns `false`.

It may be related to this issue:
https://github.com/nodejs/node/issues/17921

**Comment by PaperPlaneSoftware** [comment]
It turns out that `fs.existsSync` is failing on Windows for 2 reasons:

1. the path to cmd is in the Windows format e.g. single \ e.g. `C:\blah\blah\blah` instead of `C:/blah/blah/blah` or `C:\\blah\\blah\\blah`
2. The path does not contain the file's extension. In coc-metals case it's looking for `java` instead of `java.exe`

**Comment by oblitum** [comment]
> The problem is with a call to `fs.existsSync`

Which call in the sources?

**Comment by chemzqm** [comment]
Should be https://github.com/neoclide/coc.nvim/blob/d9c79939f811a00a6a35e93f406cd66b140eea4c/src/language-client/index.ts#L425

**Comment by chemzqm** [comment]
I've removed that check, it's not necessary.
