### ISSUE TITLE
Tab doesn't trigger completion on markdown files

### ISSUE THREAD

**Issue by indeedwatson** [neoclide/coc.nvim#1837]
The popup with the possible completion words appears, but if I press Tab then the default Tab behavior happens (4 spaces are inserted). This only seems to happen with markdown files.
Using the bindings described in the readme:

```vimscript

inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>" :
    \ <SID>check_back_space() ? "\<TAB>":
    \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
```

**Comment by chemzqm** [comment]
Use verbose imap to check your keymap

**Comment by indeedwatson** [comment]
Looks like vimwiki is the issue, cheers.
