### ISSUE TITLE
Extra column on left side?

### ISSUE THREAD

**Issue by winkee01** [neoclide/coc.nvim#1839]
There is an extra column on the left side, I think it a bit disturbing, how can I remove it? or minimize it? it takes up two character size.

<img width="473" alt="extra_column" src="https://user-images.githubusercontent.com/49930785/80796680-70cb8300-8bd2-11ea-9fc1-2863fd201aac.png">

**Comment by jaredgorski** [comment]
@winkee01 - This is the SignColumn in Vim. It's used by coc for diagnostic signs, which is a key feature of coc. You probably want to set it to always be there in your `.vimrc` using `set signcolumn=yes`: https://github.com/neoclide/coc.nvim/blob/b47c4a8738bcb11c693534a523185baf2c0f9a65/README.md#example-vim-configuration

It's a common Vim feature that's very helpful, not a bug.

**Comment by winkee01** [comment]
Thank you so much for the explanation, very helpful.
