### ISSUE TITLE
scroll through show_documentation popup?

### ISSUE THREAD

**Issue by Praful** [neoclide/coc.nvim#1841]
I have a mapping to show documentation:
```
nnoremap <silent> K :call <SID>show_documentation()<CR>
```
This works great. When the help appears sometimes there is more information than can be displayed in the popup window. Is there a way of moving focus to the popup windows (using the keyboard) and scrolling through the help information to read it all?

Thanks

**Comment by fannheyward** [comment]
`C-w-w` moves to the floating window.

**Comment by Praful** [comment]
Thanks for replying. 

C-w-w doesn't work. Even just clicking inside the floating windows or using the mouse wheel to scroll doesn't do anything. It almost looks like the floating window can't take focus. However, I can select text in it - but then text in the underlying window is selected to and I can't copy the text.

I'm using gvim 8.x on Windows. I've tried vim in the command line too.

Anything I could try?

Thanks 

Praful

**Comment by chemzqm** [comment]
Not implemented yet

**Comment by Praful** [comment]
In which case, can you keep the issue open please as a feature request?

Thanks
Praful

**Comment by chemzqm** [comment]
Duplicate of #1160

**Comment by brillout** [comment]
> C-w-w moves to the floating window.

Where is the C-w-w keybinding defined? It doesn't seem to work in neovim v0.4.4

With `C-w-w` you mean holding `<Ctrl>` down while pressing `w` twice in a row, right?

**Comment by chemzqm** [comment]
Read doc for scroll function provided by coc.nvim

**Comment by brillout** [comment]
Found the problem, my `c-w` was remaped. I removed the map and it now works. Sorry I should have digged deeper before asking. Thanks for coc-nvim, it's a wonderful tool.

**Comment by quashact** [comment]
The `<C-w>w` doesn't work to me. In insert mode, that just deletes a word.

**Comment by maxnoe** [comment]
Is there a possibility for scrolling in insert mode in a popup opened by the LSP (e.g. typing inside a function shows the signatures).
When going back to normal mode, the popup goes away so I cannot use ctrl w w to go into it.

**Comment by chemzqm** [comment]
> Is there a possibility for scrolling in insert mode in a popup opened by the LSP (e.g. typing inside a function shows the signatures). When going back to normal mode, the popup goes away so I cannot use ctrl w w to go into it.

`:h coc#float#has_scroll`
