### ISSUE TITLE
suggest.minTriggerInputLength does not work

### ISSUE THREAD

**Issue by michael-angelozzi** [neoclide/coc.nvim#1842]
## Result from CocInfo
```
## versions

vim version: NVIM v0.5.0-dev
node version: v12.16.1
coc.nvim version: 0.0.78-ceb9e47d24
term: xterm-256color
platform: linux
```
## Describe the bug
The value of `"suggest.minTriggerInputLength": 3` is not honored.

## Reproduce the bug
- Create file `mini.vim` with：
  ```vim
  set nocompatible
  set runtimepath^=/home/michael/.config/nvim/tmp/vim-plug/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Open the config with `:CocConfig`
Replace with the following and then save:
```
{
    "suggest.minTriggerInputLength": 3
}
```
Close and re-open Neovim.
- Open the config with `:CocConfig`
Try add another line to the config, and you will see autocompletion will pop up immediately instead of after 3 chars, see the screen shot below.

## Screenshots (optional)
You can see the autosuggestion has popped up before typing 3 chars:
![image](https://user-images.githubusercontent.com/19764314/80807008-5d152200-8bbc-11ea-9fc8-f7227ad717d1.png)

**Comment by chemzqm** [comment]
It's trigger character
