### ISSUE TITLE
 allow to see debug log of consecutive runs 

### ISSUE THREAD

**Issue by eyalk5** [neoclide/coc.nvim#1843]
Hi,

There is a situation where coc.nvim hangs nvim and afterward stop responding. No command `:CocSomething` works.  
It is hard to debug it because `:CocOpenLog` in the next run returns a clean file. (maybe you  delete the log - couldn't locate it)
So, I guess that you should allow one combined log of runs.
Thanks.

**Comment by fannheyward** [comment]
Try `export NVIM_COC_LOG_LEVEL=debug && export NVIM_COC_LOG_FILE=/tmp/coc.log`, this will redirect all debug log, same as `:CocOpenLog`, to `/tmp/coc.log`, and will not delete it when you exit vim.
