### ISSUE TITLE
AutoImport add the aliases instead of relative path

### ISSUE THREAD

**Issue by rcidaleassumpo** [neoclide/coc.nvim#1844]
**Is your feature request related to a problem? Please describe.**
When importing a module, use the tsconfig aliases to the auto-import functionality

**Describe the solution you'd like**
When you try and import a module, from typescript/javascript/vue be able to check for the aliases listed in the tsconfig or webpackconfig then , if there is, use that, or just leave the default behavior

**Describe alternatives you've considered**
I don't know , but I would more than happy to help work in this feature if I could be pointed to the right direction from where to start. :)

**Additional context**
When you have aliases set in your webpack, PHPStorm for instance reads the webpack.config.js information and adds the aliases to the module section, like:

`import x from '@/example/Example'`

instead of 

`import x from '../example/Example'`

**Comment by chemzqm** [comment]
It's supported. Checkout available configuration

**Comment by rcidaleassumpo** [comment]
> It's supported. Checkout available configuration

Maybe it would be useful to point me to the "available" configuration?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver

**Comment by pravinbashyal** [comment]
leaving this here in case somebody stumbles upon it:
` "typescript.preferences.importModuleSpecifier": "non-relative"`
