### ISSUE TITLE
How to disable linting for ccls language server

### ISSUE THREAD

**Issue by pianocomposer321** [neoclide/coc.nvim#1846]
Here's my coc-config.json:

```
{
	"languageserver": {
		"ccls": {
			"command": "ccls",
			"filetypes": [
				"c",
				"cpp",
				"objc",
				"objcpp"
			],
			"rootPatterns": [
				".ccls",
				"compile_commands.json",
				"Makefile"
			]
		}
	}
}
```

I also have ALE.vim installed, and right now they're both listing the file. Is there a way to disable coc.nvim's listing for ccls language server?

**Comment by oblitum** [comment]
https://github.com/neoclide/coc.nvim/blob/d6dd56bba8992aae3ade4034f1bc8d1148c3780f/data/schema.json#L28

**Comment by pianocomposer321** [comment]
@oblitum Woah, thanks for the super-quick reply!

It works great!

**Comment by oblitum** [comment]
@pianocomposer321 no problem. Please use [gitter channel](https://github.com/neoclide/coc.nvim#feedback) for basic questions next time.

**Comment by pianocomposer321** [comment]
@oblitum It seems my internet filtering software is blocking gitter. I would if I could!
