### ISSUE TITLE
Markdown Files with vim-pandoc and vim-pandoc-syntax plugins create "pandoc" filetypes

### ISSUE THREAD

**Issue by zstreeter** [neoclide/coc.nvim#1848]
I like to have vim-pandoc and vim-pandoc-syntax when creating markdown files.  Though, I can see in my status line that coc interprets a README.md file with these plugins enabled as a "pandoc" filetype.  So I added this filetype to my CocConfig options and everything seems to still work (e.g. cSpell) except formatting.  Prettier doesn't recognize the file even though I have "pandoc" in my coc.preferences.formateOnSaveFiletypes list and it's obvious because "Prettier" never shows up in the status-line.  If I don't load the pandoc plugins everything works, including formatting, like normal but it would be nice to still have these working.

Sorry if this is just an outside plugin conflict and not an internal coc bug but wanted to see if you could provide some assistance.

**Comment by chemzqm** [comment]
>  coc interprets a README.md file with these plugins enabled as a "pandoc" filetype. S

It's not true.

**Comment by oblitum** [comment]
Think this is part of coc-prettier, not coc.nvim. coc-prettier README has the following note:

> **Note:** prettier extension have lower priority, if the document have other
registered document format provider, prettier would not work.
>
> To check the format is done by prettier, check out the output message after
format, which should contains `Formatted by prettier`.
>
> **To make prettier do the format, use command `:CocCommand prettier.formatFile`**

**Comment by zstreeter** [comment]
Sorry, I don't mean coc CHANGED the filetype.  I think the vim-pandoc plugin potentially did something and prettier doesn't recognize the results.  If I try to use the "prettier.formatFile" command explicitly the command error is "Cannot read property 'replace' of undefined".

You can see below my file is a .md file put it says "pandoc" and this only occurs if vim-pandoc plugin is installed. 
 
![Screen Shot 2020-05-03 at 11 56 07 AM](https://user-images.githubusercontent.com/15461329/80922943-3dedd000-8d35-11ea-9e4a-f4cba872d1b4.png)

**Comment by oblitum** [comment]
This occurs because your plugin changes the filetype from markdown to pandoc, so it's not the markdown filetype anymore.

**Comment by zstreeter** [comment]
Yes, that I am aware of. 

Including this "pandoc" filetype in the list of coc.preferences.formateOnSaveFiletypes doesn't work.

**Comment by oblitum** [comment]
That's your actual issue but you worded it poorly. You should provide a report with minimal testcase, filling issue template, in case you really want people to give free support.

**Comment by zstreeter** [comment]
Please read my initial post again and thank you for the assistance. 

I will try and do that soon, thank you!

**Comment by chemzqm** [comment]
`:h g:coc_filetype_map`

**Comment by zstreeter** [comment]
Brilliant, thank you!!!

let g:coc_filetype_map = {'pandoc': 'markdown'} allowed everything to work with vim-pandoc!
