### ISSUE TITLE
Why do I need coc-python for python?

### ISSUE THREAD

**Issue by WhyNotHugo** [neoclide/coc.nvim#1849]
This is more of a general question than actual support request.

I've been migrating my vim to use coc, and in order to get python autocompletion, I need to install cc as well as coc-python.

I don't quite understand _why_ I need it though. I've been reading around trying to understand how the pieces of the puzzle fit together (note: they do work, and really well!).

`coc` does the autocompletion, hightlighting, etc ("intellisense" in LSP lingo?).
My LSP does all the python-specific bits like parsing the files themselves etc. coc talks to the LSP.

What's coc-python's role here? Why do I need it too?

**Comment by chemzqm** [comment]
You don't need it

**Comment by WhyNotHugo** [comment]
My question was more accurately: What's `coc-python`'s role?

Obviously this isn't the right place to ask; where _would_ the right place be?

**Comment by WhyNotHugo** [comment]
Further confused since [the documentation _recommends_](https://github.com/neoclide/coc.nvim/wiki/Language-servers#python) using `coc-python`.
