### ISSUE TITLE
show_documentation popup appears for less than a second

### ISSUE THREAD

**Issue by Praful** [neoclide/coc.nvim#1852]
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 22 2020 22:15:23)
node version: v11.4.0
coc.nvim version: 0.0.78-d6dd56bba8
term: undefined
platform: win32

## Describe the bug

I have mapped K to show_documentation as shown in the coc.nvim readme. Over the past day or so, the popup window comes up and disappears very quickly. It's displayed for less than a second. I can see a scroll bar now, which I (and other) had requested. The bug may have been introduced with that feature.

## Reproduce the bug

Add this vim config file:

```
" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```

Then press K whilst over a keyword. I'm using coc-python.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

Running in minimal mode continually produces this error message:
> Error detected while processing CursorHold Autocmmands for "*":
> E117: Unknown function: CocActionSync
>

**Comment by chemzqm** [comment]
We need debug log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc.
* Restart your vim/neovim to make the issue happen.
* Get the log filepath by `:echo $NODE_CLIENT_LOG_FILE`
* Attach the log file or paste content from the log.

**Comment by Praful** [comment]
Thanks for reviewing this issue. I assume you run `:echo $NODE_CLIENT_LOG_FILE` from vim? This produced nothing. I then searched my drive for a file starting with `node_client` and found one that had been updated when I reproduced the issue. It was empty.

**Comment by chemzqm** [comment]
Can't help if you can't provide the connection log.

**Comment by jtmkrueger** [comment]
I see this on documentation that is longer in length. I wonder if @Praful was on to something when he suggested when he started noticing it.

**Comment by Praful** [comment]
I thought this had gone away when I did `:CocRebuild` but it's still there. It's possible I was looking at shorter documentation when I thought it had gone away - which would be consistent with @jtmkrueger observation.

**Comment by mtavano** [comment]
I have the exact same issue.

1. Tried with `CocRebuild` but didn’t worked for me
2. this is my log file https://gist.github.com/mtavano/a91b93a52b6d54b40565ee9bfaff5400
