### ISSUE TITLE
Text overflowing out of popup

### ISSUE THREAD

**Issue by eliza-jane** [neoclide/coc.nvim#1853]
## Result from CocInfo
I do not think this is super relevant to my issue, but just in case:

![Screen Shot 2020-05-04 at 7 08 29 PM](https://user-images.githubusercontent.com/26049591/81022071-b094a380-8e3a-11ea-9940-40e105fc909e.png)

## Describe the bug

Based on a conversation I had with @oblitum on Gitter earlier today and with a coworker also using Elm, it looks like my issue might be scoped to how my Vim is configured. (Issue happens with both Vim and Neovim.) 

After I describe the issue, I will put information below about the configuration. Screenshots are in the "Screenshots" section of the template.

When I save Elm files that have compilation errors, I configured CoC to provide popup information when the error is hovered over. I've done this for all of the languages I use with CoC. However, in just the Elm files, the text overflows from these popups and "spills into" the actual file.

I've tried to forcefully shorten the messages, make the popups scrollable, etc. within my `vimrc` file (which is pasted below under "Reproduce the bug"), but haven't hit on a successful combination yet to prevent this from happening.

### Configuration Files
Here are my vimrc settings pertaining directly to CoC:
```vim
" CoC Settings 

" shorten the message output
set shortmess+=c

" Jump to definitions and other navigational stuff
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Rename current word
nmap <leader>rn <Plug>(coc-rename)

" Use `:Format` to format current buffer - should also do on save
command! -nargs=0 Format :call CocAction('format')

" Use K to either doHover or show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Scrolling in popups
nnoremap <expr><C-f> coc#util#has_float() ? coc#util#float_scroll(1) : "\<C-f>"
nnoremap <expr><C-b> coc#util#has_float() ? coc#util#float_scroll(0) : "\<C-b>"

" Add status line support, for integration with other plugin, checkout `:hcoc-status`
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
```

Here is my CoC config file:
```
{
    "languageserver": {
       "elmLS": {
           "command": "elm-language-server",
           "filetypes": ["elm"],
           "rootPatterns": ["elm.json"],
           "initializationOptions": {
              "elmPath": "elm", 
              "elmFormatPath": "elm-format", 
              "elmTestPath": "elm-test", 
              "elmAnalyseTrigger": "change"
            }
        }
     },

     "coc.preferences.formatOnSaveFiletypes": [
         "css",
         "markdown",
         "Markdown",
         "javascript",
         "ruby",
         "scala",
         "json",
         "elm"
     ],

     "workspace.ignoredFiletypes": ["gitcommit"]
}
```

Just in case, here is my `vim.bundles` file as well. I cut out the unnecessary plugins.

```vim
if &compatible
  set nocompatible
end

call plug#begin('~/.vim/bundle')

" Language plugins
Plug 'elmcast/elm-vim'
Plug 'pangloss/vim-javascript'
Plug 'derekwyatt/vim-scala'

" Styling/Workspace Plugins
Plug 'itchyny/lightline.vim'

" CoC Installations
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()
```

### Steps to reproduce

(1) Open an Elm file, preferably in a full Elm project. You can clone my "Hello World" project [here](https://github.com/eliza-jane/pokedex), if you want something tiny to mess around with.

(2) Save the file after you've messed something up. (I've just been inserting random lines of "alsdfjslfjskdfj" into functions to really break things.)

(3) You should get an output similar to the screenshots below. (Hopefully not as violent, though. 😆 The red in my terminal theme is kinda aggressive.)

## Screenshots

![Screen Shot 2020-05-04 at 2 23 15 PM](https://user-images.githubusercontent.com/26049591/81022320-57793f80-8e3b-11ea-8575-a872d9c15545.png)

![Screen Shot 2020-05-04 at 1 47 56 PM](https://user-images.githubusercontent.com/26049591/81022327-5c3df380-8e3b-11ea-8950-e20f1d57efd5.png)

![Screen Shot 2020-05-04 at 4 18 49 PM](https://user-images.githubusercontent.com/26049591/81022333-5fd17a80-8e3b-11ea-99e7-741146c6e7f5.png)

## Conclusion

Based on the conversation I had on Gitter, I learned that this is an issue with popups in general that others have had. However, it seems there has been some success in suppressing this kind of wild output. If you have a list of settings I should try to prevent the unholy mess shown above, that'd be awesome! I really like CoC and it has positively impacted the way I interact with Vim. 😸

**Comment by oblitum** [comment]
As I commented on gitter, I suspect it might be related with some instability with recent changes on the treatment of float-windows/popup, so for the moment, if that's the case, you can avoid it by freezing to previous commit like this:

```vim
Plug 'neoclide/coc.nvim', {'commit': '4e72e5b~'}
```

**Comment by eliza-jane** [comment]
Thanks, @oblitum ! I will try reverting to the commit you specified.

**Comment by oblitum** [comment]
@eliza-jane fyi, `4e72e5b~` is a commit ref where `4e72e5b` is the potential problem commit and `~` means to checkout the parent of that.

**Comment by eliza-jane** [comment]
Thanks! That works!

I also started up another session of Vim in another terminal emulator (to test things on a "clean slate"), kept `coc` on the release branch, and things seemed to clean themselves up fine. In this case, I zeroed in on the two things I had added not long after I talked with you earlier today:

```vim
" Scrolling in popups
nnoremap <expr><C-f> coc#util#has_float() ? coc#util#float_scroll(1) : "\<C-f>"
nnoremap <expr><C-b> coc#util#has_float() ? coc#util#float_scroll(0) : "\<C-b>"

" shorten the message output
set shortmess+=c
```

These are settings my coworker had in his `vimrc` that I originally did not. These might also help suppress output in the future, if people want to stay on the release branch? 😸

**Comment by chemzqm** [comment]
We need debug log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc.
* Restart your vim/neovim to make the issue happen.
* Open the log file by command `:call coc#client#open_log()`.
* Attach the log file or paste content from the log.

**Comment by eliza-jane** [comment]
I can get this to you this week!

**Comment by chemzqm** [comment]
I tried but works as expected, please try latest release branch of coc.nvim.

**Comment by eliza-jane** [comment]
Hi, @chemzqm - I think it works because I realized that using a combination of message shortening and scrolling stops the instability of the popups. If you remove these and restart your terminal you might start getting that overflowing behavior.

```vim
" Scrolling in popups
nnoremap <expr><C-f> coc#util#has_float() ? coc#util#float_scroll(1) : "\<C-f>"
nnoremap <expr><C-b> coc#util#has_float() ? coc#util#float_scroll(0) : "\<C-b>"

" shorten the message output
set shortmess+=c
```

However, I am about to follow your directions to reproduce the issue, so I will post that here momentarily.

**Comment by eliza-jane** [comment]
Hm, even with removing all of my most recent `vimrc` changes and restarting my terminal emulator, I still am unable to reproduce the issue. I will close this issue for now, then. Sorry for the trouble.
