### ISSUE TITLE
[Question] Different diagnostic categories for different lSP-s ?

### ISSUE THREAD

**Issue by alex-popov-tech** [neoclide/coc.nvim#1862]
I have .js file and a couple of extensions - tsserver, eslint, coc-spell.
Currently tsserver could provide me 'error's or 'warnings', eslint could provide 'error's or 'warning's and coc-spell only 'warning's.

Is that possible to configure how i see output from the extensions? For example I want to have all things from tsserver marked as 'error', things from eslint as 'warning' and coc-spell as 'info' ? To have different signcolumns for them for example...

**Comment by chemzqm** [comment]
No, it's bad idea.
