### ISSUE TITLE
Coc hangs on insert and file save

### ISSUE THREAD

**Issue by eyalk5** [neoclide/coc.nvim#1866]
## Result from CocInfo

> vim version: NVIM v0.5.0-418-g87d892afa
> node version: v13.13.0
> coc.nvim version: 0.0.78-fc983ce6dd
> term: iTerm.app
> platform: darwin
> 
> ## Output channel: Python
> 
> Starting Jedi Python language engine.
> ##########Linting Output - pylint##########
> ************* Module finddistr
> 27,0,error,E0001:Missing parentheses in call to 'print'. Did you mean print(s)? (<unknown>, line 27) (syntax-error)
> 
> ## Output channel: TexLab
> 
> (unrelated)

## Describe the bug

When I do write in file that is not associated with coc (sh file for example), and sometimes when I do write in file like tex or something which has plugin coc-texlab and coc-utilsnip. 
It hangs for a long time.

node reaches 100% cpu and stays this way for minutes! The instance is the instace of coc-nvim.

## Reproduce the bug

After a long time(6 months with occurrences of this)  I can reproduce it. But I can't provide a minimal version.
It happens if I use Ctrlspace to load workspace (which I do by default). But using the minimal vimrc you provided it doesn't happen, or if I don't load a workspace. I can't provide you my workspace. Also, I tried to copy the session into the minimal vimrc, and it still didn't happen, although it raised some errors. 

It probably has to do with something that is loaded twice, or with a file that you don't recognize it is loaded.

When it hangs, this function takes 95 seconds -> 

from vim profiling: 

    1  95.299766   0.000179  AutoSave()
    1  95.299556   0.020949  DoSave()
    1  95.231543   0.000025  <SNR>60_SyncAutocmd()
    1  95.231488  95.223590  <SNR>63_request()
    1  95.231406  95.223513       return call('rpcrequest', [channel, a:method] + a:args)

The log looks something like this:

2020-05-05T18:34:03.116 DEBUG (pid:34378) [events] - Event: InsertEnter [ 94 ]
2020-05-05T18:34:03.607 DEBUG (pid:34378) [events] - Event: CursorMovedI [ 94, [ 14, 26 ] ]
2020-05-05T18:34:03.821 DEBUG (pid:34378) [events] - Event: TextChangedI [ 94 ]
2020-05-05T18:34:04.401 DEBUG (pid:34378) [events] - Event: CursorMovedI [ 94, [ 14, 27 ] ]
2020-05-05T18:34:05.074 DEBUG (pid:34378) [events] - Event: InsertCharPre [ '1' ]
2020-05-05T18:34:05.082 DEBUG (pid:34378) [events] - Event: CursorMovedI [ 94, [ 14, 28 ] ]
2020-05-05T18:34:05.085 DEBUG (pid:34378) [events] - Event: TextChangedI [ 94 ]
2020-05-05T18:34:05.112 DEBUG (pid:34378) [completion] - trigger completion with {
  word: '2001:db8::1',
  bufnr: 94,
  col: 16,
  synname: 'shQuote',
  filepath: '/Users/eyalkarni/devdev/suddensix/suddensix.sh',
  blacklist: [],
  line: 'DEFAULT6PREFIX="2001:db8::1"',
  filetype: 'sh',
  linenr: 14,
  input: '2001:db8::1',
  colnr: 28,
  triggerCharacter: '1'
}

Notice that I don't have a handler for sh files in coc, so it should do nothing!

My coc-modules are coc-vimlsp , coc-texlab, coc-python, coc-vimtex

Any ideas? How to debug further?

**Comment by chemzqm** [comment]
Read https://github.com/neoclide/coc.nvim/wiki/F.A.Q

**Comment by chemzqm** [comment]
fc983ce6dd is old, please try latest release branch.

**Comment by eyalk5** [comment]
I will try the latest version, it will be the same. But I did profiling, and I did debug log and I still can't figure out the exact place. Although I can mitigate it such that it doesn't happen at all.

**Comment by chemzqm** [comment]
Try not use node v13
