### ISSUE TITLE
coc should unescape the text of the markdown hover card

### ISSUE THREAD

**Issue by jsholmes** [neoclide/coc.nvim#1869]
## Result from CocInfo
```
## versions

vim version: NVIM v0.5.0-dev
node version: v14.1.0
coc.nvim version: 0.0.78-be094451df
term: xterm-256color
platform: linux

## Output channel: clangd log

I[11:29:31.424] clangd version 9.0.1-8+hrt1hrt9.1
I[11:29:31.425] Working directory: /usr/scratch/john/hrt/dev
I[11:29:31.425] argv[0]: /usr/bin/clangd-9
I[11:29:31.425] Starting LSP over stdin/stdout
...
```
## Describe the bug
coc requests the markdown version of the hover card, but then doesn't unescape the text per markdown rules.

This leaves the hover card pretty unreadable.

See https://github.com/clangd/coc-clangd/issues/48#issuecomment-625555456

## Screenshots (optional)
Screenshot from cited issue for coc-clangd:

<img width="617" alt="Screen Shot 2020-05-07 at 2 28 43 PM" src="https://user-images.githubusercontent.com/288824/81331420-92fc4f80-906f-11ea-958b-c6d90c574b0d.png">

**Comment by fannheyward** [comment]
https://github.com/clangd/coc-clangd/issues/48#issuecomment-625983541 looks like this is a server error, close and track on https://github.com/clangd/coc-clangd/issues/48
