### ISSUE TITLE
Floating window comes with text scrolled

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#1871]
## Result from CocInfo

<details>

<summary> Result </summary>

## versions

vim version: NVIM v0.4.3
node version: v14.2.0
coc.nvim version: 0.0.78-be094451df
term: tmux-256color
platform: linux

## Output channel: watchman

[Info  - 11:33:02 PM] watchman watching project: /home/francisco/Projects/samples/rust
[Info  - 11:33:02 PM] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /home/francisco/Projects/samples/rust
[Info  - 11:33:02 PM] subscribing "**/.eslintignore" in /home/francisco/Projects/samples/rust
[Info  - 11:33:02 PM] subscribing "**/package.json" in /home/francisco/Projects/samples/rust
[Info  - 11:33:02 PM] subscribing "**/{.prettierrc,.prettierrc.json,.prettierrc.yaml,.prettierrc.yml,.prettierrc.js,package.json,prettier.config.js}" in /home/francisco/Projects/samples/rust
[Info  - 11:33:02 PM] subscribing "/home/francisco/Projects/samples/rust/**/*.rs" in /home/francisco/Projects/samples/rust

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/francisco
> git ls-files -- Projects/samples/rust/src/main.rs
resolved root: /home/francisco
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Output channel: snippets

[Info 11:33:02 PM] Using ultisnips directories: UltiSnips /home/francisco/.config/coc/ultisnips
[Info 11:33:02 PM] Using ultisnips python command: pyx

## Output channel: translator

</details>

## Describe the bug

After floating window refactoring, signatureHelp window sometimes comes with text scrolled down.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set runtimepath^=~/.vim/plugged/coc.nvim
  set mouse=a
  colorscheme peachpuff
  ```

- Start neovim with command: `nvim -u mini.vim src/main.rs`

- Operate nvim.

## Screenshots (optional)

With coc-rust-analyzer installed:

![screencast](https://user-images.githubusercontent.com/1269815/81461914-663a5c00-9185-11ea-9dca-4d7cebb628c8.gif)

**Comment by Avi-D-coder** [comment]
Can confirm, with hie as well when asking for docs `K`.

**Comment by chemzqm** [comment]
We need connection log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc, save your vimrc and exit vim.
* Restart your vim/neovim to make the issue happen.
* Get the log filepath by :echo $NODE_CLIENT_LOG_FILE
* Attach the log file or paste content from the log.

**Comment by oblitum** [comment]
This is the log:

[node-client.log](https://github.com/neoclide/coc.nvim/files/4602812/node-client.log)
