### ISSUE TITLE
Is it possible to entirely disable auto-completion / use only part of the plugin's functionality?

### ISSUE THREAD

**Issue by ashrasmun** [neoclide/coc.nvim#1874]
Hello,

I hope it's not rude to ask about disabling the main feature of a plugin.

I installed `coc.nvim` in order to use it with another plugin - `vim-lsp-cxx-highlight`. I admire your work, but I would like to use different auto-completion engine for my projects. Is it possible to disable the auto-completion, so that I can use something else to do it?

My `:CocConfig`:

```
{
    "suggest.autoTrigger": "none",
    "suggest.timeout": 1,
    "diagnostic.enable": false,
    "clangd.semanticHighlighting": true
}
```

Configuring stuff takes a lot of my time and I just don't want to configure yet another plugin for days :( 

Thanks in advance

**Comment by chemzqm** [comment]
it should work

**Comment by chemzqm** [comment]
Please read docs, there're also variables could help
