### ISSUE TITLE
Allow for specifying destination path when moving to a different file (codeAction)

### ISSUE THREAD

**Issue by mrjoedang** [neoclide/coc.nvim#1876]
When refactoring and attempting to move a selection to a different file, there is no option to set the destination path. If the file needs to be moved, all the imports pointing to that file must change as well, which defeats the purpose of automatically changing the imports upon file move.

Allowing for specifying the destination path (as well as the filename) would make this process more seamless.

**Comment by chemzqm** [comment]
What codeAction?

**Comment by mrjoedang** [comment]
```
nmap <leader>a <Plug>(coc-codeaction-selected)
```

```
Choose by number:
1. Move to a new file
```

**Comment by chemzqm** [comment]
This is how tsserver works, send your feature request to https://github.com/microsoft/TypeScript
