### ISSUE TITLE
preferShownAbove stopped being respected

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#1877]
## Result from CocInfo

<details>

<summary> CocInfo </summary>

## versions

vim version: NVIM v0.4.3
node version: v14.2.0
coc.nvim version: 0.0.78-fd9e7d3972
term: tmux-256color
platform: linux

## Output channel: watchman

[Info  - 3:29:17 PM] watchman watching project: /home/francisco/Projects/samples/rust
[Info  - 3:29:17 PM] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /home/francisco/Projects/samples/rust
[Info  - 3:29:17 PM] subscribing "**/.eslintignore" in /home/francisco/Projects/samples/rust
[Info  - 3:29:17 PM] subscribing "**/package.json" in /home/francisco/Projects/samples/rust
[Info  - 3:29:17 PM] subscribing "**/{.prettierrc,.prettierrc.json,.prettierrc.yaml,.prettierrc.yml,.prettierrc.js,package.json,prettier.config.js}" in /home/francisco/Projects/samples/rust
[Info  - 3:29:17 PM] subscribing "/home/francisco/Projects/samples/rust/**/*.rs" in /home/francisco/Projects/samples/rust

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/francisco
> git ls-files -- Projects/samples/rust/src/main.rs
resolved root: /home/francisco
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Output channel: snippets

[Info 3:29:17 PM] Using ultisnips directories: UltiSnips /home/francisco/.config/coc/ultisnips
[Info 3:29:17 PM] Using ultisnips python command: pyx

## Output channel: translator

</details>

<details>

<summary> Node client debug log </summary>

[node-client.log](https://github.com/neoclide/coc.nvim/files/4604284/node-client.log)

</details>

## Describe the bug

After floating window refactoring, `preferShownAbove` setting seems not to be respected anymore and signatureHelp shows above or bellow at random.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  let g:node_client_debug = 1
  set runtimepath^=~/.vim/plugged/coc.nvim
  call coc#config('signature', {'preferShownAbove': v:false})
  colorscheme peachpuff
  set mouse=a
  ```

- Start neovim with command: `nvim -u mini.vim src/main.rs`

- Operate nvim.

## Screenshots (optional)

With coc-rust-analyzer installed:

![15:27:40_09-05-2020](https://user-images.githubusercontent.com/1269815/81481912-cc68c280-9209-11ea-9216-ff373c7cac2e.png)

**Comment by chemzqm** [comment]
Looks like your have `  "signature.preferShownAbove": false`

**Comment by oblitum** [comment]
@chemzqm the option doesn't seem useful to exist that way, because like in the screenshot, often there's plenty of room for it to fit bellow, but it simply won't show bellow.

**Comment by oblitum** [comment]
Another factor is that this also differs from how completion menu behaves, the completion menu will shown bellow if there's room to show bellow, otherwise it shows above, only when there's no room bellow but there's room above. It's how `preferShownAbove` worked before, but now the two behaviors are not following each other, so ofter you get menu switching bellow and above.

**Comment by oblitum** [comment]
Ah,

Thanks, this is already fixed as expected as described above at commit a026ec932e514bb86cba480cb63f4f8996e8051a.
