### ISSUE TITLE
disable the highlight override on column numbers

### ISSUE THREAD

**Issue by doums** [neoclide/coc.nvim#1880]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v12.16.1
coc.nvim version: 0.0.78-fd9e7d3972
term: alacritty
platform: linux

## Output channel: Rust Analyzer Language Server Trace


## Output channel: watchman

[Info  - 23:13:43] watchman watching project: /home/pierre/Documents/baru
[Info  - 23:13:43] subscribing "/home/pierre/Documents/baru/**/*.rs" in /home/pierre/Documents/baru
```

## Describe the bug

It's not a bug, it's more a question.
I would like to know if there is a way to disable the highlight override on column numbers whose corresponding line contains a diagnostic (error, warn, info, hint) ?

## Screenshots

[![image.png](https://i.postimg.cc/T1yJbM3x/image.png)](https://postimg.cc/7JkzvRzt)

Here I'am talking about the number 111 that is orange instead of grey like others numbers.

**Comment by chemzqm** [comment]
Yes checkout available configuration for diagnostics

**Comment by doums** [comment]
I can find option to disable sign, but that's not I want. I want to keep signs and disable that highlight override on number.

**Comment by oblitum** [comment]
@doums `:h coc-highlights@en`

**Comment by doums** [comment]
@oblitum that does not help.

**Comment by fannheyward** [comment]
@doums `diagnostic.enableHighlightLineNumber` to false.

**Comment by doums** [comment]
Arf, sorry, I didn't found it because this setting is not present in `:h coc-nvim`.

**Comment by chemzqm** [comment]
I will improve it.

**Comment by doums** [comment]
Ok thank!
