### ISSUE TITLE
Unexpected behaviour with UltiSnips

### ISSUE THREAD

**Issue by oyasin** [neoclide/coc.nvim#1883]
**Expected behavior:**

pressing \<C-j\> should put me outside my defined brackets in latex which it does if coc.nvim is disables

**Actual behavior:**
If I enable coc.nvim then \<C-j\> has a weird behaviour.
 
If I entered one character \<C-j\> stops short of exiting the brackets.

If I entered two or more characters inside the snippet \<C-j\> works as expected. 

![81304347-a0243900-9085-11ea-9bc3-dd6606569306](https://user-images.githubusercontent.com/50802294/81494195-87976700-92af-11ea-9dba-a360dbb20ca6.gif)

**Steps to reproduce**

1. use the following snippets in UltiSnips 
`snippet mm "Math" wA`
 `\(${1}\)$0`
`endsnippet`

2. `context "math()"`
  `snippet sr "^2" iA`
  `^2`
  `endsnippet`

I'm also using the default remapping found on con.nvim Read.ME
 " Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.

    inoremap <silent><expr> <TAB>
       \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ coc#refresh()
     inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"'

    function! s:check_back_space() abort
      let col = col('.') - 1
      return !col || getline('.')[col - 1]  =~# '\s'
    endfunction

" Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.

    if exists('*complete_info')
      inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
    else
      inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
    endif

and this is what I have for UltiSnips

    Plug 'sirver/ultisnips'
      let g:UltiSnipsExpandTrigger = '<C-j>'
      let g:UltiSnipsJumpForwardTrigger = '<C-j>'
      let g:UltiSnipsJumpBackwardTrigger = '<C-k>'
-----

- **Operating System**:  Mac OS 10.5
- **Vim Version**: NVIM v0.4.3

**Comment by chemzqm** [comment]
Configure g:coc_snippet_next and g:coc_snippet_prev to avoid conflict
