### ISSUE TITLE
`b:coc_diagnostic_info` can be empty upon entering the buffer even when diagnostics is enabled

### ISSUE THREAD

**Issue by xulongwu4** [neoclide/coc.nvim#1885]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 17 2020 13:03:59)
node version: v12.16.3
coc.nvim version: 0.0.78-030aef2f6d
term: dumb
platform: linux

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/oulongwu/Documents/dotfiles
> git ls-files -- snowblocks/vim/vimrc
resolved root: /home/oulongwu/Documents/dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :snowblocks/vim/vimrc
> git diff /home/oulongwu/Documents/dotfiles/snowblocks/vim/vimrc
resolved root: /home/oulongwu/Documents/dotfiles
resolved root: /home/oulongwu/Documents/dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- snowblocks/vim/vimrc
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :snowblocks/vim/vimrc
> git diff /home/oulongwu/Documents/dotfiles/snowblocks/vim/vimrc

## Output channel: prettier


## Output channel: snippets

[Info 10:11:12 AM] Using ultisnips directories: UltiSnips /home/oulongwu/.config/coc/ultisnips
[Info 10:11:13 AM] Using ultisnips python command: pyx
```

## Describe the bug

I use `coc.nvim`'s diagnostic function and have `diagnostic.refreshOnInsertMode: true` in `coc-settings.json`. Every time I enter a vim buffer with a supported filetype (which I have installed a language server for), `coc` lints the opened buffer. However, I found that `b:coc_diagnostic_info` is only filled when there are errors/warnings in the lint results. If `coc` does not find any error in this file when the file is just opened, `b:coc_diagnostic_info` is empty. Since I use "manual function in [this page](https://github.com/neoclide/coc.nvim/wiki/Statusline-integration) for statusline integration, this means that the status line does not report the the file passes linter's check when it is just open.

The `b:coc_diagnostic_info` variable is only filled when the first error is found in the file.

## Reproduce the bug
Create this file `a.c`:

```c
int main() { return 0; }
```

Open this file in vim and then do `:echo b:coc_diagnostic_info`. I get this error:

> E121: Undefined variable: b:coc_diagnostic_info

Expected output is:

> {'information': 0, 'hint': 0, 'lnums': [0, 0, 0, 0], 'warning': 0, 'error': 0}

**Comment by chemzqm** [comment]
It's expected, you have to check if it exists.

**Comment by xulongwu4** [comment]
The file was checked by linters and no errors were reported. However, `b:coc_diagnostic_info` is empty. Is that expected behavior?

**Comment by chemzqm** [comment]
No, it could be not defined

**Comment by xulongwu4** [comment]
Yeah it could be not defined if there is no LSP running. However, I was concerned about the case where I know that an LSP was running and there was no diagnostic error in my file, yet the diagnostic info was not shown in my status line. This only happened when I open the file in vim before I do any editting. Once I started editing the file, diagnostic info was correctly displayed. This behavior is now fixed and I get the diagnostic info displayed when I open a file in vim without having to edit it.

Let me show a comparison between the current release branch and the release branch at b1b8d50.
This is when I was at b1b8d50.
![2020-06-11-082333_647x411_scrot](https://user-images.githubusercontent.com/16892446/84385559-c9247600-abbd-11ea-976c-1e9f2ba92e2a.png)

This is after I update to the latest release branch.
![2020-06-11-082051_650x414_scrot](https://user-images.githubusercontent.com/16892446/84385602-de99a000-abbd-11ea-8c34-6629351db5b2.png)

Everything else is kept the same. Notice the small check sign next to the file name in the status line. It was not shown in the first image. I would have to start editing the file to make it show up in that case. With the latest release branch, it shows up correctly when I only open vim to view the file without any editing.

**Comment by chemzqm** [comment]
It only means your language server send empty diagnostics after initialized, this behavior is not guaranteed.

**Comment by xulongwu4** [comment]
I see.

The only difference between the two screenshots above is that I was at different commits on the release branch. All the other settings, including LSP versions and settings are kept the same. So I think some changes in `coc` resulted in the difference in this behavior. That is why I said this is fixed in the `coc` now. If I open a file which has no associated LSP, the status line does not show diagnostic info and that is expected. If I open a file with LSP defined and when there is no diagnostic wanrings/errors, the status line shows the check sign correctly.
