### ISSUE TITLE
After update,coc cannot work normally for c/c++

### ISSUE THREAD

**Issue by chenyidao110** [neoclide/coc.nvim#1886]
vim version: NVIM v0.5.0-424-g6ca7ebb34-dirty
node version: v10.19.0
coc.nvim version: 0.0.78-fd9e7d3972
term: xterm-256color
platform: linux

1 run "PlugUpdate" to update 
2 close neovim,then CocUpdate to update
alter update, there is no parsing c/c++ source file while programming.
for details,please prefer https://files.gitter.im/neoclide/coc-cn/MDhT/Tu-Pian.png

**Comment by chemzqm** [comment]
It's fixed on master code
