### ISSUE TITLE
[Help] Keybinding for parameter toggle unclear

### ISSUE THREAD

**Issue by schanzen** [neoclide/coc.nvim#1887]
In the gif shown at the beginning of the readme, it can be seen that the user toggled between two function parameters after function name completion without editing them (the parameters).
Now, I have set up coc-clangd and completion(!) works just fine, including the function parameter completion with documentation and types etc.
But, when I "complete" the function selection, I am sitting in SELECT mode on the first parameter. Which is ok. I can replace the completed parameter with a variable.
However, I am unable to either toggle between editing parameters neither move on to the second parameter after I am finished with the first.
I am sure this might just be that I do not know the correct key binding to use, but maybe this could be documented somewhere (preferably also answered in this issue ;)

**Comment by oblitum** [comment]
The bindings are `<c-j>` and `<c-k>`.

**Comment by oblitum** [comment]
Documentation is at `:h g:coc_snippet_next`.
