### ISSUE TITLE
end of file expected  "command": " [config:] 

### ISSUE THREAD

**Issue by Happy-zyy** [neoclide/coc.nvim#1888]
但是每当我登陆vim的时候
下面都会出现一行 [coc.nvim] settings file parse error, run ':CocList diagnostics'
我运行 CocList diagnostics之后，报告
  .vim/coc-settings.json:1:19 Error [config] end of file expected 
但是，我的 vim/coc-settings.json是直接copy官网c++的配置，如下
<img width="565" alt="图片" src="https://user-images.githubusercontent.com/25721721/81504758-acc2be80-931d-11ea-995f-6c73ad70dfbf.png">

而且我的自动补全功能也是可以用的，就很奇怪，有大佬知道怎么回事吗？

**Comment by oblitum** [comment]
Duplicate #1733

**Comment by whoarethey** [comment]
解决了吗？我也遇见了这个问题。

**Comment by August0424** [comment]
同问，我也是

**Comment by Sbrgw** [comment]
有解决的吗，我也是这个问题

**Comment by oblitum** [comment]
@whoarethey @August0424 @Sbrgw ------> #1733
