### ISSUE TITLE
Format on save no longer works (vim update?)

### ISSUE THREAD

**Issue by guigui64** [neoclide/coc.nvim#1890]
## Result from CocInfo

> ## versions
> 
> vim version: VIM - Vi IMproved 8.2 8020726
> node version: v12.16.3
> coc.nvim version: 0.0.78-fd9e7d3972
> term: dumb
> platform: linux
> 
> ## Output channel: prettier
> 

## Describe the bug

Formatting on save no longer works, I wonder if this is due to a vim update (I compile vim from sources and pulled master today, version is 8.2 8020726 as shown by CocInfo above).

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

Example of mal-formatted file:
```json
{
  "python.linting.pylintEnabled": false,
  "python.linting.flake8Enabled": true,
  "python.linting.enabled": true,
      "coc.preferences.formatOnSaveFiletypes":        ["rust", "json"],
  "rust-analyzer.checkOnSave.extraArgs": ["--all-features"]
}
```

Saving won't format (I have coc-prettier installed) whereas `:call CocAction('format')` works.

**Comment by fannheyward** [comment]
Upgrade coc.nvim to latest and try again.

**Comment by guigui64** [comment]
I'm confused, I'm already on latest (0.0.78)

**Comment by oblitum** [comment]
@guigui64 simply ignore semantic version, latest release just mean last commit on release branch.

**Comment by chemzqm** [comment]
Check your filetype by `echo &filetype`

**Comment by guigui64** [comment]
My filetype was set. The issue is fixed on latest :)
