### ISSUE TITLE
Can't use custom language server after update

### ISSUE THREAD

**Issue by wrvsrx** [neoclide/coc.nvim#1893]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.2 8020717
node version: v14.2.0
coc.nvim version: 0.0.78-657ca3c0fa
term: dumb
platform: linux

## Describe the bug

After update, I found ccls and bash-language-server don't work.

## Reproduce the bug

1. Update to current coc version (0.0.78-657ca3c0fa).
2. Install ccls and configure it following the coc.nvim wiki.
3. Open a cpp file.
4. Nothing happen. We can't also find ccls in workspace.showOutput.

**Comment by wrvsrx** [comment]
It seems that this issue has been fixed in master.

**Comment by chemzqm** [comment]
Fixed on release branch as well.
