### ISSUE TITLE
悬浮窗消失延迟问题

### ISSUE THREAD

**Issue by wNakiami** [neoclide/coc.nvim#1894]
## Describe the bug

在coc-settings.json中设置了diagnostic.messageDelay之后，悬浮窗消失也有这个延迟，必须要停下光标等延迟之后悬浮窗才消失

coc-settings.json:
  ```json
{
  "diagnostic.messageDelay": 1000
}

**Comment by chemzqm** [comment]
It's  delay for display diagnostic message.
