### ISSUE TITLE
Use :spell language file for suggestions in .md documents

### ISSUE THREAD

**Issue by Bloodyfool** [neoclide/coc.nvim#1895]
**Is your feature request related to a problem? Please describe.**
When typing regular text documents in vim the words suggested by coc are the words that are used in the document. This is not very useful unless editing a very large document.

**Describe the solution you'd like**
It would be really nice if there was an option to use the current spell checker file as a basis for the word suggestions. 

**Describe alternatives you've considered**
I haven't found an option or extension that does this, but if there already is i would love to know about it. 

I love this extension and am really thankful to everyone building and maintaining it.

**Comment by chemzqm** [comment]
Checkout `:h compl-spelling`, it's recommended way for completion from spell file
