### ISSUE TITLE
Ctrl-j jump to next won't work

### ISSUE THREAD

**Issue by juniway** [neoclide/coc.nvim#1897]
`ctrl-j` is the default key to jump to next placeholder (e.g. function argument), but in several conditions, this key behavior abnormally.

Generally, when I press `ctrl-j`, the next placeholder should be in SELECT mode, then I press any key it can override the placeholder. But in my case, sometimes it goes into NORMAL mode, and sometimes it just acts like a <CR> keystroke, so I can not continue my typing. So I think something must have gone wrong.

`main.c`

```c
#include <stdio.h>

void printValue(char a[], int n, int i) {
    if (n == 0) return;
    printf("%c\n", a[i]);
    printValue(a, n-1, i+1);
}

int main() {
    char a[5] = {'h', 'e', 'l', 'l', 'o'};
    printValue(a, 5, 0);
}
```

This is a simple test program, When I type `printValue()` and use `c-j` to hop to next argument, 
`n-1 c-j` will not work, but `5 c-j` will work. in some other cases, `a c-j` won't work, I can not continue my edit. I test many other cases, n - something just won't work, but other keys seems work even if they are just random chars.

<img width="492" alt="pp1" src="https://user-images.githubusercontent.com/3980841/81648134-c4569000-9460-11ea-944b-072fe818660d.png">
<img width="333" alt="pp2" src="https://user-images.githubusercontent.com/3980841/81648145-c882ad80-9460-11ea-9f30-fa2c7e957ce5.png">
<img width="474" alt="pp3" src="https://user-images.githubusercontent.com/3980841/81648237-f536c500-9460-11ea-8567-ed1614f97610.png">
<img width="504" alt="pp4" src="https://user-images.githubusercontent.com/3980841/81648243-f667f200-9460-11ea-996b-4dbe9a109485.png">

**My environment**
- Mac OSX
- Vim 8.2

I disabled other plugins(possible) before I made above tests.

**Comment by chemzqm** [comment]
Happens on neovim as well, snippet session is broken.

**Comment by oblitum** [comment]
In many occasions now I'm getting strange content for signatureHelp when expanding member function snippet.

**Comment by oblitum** [comment]
![13:38:48_12-05-2020](https://user-images.githubusercontent.com/1269815/81721329-1940d900-9456-11ea-9a4d-8b9b4f91578e.png)

**Comment by chemzqm** [comment]
@oblitum It's  different issue

**Comment by juniway** [comment]
it happens quite irregularly, either you get into a NORMAL mode, or you get a simple <CR> keystroke, sometimes it does not reoccur.

**Comment by chemzqm** [comment]
It happens for me every time for that case, should not be hard to fix.

**Comment by winkee01** [comment]
> It happens for me every time for that case, should not be hard to fix.

For this example code, yes  it is, but I've also encountered some other case that behaves different, it's another file, it bugged me last night but now I can't get it reoccur.

**Comment by athulp01** [comment]
Having this issue too frequently now. How do I disable snippets? Putting `coc.preferences.snippets.enable": false,` doesn't seem to work. Am i missing something.

**Comment by chemzqm** [comment]
> Am i missing something.

Yes, you should not use configuration that not exists at all.

**Comment by athulp01** [comment]
:sweat_smile: I found that option in [](https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt). Is there any way I could disable snippets. Thanks.

**Comment by chemzqm** [comment]
@athulp01 yes, avoid use this plugin could fix all your issues with it.

**Comment by athulp01** [comment]
Thanks

**Comment by juniway** [comment]
Try this program, the issue still exists.

```cpp
#include <iostream>
#include <vector>
using namespace std;

// {}
int binarySearch(vector<int>& a, int left, int right, int val) {
    int mid = left + (right - left) / 2;
    while (left + 1 < right) {
        if (a[mid] <= val)
            left = mid;
        else right = mid - 1;
    }

    if (a[right] <= val) return right;
    if (a[left] <= val) return left;
    return -1;
}

int main(int argc, char *argv[]) {
    return 0;
}
```
![image](https://user-images.githubusercontent.com/3980841/83316078-6db9c600-a256-11ea-85e2-fc45f289cc8a.png)

I have tested many many times, this does not happen every time. But still it happens quite often.

**Comment by oblitum** [comment]
@juniway I could not reproduce it.

**Comment by juniway** [comment]
> @juniway I could not reproduce it.

maybe you can try more times? It's not happen every time, but after you try some times (maybe more), it will reoccur. like the picture I posted, when it happens, the cursor is under select mode.

**Comment by oblitum** [comment]
well, I tried a lot and gave up.
