### ISSUE TITLE
floating window in vim8 can't show word

### ISSUE THREAD

**Issue by cposture** [neoclide/coc.nvim#1900]
- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=~/.vim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```
the waning word can't show

![image](https://user-images.githubusercontent.com/8305198/81670669-8a928300-947a-11ea-8e0a-7021265ff1dc.png)

**Comment by chemzqm** [comment]
We need connection log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc, save your vimrc and exit vim.
* Restart your vim/neovim to make the issue happen.
* Get the log filepath by :echo $NODE_CLIENT_LOG_FILE
* Attach the log file or paste content from the log.

**Comment by chemzqm** [comment]
Should be bug of your broken vim.
