### ISSUE TITLE
Coc in infinite loop for installing extensions

### ISSUE THREAD

**Issue by The-BigDaddy** [neoclide/coc.nvim#1902]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-504-g55b62a937
node version: v13.2.0
coc.nvim version: 0.0.78-3f305ac739
term: xterm-256color
platform: linux
```
## Describe the bug

Upon opening any filetype (after the recent update) I've set coc to be used in, the window will split with the `[Scratch]` buffer with coc trying to install a couple of extensions. It tries to install `coc-snippets` and `coc-elixir`. I've even removed coc from the `plugged` directory and reinstalled and it does the same thing.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  filetype plugin indent on
  syntax on
  set hidden
  call plug#begin()
  Plug 'neoclide/coc.nvim', { 'branch': 'release',
							\ 'for': ['c', 'cpp', 'crystal', 'd', 'elixir',
							\ 'javascript', 'latex', 'nim', 'ruby', 'tex',
							\ 'typescript', 'vim', 'vue'] }
  call plug#end()
  let g:coc_global_extensions=[ 'coc-yank', 'coc-snippets', 'coc-template',
			\ 'coc-elixir', 'coc-solargraph', 'coc-texlab',
			\ 'coc-tsserver', 'coc-vetur', 'coc-vimlsp',
			\ ]
  " Don't even need to include this, just the coc_gloabl_extensions bit above will work too.
  " if textDocument.documentSymbol
  xmap if <Plug>(coc-funcobj-i)
  xmap af <Plug>(coc-funcobj-a)
  omap if <Plug>(coc-funcobj-i)
  omap af <Plug>(coc-funcobj-a)

  nmap <silent> <TAB> <Plug>(coc-range-select)
  xmap <silent> <TAB> <Plug>(coc-range-select)

  command! -nargs=0 Format :call CocAction('format')
  command! -nargs=? Fold   :call CocAction('fold', <f-args>)
  command! -nargs=0 OR     :call CocAction('runCommand', 'editor.action.organizeImport')
  ```

- `vim -u mini.vim mini.vim` to edit the `vim` file (though any `vim` file, or file for any language in the Plug `for` statement works)

- Operate vim.

- Window will split with coc in a scratch buffer "installing" coc-snippets and coc-elixir

## Screenshots

[Screenshot with `mini.vim` above running `vim -u mini.vim mini.vim`](https://imgur.com/bTI0JGs.png)

[Screenshot with just using my personal config (opening the `mini.vim`)](https://imgur.com/M3g02gr.png)

## EDIT:

From `:CocOpenLog`

```
2020-05-12T13:30:06.472 INFO (pid:6660) [services] - registered service "languageserver.ccls"
2020-05-12T13:30:06.474 INFO (pid:6660) [services] - registered service "languageserver.dls"
2020-05-12T13:30:06.474 INFO (pid:6660) [services] - registered service "languageserver.nimlsp"
2020-05-12T13:30:06.517 INFO (pid:6660) [model-extension] - Using npm from: /usr/bin/npm
2020-05-12T13:30:06.517 INFO (pid:6660) [model-extension] - Loading info of coc-snippets.
2020-05-12T13:30:06.522 INFO (pid:6660) [model-fetch] - fetch: https://registry.npmjs.org/coc-snippets
2020-05-12T13:30:06.537 INFO (pid:6660) [model-extension] - Using npm from: /usr/bin/npm
2020-05-12T13:30:06.537 INFO (pid:6660) [model-extension] - Loading info of coc-elixir.
2020-05-12T13:30:06.538 INFO (pid:6660) [model-fetch] - fetch: https://registry.npmjs.org/coc-elixir
2020-05-12T13:30:06.539 INFO (pid:6660) [plugin] - coc 0.0.78-3f305ac739 initialized with node: v13.2.0
2020-05-12T13:30:06.543 INFO (pid:6660) [services] - registered service "vimlsp"
2020-05-12T13:30:06.544 INFO (pid:6660) [services] - vim language server state change: stopped => starting
2020-05-12T13:30:06.550 INFO (pid:6660) [language-client-index] - vimlsp started with 6674
2020-05-12T13:30:06.708 INFO (pid:6660) [services] - vim language server state change: starting => running
2020-05-12T13:30:06.714 INFO (pid:6660) [services] - service vimlsp started
```

**Comment by fannheyward** [comment]
<img width="383" alt="2020-05-13 11 52 07" src="https://user-images.githubusercontent.com/345274/81769438-2d491100-9510-11ea-9158-6f561c91b94c.png">

After installation finished, you will see this result. Can you get this? Looks like installations are failed. Doest `~/.config/coc/extensions/node_modules/coc-snippets/package.json` exists?

**Comment by The-BigDaddy** [comment]
I've let it run for about 10 minutes and nothing changed. `~/.config/coc/extensions/node_modules/coc-snippets` doesn't exist.

For the hell of it I'll just remove `~/.config/coc` and the extension in `~/.config/nvim/plugged` to see if that changes anything.

**Comment by The-BigDaddy** [comment]
Removed both `~/.config/coc` and `~/.config/nvim/plugged/coc.vim` and it's just [failing to download anything now](https://imgur.com/6KtQ8JS.png).

**Comment by chemzqm** [comment]
Try disable proxies from env or add `"http.proxyStrictSSL": false` in your coc-settings.json

**Comment by The-BigDaddy** [comment]
Fixes the issue of coc.nvim doing the auto install out the gate of opening the file, but it does not fix the issue of the infinite download. 

Running `:CocInstall coc-snippets` show it changes nothing in that regard. [It just sits on the download, again](https://imgur.com/CjBsUOL.png). I'll wait a bit to see if it actually downloads.

[Screenshot of the coc-settings.json](https://imgur.com/FdmI1LA.png).

**Comment by The-BigDaddy** [comment]
Nope. Been about 10 minutes since I started the download.

[Nothing changed](https://imgur.com/maTrE0b.png).

**Comment by doums** [comment]
Hi, I think I have the same problem, I try to install clangd: `:CocInstall coc-clangd`.
A window opens and almost instantly shows:
```
Install finished

- ✓ coc-clangd
```

But the extension is not installed (it's not present when I check with `:CocInfo` or `:CocList extensions`)

In the node_modules I just see a file `-rw-r--r-- 1 pierre users    0 12.05.2020 01:34 coc-clangd`.

**Comment by ronniedroid** [comment]
I have the same problem as above, I am also on Void linux like @The-BigDaddy 

On a fresh Install, running :CocInstall coc-css or coc-css or anything keeps in downloading forever and never finishes. Please reopen the issue as it clearly is not fixed yet.

**Comment by The-BigDaddy** [comment]
@doums @ronniedroid 

I'm thinking this is an NPM issue actually. 

Complete reinstall node (and npm if your distro's package manager does not ship it with node), and try running `npm i -g some-package`.

For me, I got an error that said `cb() never called`. There are two issue open on npm/cli

[1](https://github.com/npm/cli/issues/1272)
[2](https://github.com/npm/cli/issues/1267)

Though, I would recommend you set some of the node/npm environment variables so you never have to run `sudo` with npm (it's stupid you even have to do that anyway).

**POSIX Shell:**

```sh
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_RUNTIME_DIR="$HOME/.runtime"
export NPM_PACKAGES="$XDG_DATA_HOME/npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
```

**Fish Shell:**

```fish
set -x XDG_CONFIG_HOME "$HOME/.config"
set -x XDG_CACHE_HOME "$HOME/.cache"
set -x XDG_DATA_HOME "$HOME/.local/share"
set -x XDG_RUNTIME_DIR "$HOME/.runtime"
set -x NPM_PACKAGES "$XDG_DATA_HOME/npm-packages"
set -x NODE_PATH "$NPM_PACKAGES/lib/node_modules"
set -x NPM_CONFIG_USERCONFIG "$XDG_CONFIG_HOME/npm/npmrc"
```

The log with the error I get (the log is in `~/.npm/_logs/some-stupidly-formatted-timestamp-debug.log`):

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '-g', 'pnpm' ]
2 info using npm@6.13.1
3 info using node@v13.2.0
4 verbose npm-session deeed2eecd352040
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 timing npm Completed in 715ms
8 error cb() never called!
9 error This is an error with npm itself. Please report this error at:
10 error <https://npm.community>
```

**Comment by doums** [comment]
In doubt I updated my node version to the latest current `v14.2.0` and npm after that, `6.14.5`.
After a reboot (just in case), I retried `:CocInstall coc-clangd`. Nothing change.
No error in npm logs like you have posted @The-BigDaddy.
So no, it's not the same error. And I'm agree with @ronniedroid, the issue is still here. Why keep it closed ??

**Comment by ronniedroid** [comment]
It's bugling my mind, I installed coc.nvim on my work computer today, on a void Linux installation that is exactly the same as my home computer, and it worked fine, but it won't work in my home computer.

**Comment by The-BigDaddy** [comment]
@chemzqm this issue seems to not be fixed. Please reopen the issue.

**Comment by fannheyward** [comment]
Try `npm cache clean` and run `CocInstall` again.

**Comment by The-BigDaddy** [comment]
@fannheyward that changes nothing in the context of npm itself. `npm cache clean --force` does not change the result of running into this issue of `cb() never called`, and does not change this infinite download problem I'm having.

**Comment by chemzqm** [comment]
@daern91 please provide the log opened by `:CocOpenLog`

**Comment by chemzqm** [comment]
Apparently you network get blocked when requesting https://registry.npmjs.org/coc-snippets

**Comment by doums** [comment]
Running myself `npm i coc-clangd` in `~/.config/coc/extensions` solves the problem.

**Comment by The-BigDaddy** [comment]
Fixes with updating Void Linux's version of Node. *\*Sighhhhh\**

**Comment by ronniedroid** [comment]
Same thing, got fixed after updating the Node version after running `xbps-install -Su' thank you very much.

**Comment by fannheyward** [comment]
@The-BigDaddy @ronniedroid what's the *wrong* node version when you occur this issue?

**Comment by chemzqm** [comment]
Should be network issue.

The master now have a new UI for extension install status, check messages on window or check the log by `:CocOpenlog`
