### ISSUE TITLE
When completion, the cursor sporadically jump to the first line of the file

### ISSUE THREAD

**Issue by againxx** [neoclide/coc.nvim#1906]
### versions
vim version: NVIM v0.5.0-504-g55b62a937
node version: v13.14.0
coc.nvim version: 0.0.78-3f305ac739
term: tmux-256color
platform: linux

## Describe the bug

In last few days, when the completion popup in insert mode, the cursor randomly jump to the first line of the file, I have encountered it in vimscript, python and markdown files.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=~/.vim
  filetype plugin indent on
  syntax on
  set hidden

  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', { 'branch': 'release' }
  call plug#end()
  ```

- Start (neo)vim with command: `nvim -u mini.vim`

- Operate neovim.

## Screenshots (optional)

![coc_test1](https://user-images.githubusercontent.com/22728604/81820292-010ab000-9563-11ea-973b-32b561c0c37d.gif)

I used minimal vimrc in the second screenshot.

![coc_test2](https://user-images.githubusercontent.com/22728604/81820647-770f1700-9563-11ea-869b-023c597ebd91.gif)

**Comment by chemzqm** [comment]
Please try latest release branch, should ne fixed.

**Comment by teddyhwang** [comment]
This issue is still happening for me even after pulling from the latest release branch.

**Comment by chemzqm** [comment]
@teddyhwang provide your `:CocInfo` and how to reproduce.

**Comment by teddyhwang** [comment]
```
## versions

vim version: NVIM v0.4.3

node version: v14.2.0


coc.nvim version: 0.0.78-0033e4e624


term: iTerm.app


platform: darwin

```

I'm using Ruby and sorbet as my LSP in a fairly large codebase. The best way to trigger is by typing in a module. The same thing happens in the screenshots above. If you're in two panes and the cursor is on the second pane, the cursor will sporadically jump to the first pane but not all the way to the top.

**Comment by jackielii** [comment]
same thing happens to me. In a relatively big Typescript project. Been trying to find a reproducible pattern but feels just random

**Comment by timtyrrell** [comment]
I had this issue for a while, switched to "release" months back and it went away until the past week or the past few days, I swear. large JS project so using tsserver, Neovim nightly, coc-nvim lastest code (I update every morning), Kitty terminal 0.19.1

**Comment by jackielii** [comment]
found some suspicious events when turning on tsserver tracing:

```
[Trace  - 22:21:02] TypeScript Server: trying to cancel ongoing request with sequence number 931
[Trace  - 22:21:02] Sending request: updateOpen (932). Response expected: no. Current queue length: 0
Arguments: {
    "changedFiles": [
        {
            "fileName": "/home/jackieli/nodejs/df-fe/src/pages/Studio/CatalogEdit.tsx",
            "textChanges": [
                {
                    "newText": "",
                    "start": {
                        "line": 1,
                        "offset": 1
                    },
                    "end": {
                        "line": 1,
                        "offset": 2
                    }
                }
            ]
        }
    ]
}
```

**Comment by jackielii** [comment]
observed it a bit more: I noticed everytime it happened, the log has a huge entry of response from the language server:

[coc.log](https://github.com/neoclide/coc.nvim/files/5344519/coc.log)

**Comment by chemzqm** [comment]
Should be fixed on latest release branch of coc.nvim.
