### ISSUE TITLE
:CocLocalConfig not working

### ISSUE THREAD

**Issue by Axioplase** [neoclide/coc.nvim#1907]
Hi,

When I run :CocLocalConfig, nothing happens...

```
vim version: NVIM v0.4.3
node version: v14.2.0
coc.nvim version: 0.0.78
term: iTerm.app
platform: darwin
```

Also, I have a /some/path/.vim/coc-settings.json and I put some config in there, but it is apparently ignored.

**Comment by spastorino** [comment]
I have some main coc-settings.json file and some workspace related files too in a Rust project. One thing that I've just figured is that if I open a Rust file the local configuration is merged and everything works perfect but if I start vim without opening a file and then I do try to open from vim a Rust file I don't have the workspace related configs applied until I do `:CocRestart`.

@Axioplase unsure if it's related to what you're reporting ...

**Comment by chemzqm** [comment]
It's resolved from current buffer

**Comment by spastorino** [comment]
@chemzqm I consider there is some kind of ungreat thing going on here. Opening vim, editing a file and after that needing to run `:CocRestart` is not ideal. Maybe I misunderstood what you meant?.

**Comment by chemzqm** [comment]
It's another issue and you didn't provide the way to reproduce

**Comment by spastorino** [comment]
I still don't get what you meant. Should I open a fresh issue explaining what I'm running into?.

**Comment by chemzqm** [comment]
Yes, you need provide the details.

**Comment by spastorino** [comment]
Create here https://github.com/neoclide/coc.nvim/issues/1926

**Comment by Axioplase** [comment]
> Hi,
> 
> When I run :CocLocalConfig, nothing happens...
> 
> ```
> vim version: NVIM v0.4.3
> node version: v14.2.0
> coc.nvim version: 0.0.78
> term: iTerm.app
> platform: darwin
> ```
> 
> Also, I have a /some/path/.vim/coc-settings.json and I put some config in there, but it is apparently ignored.

For what is worth, I reinstalled with yarn, and now it works.
