### ISSUE TITLE
:CocInstall does not run npm postinstall script

### ISSUE THREAD

**Issue by pappasam** [neoclide/coc.nvim#1909]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-504-g55b62a937
node version: v14.2.0
coc.nvim version: 0.0.78
term: screen-256color
platform: linux
```

## Describe the bug

As part of [coc-jedi](https://github.com/pappasam/coc-jedi), I automatically install [jedi-language-server](https://github.com/pappasam/jedi-language-server) into a coc-jedi-managed Python virtual environment. I achieve this using an [npm postinstall script](https://docs.npmjs.com/misc/scripts), which creates a virtualenv in coc-jedi's root and installs a specific version of `jedi-language-server` there.

Unfortunately, the CocInstall command does not seem to execute my postinstall script, which in turn results in no virtualenv being created, which in turn results in issues like this: https://github.com/pappasam/coc-jedi/issues/1#issuecomment-628081698

## Reproduce the bug

1. Start neovim / Vim
2. Run `:CocInstall coc-jedi`
3. Open a Python file.

You should receive the following error:

```
[coc.nvim] error: UnhandledRejection: Launching server "jedi" using command ~/.config/coc/extensions/node_modules/coc-jedi/.venv/bin/jedi-language-server failed.
```

This error is raised because the postinstall script was not run.

**Comment by chemzqm** [comment]
It's intended, use data folder in extension context for extra files.

**Comment by chemzqm** [comment]
We publish webpacked js bundle to npm which have postinstall script for build the bundle that won't work.
