### ISSUE TITLE
Look into using deno instead of node

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#1916]
[Deno](https://deno.land/v1) is a sand boxed typescript and WASM runtime by the author of node.js ([wiki](https://en.wikipedia.org/wiki/Deno_(software))).

It looks like a great fit for Coc. It has a built in package/module system and typescript run time this could make distribution simpler, and development easier.

**Comment by chemzqm** [comment]
No such plan.

**Comment by tmerse** [comment]
In my humble opinion investigating this could be a net win because of the cababilities/sandboxing features deno provides. Maybe I'll have a look at this if I can find the time.

**Comment by chemzqm** [comment]
Deno have lots of features that looks great, but the big problem is we don't have enough power to rewrite it.

**Comment by lambdalisue** [comment]
It's completely different and not coc.nvim related but I recently started development of an eco-system which use Deno in central with vim-jp members. Just fyi.
https://github.com/vim-denops/denops.vim
