### ISSUE TITLE
there is no diagnostic sign shows in the signcolumn

### ISSUE THREAD

**Issue by XDID** [neoclide/coc.nvim#1920]
<img width="781" alt="截屏2020-05-13下午10 46 40" src="https://user-images.githubusercontent.com/51253594/81883296-68f2e200-95c7-11ea-98cf-f83030d63984.png">
and i set signcolumn to yes
<img width="439" alt="截屏2020-05-1401 04 56" src="https://user-images.githubusercontent.com/51253594/81883318-7740fe00-95c7-11ea-9176-848009db01c1.png">

<img width="439" alt="截屏2020-05-1401 03 42" src="https://user-images.githubusercontent.com/51253594/81883319-7a3bee80-95c7-11ea-8f17-2e660a091ffe.png">

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by chemzqm** [comment]
Use `:sign place` to check signs placed in your buffers.
