### ISSUE TITLE
error loading workspace folders after relative cd

### ISSUE THREAD

**Issue by jeff-blank** [neoclide/coc.nvim#1922]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8020491
node version: v13.13.0
coc.nvim version: 0.0.78-3f305ac739
term: dumb
platform: freebsd

## Output channel: go

[Info  - 1:42:02 AM] 2020/05/14 01:42:02 Build info
----------
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200407041343-bf15fae40dea h1:DUwLyMDMUauGMd9kSLIlhhYJNELm06HuxeBdkFkeax4=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=

Go info
-------
go version go1.13.5 freebsd/amd64
```
## Describe the bug

when opening vim with no command-line arguments, using `:cd` to change to a directory without a leading `/`, and opening a Go file, I get an error like the following:

```
[coc.nvim] Error loading workspace folders (expected 1, got 0)
failed to load view for file:///.gopkg/src/github.com/jeff-blank/wg: err: chdir /.gopkg/src/github.com/jeff-blank/wg: no such file or directory: stderr:
```
I assume this error is from gopls, but I'm also assuming that coc.nvim is sending the erroneous leading `/`. I may be incorrect about the latter; but I don't really know how to troubleshoot it.

the problem does not occur when opening a go file in the current directory or with an absolute or relative path to the go file, only when issuing a `:cd` to a relative path.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=~/.vim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

(the error occurs with the `mini.vim` provided in the issue template after updating the `runtimepath`.)

- Start vim with command: `vim -u mini.vim`
- enter `cd <directory>`, where directory exists and is a relative path (does not begin with `/`).
- enter `:e file.go`. this issue occurs whether the file exists or not.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Should be bug of extension you're using.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
