### ISSUE TITLE
In command line window, the cursor jumps into a popup window, even after disabling coc suggestion

### ISSUE THREAD

**Issue by againxx** [neoclide/coc.nvim#1923]
### versions

vim version: NVIM v0.5.0-504-g55b62a937
node version: v13.14.0
coc.nvim version: 0.0.78-0033e4e624
term: tmux-256color
platform: linux

## Describe the bug

When I try to slightly modify the command's history in command line window, the cursor suddenly jump into a popup window, even though I have already disabled coc suggestion in command line window.

After that, the command line window is invalid, and I cannot press `<Enter>` to execute ex commands.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set runtimepath^=~/.vim
  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', { 'branch': 'release' }
  call plug#end()

  autocmd FileType vim if bufname('%') == '[Command Line]' | let b:coc_suggest_disable = 1 | endif
  ```

- Start (neo)vim with command: `nvim -u mini.vim`

- Operate neovim.

## Screenshots (optional)

I have these extensions installed, the popup seems to come from vimlsp.

![coc-extensions](https://user-images.githubusercontent.com/22728604/81952776-7779e180-9639-11ea-9613-84d7538245e8.png)

This is a screenshot for what happens.

![coc_test3](https://user-images.githubusercontent.com/22728604/81952923-9e381800-9639-11ea-871f-2c1c1a5688b9.gif)

**Comment by againxx** [comment]
After I updated coc-vimlsp to version 0.8.0, the problem still exists.

**Comment by chemzqm** [comment]
It's signature window, not completion

**Comment by againxx** [comment]
Can this be fix by some settings?
