### ISSUE TITLE
There is a way to close completion dialog and return my initial word without came back to the init in the list?

### ISSUE THREAD

**Issue by heubd** [neoclide/coc.nvim#1928]
**Is your feature request related to a problem? Please describe.**
If I am in the middle of one list, I want a way to came back to the init (initial word before start select completion) without moving through the list

**Describe the solution you'd like**
I want to put something like
imap <S-TAB> "here function to do the magic"

**Additional context**
I use tab for trigger completion, completion confirm, snippet expand and jump like VSCode. Maybe something here could give me that feature?

Thanks in advance.
Sorry for my english, I'm not a native speaker.

**Comment by chemzqm** [comment]
`<c-e>` without keymapping

**Comment by heubd** [comment]
> `<c-e>` without keymapping

Thanks, I don't understand that in the doc file.
