### ISSUE TITLE
coc-pyls fails to jump to definition

### ISSUE THREAD

**Issue by RobertBuhren** [neoclide/coc.nvim#193]
Example code:
```
def test():
    return 10


def main():
    test()
```
If I put the cursor on the call of "test()":

CocAction('jumpReference') works as expected -> i.e. lists the two references of the function test()
However,
CocAction('jumpDefinition') gives me simply: "[coc.nvim] Definition not found"

Regards,

Robert

**Comment by Kazimazi** [comment]
It works perfectly for me.

**Comment by oblitum** [comment]
@RobertBuhren @Kazimazi what's your setup for python? For me Coc doesn't recognize `CocAction('jumpReference')`, but `:Denite coc-symbols` shows `test` and `main`.

**Comment by Kazimazi** [comment]
Nothing special it worked right out of the box after `:CocInstall coc-pyls`.

**Comment by oblitum** [comment]
I'm getting same behavior as OP, I get the references, but jumpDefinition fails with definition not found.

**Comment by oblitum** [comment]
python-language-server 0.21.3 on ArchLinux.

**Comment by oblitum** [comment]
The new `:CocInfo` command shows useful info, you may try it. I'm checking for my case there's indeed an error coming out from `definition.py`:

```
File "/usr/lib/python3.7/site-packages/pyls/plugins/definition.py", line 11, in pyls_definitions
    definitions = document.jedi_script(position).goto_assignments(**params)
TypeError: goto_assignments() got an unexpected keyword argument 'enabled'
```

**Comment by chemzqm** [comment]
It's bug of python language server, I've removed `pyls.plugins.jedi_definition.enabled` option from coc-pyls to make it work.
