### ISSUE TITLE
PlugInstall 问题，Plug 'neoclide/coc.nvim', {'branch': 'release'}显示已经克隆成功了，但是plugstatus时显示coc.nvim: fatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by leeyunlong001230** [neoclide/coc.nvim#1931]
PlugInstall 时Plug 'neoclide/coc.nvim', {'branch': 'release'}显示已经克隆成功了，但是plugstatus时显示coc.nvim: fatal: the remote end hung up unexpectedly

**Comment by fannheyward** [comment]
这个不是 coc.nvim 的问题，是 vim-plug 的错误。

**Comment by Kenny-G** [comment]
我遇到了相同的问题。到 ~/.vim/plugged/ 目录下， git clone -b release https://github.com/neoclide/coc.nvim.git , 成功解决了。
