### ISSUE TITLE
"nvim -c 'CocInstall <some-coc-extension>'" erroring out

### ISSUE THREAD

**Issue by Bee-Mar** [neoclide/coc.nvim#1933]
## CocInfo

vim version: NVIM v0.5.0-dev
node version: v10.20.1
coc.nvim version: 0.0.78-0033e4e624
term: xterm-256color
platform: linux

## Bug Description

I'm uncertain of the last version number where this worked, but it worked approximately one week ago. I was able to execute `nvim -c 'CocInstall <some-coc-extension>'` from terminal, but as of this morning I receive an error message:

`[coc.nvim] error: error on notification 'installExtensions': TypeError: Cannot read property 'setExtensions of undefined`

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `nvim -u mini.vim -c 'CocInstall coc-clangd'` (or any other Coc extension)

- Operate vim.

## Screenshot

![2020-05-15-094252_952x1048_scrot](https://user-images.githubusercontent.com/17814198/82056835-7f18a500-9690-11ea-9c9a-aa898c936fd2.png)

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
