### ISSUE TITLE
Vim(call):E5555: API call: 'height' key must be a positive Integer

### ISSUE THREAD

**Issue by FongHou** [neoclide/coc.nvim#1934]
## versions
  vim version: NVIM v0.4.3
  node version: v14.2.0
  coc.nvim version: 0.0.78-0033e4e624
 term: tmux-256color
 platform: linux

## Describe the bug

:CocOpenLog

[coc.nvim] error: UnhandledRejection: request error nvim_call_function - Vim(call):E5555: API call: 'height' key must be a positive Integer
Error: request error nvim_call_function - Vim(call):E5555: API call: 'height' key must be a positive Integer
    at /mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:14294:32
    at /mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:10940:13
    at NvimTransport.parseMessage (/mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:10881:17)
    at DecodeStream.<anonymous> (/mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:10851:18)
    at DecodeStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at DecodeStream.Readable.push (_stream_readable.js:217:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:13818:12)

## Reproduce the bug

Only clojure-lsp triggers it when auto suggest and document.

```
  "languageserver": {
    "clojure-lsp": {
      "command": "bash",
      "args": ["-c", "clojure-lsp"],
      "filetypes": ["clojure"],
      "rootPatterns": ["project.clj"],
      "additionalSchemes": ["jar", "zipfile"],
      "trace.server": "verbose",
      "initializationOptions": { "keep-require-at-start?": true }
    }
  } 
```
- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
We need connection log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc, save your vimrc and exit vim.
* Restart your vim/neovim to make the issue happen.
* Get the log filepath by :echo $NODE_CLIENT_LOG_FILE
* Attach the log file or paste content from the log.

**Comment by FongHou** [comment]
log has 30000 lines. Here are lines around "'height' key must be a positive Integer" error

2:36:10 PM DEBUG [transport] - request to nvim: 77,nvim_call_function,[
  "coc#util#create_float_win",
  [
    0,
    0,
    {
      "col": 54,
      "row": 8,
      "height": null,
      "width": 2,
      "relative": "editor"
    }
  ]
]
2:36:10 PM DEBUG [transport] - receive notification: [
  "redraw",
  [
    [
      "grid_cursor_goto",
      [
        1,
        1,
        0
      ]
    ],
    [
      "flush",
      []
    ]
  ]
]
2:36:10 PM DEBUG [transport] - response of nvim: 77,2ms,null,[
  0,
  "Vim(let):E5555: API call: 'height' key must be a positive Integer"
]

  "2020-05-15T14:36:10.300 DEBUG (pid:17665) [events] - Event: MenuPopupChanged [",
  "  {",
  "    col: 7,",
  "    row: 8,",
  "    scrollbar: false,",
  "    completed_item: {",
  "      word: 'aws',",
  "      menu: 'cognitect.aws.client.api [LS]',",
  "      user_data: '{\"cid\":1589567765,\"source\":\"languageserver.clojure-lsp\",\"index\":4}',",
  "      info: '',",
  "      kind: '',",
  "      abbr: 'aws'",
  "    },",
  "    width: 47,",
  "    height: 7,",
  "    size: 7",
  "  },",
  "  7",
  "]",
  "2020-05-15T14:36:10.302 DEBUG (pid:17665) [events] - Event: TextChangedP [ 4 ]",
  "2020-05-15T14:36:10.522 ERROR (pid:17665) [server] - unhandledRejection  Promise {",
  "  <rejected> Error: request error nvim_call_function - Vim(let):E5555: API call: 'height' key must be a positive Integer",
  "      at /mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:14294:32",
  "      at /mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:10940:13",
  "      at NvimTransport.parseMessage (/mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:10881:17)",
  "      at DecodeStream.<anonymous> (/mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:10851:18)",
  "      at DecodeStream.emit (events.js:315:20)",
  "      at addChunk (_stream_readable.js:302:12)",
  "      at readableAddChunk (_stream_readable.js:278:9)",
  "      at DecodeStream.Readable.push (_stream_readable.js:217:10)",
  "      at DecodeStream.Transform.push (_stream_transform.js:152:32)",
  "      at DecodeBuffer.DecodeStream.decoder.push (/mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:13818:12)",
  "} Error: request error nvim_call_function - Vim(let):E5555: API call: 'height' key must be a positive Integer",
  "    at /mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:14294:32",
  "    at /mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:10940:13",
  "    at NvimTransport.parseMessage (/mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:10881:17)",
  "    at DecodeStream.<anonymous> (/mnt/c/Users/houfe/haskeller/.config/nvim/plugged/coc.nvim/build/index.js:10851:18)",
  "    at DecodeStream.emit (events.js:315:20)",
  "    at addChunk (_stream_readable.js:302:12)",
  "    at readableAddChunk (_stream_readable.js:278:9)",

**Comment by a-torgovitsky** [comment]
I am still running into this problem.

Here's the output of the connection log surrounding the error.
(Please let me know if you need more of the output. It is a large file.)

```
12:00:56 PM DEBUG [transport] - receive notification: [
  "CocAutocmd",
  [
    "MenuPopupChanged",
    {
      "col": 72,
      "row": 43,
      "scrollbar": false,
      "completed_item": {
        "word": "under",
        "menu": "underline text [S]",
        "user_data": "{\"cid\":1602522056,\"source\":\"snippets\",\"index\":85}",
        "info": "",
        "kind": "S",
        "abbr": "under~"
      },
      "width": 35,
      "height": 8,
      "size": 8
    },
    42
  ]
]
12:00:56 PM DEBUG [transport] - request to nvim: 13763,nvim_eval,[
  "&filetype"
]
12:00:56 PM DEBUG [transport] - response of nvim: 13763,0ms,tex,null
12:00:56 PM DEBUG [transport] - request to nvim: 13764,nvim_call_function,[
  "coc#util#create_float_win",
  [
    null,
    2,
    {
      "col": 53,
      "row": 43,
      "height": -6,
      "width": 18,
      "relative": "editor"
    }
  ]
]
12:00:56 PM DEBUG [transport] - response of nvim: 13764,0ms,null,[
  0,
  "Vim(let):E5555: API call: 'height' key must be a positive Integer"
]
12:00:56 PM DEBUG [transport] - receive notification: [
  "CocAutocmd",
  [
    "InsertCharPre",
    "c"
  ]
]
```

**Comment by chemzqm** [comment]
Negative height should not possible.
