### ISSUE TITLE
Error on MenuPopupChanged: Cannot read property 'setDocuments' of null

### ISSUE THREAD

**Issue by Iron-E** [neoclide/coc.nvim#1935]
## Result from CocInfo

<details><summary>CocInfo Output</summary>

### versions

vim version: NVIM v0.4.3
node version: v14.2.0
coc.nvim version: 0.0.78-57637bb44c
term: xterm-256color
platform: linux

### Output channel: snippets

[Info 4:16:56 PM] Using ultisnips directories: UltiSnips /home/iron-e/.config/coc/ultisnips
[Info 4:16:56 PM] Using ultisnips python command: pyx

### Output channel: highlight

[Info  - 4:16:56 PM] Highlight server running in node v14.2.0
</details>

## Describe the bug

Whenever attempting to use snippets/auto-completions from a language server that also provides a definition/preview, an error will occur.

After this error occurs, there is no way to accept the completion/snippet and expand it, nor is there a way to view the definition/preview.

I have tested:

* `coc-flutter`
* `coc-java`
* `coc-lua`
* `coc-tabnine`
* `coc-xml`
* `coc-vimlsp`

Out of those, `coc-tabnine` works. I suspect this may be because it does not provide previews nor definitions for the completions.

## Reproduce the bug

1. Begin typing something that will produce an auto-completion with a preview/definition.
2. Use the arrow keys/`<Tab>` to attempt to select the auto-completion.
3. This error message will appear:
    ```log
    [coc.nvim] error: Error on MenuPopupChanged: Cannot read property 'setDocuments' of null

	TypeError: Cannot read property 'setDocuments' of null
		at Floating.calculateBounding (/home/iron-e/.local/share/nvim/plugged/coc.nvim/build/index.js:68839:27)
		at Floating.showDocumentationFloating (/home/iron-e/.local/share/nvim/plugged/coc.nvim/build/index.js:68787:33)
		at runMicrotasks (<anonymous>)
		at processTicksAndRejections (internal/process/task_queues.js:97:5)
		at async Floating.show (/home/iron-e/.local/share/nvim/plugged/coc.nvim/build/index.js:68782:9)
		at async Completion.onPumChange (/home/iron-e/.local/share/nvim/plugged/coc.nvim/build/index.js:39713:13)
		at async /home/iron-e/.local/share/nvim/plugged/coc.nvim/build/index.js:15385:25
    ```

### `mini.vim`

```vim
filetype plugin indent on
let g:python3_host_prog='/usr/bin/python3'
set hidden
set nocompatible
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
syntax on
```

## Screenshots

From some `foo.lua` file:

![Error](https://user-images.githubusercontent.com/36409591/82095569-d0578180-96ee-11ea-8e96-ed7de2a612e4.png)

**Comment by chemzqm** [comment]
Use latest release branch from github
