### ISSUE TITLE
Break changes with next release 0.0.79

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#1937]
Most of them are made to improve the user experience or avoid unnecessary issue.

* Remove automatic change locationlist on diagnostics change.  Remove `diagnostic.locationlist` configration , use `:CocDiagnostics` to open location list for diagnostics of current buffer.

* `suggest.triggerCompletionWait` now used for debounce completion instead of completion wait time of language server. It means the completion would be canceled when change made during wait time after completion triggered.

* `coc#util#install()` will run `yarn install --frozen-lockfile` command to compile the code instead of fetch javascript file from github.

    The reason is if you fetch the bundle and not upgrade vim files of coc.nvim, it's most likely to have some unexpected issues.

* Options of `fetch` and `download` module will be changed.

    Those modules are not well implemented before, so changes need for better error handling and easier to use API.
    **Note** the changes could break some extensions, it's recommended to use modules like https://www.npmjs.com/package/request-light for request.

* No timeout error for request to coc.nvim.

   The request handling could be slow, checkout the error from log file by `:CocOpenLog`, or specify `NVIM_COC_LOG_FILE` environment variable before vim start for fixed log file.

* Signatrue of `document.applyEdit` changed to `edits: TextEdit[], sync = true`, the old call with neovim as first parameter would still work but you have to fix the signature before compile the extension.

* `FloatFactory` and `FloatBuffer` module have reworked, extensions using `FloatBuffer` could be broken.

* Range of codeAaction defaults to current file, which was current line before, affected key-mapping: `<Plug>(coc-codeaction)` (will use full range of current file instead of current line as range)

    use `<Plug>(coc-codeaction-line)` for codeAction of current line.

* Support of node < 10.12.0 will be dropped in the feature, a warning would be shown if you're using node v8 , node 14 is recommended.

* Use javascript files from `lib` folder when it's exists, and `build` folder (compiled by webpack) as fallback. `build` folder was preferred before, but it would cause issue after you switched to master branch. 

    `g:coc_force_debug` would be unnecessary since `lib` folder is preferred
     Use `let g:coc_force_bundle = 1` if you want coc.nvim always use javascript from `build` folder.

* `workspaceSymbols` action is removed from list of `CocAction`, use `CocList symbols` instead.

* `textprop` and `popup` features of vim8 would not work on vim <= 8.1.1719, since it could be buggy, a warning would be shown.

* `coc.preferences.extensionUpdateCheck` would be `never` be default, which means no auto update by default, no surprise any more. 

*  Jump to final placeholder should unmap snippet navigate keys, like VSCode.

*  Support mulitple final placeholder with value like VSCode.

*  Not check document for workspace symbols like vscode.

* `CocList commands` will list workspace commands only.

**Comment by antoinemadec** [comment]
@chemzqm , is there a reason why the ```workspaceSymbols``` action has been removed?
It makes it impossible to implement symbols in plugin like [coc-denite](https://github.com/neoclide/coc-denite) or [coc-fzf](https://github.com/antoinemadec/coc-fzf)

I also see that the support of actions returning a dict has been removed, such as:
```vim
let l:diags = CocAction('diagnosticList')
```

Once again, this makes any plugin using those lists deprecated.
Would it be possible to re-introduced the "list actions" returning those dict?

Thanks,
Antoine

**Comment by chemzqm** [comment]
@aaronmcdaid use `getWorkspaceSymbols`, `workspaceSymbols` just invoke `CocList -I symbols`, it's useless.

**Comment by antoinemadec** [comment]
@chemzqm , thanks for fixing the v:null dict issue.

Regarding the symbols, sorry about the confusion. My problem came from the rpcrequest method name.
Here is what I was using:
```vim
call rpcrequest(3, 'CocAction', 'getWorkspaceSymbols', 2)
```

I just had to change ```CocAction``` to ```cocAction``` to fix this issue.

Thanks a lot,
Antoine

**Comment by chemzqm** [comment]
@antoinemadec you should not use `rpcrequest`, it's not public API and likely to be changed in the feature, use `CocAction()` instead.

**Comment by antoinemadec** [comment]
@chemzqm, is there a mechanism to point to a specific buffer with CocAction()? If not, I will need to keep on using rpcrequest because of the interactive nature of the process. Switching buffers does not play well with Fzf interactive mode...

**Comment by chemzqm** [comment]
You can pass bufnr to CocAction and you don't need to pass channel id.

**Comment by antoinemadec** [comment]
@chemzqm , oh wow, I had no idea buffer could be passed to ```CocAction()```.
The way I was doing it was really convoluted :smile: 

I just changed it on ```coc-fzf```, thanks a lot!

**Comment by AdrienLemaire** [comment]
How about following the [semver convention](https://semver.org/) for versioning? Nobody expects breaking changes when switching from 0.0.78 to 0.0.79.

**Comment by chemzqm** [comment]
> How about following the [semver convention](https://semver.org/) for versioning? Nobody expects breaking changes when switching from 0.0.78 to 0.0.79.

Not until we have a stable release.

**Comment by oblitum** [comment]
Indeed, the project is following semver.

**Comment by wadkar** [comment]
Are we making `yarn` as dependency to `coc.nvim`?

I agree that this is not a stable release so breaking changes are to be expected. Would it would be possible if we can make a deprecation release and give users a heads up?

**Comment by chemzqm** [comment]
Yarn is required unless you what to build coc.nvim or some coc extensions.

**Comment by wadkar** [comment]
My understanding of this thread is that **yarn is still not required**. The caveat being that one has to build their own `coc.nvim` and `coc-extensions` using their node/npm installation. And that would be fine for someone like me.

Please correct me if this will change after `0.0.79`.

Again, thanks for your contribution to the community.

---

For the sake of posterity. I am on neovim-0.4.3 with no system wide installation of node or yarn. I use `pyenv` and `nodenv` to manage my python and node installations. I have following one liners in my `~/bin`:

```sh
$ cat ~/bin/coc-node # let g:coc_node_path = $HOME . '/bin/coc-node'
NODENV_VERSION='12.18.0' nodenv exec node "$@"
$ cat ~/bin/neovim-node-host # let g:node_host_prog = $HOME . '/bin/neovim-node-host'
NODENV_VERSION='12.18.0' nodenv exec neovim-node-host "$@"
$ cat ~/bin/neovim-python # let g:python_host_prog = $HOME . '/bin/neovim-python'
PYENV_VERSION='neovim-3.8.3' pyenv exec python "$@"
$ cat ~/bin/neovim-python2 # let g:python2_host_prog = $HOME . '/bin/neovim-python2'
PYENV_VERSION='neovim-2.7.18' pyenv exec python "$@"
```

**Comment by khalidchawtany** [comment]
```:call CocAction('format')``` throws the following error. 
`Error on request (format): Vim(return):Error invoking 'format' on channel 3 (coc):
Method "format" not exists with coc.nvim
`
Is this related or I should open an issue?

**Comment by oblitum** [comment]
What about making the release branch the default github branch and avoid  #2242?

**Comment by expipiplus1** [comment]
Will 0.0.79 be released on npm? The most recent version there is 0.0.77.

**Comment by masaeedu** [comment]
Now that the diagnostics.locationlist option is removed, how does one display an automatically updating list of diagnostics in the location list? I could set it up to run `CocDiagnostics` every time I save, but that doesn't seem right because it probably takes some time for the relevant language server to process the file and come up with new diagnostics.

**Comment by chemzqm** [comment]
@masaeedu we could support location automatic update when it's opened.

**Comment by chemzqm** [comment]
Added location list automatic update by 272b46d1

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/releases/tag/v0.0.79
