### ISSUE TITLE
coc-java: Invalid cursor position after completion

### ISSUE THREAD

**Issue by tbo** [neoclide/coc.nvim#194]
The cursor jumps back to the beginning after selecting a completion item. This issue appeared with release v0.0.33 and is still present in v0.0.34:

![kapture 2018-11-26 at 22 30 06](https://user-images.githubusercontent.com/264745/49044002-da20b880-f1cc-11e8-8b8b-8cb1318f0c24.gif)

Correct behavior in v0.0.32:

![kapture 2018-11-26 at 22 34 58](https://user-images.githubusercontent.com/264745/49044039-fde3fe80-f1cc-11e8-8646-66f75e0b2fca.gif)

If you look closely, you can see, that the cursor jumps twice in coc-java release v0.0.32. Other extensions don't exhibit this behavior.

This issue only appears in combination with coc-java. coc-tsserver and coc-rust work as expected.

**Comment by chemzqm** [comment]
This issue is fix on master b2508ee

**Comment by tbo** [comment]
Thanks, that fixed it!
