### ISSUE TITLE
[coc.nvim] Can't load extension from "/home/user/.config/nvim": package.json not found in: /home/user/.config/nvim

### ISSUE THREAD

**Issue by voldikss** [neoclide/coc.nvim#1941]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-d7d69fe
node version: v14.2.0
coc.nvim version: 0.0.78
term: xterm-256color
platform: linux
```

## Describe the bug

After 14623e1ca36254fc9271c3bf20a60fe92aa2f0bd, every time when I use `:Startify` coc throws the following messages:
```
[coc.nvim] Can't load extension from "/home/user/.config/nvim": package.json not found in: /home/user/.config/nvim
[coc.nvim] Can't load extension from "/usr/share/vim/vimfiles": package.json not found in: /usr/share/vim/vimfiles
[coc.nvim] Can't load extension from "/home/user/.cache/nvim/plugged/yats.vim": can't find name & engines in /home/user/.cache/nvim/plugged/yats.vim/package.json
...
```

I put all my coc extension only in `~/.config/coc`,  the directory `~/.cache/nvim/plugged` is only used for vim plugins(coc.nvim, vim-startify, etc.). Coc shouldn't look for coc extensions from my vim plugins location. 

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  call plug#begin('~/.cache/nvim/plugged')
  Plug 'mhinz/vim-startify', {'on': 'Startify'}
  call plug#end()
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

 Input `:Startify` and type Enter.

## Possible causes

Might be caused by the following lines

https://github.com/neoclide/coc.nvim/blob/9704f8d076426177dcbd92067dc76bafa266f852/src/extensions.ts#L102-L111

Since I use lazy loading provided by vim-plug. Once I use `:Startify`, vim-plug adds vim-startify path to `&runtimepath`. Once the `runtimepath` was changed, that event got fired and coc began to `loadExtension` from one of my `&runtimepath`...

But I don't know how to fix it. I disabled this line for a temporary fix.
https://github.com/neoclide/coc.nvim/blob/9704f8d076426177dcbd92067dc76bafa266f852/src/extensions.ts#L452
Please help.

**Comment by sQVe** [comment]
I'm still getting the exact same output when running `:PlugUpdate`. Running the latest from `master`.

**Comment by chemzqm** [comment]
@sQVe build the project.

**Comment by chemzqm** [comment]
Sorry, bad commit.

**Comment by tombh** [comment]
I'm still seeing this with latest commit de70457

**Comment by chemzqm** [comment]
@tombh you didn't compile the code.

**Comment by tombh** [comment]
I've done `yarn install --frozen-lockfile`, is there something else I need to do?

**Comment by chemzqm** [comment]
@tombh `rm -rf build`

**Comment by tombh** [comment]
Thank you. Sorry about this. I removed the entire `~/.config/nvim/plugged/coc.nvim` folder, ran `yarn install --frozen-lockfile` and I still see the same error messages on neovim boot.

**Comment by chemzqm** [comment]
I will make some change to avoid this issue, this could be happened after switch branch of coc.nvim.

**Comment by chemzqm** [comment]
Checkout coc.nvim version by `:CocInfo` looks like your activated coc.nvim is not what you just downloaded.

**Comment by tombh** [comment]
Thank you. I get this:
```
vim version: NVIM v0.4.3
node version: v12.16.1
coc.nvim version: 0.0.78
coc.nivm directory: /home/tombh/.config/nvim/plugged/coc.nvim
term: screen-256color
platform: linux
```

And still after recent updates I get all the `[coc.nvim] Can't load extension from "/home/user/.config/nvim": package.json not found in: /home/user/.config/nvim` errors in status, that I need to press Enter on multiple times.

**Comment by chemzqm** [comment]
You have to reinstall your broken extension

**Comment by tombh** [comment]
Ok. How did I break them?

**Comment by chemzqm** [comment]
I don't know

**Comment by semanser** [comment]
Check permissions on your folders. In my case, this error was caused by an incorrect `chmod`.
