### ISSUE TITLE
Documentation explaining right side of auto complete

### ISSUE THREAD

**Issue by jrock2004** [neoclide/coc.nvim#1942]
So when I look at the auto complete, I am not sure what f or m is. I do not understand what is TSC. Is there documentation explaining what this is?

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/655716/82156008-b466f380-9846-11ea-9e8d-5f895ca355c0.png">

**Comment by chemzqm** [comment]
Wiki

**Comment by jrock2004** [comment]
@chemzqm I am not sure where in the wiki to look. Do you have a link?

**Comment by chemzqm** [comment]
`:CocList sources`
