### ISSUE TITLE
Blank line at top of floating windows in vim

### ISSUE THREAD

**Issue by sam-mccall** [neoclide/coc.nvim#1949]
## Result from CocInfo
```
## versions

vim version: VIM - Vi IMproved 8.1 8012269
node version: v10.19.0
coc.nvim version: 0.0.78-d7b3084375
term: dumb
platform: linux

## Output channel: clangd log

I[04:15:01.188] clangd version 10.0.0 (https://github.com/llvm/llvm-project d32170dbd5b0d54436537b6b75beaf44324e0c28)
I[04:15:01.188] PID: 199624
I[04:15:01.188] Working directory: /home/sammccall/.config/coc/extensions/node_modules
I[04:15:01.188] argv[0]: /home/sammccall/.config/coc/extensions/coc-clangd-data/install/10.0.0/clangd_10.0.0/bin/clangd
I[04:15:01.188] argv[1]: -hidden-features
I[04:15:01.188] argv[2]: -log=verbose
I[04:15:01.188] argv[3]: -background-index=0
I[04:15:01.188] Starting LSP over stdin/stdout
I[04:15:01.188] <-- initialize(0)
I[04:15:01.188] --> reply:initialize(0) 0 ms
I[04:15:01.192] <-- initialized
I[04:15:01.194] <-- textDocument/didOpen
I[04:15:01.194] Failed to find compilation database for /home/sammccall/test.cc
I[04:15:01.194] --> textDocument/clangd.fileStatus
I[04:15:01.194] Updating file /home/sammccall/test.cc with command clangd fallback
[/home/sammccall]
/home/sammccall/llvm7/bin/clang /home/sammccall/test.cc -fsyntax-only -resource-dir=/home/sammccall/.config/coc/extensions/coc-clangd-data/install/10.0.0/clangd_10.0.0/lib/clang/10.0.0
I[04:15:01.205] --> textDocument/publishDiagnostics
V[04:15:01.205] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"init_conversion_failed","message":"Cannot initialize a variable of type 'int' with an lvalue of type 'const char [4]'","range":{"end":{"character":5,"line":0},"start":{"character":4,"line":0}},"relatedInformation":[],"severity":1,"source":"clang"}],"uri":"file:///home/sammccall/test.cc"}}
I[04:15:01.205] --> textDocument/semanticHighlighting
I[04:15:01.205] --> textDocument/clangd.fileStatus
```

## Describe the bug

A blank line is added at the top of every float (diagnostics window, hover, signature help...).
The coordinate-based highlights for diagnostics are correspondingly all in the wrong place.

## Reproduce the bug

0. install `coc-clangd`
1. vim -u mini.vim test.cc (`int x = "foo";`)
2. move cursor over `x`
3. Get result from first screenshot.
4. `:call CocAction('doHover')<cr>`
5. get result from second screenshot

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/548993/82277257-af5d8d80-9987-11ea-9d63-4a0d726ccc8e.png)

![image](https://user-images.githubusercontent.com/548993/82277413-12e7bb00-9988-11ea-9487-843855a706f6.png)

**Comment by chemzqm** [comment]
Don't know the reason, try minimal vimrc and latest vim.

**Comment by fannheyward** [comment]
@sam-mccall Tested with nvim and Vim 8.2, can't reproduce this.

**Comment by sam-mccall** [comment]
(Sorry, I thought I'd already posted this comment)

Log is here: https://gist.github.com/sam-mccall/51f7fc2c82f3b06de5390f22ec4028ab

Indeed it doesn't reproduce in latest vim built locally. Unfortunately that doesn't help me much, as most of the users we're targeting are using packaged debian vim 8.1, and I can't really fix that (we tend to lag behind head by a year or so, and vim 8.2 is only 6 months old).

It sounds like you don't consider breaking in vim 8.1 a bug. I totally understand if you want to target latest neovim/vim only, and am very aware of how difficult and tedious it is to verify things work in multiple vim versions/flavors. It's a reasonable tradeoff and it's your project. For us it may mean not using it, which is sad.

**Comment by chemzqm** [comment]
> It sounds like you don't consider breaking in vim 8.1 a bug.

No, we should support vim 8.1.1610 for popup feature, we will try to reproduce.

**Comment by fannheyward** [comment]
Reproduce with macOS builtin vim 8.1

```
/usr/bin/vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 29 2020 00:47:39)
macOS version
Included patches: 1-503, 505-680, 682-2292
```

**Comment by fannheyward** [comment]
[e.log](https://github.com/neoclide/coc.nvim/files/4655760/e.log)

**Comment by chemzqm** [comment]
> Included patches: 1-503, 505-680, 682-2292

I don't have this version of vim.

**Comment by fannheyward** [comment]
This is the builtin vim in macOS 10.15.4

**Comment by chemzqm** [comment]
Problem with `bufsetline` on vim.
