### ISSUE TITLE
Diagnostics doesn't work for the most coc extensions on a fresh install

### ISSUE THREAD

**Issue by mikeTWC1984** [neoclide/coc.nvim#1954]
## Result from CocInfo
![image](https://user-images.githubusercontent.com/31977106/82346747-db4b3400-99c4-11ea-8176-6420ba46987b.png)

## Describe the bug

When installing coc.nvim and coc extensions on the fresh linux VM or docker diagnostics doesn't seem to work for the most extension (tried omnisharp/python/powershell/java). It works for coc-json and I also see it if editing vim files. 
It also works on systems I set up a while ago, even after updating plugins and coc extensions. The only difference was that on the old set up coc.nvim plugin was installed via 
 ```
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
```
Besides that the issue is agnostic to neovim version (same for vim) , node version, linux version or init.vim (same works on old set up and doen't on the new one). To reproduce - just install neovim/coc.nvim on a fresh linux VM / docker. Install coc-json and coc-python. Latter should no highlight any error or warning (but it will work for coc-json)

mini.vim
```
call plug#begin('~/.vim/plugged')
   Plug 'neoclide/coc.nvim', {'branch': 'release'}
   Plug 'sheerun/vim-polyglot'
   Plug 'vim-airline/vim-airline'
   Plug 'vim-airline/vim-airline-themes'
plug#end()
```

## Screenshots (optional)
Just a demo - json works and/ python doesn't
![image](https://user-images.githubusercontent.com/31977106/82347784-0da96100-99c6-11ea-957e-4a1f8a626858.png)

**Comment by oblitum** [comment]
Are you still installing which `coc#util#install()`?

**Comment by oblitum** [comment]
You should post your mini.vim for reproduction, not strip it from issue template.

**Comment by mikeTWC1984** [comment]
No, coc#util#install() doesn't work anymore. Using branch/release.
I added mini.vim but it doesn't really matter. I removed all possible settings, same effect. Same vim work on old set ups. Moreover diagnostics works with coc-json.

**Comment by oblitum** [comment]
It does matter, it would avoid the confusion regarding how you're installing it or not, which was not clear, it avoids further querying.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
