### ISSUE TITLE
Coc-python extension seems to search filesystem for Python libraries in an invalid way

### ISSUE THREAD

**Issue by benstaniford** [neoclide/coc.nvim#1957]
## versions

vim version: VIM - Vi IMproved 8.2 8020000
node version: v12.16.3
coc.nvim version: 0.0.78-d7b3084375
term: undefined
platform: win32

## Describe the bug

I'm running:

Vim 8.2 via Windows Gvim
Latest Coc release from your release branch (commit 9e1f8389)
Python 3.8.3.
Node 12.16.3
Whatever version of rope that Coc installed
The .vimrc from your github homepage.

After installing Python/Node/Coc I installed the Python extension.  This installed several tools and completion was soon working.  However, I discovered that refactoring did not work.  I got an error in my CocOpenLog saying that renaming had timed out.  Then after around 45 seconds, I saw a stack trace from rope:

[coc.nvim] Refactor failed. Syntax error in file <AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rh
kp1fndgsc/LocalState/rootfs/usr/lib/python2.7/lib2to3/pgen2/pgen.py> line <206>: Missing parentheses in call to 'print'.
Did you mean print("Dump of NFA for", name)?
[
<FrameSummary file refactor.py, line 294 in watch>,
<FrameSummary file refactor.py, line 274 in _process_request>,
<FrameSummary file refactor.py, line 206 in rename>,
<FrameSummary file refactor.py, line 117 in refactor>,
<FrameSummary file refactor.py, line 139 in onRefactor>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\rename.py, line 97 in get_changes>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\rename.py, line 195 in rename_in_module>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\occurrences.py, line 76 in find_occurrences>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\utils_init.py, line 12 in wrapper>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\occurrences.py, line 392 in source_code>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\utils_init.py, line 12 in _wrapper>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\occurrences.py, line 412 in pymodule>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\project.py, line 116 in get_pymodule>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pycore.py, line 142in resource_to_pyobject>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pycore.py, line 254 in get_pymodule>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pyobjectsdef.py, line 162 in init>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pyobjectsdef.py, line 191 in _init_source>]

This is a strange stack trace, because it appears that rope left my Windows environment and began searching my disk.  It found files belonging to a VM and it searched inside and found some older Python libraries.  Then it got a syntax error.  I raised this with the rope guys, but they were unable to help:

https://github.com/python-rope/rope/issues/298

However, one thing I noticed was that Coc-python plugin reports something suspicious.  It says:

2020-05-18T22:50:08.329 INFO (pid:6610) [extension-coc-python] - Python Extension: Create file systemwatcher with pattern */python
2020-05-18T22:50:08.333 INFO (pid:6610) [extension-coc-python] - Python Extension: Create file systemwatcher with pattern //python

Can you tell me, is this searching the disk for Python folders?  Is it possible it's searched into an area of the disk which is completely unrelated to my Python installation (in one of my VMs) and found some python folder?  If so, I think this would be a bug in Coc because I guess it should be relying on registered local configuration to find Python installations.

## Reproduce the bug

I'm sorry, but the instructions to create mini.vim don't work in my environment.  The cause this error:

https://imgur.com/a/fWZ7Rw9

Like I say, I'm just using the .vimrc from your page along with the default vim 82 plugin manager which installs a few plugins like gruvbox.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by benstaniford** [comment]
I'm running:

Vim 8.2 via Windows Gvim
Latest Coc release from your release branch (commit 9e1f8389)
Python 3.8.3.
Node 12.16.3
Whatever version of rope that Coc installed
The .vimrc from your github homepage.

After installing Python/Node/Coc I installed the Python extension.  This installed several tools and completion was soon working.  However, I discovered that refactoring did not work.  I got an error in my CocOpenLog saying that renaming had timed out.  Then after around 45 seconds, I saw a stack trace from rope:

[coc.nvim] Refactor failed. Syntax error in file <AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rh
kp1fndgsc/LocalState/rootfs/usr/lib/python2.7/lib2to3/pgen2/pgen.py> line <206>: Missing parentheses in call to 'print'.
Did you mean print("Dump of NFA for", name)?
[
<FrameSummary file refactor.py, line 294 in watch>,
<FrameSummary file refactor.py, line 274 in _process_request>,
<FrameSummary file refactor.py, line 206 in rename>,
<FrameSummary file refactor.py, line 117 in refactor>,
<FrameSummary file refactor.py, line 139 in onRefactor>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\rename.py, line 97 in get_changes>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\rename.py, line 195 in rename_in_module>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\occurrences.py, line 76 in find_occurrences>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\utils_init.py, line 12 in wrapper>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\occurrences.py, line 392 in source_code>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\utils_init.py, line 12 in _wrapper>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\occurrences.py, line 412 in pymodule>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\project.py, line 116 in get_pymodule>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pycore.py, line 142in resource_to_pyobject>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pycore.py, line 254 in get_pymodule>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pyobjectsdef.py, line 162 in init>,
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pyobjectsdef.py, line 191 in _init_source>]

This is a strange stack trace, because it appears that rope left my Windows environment and began searching my disk.  It found files belonging to a VM and it searched inside and found some older Python libraries.  Then it got a syntax error.  I raised this with the rope guys, but they were unable to help:

https://github.com/python-rope/rope/issues/298

However, one thing I noticed was that Coc-python plugin reports something suspicious.  It says:

2020-05-18T22:50:08.329 INFO (pid:6610) [extension-coc-python] - Python Extension: Create file systemwatcher with pattern */python
2020-05-18T22:50:08.333 INFO (pid:6610) [extension-coc-python] - Python Extension: Create file systemwatcher with pattern //python

Can you tell me, is this searching the disk for Python folders?  Is it possible it's searched into an area of the disk which is completely unrelated to my Python installation (in one of my VMs) and found some python folder?  If so, I think this would be a bug in Coc because I guess it should be relying on registered local configuration to find Python installations.

**Comment by oblitum** [comment]
Are you launching vim to open a python file from your home directory? In general language servers may present an issue with that on root discovery and assume your home directory is the root of project and scan everything there, you're responsible to avoid this in that case.

**Comment by benstaniford** [comment]
@oblitum 

Yeh, I'm editing ~/scripts/pipeline.py

On Windows this renders as c:\users\ben\scripts\pipeline.py

My CWD is c:\users\ben

However, the python files found are in:

$AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rh

Which is a VM that isn't in my home folder.  It's in my AppData folder (a Windows special directory belonging to the user but not part of their home/profile).

**Comment by benstaniford** [comment]
@oblitum Actually $AppData is C:\Users\Ben\AppData\Local

Is it possible then that my CWD being C:\Users\Ben has caused the langage server to search the whole appdata folder?  This seems like a bug in Windows environments because that folder is enormous and definitely not considered part of the home.

**Comment by oblitum** [comment]
Yes, I suspect that's the case.

**Comment by oblitum** [comment]
Check docs about a setting to exclude root folders and prevent language servers from loading. Not sure if it works for extensions.

**Comment by benstaniford** [comment]
@oblitum Invoking the rename while in a different working directory does seem to have stopped the stack trace.  Sadly the rename now fails silently with no error in the logs but I guess I'm past this particular language server issue.  Thanks for your help.

**Comment by oblitum** [comment]
k, you should prefer to open files from workspace root, not home, many language serves have this issue.
