### ISSUE TITLE
'.' Does not trigger completion in Python project.

### ISSUE THREAD

**Issue by Dissonant-Tech** [neoclide/coc.nvim#196]
**Describe the bug**
When working on a python project completion triggers when typing letters but does not trigger on '.'. Although, the menu does correctly populate when using 'C-x C-o'

'.' triggering completion does work in typescript. Just not python.

**Expected behavior**
Completions should trigger on '.'

**Screenshots**
Typing regularly works: 
![screenshot from 2018-11-27 15-26-34](https://user-images.githubusercontent.com/8030680/49109736-7c867d80-f259-11e8-90d7-8457b7b00666.png)

Entering '.' does not work
![screenshot from 2018-11-27 15-26-37](https://user-images.githubusercontent.com/8030680/49109735-7c867d80-f259-11e8-9a33-032458271320.png)

After pressing C-x C-o:
![screenshot from 2018-11-27 15-26-43](https://user-images.githubusercontent.com/8030680/49109734-7bede700-f259-11e8-9de0-91ade0796d82.png)

**Desktop (please complete the following information):**
 - Terminal: Urxvt
 - Version: v9.2.2

**Comment by chemzqm** [comment]
It should be timeout, pyls quite slow sometimes, check messages by `:messages`, you should get the message. You can change timeout by `  "coc.preferences.timeout": 3000,` in your coc-settings.json.

**Comment by Dissonant-Tech** [comment]
Thanks for the quick reply! Unfortunately that doesn't seem to be the issue. `:messages` is empty and changing the timeout doesn't seem to work.

Also, using C-x C-o is (at least currently) very fast, so I'm not sure it would be hitting the timeout, especially now that I've set it to 3000.

**Comment by chemzqm** [comment]
Maybe pyls doesn't understand your code, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel to get the output from language server.

**Comment by Dissonant-Tech** [comment]
Thanks for all the help! The issue was a missing `coc-pyls`. For the record `coc-pyls` is missing from [the list of packages](https://www.npmjs.com/search?q=keywords%3Acoc.nvim) returned by the NPM search query.

Thanks again for the help +1
