### ISSUE TITLE
Indenting and Formatting

### ISSUE THREAD

**Issue by nomo-nomad** [neoclide/coc.nvim#1960]
I read through everything I could find in the help docs and haven't been able to figure out how to disable a specific warning or formatting error such as "mix-indent-file". It's not something vital, but I use tabs for indentation and spaces for alignment. If I missed a wiki or FAQ doc, sorry!

**Comment by chemzqm** [comment]
The reason is we don't have such kind of feature.

**Comment by chemzqm** [comment]
You have to fix the problem or silent your service for such kind of diagnostic.
