### ISSUE TITLE
How to change coc-config.json's property's Value for Current buffer?

### ISSUE THREAD

**Issue by collegeimprovements** [neoclide/coc.nvim#1961]
### How to  change `coc-config.json`'s `property`'s Value for Current buffer?
![Screenshot 2020-05-20 at 4 36 38 PM](https://user-images.githubusercontent.com/1519705/82439335-15e1c900-9ab8-11ea-83f3-8265659c9fe3.png)

I've the following line in my `coc-config.json` file.
```
 "codeLens.enable": true,
```

Is there any way to toggle the `codeLens.enable` property `false` and `true` with some command for current buffer ? 

#amiralies/coc-elixir/issues/19

**Comment by chemzqm** [comment]
`:h coc#config()`

**Comment by chemzqm** [comment]
The configuration could be changed, but it doesn't refresh your current codeLens on UI.

**Comment by collegeimprovements** [comment]
You're awesome. Thanks @chemzqm 🙌🏼
