### ISSUE TITLE
Hide :CocUpdate results window or redirect to a log.

### ISSUE THREAD

**Issue by lc9er** [neoclide/coc.nvim#1962]
**Is your feature request related to a problem? Please describe.**
After a recent update, the daily automatic CocUpdate command opens a vertical split with extension update results. 

**Describe the solution you'd like**
I'd like an option to suppress this window, or maybe just log results to a file.

**Describe alternatives you've considered**
Disabling automatic updates and run them manually.

**Additional context**
coc.nvim version: 0.0.78-23d26d8e02

**Comment by chemzqm** [comment]
It can be disabled

**Comment by lc9er** [comment]
I checked schema.json and :h coc-variable, and I can't find how to do that.
Any suggestions?

Thank you

**Comment by kovetskiy** [comment]
@lc9er did you find out how to disable this behavior?

**Comment by chemzqm** [comment]
I mean disable auto update, `:h coc-config`

**Comment by kovetskiy** [comment]
@chemzqm I believe in the original issue it was asked if there is any option to suppress the window, not the automatic update. My everyday workflow now is to start vim and close window created by coc.nvim, would be great to have the same behavior as a few weeks ago when plugin updates were working fine but I didn't need to close any additional windows.

**Comment by chemzqm** [comment]
Use `CocUpdateSync` if you don't like split window.
