### ISSUE TITLE
vim-repeat integration causes unexpected behavior

### ISSUE THREAD

**Issue by luan** [neoclide/coc.nvim#1965]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v14.2.0
coc.nvim version: 0.0.78-70aac81740
term: xterm-256color
platform: linux

## Output channel: snippets
[Info 7:57:21 AM] Using ultisnips directories: UltiSnips gosnippets/UltiSnips /home/luan/.config/coc/ultisnips
[Info 7:57:21 AM] Using ultisnips python command: pyx


## Output channel: highlight
[Info  - 7:57:22 AM] Highlight server running in node v14.2.0
```

## Reproduce the bug

- Create file `mini.vim` with (needs vim-repeat and at least one action that triggers somehow, in this case I'm using my golang autoformat command)

```vim
set nocompatible
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
set runtimepath^=~/.local/share/nvim/plugged/vim-repeat
autocmd BufWritePre *.go :call CocAction('runCommand', 'editor.action.organizeImport')
filetype plugin indent on
syntax on
set hidden
```

- Start (neo)vim with command: `vim -u mini.vim somefile.go`

- Make a change, save.

- try using `.` to repeat that previous change, see this printed on the command line:
```
:call       CocAction('repeatCommand')
```

## Notes

I know that this is happening because of my `BufWritePre` hook in this case. I got that recommendation on this issue: https://github.com/neoclide/coc.nvim/issues/888. And as someone points out there, this is extremely common in Go development and I (and I assume a lot of Go devs) don't think of it as an action that needs repeating. I don't see a way of disabling this in any way, it'd be nice to have it be disable-able on a per `CocAction` call.

**Comment by luan** [comment]
oops hit enter too soon, editing

**Comment by chemzqm** [comment]
It's feature, you have to invoke codeAction without command.

**Comment by luan** [comment]
Could you point me to where this feature is documented? I couldn't find it.
