### ISSUE TITLE
Strange symbols in popups

### ISSUE THREAD

**Issue by lervag** [neoclide/coc.nvim#1968]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-132-g83b6d9f19
node version: v14.2.0
coc.nvim version: 0.0.78-23d26d8e02
term: xterm
platform: linux

## Output channel: snippets

[Info 10:14:34 AM] Using ultisnips directories: UltiSnips /home/lervag/.config/coc/ultisnips
[Info 10:14:34 AM] Using ultisnips python command: pyx

## Output channel: Python

Starting Jedi Python language engine.
```

## Describe the bug

In recent updates the floating windows for e.g. function signatures have changed and there's now strange symbols, see the following screenshot:

![screen](https://user-images.githubusercontent.com/998898/82538805-96520980-9b4c-11ea-9940-e4449c73f5de.png)

I'll be happy to add more details, but I was wondering if you first would know immediately what might cause this.

**Comment by chemzqm** [comment]
You font doesn't support `—`

**Comment by lervag** [comment]
Ok, thanks. Is it possible to specify a different symbol?

**Comment by chemzqm** [comment]
No

**Comment by lervag** [comment]
Then I would suggest that one either changes the symbol to something more readily available, or to allow specifying a different symbol. Why not simply use a normal dash `-` or [box drawings light horizontal `─`](https://unicode-table.com/en/2500/)?

**Comment by chemzqm** [comment]
We should use horizon line, thanks.
