### ISSUE TITLE
Support for automatically applying certain quickfixes 

### ISSUE THREAD

**Issue by sheerun** [neoclide/coc.nvim#1973]
**Is your feature request related to a problem? Please describe.**

When I write code in Go I often use quick command to automatically add imports. In fact I use it always when when it becomes available. It would be nice if coc.nvim could automatically apply certain quickfixes instead of listing them as diagnostic warnings / errors.

**Describe the solution you'd like**

It would be nice if I was able to configure which quickfixes coc.nvim should apply automatically. Eg.:

```json
{
  "diagnostic.autofix": ["Add import"]
}
```

the configuration above would make coc.nvim to automatically apply quickfixes that have "Add import" in their description.

**Describe alternatives you've considered**

I'm not aware of any way to do it automatically without changes in coc.nvim

**Comment by chemzqm** [comment]
Seems reasonable, but we should use diagnostic code instead

**Comment by tmerse** [comment]
For the time being, the possibility to add multiple Quickfix-Instructions in one run would be helpful for me.

```
Choose by number:
1. Add 'FC' to existing import declaration from "react"
2. Add import
3. Convert named imports to namespace import
4. Move to a new file
5. Fix this prettier/prettier problem
6. Disable prettier/prettier for this line
7. Disable prettier/prettier for the entire file
8. Show documentation for prettier/prettier
Type number and <Enter> or click with mouse (empty cancels):
```

For example the possibility to add a selection of multiple quickfix instructions by typing a comma-separated list of numbers (e.g. `1, 5,` to run fixes 1 and 5). Because now I have to open the dialog window multiple times for multiple fixes which always takes a bit of time.

**Comment by chemzqm** [comment]
> For example the possibility to add a selection of multiple quickfix instructions by typing a comma-separated list of numbers (e.g. 1, 5, to run fixes 1 and 5)

No, actions could be conflict.

**Comment by chemzqm** [comment]
Could be implemented by make use of `:h coc-action-codeActions` and `:h coc-action-doCodeAction`
