### ISSUE TITLE
coc's buf write autocmd seems to break `echo`s

### ISSUE THREAD

**Issue by ZSaberLv0** [neoclide/coc.nvim#1977]
## versions

vim version: VIM - Vi IMproved 8.2 8020400
node version: v12.9.1
coc.nvim version: 0.0.78-05f8f7bd71
term: dumb
platform: darwin

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  execute 'set runtimepath^=' . $HOME . '/.vim/bundle/coc.nvim'
  filetype plugin indent on
  syntax on
  set hidden
  
  function! Test()
      redraw!
      echo 123
      echo 456
  endfunction
  nnoremap <silent> zz :w<cr>:call Test()<cr>
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- edit a file, modify contents and use `zz` to write and echo, and see screenshots below

## Screenshots (optional)

* with coc not enabled, or, if file contents not changed when `zz`
![image](https://user-images.githubusercontent.com/6846867/82647039-26c14480-9c48-11ea-8d5a-8f62b29c0917.png)

* with coc enabled and file contents changed before `zz`
![image](https://user-images.githubusercontent.com/6846867/82647081-38a2e780-9c48-11ea-983e-ecb502d31021.png)

**Comment by chemzqm** [comment]
It's vim's bug of channel with your terminal, and I can't reproduce it on Mac and Linux.

**Comment by ZSaberLv0** [comment]
```
## versions

vim version: VIM - Vi IMproved 8.2 8020000
node version: v12.14.1
coc.nvim version: 0.0.78-05f8f7bd71
term: undefined
platform: win32
```

Windows gVim also occur

f4cdc6545347e05a48b18ec2b0852513960df79a seems to be the first release commit that reproduce the issue

**Comment by chemzqm** [comment]
I've update my comment, it can't be avoided unless fixed by vim.

**Comment by ZSaberLv0** [comment]
I've found a workaround:

```
function! SaveAndRun()
    let b:coc_diagnostic_disable=1
    update

    redraw!
    echo 123
    echo 456

    unlet b:coc_diagnostic_disable
endfunction
nnoremap <silent> zz :call SaveAndRun()<cr>
```

simply `:CocDisable` before write does not work

@chemzqm maybe you could add some way to **temporarily** disable all coc events?

**Comment by chemzqm** [comment]
`:CocDisable` already does that.
