### ISSUE TITLE
"call coc#add_command" 自定义命令不显示

### ISSUE THREAD

**Issue by pacmanzou** [neoclide/coc.nvim#1984]
这个可以自己添加命令的方法失效了，前几天还是正常的，现在CocComands里根本不出现这个自定义命令的选项。mini.vim也尝试了，还是不出现，是不是把这个方法取消了啊？

![截图录屏_Alacritty_20200524122216.png](https://img01.sogoucdn.com/app/a/100520146/b898c48ad43cd449538b6df1eb0e8bec)

![截图录屏_选择区域_20200524122018.png](https://img03.sogoucdn.com/app/a/100520146/1b5532b1cb03b24b4fa2463811b2ef03)

**Comment by chemzqm** [comment]
去掉了

**Comment by pacmanzou** [comment]
嗯 不过感觉这功能很好啊
