### ISSUE TITLE
Invoke :coc#start({'source': my_source'

### ISSUE THREAD

**Issue by ludvikn** [neoclide/coc.nvim#1985]
**Is your feature request related to a problem? Please describe.**
I have this mapping in my ```init.vim```:
```inoremap <C-x><c-p> <c-r>=coc#start({'source': 'yank'})<CR>```. Currently, it only show my yank-history when I type a minimum of 1 character, and I have an item in my yank-history which matches this character.

**Describe the solution you'd like**
I would like to be able to make the popup-menu appear without having to type any characters. If I could do this, browsing and selecting yanks would be a breeze.

**Describe alternatives you've considered**
I am aware of ```:CoCList yank```, but I prefer the usability of the popup menu.

**Additional context**

**Comment by oblitum** [comment]
Shouldn't this be opened on https://github.com/neoclide/coc-yank?

**Comment by ludvikn** [comment]
I considered it. I do not know CoC that well, but it seems to me that coc-yank is merely providing the source in this case.

I guess, more specifically what I am asking for is this:
how to open the popup menu for **any** source, without having to type any characters.

**Comment by chemzqm** [comment]
Use yank list, the yarnk source doesn't provide compeltion for empty input.
