### ISSUE TITLE
 Linting does not work in Insert mode

### ISSUE THREAD

**Issue by rbhanot4739** [neoclide/coc.nvim#1986]
## Result from CocInfo
vim version: NVIM v0.4.3
node version: v12.16.2
coc.nvim version: 0.0.78-881f98ce99
term: iTerm.app
platform: darwin

## Describe the bug
Setting `diagnostic.refreshOnInsertMode: true` in `coc-settings.json` does not enable linting in insert mode. I am using `coc-python` with `jedi` set to `true`, whenever I open a python file, diagnostic only runs after saving the file and does not run instantly in insert mode. I have set `diagnostics.refreshOnSave: false`.

## Reproduce the bug

Load nvim without any custom settings/mappings/autocommands using the below mini.vim
Open any python file (since I use coc-python) go to insert mode and start typing, the diagnostics engine does not start until I exit the Insert mode and `write` the file.

## mini.vim

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

**Comment by rbhanot4739** [comment]
How can I get this change?

**Comment by krehwell** [comment]
in `:CocConfig` put 
```json 
{
    "diagnostic.refreshOnInsertMode": true,
}
`
