### ISSUE TITLE
Can't run on windows

### ISSUE THREAD

**Issue by dakom** [neoclide/coc.nvim#1989]
I'm not sure what more info to provide, please let me know... here's a start:

## :CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v11.14.0
coc.nvim version: 0.0.78-0c973a7a47
coc.nivm directory: C:\Users\david\.local\share\nvim\plugged\coc.nvim
term: undefined
platform: win32
```

## :CocOpenLog

```
Failed to open C:\Users\david\AppData\Local\Temp\coc.nvim-1492\coc-nvim.log
```

## :CocList commands

Shows entries for tsserver, rust-anlyzer, etc.

However, trying to actually run them fails

**Comment by chemzqm** [comment]
What does `fails` means?

**Comment by dakom** [comment]
I'm not sure what the cause is - but I can't run the commands in `:CocList commands` and also `:CocOpenLog` can't find the log file

I tried wiping and re-installing the vim-plug folder, and re-installing the extensions, but it didn't fix.

That said my OS drive is gathering a bit of dust and I'm looking to reformat soon. If nobody else is experiencing problems, I could just try again after I reformat next week-ish ;)

**Comment by dakom** [comment]
I tried uninstalling NeoVim completely, and re-installing (via choco). Tried deleting plugins. Same problem.

Is anyone else running with latest NeoVim on Windows?

**Comment by dakom** [comment]
D'oh... although at first Coc itself genuinely wasn't working, now after re-installing I could get it to work - but wasn't checking acurately since coc commands requires that there be a real file open (e.g. trying to restart the ts server, without having a typescript file open, doesn't work)

Closing for now :)
