### ISSUE TITLE
Small question: `<CR>` or `<C-g>u\<CR>` to complete snippet?

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#199]
In README:

```
" Coc only does snippet and additional edit on confirm.
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```

In snippets wiki: https://github.com/neoclide/coc.nvim/wiki/Using-snippets/_compare/0d791a8^...0d791a8#diff-1abe99a5e6ecd5d84e24b03c82a0ad1cL16

```
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<CR>"
```

Which is recommended or prefer?

**Comment by chemzqm** [comment]
The explantation http://vim.wikia.com/wiki/Modified_undo_behavior#Comments, you can choose whether to make `<CR>` break your undo.

**Comment by chemzqm** [comment]
I've add explantation to readme.
