### ISSUE TITLE
b:coc_diagnostic_disable should clear diagnostics info

### ISSUE THREAD

**Issue by davidsierradz** [neoclide/coc.nvim#1990]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-525-g97bcab8f5
node version: v14.3.0
coc.nvim version: 0.0.78
coc.nivm directory: /home/neuromante/dotfiles/all/.config/nvim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Output channel: markdownlint

[11:03:11 AM] Info: global config: {"_":[]}
[11:03:11 AM] Info: config from coc-settings.json: {"default":true,"line_length":false}
[11:03:11 AM] Info: full config: {"_":[],"default":true,"line_length":false}

```

## Describe the bug

When we enable `b:coc_diagnostic_disable` to disable diagnostics COC should clear the diagnostics highlights, the diagnostics signs and the output of `b:coc_diagnostic_info` (to clear statusline also).

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  call plug#begin('~/.config/nvim/plugged')
  Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
  call plug#end()
  let g:coc_global_extensions = [
        \ 'coc-markdownlint'
        \ ]
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Open or create a `markdown` file with errors:

  ```markdown
  ## foobar
  # foo
  ```

We see errors:

![image](https://user-images.githubusercontent.com/9190258/82924790-7a7ea700-9f42-11ea-874e-6cf96794f909.png)

also, diagnostics from `b:coc_diagnostic_info`:

  ```
  :echo b:coc_diagnostic_info
  {'information': 0, 'hint': 0, 'lnums': [0, 1, 0, 0], 'warning': 4, 'error': 0}
  ```

- Disable diagnostics at buffer level:

  ```
  :let b:coc_diagnostic_disable=1
  ```

We still see all the visual artifacts related to diagnostics:

![image](https://user-images.githubusercontent.com/9190258/82925173-00025700-9f43-11ea-9db8-f71089cfb552.png)

also, diagnostics from `b:coc_diagnostic_info`:

  ```
  :echo b:coc_diagnostic_info
  {'information': 0, 'hint': 0, 'lnums': [0, 1, 0, 0], 'warning': 4, 'error': 0}
  ```

Thanks!

**Comment by chemzqm** [comment]
No

**Comment by JakeElder** [comment]
> No

Is there another way to enable/disable diagnostics? I have tried this

```vim
" Function that toggles Coc diagnostics
function! s:toggle_diagnostics()
  if coc#util#get_config('diagnostic').enable
    set signcolumn=no
    call coc#config('diagnostic', { 'enable': v:false })
  else
    set signcolumn=yes
    call coc#config('diagnostic', { 'enable': v:true })
  endif
  silent call coc#rpc#restart()
endfunction
```

But it's clunky and takes a long time. It also leaves markings sometimes.

**Comment by chemzqm** [comment]
You have to set `b:coc_diagnostic_info` on buffer create.

**Comment by JakeElder** [comment]
I'm not sure I understand. From what I can tell from the documentation, `b:coc_diagnostic_info` is populated by Coc with the current state of diagnostics.

I have tried modifying the value after diagnostics have been displayed like this, but it has no effect.

```vim
" Attempt to disable and hide Coc diagnostics
let b:coc_diagnostic_disable=1
let b:coc_diagnostic_info={'information': 0, 'hint': 0, 'lnums': [0, 0, 0, 0], 'warning': 0, 'error': 0}
```

What I'm trying to achieve is being enable/disable diagnostics while I edit

IE
1. Open a buffer (no diagnostics are visible)
2. Make changes (still no diagnostics visible)
3. Enable diagnostics (errors and warnings are shown)
4. Disable diagnostics (all errors and warnings are hidden)

**Comment by chemzqm** [comment]
There is no such kind of feature.

**Comment by JakeElder** [comment]
Thank you @chemzqm , I can see you've committed a new feature. I've pulled the latest Coc and run 

```vim
:call CocAction('diagnosticToggle')
```

It seems to work great. Nicely done 🙂
