### ISSUE TITLE
<Plug>CocRefresh appears whenever i open paranthesis in css files

### ISSUE THREAD

**Issue by joe23rep** [neoclide/coc.nvim#1991]
hi- im just getting into neovim and just followed a few tutorials about coc.nvim and im loving it so far. so far it works really great and i wouldnt want to miss it. ive one issue tho where i cant find an answer. i searched threw older issues but this wasnt mentioned. 

when ever im in a css file and i want to add something in paranthesis (like say for example):

`background-color: var(--bg-color)`

i write background-color: var(

and i get this:

`background-color: var(<Plug>CocRefresh)`

ive no special configuration just yet. just the basic config from the github example and i installed a few extensions via CocInstall coc-css coc-eslint etc.

is there anything i can do that i get rid of this?

**Comment by chemzqm** [comment]
Can't help without minimal vimrc of reproduce way.
