### ISSUE TITLE
Coc doesn't work for lanugage autocompletion

### ISSUE THREAD

**Issue by Godnyx** [neoclide/coc.nvim#1992]
## Result from CocInfo

vim version: NVIM v0.4.3
node version: v14.2.0
coc.nvim version: 0.0.78-0c973a7a47
coc.nivm directory: /home/godnyx/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Describe the bug

Coc does generic word autocpletion but not language specific. What I mean is that I will open a file (eg. Python, C++) and I will start typing words any it will prompt me for this words but not for every language word. So yeah it works but only for the words I'm typing. The wired thing and the one reminded me that I most solve this problem (cause it happens since I've installed Coc) is that yesterday it worked when I opened a python file and it then it stopped working suddenly after switching buffers. And then it never worked again. That was the first and last time Coc properly worked for me.

## Reproduce the bug

I've done it and it doesn't fix the problem. Also I tried with the example configuration and it still doesen't works. My current config is:
Plug 'neoclide/coc.nvim', {'branch': 'release'}
inoremap <silent><expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
inoremap <silent><expr><a-tab> pumvisible() ? "\<c-p>" : "\<s-tab>"

Just these three lines. But no matter what I've tried it doesn't work.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

None. I don't think it will help anyway...

**Comment by chemzqm** [comment]
It's expected, it's not YCM and you have to install extension or configure language server.

**Comment by Godnyx** [comment]
Oh! I didn't knew. Tho why Python worked yesterday? Is this normal?

**Comment by chemzqm** [comment]
Probably it was from other vim plugin.
