### ISSUE TITLE
Docs tips window not disapper after press ESC or Select

### ISSUE THREAD

**Issue by ehyyoj** [neoclide/coc.nvim#1993]
## Result from CocInfo

  vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 17 2020 17:54:23)
  node version: v12.16.1
  coc.nvim version: 0.0.78-89c0c2380b
  term: dumb
  platform: linux(on darwin also has this bug)

## Describe the bug

Docs tips window not disapper after press ESC or Select.

![1590573388531](https://user-images.githubusercontent.com/9150170/83005508-74bcba80-a043-11ea-8cf7-dd8da20e65da.jpg)

## Reproduce the bug
1. write some code
2. show the completion and docs
3. press `Tab` to select and then press `ESC`
4. the docs window not disapear

`.vimrc`:
https://github.com/ehyyoj/IDE-Config/blob/master/vim/.vimrc

**Comment by chemzqm** [comment]
```
* 89c0c238 - fix(list): avoid double cursors when &guicursor is empty (3 months ago)
```
you're using release version that 3 months ago, upgrade coc.nvim to latest release.

**Comment by ehyyoj** [comment]
thanks, it solved by upgrade to the latest version. I was curious why the version is the same but the commit hash was different.
coc.nvim version: 0.0.78-89c0c2380b (before, has bug)
coc.nvim version: 0.0.78-3c774fbfa5(now, it's ok)
