### ISSUE TITLE
Installing coс.nvim only in neovim without vim.

### ISSUE THREAD

**Issue by dikoobrazz** [neoclide/coc.nvim#1999]
**System:** Linux
**Distribution:** Arch Linux

Installed in the system **vim** and **neovim**:

> vim -> $Home/.vim/vimrc
> neovim -> $HOME/.config/nvim/init.vim

I install the coc.vim for neovim (used vim-plug), but he appeared in my vim!
There are no coc entries in the vim config file.

How to leave the **vim** clean from **coc**?

**Comment by michalrus** [comment]
> Distribution: Arch Linux

@dikoobrazz incorrect behaviors like these might inspire you to try a more immutable distribution, e.g. NixOS. (ﾉ^_^)ﾉ

**Comment by chemzqm** [comment]
It's not issue of coc.nvim.
You should be able to use `has('nvim')` for detect neovim.
