### ISSUE TITLE
Error on execute python script

### ISSUE THREAD

**Issue by Godnyx** [neoclide/coc.nvim#2000]
## versions                                                             
                                                                
vim version: NVIM v0.4.3                                                             
node version: v14.2.0                                                             
coc.nvim version: 0.0.78-6fc0d73c13                                                             
coc.nivm directory: /home/godnyx/.config/nvim/plugged/coc.nvim                                                             
term: xterm-256color                                                             
platform: linux                                                             
                                                                
## Output channel: snippets                                                             
                                                                
[Info 9:39:13 PM] Using ultisnips directories: UltiSnips /home/godnyx/.config/coc/ultisnips                                   
[Info 9:39:13 PM] Using ultisnips python command: pyx                                                             
Error on execute python script:                                                             
request error nvim_command - Vim(return):Error invoking 'python_execute_file' on channel 4 (python3-script-host):
Traceback (most recent call last):                                                             
  File "/tmp/coc.nvim-157387/coc-ultisnips-WC-2O-Dydx.py", line 293, in <module>                                              
    from javascript_snippets import (                                                             
ModuleNotFoundError: No module named 'javascript_snippets'

## Describe the bug

I'm taking an error. That's the output:

[coc.nvim] Error on execute python script: request error nvim_command - Vim(return):Error invoking 'python_execute_file' on cha
nnel 4 (python3-script-host):
Traceback (most recent call last):
File "/tmp/coc.nvim-155053/coc-ultisnips-tktR_CCdRe.py", line 293, in
from javascript_snippets import (
ModuleNotFoundError: No module named 'javascript_snippets'

I can't say anything else cause really I don't understand what's going on. Yeah I know it can't find this module but since I haven't done any configuration I think It's not my fault.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

This works! And in general it works when disabling coc-snippets. The thing is that I swear it was working and then it prudently stopped. Any idea?

**Comment by chemzqm** [comment]
Should be problem with your snippet.

**Comment by josuerom** [comment]
Buen día, aún no he podido darle solución a ese molestoso error pero seguiré averiguando, en cuánto la halle, por este medio la publicaré, gracias.

**Comment by lasorda** [comment]
i solve this with uninstall all pynvim, include python3 and python2, include users and systems. reinstall pynvim

**Comment by lasorda** [comment]
i solve this with uninstall all pynvim include users and system (python3 and python2), reinstall pynvim

**Comment by rempas** [comment]
> i solve this with uninstall all pynvim include users and system (python3 and python2), reinstall pynvim

Thank you for the answer! However, I now use Neovim's built-in LSP so no problems there!
