### ISSUE TITLE
Inconsistency with root_patterns

### ISSUE THREAD

**Issue by ckipp01** [neoclide/coc.nvim#2001]
I've had multiple users of `coc-metals` mention that the `root_patterns` seems to be not behaving as expected. After some testing I'm a bit confused at how this is working, and have a way to reproduce this.

`coc-metals` contributes the following `root_patterns`:

```json
      {
        "filetype": "scala",
        "patterns": [
          "build.sbt",
          "build.sc",
          "build.gradle",
          "pom.xml"
        ]
      }
```

I have an example repo [here](https://github.com/ckipp01/metals-minimal-sbt) that can be used to demonstrate.

## Steps to demonstrate correct behavior 
- Clone the repo
- `:CocInstall coc-metals`
- `cd src/main/scala/example`
- `nvim Hello.scala`

It seems to correctly identify the root of the root of the workspace, and you'll notice that a `.metals/` directory is created there, and the user should be prompted to import the build.

`:echo coc#util#root_patterns()` shows the following while this happens:

```js
{'global': ['.git', '.hg', '.projections.json'], 'buffer': [], 'server': ['build.sbt', 'build.sc', 'build.gradle', 'pom.xml']}
```

## Now produce the issue
- Ensure that the `.metals/` directory, the `.bloop/` directory and the `project/metals.sbt` file are all deleted (basically, go back to a clean workspace)
- Delete the `.git/` directory. 
- Repeat the steps above:
	- `cd src/main/scala/example`
	- `nvim Hello.scala`

The initialize process shows the `rootPath` as `src/main/scala/example` instead of the actual root of the project. It seems that the `root_patterns` provided by the server aren't being taken into account, and the `build.sbt` file is not correctly being found since the `.git` directory was removed. The result of `:echo coc#util#root_patterns()` is still exactly the same as it was above.

## Result from CocInfo

```
vim version: NVIM v0.5.0-2ca8f02
node version: v14.2.0
coc.nvim version: 0.0.78
coc.nivm directory: /Users/ckipp/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

I've tried this with the above, but also with Vim and a minimal `.vimrc`. None of that seems to matter.

**Comment by chemzqm** [comment]
> Ensure that the .metals/ directory, the .bloop/ directory and the project/metals.sbt file are all deleted (basically, go back to a clean workspace)

Do your mean `project/build.sbt` instead of `project/metals.sbt`?

**Comment by ckipp01** [comment]
No, there is no `project/build.sbt`, and there should be.

**Comment by chemzqm** [comment]
Yes, it resolved correct project root unless I have `build.sbt` removed from project root.

**Comment by fannheyward** [comment]
Reproduced. When `getRootPatterns`, extensions are not inited, did not set `contributes.rootPatterns` to `workspace.rootPatterns`, so `build.sbt` patterns doesn't exist.

https://github.com/neoclide/coc.nvim/commit/44f8790d2a88fe5a38e7993ba0c10e35cd2c6a6a#diff-9c712ef008f0c005b1e21d9c82dfa57bL149

This commit moved `extensions.init` behind `workspace.init`.

**Comment by chemzqm** [comment]
I was using metals from configuration of languageserver.

**Comment by fannheyward** [comment]
Yes, `languageserver.XXX` will work.
