### ISSUE TITLE
Diagnostic popup cause flicker in vim

### ISSUE THREAD

**Issue by dedowsdi** [neoclide/coc.nvim#2004]
Diagnostic popup window cause flicker in vim 8.2 1-766, urxvt v9.22, ubuntu18.04. After some debugging, the culprit is this line: https://github.com/neoclide/coc.nvim/blob/95e7ca83242e38c162ac85fba875faee81f0b372/autoload/coc/util.vim#L220

vim redraw everything if you change `signcolumn`, even for a popup window, not sure if it's a bug.

AFAIK, `signcolumn` defaults to `no` for vim popup window.

Comment it would solve the issue, but I don't know how would it affect neovim.

This won't happen inside tmux.

**Comment by chemzqm** [comment]
Thanks for the tip.

**Comment by dedowsdi** [comment]
There is something wrong with my urxvt, it flickers after a full screen scroll.  I guess it's  the same reason why change `'signcolumn'` flickers. 

Most people can't reproduce it, see this [question](https://vi.stackexchange.com/questions/25487/flicker-during-scroll-in-single-window) if you have the same problem.

Sorry for the noise.

**Comment by hdnha11** [comment]
I have the same issue on Vim 8.2.850, iTerm2 3.3.9, macOS 10.15.4. It is hard to see if run with the `mini.vim` but if I run with my [vimrc](https://github.com/hdnha11/dotfiles/blob/master/.vimrc) it flickers a lot:

![bad](https://user-images.githubusercontent.com/1773032/83485740-dfea0f00-a4d1-11ea-8149-8be070a7070d.gif)

Confirm that remove `call setwinvar(winid, '&signcolumn', 'no')` line in `util.vim` can help.
