### ISSUE TITLE
Major bug after updating to 0.0.78-bcb2fe977c: UnhandledRejection: request error nvim_eval - Vim:E117: Unknown function: coc#util#valid_state

### ISSUE THREAD

**Issue by yedhink** [neoclide/coc.nvim#2005]
## versions

vim version: NVIM v0.5.0-357-g405f49a9b
node version: v14.3.0
coc.nvim version: 0.0.78-bcb2fe977c
term: xterm-kitty
platform: linux

## Describe the bug
```
[coc.nvim] error: UnhandledRejection: request error nvim_eval - Vim:E117: Unknown function: coc#util#valid_state                                       
Error: request error nvim_eval - Vim:E117: Unknown function: coc#util#valid_state                                                                      
    at /home/ikigai/.local/share/nvim/plugged/coc.nvim/build/index.js:14273:32                                                                         
    at /home/ikigai/.local/share/nvim/plugged/coc.nvim/build/index.js:10919:13                                                                         
    at NvimTransport.parseMessage (/home/ikigai/.local/share/nvim/plugged/coc.nvim/build/index.js:10860:17)                                            
    at DecodeStream.<anonymous> (/home/ikigai/.local/share/nvim/plugged/coc.nvim/build/index.js:10830:18)                                              
    at DecodeStream.emit (events.js:315:20)                                                                                                            
    at addChunk (_stream_readable.js:302:12)                                                                                                           
    at readableAddChunk (_stream_readable.js:278:9)                                                                                                    
    at DecodeStream.Readable.push (_stream_readable.js:217:10)                                                                                         
    at DecodeStream.Transform.push (_stream_transform.js:152:32)                                                                                       
    at DecodeBuffer.DecodeStream.decoder.push (/home/ikigai/.local/share/nvim/plugged/coc.nvim/build/index.js:13797:12) 
```
Updated the plugin to latest (95e7ca8 refactor(completion): reduce communicate with vim (26 hours ago)) using vim-plug. Was editing a c++(.cpp) file. Completion is auto-triggered when I start typing, and after selection of one of the choice, and pressing `ESC`(normal mode) key more than once this error pops up. Most of the time the error pops up when completing function names and pressing `ESC`  near parentheses. Also the definition window/popup of a particular function stays on screen even after completion is over. Refer gif attached at bottom for example.

## Reproduce the bug
In my system I tried with the following `init.vim` and `coc-settings.json` and still error produced:-
```
" init.vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
call plug#end()
```
```json
{
	"languageserver": {
		"clangd": {
			"command": "clangd",
			"filetypes": ["c", "cpp", "objc", "objcpp"]
		}
	}
}
```
Then create a new c++ file say  `nvim try.cpp`, and then type from scratch:-
```cpp
#include <iostream>
int main(){  ---> press ESC multiple times over here
}
```

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

Tried the `mini.vim` with nvim and getting the same error. In vim the plugin doesn't load.

## Screenshots (optional)

Attaching a gif showing what is happening.
https://asciinema.org/a/uekajyS79TJLhPKBRQlFcWVS4

**Comment by oblitum** [comment]
I'm on arch too, can't reproduce your issue. Running latest neovim release, not nigthly.

**Comment by oblitum** [comment]
Fyi, `coc#util#install()` isn't recommended/used anymore.

**Comment by oblitum** [comment]
The version you're reporting is one month late.

**Comment by oblitum** [comment]
Hmm, reopening. Just noticed you reported to have upgraded to latest in comment.

**Comment by chemzqm** [comment]
coc#util#install is won't work any more, you have to compile the code when using master branch.

**Comment by zgiber** [comment]
Was the issue resolved, or has this been closed for not being able to reproduce it? I'm having the same error message after having upgraded with vim-plug's PlugUpdate. I'm using it with vim-go.

**Comment by oblitum** [comment]
@zgiber `-> coc#util#install()` isn't used anymore, check readme instructions.

**Comment by chemzqm** [comment]
You need remove the folder after switch branch for now, we need figure out if we can avoid it

**Comment by yedhink** [comment]
@zgiber The issue was fixed for me by updating my neovim and reinstalling coc.nvim in the newly recommended way.

**Comment by 0x4ndy** [comment]
Can you please send me a link to the instructions? I'm having a problem ``"coc.preferences.formatOnSaveFiletypes"`` is present in my ``~/.config/nvim/coc-settings.json``. I want to use it so that the formatter is activated when I save the file - is there an alternative?

**Comment by chemzqm** [comment]
Use `autocmd BufWritePre` which is more flexiable.
