### ISSUE TITLE
How to dismiss some kinds of warnings/errors

### ISSUE THREAD

**Issue by dakom** [neoclide/coc.nvim#2007]
Sometimes warnings or errors pop up and I can't dismiss them without moving away from the line.

How can I dismiss them? 

Note that I don't really want to move away from the line, I just want to dismiss the window so that I can see the surrounding code and fix that line

Here's just one example from a small JS file but I've encountered it in Rust too

![image](https://user-images.githubusercontent.com/6406986/83348223-35d48080-a333-11ea-8198-4a13e258b1a5.png)

**Comment by chemzqm** [comment]
Read doc of coc-tsserver

**Comment by dakom** [comment]
This isn't ts-specific... see here with Rust:

![image](https://user-images.githubusercontent.com/6406986/83424509-29d0e780-a435-11ea-8e5c-6bbb22bd532b.png)

**Comment by chemzqm** [comment]
We don't provide configuration for ignore specific error/warning, since it should be done by configuration of the language server, you can hack the code if you want to.
