### ISSUE TITLE
Python can't import modules

### ISSUE THREAD

**Issue by Cvar1984** [neoclide/coc.nvim#2008]
## Result from CocInfo
`
3 vim version: NVIM v0.4.3                                                              4 node version: v14.2.0                                                                 5 coc.nvim version: 0.0.78-95e7ca8324                                                   6 coc.nivm directory: /storage/0403-0201/Android/data/com.termux/files/nvim/plugged/    7 term: xterm-256color                                                                  8 platform: android                                                                     9                                                                                      10 ## Output channel: snippets                                                          11                                                                                      12 [Info 9:10:55 PM] Using ultisnips directories: UltiSnips /data/data/com.termux/fil   13 [Info 9:10:55 PM] Using ultisnips python command: pyx                                14 Error on execute python script:
   15 request error nvim_command - Vim(return):Error invoking 'python_execute_file' on c   16 Traceback (most recent call last):
   17   File "/data/data/com.termux/files/usr/tmp/coc.nvim-23490/coc-ultisnips-0glNV1JBq
   18     from vimsnippets import complete, has_cjk, display_width                         19 ImportError: cannot import name 'has_cjk' from 'vimsnippets' (/data/data/com.termu   20
`

## Describe the bug

When im tring to install vim gitignore this happen `cannot import name 'has_cjk' from 'vimsnippets'`

```
Package: neovim
Version: 0.4.3

Name: pynvim
Version: 0.4.1

neovim@4.9.0 | MIT | deps: 5 | versions: 33
Neovim client API and neovim remote plugin provider
https://github.com/neovim/node-client
```

**Comment by chemzqm** [comment]
It's not issue of coc.nvim
