### ISSUE TITLE
[coc.nvim] javascript file not found, use "yarn install --frozen-lockfile" to compile

### ISSUE THREAD

**Issue by dr3cod3** [neoclide/coc.nvim#2011]
yarn: error: no such option: --frozen-lockfile
I have yarn installed, I even ran the curl install script and have followed the previous thread still getting the error when on vim and neovim. The "yarn install --frozen-lockfile"  resulting to the  first line above.Running yarn version 1.224. OS is Linux Ubuntu 20.4  and Mint 19.4

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 0xCAP** [comment]
Having the same issue here on KDE neon 5.19, NVIM v0.2.2

**Comment by chemzqm** [comment]
NVIM v0.2.2 is not supported

**Comment by amincoding** [comment]
yeah same problem here as well in kali linux . was using ycm but i found it hard to configure and doesnt really autocomplete for most cases . so i thought it would be great to switch to coc but nah . i am facing thins error now

**Comment by phonzia** [comment]
have the same issue on ubuntu 20.04

**Comment by kelnos** [comment]
I just started getting this on Debian bullseye, nvim 0.4.4.

It looks like `yarn` on Debian is not the yarn coc.nvim is expecting; it's a part of the `cmdtest` package, "blackbox testing of Unix command line programs".

Not sure what to do here; it's pretty annoying that every time I run vim, I get two extra vertical split windows that take up most of the editor printing out this error.

**Comment by jfredett** [comment]
Here's how you fix it (on Debian-alikes, at least, I had this problem on my Kali box, but I suspect it'll work for most debians)

1. `apt remove cmdtest` -- remove the thing that gets install when you `apt install yarn`
2. `apt install yarnpkg` -- this is the _correct_ yarn for coc.vim.
3. `ln -s /usr/bin/yarnpkg /somewhere/on/your/path/yarn` -- this makes it so you can call `yarn` as nvim expects.

HTH
