### ISSUE TITLE
Why is set hidden required?

### ISSUE THREAD

**Issue by nhooyr** [neoclide/coc.nvim#2014]
What does the README mean when it says

> " TextEdit might fail if hidden is not set.

https://github.com/neoclide/coc.nvim#example-vim-configuration

What's `TextEdit` supposed to refer to? I couldn't find anything in the docs.

**Comment by chemzqm** [comment]
It's interface from lsp

**Comment by nhooyr** [comment]
> It's interface from lsp

Ah I see. What exactly does it do? And why would it fail if `set hidden` is not set?

**Comment by chemzqm** [comment]
Read vim's help

**Comment by nhooyr** [comment]
I've checked. There is no mention of `hidden` or `textedit` in `coc.txt`.

**Comment by chemzqm** [comment]
We have to load buffer to make change to buffer, but it's abandoned on hide how could we change it?

**Comment by nhooyr** [comment]
Ohhh I see. So if I accept a completion but then hide the buffer before the edit is applied, it will fail without `set hidden`?

If so, I'm not sure if it should be recommended as the default as I think that's expected behaviour if I unload the buffer.

**Comment by chemzqm** [comment]
We need load the buffer, then hide it and apply workspace edit for it, it's not required if we can use bufload api, you can not use set hidden but don't create issue when you have trouble with that

**Comment by nhooyr** [comment]
Makes sense, thank you for explaining!
