### ISSUE TITLE
Simple adjustment to PureScript language server example configuration

### ISSUE THREAD

**Issue by k-onrad** [neoclide/coc.nvim#2016]
**Is your feature request related to a problem? Please describe.**
Spent an hour or so trying to make the PureScript language server work correctly with coc, eventually [found out in their git repo](https://github.com/nwolverson/purescript-language-server/issues/38#issuecomment-406528193) that the language server may require a `--config {}` argument to be passed so it can work correctly (`{}` being any valid configuration object, per their docs).

**Describe the solution you'd like**
Just adding `--config {}` to the example configuration should save people some minutes, in case they bump into this.

**Describe alternatives you've considered**
I guess even if the configuration example stays the same, at least a comment on the possibility of needing that arg could help.

**Additional context**
Never submitted an issue here before, so I'll take the opportunity to thank the contributors for this awesome plugin 👍

**Comment by oblitum** [comment]
The wiki is editable. Just edit it.
