### ISSUE TITLE
Vim function to see if Coc extension is installed or not

### ISSUE THREAD

**Issue by antoinemadec** [neoclide/coc.nvim#2017]
**Is your feature request related to a problem? Please describe.**
It is hard for vim plugins to know which Coc extension is installed

**Describe the solution you'd like**
```CocHasExtension('coc-yank')``` would return true if coc-yank is installed, false otherwise.

**Describe alternatives you've considered**
Parsing ```CocAction('extensionStats')```, this is doable but not very user friendly.

Thanks,
Antoine

**Comment by chemzqm** [comment]
You can create vim function yourself, I don't feel like unnecessary public API.

**Comment by antoinemadec** [comment]
@chemzqm, got it. Thanks :grinning:

**Comment by antoinemadec** [comment]
As a reference, if someone else is looking for the same feature:
```vim
function coc_has_extension(ext) abort
  return len(filter(CocAction('extensionStats'), {key, val -> val.id == a:ext}))
endfunction
```
