### ISSUE TITLE
:CocList outline should obey useQuickfixForLocations

### ISSUE THREAD

**Issue by nhooyr** [neoclide/coc.nvim#2018]
I'd prefer the outline to go into the quick fix list so I can easily navigate through it and understand the structure of the file.

As of now, it still uses denite even if you have `coc.preferences.useQuickfixForLocations` set.

Some background re use of quickfix at https://github.com/neoclide/coc.nvim/issues/480

**Comment by chemzqm** [comment]
No, create quickfix list yourself instead.

**Comment by nhooyr** [comment]
But the outline is a list of jump locations?

**Comment by nhooyr** [comment]
Ah it's fairly easy to use quick fix myself.

For anyone in the future, https://github.com/neoclide/coc-denite/blob/master/rplugin/python3/denite/source/symbols.py is a good reference for how it's done for `denite`.

**Comment by drbeco** [comment]
I'm having a hard time figuring this out. 

Related issue: https://github.com/neoclide/coc.nvim/issues/4891

Would you be kind to expand on how to make COC use quickfix?
