### ISSUE TITLE
Disable certain sources on filetype or buffer level

### ISSUE THREAD

**Issue by kristijanhusak** [neoclide/coc.nvim#2019]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this is already possible. I know i can do `b:coc_enabled = 0`, but i don't want to disable whole thing. 
For example, I'm using `coc-tag` by default almost everywhere. Only place where i don't need it is when writing sql. For that filetype I would like to disable it.

**Describe the solution you'd like**
I would like to have an option either to blacklist or whitelist sources on buffer level. For example, in my case, something like this:
```vimL
" blacklist
let b:coc_disabled_sources = ['coc-tag']

" or whitelist
let b:coc_enabled_sources = ['coc-db']
```

**Describe alternatives you've considered**
I guess alternative would be to add a whitelist of all filetypes that I use for the coc-tag configuration (`coc.source.tag.filetypes`), but that list can be pretty big.

**Additional context**
I can try to do this myself if you agree with something like this, or you want some other solution that would make this work.

**Comment by chemzqm** [comment]
If you use tag completion a lot, use vim's builtin completion for tag would be better option, we only have whilelist for now

**Comment by chemzqm** [comment]
No such support, it should not be hard to support b:coc_disabled_sources

**Comment by kristijanhusak** [comment]
Yeah i think having coc_disabled_sources is better than coc_enabled_sources. Whitelist can be easily achieved with the current functionality.

Should I leave it to you or should I try it?

**Comment by chemzqm** [comment]
I prefer you try it out

**Comment by chemzqm** [comment]
I've added support for `g:coc_sources_disable_map` fd6f1a5e.

**Comment by z0xyz** [comment]
@chemzqm Is this variable still viable? It doesn't seem to be anywhere at the docs, whether that the `coc-variables` or `cco-nvim.txt`. It also seems to be ineffective whether set or not

**Comment by chemzqm** [comment]
It's removed, use b:coc_disabled_sources instead

**Comment by z0xyz** [comment]
It's rather quirky for me i.e. let's say for any buffer of filetype `text`, i set the variable set in this way `let b:coc_disabled_sources = ['around', 'buffer' , 'file']`.  When i open a text file, and input a `/` forward slash character, it still shows path completions, but it only allows tabbing, but no substring matching of the completions available . Same behavior applies for every other disabled source. They show up when their trigger character is inputted, but they only allow tabbing .

**Comment by z0xyz** [comment]
@chemzqm Should i preferably open an issue instead ?

**Comment by chemzqm** [comment]
Yes, reproduced the bug.
