### ISSUE TITLE
Presence of popup prevents signatureHelp from working correctly

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#202]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

## versions

vim version: NVIM v0.3.1
node version: v11.2.0
coc.nvim version: 0.0.35
term: tmux-256color
platform: linux

## Output channel: prettier

**Describe the bug**

`signatureHelp` is almost working, I can use it in Python much more effectively than in C/C++/Go though. The reason is that in those languages, contrary to Python, the popup menu is much more present, and its presence for some reason cause the `signatureHelp` not to show for additional function arguments after the first one is insert, sometimes even help for the first is not shown.

**To Reproduce**

It suffices to try signature help for the second argument at the following code, it's very difficult to make it work:

```cpp
int foo(int x, int y);

int main() {
    foo(1,
}
```

When `,` is typed, the popup menu is already open (with many not  very useful suggestions). There's no signature help for second argument.

But there's a way to hide the menu before typing `,`:

```cpp
foo(1.,
```

`1.` creates a double, and it's pretty valid syntax, on typing `.` we cause the popup to go away, then when `,` is typed, the second argument is correctly highlighted in `signatureHelp` output.

**Screenshots**

![signaturehelp](https://user-images.githubusercontent.com/1269815/49128131-35c47200-f2b1-11e8-8f5c-3f645d155b91.gif)

**Comment by oblitum** [comment]
```jsonc
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "objc", "objcpp"],
      "initializationOptions": {
        "cacheDirectory": "/tmp/ccls"
      }
    }
```

**Comment by oblitum** [comment]
I've also set `set shortmess+=c` to remove `match 1 of N` message.

**Comment by chemzqm** [comment]
Some language could be slow for TextChange, I've added timeout to fix this.

**Comment by oblitum** [comment]
Much better now :) I thought it had no relation to speed because even if I typed slowly, I was getting signature only after `1.,`, but never after `1,`, despite typing slowly in both cases.

**Comment by oblitum** [comment]
But anyways, looks like it's fixed.
