### ISSUE TITLE
`*` doesn't trigger completion window

### ISSUE THREAD

**Issue by Melkster** [neoclide/coc.nvim#2021]
## Result from CocInfo

```

## versions

vim version: NVIM v0.4.3
node version: v14.2.0
coc.nvim version: 0.0.78-e8e583c8e0
term: xterm-256color
platform: linux

## Messages

## Output channel: snippets

[Info 20:35:17] Using ultisnips directories: UltiSnips /home/melker/.config/coc/ultisnips
[Info 20:35:17] Using ultisnips python command: pyx

## Output channel: prettier


## Output channel: explorer

```

## Describe the bug

Completion window doesn't show up after I type `*`, which is bound to a snippet in Markdown files. However, if I trigger `coc#refresh()` the completion window shows and displays the available snippet up as expected.

It does for instance work with the charater `_`, i.e. the completion window shows up after pressing it.

My `:CocConfig` file is empty.

## Reproduce the bug

- Create file `mini.vim` with

  ```vim
  set rtp+=~/.vim/bundle/Vundle.vim
  call vundle#begin()
  Plugin 'VundleVim/Vundle.vim'
  Plugin 'neoclide/coc.nvim'
  Plugin 'honza/vim-snippets'
  call vundle#end()
  inoremap <silent><expr> <c-space> coc#refresh()
  ```

- Start (neo)vim with command: `vim -u mini.vim testfile.md`

- Enter insert mode

- Type `*`

- No completion window pops up (which it should)

- Press `<c-space>`

- The completion window should show up and show the `*` snippet

**Comment by chemzqm** [comment]
It's expected, since `*` is not trigger character and keyword

**Comment by Melkster** [comment]
@chemzqm Ok, so there's no way for me to make `*` a trigger character?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-snippets/blob/master/Readme.md#options
