### ISSUE TITLE
:CocOpenLog doesn't work in Windows gVim

### ISSUE THREAD

**Issue by yous** [neoclide/coc.nvim#2022]
## Result from CocInfo

```
## versions

vim version: VIM - Vi iMproved 8.2 8020801
node version: v12.17.0
coc.nvim version: 0.0.78-4d98f9059c
coc.nvim directory: C:\Users\Yous\vimfiles\plugged\coc.nvim
term: undefined
platform: win32
```

## Describe the bug

`:CocOpenLog` fails to open the log even if the file exists.

```
Failed to open C:\Users\Yous\AppData\Local\Temp\coc.nvim-11692\coc-nvim.log
```

## Reproduce the bug

gVim is installed via [gvim_8.2.0801_x64_signed.exe](https://github.com/vim/vim-win32-installer/releases/download/v8.2.0801/gvim_8.2.0801_x64_signed.exe) of [vim-win32-installer](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.0801).

- Create file `mini.vim` with:

  ```vim
  set nocompatible
  filetype off
  call plug#begin()
  Plug 'neoclide/coc.nvim', { 'branch': 'release' }
  call plug#end()
  ```
- Start gVim with command: `"C:\Program Files (x86)\Vim\vim82\gvim.exe" -u mini.vim`
- Run `:CocOpenLog`

**Comment by yous** [comment]
It seems that following line fails:
https://github.com/neoclide/coc.nvim/blob/a423c49f2b5d319e4001888c69733ca11ba3f6d8/autoload/coc/util.vim#L895

Running `cmd /c start "" /b C:\Users\Yous\AppData\Local\Temp\coc.nvim-11692\coc-nvim.log` gives me the following error:
```
The process cannot access the file because it is being used by another process.
```

**Comment by chemzqm** [comment]
Run `:call coc#rpc#stop()` to stop the node process.

**Comment by yous** [comment]
FWIW, I think `:CocOpenLog` would be okay if it lets Vim open the log file directly, instead of running OS-dependent commands. That will be useful for servers without GUI.

**Comment by yous** [comment]
`:CocLocalConfig` also doesn't work on gVim 8.2.0931 with coc.nvim 21e23d770848fe9bf4bdad1a1888ab61cfcc63f3. I got the following error message:
```
[coc.nvim] Can't create local config in home directory
```
It seems that this comes from here: https://github.com/neoclide/coc.nvim/blob/2984f288554ce1713d63465da0201bc22436e9fd/src/workspace.ts#L316-L321

But these are results from commands in gVim:

| Command | Result |
|-|-|
| `:pwd` | `C:\Users\Yous` |
| `:!node.exe -e "const process = require('process'); console.log(process.cwd())"` | `C:\Users\Yous` |
| `:!node.exe -e "const os = require('os'); console.log(os.homedir())"` | `C:\Users\Yous` |

**Comment by chemzqm** [comment]
`CocLocalConfig` won't work inside user's home, you have to use `:CocConfig` for user configuration.

**Comment by yous** [comment]
Ah, that was obvious. My mistake, sorry for the noise.

**Comment by yous** [comment]
By the way, is this issue still not reproducible? Maybe I can do some experiments for debugging.

**Comment by Alex-duzhichao** [comment]
@chemzqm I encounter this problem `Failed to open C:\Users\my\AppData\Local\Temp\coc.nvim-7896\coc-nvim.log` on my windows10 pc too. The reason is that coc node process is using this log file, so windows would produce  `The process cannot access the file because it is being used by another process.` error.
I agree @yous 's point: 

> :CocOpenLog would be okay if it lets Vim open the log file directly, instead of running OS-dependent commands. That will be useful for servers without GUI.

So can you fix this problem? thank you very much.

**Comment by fannheyward** [comment]
Fixed by https://github.com/neoclide/coc.nvim/commit/527bf5e9f5d8e20c101db39a8803226ef64aa643 , CocOpenLog will copy log file path to your clipboard.
