### ISSUE TITLE
hover doesn't work properly

### ISSUE THREAD

**Issue by CODESOLE** [neoclide/coc.nvim#2024]
when i press shift + k at first it works but after second, third, .... and so on it doesn't show proper string. 

**System information**
Output of `clangd --version`:  clangd version 10.0.0-4ubuntu1 
Editor/LSP plugin: vim coc-clangd
Operating system: kubuntu 20.04
![issue](https://user-images.githubusercontent.com/22984206/83554454-74c22c00-a515-11ea-9f9c-d02821bf8828.gif)

**Comment by CODESOLE** [comment]
here is CocInfo:
## versions

vim version: VIM - Vi IMproved 8.1 8012269
node version: v10.19.0
coc.nvim version: 0.0.78-fd9e7d3972
term: dumb
platform: linux

## Output channel: snippets

[Info 2:37:03 PM] Using ultisnips directories: UltiSnips /home/caner/.config/coc/ultisnips
[Info 2:37:03 PM] Using ultisnips python command: pyx

## Output channel: explorer


## Output channel: clangd log

I[14:37:03.786] clangd version 10.0.0-4ubuntu1 
I[14:37:03.786] PID: 8681
I[14:37:03.786] Working directory: /home/caner/C++/GL/src
I[14:37:03.786] argv[0]: /usr/bin/clangd
I[14:37:03.786] Starting LSP over stdin/stdout
I[14:37:03.787] <-- initialize(0)
I[14:37:03.787] --> reply:initialize(0) 0 ms
I[14:37:03.796] <-- initialized
I[14:37:03.796] unhandled notification initialized
I[14:37:03.797] <-- textDocument/didOpen
I[14:37:03.798] Failed to find compilation database for /home/caner/C++/GL/src/Particle.cpp
I[14:37:03.798] --> textDocument/clangd.fileStatus
I[14:37:03.798] Updating file /home/caner/C++/GL/src/Particle.cpp with command clangd fallback
[/home/caner/C++/GL/src]
/usr/lib/llvm-10/bin/clang /home/caner/C++/GL/src/Particle.cpp -fsyntax-only -resource-dir=/usr/lib/llvm-10/lib/clang/10.0.0
I[14:37:05.727] --> textDocument/publishDiagnostics
I[14:37:05.727] --> textDocument/semanticHighlighting
I[14:37:05.728] --> textDocument/clangd.fileStatus

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chrisshangguan** [comment]
how do you solve this problems?

**Comment by chemzqm** [comment]
Could be bug of vim, but I can't reproduce.

**Comment by CODESOLE** [comment]
I solve this after i open this issue, just update the coc and extensions it's working for me right now as usual.

**Comment by sergei-grigorev** [comment]
This bug is still reproducible in my environment multiple times a day and works fine after restart for some period till I see that again. I don't know what exact steps are need it to be. My environment:
- VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 14 2021 23:04:22)
- macOS version - x86_64
- iterm

I compared it inside tmux, tmux pane and without tux. Result is the same, maybe in tmux pane it appears a little bit earlier.

**Comment by jackkinsella** [comment]
When this happened to me, I ran `:CocUpdate` and it worked again.

**Comment by ytian81** [comment]
> This bug is still reproducible in my environment multiple times a day and works fine after restart for some period till I see that again. I don't know what exact steps are need it to be. My environment:
> 
> * VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 14 2021 23:04:22)
> * macOS version - x86_64
> * iterm
> 
> I compared it inside tmux, tmux pane and without tux. Result is the same, maybe in tmux pane it appears a little bit earlier.

Also reproducible in my environment 
* Neovim 
```
NVIM v0.5.0-dev+1152-gf5daf55c1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az204-819

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```
* OS: OS: Ubuntu 18.04.5 LTS x86_64

**Comment by ytian81** [comment]
trying a minimal vimdc setup and find that hover works fine for a single cpp file all the time but it failed and throw `hover not found` when I am working in some large cpp codebase.

**Comment by CODESOLE** [comment]
> After trying a minimal vimdc setup and find that hover works fine for a single cpp file all the time but it failed and throw `hover not found` when I am working in some large cpp codebase.

Did you place compile_commands.json into root of the project ? Language Server understand the whole project with that file.
Here is good doc:
https://sarcasm.github.io/notes/dev/compilation-database.html

**Comment by ytian81** [comment]
I am having a soft link in root dir to the compilation data base. and I can read from coc clangd output that coc sourced my compilation database file. I am getting no issue with `doHover` or `goToDefintion` after I restart coc but after a few mins, they both don't work and I have to restart coc again.

**Comment by kingluddite** [comment]
I used this and it got rid of the error
"coc.preferences.messageLevel": "error" to avoid warning message.
