### ISSUE TITLE
Be able to set Workspace provider(s) for a folder/all buffer types.

### ISSUE THREAD

**Issue by ashb** [neoclide/coc.nvim#2026]
**Is your feature request related to a problem? Please describe.**

I often start up `nvim` in my project folder, and want ` s` (bound to `CocList -I symbols`) to work.

The problem is because the current (empty) buffer has no filetype, I get an error saying

```
[coc.nvim] Error on "CocList symbols": Workspace symbols provider not found for current document
```

**Describe the solution you'd like**

I imagine some setting in `.vim/coc-settings.json` that would let me list which providers/language servers I want to always be active in this project

**Comment by chemzqm** [comment]
Not possible

**Comment by ashb** [comment]
Not possible right now, or _never_ possible?

**Comment by ashb** [comment]
> Many coc.nvim extensions are dynamic loaded, so you can't expect they can work when you just start vim by empty buffer.

That is exactly why I said "let me list which providers/language servers I want to always be active in this project"

**Comment by chemzqm** [comment]
We don't have such kind of support for now.

**Comment by ashb** [comment]
Yes, I know that. This is a request for a new feature :grin:

**Comment by chemzqm** [comment]
You can use CocAction to activated extensions
