### ISSUE TITLE
"diagnostic.messageTarget": "echo" always prints "..." at the end of the line

### ISSUE THREAD

**Issue by karb94** [neoclide/coc.nvim#2027]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v14.3.0
coc.nvim version: 0.0.78-4aaf5bf73c
coc.nivm directory: /home/carles/.config/nvim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Output channel: clangd log


## Output channel: Python

Starting Microsoft Python language server.
##########Linting Output - pylint##########
************* Module plot_maker
6,0,error,E0402:Attempted relative import beyond top-level package (relative-beyond-top-level)
7,0,error,E0402:Attempted relative import beyond top-level package (relative-beyond-top-level)

-------------------------------------------------------------------
Your code has been rated at 8.33/10 (previous run: 10.00/10, -1.67)
```
## Describe the bug
Diagnostic message always prints three dots (`...`) at the end of the command line even if the message is not truncated. The three dots go away if `<Plug>(coc-diagnostic-info)` is used.

Is this expected behaviour? If so, is there any way to use `<Plug>(coc-diagnostic-info)` instead of echo automatically?

## Reproduce the bug

- Create file `mini.vim` with:

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```
- Create file `coc-settings.json` with:
`{"diagnostic.messageTarget": "echo"}`

- Start (neo)vim with command: `nvim -u mini.vim`

- Place cursor on top of diagnostic.

## Screenshots
![sc](https://user-images.githubusercontent.com/41967813/83656325-4c8b0980-a5b7-11ea-8820-ddc27383eb13.png)

**Comment by chemzqm** [comment]
You have to change cmdheight option or use float window for better experience
