### ISSUE TITLE
Suggestions and completion won't show up

### ISSUE THREAD

**Issue by wardinh0** [neoclide/coc.nvim#2029]
## Result from CocInfo

versions

vim version: NVIM v0.5.0-542-g96568d5b0
node version: v14.4.0
coc.nvim version: 0.0.78-d5471449bf
coc.nivm directory: C:\Users\Eduardo\.nvim\plugged\coc.nvim
term: cygwin
platform: win32

Output channel: snippets

[Info 8:47:33 PM] Using ultisnips directories: UltiSnips C:\Users\\[myuser]\AppData\Local\coc\ultisnips
[Info 8:47:33 PM] Using ultisnips python command: pyx

## Describe the bug

Suggestions and completion not working, they won't show up.

## Reproduce the bug

I start Neovim with the mini.vim, I create a main.c file, save it, and start to type C code. Nothing happens, no suggestions, no completion. I tried other languages as well, tried HTML, CSS, nothing.

## Screenshots (optional)

[Screenshot](https://i.imgur.com/f8Wy2iX.png)

**Comment by fannheyward** [comment]
You need to set completion sources for your work, for example `coc-html` for HTML, `coc-css` for CSS, and C language server, ccls or clangd, for C.

https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources
https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions
