### ISSUE TITLE
Request for comment/help for source for wiki.vim

### ISSUE THREAD

**Issue by lervag** [neoclide/coc.nvim#2032]
I've written a custom source for [wiki.vim](https://github.com/lervag/wiki.vim/) that I currently only have for personal use. I am considering to publish it (either separately or as part of the main plugin). I was wondering if someone could help with a couple of things:

1. Recently, my source has stopped working. The code is attached below. I've added it through the mechanism explained in [this blog post](https://medium.com/@chemzqm/create-coc-nvim-extension-to-improve-vim-experience-4461df269173). The idea is to invoke the omnicomplete function of `wiki.vim` for wiki links `[[LinkHere#possibly#anchored]]` and for one particular type of reference link `@citekey` and `zot:citekey`. This worked well perhaps one month ago. If anyone would be able to recognize recent changes that affects this type of extension or otherwise bugs in my code that would help me fix the source, then I would be very happy!

2. If I want to convert this source to a full extension, how would I proceed?

Here's the custom source:

```javascript
const { sources, workspace, SourceType } = require('coc.nvim')

exports.activate = async context => {
  context.subscriptions.push(
    sources.createSource({
      name: 'wiki',
      filetypes: ['wiki'],
      priority: 100,
      triggerPatterns: [
        /\[\[[^\]\|]{2,}$/,
        /(zot:|@)\w+$/
      ],
      doComplete: async opt => {
        let { nvim } = workspace
        let { line, colnr, col } = opt
        try {
          startcol = await nvim.call('wiki#complete#omnicomplete', [1, ''])
          startcol = Number(startcol)
        } catch (e) {
          workspace.showMessage(`Error from wiki#complete#omnicomplete: ${e.message}`, 'error')
          return null
        }

        // invalid startcol
        if (isNaN(startcol) || startcol < 0 || startcol > colnr) return null

        return {
          startcol: startcol,
          items: await nvim.call('wiki#complete#omnicomplete',
            [0, byteSlice(line, startcol, colnr - 1)])
        }
      }
    })
  )
}

byteSlice = function (content, start, end) {
  let buf = Buffer.from(content, 'utf8')
  return buf.slice(start, end).toString('utf8')
}
```

**Comment by fannheyward** [comment]
1. is there any error message when this source stops work?
2. try https://github.com/fannheyward/create-coc-extension

**Comment by lervag** [comment]
>     1. is there any error message when this source stops work?

No, there are no error messages. However, I've just noticed that the completion works in the single case when `#` is inserted. That is, if I type `[[SomePage#]]` then the completion is shown when `#` is typed. But I expect it to also show completion candidates when I type `[[Som` (e.g. to complete `[[SomePage`). Note, the omnicomplete function does work as expected (i.e., `<c-x><c-o>` works).

Further suggestions for how to debug this is also very much appreciated.

>     2. try https://github.com/fannheyward/create-coc-extension

Thanks, I'll look into that! I'm not very familiar with javascript/typescript, so do you have any suggestions on how to convert the single-file source into the more full multi-file project?

**Comment by fannheyward** [comment]
> how to convert the single-file source into the more full multi-file project?

Move your current `exports.activate` function body to https://github.com/fannheyward/create-coc-extension/blob/master/template/src/index.ts#L4, that's all.

**Comment by fannheyward** [comment]
> expect it to also show completion candidates when I type [[Som

Maybe the `triggerPatterns` regex issue?

**Comment by lervag** [comment]
> Move your current `exports.activate` function body to https://github.com/fannheyward/create-coc-extension/blob/master/template/src/index.ts#L4, that's all.

Thanks!

> Maybe the `triggerPatterns` regex issue?

Are you referring to a particular issue, or are you saying there might be an issue with my `triggerPatterns`?

If you mean the former, then I don't know which issue you are referring to. If you mean the latter, then note that this worked perfectly some weeks ago and I did not change anything since then myself.

**Comment by lervag** [comment]
Are there some convenient ways to add some debug statements/output within the `doComplete` function? E.g., it could be interesting to check if the function is actually run or not.

**Comment by fannheyward** [comment]
`export NVIM_COC_LOG_LEVEL=debug && export NVIM_COC_LOG_FILE=/tmp/coc.log`, this will redirect coc log to /tmp/coc.log.

You can use `console.error` in doComplete to check your function works or not.

**Comment by lervag** [comment]
Ok, thanks! With this, I see that the wiki source is not triggered until the `#` character is typed. Do you know any way to debug the `triggerPatterns`?

**Comment by lervag** [comment]
I'm curious: Are there important benefits in defining the source in javascript as opposed to vimscript (e.g. as proposed [here](https://github.com/neoclide/coc.nvim/wiki/Create-custom-source))?

**Comment by chemzqm** [comment]
> I'm curious: Are there important benefits in defining the source in javascript as opposed to vimscript (e.g. as proposed [here](https://github.com/neoclide/coc.nvim/wiki/Create-custom-source))?

I don't think there is except that you can use javascript api.

To make coc.nvim extenison, make sure your have `main` point to your javascript entry file and add `coc.nvim` to `engines` field.

**Comment by chemzqm** [comment]
The vim function could block your vim and `triggerPatterns` would make coc.nvim trigger completion from time to time.

**Comment by lervag** [comment]
> > I'm curious: Are there important benefits in defining the source in javascript as opposed to vimscript (e.g. as proposed [here](https://github.com/neoclide/coc.nvim/wiki/Create-custom-source))?
> 
> I don't think there is except that you can use javascript api.

Ah, nice. That means I can safely write my source in vimscript in which I am much more familiar.

Is there a vimscript api for coc.nvim similar to the javascript api? If so, is it documented anywhere?

> To make coc.nvim extenison, make sure your have `main` point to your javascript entry file and add `coc.nvim` to `engines` field.

Thanks!

> The vim function could block your vim and `triggerPatterns` would make coc.nvim trigger completion from time to time.

I don't quite understand. As mentioned, this source worked as expected before, but does not work as expected any longer. Do you see any errors in my source (defined in the original post)?
