### ISSUE TITLE
Jump to definition and only open a new buffer the first time

### ISSUE THREAD

**Issue by NGPONG** [neoclide/coc.nvim#2035]
**Is your feature request related to a problem? Please describe.**
Hello everyone, I'm using **nnoremap <silent> gd <Plug>(coc-definition)** to jump to definition when navigating c++ files. The question is how do I jump to the definition and only open the new buffer for the first time, and then use the first opened buffer(by jump definition) to perform subsequent jump definition operations

**Why do I have this querstion**
When a file has too many downward dependencies, I find that a lot of buffers are opened every time a jump is defined

**Additional context**
I'm totally new to vim and any help is appreciated.

ps: just like vscode

**Comment by chemzqm** [comment]
You can't reuse loaded buffer, you can use vim's api to delete hidden buffers

**Comment by chemzqm** [comment]
It's problem of how you use vim, we won't provide such feature
