### ISSUE TITLE
Multiselect in CocList using keyboard

### ISSUE THREAD

**Issue by ravisumit33** [neoclide/coc.nvim#2038]
Suppose I open CocList outline. It starts in fuzzy mode. I typed few letters and I can see some results of my interest. I want to select all of them and open using my keyboard(not mouse). 

I see, in wiki, it says to go to normal mode and do select in visual mode. But pressing Esc closes the list. I can't figure out how to go to normal mode and do multiselect with keyboard.

**Comment by fannheyward** [comment]
`C-o` switch to normal mode.
