### ISSUE TITLE
CocList grep doesn't highlight word in preview

### ISSUE THREAD

**Issue by ravisumit33** [neoclide/coc.nvim#2039]
As the heading suggest, in preview window grepped word is not highlighted. Other methods, such as CocList words properly highlight. Is this a bug or expected behaviour?

**Comment by fannheyward** [comment]
`:CocList grep coc` does highlighting.

**Comment by ravisumit33** [comment]
I was talking about highlighting in preview window not in list window. I still can't words getting highlighted when I do :CocList grep.
:CocList words is fine

**Comment by ravisumit33** [comment]
Apart from the preview window, list window also shows different behaviours.

If i use any colorscheme(i am using _gruvbox_ but tried several others also) list window is also not getting highlighted.

<img width="1792" alt="Screenshot 2020-06-08 at 4 37 31 PM" src="https://user-images.githubusercontent.com/19284116/84023996-b71cba80-a9a6-11ea-9f72-d65288bdd613.png">

But if i use any default neovim colorschemes (e.g. _desert_) list window is nicely highlighted.

<img width="1792" alt="Screenshot 2020-06-08 at 4 38 02 PM" src="https://user-images.githubusercontent.com/19284116/84024518-a751a600-a9a7-11ea-8029-6fd07ffd5027.png">

**Comment by chemzqm** [comment]
No such support, don't have time to, consider help by send PR if you need it.

**Comment by ravisumit33** [comment]
What about [highlighting](https://github.com/neoclide/coc.nvim/issues/2039#issuecomment-640419821) in preview window during CocList grep ?  It should be there as other searches like CocList words have it.

**Comment by chemzqm** [comment]
It's much more complicated for grep, I don't have time for it.
