### ISSUE TITLE
show_documentation() works on file from disk instead of buffer

### ISSUE THREAD

**Issue by ecly** [neoclide/coc.nvim#2041]
## Result from CocInfo
```sh
## versions

vim version: NVIM v0.4.3
node version: v14.3.0
coc.nvim version: 0.0.78-d5471449bf
coc.nivm directory: /home/ecly/.vim/plugged/coc.nvim
term: tmux-256color
platform: linux

## Output channel: snippets

[Info 5:30:32 PM] Using ultisnips directories: UltiSnips /home/ecly/.config/coc/ultisnips
[Info 5:30:32 PM] Using ultisnips python command: pyx
```

## Describe the bug
Using the sample configuration provided in README.md, specifically the `show_documentation` function defined works on the files on disk, rather than the buffer itself, which causes it to either show no documentation or wrong documentation for files that have been changed without being written to disk. I'm sorry if this is expected/intentional and I just wasn't aware of this.

## Reproduce the bug
I use vim-plug for simplicity, so as an optional step, download and install vim-plug using:
```sh
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```
Create a minimal 'test.vim' file with below contents (I create one intended for Python for my example):
  ```vim
let g:coc_global_extensions = ['coc-python']
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}"
call plug#end()

set nocompatible
filetype plugin indent on
syntax on
set hidden

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

nmap <silent>K :call <SID>show_documentation()<CR>

  ```

- Open a Python file with neovim with command: `nvim -u test.vim test.py`
Write a line like below, save the file and use `K` while cursor is hovering `repeat` - observe expected behavior.
```python
from itertools import repeat
```
Now add a line above our previous line, **do not save the file**, and press `K` while cursor is hovering `repeat` once more. This time, it will not work.
```python
import sys
from itertools import repeat
```

**Comment by chemzqm** [comment]
Please read readme of coc-python, it mentioned you have to save the buffer for the language server to work, it's problem of language server.

**Comment by ecly** [comment]
Thank you @chemzqm - I had missed that. In case anyone fails to read this as well before getting confused, it is mentioned in the FAQ of coc-python README here: https://github.com/neoclide/coc-python/#faq
