### ISSUE TITLE
`/` is not appended when entering directory paths

### ISSUE THREAD

**Issue by tbrodbeck** [neoclide/coc.nvim#2042]
**Is your feature request related to a problem? Please describe.**
When typing directory paths I the `/` after a directory is not appended in the prediction for some reason. Therefore I have to enter a slash after every directory myself when I want to type a directory path with the help of `coc`.

**Describe the solution you'd like**
Appending the `/` at the end of a directory entered would already suffice.

**Additional context**
Example:
I type:
`/` + `U` + `tab` -> /Users
/Users + `/` -> /Users/ (this step could be merged with one the above!)
/Users/  + `tab` -> /Users/username
/Users/  + `/` -> /Users/username/ (here again, etc ..)

**Comment by chemzqm** [comment]
It's expected.

**Comment by iasj** [comment]
@chemzqm, what does that mean? I also want this feature. Can I set it somewhere? How?

**Comment by chemzqm** [comment]
No such support, PR welcome

**Comment by iasj** [comment]
Can you point the files in the code that are responsible for producing the sugestion? Is there a developer guide anywhere?

**Comment by iasj** [comment]
I'm very sad with this unexisting feature. It's even built-in in both Vim and Neovim. I made a gif showing the use of the feature under normal (ctrl-x followed by ctrl-f in insert mode).
 
![complete](https://user-images.githubusercontent.com/7888397/89005624-4ecdc380-d2db-11ea-9fba-904c377b4c52.gif)

is there a coc function that returns wheather or not the completion suggestion is a path. If so, which one?

Any chance to make Coc have the default behaviour for path completion? Is there a particular need for removing this last slash on directory paths?

**Comment by Melkster** [comment]
I also think it's odd that the trailing slash is omitted even though it's displayed in the completion menu.

I think that there should at least be a toggle available for this behaviour in `coc-settings.json`.
