### ISSUE TITLE
Failed to terminate coc.nvim node.js processes after vim exited

### ISSUE THREAD

**Issue by ray-x** [neoclide/coc.nvim#2043]
## Describe the bug

Use neovim in terminal.  Open files,  exit normally (:q! etc).  After a few hours usage, exit all vim application and check the system. There are a few node.js services still running. (e.g. node_modules/coc-vimlsp/out/scan.js)

## Reproduce the bug
Open file, close file, split, navigate.  And exit all vim applications and check the system processes. 
Sometime found language server also not stopped. 

This bug is more a stability issue. Does not reproduce each time. But kind of annoying because you do not know which node.js is a zombie unless you exit all vim applications. And only after that you can kill node.js.

## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v14.3.0
coc.nvim version: 0.0.78
coc.nivm directory: /Users/ray.xu/.vim/plugged/coc.nvim
term: xterm-256color
platform: darwin

## Output channel: explorer


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /Users/ray.xu
fatal: not a git repository (or any of the parent directories): .git

## Output channel: prettier


## Output channel: snippets

[Info 9:36:54 am] Using ultisnips directories: UltiSnips gosnippets/UltiSnips /Users/ray.xu/.config/coc/ultisnips
[Info 9:36:54 am] Using ultisnips python command: pyx

## Output channel: highlight

[Info  - 9:36:54 am] Highlight server running in node v14.3.0


```

## Screenshots (optional)
The screen shot shows that all nvim program stopped, but still multiple node.js servers running. They consume lot of memory.

<img width="1186" alt="Screen Shot 2020-06-08 at 9 35 05 am" src="https://user-images.githubusercontent.com/1681295/83982733-540e3200-a96c-11ea-9544-a2ba0d58c509.png">

<img width="731" alt="Screen Shot 2020-06-08 at 9 43 39 am" src="https://user-images.githubusercontent.com/1681295/83982777-920b5600-a96c-11ea-80cc-0939691ff73e.png">

**Comment by chemzqm** [comment]
Can't reproduce, try use `autocmd VimLeavePre * :call coc#rpc#kill()` in your vimrc.

**Comment by oblitum** [comment]
I've never seen this too.

**Comment by ray-x** [comment]
Hi, Chemzqm, oblitum
Thanks for following up on this issue.
I added VimLeavePre * :call coc#rpc#kill() to init.vim. But after one day. Still saw zombie node.js running.
I agree that coc#rpc#kill() can improve the situation. But did not fix.
Any way to ping server.js to know what is the status?

<img width="776" alt="Screen Shot 2020-06-12 at 2 00 18 pm" src="https://user-images.githubusercontent.com/1681295/84463482-45e64b80-acb5-11ea-8926-ccf7b8a2eca5.png">

It shows that parent process 60050 is terminated (null) 
<img width="562" alt="Screen Shot 2020-06-12 at 2 04 41 pm" src="https://user-images.githubusercontent.com/1681295/84463631-b8572b80-acb5-11ea-8426-d7282906e5e7.png">

**Comment by chemzqm** [comment]
Try
```
autocmd VimLeavePre * if get(g:, 'coc_process_pid', 0) | call system('kill -9 '.g:coc_process_pid) | endif
```
if still can't work, then I don't know how to fix.

**Comment by ray-x** [comment]
Your suggestions reminds me I can do this:

```vim
autocmd VimLeavePre * :call coc#rpc#kill()
autocmd VimLeave * if get(g:, 'coc_process_pid', 0) | call system('kill -9 -'.g:coc_process_pid) | endif
```
I know that coc#rpc#kill is essentially calling `kill -9`. But it is no harm to do it again.  
Works well so far.

**Comment by sisrfeng** [comment]
Is `autocmd VimLeavePre * :call coc#rpc#kill()` the same as 
    `autocmd VimLeavePre * call coc#rpc#kill()` ?

**Comment by sisrfeng** [comment]
Many old processes (started 2 months ago) of bin/node are running on my machine.  Maybe the reason is that I sometimes use `kill -9` on the nvim process (because of some bugs of neovide, especially when I ssh from a win10 machine to a ubuntu machine.)
Is there a method to kill the node processes automatically when using `kill -9` on the nvim process?
