### ISSUE TITLE
Enable virtual text on line hover only does not work -- property not allowed.

### ISSUE THREAD

**Issue by hsheikhali** [neoclide/coc.nvim#2047]
## versions

vim version: NVIM v0.4.3
node version: v12.16.1
coc.nvim version: 0.0.78
term: screen
platform: darwin

## Output channel: snippets

[Info 9:59:22 AM] Using ultisnips directories: UltiSnips /Users/hsheikhali/.config/coc/ultisnips
[Info 9:59:22 AM] Using ultisnips python command: pyx
<img width="1440" alt="Screen Shot 2020-06-08 at 10 05 16 AM" src="https://user-images.githubusercontent.com/35124039/84039658-8ff6c680-a96f-11ea-83f4-ab650c25c62c.png">
<img width="1440" alt="Screen Shot 2020-06-08 at 10 05 00 AM" src="https://user-images.githubusercontent.com/35124039/84039681-98e79800-a96f-11ea-9de9-6fdd3301f4a8.png">

## Describe the bug
Not sure if this is a bug or not but I wanted to enabled virtual text within neovim. I feel sometimes that is nicer than floating buffers so I did exactly that. Now this works however, it displays all errors and warnings within a file regardless if you are hovering over it or not. The documentation shows a property that you can enable if you want to only enable virtual text for that line. But you cant enable that property..
`Property diagnostic.virtualTextCurrentLineOnly is not allowed`

## Reproduce the bug
in your coc-settings.json enabled the following settings:
1.   "diagnostic.virtualText": true,
2.  "diagnostic.virtualTextCurrentLineOnly": true, // this always shows up as property not allowed?
3.  "diagnostic.messageTarget": "echo",

**Comment by oblitum** [comment]
Update your coc.nvim installation, version looks outdated.

**Comment by AnishDe12020** [comment]
It still happens for me and packer says i am on the latest version (commit https://github.com/neoclide/coc.nvim/commit/0ce16402d3d7b245284f07e0d439a7e6e2bb0b28)
