### ISSUE TITLE
Error after manually restarting coc service - CocRestart

### ISSUE THREAD

**Issue by zlianon** [neoclide/coc.nvim#2048]
nvim --version - NVIM v0.3.8
coc.nvim latest source build
node --version - v12.16.3

## Screencast
https://asciinema.org/a/7oSThPnLhSVA3Llu1SyFXrkle

## Screenshots
![2020-06-08-224741_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/84079139-5b6c2480-a9da-11ea-9e62-1633c7d7e48e.png)

**Comment by fannheyward** [comment]
Please upgrade your nvim to 0.4.3, https://github.com/neovim/neovim/pull/9726/commits/cfed9a4123afe3184c3914b6123869f2a52be250#diff-bc068d8c20925a8125453fcbd542b977R483
