### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by samueltwallace** [neoclide/coc.nvim#2049]
## Result from CocInfo

`Error: javascript bundle not found, please compile the code of coc.nvim.`

## Describe the bug

Unable to build. I installed via vim-plug, and let nvim run. I get a terminal window where it tries to build, but it gives me `➤ YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead`. this seems like a yarn/nodejs versioning issue, but according to the README I have the required nodejs (`v10.19.0`) and yarn (`2.0.0-rc.33`). I tried building from source with the yarn 2.0 replacements for it, `--immutable` and `--immutable-cache`. Still get the issue when I open nvim.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.
Done. Screenshot of error below.
## Screenshots (optional)

![image](https://user-images.githubusercontent.com/62719989/84079814-2bf0f400-a9a9-11ea-879f-8236b622ed4a.png)

**Comment by oblitum** [comment]
I think your yarn is too new. IIRC yarn 2 have many differences with version 1.

**Comment by samueltwallace** [comment]
What version(s) works? any 1.x version?

**Comment by oblitum** [comment]
Been using it on yarn 1.x on ArchLinux for a very long time, but I don't build coc.nvim from sources anymore, so it's in use solely for the coc extensions, but last time I tried build was fine.

**Comment by samueltwallace** [comment]
Okay, since this is a yarn issue and not a CoC issue, I'll close.

**Comment by chemzqm** [comment]
Use release branch of coc.nvim is recommended, no need to build.

**Comment by koushikg** [comment]
This still happens if yarn is not installed
