### ISSUE TITLE
Do I need denite for this to work?

### ISSUE THREAD

**Issue by esn89** [neoclide/coc.nvim#205]
Could never manage to get it to work, is denite a dependency?

**Comment by fannheyward** [comment]
No, you do not need denite for completion or lint or goto definition or anything LSP can do.

Denite is only used to manage extensions, symbols location jumping. `:h coc-denite` for more info.

**Comment by esn89** [comment]
Any there any sort of dependencies? 

So far I have added this line to my nvim's init.vim:
```Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}``` since I do not want to build from source.

I included this in my init.vim:

```" use <tab> for trigger completion and navigate next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"
``` and I could not get it to work.

Instead, I get something like this:
https://i.imgur.com/gGmpw5z.png

**Comment by iamcco** [comment]
@esn89 the error seems throw by deoplete instead of coc

**Comment by esn89** [comment]
I see.  Are these two plugins know to work together well, side by side?  Or do I need to get rid of it?

**Comment by iamcco** [comment]
@esn89 just disable deoplete.

**Comment by ayellapragada** [comment]
I had the same issue, I ended up just removing deoplete. 
Either I don't remember what deoplete did, or CoC just takes over the job well enough.

**Comment by chemzqm** [comment]
Denite is used to provide a list view with actions, it's optional.

For coc to work with deoplete, you have options:

* Disable completion trigger of coc by add `  "coc.preferences.autoTrigger": "none",`, and then only use manual trigger by `coc#refresh()`
* Disable completion trigger of deoplete (I don't know how), and use coc for trigger completion

It's obvious that you should not have more than more plugin that does trigger completion for you.

**Comment by chemzqm** [comment]
@esn89 
The problem you have is your keymap is not working as expected, it's mapped to other function, you can use command like `verbose imap <tab>` to check your mapping.

**Comment by esn89** [comment]
Ah, I see.  Let me try this out.  I will report back here

**Comment by esn89** [comment]
Fixed.  I did as you guys told me to and everything works great.  Amazing plugin.  Thanks <3
