### ISSUE TITLE
Support semantic tokens

### ISSUE THREAD

**Issue by heftig** [neoclide/coc.nvim#2053]
It would be nice if CoC would retrieve semantic tokens from the LS in order to enable semantic highlighting. The `rust-analyzer` LS has support for this.

**Comment by oblitum** [comment]
Duplicate of #1671.

https://github.com/neoclide/coc.nvim/issues/1671#issuecomment-616895670

**Comment by oblitum** [comment]
Done. See #2756 and #3048.
