### ISSUE TITLE
Support invoking methods defined in coc extensions from vim plugins using `coc#rpc#notify`

### ISSUE THREAD

**Issue by voldikss** [neoclide/coc.nvim#2054]
**Is your feature request related to a problem? Please describe.**

Sometimes we want to invoke functions defined by coc extension from vim plugins. For example,

coc.nvim can not support `BufWriteCmd` for `events.on`(Actually there are many more autocmds which are not supported). The currently solution is to adding it as coc.nvim has done:
```vim
augroup myau
  autocmd!
  autocmd BufWriteCmd *   call s:Autocmd('BufWriteCmd', +expand('<abuf>'))
augroup END

function! s:Autocmd(...) abort
  if !get(g:,'coc_workspace_initialized', 0)
    return
  endif
  call coc#rpc#notify('CocAutocmd', a:000)
endfunction
```
Then in the extension, we can use `BufWriteCmd` in `events.on`(typescript lint throws error though, because `BufWriteCmd` was not in [`BufEvents`](https://github.com/neoclide/coc.nvim/blob/master/src/events.ts#L9) type)
```typescript
 events.on('BufWriteCmd', async () => {...})
```

However, if coc.nvim supports that feature, we can just using an `autocmd` in vimscript.
```vim
augroup myau
  autocmd!
  autocmd BufWriteCmd *   call coc#rpc#notify('...')
augroup END
```

**Describe the solution you'd like**

Make this function as `public` would be a solution, but it's not good. Can we make an analogous function for extension?

https://github.com/neoclide/coc.nvim/blob/d48afceae96412907ef89bc938d46017c9972e32/src/plugin.ts#L361-L366

**Describe alternatives you've considered**
Or add built-in support for `BufWriteCmd`(I only need that autocmd at the moment).

**Comment by weirongxu** [comment]
I have do some similar functions in `coc-explorer`, you can take a look here https://github.com/weirongxu/coc-explorer/blob/master/plugin/coc_explorer.vim#L17-L20

**Comment by voldikss** [comment]
@weirongxu thanks, using `CocAction` is an adequately beautiful solution.
