### ISSUE TITLE
Control toggling of coc extension

### ISSUE THREAD

**Issue by unphased** [neoclide/coc.nvim#2055]
I am attempting to predicate the enabling of a resource-heavy extension based on battery discharging state of the machine. 

I am trying to use a `autocmd BufEnter * ` to call a function inside of which a shell command is run which figures out whether the machine is running on battery. Then what I need is to be able to selectively toggle the extension(s) in question (in this case I am targeting TabNine but in general there could be more). 

So far I had this working fine on a per-vim-instance basis by simply checking this on startup and if on battery to explicitly disable extension like so: 

    call CocAction('deactivateExtension', 'coc-tabnine')

However, according to the help doc, there is no corresponding `activateExtension` for the next level of implementation I'm doing now (where newly entered buffers can enable the extension if it determines that I'm actually charging now, so that I don't need to save and reload session just to update the extension state). 

So, given this situation the way should be to use `toggleExtension` if the extension is determined to be in the wrong state. This requires a way to query for whether TabNine extension is currently activated or not. 

Is there a way to query this?

**Comment by unphased** [comment]
When I run 

    let l:z = CocAction('extensionStats')  
    echo 'extensionStats: '.l:z          

I just get `extensionStats: null`.

**Comment by chemzqm** [comment]
There is `activeExtension` CocAction, you get `null` because extensions not loaded

**Comment by unphased** [comment]
Thank you for providing the functionality! This reminds me, I think you should post a bitcoin address so appreciative people like me can donate to the development of this plugin!
