### ISSUE TITLE
Per-project CoC Configuration

### ISSUE THREAD

**Issue by jackno** [neoclide/coc.nvim#2056]
**Is your feature request related to a problem? Please describe.**
I find myself working on a lot of different projects that use different formatters and linters. For example, some Python projects use `flake8` for linting and others use `pylint`.

When I open a new project with the wrong linter enabled, I'm thrown tons of errors and need to change my CocConfig.

**Describe the solution you'd like**
Having a configuration file for CoC in the project directory could help solve this problem. For example, a `coc-settings.json` in the project directory could describe that the project uses `pylint` for linting and `yapf` for code formatting.

**Describe alternatives you've considered**
It would be possible to load different configurations by defining vim triggers in `init.vim` but this isn't automatic and doesn't feel right.

**Additional context**

`project tree`
```
my_project
|- .coc-config.json
|- .flake8
|- main.py
|- test.py
-- app/
```

`.coc-config.json`
```json
{                                                                                                   
    "python.setlinter": "flake8",
    "python.formatting.provider": "yapf"
}
```

**Comment by oblitum** [comment]
Check docs/wiki, there's support for per project settings already.

**Comment by trygveaa** [comment]
Why was this removed from the wiki in 2022? I had to look at the wiki revision history to find out how to do it. It was removed here: https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file/_compare/821e033ae08a9d1ecdf7bc51b1f0e6762175fd15...a884fe0c525f1bdb78a4400092440a03a4984b32?w=1

**Comment by Salomanuel** [comment]
I still have no clue on how to make this work

**Comment by trygveaa** [comment]
@Salomanuel: In your project directory create a new directory named `.vim`. Inside that directory create a file named `coc-settings.json`. Put your project specific config in that file. Your global config will still be used for anything not specified in it.
