### ISSUE TITLE
Delay quit until actions finished

### ISSUE THREAD

**Issue by swizzard** [neoclide/coc.nvim#2057]
I have `"python.linting.lintOnSave": true` in my `CocConfig`; when I `wq` out of NeoVim, the linting starts but is often killed before it's done, resulting in a `whatever.py.<some big ugly hex value>` file being created. Is there a way to configure CoC or NeoVim to delay exiting until the linter has finished?

This may not pertain strictly to this project, but I've had no luck Googling and know nowhere else to turn.

**Comment by chemzqm** [comment]
No, and I can't reproduce your issue.
