### ISSUE TITLE
How to autoselect the first word

### ISSUE THREAD

**Issue by sometimesstudy** [neoclide/coc.nvim#2058]
When I use coc.nvim to autocomplete python, I have to press <ctrl-p> and <ctrl-n> to select the proposed word. And I want to know how to autoselect the first word like pycharm and press <Enter> to compelete

**Comment by chemzqm** [comment]
`:h coc-config-suggest`

**Comment by oblitum** [comment]
I use this instead of preselect feature (which depends on server):

```vim
inoremap <silent><expr> <c-y> pumvisible() ? coc#_select_confirm() : "\<c-y>"
```

**Comment by sometimesstudy** [comment]
thank you all, the question have been solve so quickly

**Comment by johnnyvergara** [comment]
@chemzqm 
How do I set 
`:h coc-config-suggest`
To true

**Comment by chemzqm** [comment]
Read https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file

**Comment by louisrli** [comment]
Reading the docs, I'm not quite understanding the difference between these two:

>   "suggest.noselect":          Prevent Vim from selecting the first item on completion start,

>   "suggest.enablePreselect":           Enable preselect feature on Neovim, default: false

(actually preselect isn't working for me on tsserver, but setting noselect to false autoselects the first word). I'm wondering if there's some nuance, the docs are quite concise with respect to what these features are (still not completely sure I get what preselecting is).

**Comment by chemzqm** [comment]
preselect can select item other than first one.
