### ISSUE TITLE
cocAction to show diagnostic info in a floating window.

### ISSUE THREAD

**Issue by XiaowenHu96** [neoclide/coc.nvim#2059]
**Is your feature request related to a problem? Please describe.**
Currently diagnostic can be configured to show either in `echo` or `float`.

Set diagnostic target to `echo` is the classic way before floating window is a thing, and most of the time I can fix the error message without the hint or simply with a quick glance in the command-line window.
However, sometimes I do need a full and detailed diagnostic info and I want a way to show the message in a floating window so I can have a close look.

For me, simply setting diagnostic to `float` is not very desired since most of the time it is more distracting than helping.

**Describe the solution you'd like**
A new `cocAction` called `diagnosticFloat`, similar to `diagnosticPreview`, it shows the diagnostics under current cursor in a floating window.

In an ideal world, it would be wonderful if we can supply argument to the action specifying how the message show be presented.

**Describe alternatives you've considered**
I don't know how hard it is to implement this functionality. If this feature is too much to ask, I guess I can just use `diagnosticPreview` as an alternative.

edited: refactor wording.

**Comment by chemzqm** [comment]
`:h coc-action-diagnosticPreview`

**Comment by XiaowenHu96** [comment]
Hi @chemzqm  ,

I'm not entirely sure I understand your reply. Are you suggesting the feature I'm asking is not currently the priority so `diagnosticPreview` should be used as an alternative?

Anyway, I quickly dug into the source code in `index.js` and implement the feature by myself, mostly based on `async echoMessage` and `async preview` with a bit of modification. 

The problem here is that I don't think naively adding a new function for every single way a message can be presented is a good idea.
It is better if we can provide an interface where user can pass an argument to the interface and specify how the message should be presented.
Something like `async showMessage(target)`, where the target can be either float, echo or preview. If `target` is omitted, then we look into the user config.

That being said, I'm not a javascript programmer by any mean and I might not see the whole picture here. I'm pretty happy with my own ugly modification right now anyway.

**Comment by chemzqm** [comment]
I don't consider it necessary, use preview window should be better solution.

**Comment by XiaowenHu96** [comment]
Yes I understand, it is not a critical feature anyway. Maybe it's just me being too attracted to the floating window feature. Before floating window is a thing I did use the preview window.

Anyway, I'll just stick to my own modification then,
