### ISSUE TITLE
How to back to show logs at terminal bottom

### ISSUE THREAD

**Issue by RafaelGSS** [neoclide/coc.nvim#2061]
Hi! First of all, amazing plugin, thanks!

So, after an upgrade of my neovim version to 0.4.3 and using coc version: 0.0.78 the eslint display errors is showing at pane like the following snapshot:
![Screenshot from 2020-06-10 11-42-41](https://user-images.githubusercontent.com/26234614/84282233-e438ac80-ab0f-11ea-97e7-a920970fc072.png)

But for me, it disturbed me a little because I got used to the display at the bottom of the terminal.
How I can show the message logs at bottom side again?

**Comment by T0maas** [comment]
@chemzqm Could you please tell me what excactly do I need to put in coc-settings.json? I dont understand that help from `:h coc-config-diagnostic`

**Comment by chemzqm** [comment]
`"diagnostic.messageTarget": "echo"`

**Comment by T0maas** [comment]
Thank you, I was confused, I was looking for something like "diagnostic.messageLocation": "bottom".
