### ISSUE TITLE
Autocompletion Appears in Some instances - Impacting Pairs?

### ISSUE THREAD

**Issue by jasontcole** [neoclide/coc.nvim#2064]
Why is it that even with `suggest.minTriggerInputLength: 4`, even just for experimental purposes, autocompletion appears within `{}`?  Shouldn't it require 4 characters?  

![image](https://user-images.githubusercontent.com/62342797/84311736-d3009780-ab31-11ea-8e97-b304fcc78b5e.png)

This impacts how I'd intuitively imagine coc-pairs would work.  For instance, when I try to create a function, without typing anything into `{}` and hit enter, it auto selects the first autocompletion item.  This isn't the behavior I'd expect.

![image](https://user-images.githubusercontent.com/62342797/84312130-7487e900-ab32-11ea-8fd9-95607be4c120.png)
![image](https://user-images.githubusercontent.com/62342797/84312168-84073200-ab32-11ea-8bd3-f37462ca0287.png)

![image](https://user-images.githubusercontent.com/62342797/84312240-9ed9a680-ab32-11ea-9729-82d81a1747dd.png)

On the other hand, when I declare a variable, it works as I'd expeect.  No autocompletion is suggested and so pairs works

![image](https://user-images.githubusercontent.com/62342797/84312454-f7a93f00-ab32-11ea-9719-ae1b3f58ebac.png)

![image](https://user-images.githubusercontent.com/62342797/84312470-fd068980-ab32-11ea-9f00-60d932435acf.png)

```
inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>" :
    \ <SID>check_back_space() ? "\<TAB>" :
    \ coc#refresh()
inoremap <silent><expr> <c-space> coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

```
$ more ~/.vim/coc-settings.json
{
    "diagnostic.messageTarget": "echo",
    "diagnostic.checkCurrentLine": true,
    "coc.preferences.formatOnType": true,
    "coc.preferences.hoverTarget": "float",
    "suggest.maxCompleteItemCount": 100,
    "suggest.minTriggerInputLength": 1,
    "coc.preferences.formatOnType": true
}
```

**Comment by jasontcole** [comment]
I found this to be a problem with the particular language server.  When I used a different go lang server, this didn't not occur.  The language server that I was using was internal to my company, and I didn't realize this was related to that.  

@chemzqm How would I describe this to our SWEs to request a patch?  I am not fluent in vim, so I'm wondering if there are some terms I can use to more clearly describe this problem to them.

**Comment by chemzqm** [comment]
Your language server registed it as trigger character.

**Comment by jasontcole** [comment]
> Your language server registed it as trigger character.

I am actually noticing that the only difference between the LSPs that this works with e.g. coc-go, coc-python, coc-java, is that they don't trigger the pum with `{}`.  I understand that Golang wants autocomplete for `{}` because of struct values.  Isn't the real problem that when an element isn't selected from the list, it defaults to the first one rather than breaking?

**Comment by chemzqm** [comment]
`:h coc-config-suggest` enable preselect and disable noselect, I don't think default selection is good idea.

**Comment by jasontcole** [comment]
I agree.  I'd rather not have that behavior.  How can I have `<CR>` escape the pum when default selection is off and nothing is highlighted, while still using `<CR>` for autocomplete selection and coc-pairs?

Am I required to switch to `<c-space>`?

**Comment by jasontcole** [comment]
> I agree. I'd rather not have that behavior. How can I have `<CR>` escape the pum when default selection is off and nothing is highlighted, while still using `<CR>` for autocomplete selection and coc-pairs?

@chemzqm 

Do I need to merge something similar to whats below with my vimrc (which I actually copied from [your vimrc](https://github.com/chemzqm/vimrc/blob/master/remap.vim))? If so, how would that look?

**Would this work??**
```
" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
if exists('*complete_info')
  "When enter is pressed, don't select the first auto complete item
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
endif
```

**My vimrc**
```
inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>" :
    \ <SID>check_back_space() ? "\<TAB>" :
    \ coc#refresh()
inoremap <silent><expr> <c-space> coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

**Comment by chemzqm** [comment]
You have to figure it out yourself, it's not problem of coc.nvim

**Comment by chemzqm** [comment]
You have to map cr to `<c-e>` when pumvisible without selection.
