### ISSUE TITLE
Doc of a method not disappear

### ISSUE THREAD

**Issue by RafaelGSS** [neoclide/coc.nvim#2065]
So, after an upgrade of my neovim version to 0.4.3 and using coc version: 0.0.78
some autocompletion with doc do not disappear. Like the following
![Screenshot from 2020-06-10 17-49-46](https://user-images.githubusercontent.com/26234614/84317507-4363e480-ab43-11ea-82cc-d549f72a32e9.png)
 snapshot:

The floating window just disappears when needs autocomplete another word. I don't know any more info to send here

Thanks for support.

**Comment by oblitum** [comment]
Try fill issue template and provide minimal vimrc.

**Comment by cooljser** [comment]
+1
