### ISSUE TITLE
Format fallback

### ISSUE THREAD

**Issue by tkkcc** [neoclide/coc.nvim#2068]
Hi, suck amazing plugin!

I am trying to format bash script, but bash-lsp do not support formatting. Is there a way to check if `format` action exist, then fallback to other methods.

Thanks

**Comment by chemzqm** [comment]
There is hasProvider CocAction, you can also create custom function for your Format command.

**Comment by tkkcc** [comment]
Thanks, make it out to format bash

```vim
nn <silent><expr> <leader>i CocHasProvider('format') ? CocActionAsync('format') : ":Autoformat<cr>"
````

**Comment by chemzqm** [comment]
It's better to use custom function with detect for filetype, so you know what plugin format your code.

**Comment by tkkcc** [comment]
@chemzqm I can not find an example in wiki. Do you have an example?

**Comment by chemzqm** [comment]
No, I think you should learn basic viml to write the function.

**Comment by tkkcc** [comment]
Thank you for advice.

**Comment by Moshem123** [comment]
@chemzqm 
Is this acceptable:
```
nmap <expr> <leader>p CocHasProvider('format') ? "\<Plug>(coc-format)" : ":call MyCoolFormatter()\<cr>"
```

Where `MyCoolFormatter()` has filetype detect logic?
Thanks.

**Comment by chemzqm** [comment]
My suggestion is use `&filetype` instead of `CocHasProvider` which is more clear.
