### ISSUE TITLE
compatibility with vim-template plugin

### ISSUE THREAD

**Issue by Char-Aznable** [neoclide/coc.nvim#2069]
## versions

vim version: VIM - Vi IMproved 8.2 8020950
node version: v13.11.0
coc.nvim version: 0.0.78
coc.nvim directory: /home/dlin2/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Describe the bug

The following error shows up whenever I run `vim`:
```
[coc.nvim] init not found for source vim-template
```
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：
```vim
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'do': 'yarn install'}
Plug 'aperezdc/vim-template'
call plug#end()
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
It's broken, the filename should be template.vim

**Comment by Char-Aznable** [comment]
@chemzqm  would https://github.com/aperezdc/vim-template/pull/143 resolve this?

**Comment by chemzqm** [comment]
Yes
