### ISSUE TITLE
action "addCommand" not registered

### ISSUE THREAD

**Issue by weirongxu** [neoclide/coc.nvim#2071]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-2f818eb9e
node version: v10.21.0
coc.nvim version: 0.0.78
coc.nvim directory: /Users/raidou/Projects/coc.nvim
term: iTerm.app
platform: darwin

## Output channel: watchman

[Info  - 7:42:10 PM] watchman watching project: /Users/raidou/.vim
[Info  - 7:42:10 PM] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /Users/raidou/.vim
[Info  - 7:42:10 PM] subscribing "**/.eslintignore" in /Users/raidou/.vim
[Info  - 7:42:10 PM] subscribing "**/package.json" in /Users/raidou/.vim
[Info  - 7:42:10 PM] subscribing "**/{.prettierrc,.prettierrc.json,.prettierrc.yaml,.prettierrc.yml,.prettierrc.js,package.json,prettier.config.js}" in /Users/raidou/.vim

## Output channel: prettier


## Output channel: highlight

[Info  - 7:42:10 PM] Highlight server running in node v10.21.0



```

## Describe the bug

`coc#add_command` will display an error message

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
	set nocompatible
	set runtimepath^=/Users/raidou/Projects/coc.nvim
	
	autocmd User CocNvimInit :call coc#add_command('tabnew', 'tabnew')
	
	filetype plugin indent on
	syntax on
	set hidden
  ```

- Start (neo)vim with command: `nvim -u mini.vim`

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/1709861/84567858-2da62780-adae-11ea-92db-4ba5aaef6aa0.png)

**Comment by thekenu** [comment]
Was this ever resolved? Running into a similar issue

**Comment by weirongxu** [comment]
Fixed in here https://github.com/neoclide/coc.nvim/pull/2075

**Comment by thekenu** [comment]
Awesome, thanks. My program was with `diagnosticToggle` but that was fixed after I upgraded `coc` (There was probably a patch for it similar to #2075!)
