### ISSUE TITLE
Use statusbar instead of popups

### ISSUE THREAD

**Issue by WhyNotHugo** [neoclide/coc.nvim#2072]
**Is your feature request related to a problem? Please describe.**

The popups with error messages are very annoying since they cover up the code around the cursor.
Example:

![2020-06-12T23:58:11,468187586+02:00](https://user-images.githubusercontent.com/730811/84576492-9e484680-ada4-11ea-9f00-2dacce5824ca.png)

I frequently can't see the code that's literally on the line following the error, which is often the most portion of code.

**Describe the solution you'd like**

I'd like to be able to configure coc to show error messages in the status bar rather than popups. This is pretty much what all other linters and error checkers do).

**Describe alternatives you've considered**

Can't think of any.

**Additional context**

Another example: I can see the error description, but not the relevant code.

![2020-06-13T20:37:39,220876594+02:00](https://user-images.githubusercontent.com/730811/84576539-fda65680-ada4-11ea-860d-85172af257c1.png)

**Comment by Avi-D-coder** [comment]
I use virtual text diagnostics for this reason, and trigger popups with a keybinding.

**Comment by chemzqm** [comment]
Use echo or virtual text

**Comment by hugoruscitti** [comment]
I had the same issue today, so following the recommendations of @Avi-D-coder and @chemzqm i added these lines to the `coc-settings.json` file (by calling :CocConfig):

```
  "diagnostic.virtualTextCurrentLineOnly": true,
  "diagnostic.messageTarget": "echo",
```

![image](https://user-images.githubusercontent.com/99183/91006226-3b96d680-e5af-11ea-8fc0-dcbc020add03.png)
