### ISSUE TITLE
coc.nvim create a blank file when run CocInstall

### ISSUE THREAD

**Issue by you-n-g** [neoclide/coc.nvim#2074]
## Result from CocInfo
![image](https://user-images.githubusercontent.com/465606/84582073-b908d280-ae19-11ea-9d55-92593d5408e5.png)

## Describe the bug
I want install a coc extension. So I run CocInstall(e.g. `:CocInstall coc-marketplace`)
It prompt me that it is installed and a error below.

![image](https://user-images.githubusercontent.com/465606/84582158-06d20a80-ae1b-11ea-8b7c-e168c8aeeeb5.png)

My problem is very similar to https://github.com/neoclide/coc.nvim/issues/2010 . The only difference is that deleting the blank file will not solve the problem.

## Reproduce the bug

I installled my environment on another machine. But I can't reproduce my bug on that machine.
I just want to get some suggestions
-  When will coc.nvim create  a blank file instead of installing a plugin when running `CocInstall`
- How to completely reintall neovim and coc.nvim? (I tried to remove `~/.vim/` , `~/.config/coc/` and `~/.config/nvim/`), but it doesn't work. 

Thanks so much!

**Comment by chemzqm** [comment]
Check `CocList extensions`

**Comment by you-n-g** [comment]
@chemzqm  here is the result of `CocList extensions`
![image](https://user-images.githubusercontent.com/465606/84614707-833b1b00-aef9-11ea-8479-296fdfb6b5d7.png)

**Comment by smhc** [comment]
Also seeing this issue. I have g:coc_data_home set to an EFS mount from AWS and the directories are created as blank files with error 'file already exist' errors when installing. The mount is specified as:

 type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.2.2.2,local_lock=none,addr=10.1.1.1

**Comment by you-n-g** [comment]
Here is [my workaround](https://github.com/neoclide/coc.nvim/issues/2222#issuecomment-681326292) to solve this issue
