### ISSUE TITLE
Format function will change tab to space, how can I fix it?

### ISSUE THREAD

**Issue by BSDxxxx** [neoclide/coc.nvim#2076]
I'm writing C with coc-clangd, here are my related settings:
```
set noexpandtab
set tabstop=4
set shiftwidth=4
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)
```

**Comment by fannheyward** [comment]
Can't reproduced, I've tested with coc+coc-clangd, tab didn't change after formatting.

**Comment by oblitum** [comment]
If it's calling clangd, this is set on your `.clang-format` file.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by BSDxxxx** [comment]
@oblitum Thks, I tried set:
```
UseTab: UT_Always
```
But it won't work.

**Comment by BSDxxxx** [comment]
@chemzqm Tried that, still no clue.
