### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by franleplant** [neoclide/coc.nvim#2077]
Hey guys, I know this is technically not a valid feature request nor a bug. I just wanted to say thank you for this, this is awesome, it works super fine, easy to install and gives all the nice things that modern editors have in our good old vim. 

I had some problems with YouCompleteMe and started to find alternatives and that is when I found this awesome plugin.

Thanks a lot for your work, and good job!
Fran

**Comment by oblitum** [comment]
@franleplant same experience, though I'm very early adopter. I also migrated out from YCM (long time user).
