### ISSUE TITLE
Working wtih multiple compile_commands.json

### ISSUE THREAD

**Issue by thekenu** [neoclide/coc.nvim#2078]
**Is your feature request related to a problem? Please describe.**
I have a CMake project with two build configurations, and as a result I have two different `compile_commands.json`. How can I make `ccls` use both of my `compile_commands.json`?

I'm new to CoC but did a reasonable amount of researching into this. I thought this would be a common use-case but couldn't find much discussion on this topic. 

**Describe the solution you'd like**
Some way to add a list of `compile_commands.json` to `ccls`

**Describe alternatives you've considered**

**Additional context**

**Comment by fannheyward** [comment]
Language server issue, ccls needs to add such support.

**Comment by thekenu** [comment]
Thank you!
