### ISSUE TITLE
Uncaught exception: Error: spawn ccls ENOENT

### ISSUE THREAD

**Issue by shimmeryang** [neoclide/coc.nvim#2082]
[coc.nvim]: Uncaught exception: Error: spawn ccls ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

hi,启动的时候报这个错误，但是启动完之后，能用ccls自动补全。

**Comment by fannheyward** [comment]
Make sure you are using the latest coc.nvim. Please provide minimal vimrc to reproduce this issue.

**Comment by shimmeryang** [comment]
thanks for answer, it's seems working well now. I'm just comments this warning.&nbsp;
------------------
帅哥，测试测试

&nbsp;




------------------&nbsp;Original message&nbsp;------------------
From: "Heyward Fann"; 
Sendtime: Thursday, Jun 18, 2020 10:07 AM
To: "neoclide/coc.nvim"; 
Cc: "羊羊"<382913222@qq.com>; "Author"; 
Subject: Re: [neoclide/coc.nvim] Uncaught exception: Error: spawn ccls ENOENT (#2082)





 
Make sure you are using the latest coc.nvim. Please provide minimal vimrc to reproduce this issue.

**Comment by atoder** [comment]
I have the latest coc.nvim and see the same issue.

**Comment by ashashev** [comment]
I have the same issue.

## Environment:
MacOS Monterey 12.6.2
CPU Apple M1
NodeJS installed with brew: 16.20.0, 18.16.0, 20.0.0 (I tried different version. At the same time, I had only one version of Node JS).

## Error:
```
[Error - 19:13:39.795] go client: couldn't create connection to server.
Error: Launching server "languageserver.go" using command gopls failed.
    at /Users/shashev/.vim/plugged/coc.nvim/build/index.js:248:6419
    at async Nd.createConnection (/Users/shashev/.vim/plugged/coc.nvim/build/index.js:244:15252)
    at async Nd._start (/Users/shashev/.vim/plugged/coc.nvim/build/index.js:244:7748)
    at async Object.start (/Users/shashev/.vim/plugged/coc.nvim/build/index.js:249:5338)
[Error - 19:13:39.799] spawn gopls ENOENT
Error: spawn gopls ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

## .vimrc
```
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Initialize plugin system
call plug#end()
```

## CocConfig
```
{
    "languageserver": {
        "go": {
          "command": "gopls",
          "rootPatterns": ["go.work", "go.mod", ".vim/", ".git/", ".hg/"],
          "filetypes": ["go"],
          "initializationOptions": {
            "usePlaceholders": true
          }
        }
    }
}
```

**Comment by fannheyward** [comment]
> spawn gopls ENOENT

`ENOENT` means no entity, node can't find gopls to run, make sure it's in your $PATH.

**Comment by ashashev** [comment]
There is something strange inside my laptop, because I can run gopls manually from terminal, from terminal inside vim and from vim script too. Nevertheless, I put full path to gopls in coc config and it helped. Now it works.

Thank you!
