### ISSUE TITLE
BountySource have turned evil - Are there alternate ways to support the project?

### ISSUE THREAD

**Issue by anelson** [neoclide/coc.nvim#2085]
**Is your feature request related to a problem? Please describe.**

Sort of.  This is a meta issue about Bountysource, the system used to support the project.

**Describe the solution you'd like**

Bountysource recently changed their terms of service in a very dishonest and underhanded way.

[BountySource have turned evil – alternatives?](https://news.ycombinator.com/item?id=23551098)

I've been a supporter of (and daily user of) coc.nvim for several months now.  Unfortunately after this change I consider Bountysource to be completely unworthy of trust and have cancelled my payments to both Neovim and coc.nvim on that platform.  

I want very much to continue to support your work, but I don't want to support such evil behaviour on the part of the payment processor.

**Describe alternatives you've considered**

I am open to using any alternative mechanism.  Maybe Github Sponsors is mature enough, I don't know.  

**Additional context**

What BountySource did is not the fault of the projects that use BountySource to collect funds from supporters, and it's definitely not fair that projects like this one could lose supporters as a result of this change.  I am not trying to strong-arm the project or force your hand, so I hope it doesn't come across that way.  Once you have an alternative funding mechanism in place I'll continue to support the project and will add whatever amount I would have paid via BountySource in the time it takes to make the transition.

In the HackerNews thread I linked above, commenter buovjaga listed a few possible alternative services:

* https://gitpay.me/
* https://issuehunt.io/
* https://gitcoin.co/landing
* https://tip4commit.com/

**Comment by happycoder97** [comment]
just found there's an update to original the article: https://diziet.dreamwidth.org/5938.html

**Comment by OkanEsen** [comment]
> I am open to using any alternative mechanism. Maybe Github Sponsors is mature enough, I don't know.

Github Sponsors won't work, because @chemzqm is from China.

See: https://github.com/neoclide/coc.nvim/issues/1695#issuecomment-605763307

The other alternatives to support the project/maintainer directly is via:

Patreon: https://patreon.com/chemzqm
Paypal: https://www.paypal.me/chezqm

I admit, that I didn't check the other alternatives but are there any additional advantages they provide that the other (Paypal, Patreon) don't?
