### ISSUE TITLE
getReferences timeout after 5s

### ISSUE THREAD

**Issue by rosmanov** [neoclide/coc.nvim#2086]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v10.16.3
coc.nvim version: 0.0.78-fc983ce6dd
term: screen-256color
platform: linux

## Output channel: phpls
[Info  - 4:21:17 PM] Initialising intelephense 1.3.11
[Info  - 4:21:17 PM] Reading state from /home/ruslan/.config/coc/extensions/coc-phpls-data/7e45e085.
[Info  - 4:21:18 PM] Initialised in 1134 ms
[Info  - 4:21:19 PM] Indexing started.
[Info  - 4:22:07 PM] Indexing ended. 66997 files indexed in 47s.
[Info  - 4:22:14 PM] Writing state to /home/ruslan/.config/coc/extensions/coc-phpls-data/7e45e085.
[Info  - 4:22:14 PM] Wrote state in 7.3s.
```

## Describe the bug

I'm using [coc-phpls](https://github.com/marlonfan/coc-phpls) extension with Premium Intelephense in PHP projects. The issue is that `:call CocAction('jumpReferences')` fails to fetch references for most of `public` methods after timeout of 5 seconds:

```
2020-06-18T16:40:46.178 ERROR (pid:22872) [languages] - getReferences timeout after 5s
2020-06-18T16:40:46.178 ERROR (pid:22872) [plugin] - Error: getReferences timeout after 5s
    at Timeout.setTimeout [as _onTimeout] (/home/ruslan/.vim/plugged/coc.nvim/build/index.js:51180:28)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2020-06-18T16:41:23.463 INFO (pid:22872) [services] - registered service "Json language server"
2020-06-18T16:41:23.463 INFO (pid:22872) [services] - Json language server state change: stopped => starting
2020-06-18T16:41:23.465 INFO (pid:22872) [language-client-index] - json started with 24186
2020-06-18T16:41:23.536 INFO (pid:22872) [services] - Json language server state change: starting => running
2020-06-18T16:41:23.537 INFO (pid:22872) [services] - service Json language server started
```

## Reproduce the bug

Since I'm working with a large closed source project, and the bug is apparently related to the size of the project, I cannot provide the "minimal reproducible" case here. If you close the issue, then I'll try to find a solution myself, and if I don't, I'll probably switch to something else.

But the test case is simple:
0. Install `coc-phpls` Coc extension: `CocInstall coc-phpls`
1. Choose a large project with 60e3 PHP files.
2. In Neovim, open a file with PHP class having a public method which is used in at least one place in the project.
3. Place keyboard cursor on the method name (in the method declaration)
4. `:call CocAction('jumpReferences')` or invoke a keyboard shortcut similar to the following:
```
nmap <silent> gr <Plug>(coc-references)
```
5. Wait for 5-10 seconds, then check out contents of "Coc Neovim log" which was located at `/run/user/1000/coc-nvim-22872.log` on my PC at the time of writing. I had to track down the file with `lsof`, since I haven't found how to debug the stuff in the docs.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

Your language server is too slow to response.

**Comment by rosmanov** [comment]
Okay, I switched from `coc-phpls` to `intelephence` and have some information in the output channel now.

h3. Steps

- Opened `output:///languageserver.intelephense` with `:CocCommand workspace.showOutput`
- Opened a class with a public method
- Put cursor on the method name
- Called `:call CocAction('jumpReferences')`

h3. Actual Result

```
:CocCommand workspace.showOutput

[Trace - 11:56:36 AM] Sending request 'textDocument/references - (8)'.
Params: {
    "textDocument": {
        "uri": "file:///home/ruslan/projects/my-project/path/to/MyClass.php"
    },
    "position": {
        "line": 91,
        "character": 20
    },
    "context": {
        "includeDeclaration": false
    }
}

[Trace - 11:56:57 AM] Received response 'textDocument/references - (8)' in 21184ms.
Result: [
    {
        "uri": "file:///home/ruslan/projects/my-project/path/to/MyClass.php"
        "range": {
            "start": {
                "line": 201,
                "character": 39
            },
            "end": {
                "line": 201,
                "character": 47
            }
        }
    }
]
```

h3. Expected Result

At least one reference to the usage of the public method. And there is that reference, and I can even jump from the method call to its definition with `:call CocAction('jumpDefinition')` from another file where the method is called as follows:

```
$this->BuildValidator->validate($partners, $this->BuildStructure);
```

h3. Coc configuration


```json
{
    "languageserver": {
        "intelephense": {
            "command": "intelephense",
            "args": ["--stdio"],
            "filetypes": ["php"],
            "initializationOptions": {
                "storagePath": "/home/ruslan/tmp/intelephense"
            },
            "trace.server": "verbose"
        }
    },
    "intelephense.completion.insertUseDeclaration": false,
    "intelephense.phpdoc.useFullyQualifiedNames": true,
    "intelephense.files.associations": [ "*.php", "*.phtml", "*.inc" ],
    "intelephense.references.exclude": [
        "**/vendor/**",
        "*.phtml"
    ],
    "intelephense.licenceKey": "XXX",
    "intelephense.phpdoc.returnVoid": false,
    "intelephense.files.maxSize": 5000000
}
```
where the `intelephense.licenceKey` value was changed for obvious reasons.

**Comment by chemzqm** [comment]
21184ms it's too slow

**Comment by rosmanov** [comment]
@chemzqm, 
> 21184ms it's too slow
yeah, but `intelephense` language server was the official one, right? I don't mind using any, if it's going to be faster. But, as I mentioned, the project is really big.

**Comment by rosmanov** [comment]
@chemzqm , did you notice the following part?

> ￼ But after I renamed validate to validatePartners the jumpReferences worked as expected!

It is working well (and is pretty fast) with more specific method names.
