### ISSUE TITLE
Only completes the function name without the corresponding parameter.

### ISSUE THREAD

**Issue by NGPONG** [neoclide/coc.nvim#2089]
**Is your feature request related to a problem? Please describe.**
As the title suggests, I would expect coc's completions to be able to complete function names without taking the corresponding parameter.

**Describe the solution you'd like**
Provides the user with an option to set

**Describe alternatives you've considered**
`<C-n>` & `<C-p>` are possible to a certain extent, but they only complete the function name of the previous or next item, not the currently selected item.

**Comment by chemzqm** [comment]
Disable preselect and enable noselect of suggest

**Comment by NGPONG** [comment]
> Disable preselect and enable noselect of suggest

Thanks for the response, I noticed the two options you mentioned, but that was just another way to solve the problem, not really an experience that was needed, isn't it? 

Because I still need to work around to pressing `C-n` and `C-p` to fix **Only completes the function name without the corresponding parameter**

Ideally have a setting that allows us have `<CR>` or `<Tab>` to complete only the function name even if the `pre-selected` & `no-select`  was be seted

As shown in the following gif(by vscode), when I press enter or tab, it will always just fill in the function name for me without taking the corresponding argument.

![Mygif](https://user-images.githubusercontent.com/38415769/85192684-055e8180-b2f6-11ea-8927-7dcf82965bb4.gif)

**Comment by chemzqm** [comment]
You can pass configuration to disable snippet completion support for a language server now.

> Ideally have a setting that allows us have <CR> or <Tab> to complete only the function name even if the pre-selected & no-select was be seted

It's not possible, coc.nvim won't detect function name and it's intended to expand snippet on completion confirm.
You have to disable snippet for your language server, or use `<C-n>` and `<C-p>` to insert word without confirm.

**Comment by NGPONG** [comment]
As you said, I looked through the ccls documentation and found this option, and it did work when I disabled the appropriate settings!

**Comment by oblitum** [comment]
@NGPONG first time seeing this request, sounded a bit weird, in general, when completing, if you don't want snippet expansion, you just have to select the menu option and move on without confirming, that's normal bare textual completion. If when selecting itens in the menu, there's NO completion, then there's something wrong. Guess you figured that on your server.

**Comment by oodzchen** [comment]
If you use ccls, this would be helpful: https://github.com/MaskRay/ccls/wiki/Customization#completionplaceholder
