### ISSUE TITLE
Extensions added through vim-plug not showing on extensions list nor extension stats

### ISSUE THREAD

**Issue by asermax** [neoclide/coc.nvim#2097]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-567-g4496628c1
node version: v14.4.0
coc.nvim version: 0.0.78
coc.nvim directory: /home/xxx/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Output channel: snippets

[Info 8:47:08 PM] Using ultisnips directories: UltiSnips /home/xxx/.config/coc/ultisnips
[Info 8:47:09 PM] Using ultisnips python command: pyx

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Error 128 on: 'git rev-parse --show-toplevel' in /home/xxx
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

## Output channel: watchman

## Output channel: explorer

## Output channel: highlight

[Info  - 8:47:09 PM] Highlight server running in node v14.4.0
```

## Describe the bug

Currently using the `master` branch of `coc`; I noticed that after [this](https://github.com/neoclide/coc.nvim/commit/10afb3dcd6355563005eae807bfc6f931a0dfb62) commit, extensions loaded through `vim-plug` are no longer shown when using `CocList extensions` or calling `CocAction('extensionStats')`, I'm not sure if that's the intended behaviour.
This is mostly innocuous, but I'm using another plugin that depens on the extension stats to know if some `coc` extensions are available to enable certain behaviour which is now broken because of this.
If this is the intended behaviour then I'll open an issue on the other plugin; just wanted to double check here first!

## Reproduce the bug

- Create file `mini.vim` with (need `vim-plug` in place):

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  call plug#begin()
  Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
  Plug 'neoclide/coc-highlight', {'do': 'yarn install --frozen-lockfile'}
  call plug#end()
  ```
- Start (neo)vim with command: `vim -u mini.vim`
- Input either the `CocList extensions` or `echom CocAction('extensionStats')` command.
- The extension list shown is empty

**Comment by fannheyward** [comment]
Reproduced.
