### ISSUE TITLE
incorrect completion list for rust reqwest crate

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2099]
## Result from CocInfo
![image](https://user-images.githubusercontent.com/33961674/85407932-262c0e80-b564-11ea-9418-990bdb6bc9fb.png)

![image](https://user-images.githubusercontent.com/33961674/85407894-190f1f80-b564-11ea-8adb-0f1599a8e29c.png)

## Describe the bug

coc.nvim doesn't correct completes the full list of a rust external crate

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

https://github.com/GopherJ/cfg/blob/master/coc/.vimrc

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/33961674/85407785-f0872580-b563-11ea-9e08-e0489076d1f9.png)

**Comment by GopherJ** [comment]
It should have `client` completed but I cannot find it

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
