### ISSUE TITLE
Do not close documentation while completing in insert mode

### ISSUE THREAD

**Issue by ChrisAmelia** [neoclide/coc.nvim#2102]
**Is your feature request related to a problem? Please describe.**
When completing from a method with parameters, documentation can be shown with:

```vim
augroup mygroup
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end
```

However, when typing in insert mode, the preview window closes.

**Describe the solution you'd like**
Do not close the preview window until completion is done.

**Comment by fannheyward** [comment]
Can't reproduce, the signature floating window will not close in insert mode.
