### ISSUE TITLE
getHover is synchronous? which freezes my neovim

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2107]
## Describe the bug

1. I installed coc.nvim and coc-rust-analyzer
2. rust-analyzer crashed when I hit *K* on `}`
3. neovim freezes for 5 seconds
4. I got following error

![image](https://user-images.githubusercontent.com/33961674/85631031-0c2e2100-b675-11ea-8ffc-8177449192a2.png)

I think this means `getHover` function is synchrnous no? I cannot type and the whole world stopped

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

https://github.com/GopherJ/cfg/blob/master/coc/.vimrc

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by GopherJ** [comment]
reproduce:

1. install coc.nvim
2. install coc-rust-analyzer
3. create a cargo project
4. put cursor: 
![image](https://user-images.githubusercontent.com/33961674/85631375-b312bd00-b675-11ea-97bc-32c6da3e8338.png)
5. hit *K*

**Comment by GopherJ** [comment]
I'm incorrect here, seems it's not because of `}` because it always crashes.

**Comment by fannheyward** [comment]
No, most likely it's LS error.

**Comment by chemzqm** [comment]
Use CocActionAsync function to avoid vim block
