### ISSUE TITLE
Disable/hide cursor under F character of "FUZZY"?

### ISSUE THREAD

**Issue by tmpm697** [neoclide/coc.nvim#2108]
## Result from CocInfo
```
vim version: NVIM v0.4.3
node version: v14.4.0
coc.nvim version: 0.0.78
coc.nvim directory: /home/user/.vim/pack/default/start/coc.nvim
term: tmux
platform: linux
```
## Describe the bug

When open `:CocList` there's always cursor under `F` character of `FUZZY` word, I want to disable or remove it.
## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- type `:CocList` in command mode.

**Comment by chemzqm** [comment]
You have to use latest neovim
