### ISSUE TITLE
during editing, my page flicks by coc errors and warnings 

### ISSUE THREAD

**Issue by alisajadih** [neoclide/coc.nvim#2109]
## Result from CocInfo
     1                                                                                  
     2 vim version: VIM - Vi IMproved 8.2 8020539                                       
     3 node version: v14.4.0
     4 coc.nvim version: 0.0.78-551353208d
     5 coc.nvim directory: /Users/sedali/.vim/plugged/coc.nvim                          
     6 term: Apple_Terminal
     7 platform: darwin
     8 
     9 ## Output channel: prettier            
    10 
    11                                                                                  
    12 ## Output channel: snippets                                                      
    13                                                                                  
    14 [Info 2:33:35 PM] Using ultisnips directories: UltiSnips /Users/sedali/.config/coc/ultisnips
    15 [Info 2:33:35 PM] Using ultisnips python command: pyx                            
    16 

## Describe the bug
 during editing my code in macvim, coc errors and wanings shows up in left side of my screen and before line numbers.
and by changing the code, errors and their placement will change actually. but my screen flicks when placement of errors changes.  

## Reproduce the bug
here is my `coc-settings`

   ```{
     1   "eslint.autoFixOnSave": true, 
     2   "eslint.filetypes": [ 
     3     "javascript", 
     4     "javascriptreact", 
     5     "typescript", 
     6     "typescriptreact" 
     7   ], 
     8   "prettier.disableSuccessMessage": true, 
     9   "suggest.noselect": false, 
    10   "diagnostic.messageDelay": 100, 
    11   "diagnostic.refreshOnInsertMode": true 
    12 
} 
```

and here is some for coc section of my `.vimrc`,

```
let g:coc_global_extensions = [
      \ 'coc-tsserver'
       \ ]
     if isdirectory('./node_modules') && isdirectory('./node_modules/prettier')
       let g:coc_global_extensions += ['coc-prettier']
     endif
     
     if isdirectory('./node_modules') && isdirectory('./node_modules/eslint')
       let g:coc_global_extensions += ['coc-eslint']
     endif
     inoremap <silent><expr> <TAB>
           \ pumvisible() ? "\<C-n>" :
           \ <SID>check_back_space() ? "\<TAB>" :
           \ coc#refresh()
     inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
    
     function! s:check_back_space() abort
       let col = col('.') - 1
       return !col || getline('.')[col - 1]  =~# '\s'
     endfunction
     
     inoremap <silent><expr> <leader><leader> coc#refresh()
      
      if exists('*complete_info')
        inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
      else
       inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
      endif
      nmap <silent> [g <Plug>(coc-diagnostic-prev)
      nmap <silent> ]g <Plug>(coc-diagnostic-next)
      nmap <silent> gd <Plug>(coc-definition)



```
do i need config in vimrc or coc-settings ? or this is a embed problem of coc

## Screenshots (optional)
as you can see, when i try editing, the button of screen flicks first, by continuing editing, screen will flicks more.

![bugcoc](https://user-images.githubusercontent.com/44581771/85703518-ad0ff100-b6f4-11ea-8956-e931a007c57b.gif)

**Comment by chemzqm** [comment]
The reason is we have to send redraw to vim when  using channel feature, you can disable coc.nvim to avoid it
