### ISSUE TITLE
Disable preview and set delay for autocomplete

### ISSUE THREAD

**Issue by xvoidee** [neoclide/coc.nvim#211]
Hello,
I started using your coc plugin (with ccls) for C++ (not a smallest project: >300k of lines), amazing job! I like it very much, easy to use and most important - IT WORKS! From the box :)

So far 1 have only 3 questions for now:
- can I disable hidden popup showing me documentation of class/method/variable? It is popping up in upper part of my editor. I managed to disable it when I completed my input, but it is annoying (as I have generated documentation separately)
- can I set delay for autocomplete popup? Example: I press "." and after 1 second window pops up

Last question: semantic highlight, do you plan to implement it?

Thanks, and keep going!

**Comment by chemzqm** [comment]
> can I disable hidden popup showing me documentation of class/method/variable?

Sure, just remove `preview` from `completeopt` by `set completeopt-=preview` in your .vimrc.

> can I set delay for autocomplete popup? Example: I press "." and after 1 second window pops up.

No, the earlier version of vim 8.1 and neovim 3.1 has bug when you open preview window with pumvisible.

> semantic highlight, do you plan to implement it?

It's proposed feature of LSP, will add the support when it's finalized.

**Comment by xvoidee** [comment]
Thank you! :)
