### ISSUE TITLE
Show language server source completion items higher up in the completion menu

### ISSUE THREAD

**Issue by rbhanot4739** [neoclide/coc.nvim#2111]
**Is your feature request related to a problem? Please describe.**
Hello, I am using `coc-tabnine` and `coc-python` for getting autocompletion in python files, plus there `coc-yank` items as well. So in the completion menu I get multiple entries from multiple sources mentioned above which is fine but the issue is with order in which they are displayed. I would expect to see the items from language server i.e. `coc-python` at the top, followed by `tabnine` and lastly the items from `coc-yank`. I see there are options like `suggest.defaultSortMethod` and `suggest.languageSourcePriority` but there is not much context on how to get done what I am expecting.

**Describe the solution you'd like**
Some way to either increase the priority of language server items or better sorting method.

**Comment by chemzqm** [comment]
Read wiki

**Comment by jchook** [comment]
For future visitors..

## Language server sources

Language server source priorities have a special config option. I found the option in the coc-settings [schema.json](https://github.com/neoclide/coc.nvim/blob/c447dc25b5d37f03738e566c856208dd5d4ae613/data/schema.json#L344).

1. Use `:CocConfig` to edit your coc-settings.json
2. Set the priority of all language server suggestions with `suggest.languageSourcePriority`, e.g.

```json
{
  "suggest.languageSourcePriority": 99
}
```

For changes to take effect, you can run `:CocRestart` then see if the changes took hold in `:CocList sources`.

## TabNine

TabNine (and perhaps others) has their own priority option that appears to override other settings. By default it uses the `suggest.languageServerPriority` value, but you can override it with `tabnine.priority` like so:

```json
{
  "tabnine.priority": 98
}
```

## Other sources

See the [Configuring Sources](https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#configuring-sources) in the wiki.

1. You can use `:CocList sources` to see the available sources
1. Take note of the name of the sources (first column) and the current priority (number column, between 0-99?)
1. Edit your coc-settings.json with `:CocConfig`. 
1. At the top level, you can add a setting like `"coc.source.{name}.priority": 10,`, e.g.

```json
{
  "coc.source.buffer.priority": 50
}
```

**Comment by sisrfeng** [comment]
How should we chose the proper priority?   Is the absolute value not important?
Why some default priority is 90, instead of 10, 20 or something else?

**Comment by arrosbullit** [comment]
Hi,
How to change `coc-clangd` source priority?

I use `coc-clangd` as autocompletion source and I would like to lower its priority from 99 to 70. I cannot find how to do in the doc. 
 I tried the following without success  :CocConfig and then:
```
  "suggest.languageSourcePriority": 70,
  "coc.source.clangd.priority": 70,
  "clangd.priority": 70,

```
To check the current priority I do :CocList, sources, TAB, refresh and it always show:
`* clangd                 [LS]       .<>:"/*    99
`
