### ISSUE TITLE
Insert all possible completions

### ISSUE THREAD

**Issue by segeljakt** [neoclide/coc.nvim#2115]
When coding in a language with match expressions (e.g., Rust) I use completions to complete each enum-variant:

```rust
match my_enum {
  MyEnum::MyVariant1 => ...
  MyEnum::MyVariant2 => ...
  MyEnum::MyVariant3 => ...
}
```

The annoying thing is I need to complete each variant in isolation. A match-expression over an enum with *N* variants requires at most *N* completions. What I want is the ability to insert all variants at once (i.e., insert all completions). This functionality is common to most IDEs.

**Comment by oblitum** [comment]
Language server task. Provided by ["magic completions"](https://rust-analyzer.github.io/manual.html#magic-completions) in rust-analyzer (`foo.match`, then expand snippet).
