### ISSUE TITLE
coc ignores 'shiftwidth' when formatting

### ISSUE THREAD

**Issue by heftig** [neoclide/coc.nvim#212]
My setup uses `shiftwidth=4` for indentation and leaves `tabstop` set to 8.

This is similar to what the `rust-vim` ftplugin does, which uses
```vim
setlocal tabstop=8 shiftwidth=4 softtabstop=4 expandtab
```

However, coc.nvim always sends the tabstop value to the server, and as a result `coc-rls` formats the document with an indent of 8 instead of 4, as every other function does.

Now, it's impossible to perfectly map vim's complex indentation settings to the language server settings. The latter is only capable of using either spaces or a single tab for indent; mixed indent or using multiple tabs is impossible. Still, I believe we can do a bit better than only using tabstop.

I think coc.nvim should prefer the `shiftwidth` value and only use `tabstop` if `shiftwidth == 0`.

Maybe there's a better solution? Should shiftwidth only be used if `expandtab` is set?

**Comment by heftig** [comment]
Maybe something like this? I'm not familiar with Typescript and only gave it a cursory test.
```diff
diff --git i/src/workspace.ts w/src/workspace.ts
index 69b2b91..ea80bca 100644
--- i/src/workspace.ts
+++ w/src/workspace.ts
@@ -506,13 +506,9 @@ export class Workspace implements IWorkspace {
     } else {
       doc = await this.document
     }
-    if (!doc) return {
-      tabSize: await this.nvim.getOption('tabstop') as number,
-      insertSpaces: (await this.nvim.getOption('expandtab')) == 1
-    }
-    let { buffer } = doc
-    let tabSize = await buffer.getOption('tabstop') as number
-    let insertSpaces = (await buffer.getOption('expandtab')) == 1
+    let tabSize = await this.getDocumentOption('shiftwidth', doc) as number
+    if (!tabSize) tabSize = await this.getDocumentOption('tabstop', doc) as number
+    let insertSpaces = (await this.getDocumentOption('expandtab', doc)) == 1
     let options: FormattingOptions = {
       tabSize,
       insertSpaces
@@ -1144,6 +1140,10 @@ augroup end`
     return await this.nvim.call('fnameescape', bufname)
   }
 
+  private getDocumentOption(name: string, doc?: Document) {
+    return doc ? doc.buffer.getOption(name) : this.nvim.getOption(name)
+  }
+
   private setMessageLevel(): void {
     let config = this.getConfiguration('coc.preferences')
     let level = config.get<string>('messageLevel', 'more')
```

**Comment by chemzqm** [comment]
You're right, we should prefer to use `shiftwidth` as tabSize.

**Comment by chemzqm** [comment]
Fixed by https://github.com/neoclide/coc.nvim/commit/7fa8bb9830ddfeeecfc15d335c4be415fc3cd14c

**Comment by lippirk** [comment]
I had this issue even with this patch - i fixed it by calling `set shiftwidth=n` after loading the coc plugin

**Comment by chemzqm** [comment]
Your setting should have changed by other plugin.
