### ISSUE TITLE
coc.nvim and unicode support (with julia-vim)

### ISSUE THREAD

**Issue by AndreasAZiegler** [neoclide/coc.nvim#2120]
**Is your feature request related to a problem? Please describe.**
I use coc.nvim daily at work for C++ code and I'm very happy with it. I'm now playing around with the Julia programming language and facing the following problem. In the Julia REPL I can type latex and with a press on TAB it turns into unicode e.x. ```\alpha``` -> ```α```. I installed [julia-vim](https://github.com/JuliaEditorSupport/julia-vim) which supports this feature in neovim but doesn't work together with coc.nvim.

**Describe the solution you'd like**
I would like to use coc.nvim together with [julia-vim](https://github.com/JuliaEditorSupport/julia-vim) so that I can convert latex into unicode but also have type completion. One idea (not sure if it is possible): As all the latex "code" starts with ```\``` there could be a way to pass the TAB button press to another plugin?

**Comment by oblitum** [comment]
Did you try checking whether disable signature help is what you want? https://github.com/neoclide/coc.nvim/blob/master/data/schema.json#L627

**Comment by oblitum** [comment]
I guess you won't want it disable for actual julia code, so, I don't think coc.nvim can do much, this seems like some option that should be on the server, regarding trigger characters it reports.

**Comment by chemzqm** [comment]
The problem could be julia-vim not support for TextChanged or your key-mapping of `<tab>` is broken.
