### ISSUE TITLE
Can i disable code formating on when using coc-rename?

### ISSUE THREAD

**Issue by MarkoB-hub** [neoclide/coc.nvim#2122]
every time i use rename my code formats, is there a way to disable this? or to change formating style?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

coc.nvim doesn't format your code on rename, but language server may send textEdits with for format.

**Comment by MarkoB-hub** [comment]
okay, thanks
