### ISSUE TITLE
coc.vim can't creat ~/AppData/Local/nvim, file already exists.

### ISSUE THREAD

**Issue by TUT123456** [neoclide/coc.nvim#2123]
Since I used the Spacevim, the nvim folder already exists, when I used ```:CocConfig``` to open ```coc-settings.json```, the nvim outputs a message: ```E739: Cannot create directory C:\Users\75679\AppData\Local\nvim: file already exists```, but I can still open coc-settings.json.  This is an annoying tip.

**Comment by chemzqm** [comment]
Looks like it's symbol link.

**Comment by TUT123456** [comment]
> Looks like it's symbol link.
Maybe coc doesn't recognize it as a directory. 
How do I change the ```C:\Users\75679\AppData\Local\nvim``` to ```C:\Users\75679\SpaceVim```.

**Comment by chemzqm** [comment]
It's problem of your vim, checkout `:h g:coc_config_home`
