### ISSUE TITLE
Snippets jump error when choose the completion item in snippets

### ISSUE THREAD

**Issue by glepnir** [neoclide/coc.nvim#2125]
## Result from CocInfo

```log
vim version: NVIM v0.5.0-nightly
node version: v14.4.0
coc.nvim version: 0.0.78
coc.nvim directory: /Users/stephen/.cache/vim/dein/repos/github.com/neoclide/coc.
term: iTerm.app
platform: darwin
```

## versions

coc.nvim : 0.0.78

## Describe the bug

If choose the completion item, the jump snippets action will skip next snippet.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
set runtimepath+=~/.cache/vim/dein/repos/github.com/neoclide/coc.nvim
set runtimepath+=~/.cache/vim/dein/repos/github.com/honza/vim-snippets
set nocompatible
filetype plugin indent on
syntax on
set hidden
let g:coc_snippet_next = '<TAB>'
let g:coc_snippet_prev = '<S-TAB>'

call coc#config('languageserver', {
  \ 'golang': {
  \ "command": "gopls",
  \ "rootPatterns": ["go.mod"],
  \ "disableWorkspaceFolders": "true",
  \ "filetypes": ["go"]
  \ }
  \})
```

- Start (neo)vim with command: `vim -u mini.vim`

- vi main.go then input a People struct with a test method. then type meth to trigger method snippet.
```go
type People struct{
    age int
}

// type meth to trigger method snippets.  `|` means cursor here.
func (p  |)name(params)type{
}
````
- the server will return a completion item `People struct` choose this. then tab to jump next snippet.

- the cursor will jump to `params` , it skip the `name` snippet.

- If i input `People`  it works fine. maybe it's a bug of gopls?

## Screenshots (optional)

![test](https://user-images.githubusercontent.com/41671631/86132640-bdbbcf00-bb19-11ea-9b08-5548f38b25bb.gif)

**Comment by oblitum** [comment]
Looks like a regression of #1562 / #156. It's also broken in Rust:

![screencast](https://user-images.githubusercontent.com/1269815/86146465-a1df0b80-bace-11ea-98c3-19ff21e30e31.gif)

**Comment by glepnir** [comment]
Works fine. Thanks.
