### ISSUE TITLE
Coc-rename only works in open buffers

### ISSUE THREAD

**Issue by intercaetera** [neoclide/coc.nvim#2126]
When using `coc-rename`, only open buffers are affected. If you need to change a variable name in a file that is imported in 100 different files, it's a bit unwieldy to manually open all those 100 files on your own. You can try something like a `vimgrep`, but that's not necessarily ideal.

How do you use `coc-rename` without manually opening all the buffers that it would affect?

**Comment by chemzqm** [comment]
It's documented, some servers support cross files rename you can use reafctor support of coc.nvim

**Comment by oblitum** [comment]
For example, with clangd (or coc-clangd), you can pass `-cross-file-rename` to enable this.

**Comment by intercaetera** [comment]
@chemzqm I'm not sure what you mean by "it's documented", I checked the docs of both coc.nvim and coc-tsserver and I can't find anything about this.

**Comment by iago-lito** [comment]
@intercaetera I think this is documented on the servers side, whether they support cross file renaming or not, although I haven't checked myself.
