### ISSUE TITLE
Unhandled rejection: character number must not be less than zero

### ISSUE THREAD

**Issue by glacambre** [neoclide/coc.nvim#2128]
Hi,

Somebody opened an issue in my repo, but the error looks like it comes from CoC: https://github.com/glacambre/firenvim/issues/619 .

Apparently CoC throws a `UnhandledRejection: request error nvim_call_function - Vim(let): E5070: Character number must not be less than zero` error. They didn't provide a way to reproduce the problem and I haven't tried to reproduce it either.

As far as I can tell, this error is thrown by neovim in nr2char:

https://github.com/neovim/neovim/blob/267bc57d21fd7cc995ea91028de912d92d5fd662/src/nvim/eval/funcs.c#L6105-L6133

Hopefully this helps debugging this problem.

Feel free to close this issue if you don't want to deal with it - I just thought it should be logged in the right place before I close the issue in my repo :).

**Comment by chemzqm** [comment]
Should be problem with neovim's channel and `getchar()` which return value less than 0
