### ISSUE TITLE
Error on BufEnter: Cannot read property 'uri' of null

### ISSUE THREAD

**Issue by lee-shun** [neoclide/coc.nvim#2129]
hello, there

When I was using the nvim(v0.5)and coc.nvim with the coc-python and coc-pyright on ubuntu18,04. There was an error saying: "Error on BufEnter: Cannot read property 'uri' of null". And I find a same error in the VScode project:https://github.com/microsoft/vscode/issues/79172, But I don't know how to fix it! Could you help me!

**Comment by oblitum** [comment]
No idea on that error, but in the first place you're not advised to sub both coc-python and coc-pyright at the same time.

See https://github.com/fannheyward/coc-pyright/issues/67

**Comment by fannheyward** [comment]
@lee-shun please provide a minimal vimrc to reproduce this issue.

**Comment by chemzqm** [comment]
Checkout the log of coc.nvim.
