### ISSUE TITLE
Add  coc-stylelint* packages to wiki?

### ISSUE THREAD

**Issue by NullVoxPopuli** [neoclide/coc.nvim#2132]
This is neither a bug nor a feature request, but... documentation issue? idk

Today, I discovered that these exist

- https://github.com/bmatcuk/coc-stylelintplus#readme
- https://github.com/neoclide/coc-stylelint

Should they be added to this list? https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#implemented-coc-extensions

**Comment by oblitum** [comment]
The wiki is open for edits, if you think it's worth mentioning you can add.
