### ISSUE TITLE
Does not support multiple completion sources from a single LSP source.

### ISSUE THREAD

**Issue by vantreeseba** [neoclide/coc.nvim#2138]
https://github.com/neoclide/coc.nvim/blob/master/src/language-client/client.ts#L1885

Due to using the client id here, when more than one type of file completion is registered from a server, it overrides the previous one,

Since this is just a lookup string, can we make this unique by doing something like 

this._client.id + languageIds so that if a server provides capabilities for completion for different language ids, it correctly registers?

This is the cause of vshaxe/vshaxe#447

**Comment by vantreeseba** [comment]
I did test this by appending a randomly generated ID to the client id and it corrected the issue.

**Comment by chemzqm** [comment]
Fixed by 190ebfce
