### ISSUE TITLE
vim freeze while call <Plug>(coc-codeaction-selected)

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2145]
## Result from CocInfo

![image](https://user-images.githubusercontent.com/33961674/86536106-54570a00-bee5-11ea-83e1-9d7dc4e61662.png)

## Describe the bug

while hit \<leader\>a without selecting anything, vim starts to freeze, I must kill it from another shell

## Reproduce the bug

1. enter vim
2. hit \<leader\>a without doing anything

- Create file `mini.vim` with：

![image](https://user-images.githubusercontent.com/33961674/86536123-73559c00-bee5-11ea-98de-873958f659b5.png)
https://github.com/GopherJ/cfg/blob/master/coc/.vimrc

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
Vim's bug with channel, it just blocked when `operatorfunc` send synchronize request to channel.
