### ISSUE TITLE
use detached child process to format file instead of waiting to finish

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2148]
**Is your feature request related to a problem? Please describe.**

`formatOnSave` needs to wait the process to finish its job before exiting vim, which can be really long

https://github.com/neoclide/coc.nvim/blob/5d0557f13f6c03cc3ff3a54bdc08755ea9318d4f/src/languages.ts#L118

**Describe the solution you'd like**

> Can we use detached child process to format the file? I'm not really sure if it's possible. If it's ok, do we need a file lock?

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
No, it have to sync.

**Comment by eddiewang** [comment]
do you know if there's any solution for this? coc-prettier takes about 5-10s the first time i try to save. Subsequent saves are fine, but it is quite annoying.

**Comment by chemzqm** [comment]
Avoid use eslint with prettier

**Comment by chemzqm** [comment]
My recommendation is use coc-tsserver for format
