### ISSUE TITLE
yaml-language-server sending the LanguageServer the wrong URL.

### ISSUE THREAD

**Issue by esn89** [neoclide/coc.nvim#215]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
## versions

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.35
term: iTerm.app
platform: darwin

## Error messages

**Describe the bug**
I'm trying to get schemas working for AWS CloudFormation yaml template.
I have successfully got the yaml-language-server installed and working, however when I pass in the settings of schema, it is sending the wrong URL to the language server.

A detailed description is also found in the [yaml-language-server issues thread](https://github.com/redhat-developer/yaml-language-server/issues/20#issuecomment-443303419)

Essentially, the language server does not register the '.'s that are needed to generate a proper url to access the schema.json

Resulting in an error like this:
https://user-images.githubusercontent.com/8839537/49313961-e94a8380-f4b6-11e8-9c2e-a2cae3568d59.png

From my :CocConfig, I have the schema set like this:
```
	"yaml.schemas": {
		"https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json": "/*"
	}
```

There seems to be no similar behaviour in a different client like VS Code, so my educated guess is that it could be in Coc?

**To Reproduce**
In [this comment](https://github.com/redhat-developer/yaml-language-server/issues/20#issuecomment-443319445) I have the detailed step-by-step to reproduce

**Screenshots**
https://user-images.githubusercontent.com/8839537/49313696-206c6500-f4b6-11e8-830b-6a6667ecded6.png

https://user-images.githubusercontent.com/8839537/49313961-e94a8380-f4b6-11e8-9c2e-a2cae3568d59.png

**Comment by esn89** [comment]
Hi @chemzqm , 

I see that you've pushed a fix to it, so I decided to test it out using my configuration:

```
{
	"coc.preferences.diagnostic.errorSign": " ",
	"coc.preferences.diagnostic.warningSign": " ",
	"coc.preferences.diagnostic.infoSign": " ",
	"coc.preferences.diagnostic.hintSign": "",
	"yaml.trace.server": "verbose",
	"yaml.customTags": [
		"!Ref",
		"!GetAtt",
		"!fn",
		"!And",
		"!If",
		"!Not",
		"!Equals",
		"!Or",
		"!FindInMap sequence",
		"!Base64",
		"!Cidr",
		"!Sub",
		"!GetAZs",
		"!ImportValue",
		"!Select",
		"!Split",
		"!Join sequence"
	],
	"languageserver": {
		"yaml": {
			"module": "/Users/esn89/.config/coc/extensions/node_modules/yaml-language-server/out/server/src/server.js",
			"filetypes": ["yaml"],
			"cwd": "./src",
			"args": ["--stdio"],
			"settings": {
				"format.enable": true,
				"validate": true,
				"completion": true,
				"schemas": {
					"https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json": "/*"
				}
			}
		}
	}
}
```
It still didn't manage to work, so I took a look inside the verbose debug log and I got this:

`[Trace - 09:39:38] Sending request 'initialize - (0)'.
Params: {
    "processId": 6193,
    "rootPath": "/Users/esn89/Documents/Projects",
    "rootUri": "file:///Users/esn89/Documents/Projects",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": false,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ]
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            }
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///Users/esn89/Documents/Projects",
            "name": "Projects"
        }
    ]
}


[Trace - 09:39:38] Received response 'initialize - (0)' in 207ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "completionProvider": {
            "resolveProvider": true
        },
        "hoverProvider": true,
        "documentSymbolProvider": true,
        "documentFormattingProvider": false
    }
}


[Trace - 09:39:38] Sending notification 'initialized'.
Params: {}


[Trace - 09:39:38] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "yaml": {
            "trace": {
                "server": "verbose"
            },
            "schemas": {},
            "format": {
                "enable": false,
                "singleQuote": false,
                "bracketSpacing": true,
                "proseWrap": "preserve"
            },
            "validate": true,
            "hover": true,
            "completion": true,
            "customTags": [
                "!Ref",
                "!GetAtt",
                "!fn",
                "!And",
                "!If",
                "!Not",
                "!Equals",
                "!Or",
                "!FindInMap sequence",
                "!Base64",
                "!Cidr",
                "!Sub",
                "!GetAZs",
                "!ImportValue",
                "!Select",
                "!Split",
                "!Join sequence"
            ]
        },
        "http": {
            "proxyStrictSSL": true
        }
    }
}


[Trace - 09:39:38] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///Users/esn89/Documents/Projects/confluence/templates/confluence-database2.yaml",
        "languageId": "yaml",
        "version": 1,
        "text": "---\nAWSTemplateFormatVersion: False\n\nDescription: Creation of RDS\n\nResources:\n\n  RDSConfluence:\n    Type: AWS::RDS::DBInstance\n    Properties:\n      DeletetionProtection: 8\n      AllowMajorVersionUpgrade: \"wee\"\n"
    }
}


[Trace - 09:39:38] Sending notification 'json/schemaAssociations'.
Params: {}


[Trace - 09:39:38] Sending notification 'yaml/registerCustomSchemaRequest'.
No parameters provided.


[Trace - 09:39:38] Received request 'custom/schema/request - (0)'.
Params: "file:///Users/esn89/Documents/Projects/confluence/templates/confluence-database2.yaml"


[Trace - 09:39:38] Sending response 'custom/schema/request - (0)'. Processing request took 0ms
No result returned.


[Trace - 09:39:39] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/esn89/Documents/Projects/confluence/templates/confluence-database2.yaml",
    "diagnostics": []
}


[Trace - 09:39:39] Received request 'custom/schema/request - (1)'.
Params: "file:///Users/esn89/Documents/Projects/confluence/templates/confluence-database2.yaml"


**[Trace - 09:39:39] Sending response 'custom/schema/request - (1)'. Processing request took 0ms
No result returned.**


[Trace - 09:39:39] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/esn89/Documents/Projects/confluence/templates/confluence-database2.yaml",
    "diagnostics": []
}



[Trace - 10:00:04] Sending notification '$/setTraceNotification'.
Params: {
    "value": "verbose"
}


[Trace - 10:00:04] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "yaml": {
            "trace": {
                "server": "verbose"
            },
            "schemas": {},
            "format": {
                "enable": false,
                "singleQuote": false,
                "bracketSpacing": true,
                "proseWrap": "preserve"
            },
            "validate": true,
            "hover": true,
            "completion": true,
            "customTags": [
                "!Ref",
                "!GetAtt",
                "!fn",
                "!And",
                "!If",
                "!Not",
                "!Equals",
                "!Or",
                "!FindInMap sequence",
                "!Base64",
                "!Cidr",
                "!Sub",
                "!GetAZs",
                "!ImportValue",
                "!Select",
                "!Split",
                "!Join sequence"
            ]
        },
        "http": {
            "proxyStrictSSL": true
        }
    }
}


[Trace - 10:00:04] Received request 'custom/schema/request - (2)'.
Params: "file:///Users/esn89/Documents/Projects/confluence/templates/confluence-database2.yaml"


[Trace - 10:00:04] Sending response 'custom/schema/request - (2)'. Processing request took 0ms
No result returned.


[Trace - 10:00:04] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/esn89/Documents/Projects/confluence/templates/confluence-database2.yaml",
    "diagnostics": []
}

`

**Comment by esn89** [comment]
Hi @chemzqm 

Thank you for your fast reply.  I did as you told me to, however I am still experiencing this:

https://i.imgur.com/d570vrm.png

I see that in the autocomplete there are two choices "yaml.schema" and "yaml.schemas".

However, yaml.schema gives this error.

**Comment by iamcco** [comment]
yaml.schemas works for me

**Comment by esn89** [comment]
Right now I have:
```
{
	"coc.preferences.diagnostic.errorSign": " ",
	"coc.preferences.diagnostic.warningSign": " ",
	"coc.preferences.diagnostic.infoSign": " ",
	"coc.preferences.diagnostic.hintSign": "",
	"yaml.trace.server": "verbose",
	"yaml.schemas": {
		"https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json": "/*"
		},
	"yaml.customTags": [
		"!Ref",
		"!GetAtt",
		"!fn",
		"!And",
		"!If",
		"!Not",
		"!Equals",
		"!Or",
		"!FindInMap sequence",
		"!Base64",
		"!Cidr",
		"!Sub",
		"!GetAZs",
		"!ImportValue",
		"!Select",
		"!Split",
		"!Join sequence"
	],
	"yaml.validate": true,
	"yaml.completion": true
}
```
And I have a bigger log this time [https://pastebin.com/0inzYA9B](https://pastebin.com/0inzYA9B)

I use this as input:

```
---
AWSTemplateFormatVersion: False

Description: Creation of RDS

Resources:

  RDSConfluence:
    Type: AWS::RDS::DBInstance
    Properties:
      DeletetionProtection: 8
      AllowMajorVersionUpgrade: "wee"
```

As you can see here, as per the schema https://i.imgur.com/AVmOu99.png
The "AllowMajorVersionUpgrade must be a boolean.  But I am not getting any errors.

**Comment by chemzqm** [comment]
@esn89 settings send to language server is wrong, looks like you're using binary version of coc, to make latest fix works, you need to run `yarn install` in folder of coc.nvim.

**Comment by esn89** [comment]
aaaah I see.

so this hasn't been released yet?

**Comment by chemzqm** [comment]
Yes, binary release is not update quite often.

**Comment by esn89** [comment]
So this will give the latest/testing version?
Plug 'neoclide/coc.nvim', {'do': 'yarn install'}


And this gives stable binary?

Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}

**Comment by chemzqm** [comment]
Use `:echo coc#util#job_command()` to get the command used for start server, maybe I should add this to `:CocInfo`

**Comment by esn89** [comment]
That means each time, I have to manually run this command to start it?

By the way, I have made sure that I have the master branch:
``` git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean```

This is in ~/.config/nvim/plugged/coc.nvim

```
git rev-parse HEAD
8c07f4be4b9c781a706c3e66de03a2d908ef30cf
```

However, it still says that yaml.schema (with no s) is:
[json] [W] Property yaml.schema is not allowed.

**Comment by chemzqm** [comment]
Use `yaml.schemas` instead.

**Comment by chemzqm** [comment]
> That means each time, I have to manually run this command to start it?

No, it's just function to get command used for start coc server.

**Comment by esn89** [comment]
Yay, it works now.  Thank you.

So I just wait for binary release, yes?

**Comment by chemzqm** [comment]
Yes, or build from source
