### ISSUE TITLE
Issues I had while adding this plugin into Vim 8.1

### ISSUE THREAD

**Issue by hqkhan** [neoclide/coc.nvim#2150]
## Result from CocInfo

```
## versions


vim version: VIM - Vi IMproved 8.1 8012269
node version: v14.5.0
coc.nvim version: 0.0.78-c9246e45a1
coc.nvim directory: /home/hkhan/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Output channel: snippets

[Info 2:28:27 PM] Using ultisnips directories: UltiSnips /home/hkhan/.config/coc/ultisnips
[Info 2:28:28 PM] Using ultisnips python command: pyx
```

## Describe the bug

Disclaimer: This is more so to explain what I had to deal with. I was using Vim 8.1 when I had the issues that I will describe below. I have since switched to `neovim` and my problems immediately went away.

1. Editing a path in `workspacefolders` was acting weird as it caused a graphical issue where nothing was show in vim as I was typing. Here is a picture of what I was seeing:

![image](https://user-images.githubusercontent.com/22674069/86633772-14ecf400-bf9f-11ea-819d-dddea2c5ebc1.png)

I was editing the only path that exists there but as I typed, nothing gets shown or the path being updated would "flicker" in and out. Deleting the path caused issues as well. Basically, interacting with `CocList` -> `folders` caused these issues.

2. Another issue I had was scrolling through options in `Coc` command mode. For example, if I issued `:CocCommand` and scrolled through them quickly using my down key, vim immediately quit command mode and goes into insert mode while inserting a `B` character in my cursor's position. 

This issue is bizarre to me but I wanted to let you know regardless.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim mini.vim`

- Operate vim.

*Again, switching to `neovim` solved these problems immediately.*

**Comment by chemzqm** [comment]
Fixed first one, for the second, read https://github.com/neoclide/coc.nvim/wiki/F.A.Q#coclist-is-broken-when-holding-up-or-down-on-vim

**Comment by hqkhan** [comment]
Ty @chemzqm
