### ISSUE TITLE
Documentation popup doesn't display text inside parenthesis and quotes

### ISSUE THREAD

**Issue by Heermod** [neoclide/coc.nvim#2151]
Hi, in my documentation popup, text inside parenthesis ( example) and inside quotes inside parenthesis ("example") is not visible unless marked with mouse.
Changing themes did not work.
How do i fix it?
![Screenshot_20200707_014245](https://user-images.githubusercontent.com/32239575/86670307-c8cc9e80-bff4-11ea-9e61-3925aae758f7.png)

**Comment by fannheyward** [comment]
<img width="484" alt="2020-07-07 09 37 20" src="https://user-images.githubusercontent.com/345274/86684799-75c70b80-c035-11ea-91a8-4eff03a8a13b.png">

colorscheme issue.

**Comment by chemzqm** [comment]
`:h coc-highlights`
