### ISSUE TITLE
CocInstall request timeout

### ISSUE THREAD

**Issue by ehyyoj** [neoclide/coc.nvim#2152]
When I install the `coc-explorer`, but get error: `✗ coc-explorer Request timeout after 10000ms`. 

It may be the network proxy cause this problem and I run `npm install -g coc-explorer --registry=http://myregistry.com` is OK.

Does has any way to change the `--registry` ?

**Comment by fannheyward** [comment]
You can't change `registry` now. You can use `vim-plug` to install:

`Plug 'weirongxu/coc-explorer', {'do': 'yarn install --frozen-lockfile'}`

**Comment by ehyyoj** [comment]
thanks, bro!
