### ISSUE TITLE
anguageserver.python" server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by chenyidao110** [neoclide/coc.nvim#2153]
OS: WSL ubuntu 20.04
software: NVIM v0.5.0-dev, latest coc.nvim
issue descriable: start vim/neovim, open py file,then generate error and message as follow: [coc.nvim] The "languageserver.python" server crashed 5 times in the last 3 minutes. The server will not be restarted. I'm sure python-server(pyls) is normal ,so there must be something wrong in coc

**Comment by oblitum** [comment]
Try filling issue template.

**Comment by oblitum** [comment]
Also, it's the server that's crashing, not coc.
