### ISSUE TITLE
Incorrect document context after apply textEdit

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#2154]
## Describe the bug

Incorrect document context after apply textEdit.

## Reproduce the bug

coc-settings.json:

```json
{
  "languageserver": {
    "rust": {
      "command": "rust-analyzer",
      "filetypes": ["rust"],
      "rootPatterns": ["Cargo.toml", ".git/"],
      "progressOnInitialization": true
    }
  }
}
```

main.rs:

```rust
fn main() {
    abc();
}
```

Put cursor on `abc`, fire codeAction to choose `Add function`, will result

```rust
fn main() {
    abc();
}
fn abc() {
    todo!()
}

```

This result is wrong.

## Tracking issue

The textEdit from LS:

```
{
  newText: '\n\nfn abc() {\n    todo!()\n}',
  range: { end: { character: 1, line: 2 }, start: { character: 1, line: 2 } }
}
```

After [TextDocument.applyEdits](https://github.com/neoclide/coc.nvim/blob/e902150e8e1a9c0cfee22533339b0eba227237ce/src/model/document.ts#L304), `applied` is:

```rust
fn main() {
    abc();
}

fn abc() {
    todo!()
}

```

buffer lines after [this.buffer.setLines](https://github.com/neoclide/coc.nvim/blob/e902150e8e1a9c0cfee22533339b0eba227237ce/src/model/document.ts#L308-L314)

```
[
  'fn main() {',
  '    abc();',
  '}',
  '',
  'fn abc() {',
  '    todo!()',
  '}'
]
```

**Comment by fannheyward** [comment]
I came this error with `rust-analyzer` and https://github.com/rodrigore/coc-tailwind-intellisense, after some tracking, I found `TextDocument.applyEdits` will result correct content, but document content is wrong.

**Comment by davidsierradz** [comment]
After this commit, all files formatted by `coc-prettier` are getting an extra `\n`
