### ISSUE TITLE
Any idea why is this.

### ISSUE THREAD

**Issue by MhammadDayeh** [neoclide/coc.nvim#2156]
The warning sign appear too small, i tried switching to other fonts and it sometimes appear a smaaaaall little bit bigger, but still small. Not sure why it appears like this.
![problem](https://user-images.githubusercontent.com/42265793/86800613-44c1f780-c084-11ea-9af9-821077fd390c.PNG)

**Comment by oblitum** [comment]
Please ask on gitter channel, I may provide some help there. Guess this is too long to discuss here, given it's not coc.nvim issue.

**Comment by MhammadDayeh** [comment]
Oh ya, i figured that the issue must be on my side, as coc.nvim is working perfect. Sorry about that.
