### ISSUE TITLE
Goto definition open new tab file.

### ISSUE THREAD

**Issue by windwp** [neoclide/coc.nvim#2158]
Hi is there anyway to customize goto definition to open file in new tab like vscode.
Currently if i am press `gd` it open file in current buffer but I already open it in a newtab . I need it go to that tab

**Is your feature request related to a problem? Please describe.**
Goto definition change current file in buffer

**Describe the solution you'd like**
Goto definition open new tab file.

**Comment by fannheyward** [comment]
`"coc.preferences.jumpCommand": "tabe"` to your coc-settings.json

**Comment by Hanwn** [comment]
But when I want to jump back, using `ctrl-o`, it will open previous file in current buffer. The situation just like the [link](https://stackoverflow.com/questions/40612870/vim-jump-back-dont-use-existing-tab).
