### ISSUE TITLE
Error on notification "highlight": Cannot read property 'start' of null

### ISSUE THREAD

**Issue by jackielii** [neoclide/coc.nvim#2160]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v12.14.1
coc.nvim version: 0.0.78
coc.nvim directory: /home/jackieli/.dotfiles/nvim/plugged/coc.nvim
term: screen-256color
platform: linux

## Output channel: explorer


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/jackieli/nodejs/coc.nvim
resolved root: /home/jackieli/nodejs/coc.nvim
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Output channel: prettier


## Output channel: snippets

[Info 11:17:46] Using ultisnips directories: UltiSnips gosnippets/UltiSnips /home/jackieli/.dotfiles/coc/ultisnips
[Info 11:17:47] Using ultisnips python command: pyx


```

## Describe the bug

This happens in bash language server: cocconfig:

```
  "languageserver": {
    "bash": {
      "command": "bash-language-server",
      "args": ["start"],
      "filetypes": ["sh"],
      "ignoredRootPaths": ["~"]
    }
  },
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
set nocompatible
let g:coc_node_args = ['--nolazy', '--inspect-brk=6045']
set runtimepath^=/home/jackieli/nodejs/coc.nvim
filetype plugin indent on
syntax on
set hidden
autocmd CursorHold * silent call CocActionAsync('highlight')
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

`nvim -u ~/.config/nvim/minimal-coc.vim ~/.tmux/plugins/extrakto/scripts/helpers.sh`

Just over over a word inside double quote, see screenshot.

I've seen this error in quite a few places, but with minimal, I was able to reproduce this problem with that file. The files is avalable at: https://github.com/jackielii/extrakto/blob/master/scripts/helpers.sh

You have to clone the full repo, as I think this has something to do the bash language server

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/360983/86910965-6a95dd80-c112-11ea-9e9e-2f717cfdb9c3.png)

## Stack trace
```
TypeError: Cannot read property 'start' of null
    at /home/jackieli/nodejs/coc.nvim/lib/model/document.js:504:28
    at Array.reduce (<anonymous>)
    at Document.matchAddRanges (/home/jackieli/nodejs/coc.nvim/lib/model/document.js:503:30)
    at DocumentHighlighter.highlight (/home/jackieli/nodejs/coc.nvim/lib/handler/documentHighlight.js:61:32)
    at async Handler.highlight (/home/jackieli/nodejs/coc.nvim/lib/handler/index.js:677:9)
    at async /home/jackieli/nodejs/coc.nvim/lib/plugin.js:199:13
    at async Plugin.cocAction (/home/jackieli/nodejs/coc.nvim/lib/plugin.js:442:16)
    at async NeovimClient.<anonymous> (/home/jackieli/nodejs/coc.nvim/lib/attach.js:66:21)
```

**Comment by jackielii** [comment]
my imperative fix seem to work but I don't think this is solving the root problem:

![image](https://user-images.githubusercontent.com/360983/86911952-05db8280-c114-11ea-9f5b-ff3981372238.png)

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by jackielii** [comment]
Indeed, upgrade to latest language server fixed the problem:

```
npm upgrade -g bash-language-server
```

**Comment by jackielii** [comment]
gg
