### ISSUE TITLE
Activate hover manually

### ISSUE THREAD

**Issue by jason0x43** [neoclide/coc.nvim#2162]
**Is your feature request related to a problem? Please describe.**

I like using floating windows to display code errors. However, I don't want the floats to always be visible. For example, if I'm moving through a segment of code with a lot of errors, I'll often have trouble reading the code because error floats keep popping up over the text.

**Describe the solution you'd like**

coc should have an option that allows hover actions (or at least error displays) to be manually triggered instead of automatically triggered.

This would let coc work more like VSCode. In VSC, hovering is a function of the mouse cursor rather than the text cursor, and you can move the text cursor around in code without triggering error popups. 

**Describe alternatives you've considered**

I setup a hotkey to hide floats, but having to hit the hotkey every time I land on an error is annoying.

**Additional context**

**Comment by chemzqm** [comment]
It's already supported

**Comment by jason0x43** [comment]
Great! How? I've read through the manual, but I don't see any way to 1) manually open an error float (just hide them), or 2) prevent floats from opening automatically when `diagnostic.messageTarget` is float.

**Comment by oblitum** [comment]
I think there may be a confusion, you use the "hover" term, which in general refers to the "doHover" code action, nothing to do with error floats that show when cursor is at error.

**Comment by oblitum** [comment]
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-could-i-disable-floating-window.

**Comment by chemzqm** [comment]
Change `"diagnostic.enableMessage"` to `"jump"` and use `<Plug>(coc-diagnostic-info)` to show diagnostic messages.

**Comment by jason0x43** [comment]
> I think there may be a confusion, you use the "hover" term, which in general refers to the "doHover" code action (which is activated manually), nothing to do with error floats that show when cursor is at error.

Yeah, that wasn't the best terminology. I noticed that diagnostic messages didn't trigger with `doHover`, but I figured they were still conceptually a "hover" behavior.

> Change "diagnostic.enableMessage" to "jump" and use <Plug>(coc-diagnostic-info) to show diagnostic messages.

That works great, thanks!

**Comment by p135246** [comment]
Can one make "jump" work also in the case that the cursor jump was initiated by a mouse click?

**Comment by p135246** [comment]
Is it possible to add an option that shows the diagnostic  when the cursor is moved to the current line? (similar to "jump" but with the trigger being the change of the position of the cursor to the current line)

**Comment by fannheyward** [comment]
@p135246 

> shows the diagnostic when the cursor is moved to the current line

Check `:h coc-config-diagnostic-checkCurrentLine`.
