### ISSUE TITLE
[Question] Is there any way to declare all installed exentions?

### ISSUE THREAD

**Issue by rjshrjndrn** [neoclide/coc.nvim#2165]
First of all, thank you for this awesome plugin. Now I can use most of the ide stuff in my fingertips.
A small question. If we're using plugins like `deoplete` or such, then all our installed plugins will be in init.vim.
But in coc, we're using `coc-install`. So is there **any way to declare all the plugins**, so that If I check out my dotfiles, all the plugins will be installed and ready to use?

**Comment by oblitum** [comment]
`:h g:coc_global_extensions@en` or directly by plugin manager.

**Comment by rjshrjndrn** [comment]
@oblitum Sorry for being a noob. But what you meant by directly plugin manager ? can you please elaboate a bit.

**Comment by oblitum** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension

**Comment by oblitum** [comment]
It's not the primary approach, `g:coc_global_extensions` is okay.
