### ISSUE TITLE
list all symbols in a folder (golang package)

### ISSUE THREAD

**Issue by smartding** [neoclide/coc.nvim#2167]
It's already possible to list all symbols in a document and workspace with the `CocList outline` and `CocList -I symbols`.

Is it possible to list all symbols in a folder (golang package).  

In golang, we can divide a package into multiple files. When I search for a symbol in a package, it's not always clear which one of these files a symbol might be in.

vim-go provides a command called `GoDeclsDir`, which parses the whole directory for the given file and lists all the declarations from the files in the given directory (but not subdirectories)

**Comment by chemzqm** [comment]
No, no such kind of feature of LSP.
