### ISSUE TITLE
coc.nvim's signatureHelp offsets are not identical to VSCode, bug?

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#2168]
See this comment: https://github.com/rust-analyzer/rust-analyzer/issues/4751#issuecomment-657126783.

All details to reproduce, with minimal `.vimrc` and communication logs here: https://github.com/rust-analyzer/rust-analyzer/issues/4751#issuecomment-640753866.

**Comment by fannheyward** [comment]
Reproduced with coc + coc-rust-analyzer, not coc + languageserver.rust. It's coc-rust-analyzer issue.
