### ISSUE TITLE
Autoupdate: not windows, but command line

### ISSUE THREAD

**Issue by wookayin** [neoclide/coc.nvim#2171]
**Is your feature request related to a problem? Please describe.**

From some recent versions autoupdate of plugin appears in a vertically-splitted window. But this is annoying for me. Previously autoupdate status messages were printed on the command line.

**Describe the solution you'd like**

Can we have the previous behavior back? Or is there any way to configure it? I cannot find anything in the documentation.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by chemzqm** [comment]
No, the split window could gives you more information,  you can use `vim +CocUpdateSync +qa` to upgrade extensions in your shell.

**Comment by wookayin** [comment]
I am sorry, but I disagree. Because autoupgrade happens at the startup of vim (daily), `vim +CocUpdateSync +qa` doesn't help this situation much unless one completely disable the autoupdate.

The vertical column consumes too much space, this is pretty distracting. Why not horizontal split below with few lines, for example? I think this should be ideally configurable. Could you leave this issue open?

**Comment by oblitum** [comment]
Autoupdates are not being applied by default anymore, you have to enable it explicitly.

**Comment by DONofDESTROY** [comment]
@wookayin  I totally agree with you

@chemzqm  atleast horizontal split will be great as many have small screen (especially me) atleast an option to configure it for horizontal split 

@oblitum I think making auto update off by default doesn't solve this issue

**Comment by chemzqm** [comment]
It's easy to add options, we could try to use statusline and floating window for extension update in the feature.
When using vim-plug you have to build the code and it would takes much more disk space.
