### ISSUE TITLE
global extensions didn't support custom version @vx.x.x

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2173]
#1613  Result from CocInfo

## Describe the bug

If we use custom version of certain extension, coc will try to download it every time when we open vim

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden

  let g:coc_global_extensions = [
    "coc-prettier@1.1.12"
  \]
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by GopherJ** [comment]
@chemzqm Have you been waitting for more than 5 seconds? It starts to download after like 5 seconds

**Comment by chemzqm** [comment]
No

**Comment by GopherJ** [comment]
@chemzqm 
![Peek 2020-07-14 11-49](https://user-images.githubusercontent.com/33961674/87411922-b04a1e80-c5c8-11ea-869c-ec2fb0f4e058.gif)
