### ISSUE TITLE
gVim8.2下, 行号左侧的错误提示列双宽度字符的残留问题

### ISSUE THREAD

**Issue by RickoNoNo3** [neoclide/coc.nvim#2174]
## 运行环境
gVim8.2 on Windows 10 2004
## 问题简介
行号左侧的错误提示列存在字符残留的问题
(好像这一列叫signcolumn?)
### 第一种情况: 左侧消失, 右侧残留
- 当行号左侧显示一个占用两个字符宽度的图标时: ![QQ截图20200715003258](https://user-images.githubusercontent.com/42743884/87451683-cee4ff80-c632-11ea-9c78-1c93606bae27.jpg)
- 当这个图标代表的**问题被解决后**(或**切换buffer后**): ![QQ截图20200715003451](https://user-images.githubusercontent.com/42743884/87451856-094e9c80-c633-11ea-83c9-83b7d9d0e000.jpg)
### 第二种情况: 右侧消失, 左侧残留
- 显示图标时与第一种情况相同
- 问题依然存在时, **最小化gVim**, 再还原: ![QQ截图20200715004014](https://user-images.githubusercontent.com/42743884/87452450-d22cbb00-c633-11ea-8aaa-2ca81914ed9e.jpg)
### 双宽度字符 vs 单宽度字符
双宽度单字符存在上述问题, 单宽度的双字符无此问题
![QQ截图20200715004228](https://user-images.githubusercontent.com/42743884/87452794-39e30600-c634-11ea-8fd2-f1bee6876ab5.jpg)
### Vim vs gVim
powershell/cmd下的Vim无此问题
gVim有此问题
### Linux vs Windows
Ubuntu/CentOS下的纯控制台/GUI终端/SSH均无此问题, 未安装gVim不便测试

**Comment by RickoNoNo3** [comment]
After writing descriptions above, I tried to reclone and rebuild my coc.nvim and it now works as:
![QQ截图20200715015008](https://user-images.githubusercontent.com/42743884/87459128-91d23a80-c63d-11ea-86fc-6ed28161e4ba.jpg)
**It's JUST half of the display no matter what kind of situation!**

## My CocInfo(may not help)
```
vim version: VIM - Vi IMproved 8.2 8020012
node version: v12.16.1
coc.nvim version: 0.0.78
coc.nvim directory: C:\Users\rick\vimfiles\plugged\coc.nvim
term: undefined
platform: win32
```

**Comment by chemzqm** [comment]
Issue of your vim
