### ISSUE TITLE
<c-space> mapping does not work in vim but works in neovim

### ISSUE THREAD

**Issue by pbnj** [neoclide/coc.nvim#2176]
## Result from CocInfo

```text
## versions

vim version: VIM - Vi IMproved 8.2 8021200
node version: v12.16.3
coc.nvim version: 0.0.78-c250e18604
coc.nvim directory: /Users/pbenjamin/.vim/plugged/coc.nvim
term: dumb
platform: darwin
```

## Describe the bug

Per README:

```
" Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()
```

This works in neovim, but vim does not support `<c-space>`.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  inoremap <silent><expr> <c-space> coc#refresh()
  ```

- Start vim with command: `vim -u mini.vim Dockerfile`

- Go into insert mode and type: `FROM ubuntu:` + `<c-space>` (you will receive the error in the screenshot below)

- In `mini.vim`, replace `inoremap <silent><expr> <c-space> coc#refresh()` with

  ```vimrc
  if has('nvim')
	  inoremap <silent><expr> <c-space> coc#refresh()
  else
	  inoremap <silent><expr> <c-@> coc#refresh()
  endif
  ```

- Restart vim with command: `vim -u mini.vim Dockerfile`

- Go into insert mode and type: `FROM ubuntu:` + `<c-space>` (now you will receive completions as expected)

## Screenshots (optional)

![Screen Shot 2020-07-15 at 10 25 38 AM](https://user-images.githubusercontent.com/6811830/87576417-38dac480-c686-11ea-97b7-839a3870388e.png)

**Comment by pbnj** [comment]
I arrived at `<c-@>` by printing the keycode that vim sees when users press space in insert mode (i.e. open a buffer, go into insert mode, type `<c-v> <space>`).

Would you like me to contribute this to the README?

```viml
" Use <c-space> to trigger completion.
if has('nvim')
    inoremap <silent><expr> <c-space> coc#refresh()
else
    inoremap <silent><expr> <c-@> coc#refresh()
endif
```

Alternatively, we can just add this as a comment:

```viml
" Use <c-space> to trigger completion in neovim with ctrl+space
inoremap <silent><expr> <c-space> coc#refresh()
" Use <c-@> to trigger completion in vim with ctrl+space
" inoremap <silent><expr> <c-@> coc#refresh()
```

**Comment by oblitum** [comment]
Vim has many issues with special key mappings which NeoVim fixes. This is not a coc.nvim issue, except for recommending such a mapping without a warning.

**Comment by pbnj** [comment]
@oblitum - I agree. I am fine with contributing that info in the appropriate docs.
