### ISSUE TITLE
<Plug>(coc-range-select) does notr respect v:count

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#2179]
`<Plug>(coc-range-select)` only ever executes once. `2<Plug>(coc-range-select)` setting `v:count = 2` should expand twice, but it does not. This makes `<Plug>(coc-range-select)` unusable with [vim-expand-region](https://github.com/terryma/vim-expand-region)

**Comment by chemzqm** [comment]
It's doesn't trigger twice, so I think it's not problem of the key-mapping.

**Comment by chemzqm** [comment]
It's not normal mode command of vim, so it's expected.

**Comment by Avi-D-coder** [comment]
Is there any way to get this to work?
It'd be a shame if coc text object are completely incompatible with the text obj ecosystem.

**Comment by chemzqm** [comment]
It's not text object, you can create text object by lower level api.

**Comment by Avi-D-coder** [comment]
What API?
Also why isn't it a text object?
Extend selection in vscode behaves like a text object, why not here?

**Comment by chemzqm** [comment]
Sorry, can't help

**Comment by Avi-D-coder** [comment]
Well this is the best I can do:
If I type `<F11><F11>` I get a selection starting on line 452, colum 19, but if I type `2<F11>` a line is added after the the cursor line containing the text `452G17|o`

```vim
function CocActionCount(args) range
  let count = v:count
  call call('CocAction', a:args)
  let i = 1
  while i < count
    call CocAction('rangeSelect', visualmode(), v:true)
    let i += 1
  endw
endfunction

vnoremap <F11> :call CocActionCount(['rangeSelect', visualmode(), v:true])<CR>
nnoremap <F11> :call CocActionCount(['rangeSelect', '', v:true])<CR>
```

**Comment by Avi-D-coder** [comment]
For any who cares this is the fix
```
function! ExtendSelection() range
  let count = v:count1
  while count > 0
    call feedkeys("\<Plug>(coc-range-select)")
    let count -= 1
  endwhile
  let head_pos = getpos("'<")
  let tail_pos = getpos("'>")
  let tail_pos[2] -= 1
  return ['v', head_pos, tail_pos]
endfunction

call textobj#user#plugin('extend', {
\   '-': {
\     'select-a-function': 'ExtendSelection',
\     'select-a': 'ae',
\   },
\ })

let g:expand_region_text_objects_rust = {
      \ 'iv'  :0,
      \ 'iw'  :0,
      \ 'ia'  :1,
      \ 'ae'  :1,
      \ 'il'  :0,
      \ 'i]'  :1,
      \ 'ib'  :1,
      \ 'iB'  :1,
      \ 'if'  :1,
      \ 'af'  :1,
      \ }
```
