### ISSUE TITLE
call CocActionAsync('rename') does not work

### ISSUE THREAD

**Issue by CodyGuo** [neoclide/coc.nvim#2181]
## versions

vim version: VIM - Vi IMproved 8.2 8021233
node version: v14.4.0
coc.nvim version: 0.0.78
coc.nvim directory: /Users/CodyGuo/.vim/bundle/coc.nvim
term: iTerm.app
platform: darwin

## Output channel: languageserver.golang

[Info  - 上午9:50:27] 2020/07/18 09:50:27 Build info
----------
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.4.3 h1:irz7Q+XdHNECamFKbNWKvMV2Ak6zBbwdwbZndG4545I=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
    golang.org/x/tools@v0.0.0-20200717024301-6ddee64345a6 h1:nULzSsKgihxFGLnQFv2T7lE5vIhOtg8ZPpJHapEt7o0=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.4 darwin/amd64
[Info  - 上午9:50:27] 2020/07/18 09:50:27 go/packages.Load
    snapshot=0
    directory=/Users/CodyGuo/go/src/tools/scan-image
    query=[./... builtin]
    packages=2

[Info  - 上午9:50:27] 2020/07/18 09:50:27 go env for /Users/CodyGuo/go/src/tools/scan-image
(valid build configuration = true)
(build flags: [])
GO111MODULE=""
GOARCH="amd64"
GOBIN="/opt/app/go/bin"
GOCACHE="/Users/CodyGuo/Library/Caches/go-build"
GOENV="/Users/CodyGuo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/opt/data/golang"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/opt/app/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/app/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/CodyGuo/go/src/tools/scan-image/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/fol

## Describe the bug
:call       CocActionAsync('rename') 
Nothing happens when call

It worked last month, but it will not work after upgrading the version today.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/10672966/87842239-800ec280-c8dd-11ea-8812-75940ba51ed8.png)

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by CodyGuo** [comment]
I didn't make any changes, I just upgraded coc.nvim and it won't work.

```shell
 "golang": {
            "command": "gopls",
            "rootPatterns": ["go.mod"],
            "trace.server": "verbose",
            "disableWorkspaceFolders": true,
            "filetypes": ["go"]
        },
```

**Comment by chemzqm** [comment]
Check output of your gopls

**Comment by CodyGuo** [comment]
It has been solved, delete coc.nvim and install it and it will work normally
