### ISSUE TITLE
vim example config question

### ISSUE THREAD

**Issue by ddl-mcetin** [neoclide/coc.nvim#2182]
I am copying and pasting the example config into `init.vim` but i can't get coc to work in neovim-- ctrl + space does nothing...am i missing something?

thanks.

**Comment by chemzqm** [comment]
Use `:verbose` command

**Comment by ddl-mcetin** [comment]
hmm.. that does not help..is that supposed to fix ctrl+space ?

**Comment by chemzqm** [comment]
No, you need read vim's help.

**Comment by ddl-mcetin** [comment]
i think i see the problem i am getting `yaml.schemas` is not allowed in my coc.config which looks like:

```
{
    "languageserver": {
      "golang": {
        "command": "gopls",
        "rootPatterns": ["go.mod"],
        "disableWorkspaceFolders": true,
        "filetypes": ["go"]
      }
    },

⚠   "yaml.schemas": {
     [json] [W] Property yaml.schemas is not allowed.
    }

  }

```

**Comment by ddl-mcetin** [comment]
any thoughts? thanks in advance

**Comment by oblitum** [comment]
You should read docs about how to configure stuff, that also requires you to read the docs on the yaml extension or server you're using.
