### ISSUE TITLE
Prompt when opening rust file

### ISSUE THREAD

**Issue by 1235452356** [neoclide/coc.nvim#2184]

**Comment by 1235452356** [comment]
![截图录屏_deepin-terminal_20200719132353](https://user-images.githubusercontent.com/52132505/87867860-b7f03580-c9c3-11ea-8354-44841c73440d.png)

**Comment by 1235452356** [comment]
I had downloaded Rust Analyzer, but always appeared

**Comment by 1235452356** [comment]
let coc_global_extensions = ['coc-snippets', 'coc-highlight', 'coc-emmet', 'coc-vetur', 'coc-tsserver', 'coc-json', 'coc-java', 'coc-css', 'coc-python', 'coc-calc','coc-powershell', 'coc-smartf', 'coc-vimlsp']

**Comment by fannheyward** [comment]
This messages are came from `coc-rust-analyzer`, try uninstall it.
