### ISSUE TITLE
vim-8.1: Press UP or DOWN key in completion hint window or List window causes insertion of ^[[B or ^[[A into the editing file

### ISSUE THREAD

**Issue by x48Jason** [neoclide/coc.nvim#2186]
I am using vim 8.1 of Ubuntu 20.04

When I use ccls as the LSP, in the completion window or the symbol reference search window, if there are a lot of items, we need to use UP or DOWN key to move to the item that we want to choose. However, if I press the UP or DOWN key constantly for a long time, the cursor will break out and insert a ^[[B or ^[[A in the editing file.

It looks like holding the UP/DOWN key will cause to insert a ^[[B or ^[[A into the currently editing file.

This issue doesn't happen in neovim, it only happens in vim.

**Comment by chemzqm** [comment]
Known issue, read F.A.Q
