### ISSUE TITLE
Permission denied on deleting the coc extensions.

### ISSUE THREAD

**Issue by sidntrivedi012** [neoclide/coc.nvim#2192]
Tried to uninstall `coc-prettier` from Vim. But it showed EACESS denied error.

When tried to do that manually, showed permission denied.

![Screenshot 2020-07-20 at 9 37 26 PM](https://user-images.githubusercontent.com/31186013/87960254-abf29980-cad1-11ea-80f2-dfbdd9997443.png)
```
~/.config/coc/extensions                                                                                                                                              at 21:37:02
❯ rm -rf node_modules
rm: node_modules/coc-rust-analyzer: Permission denied
rm: node_modules/coc-prettier: Permission denied
rm: node_modules/coc-emmet: Permission denied
rm: node_modules/coc-tsserver: Permission denied
rm: node_modules: Directory not empty
```

**Comment by fannheyward** [comment]
Can't reproduce. What's your file/folder owner of `.config/coc/extensions/node_modules`?
