### ISSUE TITLE
I got a problem as "Unknown function: coc#util#regist_extension"

### ISSUE THREAD

**Issue by MiseryForMe** [neoclide/coc.nvim#2193]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
`coc#util#regist_extension` doesn't exists at all

**Comment by sigvaldm** [comment]
I got this too, but then I also included `neoclide/coc-jedi`. I think the problem might be with `neoclide/coc-jedi`, possibly in combination with `neoclide/coc.nvim`. It seems `neoclide/coc-jedi` isn't maintained anymore, but there seems to be two alternatives: `pappasam/coc-jedi` or `fannhayworth/coc-pyright`.

**Comment by chemzqm** [comment]
`neoclide/coc-jedi` not maintained for some time, please avoid use it.
