### ISSUE TITLE
nodejs error

### ISSUE THREAD

**Issue by sleeperzjf** [neoclide/coc.nvim#2194]
When I do `:healthcheck`, I get this:
![image](https://user-images.githubusercontent.com/65698607/88022490-f4f22e80-cb61-11ea-95a2-d4a8bb37dd9e.png)
And `:mess` get this:
![image](https://user-images.githubusercontent.com/65698607/88022532-06d3d180-cb62-11ea-9056-4a420a8c1228.png)
I'm using `manjaro`, and I have `nodejs` and `npm` installed. When I run `npm install -g neovim` from terminal:
![image](https://user-images.githubusercontent.com/65698607/88022636-3e427e00-cb62-11ea-8b8a-8994dc1ff3f2.png)

**Comment by chemzqm** [comment]
Your nodejs is broken.

**Comment by sleeperzjf** [comment]
How can I fix this?
I tried to reinstall `nodejs`, but it doesn't work.
