### ISSUE TITLE
Is there a way to trigger completion without typing the prefix of variable?

### ISSUE THREAD

**Issue by VVKot** [neoclide/coc.nvim#2195]
I often find myself wishing to trigger completion without typing the prefix of the variable/property names. For example, that happens when I need to pass parameters to an unfamiliar function that accepts an object.

In the example below, `|` denotes the position of the cursor. In VSCode, I can press `<C-Space>` to get suggestions for all properties of the object that I need to pass. Is there a way to do that with coc.nvim?

```
someFunction({
  |
});
```

**Comment by fannheyward** [comment]
`inoremap <silent><expr> <c-space> coc#refresh()`.
