### ISSUE TITLE
Documentation for `g:coc_global_extensions` is Confusing

### ISSUE THREAD

**Issue by jherdman** [neoclide/coc.nvim#2196]
`g:coc_global_extensions` documentation says:

https://github.com/neoclide/coc.nvim/blob/3afe7d5d7ce087afaac39b07dea81026d8abb82a/doc/coc.txt#L1178-L1182

OK. `coc#add_extension({name}, ...)` indicates it's deprecated:

https://github.com/neoclide/coc.nvim/blob/3afe7d5d7ce087afaac39b07dea81026d8abb82a/doc/coc.txt#L1433-L1443

1. Is `coc#add_extension` really deprecated?
2. If so, should not `g:coc_global_extensions` avoid pointing to it and have expanded examples?
3.   Does `g:coc_gobal_extensions` offer similar arguments?

**Comment by oblitum** [comment]
3. `g:coc_global_extension` is just a list variable with the extensions you want.

**Comment by jherdman** [comment]
OK, so it sounds like the documentation should be updated then to not point to `coc#add_extension`.

**Comment by mirageglobe** [comment]
is there an example of using coc_global_extensions?

**Comment by fannheyward** [comment]
@mirageglobe `let g:coc_global_extensions = [ 'coc-css', 'coc-eslint', 'coc-json' ]`
