### ISSUE TITLE
:CocOpenLog opens a log file at an external log viewer outside vim

### ISSUE THREAD

**Issue by wookayin** [neoclide/coc.nvim#2197]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-nightly-88-g55b62a937
node version: v13.11.0
coc.nvim version: 0.0.78-3afe7d5d7c
coc.nvim directory: $HOME/.vim/plugged/coc.nvim
term: xterm-256color
platform: darwin
```

## Describe the bug

When I run `:CocOpenLog`, an external log viewer (e.g. Console in macOS) is opened:
![image](https://user-images.githubusercontent.com/1009873/88107430-11e42d00-cb75-11ea-8ef8-0c008751ca59.png)

At some previous versions it was opening a window inside the same vim instance.

Please note that, as a result, when the machine has no GUI/graphics servers running (e.g. under SSH sessions), nothing window would be displayed.

## Reproduce the bug

```
❯❯❯ vim -u NONE -c 'set rtp+=~/.vim/plugged/coc.nvim' -c 'source ~/.vim/plugged/coc.nvim/plugin/coc.vim'

:CocOpenLog
```

**Comment by wookayin** [comment]
Related: #2022 (but it's about a different issue)

**Comment by chemzqm** [comment]
it's expected.

**Comment by wookayin** [comment]
Are you sure? It's vim! Vim users would want to see logs in vim. As I said, please note that in headless environments where GUI log viewer is not available, it does nothing.

**Comment by chemzqm** [comment]
The problem is if you open log in current vim, the log would be changed from time to time.

**Comment by chemzqm** [comment]
I've made `:CocOpenLog` to copy filepath to system clipboard, so you can decide how to open it.

**Comment by wookayin** [comment]
> The problem is if you open log in current vim, the log would be changed from time to time.

I think one could use `autoread` feature or manual reload to refresh the log file.
https://superuser.com/questions/181377/auto-reloading-a-file-in-vim-as-soon-as-it-changes-on-disk

> I've made :CocOpenLog to copy filepath to system clipboard, so you can decide how to open it.

Thanks for reconsidering. Per the name of the command, I think directly opening files would be better (you may want to add a configuration point but I agree that it can be bit overkill). That said, the current behavior will work fine for many of the users.

**Comment by wookayin** [comment]
Actually in a headless machine (i.e. remote/ssh) clipboard might be inaccessible. Why don't we just print the path into the status message? Or make it accessible from a variable? IMHO having a customizable command about how to handle the log filepath would be best.
