### ISSUE TITLE
Connection to server got closed. Server will restart.

### ISSUE THREAD

**Issue by Shandun** [neoclide/coc.nvim#2199]
## Result from CocInfo

  1   ## versions
    1 
    2 vim version: VIM - Vi IMproved 8.1 8012269
    3 node version: v10.19.0   
    4 coc.nvim version: 0.0.78-3afe7d5d7c
    5 coc.nvim directory: /home/roro8/.vim/plugged/coc.nvim
    6 term: dumb
    7 platform: linux
    8 
    9 ## Output channel: snippets
   10 
   11 [Info 3:15:43 p.m.] Using ultisnips directories: UltiSnips /home/roro8/.config/coc/ultisnips
   12 [Info 3:15:43 p.m.] Using ultisnips python command: pyx
   13 
   14 ## Output channel: highlight
   15 
   16 [Info  - 3:15:43 p.m.] Highlight server running in node v10.19.0
   17 
   18 ## Output channel: java
   19 
   20 [Info  - 3:15:47 p.m.] Connection to server got closed. Server will restart.
   21 [Error  - 3:15:47 p.m.] /usr/lib/jvm/java-8-openjdk-amd64/bin/java exited with code: 13
   22 [Info  - 3:15:49 p.m.] Connection to server got closed. Server will restart.
   23 [Error  - 3:15:49 p.m.] /usr/lib/jvm/java-8-openjdk-amd64/bin/java exited with code: 13
   24 [Info  - 3:15:50 p.m.] Connection to server got closed. Server will restart.
   25 [Error  - 3:15:50 p.m.] /usr/lib/jvm/java-8-openjdk-amd64/bin/java exited with code: 13
   26 [Info  - 3:15:51 p.m.] Connection to server got closed. Server will restart.
   27 [Error  - 3:15:51 p.m.] /usr/lib/jvm/java-8-openjdk-amd64/bin/java exited with code: 13
   28 [Error  - 3:15:53 p.m.] Connection to server got closed. Server will not be restarted.
   29 [Error  - 3:15:53 p.m.] /usr/lib/jvm/java-8-openjdk-amd64/bin/java exited with code: 13

## Describe the bug

When I open vim to edit a java file, the language server do not work and I can not use command like <leader> gd

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**
 " Install stable build
 Plug 'neoclide/coc.nvim', {'branch': 'release'}

 "go to definition
   nmap <silent> gd <Plug>(coc-definition)
   nmap <silent> gy <Plug>(coc-type-definition)
   nmap <silent> gi <Plug>(coc-implementation)
   nmap <silent> gr <Plug>(coc-references)

  ```

## Screenshots (optional)

If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/32905893/88113368-82d01880-cb66-11ea-89d8-dbae76097adf.png)

**Comment by fannheyward** [comment]
Your Java language server is broken, how do you install it? Are you using coc-java?

Check https://github.com/neoclide/coc.nvim/wiki/Debug-language-server to get more info from language server.

**Comment by Shandun** [comment]
> Your Java language server is broken, how do you install it? Are you using coc-java?
> 
> Check https://github.com/neoclide/coc.nvim/wiki/Debug-language-server to get more info from language server.

Yes, I'm using coc-java, I finally found if we change to java 11, it's works fine, if change back to java 8, it breaks, but  our project is base on java 8 so I hope someone could fix this bug if possible. Thank you.

**Comment by jkmrto** [comment]
I was having a similar problem and the problem was related to **jdt.ls**. Hope this helps someone: https://github.com/neoclide/coc-java/issues/99#issuecomment-663856695

**Comment by baron-z** [comment]
删掉 CocConfig 中对应的文件, 例如
```"directory": ".ccls-cache"``` 删掉 ```.ccls-cache``` 文件重新打开
