### ISSUE TITLE
Auto insert brackets or parenthesis after completion

### ISSUE THREAD

**Issue by elleven11** [neoclide/coc.nvim#2201]
**Is your feature request related to a problem? Please describe.**
I would like to get brackets/parenthesis after a function call or class def and such

**Describe the solution you'd like**
After a completion, if it is appropriate to do so, parenthesis should appear, and my cursor inside the parenthesis.

**Describe alternatives you've considered**
Coming from modern mainstream text editors this feature is missing, editors like VSCode or Intellij IDEA offer such feature.

If there is already such feature, i am sorry for missing it in the wiki, but i promise I've read it.

**Comment by oblitum** [comment]
This is provided by the language server.
