### ISSUE TITLE
How to toggle parameter hint?

### ISSUE THREAD

**Issue by MaMrEzO** [neoclide/coc.nvim#2202]
How can I toggle parameters/arguments hint after its gone?
I leave parentheses for any reason, I need the hint again, How can I do that?  

![Screenshot_20200723_072631](https://user-images.githubusercontent.com/1070230/88248269-d69d4780-ccb5-11ea-8ccb-6a07a3c66a86.png)

For more detail, I used `inoremap ( ....` to brace completion, above screenshot done with completion, otherwise I cant get it to work if I type parentheses by my self.

**Comment by oblitum** [comment]
As far as I know, there is not way to trigger signatureHelp, except by typing the trigger. You should just delete and add `(` again. Also, there is not need to create any `inoremap (` for this to happen.

**Comment by oblitum** [comment]
Instead of thinking about triggering signatureHelp, you should check whether the doHover action over the function name does what you want.

**Comment by oblitum** [comment]
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-show-documentation-of-symbol-under-cursor-also-known-as-cursor-hover

**Comment by chemzqm** [comment]
`call CocActionAsync('showSignatureHelp')`

**Comment by oblitum** [comment]
ugh, completely forgot that I even had the suggested `autocmd` at `:h coc-action-showSignatureHelp@en` configured in my `.vimrc`.

**Comment by MaMrEzO** [comment]
Tnx guys, this is what I got:
```
inoremap <C-P> <C-\><C-O>:call CocActionAsync('showSignatureHelp')<cr>
```

**Comment by borisbrodski** [comment]
I think, this mapping should be included into the suggested snippet with all the other mappings in the README.md.

BUT, with `<silent>` and probably not mapped to `i_CTRL-P` (<C-P>) ;)
