### ISSUE TITLE
js自动补全完成后，光标会移动到其他位置

### ISSUE THREAD

**Issue by Joltik** [neoclide/coc.nvim#2204]
使用版本是最新的版本

## 复现方式

创建一个test.js文件
  ```
class Test extends React.Component {
	render() {
		return <View></View>;
	}
}

export default Setting;
  ```

render下输入const {view} 补全view，光标位置会移动到上一行

## 录屏
![elfgp-37kdv](https://user-images.githubusercontent.com/51736940/88271619-fd856900-cd09-11ea-82c9-1c96d56b27c7.gif)

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by Joltik** [comment]
找到了原因了，是auto-pairs这个插件的bug
