### ISSUE TITLE
update changes made in header files

### ISSUE THREAD

**Issue by MrGeorgen** [neoclide/coc.nvim#2207]
**Is your feature request related to a problem? Please describe.**

If I change the header file in c, coc does not recognize the changes. I have edit the with the corresponding `#include` statement to cause coc to reload the header file. 

**Describe the solution you'd like**

Every time I edit a header file, coc should reload the header file and update the auto completion in the sources.

**Describe alternatives you've considered**

Option a manually reload a header file.

**Additional context**

**Comment by oblitum** [comment]
coc already supports file watching events [through watchman](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions). This is responsibility of the extension you're using, or the language server. I, for example, can't reproduce your issue with coc-clangd. Once I update the header, the cpp files pick it.
