### ISSUE TITLE
CocAction('format') to have default equalprg

### ISSUE THREAD

**Issue by Moshem123** [neoclide/coc.nvim#2211]
I'd like that `call CocAction('format')` would have default behaviour of how `formatprg` acts, just like when doing `gg=G` on normal mode.

**Describe alternatives you've considered**
By default, coc-format does nothing if there's no formatter configured for the file format. By default, I think it should always use whatever is defined in `formatprg`, else, use what is defined by the file-type formatter.

**Comment by chemzqm** [comment]
No, but you can write function yourself

**Comment by Moshem123** [comment]
> No, but you can write function yourself

Sure thing. How can I set the `format` action on coc?

**Comment by applejwjcat** [comment]
> > No, but you can write function yourself
> 
> Sure thing. How can I set the `format` action on coc?

for cpp and c, coc use clang-format default to format files, so you can :
```
clang-format --style=llvm --dump-config > .clang-format 
```
to generate the format file, and you can edit it as what you want to do. Remember, for clang-format ,the format must be in the current directory or pre-parent directory. So I usually put it in my home root directory.
For other files ,you can scan the source code of coc, and look for the default format program. Then do the same thing!

**Comment by Moshem123** [comment]
Bump, I wrote my function to format a filetype,
I want to invoke the function with `<Plug>(coc-format)`, how do I set the behaviour of `coc-format`?

**Comment by Moshem123** [comment]
Maybe I'll better my question:
How can I override or set the formatter when my language server doesn't provide a formatter?
```
    autocmd FileType groovy setlocal formatexpr=MyCustomFunction()
```
How can I make `<Plug>(coc-format)` invoke `MyCustomFunction()`?
