### ISSUE TITLE
Floating window closes automatically and fast

### ISSUE THREAD

**Issue by zSucrilhos** [neoclide/coc.nvim#2214]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v12.17.0
coc.nvim version: 0.0.78-56999634f4
coc.nvim directory: /home/zsucrilhos/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Output channel: snippets

[Info 9:21:46 PM] Using ultisnips directories: UltiSnips /home/zsucrilhos/.config/coc/ultisnips
[Info 9:21:48 PM] Using ultisnips python command: pyx

## Output channel: tsserver

[Info  - 9:21:48 PM] Forking TSServer
PATH: /home/zsucrilhos/.local/bin/:/home/zsucrilhos/.gem/ruby/2.7.0/bin/:/home/zsucrilhos/.cargo/bin/:/home/zsucrilhos/_my-scripts:/home/zsucrilhos/.local/bin/:/home/zsucrilhos/.gem/ruby/2.7.0/bin/:/home/zsucrilhos/.cargo/bin/:/home/zsucrilhos/_my-scripts:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl 
[Info  - 9:21:48 PM] Started TSServer
{
  "path": "/home/zsucrilhos/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.9.5",
    "version": "3.9.5"
  }
}

## Output channel: highlight

[Info  - 9:21:48 PM] Highlight server running in node v12.17.0

## Output channel: eslint

[Info  - 9:21:48 PM] ESLint server running in node v12.17.0
[Info  - 9:21:56 PM] ESLint library loaded from: /usr/lib/node_modules/eslint/lib/api.js


```

## Description of the bug

The "completion" floating window closes automatically more or less 0.5 seconds after it opens
I can't go through the options or even accept the currently selected option. There is no time.

## Reproduce the bug

I don't know how to reproduce it exactly because it started all of a sudden, 
It was working normally, i instaled coc-tsserver and, looking at the git repo, i saw this:

```
" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

```
I went to test it and it the problem started. Even after removing the text above from my neovim config,
it stills doesn't work.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

This didn't work either, it doesn't load coc...

## Screenshots (optional)

I recorded two videos:
I was recording this to show to a friend that i'm trying to bring to vim (hehe) as he uses VSCode.

Normal working, as it should:
https://www.youtube.com/watch?v=7vljkq_rszQ

After editing the config file, as it is now:
https://www.youtube.com/watch?v=d9Y6JW4xbKE

*Things i tried:*

- Reinstalling all my plugins by deleting the plugged folder (plug.vim) and installing them again.
- To reboot my computer after reinstalling the plugins
- Updating all my plugins by running :PlugInstall and :PlugUpdate
- And lastly i tried uninstalling all coc's extensions i use and installing them again

*Thanks for the amazing software and for your attention!*

**Comment by chemzqm** [comment]
It's your popup menu closed automatically, I can't make it happen, please try minimal vimrc.
You need to modify this line
```
set runtimepath^=/path/to/coc.nvim
```

**Comment by zSucrilhos** [comment]
Hi! Sorry for the delay, i was quite busy lately. So, i tried it with the minimal vimrc, and this time set the path to coc correctly, sorry for not seeing it before. It worked, the autocomplete window doesn't close.

![image](https://user-images.githubusercontent.com/37763819/89598344-f9416b80-d832-11ea-9547-0711465f4591.png)

**Comment by fannheyward** [comment]
It's likely that some other plugins conflict. Try to remove other plugins one by one to find it.

**Comment by zSucrilhos** [comment]
Ah ok, i don't think so, because i have not added nor removed any plugins in the last 6 months or so, but i'll take a look. Thanks for your attention.

**Comment by shobhitsinghal624** [comment]
@fP4rad0x Please post the solution if you found one.

**Comment by chemzqm** [comment]
> @fP4rad0x Please post the solution if you found one.

Try upgrade coc.nvim and use minimal vimrc.

**Comment by shaypal5** [comment]
Started happening to me as well, all of a sudden, and updating coc.nvim didn't help.
