### ISSUE TITLE
Repeated information in the floating window on hover.

### ISSUE THREAD

**Issue by Infi-Knight** [neoclide/coc.nvim#2215]
## Describe the bug

Repeated information in the floating window on hover.

## Reproduce the bug

I haven't modified the default settings related to suggest window.  Other than that my dotfiles are at: 
[github.com/Infi-Knight/dotfiles](https://github.com/Infi-Knight/dotfiles)

## Screenshots (optional)

As you can see, the description about `div` is being shown two times.
<img width="429" alt="Screen Shot 2020-07-29 at 2 05 09 PM" src="https://user-images.githubusercontent.com/20504781/88777567-fbf1f000-d1a4-11ea-8c57-b7e22543d884.png">

**Comment by chemzqm** [comment]
`:CocList services`
