### ISSUE TITLE
yarn install --frozen-lockfile fails because of unrelated npm package

### ISSUE THREAD

**Issue by antoinemadec** [neoclide/coc.nvim#2216]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-606-g409a1dcdc
node version: v10.21.0
coc.nvim version: 0.0.78
coc.nvim directory: /home/antoine/dotfiles/.vim/plugins/coc.nvim
term: xterm-256color
platform: linux

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /home/antoine/dotfiles/.vim/plugins/coc.nvim
resolved root: /home/antoine/dotfiles/.vim/plugins/coc.nvim
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Output channel: prettier


## Output channel: snippets

[Info 1:29:38 PM] Using ultisnips directories: UltiSnips /home/antoine/.config/coc/ultisnips
[Info 1:29:38 PM] Using ultisnips python command: pyx

## Output channel: highlight

[Info  - 1:29:38 PM] Highlight server running in node v10.21.0
```

## Describe the bug

I installed this package in my home directory:
```sh
> npm list
/home/antoine
└── @types/p5@0.9.1
```

when running ```yarn install --frozen-lockfile``` it creates the following errors:
```log
$ tsc -p tsconfig.json
../../../../node_modules/@types/p5/index.d.ts:88:57 - error TS2304: Cannot find name 'HTMLElement'.

88     constructor(sketch: (...args: any[]) => any, node?: HTMLElement);
                                                           ~~~~~~~~~~~

../../../../node_modules/@types/p5/lib/addons/p5.dom.d.ts:149:28 - error TS2304: Cannot find name 'AudioNode'.

149         connect(audioNode: AudioNode | object): void;
                               ~~~~~~~~~
...
```

## Reproduce the bug

1. ```npm install @types/p5```
2. ```cd <coc.nvim>```
3. ```yarn install --frozen-lockfile```

**By just adding "dom" to the tsconfig.json "lib" field, it fixes the issue.**

Could you please fix this or point me to a way not to look at **@types/p5** during **yarn install**?

Thanks in advance!

**Comment by chemzqm** [comment]
Avoid install node modules in your home

**Comment by antoinemadec** [comment]
@chemzqm that seems a bit drastic. Is there a way to tell Coc.nvim's yarn install not to pick up modules in my home instead?

**Comment by oblitum** [comment]
@antoinemadec build it outside of home?

**Comment by antoinemadec** [comment]
@oblitum , I am very new to JS, so I am certainly missing something here.
I actually ran ```yarn install``` in ```~/.vim/plugins/coc.nvim```.
Are you saying ```yarn install``` recursively look for ```node_modules``` dir in the directories above the install dir?

**Comment by oblitum** [comment]
@antoinemadec I'm not sure about `npm` as I don't use it entirely, I'm just using `yarn` for everything. When I wish to install packages globally for _my user_, I do `yarn global add`, which put them in a specific store at `~/.config/yarn/global/node_modules`, this is not the same as considering `~` as a project folder to put modules into. If that's what you're doing, then your `~` will be a project folder.
