### ISSUE TITLE
not an issue-how can i set a suggest.noselect to false

### ISSUE THREAD

**Issue by Qwerty2o** [neoclide/coc.nvim#2223]
I'm sorry i already opened a ticket but it was closed before i could say anything.
also not seeing a manual about those things anywhere.

I'm trying to enable autoselect on first completion (so that the first option will automatically be pointed at)
I've read that I could set suggest.noselect to false to resolve this but didn't quite get how to do that.

Or at all, how to enable and disable certain suggestions. looked for it and it doesn't seems to be explained anywhere.

Also been suggested to use mapping (inoremap). I took a guesss and put it on coc.vim, it just gave an error so I guess I made a mistake there.
any guidance would be appreciated.

**Comment by fannheyward** [comment]
Open `coc-settings.json` by `CocConfig`. Check out the wiki page for more informations.
