### ISSUE TITLE
x EINVAL: invalid argument, read

### ISSUE THREAD

**Issue by amebrahimi** [neoclide/coc.nvim#2225]
## Result from CocInfo
```
## versions

vim version: NVIM v0.4.3
node version: v12.16.1
coc.nvim version: 0.0.78-0ff42027ff
coc.nvim directory: C:\Users\amebrahimi\AppData\Local\nvim-data\plugged\coc.nvim
term: vtpcon
platform: win32
```

## Describe the bug

When I want to install for example `coc-json` I get this error `coc-json EINVAL: invalid argument, read`. My operating system is `Windows10`. 

and this is my minified version of vimrc:
```
set nocompatible
set runtimepath^=C:\Users\amebrahimi\AppData\Local\nvim-data\plugged\coc.nvim\plugin
filetype plugin indent on
syntax on
set hidden

call plug#begin(stdpath('data').'/plugged')
" Stable version of coc
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/12514657/89126473-2c19f580-d4fb-11ea-8b6b-dbc2f459addb.png)

**Comment by chemzqm** [comment]
Hover that line to get full messages

**Comment by amebrahimi** [comment]
Here is the full message

![image](https://user-images.githubusercontent.com/12514657/89368706-6d73f600-d6f1-11ea-93aa-972268682d15.png)

**Comment by amebrahimi** [comment]
Here is the full message

![image](https://user-images.githubusercontent.com/12514657/89368782-97c5b380-d6f1-11ea-92fd-1981292796f4.png)

**Comment by fannheyward** [comment]
https://stackoverflow.com/questions/47087759/getting-error-einval-invalid-argument-read-for-npm-install-save-dev-esli

**Comment by amebrahimi** [comment]
I've seen these but they didn't help me. When I install for example `npm i coc-json` or `yarn add coc-json` from command line everything works completely fine. But when I come and try to download these packages via CocInstall this error occurs.

**Comment by chemzqm** [comment]
The command used by coc.nvim is `npm install --ignore-scripts --no-lockfile --production`.

Should be problem of your npm, try configure `npm.binPath` to `yarn`
