### ISSUE TITLE
[Question] Black background in suggestions?

### ISSUE THREAD

**Issue by chinleung** [neoclide/coc.nvim#2228]
Hi,

I'm new to coc.nvim and I'm having issues when displaying the suggestions.

This is a screenshot of what I get:
![image](https://user-images.githubusercontent.com/19669331/89300277-f299d500-d635-11ea-9ed9-e1009e594c63.png)

Is there a way for me to remove the black background in the right box?

**Comment by chemzqm** [comment]
`:h coc-highlights`
