### ISSUE TITLE
Add an option to disable update prompts

### ISSUE THREAD

**Issue by yardnsm** [neoclide/coc.nvim#223]
**Is your feature request related to a problem? Please describe.**

Currently, the plugin will suggest to update an extension to a new version if available:

```
a new version: 1.1.16 of coc-tsserver available, update? (y/n)
```

While this feature is very useful sometimes, I sometimes interrupts me when I'm working.

**Describe the solution you'd like**

I would suggest adding an option to disable this kind of behaviour, or maybe even to set an interval for it (for examples, check for updates every 10 days). I'm not sure where the preferred place would be to set it (in the `coc-settings.json` file or in Vim's runtime files).

Thanks!

**Comment by chemzqm** [comment]
It checks once everyday.

**Comment by yardnsm** [comment]
What about an option to completely disable this check?

**Comment by dibusure** [comment]
same problem
