### ISSUE TITLE
Using :call CocActionAsync('rename') results in timeout

### ISSUE THREAD

**Issue by lamabro23** [neoclide/coc.nvim#2232]
# Result from CocInfo
## versions
```
vim version: VIM - Vi IMproved 8.2 8020905
node version: v12.16.3
coc.nvim version: 0.0.78-0ff42027ff
coc.nvim directory: /home/duradnik/.vim/plugged/coc.nvim
term: dumb
platform: linux
```

## Output channel: java
https://gist.github.com/lamabro23/89a47107863e1263875bfb5ab81e022c

## Describe the bug

When using `nnoremap <Space>le :call CocActionAsync('rename')` (I also tried `nmap <Space>le <Plug>(coc-rename)`) I'm getting this message `[coc.nvim] Error on applyEdits: Create document file:///home/duradnik/wo/ija-project/src/main/java/ija/project/Data.java timeout after 1s.` even after removing all plugins except coc.nvim from vim. Profiling vim did not show any time-consuming activity. 
Result of profiling: https://gist.github.com/lamabro23/04431ac1e62720ab1e6d485d7031c45a

## Reproduce the bug

- Create file `.vimrc` with：

  ```vim
  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()
  nnoremap <silent> <Space>le :call CocActionAsync('rename')<CR>
  ```
- Open file in a project structure like this
```
 .
├── build.xml
├── data
│   └── map.yml
├── lib
│   └── get-libs.sh
├── README.md
└── src
    └── main
        ├── java
        │   └── ija
        │       └── project
        │           ├── Closure.java
        │           ├── Coordinate.java
        │           ├── Data.java
        │           ├── Delay.java
        │           ├── Detour.java
        │           ├── Drawable.java
        │           ├── LayoutController.java
        │           ├── Line.java
        │           ├── Main.java
        └── resources
            ├── app-layout.fxml
            └── style.css
```
- Use \<Space\>le to change the name of a variable in all files of the project.

**Comment by chemzqm** [comment]
Try minimal vimrc.
