### ISSUE TITLE
Question about how this plugin works

### ISSUE THREAD

**Issue by unphased** [neoclide/coc.nvim#2234]
Hi I'm looking to do some custom scripting and I would like to write it in JS. I noticed that this plugin uses its own fork of neovim's node-client (seems like it is extended to support vim 8). 

I noticed that node-client has you install the package from npm globally so that your nvim runs it from there. However this is clearly not necessary for operation of coc.nvim. So there is some workaround for that. I was wondering if it makes sense to possibly use a similar thing. 

Anyway it has turned into a really difficult thing to figure out how to get a minimal example working. I'd like to just do such things as write out the most recent vim search to a file, read the contents of the file to set state in vim/nvim, etc.  I am currently getting that stuff done using `:python` but I think python's days are limited so I'd like to start doing more of my vim scripting via node.js.

I am reading the instructions for node-client and I'm not able to figure out what the `rplugin/node` directory that it's talking about is. 

I also noticed that a lot of coc's functionality is done through a simple clean interface to nvim/vim state, which is really great and I want to have that. However I do not know where to even start if I want to first place these js/ts files in my .nvim/ repo and  most importantly I am looking for documentation that explains how the entry point to wire it up is. I have also been looking at this: https://learnvimscriptthehardway.stevelosh.com/chapters/53.html but it is not clear that autoload is the mechanism being used?

**Comment by unphased** [comment]
My bad, now I've found https://neovim.io/doc/user/remote_plugin.html which is probably something I need to read.

**Comment by unphased** [comment]
Now I'm even more confused: 

```
❯ cat ~/.local/share/nvim/rplugin.vim 
" perl plugins


" node plugins


" python3 plugins
call remote#host#RegisterPlugin('python3', '/Users/slu/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete', [
      \ {'sync': v:false, 'name': '_deoplete_init', 'type': 'function', 'opts': {}},
     \ ])


" ruby plugins


" python plugins


```

coc is not listed here

**Comment by chemzqm** [comment]
It's not remote plugin but make use of lower level job api

**Comment by unphased** [comment]
I figured some stuff out. So it looks like coc is doing a "nonstandard" way of running node in a job. this is `jobstart` in nvim and `job_start` for vim. The smoking gun was I added a `echom` in `client.vim` in `s:start()` showing me node is being spawned.

Anyway I don't understand why the "standard" way of starting node is so insanely slow. See this post I made: https://www.reddit.com/r/neovim/comments/i6zf0u/neovim_node_remoteplugin_adds_2_seconds_to/

**Comment by unphased** [comment]
> It's not remote plugin but make use of lower level job api

Yep! Ah damn I did not see the notification. Worked it out anyway. Thanks!

Seems like the plugin API remains very useful and easy to use once the code gets started as a job.

**Comment by chemzqm** [comment]
It support vim as well and no need for updateRemotePlugins on api update

**Comment by unphased** [comment]
Yeah I don't understand what the point of the remote-plugin functionality in neovim is. node startup is very very slow. It blocks the main thread for 2 full seconds on my MacBook. Async jobs are definitely the way to go.

**Comment by chemzqm** [comment]
Detect of node-client module could be slow, it  can be avoided
