### ISSUE TITLE
Is there a way to display actions in floating window in neovim, just like a popup in vim?

### ISSUE THREAD

**Issue by VVKot** [neoclide/coc.nvim#2235]
**Is your feature request related to a problem? Please describe.**
Neovim displays available actions at the bottom of the buffer when I call `<Plug>(coc-codeaction)`.

**Describe the solution you'd like**
It would be nice to have it as pop-up in the center of the screen instead. It is much easier to work with since the line you're calling action on is like positioned roughly in the center anyway; so, you don't have to move your eyes all the way down.

**Describe alternatives you've considered**
coc-fzf already provides a fzf-based solution for lists. I don't think it is worth firing the fzf for actions though, picking action by pressing a number is much more convenient.

**Additional context**
Maybe there some switch already to do that?

**Comment by oblitum** [comment]
Check [coc-actions](https://github.com/iamcco/coc-actions).
