### ISSUE TITLE
Replace `yarn` command with `yarnpkg`

### ISSUE THREAD

**Issue by GalLalouche** [neoclide/coc.nvim#2236]
**Is your feature request related to a problem? Please describe.**
`yarn` conflics with hadoop `yarn` if the former is placed before the latter in `PATH`, which leads to confusing errors for first-timers.

**Describe the solution you'd like**
Replace with `yarnpkg`, so there are no conflicts.

**Comment by chemzqm** [comment]
`yarnpkg` could also be wrong, use release branch is recommended, which doesn't need yarn
