### ISSUE TITLE
CocInstall requires listing the extensions and is not instant if extensions already installed

### ISSUE THREAD

**Issue by smhc** [neoclide/coc.nvim#2237]
**Is your feature request related to a problem? Please describe.**

I would like to install extensions from a shell as part of an environment setup script. I expect this process to take a while the first time it is run, but on subsequent runs I would expect it to finish virtually instantly. I would also like to install all extensions from "g:coc_global_extensions" without having to list them all. The below is from the wiki doc:

> Note you can add extension names to the g:coc_global_extensions variable, and coc will install the missing extensions for you on server start.
> To install extensions with shell script, use command like:
> vim -c 'CocInstall -sync coc-json coc-html|q'

**Describe the solution you'd like**

I would like to run "CocInstall -sync" and have it install all extensions from 'g:coc_global_extensions', without needing to specify them all. If the extensions are already installed this should complete almost immediately.

**Describe alternatives you've considered**

Running 'vim -c 'CocInstall -sync coc-json coc-html|q' will take a long time to complete, even if the extensions are installed.

**Comment by chemzqm** [comment]
Use `CocUpdate` for update extension

**Comment by oblitum** [comment]
Or `:CocUpdateSync`.

**Comment by smhc** [comment]
That doesn't install the plugins if they don't exist. It also updates them if they are already installed.

I want to install them synchronously if they don't exist, but leave them alone if they do exist. Similar to how "PlugInstall" works for vim-plug. Neither :CocUpdate or :CocUpdateSync does this.

I want to have an environment setup script that deploys the extensions synchronously as part of setup. For virgin installs this will need to install them all up front. But for installs where the extensions are already installed (e.g on an NFS mount - but currently broken) it should do nothing, and it should nothing fast.

I currently don't see any option that does a "PlugInstall" equivalent.

**Comment by chemzqm** [comment]
You can write your own shell script to install extensions
