### ISSUE TITLE
Please, provides support for Arduino and AVR with coc-extension

### ISSUE THREAD

**Issue by MuhammadMouradG** [neoclide/coc.nvim#2238]
**Is your feature request related to a problem? Please describe.**
I tried to use `coc-clangd` but it was complicated to adjust and also when I tried to compile the project. I think it misses a lot things to be acceptable for using as a development tool for AVR (Arduino is a product that uses an AVR microcontrollers and the name of the product varies according to the type of used AVR microcontroller. However, Arduino has a lot of package that may be simplified the implementation of extension).

**Describe the solution you'd like**
I suggest `coc-avr` or at least `coc-arduino` extension for support AVR programming which include Arduino support. There is a VS Code plugin for arduino [vscode-arduino](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino)

**Comment by phaalonso** [comment]
I need it too

**Comment by pvonmoradi** [comment]
Did you provide a `compile-commands.json` in the project directory to clangd?

**Comment by purofle** [comment]
I need it too
