### ISSUE TITLE
[Documentation] mention yarn

### ISSUE THREAD

**Issue by gustaphe** [neoclide/coc.nvim#2242]
I'm not sure if I'm missing something, but I've installed this plugin on two systems (both windows and arch linux), and both times had to install `yarn` for it to work. But the documentation doesn't mention yarn, and without it some of the installation steps silently fail.

**Comment by fannheyward** [comment]
Checkout https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#requirements

**Comment by oblitum** [comment]
yarn/npm is only needed if built from sources or using extensions.

**Comment by gustaphe** [comment]
Okay, apparently installing coc with Vundle constitutes building from source.

**Comment by oblitum** [comment]
@gasuketsu only if you're installing from master branch. You need to use release branch which is already built. You have to check with your plugin manager whether it's possible to set specific branches to pull.

**Comment by gustaphe** [comment]
Definite pebcac. Unfortunately Vundle has no such functionality (it's been requested though).

**Comment by wadkar** [comment]
@gustaphe : If I may recommend, a drop-in replacement would be [vim-plug](https://github.com/junegunn/vim-plug) , that _should_ work by simply `%s/Plugin/Plug/` your vimrc. It does provide you with the "advance" option of specifying a specific branch (among other things - see the docs).

**Comment by gustaphe** [comment]
Thank you, that was actually way less painful than I imagined it would be.
