### ISSUE TITLE
Cannot setup coc.nvim to work properly with Linux kernel headers

### ISSUE THREAD

**Issue by ang1337** [neoclide/coc.nvim#2243]
Hello.

I cannot setup coc.nvim to work properly with Linux kernel headers (such as <linux/init.h>, <linux/list.h> etc.). The error message is:
`'blabla kernel header' file not found [clang: pp_file_not_found]`

I've tried to set path manually via `set path+=path/to/kernel/headers` but it didn't work for me.
The kernel modules compile and execute as expected, but no autocompletion and snippets during actual code writing due to above mentioned error.
Thank you in advance.

**Comment by fannheyward** [comment]
You need to setup `compile_commands.json` for your project.

**Comment by oblitum** [comment]
Also check about `compile_flags.txt`.
