### ISSUE TITLE
I can't use ocaml-language-server, I need help

### ISSUE THREAD

**Issue by jingkai1** [neoclide/coc.nvim#2247]
My coc-settings as follows.
      "ocaml": {
       "command": "ocaml-language-server",
       "args": ["--stdio"],
       "filetypes": ["ocaml", "reason"]
     }

when I open a .ml file , 
[coc.nvim] Double check your path or try configuring "reason.path.ocalmerlin" under "User Settings" .
I'm a novice in ocaml, and I don't know how to do it.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by tankorsmash** [comment]
Did you figure this out? I think I'm having a semi-related issue with ocamllsp/ocaml-language-server silently not working, with no output to :CocInfo when hovering.
