### ISSUE TITLE
Proper handling of removing entries from g:coc_global_extensions

### ISSUE THREAD

**Issue by xaviergmail** [neoclide/coc.nvim#2251]
## versions

vim version: NVIM v0.4.4
node version: v12.18.2
coc.nvim version: 0.0.78-bdd9a9e140
coc.nvim directory: /home/xavier/.dotfiles/vim/.vim/plug-install/coc.nvim
term: rxvt-unicode-256color
platform: linux

## Output channel: highlight

[Info  - 10:55:58 AM] Highlight server running in node v12.18.2

## Describe the bug

Removing an extension from `g:coc_global_extensions` does not disable / uninstall it

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  let g:coc_global_extensions = [ 'coc-css', 'coc-cord']
  ```

1. Start (neo)vim with command: `vim -u mini.vim`
2. Start vim and wait for coc to install the extensions
3. Close vim and edit the mini.vim to remove `'coc-cord'` from  `g:coc_global_extensions`
4. Start vim back up and notice that coc-cord still gets loaded

**Comment by fannheyward** [comment]
This is expected, extensions removed from `g:coc_global_extensions` will not be uninstalled.

**Comment by oblitum** [comment]
I think it could be useful if this variable is set to only keep the extensions that are listed by it to be installed?

**Comment by chemzqm** [comment]
Use extensions list is preferred, it provides more actions.
