### ISSUE TITLE
trivial problem with modeline and example vim config

### ISSUE THREAD

**Issue by dahe3141** [neoclide/coc.nvim#2252]
In the example config, there is a comment line that would trigger modeline error. 
`" Requires 'textDocument/selectionRange' support of LS, ex: coc-tsserver`
It took me an hour to debug since I did not understand what modeline is.
Simply remove the colon after `ex:` fixed it.
With it, nvim would complain `E518 Unknown option: coc-tsserver`.
Thank you for supporting this awesome software.
```
## versions

vim version: NVIM v0.4.3
node version: v14.5.0
coc.nvim version: 0.0.78-bdd9a9e140
coc.nvim directory: /home/markov/.config/nvim/plugged/coc.nvim
term: alacritty
platform: linux
```

**Comment by fannheyward** [comment]
Can't reproduce with `" Requires 'textDocument/selectionRange' support of LS, ex: coc-tsserver` in my init.vim.

**Comment by chemzqm** [comment]
It should not trigger mode line.
