### ISSUE TITLE
Peek/preview definition?

### ISSUE THREAD

**Issue by pianocomposer321** [neoclide/coc.nvim#2253]
I am aware of `coc_user_config['coc.preferences.jumpCommand'] = ':vsp'`, but I am looking for something more like VSCode:

![image](https://user-images.githubusercontent.com/54072354/90343031-912d1b00-dfd2-11ea-9102-e842787f6bfa.png)

Is there a way to do this with coc.nvim?

**Comment by fannheyward** [comment]
Try something like this: `nnoremap <silent><nowait> <space>d  :call CocAction('jumpDefinition', v:false)<CR>`

`<space>-d` will open the split view to show definition.

**Comment by wookayin** [comment]
@pianocomposer321 This is my approach (including screenshot): https://github.com/wookayin/dotfiles/commit/c64b4f34c1f8051d4e0feb15eb3d4e57d7eab475

Please note that having `v:false` as openCommand will show coc list a split view. I wanted to have a floating window instead.
