### ISSUE TITLE
How to change the coc hinting colors.

### ISSUE THREAD

**Issue by apoorv569** [neoclide/coc.nvim#2257]
I have `coc` installed for many languages, including `coc-python`, the hint/error that `coc` shows, has very weird color scheme, how do I change the color scheme for `coc`? I couldn't find anything in the documentation. Right now it looks like this(Red on pink)

![2020-08-18_00-59](https://user-images.githubusercontent.com/53279454/90437251-aea3d700-e0ef-11ea-9bd5-4ddef9e0a763.png)

This is not very clear to view. I'm using the `monokai` color scheme, if it matters.

**Comment by oblitum** [comment]
`:h CocErrorHighlight@en`
