### ISSUE TITLE
Is it possible to map <Plug>(Coc-format) to a key mapping?

### ISSUE THREAD

**Issue by mesa123123** [neoclide/coc.nvim#2262]
I know from the reccomended config that you can updated a selected block of code using <leader>f but would there be a way to update the entire buffer using something like <leader>fa?

I've already tried writing in something like `<leader>fa <Plug>(coc_format)` but it doesn't seem to work?

Is this a possible feature?

**Comment by fannheyward** [comment]
It's `coc-format`, not `coc_format`.
