### ISSUE TITLE
Disable highlight symbol after call CocAction('highlight')

### ISSUE THREAD

**Issue by DedSecer** [neoclide/coc.nvim#2265]
I've copied `autocmd CursorHold * silent call CocActionAsync('highlight')` from readme.md to my init.vim .
So is there any way to disable this highlight symbol?

**Comment by chemzqm** [comment]
Move your cursor.

**Comment by DedSecer** [comment]
I mean sometime I don't want it to highlight the symbol under the cursor.

**Comment by DedSecer** [comment]
I mean sometime I don't want it to highlight the symbol under the cursor.

**Comment by DedSecer** [comment]
I mean sometime I don't want it to highlight the symbol under the cursor.

**Comment by DedSecer** [comment]
I mean sometime I don't want it to highlight the symbol under the cursor.

**Comment by DedSecer** [comment]
I mean sometime I don't want it to highlight the symbol under the cursor.

**Comment by DedSecer** [comment]
I mean sometime I don't want it to highlight the symbol under the cursor.

**Comment by DedSecer** [comment]
I mean sometime I don't want to highlight symbol under the cursor,but sometime I want.Should I edit my init.vim each time?

**Comment by oblitum** [comment]
> Should I edit my init.vim each time?

@DedSecer write vimscript to deactivate/activate the `autocmd`.

**Comment by DedSecer** [comment]
Isn't there a more convenient way?

**Comment by oblitum** [comment]
@DedSecer no, but that is pretty trivial, as much as the example conf you copied. Notice that what you copied already, also isn't builtin, you just copied & pasted suggested vimscript configuration.

**Comment by DedSecer** [comment]
I've define commands like this :+1: `
command! HlCsHold autocmd CursorHold * silent call CocActionAsync('highlight')
command! NoHlCsHold autocmd! CursorHold * silent call CocActionAsync('highlight')
`
But the autocmd! just stio catching symbol under the cursor,the highliht symbol are still there,how to disable it?

**Comment by oblitum** [comment]
Please read vim help, `!` is not for that purpose, if you don't know basic vimscript maybe better avoid it.

**Comment by DedSecer** [comment]
Sorry,I've read help just now,i think this may work:
`augroup Coc`
`command! HlCsHold autocmd Coc CursorHold * silent call CocActionAsync('highlight')`
`command! NoHlCsHold autocmd! Coc `
It has a behaviour previous.

**Comment by DedSecer** [comment]
I've  found a solution:

```
augroup CocHighightText

command! HlCsHold call HlcsHold() 
command! NoHlCsHold call NoHlcsHold()

func! HlcsHold()
    hi default link CocHighightText CursorColumn
    autocmd CocHighightText CursorHold * silent call CocActionAsync('highlight')
endfun 

func! NoHlcsHold()
    hi default link CocHighightText None
    autocmd! CocHighightText
endfun 
```

**Comment by nomasprime** [comment]
> Please read vim help, `!` is not for that purpose, if you don't know basic vimscript maybe better avoid it.

Boo!

Well done @DedSecer 👏
