### ISSUE TITLE
The organization of imports is not ordered properly.

### ISSUE THREAD

**Issue by yassinebridi** [neoclide/coc.nvim#2276]
**Is your feature request related to a problem? Please describe.**
Whenever i organize the imports in a react based application, the order of the imports is always not the one that is expected,
for example to have the imports from the react library first, then the imports from the local components last, as it would be for vs code.

**Describe the solution you'd like**
For the imports to be ordered like what vs code have, or have an option to reverse the order of the imports

**Comment by chemzqm** [comment]
Could be problem of different typescript version, I have same result with VSCode.
