### ISSUE TITLE
Wiki: text is cut off in Rust section?

### ISSUE THREAD

**Issue by Ran4** [neoclide/coc.nvim#2278]
The wiki says this under the Rust section:

`It's necessary to rustup component add rust-src and build rust-analyzer from sources (just cargo install-ra --server).`

What does `cargo install-ra --server` mean?

**Comment by fannheyward** [comment]
`cargo install-ra --server` in rust-analyzer source folder will install rust-analyzer server. Checkout rust-analyzer's wiki for more information.

**Comment by Ran4** [comment]
rust-analyzer doesn't seem to have a wiki? There's no github wiki, no link to a wiki on https://rust-analyzer.github.io/ and googling gets me nowhere.

These things might be easy for the autocompletion tooling developers but it's *very* confusing to end-users!

**Comment by fannheyward** [comment]
https://github.com/rust-analyzer/rust-analyzer/blob/master/.cargo/config#L3
https://rust-analyzer.github.io/manual.html#building-from-source

**Comment by fannheyward** [comment]
rust-analyzer's README used to provide how to build from source https://github.com/rust-analyzer/rust-analyzer/blob/9f68f7acf2e4cae65122cae072bae2386f48bff1/README.md#language-server-quick-start

I've changed coc wiki page document.

**Comment by Ran4** [comment]
Thank you, that solved my problem!
