### ISSUE TITLE
Duplicated diagnostics after undo

### ISSUE THREAD

**Issue by xuanduc987** [neoclide/coc.nvim#2279]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8021058
node version: v12.18.3
coc.nvim version: 0.0.78
coc.nvim directory: /Users/d.xuan.nghiem/.vim/plugged/coc.nvim
term: dumb
platform: darwin

```

## Describe the bug

After undo, vim restore the textprop Coc used to highlight error, and then, the result of lsp diagnostic came and Coc add the same textprop again.

## Reproduce the bug

- Open file and create an error -> coc highlight error with textprop
- Fix the error -> no highlight
- In normal mode, press <kbd>u</kbd> to undo -> the error got highlighted
- Fix the error again -> the highlight got stuck

## Screenshots (optional)

![coc](https://user-images.githubusercontent.com/1186411/91260008-58e3c480-e7aa-11ea-9a30-a72336f28c9d.gif)

**Comment by fannheyward** [comment]
Reproduced with vim, works as expected in Neovim. I'll test your PR ASAP.
