### ISSUE TITLE
Handle modeline processing on User events

### ISSUE THREAD

**Issue by jamedranoa** [neoclide/coc.nvim#2285]
**Is your feature request related to a problem? Please describe.**

Currently the `User` events are triggering modeline processing whenever the user had defined a listener, I'm not sure if this is intended, but in my case is affecting my workflow, I listen to `User CocStatusChange` to update my status line and I also use modelines on some files to define folds, so after opening folds and doing some work a `CocStatusChange` event will close all my folds.

**Describe the solution you'd like**
- If intended a brief mention in the docs would be nice so users can set `nomodline` in ther modlines as an alternative
- if not intended just adding <[nomodelines](https://github.com/vim/vim/blame/e7b1ea0276cc83cd5c612f3189a174a60d57b5ed/runtime/doc/autocmd.txt#L1476)> in [here](https://github.com/neoclide/coc.nvim/blob/9f9d8a32c4669ba6895e801812c60153b94e22dd/autoload/coc/util.vim#L981) could fix the issue.

I would be happy to make a PR if any of the two solutions seems like a good idea. 
This looks like the possible cause of this issue too https://github.com/neoclide/coc.nvim/issues/1817.

Note: Thank you so much for this plugin! I use it everyday :)

**Comment by chemzqm** [comment]
Fixed by eb3b8e9d
