### ISSUE TITLE
Question: how to trim leading/trailing newlines of a float window of LSP output?

### ISSUE THREAD

**Issue by Congee** [neoclide/coc.nvim#2286]
Many LSPs return texts with leading/trailing newlines. Can anyone help to tell a way of trimming them?
![image](https://user-images.githubusercontent.com/2083950/91452091-31ddcf00-e84c-11ea-9b18-1093023d14ee.png)

**Comment by fannheyward** [comment]
Language server's issue, should be trimmed by LS.

**Comment by Congee** [comment]
Of course I know LSP server should trim output, but many implementations don't do it. I am really disappointed about the attitude

**Comment by chemzqm** [comment]
These're intended padding to make floating window looks better.
