### ISSUE TITLE
Coc-java can not start up with openjdk-8.0

### ISSUE THREAD

**Issue by Shandun** [neoclide/coc.nvim#2287]
## Result from CocInfo
![Screenshot from 2020-08-27 10-20-11](https://user-images.githubusercontent.com/32905893/91474859-a8300080-e84f-11ea-9c34-8001f7be393c.png)

## Describe the bug

![Screenshot from 2020-08-27 10-20-38](https://user-images.githubusercontent.com/32905893/91474879-aebe7800-e84f-11ea-8899-b872a591f3dc.png)
the server can not be started with choose to the jdk-8.0 home folder,if we change to 11, it is ok, but we use 8 as support for our project for a long time, hope 8 can be included in support list.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**
![Screenshot from 2020-08-27 10-21-51](https://user-images.githubusercontent.com/32905893/91474966-c564cf00-e84f-11ea-9a40-b62aac087a8a.png)
the server can not be started with choose to the jdk-8.0 home folder,if we change to 11, it is ok, but we use 8 as support for our project for a long time, hope 8 can be included in support list.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
JDT Lang Sever issue. 

- https://github.com/neoclide/coc-java/issues/106
- https://github.com/neoclide/coc-java/issues/99#issuecomment-663856695
