### ISSUE TITLE
Integration with VSCode Extension Host?

### ISSUE THREAD

**Issue by colinxs** [neoclide/coc.nvim#2288]
**Is your feature request related to a problem? Please describe.**

Currently, coc.nvim depends on coc extensions (e.g. coc-julia) to provide language support. Some of these wrappers, like coc-ccls, appear to be direct ports of their VSCode equivalents and support additional VSCode-specific features not provided by the LSP. Others, like coc-julia, are just wrappers around a standalone LSP instance (i.e.. coc-julia just launches LanguageServer.jl).

This poses two challenges:
1) Keeping the coc extensions up-to-date with their VSCode equivalents.
2) Many coc extensions (e.g. coc-julia) don't support the additional VSCode-specific functionality.

**Describe the solution you'd like**

Instead of creating coc-specific extensions, could coc.nvim directly use the VSCode extension host, which would allow for VSCode extensions to be used directly, without a wrapper?

As an example, this is what [onivim2](https://github.com/onivim/oni2) does using a [standalone VSCode Extension Host](https://github.com/onivim/vscode-exthost). 

coc.nvim then becomes an interface between (neo)vim and the VSCode extension host, eliminating the need for coc-specific extensions.

**Comment by chemzqm** [comment]
No, it's possible to create a coc.nvim extension that could load VSCode extension like VSCode Extension Host, but I don't think it's worth it.  There would be too much work that we can't afford.
