### ISSUE TITLE
Parsing includes takes a long time and is repeated if a file is opened again

### ISSUE THREAD

**Issue by amandeepgautam** [neoclide/coc.nvim#2293]
I am working on a large project and when I open a file, I see that clangd spends a lot of time in parsing on includes.
If the file is re-opened, all this effort will be done again. Would it be possible to cache these results, so that this parsing is not done again and again?

**Comment by oblitum** [comment]
This is a question for clangd, not coc.nvim.

**Comment by oblitum** [comment]
FYI, latest clangd has caching.
