### ISSUE TITLE
coc.nvim should not suggest autocompletion candidates from all opened files

### ISSUE THREAD

**Issue by GianniGi** [neoclide/coc.nvim#2294]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.2 8020773
node version: v10.19.0
coc.nvim version: 0.0.78-9f9d8a32c4
coc.nvim directory: /home/ego/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Describe the bug

I've disabled coc.nvim on all filetypes except python, yet when I have multiple files opened at the same time, coc suggests autocomplete candidates also from other opened files which are not filetype=python

## Reproduce the bug

Open multiple filetypes (text and python).

Type some words in the python buffer, and see that it populates the list using candidates from the text file, and this should not happen.

## .vimrc
vimrc relevant options

" load coc.nvim on python
autocmd BufNew,BufEnter *.py execute "silent! CocEnable"
autocmd BufLeave *.py execute "silent! CocDisable"
autocmd FileType txt :let b:coc_enabled = 0

Plug 'neoclide/coc.nvim', {'branch': 'release','for': ['python', 'vim', ]}

I use vim with all kind of files (big files), so I think that autcompletion should work through a whitelist, and not through a blacklist. I've seen that there is the option for vimrc
"autocmd FileType txt :let b:coc_enabled = 0"
But as I said a whitelist is surely a more educated behaviour for autocompletion. 
I'd like to find a way to enable coc.nvim features (autocomplete, tag suggestions etc) only for python files.

**Comment by fannheyward** [comment]
Try `coc.source.buffer.enable` to false in your coc-settings.json
