### ISSUE TITLE
How to disable auto-preview feature?

### ISSUE THREAD

**Issue by SolaWing** [neoclide/coc.nvim#2296]
when I use jump to definition or jump to reference, I feels auto preview for the selected list is a little slow, and don't want it. How can I disable it and only preview when I press p? currently the preview window is auto open and have to manually close it.

当我跳到定义或者引用时，跳转列表的自动预览功能使我的VIM响应有些慢，我想关掉它，并仅在我主动按P预览时展示它。现在支持这功能吗？我该怎么做？

**Comment by fannheyward** [comment]
目前不支持，你用的 vim 版本是多少？没有遇到过预览导致 vim 响应慢的问题。

**Comment by SolaWing** [comment]
nvim 0.4, 不是特别慢，只是会有一些延迟，让人能感觉出来的卡顿。
在ruby这种高亮比较费时的语言上会很明显

**Comment by fannheyward** [comment]
```
let g:coc_enable_locationlist = 0
autocmd User CocLocationsChange CocList --normal location
```

`:h CocLocationsChange` 禁用 auto-preview.
