### ISSUE TITLE
coc.nvim consuming too much resources

### ISSUE THREAD

**Issue by amandeepgautam** [neoclide/coc.nvim#2297]
It seems coc is the problem due to which I am facing high resources being consumed. There are too many pch files and seems like it is expected if the number of files opened is high in number (https://github.com/clangd/clangd/issues/512).  However, I am working on only ~7 files.

On my system, even when no editor is open I see that there are 5 clang processes running:
And if you kill these processes they are restarted as they are monitored using node.js processes.

How many node processes are expected without any editor instance?
Thanks for helping me debug the issue.

**Comment by oblitum** [comment]
I only ever see I single clangd instance and it only exists when vim/neovim is running. You may have to debug why there's process leaking on your side, we may not have an idea without further information.

**Comment by amandeepgautam** [comment]
@oblitum thanks for letting me know the expected behaviour. I have cleaned up everything. let's see if this happens again.
