### ISSUE TITLE
echodoc did not activate 

### ISSUE THREAD

**Issue by devstefancho** [neoclide/coc.nvim#2299]
I want to use echodoc, so install this [plugin echodoc](https://github.com/Shougo/echodoc.vim) and add this snippet
```
{
 "suggest.autoTrigger": "always",
"suggest.echodocSupport":true
}
```
to `.config/nvim/coc-settings.json`, but nothing displayed in cmd area
I reference #537

Actually what I want to do is [this question)](https://stackoverflow.com/questions/63691893/how-to-trigger-autocomplete-suggestion-box-in-vim-or-neovim-plugin-neoclide-coc)

I want to reopen this suggestion box, 
when I focus out of autocomplete, I lose this suggest box and did not appear again.
I apprecitate if anyone can help me.

Best regards

**Comment by fannheyward** [comment]
The suggestion box in your image is signatureHelp. If you want to reopen it, you need to trigger `triggerCharacters` in your function, usually is `(` and `,`. The triggerCharacters is defined by LS.

**Comment by chemzqm** [comment]
`echodoc` only works after completion and may failed to work depends on how it detects signature.

**Comment by afranioce** [comment]
This a suggestion to showing parameter hint with shortcut https://github.com/neoclide/coc.nvim/issues/2202#issuecomment-662969193
