### ISSUE TITLE
doHover displays documentation twice

### ISSUE THREAD

**Issue by sigzegv** [neoclide/coc.nvim#2300]
I'm using coc with coc-go (gopls inside).
When I run the doHover action, this displays the documentation twice in the popup.

Command I use for the doHover :
`nmap <silent> gd :call CocActionAsync('doHover')<cr>`

## Screenshots
![image](https://user-images.githubusercontent.com/6304596/92010422-168e2a80-ed4a-11ea-82b0-c23edbb433bd.png)

How could I get ride of this and display doc once in the popup ?

**Comment by oblitum** [comment]
I can't reproduce your issue. Please fill issue template.

**Comment by fannheyward** [comment]
Checkout `:CocList services`.

**Comment by sschlereth** [comment]
I know this was closed as not reproducible, but has anyone figured it out? I see the same behavior with both coc-go and coc-omnisharp, so I don't think it's specific to Go.

I ran :CocList services and the gopls is the only entry (even if in C# file w/ Omnisharp running). Starting/stopping the service makes no difference.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by C-Rmoser** [comment]
Having the same problem using coc-omnisharp. Did anyone find a solution yet?

**Comment by sigzegv** [comment]
> Having the same problem using coc-omnisharp. Did anyone find a solution yet?

I solve the issue by completing unistalling and clearing coc files in ~/.config and reinstalling it.. I never got the issue again since then. Should a caching issue or something.

**Comment by C-Rmoser** [comment]
Thanks for your quick reply! 
Sadly this didn't fix it for me. Uninstalled coc by removing extension and running PlugClean, deleted the coc folder in C:\users\username\AppData\coc and also deleted everyting in C:\users\username\AppData\Temp. Is there something I missed?

**Comment by jonaustin** [comment]
@C-Rmoser you shouldn't have to delete everything, at least just uninstalling the coc-go extension fixed it for me: https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#uninstall-coc-extension
