### ISSUE TITLE
b:coc_enabled does not take effect when LSP already started before opening large file

### ISSUE THREAD

**Issue by ZSaberLv0** [neoclide/coc.nvim#2302]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8021050
node version: v12.18.1
coc.nvim version: 0.0.78-0ff42027ff
coc.nvim directory: /Users/mac/.vim/bundle/coc.nvim
term: dumb
platform: darwin
```

## Describe the bug

prepare:
1. using the config below
1. assume we have two file:
    * `normal.js` : normal js file
    * `large.js` : a very large js file, typically generated by webassembly, maybe 5MB or more

this is the right and expected behavior:
1. open vim
1. open `large.js`
1. `b:coc_enabled` is set to 0 automatically, and no lag occurred

this is the issue:
1. open vim
1. open `normal.js`, so LSP is started
1. open `large.js`
1. `node` takes 100% CPU, since the `large.js` is parsed by LSP

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=~/.vim/bundle/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  
  let g:coc_user_config = {
              \   'coc' : {
              \     'preferences' : {
              \       'maxFileSize' : '1MB',
              \     },
              \   },
              \ }
  let g:coc_data_home = $HOME . '/.vim_cache/coc/data'
  
  function! s:isLargeFile(file)
      let size = getfsize(a:file)
      if size == -2 || size > 1*1024*1024
          return 1
      endif
      return 0
  endfunction
  augroup Largefile_augroup
      autocmd!
      function! s:largefileDetect()
          if s:isLargeFile(expand('<afile>'))
              let b:coc_enabled=0
          endif
      endfunction
      autocmd BufReadPre * call s:largefileDetect()
      autocmd BufWritePost * call s:largefileDetect()
  augroup END
  
  augroup CocInit
      autocmd!
      function! s:cocInit()
          call coc#config('languageserver.typescript', {
                      \   'command': &shell,
                      \   'args': [&shellcmdflag, 'typescript-language-server --stdio'],
                      \   'filetypes': ['typescript', 'typescript.tsx', 'javascript', 'javascript.jsx'],
                      \   'initializationOptions': {},
                      \ })
      endfunction
      autocmd VimEnter * call s:cocInit()
  augroup END
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- using the steps mentioned above

**Comment by fannheyward** [comment]
Why do you use `typescript-language-server` instead of https://github.com/neoclide/coc-tsserver?

**Comment by ZSaberLv0** [comment]
> Why do you use `typescript-language-server` instead of https://github.com/neoclide/coc-tsserver?

I'm using vim in many different envs, and may use LSP with deoplete or ncm2 on different situations, so using standalone LSP is more convenient, and can keep same behavior

**Comment by chemzqm** [comment]
You have to set that variable on buffer create, or use `coc.preferences.maxFileSize` configuration.

**Comment by ZSaberLv0** [comment]
@chemzqm please check and test the mini.vim I supplied

> You have to set that variable on buffer create

is `BufReadPre` not enough? if not, which should I use?

> or use `coc.preferences.maxFileSize` configuration

I have already configured maxFileSize to `1MB`

**Comment by chemzqm** [comment]
It should work, try `autocmd BufReadPre * let b:coc_enabled=0`

**Comment by chemzqm** [comment]
Find the reason, you have to use `BufAdd` autocmd instead, since `BufReadPre` could trigger before or after `BufAdd`

**Comment by ZSaberLv0** [comment]
tested, using `BufAdd` / `BufCreate` could solve this issue

however, maybe you should also check why `coc.preferences.maxFileSize` does not take effect
