### ISSUE TITLE
call coc-refactor on golang package exported fields would trigger warnning from language server

### ISSUE THREAD

**Issue by CodeNoobKc2** [neoclide/coc.nvim#2304]
## Describe the bug

When I called CoCActionAsync('refactor') on golang's exported field which is already referenced by other pkg, an warning will be triggered by the language server and the refactor would be aborted.

The reason behind this is that in golang, exported field's name must be started with a capitalized letter, but when calling coc-refactor method, the default newname for hovered symbol is "newname" of which the first letter is not capitalized, thus causing the bug. 

## Reproduce the bug

- coc-settings.json
```
{
...
"languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"],
      "disableWorkspaceFolders": true,
      "initializationOptions": {
        "usePlaceholders":true,
        "completeUnimported":true
      }
    },
...
}
```

- Opening a go project and move the cursor on an exported method or filed from the other pkg

- Run 
```
:call CoCActionAsync('refactor')
```

## Screenshots
![截屏2020-09-04 下午5 31 15](https://user-images.githubusercontent.com/67936979/92224542-84fef400-eed4-11ea-8ee8-d7fb4956513c.png)

**Comment by fannheyward** [comment]
Fixed om master
