### ISSUE TITLE
the config of coc doesn't work

### ISSUE THREAD

**Issue by mfyx** [neoclide/coc.nvim#2305]
i copy the code to my vimrc(~/.vim/vimrc), but they doesn't work

```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
```

and when i run ":source vimrc", the config is effecitve.
then i try to other way to run the config, i copy the code to /etc/vimrc, it's useless.
i try to copy the code to the file “other" i created, then my vimrc source the file, that's useless too, but when i run "source vimrc", the code is working too.
what can i do?
i'm a chinese. my English is poor. but the chinese issue communication can't log in. i have to use my student level English to ask my question, that is my first English issue, forgive me.

**Comment by fannheyward** [comment]
Can't reproduce, please check `:verbose imap <tab>`, and provide a minimal vimrc to reproduce this error.

**Comment by mfyx** [comment]
thanks, when i run `:verbose imap <tab>', the trouble ponits to my plug "Ultisnips", i didn't specify `g:UltisnipsExpandTrigger`, they auto bundle the `<tab>`
when i have a smilar problem, i will use the `verbose`, this is what i learnd
