### ISSUE TITLE
strange characters in msys2 in windows terminal

### ISSUE THREAD

**Issue by vdyn** [neoclide/coc.nvim#2309]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.2 8020869
node version: v14.0.0
coc.nvim version: 0.0.78-9f9d8a32c4
coc.nvim directory: D:\msys64\home\user01\.vim\plugged\coc.nvim
term: dumb
platform: win32

## Describe the bug

Strange characters when start application at the top:

←[?1h←[?1h←[?1h←[?1h←[?1h←[?1h←[?1h←[?1h←[?1h←[?1h←[?1h←[?1h

## Reproduce the bug

- Integrate msys2 in windows terminal (settings.json):

  ```vim
     {
          "hidden": false,
          "name": "MSYS2 MinGW 64",
          "colorScheme": "Solarized Light",
          "commandline": "cmd.exe /c \"set MSYSTEM=MINGW64&& D:\\msys64\\usr\\bin\\bash.exe --login\"",
          "icon" : "D:\\msys64\\mingw64.ico",
      }
  ```
- Install coc plugin

- File .vimrc

  ```vim
  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()
  ```

- Start msys2 in windows terminal 

- Start vim in msys2 terminal

## Screenshots (optional)

![capture](https://user-images.githubusercontent.com/4441815/92330241-fc4a9a00-f032-11ea-8a25-b7ccf2c38d41.PNG)

## Aditional information

Work fine in pure msys2 terminal.
![Capture1](https://user-images.githubusercontent.com/4441815/92330293-6400e500-f033-11ea-999d-bf35c91b8a2a.PNG)

**Comment by fannheyward** [comment]
Properly it's an issue of msys2.

**Comment by CervEdin** [comment]
same
mingw64/msys2 mintty 3.4.7

**Comment by CervEdin** [comment]
but not if I RD into the same system and run vim there in a differnt mingw64/msys2 mintty 3.4.4 terminal

**Comment by CervEdin** [comment]
The same issue doesn't appear when I'm using neovim.

I put this abomination as a work-around in vim.

```vim
function DelayedRedraw(timer)
	redraw!
endfunction
let timer=timer_start(1000, 'DelayedRedraw')
```

**Comment by CervEdin** [comment]
I have another machine where I don't encounter this issue. It may be related to the `code page` setting of the windows console (cmd/ps). On the working machine it's set to `utf-8`

**Comment by CervEdin** [comment]
Can confirm that changing the windows code page to `utf-8` [as per](https://superuser.com/a/1435645) resolved the issue on my machine
