### ISSUE TITLE
What is the format for CocCommand arguments?

### ISSUE THREAD

**Issue by ApolloBian** [neoclide/coc.nvim#2311]
The document for CocCommand states such usage:
![image](https://user-images.githubusercontent.com/13659369/92370407-d3a6cb00-f12c-11ea-88fb-28eb1c0d5f59.png)

However, I tried to pass arguments to the `python.enableLinting` command:
`:CocCommand python.enableLinting on`
but it does not seem to recognize the argument. Instead, it prompts me to select on/off.
![image](https://user-images.githubusercontent.com/13659369/92370704-3a2be900-f12d-11ea-83f8-d4012be27be3.png)

![image](https://user-images.githubusercontent.com/13659369/92370645-22ecfb80-f12d-11ea-9a41-fef64fe298fe.png)

Is this expected behavior? Is it possible to get the command to recognize the argument so that I can bind this to a shortcut, e.g. to toggle  linting without any further interaction required?

**Comment by ApolloBian** [comment]
Similar behavior is also recognized for `python.setInterpreter <somepath>/bin/python`. It would be nice to be able to pass the args so that I can write custom commands to select interpreter automatically

**Comment by fannheyward** [comment]
This is expected, coc-python uses quickPick to select option, you can't use argument yet.

**Comment by ApolloBian** [comment]
Are there any ways to work around this? e.g. call the function used by python.setInterpreter and pass commands?

**Comment by chemzqm** [comment]
No, it should be persisted for your current workspaceFolder, which means you only need do that once for each folder.
