### ISSUE TITLE
:CocCommand hangs up vim

### ISSUE THREAD

**Issue by GianniGi** [neoclide/coc.nvim#2313]
## versions

vim version: VIM - Vi IMproved 8.2 8020773
node version: v10.19.0
coc.nvim version: 0.0.78-9f9d8a32c4
coc.nvim directory: /home/my/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Output channel: Python

Starting Jedi Python language engine.

## Describe the bug

vim hangs completely with the command
:coccommand
It shows and empty "fuzzy" list and I can't type anything
I've used for ten days, and before this this command worked, showing fuzzy completions

## Reproduce the bug

start vim
open a python file
:coccomand

**Comment by fannheyward** [comment]
Can't reproduce, do you use `coc-python` or `coc-jedi` or set Python language server in coc-settings.json?

**Comment by GianniGi** [comment]
I've installed coc-python, and jedi via pip install.

In coc settings I've just an option to enable coc.nvim for python files
only.

In retrospect, probably this error was born after some linter modifications
(coc.command - choose linter). After that I've disabled linting as it was
before, and still I have the same error.


Il mar 8 set 2020, 10:06 Heyward Fann <notifications@github.com> ha scritto:

**Comment by fannheyward** [comment]
Don't open Python file in $HOME directly, some language server maybe index all files in your $HOME. Try to make a folder and try again.

**Comment by GianniGi** [comment]
Thanks but I have no files in home

Il mar 8 set 2020, 10:20 Heyward Fann <notifications@github.com> ha scritto:

**Comment by GianniGi** [comment]
How can I solve this? I've tried to uninstall coc.nvmi (via Plug) and then to uninstall jedi. But when I reinstall everything I still have the same problem...

**Comment by GianniGi** [comment]
Right now I'm stuck in the fuzzy prompt
     FUZZY> 
I can type in the prompt, but I can't exit, I've tried C-c, C-q, C-s, exit, :exit, exit()....

**Comment by GianniGi** [comment]
```
{
	"coc.source.word.filetypes": ["python"],
	"coc.source.buffer.enable": false,
	"python.linting.enabled": false
}

```

**Comment by chemzqm** [comment]
Use `<esc>` to exit.

**Comment by GianniGi** [comment]
It doesn't exit. It just stays there in the fuzzy prompt

Il giorno giovedì 10 settembre 2020, Qiming zhao <notifications@github.com>
ha scritto:

**Comment by chemzqm** [comment]
Could you reproduce it with coc-python disabled?

**Comment by GianniGi** [comment]
I've uninstalled everything, the reinstalled coc.nvim without coc-python and the error is still there. I reinstalled coc-python and things are a little bit better, fuzzy doesn't hangs anymore, it simply opens some empty tabs, that make me lose forever the file I was working on.

When I type the 
:coccommand
I get the fuzzy prompt, which doesn't autocomplete anything, it simply opens a split or two, and if I press esc it just sends me to one of the splits which says something like
Press ? on normal mode to get help

**Comment by GianniGi** [comment]
coc.nvim accepts coc-nvim commands like these ones
https://github.com/neoclide/coc-python

but when I type 
:coccomand
this brings an unresponsive split that doesn't allow me to go back to my file
showing errors like "list:///commands [none...]c:000
and when I press esc I get
press ? on normal mode to get help

**Comment by chemzqm** [comment]
Try minimal vimrc

**Comment by chemzqm** [comment]
Maybe your vim plugin can't receive esc by getChar, try customize list keymapping

**Comment by GianniGi** [comment]
I've tried with a minimal vimrc, but I have the same problem.

Here is a screenshot that shows the fuzzy output, and a screenshot that shows the fuzzy split tab that opens after I press esc

![$Screenshot from 2020-09-12 22-10-32](https://user-images.githubusercontent.com/9282332/93004165-d4809800-f544-11ea-9801-017efef9ed85.png)

![$Screenshot from 2020-09-12 22-09-57](https://user-images.githubusercontent.com/9282332/93004166-d5b1c500-f544-11ea-99ef-b0f6f5c99a5a.png)



```
syntax on
filetype on
filetype plugin on
filetype plugin indent on

set backspace=indent,eol,start

filetype plugin indent on

call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release','for': ['python']}

call plug#end()
```
