### ISSUE TITLE
Error with "node.js" file name

### ISSUE THREAD

**Issue by ursi** [neoclide/coc.nvim#2314]
## Result from CocInfo

Behaves weirdly. First it tells me there's a swap file for the file, so I hit open [read only]. then it opens up a new nvim-qt (operating system) window, split into two (vim) windows, one with the file I was on when I ran the command and the other with the text below (my original window is still open as well).
```
Error: Node version  < 10.12.0, please upgrade node.js
```
The Node.js version I have on my system is 12.13.0

## Describe the bug
If neovim (maybe vim too) is opened in a directory containing a file by the name of `node.js`, there is an error when opening the file (shown below).

## Reproduce the bug
```vim
" init.vim

set nocompatible
set runtimepath^=~\AppData\Local\nvim\plugged\coc.nvim
filetype plugin indent on
syntax on
set hidden
```

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/17836748/92439505-f4950d80-f178-11ea-95c9-74dc67847866.png)

**Comment by fannheyward** [comment]
Can't reproduce with macOS + nvim, needs more info on windows.

**Comment by ursi** [comment]
Let me know what info you'd like.

**Comment by Ende93** [comment]
I reproduced the error. Opened the file `node.js` for the first time is ok, reopened would raise the error. vim is both ok.

**Comment by fannheyward** [comment]
@ursi  Set `let g:coc_node_path = 'path_to_your_node'` in your vimrc and try again.

**Comment by chemzqm** [comment]
Caused by nvim-qt expand `node` from your cwd, which is buggy.

**Comment by ursi** [comment]
@chemzqm is there an easy workaround?

**Comment by chemzqm** [comment]
Use `let g:coc_node_path = 'path_to_your_node'`

**Comment by ursi** [comment]
oh, okay, yeah I hadn't gotten around to doing that yet. Thanks.
