### ISSUE TITLE
Should coc handle the file path case-sensitively?

### ISSUE THREAD

**Issue by zXie-R** [neoclide/coc.nvim#2316]
## versions

vim version: NVIM v0.4.3
node version: v14.9.0
coc.nvim version: 0.0.78-9f9d8a32c4
coc.nvim directory: C:\Users\\***\\.vim\plugged\coc.nvim
term: vtpcon
platform: win32

## Describe the bug

So, recently I've been working on a large typescript react code base and got the following error when I ran `<Plug>(coc-codeaction)` and selected the fix.
```
2020-08-31T22:16:35.569 ERROR (pid:32180) [workspace] - TypeError: Cannot read property 'uri' of null
at Workspace.applyEdit (C:\Users\***\.vim\plugged\coc.nvim\build\index.js:25734:56)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Handler.applyCodeAction (C:\Users\***\.vim\plugged\coc.nvim\build\index.js:72793:13)
at async Handler.doCodeAction (C:\Users\***\.vim\plugged\coc.nvim\build\index.js:72758:17)
at async Plugin.cocAction (C:\Users\***\.vim\plugged\coc.nvim\build\index.js:23695:16)
at async NeovimClient.<anonymous> (C:\Users\***\.vim\plugged\coc.nvim\build\index.js:11342:21)
```

## Reproduce the bug
Then I looked into `index.js` and used logger to debug, I found that the `uri` in the `edit.changes` object that is supplied to `applyEdit(edit)` near line 25646 has some folders lowercased. For example, actual path `Very/long/path/to/Project/to/Subfolder/Anothersubfolder/File.tsx` turned into `Very/long/path/to/Project/to/subfolder/anothersubfolder/File.tsx` in `edit.changes.uri`, two folders `Subfolder/Anothersubfolder` got lowercased. This difference resulted in `getDocument(uri) = null`, which means couldn't find the file in open buffers and will fail to load the files due to the lowercased `uri`. I did a band-aid fix locally in `getDocument(uri)` to workaround, but I think it'd be better not to lowercase `uri` in `edit.changes` in the first place
```
    getDocument(uri) {
        if (typeof uri === 'number') {
            return this.buffers.get(uri);
        }
        uri = vscode_uri_1.URI.parse(uri).toString().toLowerCase();
        for (let doc of this.buffers.values()) {
            if (doc && doc.uri.toLowerCase() === uri)
                return doc;
        }
        return null;
    }
```

Can this be fixed? Or I missed something in the config?

**Comment by fannheyward** [comment]
The problem is why `edit.changes.uri` will be lowercased, this is unexpected.

**Comment by zXie-R** [comment]
> The problem is why `edit.changes.uri` will be lowercased, this is unexpected.

@fannheyward Yes, that's strange. I don't know how `uri` in `changes` is generated.

**Comment by fannheyward** [comment]
I'm using nvim+coc.nvim on coc.nvim codebase, can't reproduce this issue.

**Comment by chemzqm** [comment]
No, your language server need to fix it.

**Comment by zXie-R** [comment]
> No, your language server need to fix it.

@chemzqm I've tried the same action on the same file with vscode with no error. So I suspected it might be something on the coc end.
