### ISSUE TITLE
g:coc_data_home cannot work with vim8's native package manager?

### ISSUE THREAD

**Issue by fly-potato-100** [neoclide/coc.nvim#2319]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.2 8020267
node version: v12.18.3
coc.nvim version: 0.0.78-9f9d8a32c4
coc.nvim directory: /home/yk/.vim/pack/default/opt/coc.nvim-release
term: dumb
platform: linux

## Describe the bug

I have set `g:coc_data_home` to somewhere other than `~/.config/coc`.
But vim still notified me `[coc.nvim] creating data directory: /home/yk/.config/coc`

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  packadd coc.nvim-release
  let g:coc_config_home = '~/path/to/config'
  let g:coc_data_home = '~/path/to/data'
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
How to install coc.nvim with Vim native package manager? I haven't use native package manager.

**Comment by fannheyward** [comment]
I can't run with your mini.vim, I haven't used native package manager.

**Comment by Gankarloo** [comment]
I have this working fine in vim.

but you have to define the variables before loading the plugin.

**Comment by fly-potato-100** [comment]
> I have this working fine in vim.
> 
> but you have to define the variables before loading the plugin.

Yeah. Put `packadd coc.nvim-release` bottom then everything goes well.
Thx!
