### ISSUE TITLE
`doHover` window contains markdown code block opening instead of type information

### ISSUE THREAD

**Issue by dashea** [neoclide/coc.nvim#2323]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8020550
node version: v13.13.0
coc.nvim version: 0.0.78-3a10d7e1a7
coc.nvim directory: /Users/dshea/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Output channel: metals

2020.09.10 17:31:57 INFO  logging to file /Users/dshea/.metals/metals.log
2020.09.10 17:31:57 INFO  started: Metals version 0.9.3 in workspace '/Users/dshea' .
2020.09.10 17:31:58 INFO  time: initialize in 0.87s
2020.09.10 17:31:58 WARN  no build tool detected in workspace '/Users/dshea'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. 
2020.09.10 17:31:58 INFO  no build target: using presentation compiler with only scala-library
2020.09.10 17:32:00 WARN  no build target for: /Users/dshea/tmp.scala
```

NB: The messages about no build tool, no build target etc don't matter for this, I'm just opening a scala file without creating a project.

## Describe the bug

The floating window created by `CocAction('doHover')` contains a markdown code block opening and not the documentation and type information that is supposed to follow. This appears to have started with commit 3dd7d8d0928a27bc443937261ee2ab3f3d6e78fa.

## Reproduce the bug

Reproduced using minimal vimrc from template plus `coc-metals` extension, moving the cursor to an item and running `:call CocAction('doHover')`

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

## Screenshots (optional)

Using commit 3dd7d8d0928a27bc443937261ee2ab3f3d6e78fa:

<img width="261" alt="Screen Shot 2020-09-10 at 5 39 35 PM" src="https://user-images.githubusercontent.com/4419868/92811933-e9b2c680-f38c-11ea-859d-6e04be39eb50.png">

Using commit 52c18cefd06879924a8469fc493af58fb3e7f1f4:

<img width="236" alt="Screen Shot 2020-09-10 at 5 43 34 PM" src="https://user-images.githubusercontent.com/4419868/92812276-34344300-f38d-11ea-8954-a6f1dc4d0120.png">

**Comment by fannheyward** [comment]
Yes, coc used to trim code block, but this will cause render issue on vim. You can use some plugin like `Plug 'plasticboy/vim-markdown'` to handle markdown in vim.

**Comment by dashea** [comment]
The problem isn't the code block, it's that the floating window *only* displays the markdown. If I use the markdown plugin, I just get an empty window from the code block being formatted out.

<img width="187" alt="Screen Shot 2020-09-10 at 9 20 24 PM" src="https://user-images.githubusercontent.com/4419868/92837392-871cf300-f3ab-11ea-91e4-2dba262d9950.png">

**Comment by fannheyward** [comment]
Do you have set `coc.preferences.previewMaxHeight` in coc-settings.json?

**Comment by dashea** [comment]
I don't. I tried setting it to 100, and got the same result. The height of the window is the size of the text minus the markdown backquotes, in the examples here 1 line, but the text displayed starts on the markdown backquotes, which are blanked out by the markdown highlighting, and the actual data ends up being hidden.
