### ISSUE TITLE
javascript bundle not found please compile the code of coc.nvim

### ISSUE THREAD

**Issue by hoerdan** [neoclide/coc.nvim#2326]
Hi, so basically, I'm using gVim and wanted an autocomplete, so I tried using coc.nvim. now it's ".nvim", but I have been told that I can use coc on gVim. I tried using vim-plug and installing it, but I run into this issue where it says " javascript bundle not found please compile the code of coc.nvim" everytime I start up gVim. I have node and yarn both installed. Is there anyway to fix this?

**Comment by chemzqm** [comment]
Use release branch
