### ISSUE TITLE
Sync with shiftwidth, softtabstop, tabstop

### ISSUE THREAD

**Issue by danielfalbo** [neoclide/coc.nvim#2328]
**Is your feature request related to a problem? Please describe.**
In my vimrc I have
```
set shiftwidth=4
set softtabstop=4
set tabstop=4
```
but every time I format my file with `<Plug>(coc-format)`, based on the filetype the tabs (expanded in spaces in my case) adapt their width to the convention.

**Describe the solution you'd like**
Is there a way to sync the vim settings `shiftwidth`, `softtabstop` and `tabstop` with the width used by `coc-format` without manually writing the filetype specific settings in the vimrc?

**Describe alternatives you've considered**
Writing filetype specific settings in the vimrc

**Additional context**
none

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
