### ISSUE TITLE
PHP LS cuts variable names in completion.

### ISSUE THREAD

**Issue by Kazimazi** [neoclide/coc.nvim#233]
**Result from CocInfo**
`## versions

vim version: NVIM v0.3.1
node version: v10.13.0
coc.nvim version: 0.0.37
term: xterm-256color
platform: linux

## Output channel: languageserver.phplang
DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is loaded (2.6.1)
DEBUG     Process restarting (PHPLS_ALLOW_XDEBUG=internal|2.6.1|1|*|*)
DEBUG     Running '/usr/bin/php' '-n' '-c' '/tmp/VM6DFk' '/home/kazimazi/.config/composer/vendor/bin/php-language-server.php'
DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     Restarted (20 ms). The xdebug extension is not loaded
DEBUG     Listening on STDIN
[Info  - 12:26:50 PM] 2 files total
[Info  - 12:26:50 PM] Indexing project for definitions and static references
Parsing file:///home/kazimazi/temp/.phan/.config.php
Parsing file:///home/kazimazi/temp/asd.php
[Info  - 12:26:50 PM] Indexing project for dynamic references
Parsing file:///home/kazimazi/temp/.phan/.config.php
Parsing file:///home/kazimazi/temp/asd.php
[Info  - 12:26:50 PM] 0 Packages
[Info  - 12:26:50 PM] All 2 PHP files parsed in 0 seconds. 148 MiB allocated.

## Output channel: highlight
[Info  - 12:26:50 PM] Highlight server running in node v10.13.0`

**Describe the bug**
Let's say I have a php file like:
`<?php $nocutting=true`
When I use LS to autocomplete my variable it cuts it in half and takes away the part I've already typed for example: `$nocut` will produce `$ting` after completion.
I use my tab key for completion which is configured like this:
`inoremap <silent><expr> <TAB>
            \ pumvisible() ? "\<C-n>" :
            \ <SID>check_back_space() ? "\<TAB>" :
            \ coc#refresh()
`
If I use arrow key it won't bug.

**Screenshots**
[before completion](https://gyazo.com/72cee622fdfd4eaf37d86bc22a4f3164)
[after completion](https://gyazo.com/98ee8814f7f2cee1d572f5a4a3811d08)

**Comment by chemzqm** [comment]
You can confirm completion by `<C-y>` to fix this problem for now.
