### ISSUE TITLE
javascript bundle not found

### ISSUE THREAD

**Issue by GGCristo** [neoclide/coc.nvim#2331]
## Describe the bug

I cant open vim since the last update (0.0.79) (e5cedd3)

## Screenshots (optional)
![Screenshot_20200912_174347](https://user-images.githubusercontent.com/58046649/93000338-a341a100-f51f-11ea-9b93-b97463c12347.png)

**Comment by jethrosun** [comment]
Running into the same issue just now. And the auto installation results a building failure in my neovim (triggered by that coc util install)
```
  $ npm-run-all clean build
  yarn run v1.22.5
  $ rimraf lib build
  Done in 0.22s.
  yarn run v1.22.5
  $ tsc -p tsconfig.json
  error TS5058: The specified path does not exist: 'tsconfig.json'.
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  ERROR: "build" exited with 1.
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Congee** [comment]
```log
yarn install v1.22.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has
been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://
github.com/request/request/issues/3142
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request > har-validator@5.1.5: this library is no longer
supported
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://gith
ub.com/lydell/resolve-url#deprecated
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://
github.com/lydell/urix#deprecated
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @typescript-eslint/eslint-plugin-tslint@4.1.0" has unmet peer dependency "tslint@^5.0.0 || ^6.0.0".
[5/5] Building fresh packages...
$ npm-run-all clean build
yarn run v1.22.4
$ rimraf lib build
Done in 0.13s.
yarn run v1.22.4
$ tsc -p tsconfig.json
error TS5058: The specified path does not exist: 'tsconfig.json'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[Process exited 1]
```

**Comment by mirsella** [comment]
mabe this [comment](https://github.com/neoclide/coc.nvim/issues/2330#issuecomment-691517104) can help, even if it's not the same problem.

**Comment by chemzqm** [comment]
Looks like vim-plug tend to use latest tag instead of default branch when the tag is newer.
Should be fixed now.

**Comment by chemzqm** [comment]
Bad release script added bin/server.js, fixed now.

**Comment by katsika** [comment]
Getting `[coc.nvim] build/index.js not found, reinstall coc.nvim to fix it.` now, `CocRebuild` doesn't seem to help.

**Comment by chemzqm** [comment]
You may need run `git reset head --hard` in folder of coc.nvim and update it by `:PlugUpdate` in your vim.

**Comment by katsika** [comment]
@chemzqm Perfect, thanks! Works now.

**Comment by AdrienLemaire** [comment]
@chemzqm getting the same "javascript bundle not found" error on master. Reverting to release branch (tag v0.0.79) works. 
Latest commit: 9918875

**Comment by chemzqm** [comment]
You have to build javascript when using master

**Comment by timnolte** [comment]
Seem that v0.0.79 is still broken. If I manually go in and switch to version v0.0.78 and remove the node_modules directory then things install fine and are working. As soon as I run a PlugUpdate then version v0.0.79 is installed and my Neovim is broken with yarn trying to run and install the missing tsconfig.json again. When is this going to get fixed?

**Comment by chemzqm** [comment]
v0.0.79 is borken, use latest release branch or wait for next release tag.

**Comment by timnolte** [comment]
OK, I found that I had specified `{'tag': '*'}` so every time I would run `:PlugUpdate` it would still update to the latest tagged release. Wouldn't it be wise to remove that release tag since it's bad? Anyways, I changed my config to use `{'branch': 'release'}` and things are working. Thanks!

**Comment by travisboss** [comment]
For anyone else who might find this I did as @timnolte did but I also did as @chemzqm suggested above and `git reset head --hard` then a `:PlugUpdate` to fix the issue.

**Comment by Shokodemon** [comment]
cd ~/.vim/bundle/coc.nvim/ && git reset head --hard
open vim && :PluginUpdate && :call coc#util#install()

**Comment by magidandrew** [comment]
> cd ~/.vim/bundle/coc.nvim/ && git reset head --hard
> open vim && :PluginUpdate && :call coc#util#install()

^^This!! Running macos catalina with neo plug (was running vundle before, but was having issues).
Was looking for hours for this solution.

**Comment by FrankReh** [comment]
Running macOS Catalina and vim with Pathogen, I had just git cloned coc.nvim from master and was seeing the same problem. Read above that getting back to tag v0.0.78 would get it working for now, and this is all it took. Thanks.
```
cd ~/.vim/bundle/coc.nvim
git checkout tags/v0.0.78
```

**Comment by yannham** [comment]
I also run into this problem on Debian with Vundle. Tried resetting, wiping, reinstalling, without success. Checking the same release as @FrankReh - v0.0.78 - did fix the problem for now.

**Comment by yannham** [comment]
It's now working with master after a fresh reinstall of coc.nvim

**Comment by Lake-Jee** [comment]
@FrankReh Thanks man! Saved me a ton of time!

**Comment by jcnauta** [comment]
> cd ~/.vim/bundle/coc.nvim/ && git reset head --hard
> open vim && :PluginUpdate && :call coc#util#install()

For me it's `PlugUpdate`, not `PluginUpdate`.

**Comment by jpalus** [comment]
Any reason not to tag 0.0.80 with the fix?

**Comment by mke21** [comment]
I cannot get it to work on Windows10, while coc used to work on an older laptop.
In checkhealth I get:
```
ERROR: Javascript entry not found, please compile coc.nvim by esbuild
```
Doing the actions described above, the coc#util#install() function give the following error:
```
FIle coould not be loaded: env-ns:node_modules\log4js\lib\appenders
```
Nodejs and yarn are installed. Don't know what to do.

**Comment by foxx** [comment]
This happened to me because I quit Neovim too quickly after running `call dein#install()`, which left the plugin corrupt. Remove the dein plugin dir then try again, but wait until it says "done" or until there's no processes left in `ps faux`. Good luck!

**Comment by Adit-Joshi** [comment]
> cd ~/.vim/bundle/coc.nvim/ && git reset head --hard open vim && :PluginUpdate && :call coc#util#install()

This was the solution for me.. I wasn't able to do the `git reset head --hard` but a `call coc#util#install()` worked for me

**Comment by zcngihub** [comment]
> MacOS Catalina ve vim'i Pathogen ile çalıştırırken, master'dan sadece git klonlanmış coc.nvim'i almıştım ve aynı sorunu görüyordum. Yukarıda, v0.0.78 etiketine geri dönmenin şimdilik çalışmasını sağlayacağını okuyun ve hepsi bu kadar. Teşekkürler.
> 
> ```
> cd ~/.vim/bundle/coc.nvim
> git checkout tags/v0.0.78
> ```

Tankyou a hundred times. you are awesome
