### ISSUE TITLE
Is it possible to create/configure custom list sources for CocList?

### ISSUE THREAD

**Issue by opti-mix** [neoclide/coc.nvim#2333]
Coc Wiki describes how to define [custom sources](https://github.com/neoclide/coc.nvim/wiki/Create-custom-source).

But is it possible to create custom sources for CocList in a modular way as well? I understand that one could simply change coc.nvim sources and add some new files under `src/list/source`, but it would interfere with Coc git repo and is inconvenient in terms of maintenance. Additionally, my custom list sources would access some private databases and thus they cannot be upstreamed. Ideally, I'd like to keep such custom list sources in a separate user-defined directory if possible.

**Comment by chemzqm** [comment]
Sure, checkout https://github.com/neoclide/coc-lists
