### ISSUE TITLE
Remap autocomplete dialog arrow keys to default vim movement keys

### ISSUE THREAD

**Issue by yona-asael** [neoclide/coc.nvim#2343]
**Is your feature request related to a problem? Please describe.**
I was working with coc like 6 months right now, i tried to remap the arrow keys to select the auto complete to basic movement in vim, i read all documentation but i not have idea how do that.

**Describe the solution you'd like**
Hi i just want to remap the arrow keys for autcomplete dialog to basic arrow keys in vim that keys are  J K 

**Describe alternatives you've considered**
I consider to user remap with leader key but that is doesnt work

**Comment by chemzqm** [comment]
It's your vim's behavior, not coc.nvim related.
