### ISSUE TITLE
Improve Debug Documentation

### ISSUE THREAD

**Issue by pascal-mueller** [neoclide/coc.nvim#2346]
In https://github.com/neoclide/coc.nvim/wiki/Debug-language-server some debug options are described.

For me, it's unclear:
- If the id includes "languageserver"

- It's unclear if we need both verbose properties (i.e. "tsserver.trace.server": "verbose", and "trace.server": "verbose" if we have a server configured with in the settings file instead of using an extension)

- If possible add the solution using chrome wiht a different browser.

- It's unclear again, if the id-tag (css) would include languageserver or not "css.execArgv": ["--nolazy", "--inspect-brk=6045"]

I suggest to just define the id more clearly and then write the docs it using <id> followed by 1-2 examples.

**Comment by chemzqm** [comment]
Improved, install coc-json for auto completion.
