### ISSUE TITLE
User configuration not loaded?

### ISSUE THREAD

**Issue by heftig** [neoclide/coc.nvim#235]
I'm setting `"rust-client.rls-name": "rls"` in my user's coc-settings.json but it doesn't have any effect; coc-rls still looks for `rls-preview` and asks to install the now (in beta) renamed component.

**Comment by chemzqm** [comment]
fixed at 7b3bd30

**Comment by heftig** [comment]
It's fixed. Thanks a lot for your prompt responses!

**Comment by oblitum** [comment]
@heftig for your information: https://github.com/neoclide/coc-rls/issues/4#issuecomment-445289894

**Comment by heftig** [comment]
@oblitum That wasn't the case for me.
