### ISSUE TITLE
No autocompletion start after installing and cannot install :CocInstall coc-css plugin. Throwing request timeout.

### ISSUE THREAD

**Issue by electrovoyager** [neoclide/coc.nvim#2350]
## vim Versions

vim versions: NVIM v0.4.4
node version v12.18.4
coc.nvim version: 0.0.79-b71
coc.nvim directory: /home/user/.config/nvim/plugged/coc.nvim
term: xterm256color
platform: linux

## Describe the bug
After I installed the plugin unlike previous times it's not even start completing for CSS. I then tried to install coc-css plugin but it's either showing timeout or not installing.

In the past I installed and used the plugin in same os (parrot os KDE parrot latest version). No problem found then, but now after reinstalling the OS and installing the plugin again this problem started.
No auto completion is starting after the installation. Installed npm yarn and other prerequisites. Also when try to install :CocInstall coc-css below error is produced
Request timeout after 10000ms 

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)
Not starting autocomplete
![Screenshot_20200916_211753](https://user-images.githubusercontent.com/22958419/93362165-47e71a00-f863-11ea-9b80-7aecd9079a6a.png)

Here is the error while trying to install coc-css plugin:
![Screenshot_20200916_211823](https://user-images.githubusercontent.com/22958419/93362232-5f260780-f863-11ea-943e-f5ded1c6174a.png)

**Comment by chemzqm** [comment]
Yournetwork issue

**Comment by electrovoyager** [comment]
Network is working properly. I even searched for this issue over internet before posting this bug as well as tried several times. So it should be something else other than netwrok issue.

**Comment by electrovoyager** [comment]
Also why the autocomplete not starting. It's not even showing. Below screenshot contain the list of plugins I installed using vim-plug manager. So please, refer and tell whether any incompatibility
![Screenshot_20200916_214911](https://user-images.githubusercontent.com/22958419/93364693-7a464680-f866-11ea-9e95-19a3145a86d7.png)
 between these plugins.

**Comment by chemzqm** [comment]
Move cursor to that line or check log
