### ISSUE TITLE
Waiting for your editor to close the file... [coc.nvim] javascript bundle not found, running :call coc#util#install()

### ISSUE THREAD

**Issue by RTS5227** [neoclide/coc.nvim#2353]
## versions

vim version: NVIM v0.4.3
node version: v12.13.0
coc.nvim version: 0.0.79-b71489207a
coc.nvim directory: /home/xxx/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Describe the bug

Everytime i run git commit --amen, i see this error
```
hint: Waiting for your editor to close the file... [coc.nvim] javascript bundle not found, running :call coc#util#install()
Press ENTER or type command to continue
```
![Screenshot from 2020-09-17 10-09-07](https://user-images.githubusercontent.com/4760430/93415540-f031c880-f8cd-11ea-810a-e65ada5eb402.png)

**Comment by fannheyward** [comment]
Use coc.nvim release `Plug 'neoclide/coc.nvim', {'branch': 'release'}`.

**Comment by RTS5227** [comment]
> Use coc.nvim release `Plug 'neoclide/coc.nvim', {'branch': 'release'}`.

I've used it already
Plug 'neoclide/coc.nvim', {'branch': 'release'}

**Comment by fannheyward** [comment]
Remove coc.nvim and PlugInstall again.

**Comment by RTS5227** [comment]
> Remove coc.nvim and PlugInstall again.

I removed and reinstalled coc.nvim but the error is still there.

**Comment by fannheyward** [comment]
Do you have `~/.config/nvim/plugged/coc.nvim/bin/server.js` exists? Remove it and open vim again.

**Comment by RTS5227** [comment]
@fannheyward no, that file doesn't exist.

**Comment by fannheyward** [comment]
Can't reproduce your error.

**Comment by chemzqm** [comment]
`rm -rf ~/.config/nvim/plugged/coc.nvim` and install coc.nvim again.

**Comment by RTS5227** [comment]
I realize I set up vim as git mergetool, so `rm -rf ~/.vim/plugged/coc.nvim` fixes the error.
Sorry for the noise!
