### ISSUE TITLE
Auto Import in Neovim

### ISSUE THREAD

**Issue by lioaslan** [neoclide/coc.nvim#2356]
## Purpose
Auto import with js (ES6)
## Current configuration
```
let g:coc_global_extensions = ['coc-tslint-plugin', 'coc-tsserver', 'coc-css', 'coc-json']
set updatetime=300
set shortmess+=c
set signcolumn=yes

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:show_documentation()
  if (index(['nvim','help'], &filetype) >= 0)
    xecute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```
## Current problem
When the cursor focus on suggestion, I see the function I want to select and import, then I press <tab> but It only turn into the next suggestion.
## What I want
I press <Tab>, it will have a trigger completion and auto import.
________________________________
Thanks

**Comment by chemzqm** [comment]
Read https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources
