### ISSUE TITLE
set complete=~kFILE completion?

### ISSUE THREAD

**Issue by dezza** [neoclide/coc.nvim#2359]
**Is your feature request related to a problem? Please describe.**
I simply wanted to add the names (dh_) from https://manpages.debian.org/buster/debhelper/debhelper.7.en.html to completion.

One of the solutions I found was adding a k-flag to `set complete=` like so
`set complete=k~/vim/dh.txt`

**Describe the solution you'd like**
Completions from `set complete=` k-flags
`set complete=k~/.vim/dh.txt`

**Describe alternatives you've considered**
Make a `/syntax/debrules` file

**Additional context**
I wanted to add this issue, just in case it wasn't already considered, or if `complete=` is partially ignored for coc?

**Comment by chemzqm** [comment]
`complete` option is used by vim's insert completion, not used by coc.nvim,
Install `coc-dictionary` if you wan complete words from files of 'dictionary' option

**Comment by dezza** [comment]
Thanks for clarifying! I appreciate it! First time I'm using dictionaries 👍
