### ISSUE TITLE
Enable preview after completion

### ISSUE THREAD

**Issue by quantum-booty** [neoclide/coc.nvim#2360]
Problem: After selection a completion item using <tab> then <ct>, I don't get any previews.
![image](https://user-images.githubusercontent.com/28958399/93668950-39c61300-fa88-11ea-8a88-01435dea67a0.png)

![image](https://user-images.githubusercontent.com/28958399/93668973-5febb300-fa88-11ea-9b65-d18c06e9b567.png)

If I do not select a completion, instead just type np.array(), I would get the preview window.
![image](https://user-images.githubusercontent.com/28958399/93669038-ddafbe80-fa88-11ea-82ed-662961b83ff0.png)

Is there a setting to enable the latter behaviour after completion?

**Comment by chemzqm** [comment]
Use `autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')`
