### ISSUE TITLE
Lisp extension

### ISSUE THREAD

**Issue by gonced8** [neoclide/coc.nvim#2361]
Is there any extension for Lisp? I'm starting to learn CL and I'd appreciate an extension to help out with completions, etc.

I saw that there is a language server implementation that can be used with VSCode: [cxxxr/cl-lsp](https://github.com/cxxxr/cl-lsp). However, I'm new to using CoC and I don't know if I can simply adapt it and use it or something else.

Thank you for any help you can give!

**Comment by oblitum** [comment]
@gonced8 you can use any language server with coc.nvim, no need for extensions. Check wiki and README about that. If you're new to LSP, [check this blog post](https://samroeca.com/coc-plugin.html).

**Comment by UltiRequiem** [comment]
In case anyone needs the plugin:
https://github.com/UltiRequiem/coc-cl
