### ISSUE TITLE
coc#config("suggest.completionItemKindLabels", ...) doesn't work until coc.nvim has been inited

### ISSUE THREAD

**Issue by tcx4c70** [neoclide/coc.nvim#2362]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8021551
node version: v12.18.3
coc.nvim version: 0.0.79
coc.nvim directory: /home/tcx4c70/.vim/bundle/coc.nvim
term: dumb
platform: linux

## Output channel: explorer


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /home/tcx4c70
fatal: not a git repository (or any of the parent directories): .git
resolved root of /home/tcx4c70/test.py: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /home/tcx4c70
fatal: not a git repository (or any of the parent directories): .git
resolved root of /home/tcx4c70/test.py: undefined
fatal: not a git repository (or any of the parent directories): .git

<so many Error 128, so I remove them except the first one>

## Output channel: Python

Starting Jedi Python language engine.

## Output channel: snippets

[Info 7:56:33 PM] Using ultisnips directories: UltiSnips /home/tcx4c70/.vim/.coc/ultisnips
[Info 7:56:33 PM] Using ultisnips python command: pyx

## Output channel: highlight

[Info  - 7:56:33 PM] Highlight server running in node v12.18.3
```

## Describe the bug

I don't like write configuration in coc-setttings.json, so I configure coc.nvim by coc#config.  In most cases, it works well.  However, I found that coc#config("suggest.completionItemKindLabels", ...) doesn't work until coc.nvim has been inited.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=~/.vim/bundle/coc.nvim
filetype plugin indent on
syntax on
set hidden

let g:coc_data_home = '~/.vim/.coc'

call coc#config("suggest.completionItemKindLabels", {
      \   "keyword": "\uf1de",
      \   "variable": "\ue79b",
      \   "value": "\uf89f",
      \   "operator": "\u03a8",
      \   "function": "\u0192",
      \   "reference": "\ufa46",
      \   "constant": "\uf8fe",
      \   "method": "\uf09a",
      \   "struct": "\ufb44",
      \   "class": "\uf0e8",
      \   "interface": "\uf417",
      \   "text": "\ue612",
      \   "enum": "\uf435",
      \   "enumMember": "\uf02b",
      \   "module": "\uf40d",
      \   "color": "\ue22b",
      \   "property": "\ue624",
      \   "field": "\uf9be",
      \   "unit": "\uf475",
      \   "event": "\ufacd",
      \   "file": "\uf723",
      \   "folder": "\uf114",
      \   "snippet": "\ue60b",
      \   "typeParameter": "\uf728",
      \   "default": "\uf29c"
      \ })
```

- Start (neo)vim with command: `vim -u mini.vim test.py`

- Operate vim.  And the configuration about "suggest.completionItemKindLabels" doesn't work.

- If change `call coc#config(...)` to `autocmd User CocNvimInit call coc#config(...)`, the configuration will work.

- If write the configuration in coc-settings.json, it will work too.

## Screenshots (optional)
The screenshot of `call coc#config(...)`:
![image](https://user-images.githubusercontent.com/16728230/93710567-63f7fd80-fb7a-11ea-9a93-a72546133be0.png)

The screentshot of `autocmd User CocNvimInit call coc#config(...)`:
![image](https://user-images.githubusercontent.com/16728230/93710604-9144ab80-fb7a-11ea-8c07-0f8e0b4cfd9e.png)

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by tcx4c70** [comment]
I'm sorry, but I didn't find a minimal vimrc.  Could you please give me a link?

And I tried to add log when loading the "suggest" configuration like this (I'm new to typescript, so please let me know if I'm wrong):
![image](https://user-images.githubusercontent.com/16728230/93712156-990a4d00-fb86-11ea-9f2b-f754f3229d2c.png)

If I use `call coc#config(...)` in vimrc, I'll get the following log:
![image](https://user-images.githubusercontent.com/16728230/93712321-bd1a5e00-fb87-11ea-8cc6-f3ab59e1d777.png)

However, if I use `autocmd User CocNvimInit call coc#config(...)`, I'll get the similar log twice.  The first one is just as same as former.  And the second one is:
![image](https://user-images.githubusercontent.com/16728230/93712382-24381280-fb88-11ea-9e3e-f867cde7e8df.png)

It seems like that coc#config("suggest.completionItemKindLabels", ...) doesn't take effect before the coc.nvim server has been initialized?

Also, my other configurations work well and they are all configured by coc#config instead of coc-settings.json.

**Comment by oblitum** [comment]
This is finally fixed to work from `init.vim` or `VimEnter`, see  #2611 for resolution. Already in release branch.
