### ISSUE TITLE
Incorrect find and replace with rust-analyzer

### ISSUE THREAD

**Issue by kneasle** [neoclide/coc.nvim#2365]
## Result from CocInfo

```
vim version: NVIM v0.4.3
node version: v12.18.2
coc.nvim version: 0.0.78-449dcad0b2
coc.nvim directory: /home/kneasle/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux
```

## Describe the bug

Suppose we have the following rust file, using `rust-analyzer` as the language server (this only happens with `rust-analyzer` but this is still a bug in `CoC` - see below for more info).

The bug occurs when renaming an identifier that is used multiple times on the same line, as in the following file (`x` will be renamed):

```rust
fn main() {
    let x = 0;
    let longer_variable = 1;
    println!("{} {} {} {} {}", x, longer_variable, x, longer_variable, x);
}
```
and we rename that identifier to something that changes the length (in this case we rename it to `YYYYYYY`) we get the following file:
```rust
fn main() {
    let YYYYYY = 0;
    let longer_variable = 1;
    println!("{} {} {} {} {}", YYYYYY, longer_variaYYYYYYle, x, longer_YYYYYYariable, x);
}
```

`rust-analyzer` has found the instances of `x` (correctly), but `CoC` has has replaced them _by index_ from left to right.  Therefore, it has missed the 2nd instance of `x` by 5 chars and the 3rd instance of `x` by 10 chars and replaced the corresponding parts of the text.  This means that whenever this occurs you have to fix these instances by hand, which usually takes longer than doing a basic text substitution.

### Some information that I think narrows down the cause a lot

I opened [this issue](https://github.com/rust-analyzer/rust-analyzer/issues/6039) in the `rust-analyzer` repository because I thought that it was a problem with `rust-analyzer`.  But what `rust-analyzer` is entirely within the specification of LSP and VS Code apparently does not show this bug (leading me to thing that the bug is in `CoC` instead).

However, one of the maintainers of `rust-analyzer` did inadvertently give me a really useful tidbit that I think narrows down the problem a lot.  They pointed out that `rust-analyzer` returns all the replacements not as one change with many edits but as multiple changes that all reference the same document version (I would copy the JSON from that issue, but it would really clutter things so here's [another link](https://github.com/rust-analyzer/rust-analyzer/issues/6039)).

So I think that the cause of the bug is that the separate changes are being applied one after the other sequentially but not updating in the `range`s in consequent changes.  One solution would be to just apply the changes in reverse order of the range's start column index, but this seems very hacky and the same issue might appear in different circumstances .... someone who knows LSP/CoC better than me probably has a better solution.

## Reproduce the bug

- Rust has to be [installed](https://www.rust-lang.org/learn/get-started) for this to be reproduced
- Make a new empty directory and run `cargo init` to make an empty rust project
- Create file `mini.vim` with:
  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```
- Open `src/main.rs` with (neo)vim using: `vim -u mini.vim src/main.rs`
- Run `:CocInstall coc-rust-analyzer` to install rust-analyzer (and wait for rust-analyzer to compile in the background)
- Replace the contents of `src/main.rs` with the above file
- Attempt to rename `x` with any string longer than 1 char (`YYYYYY` happens to give a nice illustration of the issue).

## P.S.
I'd just like to add that I'm really enjoying CoC - it makes a huge difference to the speed of my workflow and means that I can use neovim like an IDE without consuming my computer.  Thanks for all the hard work making it `:)`.

**Comment by fannheyward** [comment]
coc-rust-analyzer author here, can't reproduce your issue. Please upgrade your coc.nvim to latest version, you're using an outdated coc.nvim.
