### ISSUE TITLE
conflict with xolox/vim-session 

### ISSUE THREAD

**Issue by love4myxsg** [neoclide/coc.nvim#2366]
Maybe coc#insert_key has conflicts with xolox/vim-session .

Before SaveSession! and OpenSession! (which provided by xolox/vim-session).

All seems ok.

But After OpenSession! , then can not input brackets like <>(), even backspace in insert mode.

Tested with Gvim8.2.

But not sure why.

Thanks!

**Comment by chemzqm** [comment]
Use `set sessionoptions-=options` in your vimrc until fix.
