### ISSUE TITLE
coc-list shortcut <C-o> will trigger cursor move to another window in normal mode

### ISSUE THREAD

**Issue by chrisniael** [neoclide/coc.nvim#2368]
## Result from CocInfo

```log
## versions

vim version: NVIM v0.4.4
node version: v12.18.3
coc.nvim version: 0.0.79-d2a3186309
coc.nvim directory: /home/shenyu/.vim/plugged/coc.nvim
term: tmux-256color
platform: linux

## Output channel: snippets

[Info 6:37:27 PM] Using ultisnips directories: UltiSnips /home/shenyu/.config/coc/ultisnips
[Info 6:37:27 PM] Using ultisnips python command: pyx

```

## Describe the bug

In coc-list, using <C-o> to switch from insert mode to normal mode, if I press **again**, cursor will move to the file I am editing. I tried revert the coc.nvim release version to [825f7f5b89fb1708f18711798ef7a2ba6aa1bde5](https://github.com/neoclide/coc.nvim/tree/825f7f5b89fb1708f18711798ef7a2ba6aa1bde5), everything became OK, no matter how many times I press <C-o> in normal mode in coc-list, cursor always in coc-list.

## Reproduce the bug

Using latest release version of coc.nvim, trigger coc-list(using shortcut to call <Plug>(coc-references)), make coc-list be in normal mode, than press shortcut <C-o> **again**.

**Comment by chemzqm** [comment]
It's feature, you can remap it
