### ISSUE TITLE
Create Directory Of A File When Opened

### ISSUE THREAD

**Issue by brunoczim** [neoclide/coc.nvim#2371]
One of rust-analyzer's auto fix is that it opens a buffer with a path of a module that does not exist. It does not create parent directories! However, LSP doesn't mandate the plugin to do that. So, an error happens when I try to autofix a missing module.

I would like Coc to create parent directories when a LSP plugin asks to open a file.

If I understood the Coc code correctly, another alternative would be to simply not to write the file using node API, but with (Neo)Vim API, so users could use Vim hooks like `BufWritePre`.

See rust-analyzer/rust-analyzer#6040 for steps to reproduce the problem.

**Comment by chemzqm** [comment]
Does VSCode create directory for this case?

**Comment by brunoczim** [comment]
Yes
