### ISSUE TITLE
floating hover message's scroll bar

### ISSUE THREAD

**Issue by sa82trip** [neoclide/coc.nvim#2372]
**Is your feature request related to a problem? Please describe.**
First of all, im huge fan of coc nvim. 
here is a small problem on my coding routine.
when i see hover message i can't see full document of it.
vscode's hover message floating window has scrollbar so I can see full document.

**Describe the solution you'd like**
able to move hovering window so i can move around with hjkl
or it is also good to be able to see hovering message in one specific register.

thanks in advance!

**Additional context**
![image](https://user-images.githubusercontent.com/38380280/93844253-87848a80-fcd7-11ea-8be2-02eca1c50de6.png)
vscode's hovering message has scrollbar in it so I can see full document.
![image](https://user-images.githubusercontent.com/38380280/93844271-966b3d00-fcd7-11ea-93ef-614887649e25.png)

**Comment by fannheyward** [comment]
`C-ww` move your cursor to floating window, then you can use hjkl.

**Comment by chemzqm** [comment]
Vim's popup support scrollbar, not neovim as far as I know.

**Comment by sa82trip** [comment]
> `C-ww` will move your cursor to floating window, then you can use hjkl.

thanks!! this is very nice tip!

**Comment by sa82trip** [comment]
> Vim's popup support scrollbar, not neovim as far as I know.

scrollbar is not needed if I can move around with hjkl.
thanks!!

**Comment by oblitum** [comment]
@sa82trip check [this tip](https://github.com/neoclide/coc.nvim/issues/1405#issuecomment-626998607) for floating scroll without leaving insert mode.
