### ISSUE TITLE
feat: support intellicode

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc.nvim#238]
**Is your feature request related to a problem? Please describe.**

No, it’ just very cool to have.

**Describe the solution you'd like**

using AI to augment auto completion with IntelliCode

MS just releases IntelliCode extension for VSCode.

https://blogs.msdn.microsoft.com/typescript/2018/12/05/intellicode-for-typescript-javascript/

I think coc could use vscode extension so I wonder if we could use IntelliCode in coc.
**Describe alternatives you've considered**

**Additional context**

**Comment by iamcco** [comment]
it seems cool

**Comment by chemzqm** [comment]
Unfortunately, both the extension and server code are not open sourced, there's only a repo with documentation.
We can still make use of that service by use the javascript code from extension, but I don't know whether the policy allows.

**Comment by chemzqm** [comment]
It's not allowed by intellicode https://github.com/MicrosoftDocs/intellicode/issues/31.

If you want to use this, use VSCode or Visual Studio, closing.
