### ISSUE TITLE
Can't chain commands after CocUpdate

### ISSUE THREAD

**Issue by marekdedic** [neoclide/coc.nvim#2380]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.4
node version: v13.14.0
coc.nvim version: 0.0.79-4f35a557af
coc.nvim directory: /home/user/.vim/plugged/coc.nvim
term: screen-256color
platform: linux
```

## Describe the bug

Hi, I cannot chain vim commands after `CocUpdate` in the same way as other commands (see https://vim.fandom.com/wiki/Multiple_commands_at_once)

## Reproduce the bug

1. Open vim
2. Type `:CocUpdate | qa`
3. I'd expect this to update CoC extensions and quit vim, it does neither and complains about `E488: Trailing chcaracters`

**Comment by chemzqm** [comment]
Use CocUpdateSync https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#update-extensions

**Comment by marekdedic** [comment]
Thanks, that solves my problem. On the other hand, shouldn't even `CocUpdate` not break vim piping?

**Comment by chemzqm** [comment]
It's designed to be async.

**Comment by marekdedic** [comment]
Yeah, I understand that, but even so, I could imagine wanting to start it and the run another command while it's running...
