### ISSUE TITLE
coc-references is missing legitimate references

### ISSUE THREAD

**Issue by aidos** [neoclide/coc.nvim#2381]
## Result from CocInfo

````
  ## versions

  vim version: NVIM v0.5.0-dev
  node version: v12.18.3
  coc.nvim version: 0.0.79
  coc.nvim directory: /home/vagrant/.config/nvim/plugged/coc.nvim
  term: xterm-256color
  platform: linux

  ## Output channel: tsserver

  [Info  - 11:53:31 AM] Forking TSServer
  PATH: /home/vagrant/.cargo/bin:/home/vagrant/.local/bin:/usr/local/lib/npm/bin:/home/vagrant/.cargo/bin:/home/vagrant/.local/bin:/usr/local/lib/npm/bin:/usr/local/sbin:/usr/local/
  bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  [Info  - 11:53:31 AM] Started TSServer
  {
    "path": "/var/www/countfire/rapidtender/frontend/node_modules/typescript/lib",
    "_api": {
      "versionString": "4.0.2",
      "version": "4.0.2"
    }
  }
````

## Describe the bug

I've found that `coc-references` is missing some of the references (for me this is on ts-server, but it's probably a more general issue). I've tracked it down to a mismatch in the way the language server defines a definition (`isDefinition`) and the switch that is used in the coc context (`includeDeclaration: false`) that then skips those references.

Flipping this flag makes the issue go away (with the sideffect that you also see the original declaration in the listing too). 

https://github.com/neoclide/coc.nvim/blob/128aff220afec5434099e5918331e85e4e16a527/src/handler/index.ts#L428

Is ts-server wrong by making these as definitions? Or is coc being too aggressive in stripping these down? I'm not sure who is at fault here as I don't really know the spec at all, but whatever the case, pragmatically, this seems like flipping that flag is the best approach to make sure that people aren't missing out on important refs (I'm deep in some refactoring work at the moment and this has tripped me up).

## Reproduce the bug

A simple test to demonstrate the issue

```
class Test {
  // gotoRefs on here
  find_me() {
  }
}
const t = new Test()

// this one is found
const found = t.find_me

// this won't be found
const { find_me } = t
```

Logging from ts-server demonstrates that they are marking the final line as `isDefinition:true`

```
{
  "seq": 0,
  "type": "response",
  "command": "references",
  "request_seq": 24,
  "success": true,
  "body": {
    "refs": [
      {
        "file": "/ref.ts",
        "start": {
          "line": 2,
          "offset": 3
        },
        "end": {
          "line": 2,
          "offset": 10
        },
        "contextStart": {
          "line": 2,
          "offset": 3
        },
        "contextEnd": {
          "line": 3,
          "offset": 4
        },
        "lineText": "  find_me() {",
        "isWriteAccess": true,
        "isDefinition": true
      },
      {
        "file": "/ref.ts",
        "start": {
          "line": 8,
          "offset": 17
        },
        "end": {
          "line": 8,
          "offset": 24
        },
        "lineText": "const found = t.find_me",
        "isWriteAccess": false,
        "isDefinition": false
      },
      {
        "file": "/ref.ts",
        "start": {
          "line": 11,
          "offset": 9
        },
        "end": {
          "line": 11,
          "offset": 16
        },
        "contextStart": {
          "line": 11,
          "offset": 1
        },
        "contextEnd": {
          "line": 11,
          "offset": 22
        },
        "lineText": "const { find_me } = t",
        "isWriteAccess": true,
        "isDefinition": true
      }
    ],
    "symbolName": "find_me",
    "symbolStartOffset": 3,
    "symbolDisplayString": "(method) Test.find_me(): void"
  }
}
```

**Comment by aidos** [comment]
Just had a quick shifty at the official spec and it looks like we can forward the `includeDeclaration` over to the language server to handle, rather than trying to implement after the fact in coc.

(Again, I'm no expert here)

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_references

**Comment by chemzqm** [comment]
Changed to make it same as VSCode.

**Comment by aidos** [comment]
Awesome! Thanks @chemzqm. I noticed that the ordering often isn’t ideal. I might submit a PR to change it so the reference you’re on is pushed down the list (if there’s enough context to make it easy).

**Comment by ingjieye** [comment]
Is there a way to set the includeDeclaration to false on configurations?
