### ISSUE TITLE
有替换 yarn --install 的安装方式吗？

### ISSUE THREAD

**Issue by xaljer** [neoclide/coc.nvim#2383]
**Is your feature request related to a problem? Please describe.**
更新到79版本之后，`coc#add_extension` 应该也是换用 `yarn --install` 来安装插件了是吧？但是感觉这个对网络环境要求比较高，我几次尝试都无法运行成功。
是否有采用原有方式的命令呢？同时又希望是 `coc#add_extension` 这种可以写在 vimrc 中的方式，因为这样方便一两个个文本就维护自己的所有的vim环境。
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
Read wiki https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#install-extensions

**Comment by xaljer** [comment]
@chemzqm 我还是有一点没弄懂，我现在vimrc没有配置任何安装coc插件的方式，但是启动还是会运行这个：
![image](https://user-images.githubusercontent.com/8309631/94336664-5c6fa300-0017-11eb-86cd-256aef31ee7d.png)
这个是在更新插件，还是coc本身需要再安装一些东西？

**Comment by chemzqm** [comment]
v0.0.79 的问题，升级最新的 release 分支

**Comment by xaljer** [comment]
我更新到最新的release分支，还是会有这样的问题。

**Comment by chemzqm** [comment]
不要用 tag

**Comment by xaljer** [comment]
可以了，谢谢~
