### ISSUE TITLE
let g:loaded_python_provider = 0 is not work.

### ISSUE THREAD

**Issue by CalmFireVV** [neoclide/coc.nvim#2385]
I am not use python2 and ruby, so I set 
let g:loaded_python_provider = 0
let g:loaded_ruby_provider = 0 
but let g:loaded_python_provider = 0 is not work, and let g:loaded_ruby_provider = 0 work.
"checkhealth": python2 provider is error and ruby`s is disabled.

**Comment by chemzqm** [comment]
Not coc.nvim related
