### ISSUE TITLE
[coc.nvim] hover not found & doHover flashing after recent update

### ISSUE THREAD

**Issue by distek** [neoclide/coc.nvim#2386]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-625-g602e7505e
node version: v14.11.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/distek/.config/nvim/plugged/coc.nvim
term: xterm-termite
platform: linux
```

## Describe the bug

Originally noticed on my Macos box after a PlugUpdate. Two things have started happening.
Recent update seems to have brought this about as it wasn't happening on my Linux box, which I use less frequently than my Macos box.

Confirmed it was not happening on my Linux box until after a PlugUpdate on there as well, in which coc was updated.

Issue 1:
```
[coc.nvim] hover not found
```
This message is consistently present when a buffer is open. For me, this is while writing in Go. My buddy also has this happen when he's writing in python as well, but not in Go.

I wouldn't mind the message if it wasn't always present, but it ends up writing over other messages that may pop up in the status line.

Issue 2:
The highlight used for `doHover` flashes constantly. It's every update cycle as determined by `set updatetime=300`, but the "on" time varies wildly. Sometimes almost instant, sometimes for near the entire update cycle. If I set the doHover call to this, it only comes on and off once:
```autocmd CursorHold * silent call CocAction('doHover')```
as opposed to what I used to have:
```autocmd CursorHold * silent call CocActionAsync('doHover')```

## Reproduce the bug
mini.vim:
```set nocompatible
set runtimepath^=/home/distek/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

set updatetime=300
autocmd CursorHold * silent call CocActionAsync('doHover')
```
With only the extention `coc-go` installed.

## Screenshots (optional)

![coc](https://user-images.githubusercontent.com/49327592/94344001-fb24e100-ffd0-11ea-8dd3-80d8e27a713d.gif)

**Comment by chemzqm** [comment]
It's expected, avoid call `'doHover'` with `CursorHold`

**Comment by chemzqm** [comment]
There might be silent option in the feature.

**Comment by chemzqm** [comment]
Use `"coc.preferences.messageLevel": "error"` to avoid warning message.

**Comment by distek** [comment]
> Use "coc.preferences.messageLevel": "error" to avoid warning message.

That helps. Thank you.

Regarding the flashing - Is there a reason why this only recently started to occur?

**Comment by chemzqm** [comment]
The warning for doHover added recently.
