### ISSUE TITLE
Can't easily list available coc extensions

### ISSUE THREAD

**Issue by jpear1** [neoclide/coc.nvim#2389]
I just installed coc, and I'm planning on mainly using extensions because I don't want to mess with config files.

A couple of example extensions are given in the installation guide, but I can't find a complete list anywhere. It would be nice to have a command like `:CocInstall --list` or something that would tell me all available extensions.

**Comment by fannheyward** [comment]
Use https://github.com/fannheyward/coc-marketplace#coc-marketplace

**Comment by jpear1** [comment]
Maybe this could be mentioned in the docs somewhere.
