### ISSUE TITLE
occur error after leave insert mode when edit vim file

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#239]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

**Describe the bug**

occur error after leave insert mode when in autocomplete.

**To Reproduce**

1. nvim test.vim
2. call sub$
3. the $ is cursor, then type \<Esc\>

**Screenshots**

<img width="463" alt="2018-12-07 2 13 49" src="https://user-images.githubusercontent.com/5492542/49630886-fa514280-fa2a-11e8-96ca-13a9bc8633a8.png">

**Comment by iamcco** [comment]
this is the record: https://asciinema.org/a/orjYz1w0xS3h2cswdAN8pvpKN

**Comment by chemzqm** [comment]
It should be error from other plugin, since `nvim_buf_clear_namespace` never called by coc.

**Comment by iamcco** [comment]
i have update origin description that `<Esc>` become an html tag

**Comment by iamcco** [comment]
OK, i seems echodoc.vim's error
