### ISSUE TITLE
Unknown option  "jsxSingleQuote" with value false was found. 

### ISSUE THREAD

**Issue by josiahmokob0** [neoclide/coc.nvim#2391]
my vimrc
`nmap <leader>f  <Plug>(coc-format-selected)`

## Describe the bug

Gives me this warning whenever I try to format selected text

```
[coc.nvim]: ● Validation Warning:   Unknown option  "jsxSingleQuote" with value false was found. 
  This is probably a typing mistake. Fixing it will remove this message.
```

PS: I can't find `jsxSingleQuote` option on coc-settings.json

## Reproduce the bug
 running the format command when text is selected

**Comment by chemzqm** [comment]
Should be problem of your tsconfig.json
