### ISSUE TITLE
Please add an option to insert the common part of the completion suggestion

### ISSUE THREAD

**Issue by necrosovereign** [neoclide/coc.nvim#2392]
I often have several items that begin with a long common sequence of letters. For example, if I have variables "vertex1", "vertex2", "vertex3", "vertex4", "vertex5", "vertex6" (simplified example), to insert "vertex6", I have to type "ver" and press <Tab> 6 times.
It would be nice if I could press <Tab> to insert "vertex" and then type the rest of the name

**Comment by chemzqm** [comment]
Why not just type 6? It's fuzzy match

**Comment by necrosovereign** [comment]
Can you please explain what does fuzzy match means exactly? Or point me to where in the documentation it's explained?

**Comment by fannheyward** [comment]
https://en.wikipedia.org/wiki/Fuzzy_matching_(computer-assisted_translation)
