### ISSUE TITLE
The 'statusline' leaks outside the lists

### ISSUE THREAD

**Issue by psprint** [neoclide/coc.nvim#2394]
## Result from CocInfo

<details>
<pre>
## versions

vim version: VIM - Vi IMproved 8.2 8021743
node version: v14.8.0
coc.nvim version: 0.0.79
coc.nvim directory: /root/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vimrc: undefined
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /root/.vim
fatal: not a git repository (or any of the parent directories): .git
resolved root of /root/.vim/coc-settings.json: undefined

## Output channel: snippets

[Info 06:07:42] Using ultisnips directories: UltiSnips /root/.config/coc/ultisnips
[Info 06:07:42] Using ultisnips python command: pyx

## Output channel: vimlsp

[Error  - 06:08:38] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'getGlobalFunctions' of undefined
  Code: -32603 
</pre>
</details>

## Describe the bug

I set a custom statusline, however it's overridden by coc when I:

a. Press `<C-O>` while in a list, to get to normal
b. Press `<C-W>k`, `<C-W>w`, etc. to move to the buffer for a moment.

Then the statusline of the buffer will be changed to:

![2020-09-28-063415_1198x463_scrot](https://user-images.githubusercontent.com/6049288/94391204-351ef000-0155-11eb-91d7-5ca688b717d5.png)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

a. Start any list, e.g.: `:CocList`
b. Press `<C-O><C-W>w`, then `<C-W>w`.
c. Observe the outside status line changing.
d. Close with `<ESC>` to prove that the change is permanent.

**Comment by psprint** [comment]
An [asciicast](https://asciinema.org/a/An3G3uMYMLo0Zom0bYyEZQDP4) presenting the problem.

**Comment by chemzqm** [comment]
Can't reproduce, coc.nvim set `statusline` option for window of CocList only.

**Comment by chemzqm** [comment]
Try minimal vimrc.
