### ISSUE TITLE
wrong snippet

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#240]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

**Describe the bug**

wrong snippet

**To Reproduce**

```javascript
import React from 'react'

class App extends React.Component {
  did$
}
```

`$` is cursor, select `componentDidMount` snippet, it replace with `dcomponentDidMount()`

**Screenshots**

https://asciinema.org/a/Op1l3CmLqreCcQ5VneGmBiNKI

**Comment by chemzqm** [comment]
Can't reproduce, please paste output from `:CocInfo` including output from tsserver.

**Comment by iamcco** [comment]
cocinfo: https://gist.github.com/iamcco/d22d4553501828e5dfcf8ff9f7d9ec70

tsserver output: https://gist.github.com/iamcco/25bcaaa6b2073ac7016169dce4cc64f2

**Comment by chemzqm** [comment]
Try `:CocInstall coc-tsserver`, it's fixed for increment complete.

**Comment by iamcco** [comment]
resolve after reinstall coc-tsserver
