### ISSUE TITLE
only maping  when some coc-language is enable

### ISSUE THREAD

**Issue by jiahut** [neoclide/coc.nvim#2403]
I had installed `coc-go`  extensions, and config  `gd` blew

```
nmap <silent> gd <plug>(coc-definition)
```
but when I `gd` in  vimrc

it repot:

```
[coc-vim] Definition provider not found for current document
```

I just  only  install `cocInstall coc-go`, and just want only this.

so How can I implement that only the `coc-go`  is staring, the `gd` map to `<plug>(coc-definition) , otherwize back to default behavior (`gd` work well on any other case )

 I know `coc-vimlsp` I just do not want this.

**Comment by chemzqm** [comment]
Create buffer keymapping instead
