### ISSUE TITLE
CocHighlightText doesn't work very well

### ISSUE THREAD

**Issue by GGCristo** [neoclide/coc.nvim#2405]
## versions

vim version: VIM - Vi IMproved 8.2 8021634
node version: v14.9.0
coc.nvim version: 0.0.79-6cb5c6cd2d
coc.nvim directory: /home/cristo/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Describe the bug
This is the minimal configuration I have used.
```
" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')
hi CocHighlightText ctermfg=black ctermbg=72 guifg=black guibg=#689d6a
hi CoCHoverRange ctermfg=black ctermbg=72 guifg=black guibg=#689d6a
```
\+ the configuration in the README.

When I call showDocumentation(), the highlight never get updated, this mean that is still highlighted even if I move trough the text.

+Another bug, but less important.
```
vector.push_back(2);
std::cout << "Hello";
```
My cursor is in the "push_back()" method, everything work fine, if I jump to the word "cout" its still work, but if I jump to something that doesn't have a documentation for example "<<" my previous word (in this case "push_back()") it is still highlighted, I need to do an extra move (let's say move to the left) in order to get update.

**Comment by chemzqm** [comment]
Can't reproduce, upgrade your coc.nvim

**Comment by GGCristo** [comment]
Hi, sorry for the late response I was kind of busy with college.
Debugging I found out the problem. If I use CoCHoverRange the highlight doesn't update it state, but if I use CocHoverRange everything works fine.
