### ISSUE TITLE
Alternative escape sequence for CocList

### ISSUE THREAD

**Issue by knpwrs** [neoclide/coc.nvim#2406]
**Is your feature request related to a problem? Please describe.**

I use `jk` to escape insert mode as such:

```
"" Use jk as escape sequence
imap jk <Esc>
```

It seems like the only way I can escape from `CocList` (or subcommands like `CocList outline`) is to press <Esc> directly.

**Describe the solution you'd like**

I would like to be able to define another escape sequence for `CocList`.

**Describe alternatives you've considered**

I've searched and haven't found anyone else discussing this. Am I missing existing functionality?

**Comment by chemzqm** [comment]
`:h coc-list-mappings-custom` you can't use key combination.

**Comment by knpwrs** [comment]
Cool, I set up the following to map `<C-d`>:

```json
  "list.insertMappings": {
    "<C-d>": "do:exit"
  }
```

**Comment by chemzqm** [comment]
You may need to set `list.normalMappings` as well.
