### ISSUE TITLE
help wanted: While formating, how do I change the max number of characters allowed in a line?

### ISSUE THREAD

**Issue by nishantpratimdas** [neoclide/coc.nvim#2408]
I want to increase the maximum number of characters in a line. By default, the 'formatter' just puts the rest of the code in a new line when this maximum number of characters in crossed.

**Comment by chemzqm** [comment]
Configure the formatter you're using

**Comment by nishantpratimdas** [comment]
I am not using anything other plugin for formatting. I use :Format which calls CocAction('format')

**Comment by nishantpratimdas** [comment]
> Configure the formatter you're using

I am not using any other plugin for formatting. I use :Format which calls CocAction('format') as described in the readme.

**Comment by chemzqm** [comment]
The function would invoke formatter used by your language server, you need checkout doc of your language server.
