### ISSUE TITLE
How do I close the documentation floating window while in insert mode without escaping to normal mode?

### ISSUE THREAD

**Issue by sdkjgigoqeut** [neoclide/coc.nvim#2409]
How do I make the floating window disappear?
Not permanently, I don't want to completely disable it.
Just to close it while in insert mode.
![float](https://user-images.githubusercontent.com/72260472/94935981-604b6b80-04d6-11eb-9818-ae4529273b90.png)

**Comment by sdkjgigoqeut** [comment]
create an insert mode mapping to call coc#util#close_floats()

something like inoremap <silent><expr> <c-o> coc#util#close_floats() ? '' : ''

The characters after the function are to override vim's behavior of returning 0 in the buffer

**Comment by oblitum** [comment]
`coc#util#float_hide()` seems a more appropriate, more specific, API for this job.
