### ISSUE TITLE
coc-references works, but enter no longer opens file.

### ISSUE THREAD

**Issue by dessalines** [neoclide/coc.nvim#2410]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8021704
node version: v14.13.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/xxx/.vim_runtime/my_plugins/coc.nvim
term: dumb
platform: linux

## Output channel: Rust Analyzer Language Server Trace

[ERROR rust_analyzer::main_loop] duplicate DidOpenTextDocument: files here
[ERROR rust_analyzer::main_loop] duplicate DidOpenTextDocument: 
[ERROR rust_analyzer::main_loop] duplicate DidOpenTextDocument:
[ERROR rust_analyzer::main_loop] duplicate DidOpenTextDocument:
[ERROR rust_analyzer::main_loop] duplicate DidOpenTextDocument: 
```

## Describe the bug

Doing `gr` does find the references, but pressing enter on an item no longer opens the file, it simply selects the next item in the list.

## Reproduce the bug

Install coc.nvim, try to find references, press enter on one.

**Comment by pheeria** [comment]
I have the same problem with ts-server, iTerm2 and Vim 8.2 with the latest master of coc.nvim.

**Comment by wilhelmeek** [comment]
Reinstalling the plugin fixed the problem for me.

**Comment by chemzqm** [comment]
We need connection log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc, save your vimrc and exit vim.
* Restart your vim/neovim to make the issue happen.
* Get the log filepath by :echo $NODE_CLIENT_LOG_FILE
* Attach the log file or paste content from the log.

**Comment by chemzqm** [comment]
Try minimal vimrc and checkout `:echo g:coc_enable_locationlist`, `0` means you have disabled location list of coc.nvim.

**Comment by chemzqm** [comment]
Most likely you're using other's vimrc from github, and the author decided not use location list of coc.nvim.

**Comment by dessalines** [comment]
Thanks @wilhelmeek , doing a `git pull && yarn` fixed the problem for me with the newest vim.
