### ISSUE TITLE
Add ":CocStop" command

### ISSUE THREAD

**Issue by hasufell** [neoclide/coc.nvim#2413]
**Is your feature request related to a problem? Please describe.**

coc.nvim spawns processes that can take several GB of ram. The only way to completely shut such process down is closing the entire editor and losing my work or killing the process manually, which is error prone and bad UI.

**Describe the solution you'd like**

A command `:CocStop`, the opposite of `:CocStart`.

**Additional context**

https://github.com/neoclide/coc.nvim/issues/1606

I am not using additional extensions.

**Comment by fannheyward** [comment]
Try `CocRestart`.

**Comment by hasufell** [comment]
@fannheyward how is that related? I want to **stop** the server, when I'm done coding. Not restart it.

**Comment by oblitum** [comment]
Agreed that `CocRestart` won't help for that.

**Comment by chemzqm** [comment]
Use coc#rpc#stop function

**Comment by hasufell** [comment]
> Use coc#rpc#stop function

Then it should be easy to add this as a dedicated command. So would someone reopen this ticket?

**Comment by chemzqm** [comment]
No, you have to create that command

**Comment by hasufell** [comment]
> No, you have to create that command.

Aha, so why have `CocStart` command then?? It took me 2 days to get an answer to this question. This isn't good UI.

**Comment by chemzqm** [comment]
Because user could disable coc.nvim auto start, I don't think CocStop is needed

**Comment by hasufell** [comment]
What an awful reasoning. This plugin may eat multiple GB of memory and the authors think the user shouldn't have an easy way to stop all processes if needed.

**Comment by oblitum** [comment]
@hasufell it's not the plugin that eat GBs though, it's the servers.

**Comment by oblitum** [comment]
@hasufell in all these years of coc.nvim, I've rarely seen a need for this personally, or a request by others. If you got into the situation that you want the servers to terminate, you most likely will wish an emergency mapping for that instead of going about to execute a command. Given that and that Coc won't provide built-in mappings, you'll have to write on anyways, so just write one and simply call `coc#rpc#stop`. Having a command here isn't much relevant.

**Comment by oblitum** [comment]
> Because user could disable coc.nvim auto start

A <PLUG> mapping seems more relevant to have, see above.

**Comment by chemzqm** [comment]
You should use CocRestart

**Comment by chemzqm** [comment]
That command is useless since user would receive errors all the time when they have autocmds
