### ISSUE TITLE
An action for toggling the preview window in CocList

### ISSUE THREAD

**Issue by eulertour** [neoclide/coc.nvim#2418]
**Is your feature request related to a problem? Please describe.**
When using CocList on a source that allows the preview action there is no action to toggle the preview window. `action:preview` will open the preview window but repeating the action will not close it.

**Describe the solution you'd like**
An action to toggle the preview window.

**Describe alternatives you've considered**
Using the `p` shortcut from normal mode toggles the preview window, but it means that closing the preview window from insert mode requires switching to normal mode, toggling the window, and switching back, which is slow.

**Comment by chemzqm** [comment]
You can create custom keymappings

**Comment by eulertour** [comment]
The point of this request is that there's no action that closes the preview window. There's nothing to map the key to.

**Comment by chemzqm** [comment]
action:preview should toggle preview

**Comment by eulertour** [comment]
It currently doesn't. The `p` key will toggle the preview window _by default_, but `action:preview` will only open the preview window.

**Comment by eulertour** [comment]
Were you able to confirm or at least check whether this problem exists?
