### ISSUE TITLE
How to implement config to run after plugin extensions get registered? 

### ISSUE THREAD

**Issue by unphased** [neoclide/coc.nvim#2426]
I have added a call to a function of mine in `~/.vim/after/plugin/coc-nvim.vim` which I confirmed nevoid is running. It produces this error: 
```
Error on request (activeExtension): Vim(return):Error invoking 'activeExtension
' on channel 5:
Extension coc-tabnine not registered!
Press ENTER or type command to continue
```
This is trying to run a function of mine which calls `CocAction('activeExtension', 'coc-tabnine')`.

So it looks like this is after the coc plugin itself is loaded (good), but I know that it runs in an async job and also has to do some work before the coc extensions load, so it is not surprising that the coc-extension is not registered as of this time yet.

As the after/plugin/*.vim config file is the standard way to implement something that depends on a plugin, what would be the most sane way to implement something that depends on an extension being registered?

**Comment by unphased** [comment]
Meanwhile for others with this problem, the workaround of 

    autocmd VimEnter * call timer_start(200, "CheckBatteryTabNine")

is working well. just make sure your function takes a single timer arg

**Comment by chemzqm** [comment]
`:h CocNvimInit`

**Comment by unphased** [comment]
Thanks. I tried the following combinations in both after/plugin/coc-nvim.vim and in the regular config, and none of the 10 worked. Going to stick with my 200ms deferred timer.

**Comment by chemzqm** [comment]
You can write single file coc.nvim extension so you can events from `extensions module`.
