### ISSUE TITLE
how to offline install coc.nvim on windows64

### ISSUE THREAD

**Issue by physicistgeng** [neoclide/coc.nvim#2434]
how to offline install coc.nvim on windows64.

**Comment by chemzqm** [comment]
* Download zip from https://github.com/neoclide/coc.nvim/archive/release.zip
* Copy zip to your computer and extract it.
* Add extracted folder `coc.nvim-release` to your vim's `runtimepath` or use vim's package feature.

**Comment by SebastianBehrens** [comment]
> Add extracted folder coc.nvim-release to your vim's runtimepath or use vim's package feature.

Does adding to vim's runtime path means placing it in `vimfiles/pack/plugins/start/` ?
