### ISSUE TITLE
Completion window to the left of cursor near edge of window

### ISSUE THREAD

**Issue by flimofly** [neoclide/coc.nvim#2435]
**Is your feature request related to a problem? Please describe.**
When the completion window is used near the right edge of the nvim window, a big chunk of the info cannot be read.

Compare: 
<img width="1045" alt="Screenshot 2020-10-10 at 20 12 51" src="https://user-images.githubusercontent.com/20085376/95662154-2b25c580-0b35-11eb-90b3-1814afcc757e.png">
with:
<img width="1022" alt="Screenshot 2020-10-10 at 20 13 40" src="https://user-images.githubusercontent.com/20085376/95662157-30831000-0b35-11eb-9f58-9dfe3941964c.png">

**Describe the solution you'd like**
Completion window should then pop up to the left of the cursor rather than to the right.

**Describe alternatives you've considered**
Making the window larger and limit the number of characters per line works but is inelegant when using different windows side by side.

**Comment by chemzqm** [comment]
Completion window is pisitioned by vim, consider limit pum width

**Comment by flimofly** [comment]
Thanks. And in nvim? Is it a floatwin or also a pum?

**Comment by chemzqm** [comment]
Yes, you can use `"suggest.labelMaxLength"` configuration.
