### ISSUE TITLE
Error on list create: request error nvim_call_function: Invalid scroll size

### ISSUE THREAD

**Issue by lioaslan** [neoclide/coc.nvim#2438]
## Result from CocInfo
vim version: NVIM v0.4.3
node version: v12.19.0
coc.nvim version: 0.0.79-8a5b4b2f92
coc.nvim directory: /home/leo/.config/nvim/bundle/coc.nvim
term: xterm-256color
platform: linux

## Describe the bug

`[coc.nvim] Error on list create: request error nvim_call_function - Vim(set):E49: Invalid scroll size: scroll = 10`

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Install vim-floatterm, coc.nvim
- Run command `CocInstall coc-floaterm`
- Run `:FloatermNew` x 5 times to create 5 floaterm
- Run `:FloatermToggle` to hide all floaterm
- Run `CocList floaterm` and then show that error. I can't press any key except killing terminal to close Vim.
You can see more about my neovim configure here:  https://github.com/lioaslan/nvim

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/24852182/95672096-134b5180-0bc8-11eb-8e76-a3bee6ae5801.png)

**Comment by chemzqm** [comment]
Should be bug of coc-floaterm

**Comment by chemzqm** [comment]
I've tried nvim 0.4.3, can't reproduce.
