### ISSUE TITLE
[coc.nvim] Invalid position for rename

### ISSUE THREAD

**Issue by weishenl6y6n** [neoclide/coc.nvim#2439]
你好，在我给py文件重命名变量的时候，会出现[coc.nvim] Invalid position for rename这个报错。
我的版本信息
version: NVIM v0.4.4
node version: v14.11.0
coc.nvim version: 0.0.79-d2a3186309

**Comment by chemzqm** [comment]
Language server doesn't support rename on cursor position

**Comment by weishenl6y6n** [comment]
> cursor position

so how can I use cog-rename to rename my function name?

**Comment by weishenl6y6n** [comment]
<img width="294" alt="image" src="https://user-images.githubusercontent.com/65407708/95677978-f7fa3980-0bfb-11eb-815e-dbee6e55e615.png">
I just rename it like this. I think it should worked, but raise error

**Comment by weishenl6y6n** [comment]
I use coc-python and I can rename it before, so I feel confused

**Comment by weishenl6y6n** [comment]
I install coc-jedi then it fixed!!!
