### ISSUE TITLE
Tried to download coc.nvim ub

### ISSUE THREAD

**Issue by idoSinai** [neoclide/coc.nvim#2440]
Hey, I added to vim-plug/plugins.vim the following:

" Stable version of coc
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Keeping up to date with master
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}

After trying :PlugInstall everytime I open nvim I receive the error:
"javascript bundle not found, please try :call coc#util#install()"

What can I do in order to solve it? thanks for the helpers

**Comment by chemzqm** [comment]
Remove folder of coc.nvim and install again.
