### ISSUE TITLE
How to manually disable and enable CoC?

### ISSUE THREAD

**Issue by pvonmoradi** [neoclide/coc.nvim#2442]
Thanks for all your efforts developing this awesome plugin :heart: 
I'm a little confused about some options.   
1. What is the optimal and recommended way to disable CoC completely on every file and enable it manually?  
2. What is the difference between CocEnable (Disable) and CocStart (Stop)?  
3. Why CocStop feature was removed recently?  

Note that CocDisable does **not** kill the processes (nodejs and clangd for example). It just detaches vim from CoC services. 
My confusion stems from the fact that there are 2 implementations for an action:    
- Enable and Start -> Coc plugin is enabled , LSP processes are spawned
- Enable and Stop ->  Coc plugin is enabled , LSP processes are killed (Stop not implemented)
- Disable and Start ->Coc plugin is disabled, LSP processes are spawned 
- Disable and Stop ->Coc plugin is disabled, LSP processes are killed (Stop not implemented)

Currently I'm doing it like this:  
```vim
" CoC configurations
Plug 'neoclide/coc.nvim', {'branch': 'release'}
" CoC plugin dependencies
Plug 'kevinoid/vim-jsonc'

" stop CoC by default (but Coc is enabled)
let g:coc_start_at_startup=0
" manually start CoC
nmap <leader>cc :<C-u>CocStart<CR>
" manually stop CoC

" CoC extensions
let g:coc_global_extensions = [
    \ "coc-clangd",
    \ 'coc-vimlsp'
    \ ]
" CoC related vim configs
" ...
```

**Comment by chemzqm** [comment]
`:h g:coc_process_pid` you can kill process of coc.nvim, or stop it by use function `coc#rpc#stop()` to stop it.

**Comment by pvonmoradi** [comment]
@chemzqm 
`coc#rpc#stop()` indeed kills both Coc node process and the LSP process (and was the binding I was using before) but:   
1- It throws this error at the statusbar:  `client coc abnormal exit with: -1` Is this expected for manual shutdown?
2- Plugins like Airline still reporting that the LSP exist. So I'm guessing it was not shut down cleanly? or is it so the plugin can't detect that Coc service was terminated (hence not a Coc problem)?

**Comment by chemzqm** [comment]
>  Is this expected for manual shutdown?

Yes.

> Plugins like Airline still reporting that the LSP exist.

Should not problem of coc.nvim.

**Comment by gianarb** [comment]
Hello!

I am playing with neovim those days and copilot, for this reason I want to disable coc when I am using it:

```

if has('nvim')
  call coc#rpc#stop()
endif
```

I placed this statement in my `.vimrc` file after `call plug#end()` but I keep saying the coc.js process running. If I call the same function directly into vim with `:call coc#rpc#stop()` I see the process disappearing, most likely I call it to early? but I am not sure about when it is the right time.

Thanks

**Comment by SalazarSDF** [comment]
just find process in htop throug filter and SIGKILL to cocvim
