### ISSUE TITLE
Change language mode for file extensions

### ISSUE THREAD

**Issue by josete89** [neoclide/coc.nvim#2446]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.2 8021456
node version: v12.16.3
coc.nvim version: 0.0.79-b71489207a
coc.nvim directory: /somepath/vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Describe the bug

I have a file with the extension .template and the language mode is set as JSON so all the syntax highlighting is wrong. I would like to use the yaml plugin instead and I'm not able to find a place where to change this, any help will be appreciated!

**Comment by chemzqm** [comment]
Write autocmd in your vimrc or use vim's modeline.
