### ISSUE TITLE
Question: How to select 10 and above on codeaction menu??

### ISSUE THREAD

**Issue by natac13** [neoclide/coc.nvim#2447]
Sorry for such a dumb question but I cannot for the life of me figure out how to select 10 or above with the codeaction menu.

I am selecting a block of code I wish to refactor to a new file. then using `<space>a` to bring up the menu. However when I try to select 10 ( move to new file ), even really fast, number 1 is picked! Is there a way to stop the entry until <enter> is pressed?? or what am I missing?? :disappointed: 

Everything else seems to be working GREAT! Thanks for the amazing package to get me away from vscode.
![coc-select](https://user-images.githubusercontent.com/10660283/95851719-a4cdd700-0d20-11eb-82bb-2f80ee58ee0f.png)

**Comment by chemzqm** [comment]
You can use arrow keys or (j & k) and press enter.

**Comment by natac13** [comment]
Hmmm. I did try that. Plus with hold Ctrl neither work.... I took the config from this website and didn't change anything. Could there be something else in my init.vim preventing this?

**Comment by natac13** [comment]
I will take that this is something wrong with my setup as your answer seems pretty simple. Not sure what I have setup wrong though. Thanks for the quick reply!
