### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY - Breakage after fd27cb

### ISSUE THREAD

**Issue by dharrigan** [neoclide/coc.nvim#2448]
## versions

vim version: NVIM v0.4.4
node version: v14.13.1
coc.nvim version: 0.0.79-f176d09dc9
coc.nvim directory: /home/david/tmp/coc.nvim
term: xterm-kitty
platform: linux

(although, I've checked out the release branch, and using git bisect to identify the issue, so the coc.nvim version could be different).

## Describe the bug

Hi, 

Since version `fd27cb712b58d144dc60b08f60f26317220c0f16`, commands to `clojure-lsp` have been failing with this error `java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY`. I've also raised this on the `clojure-lsp` [issue list](https://github.com/snoe/clojure-lsp/issues/190)

`clojure-lsp` doesn't do anything special at this point, it simply hands off to the `lsp4j` eclipse project, which attempts to parse the request coming in. 

Using this nvim mapping:

`nnoremap <silent> crcn :call CocRequest('clojure-lsp', 'workspace/executeCommand', {'command': 'clean-ns', 'arguments': [Expand('%:p'), line('.') - 1, col('.') - 1]})<CR>`

If you look at the previous - working - commit `ee46665236dcb1bf7f0c4778de5b979d616602f4`, this is sent for the request when `crcn` is invoked:

```
[Trace - 15:03:55] Sending request 'workspace/executeCommand - (3)'.
Params: {
    "arguments": [
        "file:///home/david/foo/main.clj",
        44,
        0
    ],
    "command": "clean-ns"
}
```

However, from commit `fd27cb712b58d144dc60b08f60f26317220c0f16` onwards, this is sent:

```
[Trace - 15:05:52] Sending request 'workspace/executeCommand - (1)'.
Params: [
    {
        "arguments": [
            "file:///home/david/foo/main.clj",
            44,
            0
        ],
        "command": "clean-ns"
    },
    null
]
```

Notice that the difference between the two requests is that in the working version, `Params` is an Object, whereas in the breaking version `Params` is a list containing an object, with a null as an additional value.

## Reproduce the bug

Well, you'll need a few things, like the `conjure-lsp` downloaded from [here](https://github.com/snoe/clojure-lsp). I'm using release [20201009T224414](https://github.com/snoe/clojure-lsp/releases/tag/release-20201009T224414). That file, `clojure-lsp` needs to go on your path.

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden
call plug#begin('~/.vim/bundle')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

This is my `coc-settings.json`

```
{
  "coc.preferences.enableFloatHighlight": true,
  "coc.preferences.messageLevel": "error",
  "coc.preferences.snippetStatusText": "Ⓢ ",
  "coc.preferences.useQuickfixForLocations": true,
  "coc.source.around.firstMatch": false,
  "coc.source.buffer.firstMatch": false,
  "coc.source.conjure.priority": 999999,
  "diagnostic.virtualText": true,
  "suggest.autoTrigger": "always",
  "suggest.detailField": "preview",
  "suggest.detailMaxLength": 60,
  "suggest.enablePreview": true,
  "suggest.maxCompleteItemCount": 15,
  "suggest.removeDuplicateItems": true,
  "suggest.snippetIndicator": "🤔",
  "suggest.timeout": 5000,
  "suggest.triggerCompletionWait": 100,
  "suggest.completionItemKindLabels": {
    "class": "\uf0e8",
    "color": "\ue22b",
    "constant": "\uf8fe",
    "default": "\uf29c",
    "enum": "\uf435",
    "enumMember": "\uf02b",
    "event": "\ufacd",
    "field": "\uf93d",
    "file": "\uf723",
    "folder": "\uf115",
    "function": "\u0192",
    "interface": "\uf417",
    "keyword": "\uf1de",
    "method": "\uf6a6",
    "module": "\uf40d",
    "operator": "\uf915",
    "property": "\ue624",
    "reference": "\ufa46",
    "snippet": "\ue60b",
    "struct": "\ufb44",
    "text": "\ue612",
    "typeParameter": "\uf728",
    "unit": "\uf475",
    "value": "\uf89f",
    "variable": "\ue71b"
  },
  "languageserver": {
    "clojure-lsp": {
      "command": "bash",
      "args": ["-c", "clojure-lsp"],
      "filetypes": ["clojure"],
      "disableDiagnostics": true,
      "rootPatterns": ["deps.edn", "project.clj"],
      "additionalSchemes": ["jar", "zipfile"],
      "trace.server": "verbose",
      "initializationOptions": {
        "project-specs": [{
          "project-path": "deps.edn",
          "classpath-cmd": ["clj", "-Spath"]
        }],
        "use-metadata-for-privacy?": true,
        "ignore-classpath-directories": true
      }
    }
  }
}
```

- Start (neo)vim with command: `vim -u mini.vim`

I am using git bisect on the release branch to narrow down the bug, so I hope you can identify the issue there too.

let me know if I can be of further assistance.

**Comment by fannheyward** [comment]
Does this work? 

```
nnoremap <silent> crcn :call CocRequest('clojure-lsp', 'workspace/executeCommand', {'command': 'clean-ns', 'arguments': [Expand('%:p'), line('.') - 1, col('.') - 1]}, null)<CR>
```
