### ISSUE TITLE
Plugin doesn't work when raghur/vim-ghost is installed as well

### ISSUE THREAD

**Issue by doronbehar** [neoclide/coc.nvim#245]
**Result from CocInfo**
No output

**Describe the bug**
When I open for example a python file and I have `coc-pyls` installed or for example when I open an HTML file and I have `coc-html` installed I get an error every-time completion is triggered:

```
[coc.nvim] server connection lost
```

**To Reproduce**

1. Clone the repository.
2. Run `yarn install` in the repository's directory

I have no idea how to debug this in order to give more information so please help will be appreciated.

**Comment by chemzqm** [comment]
This could happen when coc process is killed by other process or the channel between vim and coc server is broken.
Is there any error from `:call coc#rpc#show_error()`?

**Comment by doronbehar** [comment]
No, it uses 0%.

**Comment by oblitum** [comment]
Ok, I thought it could be hanging/looping, like happened in other cases.

**Comment by doronbehar** [comment]
It happens with an empty buffer as well. My `node -v` is `v11.3.0`. I use Neovim so that `nocompatible` is useless in my case. But you were right to point out that I should test if it happens when coc is the only plugin installed because it works fine without any other plugin installed.

After some debugging, I've found the guilty plugin: https://github.com/raghur/vim-ghost can anyone suggest why would it block coc.nvim ?

**Comment by oblitum** [comment]
@doronbehar dunno but that plugin seems awesome.

**Comment by doronbehar** [comment]
It certainly is. Do you think I should report this issue to vim-ghost's tracker?

**Comment by oblitum** [comment]
@doronbehar by the way, I suggest changing the title for this current issue to something like that too.

**Comment by chemzqm** [comment]
It should be problem of how neovim handle clients, but I can't install that plugin, so I can't get more information.

**Comment by iamcco** [comment]
i got the error when open an buffer in neovim's terminal using nvim itself.

https://asciinema.org/a/I8nyejAzYZo3OWD6Ui2WMki6V

**Comment by chemzqm** [comment]
Got the reason, neovim reuse socket when nested, so when the inner one exit, coc connection would lost.
Could be fixed by use stdio for communication.
Will fix this in next release.

**Comment by doronbehar** [comment]
Thanks @chemzqm , I suppose the reason vim-ghost has broke coc.nvim was because of https://github.com/raghur/vim-ghost/commit/204916e7762f52193a7a3108020b380f36ddbbb0 ? I mean because of it's new dependence on [vim-hug-neovim-rpc](https://github.com/roxma/vim-hug-neovim-rpc) and [nvim-yarp](https://github.com/roxma/nvim-yarp) which is part of it's new compatibility with Vim?

I've found out that reverting vim-ghost to commit `4e06bc238d23e6eb245a766105c62344a132b3f4` is the most sufficient workaround for Neovim users, Vim support in vim-ghost wasn't available until the commit that came afterwards and caused this issue.

**Comment by chemzqm** [comment]
It could be that vim-bug-neovim-rpc start another neovim instance and cause this issue.
However, it's not problem of vim-ghost, it's bug of neovim https://github.com/neovim/neovim/issues/9336.
