### ISSUE TITLE
TextYankPost highlight with documentHighlight

### ISSUE THREAD

**Issue by nomasprime** [neoclide/coc.nvim#2452]
## versions

vim version: NVIM v0.5.0-nightly-43-g759a05407
node version: v14.2.0
coc.nvim version: 0.0.79-6fc00f1a28
coc.nvim directory: /Users/nomasprime/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Output channel: snippets

[Info 23:41:23] Using ultisnips directories: UltiSnips /Users/nomasprime/.config/coc/ultisnips
[Info 23:41:23] Using ultisnips python command: pyx

## Output channel: highlight

[Info  - 23:41:23] Highlight server running in node v14.2.0

## Describe the bug

documentHighlight doesn't behave as expected with TextYankPost highlight.

Not sure this is an issue for coc or nvim though.

## Reproduce the bug

Configure TextYankPost highlight in nvim config:

```viml
autocmd TextYankPost * silent! lua return (not vim.v.event.visual) and require'vim.highlight'.on_yank {higroup='Visual', timeout=500}
```

Move cursor to documentHighlight symbol with other text on the line and yank the line.

The whole line apart from the documentHighlight symbol changes to the correct highlight.

**Comment by chemzqm** [comment]
Should be expected since `documentHighlight ` is added by `matchaddpos` and may have higher priority, you may increase priority for `vim.highlight`

**Comment by sabah1994** [comment]
@nomasprime did you find a work around this?
