### ISSUE TITLE
How do I turn off autocomplete feature for comments?

### ISSUE THREAD

**Issue by ProgrammingLife** [neoclide/coc.nvim#2456]
How do I turn off autocomplete feature for comments? Because it's waste of performance in case of big files.

**Comment by chemzqm** [comment]
Hack `coc#util#get_complete_option` https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/util.vim#L624

**Comment by ProgrammingLife** [comment]
@chemzqm, Might be it would be better to have separate setting for getting such behaviour?

**Comment by chemzqm** [comment]
Nope.
