### ISSUE TITLE
Yank / copy hover info to clipboard

### ISSUE THREAD

**Issue by NathanKleekamp** [neoclide/coc.nvim#2461]
**Is your feature request related to a problem? Please describe.**
I'd like a way to yank the contents of a hover popup. Even better, I'd like to add a mapping to capture the hover info to my clipboard without having to open the popup.

**Describe alternatives you've considered**
Unfortunately, I don't know enough about n/vim to suggest alternatives.

Thank you for your awesome work!

**Comment by chemzqm** [comment]
Use `:CocAction('getHover')` to get array of hover texts.

**Comment by NathanKleekamp** [comment]
Your awesomeness has no limits!!!

**Comment by NathanKleekamp** [comment]
Hey, so, I pulled down the latest and greatest, and I'm getting the following when I try to use "getHover".

![image](https://user-images.githubusercontent.com/1002258/96269920-fb454a80-0f98-11eb-90b3-2517484ba4e6.png)

Also, I think that the commit `8fd7bf0fd08827fe7444d7649fe599579c7fb18c` broke hover functionality generally. At least, when I checkout that commit, I can no longer trigger the hover float.

Thanks again!!
