### ISSUE TITLE
Escaping occuring in hover window

### ISSUE THREAD

**Issue by ldelossa** [neoclide/coc.nvim#2464]
## versions

vim version: VIM - Vi IMproved 8.2 8021805
node version: v12.18.3
coc.nvim version: 0.0.79-d4d93dc25f
coc.nvim directory: /home/ldelossa/.local/share/nvim/plugged/coc.nvim
term: dumb
platform: linux

## Output channel: go

[Info  - 12:25:42 AM] 2020/10/16 00:25:42 Handshake session update
	update_session=10
	debug_address=""
	logfile=""
	server="1"
	gopls_path="/home/ldelossa/.config/coc/extensions/coc-go-data/bin/gopls"

[Info  - 12:25:42 AM] 2020/10/16 00:25:42 go env for /home/ldelossa/git/redhat/quay-terraform
(root /home/ldelossa/git/redhat/quay-terraform)
(go version go version go1.15.2 linux/amd64
)
(valid build configuration = true)
(build flags: [])
GOMOD=/home/ldelossa/git/redhat/quay-terraform/go.mod
GOMODCACHE=/home/ldelossa/git/gopath/pkg/mod
GOPATH=/home/ldelossa/git/gopath
GOSUMDB=sum.golang.org
GOCACHE=/home/ldelossa/.cache/go-build
GOPRIVATE=
GOPROXY=https://proxy.golang.org,direct
GOFLAGS=
GONOSUMDB=
GOROOT=/usr/local/go
GO111MODULE=
GOINSECURE=
GONOPROXY=

[Info  - 12:25:42 AM] 2020/10/16 00:25:42 go/packages.Load
	snapshot=0
	directory=/home/ldelossa/git/redhat/quay-terraform
	query=[./... builtin]
	packages=2

[Info  - 12:25:50 AM] 2020/10/16 00:25:50 go/packages.Load
	snapshot=4
	directory=/home/ldelossa/git/redhat/quay-terraform
	query=[github.com/quay/quay-terraform]
	packages=1

[Info  - 12:25:50 AM] 2020/10/16 00:25:50 go/packages.Load
	snapshot=4
	package_path="github.com/quay/quay-terraform"
	files=[/home/ldelossa/git/redhat/quay-terraform/config.go /home/ldelossa/git/redhat/quay-terraform/main.go /home/ldelossa/git/redhat/quay-terraform/packer.go]

[Info  - 12:25:57 AM] 2020/10/16 00:25:57 go/packages.Load
	snapshot=7
	directory=/home/ldelossa/git/redhat/quay-terraform
	query=[github.com/quay/quay-terraform]
	packages=1

[Info  - 12:25:57 AM] 2020/10/16 00:25:57 go/packages.Load
	snapshot=7
	package_path="github.com/quay/quay-terraform"
	files=[/home/ldelossa/git/redhat/quay-terraform/config.go /home/ldelossa/git/redhat/quay-terraform/main.go /home/ldelossa/git/redhat/quay-terraform/packer.go]

[Info  - 12:26:20 AM] 2020/10/16 00:26:20 background imports cache refresh starting

[Info  - 12:26:20 AM] 2020/10/16 00:26:20 background refresh finished after 394.511263ms

[Error  - 12:27:05 AM] 2020/10/16 00:27:05 no signature help: cannot find an enclosing function
	position={8 11}

[Error  - 12:29:36 AM] 2020/10/16 00:29:36 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:29:38 AM] 2020/10/16 00:29:38 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:29:38 AM] 2020/10/16 00:29:38 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:29:47 AM] 2020/10/16 00:29:47 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:29:48 AM] 2020/10/16 00:29:48 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:29:48 AM] 2020/10/16 00:29:48 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Info  - 12:30:20 AM] 2020/10/16 00:30:20 background imports cache refresh starting

[Info  - 12:30:20 AM] 2020/10/16 00:30:20 background refresh finished after 100.812093ms

[Info  - 12:30:21 AM] 2020/10/16 00:30:21 go/packages.Load
	snapshot=48
	directory=/home/ldelossa/git/redhat/quay-terraform
	query=[github.com/quay/quay-terraform]
	packages=1

[Info  - 12:30:21 AM] 2020/10/16 00:30:21 go/packages.Load
	snapshot=48
	package_path="github.com/quay/quay-terraform"
	files=[/home/ldelossa/git/redhat/quay-terraform/config.go /home/ldelossa/git/redhat/quay-terraform/main.go /home/ldelossa/git/redhat/quay-terraform/packer.go]

[Error  - 12:31:24 AM] 2020/10/16 00:31:24 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:31:25 AM] 2020/10/16 00:31:25 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:31:27 AM] 2020/10/16 00:31:27 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:33:45 AM] 2020/10/16 00:33:45 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:33:48 AM] 2020/10/16 00:33:48 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:33:48 AM] 2020/10/16 00:33:48 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:33:49 AM] 2020/10/16 00:33:49 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:33:51 AM] 2020/10/16 00:33:51 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:33:56 AM] 2020/10/16 00:33:56 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:34:31 AM] 2020/10/16 00:34:31 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:34:36 AM] 2020/10/16 00:34:36 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:34:37 AM] 2020/10/16 00:34:37 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:34:38 AM] 2020/10/16 00:34:38 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:35:31 AM] 2020/10/16 00:35:31 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Error  - 12:35:32 AM] 2020/10/16 00:35:32 unable to compute error positions: invalid position for type error -: missing return
	package="github.com/quay/quay-terraform"

[Info  - 12:36:13 AM] 2020/10/16 00:36:13 background imports cache refresh starting

[Info  - 12:36:13 AM] 2020/10/16 00:36:13 background refresh finished after 73.21092ms

## Describe the bug

When viewing golang documentation via the hover window normal punctuation characters are being escaped.

## Reproduce the bug

Bug can be reproduced by performing "doHover" action over any golang function with gopls language server. 

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/5642902/96213769-c3fa7d80-0f47-11eb-8217-bd5b3e1ecc9c.png)

**Comment by chemzqm** [comment]
It's expected since coc.nvim tells language server markdown is supported and you get raw markdown text.

**Comment by ldelossa** [comment]
Would it be wise/possible to run the returned "hover" response thru the function:

substitute({expr}, {pat}, {sub}, {flags})
                                String  all {pat} in {expr} replaced with {sub}

Replacing "\." with ".", "\(" with "(", etc...

**Comment by chemzqm** [comment]
That would break highlight and we need avoid substitute in code block.

**Comment by ldelossa** [comment]
I can live with the escaping, but optimally its not there. Any ideas on how to remove? If not feel free to close ticket.

**Comment by chemzqm** [comment]
A function to calculate position of `\` which need to be concealed and use `matchaddpos()` to conceal them.

**Comment by ldelossa** [comment]
What function in coc-vim holds the buffer with the markdown response of "Hover" lsp command?

**Comment by chemzqm** [comment]
Only need to use `g:coc_last_float_win` with `CocOpenFloat` autocmd.

**Comment by ldelossa** [comment]
@chemzqm 

I've gotten this far, and I think I've calculated the [line, column] offet of "\" chars in the popup window. However I seem to not be using "matchaddpros" correctly. Any advice?

```
autocmd User CocOpenFloat call coc#conceal() <cr>

function! coc#conceal() abort
  let popup_id = g:coc_last_float_win
  let bufnr = winbufnr(popup_id)
  let escapes = []

  let lines = getbufline(bufnr, 1, '$')

  # nested loop to record [line,column] 
  let lineN = 0
  for line in lines
    let chars = split(line, '\zs')
    let n = len(chars)
    let column = 0

    while column < n
      if chars[column] == '\'
        let tuple = [lineN, column]
        let escapes = add(escapes, tuple)
      endif
      let column += 1
    endwhile

    let lineN += 1
  endfor

  if len(escapes) > 0
    for escape in escapes
      # column index starts at 1
      let escape = [escape[0], escape[1]+1]
      matchaddpos("Conceal", escape, 99, -1, {'window', popup_id})
    endfor

  endif

endfunction
```

**Comment by chemzqm** [comment]
You need conceal property for last argument of matchaddpos, you may need redraw on vim

**Comment by ldelossa** [comment]
Ohhh, i had thought if simply concealing with an empty character that that key is not needed, but would make sense to add it and replace with ''. 

Let me try that out along with redraw, thanks for tip.

**Comment by ldelossa** [comment]
@chemzqm 

I have worked out all the kinks in the function but the pop-up window still will not update.

```
autocmd User CocOpenFloat call coc#conceal() <cr>

function! coc#conceal() abort
  let popup_id = g:coc_last_float_win
  echom "popup window number ".popup_id
  let bufnr = winbufnr(popup_id)
  echom "buffer number ".bufnr
  let escapes = []

  let lines = getbufline(bufnr, 1, '$')

  let lineN = 1
  for line in lines
    let chars = split(line, '\zs')
    let n = len(chars)
    let column = 0

    while column < n
      if chars[column] == '\'
        let posColumn = column + 1 
        let tuple = [lineN, posColumn, 1] 
        let escapes = add(escapes, tuple)
      endif
      let column += 1
    endwhile

    let lineN += 1
  endfor

  if len(escapes) > 0
    for escape in escapes
      echom escape
      call matchaddpos("Conceal", [escape], 10, -1, {'window': popup_id, 'conceal': ''})
    endfor
  endif
endfunction
```

I can test that this function works in a bit of a hacky way:
* remove the 'window' property from the dictionary in the "matchaddpos" only leaving "conceal" 
* open vim and perform a "doHover" action on some string, the above function will dump the buffer number of the popup contents
* perform "sbuffer {num}" to open the buffer with the contents of the popup window
* call the updated "coc#conceal" function which will act on current buffer, it correctly conceals "\" characters. 

So the function works fine when operating on the current window/buffer. It doesn't seem to work when pointing to the window id of the popup window.

**Comment by chemzqm** [comment]
Will rework highlights for markdown, please comment #2497
