### ISSUE TITLE
closing 

### ISSUE THREAD

**Issue by marene** [neoclide/coc.nvim#2470]
## Result from CocInfo
```
## versions

vim version: NVIM v0.4.4
node version: v12.19.0
coc.nvim version: 0.0.79-80ae19dee6
coc.nvim directory: /Users/matthieu.arene/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug
When a split window (or a tab) is open, and a coc floating window pops up (for example when the cursor gets placed on a warning, or when the documentation of a symbol gets consulted), if the cursor is moved, then the current window is closed.
(see screenshot section for more clarity).

This baffles me because I had close to exactly the same nvim/coc setup on my previous work macbook three days ago, and it worked just fine: I possibly done a stupid configuration mistake, but I just cannot find it.

## Reproduce the bug
- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/Users/matthieu.arene/.local/share/nvim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  call plug#begin(stdpath('data') . '/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  call plug#end()
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Open a split window, in one of those windows navigate to a warning (or hover over a documented symbol). Once a floating window pops up, move the cursor and the current window will close

## Screenshots
![output](https://user-images.githubusercontent.com/6116823/96286843-4d11c300-0fe1-11eb-9fb8-cf73adf7df1b.gif)

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by marene** [comment]
Ah, I feel silly now, thanks a bunch!
Out of curiosity, what precise commit did fix this? I'm asking because I installed coc on the 15th (with `Plug 'neoclide/coc.nvim', {'branch': 'release'}'`), so I guess it was a recent one?

**Comment by chemzqm** [comment]
c563f91d - fix(float): only close border window if it exists,
