### ISSUE TITLE
Still Cannot select Code action menu with J or K

### ISSUE THREAD

**Issue by natac13** [neoclide/coc.nvim#2471]
## Result from CocInfo
```
vim version: NVIM v0.4.4
node version: v12.18.3
coc.nvim version: 0.0.79-b1c5962f6f
```

## Describe the bug

I see the changes to the code actions menu from my last issue #2447. And I can input a number higher than 10 now so thank you very much!
However I still cannot select with `j` or `k` or `G` or the arrow keys. I have tried with the ctrl key and still nothing. At least I do not see anything visually changing.

Is there a setting or key binding I have to change. 

Again Thank you for updating the ability to input a number 10 and higher. Works go I just wanted to let you know about `j` and `k` not working, at least for me.

**Comment by chemzqm** [comment]
NVIM v0.4.4 doesn't support cursorline with float window, use v0.5.0 could help.
