### ISSUE TITLE
popups no longer showing up

### ISSUE THREAD

**Issue by ornicar** [neoclide/coc.nvim#2476]
![](https://i.imgur.com/RroRBhB.png)

These no longer show up on lines with errors.

I bisected the first faulty commit to this one: 8fd7bf0fd08827fe7444d7649fe599579c7fb18c
Reverting to previous commit (60e5ba21262af78640fefb70a82a6242cc08d253) and popups show up normally.

NVIM v0.4.4 on Linux.

**Comment by chemzqm** [comment]
Try latest release branch.

**Comment by ornicar** [comment]
It works! Thank you <3

**Comment by ornicar** [comment]
![](https://i.imgur.com/mIpFzuN.png)

Oh yeah. I like this very much. Great job :+1:
