### ISSUE TITLE
gopls problem.

### ISSUE THREAD

**Issue by sober-wang** [neoclide/coc.nvim#2477]
6 2020-10-18T20:06:20.141 INFO (pid:20472) [services] - gopls state change: stopped => starting^M                                                                                               7 2020-10-18T20:06:20.222 ERROR (pid:20472) [server] - uncaughtException Error: Header must provide a Content-Length property.                                                                  8     at StreamMessageReader.onData (C:\Users\Sober\.vim\plugged\coc.nvim\build\index.js:16770:27)                                                                                              9     at Socket.<anonymous> (C:\Users\Sober\.vim\plugged\coc.nvim\build\index.js:16755:18)                                                                                                     10     at Socket.emit (events.js:210:5)                                                                                                                                                         11     at addChunk (_stream_readable.js:309:12)                                                                                                                                                 12     at readableAddChunk (_stream_readable.js:290:11)                                                                                                                                         13     at Socket.Readable.push (_stream_readable.js:224:10)                                                                                                                                     14     at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)^M  

What should I do?

**Comment by chemzqm** [comment]
Upgrade your gopls
