### ISSUE TITLE
Signature window in horrible position

### ISSUE THREAD

**Issue by matheusfillipe** [neoclide/coc.nvim#2478]
Why is my signature floating window in such a bad position? Is it possible to get it on the right of the autocomplete list instead of behind it and on the left side? This makes it totally useless.
 
![2020-10-19_04-35](https://user-images.githubusercontent.com/24435787/96415194-8fdfc080-11c4-11eb-926f-56bf8527b55e.png)

 I don't have nothing on my coc-settings and commented all coc settings on my init.vim but it is still like this.

**Comment by chemzqm** [comment]
Seems your vim report wrong pum position on `CompleteChanged` event.
You can disable it.

**Comment by matheusfillipe** [comment]
How do I disable it?

**Comment by matheusfillipe** [comment]
I think when I first installed Coc the previews were in the right place, but i don't recall exactly what I changed that screwed them up and nothing I do now seem to change them.

**Comment by matheusfillipe** [comment]
--> https://github.com/equalsraf/neovim-qt/issues/780

I filled an issue there and found that the solution was `GuiPopupmenu 0` 

"It looks like the plugin is making some invalid assumptions regarding ext_popupmenu"

**Comment by chemzqm** [comment]
Should be problem of neovim, which doesn't report pum position on `CompleteChanged` when using external pum.
