### ISSUE TITLE
Can it add autocompletion source for python surpported by jedi?

### ISSUE THREAD

**Issue by hackingcat** [neoclide/coc.nvim#248]
Although we can apply coc-pyls for python,pyls is too laggy.It would be a better choice if coc.nvim can add a source powed by jedi.Indeed,language server is always perfect.

**Comment by chemzqm** [comment]
There used to jedi source for coc, but I'm not satisfied with that, the integration with MPLS https://github.com/Microsoft/python-language-server is in progress, it works well in VSCode.

**Comment by robertocarta** [comment]
Any way I can contribute to this?

**Comment by chemzqm** [comment]
Try out https://github.com/neoclide/coc-python
