### ISSUE TITLE
Jump to customized location

### ISSUE THREAD

**Issue by yueyingjuesha** [neoclide/coc.nvim#2480]
Hi, Just wondering if coc can allow user to edit the location they want to jump to using gr/gd.

The senario is that most of lsp jump to definition/reference is not perfect, it often misses some references or some definitions. So every time I have to manually search the codebase for definition/reference and jump to that, which is quite a waste of time.

I am wondering if COC have some mechanism that allow user to manually fix the jump location list  from goto reference/goto definition. If not, does anyone know is there any vim plugin that allow me to do that?

**Comment by chemzqm** [comment]
> it often misses some references or some definitions.

Send your bug report to language server you're using.

**Comment by chemzqm** [comment]
Also checkout `:h CocSearch` for code refactor if you language server is not reliable.
