### ISSUE TITLE
A way to retrieve the diagnostics at the current cursor position (for further processing in vimscript / python)

### ISSUE THREAD

**Issue by reinhrst** [neoclide/coc.nvim#2485]
**Is your feature request related to a problem? Please describe.**
I use pylint as a linter, and in many cases it produces an message I would like to suppress. An example of an error: `[pylint R0201] [H] Method could be a function (no-self-use)`. This message can be suppressed by adding `# pytlint: disable no-self-use` to the end of the line -- and I'm lazy and would like a vim-function to do this for me. Obviously creating a vim-function to insert this comment at the end of the line is trivial, if I can retrieve the diagnostics. My first hunch was to use `coc-diagnostic-info`, but this only _shows_ the diagnostics, it doesn't _return_ it for further processing.

**Describe the solution you'd like**
The fix seems to be relatively simple:

```
        this.addAction('getDiagnosticsAt', (bufnr, cursor) => {
            return manager_1.default.getDiagnosticsAt(bufnr, cursor);
        });
```

This will allow direct calls from vim like:
`echo coc#rpc#request("getDiagnosticsAt", [bufnr("%"), coc#util#cursor()])`, returning `[{'source': 'pylint', 'range': {'end': {'character': 5, 'line': 69}, 'start': {'character': 4, 'line': 69}}, 'code': 'R0201', 'message': 'Method could be a function (no-self-use)', 'severity': 4}]`

**Describe alternatives you've considered**
I could imagine that I would want to build by whole function within the coc environment, so that (e.g.) if I were to type `# pylint` it would suggest the full line. However, in addition to the learning curve involved for a relatively simple project, I'm not even sure that this is possible (i.e. that a coc plugin would have access to the diagnostics).

**Additional context**
None, however feel free to let me know if things are unclear.

**Comment by oblitum** [comment]
Isn't `:h coc-action-diagnosticList@en` sufficient?

**Comment by oblitum** [comment]
For example, I use both `'quickfixes'` and `'diagnosticList'` to process available quickfixes for the current line and display the count in statusline.

**Comment by chemzqm** [comment]
Use `CocAction('diagnosticList')`

**Comment by reinhrst** [comment]
Thanks! `CocAction('diagnosticList')` doesn't work for me (`[coc.nvim] No ("diagnosticList") code action available` -- I should one day dive into this), but `coc#rpc#request("diagnosticList", [])` does indeed give me all I need!

**Comment by chemzqm** [comment]
Use it as function

**Comment by reinhrst** [comment]
Got it, thanks. For future reference `:CocAction('diagnosticList')` gives the error but something like `:echo CocAction('diagnosticList')` works!
