### ISSUE TITLE
Rust: error in wrong place

### ISSUE THREAD

**Issue by dakom** [neoclide/coc.nvim#249]
**Result from CocInfo**
## versions

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.37
term: xterm-256color
platform: linux

## Output channel: rust
error[E0703]: invalid ABI: found ` `
   --> <racer-file>:188:23
    |
188 |     pub unsafe extern " " fn __wbindgen_global_argument_ptr() -> *mut u32 {
    |                       ^^^ invalid ABI
    |
    = help: valid ABIs: cdecl, stdcall, fastcall, vectorcall, thiscall, aapcs, win64, sysv64, ptx-kernel, msp430-interrupt, x86-interrupt, amdgpu-kernel, Rust, C, system, rust-intrinsic, rust-call, platform-intrinsic, unadjusted

thread '<unnamed>' panicked at 'Forcing query with already existing DepNode.
- query-key: Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing }, value: Binder(TraitPredicate(<&[type error] as std::marker::Sized>)) } }
- dep-node: EvaluateObligation(4ee94ed3b06f071d-9c275bbcf6336547)', src/librustc/ty/query/plumbing.rs:531:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0-nightly (400c2bc5e 2018-11-27) running on x86_64-unknown-linux-gnu

error[E0703]: invalid ABI: found ` `
   --> <racer-file>:188:23
    |
188 |     pub unsafe extern " " fn __wbindgen_global_argument_ptr() -> *mut u32 {
    |                       ^^^ invalid ABI
    |
    = help: valid ABIs: cdecl, stdcall, fastcall, vectorcall, thiscall, aapcs, win64, sysv64, ptx-kernel, msp430-interrupt, x86-interrupt, amdgpu-kernel, Rust, C, system, rust-intrinsic, rust-call, platform-intrinsic, unadjusted

error[E0703]: invalid ABI: found ` `
   --> <racer-file>:188:23
    |
188 |     pub unsafe extern " " fn __wbindgen_global_argument_ptr() -> *mut u32 {
    |                       ^^^ invalid ABI
    |
    = help: valid ABIs: cdecl, stdcall, fastcall, vectorcall, thiscall, aapcs, win64, sysv64, ptx-kernel, msp430-interrupt, x86-interrupt, amdgpu-kernel, Rust, C, system, rust-intrinsic, rust-call, platform-intrinsic, unadjusted

**Describe the bug**
The error should be on line `#15` but instead it's at the top of the file

**To Reproduce**
Not sure if this error exists in a standalone file... might be a wasm or workspace related issue?

To reproduce exactly, copy this into a wasm project in a crate under a workspace:

```
extern crate wasm_bindgen;
extern crate web_sys; 
extern crate js_sys;
use wasm_bindgen::prelude::*;
use web_sys::console;

#[wasm_bindgen]
pub extern fn start(name: &str) {
    let value = JsValue::from_str(format!("Hello {}", name).as_str());
    console::log_1(&value);
}

#[wasm_bindgen]
//TODO - accept Canvas Element
pub extern fn load_assets(onLoad: Function) {
    //TODO - call onLoad
}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/6406986/49698312-b1d08b00-fbca-11e8-83c0-de4223528317.png)

**Comment by oblitum** [comment]
Didn't the compiler simply panic?

**Comment by dakom** [comment]
Not sure ... FWIW I just got another error (different code) and it's not showing up in vim at all :(

I see this in terminal:

```
error[E0308]: mismatched types
 --> <::alloc::macros::format macros>:2:1
  |
2 | $ crate :: fmt :: format ( format_args ! ( $ ( $ arg ) * ) ) )
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected &str, found struct `std::string::String`
  |
  = note: expected type `&str`
             found type `std::string::String`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `webgl-demo`.
```

But nothing in NeoVim

No idea if any of this is related...

**Comment by oblitum** [comment]
This last error is fine, but the previous one pointed to compiler panic, which is a bug in the compiler itself. I use Rust myself and Coc has been fine with it but I still never tried WebAssembly. Gonna check out how it behaves on my side, but from what I've seen it's still early tech.

**Comment by oblitum** [comment]
Please, send the snippet source for this last error, if it's not too big.

**Comment by oblitum** [comment]
Also, you should be aware that Rust's usage of macros can make errors show up in strange places.

**Comment by dakom** [comment]
Oh - thanks for the push, I was able to isolate the issue a bit better, will open a new issue :)

**Comment by chemzqm** [comment]
It's not possible for coc to show error locations from output channel, rls should send them as diagnostics.
