### ISSUE TITLE
Why not use vim plugin in vscode

### ISSUE THREAD

**Issue by tydra-wang** [neoclide/coc.nvim#2490]
**Is your feature request related to a problem? Please describe.**
not a issue, but a question.

**Describe the solution you'd like**
coc.nvim makes vim smart like vscode.
So why not just use vscode + vim plugin?
I try to learn vim recently and enjoy it. But I feel it really difficult to config vim like an IDE. I need to learn vimL and so many plugins.
I want to know why you create coc.nvim.

**Comment by chemzqm** [comment]
Vim is editor, I don't think it's a good idea to make it IDE.
Vim has many good features for test editing and the flexible for extend & configuration, coc.nvim is created to bring some good features like lsp and configuration of VSCode to (neo)vim and make it possible to create typescript/javascript extension of vim much easier.

**Comment by chemzqm** [comment]
> learn vimL and so many plugins.

The most important thing is understanding how vim works and how could you make it to improve your coding experience and then get used to it.  Viml could be awful and many plugins could be unnecessary for you.
