### ISSUE TITLE
scrollbar in wrong position

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#2491]
## versions

vim version: NVIM v0.4.4
node version: v14.14.0
coc.nvim version: 0.0.79-230b8a7247
coc.nvim directory: /home/francisco/.config/nvim/plugged/coc.nvim
term: tmux-256color
platform: linux

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root of /home/francisco/Projects/samples/rust/src/main.rs: /home/francisco
> git ls-files -- Projects/samples/rust/src/main.rs
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git ls-files -- Projects/samples/rust/src/main.rs
> git ls-files -- Projects/samples/rust/src/main.rs
> git ls-files -- Projects/samples/rust/src/main.rs
> git ls-files -- Projects/samples/rust/src/main.rs
> git ls-files -- Projects/samples/rust/src/main.rs
> git ls-files -- Projects/samples/rust/src/main.rs
> git ls-files -- Projects/samples/rust/src/main.rs
> git ls-files -- Projects/samples/rust/src/main.rs
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git ls-files -- Projects/samples/rust/src/main.rs
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git ls-files -- Projects/samples/rust/src/main.rs
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git ls-files -- Projects/samples/rust/src/main.rs
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git ls-files -- Projects/samples/rust/src/main.rs

## Output channel: snippets

[Info 1:43:01 PM] Using ultisnips directories: UltiSnips /home/francisco/.config/coc/ultisnips
[Info 1:43:01 PM] Using ultisnips python command: pyx

## Describe the bug

Scrollbar is rendered in wrong position.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set runtimepath^=~/.vim/plugged/coc.nvim
  colorscheme peachpuff
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots

![imgur-13:43:23_21-10-2020](https://user-images.githubusercontent.com/1269815/96751738-f3741480-13a3-11eb-86e4-9c29dd4fe67c.png)

## Related issues

- #2472

**Comment by chemzqm** [comment]
Can't reproduce, but I will try to use window relative for related windows.

**Comment by oblitum** [comment]
It's fixed.

It's in the correct horizontal position now, on the right edge. Though I noticed that for a small signatureHelp window, it seems it's not very useful, it's not moving vertically when I scroll line-by-line, it's simply fixed on top, despite of scrolling down.
