### ISSUE TITLE
Don't delay completion when triggering this manually

### ISSUE THREAD

**Issue by YorickPeterse** [neoclide/coc.nvim#2494]
**Is your feature request related to a problem? Please describe.**

coc.nvim allows for manual completion by setting `suggest.autoTrigger` to `none`. It also allows you to configure the completion delay, using `suggest.triggerCompletionWait`. The minimum value of `suggest.triggerCompletionWait` is `30`. 

When using manual completion (e.g. by mapping `coc#refresh` to `<tab>`), this delay is still applied, as seen here: https://github.com/neoclide/coc.nvim/blob/52460fd6c37dd19068956bfd0e0631d60e35fca0/src/completion/index.ts#L242

I personally use manual completion, as I find this a little less annoying compared to auto completion; I simply don't always need a list of suggestions, but it's nice being able to request one when needed. But the delay (a minimum of 30 ms) becomes noticeable when added on top of the delay of the completion/language server. Even if not noticeable, it's redundant to delay a manual completion request.

**Describe the solution you'd like**

If would be nice if there is no delay when manually completing. For example, if `suggest.autoTrigger` is set to `none` the delay would be ignored or perhaps be allowed to be set to `0` (don't think JSON schemas allow for such complex rules). This means that manual completion is only delayed by the time it takes to generate the completions, instead of the `suggest.triggerCompletionWait` delay being added on top.

**Describe alternatives you've considered**

For now I can live with the delay. Unfortunately, there's no alternative other than using auto completion; which not everybody may like using.

**Additional context**

Here is an extreme example: completion is done manually using `tab`, and `suggest.triggerCompletionWait` is set to 500 to illustrate the delay:

https://asciinema.org/a/tnCANuBue7gAHNDXREZfVUXqs

**Comment by chemzqm** [comment]
Delay is needed to make sure server is synchronized，you can configured it to 0

**Comment by YorickPeterse** [comment]
@chemzqm 

> you can configured it to 0

According to https://github.com/neoclide/coc.nvim/blob/d0e111bff55cb645959bad981dd998fe2ae45cb0/data/schema.json#L414 the minimum is 30. Can I simply ignore that minimum and set it to 0 anyway?

I noticed commit https://github.com/neoclide/coc.nvim/commit/f9285bad1402cedb2eaffe6ae1222d0ce5cd4e6c, which appears to disable the delay _if_ no trigger character is defined. I'll give that a test when it's on the `release` branch, thanks!

**Comment by YorickPeterse** [comment]
https://github.com/neoclide/coc.nvim/commit/f9285bad1402cedb2eaffe6ae1222d0ce5cd4e6c works perfect as far as I can tell, thanks! :smile:

**Comment by kidyme** [comment]
test
