### ISSUE TITLE
Rework highlights for float windows/popups

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#2497]
Here's my plan:

* Parse markdown to generate plaintext(without characters like `#` `*` `\` ` ) and highlights(bold text, underlined text, italic text, links and headers) and code block regions information.

* Avoid use neovim process for parse highlights, use `syntax region` like:

  ``` vim
  syntax include @TYPESCRIPT syntax/typescript.vim
  syntax region Markdown start=/\%1l/ end=/\%3l/ contains=@TYPESCRIPT
  ```

Don't know if there's existing markdown parser written in javascript that already good enough.

**Comment by oblitum** [comment]
> Don't know if there's existing markdown parser written in javascript that already good enough.

@iamcco does a great job on [markdown-preview.nvim](https://github.com/iamcco/markdown-preview.nvim), which uses [markdown-it](https://github.com/markdown-it/markdown-it).

**Comment by chemzqm** [comment]
Working on #2518

**Comment by chemzqm** [comment]
There would be no need to change current window, so `<C-w>p` won't work any more.

**Comment by chemzqm** [comment]
It's finished, consider try it out.

**Comment by oblitum** [comment]
Just tried and seems to be working pretty fine, I could not notice the difference in Rust/C for now, while Haskell output seems to have got a bit better.

**Comment by oblitum** [comment]
If there's any known programming language or situation where the difference would be more noticeable, I can try.

**Comment by oblitum** [comment]
Ah, just noticed that the output for C is much improved indeed, it's not turning bold what should not, like `__THROW` for example.

**Comment by chemzqm** [comment]
Seems language server of php send complex markdown texts
