### ISSUE TITLE
Signature hint float window appears over cursor line

### ISSUE THREAD

**Issue by romgrk** [neoclide/coc.nvim#2498]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-769-g23e109b13
node version: v12.18.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/romgrk/.config/nvim/bundle/coc.nvim
term: xterm-256color
platform: linux

## Output channel: explorer


## Output channel: coc-helper

declare fn 1_util.global_cursor_position
declare fn 1_util.is_float
declare fn 1_util.close_win_by_bufnr
declare fn 1_util.run_coc_cmd
declare fn 1_util.run_coc_cmd_async
declare fn 2_events.activate
declare fn 2_events.deactivate
declare fn 2_events.do_autocmd
declare fn 3_buf.create_by_name
declare fn 3_buf.create
declare fn 4_float.init_execute
declare fn 4_float.open_win
declare fn 4_float.create
declare fn 4_float.open
declare fn 4_float.resume
declare fn 4_float.update
declare fn 4_float.winid
declare fn 4_float.border_winid
declare fn 4_float.close
call 2_events.activate
call 2_events.activate
```

## Describe the bug

The signature hint float window is positioned over the cursor line, the typed text is therefore hidden.

## Reproduce the bug

I have not been able to reproduce the problem with the minimal vimrc. I've tried progressively adding some plugins but it's messy because there are interdependency between lots of things in my config. I was wondering if you had any idea where this bug may come from even without a minimal vimrc. If you have no idea, just let me know, keep this issue open and I'll debug further.

## Screenshots (optional)

![Screenshot from 2020-10-22 02-05-42](https://user-images.githubusercontent.com/1423607/96831786-ae83c880-140b-11eb-94e6-13c97a30e271.png)

![Screenshot from 2020-10-22 02-13-57](https://user-images.githubusercontent.com/1423607/96832706-2ef6f900-140d-11eb-8a0e-909bb113e094.png)

**Comment by chemzqm** [comment]
It seems that you have current window scrolled but the floating window doesn't follow.

We need connection log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc, save your vimrc and exit vim.
* Restart your vim/neovim to make the issue happen.
* Get the log filepath by :echo $NODE_CLIENT_LOG_FILE
* Attach the log file or paste content from the log.

**Comment by romgrk** [comment]
Here is the log file: https://gist.github.com/romgrk/2ce6bc48acbad9c15227c6e8ad680b77

Also note that the window is not scrolled, here is an example:

![demo](https://user-images.githubusercontent.com/1423607/96835357-7b443800-1411-11eb-9ed4-158e4906bf5b.gif)

**Comment by chemzqm** [comment]
The log is wrong.

**Comment by romgrk** [comment]
What do you mean by the log is wrong? Is there missing information? What were you expecting?

**Comment by chemzqm** [comment]
It's not generated by coc.nvim, try add `echo config` after https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/float.vim#L94 and paste the echoed string.

**Comment by romgrk** [comment]
Sure, here it is:
```
// config
{'col': -8, 'row': -8, 'width': 59, 'relative': 'cursor', 'height': 8}
// #{lines:&lines, columns: &columns, position: getpos('.')}
{'columns': 124, 'lines': 27, 'position': [0, 172, 13, 0]}
```

![Screenshot from 2020-10-22 08-38-19](https://user-images.githubusercontent.com/1423607/96872701-fb829180-1441-11eb-9442-eceb8d6f9d5e.png)

**Comment by chemzqm** [comment]
The `height` is `8`, so looks like something resize the window, try disable other coc.nvim's extension.

**Comment by oblitum** [comment]
@romgrk may I ask what you're using for statusline/tabline?

**Comment by romgrk** [comment]
@oblitum sure, you can dm me on gitter @romgrk if you have questions
 - tabline: https://github.com/romgrk/barbar.nvim (released today, you're lucky!)
 - statusline: custom made: https://github.com/romgrk/nvim/blob/master/plugin/statusline.vim (depends on [lib.kom](https://github.com/romgrk/lib.kom) and [icon.vim](https://github.com/romgrk/nvim/blob/master/plugin/icon.vim))

@chemzqm one more observation: it happens only for vimscript files, not for any other ftypes I've tested with. Keep the issue open I'll continue debugging in the next days.

**Comment by romgrk** [comment]
I've investigated further and indeed, the configuration of the float window right after it has been open is `height: 8`. However after 1-100ms, the height of the window is changed to 10 by something else. I've added a `timer_start` in there to confirm that. I have however no idea who might be causing it.

I've tried disabling all coc.nvim extensions, however the issue isn't reproducible in that case because the hints window simply doesn't appear. Any other hint how I may debug this?

**Comment by chemzqm** [comment]
Enable coc-vimlsp first, then enable some of them each time

**Comment by romgrk** [comment]
After updating coc, disabling all the extensions & reinstalling all of them, I can't reproduce the issue anymore. I'll reopen if the problem re-appears.

**Comment by oblitum** [comment]
On #2472 I did comment regarding max height stopped being respected though. May or may not be related to this.
