### ISSUE TITLE
Disable startup warning for vim version except for the first time

### ISSUE THREAD

**Issue by himat** [neoclide/coc.nvim#2501]
**Is your feature request related to a problem? Please describe.**
When I install my dotfiles with coc on a new machine, that machine may not have the up to date vim that I have on my regular machine.
In this case, I always get this error 
```
coc.nvim need vim >= 8.1.1719 to support features like popup and text property.
Consider upgrade your vim for better experience.
You can add this to your vimrc to avoid this message:
    let g:coc_disable_startup_warning = 1
Note that some features may behave incorrectly.
```

I can indeed set `g:coc_disable_startup_warning = 1`
But if I add that to my .vimrc, then on other machines, I'll never see that warning again.

But the thing is that the first time I open vim with coc on a new machine, I do want to see that warning just so I'm aware that my coc may not work properly on this machine. And after I see it the first time, then I don't want to see it again on this machine the next time I open vim.

Is there a way to make this happen?

**Describe the solution you'd like**
I guess one possible way is to store some flag in the coc files that gets set when the warning is first shown, and then have an option to disable the warning from showing after the first time it's shown.

**Describe alternatives you've considered**
Without modifying coc, the only thing I can think of is that I would have to add another .vimrc file like `.vimrc.extra` which is local to each machine I add my vimrc to, which would get sourced in my regular, shared .vimrc, in which I can set `g:coc_disable_startup_warning = 1` after I get that warning.

**Comment by himat** [comment]
Also, is there a way to just automatically disable coc if the vim version isn't high enough?

**Comment by chemzqm** [comment]
You have to implicit set that variable

**Comment by chemzqm** [comment]
My suggestion is upgrade your vim for better experience

**Comment by himat** [comment]
Yeah but in some cases, I am sshing into a machine where I don't have permission to upgrade the vim
