### ISSUE TITLE
2507d7 broke language server logging

### ISSUE THREAD

**Issue by smackesey** [neoclide/coc.nvim#2505]
## Describe the bug

After commit 2507d7, language-server-specific logs stopped appearing under `CocInfo`. It's unclear how to view logs at all now.

## Reproduce the bug

Just run any language server and check `CocInfo`. There are no longer sections for each server.

**Comment by chemzqm** [comment]
Yes, because that could be too long, use output channel instead

**Comment by smackesey** [comment]
Ok, I see. I was able to find `workspace.showOutput` command in the wiki. There is no mention of this anywhere in the vim help though, and the old option of `CocList output` doesn't work anymore, even though it's still listed.

**Comment by wheelhorse** [comment]
> Ok, I see. I was able to find `workspace.showOutput` command in the wiki. There is no mention of this anywhere in the vim help though, and the old option of `CocList output` doesn't work anymore, even though it's still listed.

Could you help to post the wiki link? it's not easy to find the related information.

**Comment by wheelhorse** [comment]
> > Ok, I see. I was able to find `workspace.showOutput` command in the wiki. There is no mention of this anywhere in the vim help though, and the old option of `CocList output` doesn't work anymore, even though it's still listed.
> 
> Could you help to post the wiki link? it's not easy to find the related information.

Found the sequence of how to check language server log now ... as follows:
:CocList commands
select > workspace.showOutput

Thanks for your update.
