### ISSUE TITLE
Visual artifacts when canceling an auto-completion

### ISSUE THREAD

**Issue by MasterMedo** [neoclide/coc.nvim#2506]
## versions

vim version: NVIM v0.5.0-762-g9817d9914
node version: v15.0.0
coc.nvim version: 0.0.79-45cda5fc30
coc.nvim directory: /home/medo/.vim/plugged/
term: st-256color
platform: linux

## Output channel: Python
Starting Jedi Python language engine.

## Output channel: snippets
[Info 9:05:50 PM] Using ultisnips directorie
[Info 9:05:50 PM] Using ultisnips python com

## Describe the bug

When canceling an auto-completion; visual artifacts (in this case, but not limited to, function documentation) stay on the screen.
I'm trying to get rid of pesky dots at the end of some auto-completions using an autocommand.
The idea is to delete a dot at the end of an auto-completed word if it contains one using a regular expression.
In this particular example, for simplicity's sake I'm matching the python's built-in function range.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim'
  call plug#end()

  autocmd CompleteDone <buffer> silent! if v:completed_item.word =~ 'range'
                              \| call feedkeys("\<bs>")
                              \| endif
  ```

- Start neovim with command: `nvim -u mini.vim tmp.py`

- Type something to get off the edge of the screen

- start a new word with a single letter

- scroll through the menu until any visual artifact is shown

- press escape, the artifact stays on the screen

## Screenshots (optional)

![output](https://user-images.githubusercontent.com/16375100/97047911-f32d7200-1579-11eb-9795-bd6adeb2c61f.gif)

**Comment by cdddg** [comment]
I ran into the same problem

**Comment by chemzqm** [comment]
It's already fixed, please upgrade to the latest release branch of coc.nvim.

**Comment by MasterMedo** [comment]
This issue still persists on the release branch.

## versions

vim version: NVIM v0.5.0-762-g9817d9914
node version: v15.0.0
coc.nvim version: 0.0.79-d3293597d1
coc.nvim directory: /home/medo/.vim/plugged/coc.nvim
term: st-256color
platform: linux

**Comment by chemzqm** [comment]
I got the reason, your vimscript could be broken since `v:completed_item` could be empty.

**Comment by MasterMedo** [comment]
Yep, that did it.

For completeness' sake:

```vim
autocmd CompleteDone <buffer> if has_key(v:completed_item, 'word') && v:completed_item.word =~ '\.$'
                            \| call feedkeys("\<bs>")
                            \| endif
```
