### ISSUE TITLE
Question: can I set hover target type to preview for functions?

### ISSUE THREAD

**Issue by amirongit** [neoclide/coc.nvim#2508]
I'm new to coc.nvim, so I don't like float windows, I made documentaion to show in preview mode using this settings:
```coc.preferences.hoverTarget: preview```
when I'm calling a function in vim, coc shows me arguments in a float window, can I make it to show them in a split window like preview mode ?

**Comment by chemzqm** [comment]
It's signture, you can change the target to echo
