### ISSUE TITLE
[model-float] - Error on create popup: request error nvim_call_function

### ISSUE THREAD

**Issue by heapslip** [neoclide/coc.nvim#2512]
## Result from CocInfo

vim version: NVIM v0.5.0-773-g932585fd9
node version: v14.7.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/x/.local/share/nvim/site/pack/packer/start/coc.nvim
term: screen-256color
platform: linux

## Describe the bug

Floating windows such as the doHover one are not working (tested for go, tsserver).

2020-10-25T11:40:43.178 ERROR (pid:306350) [model-float] - Error on create popup: request error nvim_call_function - Vim:E118: Too many arguments for function: coc#float#get_float_mode

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Move your cursor over a keyword and `call CocActionAsync('doHover')`

**Comment by chemzqm** [comment]
You have to compile javascript after update when not using release branch
