### ISSUE TITLE
When showing symbol references in CocList, add the function name where the symbol is found

### ISSUE THREAD

**Issue by shahar3000** [neoclide/coc.nvim#2514]
When looking for a symbol, Similar to cscope, it would be great if the function name the symbol was found at would appear in the list of results, for example:

![image](https://user-images.githubusercontent.com/12958289/97109258-e4120580-16da-11eb-9fc2-ee7594b1f489.png)

**Comment by chemzqm** [comment]
Can't understand.

**Comment by shahar3000** [comment]
when using for example <Plug>(coc-references) the location list shows lines in the format:
`<file_path>|<line_num> col <col_num>|<line>`

the new format I propose is
`<file_path>|<line_num> col <col_num>|<<function_name>><line>`


for example, this line:
`src/vsd/vsd-rsm.c |1251 col 11|  wcommon->released = false;`
would become:
`src/vsd/vsd-rsm.c |1251 col 11|  <rsm_st_dst_apply_log_tree_intent> wcommon->released = false;`
