### ISSUE TITLE
Relative path doesn't recognized

### ISSUE THREAD

**Issue by timsofteng** [neoclide/coc.nvim#2515]
Hello.
When I'm usign relative path like that in my `vue` files coc doesn't recognize it so I cant  do go to definition.
![image](https://user-images.githubusercontent.com/51912173/97115443-6c0a0680-16ff-11eb-958b-91636dfb5e6d.png)

What i need to do to enable it?
Thanks.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Ask maintainer of your language server.

**Comment by NathanKleekamp** [comment]
In case it helps anyone else, try adding a `jsconfig.json` file to your project root as described in [the docs](https://github.com/neoclide/coc-tsserver#coc-tsserver). Also see [VSCode's docs](https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases), which are relevant to this issue.
