### ISSUE TITLE
No autocompletion for JS and TS files except for words opened in buffers

### ISSUE THREAD

**Issue by KerryMahne** [neoclide/coc.nvim#2517]
Greetings! As of the latest version, I am getting no autocompletion for imported libraries like `React` and not even for vanilla JS functions like `console`.  The only autocompletion suggestions I get are for things already open in other nvim buffers.

![image](https://user-images.githubusercontent.com/23449297/97167250-c601df00-1786-11eb-9ddd-bc3e20bbd42c.png)

As you can see, it doesn't recommend any useX hooks, instead it just returns the `useTranslation` one which is written on the line above.

Versions:
- coc - latest release (0.0.79)
- node - 14.14.0
- neovim - 0.4.4

Could you perhaps guide me on how to provide more useful info? The same nvim config works on another machine, it just stopped working on my PC :/

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by KerryMahne** [comment]
Not sure how this can be closed by linking troubleshooting for ts-server, since I am not even using it. 
It happens on vanilla JS files too, even without all the typescript plugins.
I followed the steps and got no output sadly

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by KerryMahne** [comment]
Thanks for the tips, I was missing the npm path, so the service didn't even start.
Probably borked when updating the node version.

Cheers!
