### ISSUE TITLE
"diagnostic.displayByAle": true trumps  "diagnostic.enable": false

### ISSUE THREAD

**Issue by DZ84** [neoclide/coc.nvim#2519]
# Result from CocInfo

vim version: VIM - Vi IMproved 8.2 8021767
node version: v14.14.0
coc.nvim version: 0.0.79-d3293597d1
coc.nvim directory: /home/dennis/.vim/pack/mypackages/start/coc.nvim
term: dumb
platform: linux

## Describe the bug

`"diagnostic.displayByAle": true` trumps  `"diagnostic.enable": false` which I think is not intuitive. If I put `diagnostic.enable` to `false` I wouldn't expect any diagnostics run, regardless of any other settings. However if `diagnostic.displayByAle` is set to `true` diagnostics are run anyway.

**Comment by chemzqm** [comment]
You can disable duagnostic shown, not run, unless you can disable server's diagnose feature
