### ISSUE TITLE
coc-diagnostic-info on line

### ISSUE THREAD

**Issue by dakom** [neoclide/coc.nvim#252]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I'm on a line containing an error, but not on the exact word, and hit my keybinding for `coc-diagnostic-info` but nothing happens

**Describe the solution you'd like**
make `coc-diagnostic-info` fire per-line... tbh I'm not sure what should happen when there's multiple errors on the line, might be worth looking at ALE for inspiration

**Describe alternatives you've considered**
I tend to jump next/previous until I hit the word - it's not awful, but not ideal

**Additional context**
Nope :)

**Comment by chemzqm** [comment]
Nope, you should use something like:
```
nmap <silent> [c <Plug>(coc-diagnostic-prev)
nmap <silent> ]c <Plug>(coc-diagnostic-next)
```
to jump to the range that contain error. coc is not ale, each error has range, you won't get error message if your cursor is not in error range. 
After the jump coc could echo multiple lines of error message.

**Comment by dakom** [comment]
is it something that could be solved programatically?

For example to set the range to contain all the errors on the current line and display them (if there are any) ?

**Comment by chemzqm** [comment]
The current errors of coc are the errors that contain current cursor position, not current line, this is by design, you have to fork coc if you want the errors to be the ones interact with current line.

**Comment by dakom** [comment]
ok, will keep using next/prev :)

Sortof a followup question, but not sure if it's a quick answer so I figured I'll ask here instead of opening another issue:

To see all the current errors at once, I `:lopen` to open the location list. Is it possible to jump to the error from the location list?

**Comment by chemzqm** [comment]
> I :lopen to open the location list. Is it possible to jump to the error from the location list?

Press `<enter>` should jump, also checkout `:h location-list` for available commands of vim.

**Comment by dakom** [comment]
Thanks - didn't realize I was on the line and needed :lnext / :lprev to jump in the location list.

Feel free to close this at your convenience :)
