### ISSUE TITLE
Visual guide for what each highlight/color stands for

### ISSUE THREAD

**Issue by JDuchniewicz** [neoclide/coc.nvim#2520]
**Problem**
I am currently having some troubles in deducing which highlighting element I should change in order to have my documentation of function display properly in a floating/scrollable window. 

The background is what I want, but the text inside the backticks obtains the same color as background, rendering it invisible. 

I thought that maybe it is related to some syntax highlighter running in the background but that is not the case.

**Solution**
Incorporate descriptions of different highlight zones to the manual, so that the user can see which color is responsible for what visually (I, for instance, cannot find the proper element to highlight in the manual).

**Screenshots**
![github](https://user-images.githubusercontent.com/18423461/97194900-f8bdce80-17aa-11eb-9a70-41fd601d903e.png)

**Comment by chemzqm** [comment]
That would only cause unnecessary performance cost, my suggestion is change CocFloat highlight group.

**Comment by benknoble** [comment]
@chemzqm Forgive me if I have missed some context, but what performance cost is incurred by adding documentation? I think what is asked for here is simply documentation.

**Comment by chemzqm** [comment]
:h coc-highlights

**Comment by JDuchniewicz** [comment]
Hmm maybe I made myself not clear enough. What I proposed is a documentation of these highlights in a human-friendly fashion, like this ( a very crude sketch):

A visual description of highlights in coc.nvim:
```
completionText
       |     omni dropdown -> highlight CocFloating             |          documentation -> highlight CocFloating        |
       |     additional suggestion                              |                                                        |
                                                                |         ```programming_lang                            |
                                                                |         some code -> highlight Constant                |
                                                                |                                                        |
                                                                |                                                        |
                                                                |       ```                                              |
```
