### ISSUE TITLE
Make coc#float#scroll work in visual mode?

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#2521]
**Is your feature request related to a problem? Please describe.**

#2472 has added `coc#float#scroll` which works in normal and insert mode. Sadly (tested on nvim 0.4.4), it doesn't work on visual mode, which is an important use case on snippet expansion and jump placeholder.

**Describe the solution you'd like**

I wished it could be made to work as it works for insert and normal mode.

**Describe alternatives you've considered**

`coc#util#float_scroll_i`, which was added before #2472, can scroll in visual mode, the problem is that it was not improved to handle the scrollbar that was introduced by #2472, so even though it scrolls, the scrollbar is static on top, it never updates.

I'm not sure whether code from `coc#util#float_scroll_i` can be used as reference to make `coc#float#scroll` work in visual mode, or whether `coc#util#float_scroll_i` can be improved to update scrollbar position. I tried the latter by appending a call to `coc#float#nvim_scrollbar` to it but it didn't work.

**Additional context**

I commented about this [here](https://github.com/neoclide/coc.nvim/issues/2472#issuecomment-714681891), so I'm just opening this new issue so that won't get lost in comments.

**Comment by chemzqm** [comment]
Nope, it can't be correct IMO

**Comment by oblitum** [comment]
Oh, just managed to make `coc#util#float_scroll_it` to update the scrollbar state in visual mode, I just had to use the `timer_start` hack instead of calling `coc#float#nvim_scrollbar` directly:

```diff
diff --git a/autoload/coc/util.vim b/autoload/coc/util.vim
index 08ee758..9ead5e0 100644
--- a/autoload/coc/util.vim
+++ b/autoload/coc/util.vim
@@ -115,6 +115,7 @@ function! coc#util#float_scroll_i(amount)
   endif
   call nvim_win_set_var(float, 'coc_float_scroll_last_amount', a:amount)
   call nvim_win_set_cursor(float, pos)
+  call timer_start(10, { -> coc#float#nvim_scrollbar(float)})
   return ''
 endfunction
```

**Comment by oblitum** [comment]
My current mappings after that patch being applied locally:

```vim
let g:coc_snippet_next = '<c-l>'
let g:coc_snippet_prev = '<c-h>'
nnoremap <silent><expr> <c-j> coc#float#has_scroll() ? coc#float#scroll(1, 1) : "\<c-j>"
nnoremap <silent><expr> <c-k> coc#float#has_scroll() ? coc#float#scroll(0, 1) : "\<c-k>"
inoremap <silent><expr> <c-j> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1, 1)\<cr>" : "\<c-j>"
inoremap <silent><expr> <c-k> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0, 1)\<cr>" : "\<c-k>"
vnoremap <silent><expr> <c-j> coc#float#has_scroll() ? coc#util#float_scroll_i( 1) : "\<c-j>"
vnoremap <silent><expr> <c-k> coc#float#has_scroll() ? coc#util#float_scroll_i(-1) : "\<c-k>"
```

![gif-2020-10-27-154243](https://user-images.githubusercontent.com/1269815/97347392-806b1200-186b-11eb-90c2-4659079205b8.gif)

**Comment by oblitum** [comment]
> Nope, it can't be correct IMO

Sorry, I didn't get what you mean. Do you mean there isn't a way to implement it right? (`coc#util#float_scroll_i` is not ideal as it still miss correct scroll on wrapped text)

**Comment by chemzqm** [comment]
It's neovim only and could be not work at all

**Comment by oblitum** [comment]
Okay, I'll send a PR then, to add this line to sync the scrollbar.

**Comment by oblitum** [comment]
Partially solved by #2532. Maybe futurely `coc#float#scroll` will be able to handle this :)

**Comment by chemzqm** [comment]
It can't be correct unless neovim provide `win_execute` function or support `winid` for `line()`.

**Comment by oblitum** [comment]
> It can't be correct unless neovim provide `win_execute` function or support `winid` for `line()`.

@chemzqm, I just learned that in neovim exists `:h <Cmd>`, and the docs has something about it not changing modes, while executing complex stuff. Not sure whether it may be useful for this.

**Comment by chemzqm** [comment]
No, it's caused by cursor have to move to another window

**Comment by oblitum** [comment]
@chemzqm hm, okay.

**Comment by rpearce** [comment]
@oblitum's remapping got this working for me, but I used `C-d` and `C-u`. Thanks!

**Comment by chemzqm** [comment]
coc#float#scroll now works on all modes.
