### ISSUE TITLE
question: how to get rid of the server will not be restarted message

### ISSUE THREAD

**Issue by ssh352** [neoclide/coc.nvim#2523]
[coc.nvim] The "java" server crashed 5 times in the last 3 minutes. The server will not be restarted.

Could you please advise what cache files to delete or something like that to reset the coc state so that when I open my project this doesn't happen? Thanks!

**Comment by chemzqm** [comment]
It's a variable, you have to fix your language server

**Comment by ssh352** [comment]
It is a variable. Could you advise why even after rebooting the computer and killing all node instances coc still remembers this state? How to let coc forget the fact the server has crashed many times before? Thanks

**Comment by ssh352** [comment]
> It's a variable, you have to fix your language server

It is a variable. Could you advise why even after rebooting the computer and killing all node instances, coc still remembers this state? How to let coc forget the fact the server has crashed many times before? Thanks
