### ISSUE TITLE
[ccoc-references] gr not working for js export default

### ISSUE THREAD

**Issue by neewbee** [neoclide/coc.nvim#2526]
## versions

```terminal
vim version: VIM - Vi IMproved 8.2 8021719
node version: v12.18.2
coc.nvim version: 0.0.79-799348cd1a
coc.nvim directory: /Users/neewbee/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug

gr not working for

```javascript
export default () => {}
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
Should be problme of your tsserver https://github.com/neoclide/coc-tsserver#troubleshooting

**Comment by chemzqm** [comment]
Ask typescript team for help.
