### ISSUE TITLE
revealOutputChannelOn is not actually default never

### ISSUE THREAD

**Issue by daquexian** [neoclide/coc.nvim#253]
**Result from CocInfo**
vim version: NVIM v0.3.1
node version: v11.4.0
coc.nvim version: 0.0.38
term: screen-256color
platform: linux

**Describe the bug**
Although f5271b671469761dad37fb0377f8829e8819135d exists, the `revealOutputChannelOn` is not actually 'never' by default. It is controlled by `data/schema.json` instead of https://github.com/neoclide/coc.nvim/blob/462ce6c4a84de5a6ae610ec53251cdeda0b952aa/src/language-client/client.ts#L3132-L3133

**To Reproduce**
1. The split window still pops up when an error occurs.
2. Change all `revealOutputChannelOn` in `data/schema.json` to `never`
3. The split window doesn't appear anymore

**Comment by chemzqm** [comment]
I got it, the code in `servers.ts` should change too.

**Comment by oblitum** [comment]
This also may be related to my request regarding it showing up when server command is not available?

**Comment by chemzqm** [comment]
It's same issue.

**Comment by oblitum** [comment]
Shouldn't `schema.json` have been changed too?
