### ISSUE TITLE
Option to show ItemKindLabels on the left

### ISSUE THREAD

**Issue by cooper-anderson** [neoclide/coc.nvim#2535]
I am not sure if there is already a way to do this, but I have done research and not found anything.
What I want is to be able to show ItemKindLabels on the left side of the completion popup, instead of the right.

In addition, perhaps the ability to offset the completion window to the left so that the characters still line up with the completion options.

Currently, what I have looks like this:
![image](https://user-images.githubusercontent.com/21961037/97414783-6ca6c680-18d2-11eb-9ff3-9fb789196ad5.png)

Whereas in a program like WebStorm, I can have this:
![image](https://user-images.githubusercontent.com/21961037/97414894-8ba55880-18d2-11eb-9206-077ec26f6c6a.png)

**Comment by chemzqm** [comment]
You have to send this feature request to vim.
