### ISSUE TITLE
Is there is a way to paste local machine's clipboard in CocList

### ISSUE THREAD

**Issue by chrisniael** [neoclide/coc.nvim#2536]
Local machine: Mac
Remote machine: Linux
Mac ssh Linux

By default, when I using shortkey `C-v` in coclist(**insert mode**), **coclist** will paste remote linux's system clipboard.

Can I paste Mac's system clipboard content to **coclist** (insert mode) directly?

**Comment by chemzqm** [comment]
You can use custom vim function which retrieve your paste content from your mac, but I don't know how.

**Comment by chrisniael** [comment]
Thanks Reply.

Maybe my description above is not very clear. 

I don't want to use the default shortcut key C-v of coclist to paste the contents of the clipboard of the local system.

What I want to do is to use the local Mac system shortcut (Command + v) to paste the content into the coclist opened remotely by ssh.

Just like executing the vim command, you can directly use the paste shortcut of the local system to paste the contents of the local clipboard in the vim command mode.

**Comment by chemzqm** [comment]
It's not possible to get your paste text when using `getchar()` of vim, so you have to implement the feature.
