### ISSUE TITLE
The future of coc.nvim

### ISSUE THREAD

**Issue by BonaBeavis** [neoclide/coc.nvim#2544]
Now that the built-in lsp client approaches a usable state, how does coc.nvim relate to it? Will it soon be obsolete? Does it have unique features, nvims lsp client won't be able to implement? Or is the future the built-in lsp client + coc as an "compatibility layer" for vscode plugins + coclist as an ui?

**Comment by chemzqm** [comment]
Read wiki https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#why-are-coc-extensions-needed, it's not goal for coc.nvim to load vscode plugins.

**Comment by oblitum** [comment]
> Now that the built-in lsp client approaches a usable state, how does coc.nvim relate to it?

There no code relation whatsoever, doesn't mean it there can't be.

> Will it soon be obsolete?

coc.nvim supports both Vim and NeoVim, so the question kinda doesn't make much sense.

> Does it have unique features, nvims lsp client won't be able to implement?

Coc provides lots of UX logic for signatureHelp floating windows, docs, lists, etc, besides
easy-to-install extensions, with added features and commands. From what I could gather from
nvimlsp ecosystem, it'll take a good time for it to attain feature parity with stability,
until then, coc.nvim could (possibl) be using nvim's native lsp features (or not).

> Or is the future the built-in lsp client + coc as an "compatibility layer" for vscode plugins + coclist as an ui?

Mistaken vision. Doesn't apply as previously commented.

IIRC, @justinmk once shared an opinion, which I agree, that (on NeoVim's side)
post built-in LSP, the field will be mainly reduced to minimalist nvimlsp-based
solutions vs fully featured VSCode-like experience (like Coc) solutions, and
other approaches in the middle will fall in desuse or not make much sense.

You have to realise that just by having built-in LSP doesn't equate to have a
an IDE-like experience, it's just some building block, and until someone writes
a plugin that builds on that foundation to provide the IDE-like experience,
there'll be users left interested in having that, and hence in Coc.

**Comment by nichohells** [comment]
For people who still use Vim and probably won't ever move to Nvim, CoC will be the last pinnacle of reliable LSP support for the OG Vim
