### ISSUE TITLE
pyx javascript problem

### ISSUE THREAD

**Issue by Bhaffo** [neoclide/coc.nvim#2551]
Help i have this when i run :checkhealth and i dont know what to do, i try many thing and nothing works

>health#coc#check
>========================================================================
 >- OK: Environment check passed
  >- WARNING: pyx command not work, some extensions may fail to work, checkout ":help pythonx"
  >- ERROR: Javascript entry not found, run "yarn install --frozen-lockfile" in terminal to fix it.
  >- ERROR: service could not be initialized
    - ADVICE:
      - Use command ":messages" to get error messages.
      - Open a issue at https://github.com/neoclide/coc.nvim/issues for feedback.

>health#nvim#check
>========================================================================
>## Configuration
  >- OK: no issues found

>## Performance
  >- OK: Build type: RelWithDebInfo

>## Remote Plugins
  >- OK: Up to date

>health#provider#check
>========================================================================
>## Clipboard (optional)
  >- OK: Clipboard tool found: win32yank

>## Python 2 provider (optional)
  >- WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  >- ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          C:\Users\Bhaffo\anaconda3\python.EXE is Python 3.8 and cannot provide Python 2.
  >- INFO: Executable: Not found

>## Python 3 provider (optional)
  >- WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  >- ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          python3 not found in search path or not executable.
          python3.7 not found in search path or not executable.
          python3.6 not found in search path or not executable.
          python3.5 not found in search path or not executable.
          python3.4 not found in search path or not executable.
          python3.3 not found in search path or not executable.
          C:\Users\Bhaffo\anaconda3\python.EXE does not have the "neovim" module. :help |provider-python|
  >- INFO: Executable: Not found

>## Ruby provider (optional)
 > - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
     - Install Ruby and verify that `ruby` and `gem` commands work.

>## Node.js provider (optional)
  >- INFO: Node.js: v15.0.1
  >- WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add

**Comment by chemzqm** [comment]
Read wiki
