### ISSUE TITLE
Change default branch to release

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#2555]
Most people don't want to build coc.nvim from typescript source code, and many of them have trouble with branch select when using their plugin manager.

> Changing your default branch can have unintended consequences that can affect new pull requests and clones.

After change default branch to release, the default cloned branch and PR branch would be changed to release, change it to master when needed. 

We will also change docs and wiki.

For vim-plug user who want to build from source code, you may need use:

``` vim
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
```
in your vimrc.

**Comment by oblitum** [comment]
Shouldn't README change this

```vim
" Use release branch (recommend)
Plug 'neoclide/coc.nvim', {'branch': 'release'}
```

to this

```vim
" Use release branch (recommend)
Plug 'neoclide/coc.nvim'
```

Since release is the default and was made so because some package managers don't support branch?

**Comment by chemzqm** [comment]
No, vim-plug will always use master as default.

**Comment by oblitum** [comment]
oh, sad, didn't know it behaved like that :-/

**Comment by oblitum** [comment]
But, wait a moment, I myself don't have it set and it clones the release branch, at least on Linux it behaves accordingly, actually I removed the branch setting as soon as release became the default.
