### ISSUE TITLE
"preview" hoverTarget and CocDiagnosticChange autocmd are not synchronized

### ISSUE THREAD

**Issue by tomtomjhj** [neoclide/coc.nvim#2557]
## Describe the bug
`"coc.preferences.hoverTarget": "preview"` and `autocmd User CocDiagnosticChange` breaks RPC because they are not well-synchronized. This makes `autocmd User CocStatusChange,CocDiagnosticChange call lightline#update()` unusable.

### `mini.vim`
```vim
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

let g:coc_global_extensions = ['coc-tsserver']
autocmd User CocDiagnosticChange sleep 123m
```

### `coc-settings.json`
```json
{ "coc.preferences.hoverTarget": "preview" }
```

### `example.js`
```javascript
var a = 1
```

### steps to reproduce
1. `nvim -u mini.vim example.js` (not reproducible in vim)
2. move the cursot to the variable `a`
3. run `:call CocAction("doHover")<CR>`. Wait for the hover info on the preview window. Do not close the preview window.
4. run `:call CocAction("doHover")<CR>` again.

Result:
```
Error on request (CocAutocmd): Vim(return):Error invoking 'CocAutocmd' on channel 3 (coc):
ch 3 returned a response with an unknown request id. Ensure the client is properly synchronized
Error on request (doHover): Vim(return):Error invoking 'doHover' on channel 3 (coc):
ch 3 returned a response with an unknown request id. Ensure the client is properly synchronized
```

### `:CocInfo`
```
## versions

vim version: NVIM v0.5.0-dev
node version: v10.19.0
coc.nvim version: 0.0.79-73397d535c
coc.nvim directory: ~/.vim/plugged/coc.nvim
term: tmux-256color
platform: linux

## Log of coc.nvim

2020-11-04T15:09:39.546 INFO (pid:554308) [services] - registered service "tsserver"
2020-11-04T15:09:39.577 INFO (pid:554308) [plugin] - coc.nvim 0.0.79-73397d535c initialized with node: v10.19.0 after 119ms
2020-11-04T15:09:39.926 INFO (pid:554308) [services] - service tsserver started
```

### `:version`
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-LrBDH4/neovim-0.5.0+ubuntu2+git202010290556-c6ccdda26-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-LrBDH4/neovim-0.5.0+ubuntu2+git202010290556-c6ccdda26-d569569c9/build/config -I/build/neovim-LrBDH4/neovim-0.5.0+ubuntu2+git202010290556-c6ccdda26-d569569c9/src -I/build/neovim-LrBDH4/neovim-0.5.0+ubuntu2+git202010290556-c6ccdda26-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-LrBDH4/neovim-0.5.0+ubuntu2+git202010290556-c6ccdda26-d569569c9/build/src/nvim/auto -I/build/neovim-LrBDH4/neovim-0.5.0+ubuntu2+git202010290556-c6ccdda26-d569569c9/build/include
Compiled by buildd@lgw01-amd64-024

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

## Note
I believe the bug is related to `BufUnload` autocmd for `coc://document` because the last autocmd before `CocDiagnosticChange` is `BufUnload` (see the log below).  If I make `BufUnload` strictly happen before `CocDiagnosticChange` by manually closing the preview window before the second hover, everyting works fine.  So I guess we should add some synchrization between `BufUnload` and `CocDiagnosticChange`.

<details>
<summary>part of `-V9` log</summary>
<pre>
Executing CursorMoved Autocommands for "*"
autocommand call coc#float#nvim_refresh_scrollbar(win_getid())

autocommand call s:Autocmd('CursorMoved', +expand('<abuf>'), [line('.'), col('.')])

Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing WinLeave Autocommands for "*"
autocommand call coc#util#clear_highlights()

autocommand call s:Autocmd('WinLeave', win_getid())

Executing WinEnter Autocommands for "*"
autocommand call coc#float#nvim_win_enter(win_getid())

autocommand call s:Autocmd('WinEnter', win_getid())

Executing WinEnter Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMoved Autocommands for "*"
autocommand call coc#float#nvim_refresh_scrollbar(win_getid())

autocommand call s:Autocmd('CursorMoved', +expand('<abuf>'), [line('.'), col('.')])

Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing BufLeave Autocommands for "*"
autocommand if &ft != "netrw"|let w:netrw_prvfile= expand("%:p")|endif

Executing BufReadCmd Autocommands for "coc://*"
autocommand call coc#rpc#request('CocAutocmd', ['BufReadCmd','coc', expand('<amatch>')])

Executing FileType Autocommands for "*"
autocommand call s:LoadFTPlugin()

continuing in function <SNR>3_LoadFTPlugin
Executing FileType Autocommands for "*"
autocommand call s:LoadIndent()

not found in 'runtimepath': "indent/markdown.vim"
Executing FileType Autocommands for "*"
autocommand exe "set syntax=" . expand("<amatch>")

Executing Syntax Autocommands for "*"
autocommand call s:SynSet()

continuing in function <SNR>6_SynSet
Executing FileType Autocommands for "*"
autocommand call s:Autocmd('FileType', expand('<amatch>'), +expand('<abuf>'))

Executing BufEnter Autocommands for "*"
autocommand call s:Autocmd('BufEnter', +expand('<abuf>'))

Executing BufEnter Autocommands for "*"
autocommand sil call s:LocalBrowse(expand("<amatch>"))

Executing BufWinEnter Autocommands for "*"
autocommand call s:Autocmd('BufWinEnter', +expand('<abuf>'), win_getid())

Executing BufLeave Autocommands for "*"
autocommand if &ft != "netrw"|let w:netrw_prvfile= expand("%:p")|endif

Executing WinLeave Autocommands for "*"
autocommand call coc#util#clear_highlights()

autocommand call s:Autocmd('WinLeave', win_getid())

Executing WinEnter Autocommands for "*"
autocommand call coc#float#nvim_win_enter(win_getid())

autocommand call s:Autocmd('WinEnter', win_getid())

Executing WinEnter Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing BufEnter Autocommands for "*"
autocommand call s:Autocmd('BufEnter', +expand('<abuf>'))

Executing BufEnter Autocommands for "*"
autocommand sil call s:LocalBrowse(expand("<amatch>"))

Executing CursorMoved Autocommands for "*"
autocommand call coc#float#nvim_refresh_scrollbar(win_getid())

autocommand call s:Autocmd('CursorMoved', +expand('<abuf>'), [line('.'), col('.')])

Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing WinClosed Autocommands for "*"
autocommand call coc#float#close_related(+expand('<afile>'))

Executing BufWinLeave Autocommands for "*"
autocommand call s:Autocmd('BufWinLeave', +expand('<abuf>'), bufwinid(+expand('<abuf>')))

Executing BufUnload Autocommands for "*"
autocommand call s:SyncAutocmd('BufUnload', +expand('<abuf>'))

Executing User Autocommands for "CocDiagnosticChange"
autocommand sleep 123m

Error on request (CocAutocmd): Vim(return):Error invoking 'CocAutocmd' on channel 3 (coc):
ch 3 returned a response with an unknown request id. Ensure the client is properly synchronized
Error on request (doHover): Vim(return):Error invoking 'doHover' on channel 3 (coc):
ch 3 returned a response with an unknown request id. Ensure the client is properly synchronized
Executing BufWinLeave Autocommands for "*"
autocommand call s:Autocmd('BufWinLeave', +expand('<abuf>'), bufwinid(+expand('<abuf>')))

[coc] server connection lost
Executing BufUnload Autocommands for "*"
autocommand call s:SyncAutocmd('BufUnload', +expand('<abuf>'))

Executing VimLeavePre Autocommands for "*"
autocommand let g:coc_vim_leaving = 1
</pre>
</details>

--------

**Comment by chemzqm** [comment]
Use CocActionAsync instead, it's limitation of neovim since rpcrequest can't nest.
