### ISSUE TITLE
Change path of coc directory in ~/.config

### ISSUE THREAD

**Issue by noib3** [neoclide/coc.nvim#2570]
I noticed coc creates a `~/.config/coc` directory. Would be it possible to add an option to set a different path, for example `~/.config/nvim/coc`?

Since coc is a part of (neo)vim, it would make sense to create that subdirectory *inside* `~/.config/nvim` or `~/.vim`.

**Comment by chemzqm** [comment]
Read help

**Comment by Vanillma** [comment]
> Read help

Hi, is this feature available now??...I read the help...but didn't see anything about ~/.config (I tried searching with regex!) 😬

**Comment by fannheyward** [comment]
@Vanillma check `:h g:coc_config_home`

**Comment by Vanillma** [comment]
> @Vanillma check `:h g:coc_config_home` and `:h g:coc_data_home`.

Thanks bro...it works great...and thanks for the quick support!
