### ISSUE TITLE
unnormal exit with code 9

### ISSUE THREAD

**Issue by PICKQUE** [neoclide/coc.nvim#2571]
## Describe the bug

install failed.

## Reproduce the bug

ubuntu 18.04 vim version 8.2 
coc install failed. exitd code 9

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
Configure npm.binPath

**Comment by PICKQUE** [comment]
> Configure npm.binPath
where to configure the npm.binpath
