### ISSUE TITLE
Add option to select wether to use word or WORD boundaries for buffer and around source completion

### ISSUE THREAD

**Issue by nstetter** [neoclide/coc.nvim#2572]
**Is your feature request related to a problem? Please describe.**
I often use variables containing dashes e.g `extra-super-long-example-variable`. When navigating text using vim having dashes not in `iskeyword`  (default) is comfortable because I can jump inside my variable name, from dash to dash with `w` or jump the complete variable with `W`.
But using coc autocomplete with buffer or around as source the completion seems to us `iskeyword` (word boundaries), so when I start typing `ext ` I get completion for `extra`, but I would like to have it suggest `extra-super-long-example-variable`, using WORD boundaries.

**Describe the solution you'd like**
Add an option to coc, that let's the user decide wether to use WORD or word boundaries for buffer and around completions.

**Comment by chemzqm** [comment]
There is variable for additional keywords

**Comment by nstetter** [comment]
> There is variable for additional keywords

Could you please tell what the variable is called? I don't find it.

**Comment by chemzqm** [comment]
Use it with filetype autocmd.

**Comment by nstetter** [comment]
setting `autocmd FileType * let b:coc_additional_keywords = ["-"]` works. Thanks for the help.

**Comment by daedsidog** [comment]
Is it possible to also include `" "` in the additional keywords? Doing so has no effect for me.
