### ISSUE TITLE
Pressing enter (CR) causes pumvisible() ? "\"" : "\\ to be outputted

### ISSUE THREAD

**Issue by 12-Seconds** [neoclide/coc.nvim#2576]
## versions

vim version: NVIM v0.5.0-nightly
node version: v15.1.0
coc.nvim version: 0.0.79-be822b546f
coc.nvim directory: /Users/Matei/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2020-11-09T11:04:52.799 INFO (pid:65838) [services] - registered service "languageserver.bash"
2020-11-09T11:04:53.319 INFO (pid:65838) [plugin] - coc.nvim 0.0.79-be822b546f initialized with node: v15.1.0 after 1426ms

## Describe the bug

I've added `inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"` to my .vimrc to have enter confirm the autocompletion

## Reproduce the bug

Add `inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"` to your .vimrc

**Comment by fannheyward** [comment]
Can't reproduce, checkout `:verbose imap <cr>`.

**Comment by fannheyward** [comment]
Your `<cr>` is remapped by auto-pairs.vim and endwise.vim.

**Comment by drazik** [comment]
I also had a problem with `<cr>` being remapped by auto-pairs.vim. I didn't find how to make the mapping from Coc.nvim "stronger" than the one from auto-pairs.vim of how to disable the one from auto-pairs.vim. But it turns out that using coc-pairs in place of auto-pairs.vim do the job.
