### ISSUE TITLE
:CocAction('format') fails in `.vue` files

### ISSUE THREAD

**Issue by deathmaz** [neoclide/coc.nvim#258]
**Result from CocInfo**
## versions

vim version: NVIM v0.3.1
node version: v10.13.0
coc.nvim version: 0.0.38
term: xterm-256color
platform: linux

## Output channel: eslint
[Info  - 5:48:16 PM] ESLint server running in node v10.13.0
[Info  - 5:48:16 PM] ESLint library loaded from: /home/maz/server/www/homestead/t-rax/node_modules/eslint/lib/api.js

## Output channel: vetur
Vetur initialized
Prettier format failed
[Error  - 5:48:18 PM] Cannot read property 'useTabs' of undefined

**Describe the bug**
`:call CocAction('format')` - returns `[coc.nvim] Error output from vetur: Cannot read property 'useTabs' of undefined`
Worked fine before.

**To Reproduce**
create `.vue` file, put this inside:
```vue
<script>
export default {
    data: () => ({
        test: ''
    })
};
</script>

<template>
    <div></div>
</template>
```
run `:call CocAction('format')`

Thank you for a nice plugin!

**Comment by chemzqm** [comment]
It's caused by break change of options introduced by vetur, I've fixed that.

**Comment by deathmaz** [comment]
Thank you!
