### ISSUE TITLE
Error UI does not render for new buffer if the diagnostics where received before it was opened

### ISSUE THREAD

**Issue by zapling** [neoclide/coc.nvim#2583]
## versions

vim version: NVIM v0.4.4
node version: v15.0.1
coc.nvim version: 0.0.79-be822b546f
coc.nvim directory: /home/andreas/.vim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2020-11-10T09:52:37.401 INFO (pid:3811098) [services] - registered service "languageserver.golang"
2020-11-10T09:52:37.405 INFO (pid:3811098) [plugin] - coc.nvim 0.0.79-be822b546f initialized with node: v15.0.1 after 61ms
2020-11-10T09:52:42.407 INFO (pid:3811098) [services] - golang state change: stopped => starting
2020-11-10T09:52:42.417 INFO (pid:3811098) [language-client-index] - Language server "languageserver.golang" started with 3811317
2020-11-10T09:52:42.464 INFO (pid:3811098) [services] - golang state change: starting => running
2020-11-10T09:52:42.471 INFO (pid:3811098) [services] - service languageserver.golang started

## Describe the bug

I use `gopls` as the language server and I'm having a bit of trouble with diagnostics. When I open a new buffer the error UI isn't rendered. I can see in log that diagnostics was received when the language server was first instantiated. But when I open a new buffer with the file that the diagnostics was sent for, no errors are rendered.

I can see in `:CocList diagnostics` that Coc is aware of the diagnostics, but only after I made some minor change to the buffer (new line etc) the errors are rendered.

I filed a report at `gopls` thinking this was an issue with the language server at first, when `textDocument/didOpen` didn't get a diagnostics response. But `gopls` sends the diagnostics when first instantiated, and as the file hasn't changed since then, no new diagnostics request is made to respond to the `textDocument/didOpen`.

https://github.com/golang/go/issues/42468

## Reproduce the bug

Minimal vimrc `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```
This is my `coc-settings.json`
```
{
    "languageserver": {
        "golang": {
            "command": "gopls",
            "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
            "trace.server": "verbose",
            "filetypes": ["go"],
            "initializationOptions": {
                "usePlaceholders": true
            }
        }
    }
}
```
I can re-create the issue with this sample project.

```
go.mod
a.go
b/
b/c.go
```

`a.go`
```go
package main

import (
	"fmt"

	"github.com/zapling/gopls_test/b"
)

func main() {
    test := b.Abc()
    fmt.Println(test)
}
```

`c.go`
```go
package b

func Abc(s string) string {
    return "" + s
}
```

- Start vim `nvim -u ~/.config/nvim/mini.vim`
- Open `c.go` with `:e b/c.go`
- Open `a.go` in a new vertical split

## Screenshots (optional)

Directly after opening the vertical split and `a.go`
![Screenshot_2020-11-10_10-12-00](https://user-images.githubusercontent.com/15123086/98653420-4c005700-233d-11eb-9993-962ec769cfbf.png)

`:CocList diagnostics` output
![Screenshot_2020-11-10_10-12-16](https://user-images.githubusercontent.com/15123086/98653506-69352580-233d-11eb-84c1-8c3918278a93.png)

`a.go` after adding a new line
![Screenshot_2020-11-10_10-12-32](https://user-images.githubusercontent.com/15123086/98653530-70f4ca00-233d-11eb-9277-51122ee3e642.png)

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by zapling** [comment]
> Fixed on latest release branch of coc.nvim.

Much appreciated, the fix works like a charm.

Thank you!
