### ISSUE TITLE
CocNext/CocPrevious do not behave correctly

### ISSUE THREAD

**Issue by piersy** [neoclide/coc.nvim#2584]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v10.19.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/pierspowlesland/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-11-10T13:12:24.074 WARN (pid:3906387) [attach] - Plugin not ready when received "highlight" []
2020-11-10T13:12:24.200 INFO (pid:3906387) [plugin] - coc.nvim 0.0.79 initialized with node: v10.19.0 after 101ms
2020-11-10T13:12:24.208 INFO (pid:3906387) [services] - registered service "go"
2020-11-10T13:12:24.208 INFO (pid:3906387) [services] - gopls state change: stopped => starting
2020-11-10T13:12:24.276 INFO (pid:3906387) [services] - gopls state change: starting => running
2020-11-10T13:12:24.281 INFO (pid:3906387) [services] - service go started
```
Coc commit hash:`bd91ae42544d25e160eaf4e3fd63ecdde8441867`

### Part 1
`CocNext` does nothing the first time it is used (when we are at the beginning of the list). `CocPrevious`, similarly does nothing the first time it is used, when we are at the end of the list.
### Part 2
With previous versions of coc-nvim I was able to use the `CocNext` and `CocPrevious` commands to jump to the different locations in lists such as a list of references. `CocNext`/`CocPrevious` would leave my cursor at the location jumped to, allowing me to edit or explore that location.

We previously discussed this functionality [here](https://github.com/neoclide/coc.nvim/issues/2087#issuecomment-646943350) and you  were able to provide it.

Now `CocNext`/`CocPrevious` jump to the location but the cursor looks as if it is held in the command line, although I am able to scroll the main window by holding down `j`.
 
## Reproduce the bug

- Create file `mini.vim` with:

```vim
call plug#begin()

Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}

call plug#end()


" coc nvim suggests these settings

" TextEdit might fail if hidden is not set.
set hidden

" Some servers have issues with backup files, see #649
set nowritebackup
set nobackup
" Better display for messages
set cmdheight=2

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes

let g:coc_global_extensions = ['coc-go']


let mapleader = "\<Space>"
nmap <leader>u <Plug>(coc-references)
nnoremap <c-l> :CocNext<cr>
nnoremap <c-h> :CocPrev<cr>

let g:coc_enable_locationlist = 0
autocmd User CocLocationsChange CocList --no-quit --normal location
```
- Create file `coc-settings.json` with:
```json
{
	"list.normalMappings": {
		"<C-l>": "command:CocNext",
		"<C-h>": "command:CocPrev"
	}
}
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

1. Open a .go file.
1. Get references of some identifier (`<space>u`)
1. Press `<c-l> `(CocNext)
1. Notice that the highlighted list element has changed but that the main window content doesn't change to show that location.
1. Press `<c-l>` (CocNext) again.
1. Notice that now the main window has now updated to show the location of the highlighted list element.
1. Press `<c-l>` (CocNext) again.
1. Notice that the main window has jumped to show the location of the next list element (although the highlighted list element has not changed)
1. Notice that during these jumps the cursor is not appearing in main window.
1. Hold down `j`
1. Notice that the main window scrolls and brackets are highlighted even though the cursor remains in the command line.

## Screenshots (optional)
See the steps above in this gif.
![CocListCocNextCocPrevBug](https://user-images.githubusercontent.com/5087847/98685724-a27e8d00-235f-11eb-9257-b5bf80ab57fe.gif)

**Comment by chemzqm** [comment]
Why don't use auto preview feature? `:CocNext` would broken when type fast.

**Comment by piersy** [comment]
Hi @chemzqm 

In answer to your question

> Why don't use auto preview feature? :CocNext would be broken when type fast.

I explain a number of reasons why I don't want to use the auto preview feature, in the original feature request I raised here #2087. I don't understand what you mean about `:CocNext` being broken when typing fast.

This functionality is still not working as expected.

The functionality requested in #2087 was to be able to jump to the prev/next entires in the coc list in the same way as using  `:cnext/:cprev` with the quickfix list.

At present using `:CocNext/:CocPrev` leaves my cursor inside the `CocList` window, when in fact using `:CocNext/:CocPrev` should place my cursor in the main window at the location defined by the list entry.
