### ISSUE TITLE
Settings sometimes ignored

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#2597]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-822-g4e6f00dd2
node version: v12.19.0
coc.nvim version: 0.0.79
coc.nvim directory: /Users/chemzqm/vim-dev/coc.nvim
term: iTerm.app
platform: darwin

```
## Describe the bug

If I open Vim with an empty buffer and open a Java file later, the local setting is ignored. 

## Reproduce the bug

Create file `.vim/coc-settings.json` with:

```json
{
  "java.enabled": false
}
```

Start vim with other directory then open the file, jdt.ls would be started.

**Comment by oblitum** [comment]
Other problem with ignored settings as commented previously is due to inconsistency when `coc#config` should apply:

* https://github.com/neoclide/coc.nvim/issues/2593#issuecomment-726393937
* https://gitter.im/neoclide/coc.nvim?at=5fae0c23c10273610a0169be

**Comment by oblitum** [comment]
Signs now correct after 8b1bbed6e3850c0be16a1aae9a6f14d0d71781ff on `User CocNvimInit`, fixing what was commented at https://github.com/neoclide/coc.nvim/issues/2593#issuecomment-726393937, but there's still other configurations that don't apply on `coc#config` call on `User CocNvimInit`, like `signature.preferShownAbove`. I don't have much idea how many settings are ineffective from `User CocNvimInit`. I expect all configuration calls should work from this `autocmd`.
