### ISSUE TITLE
[Feature Request] make `codelens run` keep only one terminal buffer

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2599]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I run `codelens run` action it keeps opening new terminal buffers

![Peek 2020-11-13 12-14](https://user-images.githubusercontent.com/33961674/99066773-c7fed700-25a9-11eb-8321-062ef0ab2ade.gif)

As you can see it always try to open a new terminal buffer. It'll get worse if the project is a webserver which listens on a port, in that case even if we close the buffer, the process will still be there

**Describe the solution you'd like**

Keep track of all the opened terminal buffer which ends with a specific name like `coc.nvim`, close the previous one and kill its process (if webserver not exits) when user run codelens action again, or ask permission to close the previous one

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
Please send your feature request to https://github.com/fannheyward/coc-rust-analyzer

**Comment by chemzqm** [comment]
It could make use of terminal module by `workspace.createTerminal`
