### ISSUE TITLE
Please, search for the settings file in ~/.config/coc/coc-settings.json

### ISSUE THREAD

**Issue by Zeioth** [neoclide/coc.nvim#2601]
Since there's already a `~/.config/coc/` directory I see very little reason to obligate the user to have a ~/.vim or ~/.nvim folder. It would be a good idea to keep the config files on the config directory.

**Comment by Zeioth** [comment]
Just in case someone else read this post in the future: Add this to your vimrc

    let g:coc_config_home = '~/.config/coc'

**Comment by jared-mackey** [comment]
You may also want `let g:coc_data_home` if you want to move the data from COC into the NVIM folder instead.
