### ISSUE TITLE
The Search for the Missing Link, or, Links in markdown floating windows are hidden and unopenable

### ISSUE THREAD

**Issue by expipiplus1** [neoclide/coc.nvim#2603]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.4
node version: v12.19.0
coc.nvim version: 0.0.79-53f8a1d52b
coc.nvim directory: /nix/store/aclddl8n5qd8zb2c2zh1481ijxphymir-vimplugin-coc-nvim-2020-11-13/share/vim-plugins/coc-nvim
term: tmux
platform: linux

## Log of coc.nvim

2020-11-14T20:44:40.659 INFO (pid:20149) [plugin] - coc.nvim 0.0.79-53f8a1d52b initialized with node: v12.19.0 after 65ms

vim version: NVIM v0.4.4
node version: v12.19.0
coc.nvim version: 0.0.79-53f8a1d52b
coc.nvim directory: /nix/store/aclddl8n5qd8zb2c2zh1481ijxphymir-vimplugin-coc-nvim-2020-11-13/share/vim-plugins/coc-nvim
term: tmux
platform: linux

## Log of coc.nvim

2020-11-14T20:44:40.659 INFO (pid:20149) [plugin] - coc.nvim 0.0.79-53f8a1d52b initialized with node: v12.19.0 after 65ms
```

## Describe the bug

The markdown links in floating windows are not visible or openable. This is [important to me](https://xkcd.com/1172/) as I parse the text in this window in order to open documentation and source in my browser with this function: https://github.com/expipiplus1/dotfiles/blob/da408b1ce0ed51574b48d7cf9895757687bbd085/config/nixpkgs/home/coc-nvim.nix#L32-L51

Is it possible to get an option to disable this hiding behaviour, please?

## Reproduce the bug

- Open a floating window with a markdown link with `doHover`
- Observe that the link `[foo](file://bar)` is rendered as just `foo`
- Observe that the link is in the markdown with `getHover` which returns the pure text
- Run `CocList links` in the floating window
- Observe the error message: `[coc.nvim] Error on "CocList links": Links provider not found.`
- Put the cursor on one of these links and run `CocAction('openLink')` and observe that nothing happens. 

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

vimrc:

```vim
set nocompatible
" contains pack/home-manager/coc-nvim
" contains pack/home-manager/vscode-haskell (which creates the markdown hover)
set packpath^=/nix/store/g0ph92yy3g3y318vsk3cl90r8p5w39gi-vim-pack-dir
set runtimepath^=/nix/store/g0ph92yy3g3y318vsk3cl90r8p5w39gi-vim-pack-dir
filetype indent plugin on | syn on
nnoremap <silent> K :call CocAction('doHover')<CR>
```

## Screenshots (optional)

See in this image how `Documentation` and `Source` are no longer links, also see in the next picture that the links are there in the text:

![image](https://user-images.githubusercontent.com/857308/99147415-c02f5780-26bb-11eb-95a7-f84331888fbd.png)

![image](https://user-images.githubusercontent.com/857308/99147516-9b87af80-26bc-11eb-8ca8-30249dc9c93f.png)

**Comment by expipiplus1** [comment]
I notice that the links appear as concealed links in the `preview` mode:

![image](https://user-images.githubusercontent.com/857308/99147874-413c1e00-26bf-11eb-8e97-5431f636ffc8.png)

**Comment by expipiplus1** [comment]
Seems that the lines returned here have the missing links https://github.com/neoclide/coc.nvim/blob/53f8a1d52b4a459cbd848e1a1acba885d0d672e5/src/model/floatFactory.ts#L154

**Comment by chemzqm** [comment]
Hm, maybe add links at the end of float window is good?

**Comment by expipiplus1** [comment]
That might work, however I think it still quite surprising behaviour.

**Comment by chemzqm** [comment]
It's how markdown rendered, the missing part is it's not clickable.

**Comment by expipiplus1** [comment]
I think in general the markdown rendering is really good! Thank you!

I think that you're right that one needs to be able to follow the link (nvim's `gx` command is really quite good for this), and also to find links in the document which is more tricky if they're rendered the same as regular text.

**Comment by expipiplus1** [comment]
Thanks! If I'm reading the commit correctly, it should put, for example,

```
Documentation: file:///foo
Source: file:///bar
```
at the end of the document?

**Comment by chemzqm** [comment]
Yes.

**Comment by expipiplus1** [comment]
cool, thanks again
