### ISSUE TITLE
How can i prevent Enter to select an item in autocomplete

### ISSUE THREAD

**Issue by otavioschwanck** [neoclide/coc.nvim#2604]
I'm used to use only tab to complete and i disabled suggest.noselect, so when i type, i can just press tab to select and fill the first entry, and use C-j and C-k to select the entries (my config on doom is in this way).

I always use enter to new line (ignoring the opened autocomplete).  How can i do this with coc ?

**Comment by chemzqm** [comment]
Remap it, it's not mapped by coc.nvim.
