### ISSUE TITLE
When suggest.noselect is false, it binds <cr> to complete the complation

### ISSUE THREAD

**Issue by otavioschwanck** [neoclide/coc.nvim#2605]
I'm trying to use enter only to get a new line, but when i disable noselect, enter bindings it to complete, event when i not mapped <cr> to nothing.

Demontration of the behaviour:
https://www.dropbox.com/s/i6zgrar4fcot17t/coc%20bug-2020-11-14_14.26.28.mkv?dl=0

With the default coc complete:

``` 
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

When i am at the end of the line, like:
`payers.each do`

The autocomplete complete like `documents` instead going to a new line.  A nice alternative to  fixing my bug is:

enabling noselect again and only adding a verification with pumvisible() to see if some autocomplete is selected.  It needs to be default and on the readme!  but i dont know how to do it, i'm coming back to vim after 3 years on emacs.

**Comment by chemzqm** [comment]
It's not default, just example, you're free to bind whatever you like

**Comment by chemzqm** [comment]
Simply bind to `<c-e><cr>` when pumvisible

**Comment by otavioschwanck** [comment]
> Simply bind to `<c-e><cr>` when pumvisible

the coc#_select_confirm() is completing when is not selected !

**Comment by chemzqm** [comment]
Sure, don't use it to avoid that behavior.
