### ISSUE TITLE
Check if coc is loaded to conditionally set up mappings

### ISSUE THREAD

**Issue by VVKot** [neoclide/coc.nvim#2607]
**Is your feature request related to a problem? Please describe.**
I would like to only setup coc-related mappings if coc is loaded.

**Describe the solution you'd like**
Something similar to `buffer.lsp` in Neovim's LSP.

**Describe alternatives you've considered**
Some hacks like checking for `b:coc_diagnostic_info`.

**Comment by chemzqm** [comment]
Use 'g:did_coc_loaded'
