### ISSUE TITLE
How to call plugin function

### ISSUE THREAD

**Issue by tavoda** [neoclide/coc.nvim#2608]
Hello, I would like to call coc-explorer searchRecursive. When I open coc-explorer window I can do it with
:CocAction
and find searchRecursive or
:call coc#rpc#request('doKeymap', ['explorer-key-n-f'])

However it's working only in coc-explorer buffer/window. Coc-explorer doesn't export other actions than 'explorer'. Can I somehow call searchRecursive from anywhere. Best will be to have :nmap which allow to call it from any buffer.

THANKS

**Comment by weirongxu** [comment]
Please check out the wiki of `coc-explorer` https://github.com/weirongxu/coc-explorer/wiki/Vim-API

**Comment by tavoda** [comment]
If anybody is interesting:
`    :call CocAction('runCommand', 'explorer.doAction', 'closest', ['searchRecursive'])`

However it's called for folder where file in actual buffer is open. Can I run it for current working dir (shell $PWD)?

**Comment by tavoda** [comment]
CocAction('runCommand', 'explorer.doAction', 'closest', [{'name':'gotoSource', 'args':['file']}])
CocAction('runCommand', 'explorer.doAction', 'closest', ['searchRecursive'])

@weirongxu thanks :sunglasses: 
It's amazing plugin, great configurability and integration. I miss only one feature, exclude some folders (node_modules). I saw already feature request, hope you will find time to implement.
