### ISSUE TITLE
CocInstall installs any given npm package

### ISSUE THREAD

**Issue by cjnucette** [neoclide/coc.nvim#261]
I was having an issue with coc, and the problem was that I installed an extension but gave the wrong name:
```vim
:CocInstall highlight
```
instead of 
```vim
:CocInstall coc-highlight
```
Everything was working as expected, but everytime I started vim I got an error message which by the way was overwritten by the extensions' "service whatever started" message which made the debugging kind of annoying.

Great plugin by the way!

**Comment by chemzqm** [comment]
What does `installs any npm package` means?

**Comment by cjnucette** [comment]
Sorry, I mean any npm package you give to CocInstall. I just edited the comment.

**Comment by cjnucette** [comment]
Thanks, I did exactly that; forgot to comment.
