### ISSUE TITLE
Highlight group for popup borders

### ISSUE THREAD

**Issue by OkanEsen** [neoclide/coc.nvim#2610]
**Is your feature request related to a problem? Please describe.**
Maybe I haven't looked hard enough but I couldn't find a way to change the highlight groups for the popups used by coc.nvim.

**Describe the solution you'd like**
I'd like to be able to change the border color of various popups used by coc.nvim.

**Additional context**
![2020-11-16_10-18](https://user-images.githubusercontent.com/552226/99234902-72b70580-27f5-11eb-91e0-68406c230a11.png)

![2020-11-16_10-21](https://user-images.githubusercontent.com/552226/99234999-937f5b00-27f5-11eb-85ea-2707df275069.png)

**Comment by chemzqm** [comment]
`:h coc-config-dialog`

**Comment by OkanEsen** [comment]
Sorry to bother but I already found and tried those before but changing them didn't have any effect on the popup, which made me believe that the options weren't used for the popups.

I tried setting `dialog.floatBorderHighlight` to:
``` json
  "dialog.floatBorderHighlight": "CocFloatingBorder"
```

But the colors, which I set for testing purposes to:
``` vim
cocfloatingborder xxx guifg=#fb4934 guibg=#8ec07c
```

Don't get applied to the border.

By the way, changing `dialog.floatHighlight` don't seem to affect the name of the highlight group either:
``` json
  "dialog.floatHighlight": "GruvboxRed",
```

I forgot to say: I'm using the master branch of coc.nvim.

```
vim version: NVIM v0.5.0-839-g1b8867ab3
node version: v15.1.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/okan/.local/share/nvim/site/pack/packer/start/coc.nvim
term: alacritty
platform: linux
```

**Comment by OkanEsen** [comment]
Oh never mind actually...

Seems like `"dialog.floatBorderHighlight": "CocFloatingBorder"` only affects the code actions popup but the rename popup remain same:

![2020-11-16_11-00](https://user-images.githubusercontent.com/552226/99239169-f7585280-27fa-11eb-9b20-96997d8a3040.png)

![2020-11-16_11-00_1](https://user-images.githubusercontent.com/552226/99239183-fa534300-27fa-11eb-936c-4623d5e84ec1.png)

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
