### ISSUE TITLE
coc#config() currently inconsistent when should work

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#2611]
## versions

vim version: NVIM v0.4.4
node version: v15.2.0
coc.nvim version: 0.0.79-41d77ab2ca
coc.nvim directory: /home/francisco/.config/nvim/plugged/coc.nvim
term: tmux-256color
platform: linux

## Log of coc.nvim

2020-11-16T12:56:06.337 INFO (pid:17826) [services] - registered service "eslint"
2020-11-16T12:56:06.509 INFO (pid:17826) [services] - registered service "reason"
2020-11-16T12:56:06.543 INFO (pid:17826) [plugin] - coc.nvim 0.0.79-41d77ab2ca initialized with node: v15.2.0 after 297ms

vim version: NVIM v0.4.4
node version: v15.2.0
coc.nvim version: 0.0.79-41d77ab2ca
coc.nvim directory: /home/francisco/.config/nvim/plugged/coc.nvim
term: tmux-256color
platform: linux

## Log of coc.nvim

2020-11-16T12:56:06.337 INFO (pid:17826) [services] - registered service "eslint"
2020-11-16T12:56:06.509 INFO (pid:17826) [services] - registered service "reason"
2020-11-16T12:56:06.543 INFO (pid:17826) [plugin] - coc.nvim 0.0.79-41d77ab2ca initialized with node: v15.2.0 after 297ms

## Describe the bug

`coc#config()` configuration calls may not work when called directly from `init.vim` or `VimEnter`, this goes against the docs that says it can be called multiple times, even from `init.vim`. It seems that when a call doesn't work at that point, it does work from `User CocNvimInit`, like `suggest.completionItemKindLabels` for example, but then again, not everything works from `User CocNvimInit`, like `signature.preferShownAbove` (this one works from `init.vim` or `VimEnter`).

This creates a confusing experience for configuration from `init.vim` where the user needs to figure out without any docs where the `coc#config()` calls should go for them to apply.

A note should be added to docs in case the plan is to have working `coc#config()` guaranteed only after  `User CocNvimInit`.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set runtimepath^=~/.vim/plugged/coc.nvim

  colorscheme peachpuff
  
  autocmd User CocNvimInit call coc#config('signature', { 'preferShownAbove': v:false }) 
  
  call coc#config('suggest', {
  \   'completionItemKindLabels': {
  \     'function'              : "\uf794",
  \     'method'                : "\uf6a6",
  \     'variable'              : "\uf71b",
  \     'constant'              : "\uf8ff",
  \     'struct'                : "\ufb44",
  \     'class'                 : "\uf0e8",
  \     'interface'             : "\ufa52",
  \     'text'                  : "\ue612",
  \     'enum'                  : "\uf435",
  \     'enumMember'            : "\uf02b",
  \     'module'                : "\uf668",
  \     'color'                 : "\ue22b",
  \     'property'              : "\ufab6",
  \     'field'                 : "\uf93d",
  \     'unit'                  : "\uf475",
  \     'file'                  : "\uf471",
  \     'value'                 : "\uf8a3",
  \     'event'                 : "\ufacd",
  \     'folder'                : "\uf115",
  \     'keyword'               : "\uf893",
  \     'snippet'               : "\uf64d",
  \     'operator'              : "\uf915",
  \     'reference'             : "\uf87a",
  \     'typeParameter'         : "\uf278",
  \     'default'               : "\uf29c"
  \   }
  \ })
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim on a c++ file for example (I have `coc-clangd`) or any other file type with language server supporting signature help.

- Notice how neither of these settings has took effect.

- If the calls are swapped for `init.vim`/`User CocNvimInit` placement, then both take effect.

## Relevant previous issues reporting this

#2597, #2593, #2567, #2362

**Comment by oblitum** [comment]
Thanks @chemzqm. 0a01e01 fixed it for me on `init.vim`/`VimEnter`. It didn't fix it for `User CocNvimInit` though. The docs says that coc.nvim is fully initialized on this autocmd, so it seems okay to call `coc#config` also for it and it work, but I noticed that some `coc#config` calls still doesn't apply when called from `CocNvimInit`, e.g., for coc-git I do:

```vim
  call coc#config('git', {
  \   'enableGlobalStatus'       : v:false,
  \   'addedSign.text'           : '',
  \   'removedSign.text'         : '▁',
  \   'changedSign.text'         : '',
  \   'topRemovedSign.text'      : '▔',
  \   'changeRemovedSign.text'   : '',
  \   'addedSign.hlGroup'        : 'GitGutterAdd',
  \   'changedSign.hlGroup'      : 'GitGutterChange',
  \   'removedSign.hlGroup'      : 'GitGutterDelete',
  \   'topRemovedSign.hlGroup'   : 'GitGutterDelete',
  \   'changeRemovedSign.hlGroup': 'GitGutterChangeDelete'
  \ })
```

It works from `init.vim`/`VimEnter`, but doesn't if called from `CocNvimInit`.

**Comment by chemzqm** [comment]
Some configurations could be not watching for changes, you can use `:CocRestart` or avoid `CocNvimInit` autocmd for `coc#config`

**Comment by oblitum** [comment]
> or avoid `CocNvimInit` autocmd for `coc#config`

Okay, will do that, thx.
