### ISSUE TITLE
Useful documentation to avoid missing out on a great vim feature

### ISSUE THREAD

**Issue by EdmundsEcho** [neoclide/coc.nvim#2615]
coc.nvim is hands down the most reliable and pleasant software engineering tool.  Thank you to all!

When making a selection from the list of options in a pop-up window, while we never use tabs in our code :), I fell into the trap of thinking I could use `<TAB>` to toggle down the list... instead of what I considered less convenient vim `<C-n> <C-p>`.  After all, it's the shortcut often used here.

What's the harm of using `<TAB>`?

The hidden issue is that `<TAB>` is actually encoded using `<C-i>`. Who knew?...  So, why care? This matters because it prevents users from benefiting from a time-saving, solid capacity to navigate the jump list both back `<C-o>` and forward `<C-i>`.  

Only to the degree that demand for wanting to use the <TAB> key to move down a list in a pop-up is created by wanting to use coc.nvim, and because users can't be blamed for wanting to use this otherwise ubiquitous use of <TAB>, perhaps coc.nvim users might benefit from being made more aware of what they are "trading-away" in order to use <TAB> by adding the "buyer-beware" in the docs?  

\- E

**Comment by oblitum** [comment]
Not only that but also a tab mapping often getting in the way of generating actual tabs.

**Comment by vimpostor** [comment]
I personally only use the vim jumplist in insert mode, so the mapping is unaffected for me because the mapping is only overwritten in insert mode.

**Comment by chemzqm** [comment]
> This matters because it prevents users from benefiting from a time-saving, solid capacity to navigate the jump list both back <C-o> and forward <C-i>.

But those're normal mode mappings with vim.

**Comment by EdmundsEcho** [comment]
@chemzqm - Great catch.  I made a mistake describing where the issue arises. I corrected the post accordingly.  The conflict happens with the suggested setting: `nmap <silent> <TAB> <Plug>(coc-range-select)`.

**Comment by chemzqm** [comment]
@EdmundsEcho it was changed in Readme.
