### ISSUE TITLE
Feature Request: allow hooking Workspace.jumpTo()

### ISSUE THREAD

**Issue by richardtsai** [neoclide/coc.nvim#2617]
**Is your feature request related to a problem? Please describe.**
Say we `jumpDefinition` into a symbol. Our codebase contains lots of auto generated code (e.g. protobuf). But we might not aware that a symbol is defined in a generated file we before we `jumpDefinition` into it, and accidentally jumping into a 100KLOC generated file is generally meaningless and could makes vim hang for a long time. It seems to be more useful to jump to the corresponding *source file* of the generated code in this case, even if the precise position of the symbol cannot be located.

**Describe the solution you'd like**
Allow users to hook [`Workspace.jumpTo()`](https://github.com/neoclide/coc.nvim/blob/470e8319e3f5fc7b59c878494f0631537d3fdf2e/src/workspace.ts#L808) so that jumping into generated files can be intercepted and altered (with confirmation or uri rewritting).

Example:
```vim
function! TryJumpToProto(uri, pos)
    if a:uri =~ '.*/generated/.*\.pb\..*'
        return [substitute(a:uri, '\(.*\)/generated/\(.*\)\.pb\..*', '\1/\2.proto', ''), v:null]
    else
        return [a:uri, a:pos]
    endif
endfunction

let g:coc_hook_jump_to = function('TryJumpToProto')
```

**Describe alternatives you've considered**
Letting the langservers to decide where to jump to might be a cleaner way to do but source code generation is more related to the build scripts or build systems rather than the compilers.
Another alternative is to provide hooking capability for extensions, but the uri rewriting rules seems to be very project specific and I wonder if it would be valuable to implement an extension for this.

**Comment by chemzqm** [comment]
> 100KLOC generated file is generally meaningless and could makes vim hang for a long time

**Comment by chemzqm** [comment]
> 100KLOC generated file is generally meaningless and could makes vim hang for a long time

It's problem of your syntax plugin.

You can create your own jump command and use that.
