### ISSUE TITLE
Have to press Enter twice to get line break when popupmenu is open

### ISSUE THREAD

**Issue by hallettj** [neoclide/coc.nvim#262]
**Result from CocInfo**

```
## versions

vim version: NVIM v0.3.1
node version: v11.2.0
coc.nvim version: 0.0.37
term: konsole-256color
platform: linux

## Error messages
```

**Describe the bug**

When the popupmenu is visible if the user has not highlighted any suggested completion then pressing Enter should insert a line break. But when using coc.nvim with no custom keybinding for `<CR>` pressing Enter makes the popupmenu disappear, but does not insert a line break.

The documentation for `popupmenu-completions` explains about the three possible states for the popupmenu:

> There are three states:
> 1. A complete match has been inserted, e.g., after using CTRL-N or CTRL-P.
> 2. A cursor key has been used to select another match.  The match was not
   inserted then, only the entry in the popup menu is highlighted.
> 3. Only part of a match has been inserted and characters were typed or the
   backspace key was used.  The list of matches was then adjusted for what is
   in front of the cursor.

It also explains the behavior of Enter when the popupmenu is open:

> The behavior of the &lt;Enter&gt; key depends on the state you are in:
> first state:	  Use the text as it is and insert a line break.
> second state:	  Insert the currently selected match.
> third state:	  Use the text as it is and insert a line break.

The behavior that I observe seems to match what is described by state 2. The editor attempts to insert the selected match, but since there is no match selected it simply closes the popupmenu. In either of the other states pressing Enter would insert a line break.

My understanding is that the popupmenu should not enter state 2 unless the user takes action to select a match from the popupmenu. If I have typed some text but have not selected a completion then I expect the popupmenu to be in state 3. It seems that coc.nvim puts the popupmenu into state 2 without that explicit user interaction.

**To Reproduce**

1. Disable any insert mode binding for `<CR>` with `:iunmap <CR>`
2. Type something so that the popupmenu appears with completion suggestions
3. Press Enter

**Expected Results**

The popupmenu should disappear, a line break should be inserted, the cursor should be positioned on the new line, any text that was typed immediately before pressing Enter should be preserved.

**Actual Results**

The popupmenu disappears, and entered text is preserved, but no line break is inserted. It is necessary to press Enter twice to insert a line break in this situation.

**Comment by chemzqm** [comment]
Coc doesn't add `<CR>` mapping for you, check out where it's added by `verbose imap <CR>`

**Comment by chemzqm** [comment]
It's expected behaviour with complete option of `noinsert,noselect,menuone`, which required for increment filter.

**Comment by jared-w** [comment]
@hallettj, setting this inside your config file will give you the expected behavior of enter that you're asking for.

```vim
inoremap <silent><expr> <CR> pumvisible() ? "\<C-y><CR>" : "\<CR>"
```

It's not entirely obvious, but [this page in the wiki](https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#use-tab-or-custom-key-for-trigger-completion) gets you almost all of the way there. It's only missing the extra `CR` in the ternary statement.

**Comment by oblitum** [comment]
@jared-w won't that send enter after item selection though?

**Comment by oblitum** [comment]
@jared-w yep, that tip doesn't work. Also check README for [updated mapping](https://github.com/neoclide/coc.nvim/blame/cdb40c9dc9714a1a4d426457f255284d2ee92639/Readme.md#L201)

**Comment by hallettj** [comment]
@chemzqm  If the `noinsert,noselect` behavior is necessary then I can work around that. Thank you for the explanation!

@oblitum, @jared-w Thank you for the follow-up advice! With the mapping in the wiki does not change the issue of pressing enter twice. Of course that mapping is helpful for triggering actions on Enter.

@jared-w Adding `<CR>` after `<C-y>` seems to prevent snippet expansion from working using enter, and does not seem to trigger other actions such as automatically adding import lines either. But it does resolve the double Enter issue, and I could type `<C-y>` instead of Enter to confirm completions. So that is a viable workaround.

**Comment by oblitum** [comment]
> @jared-w Adding `<CR>` after `<C-y>` seems to prevent snippet expansion from working using enter, and does not seem to trigger other actions such as automatically adding import lines either. But it does resolve the double Enter issue, and I could type `<C-y>` instead of Enter to confirm completions. So that is a viable workaround.

@hallettj you can simply use `<c-y>` then, it's a default vim mapping for selection, no need to create additional one.

**Comment by oblitum** [comment]
I mean, if you simply remove the mapping with `pumvisible` and just use default vim behavior of `<c-y>`, it will still work. Check [`:h complete_CTRL-Y`](http://vimdoc.sourceforge.net/htmldoc/insert.html#complete_CTRL-Y).

**Comment by chemzqm** [comment]
You can reproduce it by: `vim -u NORC`, then:
```
:set completeopt=noinsert,noselect,menuone
```
Type characters `foo f`.
type `<C-n>` at the end and then type `o` and `<enter>`.
What you got is pupup menu become hidden without new line.

It should be third state, so the documentation:
```
third state:	  Use the text as it is and insert a line break.
```
is wrong.

**Comment by Frydac** [comment]
Hi,

I also have this issue, it has been closed, but I don't really understand what is the conclusion here, or a correct workaround?

The suggestion by jared-w ( https://github.com/neoclide/coc.nvim/issues/262#issuecomment-447140117 ) seems to work for me, when I don't have anything selected in the popup menu, it closes the menu and inserts a <cr>, which is the behaviour I would like. However oblitum seems to indicate there is something wrong with this mapping, but I don't understand what exactly?
I don't have any problems with ultisnips snippets completion or execution/expansion (I do use <C-j> to expand snippets, so there is no clash (if that was the problem maybe?)).

**Comment by chemzqm** [comment]
> but I don't understand what exactly?

That keymap should just works fine.

You can use `call coc#rpc#request('hasSelected', [])` to check if there's any complete item selected.

Also use `call coc#_select_confirm()` to make vim select first complete item if no item selected and do comfirm completion.

**Comment by boatrite** [comment]
I've finally figured out a CR mapping that works for my use cases and wanted to share with the community.

Features:
* Works with vim-endwise
* Does **not** insert the first option on enter when there are none highlighted, it inserts a newline instead. This makes it possible to, y'know, actually use the enter key at any given point regardless of what the lsp is barfing into the pum
* If an option is highlighted, CR will choose it and leave the user in insert mode to continue on typing.

One unfortunate thing which I believe is purely vim/completeopt related (yet relevant for this discussion, so I'm going to mention it here) is that sometimes only some of the text in the pum is auto-inserted requiring the use of CR to select the highlighted option and insert the rest. All in all, this is fine, it's probably why we all have CR configured to do coc#_select_confirm(). From my investigating, it seems to be that it stops auto-inserting when it hits a space. [This](https://stackoverflow.com/questions/59543882/vim-how-to-auto-complete-words-in-insert-mode-past-word-boundaries-e-g-puncta) is the only information I could find about this on the internet. It suggests a possible fix, but with some potentially far-reaching (and possibly undesirable consequences). I have no earthly idea if this is somehow solvable in a minimally invasive way via configuration or a plugin.

And fwiw, my completeopt is `menu,preview`.

```
function! My_mapping()
  if pumvisible() && complete_info()["selected"] == -1
    return "\<C-y>\<CR>"
  elseif pumvisible()
    return coc#_select_confirm()
  else
    return "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
  endif
endfunction
let g:endwise_no_mappings = v:true
inoremap <expr> <Plug>CustomCocCR My_mapping()
imap <CR> <Plug>CustomCocCR<Plug>DiscretionaryEnd
```

I know you can't exactly see when I'm pressing Enter in this gif, but hopefully this makes understanding the behavior a bit easier given the description above.
![coc_nvim_cr_mapping_example_2](https://user-images.githubusercontent.com/5781611/110249831-ca60b480-7f3d-11eb-8ce7-68dfd1bf4213.gif)

**Comment by MahdiNazemi** [comment]
This is what worked for me:

1. Disable the automatic selection of the first suggestion shown in the popup menu by adding the following lines to your `~/.vim/coc-settings.json` (`:CocConfig`)

    ```jsonc
    // Do not automatically select the first result
    "suggest.noselect": true,
   ```

2. Map `<CR>` to the following

    ```vim
    inoremap <silent><expr> <CR> coc#pum#visible() && coc#pum#info()['index'] == -1
      \ ? "\<C-e>\<CR>"
      \ : coc#pum#visible()
        \ ? coc#_select_confirm()
        \ : "\<CR>"
    ``` 

    The pseudo-code for the said mapping is

    ```
    if the popup menu is open but no item is selected
        close the popup menu, keep the inserted text, and go to the next line
    else if the popup menu is open (and an item is selected)
        insert the selected text and confirm the selection (e.g., insert parentheses if a function)
    else
        go to the next line (just as pressing <CR> would do)
    ```

If you like the tab key to have the same behavior as up and down arrow keys in that they do not insert the selected text while navigating different suggestions, change your mapping for tab to the following

```vim
inoremap <silent><expr> <TAB>
  \ coc#pum#visible() ? coc#pum#next(0) :
  \ CheckBackspace() ? "\<Tab>" :
  \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(0) : "\<C-h>"
```

The mapping is very similar to the example shown in the [README](https://github.com/neoclide/coc.nvim#example-vim-configuration), but passes 0 to `next()` and `prev()` functions instead of 1.
