### ISSUE TITLE
Support: Make <tab> trigger both 4space tab & autohint select

### ISSUE THREAD

**Issue by rajeshisnepali** [neoclide/coc.nvim#2632]
My coc configuration
```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible
```

My tab configuration
```
" Indent tab to 4 space
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
```
### Desc
What I want is to have both tab & autohint option for the same key. I'm getting an error on pressing `tab` in an empty place. 

#### Screenshots below. 
![coc_nvim0](https://user-images.githubusercontent.com/23610013/99867238-ed11cc00-2bdf-11eb-88ca-e3de506f406f.png)
![coc_nvim1](https://user-images.githubusercontent.com/23610013/99867237-ec793580-2bdf-11eb-8f06-a847135ca96b.png)
![coc_nvim2](https://user-images.githubusercontent.com/23610013/99867236-eaaf7200-2bdf-11eb-910a-8d77581481f0.png)

**Comment by chemzqm** [comment]
You missed to copy `check_back_space` function.
