### ISSUE TITLE
Closing CocSearch pane crashes vim

### ISSUE THREAD

**Issue by unknownbreaker** [neoclide/coc.nvim#2634]
## versions

vim version: NVIM v0.5.0-77dc891
node version: v14.12.0
coc.nvim version: 0.0.79-1cf07be052
coc.nvim directory: /Users/robertyang/Documents/Repos/Configs/Neovim/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2020-11-21T10:49:37.165 INFO (pid:82197) [services] - registered service "eslint"
2020-11-21T10:49:37.802 INFO (pid:82197) [plugin] - coc.nvim 0.0.79-1cf07be052 initialized with node: v14.12.0 after 801ms

node version: v14.12.0
coc.nvim version: 0.0.79-1cf07be052
coc.nvim directory: /Users/robertyang/Documents/Repos/Configs/Neovim/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2020-11-21T10:49:37.165 INFO (pid:82197) [services] - registered service "eslint"
2020-11-21T10:49:37.802 INFO (pid:82197) [plugin] - coc.nvim 0.0.79-1cf07be052 initialized with node: v14.12.0 after 801ms

## Describe the bug

After getting results back from a CocSearch, when closing that search results pane, all of vim crashes.

## Reproduce the bug

1. Use a codebase with many files already in place.
2. Run :CocSearch thing (or use any search term that will return lots of results).
3. Run :q in the CocSearch window pane.

Result should be that vim closes entirely.

**Comment by cambp4** [comment]
Hi, I'm just having the same issue, closing CocSearch with :q or <C-w>c causes a segfault. 
I was using a pretty old version of node.js but I just updated to v14.15.1 and it is similar. 
I am running Ubuntu 18.04.4 LTS, NVIM v0.5.0-824-ge786fb5af. the error occurred after I did a Plug update

**Comment by iamcco** [comment]
Don't know if it's neovim or coc.nvim's issue. This happened after upgrade to latest neovim version
