### ISSUE TITLE
Question: Why do extensions need to get bundled?

### ISSUE THREAD

**Issue by antonk52** [neoclide/coc.nvim#2636]
Hi, thanks for the great extension. 

Please clarify why do extensions need to get bundled. From my understanding the extensions are installed via npm itself and can contain their own dependencies.

For instance there are extensions like `coc-prettier` which do not use webpack and the source code only gets transpiled using typescript's `tsc`. Are there any benefits to use webpack? From what I could find the extensions are listed in a separate `package.json`and their common dependencies could be shared which makes it confusing to why some still use webpack for coc extensions

**Comment by chemzqm** [comment]
> and their common dependencies could be shared

No, they could only have errors. It's same as VSCode extension, it makes extension self contained.

**Comment by chemzqm** [comment]
Webpack is no required, but your code would takes more times to download and maybe issues with different dependencies.

**Comment by fannheyward** [comment]
Bundling Extensions https://code.visualstudio.com/api/working-with-extensions/bundling-extension
