### ISSUE TITLE
Global patch to promise prototype causes typescript errors in other packages

### ISSUE THREAD

**Issue by antonk52** [neoclide/coc.nvim#2637]
## Result from CocInfo

Coc functionality is not effected, CocInfo output is irrelevant for this issue.

## Describe the bug

`coc.nvim` patches promise prototype to add `logError` globally ([file](https://github.com/neoclide/coc.nvim/blob/master/src/util/extensions.ts)), this causes issues when developing coc plugins using typescript. In my example it is a thrid party code `postcss` which has a [line of code](https://github.com/postcss/postcss/blob/0d89106b73bf6ab6c0848c26cca29cbe874de7c8/lib/lazy-result.d.ts#L16) such as

```ts
class LazyResult implements Promise<Result> {}
``` 

## Reproduce the bug

I've created a [repository](https://github.com/antonk52/cocnvim-typescript-pollution-bug) to reproduce the issue.

When attempting to build using typescript you will see the following error

```
node_modules/postcss/lib/lazy-result.d.ts:16:22 - error TS2420: Class 'LazyResult' incorrectly implements interface 'Promise<Result>'.
  Property 'logError' is missing in type 'LazyResult' but required in type 'Promise<Result>'.

16 export default class LazyResult implements Promise<Result> {
                        ~~~~~~~~~~

  node_modules/coc.nvim/lib/util/extensions.d.ts:6:5
    6     logError(): void;
          ~~~~~~~~~~~~~~~~~
    'logError' is declared here.


Found 1 error.
```

A potential fix would be to avoid patching promise globally and to log errors where it is needed manually/adding a util promise wrapper for this purpose.

**Comment by chemzqm** [comment]
The prototype of Promise could be changed in standard js as well, make your tsc not check thet file.

**Comment by chemzqm** [comment]
It's not good design to add method to builtin object, but it worse to try to implement same interface for builtin object, it should use something like thenable of vscode.

**Comment by antonk52** [comment]
I would like to ask you to reconsider. Globally patching prototype is an anti pattern in the js ecosystem. This may be acceptable in smaller projects that do not share a limited runtime. Coc.nvim is not a small project and it both has it's own dependencies and there are a bunch of plugins that depend on coc.nvim itself.  You proposed solution of ignoring the file that throws the error is not optimal since it is no better than `@ts-ignore` or `any`. Vscode's `Thenable` is also not an option since unlike coc.nvim postcss can be run in a browser.

**Comment by Ceda-EI** [comment]
I agree with @antonk52 about polluting Promise prototype. It is generally accepted to be a bad practice and shouldn't be used. In this particular case, it doesn't even provide enough value to justify it's creation. It simply makes a line of code shorter by a few characters which imo is not worth opting for a bad practice.
