### ISSUE TITLE
Auto-completion only completes 'til the first space

### ISSUE THREAD

**Issue by Ran4** [neoclide/coc.nvim#2638]
## versions

    vim version: NVIM v0.4.3
    node version: v12.19.1
    coc.nvim version: 0.0.78-bdd9a9e140
    coc.nvim directory: /home/ran/.local/share/nvim/site/pack/coc/start/coc.nvim-release
    term: screen-256color
    platform: linux

    ## Output channel: prettier

    ## Output channel: Rust Analyzer Language Server Trace

## Describe the bug

Let's say I'm writing Rust and is currently in the process of typing `default`:

    impl Default for Something {
        fn d|
    }

(`|` signifies where my cursor is)

This popups a window looking like this:

       10 impl Default for Something {
    >> 11     fn d
       12 }      fn default()~ f [LS]
       13        doHover         [B]
       14        definition      [B]
       15        diagnostic      [B]
       16        documentation   [B]
    ~

I can use `<c-n>` to select `fn default()~ f [LS]`, but it doesn't auto complete the entire line - only up to the first space, like this:

       10 impl Default for Something {
    >> 11     fn fn|
       12 }      fn default()~ f [LS]  Returns the "default value" for a type.
       13        definition      [B]

So if I now exit insert mode, I'm left with `fn fn` which is obviously not what I would ever want.

Any idea what might causes this? What's the "proper" way to choose an autocomplete selection?

## Reproduce the bug

This is my current ftplugin for Rust:

    let g:SuperTabDefaultCompletionType = "context"
    let g:syntastic_mode_map = {
        \ "mode": "passive",
        \ "active_filetypes": [],
        \ "passive_filetypes": ['python', 'elixir'] }

    call SuperTabSetDefaultCompletionType("<c-x><c-o>")

    " Use tab for trigger completion with characters ahead and navigate.
    " NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
    " other plugin before putting this into your config.
    inoremap <silent><expr> <TAB>
          \ pumvisible() ? "\<C-n>" :
          \ <SID>check_back_space() ? "\<TAB>" :
          \ coc#refresh()
    inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

    function! s:check_back_space() abort
      let col = col('.') - 1
      return !col || getline('.')[col - 1]  =~# '\s'
    endfunction

    " Use <c-space> to trigger completion.
    inoremap <silent><expr> <c-space> coc#refresh()

    nmap <silent> gd <Plug>(coc-definition)
    nmap <silent> gy <Plug>(coc-type-definition)
    nmap <silent> gi <Plug>(coc-implementation)
    nmap <silent> gr <Plug>(coc-references)

    nmap <silent> ]l <Plug>(coc-diagnostic-next)
    nmap <silent> [l <Plug>(coc-diagnostic-prev)

    xmap ga  <Plug>(coc-codeaction-selected)
    nmap ga  :CocAction<CR>

    nmap gf  <Plug>(coc-fix-current)

    " Use K to show documentation in preview window.
    nnoremap <silent> K :call <SID>show_documentation()<CR>

    function! s:show_documentation()
      if (index(['vim','help'], &filetype) >= 0)
        execute 'h '.expand('<cword>')
      else
        call CocAction('doHover')
      endif
    endfunction

    " Highlight the symbol and its references when holding the cursor.
    autocmd CursorHold * silent call CocActionAsync('highlight')

    let g:coc_auto_copen = 0

**Comment by chemzqm** [comment]
It's expected, the complete item could provide textEdit to adjust position after completion confirm.

**Comment by chemzqm** [comment]
There is startcol support on vim, but lsp don't have that.
