### ISSUE TITLE
Exiting CocSearch with :q crashes nvim: segmentation fault

### ISSUE THREAD

**Issue by BrianZhang1** [neoclide/coc.nvim#2644]
## versions

vim version: NVIM v0.4.4
node version: v14.15.1
coc.nvim version: 0.0.79-1cf07be052
coc.nvim directory: /Users/Brian/.config/nvim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin

## Log of coc.nvim

2020-11-23T15:00:14.945 INFO (pid:3652) [plugin] - coc.nvim 0.0.79-1cf07be052 initialized with node: v14.15.1 after 244ms

vim version: NVIM v0.4.4
node version: v14.15.1
coc.nvim version: 0.0.79-1cf07be052
coc.nvim directory: /Users/Brian/.config/nvim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin

## Log of coc.nvim

2020-11-23T15:00:14.945 INFO (pid:3652) [plugin] - coc.nvim 0.0.79-1cf07be052 initialized with node: v14.15.1 after 244ms

## Describe the bug

Using :CocSearch (some name here) open a new window in vim, as intended. Using :q to exit out of the new window causes nvim to crash with a segmentation fault.

## Reproduce the bug

1. Open a python file using nvim
2. Use :CocSearch to find a function/variable name, make sure that the variable is present in another file as well so that results show up.
3. Execute :q.

## Screenshots (optional)

A library of 2 images I screenshotted. In the first one you can see CocSearch working as normal. In the second you can see what happens after I execute :q. Not only does it crash nvim, but it also leaves a huge portion of the nvim editor still on my screen, even though I cant access it at all. The terminal works as normal from there.
https://imgur.com/a/BvHZD19

**Comment by cambp4** [comment]
Hi, I had this bug yesterday as well, an issue was raised and addressed and a fix was released. this morning I did a plug-update and the bug was gone. 
I noticed 2 things though : 
- the highlighting is flickery as is the search results will kind of blink of awhile
- in the new buffer opened in the split when we press "n" it does not go through the results highlighted but I don't remember if we ever had this feature before.

**Comment by chemzqm** [comment]
It was fixed on latest release branch of coc.nvim.

**Comment by chemzqm** [comment]
> the highlighting is flickery as is the search results will kind of blink of awhile

Could be improved.

> in the new buffer opened in the split when we press "n" it does not go through the results highlighted but I don't remember if we ever had this feature before.

Check `:h coc-config-cursors`
