### ISSUE TITLE
`getmatches` don't accept parameters

### ISSUE THREAD

**Issue by maturanomx** [neoclide/coc.nvim#2648]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-233-g76d1e9360
node version: v12.19.0
coc.nvim version: 0.0.79-0b82465e6a
coc.nvim directory: /home/maturano/.dotfiles/_vendor/vim/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-11-23T21:44:09.091 INFO (pid:24476) [plugin] - coc.nvim 0.0.79-0b82465e6a initialized with node: v12.19.0 after 23ms

vim version: NVIM v0.5.0-233-g76d1e9360
node version: v12.19.0
coc.nvim version: 0.0.79-0b82465e6a
coc.nvim directory: /home/maturano/.dotfiles/_vendor/vim/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-11-23T21:44:09.091 INFO (pid:24476) [plugin] - coc.nvim 0.0.79-0b82465e6a initialized with node: v12.19.0 after 23ms
```

## Describe the bug

`getmatches` function doesn't accept parameters. See https://github.com/neovim/neovim/commit/d7d69fed18c2cd59d28ff12ef72f6fb2a98a7b66

```
Error detected while processing function coc#highlight#clear_match_group:
line    7:
E118: Too many arguments for function: getmatches
E116: Invalid arguments for function filter
E15: Invalid expression: filter(getmatches(winid), 'v:val["group"] =~# "'.a:match.'"')
Press ENTER or type command to continue
```

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with the command: `vim -u mini.vim`

- Open another file in a split window: `:sp ~/mini.vim`

## Screenshots (optional)

![screenshot_2020-11-23_214252_937x425](https://user-images.githubusercontent.com/5768813/100045415-9837a680-2dd5-11eb-80ad-ce5f405b4e43.png)

**Comment by chemzqm** [comment]
> vim version: NVIM v0.5.0-233-g76d1e9360

Upgrade to lastet neovim if you're using nvim from master.

**Comment by maturanomx** [comment]
I'm using the version from Ubuntu repositories and was working a couple of weeks ago.

I took a look at the code and I realized it's covered [by a variable](https://github.com/neoclide/coc.nvim/blob/release/autoload/coc/highlight.vim#L2) so my workaround is hardcoded the value to `0` and It's working fine for now; simpler than compile nvim; probably also works another person.

Thanks for your help :+1:
