### ISSUE TITLE
E739: Cannot Create Directory: H\AppData

### ISSUE THREAD

**Issue by DMalladi** [neoclide/coc.nvim#2649]
**Error While installing the COC-NVIM plugin in VIM 8.2 Version,**
**VIM Details attached below,**
![image](https://user-images.githubusercontent.com/41450470/100129657-6f4ff980-2e47-11eb-8025-8d9e0166082c.png)

**Error Details attached below,**
![image](https://user-images.githubusercontent.com/41450470/100129702-7e36ac00-2e47-11eb-9556-c59af2ea9eee.png)

**What I am doing?**
I am trying to install COC-NVIM, via VIM-Plug in my VIM 8.2 editor, and I faced this issue. Could anyone please help me out with this issue. 

**Machine Details**
Windows 10
Drive Details
![image](https://user-images.githubusercontent.com/41450470/100129989-d372bd80-2e47-11eb-868d-005e53542f92.png)

_I do see that I don't have a drive H: on my machine, and I don't the reason why coc-nvim is creating the H:\APPData\Local\..
in that directory, is it possible to config this? if so, could you please guide me with the instructions._

**Comment by chemzqm** [comment]
`:h g:coc_data_home`

**Comment by DMalladi** [comment]
Thank You So much, it worked!!!
