### ISSUE TITLE
Disable firstmatch for language server completions

### ISSUE THREAD

**Issue by ApolloBian** [neoclide/coc.nvim#2650]
I'm implementing a Chinese IME using language server completion functions. I am able to get suggestions show up like so:
![image](https://user-images.githubusercontent.com/13659369/100131131-9ac1fb00-2ebe-11eb-8ae8-c94eeb516804.png)

However, after selecting the first suggestions, further suggestions no longer show up, yet in language server debugging logs I can see it calls completion functions and successfully generates proper suggestions:
![image](https://user-images.githubusercontent.com/13659369/100130315-85989c80-2ebd-11eb-9bfa-7fc05784b6f1.png)
However, the suggestions doesn't show up:
![image](https://user-images.githubusercontent.com/13659369/100130323-88938d00-2ebd-11eb-8b0a-e317624a6c6c.png)

I think it is related to the plugin tries to match '在一个yueheifenggao' with my suggestions, using firstMatch. How can I disable the firstmatch (or any matching at all) for this specific language server that I wrote?

Also, the document is not clear how to configure language server to trigger completion whenever I type. I find similar options in [Create custom source](https://github.com/neoclide/coc.nvim/wiki/Create-custom-source) wiki page (`triggerCharacter` and `firstMatch`), but there seems to be no similar configs for custom language servers.

**Comment by chemzqm** [comment]
There is no firstmatch for complete item from language server, you should use `filterText`
