### ISSUE TITLE
Customizing Diagnostics?

### ISSUE THREAD

**Issue by PouriDev** [neoclide/coc.nvim#2654]
Is there a way that I can customize Diagnostics? I want to show the diagnostics in front of the line like the way lspconfig does that, I  also to want to delete that >> sign. How can I do that?

And I think it would be better to show warning when a `variable declared, but its value never used`, Any Idea ?

**Comment by chemzqm** [comment]
Read doc.

**Comment by PouriDev** [comment]
Wait, how is it not supported ??
![a](https://user-images.githubusercontent.com/61497342/100197081-0fbd2100-2f0f-11eb-80ee-5cba1b0fc33d.png)
Isn't it coc-diagnostics??
Also how can I use that tag, can you explain more?

**Comment by chemzqm** [comment]
No support of in front of the line, you can't use that tag, also your server could be not providing them.

**Comment by chemzqm** [comment]
The diagnostic level is controlled by language server, not coc.nvim.

**Comment by PouriDev** [comment]
So what about that image

**Comment by PouriDev** [comment]
> The diagnostic level is controlled by language server, not coc.nvim.

So how LspConfig does that ?

**Comment by fannheyward** [comment]
> in front of the line like the way lspconfig does 

Please post a image for this way
