### ISSUE TITLE
Fuzzy Finding 

### ISSUE THREAD

**Issue by PouriDev** [neoclide/coc.nvim#2655]
Is there a way that I can change the finding strategy for suggests? 
![1](https://user-images.githubusercontent.com/61497342/100208831-65e59080-2f1e-11eb-90e4-28bfbe06ef0a.png)

![2](https://user-images.githubusercontent.com/61497342/100208843-67af5400-2f1e-11eb-8356-6ab93aa79462.png)
As you can see here, both are wrong. It should be the first but it's the last one, How can I make finding strategy like
`[ exact, substring, fuzzy ] `

**Comment by chemzqm** [comment]
Hack the code.

**Comment by chemzqm** [comment]
It's expected since language server have higher priority and it matches first character of words which would be given higher score.

**Comment by PouriDev** [comment]
How can I change that??
