### ISSUE TITLE
Can or how to trigger signature help?

### ISSUE THREAD

**Issue by kundzio** [neoclide/coc.nvim#2656]
**Is your feature request related to a problem? Please describe.**
I'm trying to set up signature help to be triggered just as it is possible with  completion (ig by  `<Tab>` or `<c-space>`).

**Describe the solution you'd like**
Documentation for signature has:
```
"signature.enable":~

	Enable signature help when trigger character typed, require restart
	service on change.,  default: `true`
```

And for completion:

```
"suggest.autoTrigger":~

	How should completion be triggered,  default: `"always"`

	Valid options: ["always","trigger","none"]
```

That "trigger" option and function/setting similiar to `inoremap <silent><expr> <c-space> coc#refresh()` for signature help is what I'm looking for.

**Additional context**
I'm aware of signature.triggerSignatureWait.

**Comment by chemzqm** [comment]
`coc#refresh` is for completion, there is an action for trigger signature help.

**Comment by yueyingjuesha** [comment]
@chemzqm, I tried to trigger the signature help using :call CocAction('showSignatureHelp'), or try to assign this command a map, no signature text display, however when I use autocmd User CocJumpPlaceholder call  CocActionAsync('showSignatureHelp'), and in select mode when entering function parameter, it will trigger the signature help, quite don't understand here

**Comment by chemzqm** [comment]
Your language server could be slow to response.

**Comment by yueyingjuesha** [comment]
I think it isn't the timeout fault, when I use  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp') , the signature is returned instantly, I already bumped the signature.triggerSignatureWait to maximum 1000, but still  not working when directly invoking command  :call CocActionAsync('showSignatureHelp')

**Comment by yueyingjuesha** [comment]
Basically, I want a keymap that can trigger function signature help, other than automatically triggered when entering function parameter(CocJumpPlaceholder)), do  you is there a workable solution to this? @chemzqm

**Comment by chemzqm** [comment]
`CocActionAsync('showSignatureHelp')` should work, you can debug it https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by yaegassy** [comment]
@yueyingjuesha Do you want to map "signature help" in insert mode?

**e.g:**

```vim
inoremap <silent> ,s <C-r>=CocActionAsync('showSignatureHelp')<CR>
```

**Comment by yueyingjuesha** [comment]
That's pretty nice, it works!

**Comment by jzes** [comment]
Awesome
