### ISSUE TITLE
add exclude rules for suggest.numberSelect

### ISSUE THREAD

**Issue by rusdevops** [neoclide/coc.nvim#2657]
Good day,

Сould you consider adding exceptions for specific words
I want to add an exception for words uint64, type int32,..

for example
```
suggest.numberSelectExcludes = ["uint64", "uint32", "uint8"]
```

that is, when I enter the number `6` in the word `uint64`, so that I would not select the 6 element from the list

**Comment by chemzqm** [comment]
No, I don't like it.

**Comment by chemzqm** [comment]
Try
```
iabbrev u6 uint64
iabbrev u8 uint8
iabbrev u3 uint32
```
in your vimrc.
