### ISSUE TITLE
Option to not see coc dropdown while typing

### ISSUE THREAD

**Issue by ayroblu** [neoclide/coc.nvim#2659]
Hi, I find the preview while typing to be distracting, I would rather it only showed up when I trigger `coc#refresh()` I'm not sure if there is an option and if so which option it is.

**Comment by chemzqm** [comment]
Read doc

**Comment by ayroblu** [comment]
Found it, for anyone else who's looking for this: `  "suggest.autoTrigger": "none"`
reference: https://vi.stackexchange.com/questions/23323/configuring-coc-open-suggestion-box-with-shortcut-only
