### ISSUE TITLE
Diagnostics not updating

### ISSUE THREAD

**Issue by benwainwright** [neoclide/coc.nvim#2662]
## Result from CocInfo

https://gist.github.com/benwainwright/bc9a60c4149bfe1eaf32cade98c7e865

## Describe the bug

When using NVim with coc.nvim, quite often diagnostics are wrong (out of date) until I reload the buffer using `:e`. This happens during almost all editing sessions on a regular basis.

## Reproduce the bug

I have tried to repro this bug using a minimal vimrc, but failed. This may be because it is not clear what *triggers* the bug and trying to repro is quite hard because It doesn't happen straight away, and editing with a minimal vimrc for long periods of time is incredibly awkward for me because like most Vim users, I have a fairly bespoke vimrc.

This bug *does* appear though (its been an issue for me ever since I started using coc.nvim) and my colleague @tomdaly has reported the exact same problem.

Yes, I have my `updatetime` set to 300. I appreciate this isn't a lot to go on, but if anyone has any suggestions on how to diagnose the bug, I'm all ears.

**Comment by chemzqm** [comment]
It known issue with coc-eslint https://github.com/neoclide/coc-eslint/issues/72.
I did have that issue sometimes, it's because it's using `fast-diff` modules which could be broken, will try to fix that.
