### ISSUE TITLE
Disable hover highlight

### ISSUE THREAD

**Issue by amiralies** [neoclide/coc.nvim#2664]
is this possible to disable word/location highlighting when using getting hover info?
![image](https://user-images.githubusercontent.com/13261088/100520053-15399600-31b1-11eb-8793-c8747668506c.png)

**Comment by chemzqm** [comment]
No, it's useful

**Comment by amiralies** [comment]
what about having an option in preferences for this?

**Comment by chemzqm** [comment]
You can change the highlight, so you can't see difference.
