### ISSUE TITLE
Diagnostic jump should be compatible with jump list.

### ISSUE THREAD

**Issue by JW9506** [neoclide/coc.nvim#2666]
<Plug>(coc-diagnostic-next)				*n_coc-diagnostic-next*

	Jump to next diagnostic position.

<Plug>(coc-diagnostic-prev)				*n_coc-diagnostic-prev*

	Jump to previous diagnostic position.

<Plug>(coc-diagnostic-next-error)			*n_coc-diagnostic-next-error*

	Jump to next diagnostic error position.

<Plug>(coc-diagnostic-prev-error)			*n_coc-diagnostic-prev-error*

	Jump to previous diagnostic error position.

These should commands should be compatible (or would be great) with `ctrl-o, ctrl-i` jump list navigation.

**Comment by chemzqm** [comment]
No, but you can write function to achieve that
