### ISSUE TITLE
after installing coc.nvim neovim become very slow and laggy

### ISSUE THREAD

**Issue by EhsanSarshar** [neoclide/coc.nvim#2668]
node: v12.13.0
8 GB Ram
MacBook Air 2015

**Comment by chemzqm** [comment]
Use other vim plugin instead.

**Comment by EhsanSarshar** [comment]
@chemzqm thanks for no Answer and closing

**Comment by chemzqm** [comment]
We're not Microsoft who can track your editor events, so we simply simple close issue that impossible to reproduce to avoid unnecessary noise.

**Comment by EhsanSarshar** [comment]
@chemzqm sorry as it seams I haven't followed issue template correctly.
can I reopen the issue wit better issue template.

**Comment by oblitum** [comment]
@EhsanSarshar before that, try upgrading your nodejs, people that report slowness are generally using an old node and people that upgrade claim it's super fast.

**Comment by sheldonldev** [comment]
@EhsanSarshar I meet the same problem actually, I'm using macOS Pro, 16GB RAM, Nodejs 15.4, and very slim vimrc. It seems slower than VSCode. If I switch nvim to vim, it will be better, but the popup flashes when input.

**Comment by chemzqm** [comment]
Try minimal vimrc or track debug log `:h CocOpenLog`

**Comment by sheldonldev** [comment]
@chemzqm @EhsanSarshar  I uninstall some extensions like coc-eslint and coc-prettier, it's much better now. I found some extensions may overlap some functions, which may slow down the editor.

**Comment by chemzqm** [comment]
Please read F.A.Q and check `:h :profile` to check which function is too slow.
