### ISSUE TITLE
codeLens - the reference count is nicely displayed using neovim's virtual text features, however...

### ISSUE THREAD

**Issue by EdmundsEcho** [neoclide/coc.nvim#2669]
... is there a way to jump to the references?  

I tried to learn a little more about the `codeLens` at VS Code. It looks like it outputs a link to which we can jump.  

Is that something that is up and running, or a WIP?

\- E

**Comment by chemzqm** [comment]
`:h coc-action-codeLensAction`

**Comment by EdmundsEcho** [comment]
Thank you.

**Comment by masaeedu** [comment]
@chemzqm Not sure if I'm doing something wrong, but here's the behavior I'm seeing: https://asciinema.org/a/vFDdesNER4MLaUHdcpWacNbkf

**Comment by chemzqm** [comment]
Could be wrong cursor position.
