### ISSUE TITLE
Nvim abort on floating menu suggestion

### ISSUE THREAD

**Issue by dylandjian** [neoclide/coc.nvim#2670]
## Result from CocInfo

undefined## versions

vim version: NVIM v0.5.0-nightly
node version: v14.15.1
coc.nvim version: 0.0.79-481294d1d2
coc.nvim directory: /Users/dylandjian/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2020-11-30T17:09:55.548 INFO (pid:8592) [plugin] - coc.nvim 0.0.79-481294d1d2 initialized with node: v14.15.1 after 920ms

## Describe the bug

When going down the suggestion autocomplete menu in the floating window, nvim aborts when the suggestion comes from the language server. Reproduced outside and inside of Tmux, and on another terminal than iTerm. Reproduced with `coc-tsserver`. Does not seem to crash when going down the suggestion menu coming from the file itself.

## Reproduce the bug

Init.vim config
```vim
" Plugin
call plug#begin()
"
" Language Server
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()
```

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
You can debug your neovim to figure it out, not happens for me.

**Comment by thrgamon** [comment]
I am getting a similar issue, will try and see if I can figure out any reproduction steps today

**Comment by ayellapragada** [comment]
Also getting a similar issue, can reproduce it consistently by opening any ruby file with coc-solargraph active.

What logs or steps would be useful in debugging this? I'm not familiar with the nvim logs situation.

**Comment by chemzqm** [comment]
We need connection log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc, save your vimrc and exit vim.
* Restart your vim/neovim to make the issue happen.
* Get the log filepath by :echo $NODE_CLIENT_LOG_FILE
* Attach the log file or paste content from the log.

Also checkout https://github.com/neovim/neovim/wiki/FAQ#debug

**Comment by ayellapragada** [comment]
Thank you! Will do that now.

As a possible workaround for any other folks with this issue, you can add the following to your `coc-settings.json` to disable the floating window that's causing an issue.
```"suggest.floatEnable": false```

Looking into the FAQ, I see that I can also get you the backtrace on MAC, and while I can get you a log file, it seems too massive to really help narrow down. I'll simplify my nvim setup to see if this helps make this more usable.

**Comment by ayellapragada** [comment]
Information:
vim version: NVIM v0.5.0-nightly
node version: v14.12.0
coc.nvim version: 0.0.79-4f517cc785
coc.nvim directory: /Users/ayellapragada/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

my mini.vim
```init.vim
call plug#begin()
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

let g:node_client_debug = 1

set nocompatible
filetype plugin indent on
syntax on
set hidden
```

Example file used, this is with coc-solargraph

```ruby
module Foo
  class Bar
    class << self
      def call(obj)
        # when typing actu, and the autocomplete pops up, CTRL-N to `actual_method` causes an abort()
        setup_change(obj)
      end
       
      def actual_method(obj)
        does_something_with(obj)
      end

      def setup_change(obj); end

      def does_something_with(obj); end
    end
  end
end
```

I didn't want to tamper with the files much so these are unedited. I did get it to a minimal config and as much as possible these are the logs right before / after the abort() call happened.

The before log is getting to the point right before where I would type `actu` above, then the after is once the abort() crash happened. Everything after line 4309 I guess is part of the abort(), but looking at this I can't really tell when it ends. Sorry :(
[before_break.log](https://github.com/neoclide/coc.nvim/files/5626950/before_break.log)
[after_break.log](https://github.com/neoclide/coc.nvim/files/5626949/after_break.log)

And this is the macback trace. I have more if needed, but they all seem to be the same.
[macbacktrace.log](https://github.com/neoclide/coc.nvim/files/5626980/macbacktrace.log)


Let me know if any of these are not helpful and if you need more logs or etc.

**Comment by dylandjian** [comment]
Hello, any update ?

If that can help, I added the crash dump / coc.nvim logs.
[nvim_2020-12-12-202054_dylan-djian.log](https://github.com/neoclide/coc.nvim/files/5683658/nvim_2020-12-12-202054_dylan-djian.log)
[nvim.log](https://github.com/neoclide/coc.nvim/files/5683660/nvim.log)

**Comment by chemzqm** [comment]
Seems bug of neovim, I can't reproduce.

**Comment by chemzqm** [comment]
@dylandjian could be invalid characters in documentation, how could I trigger it?

**Comment by dylandjian** [comment]
I feel like it happens not matter what is inside the documentation, more like a bug regarding floating windows !

**Comment by 3nuc** [comment]
Updated to newest coc (:PlugUpdate) and neovim (0.5.0+ubuntu2+git202011201114-480b04122-d569569c9-523645f61~ubuntu18.04.1) and this no longer happens to me

**Comment by ayellapragada** [comment]
```
vim version: NVIM v0.5.0-nightly
node version: v14.12.0
coc.nvim version: 0.0.80-7642d233d6
```

Still seems to happen to me, I've been using the following temporarily as a way to disable the floating window that causes the issue.
I'm sure there's a better way, but this has been working for now, not ideal but ah well!
``` jsonc
// coc-settings.json
{
  // ... other settings
  "suggest.floatEnable": false,
  "suggest.detailField": "abbr",
  "coc.preferences.hoverTarget": "echo",
  "diagnostic.messageTarget": "echo",
  "signature.target": "echo",
  "diagnostic.virtualText": true,
  "coc.preferences.floatActions": false
}
```

**Comment by dylandjian** [comment]
Same, still have the issue even after upgrading my coc plugin ! Any update ? 😢

**Comment by zhaogaolong** [comment]
I have same problem 😓

**Comment by chemzqm** [comment]
Use stable neovim or upgrade to latest neovim.

**Comment by dylandjian** [comment]
After downgrading to neovim v0.4.4 the issue does not happen anymore. I'm guessing it is related to the nightly build!

**Comment by thrgamon** [comment]
Downgrading to v0.4.4 also resolved the issue for me

**Comment by samrocksc** [comment]
Downgraded to 0.4.4 worked for me as well

**Comment by josex2r** [comment]
The autosuggestion started to failing in NeoVim after updating from OSX Catalina to Big Sur. The JS error was the same as your logs (`NvimTransport.request`).

After checking the `Console` app in OSX and reading the crash dump of NeoVim, I've found that `libintl.8.dylib` was causing the error. Googling this lib some people said that rebuilding NeoVim (do not forget to upgrade the version of Luajit before building).

```
# From
$ nvim --version
NVIM v0.5.0-d8e6a0396
Build type: Release
LuaJIT 2.0.5

# To
$ nvim --version
NVIM v0.5.0-dev+nightly
Build type: Release
LuaJIT 2.1.0-beta3
```

Now it works and shows the floating window with the code docs.
