### ISSUE TITLE
Multiple selection disappear when fuzzy search

### ISSUE THREAD

**Issue by elebeaup** [neoclide/coc.nvim#2675]
## Result from CocInfo

vim version: NVIM v0.5.0-356-gead61e5a5
node version: v12.16.1
coc.nvim version: 0.0.79-b9b69a267b
coc.nvim directory: /home/elebeaup/.local/share/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Describe the bug

When you do a multiple selection in coc-list and then when you return to fuzzy search, the selection is lost when typing.

## Reproduce the bug

1. `:CocList extensions` and then change to normal mode (`C-o`)
2. Select items (using `<space>`)
3. Change to insert mode (`i`)
4. Typing something

## Screenshots

![image](https://user-images.githubusercontent.com/9947807/100720537-72566700-33be-11eb-867e-3330c9e9adf5.png)

![image](https://user-images.githubusercontent.com/9947807/100720613-9154f900-33be-11eb-90d1-50f8467a4857.png)

![image](https://user-images.githubusercontent.com/9947807/100720670-a0d44200-33be-11eb-878a-2099d81f89db.png)

**Comment by chemzqm** [comment]
Yes, you have to do filter before selection.

**Comment by elebeaup** [comment]
When the list is too long, it would be interesting to persist the selection between 2 filters (first filter -> multiple selection -> second filter -> additional multiple selection).
