### ISSUE TITLE
Disabling Python 2 Provider Does Not Hide Warnings and Errors 

### ISSUE THREAD

**Issue by Carltoffel** [neoclide/coc.nvim#2676]
## Result from CocInfo
Hint: I know there is already a newer version but after an update the bug is still there

## versions

vim version: NVIM v0.4.4
node version: v10.16.3
coc.nvim version: 0.0.78-bdd9a9e140
coc.nvim directory: /home/carl/.local/share/nvim/plugged/coc.nvim
term: xterm-termite
platform: linux

## Output channel: snippets

[Info 8:56:32 AM] Using ultisnips directories: UltiSnips /home/carl/.config/coc/ultisnips
[Info 8:56:32 AM] Using ultisnips python command: pyx

## Describe the bug

Manually disabling python2 support (because who still uses python2 in 2020?) with `g:loaded_python_provider=0` does not hides the warnings and errors about python2.

## Reproduce the bug
- have no python2 installed (or no python2 in path, shouldn't matter)
- I tested it with an empty `mini.vim`, coc is installed with `vim-plug`
- in vim run `:checkhealth provider`
- it tells you it found no python2...
- disable python2 with `:let g:loaded_python_provider=0` (as described in `:help provider`)
- again run `:checkhealth provider`
- now it gives you the info, that python2 was disabled (as intended)
- *but* it gives you the same warning and error as before (not intended)
- disabling ruby the same way works as intended (`:let g:loaded_ruby_provider=0`)
- btw it does not matter if you set these options in a config file or in a running vim session

## Output of `:checkhealth provider` with manually disabled python2 (bug) and ruby (working)
```
health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: Disabled (g:loaded_python_provider=0).  This might be due to some previous error.
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /python3
  - INFO: Python version: 3.9.0
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Disabled. g:loaded_ruby_provider=0

## Node.js provider (optional)
  - INFO: Node.js: v15.3.0
  - INFO: Neovim node.js host: /home/carl/.config/yarn/global//node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0
```

**Comment by fannheyward** [comment]
The error and warning message is from nvim, not coc, can you reproduce this without coc ?

**Comment by Carltoffel** [comment]
Oh, sry my bad. Guess I move the bug report to neovim
