### ISSUE TITLE
[Break change] coc.nvim module 0.0.80 on npm would provide only types.

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#2678]
Which is the same as VSCode, some extensions may not work at all.

Old extensions will still work but could failed to compile with latest coc.nvim.

A new extension `coc-extension-codemod` will be created for migrate your typescript coc.nvim extensions.

**Comment by chemzqm** [comment]
Available on next tag of npm for now, please try that one if you're tring to create new extension.

**Comment by fannheyward** [comment]
Correct me if I misunderstand it, this means extensions will not need to import `vscode-languageserver-protocol`  any more? Directly use types from coc.nvim all?

**Comment by chemzqm** [comment]
You may still want use types from `vscode-languageserver-protocol` when the types from coc.nvim not fit your needs, especially for new featrures.

**Comment by fannheyward** [comment]
I've refactored coc-pyright with coc.nvim@next, everything works great! The webpack bundled release reduced size from 900K to 700K.

**Comment by GopherJ** [comment]
hi @fannheyward I just started to have the following issue after upgrading to `coc.nvim@0.0.80`, is this issue relevant?
![Peek 2020-12-31 01-50](https://user-images.githubusercontent.com/33961674/103388664-a54d6100-4b0a-11eb-876d-5692f7f68568.gif)

**Comment by GopherJ** [comment]
I have the same issue with `coc-css`, no idea what's happening, btw I use `nvm` and I disabled `type acquisition`

**Comment by fannheyward** [comment]
@GopherJ I don't have this issue with coc-rust-analyzer.

**Comment by chemzqm** [comment]
@GopherJ you should check if that file exists first.

**Comment by GopherJ** [comment]
@chemzqm it does exist, I had this issue recently this week

**Comment by chemzqm** [comment]
@GopherJ provide full information including reproduce steps and your versions if you want to report issue.
