### ISSUE TITLE
PHP函数方法参数列表在tag号大于0.0.0.77的时候显示有问题

### ISSUE THREAD

**Issue by dong8yong8** [neoclide/coc.nvim#2680]
## Describe the bug

如题，在编辑PHP的时候输入某个函数或者方法，如trim()
只有在输入括号的时候会显示一遍完整的参数列表，
当输入完第一个参数输入逗号空格时就没有后续的参数列表了

vim 8.2
出现此问题的coc版本号：大于0.0.0.77
php language server: phpls 1.5.1

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
