### ISSUE TITLE
Auto import  does not meet expectations in C/C++ file

### ISSUE THREAD

**Issue by mano233** [neoclide/coc.nvim#2690]
when i typing `size_t` in a `.c` file, coc.nvim auto import `#include <cstddef>`.
It should be import `#include <stddef.h>`
<img width="555" alt="image" src="https://user-images.githubusercontent.com/29190675/101493251-ca820000-39a0-11eb-92ad-f6c4db887327.png">

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
