### ISSUE TITLE
Autocompletion through Coc vs VS Code

### ISSUE THREAD

**Issue by iukej** [neoclide/coc.nvim#2696]
Hi all,

1) When putting Coc side by side with VS Code, the same (local, not standard Python package) has a different set of autocomplete suggestions. Coc has a handful of the correct module.

LHS is Coc, RHS is VS Code. As you can see, the Python paths are identical, they both point to 

`"/Users/username/anaconda3"`

<img width="1914" alt="coc_nvim_against_vscode_codecomplete_redac" src="https://user-images.githubusercontent.com/40323012/101701760-2f8f3180-3a45-11eb-8816-5cb213f92640.png">

2) It's extremely slow to autocomplete.

 When I set python.pythonPath as "/Users/username/anaconda3/bin/python" (at python itself), it's extremely fast but only includes packages that come with MPLS. To get everything else, I've appended

`"/Users/username/anaconda3/lib/python3.7/site-packages" `

to python.autoComplete.extraPaths, and it becomes just as slow as using the original 

`"/Users/username/anaconda3"` within the python.pythonPATH.

I've attached a snapshot of :CocInfo in case it's helpful for context.
<img width="1037" alt="brokenautocomplete_redac" src="https://user-images.githubusercontent.com/40323012/101701549-bc85bb00-3a44-11eb-88fe-3937125665f9.png">

**Comment by chemzqm** [comment]
Sorry, I can't fix those issues with coc-python
