### ISSUE TITLE
latest coc.nvim's status bar doesn't work well with cargo check on save

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2698]
## Describe the bug

![Peek 2020-12-10 12-43](https://user-images.githubusercontent.com/33961674/101768151-82202a80-3ae5-11eb-909e-d3199f8e9f95.gif)

as you can see every time when I finish editing, it flashes a status bar. It should be related to `cargo check`

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
So what's problem?

**Comment by GopherJ** [comment]
@chemzqm flashes of `cargo check` on save while editing

**Comment by fannheyward** [comment]
Set `workspace.progressTarget` to `statusline`.

**Comment by GopherJ** [comment]
@fannheyward cool, thanks!
