### ISSUE TITLE
Capture in popup any spawned language server interactivity

### ISSUE THREAD

**Issue by bgmonroe** [neoclide/coc.nvim#2700]
I'm not sure if this functionality already exists but [yesterday, Hashicorp updated terraform-ls](https://github.com/hashicorp/terraform-ls/releases/tag/v0.11.0) to now interactively **"Ask for init if current folder is empty root module"** (https://github.com/hashicorp/terraform-ls/pull/257).  So unless `terraform init` has already been run, this causes VIM to "seemingly" hang on startup, as no keys respond except for the the 't' (to perform the init) or <CR> or <ESC> to not.

You can see the dialog by setting `COC_NO_PLUGINS=1` before running `vim filename.tf`. 

![image](https://user-images.githubusercontent.com/40213173/101840079-4f336200-3af8-11eb-84f2-79a59cf0d364.png)

It would be nice (for clarity) to be able to capture and display that interaction for an interactive key-press in a popup.

**Comment by chemzqm** [comment]
It's already supported with latest coc.nvim.
