### ISSUE TITLE
[BREAK CHANGE] `workspace.onWillSaveUntil` method will be removed

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#2704]
`workspace.onWillSaveTextDocument` will always emit event with `waitUntil(thenable: Thenable<TextEdit[] | any>): void` method, use that instead.

Each handler will be called for `textEdit[]`, and only the first returned `textEdit[]` (not empty) would be applied to the document, this is the same behavior as VSCode,

Multiple formatters won't work in subsequence any more (which can be buggy), create `BufWritePre` autocmd in your vimrc for that purpose.

**Comment by fannheyward** [comment]
Does `formatOnSaveFiletypes` still work?

**Comment by chemzqm** [comment]
It should still work.

**Comment by develra** [comment]
Heya - apologies for the ignorance:
https://github.com/neoclide/coc-tslint-plugin/blob/master/src/index.ts#L38
Should this be updated to 
```
workspace.onWillSaveTextDocument
```
?
Thanks!
