### ISSUE TITLE
"displayByAle" is blocked due to conflicting logic in diagnostic/manager.ts

### ISSUE THREAD

**Issue by resolritter** [neoclide/coc.nvim#2710]
If `displayByAle` is true, then `enabled` is set to false

https://github.com/neoclide/coc.nvim/blob/f2afd214babdc383760f52b0876f5e254d04683d/src/diagnostic/manager.ts#L631-L633

However, if `enabled` is false, then `refreshBuffer` returns early and does not work for ALE

https://github.com/neoclide/coc.nvim/blob/f2afd214babdc383760f52b0876f5e254d04683d/src/diagnostic/manager.ts#L672

To get around it (I do not yet know if this solution is proper as a whole)

```diff
  -    if (!buf || !this.enabled) return false
  +    if (!buf || (!this.enabled && !this.config.displayByAle)) return false
```

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
