### ISSUE TITLE
Can I use `$HOME` or `~` in coc-settings.json?

### ISSUE THREAD

**Issue by stark-zhang** [neoclide/coc.nvim#2720]
I configured ccls in coc.nvim as following:
```json
{
"languageserver": {
                       "ccls":{
                               "command": "ccls",
                               "filetypes": [
                                       "c", "cc", "cpp", "cxx"
                               ],
                               "rootPatterns": [
                                       ".git/",
                                       ".svn/",
                                       ".hg/",
                                       ".ccls",
                                       "compile_commands.json"
                               ],
                               "initializationOptions": {
                                       "cache": {
                                                "directory": "$HOME/.cache/ccls"
                                       },
                                       "highlight": {
                                               "lsRanges": true
                                       }
                               }
                }
        }
}
```
you can found that I used `$HOME/.cache/ccls` as cache directory of ccls. In my expect, this path is a sub-directory of `/home/username`. But coc.nvim didn't work as my expect, it built a directory named `$HOME` in my project root path.

And this happened when I used `~` as abbreviation of home.

So it it a bug? how to use environment variables in `coc-settings.json`?

**Comment by chemzqm** [comment]
You can't

**Comment by stark-zhang** [comment]
well, i think this command didn't give me useful help. I just want to use `$HOME` or `~` in coc-settings.json, but i couldn't find solution in coc.txt.

How to? or is it not implemented?

**Comment by stark-zhang** [comment]
well, i think this command didn't give me useful help. I just want to use `$HOME` or `~` in coc-settings.json, but i couldn't find solution in coc.txt.

How to? or is it not implemented?

**Comment by chemzqm** [comment]
It's only supported for some configurations like `command` for now https://github.com/neoclide/coc.nvim/blob/master/src/workspace.ts#L1025, might improved that in the future.
