### ISSUE TITLE
signature help of coc-clangd disappears after 6b3056d42ff206db56336d583841b643994bf2f7

### ISSUE THREAD

**Issue by wrvsrx** [neoclide/coc.nvim#2721]
## Result from CocInfo

vim version: NVIM v0.5.0-dev+944-g82100a6bd
node version: v15.4.0
coc.nvim version: 0.0.79-7e550643a5
coc.nvim directory: /home/mars/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Describe the bug

After the update 6b3056d42ff206db56336d583841b643994bf2f7, coc-clangd can't show signature help.

## Reproduce the bug

1. Use minimal vimrc
2. open main.cpp, input following content
```
int plus(int a, int b) {
	return a + b;
}
int main() {
  plus([cursor]);
}
```
3. When cursor stays at the [cursor] position, there isn't any signature help
4. Checkout the previous commit of 6b3056d42ff206db56336d583841b643994bf2f7, do the same, then the signature help appears.

**Comment by chemzqm** [comment]
Signature help won't show unless you trigger it.

**Comment by wrvsrx** [comment]
I found it's because that my PC is too slow and it's timeout for signature help. After I adjust the `"signature.triggerSignatureWait
"`, it works well.
