### ISSUE TITLE
Ale diagnostics not being updated after fixing an error.

### ISSUE THREAD

**Issue by dedsm** [neoclide/coc.nvim#2724]
## versions

vim version: NVIM v0.4.4
node version: v15.4.0
coc.nvim version: 0.0.79-464bb069e2
coc.nvim directory: /home/david/.local/share/nvim/plugged/coc.nvim
term: tmux-256color
platform: linux

## Log of coc.nvim

2020-12-17T13:50:23.397 INFO (pid:3778032) [services] - registered service "jedi"
2020-12-17T13:50:23.399 INFO (pid:3778032) [services] - jedi-language-server state change: stopped => starting
2020-12-17T13:50:23.404 INFO (pid:3778032) [plugin] - coc.nvim 0.0.79-464bb069e2 initialized with node: v15.4.0 after 351ms
2020-12-17T13:50:23.416 INFO (pid:3778032) [language-client-index] - Language server "jedi" started with 3778338
2020-12-17T13:50:23.556 INFO (pid:3778032) [services] - jedi-language-server state change: starting => running
2020-12-17T13:50:23.561 INFO (pid:3778032) [services] - service jedi started
2020-12-17T13:50:25.743 INFO (pid:3778032) [completion-complete] - Results from: jedi-1
2020-12-17T13:52:45.227 INFO (pid:3778032) [completion-complete] - Results from: jedi-1

## Describe the bug
I'm using coc-jedi, but the issue seems to be related to coc: https://github.com/dense-analysis/ale/issues/3447

While coding a python source file, the last error displayed will stay on even after fixing the error.

as an example:

```python
class TestClass:
    def testcoc(self):
        pass
```
removing the `pass` line will show the correct syntax error, but after writing the `pass` again, it stays displayed.

git bisect log:
```
git bisect start
# good: [25171cab9b9e9628ba0f82d2974f0e6fd6ab7112] fix: diagnostic.refreshAfterSave (#1236)
git bisect good 25171cab9b9e9628ba0f82d2974f0e6fd6ab7112
# bad: [c9041340eb15f516b562b8fbfcd3c7bd43a63075] commit 652a8a3381aba871030c4845d5932fdab9a6b09d
git bisect bad c9041340eb15f516b562b8fbfcd3c7bd43a63075
# good: [73c05a0871b69b1b2b2475cd8616c7dd8c155306] feat(list): support first option
git bisect good 73c05a0871b69b1b2b2475cd8616c7dd8c155306
# good: [df839e641b927c9424e33f8eb70d009feb1c01b3] fix(float): avoid possible float winid
git bisect good df839e641b927c9424e33f8eb70d009feb1c01b3
# good: [37e2b9d0f87d72950047641e2f6a7a4b0f204248] fix(completion): avoid unnecessary completion refresh
git bisect good 37e2b9d0f87d72950047641e2f6a7a4b0f204248
# good: [adacff28dfabfead7770a1c716006793eeb47e37] feat(language-client): log child process error
git bisect good adacff28dfabfead7770a1c716006793eeb47e37
# good: [df7b5d4f4e64d5dc2fa24dbf8143109afa93539c] commit 721f227aa06ccf2f651ecc00c78502ece1d1aa6b
git bisect good df7b5d4f4e64d5dc2fa24dbf8143109afa93539c
# good: [2476d24473aa01c68012e06a23da83515696a523] commit 0de7494ffe4a4c97ad79d4e0a18e3cf84ddf6468
git bisect good 2476d24473aa01c68012e06a23da83515696a523
# bad: [dce1b5cb87cbafae20a24fe3b17fe9648e84dd4e] commit 7e550643a530e1de72d82e33d8b159d200aa8873
git bisect bad dce1b5cb87cbafae20a24fe3b17fe9648e84dd4e
# bad: [63cbd7bfecb6ed5598b136e859c675ae8e7156ea] commit 437fdaadabe7821f0100748fc8ca8c2f493d5476
git bisect bad 63cbd7bfecb6ed5598b136e859c675ae8e7156ea
# good: [1fe1e02eca07fe1fbe9427e2e8a1b29289f281be] commit 464bb069e2aa19b07a1bd52b77210888aba45187
git bisect good 1fe1e02eca07fe1fbe9427e2e8a1b29289f281be
# first bad commit: [63cbd7bfecb6ed5598b136e859c675ae8e7156ea] commit 437fdaadabe7821f0100748fc8ca8c2f493d5476 
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
let g:ale_disable_lsp = 1
set nocompatible
set runtimepath=/path/to/coc.nvim,/path/to/ale
filetype plugin indent on
syntax on
set tabstop=4
set softtabstop=4
set shiftwidth=4
set filetype=python

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Ale
"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let g:ale_sign_error = '✖'
let g:ale_sign_warning = '⚠'

let g:ale_python_mypy_options = '--follow-imports normal --ignore-missing-imports'

let g:ale_linters = {
\  'python': ['bandit', 'flake8', 'mypy'],
\}

set hidden

set cmdheight=2
set updatetime=300
set shortmess+=c
set signcolumn=yes
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
464bb069e2 is old release.
