### ISSUE TITLE
Disabling suggest.autoTrigger no longer works

### ISSUE THREAD

**Issue by idanarye** [neoclide/coc.nvim#2728]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-844-g8c4648421
node version: v14.8.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/idanarye/.vim/plugins/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2020-12-18T00:14:23.261 INFO (pid:15809) [plugin] - coc.nvim 0.0.79 initialized with node: v14.8.0 after 25ms
2020-12-18T00:14:25.361 INFO (pid:15809) [completion-complete] - Results from: file
2020-12-18T00:14:29.220 INFO (pid:15809) [completion-complete] - Results from: file
2020-12-18T00:14:46.087 INFO (pid:15809) [completion-complete] - Results from: file


```

## Describe the bug

Configuring `suggest.autoTrigger` to `none` no longer works - the completion popup still gets opened automatically after typing certain characters like `.` or `/`.

I have bisected the commits and found that this bug was introduced in 365c63e12f82675dfe3ec485a57eb4af964e421d. When I checkout the commit before it `suggest.autoTrigger` works and I do not get uninvited completion popups.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden

call coc#config('suggest.autoTrigger', 'none')
```

- Start (neo)vim with command: `vim -u mini.vim`

- Hit `i` to enter insert mode.
- Hit `/` (the bug still happens with other completion triggers, but `/` is the easiest to trigger with a minimal setup)
- A path completion popup is opened. It shouldn't open, because `mini.vim` sets `suggest.autoTrigger` to `none`.

**Comment by chemzqm** [comment]
Fixed by adf219e7
