### ISSUE TITLE
Flash screen while selecting range

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2729]
## Result from CocInfo

![image](https://user-images.githubusercontent.com/33961674/102566263-73d29f80-40df-11eb-8820-d92f85c22a5d.png)

## Describe the bug

A clear and concise description of what the bug is. Screen keeps flashing while calling coc.nvim's `coc-range-select`:

![Peek 2020-12-18 03-14](https://user-images.githubusercontent.com/33961674/102566334-a086b700-40df-11eb-9e4c-6d1a5092c457.gif)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by GopherJ** [comment]
I can reproduce this in rust & typescript

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by chemzqm** [comment]
You have `cursorline`, `cursorcolumn` and vistual text enable which can be really laggy.
