### ISSUE TITLE
(kitty|alacritty) + tmux + neovim + base16 highlight fail

### ISSUE THREAD

**Issue by cr0ax** [neoclide/coc.nvim#2738]
![Screenshot_2020-12-19_15-22-44](https://user-images.githubusercontent.com/60494319/102701695-7384f200-420e-11eb-95c7-64469c266da8.png)

Could someone direct me to where I could override the coloring on this window? I'm quite new to vim plugins.

I am using the stack referenced in the title with the `base16_material` theme. The error message is unreadable.

Apologies if this is not the place to ask for such things.

**Comment by oblitum** [comment]
The simplest solution is simply to try another colorscheme, this one you chose provide bad colors. Besides that, check docs for coc colors customizaton at `:h coc-highlights`.
