### ISSUE TITLE
Help setting up COC with coc-jedi, black(format on save) and pylint. 

### ISSUE THREAD

**Issue by arvindamirtaa** [neoclide/coc.nvim#2739]
My goal is to setup coc with jedi for autocompletion (which works fine), black (format on save) and pylint (for linting). 

I have both coc.vim and coc-jedi installed. 
Black is installed (and coc-settings points to the right interpreter). 

Here is my coc-settings.json. 

```
{
  "codeLens.enable": true,
  "coc.preferences.extensionUpdateCheck": "daily",
  "coc.preferences.formatOnType": true,
  "coc.preferences.formatOnSaveFiletypes": [
    "python",
    "markdown",
    "javascript",
    "json"
  ],
  "python.formatting.provider": "black",
  "jedi.enable": true,
  "jedi.startupMessage": true,
  "jedi.markupKindPreferred": "plaintext",
  "jedi.trace.server": true,
  "jedi.jediSettings.autoImportModules": [],
  "jedi.executable.command": "jedi-language-server",
  "jedi.executable.args": [],
  "jedi.completion.disableSnippets": false,
  "jedi.diagnostics.enable": true,
  "jedi.diagnostics.didOpen": true,
  "jedi.diagnostics.didChange": true,
  "jedi.diagnostics.didSave": true,
  "jedi.workspace.extraPaths": [],
  "suggest.asciiCharactersOnly": true,
  "diagnostic.format": "%message [%source]",
  "diagnostic.virtualText": true,
  "diagnostic.checkCurrentLine": true

}
```

But when I open a python file and save it, nothing happens. Formatting does not run. 

Can someone point me in the right direction?

**Comment by arvindamirtaa** [comment]
Looks like coc-python is just the way to go. 

The warning was tripping me up. I figured if there's a warning that says use something else, maybe it's not a good idea?

**Comment by fannheyward** [comment]
If you're using coc-jedi, follow this configurations: https://github.com/pappasam/coc-jedi#code-formatting https://github.com/pappasam/coc-jedi#additional-diagnostics

**Comment by manujchandra** [comment]
@arvindamirtaa 

Hi,

Were you able to make coc work with jedi + black + pylint? If yes could you please share your setup / instructions on how to do it?

(I am currently using ale to make black and jedi work)

Thanks.

**Comment by EnricoSteez** [comment]
Hi, I am having a very similar issue. This is my coc-settings.json:
```{
	"python.formatting.provider":"black",
	"python.formatting.blackPath": "/Users/enrico/Library/Python/3.9/lib/python/site-packages/black",
	"python.linting.pylamaEnabled":true,
	"coc.preferences.formatOnSaveFiletypes": [
		"python",
		"json"
	]
}
```
But when I run `:call CocAction('format')` (or I map it to a keystroke and press it), I get
[coc.nvim] Formatting with black failed 
What am I missing?

**Comment by yaegassy** [comment]
@EnricoSteez `python.formatting.blackPath` should be set to the path of the `black` command executable from "cli".

**Example**:

- `"python.formatting.blackPath": "/Library/Frameworks/Python.framework/Versions/3.10/bin/black"`
- `"python.formatting.blackPath": "~/.local/bin/black"`
