### ISSUE TITLE
Issues of onDidChangeTextDocument

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#2743]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-nightly-1894-g8b2887bd5
node version: v14.15.0
coc.nvim version: 0.0.79-958d074823
coc.nvim directory: /Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim
term: xterm-kitty
platform: darwin

```

## Describe the bug

1:

In `workspace.onDidChangeTextDocument` `const doc1 = workspace.getDocument(event.textDocument.uri)`  `const doc2 =    const doc = await workspace.document`

and `doc1.uri === doc2.uri` but `doc1 !== doc2`.

2:

`|` is cursor

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div|
</body>
</html>
```

after type `>` then contentChanges's range is empty:

```
[{"range":{"start":{"line":8,"character":6},"end":{"line":8,"
character":6}},"rangeLength":0,"text":">"}]
```

this cause the coc-html tag closing not work, i have make a pr https://github.com/neoclide/coc-html/pull/31 to get it to work.
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
Thanks , coc-html needs fix for the new implementation of textDocument property.
