### ISSUE TITLE
CocNext/CocPrev do not leave cursor at location

### ISSUE THREAD

**Issue by piersy** [neoclide/coc.nvim#2745]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v10.19.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/pierspowlesland/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-12-21T12:40:50.627 INFO (pid:127653) [plugin] - coc.nvim 0.0.79 initialized with node: v10.19.0 after 142ms
2020-12-21T12:40:50.635 INFO (pid:127653) [services] - registered service "go"
2020-12-21T12:40:50.636 INFO (pid:127653) [services] - gopls state change: stopped => starting
2020-12-21T12:40:50.703 INFO (pid:127653) [services] - gopls state change: starting => running
2020-12-21T12:40:50.710 INFO (pid:127653) [services] - service go started

vim version: NVIM v0.4.3
node version: v10.19.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/pierspowlesland/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-12-21T12:40:50.627 INFO (pid:127653) [plugin] - coc.nvim 0.0.79 initialized with node: v10.19.0 after 142ms
2020-12-21T12:40:50.635 INFO (pid:127653) [services] - registered service "go"
2020-12-21T12:40:50.636 INFO (pid:127653) [services] - gopls state change: stopped => starting
2020-12-21T12:40:50.703 INFO (pid:127653) [services] - gopls state change: starting => running
2020-12-21T12:40:50.710 INFO (pid:127653) [services] - service go started
```
Coc commit hash:`53f8a1d52b4a459cbd848e1a1acba885d0d672e5`

## Describe the bug

Using `CocNext`/`CocPrevious` to jump to a reference location does not leave the cursor at the jumped to location when the `--no-quit` option is used. This is inconsistent with their behaviour when the `--no-quit` option is not used.

With previous versions of coc-nvim I was able to use the `CocNext` and `CocPrevious` commands to jump to the different locations in lists such as a list of references whilst keeping the list open. `CocNext`/`CocPrevious` would leave my cursor at the location jumped to, allowing me to edit or explore that location.

We previously discussed this functionality [here](https://github.com/neoclide/coc.nvim/issues/2087#issuecomment-646943350) and you  were able to provide it.

Now `CocNext`/`CocPrevious` jump to the location but the cursor remains on the command line underneath the list. 
 
## Reproduce the bug

- Create file `mini.vim` with:

```vim
call plug#begin()

Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}

call plug#end()


" coc nvim suggests these settings

" TextEdit might fail if hidden is not set.
set hidden

" Some servers have issues with backup files, see #649
set nowritebackup
set nobackup
" Better display for messages
set cmdheight=2

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes

let g:coc_global_extensions = ['coc-go']


let mapleader = "\<Space>"
nmap <leader>u <Plug>(coc-references)
nnoremap <c-l> :CocNext<cr>
nnoremap <c-h> :CocPrev<cr>

let g:coc_enable_locationlist = 0
autocmd User CocLocationsChange CocList --no-quit --normal location
```
- Create file `coc-settings.json` with:
```json
{
	"list.normalMappings": {
		"<C-l>": "command:CocNext",
		"<C-h>": "command:CocPrev"
	}
}
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

1. Open a .go file.
1. Get references of some identifier (`<space>u`)
1. Press `<c-l> `(CocNext)
1. Notice that the location in the main window has changed, but the cursor is still in the command line.

## Screenshots (optional)
See repeated use of CocNext in this gif
![CocListCocNextCocPrevBug_2](https://user-images.githubusercontent.com/5087847/102784869-e3bd8000-4394-11eb-87bf-a98463e883b1.gif)

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
