### ISSUE TITLE
List window should be reused if list is open and new list command issued

### ISSUE THREAD

**Issue by piersy** [neoclide/coc.nvim#2747]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v10.19.0
coc.nvim version: 0.0.80-7642d233d6
coc.nvim directory: /home/pierspowlesland/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-12-21T16:06:34.369 INFO (pid:149177) [plugin] - coc.nvim 0.0.80-7642d233d6 initialized with node: v10.19.0 after 94ms
2020-12-21T16:06:34.374 INFO (pid:149177) [services] - registered service "go"
2020-12-21T16:06:34.374 INFO (pid:149177) [services] - gopls state change: stopped => starting
2020-12-21T16:06:34.441 INFO (pid:149177) [services] - gopls state change: starting => running
2020-12-21T16:06:34.446 INFO (pid:149177) [services] - service go started
2020-12-21T16:06:36.233 INFO (pid:149177) [attach] - receive notification: showInfo []
```

Commit hash: `7642d233d6abdce9c0076629deaacdb59ea75f70` (tip of release)

## Describe the bug

If a list is open and another list command is executed, two list windows are opened. Instead the existing list window should be repopulated with the content of the new list command.

Commands like `CocNext/CocPrev` and `CocListCancel` don't make sense if we allow more than one list to exist simultaneously.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
call plug#begin()

Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}

call plug#end()


" coc nvim suggests these settings

" TextEdit might fail if hidden is not set.
set hidden

" Some servers have issues with backup files, see #649
set nowritebackup
set nobackup
" Better display for messages
set cmdheight=2

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes

let g:coc_global_extensions = ['coc-go']


let mapleader = "\<Space>"
nmap <leader>u <Plug>(coc-references)
 ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

1. Open 2 go files.
2. Execute `:CocList outline` then switch to normal mode and navigate to the second go file.
3. Execute `:CocList outline`
4.  Notice that we have 2 windows showing the outline but they both show the outline for the second go file.

If we execute 2 different `CocList` commands then the list contents will be different.

**Comment by chemzqm** [comment]
> and navigate to the second go file.

How to make it without close existing list window?

**Comment by piersy** [comment]
> How to make it without close existing list window?

After switching to normal mode in the list window I used `ctrl+w w` to switch to the main window and then `:bn` to move to the next buffer.
