### ISSUE TITLE
Add goto definition support for yarn plug-in-play

### ISSUE THREAD

**Issue by svrana** [neoclide/coc.nvim#2751]
When using a yarn v2 project that uses yarn [plug-in-play](https://yarnpkg.com/features/pnp), it would be nice if coc-definition would jump into the archive that holds the source definition. In pnp, yarn stores project dependencies as zip files which appears to complicate things.

Oddly depending on how I attempt to jump, I get two different behaviors. If I attempt to jump to definition with ctrl-] (with `set tagfunc=CocTagFunc`), I get E429: File "/zip:/home/shaw/Project/foo/.yarn/cache/foo.zip/node_modules/foo/index.d.ts"  does not exist. However, if I run coc-definition, the screen begins to flashes/flickers until I exit neovim. 

vim version: NVIM v0.5.0-dev (4ed5204bc9d58)
node version: v12.18.4
coc.nvim version: 0.0.80-7642d233d6

**Comment by chemzqm** [comment]
Send your feature request to language server.
