### ISSUE TITLE
How to change identified file type

### ISSUE THREAD

**Issue by snprajwal** [neoclide/coc.nvim#2755]
I am currently using coc.nvim with ccls for C projects. But the config.h/config.def.h files are identified as C++ files and I get a ton of warnings and errors every time I open them. Is there any way I can change the recognised filetype to C instead?

**Comment by chemzqm** [comment]
Use filetype plugin or write autocmd yourself.

**Comment by snprajwal** [comment]
@chemzqm Ok thank you!!
