### ISSUE TITLE
Have the documentation / hover window match editorconfig width or try to fit/formatter docs better?

### ISSUE THREAD

**Issue by NullVoxPopuli** [neoclide/coc.nvim#2761]
**Is your feature request related to a problem? Please describe.**
Currently, when viewing the hover docs (JSDoc or Type Defs, for example), the hovering window is a fixed width.
In addition to being a fixed width, it seems the formatting is a little wonky:

![image](https://user-images.githubusercontent.com/199018/103012283-5c454d80-4509-11eb-9d3f-fe50c8c696a0.png)

I have a lot of screen real estate, and would like my editor to make better use of it.

For example, here is what the source docs for this hover window look like: https://github.com/ember-polyfills/ember-destroyable-polyfill/blob/master/index.d.ts#L141-L193

**Describe the solution you'd like**
Add support for maintaining:
 - indent level (maybe via common-tags' `stripIndent`?
 - widen the width of the hover window to fit contents

**Describe alternatives you've considered**
 - ignore the problem

**Additional context**
This is probably only a problem for documentation that includes code samples.

Ultimately, I think it would be fantastic if I could also have my JS/TS highlighter enabled in these docs things as well. I already have tagged template highlighting and code fence highlighting in markdown, but highlighting docs would be superb!

**Comment by chemzqm** [comment]
> the hovering window is a fixed width.

It has a fixed max width 80, we could provide configuration for that.

> indent level (maybe via common-tags' stripIndent?

Nope.

>  if I could also have my JS/TS highlighter enabled in these docs things as well.

You should have good highlight provided when you language server send it as markdown content, we've already support parse markdown for highlights including code blocks.

**Comment by windowsrefund** [comment]
I was about to open an issue but saw this and figured I'd chime in. Here's a small screenshot of my freshly updated (0.0.80) CoC with the coc-yaml extension behaving poorly when displaying documentation. Notice the broken link (due to line wrapping) as well as the escapes.

[Screenshot](https://imgur.com/DcJWruj.png)

**Comment by chemzqm** [comment]
@windowsrefund it's problem of yaml language server which doesn't tell coc.nvim it's markdown.
