### ISSUE TITLE
CocConfig file saving: Error detected while processing BufWritePre Autocommands for "*.json":

### ISSUE THREAD

**Issue by AdamBD** [neoclide/coc.nvim#2762]
Hi all,

Not sure its a bug, but I get this response when trying to save file in the CocConfig file. I just added coc-prettier so assume its something happening here?

I also use the following autosave commands in my .vimrc

```
autocmd InsertLeave * write
autocmd VimResized * wincmd =
autocmd CursorHold * update
```

**Comment by chemzqm** [comment]
It's bug of your vim script.
