### ISSUE TITLE
How to expand Fold buffer ?

### ISSUE THREAD

**Issue by zxf4399** [neoclide/coc.nvim#2768]
I try `
 command! -nargs=? Fold :call     CocAction('fold', <f-args>)`
I get
![image](https://user-images.githubusercontent.com/55656772/103164219-5b7f2500-4843-11eb-9221-65e015e37d5c.png)

So how can i expand it ? @chemzqm

**Comment by chemzqm** [comment]
Learn viml

**Comment by chemzqm** [comment]
不用问我你的 vim 该怎么用这种跟本插件无关问题，如果你自己不看文档最好趁早别用
