### ISSUE TITLE
coc crashes neovim after last update

### ISSUE THREAD

**Issue by AckmanDESU** [neoclide/coc.nvim#277]
**Result from CocInfo**

## versions

vim version: NVIM v0.3.2-922-gb1aaa0a88
node version: v8.9.0
coc.nvim version: 0.0.39
term: xterm-256color
platform: linux

## Error messages

**Describe the bug**

Last night I ran :PlugUpdate and :CocUpdate. Coc stopped working after that.

No matter what I do, it freezes my Neovim and shows that error message. Nothing seems to work, I can't close neovim without killing the process.

The error shows up whenever I open any file or run many commands.

I've disabled my entire vimrc except for vim-plug and coc. I also uninstalled all coc extensions. The error still shows up.

**To Reproduce**

Open a file, basically.

**Screenshots**

![screenshot_20181216_125852](https://user-images.githubusercontent.com/10189582/50053301-01ff9e00-0133-11e9-853b-ab84a343842d.png)

**Comment by chemzqm** [comment]
It works as expected on my linux, maybe the binary release doesn't work for you, try build the code from source by `yarn install`.

**Comment by chemzqm** [comment]
Or maybe your neovim is broken, there's not commit gb1aaa0a88 on neovim master.

**Comment by AckmanDESU** [comment]
Alright. I think I fixed it thanks to you suggesting it could be related to nvim.

I am using Arch and had installed the neovim-git AUR package. I reinstalled it and the problem seems to be gone.

This is very weird. The last time I updated my system was a week ago, so I didn't consider nvim could be what broke instead of coc, which I had just updated.

Well, thanks for your help and your work.

**Comment by chemzqm** [comment]
Thanks for reporting.
I've made a fix to client, this error should be gone.
