### ISSUE TITLE
jumpCommand set to pedit

### ISSUE THREAD

**Issue by damnskippy** [neoclide/coc.nvim#2770]
Up till release 0.78, setting `coc.preferences.jumpCommand` to `pedit` will cause `jumpDefinition` (for example) to open the definition in a vim preview window.  Same with `:call CocAction('jumpDefinition', 'pedit')`
(Similar to `edit`, but nice thing about `pedit` is that calling another jump command will reuse the preview window.)

In release 0.79 (and 0.80), something seems to have changed the behavior slightly.  The preview window gets opened correctly at the right location returned by language server, which is great.  But the main window (from where the cocAction() was called from _also_ changes to a different (some random) position for some reason.

I understand if pedit is unsupported or if this behavior is expected.  Just thought I'd note it since it worked till 0.78 release and stopped working in 0.79 and was hoping 0.80 might fix but it didn't so just letting you know.

Thanks.

**Comment by chemzqm** [comment]
Use `CocActionAsync` instead

**Comment by damnskippy** [comment]
The problem behavior exists with both `CocActionAsync` and `CocAction`.  You can try it out and see the change in behavior between 0.78 vs later releases.  The main window jumps to some random location.

**Comment by chemzqm** [comment]
Need special handle for pedit

**Comment by damnskippy** [comment]
FWIW, this change works for me:
```
--- a/autoload/coc/util.vim
+++ b/autoload/coc/util.vim
@@ -158,7 +158,6 @@ function! coc#util#jump(cmd, filepath, ...) abort
     let path = substitute(a:filepath, '\v\\', '/', 'g')
   endif
   let file = fnamemodify(path, ":~:.")
-  exe a:cmd.' '.fnameescape(file)
   if !empty(get(a:, 1, []))
     let line = getline(a:1[0] + 1)
     " TODO need to use utf16 here
@@ -166,8 +165,14 @@ function! coc#util#jump(cmd, filepath, ...) abort
     if col == 0
       let col = 999
     endif
-    call cursor(a:1[0] + 1, col)
   endif
+
+  if !empty(get(a:, 1, []))
+    exe a:cmd.' +call\ cursor('.a:1[0].','.a:1[1].')'.' '.fnameescape(file)
+  else
+    exe a:cmd.' '.fnameescape(file)
+  endif
+
   if &filetype ==# ''
     filetype detect
   endif

```
