### ISSUE TITLE
Cursor is in the wrong position during autocomplete

### ISSUE THREAD

**Issue by vaheqelyan** [neoclide/coc.nvim#2776]
## versions

vim version: NVIM v0.4.4
node version: v14.10.0
coc.nvim version: 0.0.79-7e550643a5
coc.nvim directory: /root/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-12-30T20:12:57.790 INFO (pid:9297) [plugin] - coc.nvim 0.0.79-7e550643a5 initialized with node: v14.10.0 after 205ms

## Describe the bug

When you select one of the options, the cursor is not in the middle of the quote

## Reproduce the bug

- `:CocInstall coc-html`
- Open any html file
- Write id
- Then press <C-p>

## Screenshots (optional)
![5da171a9-824d-499a-b1d4-d7f88a4dd0b7](https://user-images.githubusercontent.com/14107127/103366554-67394880-4adc-11eb-9ee6-d0d8780635b0.gif)

**Comment by chemzqm** [comment]
It's expected on vim,  check issues of coc-html
