### ISSUE TITLE
Problem in neovim-qt

### ISSUE THREAD

**Issue by gamardzoba** [neoclide/coc.nvim#2782]
How it works in a terminal and should work correctly:
![terminal](https://user-images.githubusercontent.com/3626876/103437886-6ec03500-4c35-11eb-942f-8a9d9ea5e644.png)

How it works in the https://github.com/equalsraf/neovim-qt:
![neovim-qt](https://user-images.githubusercontent.com/3626876/103437887-754eac80-4c35-11eb-8584-870c24e3f0de.png)

The bug has occurred on Ubuntu 20.10 with the very init nvim config and with a blank one. Easy reproducible.

**Comment by chemzqm** [comment]
You need configure it not use guipum.
