### ISSUE TITLE
Auto-completion of external libraries works but documentation not present

### ISSUE THREAD

**Issue by AndyOng17** [neoclide/coc.nvim#2785]
Hi all, 
By specifying the location of the external jar files to java.project.referencedLibraries. I was able to get auto-completion to work. Classes and methods of the external library showed up in the pop-up menus.  

However, no documentations was available. Only plain class names and method signatures were displayed.

What should I do to get the documentations to appear?

Andy

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by AndyOng17** [comment]
Yeah.. think you'll right. Its now working, albeit erratically.  Thanks.
