### ISSUE TITLE
coc.nvim + ccls uncaught exception

### ISSUE THREAD

**Issue by Moroxus** [neoclide/coc.nvim#279]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
![screenshot from 2018-12-18 15-39-26](https://user-images.githubusercontent.com/11667635/50161107-239b8980-02db-11e9-998b-6bb55bab4156.png)

**Describe the bug**
Autocompletion is not working at all. Below on the screenshot is shown error. I use ccls, I have set correct path to it and I checked it can run out of terminal by hand.

**To Reproduce**
I am using neovim
![screenshot from 2018-12-18 15-45-10](https://user-images.githubusercontent.com/11667635/50161378-ed123e80-02db-11e9-81e3-3e70ac9f2a4f.png)

Coc-settings.json:
![screenshot from 2018-12-18 15-50-22](https://user-images.githubusercontent.com/11667635/50161653-ad982200-02dc-11e9-9fda-f79e69922641.png)

I have compile_commands.json

![screenshot from 2018-12-18 15-47-41](https://user-images.githubusercontent.com/11667635/50161538-601bb500-02dc-11e9-9a42-6b171ae93a43.png)

**Screenshots**
![screenshot from 2018-12-18 15-31-50](https://user-images.githubusercontent.com/11667635/50160738-5002d600-02da-11e9-9267-5c96cb2b3ad8.png)

**Comment by chemzqm** [comment]
`ENOENT` means file not exits, checkout your ccls by use `which ccls` or just use `ccls` as command.

**Comment by Moroxus** [comment]
Thats why I wrote this sentence in the first place:
"I use ccls, I have set correct path to it and I checked it can run out of terminal by hand."
![screenshot from 2018-12-18 17-22-03](https://user-images.githubusercontent.com/11667635/50167451-7e3be200-02e9-11e9-9ade-e3ed269ffb8d.png)

**Comment by chemzqm** [comment]
Could be permission issue or broken node,  try command `node`, and paste:
``` js
let cp = require('child_process')
cp.spawn('/usr/bin/ccls')
```
to see if any errors.

**Comment by chemzqm** [comment]
Also check the path is executable by `:echo executable('/usr/bin/ccls')` in your vim.

**Comment by chemzqm** [comment]
Or maybe your `ccls` requires shell, you can add `"shell": true` to `ccls` section to enable shell.

**Comment by chemzqm** [comment]
The reason should be the linux binary not works for you, you have to build from source, try `yarn install` in plugin root.

**Comment by Moroxus** [comment]
I fixed my coc-settings.json, now it includes "shell": true and languageserver is not nested

![screenshot from 2018-12-18 19-00-46](https://user-images.githubusercontent.com/11667635/50173322-5a7f9880-02f7-11e9-8c55-6df2e153f299.png)

node
let cp = require('child_process')
cp.spawn('/usr/bin/ccls')

works without errors, this is few last lines of output

![screenshot from 2018-12-18 19-04-25](https://user-images.githubusercontent.com/11667635/50173502-f90bf980-02f7-11e9-925e-f551858d35a8.png)

:echo executable('/usr/bin/ccls') outputs 1

I changed my plugin root to yarn install

![screenshot from 2018-12-18 19-07-48](https://user-images.githubusercontent.com/11667635/50173593-3ff9ef00-02f8-11e9-97a0-9fe289037692.png)

There is still error, with sligltly changed output:

![screenshot from 2018-12-18 19-08-28](https://user-images.githubusercontent.com/11667635/50173632-530cbf00-02f8-11e9-840e-4e302bc068d8.png)

**Comment by chemzqm** [comment]
After change to your `.vimrc`, run `:PlugUpdate` to build coc.nvim.

**Comment by Moroxus** [comment]
Now we are getting somewhere. Error changed. When I add `"shell": true` I got `Error: spawn /bin/sh ENOENT`
![screenshot from 2018-12-18 23-30-19](https://user-images.githubusercontent.com/11667635/50186993-f53e9e00-031c-11e9-86b8-20add8d412d5.png)

**Comment by Moroxus** [comment]
Ok, so I guess I know something more now... The project I was testing it on is in directory such, that one directory on the path contains space in the name (i.e.: "C++ Projects" - space between second plus and P). When I copied my project somewhere else and no spaces where inside path, everything is working as expected.
![screenshot from 2018-12-18 23-55-47](https://user-images.githubusercontent.com/11667635/50188055-8b27f800-0320-11e9-9742-7d8244b4f382.png)

**Comment by oblitum** [comment]
>  When I copied my project somewhere else where no spaces are inside the path, everything is working as expected

Well, that would be a bug if directory with spaces isn't supported.

**Comment by oblitum** [comment]
May be language server or coc.nvim issue (or still something in your machine).

**Comment by AlecsFerra** [comment]
Having the same issue on arch linux
![Jun05::17-12-59](https://user-images.githubusercontent.com/35380179/83893210-f69d9980-a74f-11ea-939f-f8bc1a04530e.png)
