### ISSUE TITLE
[Help] Lightline error, warning, hint & info highlighting

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [neoclide/coc.nvim#2792]
Hello!

First of all thanks for all the work done in COC I have been using it almost since birth and it has changed how I work :) it's been really amazing.

I have a question on how to change the highlighting groups for `error, warning, hint & info` in lightline. I have looked quite a bit into the issues here and some plugins but found nothing that helps in setting the `fg` and `bg` colors for how `error, warning, hint & info` appear in lightline. Any hint would be useful.

Cheers!

**Comment by chemzqm** [comment]
Please read doc of lightline.
