### ISSUE TITLE
Unable to load schema from '/NODE_PATH/@angular/cli/lib/config/schema.json' :CocDiagnostics

### ISSUE THREAD

**Issue by danushk** [neoclide/coc.nvim#2795]
Here is the problem 

![image](https://user-images.githubusercontent.com/185419/103534129-4c881a80-4eb4-11eb-9de4-cb41603d9b1e.png)

## Result from CocInfo

![image](https://user-images.githubusercontent.com/185419/103534262-8f49f280-4eb4-11eb-9dd1-2c71a5d77aa6.png)

## Describe the bug

I have multiple angular projects which uses same node_modules folder , since having each copy of node_modules under each directory is an overkill , i moved them to a common place and set NODE_PATH to it. 

Projects get compiled fine , and works at expected , but not Coc - it keeps showing this warning 

## Reproduce the bug

1 move node_modules folder to a common place outside your project directory
2 set NODE_PATH env variable to that on your .bashrc
3 open an existing angular project on vim enabled with Coc
4 run :CocDiagnostics

You will see the same results.

This annoying problem makes very difficult to code because it makes the vim window dance , so unable to maintain focus. 

love to get it fixed

**Comment by chemzqm** [comment]
Should be issue with your coc-angular extension
