### ISSUE TITLE
coc.txt help

### ISSUE THREAD

**Issue by davidsu** [neoclide/coc.nvim#2796]
```vim
:h coc.nvim
```
gives me `Sorry, no help for coc.nvim`, are we missing a tags file?
I added on my filesystem under `coc.nvim/docs/tags`
```vim
coc.nvim	coc.txt	/*coc-contents*
```
and than it works. Am I missing something? should I pr this?

**Comment by chemzqm** [comment]
You have to use `:h coc-nvim`
