### ISSUE TITLE
Language server/plugin persistency

### ISSUE THREAD

**Issue by marekdedic** [neoclide/coc.nvim#2797]
**Is your feature request related to a problem? Please describe.**
Hi, my way of working is editing files with vim all over the place (I like to have my code split into files), quickly going in and out of files. This way, I'm starting and quitting vim quite often. Some language servers/plugins take quite some time to start (for example coc-julia) and that means that if I want to see their output, I have to wait quite a lot...

**Describe the solution you'd like**
I would like for language servers and plugins to be able to persist even after closing vim. I imagine it as there being some timeout, for example 5 minutes, so that when I close vim and reopen it inside 5 minutes, the language server would still be running and wouldn't need to start again.

**Describe alternatives you've considered**
Changing my working habits by opening files directly from vim. Not nearly as quick and simple (for example I can't change directories...)

**Comment by chemzqm** [comment]
Not possible, maybe send your feature request to lsp.
I did open and quit vim quite often as well without your issue, so I think the language server you're using should improved.
