### ISSUE TITLE
Triggering after '.' or backspaces

### ISSUE THREAD

**Issue by bschulte** [neoclide/coc.nvim#28]
Thanks for writing the plugin! I've been testing it out and an initial pain point for me is I lose the autocomplete suggestions if I have to backspace or if I complete a suggestion and want to get suggestions for properties on the object that I just selected. 

For example if I'm writing in Javascript and I type "conso" to then select the suggestion of "console" and then type "." to call a method on `console` the autocomplete suggestions do not pop up. And again, having the suggestion menu disappear if I have to hit backspace to correct a mistake does not feel great.

Maybe there's something in the config that I've missed that can help with this, but otherwise I think it would greatly enhance the experience to keep the autocomplete menu open when backspacing and also having it "re-trigger" when a character is inputted to act on a variable ('.' for Javascript as an example). Thanks again!

**Comment by bschulte** [comment]
Of course right after I post this I dig through the Wiki a bit more and find this example:
```
" use <tab> for trigger completion and navigate next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
```

This basically solves my problem since it solves the backspace issue and I can then use TAB to have the CoC menu refresh after I insert a '.'

I still would have figured that entering in a '.' would trigger the autocomplete based on triggerCharacters, but maybe I could be mistaken about that or missing something else.

**Comment by chemzqm** [comment]
> and then type "." to call a method on console the autocomplete suggestions do not pop up.

The popup menu should just be shown unless you have `  "coc.preferences.autoTrigger": "none",
` in your coc-settings.json. If not, there must be something wrong.

> having the suggestion menu disappear if I have to hit backspace to correct a mistake does not feel great.

Yes, it could be improved.
