### ISSUE TITLE
Disable formatters/change formatting priority.

### ISSUE THREAD

**Issue by colbydehart** [neoclide/coc.nvim#280]
I installed coc-prettier as well as coc-tsserver. However, prettier has a lower priority than the tsserver formatter, but I would rather format my code with prettier. 

Is there some way to configure which formatter has priority or disable formatters for certain filetypes? 

right now, the way i'm handling it is just having 
```
  au! bufwritepre *.tsx :CocCommand prettier.formatFile
  au! bufwritepre *.jsx :CocCommand prettier.formatFile
  au! bufwritepre *.ts :CocCommand prettier.formatFile
  au! bufwritepre *.js :CocCommand prettier.formatFile
```
to get formatting, but I think using this autocommand hook might not be the best way to go.

**Comment by chemzqm** [comment]
The current API doesn't support priority for formatter, it could be improved.

**Comment by colbydehart** [comment]
Cool, ill pull it down and look at it over the holidays. Great job on this plugin, its wonderful

**Comment by chemzqm** [comment]
There is `prettier.disableLanguages` to disable languages for prettier.
Update coc.nvim and coc-prettier to have prettier as higher priority.

**Comment by soywod** [comment]
I was looking for this feature also, and the reply was not that clear. So, for those who stop here, add in your coc config `"prettier.formatterPriority: -1"` as describe in the [coc-prettier](https://github.com/neoclide/coc-prettier#prettierformatterpriority-default-1---priority-of-fomatter) doc.

Btw your plugin is awesome :ok_hand:
