### ISSUE TITLE
Updating to 0.0.8 not working

### ISSUE THREAD

**Issue by andy-dev** [neoclide/coc.nvim#2800]
Hello,
Using VimPlug to install coc.nvim. I deleted directory `~/.vim/plugged/coc.nvim`
I re installed trying both:
`Plug 'neoclide/coc.nvim', {'branch': 'release'}`
and 
`Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}`

And after running `CocInfo` I still get 
`coc.nvim version: 0.0.78-9f9d8a32c4`
node `v12.14.1`
vim version: `NVIM v0.4.4`

I also tried 
PlugUpdate, PlugUpgrade, and CocUpdate
Am I missing a step?

**Comment by andy-dev** [comment]
Not sure what fixed it, but restarted my computer and reinstalled and that seemed to worked.

**Comment by Spuxy** [comment]
@andy-dev 
same problem what I did was delete the folder coc.nvim and ran "PlugUpgrade", "PlugUpdate", "PlugInstall", "CocUpdate" :D
