### ISSUE TITLE
coc.preferences.formatOnSaveFiletypes for C language will cause wrong header file sequence

### ISSUE THREAD

**Issue by cyrilwongmy** [neoclide/coc.nvim#2817]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-dev+1007-g9223d1450
node version: v15.5.1
coc.nvim version: 0.0.80-cf0e8400a4
coc.nvim directory: /home/cyril/.config/nvim/plugged/coc.nvim
term: st-256color
platform: linux

```

## Describe the bug
header file starts with higher order in alphabet order will be put in front of lower order header file. However, this formating order will cause some file dependency inconsistency.
This issue may be caused by using alphabet order.

## Reproduce the bug
coc-settings.json
```json
  "coc.preferences.formatOnSaveFiletypes": [
    "javascript",
    "typescript",
    "html",
    "css",
    "json",
    "python",
    "vue",
   "c",
  ]

```

Reproduce a main.c, types.h, buf.h.
If one header file "types.h" is in the front of another header file "buf.h" originally ("buf.h" header file relies on some types in "types.h" header file), formatOnSaveFile will cause header file "buf.h" put in front of header file "types.h". This will also cause compilation issue.

types.h
```c
typedef unsigned int   uint;
```
buf.h
```c
struct buf {
  uint refcount;
}
```
main.c
```c
#include "types.h"
#include "buf.h"
```

## Screenshots (optional)
![ReportBug2](https://user-images.githubusercontent.com/50711134/104676940-6252d680-5723-11eb-8c00-0a95854dec3b.png)
![ReportBug](https://user-images.githubusercontent.com/50711134/104676947-6848b780-5723-11eb-98f2-326b5069bfe2.png)

**Comment by fannheyward** [comment]
What's language server do you use for C?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by cyrilwongmy** [comment]
> What's language server do you use for C? The format-onsave function is provided by language server, properly is a LS issue.

Thank you, I am using clangd.
