### ISSUE TITLE
coc does not recognise set filetype

### ISSUE THREAD

**Issue by snprajwal** [neoclide/coc.nvim#2818]
## versions

vim version: NVIM v0.4.4
node version: v15.5.1
coc.nvim version: 0.0.80-fff2a86b16
coc.nvim directory: /home/prajwalsn/.config/nvim/plugged/coc.nvim
term: st-256color
platform: linux

## Log of coc.nvim

2021-01-15T12:14:35.285 INFO (pid:5483) [services] - registered service "languageserver.ccls"
2021-01-15T12:14:35.335 INFO (pid:5483) [plugin] - coc.nvim 0.0.80-fff2a86b16 initialized with node: v15.5.1 after 149ms
2021-01-15T12:14:39.119 INFO (pid:5483) [attach] - receive notification: showInfo []

## Describe the bug

Coc.nvim refuses to provide correct autocompletion when `set filetype` is used, or if the buffer is not written to disk.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start neovim with command: `nvim -u mini.vim`

- In an empty buffer, run `set filetype=cpp`.

- Type `#inc` and press `Tab`/`Ctrl-Space`/`<your autocomplete binding>`

- Autocomplete does not work

**Comment by chemzqm** [comment]
I've made a fix, if you still have issue, paste verbose output from your language server:
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by snprajwal** [comment]
Thank you!
