### ISSUE TITLE
Can't see my code

### ISSUE THREAD

**Issue by sumit-official** [neoclide/coc.nvim#2820]
When ever I go to write code in neovim and write a fuctions that has a "(" in it the autocomplete gu shows up and blocks my view 
even then i continue writing it does not go away it only does away if i leave insert mode or go up or down a line.

while im writing
![sumit@DESKTOP-U916JUG_ _mnt_c_Users_admin_OneDrive_Desktop_code_c++_CP 1_15_2021 4_20_04 PM](https://user-images.githubusercontent.com/68991489/104716681-44e73200-574e-11eb-90b2-a7cefb760e25.png)

this is the problem(see how it blocks my view)
![sumit@DESKTOP-U916JUG_ _mnt_c_Users_admin_OneDrive_Desktop_code_c++_CP 1_15_2021 4_20_16 PM](https://user-images.githubusercontent.com/68991489/104716789-5fb9a680-574e-11eb-9205-4a70eda9432b.png)

**Comment by chemzqm** [comment]
You can disable float window of completion documentation https://github.com/neoclide/coc.nvim/wiki/F.A.Q

**Comment by sumit-official** [comment]
Documentation didn't show a straight forward way to disable floating
windows could please help me I can't figure out how to make this work
