### ISSUE TITLE
Second-order pop-up menu when long strings get truncated

### ISSUE THREAD

**Issue by flimofly** [neoclide/coc.nvim#2824]
I have long had issues with long strings in completion windows, such as citation completion drawn from a .bib file in LaTeX projects. These windows get truncated when they are too close to the terminal edge. In theory the window should then move to the left side of the cursor if there is more space there (but that doesn't always work presumably because there might not be sufficient room there either).

<img width="584" alt="Screenshot 2021-01-15 at 21 44 59" src="https://user-images.githubusercontent.com/20085376/104777396-dfaa3580-577b-11eb-81bb-a343f81eba35.png">

My suggestion would be to have a second pop-up menu detailing the basic info in the main pop-up, along these lines: 

<img width="373" alt="Screenshot 2021-01-15 at 21 52 49" src="https://user-images.githubusercontent.com/20085376/104777489-08322f80-577c-11eb-9c80-f6bafa1c3ccc.png">

Apologies if there is an easier fix. I have tried a few things (such as setting a larger `pumwidth` for the window) but to no avail.

**Comment by chemzqm** [comment]
Send your feature request yo vim

**Comment by chemzqm** [comment]
coc.nvim doesn't have support for shown detail in float/popup by `"suggest.detailField": "preview"`, but the picture you give seems the completion is not from coc.nvim.
