### ISSUE TITLE
Option to enable coc on a preview window

### ISSUE THREAD

**Issue by lanza** [neoclide/coc.nvim#2826]
When using a list preview pane it would be nice to continue using coc within the preview page to still be able to jump to definitions and what not. This was previously how it worked, but it seems to have been disabled at some point in the past few months.

**Comment by chemzqm** [comment]
It's by design since it now only show part of preview lines in a `nofile` buffer for performance.

**Comment by chemzqm** [comment]
Open the target location if you need to do further action.
