### ISSUE TITLE
[BREAK CHANGE] throw error when document not attached or provider not found

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#2828]
For actions needs provider coc.nvim would throw error when document not attached or required provider not exists.

This makes the user understand what happened and other plugin easier to handle the failed request when using `CocAction()` or `CocActionAsync`.

**Comment by coderek** [comment]
I have just updated to the latest version and got this error thrown. 
`[coc.nvim]: Error on notificaiton "jumpDefinition": current buffer 1 not attached`
May I what does it mean and how can I resolve it?

**Comment by coderek** [comment]
After I installed coc-tsserver, it works now.

**Comment by chemzqm** [comment]
Check out `:h coc-action-ensureDocument` for ensure current document attached.
