### ISSUE TITLE
Pressing enter cancels the completion and begins a new line while using tab for trigger suggestion based on the docs

### ISSUE THREAD

**Issue by huyhoang8398** [neoclide/coc.nvim#2829]
## versions

vim version: NVIM v0.4.4
node version: v15.6.0
coc.nvim version: 0.0.80-1e2652e725
coc.nvim directory: /home/huyhoang8398/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-01-17T05:10:04.445 INFO (pid:104337) [services] - registered service "highlight"
2021-01-17T05:10:04.451 INFO (pid:104337) [plugin] - coc.nvim 0.0.80-1e2652e725 initialized with node: v15.6.0 after 65ms
2021-01-17T05:10:04.456 INFO (pid:104337) [language-client-index] - highlight started with 104350
2021-01-17T05:10:07.346 INFO (pid:104337) [attach] - receive notification: showInfo []

## Describe the bug

Pressing enter cancels the completion and begins a new line while using tab for trigger suggestion based on the docs

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

```vim
" use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()
```
![image](https://user-images.githubusercontent.com/25379882/104830819-a6102200-5882-11eb-8463-8de7307652fb.png)

**Comment by chemzqm** [comment]
Read wiki https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources
