### ISSUE TITLE
Extend CocDiagnostics to show diagnostics for whole project

### ISSUE THREAD

**Issue by brendanator** [neoclide/coc.nvim#2835]
**Is your feature request related to a problem? Please describe.**
I'm running a command in a language server that scans the whole project and creates diagnostics in many files. I'd like to see them all in the location list similarly to how `:CocDiagnostics` shows them for a single buffer.

**Describe the solution you'd like**
Add option to show all diagnostics: `:CocDiagnostics -all`

**Comment by chemzqm** [comment]
No, lsp provide diagnostics for opened buffer only

**Comment by chemzqm** [comment]
You need create coc.nvim extension or write some vim code for that use case

**Comment by brendanator** [comment]
Thanks for the response. What vim variable/function can I use to access the full diagnostic list?

**Comment by chemzqm** [comment]
setqflist

**Comment by ic-768** [comment]
> Thanks for the response. What vim variable/function can I use to access the full diagnostic list?



> Thanks for the response. What vim variable/function can I use to access the full diagnostic list?

Did you ever get this done? I'd like to see project-wide diagnostics as well
