### ISSUE TITLE
Possible to keep CocDiagnostic window in sync with current line of buffer?

### ISSUE THREAD

**Issue by JonDum** [neoclide/coc.nvim#2836]
**Is your feature request related to a problem? Please describe.**

CocDiagnostics does not stay in sync with the buffer. It'd be **_amazing_** if the diagnostics window would highlight the current line that matches with the line of the buffer.

**Describe the solution you'd like**

The `:CocDiagnostic` window stays in sync when you navigate through the buffer, especially when using coc-diagnostic-prev/next.

Here's a quick vid of what I'm talking about. At first I navigate with `:call CocAction('diagnosticNext')` and nothing happens in the diagnostic window. Then I navigate with `<c-w>j j<cr>` which is not as nice as normal navigation methods. It'd be awesome if the yellow highlighted line would change to the line of the issue. 🙏 

https://user-images.githubusercontent.com/191920/105137796-261bcf00-5ab1-11eb-84a3-0e3d96e3c3ff.mov

**Comment by chemzqm** [comment]
`: CocDiagnostic` opens location list of current window, you can use `:lnext` and `:lprevious` to navigate.
