### ISSUE TITLE
Format Deletes Folds

### ISSUE THREAD

**Issue by waldoplus** [neoclide/coc.nvim#2838]
## Describe the bug

I'm not sure if this is an issue with Coc or Coc-RustAnalyzer. The problem is that when I use the command :FORMAT, it deletes all of the folds in my buffer. 

## Reproduce the bug

Create any manual fold. Type :FORMAT

**Comment by GopherJ** [comment]
it's problem if many language servers I think.

**Comment by chemzqm** [comment]
We need connection log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc, save your vimrc and exit vim.
* Restart your vim/neovim to make the issue happen.
* Get the log filepath by :echo $NODE_CLIENT_LOG_FILE
* Attach the log file or paste content from the log.
