### ISSUE TITLE
jumpDefinition's open command has changed

### ISSUE THREAD

**Issue by wookayin** [neoclide/coc.nvim#2839]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-dev+nightly-582-g48caf1df8
node version: v15.6.0
coc.nvim version: 0.0.79-7e550643a5
coc.nvim directory: /Users/wookayin/.dotfiles/vim/plugged/coc.nvim
term: xterm-kitty
platform: darwin

(omitted)
```

## Describe the bug

The behavior of `jumpDefinition` has changed. More specifically, arguments to `openCommand` have changed. I assume this is a bug because it was never documented.

```
:call CocActionAsync('jumpDefinition', ':CustomJump')
```

Previously the command was invoked like `:CustomJump +call cursor(<line>, <col>) <filename>`. Now it only passes <filename>: `:CustomJump <filename>`.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden

  command! -nargs=* CustomJump :call CustomJump("<args>")    
  function! CustomJump(callstr)
    let m = matchlist(a:callstr, '^+call cursor(\(\d\+\),\s*\(\d\+\))\s\+\(.*\)')
    if len(m) < 4
      echohl WarningMsg | echom "ERROR: Invalid callstr format: " . a:callstr | echohl NONE
      return
    endif
    let linenr = m[1]
    let filename = expand(m[3])
    echo printf('%d %s', linenr, filename)
  endfunction
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Open any file with a proper definition provider.

- `:call CocActionAsync('jumpDefinition', ':CustomJump')`

Please Note that previously (before the breaking change) it was working well for me -- https://github.com/wookayin/dotfiles/commit/c64b4f34c1f8051d4e0feb15eb3d4e57d7eab475.

**Comment by wookayin** [comment]
More investigation: This change was introduced in d4e5cd7835 (#2140). So it does not use `+call cursor(...)` any more. Can we expose position information programmatically as well?

**Comment by chemzqm** [comment]
Nope, there's no need to parse cursor for custom command.

**Comment by wookayin** [comment]
Okay, jumping cursors to the definiton location is treated after jumpCommand being invoked. How can I get jump location manually then?

**Comment by chemzqm** [comment]
>  it doesn't move the cursor properly

Why? Can you fix it?

**Comment by chemzqm** [comment]
You can make it always use locations list of coc.nvim if you don't want to jumo.
