### ISSUE TITLE
Using floating window in tmux via ssh causes many dash lines.

### ISSUE THREAD

**Issue by deeperlearner** [neoclide/coc.nvim#2840]
## versions

vim version: VIM - Vi IMproved 8.2 8022054
node version: v10.21.0
coc.nvim version: 0.0.80-50544406f0
coc.nvim directory: /home/peiying/.vim/plugged/coc.nvim                                                                                                                        term: dumb
platform: linux

## Log of coc.nvim

2021-01-23T00:45:11.461 INFO (pid:31073) [plugin] - coc.nvim 0.0.80-50544406f0 initialized with node: v10.21.0 after
2021-01-23T00:45:17.664 INFO (pid:31073) [attach] - receive notification: showInfo []

## Describe the bug

When using floating window in tmux via ssh, there are many dash lines.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=~/.vim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
  inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
  ```
- tmux version: 3.1c

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)
- mini case:
![reproduce](https://user-images.githubusercontent.com/30494216/105520878-31236900-5d16-11eb-8cd6-610f01005f5f.png)
- my case:
![dash](https://user-images.githubusercontent.com/30494216/105520918-3c769480-5d16-11eb-82c7-e5623b15c767.png)

**Comment by deeperlearner** [comment]
When not using tmux or not using ssh, all work fine. Must using tmux and ssh same time cause this issue.

**Comment by GopherJ** [comment]
@deeperlearner I seem not having any issue while using `tmux` and `ssh`

**Comment by deeperlearner** [comment]
I found the reason...
This only happens when using tmux in Windows Bash
