### ISSUE TITLE
Do the helpfiles mention the wrong path to coc-settings.json?

### ISSUE THREAD

**Issue by Melkster** [neoclide/coc.nvim#2841]
[The helpfiles](https://github.com/neoclide/coc.nvim/blob/a9b682ad79cc4b7b836fc7e31f7d01ecd88d7c51/doc/coc.txt#L2185-L2193) mention `.vim/coc-settings.json` as the location for the config file. However, it seems like the actual location is `~/.config/nvim/coc-settings.json`. Is this just a typo in the helpfiles?

**Comment by fannheyward** [comment]
`~/.config/nvim/coc-settings.json` is the global location, `.vim/coc-settings.json` is the project level configuration file.

**Comment by Melkster** [comment]
Ok, but isn't the fact that `:h CocConfig` only mentions `.vim/coc-settings.json`, even though `:CocConfig` brings up `~/.config/nvim/coc-settings.json` misleading?
