### ISSUE TITLE
Some plugin change completeopt on insert mode

### ISSUE THREAD

**Issue by lioaslan** [neoclide/coc.nvim#2843]
### versions

vim version: NVIM v0.4.4
node version: v12.20.1
coc.nvim version: 0.0.80-50544406f0
coc.nvim directory: /home/leo/.config/nvim/bundle/coc.nvim
term: xterm-256color
platform: linux

### Log of coc.nvim

2021-01-24T22:50:34.856 INFO (pid:5644) [plugin] - coc.nvim 0.0.80-50544406f0 initialized with node: v12.20.1 after 667ms
2021-01-24T22:50:38.262 INFO (pid:5644) [attach] - receive notification: showInfo []

## Error screenshot
![image](https://user-images.githubusercontent.com/24852182/105635671-ad44ba80-5e96-11eb-8d65-ca8adb6058ea.png)
### Coc.nvim
Be like [this](https://github.com/neoclide/coc.nvim#example-vim-configuration)
### ALE
```vim
let g:ale_sign_error = '>>'
let g:ale_sign_warning = '--'
let g:ale_linters = {
\   'javascript': ['tsserver'],
\   'typescript': ['tslint'],
\}
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace','prettier'],
\   'python': ['black']
\}
let g:ale_fix_on_save = 0
let g:ale_completion_enabled = 1
let g:ale_linters_explicit = 1
let g:airline#extensions#ale#enabled = 1
nmap <leader>df :ALEGoToDefinition<CR>
let g:ale_disable_lsp = 1
```

**Comment by chemzqm** [comment]
Avoid use different auto completion engine at the same time.
