### ISSUE TITLE
Unable to install "scoped package" with :CocInstall

### ISSUE THREAD

**Issue by yaegassy** [neoclide/coc.nvim#2844]
## Describe the bug

> See [gitter](https://gitter.im/neoclide/coc.nvim?at=600e27438816425540ea7081)

I created a scoped package, coc-extension.

https://www.npmjs.com/package/@yaegassy/coc-intelephense

It was not possible to install with ":CocInstall" (`:CocInstall @yaegassy/coc-intelephense`).

```
Install finished

- ✗ @yaegassy/coc-intelephense Cannot read property 'yaegassy/coc-intelephense' of undefined
```

## Reproduce the bug

`:CocInstall @yaegassy/coc-intelephense`

**Comment by fannheyward** [comment]
- `:CocInstall coc-json`
- `:CocInstall coc-json@1.3.0`
- `:CocInstall https://github.com/hollowtree/vscode-vue-snippets`
- `:CocInstall @yaegassy/coc-intelephense`
- `:CocInstall @yaegassy/coc-intelephense@0.2.1`

**Comment by yaegassy** [comment]
@fanheyward Thanks for the quick fixes and tweaks!

I tried the `fix/scoped-package` branch, It worked fine in my environment.

The support for "scoped package" has been very useful!
