### ISSUE TITLE
Hello! Is it possible to add vim plugin coc-vue or coc-nodejs

### ISSUE THREAD

**Issue by jiclivi** [neoclide/coc.nvim#2855]
Does vim have nodejs vue smart (such as: coc-html) code completion

**Comment by fannheyward** [comment]
Check https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#implemented-coc-extensions

**Comment by jiclivi** [comment]
Thank！
There is coc-vetur for vue, use vetur.
No coc-nodejs

**Comment by jiclivi** [comment]
> 检查https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#implemented-coc-extensions

谢谢！
vue有coc-vetur，请使用vetur。
没有coc-nodejs

**Comment by chemzqm** [comment]
Use coc-tsserver for javascript and typescript support.
