### ISSUE TITLE
Update the documentation for troubleshooting when vim-airline is involved

### ISSUE THREAD

**Issue by comatory** [neoclide/coc.nvim#2856]
**Is your feature request related to a problem? Please describe.**
No not really, just an improvement to documentation. I was trying to figure out why COC was causing nvim to slow over time. Turns out it was `vim-airline` plugin that was causing this. I got tip from someone on Gitter and turns out this plugin is problematic in different ways.

**Describe the solution you'd like**
Create a section in docs with some checklist for debugging bad performance. One of the points in the section would be 

> Do you use `vim-airline`? Have you tried disabling it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chemzqm** [comment]
How does it related to coc.nvim and how to reproduce?

**Comment by comatory** [comment]
I think it's related because of the way I tried debugging my slow performance. If I disabled COC my performance was fine. So initially I thought it's a COC problem but then I got tip to try to disable `vim-airline` and that indeed fixed it.

So that's why I'm suggesting just mentioning this as a _possible_ problem in the documentation. It just seems the interaction between these two plugins is not right.

But I have to admit that this is hard to reproduce, it happens just to some people (I think on Mac OS) and the problem starts manifesting after some time (sometimes minutes, sometimes hours). So reproducing it is not reliable. If you think that this is too vague, please feel free to close the issue.

If people search for the problem online, maybe they will find this issue at least so I'm glad I got it out in the public. Thanks for paying attention to this.

Great job on COC 👍

**Comment by chemzqm** [comment]
It was fixed by vim-airline https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/extensions/hunks.vim#L21, `CocAction` function not called any more.
