### ISSUE TITLE
Open coc-install in tab or hsplit

### ISSUE THREAD

**Issue by Andoku** [neoclide/coc.nvim#2858]
**Is your feature request related to a problem? Please describe.**
I think that opening the process of CocInstall and CocUpdate in vertical split looks kinda off

**Describe the solution you'd like**
It would be nice to have an option to open it in tab or horizontal split. For example VimPlug has similar option "g:plug_window".

**Comment by chemzqm** [comment]
My suggestion is fork the code, PR welcome

**Comment by anjos** [comment]
I was searching for a way to do this like @Andoku mentioned and came about this bug here, that was closed.

Maybe, leaving the bugs opened would give people the opportunity to implement them?  A closed bug looks like the feature or issue has been resolved.
