### ISSUE TITLE
<C-j> become the trigger when setting "coc.preferences.noselect" to true

### ISSUE THREAD

**Issue by JayceCao** [neoclide/coc.nvim#286]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.40
term: iTerm.app
platform: darwin

## Error messages

## Output channel: languageserver.golang
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///Users/jaycecao/go/src/learning") is deprecated. Use rootUri instead.
tmpfriend: Removing /var/folders/95/x36qs0sj433g5d029zjlggqw0000gn/T/tmpfriend-75931-371743358
jsonrpc2 handler: notification "workspace/didChangeConfiguration" handling error: jsonrpc2: code -32601 message: method not supported: workspace/didChangeConfiguration
```

**Describe the bug**
When setting `coc.preferences.noselect` to `false`, `<C-j>` become the completion trigger.

**To Reproduce**

1. set `coc.preferences.noselect` to `false`;
2. restart coc;
3. do any completion operations.

**Screenshots**
![coc-bug](https://user-images.githubusercontent.com/17915615/50216779-a9920000-03c1-11e9-8099-7c958a610e11.gif)

**Comment by chemzqm** [comment]
`<C-j>` would be mapped to jump placeholder when snippet activated, it would do confirm completion  if pumvisible.
So the problem is why snippet activated in your situation or you're using some other plugin which maps `<C-j>` for confirm completion.

**Comment by chemzqm** [comment]
Change `g:UltiSnipsJumpForwardTrigger` to other key, it's expected behavior to confirm before jump placeholder.
