### ISSUE TITLE
Write configuration in lua

### ISSUE THREAD

**Issue by ahmadshiddiq** [neoclide/coc.nvim#2863]
**Is your feature request related to a problem? Please describe.**
I want to configure, but I use Neovim nightly with Lua extension. so I don't how to config coc in Lua, I already tried to convert from vim files into Lua files, but still doesn't work.

**Describe the solution you'd like**
Coc can provide an overview or direction on how to configure the Lua file.

**Additional context**
![image](https://user-images.githubusercontent.com/53107961/106705055-c4667380-661f-11eb-8574-42aa79f0dfc3.png)

**Comment by chemzqm** [comment]
You can call coc#config vim function
