### ISSUE TITLE
Disable/Enable coc sources for specific files

### ISSUE THREAD

**Issue by augustocdias** [neoclide/coc.nvim#2865]
Although the autocomplete shows what is the source of that suggestion I find that having the sources `around`, `file` and `buffer` on my actual code files gets more in my way than helps. But I really like it in text files like for example MD files.

**Describe the solution you'd like**
Would it be good to have a config setting to enable/disable a source based on the extension of the file (or a pattern)

**Describe alternatives you've considered**
I think the `disableSyntaxes` setting could help me achieve what I want, but I found no documentation on what values I could/should fill this setting.

**Comment by fannheyward** [comment]
Check `:h g:coc_sources_disable_map`
