### ISSUE TITLE
rootPatterns are not resolved in order

### ISSUE THREAD

**Issue by iamrecursion** [neoclide/coc.nvim#2868]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.4
node version: v14.4.0
coc.nvim version: 0.0.80-6e5a2aaeb5
coc.nvim directory: /Users/ara/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug

When resolving the workspace root, the CoC documentation states that it will resolve the `rootPatterns` in order. However, they are tested in order for each node in the path, rather than in order for the entire path. This means that it won't resolve to an inner folder if it has a more specific root pattern in it.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

1. Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

2. Add the following lines to your `coc-settings.json`:

```json
    "coc.preferences.rootPatterns": [
        ".projections.json",
        ".git"
    ],
```

3. Create a folder structure as follows:

```
temp
├── .git
└── A
    └── B
        └── C
            └── D
                ├── .projections.json
                ├── E
                │   └── file.py
                └── main.py
```

4. Set your current working directory to `temp/A/B/C/D/E`.
5. Start neovim with the command `nvim -u mini.vim file.py`.
6. The root of the workspace gets resolved to `temp`, where it should instead be resolved to `D`. This is because the settings state that `.projections.json` is more specific than `.git`.

**Comment by iamrecursion** [comment]
It would probably also be useful to have an option to always force root resolution to happen walking bottom-up instead of top-down. This would accomodate situations where you have multiple files that match root patterns, and you want to match the closest one.

**Comment by fannheyward** [comment]
coc already has bottom-up support, checkout https://github.com/neoclide/coc.nvim/pull/2760

```json
"workspace.bottomupfiletypes": [
  "python"
],
```

```
A
├── .git
└── B
    └── C
        └── D
            ├── .projections.json
            ├── E
            │   └── file.py
            └── main.py
```

steps into B/C/D/E, `nvim file.py` and `:echo CocAction('currentWorkspacePath')`.

**Comment by iamrecursion** [comment]
Yes, but that is specific to given file-types and doesn't change the bug.

**Comment by chemzqm** [comment]
You mean priority for rootPatterns array, no such support yet.

**Comment by iamrecursion** [comment]
Yes, priority! That's odd as the documentation implies that such priority exists.

**Comment by chemzqm** [comment]
We won't support priority as items order in `rootPatterns` to avoid unnecessary directory scan, you can use `workspace.bottomUpFiletypes` configuration or start your vim in your workspace folder.

**Comment by iamrecursion** [comment]
Fair enough.
