### ISSUE TITLE
visual bug, cmdheight occupying screen occasionally

### ISSUE THREAD

**Issue by yofriadi** [neoclide/coc.nvim#2869]
### Problem
A visual bug, cmdheight occupying entire screen (leaving 1 height for my cursor) occasionally.
[screenshot](https://imgur.com/jWzhlaY)

### Notes
- I'm using Windows Terminal if this related
- I'm using vim-ctrlspace (I think this is triggered when I switch file in vim-ctrlspace file list)

this is really frustrating me, I have to close all my buffer to regain screen or transferring my buffer to new tab `tabnew`.
I believe this is happen by coc.nvim, because I use other lsp before and this is never happen. and I only change my lsp plugin recently.
any help is appreciated. thankyou.

**Comment by fannheyward** [comment]
Please provide minimal vimrc and steps to reproduce this issue.

**Comment by yofriadi** [comment]
@fannheyward thank you for the response, I will try to reproduce this with minimal vim config. but any guess why this happen?
