### ISSUE TITLE
CocAction with specific action to run shows floating window

### ISSUE THREAD

**Issue by Kavantix** [neoclide/coc.nvim#2871]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.4
node version: v14.15.0
coc.nvim version: 0.0.80-6e5a2aaeb5
coc.nvim directory: redacted
term: iTerm.app
platform: darwin
```

## Describe the bug

The very nice new floating window shows up even when I call `CocAction` with the specific name of a single action.
So now instead of my keybinding executing the action it triggers this window and then does not directly execute the action.

How can I tell the `CocAction` function to not show the floating window?

Example usage:
```vim
function! s:CodeActionFromSelected(type)
  call CocAction('codeAction', a:type, g:nextCodeAction)
endfunction

function! s:RunCodeAction(action)
  let g:nextCodeAction=a:action
  set operatorfunc=s:CodeActionFromSelected
  normal g@iw
endfunction

nnoremap <buffer> <silent> <leader>fww :call <SID>RunCodeAction('Wrap with Container')<cr>viw
```

**Comment by chemzqm** [comment]
> I call CocAction with the specific name of a single action

How?

**Comment by Kavantix** [comment]
I added my example usage. Forgot to do that before sorry :)
