### ISSUE TITLE
Change language mode like in VS code

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [neoclide/coc.nvim#2873]
**Is your feature request related to a problem? Please describe.**
I would like to be able to somehow to enforce certain language onto current buffer like in VS code. Ctrl + Shift + P -> change language mode. Maybe it's already possible, but it's really not easy to find in the docs :(

**Describe the solution you'd like**
Change/Set language engine used for current buffer

**Describe alternatives you've considered**
File extension matching existing language servers

**Comment by chemzqm** [comment]
Learn vim
