### ISSUE TITLE
[coc.nvim]: UnhandledRejection: TypeError: Cannot read property 'fileHash' of undefined 

### ISSUE THREAD

**Issue by shaeinst** [neoclide/coc.nvim#2874]
after installing some coc-plugin, i am getting this error (on bottom) everytime i open file in neovim

**Comment by fannheyward** [comment]
Which extension will cause this error?

**Comment by shaeinst** [comment]
@fannheyward i don't know i intalled many extensions on single command.
```
CocInstall coc-clangd coc-cmake coc-diagnostic coc-emmet coc-go coc-html  coc-java coc-jedi coc-json coc-julia coc-just-complete  coc-python coc-
sh coc-tailwindcss
```

**Comment by fannheyward** [comment]
I think it's caused by `coc-python`, try `CocInstall` without it.
