### ISSUE TITLE
'doHover' action hangs

### ISSUE THREAD

**Issue by osa1** [neoclide/coc.nvim#2875]
### versions

vim version: NVIM v0.5.0-dev+2869-gcc1851c9f
node version: v10.15.1
coc.nvim version: 0.0.80-479a1fcdff
coc.nvim directory: /home/omer/rcbackup/.vim/pack/plugins/start/coc.nvim
term: st-256color
platform: linux

### Log of coc.nvim

2021-02-08T09:39:09.605 INFO (pid:32581) [services] - registered service "languageserver.ocaml-lsp"
2021-02-08T09:39:09.607 INFO (pid:32581) [plugin] - coc.nvim 0.0.80-479a1fcdff initialized with node: v10.15.1 after 31ms
2021-02-08T09:39:10.779 INFO (pid:32581) [attach] - receive notification: showInfo []

## Bug description and repro

In [rustc repo][1] 0b7a598e126 (updated a few minutes ago), using [coc-rust-analyzer][2] 0.31.0 (just updated a few minutes ago with `:CocUpdate`) and [rust-analyzer][3] 984898329 (updated a few minutes ago), if I run `:call CocAction('doHover')` in file `compiler/rustc_parse/src/parser/item.rs:1013:20` (line 1013, column 20), nvim hangs. 

If I do the same in vscode, hover doesn't work (it seems like a problem with rust-analyzer), but at least it doesn't hang and I can continue working.

This is really inconvenient as I have to kill nvim and restart, losing all the buffers, marks etc.

[1]: https://github.com/rust-lang/rust
[2]: https://github.com/fannheyward/coc-rust-analyzer
[3]: https://github.com/rust-analyzer/rust-analyzer

## coc-settings.json

```json
{
    "diagnostic.enable": true,
    "diagnostic.virtualText": false,
    "diagnostic.joinMessageLines": false,
    "diagnostic.checkCurrentLine": true,
    "diagnostic.messageTarget": "float",
    "diagnostic.level": "information",
    "suggest.autoTrigger": "none",
    "signature.enable": true,
    "coc.preferences.snippets.enable": false,
    "coc.preferences.hoverTarget": "float",
    "coc.preferences.colorSupport": true,
    "coc.preferences.bracketEnterImprove": true,
    "coc.preferences.floatActions": false,
    "diagnostic.warningSign": "⚠︎",
    "diagnostic.errorSign": "✗",
    "diagnostic.infoSign": "ℹ︎",
    "diagnostic.hintSign": "ℹ︎",
    "suggest.noselect": false,
    "diagnostic.locationlist": false,
    "rust-analyzer.diagnostics.enable": true,
    "rust-analyzer.inlayHints.enable": true,
    "rust-analyzer.inlayHints.typeHints": true,
    "rust-analyzer.inlayHints.chainingHints": true,
    "rust-analyzer.inlayHints.parameterHints": true,
    "rust-analyzer.serverPath": "/home/omer/.cargo/bin/rust-analyzer",
    "rust-analyzer.checkOnSave.enable": true,
    "rust-analyzer.assist.importMergeBehaviour": "last",
    "rust-analyzer.diagnostics.enableExperimental": true,
    "rust-analyzer.diagnostics.disabled": ["macro-error"],
    "languageserver": {
        "ocaml-lsp": {
            "command": "opam",
            "args": ["config", "exec", "--", "ocamllsp"],
            "filetypes": ["ocaml", "reason"]
        }
    }
}
```

**Comment by fannheyward** [comment]
Try `call CocActionAsync('doHover')`, works fine with rust-analyzer code repo.

**Comment by thijsnado** [comment]
I think this issue is still a problem if you have type issues in your codebase. If you have a mixed javascript/typescript codebase I find doing the `call CocActionAsync('doHover');` will sometimes hang instead of just erroring out gracefully. Can this issue be re-opened?
