### ISSUE TITLE
CocFix does not work with dart analysis server

### ISSUE THREAD

**Issue by Kavantix** [neoclide/coc.nvim#2877]
The dart analysis server returns its quickfix code actions with for example `quickfix.import.library1` but atm coc filters the code actions on `quickfix` only.
I noticed that for the `source` and `refactor` actions it already splits by periods and looks at the first one.
Is there any reason why we should not simply do that for all possible kinds? (Although even for those we should probably first check if we have an exact match)

Causes: iamcco/coc-flutter#57

**Comment by Kavantix** [comment]
Also, as a side question, couldn't we simply do a `startsWith` instead of splitting on the period and taking the first part?
That way you could for instance also get all the import fixes by doing `only: 'quickfix.import'`

**Comment by fannheyward** [comment]
It's expect, CocFix only fetch `CodeActionKind.QuickFix` code actions and apply. You should use `coc-codeaction`.

**Comment by Kavantix** [comment]
@fannheyward yes that's what it does, but like I said in the original comment the quickfix is `quickfix.something` and that should also be seen as a quickfix (basically everything that starts with `quickfix`
This is already done for `source` and `refactor` so why would that not be done for quickfix?

So please reopen this issue

**Comment by fannheyward** [comment]
> 

Because `quickfix.something` is not official LSP CodeActionKind, only `quickfix`. `refactor` and `refactor.extract` are official.

- https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction 
- https://github.com/microsoft/vscode-languageserver-node/blob/b90b25cc4c69824a948af71ec29e1e3c6de019d8/types/src/main.ts#L2742-L2762

**Comment by Kavantix** [comment]
Thanks for the response, I see how you would come to that conclusion.
Firstly, could you please reopen the issue so it reflects that we are currently talking about it.

As for the documentation, if you look at [these](https://github.com/microsoft/vscode-languageserver-node/blob/b90b25cc4c69824a948af71ec29e1e3c6de019d8/types/src/main.ts#L2722-L2729) lines you see that it states the following:

> Kinds are a hierarchical list of identifiers separated by `.`, e.g. `"refactor.extract.function"`

Meaning that *all* kinds are 'a hierarchical list of identifiers separated by `.`', `refactor.extract` just happens to be a pre-determined subgroup of such a list.
So also looking [here](https://github.com/microsoft/vscode-languageserver-node/blob/b90b25cc4c69824a948af71ec29e1e3c6de019d8/types/src/main.ts#L2741-L2744) tells us that `quickfix` is just the base for any quickfix `CodeActionKind` hierarchical list and thus `quickfix.something` is actually 'official' in that sense

**Comment by fannheyward** [comment]
Defined custom command `CocXYZFix` to `CodeAction quickfix.something`, `CocFix` is just a shortcut for `CodeAction quickfix`.

The problem is Dart defined codeAction with kind = quickfix.xyz according to their needs, coc as a client doesn't know what's the kind, so coc fetches the following kinds defined in vscode-languageserver-types:

```
CodeActionKind.Empty,
CodeActionKind.QuickFix,
CodeActionKind.Refactor,
CodeActionKind.RefactorExtract,
CodeActionKind.RefactorInline,
CodeActionKind.RefactorRewrite,
CodeActionKind.Source,
CodeActionKind.SourceOrganizeImports
```

**Comment by iamcco** [comment]
> 	 * Base kind for quickfix actions: 'quickfix'

Since `CodeActionKind.QuickFix` is base kind of quickfix action, I think it will make more sense to get all quickfix actions start with `quickfix` for the user when using `CocFix`.
