### ISSUE TITLE
BracketEnterImprove seem coupled to the original author's `indent` configuration

### ISSUE THREAD

**Issue by lanza** [neoclide/coc.nvim#2880]
(using `␣` to denote a space throughout)

Given `bracketEnterImprove` enabled, `cindent` enabled and `cinoption` set to `:0,g0,(0,Ws,l1,N-s`, `softtabstop` set to 2, and `test.c` containing

```
int main(|)
```

(where the `|` denotes the cursor) pressing enter inserts too many spaces. You end up with

```
int main(
␣␣␣␣|
␣␣)
```

The line with the cursor has 4 spaces and the line with the close paren has 2 spaces. This should be 2 and 2, respectively. This is defined by my the `cinoptions` listed in combination with the defaults.

You can observe this via replicating [this diff](https://github.com/lanza/coc.nvim/commit/a7c4bf06cdee9a82ec3299a97cd8859849560e8e). Pressing `enter` causes coc.nvim to print (ignoring the `|| ` at the start of every `echom`)

```
␣␣ )
␣␣
␣␣
␣␣␣␣
```

So coc.nvim's simple calculation here is taking the state of the current line which is already automatically indented via vim's indentation system and then modifying it by always appending the user's preferred spacing to this line and the next. 

I'm guessing you designed this system based on what vim was doing on your current vim setup and thus didn't take into account configurable indentation in vim. e.g. your `autoindent`, `smartindent`, `cident` or `indentexpr` configuration. So if any user has different setup it yields awkward indentation behaviors.

I think you should reimplement the `bracketEnterImprove` code via just asking vim. You can query vim for it's configured indentation via (if you have `cindent` enabled) `echo cindent(line('.'))`. 

If you have vim's indentation system correctly configured towards your preference then the only thing that doesn't happen that `bracketEnterImprove` would need to do would be to move the close paren to the following line. Vim will do this for you

```
int main(
␣␣|)
```

BracketEnterImprove current inserts `let newText = '\n' + currIndent + space`. This would just need changed to a two step process. `cindent(line('.'))` will have different answers for a line that contains a `)` and a line in between. So it would need to be something like:

```
let newLine = '\n';
let pos: Position = Position.create(line -1, pre.length);
edits.push({ range: Range.create(pos, pos), newLine })
let newText = ' '.repeat(nvim.command("cindent(line(${line}))")
edits.push({ range: Range.create(pos, pos), newText })
```

or something like this. Sorry I don't know TypeScript or this API.

```
let nextLine = ' '.repeat(nvim.command("cindent(line('.'))")) + ')';
```

**Comment by chemzqm** [comment]
The indent is created by vim now.
