### ISSUE TITLE
Error on initialize with Neovim 0.5.0~dev build

### ISSUE THREAD

**Issue by dietrichm** [neoclide/coc.nvim#2881]
## Result from CocInfo

_No output is returned from CocInfo! I started from a working nvim build and adapted the nvim version for the broken one:_

vim version: NVIM 0.5.0~dev.1083.g1aec5ba85
node version: v14.15.5
coc.nvim version: 0.0.80-479a1fcdff
coc.nvim directory: /home/dietrich/repos/dotfiles/nvim/plugged/coc.nvim
term: tmux-256color
platform: linux

## Describe the bug

coc.nvim failed to initialize with the following error:

```
[coc.nvim]: Error on initialize: Error
    at NeovimClient.request (/home/dietrich/repos/dotfiles/nvim/plugged/coc.nvim/build/index.js:10572:19)
    at NeovimClient.call (/home/dietrich/repos/dotfiles/nvim/plugged/coc.nvim/build/index.js:11709:19)
    at Workspace.init (/home/dietrich/repos/dotfiles/nvim/plugged/coc.nvim/build/index.js:43050:28)
    at Plugin.init (/home/dietrich/repos/dotfiles/nvim/plugged/coc.nvim/build/index.js:65475:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/dietrich/repos/dotfiles/nvim/plugged/coc.nvim/build/index.js:36142:9
```

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Install Neovim 0.5.0 build from [agriffis/neovim-nightly COPR repo](https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/) on Fedora. I tested with a build having version number **0.5.0~dev.1083.g1aec5ba85**.

- Start Neovim with command: `nvim -u mini.vim`

- Notice the above error being displayed. `:CocInfo` has no effect.

I suspect the changed version number format is the cause of the failure. Testing with NVIM v0.5.0-dev works correctly.

**Comment by dietrichm** [comment]
I tracked the issue down to the version format. Running `:call coc#util#vim_info()`:

```
Error detected while processing function coc#util#vim_info[1]..coc#util#version:                                                                        
line    6:
E684: list index out of range: 0
E15: Invalid expression: lines[0]
```

**Comment by agriffis** [comment]
This was a mistake in the nightly build of neovim for Fedora, now fixed. See https://github.com/agriffis/neovim/issues/5#issuecomment-777467406

**Comment by dietrichm** [comment]
Tested again with a new build, and can confirm this is now fixed. Thanks!

Closing the issue.
