### ISSUE TITLE
Backspace in insert mode block text UI when a large file is open in buffer

### ISSUE THREAD

**Issue by eggeek** [neoclide/coc.nvim#2882]
## versions

vim version: NVIM v0.5.0-dev+1083-g1aec5ba85
node version: v15.8.0
coc.nvim version: 0.0.80-6e5a2aaeb5
coc.nvim directory: /home/eggeek/.local/share/nvim/plugged/coc.nvim
term: alacritty
platform: linux

## Log of coc.nvim

2021-02-12T13:48:26.926 INFO (pid:54542) [coc-git] - Looking for git in: git
2021-02-12T13:48:26.950 INFO (pid:54542) [plugin] - coc.nvim 0.0.80-6e5a2aaeb5 initialized with node: v15.8.0 after 86ms
2021-02-12T13:48:30.200 INFO (pid:54542) [attach] - receive notification: showInfo []

## Describe the bug

Text UI becomes laggy when deleting characters in insert mode with a large buffer open.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.
1. open `test.md` (or any other file), add and delete characters - it will work as normal
2.  create a file with 50000 lines
```python
with open("test.in", "w") as f:
        f.write('\n'.join([str(i) for i in range(50000)]))
```
3. open  `test.in` (or another large file);
4. go back to the `test.md` and to insert mode;
5. adding characters seems fine, but deleting characters is laggy, the corresponding log is
`receive request: doKeymap [ 'iPGJzPg==0' ]`

## Screenshots (optional)

[![asciicast](https://asciinema.org/a/vnVaasJIBbAZwq0zVffkLWqJX.svg)](https://asciinema.org/a/vnVaasJIBbAZwq0zVffkLWqJX)

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-could-i-profile-vim
