### ISSUE TITLE
Unset hidden by default

### ISSUE THREAD

**Issue by kaldown** [neoclide/coc.nvim#2883]
```
" TextEdit might fail if hidden is not set.
set hidden
```
Is it possible to fix such behavior?
I prefer working with `hidden` unset.
It's actually confuses me, why plugin wants me to change my workflow

**Comment by chemzqm** [comment]
It's suggestion.

**Comment by kaldown** [comment]
what do you mean?
It suggest me no to tolerate TextEdit failure?

It's clearly a bug since there is `fail` word.
And setting a flag which is presumably related to the core of the failure - is not a corresponding fix.

Any way I can deal with `TextEdit` failure other that setting this flag?

**Comment by kaldown** [comment]
@chemzqm please, re-open this issue.
In case someone will have the same question.
