### ISSUE TITLE
Option to disable coc-list custom statusline or integrate vim airline

### ISSUE THREAD

**Issue by BonaBeavis** [neoclide/coc.nvim#2885]
**Is your feature request related to a problem? Please describe.**
https://github.com/vim-airline/vim-airline/issues/2242

**Describe the solution you'd like**
Either option to disable custom statusline: https://github.com/vim-airline/vim-airline/issues/2242#issuecomment-777202976, or integrate with airline.

**Comment by chemzqm** [comment]
Yes, there's is a configuration for that

**Comment by BonaBeavis** [comment]
Thanks! I found it:
Add
```
  "list.statusLineSegments": null,
```
to CocConfig
