### ISSUE TITLE
[coc.nvim] Error on notification "jumpDefinition": definition provider not found for current buffer, your language server don't support it.

### ISSUE THREAD

**Issue by Folaht** [neoclide/coc.nvim#2886]
## versions
                                                                                             
  vim version: NVIM v0.4.4   
  node version: v15.8.0                                                                      
  coc.nvim version: 0.0.80-6e5a2aaeb5                                                        
  coc.nvim directory: /home/folaht/.vim/plugged/coc.nvim
  term: xterm-256color
  platform: linux
                                                                                             
  ## Log of coc.nvim
      
  2021-02-12T15:09:28.482 INFO (pid:53380) [plugin] - coc.nvim 0.0.80-6e5a2aaeb5 initialized with node: v15.8.0 after 72ms
  2021-02-12T15:09:28.783 INFO (pid:53380) [attach] - receive notification: highlight []
  2021-02-12T15:09:33.436 INFO (pid:53380) [attach] - receive notification: highlight []
  2021-02-12T15:09:39.321 INFO (pid:53380) [attach] - receive notification: jumpDefinition []
  2021-02-12T15:09:39.328 ERROR (pid:53380) [attach] - Notification error: jumpDefinition [] Error: definition provider not found for current buffer, your language server don't support
      at FP.checkProvier (/home/folaht/.vim/plugged/coc.nvim/build/index.js:252:1049)
      at FP.gotoDefinition (/home/folaht/.vim/plugged/coc.nvim/build/index.js:252:3777)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at async OP.cocAction (/home/folaht/.vim/plugged/coc.nvim/build/index.js:254:6350)     
      at async eM.<anonymous> (/home/folaht/.vim/plugged/coc.nvim/build/index.js:129:12564)
  2021-02-12T15:09:39.630 INFO (pid:53380) [attach] - receive notification: highlight []
  2021-02-12T15:09:43.441 INFO (pid:53380) [attach] - receive notification: showInfo []

## Describe the bug

No jump -definition, -implementation, -typedefinition or 
for any language server.

## Reproduce the bug

.vimrc
```
 call plug#begin()
  
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'neoclide/coc-rls'
  Plug 'fannheyward/coc-pyright'

  call plug#end()
```

init.nvim
```
  set runtimepath^=~/.vim runtimepath+=~/.vim/after
  let &packpath = &runtimepath
  source ~/.vimrc
  source ~/.config/nvim/plug-config/coc.vim
```

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by rerrabolu** [comment]
I am getting this error when trying to look for a struct definition in C file. Anything I should install for coc in addition to coc-clangd

**Comment by CharlieCheckpt** [comment]
Hi, same problem for me, I can't go to definition in a .py file even though I have `coc` and `coc-pyright` installed.

I have the same log than the author, that is : 

```
receive notification: jumpDefinition []
```

Any idea what could be causing this ?

**Comment by rerrabolu** [comment]
I am rather new to vim/neovim plugins and the whole body of commands and options. After spending sometime I found the following helped me i.e. my ability to peek at definitions works. For this I did the following things that are relevant:

1. Load the plugin from semanticart
    " Plugin to peek at definitions of symbols
    Plug 'semanticart/tag-peek.vim'
2. Map/Bind a key to encode a leader
    " Define the key to encode leader
    let mapleader = ','
3. Map/Bind a key to invoke peek function from the plugin
    " Show definition when using ,p key
    nnoremap <leader>p :call tag_peek#ShowTag()<CR>
4. Load ctags for the body of code you wish to browse
    e.g. set tags=/home/.../ctags
5. To peek at the definition of a symbol simple enter <leader><BoundKey>
    In my case I mapped "p" as the key to peek
    ,p   will open a floating window showing the definition

My work involves C/C++ language, so I ran CocInstall coc-clangd. Once I execute step 5, I am able to go to a symbol and enter in command mode ",p" the key sequence I defined to invoke the definition .

I have not mastered the topic and probably not using the plugins to the fullest. I wish somebody provided a commercial solution to make things work out of the box.

**Comment by suvasanket** [comment]
please can anyone please what to do in init.lua

**Comment by curkan** [comment]
> please can anyone please what to do in init.lua

Have you solved this problem somehow?

**Comment by noaonoszko** [comment]
I solved this by running `:CocInstall coc-pyright`, maybe this helps someone.

**Comment by Lucfer666** [comment]
I fix this error updating nvim to 0.7 version 
and using this command in init.vim
    :CocInstall coc-json coc-tsserver

**Comment by zhehaoli1999** [comment]
For C++, I use `CocInstall coc-clangd`, if you don's have clangd installed, coc will show you that you can use "CocCommand clangd.install" to install it.

**Comment by roshanlimbu** [comment]
You need to add language server in coc-settings.json file to use the feature like jump to definition.

**Comment by Fuyubai** [comment]
I solved this by running :CocInstall coc-python, maybe this helps someone.

**Comment by jacobitosuperstar** [comment]
> I solved this by running
> 
> > :CocInstall coc-python
> 
> maybe this helps someone.

yeah, I don't know why the configuration stops working from time to time.
