### ISSUE TITLE
No codelens retry after failing

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2887]
## Result from CocInfo

![image](https://user-images.githubusercontent.com/33961674/103678791-495c5f80-4f84-11eb-8b6d-73130c27e571.png)

## Describe the bug

rust-analyzer takes quite a lot time to do indexing, if coc.nvim requests codelens before the end of indexing, RA returns back `-32801` error code. However, currently there is no way to re-fetch codelens, I tried to switch between buffer and using `:e` to load the file but none of them really works.

This makes it hard to debug code in coc-rust-analyzer and makes coc-rust-analyzer's vimspector debug feature unusable.

![Peek 2021-01-05 15-18](https://user-images.githubusercontent.com/33961674/103657332-1016f600-4f6a-11eb-8dd1-13ee1bb77d2f.gif)

This also makes it hard to run unit tests.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by GopherJ** [comment]
See also: https://github.com/fannheyward/coc-rust-analyzer/issues/562

it needs to note this happens frequently on big project, you may not be able to reproduce in small project

**Comment by fannheyward** [comment]
coc will force fetch codeLens on `CursorHold` https://github.com/neoclide/coc.nvim/commit/065a70c58c3ee3648ca8972ddcdce7cc7807fb1b

**Comment by GopherJ** [comment]
@fannheyward In practice I didn't see how it refresh codelens actually, when it fails, let's say in `main.rs`, it never fetched again.

**Comment by GopherJ** [comment]
hi @chemzqm thanks for this PR, after this PR I can see:

![image](https://user-images.githubusercontent.com/33961674/109000626-e9aa4700-76de-11eb-9872-4aa2604327a1.png)

for most of the time, even it wasn't there I can move my cursor to have it, but I think there is still one thing left:

![image](https://user-images.githubusercontent.com/33961674/109000728-0d6d8d00-76df-11eb-8357-3fd4af30feef.png)

as you can see I still dont have codelens. I can always reproduce this using a medium size project

**Comment by GopherJ** [comment]
Also if I add a new test item in code, it didn't refresh. I have to use `:e src/main.rs`

![Peek 2021-02-24 20-40](https://user-images.githubusercontent.com/33961674/109002001-9a651600-76e0-11eb-96c2-7bf4ed025800.gif)

**Comment by GopherJ** [comment]
@chemzqm @fannheyward Hi, sorry to disturb you again, do you have an idea of this problem?
