### ISSUE TITLE
eat next empty parenthesis while applying completion item

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2889]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I change a function name and hit enter, there will be two parenthesis like `()()`.

![Peek 2021-02-14 00-24](https://user-images.githubusercontent.com/33961674/107855060-26627c80-6e5b-11eb-95f6-5076d9176ddb.gif)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
No, avoid confirm completion for that case.
