### ISSUE TITLE
Can't Update Coc-nvim

### ISSUE THREAD

**Issue by MrNilDev** [neoclide/coc.nvim#2891]
I'm trying to Update Coc.nvim with vim-plug, but it seems it doesn't do anything. my currently version is 0.0.79 but the latest is
0.0.80, I'm trying to update with `PlugUpdate`

**Comment by GopherJ** [comment]
@MrNilDev  You should use `PlugUpdate` instead of `CocUpdate`

**Comment by MrNilDev** [comment]
wdym?? I did `PlugUpdate`

**Comment by GopherJ** [comment]
@MrNilDev pls provide at least some info so that the others can help you. It's not reproducible on my side. Pls try upgrade vim-plug and use minimal vimrc

**Comment by MrNilDev** [comment]
I tried updating vim-plug

**Comment by MrNilDev** [comment]
and minimal init.vim: 
```vim
call plug#begin('~/.config/nvim/plugins')
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}} " install CocCommand coc-json ..... Also install `sudo pip3 install jedi` or try 
call plug#end()
```

**Comment by fannheyward** [comment]
RTFM

```

" Use release branch (recommend)
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Or build from source code by using yarn: https://yarnpkg.com
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
```

**Comment by zmaupin** [comment]
@ItsNilDev I experienced the same problem. No amount of `:PlugUpdate` or other upgrade methods I tried would work to upgrade coc.nvim. I was using the release branch today, January 31, 2022, yet was unable to upgrade past v0.0.78, the version released in April 2020. So I hope no one else wastes their time trying to build from master. It won't help you here.

The problem isn't with coc.nvim. It's likely that you have multiple vim plugin managers. I had an old config for my docker images that I brought into my workstation. It used a different plugin manager for vim that I configured and it included coc.nvim. They collided until I removed one of them. Now it works fine for me. 

If what I said above does not help then try to run vim with the -V flag to generate a log file at the location you started vim.  Add a number to change the level of verbosity.

`vim -V1logfile`

You can look through this to see if there are any lines that call out an error.

**Comment by ItsNilDev** [comment]
@zmaupin Thanks man.
