### ISSUE TITLE
Unexpect input in the coc-list-location window

### ISSUE THREAD

**Issue by stark-zhang** [neoclide/coc.nvim#2892]
Pressing `j` twice quickly will be recognized as `ESC` twice in `coc-list-location` window after `: call CocActionAsync('jumpReferences')` when viewing a C source file.

Tested on vim `8.2.2489` and `8.2.2516`, on Linux Manjaro 21-pre1, bash and no GUI. And the coc.nvim is the latest release.

minimal vimrc and reproduce steps can be found in [Issue #7844 of vim](https://github.com/vim/vim/issues/7844).

Any Suggestions？

**Comment by fannheyward** [comment]
Check `:verbose imap jj`.

**Comment by stark-zhang** [comment]
Nothing found no matter using the minimal vimrc or normal vimrc. 

And nothing got when I tried to check all `map` commands. I think that mapping `hjkl` to `ESC` is not logical and I never do this.

The default mode is normal in `jumpReferences`, and why to check `imap`?

**Comment by chemzqm** [comment]
Should be your system or terminal issue, can't reproduce.
