### ISSUE TITLE
Any way to treat "-" connected word as a single word

### ISSUE THREAD

**Issue by fecet** [neoclide/coc.nvim#2894]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I need to write some word like hello-world, is there any way to let coc.nvim treat it as a word so I can complete it when I type "hello"

**Comment by yaegassy** [comment]
@fecet 

In the coc.nvim configuration, you can set `b:coc_additional_keywords`. 

help: `:h coc_additional_keywords`

**Example:**

```
" Add keyword characters for html
autocmd FileType html let b:coc_additional_keywords = ["-"]
```

At the Vim level, you can use `iskeyword` to set it. 

help: `:h iskeyword`

**Example:**

```
" Add keyword characters for html
autocmd Filetype html setlocal iskeyword+=-
```

Check each help file and try to add the settings to `.vimrc or init.vim`.
