### ISSUE TITLE
coc triggers autosaving of startify-sessions

### ISSUE THREAD

**Issue by divramod** [neoclide/coc.nvim#2897]
hey,

i really like coc and vim sessions.
recently i wanted to switch to not autosaving my sessions because i want to use the same sessions locally and remote. (i sync them via a git repo and when they change, i always get into problems)
i then realized, that my sessions are autosaved, when the coc-plugin is enabled (i tried a lot until i found out).
i already tried to disable all coc-configurations i set but every time i do ```:qa``` or ```:wqa``` my session is autosaved.

does anybody has similar problems or can give me a hint what might trigger the autosave of my sessions when using coc?

thx for the great plugin and in advance for a hint pointing me in the right direction.

**Comment by fannheyward** [comment]
You're using `coc-lists`, which will auto save vim session, you can disable it by `session.saveOnVimLeave`, https://github.com/neoclide/coc-lists#options

**Comment by divramod** [comment]
thx!
