### ISSUE TITLE
CocAction('format') freezes nvim

### ISSUE THREAD

**Issue by simonmclean** [neoclide/coc.nvim#2899]
I encountered this issue when working with `.scala` files.

I originally assumed the bug was with the `coc-metals` extension, so I opened an issue describing the problem [here](https://github.com/scalameta/coc-metals/issues/383).

But one of the maintainers believes that the issue is upstream with coc itself. See their reply [here](https://github.com/scalameta/coc-metals/issues/383#issuecomment-781522102).

**Comment by fannheyward** [comment]
Does `CocActionAsync('format')` work?

**Comment by simonmclean** [comment]
That's works apparently. Thanks!

**Comment by arbitrary-dev** [comment]
>Does `CocActionAsync('format')` work?

Would be nice if "Example vim configuration" be updated as well @chemzqm 

But the actual problem seems to be that `CocAction('format')` hangs on a prompt issued by the action.

In my case it was:
>No Scalafmt version is configured for this workspace, what version would you like to use?: 3.0.5

**Comment by chemzqm** [comment]
> > Does `CocActionAsync('format')` work?
> 
> Would be nice if "Example vim configuration" be updated as well @chemzqm

Done.
