### ISSUE TITLE
Is Pyls broken currently?

### ISSUE THREAD

**Issue by r-learner** [neoclide/coc.nvim#29]
I just updated coc.nvim to the lastest release and it seems pyls does not work (no code completion and linting anymore), it worked previously (last Sunday), I am curious whether extra setting has to be set.

**To Reproduce**
1. The bare init.vim,
```
call plug#begin('~/.config/nvim/plugged')
	Plug 'neoclide/coc.nvim', {'do': 'yarn install'}
call plug#end()
let g:coc_force_debug = 1
```
2. the bare python file to be tested.
```
import sys

prin('coc.nvim')
```
It seems pyls is not started (I have pyls installed previously via `pip3 install -U --user 'python-language-server[all]`), because there is no such a message `[coc.nvim] service pyls started!` or other error messages displayed during opening a python file. For a javascript file, there is an error message `[coc.nvim] ESLint: Cannot read property 'CLIEngine' of undefined.`

By the way, what would be the quick way to diagnose the issue?

**Comment by rendom** [comment]
Since friday php language server (Registered as custom server) stopped to work after an update to coc.nvim. Not sure if its related.

**Comment by rendom** [comment]
Found my issue with php, it seems as commands never gets resolved. 
https://github.com/neoclide/coc.nvim/blob/master/src/language-client/index.ts#L67

Fix:
```
55:  command = resolved
67: // if (!module) return
```

**Comment by chemzqm** [comment]
Thanks for reporting, I would setup some basic test to prevent this kind of bug from happening.
