### ISSUE TITLE
Need floating window scrolling function for insert mode 

### ISSUE THREAD

**Issue by you-n-g** [neoclide/coc.nvim#2902]
I want to scroll flaoting window in insert mode.

[This solution](https://github.com/neoclide/coc.nvim/issues/1405#issuecomment-626998607) works before.

But it doesn't work on the latest release branch.

I'm on  `origin/release` branch.
It seems that the `coc#util#get_float()` is lost.
`coc#float#get_float_win()`  looks provdes similar function. But it doesn't work when I replace `get_float`  with it 
![image](https://user-images.githubusercontent.com/465606/108586634-c1db7c00-738a-11eb-9087-64574b5f3904.png)

Besides, I can't find the float_scroll_i function [which is merged before](https://github.com/neoclide/coc.nvim/pull/2425)

Thanks for your help in advance.

**Comment by fannheyward** [comment]
Check `:h coc#float#has_scroll()`.

**Comment by you-n-g** [comment]
Thanks so much!!  It works @fannheyward
