### ISSUE TITLE
README file says to use coc-python which is not maintained

### ISSUE THREAD

**Issue by metal3d** [neoclide/coc.nvim#2904]
In https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#install-extensions-for-programming-languages-you-use-daily you say to use coc-python

But: https://github.com/neoclide/coc-python => the repository is archived and it's recommanded to use coc-pyright or coc-jedi.

Regards,

PS: coc is very cool :)

**Comment by chemzqm** [comment]
Fixed
