### ISSUE TITLE
Trigger behavior for different sources

### ISSUE THREAD

**Issue by wkcosmology** [neoclide/coc.nvim#2907]
**Is your feature request related to a problem? Please describe.**
There are three kinds of trigger behaviors: _'always'_, _'trigger'_, _'none'_.
Also, there could several sources, like _lsp_, _around_, _buffer_ etc.

So I wander if we could config different trigger behaviors for different sources.
For example,
When I am programming in C/C++, I want to _'always'_ trigger _around_ and _buffer_ sources.
But I want to _'trigger'_ _lsp_ completion though trigger characters or key-mapping.

**Describe the solution you'd like**
I'd like to have a config option like
 let g:coc_trigger_map = {
             \ 'cpp': { 'always': ['around', 'buffer'], 'trigger': ['clangd-1']},
             \ 'python': { 'always': ['around', 'buffer', 'jedi-1']
}

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by chemzqm** [comment]
No, that's bad experience.
