### ISSUE TITLE
coc nvim not close floating windows

### ISSUE THREAD

**Issue by NSLog0** [neoclide/coc.nvim#2910]
![Screen Shot 2564-02-23 at 16 15 40](https://user-images.githubusercontent.com/1640817/108823304-d1f59480-75f2-11eb-9f98-1f88355c1ad3.png)

as you see on the image there's still have a floating window on the screen and I have to close by using `<C-w> o` every time. 

it just happens from the last time I update coc which is 2 days ago

**Comment by chemzqm** [comment]
Try minimal vimrc.
