### ISSUE TITLE
codeAction at current position

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#2913]
@chemzqm I think this is still an open problem in CoC. (Note that I'm not a CoC user, but a rust-analyzer maintainer.) I think providing special commands for running code action on the whole buffer or the current line doesn't make sense; and on the other hand, it seems there is no way of running code actions with an empty range?

My impression is that there's a different interpretation of what the range in the code action request means at play here. Getting code actions with a certain range is not the same thing as getting all possible code actions for that range (/ that can affect that range). At least rust-analyzer does not interpret it that way, and instead chooses to use the range basically as an input to the code actions (so we'll return actions that will do something with the given range, e.g. extract it to a new variable). I think the spec is unclear on this, but VSCode uses it that way (sending the current selection as the range, or an empty range if there's no selection), and Emacs does the same. rust-analyzer will send lots of code actions if you provide it an empty range at a certain point.

_Originally posted by @flodiebold in https://github.com/neoclide/coc.nvim/issues/1981#issuecomment-783350621_

**Comment by fannheyward** [comment]
@chemzqm in my tests, rust-analyzer returns different code actions for `coc-codeaction-selected` with one character and current position with no character select.

**Comment by fannheyward** [comment]
maybe something like `coc-codeaction-position`?

**Comment by chemzqm** [comment]
I would prefer `<Plug>(coc-codeaction-cursor)`

**Comment by flodiebold** [comment]
Making it possible to get code actions at a position is one thing, but I also think the "code actions for line/file" commands should be rethought. They're just very unlikely to be useful, and IMO only serve to confuse users.

**Comment by chemzqm** [comment]
> Making it possible to get code actions at a position is one thing, but I also think the "code actions for line/file" commands should be rethought. They're just very unlikely to be useful, and IMO only serve to confuse users.

They're useful, some language server need that range.

**Comment by flodiebold** [comment]
Considering VSCode's behavior, that's surprising to me, but OK.
