### ISSUE TITLE
COC breaks custom snippets from ultisnips

### ISSUE THREAD

**Issue by GiancarloAparicio** [neoclide/coc.nvim#2916]
## Description

With Ultisnips you can create different types of snippets, but when using coc autocomplete it seems to fail and does not interpret it correctly, instead prepending '\ u' in these snippets instead of capitalizing the first letter.
(If coc autocompletion is not used, the snippet works fine)

## Reproduce the bug

Snippets

```snippet
snippet title1 "Titelize in the Transformation"
${1:text}
${1/\w+\s*/\u$0/g}
endsnippet

snippet title2 "Titelize in the Transformation"
$1
${1/\w+/\u$0/g}
endsnippet

snippet title3 "Titelize in the Transformation"
${1:text}
`!p snip.rv = t[1].title()`
endsnippet
```

**Expected behavior:**
![imagen](https://i.stack.imgur.com/3JjKa.gif)

**Actual behavior:**

![imagen](https://user-images.githubusercontent.com/61440825/108940846-1187a500-7622-11eb-8156-d7c322a2b1b5.png)

![imagen](https://user-images.githubusercontent.com/61440825/108940977-4267da00-7622-11eb-9864-2ba92323d65d.png)

**Comment by chemzqm** [comment]
Limitation of coc-snippets, mentioned in readme.
