### ISSUE TITLE
How do I get a problems list like in VSCode?

### ISSUE THREAD

**Issue by yepitschunked** [neoclide/coc.nvim#2917]
I can't seem to replicate the VSCode problems list using coc. Wondering if it's possible.

Things I've tried:

1. `:CocDiagnostics`: Only works for current buffer, not all opened buffers
2.`:CocList diagnostics`: This opens a list, but it seems like it's not meant to stay open. The list doesn't update, you have to run it again to capture any changes. 
3. `tsserver.watchBuild`: This is close, we can build the whole project and use quickfix. But I work on a big repo and this is slow. Also, does this result in duplicate work? We'll have both the regular tsserver used as a language server, as well as tsc running in watch mode? 
4. Use `ale` for diagnostics. This seems to work the best, but requires a separate plugin. 

Any other way to have a list of all diagnostics that stays open and updates automatically?

**Comment by chemzqm** [comment]
Use CocList diagnostics

**Comment by vjsingh** [comment]
Seems related to this one: https://github.com/neoclide/coc.nvim/issues/2734

**Comment by harjotgill** [comment]
Try - ```  autocmd BufEnter,BufWritePost,FileAppendPost,FileWritePost * call timer_start(1000, { tid -> execute('execute "CocDiagnostics" | execute "botright lwindow" | execute "wincmd p"') })```

**Comment by chemzqm** [comment]
Auto refresh feature already added to CocList diagnostics

**Comment by harjotgill** [comment]
> Auto refresh feature already added to CocList diagnostics

I am seeing an issue with that feature -- it's ignoring the level filters on auto-refresh.

**Comment by harjotgill** [comment]
> Auto refresh feature already added to CocList diagnostics

Unable to add a filter to `CocList diagnostic` -- unless I missed some config option somewhere...

**Comment by chemzqm** [comment]
Yes, you can't, don't think it's necessary since they've been sorted by diagnostic level.
