### ISSUE TITLE
Try CocRename, then CocCommand document.renameCurrentWord

### ISSUE THREAD

**Issue by hejops** [neoclide/coc.nvim#2918]
**Is your feature request related to a problem? Please describe.**
I mostly write in python and bash. The former has a rename provider, and the latter doesn't (from what I've gathered), so I have set two separate keybinds for the aforementioned commands.

**Describe the solution you'd like**
`CocRename` can fallback to `CocCommand document.renameCurrentWord` if no rename provider is available.

**Describe alternatives you've considered**
`nnoremap [binding] [condition: if language has rename provider] ? '<Plug>(coc-rename)' : ':CocCommand document.renameCurrentWord'`
This should be a decent hacky workaround; I'm just not sure what the condition should be (if there is one).

**Comment by fannheyward** [comment]
`:CocCommand document.renameCurrentWord` will check rename provider first, if provider is not found, coc will get word symbol from current buffer. So you can use `:CocCommand document.renameCurrentWord` directly.

**Comment by chemzqm** [comment]
`:h CocHasProvider()`
