### ISSUE TITLE
Unicode not working

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#292]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

```
## versions

vim version: NVIM v0.3.1
node version: v11.5.0
coc.nvim version: 0.0.40
term: tmux-256color
platform: linux

## Error messages

## Output channel: prettier
```

**Describe the bug**

coc.nvim isn't providing completion for any word containing non latin characters. YouCompleteMe supports this for example (another completely different protocol, but as far as I see, there's LSP support for Unicode).

**To Reproduce**

1. Open a empty `file.txt` and paste the words black-coffe and black-кофе
2. Write `bl`
3. ![39mqmkg](https://user-images.githubusercontent.com/1269815/50318483-9443d100-04a8-11e9-9966-59c282bf012d.png)

**Comment by chemzqm** [comment]
Coc use your `iskeyword` option to extract words.

**Comment by oblitum** [comment]
@chemzqm rules over `iskeyword` are relaxed for multi-byte characters:

```
	Multi-byte characters 256 and above are always included, only the
	characters up to 255 are specified with this option.
```

source: http://vimdoc.sourceforge.net/htmldoc/options.html#'isfname'

[`iskeyword`](http://vimdoc.sourceforge.net/htmldoc/options.html#'iskeyword') refers to `isfname`, they share the same rules, which brings the case of filename completion, another thing pretty common to have Unicode.
