### ISSUE TITLE
no textDocument/codeLens retry after failling

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#2923]
## Result from CocInfo

![image](https://user-images.githubusercontent.com/33961674/103678791-495c5f80-4f84-11eb-8b6d-73130c27e571.png)

## Describe the bug

rust-analyzer takes quite a lot time to do indexing, if coc.nvim requests codelens before the end of indexing, RA returns back `-32801` error code. However, currently there is no way to re-fetch codelens, I tried to switch between buffer and using `:e` to load the file but none of them really worked.

This makes it hard to debug code in coc-rust-analyzer and makes coc-rust-analyzer's vimspector debug feature unusable. This also makes it hard to run unit tests.

![Peek 2021-01-05 15-18](https://user-images.githubusercontent.com/33961674/103657332-1016f600-4f6a-11eb-8dd1-13ee1bb77d2f.gif)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- git clone https://github.com/rust-analyzer/rust-analyzer
- cd rust-analyzer
- vim crates/rust-analyzer/src/bin/main.rs

**Comment by GopherJ** [comment]
I just find it's hard to reproduce in normal `main.rs`

```rust
fn main() {

}
```

but I can reproduce it on:

```rust
#[actix_rt::main]
async fn main() -> anyhow::Result<()> {
}
```

**Comment by chemzqm** [comment]
Paste output from language server if you still have this issue,  https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by GopherJ** [comment]
@chemzqm @fannheyward  I already put the output there, I can always reproduce this issue

<img width="841" alt="image" src="https://user-images.githubusercontent.com/33961674/123074519-f56a0800-d449-11eb-9104-f0db418c9446.png">

**Comment by chemzqm** [comment]
We need full verbose output.

**Comment by GopherJ** [comment]
@chemzqm great I'll be start testing this evening!

**Comment by GopherJ** [comment]
@chemzqm I think it still happens but just less than before:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/33961674/123089366-6c5acd00-d459-11eb-9234-c40eaa5208aa.png">

**Comment by chemzqm** [comment]
It does refresh on `CursorHold`
