### ISSUE TITLE
.ccls loaded relative to file being edited in its buffer

### ISSUE THREAD

**Issue by kevr** [neoclide/coc.nvim#2925]
**Is your feature request related to a problem? Please describe.**
Currently, `.ccls` files are loaded by `coc.nvim` when it finds them relative to the directory where vim is run. This causes an issue when using vim to edit files in a multi-architectural project. In a project, I provide different flags for different architectures. I can set those flags in `.ccls` relative to the files that need it, which works fine if I change to that leaf directory and open vim while inside of it, but vim will not automatically load up the right `.ccls` files based on any relative to the target file, so editing different architectures requires that I relaunch vim in those other directories (which then breaks the other architecture).

Directory structure:

```
.ccls
src/
src/main.cpp
src/some_other_arch/.ccls
src/some_other_arch/file.cpp
src/some_arch/.ccls
src/some_arch/file.cpp
```

`~/.vim/coc-settings.json`
```
{
    "languageserver": {
        "ccls": {
            "command": "ccls",
            "filetypes": ["cc", "c", "h", "hpp", "cpp", "objcpp"],
            "rootPatterns": [".ccls", "compile_commands.json"],
            "initializationOptions": {
                "cache": {
                    "directory": "/tmp/ccls"
                },
                "highlight": { "lsRanges" : true }
            }
        },
        "pyls": {
            "command": "pyls",
            "filetypes": ["py", "pyc", "python"],
            "rootPatterns": [".vim/"],
            "initializationOptions": {
                "cache": {
                    "directory": "/tmp/pyls"
                },
                "highlight": { "lsRanges" : true }
            }
        }
    }
}

```

If I open up `src/some_arch/file.cpp`, the base `.ccls` is loaded and `src/some_arch/.ccls` is ignored.

**Describe the solution you'd like**
If ccls could be loaded up with a `.ccls` file found relative to the file being **edited** in vim, I believe this would solve the issue I'm having and add quite a bit of flexibility to loading configurations for projects. I'd be down to look into helping with this and possibly contributing the patch if this is accepted.

**Describe alternatives you've considered**
I've considered wrapping my vim command to auto change directories. However, his breaks if I work multi-platform, since files seem to only be loaded based on where vim was started from. For now, I need to run several tmux panes to load up the other arch editors in unison.

**Comment by chemzqm** [comment]
Read wiki for workspaceFolders

**Comment by kevr** [comment]
> Read wiki for workspaceFolders

I do not believe workspaceFolders solves the issue I've described. That's a collection of folders that ccls will search through, but it does not have any kind of priority function.

I'm probably mistaken, but I'm a bit confused on how to use workspaceFolders here?
