### ISSUE TITLE
Missing option java.projectConfiguration.update in CocCommand list

### ISSUE THREAD

**Issue by Shandun** [neoclide/coc.nvim#2926]
## Describe the bug
Usually when I run :CocCommand in prompt of vim, I get a list to choose what command I want to run, which contains one of the most frequent command java.projectConfiguration.update. But recently I've found you remove this option, which make users to type this option every time when we need update pom.xml project files. It's quite convenient to do this typing every time. Could you restore this option to the list, please? Thank you. 

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
Make sure the extension is activated.
