### ISSUE TITLE
Is it possible to auto complete without showing the pop up menu?

### ISSUE THREAD

**Issue by JakeElder** [neoclide/coc.nvim#2927]
Is it possible to complete a pattern without opening the autocomplete popup?

Ie, given this typescript example, where I am typing props

```typescript
type Props = {
  children: React.ReactN<cursor>
}
```

I can press (with my bindings) `<c-n>` to open the autocomplete menu, the first entry is `ReactNode`, which I know I want. I can then press `<c-y>` to confirm this completion (I do not have `noselect` as a `completopt`, so the first result will be automatically selected), resulting in

```typescript
type Props = {
  children: React.ReactNode<cursor>
}
```

Perfect. But, is there a way to omit the `<c-n>`? Ie, if I am confident that the first entry that will appear in my autocomplete menu is the one I want, or there will only be one, is it possible for me to bind `<c-y>` to just go ahead and complete with the would be first entry?

**Comment by chemzqm** [comment]
coc.nvim doesn't only change completeopt during it's completion, you can configure it.

**Comment by chemzqm** [comment]
Learn vim if you don't know how to make vim insert complete item when it's the only one

**Comment by JakeElder** [comment]
`completeopt` is working as I expect. I'm asking if there's a way to invoke auto complete **without** opening the popup menu. Ie, complete the word with whatever the first entry in the popup menu will be, whether there is one or multiple.
