### ISSUE TITLE
Question: with "suggest.numberSelect" on, how to type numbers?

### ISSUE THREAD

**Issue by dycw** [neoclide/coc.nvim#2928]
In the following example, is it possible to write `fac_mb2` without having to "hit space" + "write 2" + "go left" + "backspace"?

![Screenshot from 2021-02-28 21-20-44](https://user-images.githubusercontent.com/10572122/109419925-d95dd900-7a0a-11eb-96d3-fee03ca32597.png)

**Comment by chemzqm** [comment]
Cancel completion by `<C-e>`

**Comment by dycw** [comment]
Thanks!
