### ISSUE TITLE
Error on notification "jumpDefinition": definition provider not found for current buffer, your language server don't support it

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [neoclide/coc.nvim#2929]
I am not able to jump to coc-definition. Why is that? How do I fix it?

![image](https://user-images.githubusercontent.com/34586104/109432010-7ae42b00-7a09-11eb-8692-7dc26bf77bf9.png)

**Comment by as79-alex** [comment]
Hey, why this is closed? I get this error every day!

**Comment by chemzqm** [comment]
Install language server for that filetype.

**Comment by as79-alex** [comment]
Of course it was installed and then reinstalled dozens of time. Finally I found issue -by unknown reason coc sometimes creates coc-settiongs.json file in project folder with settings which disables language server. In my case it was tsserver.disable: true. Afrer deleting that file, coc loads the original file ( more precisely it loads both but local overwrite values)

**Comment by fannheyward** [comment]
@as79-alex are you in a Deno project?
