### ISSUE TITLE
Incorrect filetype found when highlighting causes abort/crash

### ISSUE THREAD

**Issue by Amndeep7** [neoclide/coc.nvim#2930]
## versions

vim version: NVIM v0.5.0-nightly
node version: v15.10.0
coc.nvim version: 0.0.80-8e7635b6a0
coc.nvim directory: /Users/amann/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: darwin

## Log of coc.nvim

2021-02-28T22:34:25.573 INFO (pid:91582) [services] - registered service "solargraph"
2021-02-28T22:34:25.578 INFO (pid:91582) [plugin] - coc.nvim 0.0.80-8e7635b6a0 initialized with node: v15.10.0 after 175ms
2021-02-28T22:34:25.585 INFO (pid:91582) [watchman] - watchman watching project: $PATH_TO_PROJECT
2021-02-28T22:35:19.022 INFO (pid:91582) [attach] - receive notification: highlight []
2021-02-28T22:35:19.611 INFO (pid:91582) [attach] - receive notification: highlight []
2021-02-28T22:35:20.231 INFO (pid:91582) [attach] - receive notification: highlight []
2021-02-28T22:35:36.147 INFO (pid:91582) [attach] - receive notification: highlight []
2021-02-28T22:53:18.932 INFO (pid:91582) [attach] - receive notification: highlight []
2021-02-28T22:53:22.210 INFO (pid:91582) [attach] - receive notification: showInfo []

## Describe the bug

For some reason it thinks the filetype for the ruby file that I'm working on is 'txt' instead of 'ruby'.  It then causes a crash when it fails to find a 'txt' syntax file.  From the vim log:

```text
chdir($PATH_TO_PROJECT)
chdir(/Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc)
chdir($PATH_TO_PROJECT)
line 1: sourcing "/Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc/prompt.vim"
finished sourcing /Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc/prompt.vim
continuing in function coc#float#create_cursor_float[4]..<SNR>51_is_blocking
chdir($PATH_TO_PROJECT)
chdir(/Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc)
chdir($PATH_TO_PROJECT)
line 12: sourcing "/Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc/helper.vim"
finished sourcing /Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc/helper.vim
continuing in function coc#float#create_cursor_float[19]..coc#float#get_config_cursor
chdir($PATH_TO_PROJECT)
chdir(/Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc)
chdir($PATH_TO_PROJECT)
line 7: sourcing "/Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc/highlight.vim"
finished sourcing /Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc/highlight.vim
continuing in function coc#float#create_cursor_float[31]..coc#float#create_float_win[87]..coc#float#nvim_create_related
chdir($PATH_TO_PROJECT)
chdir(/Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc)
chdir($PATH_TO_PROJECT)
line 2: sourcing "/Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc/compat.vim"
finished sourcing /Users/amann/.config/nvim/plugged/coc.nvim/autoload/coc/compat.vim
continuing in function coc#float#create_cursor_float[37]..coc#highlight#add_highlights
chdir($PATH_TO_PROJECT)
chdir(/usr/local/Cellar/neovim/HEAD-59712f6/share/nvim/runtime/syntax)
chdir($PATH_TO_PROJECT)
line 2: sourcing "/usr/local/Cellar/neovim/HEAD-59712f6/share/nvim/runtime/syntax/ruby.vim"
finished sourcing /usr/local/Cellar/neovim/HEAD-59712f6/share/nvim/runtime/syntax/ruby.vim
continuing in function coc#float#create_cursor_float[37]..coc#highlight#add_highlights[6]..coc#highlight#highlight_lines[21]..<SNR>59_execute
not found in 'runtimepath': "syntax/txt.vim"
Error detected while processing function coc#float#create_cursor_float[37]..coc#highlight#add_highlights[6]..coc#highlight#highlight_lines[21]..<SNR>59_execute:
line    2:
E484: Can't open file syntax/txt.vim
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `nvim -u mini.vim`

- Operate vim.

- Open the following file and then try to add another argument to the call to 'puts' where it will fail as soon as you type a comma after `'example'`.

```ruby
# frozen_string_literal: true

module Example
  class Ex
    def example()
      puts('example')
    end
  end
end
```

**Comment by chemzqm** [comment]
The language server doesn't provide filetype , checkout`:h g:coc_markdown_disabled_languages`
