### ISSUE TITLE
Completion from past vim inserts (or cache file)

### ISSUE THREAD

**Issue by kovasap** [neoclide/coc.nvim#2931]
Anyone know of a way to get vim to complete from past "inserts"? For example, if i go into insert mode, make a change, then go into insert mode again, is there a way to complete if I want to do the exact same insert again? I know '.' repeats, but I often want to repeat the same insert i did a couple other inserts ago.

I think **if I could get coc.nvim to complete from a cache file**, that would be enough functionality to make this work.  I could then have vim write the contents of each insert to that file (i think), and my functionality would work as expected.  

Thanks!

(this is a duplicate of https://github.com/neoclide/coc-sources/issues/25)

**Comment by chemzqm** [comment]
My suggestion is use register.

**Comment by kovasap** [comment]
Sorry I'm not sure what you mean, could you be more specific?

**Comment by kovasap** [comment]
@chemzqm following up on this - can you describe a bit more what you mean?

**Comment by chemzqm** [comment]
Use git.undoTrunk command from coc-git is more efficient for that purpose.
