### ISSUE TITLE
Is it possible to autocomplete without a popup?

### ISSUE THREAD

**Issue by JakeElder** [neoclide/coc.nvim#2934]
Is it possible to auto complete **without bringing up a popup window**, instead cycling through values like default Vim omnifunc?

Example below, using Neovim LSP and omnifunc (`buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')`)

![2021-03-02 15 52 29](https://user-images.githubusercontent.com/1167624/109625055-720e6900-7b71-11eb-890f-36dd056cd907.gif)

**Comment by chemzqm** [comment]
No, because that won't work with autocompletion
