### ISSUE TITLE
CocUpdate improvement

### ISSUE THREAD

**Issue by aureooms** [neoclide/coc.nvim#2945]
I want to run `vim +CocUpdate +qall` (similar to https://github.com/vim/vim/issues/2297). Because of asynchronicity, `+qall` quits before `+CocUpdate` is done.

**Describe the solution you'd like**
Either make `vim +CocUpdate +qall` just work like [`vim-plug`](https://github.com/junegunn/vim-plug) where `vim +PlugUpgrade +PlugUpdate +qall` just works, or define new `CocUpdateWait`, or improve feedback of `+CocUpdateSync` or [add some hook like `minpac` does](https://github.com/k-takata/minpac#finish-update-hooks).

**Describe alternatives you've considered**
Running `vim +CocUpdateSync +qall` works but the feedback is nonexisting since we don't get any paints until the job is finished, at which point `+qall` quits vim without even leaving time for a paint.

**Additional context**
I am trying to run the command `vim +PlugUpgrade +PlugUpdate +CocUpdate +qall`.

**Comment by chemzqm** [comment]
`:CocUpdateSync` is synchronized command, I don't think there's need to add hooks.

**Comment by aureooms** [comment]
> **Describe alternatives you've considered**
> Running `vim +CocUpdateSync +qall` works but the feedback is nonexisting since we don't get any paints until the job is finished, at which point `+qall` quits vim without even leaving time for a paint.

Can intermediate state be painted? Currently I get to wait on a nonresponsive vim.

**Comment by chemzqm** [comment]
No, it's not possible to output message to vim during request, it's limitation of vim & neovim.

**Comment by aureooms** [comment]
> No, it's not possible to output message to vim during request, it's limitation of vim & neovim.

I understand. What I want is to replicate `vim-plug`'s behavior.  It seems `vim +PlugUpgrade +PlugUpdate +qall` just works: it is able to both wait until completion for `+qall` and paint at the same time. Maybe this behavior can be imitated for `vim +CocUpdateSync +qall` or `vim +CocUpdate +qall` or some new `vim +CocUpdateAsyncButWait +qall`.

**Comment by chemzqm** [comment]
You can use `CocActionAync` which takes callback function like:
```
function! MyCallback(err, ...) abort
  if a:err
    echo a:err
  else
    echo 'done'
  endif
endfunction

call CocActionAsync('updateExtensions', v:false, function('MyCallback'))
```

**Comment by aureooms** [comment]
Thanks! That is what I am after indeed. I am going to try it out.

**Comment by aureooms** [comment]
Thanks again for your help. I ended up with the following solution to my particular problem:

```vim
" coc.nvim custom async update function
function! s:CocUpdateCallback(err, ...) abort
  if a:err
    echo a:err
  else
    execute 'qall'
  endif
endfunction

command! CocUpdateAsyncWaitThenQuit :call CocActionAsync('updateExtensions', v:false, function('<sid>CocUpdateCallback'))
```
