### ISSUE TITLE
Can't use coc in flatpak Neovim & vim plug

### ISSUE THREAD

**Issue by Starslayerx** [neoclide/coc.nvim#2948]
My system is chrome os, but the linux inside is debain10, thus I can't install neovim0.4, only 0.3 avilable(tried every way, like build or install by snapd, only flapak works)
So, I installed neovim and vim plug by **flatpak**, and install nodejs by the script.
```bash
curl -sL install-node.now.sh/lts | bash
node --version
```                                     
v14.16.0
But in neovim
> [coc.nvim] "/usr/local/bin/node" is not executable, checkout https://nod
ejs.org/en/download/

Also tried to add this line in `~/.var/app/io.neovim.nvim/config/nvim/`
```bash
let g:coc_node_path='/usr/local/bin/node'
```
How can I slove the problem?
![image](https://user-images.githubusercontent.com/53030987/110208127-46b5b200-7ec2-11eb-92e4-f472d7dd3e5b.png)

**Comment by chemzqm** [comment]
Should be problem with your node

**Comment by Fivro** [comment]
add 
`export COC_NODE_PATH="/path/to/node/`
in your ~/.bashrc or somewhere
