### ISSUE TITLE
Double results for "go-to-definition"

### ISSUE THREAD

**Issue by aj3423** [neoclide/coc.nvim#2949]
## Result from CocInfo

   vim version: NVIM v0.5.0-dev+1079-g8becdec39
   node version: v12.18.3
   coc.nvim version: 0.0.80-9184dcccc4
   coc.nvim directory: /e/vim/nvim/plugged/coc.nvim
   term: xterm-256color
   platform: linux
   
   ## Log of coc.nvim
   
   2021-03-06T21:51:26.657 INFO (pid:147066) [services] - registered servi
   ce "languageserver.go"
   2021-03-06T21:51:26.661 INFO (pid:147066) [plugin] - coc.nvim 0.0.80-91
   84dcccc4 initialized with node: v12.18.3 after 37ms
   2021-03-06T21:51:30.694 INFO (pid:147066) [attach] - receive notificati
   on: showInfo []

## Describe the bug

There're two results when "go to definition" or "go to reference"

## Reproduce the bug

- vimrc：
```vim
set runtimepath^=/e/vim/nvim/plugged/coc.nvim
nmap <silent> gd <Plug>(coc-definition)
```
- CocConfig:
 ```json
{
  "languageserver": {
    "go": {
      "command": "/gobin/gopls",
      "rootPatterns": ["go.mod", "*.aj", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
  },
  "list": {
      "maxPreviewHeight": 24
  },

  "diagnostic": {
    "checkCurrentLine": true
  }
}
```
- `vim 2.go`

- go-to-definition by pressing *gd* on variable *aaa*

## The "2.go" and result are shown in the image:
![coc](https://user-images.githubusercontent.com/4710875/110209653-88495b80-7ec8-11eb-9a11-48559f7c8058.png)

Why two results?

**Comment by fannheyward** [comment]
Check out `:CocList services`.

**Comment by aj3423** [comment]
> Check out `:CocList services`, looks like you're setting two language servers.

![image](https://user-images.githubusercontent.com/4710875/110210934-217b7080-7ecf-11eb-80b7-c951467ff170.png)

**Comment by shanukun** [comment]
@fannheyward  I'm also facing the same issue.


```
vim version: VIM - Vi IMproved 8.2 8022539
node version: v14.16.0
coc.nvim version: 0.0.80-0a565835ea
term: alacritty
platform: linux
```
- `:CocList services` result:

![ksnip_20210321-145754](https://user-images.githubusercontent.com/30050220/111899981-e1cb9180-8a55-11eb-946f-5bf8209d0149.png)

**Comment by chemzqm** [comment]
@shanukun run the command after you got the issue.

**Comment by shanukun** [comment]
I ran the command after getting the issue.
![ksnip_20210322-171421](https://user-images.githubusercontent.com/30050220/111985001-16ad1680-8b32-11eb-9a02-ca6d1b694118.png)

Also I'm only seeing this problem with python (jedi), tsserver seems to work fine.

**Comment by chemzqm** [comment]
@shanukun 
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by shanukun** [comment]
Okay. I guess I found the problem. I also had coc-python along with coc-jedi, uninstalling the former fixed it.
@chemzqm Thank you.
