### ISSUE TITLE
Signature help in Insert Mode shall stay when switching form normal mode

### ISSUE THREAD

**Issue by PezCoder** [neoclide/coc.nvim#2951]
## Result from CocInfo
```
## versions

vim version: NVIM v0.5.0-566-g5f0a1b04c
node version: v12.16.2
coc.nvim version: 0.0.80-9184dcccc4
coc.nvim directory: /Users/rahulgupta/.vim/plugged/coc.nvim
term: xterm-256color
platform: darwin

## Log of coc.nvim

2021-03-07T02:31:20.642 INFO (pid:12822) [plugin] - coc.nvim 0.0.80-9184dcccc4 initialized with node: v12.16.2 after 66ms
2021-03-07T02:31:21.800 INFO (pid:12822) [watchman] - watchman watching project: /Users/rahulgupta/Downloads/workspace/cdf/web/clumio-ui/packages/app
2021-03-07T02:31:21.837 INFO (pid:12822) [services] - registered service "tsserver"
2021-03-07T02:31:28.440 INFO (pid:12822) [attach] - receive notification: startCompletion [
  {
    word: '',
    bufnr: 2,
    col: 79,
    synname: 'typeScriptParens',
    filepath: '/Users/rahulgupta/Downloads/workspace/cdf/web/clumio-ui/packages/app/src/utils/common.ts',
    blacklist: [],
    line: 'export const getOUIdFromLocalStorage = () => getLocalStorageProperty(constants.);',
    filetype: 'typescript',
    linenr: 483,
    input: '',
    colnr: 80,
    changedtick: 4
  }
]
2021-03-07T02:31:35.982 INFO (pid:12822) [completion-complete] - Results from: tsserver-typescript
2021-03-07T02:31:37.513 INFO (pid:12822) [attach] - receive notification: startCompletion [
  {
    word: '',
    bufnr: 2,
    col: 79,
    synname: 'typeScriptParens',
    filepath: '/Users/rahulgupta/Downloads/workspace/cdf/web/clumio-ui/packages/app/src/utils/common.ts',
    blacklist: [],
    line: 'export const getOUIdFromLocalStorage = () => getLocalStorageProperty(constants.);',
    filetype: 'typescript',
    linenr: 483,
    input: '',
    colnr: 80,
    changedtick: 6
  }
]
2021-03-07T02:31:37.524 INFO (pid:12822) [completion-complete] - Results from: tsserver-typescript
2021-03-07T02:34:02.717 INFO (pid:12822) [attach] - receive notification: showInfo []


```

## Describe the bug

- For a typescript project, when using a function like `func(` auto shows the signature of the function as you type & press comma.
- A common problem I've noticed here is, when you exit the insert mode at this point (Esc) & re-enter the insert mode, it doesn't show the signature help anymore.

This is apparent because, in VIM most of the time, we explore the files & stay in the normal mode. So if we want to use a function, we may jump around a bit to copy explore & pass in the values required. Having the signature help stay in that case whenever somebody is within the parenthesis of the function, can be great.

## Reproduce the bug
Shall be reproducible by any basic COC.nvim configuration. I was not able to make the signature help itself work with 'mini.vim' that's specified here.

## Screenshots (optional)
<a href="https://asciinema.org/a/sj95YAMafYqe4Xa3glsQAdUhy" target="_blank"><img src="https://asciinema.org/a/sj95YAMafYqe4Xa3glsQAdUhy.svg" /></a>

**Comment by chemzqm** [comment]
It's by design, you can use api to show the signature help.

**Comment by PezCoder** [comment]
@chemzqm Thank you for the response. It would be great if you can also provide some insight to why did we end up doing it this certain way as per design, is there any edge cases/complexities with approaching it?

In terms of using the API I do know how to trigger signature help which is `:call CocActionAsync('showSignatureHelp')`. I know this question is more around VIM in general, but for this specific use-case, if can you guide me in the right direction on how can I achieve this behaviorour, that would be of great help.

I understand the value of your time, so it's completely okay either way. Thanks! :)

**Comment by chemzqm** [comment]
It's the same behavior as VSCode, you can hack the code https://github.com/neoclide/coc.nvim/blob/master/src/model/floatFactory.ts#L74
