### ISSUE TITLE
[Bug] Errors are kept on screen after changing tab

### ISSUE THREAD

**Issue by JJJGGGG** [neoclide/coc.nvim#2952]
## Result from CocInfo
```
  ## versions             
    
  vim version: VIM - Vi IMproved 8.1 8012269           
  node version: v12.20.1                  
  coc.nvim version: 0.0.80-9184dcccc4        
  coc.nvim directory: /home/julian/.vim/plugged/coc.nvim
  term: dumb  
  platform: linux               
                                 
  ## Log of coc.nvim                                             
               
  2021-03-07T13:57:41.648 INFO (pid:12192) [plugin] - coc.nvim 0.0.80-9184dcccc4 initialized with node: v12.20.1 after 146ms
  2021-03-07T13:57:41.655 INFO (pid:12192) [language-client-index] - eslint started with 12233
  2021-03-07T13:57:41.710 INFO (pid:12192) [services] - registered service "tsserver"
  2021-03-07T13:57:59.633 INFO (pid:12192) [attach] - receive notification: showInfo []
```

## Describe the bug

When editing a file, if an error is found a warning popup is shown on cursor hover over the lines that produce the warning. After that, when opening a new file in a new tab, and coming back to the first tab, the error popup is still there and doesn't disappear, even after moving the cursor away from the lines that produce the warning.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim 1.py`

- Install the python coc extension. For example, run command ```:CocInstall coc-python```.

- In 1.py, write something similar to
```py
aslkdjflkasjflkasjflksajlfkdkjas
```

- Save with ```:w```.

- Place the cursor over what is written (that should show syntax error on a dialog) and then use the command ```:tabnew 2.py```.

- Go back to the first file by typing ```gt```.

- Now there should be a popup error message stuck on the first tab, and no way to remove it without closing the tab

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/48324565/110250669-41587600-7f5b-11eb-93d5-5754a16b6482.png)
![image](https://user-images.githubusercontent.com/48324565/110250673-474e5700-7f5b-11eb-8214-1993d80adc90.png)
![image](https://user-images.githubusercontent.com/48324565/110250675-4caba180-7f5b-11eb-8745-33c50c34c555.png)
![image](https://user-images.githubusercontent.com/48324565/110250692-64832580-7f5b-11eb-92c3-c7289d60c82f.png)

**Comment by chemzqm** [comment]
Vim's bug, upgrade your vim or use autocmd like:
```vim
autocmd WinEnter * call popup_clear()
```
in your vimrc.
