### ISSUE TITLE
Custom CA for CocInstall

### ISSUE THREAD

**Issue by allcentury** [neoclide/coc.nvim#2956]
In order to use npm, I have to ensure a CA bundle is set with npm/yarn.  I do this via `export NODE_EXTRA_CA_CERTS=/some.pem`

I'm unsure how to get `CocInstall` to work with this, I've tried setting my coc-settings.json with:

```js
{
  "env": {
    "NODE_EXTRA_CA_CERTS": "/my.pem"
  }
}
```

but it still isn't working.  I also tried:

```js
{
  "npm.binPath": "NODE_EXTRA_CA_CERTS=/some.pem /path/to/yarn"
}
```

I am able to install in the shell via `npm install coc-tsserver` but not via `CocInstall`.  Thoughts?

**Comment by fannheyward** [comment]
`CocInstall` will download package dist tarball from npmjs, then runs `npm install` to install `dependencies` if the package has.

Try set your CA to `http.proxyCA`.

**Comment by chemzqm** [comment]
You can export NODE_EXTRA_CA_CERTS to your env in vim by `let $NODE_EXTRA_CA_CERTS = '/my.pem'` in your vimrc.
