### ISSUE TITLE
Meaning of symbols in autocomplete drop down menu

### ISSUE THREAD

**Issue by joaqo** [neoclide/coc.nvim#2958]
Hi, I was playing with `suggest.completionItemKindLabels` in CocConfig today and started wondering what the other parts of the autocomplete drop down menu meant, and if they could be modified. Here is an example of the autocomplete drop down menu I get when I type `def` in a python script:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/14966348/110699825-090c9e00-81ce-11eb-850e-2c57300c1c55.png">

What does the `[LS]` at the end of the line and the `~` at the end of some keywords mean? Can I modify them?

Thanks!

**Comment by chemzqm** [comment]
Use `:CocList sources` to check all your sources.

**Comment by joaqo** [comment]
Thanks!
