### ISSUE TITLE
:CocRestart bug with vim8

### ISSUE THREAD

**Issue by amadeus** [neoclide/coc.nvim#296]
**Result from CocInfo**
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 22 2018 17:45:27)
node version: v8.9.0
coc.nvim version: 0.0.41
term: dumb
platform: darwin

## Error messages
```

**Describe the bug**
`:CocRestart` appears broken in vim8

**To Reproduce**
When executing `:CocRestart` I get the following error, although it looks like it ends up working properly?

```
Error detected while processing function coc#rpc#restart[1]..coc#client#restart[1]..coc#client#stop[13]..<lambda>3[1]..<SNR>108_on_exit:
line   12:
client coc abnormal exit with: -1
client coc stopped!
 ```

**Comment by drazde** [comment]
I have installed the plugin in windows with 
~~~
Plug 'neoclide/coc.nvim', {'do': './install.cmd nightly'}
~~~

After i do `PlugInstall` It give me the same error when I run Vim and try to restart with `:CocRestart`

**Comment by chemzqm** [comment]
The message is expected on windows vim, since it force terminate child process.
