### ISSUE TITLE
Code Action for import symbol on cursor

### ISSUE THREAD

**Issue by luisiacc** [neoclide/coc.nvim#2961]
I think it would be nice to have a code action to import a variable/function/class/anything-that-can-be-imported. Typicall scenario for this is: I copy paste some code but hey, I have to import all of this, so I go one by one, write it again for getting autocompletion and auto import, it would be much smoother to just go over the symbols I want to import, `<code-action>`,  `Import this from "lib/awesome-vars"`

**Comment by fannheyward** [comment]
Code action is already supported in coc, this also needs LS support, for example in Typescript, move your cursor to the library, fire `<Plug>(coc-codeaction-cursor)` will show the import actions. Check `:h n_coc-codeaction`

**Comment by luisiacc** [comment]
So @fannheyward , should I post this on coc-python ? Asking because you're the one who mantains it.

**Comment by fannheyward** [comment]
> on coc-python 

Do you means `coc-pyright`?

**Comment by luisiacc** [comment]
> > on coc-python
> 
> Do you means `coc-pyright`?

yes, sry

**Comment by fannheyward** [comment]
Pyright doesn't has import code action support by now.

**Comment by fannheyward** [comment]
https://github.com/microsoft/pyright/issues/251

**Comment by gabrielbeauchemin** [comment]
Hello :) ,

Could you please explain further? On a typescript file, I had the warning: "Cannot find name" on a function. I tried after putting my cursor on it to do :CocAction cursor<CR> and I get the following message: "No cursor code action available".

I can always retype the function and the completion suggestion works and add the import automatically, but I would like to be able to add the import automatically when a function has the "Cannot find name" error and that the function is declared in a library. Is there a way to do that with a command?

Thanks!

**Comment by iamcco** [comment]
> Hello :) ,
> 
> Could you please explain further? On a typescript file, I had the warning: "Cannot find name" on a function. I tried after putting my cursor on it to do :CocAction cursor and I get the following message: "No cursor code action available".
> 
> I can always retype the function and the completion suggestion works and add the import automatically, but I would like to be able to add the import automatically when a function has the "Cannot find name" error and that the function is declared in a library. Is there a way to do that with a command?
> 
> Thanks!

``` viml
" Applying codeAction to the selected region.
" Example: `<leader>aw` for current word
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
```

**Comment by gabrielbeauchemin** [comment]
Thank you!! I did not see that, it worked like a charm! I just added <CR> at the end of the mapping for maximum confort.

**Comment by MagicDuck** [comment]
hmm, that does not work for me :( 
```
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
```
I get `No code action available`, even though it works through auto-complete

**Comment by gabrielbeauchemin** [comment]
Are you sure you put your cursor on the same spot where the error is underlined?

**Comment by MagicDuck** [comment]
yes, tried again:
![image](https://user-images.githubusercontent.com/95201/111732797-9afe5180-8833-11eb-8db2-c13f86e0a8ed.png)

For reference,
coc-settings.json:
```json
{
  "suggest.noselect": false,
  "suggest.autoTrigger": "always",
  "suggest.enablePreselect": false,
  "eslint.run": "onSave",
  "eslint.autoFixOnSave": true,
  "eslint.alwaysShowStatus": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ],
  "prettier.disableSuccessMessage": true,
  "coc.preferences.formatOnSaveFiletypes": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "json"
  ],
  "diagnostic.errorSign": "✘",
  "diagnostic.warningSign": "",
  "diagnostic.infoSign": "",
  "suggest.completionItemKindLabels": {
    "keyword": "",
    "variable": "",
    "value": "",
    "operator": "Ψ",
    "constructor": "",
    "function": "ƒ",
    "reference": "渚",
    "constant": "",
    "method": "",
    "struct": "פּ",
    "class": "",
    "interface": "",
    "text": "",
    "enum": "",
    "enumMember": "",
    "module": "",
    "color": "",
    "property": "",
    "field": "料",
    "unit": "",
    "event": "鬒",
    "file": "",
    "folder": "",
    "snippet": "",
    "typeParameter": "",
    "default": ""
  },
  "javascript.format.enabled": false,
  "typescript.format.enabled": false
}

```

**Comment by MagicDuck** [comment]
Hmm, I intermittently get "no code action available" and this:
![image](https://user-images.githubusercontent.com/95201/111734225-ea924c80-8836-11eb-98be-062c667aadb6.png)
which is nice, but does not offer the import option

**Comment by MagicDuck** [comment]
Got it to work. In case anybody is wondering, for javascript, you need to have the following prop set in your jsconfig.json file:
```json
"checkJs": true,
```

**Comment by timtyrrell** [comment]
@MagicDuck Yeah, I noticed the same with those settings. `"checkJs": true,` will make it show as an action but `  "javascript.validate.enable": false` needs be running which gets nasty. Also, I did try `<Plug>(coc-codeaction-cursor)` but that made no difference...

**Comment by timtyrrell** [comment]
Maybe relevant: https://github.com/neoclide/coc-tsserver/issues/201#issuecomment-690418964
