### ISSUE TITLE
CocRequest with buffer number instead of id?

### ISSUE THREAD

**Issue by seblj** [neoclide/coc.nvim#2968]
More of a question really:

Are there any functions similar to nvim-lspconfigs `vim.lsp.buf_request_sync`? I found that `CocRequest` works similarly, but this takes the id of the client, where `vim.lsp.buf_request_sync` takes the buffer number. I am trying to setup a picker for showing the references inside telescope.nvim instead of using the default viewer.

If I use `vim.lsp.buf_request_sync(0, 'textDocument/references', ...)` I get what I want when using nvim-lspconfig. I am able to do the same thing with `CocRequest('clangd', 'textDocument/references', ...)` for example. However this only works when using clangd, where the one from nvim-lspconfig works for every language server, since it uses buffer number instead of an id of the language server.

**Comment by chemzqm** [comment]
We only have `getHover` for general request of LSP feature for now.

**Comment by fannheyward** [comment]
https://github.com/fannheyward/telescope-coc.nvim
