### ISSUE TITLE
Conflict with Tim Pope's vim endwise

### ISSUE THREAD

**Issue by npearson72** [neoclide/coc.nvim#297]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.3.1
node version: v11.5.0
coc.nvim version: 0.0.41
term: iTerm.app
platform: darwin

## Error messages

## Output channel: tsserver
[Info  - 2:44:23 AM] Forking TSServer
PATH: /Users/nathan/.yarn/bin:/Users/nathan/.config/yarn/global/node_modules/.bin:/Users/nathan/.rbenv/shims:/Users/nathan/bin:/Users/nathan/rbenv/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/opt/fzf/bin 
[Info  - 2:44:23 AM] Started TSServer
{
  "path": "/Users/nathan/.config/coc/extensions/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.2.2",
    "version": "3.2.2"
  }
}

## Output channel: eslint
[Info  - 2:44:23 AM] ESLint server running in node v11.5.0
[Info  - 2:44:24 AM] ESLint library loaded from: /Users/nathan/Dev/learning/js/udemy/react-16-6-the-complete-guide--maximilian-schwarzmuller/react-complete-guide/node_modules/eslint/lib/api.js
```

**Describe the bug**
Using the following remapping breaks the completion:

```
inoremap <expr><cr> pumvisible() ? "\<c-y>" : "\<cr>"
```

It appears this issue only happens due to a conflict with https://github.com/tpope/vim-endwise

I'm hoping you might advise on how I can resolving the mapping.

**To Reproduce**

See screenshots below...

**Screenshots**

Menu appears and selection is made:
<img width="538" alt="screen shot 2018-12-26 at 2 46 44 am" src="https://user-images.githubusercontent.com/1323414/50427762-87fcb100-08b8-11e9-8c03-0119f198bad9.png">

Hitting the `Enter` key:
<img width="447" alt="screen shot 2018-12-26 at 2 46 52 am" src="https://user-images.githubusercontent.com/1323414/50427763-8af7a180-08b8-11e9-9cf4-bdf3f13995fc.png">

**Comment by oblitum** [comment]
That mapping is just a suggestion, you may not use it and simply rely on Vim's built in confirmation key, `c-y`.

related: https://github.com/neoclide/coc.nvim/issues/262#issuecomment-447401338

**Comment by chemzqm** [comment]
Youre mapping is not taking effect. Checkout `verbose imap <CR>`.
Use `let g:endwise_no_mappings=0` or use other key for confirm completion.

**Comment by npearson72** [comment]
BTW... I also wanted to just say thank you for the great plugin! Not only is it feature rich and modular, but it's the only one that I have tried with a language client that works properly for ruby (i.e. solagraph).

Thank you again.
