### ISSUE TITLE
Duplicate auto complete suggestions

### ISSUE THREAD

**Issue by C-Rmoser** [neoclide/coc.nvim#2970]
Hey! I'm getting duplicate auto suggestion entries (view screenshot). I am using coc-omnisharp extension. I tried disabling all Plugins except for coc.nvim but that didn't fix the issue. Any idea how to fix it? Thanks in advance! (I'm new to vim, sorry if I didn't provide enough information)

CocInfo:
vim version: NVIM v0.5.0-dev+1126-g0496b572a
node version: v15.11.0
coc.nvim version: 0.0.80-fedaf52837
coc.nvim directory: C:\Users\rohrm\AppData\Local\nvim\plugged\coc.nvim
term: vtpcon
platform: win32

![ss_autocomplete](https://user-images.githubusercontent.com/50134385/111079722-83edf580-84fb-11eb-8299-30b0df58860f.PNG)

**Comment by fannheyward** [comment]
Checkout `:CocList services`.

**Comment by Nazeehe** [comment]
I am having the same issue. I am not sure I am following the recommendation of checking out :CocList services.
