### ISSUE TITLE
CocCommand doesn't work in Neovim on Windows Powershell 

### ISSUE THREAD

**Issue by H-111-di** [neoclide/coc.nvim#2976]
## Result from CocInfo

```vim
## versions

vim version: NVIM v0.4.4
node version: v15.11.0
coc.nvim version: 0.0.80-98a0c6db19
coc.nvim directory: C:\Users\hardy\AppData\Local\nvim-data\plugged\coc.nvim
term: vtpcon
platform: win32

## Log of coc.nvim

2021-03-17T17:10:04.799 INFO (pid:15784) [plugin] - coc.nvim 0.0.80-98a0c6db19 initialized with node: v15.11.0 after 145ms
2021-03-17T17:10:08.684 INFO (pid:15784) [attach] - receive notification: showInfo []
```
## Describe the bug

The CocCommands doesn't work on Windows Powershell with Neovim v0.4.4 *(install through scoop)*.

In both coc-pyright and coc-clangd none of the commands they should provide could be found.<br>*([coc.nvim]: Error on notification "runCommand": Command: clangd.install not found)*

## Reproduce the bug
----
**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.
-------
Sorry, I've tried it and I can only get a same result. *(BTW, is minimal vimrc a kind of file or so? What should I do to provide it?)*

## Screenshots (optional)
![image](https://raw.githubusercontent.com/H-111-di/Pics/master/Coc.nvim_error.png?token=ANM3IEPIG4PYZSAZCQCNH3TAKHKFE)

**Comment by H-111-di** [comment]
Tried it on the nightly version and the problem stills.

**Comment by chemzqm** [comment]
You have to make the extension is activated by `:CocList extensions`

**Comment by H-111-di** [comment]
Great Thanks !!
So sorry for the noob questions...
I used to use coc on a  mac and it don't need to activate the extensions, so I just thought that might be a problem or bug.
