### ISSUE TITLE
Question: how to tell coc to send text on did_save command

### ISSUE THREAD

**Issue by dpriedel** [neoclide/coc.nvim#2977]
I'm new to this so I probably don't understand things well.

According to the LSP documentation I have read, the did_save command to the server can have an optional parameter of the text of the file being saved.  Logging shows that my simple server is only receiving the required file uri parameter.

Is there some way to tell coc.nvim to also send the file content as well, just as it does for the did_open command?

Thanks

**Comment by fannheyward** [comment]
In my upstanding, `includeText` is set by LS.

1. client register capability for `didSave`
2. server response with `SaveOptions`, requests client to send text or not
3. client does `didSave` request, sends text follows on `SaveOptions. includeText`

**Comment by chemzqm** [comment]
The server should send `includeText`  with `TextDocumentSaveRegistrationOptions`
