### ISSUE TITLE
On opening a new file the outline window appears, can't find a setting to disable this behavior

### ISSUE THREAD

**Issue by fuag15** [neoclide/coc.nvim#2978]
## Result from CocInfo

```
    0 ## versions
    1
    2 vim version: NVIM v0.4.4
    3 node version: v14.0.0
    4 coc.nvim version: 0.0.78-9febe802b3
    5 term: screen-256color
    6 platform: linux
```

## Describe the bug

Whenever a document is opene cock displays an outline window at the bottom. This is not a behavior I want but I can't find a way to disable it or if its intended. Its annoying to have to type escape every time a new file is opened

**Comment by fannheyward** [comment]
Can't reproduce, properly caused by your configurations.

BTW, you're using an old version of coc.nvim.
