### ISSUE TITLE
Support pattern filter of client/registerCapability

### ISSUE THREAD

**Issue by kit494way** [neoclide/coc.nvim#2980]
**Is your feature request related to a problem? Please describe.**

Because the `pattern` parameter of `DocumentFilter` included in `client/registerCapability` request is [ignored](https://github.com/neoclide/coc.nvim/blob/4e3b7f34da59aaa2753b1363fdbe8f08c75a6157/src/language-client/client.ts#L1916), unexpected completion source is activated like the issue https://github.com/coc-extensions/coc-omnisharp/issues/53 .
Although this feature does not solve the issue completely, I think it is helpful to mitigate the issue.

**Describe the solution you'd like**

Respect the `pattern` parameter.

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
Should be fixed by d9092b72
