### ISSUE TITLE
enable Auto scroll for workspace.showOutput

### ISSUE THREAD

**Issue by RobertBrunhage** [neoclide/coc.nvim#2987]
**Is your feature request related to a problem? Please describe.**
When opening `workspace.showOutput` I usually have it in a horizontal split and everytime I have to go to it and scroll to the bottom. Is it possible for this to auto scroll to the bottom?

**Describe the solution you'd like**
Auto scroll `workspace.showOutput`

**Describe alternatives you've considered**
haven't

**Additional context**
none

**Comment by chemzqm** [comment]
You can write BufEnter autocmd if you want to.
