### ISSUE TITLE
coc的补全提示框可以同时列出可能的snippets吗？

### ISSUE THREAD

**Issue by ParadoxZW** [neoclide/coc.nvim#2991]
您好，感谢提供如此好用的plugin，但是有一点美中不足的是，coc的补全提示框中貌似只有列出和补全相关的条目，而没有snippets的条目。

我尝试过使用spacevim自带的autocomplete layer的配置，其中使用了deoplete和neosnippet，这两个可以很棒地协同工作，即，我按下两个字母之后（例如‘de’），弹出来的自动补全的提示框中会同时列出补全的条目和snippet的条目（例如，提示列表中包含了以de开头的变量名，也包含了以‘def’作为缩写的snippet）。

想知道如何配置，才能使coc的使用体验达到类似的效果。

感谢！

**Comment by fannheyward** [comment]
Try `coc-snippets`
