### ISSUE TITLE
status line is frozen, only updates when I press keys

### ISSUE THREAD

**Issue by comex** [neoclide/coc.nvim#2993]
## versions

vim version: VIM - Vi IMproved 8.2 8022164

 - This is installed via Homebrew, with `brew install --HEAD macvim`; it's actually git commit `afeb743`.  I just updated it to the latest `master`, `7d55a41`, but it doesn't help.
 
node version: v14.14.0

 - Just tried upgrading to v15.12.0, doesn't help.

coc.nvim version: 0.0.80-d129f0f97e

 - Latest `release` at time of filing.  I just tried switching to `master` (`f27af73`) and it doesn't help.

coc.nvim directory: /private/tmp/coc.nvim
term: Apple_Terminal
platform: darwin

## Log of coc.nvim

2021-03-28T16:52:15.371 INFO (pid:88716) [services] - registered service "rust-analyzer"
2021-03-28T16:52:15.373 INFO (pid:88716) [services] - Rust Analyzer Language Server state change: stopped => starting
2021-03-28T16:52:15.377 INFO (pid:88716) [language-client-index] - Language server "rust-analyzer" started with 88717
2021-03-28T16:52:15.383 INFO (pid:88716) [services] - Rust Analyzer Language Server state change: starting => running
2021-03-28T16:52:15.388 INFO (pid:88716) [services] - service rust-analyzer started
2021-03-28T16:52:15.511 INFO (pid:88716) [plugin] - coc.nvim 0.0.80-d129f0f97e initialized with node: v14.14.0 after 205ms
2021-03-28T16:52:38.049 INFO (pid:88716) [attach] - receive notification: showInfo []

## Describe the bug

When the status line is supposed to show indexing progress, it stays frozen, and only updates when vim decides to redraw the screen, e.g. in response to user input.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**
- Install `coc-rust-analyzer` (used to reproduce, though this doesn't seem to be Rust-specific; I also had the same issue with `coc-clangd`)
- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/tmp/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  set laststatus=2
  set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
  ```

- Start vim with command: `vim -u mini.vim src/lib.rs` (in a Rust crate root, large enough that it doesn't finish indexing instantly)

- If you don't input anything, indexing progress does not appear in the status line.

- If you perform just about any action – e.g. pressing `h` and `l` to move the cursor – the status line will update to show the progress as of the time you performed the action, but it still won't update by itself after that.

## Screenshots (optional)

Notice how the status line only updates when I press `h` and `l` to move the cursor left and right.

https://user-images.githubusercontent.com/47517/112768214-eb6e6f80-8fe8-11eb-9eac-2c9286047781.mov

**Comment by chemzqm** [comment]
You have to add 
```
autocmd User CocStatusChange redraws
```
in your vimrc, we don't do that since it might make your cursor invisible and clear messages on the screen.

**Comment by comex** [comment]
I see.  Surely this could be documented better, like in the tutorial or a FAQ entry?  Currently, the only mentions of `CocStatusChange` in the documentation are this rather brief entry:

```
:autocmd User CocStatusChange {command}

	Triggered after `g:coc_status` changed, can be used for refresh
	stautsline.
```

...plus a mention in an entry about using Coc with the lightline plugin.

**Comment by gou4shi1** [comment]
FYI, I solved with `autocmd User CocStatusChange redrawstatus`.

**Comment by chemzqm** [comment]
Will add to `:h coc-status`

**Comment by gou4shi1** [comment]
> FYI, I solved with `autocmd User CocStatusChange redrawstatus`.

Hmm, I found this may make my cursor flash when
![image](https://user-images.githubusercontent.com/16915589/203715995-6f4dbaf2-9349-4966-9dad-758f892d59e1.png)

**Comment by gou4shi1** [comment]
`redrawstatus` also redraw cursor, is it a bug or by design?

**Comment by chemzqm** [comment]
> redrawstatus also redraw cursor, is it by design?

Depends on your vim and terminal, seems not happens with neovim.
