### ISSUE TITLE
Additional machine-local configuration file

### ISSUE THREAD

**Issue by languitar** [neoclide/coc.nvim#2996]
**Is your feature request related to a problem? Please describe.**

Some extensions such as [coc-jira-complete](https://github.com/jberglinds/coc-jira-complete) require credentials inside the settings to function properly. Such settings should not end up in git repositories containing the vim dotfiles. They are often also not a candidate for the project-local settings file, because I need to use the same JIRA token for close to all of my projects.

Another aspect is that some settings might depend on the system I am working on (work vs private, linux vs windows). They are a bad fit for the global configuration file that is shared between all environments.

**Describe the solution you'd like**

I'd like to have the possibility to include another `coc-local-settings.json` file in the configuration cascade placed between the global `coc-settings.json` from `~/.config/nvim` and the project-local settings for representing machine-local settings that should not end up in any repository (either per project or the global dot files). That file would allow providing credentials and machine-specific configuration.

**Describe alternatives you've considered**

* Placing such config values in the global config is prone to being committed to the dotfiles. Machine-specific settings wouldn't be possible.
* Per-project configs required a lot of duplication, credentials could also be accidentally committed.

**Comment by fannheyward** [comment]
For TOKEN configurations, I prefer to export to ENV and extensions read from ENV. These configurations should not be set in configuration file.

For example, https://github.com/neoclide/coc-git will read `GITHUB_API_TOKEN` from ENV to use.

**Comment by languitar** [comment]
I've also proposed that upstream for coc-jira-complete in https://github.com/jberglinds/coc-jira-complete. However, environment variables can potentially be read by many applications (event neovim may launch a lot of executables internally, all having then access to such a variable). So its also not easy to get this secure.

The issue with machine-local configuration remains at least, though.

**Comment by benmoss** [comment]
I have another use-case that I think this feature would help. I use https://github.com/luan/nvim as my vim config, and it has support for machine-local vim settings so that people don't need to maintain forks in order to make small customizations. Right now I don't think there's any way to expose a base coc-settings.json but with overrides except for the `:CocLocalConfig`.

**Comment by oblitum** [comment]
I would most probably use `coc#config()` for this.

FWIW, I _always_ use `coc#config()` anyway 😄.

**Comment by chemzqm** [comment]
It's still possible to publish `coc-local-settings.json` to github,  use environment variable is recommended for your case, and there is `workspace.expand` to expand configuration value with environment variable.
