### ISSUE TITLE
Unexpected/poor matching on autocomplete suggestions

### ISSUE THREAD

**Issue by ljden** [neoclide/coc.nvim#2997]
I have recently made the move from YCM to coc.nvim+ccls, and my biggest gripe with usability is the performance of suggestions when providing a non-contiguous subset of characters to match the intended word faster.

In particular, it seems the first character entered must either be the first character intended to match, or the character must be the correct case. There is also weird behaviour with multiple non-contiguous subsets 

For example, when searching for a #define located in a different file such as "ENOMEM" searching:
- "E" followed by any one character in "ENOMEM" matches (albeit low in list)
- "ENME" matches
  - ie 2 sets of contiguous characters with a gap between, first character is first in intended match
- "NOEM" doesn't match
  - ie 2 sets of contiguous characters with a gap between, first character is not first in intended match  
- "NOM" matches
  - Single contiguous subset of search string. But:
- "MEM" doesn't match
  - Single contiguous substring, last 3 characters
  - but:
- "EM" and "OMEM" match
  - Single contiguous substring, last 2/4 characters
- "EOM matches
  - 3 individual non-contiguous characters, first character is first in intended match
- "NMM" 
  - 3 individual non-contiguous characters, first character is not first in intended match
- "ENMM", "EOMM", and "EOEM" doesn't match
  - 3 individual non-contiguous characters + 1 contiguous character with one of the characters

- "Nom" matches
  - single contiguous subset, first character matching intended case  
- "nomem" and "nOMEM" doesn't match
  - single contiguous subset, first character not first in intended match, and first character not matching intended case 
- "enom" matches
  - single contiguous subset, first character is first in intended match, and first character not matching intended case 
- "eom" matches
  - same as "EOM", not matching case
 

I'm not sure if this is a shortfall of coc.nvim search implementation, or ccls (or both) or if this is a setup issue.  Let me know what you think

**Comment by ljden** [comment]
Not sure how much configuration plays a part in this, but if you need outputs of anything please let me know and I can add them here

**Comment by oblitum** [comment]
I wished coc offered a configuration option to [customize the string distance algorithm](https://github.com/dguo/strsim-rs) being used internally.

**Comment by oblitum** [comment]
coc.nvim indeed offer a bit of customization at that through the `suggest.defaultSortMethod` option.

**Comment by chemzqm** [comment]
* Some sources of coc.nvim like `around` and `buffer` requires strict match of first character by default.
* Some language servers support increment completion, you may have to type exact start characters for that case.

**Comment by fannheyward** [comment]
@chemzqm as I asked in Gitter, I think it's better to enable allowFuzzy in https://github.com/neoclide/coc.nvim/blob/master/src/completion/match.ts#L124 to enable `fbr` to match `foobar`.
