### ISSUE TITLE
Colors in popup menu

### ISSUE THREAD

**Issue by reportaman** [neoclide/coc.nvim#2998]
Currently all the fields in the popup menu have same color. It would be nice to have each field have its own color, and devicons have their individual colors too.

Given the width of each field is decided by the widest element in that field, a [text property](https://vimhelp.org/textprop.txt.html) solution would be fastest (if [text properties](https://vimhelp.org/textprop.txt.html) are possible in popup).

<img width="349" alt="Screen Shot 2021-03-30 at 3 30 26 PM" src="https://user-images.githubusercontent.com/71736629/113065860-61e8aa00-916e-11eb-9290-9a4af86d7cb1.png">

**Comment by reportaman** [comment]
Perhaps an alternative would be to apply a filetype to popup menu's buffer opened by coc, something like this:

``call setbufvar(winbufnr(cocpmenuwinid), '&filetype', 'cocpmenu')``

Then users can use their usual filetype highlight groups from devicons to apply coloring to devicons using other plugins.

**Comment by chemzqm** [comment]
It's vim's pum, not popup, which doesn't provide such kind of support.

**Comment by reportaman** [comment]
@chemzqm I reported this to Vim team. Vim's author Bram seems to suggest it is possible to replace pum with popup window: https://github.com/vim/vim/issues/8043#issuecomment-811259848

**Comment by chemzqm** [comment]
We have to support neovim and exist configuration, that would be too complicated

**Comment by reportaman** [comment]
@chemzqm Ok, can you comment on the vim ticket, and explain your point to Bram?
