### ISSUE TITLE
Remapping <c-y> breaks snippetNext using coc-tsserver

### ISSUE THREAD

**Issue by npearson72** [neoclide/coc.nvim#300]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.3.1
node version: v11.5.0
coc.nvim version: 0.0.41
term: iTerm.app
platform: darwin

## Error messages

## Output channel: tsserver
[Info  - 2:46:16 PM] Forking TSServer
PATH: /Users/nathan/.yarn/bin:/Users/nathan/.config/yarn/global/node_modules/.bin:/Users/nathan/.rbenv/shims:/Users/nathan/bin:/Users/nathan/rbenv/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/opt/fzf/bin 
[Info  - 2:46:16 PM] Started TSServer
{
  "path": "/Users/nathan/.config/coc/extensions/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.2.2",
    "version": "3.2.2"
  }
}
```

**Describe the bug**
I'm not sure if this is a bug or just improper mapping. I'm hoping you can help?

I've remapped `<c-y>` to `<c-j>` so it unifies snippets commands with UltiSnips. It works perfectly when used in Ruby with `coc-solargraph`, but when used with `coc-tsserver` on a React app, it prints the following when I skip to the next part of the snippet:

`:call CocActionAsync('snippetNext')`

**To Reproduce**

1. Install the following nvim/vim plugins:
```
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'cristianoliveira/vim-react-html-snippets'
Plug 'neoclide/coc.nvim', { 'do': 'yarn install' }
```
2. Define the follow nvim/vim settings:
```
let g:UltiSnipsExpandTrigger="<c-y>"
inoremap <silent><expr><c-j> pumvisible() ? "\<c-y><c-r>=UltiSnips#ExpandSnippet()<cr>" : "\<c-j>"
```
3. Install `coc-tsserver` extension
4. Create a React app using the latest `create-react-app@2.1.2`. (ex: `yarn install create-react-app && create-react-app my_app`
5. In the `my_app` dir open the app `App.js` file
6. Start typing `this.` and wait for menu to appear, then select `componentDidCatch` and hit `Ctrl`+`j`. This works properly and the following is inserted into the buffer: `this.componentDidCatch(error, errorInfo)`
7. Hit `Ctrl` + `j` again. This moves the cursor to the `error` argument in the snippet, but then it prints the following into the buffer: `:call CocActionAsync('snippetNext')`

**Screenshots**
![kapture 2018-12-27 at 14 48 43](https://user-images.githubusercontent.com/1323414/50481179-d4470e80-09e8-11e9-9d93-8b3f8b15ba30.gif)

**Comment by npearson72** [comment]
So is this a genuine bug? Is it something you can address or is it something with UltiSnips?

**Comment by chemzqm** [comment]
I've test neovim 0.3.1 with coc and UltiSnips, but I can't reproduce it.
Is this problem exists without other extension?

**Comment by npearson72** [comment]
I've narrowed down the true cause. It's related to the following mappings:

```
" Toggle relative numbers in visual line mode
nnoremap <silent> v v:<c-u>set nonu rnu<cr>gv
nnoremap <silent> V V0:<c-u>set nonu rnu<cr>gv
nnoremap <silent> <c-v> <c-v>:<c-u>set nonu rnu<cr>gv
vnoremap <esc> <esc>:set nornu nu<cr>
```

In particular it's related to the last line.

So this is not related to you COC at all.

Any chance you have suggestions on how to resolve it other than just removing the offending mappings?

**Comment by chemzqm** [comment]
I think that coc should use sendkeys function instead `nvim_input` which respect user defined keymap.
