### ISSUE TITLE
Parenthesis are not added when doing a python function call in coc.nvim

### ISSUE THREAD

**Issue by pavanscoding** [neoclide/coc.nvim#3001]
## Result from CocInfo
![needed](https://user-images.githubusercontent.com/75864715/113209828-62457b80-9228-11eb-8831-d7cb45429142.png)

## Describe the bug
So basically whenever I use C++ and I use the coc.nvim menu to get the list of functions and when I select one, I get the function and a pair of parenthesis with my cursor in between them. However, whenever I use python, I don't get the parenthesis with my mouse in between them. I was wondering if there is a way I can get the parenthesis for python as well. 

## Reproduce the bug

Here is my init.vim for neovim:
https://github.com/pavanscoding/competitive-coding-setup/blob/main/init.vim%20mac-linux

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by fannheyward** [comment]
Which language server do you use for Python?

**Comment by pavanscoding** [comment]
I am using coc-python as my language server.

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc-python has been stopped to maintain, try coc-pyright or coc-jedi.

**Comment by pavanscoding** [comment]
I tried to install coc-pyright, but I don't know if my neovim downloaded it correctly. How do I check if that is the language server that my computer is using?

**Comment by fannheyward** [comment]
Checkout `:CocList extensions`, and open an Python file, checkout `:CocList services`.

**Comment by pavanscoding** [comment]
Thanks, I figured out how to uninstall coc-python and then I install pyright which worked. Thank you so much for your help.
