### ISSUE TITLE
Add Option to Use Tag Stack Rather Than Cursor Jump List

### ISSUE THREAD

**Issue by ewhac** [neoclide/coc.nvim#3004]
**Is your feature request related to a problem? Please describe.**
I have a lot of muscle memory for the keystrokes `^]` and `^T` back when cscope and tag list generators were the best Vim users could hope for (indeed, the help text for the keystroke `^]` is, "Jump to the definition of the keyword under the cursor").  Also, the tag stack is maintained as a strict LIFO stack specifically for "tags" i.e. things expressly searched for, whereas the jump list will accumulate any large-ish cursor movement.

**Describe the solution you'd like**
Add an option to use the tag stack when jumping to definitions, declarations, or references.

**Comment by chemzqm** [comment]
:h CocTagFunc

**Comment by ewhac** [comment]
`CocTagFunc()` is intended to be assigned via `:se tagfunc`.  However, `tagfunc` isn't available in neovim 0.4.x; and 0.5.x isn't officially released yet.  (Yeah, 0.5.0-dev is available from Ubuntu, but not from official Debian (not even experimental).)

**Comment by chemzqm** [comment]
Use neovim 0.4 or implment it yourself, `:h CocLocationsChange`
