### ISSUE TITLE
Making Coc.nvim intellisense work inside docker containers

### ISSUE THREAD

**Issue by ankitpal1029** [neoclide/coc.nvim#3007]
Hey guys i'm new to docker developement ,
i have noticed that when doing angular dev inside a docker container coc tsserver isn't able to provide import information and keeps complaining that no such module exists the same goes with the django server inside the container.

Is there something that sorts this issue already or is some feature like this in the works already?
Great job on the plugin it really makes my editing experience amazing

**Comment by fannheyward** [comment]
Do you have installed language server in docker container? Does your angular project has dependences installed in container?

**Comment by ankitpal1029** [comment]
@fannheyward i'm not sure how to check these ,although i'm pretty sure angular dependencies are installed since the project works
Note: i didn't make the project from ground up hence the lack of knowledge regarding the same

**Comment by chemzqm** [comment]
>  coc tsserver isn't able to provide import information and keeps complaining that no such module exists the same goes with the django server inside the container.

Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
