### ISSUE TITLE
CocConfig settings are not honored in lua files

### ISSUE THREAD

**Issue by reportaman** [neoclide/coc.nvim#3011]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-dev+nightly-120-g1186f7dd9
node version: v15.11.0
coc.nvim version: 0.0.80-bd41b16bd9
coc.nvim directory: /Users/reportaman/.vim/plugged/coc.nvim
term: WezTerm
platform: darwin

## Log of coc.nvim

2021-04-03T11:05:47.203 INFO (pid:1719) [coc-tabnine] - Using tabnine from /Users/reportaman/.config/coc/extensions/coc-tabnine-data/binaries/3.3.104/aarch64-apple-darwin/TabNine
2021-04-03T11:05:47.205 INFO (pid:1719) [plugin] - coc.nvim 0.0.80-bd41b16bd9 initialized with node: v15.11.0 after 47ms
2021-04-03T11:05:50.789 INFO (pid:1719) [attach] - receive notification: showInfo []
```

## Describe the bug

``"suggest.minTriggerInputLength": 2`` is not honored in ``.lua`` files. I am using [coc-lua](https://github.com/josa42/coc-lua). It starts triggering right after I type 1 character instead of waiting for 2, it doesn't seem to honor other settings like ``"suggest.triggerCompletionWait": 500`` either. The reason I am filing this here is: these options should be global options, and apply irrespective of what [coc-lua](https://github.com/josa42/coc-lua) does internally.

## Reproduce the bug

File ``mini.vim``
  ```vim
set nocompatible
set runtimepath^=/Users/reportaman/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden 
```

File ``~/.config/nvim/coc-settings.json``
```json
{
"Lua.telemetry.enable": false,
"Lua.workspace.maxPreload": 0,
"Lua.workspace.library": {},
"Lua.diagnostics.enable": false,
"Lua.workspace.useGitIgnore": true,
"suggest.minTriggerInputLength": 2,
"suggest.triggerCompletionWait": 500,
"suggest.removeDuplicateItems": true
}
```

- Start (neo)vim with command: `nvim -u mini.vim`
- ``:e <someluafile.lua>``.
- Enter insert mode ``press i``, and type one character ``f`` (at this point pum will become visible, and show a bunch of suggestions)

**Comment by chemzqm** [comment]
it could be trigger character or trigger pattern matched
