### ISSUE TITLE
New window creation issues (for jump to definition etc) with noequalalways (E36)

### ISSUE THREAD

**Issue by nfd** [neoclide/coc.nvim#3012]
## versions

vim version: NVIM v0.4.4
node version: v12.18.3
coc.nvim version: 0.0.80-71b343c4ba
coc.nvim directory: (my home dir)/.config/nvim/pack/allofthem/start/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-04-04T02:06:56.077 INFO (pid:40326) [plugin] - coc.nvim 0.0.80-71b343c4ba initialized with node: v12.18.3 after 47ms
2021-04-04T02:06:58.393 INFO (pid:40326) [attach] - receive notification: showInfo []

## Describe the bug

When noequalalways is set, coc can't open its definition window when noequalalways is set.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  set noequalalways
  ```
(Note only change from template is addition of `set noequalalways`)

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

Create a file which produces multiple definitions, such as:
```python
duplicate = "hello"

def duplicate():
    pass

duplicate
```
Move the cursor to the last line and type `:call CocAction("jumpDefinition")`

You will see the error `[coc.nvim] request error nvim_call_function - Vim(sbuffer):E36: Not enough room`.

I have worked around it in the following way in my vimrc:

```vim
function s:vim_noequalalways_hack()
	if &buftype == "nofile"
		set equalalways
	else
		set noequalalways
	endif
endfunction

autocmd WinEnter,BufEnter * call s:vim_noequalalways_hack()
```

**Comment by fannheyward** [comment]
I can't reproduce this, for `nofile` buffer, `call CocAction("jumpDefinition")` will error

```
Error on request (jumpDefinition): Vim(return):Error invoking 'jumpDefinition' on channel 3
definition provider not found for current buffer, your language server don't support it.
```

because there's is no language server defined for current buffer, coc won't work.

**Comment by fannheyward** [comment]
I can reproduce this error with your code on `python` filetype.

**Comment by chemzqm** [comment]
It's global option which we won't change for user.
