### ISSUE TITLE
Match SignColumn bg in diagnostic sign highlights

### ISSUE THREAD

**Issue by ehandal** [neoclide/coc.nvim#3013]
The highlight used for signs defaults to the normal background color. Might look nicer if the background matched the SignColumn background.

I know it's possible to query the background color of SignColumn like so:

gui: `:echo synIDattr(synIDtrans(hlID("SignColumn")), "bg", "gui")`
cterm: `:echo synIDattr(synIDtrans(hlID("SignColumn")), "bg", "cterm")`

Could the Coc*Sign highlight groups use these to make the signs match the colorscheme a bit better?

**Comment by chemzqm** [comment]
The background could be omitted, no need for that function

**Comment by ehandal** [comment]
Sorry, I'm confused. My signs currently look like this:

![image](https://user-images.githubusercontent.com/23243879/113894490-a9ce8900-978d-11eb-808c-e8fc14dc2ed1.png)

The sign's background doesn't match the rest of the sign column _because_ the background is omitted, right? Instead it matches the normal background. To get it to match, the background would have to be set to match the SignColumn bg, no?

**Comment by ehandal** [comment]
@chemzqm just wanted to get your thoughts on the prior comment. Feel free to close if this is intended behavior.
