### ISSUE TITLE
Closing CocList or coc-codeaction with ctrl+c results missing cursor

### ISSUE THREAD

**Issue by Racle** [neoclide/coc.nvim#3016]
### versions

vim version: NVIM v0.5.0-dev
node version: v12.22.1
coc.nvim version: 0.0.80-2cece2600a
coc.nvim directory: ~/.local/share/nvim/plugged/coc.nvim
term: screen-256color
platform: linux

### Log of coc.nvim

2021-04-08T13:05:24.296 INFO (pid:534382) [plugin] - coc.nvim 0.0.80-2cece2600a initialized with node: v12.22.1 after 220ms
2021-04-08T13:05:24.310 INFO (pid:534382) [language-client-index] - cSpell started with 534394
2021-04-08T13:05:29.706 INFO (pid:534382) [attach] - receive notification: openList []
2021-04-08T13:05:29.711 INFO (pid:534382) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 2 ]
2021-04-08T13:05:29.712 INFO (pid:534382) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 2 ]
2021-04-08T13:05:29.714 INFO (pid:534382) [attach] - receive notification: doAutocmd [ 1 ]
2021-04-08T13:05:31.113 INFO (pid:534382) [attach] - receive notification: doAutocmd [ 1 ]
2021-04-08T13:05:47.969 INFO (pid:534382) [attach] - receive notification: showInfo []

## Describe the bug

Closing CocList or coc-codeaction with `Ctrl+c` causes cursor to be hidden. There might be other places where this happens, but those are ones I found.

## Reproduce the bug

  ```vim
set termguicolors
call plug#begin(stdpath('data') . '/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
  ```
Run `:CocList`, press `Ctrl+c` couple times. 

Note: without `set termguicolors` you get very thin cursor.

## Screenshots (optional)
Before: 
![image](https://user-images.githubusercontent.com/759091/114007039-a4df0780-9869-11eb-8641-7368f0a7010b.png)
After running CocList and closing with `Ctrl+c`: (cursor is in same place in normal mode)
![image](https://user-images.githubusercontent.com/759091/114007150-c2ac6c80-9869-11eb-9fde-15176944fb52.png)

## Hack fixes

I got few "fixes" for this situation. I personally use `Ctrl+c` a lot and `<Esc>`  only rarely, so I hide my cursor accidentally sometimes.

Fixes what I've used:

1. Open `:CocList` again and exit with `<Esc>`. Cursor will be normal again
2. Add this function to your vimrc and run `:CursorFix` to reset your cursor
```vim
function! CursorFix()
  set guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20
endfunction

command! CursorFix call CursorFix()
```
3. Close and reopen neovim

**Comment by fannheyward** [comment]
Set these to your coc-settings.json:

```
  "list.normalMappings": {
    "<C-c>": "do:exit"
  },
  "list.insertMappings": {
    "<C-c>": "do:exit"
  },
```

**Comment by Racle** [comment]
@fannheyward 
> Set these to your coc-settings.json:
> 
> ```
>   "list.normalMappings": {
>     "<C-c>": "do:exit"
>   },
>   "list.insertMappings": {
>     "<C-c>": "do:exit"
>   },
> ```

Oh yeah, I forgot that coc settings file... Those **doesn't work** (already tried those before I made this issue and they were preset when creating this issue). Issue still exists.

My full coc-settings.json
``` 
{
  "pairs.enableCharacters": ["(", "[", "{", "'", "\"", "`"],
  "snippets.userSnippetsDirectory": "~/.config/nvim/snips",
  "snippets.ultisnips.enable": false,
  "explorer.icon.enableNerdfont": true,
  "yaml.schemas": {
    "https://json.schemastore.org/ansible-stable-2.9": "**/*.ans.yml",
    "https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json": "**/docker-compose*.yml"
  },
  "coc.preferences.currentFunctionSymbolAutoUpdate": true,
  "cSpell.enabled": false,
  "cSpell.userWords": ["Dotfiles"],
  "intelephense.licenceKey": "XXXXXXXXXXXX",
  "suggest.completionItemKindLabels": {
    "variable": "\uf71b",
    "constant": "\uf8ff",
    "struct": "\ufb44",
    "class": "\uf0e8",
    "interface": "\ufa52",
    "text": "\ue612",
    "enum": "\uf435",
    "enumMember": "\uf02b",
    "color": "\ue22b",
    "property": "\ufab6",
    "field": "\uf93d",
    "unit": "\uf475",
    "file": "\uf471",
    "value": "\uf8a3",
    "event": "\ufacd",
    "folder": "\uf115",
    "keyword": "\uf893",
    "snippet": "\uf64d",
    "operator": "\uf915",
    "reference": "\uf87a",
    "typeParameter": "\uf278",
    "default": "\uf29c"
  },
  "list.normalMappings": {
    "<C-c>": "do:exit"
  },
  "list.insertMappings": {
    "<C-c>": "do:exit"
  }
}
```

**Comment by chemzqm** [comment]
`:h g:coc_disable_transparent_cursor`

**Comment by Racle** [comment]
> It's expected behavior since it's impossible for plugin to detect ctrl+c.
> Avoid `ctrl+c` or disable transparent cursor.
> 
> `:h g:coc_disable_transparent_cursor`

This works :+1:. And much better fix than my hacks..

**Comment by unphased** [comment]
Why is there no "list.commandMappings" setting? Command is a mode and probably the one that this problem is caused by... we're in command mode when we interrupt and the cursor stays in the hidden state. 

Anyway, thanks for the name of the variable to disable hidden cursor. I think this is the biggest out of the box flaw with coc that exists.
