### ISSUE TITLE
How to disable floating window for code actions?

### ISSUE THREAD

**Issue by isovector** [neoclide/coc.nvim#3020]
**Is your feature request related to a problem? Please describe.**

I've recently updated Coc, and all of a sudden, have floating windows all over the place. I'd prefer to disable them and use FZF instead for dialog choices, but after pouring over the documentation for an hour, I haven't figured out how to do it.

**Describe the solution you'd like**

I'd like to have code action suggestions pop up at the bottom of my screen, managed by FZF, not in a floating window.

**Comment by chemzqm** [comment]
Sorry, no option to support fzf, you can disable that float

**Comment by isovector** [comment]
I'm sorry for being stupid here --- maybe FZF was the wrong word. 

What I meant is that old versions of coc used to show this dialog instead of the float:

![2021-04-11-111404_580x347_scrot](https://user-images.githubusercontent.com/307223/114316172-4ad38180-9ab7-11eb-9ef1-302eec90f1ad.png)

Does this functionality still exist? I greatly prefer it over the floating windows (since it automatically chooses if there is only a single code action, and doesn't change the number of the next buffer.)

` :h coc-config-dialog` has options for changing the size and highlight groups, but nothing that obviously disables floating windows. Is it still possible?

**Comment by chemzqm** [comment]
`"coc.preferences.floatActions": fasle`

**Comment by isovector** [comment]
Thanks so much, extremely appreciated.

**Comment by christopher-francisco** [comment]
@chemzqm where should I place that? which file?

**Comment by fannheyward** [comment]
> @chemzqm where should I place that? which file?

coc-settings.json, you can open it by `:CocConfig`.

**Comment by chemzqm** [comment]
Fixed by 8c3445ad
