### ISSUE TITLE
Use project root instead of cwd by default when starting custom languageserver

### ISSUE THREAD

**Issue by smackesey** [neoclide/coc.nvim#3021]
**Is your feature request related to a problem? Please describe.**
When configuring a custom language server (no extension), you have two options to set the cwd used to start the process:

- provide `cwd` option
- Vim's cwd will be used

In some cases, a project root detection solution (that changes Vim's cwd) may run *after* CoC attempts to start a service. This means that if you don't provide the `cwd` explicitly, CoC will use a wrong `cwd` (not the project root) to start the service, even when CoC correctly detects the project root.

**Describe the solution you'd like**
Instead of using Vim's cwd as the default directory to start the service, use the project root that CoC detects. This is also more intuitive since you can provide `rootPatterns` to the language server options.

**Describe alternatives you've considered**
The only alternative I've found is to explicitly set the cwd option for each project that uses the language server. This is not good.

**Additional context**

**Comment by chemzqm** [comment]
The language server should use workspace folders
