### ISSUE TITLE
[Bug] Cannot run VSCode extension based AutoHotkey (AHK) LSP Servers

### ISSUE THREAD

**Issue by pidgeon777** [neoclide/coc.nvim#3023]
## Describe the bug

I'm try to enable AHK (Autohotkey) LSP servers available here:

https://marketplace.visualstudio.com/items?itemName=helsmy.ahk-simple-ls

https://marketplace.visualstudio.com/items?itemName=thqby.vscode-autohotkey2-lsp

I downloaded the .vsix extensions and extracted the server.js files.

See here for more info:

https://github.com/helsmy/vscode-autohotkey/issues/12

## Result from CocInfo

````
## versions

vim version: NVIM v0.4.4
node version: v14.15.4
coc.nvim version: 0.0.80-6e5a2aaeb5
coc.nvim directory: C:\Users\pcuser\.vim\bundle\coc.nvim
term: vtpcon
platform: win32

## Log of coc.nvim

2021-04-12T14:58:05.797 INFO (pid:15252) [coc-tabnine] - Using tabnine from C:\Users\pcuser\AppData\Local\coc\extensions\coc-tabnine-data\binaries\3.3.108\x86_64-pc-windows-gnu\TabNine.exe
2021-04-12T14:58:05.805 INFO (pid:15252) [plugin] - coc.nvim 0.0.80-6e5a2aaeb5 initialized with node: v14.15.4 after 430ms
2021-04-12T14:59:03.625 INFO (pid:15252) [attach] - receive notification: showInfo []
````

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## coc-settings.json

````
{
	// -----------------------------
	// Language Servers
	// -----------------------------
	// Dictionary of languageservers, key is used as id of languageserver.
	"languageserver": {
		// AHK
		// https://github.com/helsmy/vscode-autohotkey/issues/12
		"Autohotkey":{
			// "module": "C:/Users/pcuser/AppData/Local/Temp/c3586cb88bb67aac45c3c5355c8469/extension/server/out/server.js",
			"module": "C:/Users/pcuser/AppData/Local/Temp/c3586cb88bb67aac45c3c5355c8469/Nuova cartella/extension/server/dist/server.js",
			"args": ["--node-ipc"],
			"filetypes": ["ahk"],
			"trace.server": "verbose"
			// documentLanguage : "no"
		}
	}
}
````

## Setup

A valid AHK file is the only active buffer in the Neovim session.

:tcd points to that file.

## :CocList services 

![image](https://user-images.githubusercontent.com/13739892/114402099-cc084280-9ba3-11eb-9f3c-29851a7d70a7.png)

## :CocCommand document.echoFiletype

autohotkey

## :CocCommand workspace.showOutput

![image](https://user-images.githubusercontent.com/13739892/114402190-e0e4d600-9ba3-11eb-8c98-4197bc5215b2.png)

## Tests

Commands such as:

- Hover
- Goto Definition
- Goto References
...

seem not to be detected as available.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by pidgeon777** [comment]
Hello I tried to to as you suggested.

The fact is that when I execute `:CocList services`, I obtain:

![image](https://user-images.githubusercontent.com/13739892/114402099-cc084280-9ba3-11eb-9f3c-29851a7d70a7.png)

As you can notice, AHK LSP server is in the `init`, not `running` state.

When I execute `:CocCommand workspace.showOutput`, I obtain:

![image](https://user-images.githubusercontent.com/13739892/114402190-e0e4d600-9ba3-11eb-8c98-4197bc5215b2.png)

The AHK server is missing, even if in my `coc-settings.json` file I added the `"trace.server": "verbose"` element to the AHK LSP server config.

**Comment by pidgeon777** [comment]
Also, the two LSP servers I'm trying to integrate into coc.nvim successfully work in VSCode, and according to their description they're based on Microsoft LSP. Maybe there is something special to configure/add to be able to also use them with the coc.nvim LSP client? Otherwise, I couldn't explain to myself how they could work with VSCode LSP.

I'm willing to contact the two extension developers, pointing them to the necessary steps to try to add this missing linking point, but I wouldn't know where to start.

**Comment by fannheyward** [comment]
Change `"filetypes": ["ahk"],` to `"filetypes": ["autohotkey"],` in your coc-settings.json and try again.

**Comment by pidgeon777** [comment]
I've to say that: it now works. Excellent issue pinpointing.

I'm testing both the VSCode extensions I aforementioned, I'll post a report of the outcome here.

**Comment by pidgeon777** [comment]
Hoping it might help someone, I compared the current versions of the two Visual Studio Code AHK LSP extensions running into Neovim.

**AutoHotKey2 Language Support by thqby** (v0.6.1) - https://gitee.com/orz707/vscode-autohotkey2-lsp

**AutoHotKey Simple Support by Helsmy** (v0.5.4) - https://github.com/helsmy/vscode-autohotkey

Here are the differences:

# Rename

**AutoHotKey2 Language Support by thqby**

![image](https://user-images.githubusercontent.com/13739892/114539251-98392580-9c54-11eb-9ceb-f6a63fe1ea58.png)

**AutoHotKey Simple Support by Helsmy**

N/A

# Diagnostic

**AutoHotKey2 Language Support by thqby**

![image](https://user-images.githubusercontent.com/13739892/114539398-c28ae300-9c54-11eb-954a-53b1b53f4c45.png)

**AutoHotKey Simple Support by Helsmy**

N/A

# IntelliSense

**AutoHotKey2 Language Support by thqby**

![image](https://user-images.githubusercontent.com/13739892/114539443-ccace180-9c54-11eb-8ef2-16f4887c0efd.png)

Note: parenthesis is added because some of the AutoHotkey commands are considered as a C-style functions:

![image](https://user-images.githubusercontent.com/13739892/114539470-d20a2c00-9c54-11eb-9a6f-29b3a44ad034.png)

But IntelliSense works anyway:

![image](https://user-images.githubusercontent.com/13739892/114539493-d59db300-9c54-11eb-87ba-2cce71275800.png)

Note: when choosing the `MsgBox` command, all of its arguments should have been inserted into the buffer, eventually jumping between them through the placeholder jump hotkey (e.g. Ctrl+j).

Take as reference the behaviour of clangd/ccls LSPs when switching through the function arguments.

**AutoHotKey Simple Support by Helsmy**

Note: `MsgBox` arguments documentation is missing:

![image](https://user-images.githubusercontent.com/13739892/114544702-4516a100-9c5b-11eb-9a8c-19c0487a0cba.png)

# Snippets

**AutoHotKey2 Language Support by thqby**

![image](https://user-images.githubusercontent.com/13739892/114539521-ddf5ee00-9c54-11eb-9304-52b8d366a730.png)

**AutoHotKey Simple Support by Helsmy**

N/A

# Signature

**AutoHotKey2 Language Support by thqby**

![image](https://user-images.githubusercontent.com/13739892/114539544-e3533880-9c54-11eb-85c6-96138d0f1332.png)

**AutoHotKey Simple Support by Helsmy**

Note: doesn't seem to properly work. All of the `MsgBox` arguments should have been displayed:

![image](https://user-images.githubusercontent.com/13739892/114544897-8b6c0000-9c5b-11eb-8535-abd2f1a5d32c.png)

# Document Symbols

**AutoHotKey2 Language Support by thqby**

840 symbols found:

![image](https://user-images.githubusercontent.com/13739892/114539565-e9491980-9c54-11eb-8067-2322bdfa0dcf.png)

**AutoHotKey Simple Support by Helsmy**

390 symbols found:

![image](https://user-images.githubusercontent.com/13739892/114545939-dc302880-9c5c-11eb-8ad9-79c15e737bf5.png)

# Hover

**AutoHotKey2 Language Support by thqby**

![image](https://user-images.githubusercontent.com/13739892/114539604-f0702780-9c54-11eb-8a56-b5a93e9382e9.png)

**AutoHotKey Simple Support by Helsmy**

N/A

# Goto Definition

**AutoHotKey2 Language Support by thqby**

Works for:

- Variables
- Functions
- Keywords
 - Includes

**AutoHotKey Simple Support by Helsmy**

- Variables
- Functions

# Find All References

**AutoHotKey2 Language Support by thqby**

![image](https://user-images.githubusercontent.com/13739892/114539637-f7973580-9c54-11eb-9987-852042c485aa.png)

**AutoHotKey Simple Support by Helsmy**

N/A

# Code Format

**AutoHotKey2 Language Support by thqby**

Before:

![image](https://user-images.githubusercontent.com/13739892/114539655-fe25ad00-9c54-11eb-9535-09ed9fb4b120.png)

After:

![image](https://user-images.githubusercontent.com/13739892/114539678-01b93400-9c55-11eb-9533-fe119d36338f.png)

**AutoHotKey Simple Support by Helsmy**

N/A

# Final Conclusions

- The extension provided by thqby currently seems to be much more complete and LSP compliant.
- The extension provided by @helsmy is currently under active development, and hopefully one day the missing features will be added.

Note: I do not guarantee to have tested all of the functions currently provided by the two extensions.

**Comment by kintsugi** [comment]
Anyone got this working from inside of WSL? I'm still deducing problems, but changing the coc config in the OP to have the proper extension directory to one with a windows path (e.g. "C:\..." under c or a WSL path (typical unix path) both inside and out of the wsl vm has been unsuccessful.

I would post my config but since I'm still tinkering it basically is the same as the OP, I will ASAP though.
