### ISSUE TITLE
question about show documentation

### ISSUE THREAD

**Issue by butterywombat** [neoclide/coc.nvim#3025]
Hi, when I use the binding `nnoremap <silent> K :call <SID>show_documentation()<CR>` (which does `call CocAction('doHover')`
) to show documentation on the `calledOnceWith`, I get this:
<img width="564" alt="Screen Shot 2021-04-12 at 5 12 43 PM" src="https://user-images.githubusercontent.com/485316/114478156-83a45100-9bb2-11eb-88be-82b9a066ffe8.png">

however when I am typing, right after the parens I get the actual documentation:
<img width="851" alt="Screen Shot 2021-04-12 at 5 12 35 PM" src="https://user-images.githubusercontent.com/485316/114478162-84d57e00-9bb2-11eb-9c0f-5116debce175.png">

In other cases I see that they're similar and both the definitions, but wondering how I can always get the last ss's behavior of full documentation. I didn't make a bug ticket as I'm not sure if this is a bug.
Thanks for any help!

**Comment by fannheyward** [comment]
Have no idea, both the hover document and function signatureHelp are from language server, properly it's a LS issue.

**Comment by butterywombat** [comment]
hmm, how could I test the signatureHelp? I tried `:call CocActionAsync('showSignatureHelp')<CR>` but it doesn't do anything

**Comment by fannheyward** [comment]
The document shows in your second screenshot is called signatureHelp.

**Comment by butterywombat** [comment]
@fannheyward yeah, wondering if I can map K to that somehow, instead of to `doHover`

**Comment by fannheyward** [comment]
The problem is not use signatureHelp instead of hover, but why LS doesn't return document on hover request.

**Comment by butterywombat** [comment]
Currently I'm using `let heapTrackEventSpy;` at the top and setting it later. I see that if I use `const heapTrackEventSpy = sinon.spy(...)` then the show documentation works later if that helps

**Comment by fannheyward** [comment]
Do you use coc-tsserver? I haven't used Sinon, just do a quick test:

```
    const fail = sinon.spy();
    fail.calledOnceWith()
```
<img width="547" alt="截屏2021-04-13 上午9 18 52" src="https://user-images.githubusercontent.com/345274/114482510-4636d680-9c39-11eb-9cc9-8ea39fe69d6a.png">

both hover document and sinatureHelp are working.

```
  "devDependencies": {
    "@types/jest": "^26.0.22",
    "@types/sinon": "^9.0.11",
    "sinon": "^10.0.0"
  }
```

**Comment by butterywombat** [comment]
@fannheyward yes I do use coc-tsserver. is it suppose to work if you do
```
let fail;
fail = sinon.spy()
fail.calledOnceWith()

?

**Comment by fannheyward** [comment]
No, `calledOnceWith` documents `any`.

**Comment by butterywombat** [comment]
I see. my project doesn't use TS yet. Just curious why the signatureHelp works even without setting the type, but hover doesn't

**Comment by fannheyward** [comment]
Tested with VSCode, same `any` document. Properly it's tsserver issue.
