### ISSUE TITLE
Command to toggle diagnostics per buffer

### ISSUE THREAD

**Issue by Mange** [neoclide/coc.nvim#3027]
**Is your feature request related to a problem? Please describe.**

Sometimes I open a file that will have a lot of diagnostics problems. It could be, for example, a YAML file with a lot of mustache template tags (for use with Helm). This means the file is completely broken from a YAML parser's perspective, and everything will be full of errors.

This is distracting to work with.

**Describe the solution you'd like**

ALE has a command called `:ALEToggleBuffer` that turns on and off its linter for the current buffer. A similar command for CoC would be swell; in that case I could quickly turn off diagnostics for this file while still have working diagnostics for other files I have opened.

**Describe alternatives you've considered**

Turning off diagnostics globally using `:call CocAction('diagnosticToggle')`, but this affects all buffers.

**Additional context**

![Screenshot of the issue](https://user-images.githubusercontent.com/1599/114510775-5a79d400-9c37-11eb-9b44-06fd4adbd9cf.png)

Other cases where I would want this feature:

- When working with languages that have alpha-level LSP support and their diagnostics freak out.
- When working with CSS files using `postcss` and `tailwind` as it leads to a lot of errors with `coc-css`, but only in those files.
- When opening a minified JS file.
  - Alternative solution: An `autocmd` could match on `*.min.js` and disable for the buffer using `b:coc_diagnostic_disable`, I think. Some minified files don't follow "min.js", though.
- When opening a file from a vendored project that doesn't follow my own personal linting rules; at which point I don't want diagnostics.

-----

Thank you for this project! I love it! :heart:

**Comment by chemzqm** [comment]
Fixed by f0e38d6e

**Comment by Mange** [comment]
Thank you so much! :heart:
