### ISSUE TITLE
Is it possible to suppress the error [coc.nvim]: Error on notification "doHover"?

### ISSUE THREAD

**Issue by nyngwang** [neoclide/coc.nvim#3029]
**Is your feature request related to a problem? Please describe.**

Indeed I'm not sure about whether this is a bug. But anyway I choose the feature request option.

I have this two lines in my vimrc:

    autocmd CursorHold * silent call CocActionAsync('highlight')
    autocmd CursorHold * silent call CocActionAsync('doHover')

And it works well when editing files that support so call _hover provider_:

[<img src="https://user-images.githubusercontent.com/24765272/114644599-61bde200-9d0a-11eb-9037-229ae1e75c3b.png" width="400">](https://user-images.githubusercontent.com/24765272/114644599-61bde200-9d0a-11eb-9037-229ae1e75c3b.png)

but inside the filetype(s) which doesn't support it will show this error:

[<img src="https://user-images.githubusercontent.com/24765272/114644701-9a5dbb80-9d0a-11eb-8326-2640835a01a4.png" width="400">](https://user-images.githubusercontent.com/24765272/114644701-9a5dbb80-9d0a-11eb-8326-2640835a01a4.png)

But since I already put `silent` before the `call`, this error is supposed to be no showing.

**Describe the solution you'd like**

I would like to have a command like:

    CocActionAsync('doHover', 0)         " 0 means don't show the error.

**Describe alternatives you've considered**

I just let the error be shown.

**Additional context**

MacOSX 11.2.3 
alacritty: 0.7.2
NVIM v0.5.0-dev+6db3ba9

**Comment by chemzqm** [comment]
Write vim function with filetype check.

**Comment by nyngwang** [comment]
The problem is solved by these two lines:

    let blacklist = ['vim', 'help']
    autocmd CursorHold * if (index(blacklist, &ft) < 0 || !coc#rpc#ready()) | silent! call CocActionAsync('doHover')
