### ISSUE TITLE
Unexpected new line while press <CR> to accept a suggestion

### ISSUE THREAD

**Issue by lancelock** [neoclide/coc.nvim#3031]
## Result from CocInfo

vim version: VIM - Vi IMproved 8.2 8022550
node version: v15.11.0
coc.nvim version: 0.0.80-6e5a2aaeb5
coc.nvim directory: /Users/vixmatric/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Describe the bug

Sometimes i press <CR> to accept a suggestion, it will insert a new line and move the cursor to the new line，that's not what i expected

## Reproduce the bug

Related keybinding，copy from the README file

" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

## Screenshots (optional)

![unexpected-new-line](https://user-images.githubusercontent.com/13751352/114822282-665ec500-9df4-11eb-80a5-06e2e31a7a9e.gif)

**Comment by chemzqm** [comment]
Can't understand

**Comment by lancelock** [comment]
@chemzqm 如图，我按一下回车键补全user这个词，期望是继续留在这一行，继续输入，但是自动换行了并且光标移动到了新的一行

**Comment by chemzqm** [comment]
我看不明白

**Comment by PangPangPangPangPang** [comment]
我也有同样问题，使用了下面这个 map
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
            \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
现象是：
 当用 <enter> 触发了选择补全的时候不会在当前的位置进入 insert 模式，而是会在光标上方新插入一行并且进入 insert 模式。

**Comment by nima-dvlp** [comment]
I have the same problem, and same file type JavaScript/Typescript, but not in Rust, Flutter/Dart, Vim, etc.

**Comment by chemzqm** [comment]
Need minimal vimrc and verbose output from language server, please open a new issue.
