### ISSUE TITLE
Offline server installation

### ISSUE THREAD

**Issue by Mat-R** [neoclide/coc.nvim#3033]
Is there a way to install a server (e.g. doing :CocInstall coc-clangd coc-json) offline? I have the possibility to manually copy files to my machine but I cannot access the Internet directly.

I am using vim 8.

**Comment by chemzqm** [comment]
Copy the files needed

**Comment by Mat-R** [comment]
Yes obviously. Would you mind being more precise? Which files? Where?

**Comment by fannheyward** [comment]
Extensions are installed into `~/.config/coc/extensions`.

**Comment by Mat-R** [comment]
Thanks

**Comment by lixiaoquan** [comment]
Somehow I have to update extensions/package.json manually to make a copied extension (coc-clangd) work, is it expected?

**Comment by SebastianBehrens** [comment]
> Extensions are installed into `~/.config/coc/extensions`.

What would be the location on offline windows machines?

**Comment by SebastianBehrens** [comment]
Unfortunately, even after copying the files into the location for extensions (~/AppData/Local/coc/extensions/node_modules on windows) `:CocList extensions` does not list the respective object. What does one need to do besides manually placing extension files there?

**Comment by fannheyward** [comment]
@SebastianBehrens `~/AppData/Local/coc`.

**Comment by fannheyward** [comment]
@SebastianBehrens do you copy the `~/AppData/Local/coc/extensions/package.json` file?

**Comment by SebastianBehrens** [comment]
@fannheyward I took the folder such as [this one](https://github.com/kristijanhusak/vim-dadbod-completion) copy the zip to the offline machine, unzip it and place it in  `~/AppData/Local/coc/extensions/`. There is a `package.json` in that [repo](https://github.com/kristijanhusak/vim-dadbod-completion/blob/master/package.json).
What am I doing wrong?
