### ISSUE TITLE
duplicate entries for `coc-definition`

### ISSUE THREAD

**Issue by rust-shell-script** [neoclide/coc.nvim#3034]
## Describe the bug

When using both "ccls" and "coc-clangd", press "gd"(coc-definition) will show duplicate entries to choose from. It would be nice to only contain unique locations. The fix might be related to #1184.

## Reproduce the bug

- run with both plugins "ccls" and "coc-clangd".
- `CocList services` shows both `languageserver.ccls` and `clangd` are running
- press `gd`(for coc-definition), there will be duplicate location entries

**Comment by chemzqm** [comment]
Fixed by cd0cdddd
