### ISSUE TITLE
Support maxTokenizationLineLength like vscode to improve performance.

### ISSUE THREAD

**Issue by jackhub** [neoclide/coc.nvim#3036]
when open a large JS build file ( just one line ), coc highlight use a lot of time.

When open with vscode it's very fast and alert tokenization is skipped like this: 

Tokenization is skipped for long lines for performance reasons. The length of a long line can be configured via `editor.maxTokenizationLineLength`.

Maybe coc.nvim can add this feature.

**Comment by chemzqm** [comment]
It should be issue with your syntax plugin, not coc.nvim.
There is `synmaxcol` option.
