### ISSUE TITLE
Go to definition and back

### ISSUE THREAD

**Issue by normenmueller** [neoclide/coc.nvim#3044]
**Is your feature request related to a problem? Please describe.**
Using the [example config](https://github.com/neoclide/coc.nvim#example-vim-configuration), `gd` enables me to go to a definition, but not to get back from where I came. Either I don't know how to do that, or it may be considered a feature request.

**Describe the solution you'd like**
Similar to vim

Jump to a subject:  Position the cursor on a tag (e.g. |bars|) and hit CTRL-].
Jump back:  Type CTRL-O.  Repeat to go further back.

**Describe alternatives you've considered**
I alternatively use hasktags.

**Additional context**
n/a

**Comment by fannheyward** [comment]
`gd` goes to definition, `C-o` can go back.

**Comment by violin0622** [comment]
I'm writing golang and using gopls .
I found after using `gd` go to definition, I have to press <C-O> twice to go back :
First time it goes to somewhere I don't know, second time goes to source position. 

Another question is , when I use 'jumpDefinition' with 'drop' , <C-O> can't  switch to tab caontaining source file. 

Any idea can solve the problems?

**Comment by chemzqm** [comment]
Try minimal vimrc.
You should use tab drop.

**Comment by gh-liu** [comment]
> I'm writing golang and using gopls .
> I found after using `gd` go to definition, I have to press twice to go back :
> First time it goes to somewhere I don't know, second time goes to source position.
> 
> Another question is , when I use 'jumpDefinition' with 'drop' , can't switch to tab caontaining source file.
> 
> Any idea can solve the problems?

I have the same problem of `go to definition and back`, have you solved it?

**Comment by fannheyward** [comment]
@gh-liu you can set `:h CocTagFunc`,  the `gd` goto definition and `C-t` back.

**Comment by ptzz** [comment]
I have the same problem. If `coc-definition` opens a new buffer (i.e. the file with the definition is not in a vim buffer), I need to press ctrl-o twice to get back. The first ctrl-o goes to the beginning of the file containing the definition.

If repeating the process, with the file containing definition now in a buffer, it works as expected.

It looks like an unwanted jumplist entry is created when the file containing the definition is not an existing buffer. Line 1 in the opened file is added to jumplist.

I'm using ccls, not sure that's relevant though.
