### ISSUE TITLE
[Question] How to get coc.nvim working with call hierarchies

### ISSUE THREAD

**Issue by g-suraj** [neoclide/coc.nvim#3046]
How would I go about using the new call hierarchy features from clangd12? This is `textDocument/callHierarchy` and is [documented here](https://releases.llvm.org/12.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#new-navigation-features)

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/issues/1649 and https://github.com/neoclide/coc.nvim/pull/2756.
