### ISSUE TITLE
Calling nvim_win_set_config() on tooltip sometimes displaces tooltip scroll

### ISSUE THREAD

**Issue by BitPusher16** [neoclide/coc.nvim#3047]
## Result from CocInfo

  1 ## versions                                                                                                       
  2                                                                                                                   
  3 vim version: NVIM v0.4.3                                                                                          
  4 node version: v16.0.0                                                                                             
  5 coc.nvim version: 0.0.80-bf98939a8c                                                                               
  6 coc.nvim directory: /home/foo/.vim/plugged/coc.nvim                                                               
  7 term: screen-256color                                                                                             
  8 platform: linux                                                                                                   
  9                                                                                                                   
 10 ## Log of coc.nvim                                                                                                
 11                                                                                                                   
 12 2021-04-24T15:00:15.310 INFO (pid:230) [coc-git] - Looking for git in: git                                        
 13 2021-04-24T15:00:15.346 INFO (pid:230) [plugin] - coc.nvim 0.0.80-bf98939a8c initialized with node: v16.0.0 after 
 14 2021-04-24T15:00:17.166 INFO (pid:230) [attach] - receive notification: showInfo []                               
 15                      

## Describe the bug

It's possible to get the id of a coc float window as described here: https://github.com/neoclide/coc.nvim/blob/19bfd9443708a769b2d1379af874f644ba9f1cd4/doc/coc.txt#L1519

If we call NVim's function nvim_win_set_config() on this window id, sometimes the scroll bar is not moved along with the window.

For example, I have this line in my .nvimrc:
`autocmd User CocOpenFloat call nvim_win_set_config(g:coc_last_float_win, {'relative': 'editor', 'row': 9999, 'col': 0, 'anchor':'SE', 'width':9999, 'height':8})`

I expect that this line will move the tooltip to the bottom of the screen. Sometimes, this works, and the scroll bar moves to the bottom of the screen along with the tooltip. (Image A)

However, at other times, the scrollbar is not moved and hangs. (Image B)

## Reproduce the bug

I generated the example images below using this mini.vim:

`set nocompatible`
`set runtimepath^=~/.vim/plugged/coc.nvim`
`filetype plugin indent on`
`syntax on`
`set hidden`
`autocmd User CocOpenFloat call nvim_win_set_config(g:coc_last_float_win, {'relative': 'editor', 'row': 9999, 'col': 0, 'anchor':'SE', 'width':9999, 'height':8})`

## Screenshots (optional)

Image A
![image](https://user-images.githubusercontent.com/6282268/115974235-22fd0880-a510-11eb-9068-f2bafa771477.png)

Image B
![image](https://user-images.githubusercontent.com/6282268/115974227-18427380-a510-11eb-96f7-2129aaf4a5c5.png)

**Comment by chemzqm** [comment]
You have to call `coc#float#nvim_scrollbar` function, checkout https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/float.vim#L353

**Comment by BitPusher16** [comment]
Hm, unfortunately that didn't work. I see now that my autocmd is moving the window with nvim_win_set_config(), but the shape and location of the window is stored in coc somewhere. So the scroll bar just gets drawn back where the original window was. If there is a function to call that updates the win params in coc by reading directly from the window object, that would allow me to write a correct script, I think.

`autocmd User CocOpenFloat`
`  \ call nvim_win_set_config(g:coc_last_float_win, {'relative': 'editor', 'row': 9999, 'col': 0, 'anchor':'SE', 'width':9999, 'height':8})`
`  \ call coc#float#nvim_update_scrollbar(coc#float#get_float_win())`

![image](https://user-images.githubusercontent.com/6282268/115979784-c7953f80-a53c-11eb-855c-9efd52fb3ff4.png)
