### ISSUE TITLE
Stopped providing correct signatureHelp for chosen overload

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#305]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

```
## versions

vim version: NVIM v0.3.1
node version: v11.6.0
coc.nvim version: 0.0.42
term: tmux-256color
platform: linux

## Error messages

## Output channel: prettier
```

**Describe the bug**

Just as the title says.

I think this is a regression and has been discussed and fixed before to a certain extent, but I don't remember where anymore.

**To Reproduce**

1. Follow example from gif with clangd or ccls.

**Screenshots**

![simplescreenrecorder](https://user-images.githubusercontent.com/1269815/50533985-80d5dd00-0b1c-11e9-9b90-7f9a7d97e3a4.gif)

**Comment by chemzqm** [comment]
You have to increase your `cmdheight` to get all signatures, it's limitation of vim.

The server can't know which one you're completing with just `foo(`

**Comment by oblitum** [comment]
@chemzqm did you try fix it previously? I have the impression this used to work....

**Comment by oblitum** [comment]
Possibly I was using echodoc at the time, though I got there was some attempt at fixing it on coc's side.

**Comment by oblitum** [comment]
> The server can't know which one you're completing with just `foo(`

I suppose it could be figured out from contents of selection, even more if it contains complete-item `user_data` with some form of id.

**Comment by oblitum** [comment]
> You have to increase your `cmdheight` to get all signatures, it's limitation of vim.

Not a realistic solution for C++ (or most languages supporting overloads).

**Comment by oblitum** [comment]
> Because we don't have floating window yet.

Even with floating windows, it won't make sense to show all the overloads *after* one was chosen from the overload list in the popup. Unless you plan to provide an option for desabling the overloads from popup, they and their selection would be of no use.

**Comment by oblitum** [comment]
> That would require server to remember last resolved complete item, I think most server not.

Hmm, I think current signature display can only work nice on overload selection happening at opening parentheses, not before like now, when signatureHelp with current option didn't even start.

**Comment by oblitum** [comment]
> > That would require server to remember last resolved complete item, I think most server not.
> 
> Hmm, I think current signature display can only work nice on overload selection happening at opening parentheses, not before like now, when signatureHelp with current option didn't even start.

The other approach is to maintain how things work now, I think it doesn't require server to remember last resolved complete item. coc.nvim alone will have that responsibility, not the server. coc.nvim shaw store information upon item selection and when it asks for the signatureHelp overloads, it should bump the signatureHelp overload that best matches the one that was previously selected.

**Comment by chemzqm** [comment]
> coc.nvim shaw store information upon item selection and when it asks for the signatureHelp overloads

I will not implement this, since there's no spec of how signature show stored in complete item, and I don't like guess like what echodoc does. When you select a complete item, you can type more character or remove character to make it a different function call, it call be solved, but I don't think necessary.
