### ISSUE TITLE
Support for willRename event

### ISSUE THREAD

**Issue by dantleech** [neoclide/coc.nvim#3050]
**Is your feature request related to a problem? Please describe.**

When renaming/moving files it can be desired to update the namespace of any code in that file.

CoC provides the `workspace.renameCurrentFile` command, but it does not (seem) to be able to trigger the `willRename` request to the server.

**Describe the solution you'd like**

Send the [willRename](https://microsoft.github.io/language-server-protocol/specification#workspace_willRenameFiles) notification on `workspace.renameCurrentFile`.

**Describe alternatives you've considered**

As a LS author, I'm also trying to detect renames based on file notifications, but this is difficult as the rename must then happen _after_ the files have been moved and the index may be in an inconsistent state.

**Comment by fannheyward** [comment]
I'm working on this in `feat/lap-316` branch, not pushing to GitHub by now.

Looking forward to make it availability to test this week.

**Comment by fannheyward** [comment]
`willRename` event will be fired on `workspace.renameCurrentFile`, please give it a test with https://github.com/neoclide/coc.nvim/pull/2756

**Comment by dantleech** [comment]
Can confirm that it works, thanks @fannheyward :tada:
