### ISSUE TITLE
Illegal character with status line settings

### ISSUE THREAD

**Issue by Amparose** [neoclide/coc.nvim#3051]
## versions

vim version: VIM - Vi IMproved 8.2 8021972
node version: v13.5.0
coc.nvim version: 0.0.80-bf98939a8c
coc.nvim directory: /Users/user/.vim/plugged/coc.nvim
term: dumb
platform: darwin

## Log of coc.nvim

2021-04-25T17:32:39.467 INFO (pid:14781) [plugin] - coc.nvim 0.0.80-bf98939a8c initialized with node: v13.5.0 after 204ms
2021-04-25T17:32:39.594 INFO (pid:14781) [attach] - receive notification: highlight []
2021-04-25T17:32:40.618 INFO (pid:14781) [attach] - receive notification: showInfo []

## Describe the bug

Illegal character in status line setting. Using Airline.

## Reproduce the bug

Using the recommended settings or the status line setting from help:

```vim
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
OR:
set statusline^=%{coc#status()}
```

When starting vim I get this error message:

```bash
E539: Illegal character <!>: statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
```

**Comment by chemzqm** [comment]
If not fixed on latest release, compile your vim with multi-byte support.
