### ISSUE TITLE
Is it possible to show function name in location when I use gr ( coc-reference ) ?

### ISSUE THREAD

**Issue by Mer1997** [neoclide/coc.nvim#3053]
**Is your feature request related to a problem? Please describe.**
I'm a c++ developer, my toolchain is nvim + coc.nvim + ccls. Every time I use gr to search for something's reference, it gives me a result list, it's good, but I got confused. Cause if I want to know the result is I need, I have to change to preview buffer and use `[[` confirm the function is right. 

**Describe the solution you'd like**
I expect coc-reference can show function name in result buffer not only the file name and line number

**Describe alternatives you've considered**
No alternatives I found in vim/nvim, but I do know some people can do this in emacs. So I thought maybe it's a lever just the handle is not in my hand.

**Additional context**

**Comment by fannheyward** [comment]
We can't, language server will only return `Location` of the reference, which only contains file uri and range, we can't find the function name uses it.

**Comment by hawk78** [comment]
What if treesitter is available?

**Comment by ingjieye** [comment]
Any one found a solution for this?
