### ISSUE TITLE
Diagnostic message won't go away

### ISSUE THREAD

**Issue by yauneyz** [neoclide/coc.nvim#3054]
I frequently get in a state where I have tooltip that is blocking my view of the text in the editor and it won't go away. Even opening up a different file for editing doesn't solve the problem, it remains on the screen. Might be a problem with my configuration, but either way it makes coc much less usable.

![COC Tooltip documentation](https://user-images.githubusercontent.com/31226354/116158606-2deca000-a6ac-11eb-8da7-bc061b5ff250.png)

**Comment by chemzqm** [comment]
Upgrade your neovim should helps.

**Comment by yauneyz** [comment]
Thanks it looks like that worked. Love the software by the way, this is awesome.
