### ISSUE TITLE
Is there any way to diagnosis definition  in another file when edit two files at the same time?

### ISSUE THREAD

**Issue by cjnchk** [neoclide/coc.nvim#3056]
When I edit two files on two screens at the same time, after adding a variable to one file, the other file cannot detect the existence of this variable immediately, It must be reopened. Is there any way to detect it in real time?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
