### ISSUE TITLE
Is it possible to get only symbols defined in a document?

### ISSUE THREAD

**Issue by mzr1996** [neoclide/coc.nvim#3057]
When I use `CocList outline` to navigate in a python document, it lists lots of symbols imported. However, when I use the outline view, I only want to focus on classes, functions defined in this document.

**Describe the solution you'd like**
So I'm wondering if it's possible to fold all imported symbols or don't show them?

**Comment by chemzqm** [comment]
There's api `:h coc-action-documentSymbols`, you have to implement UI for now.

**Comment by mzr1996** [comment]
Sorry, but I have tested `coc-action-documentSymbols`, and still cannot do that.
Here is an example python file:
```python
from numpy import find_common_type

def foo():
    pass
```
and Here is the output of `echo CocAction('documentSymbols')`
```json
[
    {
        "lnum": 1,
        "col": 19,
        "range": {
            "end": {
                "character": 34,
                "line": 0
            },
            "start": {
                "character": 0,
                "line": 0
            }
        },
        "selectionRange": {
            "end": {
                "character": 34,
                "line": 0
            },
            "start": {
                "character": 18,
                "line": 0
            }
        },
        "level": 0,
        "kind": "Function",
        "text": "find_common_type"
    },
    {
        "lnum": 3,
        "col": 5,
        "range": {
            "end": {
                "character": 8,
                "line": 3
            },
            "start": {
                "character": 0,
                "line": 2
            }
        },
        "selectionRange": {
            "end": {
                "character": 7,
                "line": 2
            },
            "start": {
                "character": 4,
                "line": 2
            }
        },
        "level": 0,
        "kind": "Function",
        "text": "foo"
    }
]
```
It won't tell me which is the imported function (`find_common_type`), which is the function defined in this document (`foo`).
That's why I need help.

**Comment by chemzqm** [comment]
For most language servers, they won't list imported variables in document symbols request, checkout https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentSymbol, 
 you have to parse the document by yourself or send your feature request to language-server-protocol https://github.com/microsoft/language-server-protocol/issues

**Comment by chemzqm** [comment]
Or maybe your language server could provide an option to exclude imported functions for symbols.

**Comment by mzr1996** [comment]
> Or maybe your language server could provide an option to exclude imported functions for symbols.

Thanks for your suggestion, I have achieved that by modifying jedi-language-server.
