### ISSUE TITLE
The 'winheight' option conflicts with the height of the coc floating window

### ISSUE THREAD

**Issue by lwflwf1** [neoclide/coc.nvim#3058]
## Describe the bug

When I set the 'winheight' option, I find the height of the float window changes to the value I set, especially the signature help window.

For example, I set winheight = 10, which is larger than the default height 8, then the height of the float window expands to 10 and the cursor becomes inside the signature help window. This problem is similar to issue#2498.

If I do not set winheight, everything works fine.

I wonder if this is a bug, or I can't set winheight option, or I've got something else wrong.

当我设置winheight选项的时候，浮动窗口就会强制变为那个选项的值，特别是函数签名帮助窗口，比如设置为10，由于10比默认值8大，所以窗口高度向下被扩展为10，导致光标在窗口里面了，这个情况和issue#2498很类似。

如果我不设置winheight，那就没问题。

如果我想使用浮动窗口特性就不能设置winheight吗，还是说我有什么其他地方搞错了，或者这是一个bug。

## Reproduce the bug

  ```vim
  set winheight=10
  ```

## Screenshots (optional)
![屏幕截图 2021-04-27 173126](https://user-images.githubusercontent.com/58506575/116219847-ab80e080-a77e-11eb-8005-fe53fc284c69.jpg)
![屏幕截图 2021-04-27 173210](https://user-images.githubusercontent.com/58506575/116219890-b76ca280-a77e-11eb-911a-eac13eb7bf6d.jpg)
![屏幕截图 2021-04-27 173256](https://user-images.githubusercontent.com/58506575/116219902-ba679300-a77e-11eb-9a6f-82d70b797235.jpg)

**Comment by chemzqm** [comment]
Have to be fixed by neovim, coc.nvim won't change user global options.

**Comment by lwflwf1** [comment]
谢谢回复，所以目前我只能不设置winheight了
