### ISSUE TITLE
Floats get stuck during rapid switching of tab pages

### ISSUE THREAD

**Issue by medwards** [neoclide/coc.nvim#3059]
## Result from CocInfo
```
## versions
                                               
vim version: VIM - Vi IMproved 8.2 8022814     
node version: v14.16.0                         
coc.nvim version: 0.0.80-2cece2600a            
coc.nvim directory: /home/medwards/.vim/pack/coc/start/coc.nvim-release
term: dumb                                     
platform: linux                                
                                               
## Log of coc.nvim                             
                                               
2021-04-27T14:49:48.440 INFO (pid:663255) [services] - registered service "languageserver.kotlin"
2021-04-27T14:49:48.443 INFO (pid:663255) [services] - kotlin state change: stopped => starting
2021-04-27T14:49:48.464 INFO (pid:663255) [plugin] - coc.nvim 0.0.80-2cece2600a initialized with node: v14.16.0 after 61ms
2021-04-27T14:49:48.468 INFO (pid:663255) [language-client-index] - Language server "languageserver.kotlin" started with 663266
2021-04-27T14:49:52.812 INFO (pid:663255) [services] - kotlin state change: starting => running
2021-04-27T14:49:52.817 INFO (pid:663255) [services] - service languageserver.kotlin started
2021-04-27T14:53:55.641 INFO (pid:663255) [attach] - receive notification: showInfo []
```

## Describe the bug

Float messages get stuck when rapidly switching tab pages (`gt`). "Stuck" means they they remain floating and do not disappear when the cursor moves away from the symbol that has the float. Moving the cursor onto and off the symbol will make the float disappear, but if the line is deleted, then the float will remain until `:call coc#float#close(g:coc_last_float_win)` or `:call coc#float#close_all()` is executed.

In Vim 8.1 this is much easier to reproduce, simply switch tab pages and the float will remain stuck. None of the workarounds work in Vim 8.1 either.
  
## Reproduce the bug

1. Create a file that produces a float error when cursoring onto a symbol (an unresolved reference is enough)
2. Cursor on to the element to cause the float to appear
3. `:tabnew`
4. rapidly switch pages and in the middle inject an up cursor move (`k`) when you're on the code buffer
5. Repeat from 2 if unsuccessful (ie the float disappears)

The rc file used was minimal:
  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

## Screenshots
![float-repro-3](https://user-images.githubusercontent.com/7339/116247085-c9dce100-a76a-11eb-838c-d37fa10481d2.gif)

At the end of the gif I call `coc#float#close_all()`

**Comment by fransfreij** [comment]
Same problem here, can reproduce no matter what Language Server I'm using. 
However, :call coc#float#close_all() does not seem to "clear" the floats in my VIM.

**Comment by medwards** [comment]
Don't forget `:CocInfo`, at least for the version numbers. I initially
asked in gitter and a coc maintainer immediately notices i was on vim 8.1
which is where I have problems closing floats.

**Comment by chemzqm** [comment]
Can't reproduce using vim8.1.1479

**Comment by medwards** [comment]
The default for Ubuntu 20.04 is (8.1.2269)[https://packages.ubuntu.com/focal/vim]

Please note the screenshot and original error report is for **8.2.2814**. I include the 8.1 information only for context and for other people experiencing this.

Could you please try to reproduce using 8.2.2814 and if you're unable to reproduce provide the features of your vim binary? Ubuntu builds with a different set of features than the default vim build. For example, this is my current build: https://pastebin.com/Bnz7iJc8

**Comment by medwards** [comment]
I spent a bunch of time building `8.1.1479`, but I think you mean `8.2.1479`, right? Anyways I'm still able to reproduce on `8.1.2269` but on commit `5e4dcf72b`.

On latest `release` the bug appears to be fixed, I believe it was inadvertently fixed in [the changes that happened to `float.vim`](https://github.com/neoclide/coc.nvim/compare/5e4dcf72bf47aabb8b579b16812dacdac5b2e77c..release).

The floats now appear to close before the tab is switched, which means there is no way for them to get stuck. This worked on `8.2.2814` and `8.1.2269` as well.
