### ISSUE TITLE
Fallback to vim default includesearch when CoC can't find the definition

### ISSUE THREAD

**Issue by TamaMcGlinn** [neoclide/coc.nvim#3070]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when clangd is unable to find the definition of a symbol (e.g. due to an out-of-date compile_commands.json), but vim's default includesearch *is* able to find it. Instead of an errormessage, I would much rather that `:execute 'ij '.expand('<cword>')` would be done instead if it is not possible to find using the "smart" approach.

**Comment by chemzqm** [comment]
Use CocAction and implement it yourself in vimrc.
