### ISSUE TITLE
Se ha detectado un error al procesar function SwitchFlowOrTsLsps[1]..CocAction

### ISSUE THREAD

**Issue by mcljs** [neoclide/coc.nvim#3072]
Hello I have an error with the coc in nvim, I will pass the error capture

![image](https://user-images.githubusercontent.com/52798639/117110712-90046f80-ad54-11eb-9fd6-34c1fe27a251.png)

I show you where the error is. If someone knows how to solve it and help me please

![image](https://user-images.githubusercontent.com/52798639/117111038-086b3080-ad55-11eb-9a02-f1f727865848.png)

**Comment by chemzqm** [comment]
:h CocNvimInit

**Comment by vmnavarro94** [comment]
Hey I don't now if you still need this.
I had the same problem and fixed it by running this command on nvim:
`:CocInstall coc-json coc-tsserverj`
