### ISSUE TITLE
Float only flickers on doHover

### ISSUE THREAD

**Issue by marcoaaguiar** [neoclide/coc.nvim#3082]
## versions

vim version: NVIM v0.5.0-dev+1309-g516551319
node version: v15.11.0
coc.nvim version: 0.0.80-46353b786b
coc.nvim directory: /home/marco/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-05-08T12:42:49.063 INFO (pid:27119) [services] - registered service "languageserver.sourcery"
2021-05-08T12:42:49.065 INFO (pid:27119) [services] - registered service "languageserver.grammarly"
2021-05-08T12:42:49.289 INFO (pid:27119) [services] - registered service "pyright"
2021-05-08T12:42:49.328 INFO (pid:27119) [plugin] - coc.nvim 0.0.80-46353b786b initialized with node: v15.11.0 after 329ms
2021-05-08T12:42:52.332 INFO (pid:27119) [attach] - receive notification: showInfo []

## Describe the bug

When executing `:call CocAction("doHover")` the Float flick open and instantly closes itself.

## Reproduce the bug

Put the cursor on the top of some code and execute `:call CocAction("doHover")`

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by distek** [comment]
Downgraded neovim and issue went away:

```
warning: downgrading package neovim-git (0.4.0.r3548.g516551319-1 => 0.4.0.r3535.g21035cff9-1)
```

Not sure which project this should be on, though.

**Comment by lttb** [comment]
I have the same issue on nvim 5

```
vim version: NVIM v0.5.0-dev+5165513
node version: v14.15.4
coc.nvim version: 0.0.80-46353b786b
term: xterm-kitty
platform: darwin
```

https://user-images.githubusercontent.com/11135392/117567124-7fd0f500-b0b2-11eb-9675-8dcc46e8ab66.mov

**Comment by gvolpe** [comment]
Experiencing the same issue.

```
NVIM v0.5.0-dev+1309-g516551319
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

node version: v14.16.1
coc.nvim version: 0.0.80-89a2dc8fc8
term: alacritty
platform: linux
```

It seems CoC runs a `highlight` command when `doHower` is invoked, which seems to be malfunctioning.

```
2021-05-09T14:19:48.117 INFO (pid:304861) [attach] - receive request: doHover []
2021-05-09T14:19:48.481 INFO (pid:304861) [attach] - receive notification: highlight []
2021-05-09T14:19:50.966 INFO (pid:304861) [attach] - receive notification: highlight []
2021-05-09T14:19:52.179 INFO (pid:304861) [attach] - receive notification: highlight []
2021-05-09T14:19:53.358 INFO (pid:304861) [attach] - receive notification: highlight []
2021-05-09T14:19:55.665 INFO (pid:304861) [attach] - receive notification: showInfo []
```

**Comment by gvolpe** [comment]
Disabling highlighting does not help, the flickering does not go away.

```vim
" Highlight the symbol and its references when holding the cursor.
" autocmd CursorHold * silent call CocActionAsync('highlight')
```

```
2021-05-09T14:24:22.887 INFO (pid:311629) [attach] - receive request: doHover []
2021-05-09T14:24:25.285 INFO (pid:311629) [attach] - receive notification: showInfo []
```

**Comment by marcoaaguiar** [comment]
I tried rolling back to neovim to neovim/neovim@b274b9887abae7afbe9b654075b98314c739a8cf (May 4th) with no improvements. 
I also rolled back coc.nvim to the last release (ce448a6945d90609bc5c063577e12b859de0834b), still the same.

**Comment by flleonx** [comment]
Experiencing the same issue.

NVIM v0.5.0-dev+1309-g516551319
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

node version: v16.0.0
coc.nvim version: 0.0.80
term: xterm-256color
platform: linux

**Comment by timtyrrell** [comment]
This is not going to be very helpful but the only way I have found to stop this is to comment out this line: https://github.com/neoclide/coc.nvim/blob/4586b97342cff6c8b630a024db30547e53ad1d62/autoload/coc/float.vim#L560

This is not a "fix" in any way because they never close now. I was on a big commenting out mission and finally hit this but am giving up for now.

vim version: NVIM v0.5.0-dev+1309-g516551319
node version: v14.16.1
coc.nvim version: 0.0.80-46353b786b
coc.nvim directory: /Users/timtyrrell/.config/nvim/plugged/coc.nvim
term: tmux
platform: darwin

I have attempted with the minimal vim config, no coc-settings, etc.

**Comment by yaegassy** [comment]
Until "Neovim" or "coc.nvim" is fixed or tweaked, roll back to this commit and try it out. https://github.com/neovim/neovim/commit/4be0e92db01a502863ac4bb26dd0fee16d833145

```
# ... snip
git clone https://github.com/neovim/neovim
cd neovim
git checkout 4be0e92db01a502863ac4bb26dd0fee16d833145
# ... snip
```

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by gvolpe** [comment]
@chemzqm any chance you can cut a release with this fix? Unfortunately, until this is not publised to the `npm` registry, it won't be available on `nixpkgs` and it's really hard to override with the current packaging setup.
