### ISSUE TITLE
How to scroll up to down from the first item in completion popup menu (?)

### ISSUE THREAD

**Issue by jacklanda** [neoclide/coc.nvim#3083]
When I press key Tab continuously, in the completion popup memu, I hope current selection will move from the first item to the next below it, as known as **from top to bottom**. Scrolling direction like the image shown↓
<img width="741" alt="img" src="https://user-images.githubusercontent.com/54089835/117561685-8ddf3f80-b0cb-11eb-9c76-cd7273d32f6f.png">

**Comment by chemzqm** [comment]
Read vim's help or https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources
