### ISSUE TITLE
CocSeach: add option to search within specific folder

### ISSUE THREAD

**Issue by rjurado01** [neoclide/coc.nvim#3084]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I work into huge project and I want to search something within specific folder.

**Describe the solution you'd like**

I would like to have an option to pass folder within to search

For example: `CocSearch varName -folder src/js/pages/admin` (sub-directory of current folder)

**Comment by chemzqm** [comment]
My suggestion is use cd command to change your cwd or use .ignore file to ignore unnecessary folders

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
