### ISSUE TITLE
How do I prevent coc.nvim AND all coc extensions from formatting my code?

### ISSUE THREAD

**Issue by HarrisonHemstreet** [neoclide/coc.nvim#3089]
please answer my question. I know I'm not filling this out right, but it's been hell trying to figure this out. Thanks! 😃

**Comment by HarrisonHemstreet** [comment]
I want to prevent this from formatting my code on save automatically. I want to just hit `:w` and be okay

**Comment by yaegassy** [comment]
(I think you should make an additional comment on this issue...) https://github.com/neoclide/coc.nvim/issues/3088

---

Do you have `coc.preferences.formatOnSaveFiletypes` set in `coc-settings.json`?

If you have it set, please delete the setting itself.

If you have any other similar questions, please check the schema for documentation and configuration information.

- Document
  - <https://github.com/neoclide/coc.nvim/blob/release/doc/coc.txt>
- Schema
  - https://github.com/neoclide/coc.nvim/blob/release/data/schema.json

**Comment by chemzqm** [comment]
Or use `:noa w`
