### ISSUE TITLE
Customise vim completion menu

### ISSUE THREAD

**Issue by skanev** [neoclide/coc.nvim#3091]
**Is your feature request related to a problem? Please describe.**
The completion menu is a bit noisy for me. For example, the shortcut is shown as `[F]` and `[LS]`, but I'd like it to be `F`, or even better, use a nerdfont icon. The items also have a trailing `~` which I'd like to get rid of, but I haven't found out how. Additionally, there is an extra character that appears (like `f`), which meaning I'm uncertain about, but would like to be able to customise it.

**Describe the solution you'd like**
Being able to define a few vim functions that do exactly what I want would be great. Having global variables that are less flexible but easier to use is probably good, but I'd like to be able to opt for the function as well.

**Describe alternatives you've considered**
I've considered just doing a personal fork of coc.nvim and using the fork with that modification, although I'd rather not, because it will be tricky to keep with the upstream.

**Additional context**
Here's a screenshot to visualize how it looks out of the box today:

<img width="627" alt="coc_vim______code_personal_dotfiles_vim_settings_plugins__-_NVIM" src="https://user-images.githubusercontent.com/10382/118231639-124d0c00-b498-11eb-9ba2-97c31e8f0d30.png">

Finally, there may already be a feature for that somewhere, but after spending some time with the code, I could not find it.

(also, I just can't stop myself from saying it: this project is AMAZING, a HUGE thank you for your stellar work!)

**Comment by fannheyward** [comment]
Setting `suggest.completionItemKindLabels` for letter `f` and `suggest.snippetIndicator` for `~` in your coc-settings.json.

**Comment by skanev** [comment]
Hey. Thanks, but this doesn't solve my `[A]` and `[LS]` problem, that I'd like to tweak. Particularly, I'd like to get rid of the brackets.

**Comment by lervag** [comment]
I agree with @skanev that it would be nice to be able to format the shortcut part of the completion menu. I see two main issues:

* There is no option to specify the format for the source shortcut `[{source}]` where `{source}` may be e.g. `LS` for the language server or `B` for the buffer source. A simple setting like `coc.source.shortcut.format = "[%s]"` would be nice.
* Right now we can change the letters for some sources, but not all. E.g., I don't see a way to change the `LS` for the lsp or `CALC` for coc-calc. This may be harder, as it may require an update on the extension side?

**Comment by lervag** [comment]
Let me know if it is more convenient if this is opened as a new issue instead.
