### ISSUE TITLE
Support OOP

### ISSUE THREAD

**Issue by thevan96** [neoclide/coc.nvim#3092]
I create interface shape, how to auto-suggest implement method function interface oop
I want features like intelj https://www.jetbrains.com/help/phpstorm/implementing-methods-of-an-interface.html
![Screen Shot 2021-05-14 at 4 54 48 PM](https://user-images.githubusercontent.com/47932916/118254435-4b57a180-b4d5-11eb-89e3-42f26a2fe101.png)

**Comment by oblitum** [comment]
@thevan96 this is a task for the language server to provide a code-action for. Currently the nearest you can get for that in C++ with coc-clangd is by starting typing "override" in the body of the child class, once you do that all the member functions you can override will be listed:

![img-2021-05-14-221321](https://user-images.githubusercontent.com/1269815/118343835-a1dad500-b501-11eb-85db-ff699d9251f9.png)
