### ISSUE TITLE
COC Crashes on vim startup in Cygwin

### ISSUE THREAD

**Issue by devo8604** [neoclide/coc.nvim#3094]
After setting up a fresh vim environment in Cygwin, COC crashes upon opening vim with an error of:

`client coc abnormal exit with: 1`

When I run CocInfo, I get:

`coc.nvim service not started, checking environment...service stopped for some unknown reason, try :CocStart`

I currently use this .vimrc in MacOS with no issues, I can provide a copy of my config if you need. 

System Info:
OS: Windows 10 - 64 bit, in Cygwin - 64 bit, the latest version, can provide specific version info for packages if requested.
NodeJS: installed on Windows, LTS version 14.17.0 - 64 bit

I also removed NodeJS LTS and installed the latest version: 16.1.0 with the same results as above.

The node binary is in my path and starts up fine within Cygwin.

**Comment by chemzqm** [comment]
Don't know the reason, please check the log https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by derekschrock** [comment]
This issue appears to be coc/vim using cygwin paths to Windows nodejs that thinks it can just prefix C: to the path.

`[coc.nvim]: Debugger listening on ws://127.0.0.1:6045/61029f0f-1
8da-43fb-bc50-62eeb8f32945[coc.nvim]: For help, see: https://nodejs.org/en/docs/inspector[coc.nvim]: For help, see: https://nodejs.org/en/docs/inspector[coc.nvim]: internal/modules/cjs/loader.js:892[coc.nvim]: internal/modules/cjs/loader.js:892[coc.nvim]:   throw err;[coc.nvim]:   throw err;[coc.nvim]:   ^[coc.nvim]:   ^[coc.nvim]: Error: Cannot find module 'C:\cygdrive\c\Users\dereks\.vim\plugged\coc.nvim\build\index.js'[coc.nvim]: Error: Cannot find module 'C:\cygdrive\c\Users\dereks\.vim\plugged\coc.nvim\build\ind
ex.js'[coc.nvim]:     at Function._resolveFilename (internal/modules/cjs/loader.js:889:15)[coc.nvim]:     at Function._resolveFilename (internal/modules/cjs/loader.js:889:15)
[coc.nvim]:     at Function._load (internal/modules/cjs/loader.js:745:27)[coc.nvim]:     at Function._load (internal/modules/cjs/loader.js:745:27)[coc.nvim]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)[coc.nvim]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)[coc.nvim]:     at internal/main/run_main_module.js:17:47 {[coc.nvim]:     at internal/main/run_main_module.js:17:47 {[coc.nvim]:   code: 'MODULE_NOT_FOUND',[coc.nvim]:   code: '
MODULE_NOT_FOUND',[coc.nvim]:   requireStack: [][coc.nvim]:   requireStack: [][coc.nvim]: }[coc.nvim]: }client coc abnormal exit with: 1`

So root is `/cygwin/c/Users/dereks/.vim/plugged/coc.vim/`

Does coc need to run `cygpath -w ...` on any path it's trying to use if you're in cygwin?

**Comment by derekschrock** [comment]
```bash
(default:38) [dereks@DESKTOP-G632S4E ~]
(cmd)$ export COC_DATA_HOME=$HOME/.vim/plugged/coc.nvim/data/

(default:38) [dereks@DESKTOP-G632S4E ~]
(ins)$ export COC_VIMCONFIG="$HOME/.vim"


(default:38) [dereks@DESKTOP-G632S4E ~]
(cmd)$ node $(cygpath -w /cygdrive/c/Users/dereks/.vim/plugged/coc.nvim/build/index.js)
�☺�nvim_get_api_info��☻�nvim_call_function��coc#util#path_replace_patterns��☻�nvim_set_var��coc_process_pid�☼L(node:3916) [DEP0005] DeprecationWarning: Buffer() is deprecated
 due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


(default:38) [dereks@DESKTOP-G632S4E ~]
(cmd)$ node /cygdrive/c/Users/dereks/.vim/plugged/coc.nvim/build/index.js
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\cygdrive\c\Users\dereks\.vim\plugged\coc.nvim\build\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by caryyu** [comment]
In case of anyone is still struggling to find a way to solve it, here's a clue: https://github.com/neoclide/coc.nvim/issues/975#issuecomment-538706177.

my case to solve is (execute under cmd.exe):

```shell
mklink /j "c:/home" "c:/cygwin64/home"
```
