### ISSUE TITLE
PHP Auto suggest not working in GVIM windows

### ISSUE THREAD

**Issue by Bhavesh164** [neoclide/coc.nvim#3096]
I have installed coc nvim in windows. I have used vim 8.2. I have installed php extension with coc but it does not show the intelephense suggestion.  My  Coc Info looks like this
## versions

vim version: VIM - Vi IMproved 8.2 8022725
node version: v15.13.0
coc.nvim version: 0.0.80-971c5f81b4
coc.nvim directory: C:\Users\bhaveshverma\.vim\plugged\coc.nvim
term: undefined
platform: win32

## Log of coc.nvim

2021-05-18T21:57:12.925 INFO (pid:12516) [plugin] - coc.nvim 0.0.80-971c5f81b4 initialized with node: v15.13.0 after 375ms
2021-05-18T21:57:20.574 INFO (pid:12516) [completion-complete] - Results from: around,snippets
2021-05-18T21:57:25.487 INFO (pid:12516) [completion-complete] - Results from: around,snippets
2021-05-18T22:01:45.994 INFO (pid:12516) [attach] - receive notification: showInfo []

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by Bhavesh164** [comment]
I can't figure it out what is the problem. It should install directly. CocList services also does not show anything. 

![image](https://user-images.githubusercontent.com/13777960/118799150-090ad780-b8bc-11eb-9b40-b2bfb254f59b.png)

But CocList extensions show all the extensions. Please guide me.
![image](https://user-images.githubusercontent.com/13777960/118799253-217af200-b8bc-11eb-9851-0cf65fbc2395.png)

**Comment by yaegassy** [comment]
@Bhavesh164 I usually use a "Mac". I've tried it with "GVim" on "Windows" and it works fine.

It cannot reproduce the problem, so it cannot solve the problem.

<img width="738" alt="coc-php-related" src="https://user-images.githubusercontent.com/188642/118917974-f4d2e300-b96c-11eb-941b-103d787b417b.png">

**Comment by Bhavesh164** [comment]
@yaegassy did you install any separate language server or maybe something done with cocsettings.json. If Yes please provide the cocconfig.json file. i will try that.
