### ISSUE TITLE
How to go to definition in existing vsplit

### ISSUE THREAD

**Issue by gerazov** [neoclide/coc.nvim#3098]
How can we use coc-definition to open the new file in an already open split? I've read through #318 but couldn't find a solve.

Ideally, CoC could open the definition in an existing vsplit, or create a new vsplit if it doesn't.

There's something similar here https://vi.stackexchange.com/a/21776 , but seems a bit involved. It would be a nice feature to have built-in :+1:

**Comment by chemzqm** [comment]
Create your own command and configure workspace.openCommand

**Comment by oblitum** [comment]
I've landed here looking for a "split drop", that would be similar to current `tab drop`, but for splits. I'm not sure what bare `drop` should do but currently it has the same effect as `edit`, simply jumps to definition location reusing the current window. Would be nice to have the docs of this terms too (`tabe`, `tab drop`, etc).
