### ISSUE TITLE
CocAction - Buffer X is not attached

### ISSUE THREAD

**Issue by esbenboye** [neoclide/coc.nvim#3099]
## Result from CocInfo
```
   1   ## versions
     1
     2 vim version: VIM - Vi IMproved 8.2 8022825
     3 node version: v16.0.0
     4 coc.nvim version: 0.0.80-fff6d63dd7
     5 coc.nvim directory: /Users/<username>/.vim/plugged/coc.nvim
     6 term: tmux
     7 platform: darwin
     8
     9 ## Log of coc.nvim
    10
    11 2021-05-19T19:30:42.228 INFO (pid:20292) [plugin] - coc.nvim 0.0.80-fff6d63dd7 initialized with node: v16.0.0 after 68ms
    12 2021-05-19T19:30:43.349 INFO (pid:20292) [coc-phpls] - intelephense module (builtin) is ready to be started
    13 2021-05-19T19:30:43.360 INFO (pid:20292) [language-client-index] - phpls started with 20293
    14 2021-05-19T19:30:51.228 INFO (pid:20292) [attach] - receive notification: codeAction [ '' ]
    15 2021-05-19T19:30:51.238 ERROR (pid:20292) [attach] - Notification error: codeAction [ '' ] Error: current buffer 4 not attached
    16     at Handler.getCurrentState (/Users/<username>/.vim/plugged/coc.nvim/build/index.js:65135:13)
    17     at processTicksAndRejections (node:internal/process/task_queues:96:5)
    18     at async Handler.doCodeAction (/Users/<username>/.vim/plugged/coc.nvim/build/index.js:64726:17)
    19     at async Plugin.cocAction (/Users/<username>/.vim/plugged/coc.nvim/build/index.js:65622:12)
    20     at async NeovimClient.<anonymous> (/Users/<username>/.vim/plugged/coc.nvim/build/index.js:36099:13)
    21 2021-05-19T19:31:01.907 INFO (pid:20292) [attach] - receive notification: showInfo []
```

## Describe the bug

If I have a shortcut to `<Plug>(coc-codeaction)` I cannot go to a file in in my locationlist. 
It will throw an error `[coc.nvim]: Error on notification "codeAction": current buffer X not attached` when attempting to go to the file. The buffer number varies depending on how many buffers I have open. 

``` nmap <c-m> <Plug>(coc-codeaction)  ```

## Reproduce the bug
1. Start Vim with minimal config (and ```nmap <c-m> <Plug>(coc-codeaction)``` added, since it is what causes the problem).
2. Use a command that populates the locationlist, e.g. ```lgrep hello ./dictionary.txt ```
3. Open the Locationlist with ```:lopen```
4. Press enter to go to whatever occorence (or just in the empty list if nothing is found)
5. The error does not occur if ```nmap <c-m> <Plug>(coc-codeaction)``` is not in .vimrc

## Screenshots (optional)

https://user-images.githubusercontent.com/4438511/118861941-5d727f00-b8dd-11eb-8bf9-665e87eb6153.mov

**Comment by chemzqm** [comment]
It's expected.  Try `:echo "\<C-m>" == "\<CR>"` you can see `<C-m>` is `<CR>`

**Comment by esbenboye** [comment]
Ah, ok - I don't know if that makes sense, but I got my error fixed.

If anyone else comes across this, the solution was to change my shortcut to something else.
