### ISSUE TITLE
Strange conflits with CSApprox, Coc.nvim and Vim-Plug

### ISSUE THREAD

**Issue by rbsantiago** [neoclide/coc.nvim#3101]
### versions

vim version: VIM - Vi IMproved 8.1 0
node version: v10.24.0
coc.nvim version: 0.0.80-971c5f81b4
coc.nvim directory: /home/rbs/.vim/plugged/coc.nvim
term: dumb
platform: linux

### Log of coc.nvim

2021-05-20T16:45:43.503 INFO (pid:36073) [plugin] - coc.nvim 0.0.80-971c5f81b4 initialized with node: v10.24.0 after 239ms
2021-05-20T16:45:50.316 INFO (pid:36073) [attach] - receive notification: showInfo []

## Describe the bug

Using Coc.nvim, with Vim-Plug and CSApprox make CSApprox stop working. The colors do not appear correctly on the terminal.

## Reproduce the bug

If downgrade Coc.nvim to  0.0.80-d129f0f97e, CSAapprox starts to works correctly again.

This is the strange part:

With this  .vimrc, the problem occur:

  ```vim
set encoding=utf-8
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
Plug 'godlygeek/csapprox'
call plug#end()

filetype plugin indent on
syntax on
set hidden
  ```

With this .vimrc, the problem does not occur:
  ```vim
  set nocompatible
  set runtimepath^=/home/rbs/.vim/plugged/coc.nvim
  set runtimepath^=/home/rbs/.vim/plugged/csapprox
  filetype plugin indent on
  syntax on
  set hidden
  ```

To test if CSApprox is working, I do :color darkblue
When CSApprox is not working, the background does not turn blue.

**Comment by chemzqm** [comment]
Try upgrade your node and coc.nvim, node 10 is no longer maintained.
