### ISSUE TITLE
Allow any custom opener to be explicitly used as `coc.preferences.jumpCommand`

### ISSUE THREAD

**Issue by przepompownia** [neoclide/coc.nvim#3103]
**Is your feature request related to a problem? Please describe.**
I have defined [`TabDrop`](https://github.com/przepompownia/vim-arctgx/commit/bca6deee24c918fd506df977779eedc2da774884) command which works as `tab drop` equivalent. The original `tab drop` has a bug described in https://github.com/neovim/neovim/issues/14567 (both in Vim and Neovim). 

The current coc.nvim implementation allows to use such custom commands implicitly. Using `TabDrop` allows later to correctly jump back to the previous tab. 

**Describe the solution you'd like**
Please change [schema.json](https://github.com/neoclide/coc.nvim/blob/release/data/schema.json#L1058) and allow to use custom openers explicitly.

**Comment by chemzqm** [comment]
OK, PR welcome.

**Comment by chemzqm** [comment]
Or ignore that validation.
