### ISSUE TITLE
Handle dot segments in URIs

### ISSUE THREAD

**Issue by amiralies** [neoclide/coc.nvim#3104]
It seems coc doesn't handle relative dot segments in uri so a response like this would fail
```json

Result: {
    "changes": {
        "file:///home/user/rescript/././src/Main.res": [
            {
                "range": {
                    "start": {
                        "line": 0,
                        "character": 22
                    },
                    "end": {
                        "line": 0,
                        "character": 23
                    }
                },
                "newText": "y"
            }
        ],
        "file:///home/user/rescript/./src/AnotherModule.res": [
            {
                "range": {
                    "start": {
                        "line": 0,
                        "character": 4
                    },
                    "end": {
                        "line": 0,
                        "character": 5
                    }
                },
                "newText": "y"
            }
        ]
    }
}
```

this is a response to a rename request.

system info:
OS: Linux
node: 12
vim: vim 8.2
coc: 0.0.80

**Comment by fannheyward** [comment]
After some tests, here is my found:

1. LS returns edit with uri, for example `file:///Users/fannheyward/src/basic/././src/MyFile2.res`
2. coc try to apply the edit, first coc will check and load the file if not loaded
3. the `MyFile2.res` is loaded into vim, return `bufoption` with fullpath `/Users/fannheyward/src/basic/src/MyFile2.res`
4. coc checks the uri to load, and the document's uri that loaded
5. now they're different, coc return null document

Fix: check the uri with `path.resolve()`
