### ISSUE TITLE
Add ability to disable automatic parenthesis/argument completion

### ISSUE THREAD

**Issue by FooSoft** [neoclide/coc.nvim#3105]
**Is your feature request related to a problem? Please describe.**
When coding in Python (`coc-jedi`) or Go (`coc-go`), and selecting a method from the candidate list, `coc.nvim` inserts not just the method name, but also the opening and closing parenthesis. This is undesirable for my usage, as I am simply trying to match the symbol name and not have the completion engine write any other code for me.

**Describe the solution you'd like**
Have an option to globally disable adding non-symbol contents when selecting a symbol from candidate list.

**Describe alternatives you've considered**
I've been trying to find issues containing this request, but have have not found any. It seems likely that this is at least partially coming from the language server itself, but then again I've been using "ale" previously with gopls (which also uses this language server) and it did not attempt to do this additional completion.

**Additional context**

**Comment by chemzqm** [comment]
Search `coc.preferences.snippets.enable` in doc.

**Comment by yaegassy** [comment]
@chemzqm Even if I set `coc.preferences.snippets.enable` to `false`, snippet support does not seem to be disabled in my environment.

There may be a bug in `coc.preferences.snippets.enable`.

(I'm sorry if this is a problem specific to my environment.)

---

@FooSoft As a side note, If you are using `coc-jedi`, you can disable this feature by changing this setting.  `"jedi.completion.disableSnippets": true`

It seems that there is no setting in `coc-go` to completely disable snippet support, so you may need to submit a request to add this feature.

**Comment by FooSoft** [comment]
Yes, unfortunately the `coc.preferences.snippets.enable` does not appear to work. @yaegassy thanks for the tip, I will look through docs for all of the language server plugins' properties for "snippets"

**Comment by chemzqm** [comment]
`coc.preferences.snippets.enable` is broken, I will fix that.

**Comment by yaegassy** [comment]
I have confirmed that snippet support can be disabled in my environment with the newly added `suggest.snippetsSupport` setting. 😇  https://github.com/neoclide/coc.nvim/commit/aa4c2f36d9490e56e52906f5d73efb1f34dcbbf8
