### ISSUE TITLE
CocSearch: implement -F and -W

### ISSUE THREAD

**Issue by hawk78** [neoclide/coc.nvim#3108]
**Is your feature request related to a problem? Please describe.**
To use CocSearch we are forced to change directory. 

**Describe the solution you'd like**
Would be nice if it could understand -F and -W like CocList grep

**Describe alternatives you've considered**
Adding a custom command to change directory, launch search and go back? Nah!

**Additional context**
The implementation in CocList
https://github.com/neoclide/coc-lists/blob/c782b932167393a2fc0445f4fcd8c107e4c8ee22/src/grep.ts#L109

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

All you need is add directory to the end of your command, the same as using rg in command line.

**Comment by hawk78** [comment]
What about something like this?
   ```
  function HawkSearch(patt)
    let cdir = getcwd()
    let cl = len(cdir)
    for folder in g:WorkspaceFolders
      let fl = len(folder)
      if fl > cl
        continue
      endif
      if cdir[0:fl-1] ==# folder
        exec "CocSearch " . a:patt " " . folder
      endif
    endfor                                                                                                                                                                                                                                   
  endfunction
  command -bang -nargs=1 HS call HawkSearch(<f-args>)
