### ISSUE TITLE
Non-intrusive quickfix list on Code action completion

### ISSUE THREAD

**Issue by PezCoder** [neoclide/coc.nvim#3109]
**Is your feature request related to a problem? Please describe.**
Currently when `coc-codeaction` is triggered & let's say the first fix suggested is applied. It overrides the quickfix list (:clist).
It's quite common to run 'ack/grep' to have a quick fix which we iterate on, & running code action at any point in time overrides it, which mayn't be natural.

**Describe the solution you'd like**
I would suggest keeping this as an opt-in feature, opt-out, depending on what you think is most natural to most of the users. But having an option to disable it shall definitely help.

**Describe alternatives you've considered**
1. I tried setting `coc.preferences.useQuickfixForLocations: false` to this doesn't seem to impact coc actions fix
2. Alternate is to do `:colder` every time we run a quick fix but that again is tedious, everytime we end up using the feature.

**Additional context**
Related issue which handles it for jumps: https://github.com/neoclide/coc.nvim/issues/187

[![asciicast](https://asciinema.org/a/416193.svg)](https://asciinema.org/a/416193)

Notice: How the quickfix becomes empty when a code action fix is applied.

**Comment by chemzqm** [comment]
Change `coc.preferences.listOfWorkspaceEdit` configurtion to `location`

**Comment by PezCoder** [comment]
Works like a charm. Thank you!
