### ISSUE TITLE
Improve doc/markdown rendering as per nvim-lsp

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#3110]
**Is your feature request related to a problem? Please describe.**

nvim-lsp has recently improved their doc/markdown rendering, see the progress showcased:

- https://github.com/neovim/neovim/pull/14596

**Describe the solution you'd like**

I'd like that coc.nvim to follow suit and improve in this area as well. Currently it presents almost exactly the same rendering issues as described in the issue above:

![img-2021-05-25-201625](https://user-images.githubusercontent.com/1269815/119580463-d28afc00-bd96-11eb-817d-3692a940fc7a.png)

**Additional context**

As reference nvim/lua LSP setup, this is how I configure [`coc-lua`](https://github.com/josa42/coc-lua) to work on my `init.lua`:

```lua
vim.fn['coc#config']('Lua', require('lua-dev').setup().settings.Lua)
```

**Comment by chemzqm** [comment]
Please be specific

**Comment by oblitum** [comment]
The screenshot above used as example is from coc.nvim hover. It's self-explanatory: the rendering issues are being auto described in the screenshot itself. I've applied the same test code as provided in this issue comment: https://github.com/neovim/neovim/pull/14596#issuecomment-845408746. The linked comment provided more context and a screenshot of what is expected when compared to current behavior.

**Comment by oblitum** [comment]
Oh, sorry, I forgot to mention that besides coc and the referred configuration above for coc-lua, I'm using [lua-dev.nvim](https://github.com/folke/lua-dev.nvim) to get EmmyLua docs for nvim API.

**Comment by oblitum** [comment]
I've found an additional issue with markdown rendering where I'm getting `&nbsp` for spaces:

![gif-2021-06-10-132623](https://user-images.githubusercontent.com/1269815/121603567-57c11280-ca1f-11eb-9d6a-8879e6a56f3b.gif)

**Comment by denstiny** [comment]
> 我在 Markdown 渲染中发现了一个额外的问题，其中我要获取`&nbsp;`空格：
> 
> ![gif-2021-06-10-132623](https://user-images.githubusercontent.com/1269815/121603567-57c11280-ca1f-11eb-9d6a-8879e6a56f3b.gif)

May I have your vim configuration, I'd like to know how your indentation line

**Comment by chemzqm** [comment]
Don't know what to do with`&nbsp;` since what we received from server should be markdown, not html.

**Comment by oblitum** [comment]
Okay. I guess that part is server issue then, please ignore.

**Comment by hrsh7th** [comment]
The VSCode's CSS language server returns a lot of HTML entities. So I think it will be good if we support concealing HTML entities.

```
    call s:_clear('markdownEscape')
    syntax region markdownEscape matchgroup=markdownEscape start=/\\\ze[\\\x60*{}\[\]()#+\-,.!_>~|"$%&'\/:;<=?@^ ]/ end=/./ containedin=ALL keepend oneline concealends
```

It's my module's code (I referenced neovim's implementation for it.)

**Comment by oblitum** [comment]
There have been many recent PRs regarding this merged lately (like [this](https://github.com/neovim/neovim/pull/14617)), so I think it's becoming increasingly diffuse where to borrow improvements, hence I'm closing the request as it can't be evidently clear.
