### ISSUE TITLE
Error on notification "formatSelected", formatRange provider not found

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#3117]
## Result from CocInfo

<img width="496" alt="image" src="https://user-images.githubusercontent.com/33961674/120288209-8c7fec00-c2f2-11eb-83db-a24af61f25b9.png">

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/33961674/120288271-9a357180-c2f2-11eb-8dc3-30c04b5088f7.png">

## Describe the bug

rust-analyzer doesn't have a good support of formatRange yet, but coc.nvim enables it by default, and when we type more than the max_width it then says:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/33961674/120288483-d8329580-c2f2-11eb-8dc5-5e62d73b6595.png">

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by GopherJ** [comment]
is there an option to disable this? don't report `formatRange` error while typing

**Comment by GopherJ** [comment]
I find https://github.com/fannheyward/coc-rust-analyzer/commit/e6332f139390ac0df737be4a3cfcaa9cd5362ccc#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519, I'll check if it helps

**Comment by fannheyward** [comment]
@GopherJ you need to use latest rust-analyzer and enable `rust-analyzer.rustfmt.enableRangeFormatting` in your coc-settings.json.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
