### ISSUE TITLE
problem with indenting & completion

### ISSUE THREAD

**Issue by cvlmtg** [neoclide/coc.nvim#312]
it seems the completion is wrong when the text being entered is indented while typing. I'm not sure if this is a problem with coc or if it's some bug with vim/neovim. I could not reproduce it without coc just because the completion menu is not opened automatically when typing.

![registrazione schermo 2018-12-31 alle 04 57 47](https://user-images.githubusercontent.com/6401008/50554419-5457c780-0cba-11e9-90b0-fb3243cc50e6.gif)

**Comment by cvlmtg** [comment]
I updated coc.vim but the problem still happens

**Comment by chemzqm** [comment]
You have to build from source by `yarn install`

**Comment by cvlmtg** [comment]
now it works, thanks. I though anything was done automatically by vim-plug with the postinstall script
