### ISSUE TITLE
Open function or class definition in a new terminal tab

### ISSUE THREAD

**Issue by ssoulless** [neoclide/coc.nvim#3125]
**Is your feature request related to a problem? Please describe.**
most of the time I use the `gd` command then I have to browse the file manually in a new terminal tab, because I still need to leave open the previous file. 

**Describe the solution you'd like**
It would be just a bit useful to be able to open the definition in a new tab, of course, Im just wondering if this is possible and how to configure it, probably mapping a new command in the nvim config file, any idea?

**Comment by chemzqm** [comment]
We don't know how to open a new terminal tab in vim, you can make use of applescriot if you're using iterm2
