### ISSUE TITLE
Jump to start of function when in middle of a function

### ISSUE THREAD

**Issue by yueyingjuesha** [neoclide/coc.nvim#3126]
**Is your feature request related to a problem? Please describe.**
I always find it hard to use built-in ]m, [m vim function to jump to start of a function. It seems like everyone are using their own regex to jump to start of the function. I am wondering if COC provided a way in LSP that can directly jump to function start

**Comment by oblitum** [comment]
On NeoVim there's https://github.com/nvim-treesitter/nvim-treesitter-textobjects#text-objects-move
