### ISSUE TITLE
Standardize virtual text in coc.nvim with priority

### ISSUE THREAD

**Issue by nima-dvlp** [neoclide/coc.nvim#3127]
**Is your feature request related to a problem? Please describe.**
Problem?! maybe, features and extensions override virtual text with no priority! OR I DON'T KNOW IF IS THERE ANY!

There is a problem? yse? **HIGH PRIORITY**! `diagnostic.virtualText: true`
![Screenshot_20210604_110008](https://user-images.githubusercontent.com/73692252/120756065-0945dc80-c524-11eb-8981-a03af8a3cb15.png)

There is no problem? Okay then show codelnes. `codeLens.enable: true`
![Screenshot_20210604_110229](https://user-images.githubusercontent.com/73692252/120756336-5d50c100-c524-11eb-9a2f-e260d23c6fcc.png)

Nothing with code(Err, Hint, Info, Ref)? other extension like `coc-git` -> `git.addGBlameToVirtualText: true`
![Screenshot_20210604_110501](https://user-images.githubusercontent.com/73692252/120756615-b6b8f000-c524-11eb-879f-060da38125dc.png)

Currently when they are active together:
![Screenshot_20210604_110720](https://user-images.githubusercontent.com/73692252/120756863-0ac3d480-c525-11eb-82c6-bed198afe4b0.png)
I like to see the diagnostic rather than the code lens!

**Describe the solution you'd like**
I don't know if coc.nvim currently manages how virtual text gets to Nvim, or not, but I think there must be an API at least in the coc.nvim ecosystem and its extensions for this feature to detect what must be shown...

Sorry if there is something about this in the documentation and I didn't reach it...

**Comment by chemzqm** [comment]
Checkout `:h nvim_buf_set_virtual_text`, there's no priority support yet.
