### ISSUE TITLE
"TypeError: Cannot read property 'map' of null" when opening Neovim

### ISSUE THREAD

**Issue by gpanders** [neoclide/coc.nvim#313]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
`E492: Not an editor command: CocInfo`

**Describe the bug**
Upon opening Neovim, I see the following message:
```
[vim-node-coc]: Plugin initialized error: TypeError: Cannot read property 'map' of null
    at Workspace.resolveRoot (/snapshot/coc.nvim/lib/workspace.js:1136:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**To Reproduce**
1. Install most recent `HEAD` version of `coc.nvim` and start Vim.

I do not see this error when reverting to the last commit ([`c8dfedfa860124a0af4131888368c35e2c69a4d3`](https://github.com/neoclide/coc.nvim/commit/c8dfedfa860124a0af4131888368c35e2c69a4d3)).

I install `coc.nvim` with `minpac`:

```vim
call minpac#add('neoclide/coc.nvim', {'do': 'call coc#util#install()'})
```

**Comment by gpanders** [comment]
This is in neovim, so `vim-node-rpc` shouldn't be necessary. Still, just to be safe I ran `yarn global add vim-node-rpc` and `yarn global upgrade` and the issue persists.

**Comment by chemzqm** [comment]
It's caused by you've update vim files by git, but the binary is old version, build from source code or update on new tag only could avoid that.

**Comment by gavsim** [comment]
Sorry to re-open this issue but I am having similar issue and having no luck. I have been a long time user and everything has been working great. Excellent plugin.

Everytime I open a file for which I have a language server installed I an error.

Running CocInfo I get:

vim version: NVIM v0.4.0-1177-gc8e78abaf
node version: v8.9.0
coc.nvim version: 0.0.40
term: iTerm.app
platform: darwin

Error messages

Plugin initialized error: TypeError: Cannot read property 'map' of null
    at Workspace.resolveRoot (/snapshot/coc.nvim/lib/workspace.js:1048:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Output channel: prettier

CocInfo is reporting Node version 8.9.0 yet when I run node -v I get v10.15.0 - something seems strange?

I am using nvm to control my node versions.

I have tried CocRebuild, same issue. I have tried removing the plugin and installing again using:

Plug 'neoclide/coc.nvim', {'tag': '*', 'do': 'yarn install'}

I have tried specifying the node path using: g:coc_node_path

I am running neovim, latest version.

Any help appreciated.

Thanks

**Comment by chemzqm** [comment]
@gpanders I think you failed to upgrade coc.nvim, 0.0.40 is an old version and `/snapshot/coc.nvim/lib/workspace.js` means you're still using binary release, and `yarn install` doesn't work for you.

You should add `let g:coc_force_debug=1` to force coc use compiled code.

**Comment by gavsim** [comment]
@chemzqm I have added the debug line - upon launching neovim I get this message:

[coc.nvim] binary and build file not found
Press ENTER or type command to continue

and when I continue I get this:

Error detected while processing function 268:
line    4:
[coc.nvim] Abnormal exited

I'm confused why coc.nvim is reporting my node version as 8.9 where node -v is version 10 ?

**Comment by chemzqm** [comment]
The binary release using node 8.9.
You failed to run `yarn install` in folder of coc.nvim, try upgrade again, a new release just available.

**Comment by gavsim** [comment]
Hey @chemzqm 

I've been able to successfully run yarn install in the coc.nvim folder:

coc.nvim on  tags/v0.0.46 is 📦 v0.0.46 via ⬢ v10.15.0
➜ yarn install
yarn install v1.12.3
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ yarn clean && yarn build
yarn run v1.12.3
$ rimraf lib build
✨  Done in 0.25s.
yarn run v1.12.3
$ tsc -p tsconfig.json
✨  Done in 4.67s.
✨  Done in 5.69s.

CocInfo Still reporting 0.40 see:

versions

vim version: NVIM v0.4.0-1177-gc8e78abaf
node version: v8.9.0
coc.nvim version: 0.0.40
term: iTerm.app
platform: darwin

Error messages

Plugin initialized error: TypeError: Cannot read property 'map' of null
    at Workspace.resolveRoot (/snapshot/coc.nvim/lib/workspace.js:1048:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by chemzqm** [comment]
Use `:echo &rtp` to find corrent coc.nvim folder you're using as vim plugin.
