### ISSUE TITLE
Scan cwd for matching rootPatterns to start language servers

### ISSUE THREAD

**Issue by mattysweeps** [neoclide/coc.nvim#3135]
**Is your feature request related to a problem? Please describe.**

I usually start nvim by opening the root directory. It would be nice if coc could detect which language servers should be started before I open a normal file. 

**Describe the solution you'd like**

coc could scan the cwd for files which match the rootPatterns of my language servers and start them accordingly.

**Describe alternatives you've considered**

- Never close nvim
- Drink ☕ while the language servers boot once I open a file.

**Additional context**

This is a mild inconvenience. The real problem are the slow language servers which take a while to get ready once I actually open a file. In my case this is `gopls`, which can take up to 10 seconds for large golang projects.

**Comment by chemzqm** [comment]
Extensions have that supported by `activationEvents` configuration, you can use autocmd to start your language server,
 we don't tend to scan your cwd.

**Comment by mattysweeps** [comment]
Sounds good. One more thought: what about adding `activationEvents` to the language server config schema?
