### ISSUE TITLE
The header file has been included indirectly, so it should not be completed automatically.

### ISSUE THREAD

**Issue by onlycalm** [neoclide/coc.nvim#3142]
**Is your feature request related to a problem? Please describe.**
When all the header files are included in the head.h, the COC completion function will still trigger the completion of the header file.

for example:
in head.h
```c
#include "stdio.h"
#include "gpio.h"
#include "common.h"
````

in main.c
```c
#include "head.h"

int main(void)
{
    return 0;
}
```

The function SetGpio() is declared in gpio.h . Function completion should not automatically complete the header file, because the header file has been included (Indirect).

**Describe the solution you'd like**
Whether header files are included indirectly should be identified. 

**Describe alternatives you've considered**
Other, can cancel the automatic completion of the header file.

**Additional context**
![2021-06-13_20-57-35](https://user-images.githubusercontent.com/48640489/121808293-50517180-cc8a-11eb-982b-08eca2813331.gif)

**Comment by oblitum** [comment]
Not a coc.nvim issue, check if such configuration is possible with the language server (clangd). I don't think it is, as it's supposed to complete regards the translation unit as a whole, which should include all headers expanded.
