### ISSUE TITLE
Can have socket server as normal configuration?

### ISSUE THREAD

**Issue by dannypsnl** [neoclide/coc.nvim#3149]
**Is your feature request related to a problem? Please describe.**
The biggest problem is stdio mode in different languages is so complicated, if it's possible to skip it will be great.

**Describe the solution you'd like**
No

**Describe alternatives you've considered**
At least can start socket server automatically, help development easier.

**Additional context**
No

**Comment by chemzqm** [comment]
It needs language server support, coc.nvim can work with language using socket.
