### ISSUE TITLE
Conflict with vim-visual-multi. Backspace key abnormal. 

### ISSUE THREAD

**Issue by onlycalm** [neoclide/coc.nvim#3154]
## Result from CocInfo

![2021-06-20_18-12-59](https://user-images.githubusercontent.com/48640489/122670187-3fa57c00-d1f3-11eb-83b5-e6586adec24d.png)

## Describe the bug

When I use plug-ins auto-pairs and coc.nvim at the same time. When the COC detects a syntax error or warning in the file, using backspace in multi-cursor mode will cause an exception. Multiple characters are deleted at one time. 

![2021-06-20_13-22-18](https://user-images.githubusercontent.com/48640489/122670238-8abf8f00-d1f3-11eb-86fc-28ab9fc8575f.gif)

Then, When I press the `d` or `x` key, an exception will be thrown.

![2021-06-20_18-27-29](https://user-images.githubusercontent.com/48640489/122670567-52b94b80-d1f5-11eb-922d-8c90bb7d16dc.gif)

I tried the following:
1. When COC is turned off, VIM visual multi works normally.
2. When using other LSP plug-ins, VIM visual multi works normally（ I tried the ale plug-in)

I also raised the problem on vim-visual-multi

## Reproduce the bug

Install these two plug-ins, and use the default configuration for the rest. (I've verified that you can reproduce anomalies)

- Create file `mini.vim` with：

  ```vim
 Plug 'mg979/vim-visual-multi', {'branch': 'master'}
Plug 'neoclide/coc.nvim', {'branch' : 'release'} 
  ```

Using clangd, use the configuration recommended by the document.

**Comment by chemzqm** [comment]
Use `"pairs.enableBackspace": false`

**Comment by onlycalm** [comment]
@chemzqm 
Thanks for you help. 
I do it as follows. The problem doesn't seem to be solved. 

```vim
:CocInstall coc-pairs
```

my coc-settings.json
```
{
  "languageserver":
  {
    "clangd":
    {
      "command": "clangd",
      "rootPatterns": [".git/", ".svn/"],
      "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"]
    }
  },

  "diagnostic":
  {
    "enableSign": "true",
    "errorSign": "✘",
    "warningSign": "!"
  },

  "pairs.enableBackspace": false
}
```

**Comment by onlycalm** [comment]
@chemzqm
I updated VIM8.1 to VIM8.2 and it worked fine. It may be a Bug in Vim
