### ISSUE TITLE
Can't use tab

### ISSUE THREAD

**Issue by vando2108** [neoclide/coc.nvim#3167]
![image](https://user-images.githubusercontent.com/35914996/123294363-f9c41d00-d53e-11eb-962b-15764aa187d3.png)
I got this problem when I used tab. How I can fix this problem? Thank you

**Comment by fannheyward** [comment]
`Unknown function: check_back_space`, the function is missed in your vimrc, please check README.

```
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

**Comment by newptcai** [comment]
> Disabling the `julia-vim` extension's `g:latex_to_unicode_tab` setting fixes this.

Exactly the same problem for me.

**Comment by nirgal-soft** [comment]
i'm currently running into this problem and i can't figure out why. it has just suddenly started happening after years of using coc

**Comment by erickvneri** [comment]
I ran into this problem just a moment ago as well, maybe at the same time as you  @nirgal-soft 

I was checking `coc-rust-analyzer` and suddenly I wasn't able to use tabs.

Another problem that I noticed is that if I get rid of all the plugin installations, comment out CoC and reinstall I'll still get the error 🤔

**Comment by nirgal-soft** [comment]
@erickvneri thanks for checking in with me I'll try this fix asap.

**Comment by SkinyMonkey** [comment]
I got the same problem today, reinstalling plugins from 0 doesnt change thing.
I'm using the last version of coc.nvim.

The last fix posted works for me (inoremap)

**Comment by sricharankrishnan** [comment]
Hello,
Not sure if I am a bit late in this conversation but here is what I found out and probably, someone could relate to this. The issue with the Tab key is linked to installing the COC Pluggin for Neovim. And even after adding ```check_back_space()``` function to the init.vim config file, it was still not working.

I then dug around a bit, I got to this command called ':verbose imap <tab>' and when I used it, the result pointed out to a file that was located for me at ```~/.config/nvim/plugged/coc.nvim/autoload/coc/ui.vim```. I then proceeded to line number 11 where a for loop starts with an array of string values and removed the '<tab>' value from that array and now things work.

Let me know your thoughts on this.

**Comment by fannheyward** [comment]
@sricharankrishnan how do you setup `<tab>` in your init.vim?

**Comment by sricharankrishnan** [comment]
@fannheyward 
Please feel free to checkout my config file at this place:
[https://github.com/sricharankrishnan/config-files/blob/master/neovim/init.vim](https://github.com/sricharankrishnan/config-files/blob/master/neovim/init.vim)

If there are any issues that you believe I should avoid, would be happy to hear from your side. Cheers.

**Comment by fannheyward** [comment]
@sricharankrishnan and what's your `:CocInfo`? coc.nvim 0.82.0 has changed to custom popup menu, you need to use `coc#pum#visible` instead of `pumvisible`.

**Comment by sricharankrishnan** [comment]
Result for :CocInfo
```console
 vim version: NVIM v0.6.1
node version: v18.15.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /home/dell/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux 
```
```coc#pum#visible``` is similar to the example config file thats here on this repo. Would you prefer I copy that instead? Please advice?

**Comment by fannheyward** [comment]
@sricharankrishnan yes, check the README and doc to use the new function.

**Comment by owenstake** [comment]
> @sricharankrishnan and what's your `:CocInfo`? coc.nvim 0.82.0 has changed to custom popup menu, you need to use `coc#pum#visible` instead of `pumvisible`.
> 
> Check `:h coc-completion-example`.

it works!

**Comment by Datebasesystem** [comment]
The real reason is that coc is updated to a new version, and the old configuration is not working correctly.

You can update the configuration in plugin/coc.vim according to the https://github.com/neoclide/coc.nvim.
For me, the old config is:
```
inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

```

and the new configuration is :
```
" Use tab for trigger completion with characters ahead and navigate
" NOTE: There's always complete item selected by default, you may want to enable
" no select by `"suggest.noselect": true` in your configuration file
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()

inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

```
