### ISSUE TITLE
Less disturbing diagnostics

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#3168]
**Is your feature request related to a problem? Please describe.**

Current available options for diagnostic refresh can either be on every character change in insert mode, or at `InsertLeave` (the default). Still, the default can be a lot disturbing and unnecessary when jumping placeholder of snippets:

![gif-2021-06-24-235040](https://user-images.githubusercontent.com/1269815/123362670-6e9b5500-d547-11eb-8463-088807396425.gif)

One bad hack I did to get it less noisy was to:

```vim
:autocmd InsertEnter * call coc#config('diagnostic', { 'enable': v:false })
:autocmd CursorHold * call CocActionAsync('diagnosticToggle') | call CocActionAsync('diagnosticToggle')
```

The hack is ugly (I didn't find a simpler way to have manual diagnostics request on `CursorHold`), but works:
![gif-2021-06-24-235204](https://user-images.githubusercontent.com/1269815/123362695-75c26300-d547-11eb-85fd-901578218ecd.gif)

**Describe the solution you'd like**

I want some less disturbing alternative for diagnostics that plays well with snippets.

**Comment by chemzqm** [comment]
Fixed by 56b847bd

**Comment by oblitum** [comment]
Thanks.

**Comment by oblitum** [comment]
`autoRefresh = false` has stopped working :-/ I'm getting diagnostics on signatureHelp jump placeholder. It seems it's still working for snippets, but not for `CocActionAsync('showSignatureHelp')` on `CocJumpPlaceholder`.

**Comment by oblitum** [comment]
The original issue gif represents current behavior.
