### ISSUE TITLE
Can't find check.js module on CocRestart

### ISSUE THREAD

**Issue by jeffrey-l-turner** [neoclide/coc.nvim#3174]
## versions

vim version: NVIM v0.4.4
node version: v14.5.0
coc.nvim version: 0.0.80-24ded98826
coc.nvim directory: /Users/jeff/.config/nvim/plugged/coc.nvim
term: xterm-color
platform: darwin

## Log of coc.nvim

2021-06-25T18:21:06.616 INFO (pid:81546) [plugin] - coc.nvim 0.0.80-24ded98826 initialized with node: v14.5.0 after 590ms
2021-06-25T18:21:06.656 INFO (pid:81546) [watchman] - watchman watching project: /Users/jeff/src/ShaktiCrypto
2021-06-25T18:21:06.681 INFO (pid:81546) [services] - registered service "tsserver"
2021-06-25T18:24:41.343 INFO (pid:81546) [attach] - receive notification: showInfo []

## Describe the bug

`:CocRestart` reports that bin/check.js is not found

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

```  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden```


Screen shot explains the problem (with VimR/Neovim)


## Screenshots (optional)


![image](https://user-images.githubusercontent.com/1573697/123497610-59740400-d5e3-11eb-9a66-162440d67827.png)

## Resolution:

This problem can be resolved by navigating to `~/.config/nvim/plugged/coc.nvim/bin` and executing `touch check.js`

It looks like this file was removed from the codebase but I can't find where it is being referenced.

Hopefully someone can figure that out.

**Comment by jeffrey-l-turner** [comment]
just `touch bin/check.js` to temporarily fix this problem

**Comment by chemzqm** [comment]
Your coc.nvim might using old version vim files.

**Comment by jeffrey-l-turner** [comment]
That's what I thought too @chemzqm -- I did a `yarn` as well as a `:PlugClean` & `PlugInstall` but the same issue occured. I just can't find anywhere in the code base that `check.js` was still being called. Thanks

**Comment by chemzqm** [comment]
Check your node arguments by ` :echo get(g:, 'coc_node_args', [])`

**Comment by jeffrey-l-turner** [comment]
Thanks -- that doesn't look like I had a duplicate... still not sure what was going on. I've updated to the latest and everything is now working fine.
