### ISSUE TITLE
clangd.semanticHighLighting + vim-lsp-cxx-highlight don't work

### ISSUE THREAD

**Issue by ghost** [neoclide/coc.nvim#3175]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8023020
node version: v14.15.4
coc.nvim version: 0.0.80-24ded98826
coc.nvim directory: /data/data/com.termux/files/home/.vim/pack/plugin/start/coc.nvim    term: dumb                                                                              platform: android                                                                                                                                                               ## Log of coc.nvim                                                                                                                                                              2021-06-25T22:03:02.719 WARN (pid:13927) [attach] - Plugin not ready when received "regi
2021-06-25T22:03:02.727 WARN (pid:13927) [attach] - Plugin not ready when received "regi
2021-06-25T22:03:02.728 WARN (pid:13927) [attach] - Plugin not ready when received "regi
2021-06-25T22:03:02.728 WARN (pid:13927) [attach] - Plugin not ready when received "regi
2021-06-25T22:03:03.345 INFO (pid:13927) [services] - registered service "clangd"
2021-06-25T22:03:03.348 INFO (pid:13927) [services] - clangd state change: stopped => st2021-06-25T22:03:03.387 INFO (pid:13927) [language-client-index] - Language server "clan
2021-06-25T22:03:03.673 INFO (pid:13927) [services] - clangd state change: starting => r2021-06-25T22:03:03.702 INFO (pid:13927) [services] - service clangd started            2021-06-25T22:03:03.708 INFO (pid:13927) [plugin] - coc.nvim 0.0.80-24ded98826 initializ2021-06-25T22:03:03.715 INFO (pid:13927) [attach] - receive notification: registNotifica2021-06-25T22:03:03.716 INFO (pid:13927) [attach] - receive notification: registNotifica2021-06-25T22:03:03.718 INFO (pid:13927) [attach] - receive notification: registNotifica2021-06-25T22:03:03.719 INFO (pid:13927) [attach] - receive notification: registNotifica
2021-06-25T22:03:05.371 INFO (pid:13927) [attach] - receive notification: showInfo []
```

## CocCommands workshop.showOutput

```
[Warn] Ignored rootPath /data/data/com.termux/files/home of client "clangd"
clangd version 12.0.0                                                                                                                        PID: 15069                                                                                                                                   Working directory: /data/data/com.termux/files/home
argv[0]: /data/data/com.termux/files/usr/bin/clangd                                                                                          Starting LSP over stdin/stdout                                                                                                               <-- initialize(0)
Client supports legacy semanticHighlights notification and standard semanticTokens request, choosing the latter (no notifications).
--> reply:initialize(0) 4 ms                                                                                                                 <-- initialized                                                                                                                              <-- textDocument/didOpen
Failed to find compilation database for /data/data/com.termux/files/home/lipsum.c
ASTWorker building file /data/data/com.termux/files/home/lipsum.c version 1 with command clangd fallback
[/data/data/com.termux/files/home]                                                                                                           /data/data/com.termux/files/usr/bin/clang /data/data/com.termux/files/home/lipsum.c -fsyntax-only -resource-dir=/data/data/com.termux/files/u
--> textDocument/clangd.fileStatus
--> textDocument/publishDiagnostics
--> textDocument/clangd.fileStatus
<-- textDocument/semanticTokens/full(1)
--> reply:textDocument/semanticTokens/full(1) 2 ms
--> textDocument/clangd.fileStatus
<-- textDocument/didClose
--> textDocument/publishDiagnostics
```

## Describe the bug

I was using an old version of Coc.nvim and the plugin was working normally, then I updated it through my plugin manager and the highlight function I set for clangd stopped working. I have `vim-lsp-cxx-highlight` installed, too.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Install latest coc.nvim version and vim-lsp-cxx-highlight
- Put "clangd.semanticHighlighting": true in your coc settings file
- Open a file.c and add this code:

```c
#include <stdio.h>

int main(void)
{
     printf("foobar");
     return 0;
}
```

## Screenshots (optional)

(Old Coc, note that main and printf are highlighted)

![scrgh1](https://user-images.githubusercontent.com/86498478/123498442-81815880-d61f-11eb-8729-27ebfeee613e.png)

(New Coc, not highlighted anymore)

![scrgh2](https://user-images.githubusercontent.com/86498478/123498471-9a8a0980-d61f-11eb-8c29-c743462ee91d.png)

**Comment by chemzqm** [comment]
Need an option to disable smantic highlight feature for language server, so ccls would send old notifications.

**Comment by fannheyward** [comment]
Set `coc.preferences.semanticTokensHighlights` to false to disable semanticTokens highlighting.

**Comment by oblitum** [comment]
I'm afraid `semanticTokensHighlights` will turn into an unused esoteric/hidden feature if it's not made easier to use? Right now for example, with clangd, in my case, it seems I'd have to disable nvim-treesitter for c++, then `:call CocActionAsync('showSemanticHighlightInfo')` wouldn't show all possible groups, just the ones present in the current c++ file, to have all of them I'd have to search clangd sources, once possessing the groups, I'd then need to produce a highlight colorscheme with them myself.

**Comment by fannheyward** [comment]
>  ones present in the current c++ file

Yes, `showSemanticHighlightInfo` can only show current file's token type. I'll try to improve this with all token type that current LS supports.

**Comment by Neur1n** [comment]
> Set `coc.preferences.semanticTokensHighlights` to false to disable semanticTokens highlighting.

It doesn't work for me. I've also set `clangd.semanticHighlighting` to `true`. How to debug it? Thanks.

**Comment by fannheyward** [comment]
https://github.com/clangd/coc-clangd/issues/287

**Comment by Alexey104** [comment]
For me syntax highlighting works again after upgrading coc.nvim to the latest version, but it gets completely broken after performing any text modifications:
![Peek 2021-07-09 21-51](https://user-images.githubusercontent.com/38672094/125143741-49503e80-e124-11eb-96d2-3f711388b650.gif)
neovim v0.5.0

**Comment by oblitum** [comment]
I have experienced the same, though rust-analyzer seems to work fine.

**Comment by Alexey104** [comment]
This is still an issue after applying 76f407d, and manually assigning colors to semantic groups still leads to #3217.

**Comment by oblitum** [comment]
@Alexey104 I don't have any semantic color anymore after it was disabled by default on 76f407d. Manually assigning colors and/or manually toggling the option should be reported in another issue as this one is about having it turned ON by default, which I simply can't repro anymore after 76f407d.

**Comment by fannheyward** [comment]
With this fix https://github.com/neoclide/coc.nvim/pull/3268, you can set `coc.preferences.semanticTokensHighlights` to false to disable the new semanticTokens feature, to use the old semanticHighlighting protocol.

**Comment by chemzqm** [comment]
Should be fixed, checkout `:h coc-semantic-highlights` for details.
