### ISSUE TITLE
How to scroll the documentation window?

### ISSUE THREAD

**Issue by aganm** [neoclide/coc.nvim#3184]
With coc.nvim and coc-lua, when I type a function, I get some docs

![image](https://user-images.githubusercontent.com/20380758/124033650-37ee9000-d9c8-11eb-9439-4bc7f916158d.png)

The docs window has a scroll bar on the right showing that there's still more docs to read.

How do I scroll this window down to read more of the docs?

**Comment by fannheyward** [comment]
Check `:h coc#float#has_scroll()` and `:h coc#float#scroll()`.

**Comment by matrixbot123** [comment]
I have tried (C-b ) and (C-f) for some reason it just goes down the main file instead of the hovering doc

> Check `:h coc#float#has_scroll()` and `:h coc#float#scroll()`.


I have tried (C-b ) and (C-f) for some reason it just goes down the main file instead of the hovering doc
