### ISSUE TITLE
How to disable document buffer

### ISSUE THREAD

**Issue by Sammyalhashe** [neoclide/coc.nvim#319]
**Is your feature request related to a problem? Please describe.**
I just want to be able to disable the buffer that defaults at the top of the screen with function docs. I hope I am describing this alright. 

**Describe the solution you'd like**
When completing a function, I would not like the top buffer containing the docs of the function to appear.

**In the below, I would not like the `range()` documentation, it takes up a good portion of my screen'**
<img width="896" alt="screen shot 2019-01-04 at 12 41 50 am" src="https://user-images.githubusercontent.com/20797997/50675128-15778980-0fba-11e9-8b55-0470855a3e8b.png">

**Comment by chemzqm** [comment]
Add `set completeopt-=preview` in your .vimrc
