### ISSUE TITLE
Format on type request cancelled

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#3194]
## Reproduce the bug

1. `echo 'const a = 1;' > test.ts`
1. `nvim test.ts`
1. `o` to new line, `formatOnType` request work as expected
1. `<CR>` to new line, `formatOnType` request is fired, but immediately canceled, because https://github.com/neoclide/coc.nvim/blob/c0cc51d8118e19a07446f62cbda6f8c5e35283f2/src/handler/index.ts#L91-L95

**Comment by chemzqm** [comment]
Fixed by d5eb44e
