### ISSUE TITLE
Add option to turn off formatting in certain workspaces

### ISSUE THREAD

**Issue by LeviHarrison** [neoclide/coc.nvim#3198]
**Is your feature request related to a problem? Please describe.**
A project I work on contains a lot of code that isn't formatted properly, and I don't desire to have it formatted for me automatically on save.

**Describe the solution you'd like**
I'd like an option to turn off certain features in a specific workspace, of which would be formatting on save.

**Describe alternatives you've considered**
* I could turn off formatting on save altogether, but I'd still like to use it in other workspaces.
* I could completely disable coc in the workspace, but I still want to have the completions.

**Comment by chemzqm** [comment]
Use workspace configuration file https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file

**Comment by LeviHarrison** [comment]
Thanks!
