### ISSUE TITLE
ESlint error when using vim-fugitives :Gdiff command

### ISSUE THREAD

**Issue by deathmaz** [neoclide/coc.nvim#32]
**Describe the bug**
I'm using vim-fugitive plugin, so when i use `:Gdiff` command in a file that was changed, coc.nvim opens vertical split with the following error
```
[Info  - 18:04:27] ESLint library loaded from: /home/maz/server/www/homestead/voice-mvp/node_modules/eslint/lib/api.js
[Error - 18:04:37] ESLint stack trace:
[Error - 18:04:37] TypeError: Cannot read property 'CLIEngine' of undefined
    at validate (/home/maz/.config/yarn/global/node_modules/eslint-server/lib/index.js:548:40)
    at resolveSettings.then.settings (/home/maz/.config/yarn/global/node_modules/eslint-server/lib/index.js:490:13)
    at <anonymous>
```

**To Reproduce**
1. You need to have vim-fugitive plugin;
2. Open `.js` file, remove a line;
3. Save the file;
4. Run `:Gdiff` command;

**Expected behavior**
When `:Gdiff` command was executed there shouldn't be any errors from coc.nvim.

**Screenshots**
I recoreded the issue with asciinema - https://asciinema.org/a/AiTGXMXLPdtVjbLZaDqrXlS1p

**Desktop (please complete the following information):**
 - Terminal: `tilda` 
 - Version: `1.4.1-1`
 `tmux 2.7-1`
 `NVIM v0.3.1`
 `Kernel: 4.14.57-1-MANJARO x86_64 bits: 64 Desktop: Xfce 4.12.4 Distro: Manjaro Linux`

**Comment by chemzqm** [comment]
There is 
```
  "eslint.packageManager": "npm",
```
in settings.json to make it same as VSCode's settings.json, you can either run
```
npm i -g eslint
```
or if have installed eslint with yarn, add:
```
 "eslint.packageManager": "yarn",
```
to your `coc-settings.json`

**Comment by chemzqm** [comment]
The error is confusing, it could be improved.

**Comment by deathmaz** [comment]
I already have `eslint` installed globally

**Comment by chemzqm** [comment]
The eslint server check the folder: `npm root -g`, not the executable file.

**Comment by deathmaz** [comment]
ok, i tried your suggestions from https://github.com/neoclide/coc.nvim/issues/32#issuecomment-409623859, but i still have the error

**Comment by chemzqm** [comment]
Add
```
"eslint.enable": false
```
to disable eslint for now, I will send a fix for this.
