### ISSUE TITLE
An error occurred during installation and php language work

### ISSUE THREAD

**Issue by likelxl** [neoclide/coc.nvim#321]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
## versions

vim version: NVIM v0.4.0-78-g38b4ca26b
node version: v8.9.0
coc.nvim version: 0.0.45
term: xterm-256color
platform: linux

## Output channel: languageserver.phplang
DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is not loaded
DEBUG     Listening on STDIN
[Info  - 22:38:55] 4 files total
[Info  - 22:38:55] Indexing project for definitions and static references
Parsing file:///code/php/imooc/App/Controller/Home/Index.php
Parsing file:///code/php/imooc/index.php
Parsing file:///code/php/imooc/Imooc/Loader.php
Parsing file:///code/php/imooc/Imooc/Ob.php
[Info  - 22:38:55] Indexing project for dynamic references
Parsing file:///code/php/imooc/App/Controller/Home/Index.php
Parsing file:///code/php/imooc/index.php
Parsing file:///code/php/imooc/Imooc/Loader.php
Parsing file:///code/php/imooc/Imooc/Ob.php
[Info  - 22:38:55] 0 Packages
[Info  - 22:38:55] All 4 PHP files parsed in 0 seconds. 152 MiB allocated.

## Output channel: highlight
[Info  - 22:38:55] Highlight server running in node v8.9.0

**Describe the bug**
when use coc the error can occurred not only use php language server
at DecodeBuffer.__dirname.DecodeStream.decoder.push (/snapshot/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)  
**To Reproduce**
**Screenshots**
![default](https://user-images.githubusercontent.com/12811070/50725354-4c26de80-1137-11e9-90e3-ab16bcbba044.png)
![default](https://user-images.githubusercontent.com/12811070/50725598-c147e300-113a-11e9-87cf-4ed3d3cfa509.png)

**Comment by chemzqm** [comment]
Abnormal exit is normal on coc restart, since vim have to force kill the process sometiems..

> at DecodeBuffer.__dirname.DecodeStream.decoder.push (/snapshot/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)

please paste full messages, get the messages by `:messages`.

**Comment by chemzqm** [comment]
The error would only happen when you have `g:loaded_neosnippet` defined, but you don't have neosnippet plugin installed, I think you should uninstall coc-neosnippet extension by `:CocUninstall coc-neosnippet`

**Comment by chemzqm** [comment]
@likelxl https://github.com/junegunn/vim-plug#commands `PlugClean` doesn't do anything if plugin is in use, try remove coc.nvim directory manually.

**Comment by likelxl** [comment]
@chemzqm 
![default](https://user-images.githubusercontent.com/12811070/50736194-54ddea00-11f5-11e9-99b1-42b54f3be9df.png)
![default](https://user-images.githubusercontent.com/12811070/50736198-60311580-11f5-11e9-8cf0-b20ce1b5ea8d.png)

there is no plug

**Comment by chemzqm** [comment]
I've fixed the unexpected abnormal exit, you can just ignore it.
