### ISSUE TITLE
vim-like behavior from "suggest.noselect"

### ISSUE THREAD

**Issue by lijaesela** [neoclide/coc.nvim#3219]
I turned "noselect" off, as I was quite used to the behavior of Vim and Emacs completion.  
However, while this causes the first item to be selected, it doesn't actually expand to it.
![2021-07-14-231827_251x108_scrot](https://user-images.githubusercontent.com/68930149/125728449-53f2f3aa-f4c8-4f68-910a-121e7ab4c2c9.png)
I think it'd make a lot more sense, be a lot easier, and more vim-like if completing with "noselect" off simply immediately expanded the first suggestion into the actual line.  
From the wording in `:h coc-config-suggest`, it sounds like this option just exists to get rid of cruft-y behavior that wasn't needed, but in that case, why is it even an option that can be turned off?

**Comment by chemzqm** [comment]
> and more vim-like if completing with "noselect" off simply immediately expanded the first suggestion into the actual line.

It's expected behavior, looks like you need read vim's doc first.
