### ISSUE TITLE
Keep nodejs version below 12.21 for 2 years for Debian users

### ISSUE THREAD

**Issue by philliptaylorpro** [neoclide/coc.nvim#3220]
**Is your feature request related to a problem? Please describe.**

If you were to agree to develop coc-vim using nodejs 12.21 and not upgrade the node requirement it for years it would mean Debian Stable users aren't forced to pin their copy of coc-vim to an older version and thus are using the latest one with the newest features and bug fixes.

My current neovim config for Debian Buster says `Plug 'neoclide/coc.nvim', {'branch': 'v0.0.78'}` which works on Debian stable (currently 10/Buster) but I am unable to get bug fixes unless I come up with a way to increase the nodejs package my system has installed.

**Describe the solution you'd like**

Consider supporting coc-vim on nodejs 12.21 for two years as well as newer ones. Then drop  support after the next Debian arrives.

**Describe alternatives you've considered**

There are ways around this, such as installing a later nodejs package from outside the Debian stable repositories, or running coc-vim in a container, but I thought perhaps this was worth considering, if the coc-vim is relatively stable now.

You could also run a parallel branch specifically aimed at Debian stable, that Debian users could specify, if that's less work instead.

**Additional context**

Thanks for your hard work guys.

**Comment by dangerousHobo** [comment]
I'm on Ubuntu 20.04 LTS and just ran `:PlugUpdate` and had this issue bite me.
I was following the release branch `Plug 'neoclide/coc.nvim', {'branch': 'release'}` but now will have to revert to an older branch. 

The latest nodejs version on Ubuntu 20.04 LTS appears to be 10.19.0.

**Comment by chemzqm** [comment]
You have to change esbuild.js and build coc.nvim yourself if you want to use node <= 12.12.0 with it.
Checkout https://nodejs.org/en/about/releases/

**Comment by chemzqm** [comment]
We will support node >= 12.12.0 at least before 2023, but my suggestion is install node 14 or node 16 if you can.
