### ISSUE TITLE
Introduce local variable from a method call 

### ISSUE THREAD

**Issue by strogiyotec** [neoclide/coc.nvim#3226]
Good day , thanks for this amazing plugin, I switched to Vim(Neo) from Intellij and I really miss this feature 
![image](https://user-images.githubusercontent.com/20584185/126350357-40164c3a-5362-4401-b15f-df8b553436fc.png)
So basically you can call the method, trigger completion and Intellij will allow you to create a local variable that stores method call result, it's especially handy for GoLang and Python cause you can return multiple parameters from the method, I wander , Does Coc support something like this ? I read :help page and didn't find anything like this , thanks !

**Comment by chemzqm** [comment]
Should be code action provided from language server, you can write extension of coc.nvim.

**Comment by iago-lito** [comment]
In other terms, you could for instance report to https://github.com/sourcegraph/go-langserver for GoLang or to https://github.com/palantir/python-language-server for Python.
