### ISSUE TITLE
Error detected while processing ~/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim

### ISSUE THREAD

**Issue by ydolphin** [neoclide/coc.nvim#3229]
Error detected while processing /home/zhouyonglong01/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:
line   77: E1208: -complete used without -nargsPress ENTER or type command to continue

**Comment by fannheyward** [comment]
Upgrade your coc.nvim, this has been fixed already https://github.com/neoclide/coc.nvim/issues/3215

**Comment by technowar** [comment]
I am getting the same error with NVIM v0.7.2 and coc-nvim@0.0.82

**Comment by chemzqm** [comment]
@technowar use `:CocInfo` to checkout the version of coc.nvim
