### ISSUE TITLE
LS server configuration with key containing a dot doesn't work as expected

### ISSUE THREAD

**Issue by free-easy** [neoclide/coc.nvim#323]
**Describe the bug**
Given a language server configuration like this
```json
{
    "/home/user/.local/bin/ccls": {
        "args": [],
        "filetypes": ["c"],
        "command": "/home/user/.local/bin/ccls"
    }
}
```
after coc.nvim processes the received configuration, it becomes
```json
{
    "/home/user/": {
        "local/bin/ccls": {
            "args": [],
            "filetypes": ["c"],
            "command": "/home/user/.local/bin/ccls"
    }
}
```

The problems resides in this function
https://github.com/neoclide/coc.nvim/blob/0034ce4720bd99097997395f8c2db100df91ea71/src/configuration/index.ts#L81-L97
Specifically, in this line
https://github.com/neoclide/coc.nvim/blob/0034ce4720bd99097997395f8c2db100df91ea71/src/configuration/index.ts#L90

Clearly, if `${k}` contains a dot, there's not way `model.setValue()` can understand whether the dot is part of a key or means property access.

**Reproduce**

**Ensure that the key contains a dot**

**Comment by chemzqm** [comment]
Hm, I think you should only use word characters as id of language server.

**Comment by chemzqm** [comment]
coc-json doesn't support validation of `patternProperties`, so I add a error message for invalid language server id.

**Comment by free-easy** [comment]
Perfect. Seems reasonable to me.

**Comment by wsdjeg** [comment]
ok, got it:

```
{
    "/home/user/": {
        "local/bin/ccls": {
            "args": [],
            "filetypes": ["c"],
            "command": "/home/user/.local/bin/ccls"
    }
}
```

here, the first `/home/user/` is just the language server id, it is not the command.

**Comment by barlik** [comment]
Hi, I'm facing similar problem with `coc-yaml` plugin when trying to dynamically load yaml.schema using `coc#config` function:
```
        call coc#config('yaml.schemas', {
                \ 'https://schema-url.com': '*.yml',
                \})
```
The schema URL isn't interpreted as a literal, but is instead treated as a key with sub elements.
