### ISSUE TITLE
coc_current_function does not work

### ISSUE THREAD

**Issue by spamwax** [neoclide/coc.nvim#3231]
## versions
    
vim version: NVIM v0.6.0-dev+61-g6f48c018b                                                                                             
node version: v16.5.0                                                                                                                 
coc.nvim version: 0.0.80-2351fedfcc
coc.nvim directory: /Volumes/Home/hamid/.config/nvim/plugged/coc.nvim
term: xterm-256color                                                                                                                   
platform: darwin

## Log of coc.nvim

2021-07-22T06:40:17.427 INFO (pid:56584) [plugin] - coc.nvim 0.0.80-2351fedfcc initialized with node: v16.5.0 after 124ms
2021-07-22T06:40:24.040 INFO (pid:56584) [attach] - receive notification: showInfo []

## Describe the bug

`coc_current_function` does not work. Following the snippet from coc.nvim's README.md, the status line does not show the name of current function/scope when cursor is moved.

## Reproduce the bug
Testing the feature with a simple Rust language `main.rs` file:

```rust
fn main() {
    println!("Hello, world!");
}
fn show_me_please() {
    println!("Hello, world");
}
```

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
  ```

- Start (neo)vim with command: `nvim -u mini.vim main.rs`

- Move the cursor to either `main` or `show_me_please` function. Expected behavior is to see the name of the function in status bar

- Run following in command mode while cursor is within one of those functions

```lua
lua print(vim.api.nvim_buf_get_var(0, 'coc_current_function'))
```

You will get `E5108: Key not found: coc_current_function`

- Run following in command mode while cursor is within one of those functions

```vim
echo get(b:,'coc_current_function','')
```

Nothing is displayed in nvim

- I have *also* tested these steps with `python` and `c` files using `nvim` from `brew` (version `0.50`) and the latest `0.60` version built from source
- I have also tested the above `main.rs` file with and without `coc-rust-analyzer` extension and `rust-lang/rust.vim` plugin

**Comment by fannheyward** [comment]
Do you have set `"coc.preferences.currentFunctionSymbolAutoUpdate": true` in your coc-settings.json? Check `:h coc_current_function`.

**Comment by spamwax** [comment]
Thanks, did not know about that since I was just following the example in the README file.
