### ISSUE TITLE
Support definition content on hover.

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#3233]
Show definition content on hover window, Like hover with `<CMD>` pressed on VSCode.

Make languages module support fetch definition links and show the content on enhanced hover.

**Comment by riteshharjani** [comment]
yes.. this will be really appreciated :)
As of now what I do is everytime fzf grep for the current function which then opens in the preview window but it gives me all the references of this function (along with fzf preview option)
If I can directly hover and get the full scroll-able definition of the function on hover/(something similar to show_documentation()). That would be super awesome!!
