### ISSUE TITLE
I can not use "suggest.enablePreselect" on vim

### ISSUE THREAD

**Issue by Hungpro3112** [neoclide/coc.nvim#3237]
I want vim with auto-completion can always choose the first item like VSCode or PyCharm
I tried some ways in this [https://github.com/neoclide/coc.nvim/issues/124](url) but it not work to me
My version of vim i am using is 8.2.
"suggest.enablePreselect" just work on NeoVim
Does have any ways to solve this problem in Vim 8.2?
Thanks for reading

**Comment by chemzqm** [comment]
No api for vim to select complete item by index, you can use `"suggest.noselect": false` to make vim select first complete item.

**Comment by Hungpro3112** [comment]
> No api for vim to select complete item by index, you can use `"suggest.noselect": false` to make vim select first complete item.

How to write "suggest.noselect" : false in coc-settings.json. Sorry because i don't know how to write JSON file right way.
Here is my coc-settings.json file:
![image](https://user-images.githubusercontent.com/75968004/126867536-767eba1f-177f-4e2b-ae8c-4b93a31defdf.png)
