### ISSUE TITLE
can't install coc.nvim

### ISSUE THREAD

**Issue by roadupcc** [neoclide/coc.nvim#3238]
## [error info]:

coc.nvim requires at least Vim 8.0.1453 or Neovim 0.3.2, but you're using an older version.
Please upgrade your (neo)vim.
You can add this to your vimrc to avoid this message:
    let g:coc_disable_startup_warning = 1
Note that some features may error out or behave incorrectly.
Please do not report bugs unless you're using at least Vim 8.0.1453 or Neovim 0.3.2.
Error detected while processing function coc#rpc#start_server[17]..<SNR>21_start:
line   27:
E475: Invalid argument: env
Failed to start coc service
Error detected while processing function <SNR>18_Hi:
line   11:
E418: Illegal value: strikethrough
Press ENTER or type command to continue

os 
Linux n248-128-121 4.14.81.bm.15-amd64 #1 SMP Debian 4.14.81.bm.15 Sun Sep 8 05:02:31 UTC 2019 x86_64 GNU/Linux

node version
v12.22.1

## Result from CocInfo

![image](https://user-images.githubusercontent.com/18000037/126862886-4042273c-e47d-47f6-b89a-5c2adc054f73.png)

- my config file `.vimrc.` 
```vim
"autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') |
""    \ execute 'NERDTree' argv()[0] | wincmd p| enew | execute 'cd '.argv()[0] | endif
" Exit Vim if NERDTree is the only window left.
" autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
"    \ quit | endif

set number
set autoindent
set cindent
set nofoldenable
set foldmethod=syntax
set cursorline
set cul
filetype plugin indent on
set langmenu=zh_CN.UTF-8 "语言设置
set helplang=cn
filetype on " 载入文件类型插件
noremap S :w<CR>

call plug#begin("~/.vim/plugged")
Plug 'preservim/nerdtree'  "侧边栏
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'vim-airline/vim-airline'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

autocmd InsertLeave * if pumvisible() == 0|pclose|endif
let g:rustfmt_autosave = 1
let g:rust_clip_command = 'pbcopy'

" set completeopt=longest,menu
set completeopt=preview,menu
set autoread

"自动补全括号
:inoremap ( ()<ESC>i
:inoremap ) <c-r>=ClosePair(')')<CR>
":inoremap { {<CR>}<ESC>O
":inoremap } <c-r>=ClosePair('}')<CR>
:inoremap [ []<ESC>i
:inoremap ] <c-r>=ClosePair(']')<CR>
:inoremap " ""<ESC>i
:inoremap ' ''<ESC>i


autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescriptreact
```

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/18000037/126862875-7f7b7195-8106-41dd-adb3-956f66e724a2.png)

![image](https://user-images.githubusercontent.com/18000037/126862847-3c8402bc-6122-44a9-9ff0-e9a050757432.png)

**Comment by fannheyward** [comment]
> coc.nvim requires at least Vim 8.0.1453 or Neovim 0.3.2, but you're using an older version.

What's your vim/nvim version? Upgrade to newer version.

**Comment by roadupcc** [comment]
> > coc.nvim requires at least Vim 8.0.1453 or Neovim 0.3.2, but you're using an older version.
> 
> What's your vim/nvim version? Upgrade to newer version.

I already install the newest version vim

![image](https://user-images.githubusercontent.com/18000037/126863490-03c97cc6-929e-4752-b184-5910c77f2fcd.png)

$ sudo apt-get upgrade vim
Reading package lists... Done
Building dependency tree
Reading state information... Done
vim is already the newest version (2:8.0.0197-4+deb9u3).
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  python-dateutil python-magic s3cmd
Use 'sudo apt autoremove' to remove them.
The following packages have been kept back:
  libibverbs-dev libibverbs1 perftest
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Comment by fannheyward** [comment]
Your vim version is 8.0.707, lower than 8.0.1453.
