### ISSUE TITLE
Autocomplete shows wrong completion

### ISSUE THREAD

**Issue by jtroeth1** [neoclide/coc.nvim#3239]
clang cpp, completion shows me an obfuscated list of types, which do not contatin any types that actually exist in the class:
![screenshot_2021-07-24_20-20-56](https://user-images.githubusercontent.com/37925036/126865868-e7afe0eb-3b91-4c73-9ce3-aa157d012f02.png)

However if I make a selection, and then backspace the selection, it shows me the expected completion:
![screenshot_2021-07-24_20-21-30](https://user-images.githubusercontent.com/37925036/126865887-681119c7-15c3-4a8e-bc94-4142ccb9867f.png)

Any ideas what I can do to get the correct completion by default?

Thanks

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by jtroeth1** [comment]
Turns out it works fine in nvim, but not vim. I will just use nvim from now on. Also a lot of compilation errors have disappeared.

**Comment by chemzqm** [comment]
Possible your language server not fully initialized or you need to increase `"suggest.triggerCompletionWait"` configuration.
