### ISSUE TITLE
vim-node-coc: error on notification 'sendRequest': TypeError: cannot read property 'method' of undefined

### ISSUE THREAD

**Issue by vieko** [neoclide/coc.nvim#324]
**Result from CocInfo**
## versions

vim version: NVIM v0.3.3
node version: v11.6.0
coc.nvim version: 0.0.45
term: st-256color
platform: linux

## Error messages
error on notification 'sendRequest': TypeError: Cannot read property 'method' of undefined
error on notification 'sendRequest': TypeError: Cannot read property 'method' of undefined
## Output channel: highlight
[Info - 10:50:04 a.m.] Highlight server running in node v11.6.0

**Describe the bug**
Upon opening NVIM, I see the following error:
`[vim-node-coc]: error on notification 'sendRequest': TypeError: Cannot read property 'method' of undefined`

**To Reproduce**

- install any version of coc.nvim after 0.0.34 (0.0.34 does not suffer from this issue)

**Comment by chemzqm** [comment]
It should be the call to `CocRequest` missing arguments, you should find out where's used in your vimrc or your vim plugins.

**Comment by vieko** [comment]
Excellent! Thanks for the quick response.n
