### ISSUE TITLE
Language-specific autocompletion not working on remote files

### ISSUE THREAD

**Issue by Cy-r0** [neoclide/coc.nvim#3246]
## versions

vim version: VIM - Vi IMproved 8.2 8023165
node version: v14.17.0
coc.nvim version: 0.0.80-c02be2e344
coc.nvim directory: /home/ciro/.dotfiles/dotfiles/.vim/pack/coc/start/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2021-07-27T12:24:12.174 INFO (pid:8378) [plugin] - coc.nvim 0.0.80-c02be2e344 initialized with node: v14.17.0 after 78ms
2021-07-27T12:24:14.203 INFO (pid:8378) [attach] - receive notification: showInfo []

## Describe the bug

Autocompletion works on local files but not on files opened with SCP.
E.g. when I'm editing a python file on my local machine and start typing
```python
import n
```
The autocompletion gives me a wide choice of libraries installed on my system like numpy, numba, netrc, etc.
However, when I edit a remote file with 
```
vim scp://remotemachine//path/to/file
```
The only autocompletion I have is the generic one that pulls suggestions from words in the same file.

I'm not sure whether it's a problem with the language servers or coc itself, but this bug happens both when I edit python files and C files, so it affects at least those 2 languages.

Is this just a limitation of editing remote files over SCP?

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

I've tried running vim with the minimal vimrc above, but I still get this issue.

**Comment by chemzqm** [comment]
You have to install language server on your server and use ssh instead since language server can't understand scp protocol.

**Comment by Cy-r0** [comment]
Oh, I see, that's unfortunate. Thank you for the quick reply!
