### ISSUE TITLE
go back to the auto complete list, the completion does not change

### ISSUE THREAD

**Issue by chenzhiwei** [neoclide/coc.nvim#3249]
## Result from CocInfo
vim version: VIM - Vi IMproved 8.1 8012269                                                              |~
node version: v14.17.1                                                                                  |~
coc.nvim version: 0.0.80-91c1114046                                                                     |~
coc.nvim directory: /home/xxx/.vim/bundle/coc.nvim                                                  |~
term: dumb                                                                                              |~
platform: linux

## Describe the bug

When the auto completion popup appear, I use `ctrl + n` to select a target and the text before cursor changed to to this target, but when I `ctrl + p` to select the previous one, the text keeps unchanged. 

![1627463457565](https://user-images.githubusercontent.com/672668/127297275-1042fb2e-2254-4893-afe7-9f0921db09c9.png)

My vim plugins and coc extensions:

```
        Plug 'neoclide/jsonc.vim'
        Plug 'neoclide/coc.nvim', {'branch': 'release'}
        Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}
        Plug 'fatih/vim-go', {'tag': '*'}
        Plug 'plasticboy/vim-markdown'
        Plug 'vim-airline/vim-airline'
let g:coc_global_extensions = ['coc-tabnine', 'coc-yaml']
```

## Reproduce the bug

See the description.

**Comment by chemzqm** [comment]
Issue of your vim, try minimal vimrc.

**Comment by chenzhiwei** [comment]
Thank you, I also can't reproduce in my local machine now, will retry tomorrow in office.

Bye the way, I want to ask another question of coc-tabnine, after I installed the coc-tabnine extension, the completion popup menu contains both `[TN]` and `[LS]`.

When I use `ctrl+p` to select the popup menu items, only `[LS]` items can be automatically appear in the cursor position, I need to run `ctrl+y` to make the `[TN]` items to appear.

Is there a way to make '[TN]' items have same behavior with '[LS]' items?

**Comment by chemzqm** [comment]
It means coc.nvim failed to resolve InsertText from snippet https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources

**Comment by chenzhiwei** [comment]
I read through the document, and found this https://github.com/neoclide/coc.nvim/wiki/Using-snippets#snippet-completion, but it does not work.

What do you mean `coc.nvim failed to resolve InsertText from snippet`? Is is a bug or something else? I can't find error logs about this.

![image](https://user-images.githubusercontent.com/672668/127341190-1fcc55ca-e51f-445a-9903-6859fdf1933a.png)

In following picture, the `V` can be automatically inserted, but not the later part.

![image](https://user-images.githubusercontent.com/672668/127343199-0e83be5c-3cd8-4dd9-b98c-714f3e72805d.png)
