### ISSUE TITLE
[coc.nvim] build/index.js not found, please compile coc.nvim by: npm run build

### ISSUE THREAD

**Issue by robin2014** [neoclide/coc.nvim#3250]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
How do you install coc.nvim?

**Comment by robin2014** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        yes，when i open a file with vim,the error come out:
        
    
        
            
        
    this is my .vimrc:this is the plug dir:what's the problem?
    
        
        

        
    

    On 7/28/2021 18:13，Heyward ***@***.***> wrote： 



How do you install coc.nvim?

**Comment by chemzqm** [comment]
We've changed default branch to master back, you need `git checkout release` in the folder of coc.nvim.

**Comment by robin2014** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    it's ok now,thank;
        I add   Plug 'neoclide/coc.nvim', {'branch': 'release'}     in my .vimrc,and then ：PlugInstall, but it came out a error when install , but installed success actually,:PlugStatso i :PlugClean to uninstall the coc and changed the config to Plug 'neoclide/coc.nvim,and install again no erros again,but the branch is master:
    
        
            
        
    
    
        
        

        
    

    On 7/28/2021 18:43，Qiming ***@***.***> wrote： 



We've changed default branch to master back, you need git checkout release in the folder of coc.nvim.

**Comment by k2s09** [comment]
The above message is a bit confusing, so if you are getting the same error, remove the line `Plug 'neoclide/coc.nvim'` and do `:PlugClean`. This will remove the whole directory containing that plugin. Now put the line `Plug 'neoclide/coc.nvim', { 'branch': 'release'}`, save and PlugInstall. That should fix it.
