### ISSUE TITLE
C++: How to disable coc-rename applying code formatting after renaming a variable?

### ISSUE THREAD

**Issue by Nikita128** [neoclide/coc.nvim#3254]
Or maybe is there a way to edit formatting rules? I'm asking here, because I've scanned through the documentation and couldn't find anything on configuration of `coc-rename` command.

To be more specific I want to focus on indentation. I have a 4 space indentation set in my init.vim config. I have a Neoformat plugin, which utilizes clang-format-10, installed and configured to have the same indentation rules. But after I rename a variable with `coc-rename` it uses it's own formatting rules and applies 2 space indentation everywhere inside the scope of the variable. How do I change such behavior?

**Comment by fannheyward** [comment]
AFAIK, you can't.

**Comment by Nikita128** [comment]
Just checked the issue you linked and, wow, that's a shame. I see that it might be reasonable in case of snippets, but I don't need formatting at all in a case of changing a name of a specific variable.

You said that formatting comes from the language server, maybe I could set formatting configuration there.

**Comment by Nikita128** [comment]
Yeah, I had to add .clang-format file to my project, so clangd would format files accordingly to it.
