### ISSUE TITLE
[coc.nvim] build/index.js not found, please compile coc.nvim by: npm run build

### ISSUE THREAD

**Issue by CrazyOptimist** [neoclide/coc.nvim#3258]
## Result from CocInfo

```
 Error: javascript bundle not found, please compile code of coc.nvim by esbuild.
```

## Describe the bug

It was working without any issue, but this error happened today when I setup a new machine (Ubuntu 20.04, same as before maybe a few days ago).  
When I open vim editor, it shows:
`[coc.nvim] build/index.js not found, please compile coc.nvim by: npm run build`

I suspect the latest release went wrong, maybe built artifact was not pushed alright, etc.

## Reproduce the bug

- Create file `mini.vim` with：

My vimrc is here:
https://github.com/CrazyOptimist/dotfiles/blob/main/vimrc  
Just uncomment the line 51.  
Run `rm -rf ~/.vim/bundle/coc.nvim/`  
Run `:PluginInstall` in the vim.

- Start vim with command: `vim`

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/55074937/127707480-494cf661-5a45-4ad7-aab1-0ca6d060b5c6.png)

## Workaround

```bash
cd ~/.vim/bundle/coc.nvim
yarn install
yarn build
```
Boom! It works now.

**Comment by chemzqm** [comment]
The default branch changed to master

**Comment by Char-Aznable** [comment]
@chemzqm I have the same error and same OS ubuntu 20.04 with the following setup:
```
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
```
which branch should I use?

**Comment by chemzqm** [comment]
> which branch should I use?

It's up to you.

**Comment by Char-Aznable** [comment]
> The default branch changed to master

Not sure I understand your answer. You mentioned that the master branch is expected to work but I am still seeing the same error from it. Is this a branch related problem or what?

**Comment by fannheyward** [comment]
@Char-Aznable If you're using `master` branch, you need to build from source with yarn, if you're using `release` branch, it's built already.

**Comment by muyuuuu** [comment]
> Boom! It works now.

 Unknown command: yarn. 


> @Char-Aznable If you're using `master` branch, you need to build from source with yarn, if you're using `release` branch, it's built already.

I'm in release branch, this problem also exists.

**Comment by EdarkoGit** [comment]
What should I do if I'm not using plug, but the manual method nvim/pack/plugin/start ?

**Comment by jmonari** [comment]
Yoo mine worked man TY

**Comment by adamency** [comment]
@fannheyward That's not true, at least not for Windows (11). I had to go `~/Appdata/Local/nvim-data/plugged/coc.nvim` and do `yarn install ; yarn build` too solve the error.

**Comment by stev-kast** [comment]
I just had this problem in arch linux, the Workaroud works for me, just make sure about the coc path, in my case it is: ~/.local/share/nvim/plugged/coc.nvim

**Comment by CrazyOptimist** [comment]
It still happens, and I still use the workaround.  
Instead of building it, just switching the git branch also works:
```bash
git checkout release
```

**Comment by timblaktu** [comment]
Using vim 8.2 builtin plugin mgmt, Seems to happen when the coc.nvim submodule is checked out using git remote branch tracking, which checks out submodule to detached head, even when specifying to track release. As previously noted, the issue only goes away when checking out release manually.

**Comment by nojitsi** [comment]
Fixed by settin 
 NeoBundle 'neoclide/coc.nvim'
without branch specification

**Comment by nojitsi** [comment]
Changer config in your .vimrc to
NeoBundle 'neoclide/coc.nvim', {'build': {'unix': 'yarn install --frozen-lockfile'},}
other os will need other key for command
available keys: windows, cygwin, mac, unix

**Comment by tykoon787** [comment]
I encountered this error in `WSL Ubuntu 20.04 LTS`. 
This error occurs because COC is missing some of its essential dependencies. 

Here is how I solved it. 

1. Navigate to the directory (Note that this path may be different). In my case, the path was `~/.local/share/nvim/plugged/coc.nvim`
2. Use your package manager to install dependencies. You can either use `npm` or `yarn`. In my case, i ran `npm install`
3. Restart your NEOVIM
4. Works Like a CHARM 👍

**Comment by arantebw** [comment]
I encountered this after setting up a new dev machine, and resolved it by simply switching to the `release` branch. 🍻

**Comment by CatKoder123** [comment]
> @adamency I think thats more an issue of the plugin manager. If I use what @fannheyward says it still tells me to use `yarn install` and that stuff, but I realized that my `~/Appdata/Local/nvim-data/plugged/coc.nvim` was on the branch `master`, I just did `git checkout release` and all worked. Thats why I think is something related with the plugin manager.

it worked it was on master branch i saw on my terminal but didnt knew it was a issue

**Comment by shawal-mbalire** [comment]
```bash
cd ~/.vim/plugged/coc.nvim
npm ci
```

works for me

**Comment by dreamalligator** [comment]
`git submodule set-branch --branch release -- vim/.vim/pack/vendor/start/coc.nvim`

**Comment by stanleyogada** [comment]
> ## Workaround
> ```shell
> cd ~/.vim/bundle/coc.nvim
> yarn install
> yarn build
> ```
> 
> Boom! It works now.




## This worked! For me, I had to locate a similar directory 

> cd ~/.local/share/nvim/plugged/coc.nvim
> npm i

**Comment by mateotop** [comment]
> ```shell
> cd ~/.vim/plugged/coc.nvim
> npm ci
> ```
> 
> works for me since I use Plug to manage my vim plugins

I did that with `lazy-nvim` on windows. 

It has other path. Probably for novice my comment will be helpful 

0. Install coc.nvim in your  init.lua (`nvim ~\AppData\Local\nvim\init.lua` ) 

```init.lua
require('lazy').setup({
-- other plugins
'neoclide/coc.nvim',
}, {})
```

1. Install dependencies for `coc.nvim` in its path
```powershell 
cd ~\AppData\Local\nvim-data\lazy\coc.nvim\
npm ci 
```

**Comment by barrientosvctor** [comment]
> ```shell
> cd ~/.vim/plugged/coc.nvim
> npm ci
> ```
> 
> works for me since I use Plug to manage my vim plugins

It worked. Thanks!

**Comment by divaniamirmohamad** [comment]
@tykoon787 thanks man it worked on my Ubuntu 22 as well! 👍

**Comment by jotacedesigner** [comment]
For me use: :call coc#util#install()

**Comment by seriiserii825** [comment]
For me this works

```
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'npm ci'}

```

**Comment by xufew** [comment]
> ```shell
> cd ~/.vim/plugged/coc.nvim
> npm ci
> ```
> 
> works for me since I use Plug to manage my vim plugins

it worked!!

**Comment by ASHISHSINGHNEGI** [comment]
> I encountered this error in `WSL Ubuntu 20.04 LTS`. This error occurs because COC is missing some of its essential dependencies.
> 
> Here is how I solved it.
> 
> 1. Navigate to the directory (Note that this path may be different). In my case, the path was `~/.local/share/nvim/plugged/coc.nvim`
> 2. Use your package manager to install dependencies. You can either use `npm` or `yarn`. In my case, i ran `npm install`
> 3. Restart your NEOVIM
> 4. Works Like a CHARM 👍

thanks it worked for me
