### ISSUE TITLE
Can I disable colors in hover window?

### ISSUE THREAD

**Issue by carljohnesan** [neoclide/coc.nvim#3259]
I'm using 'flattened' theme, and hover popup for function definition looks like:

![Screen Shot 2021-07-31 at 12 34 55](https://user-images.githubusercontent.com/47556468/127735725-b7cdaa63-83b6-4ae9-9f60-9caef5c86b81.png)

Is there a way to disable coloring in the hover popup window?

**Comment by fannheyward** [comment]
Try to set `"coc.preferences.enableFloatHighlight"` to false.

**Comment by carljohnesan** [comment]
Thank you! Unfortunately, it did not work. Colors are still there (tried to restart vim)

**Comment by chemzqm** [comment]
No, fix your color scheme or fork the code instead

**Comment by carljohnesan** [comment]
Very nice, thanks for help
