### ISSUE TITLE
coc-tsserver: Faulty syntax highlighting

### ISSUE THREAD

**Issue by tbo** [neoclide/coc.nvim#326]
**Result from CocInfo**

```
## versions

vim version: NVIM v0.3.2
node version: v9.10.1
coc.nvim version: 0.0.45
term: xterm-256color
platform: darwin

## Error messages

## Output channel: tsserver
[Info  - 16:11:44] Forking TSServer
PATH: /Users/tbo/.config/fnm/bin:/Users/tbo/.fzf/bin:/Users/tbo/.yarn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/kitty.app/Contents/MacOS:/Users/tbo/bin:/Users/tbo/.cargo/bin 
[Info  - 16:11:44] Started TSServer
{
  "path": "/Users/tbo/git/project/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.1.2",
    "version": "3.1.2"
  }
}
```

**Describe the bug**

The syntax highlighting seems to be broken. I don't know how, but something overrides all highlight groups with "typescriptStringB". Other features (like auto completion), still work as expected. Syntax highlighting works again, after I disable coc.nvim.

**To Reproduce**

I can only produce it with my project. I was unable to find out which part of it is causing this behavior.

**Screenshots**
![kapture 2019-01-08 at 16 17 20](https://user-images.githubusercontent.com/264745/50840893-cc318c00-1363-11e9-8697-6aa7c6e086fd.gif)

**Comment by chemzqm** [comment]
It's bug of vim, try:

* `syntax sync fromstart` to fix highlight.
*  Disable coc from add highlight
*  Use another syntax plugin for tsx.

**Comment by pablopunk** [comment]
I had this issue for a long time. `syntax sync fromstart` fixes it but it's a pain to run every time it happens. How do you personally deal with this issue @chemzqm ?

**Comment by chemzqm** [comment]
- Format your code to make your lines not too long
- Use better syntax plugin
- Configure `synmaxcol` option
- Break your javascript bundle to smaller files
