### ISSUE TITLE
Timeout error in coc.nvim

### ISSUE THREAD

**Issue by Hungpro3112** [neoclide/coc.nvim#3260]
Recently, when i use vim, sometimes i see this error 
![image](https://user-images.githubusercontent.com/75968004/127739635-c2ccc84d-94b2-4b90-b1d7-360cab3ee921.png)
What happen with my vimrc and how to fix it ?
Thanks for helping !!!

**Comment by jackieli-tes** [comment]
you should try to reproduce it in minimal vimrc make sure it's a bug in coc.nvim.

**Comment by Hungpro3112** [comment]
![image](https://user-images.githubusercontent.com/75968004/127758031-4a2d56b7-cbb8-43bb-a92a-b158c2ae9f27.png)
Here is some coc.nvim settings

**Comment by chemzqm** [comment]
Some coc extension parse your vimrc, try disable some of them

**Comment by zoumi** [comment]
I got this with gvim on windows. But nvim-qt doesn't have this problem.

**Comment by sisrfeng** [comment]
![image](https://user-images.githubusercontent.com/53520949/175753165-5b8a3d02-528f-41ab-a1c3-57f674b5d7c9.png)

how to locate where the error comes from?
I have them:
![image](https://user-images.githubusercontent.com/53520949/175753194-2adb60b0-d680-440f-9a94-2db0ffcb3a1d.png)
