### ISSUE TITLE
Vim can't install Lua LSPs if configured through `g:coc_global_variable`

### ISSUE THREAD

**Issue by Jarmos-san** [neoclide/coc.nvim#3261]
## Result from CocInfo
```
## versions

vim version: NVIM v0.5.0
node version: v16.1.0
coc.nvim version: 0.0.80-9fd90ad761
term: vtpcon
platform: win32 
```

## Describe the bug

Configuring the extensions to install with `g:coc_global_variable` fails when trying to install any of the Lua extensions. This is so because they're not available in the NPM Registry & thus returns a 405 error.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  let g:coc_global_variable = [ ..., 'Alloyed/lua-lsp', ..., ]
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/31373860/127745826-6581cdfd-e98d-4942-af8e-7ef2ba8e5653.png)

## Personal Suggestions

Mention how to download either of the Lua LSP binaries on the user's local machines. It's a subtle solution & one which will save a couple of minutes for the user. And will also buy some time for the `coc` maintainers to resolve this edge case (if there're any such plans to do so).

**Comment by oblitum** [comment]
There's no `g:coc_global_variable`, only `g:coc_global_extensions`, and the purpose is to install coc extensions only, there's no support for random software. A Coc extension for Lua is coc-lua for example, and it should be installed through `g:coc_global_extensions`, I use it myself.

**Comment by Jarmos-san** [comment]
> There's no `g:coc_global_variable`, only `g:coc_global_extensions`, and the purpose is to install coc extensions only, there's no support for random software. A Coc extension for Lua is [coc-lua](https://github.com/josa42/coc-lua) for example, and it should be installed through `g:coc_global_extensions`, I use it myself.

My bad, fixed the typos I meant to talk about `coc_global_extensions` as well.

Anyway thanks for sharing about `coc-lua`, I think it might be better to add to the wiki as well. Doesn't hurt to do so & will only help someone else looking for it.

Cheers!

**Comment by oblitum** [comment]
There's also [coc-sumneko-lua](https://github.com/xiyaowong/coc-sumneko-lua). I didn't try this one but I'll, it may be even better than coc-lua because coc-lua's author doesn't respond issues, and there's some important issues open there without response.

**Comment by oblitum** [comment]
Also, by the way, the wiki is open for contributions.

**Comment by oblitum** [comment]
> I didn't try this one but I'll

Except for [this issue](https://github.com/xiyaowong/coc-sumneko-lua/issues/1), it's working well.
