### ISSUE TITLE
Allow limit the subset of used features of a specific language server

### ISSUE THREAD

**Issue by przepompownia** [neoclide/coc.nvim#3263]
For some language I use two language servers because the first does not support some feature or does it slower than the second. The side effects are duplicated requests and then duplicated results. 

I wish I could configure the client to explicitly configure which features have to be enabled (if supported) for the particular language server (like `...langservername.capabilities.textDocument.references: false`). 

Not all language servers are configurable enough to make it at the server side.

**Comment by chemzqm** [comment]
We could support user specfied capabilities section for language server

**Comment by oblitum** [comment]
FYI, at the moment this is possible to a certain extent because you can disable/enable completion for one, diagnostics for other. Not as fine grained as specific capabilities though.

**Comment by przepompownia** [comment]
> FYI, at the moment this is possible to a certain extent because you can disable/enable completion for one, diagnostics for other. Not as fine grained as specific capabilities though.

I know these settings but they are not enough to precise splitting the sets of roles of each LS for the given language.

**Comment by chemzqm** [comment]
Fixed by a60702d0

**Comment by yaegassy** [comment]
Hi, @chemzqm 

Does this change affect the coc extension if it uses `disableCompletion`, `disableDiagnostics`, `disableDefinition`, etc.? Will that extension stop working properly disable-related? <https://github.com/neoclide/coc.nvim/commit/a60702d0b0da710cfa261c0970ff51f34d0fef0b>

**e.g.**:

```vim
  const clientOptions: LanguageClientOptions = {
    documentSelector: [
      // ...snip
    ],
    initializationOptions: {
      // ...snip
    },
    disableCompletion: ...snip
    disableDiagnostics: ...snip
    disableDefinition: ...snip
  };
```

**Comment by yaegassy** [comment]
Thank you for the adjustment. <https://github.com/neoclide/coc.nvim/commit/c610d4c69e1e11ce80f8770235c85304f7277178>
