### ISSUE TITLE
Example config needlessly disables signcolumn on new vim versions

### ISSUE THREAD

**Issue by Trainraider** [neoclide/coc.nvim#3271]
This chunk here in the example config:
```
if has("nvim-0.5.0") || has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif
```
seems like a weird work around and definitely causes unnecessary pain. It makes gitsigns from coc-git overwrite my line numbers when everything works perfectly fine with signcolum set to yes. I'm using NVIM v0.6.0-dev.
I don't really know what syntax the config file uses but I'm much happier with this block removed. I assume it's necessary though for those using 0.5.0 or with the patch.

**Comment by xiyaowong** [comment]
run `h 'signcolumn'` get details about this option

**Comment by chemzqm** [comment]
Read help before you copy vim configuration.
