### ISSUE TITLE
Coc a bit laggy on large files (about 200kB+) for nvim

### ISSUE THREAD

**Issue by zawedcvg** [neoclide/coc.nvim#3273]
## versions

vim version: NVIM v0.6.0-dev
node version: v16.3.0
coc.nvim version: 0.0.80-73861dc2ae
coc.nvim directory: /home/neeladri/.config/nvim/autoload/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-08-05T17:06:54.577 WARN (pid:8101) [attach] - Plugin not ready when received "highlight" []
2021-08-05T17:06:54.818 INFO (pid:8101) [plugin] - coc.nvim 0.0.80-73861dc2ae initialized with node: v16.3.0 after 234ms
2021-08-05T17:06:54.908 INFO (pid:8101) [services] - registered service "tsserver"
2021-08-05T17:06:58.092 INFO (pid:8101) [attach] - receive notification: showInfo []

## Describe the bug

When working with big files in neovim, approx 200kb+, there seem to be a bit of lag in autocomplete and the typing. However, the same thing doesn't occur in vim or with neovim with the minimal vimrc. 
On profiling these, end up being the biggest time consumers
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    3   0.292435   0.189167  coc#highlight#update_highlights()
   44   0.214616   0.207527  coc#_complete()
    6   0.164887   0.146719  coc#float#create_cursor_float()
Is there any way to fix this?
https://github.com/zawedcvg/dotfiles  (my dotfiles if required)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden 
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.
doing this provides no lag in the completion or the typing.

**Comment by fannheyward** [comment]
What language and language server do you use?

> the same thing doesn't occur in vim or with neovim with the minimal vimrc.

What does this mean? The laggy doesn't exist with vim + coc only?

**Comment by zawedcvg** [comment]
Using the coc-tsserver. What I mean is that with the minimal vimrc and neovim or with a bit of config on my vimrc and running vim and coc gives no issues. This led me to think that it was a problem with some of my other functions or plugins. However on profiling it comes out to the above coc functions which consume the most time.

**Comment by chemzqm** [comment]
You may have enabled `diagnostic.refreshOnInsertMode` and there're too many extmarks on your buffer.

**Comment by chemzqm** [comment]
```
3 0.292435 0.189167 coc#highlight#update_highlights()
```
Seems not too much time, but if you have big file with lots of error, it will be laggy, consider use `:h b:coc_diagnostic_disable` to disable diagnostic refresh for that buffer.
