### ISSUE TITLE
[coc.nvim] build/index.js not found, please compile coc.nvim by: npm run build

### ISSUE THREAD

**Issue by wpeguero** [neoclide/coc.nvim#3276]
Hi, I am currently experiencing an issue where I constantly get the error in the title. I have already tried the steps and solutions from the last two issue in regards to the index.js not found issue, but I am still not able to resolve this. I already have nodejs installed as well as yarn. 

Here is the mini.vim file:
'''vim
set nocompatible
set runtimepath^=~/.vim/bundle/coc.nvim
filetype plugin indent on
syntax on
set hidden

Here is the error I get when I try the command npm run build:
Error: Cannot find module 'esbuild'
Require stack:
- /home/wbpeguerorosario/.vim/bundle/coc.nvim/esbuild.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at start (/home/wbpeguerorosario/.vim/bundle/coc.nvim/esbuild.js:33:9)
    at Object.<anonymous> (/home/wbpeguerorosario/.vim/bundle/coc.nvim/esbuild.js:73:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '$HOME/.vim/bundle/coc.nvim/esbuild.js' ]
}

I am currently using the release version of coc.nvim. Here is my vimrc file:

" Enabling filetype support provides filetype-specific indenting,
" syntax highlighting, omni-completion and other useful settings.
filetype plugin indent on
syntax on
set noswapfile
" `matchit.vim` is built-in so let's enable it!
" Hit `%` on `if` to jump to `else`.
runtime macros/matchit.vim

" various settings
set autoindent                 " Minimal automatic indenting for any filetype.
set backspace=indent,eol,start " Proper backspace behavior.
set hidden                     " Possibility to have more than one unsaved buffers.
set incsearch                  " Incremental search, hit `<CR>` to stop.
set ruler                      " Shows the current line number at the bottom-right
                               " of the screen.
set wildmenu                   " Great command-line completion, use `<Tab>` to move
                               " around and `<CR>` to validate.
set number		       " Turns on the numbers on the left to count the lines.

" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

" Set shift width to 4 spaces.
set shiftwidth=4

" Set tab width to 4 columns.
set tabstop=4

" Use space characters instead of tabs.
set expandtab

" Ignore capital letters during search.
set ignorecase

" Override the ignore case option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Use highlighting when doing a search.
set hlsearch

" Enable auto completion menu after pressing TAB.
set wildmenu

" Make wildmenu behave like similar to Bash completion.
set wildmode=list:longest

" There are certain files that we would never want to edit with Vim.
" Wildmenu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" This is the configuration related to Vundle. A package manager for
" installing plug-ins in vim.
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
" Changes the theme of the vim editor.
Plugin 'sonph/onehalf', {'rtp':'vim'}
Plugin 'gruvbox-community/gruvbox'
" Allows the user to view certain information from the file, such as the name
" and the type of said file.
Plugin 'powerline/powerline', {'rtp':'vim'}

" Installs the autocompletion file.
Plugin 'ycm-core/youcompleteme'

Plugin 'neoclide/coc.nvim', {'branch':'release'}
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin only
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
set t_Co=256
colorscheme gruvbox
set rtp+=/bundle/powerline
set laststatus=2

source $HOME/.vim/plugged/coc.vim

This has been an infuriating experience trying to follow through the directions only to end up with nothing but the same error no matter how hard I tried.

**Comment by chemzqm** [comment]
You have to run `yarn install` on master branch https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim
