### ISSUE TITLE
Error sign/glyph does not show up in lightline status bar integration 

### ISSUE THREAD

**Issue by Char-Aznable** [neoclide/coc.nvim#328]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
```
... too long to show
```
**Describe the bug**
I have followed coc.nvim's doc for putting coc-status in lightline status bar:
```
  let g:lightline = {
	\ 'colorscheme': 'wombat',
	\ 'active': {
	\   'left': [ [ 'mode', 'paste' ],
	\             [ 'cocstatus', 'readonly', 'filename', 'modified' ] ]
	\ },
	\ 'component_function': {
	\   'cocstatus': 'coc#status'
	\ },
\ }
```
The problem is that the error glyph does not show up correctly (it's shown as a box of string) even though I have set the error glyph as a capital `x` (`X`) in coc.nvim:
```
"coc.preferences.diagnostic.errorSign": "X",
"coc.preferences.diagnostic.warningSign": "⚠",
"coc.preferences.diagnostic.infoSign": ">>",
"coc.preferences.diagnostic.hintSign": ">>",
```
The strange thing is that the warning glyph shows up in the status bar correctly. Also, all glyphs show up correctly in the sign column in vim but they just got messed up somehow in the status bar.

**Comment by Char-Aznable** [comment]
The problem is that this line https://github.com/neoclide/coc.nvim/blob/a3696178e089f630e6dd4bf0f053e240f77d0825/autoload/coc.vim#L66 has a glyph not supported by my fonts -- @chemzqm can you change it to something simpler (like an `X`) or whatever is set for `coc.preferences.diagnostic.errorSign`?

**Comment by chemzqm** [comment]
I've changed to use emoji for mac only, so it should be useable for your, for further custmization, you can build your own function.

**Comment by adelarsq** [comment]
@chemzqm How to enable again this configuration on Linux. I was using just fine this feature with Linux.

**Comment by pbutler** [comment]
@adelarsq  use the following function instead of coc#status.  It will work mac or not

```
function! CocStatus()
  let info = get(b:, 'coc_diagnostic_info', {})
  let msgs = []
  if get(info, 'error', 0)
    call add(msgs, '❌ ' . info['error'])
  endif
  if get(info, 'warning', 0)
    call add(msgs, '⚠️ ' . info['warning'])
  endif
  return join(msgs, ' ') . ' ' . get(g:, 'coc_status', '')
endfunction
```
