### ISSUE TITLE
CoC for AVR

### ISSUE THREAD

**Issue by K4LCIFER** [neoclide/coc.nvim#3282]
**Is your feature request related to a problem? Please describe.**
With `coc-clangd` as the language server, it is very tricky to get CoC to work with AVR code. Generally CoC will not recognize the AVR includes. 

**Describe the solution you'd like**
CoC extension support for AVR, perhaps something like `coc-avr`

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/discussions/2238
