### ISSUE TITLE
Too many arguments for function: coc#compat#execute Error 

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#3283]
Rencently after upgrading to `neovim v0.6` I started to get the following errors

## Result from CocInfo

![image](https://user-images.githubusercontent.com/33961674/128992233-4d74b2a4-4fb3-4323-8d49-860f8b36b552.png)

![image](https://user-images.githubusercontent.com/33961674/128992207-c5fed195-41e0-4d88-ba06-f78cff20578a.png)

## Describe the bug

this seems happening while showing documentation

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by GopherJ** [comment]
downgraded to `0.5.0+ubuntu2+git202108101753-c5baba065-d569569c9-9cb9a8f8c~ubuntu20.04.1` worked for me

**Comment by fannheyward** [comment]
Can't reproduce in

```
vim version: NVIM v0.6.0-dev+68f61b167
node version: v16.6.1
coc.nvim version: 0.0.80-f11537377a
```

**Comment by chemzqm** [comment]
Your coc.nvim is broken.

**Comment by GopherJ** [comment]
thanks @chemzqm @fannheyward I wasn't able to reproduce this anymore these days, so I assume it's ok now, I was busy so I didn't close it sorry
