### ISSUE TITLE
Popout documentation in popup window to split window

### ISSUE THREAD

**Issue by ihasdapie** [neoclide/coc.nvim#3289]
**Is your feature request related to a problem? Please describe.**
Sometimes working with coc floating documentation/signature help/etc it would be nice to be able to pop out the floating window into a buffer so that I can keep looking at it without having to constantly either get the floating window back/remember it's contents/deal with it moving around/etc.  

**Describe the solution you'd like**
The newly released `coq.nvim` does this pretty well: [coq.nvim](https://github.com/ms-jpq/coq_nvim) where one can just map a key to pop it out 
![image](https://raw.githubusercontent.com/ms-jpq/coq.artifacts/artifacts/preview/preview.gif)

Add option to popout help/documentation popup into a split

**Describe alternatives you've considered**
The only completion client I've seen this implemented for is `coq.nvim`, but that was released like a day ago. I don't think this feature is available with `nvim-compe` either.

**Comment by chemzqm** [comment]
Add code below to your vimrc
```vim
inoremap <silent> <C-x> <C-r>=ShowDoc()<CR>
function! ShowDoc() abort
  let winid = get(g:, 'coc_last_float_win', -1)
  if winid != -1
    let bufnr = winbufnr(winid)
    exe 'below sb '.bufnr
  endif
  return ''
endfunction
```
