### ISSUE TITLE
[Feature request] add code actions for outline tree

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#3292]
Add code actions for outline tree.

![](https://camo.githubusercontent.com/d73891b2b2b12fc54f167215dd63a99451d799357f519fec064131174dc869a9/68747470733a2f2f656d6163732d6c73702e6769746875622e696f2f6c73702d646172742f696d616765732f666c75747465722d6f75746c696e652e676966)

It's possible that we can register code action for outline tree and fetch the code actions for the relative document.

**Comment by fannheyward** [comment]
I don't know if I got your point, does this is your need? https://github.com/neoclide/coc.nvim/commit/e7f4fd4d941cb651105d9001253c9187664f4ff6#diff-4f45caa500ef03d94d3c2bfa556caa1642df95d4e2b980d76b876a8fd2e8c522

You can set `actions` to tree item and invoke with `tab` to show in menu.

BTW, what's the editor/IDE in your screenshots?

**Comment by iamcco** [comment]
> I don't know if I got your point, does this is your need? [e7f4fd4#diff-4f45caa500ef03d94d3c2bfa556caa1642df95d4e2b980d76b876a8fd2e8c522](https://github.com/neoclide/coc.nvim/commit/e7f4fd4d941cb651105d9001253c9187664f4ff6#diff-4f45caa500ef03d94d3c2bfa556caa1642df95d4e2b980d76b876a8fd2e8c522)
> 
> You can set `actions` to tree item and invoke with `tab` to show in menu.
> 
> BTW, what's the editor/IDE in your screenshots?

The editor is emacs.

What I means is fetch the code actions from lsp for the outline tree view relative document.

Abount code impelement https://github.com/neoclide/coc.nvim/issues/3292#issuecomment-899944479

**Comment by fannheyward** [comment]
Maybe coc can fetch code actions and set them to tree item's actions?

**Comment by iamcco** [comment]
> Maybe coc can fetch code actions and set them to tree item's actions?

Something similar, since outline tree view is built-in support. it would be nice also have code action support too.
