### ISSUE TITLE
How can I get the stuff to recognise cmake include directory?

### ISSUE THREAD

**Issue by Latrolage** [neoclide/coc.nvim#3293]
First off, I'm going to say that I'm a beginner in programming and vim. I'm not sure if coc is the the thing which should be detecting this stuff. But basically, my CMakeLists.txt file has 
```
#CMakeLists.txt
cmake_minimum_required (VERSION 3.6)
project(bbot)

add_executable(bbot main.cpp)

#Add these two lines
add_subdirectory(deps/sleepy-discord)
target_link_libraries(bbot sleepy-discord)
```
and my main.cpp file includes
```
#include "sleepy_discord/sleepy_discord.h"
```
When compiling with make in the build directory, it finds the header file just fine, I'm assuming that the CMakeLists.txt file had a line which let make know where to find the files, the sleepy_discord.h file is in `./deps/sleepy-discord/include/sleepy_discord/sleepy_discord.h` relative to the main.cpp file.

But coc (using ccls and clangd) both say that the file is not found and code completion with stuff from that file isn't working. Is there anyway for any vim autocompletion to detect the include directories? (I haven't tried anything else, mostly because i'm not sure what part of my Vim is responsible for detecting the include files and stuff)

**Comment by fannheyward** [comment]
You need to setup a `compile_commands.json` or `compile_flags.txt ` for clangd, https://clangd.llvm.org/installation#project-setup, https://github.com/MaskRay/ccls/wiki/Project-Setup.
