### ISSUE TITLE
CocCommand document.renameCurrentWord causes underline on preview to persist after execution

### ISSUE THREAD

**Issue by rmzg** [neoclide/coc.nvim#3296]
## versions                                        
                                                   
vim version: NVIM v0.6.0-dev+65-g46009499a         
node version: v14.17.4                             
coc.nvim version: 0.0.80-9c54590c6d                
coc.nvim directory: /home/buu/.vim/plugged/coc.nvim
term: tmux                                         
platform: linux                                    
## Describe the bug

Run :CocCommand document.renameCurrentWord with the cursor on a variable to rename. 
Current variable and all other matching variables are underlined.
Perform editing actions to modify variable, all other variables change.
Exit editing mode, all other matching variables continue to be underlined.

Bug: underlining should be removed after finished modifying variable.

**Comment by oblitum** [comment]
You sure you don't wish an actual LSP variable rename instead? (`:h <plug>(coc-rename)`)

**Comment by oblitum** [comment]
The highlights/underlines of renameCurrentWord vanish once you go to normal mode, at least on my machine.
