### ISSUE TITLE
How to remove ~

### ISSUE THREAD

**Issue by PendragonSaber** [neoclide/coc.nvim#330]
Is there any setting that will allow me to remove this ugly~? I have not found the documentation.
![1](https://user-images.githubusercontent.com/41671631/51069392-48c8b100-1669-11e9-8fdd-ab14f1754465.png)

**Comment by chemzqm** [comment]
See `:h coc-completion`  also https://github.com/neoclide/coc.nvim/wiki/Using-snippets#snippet-completion
