### ISSUE TITLE
how to soIue  when i use C-j  jump i got error

### ISSUE THREAD

**Issue by PendragonSaber** [neoclide/coc.nvim#331]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
![33](https://user-images.githubusercontent.com/41671631/51069838-d01a2280-1671-11e9-82c7-9ec254c6ba2a.png)

**Describe the bug**
When I used c-j to prepare to jump to the next one, I got the error. like this pic
![untitled](https://user-images.githubusercontent.com/41671631/51069861-4028a880-1672-11e9-9a46-e56d5e0d9b4a.gif)

this is my mininit.vim 
```
inoremap <silent><expr> <TAB>                                                                                                                                                                              
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ coc#refresh()
   inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
   function! s:check_back_space() abort
        let col = col('.') - 1
          return !col || getline('.')[col - 1]  =~# '\s'
       endfunction
    
  " Use <c-space> for trigger completion.
  inoremap <silent><expr> <c-space> coc#refresh()
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<CR>"
  let g:coc_snippet_next = '<C-j>'
  let g:coc_snippet_prev = '<C-k>'
  " Use `[c` and `]c` for navigate diagnostics
  nmap <silent> [c <Plug>(coc-diagnostic-prev)
  nmap <silent> ]c <Plug>(coc-diagnostic-next)
```
my coc extensions
![222](https://user-images.githubusercontent.com/41671631/51069897-0ad08a80-1673-11e9-8001-543192554793.png)
I got these
![55](https://user-images.githubusercontent.com/41671631/51069910-4408fa80-1673-11e9-9eaa-c256d8ef5336.png)

**Comment by chemzqm** [comment]
Consider try code on master, keymapping for snippet have reworked.

**Comment by PendragonSaber** [comment]
@chemzqm  I saw the latest  `commit 8a476ad` , I reinstalled the `coc`, unfortunately I got the same error. After inserting the mode selection completion I finished the first fragment and I still can't jump to the next fragment via` c-j`.

**Comment by chemzqm** [comment]
No idea of the reason, You keystroke maybe catched by other plugin, consider try it with coc.nvim only.

**Comment by PendragonSaber** [comment]
Unfortunately, I still can't use it correctly. I only installed coc and denite. I didn't set everything to be the default. However, it can't jump. Do you need neosnippet or snippet? I have also failed before I installed it.
![2](https://user-images.githubusercontent.com/41671631/51082327-d7a7fd00-173f-11e9-80ae-070e5f9cd022.gif)

**Comment by chemzqm** [comment]
>  neosnippet or snippet?

No need for them.  Your neovim could be broken.

**Comment by chemzqm** [comment]
I can't reproduce your problem.
Use `  Plug 'neoclide/coc.nvim', {'do': 'yarn install'}` and `:PlugUpdate` to build coc from latest master, **note** you should not use tag.

`bingo` not works should be problem of your configuration.
