### ISSUE TITLE
preferCompleteThanJumpPlaceholder is not working

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc.nvim#332]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

I’m using ipad to view the master branch code.

**Describe the bug**

I found that the PR for this issue #170  was not merged into master, hence the config is not working.

**To Reproduce**

Described in the related issue

**Screenshots**
If applicable, add screenshots to help explain your problem

**Comment by chemzqm** [comment]
It was broken, try code on master branch.
