### ISSUE TITLE
Unavailable after installation

### ISSUE THREAD

**Issue by leolin49** [neoclide/coc.nvim#3327]
I use vim8.0 and vundle, 

My installation method is as follows
![image](https://user-images.githubusercontent.com/58925286/131481454-884737a2-b638-4c77-8bd6-0a823b6742a4.png)

When I installed coc.nvim, it didn't work properly and reported an error

When I execute the command "CocInfo"
![image](https://user-images.githubusercontent.com/58925286/131481601-c5a730bc-0375-4b87-a515-de12e69e05b1.png)

When I open vim it also prompts a warning
[coc.nvim] build/index.js not found, please install dependencies and compile coc.nvim by: yarn install

**Comment by fannheyward** [comment]
> vundle

vundle is too old to support branch, use another plugin manager like https://github.com/junegunn/vim-plug, checkout https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#add-cocnvim-to-vims-runtimepath for more.

**Comment by leolin49** [comment]
thanks
