### ISSUE TITLE
more sensible default for error window highlight

### ISSUE THREAD

**Issue by alextes** [neoclide/coc.nvim#3329]
Recently updated and noticed that the floating window text color for errors changed from my default colorscheme / terminal red, changed to a really aggressive red (subjective). You can see my normal red in the screenshot below too.

![Screenshot 2021-08-31 at 15 22 33](https://user-images.githubusercontent.com/2011351/131510664-ee9f08ce-f86b-4de4-868f-26735e05442e.png)

It seems this highlight group is new, as it showing up after updating suggests, and is currently:
```FgCocErrorFloatBgCocFloating xxx ctermfg=196 ctermbg=235 guifg=#ff0000 guibg=#303030```

I imagine many others will not like this red, although that is ultimately subjective. If others are looking for how to solve this the following does the trick for me:

```
highlight FgCocErrorFloatBgCocFloating ctermfg=9 guifg=#ff0000
```

I only use term. GUI users will need a different line, but that's the highlight group you're looking for anyway.

Would it make sense to set the default for this group to the color scheme red instead?

Just a suggestion and trying to help others! Thanks for an awesome plugin 🙏 !

**Comment by fannheyward** [comment]
I don't think the `FgCocErrorFloatBgCocFloating` highlight group is not from coc.nvim.

**Comment by chemzqm** [comment]
It's expected, you need overwrite CocErrorFloat highlight group.

**Comment by chemzqm** [comment]
> Would it make sense to set the default for this group to the color scheme red instead?

Never heard of `the color scheme red`, different color schemes provide different highlight groups.
It is `Red` for `ctermfg` by default:
```
hi default CocErrorSign     ctermfg=Red     guifg=#ff0000 guibg=NONE
hi default link CocErrorFloat       CocErrorSign
```

**Comment by chemzqm** [comment]
The problem should be your have enabled `termguicolors` on your vim, so the default `guifg=#ff0000` is used.

**Comment by chemzqm** [comment]
Seems coc.nvim has bug with `coc#highlight#compose_hlgroup` the result doesn't seems right.

**Comment by chemzqm** [comment]
Fixed
