### ISSUE TITLE
Show diagnostic in insert mode only on CursorHold

### ISSUE THREAD

**Issue by vzytoi** [neoclide/coc.nvim#3334]
Hi, like the title says, I would like my diagnostic of my line to appear in insert mode when I am not moving my cursor. I tried this but it don't seem to work. Any idea?
```
vim.cmd("autocmd! CursorHoldI * norm :call CocAction('DiagnosticInfo')<cr>")
```
I'm not very good at autocmds so it's probably just a mistake on my part. Thank you and good day!

**Comment by chemzqm** [comment]
It's `diagnosticInfo`, you may also need `"diagnostic.refreshOnInsertMode": true` configuration.
`CursorHoldI` not reliable, my suggestion is avoid use it.
