### ISSUE TITLE
[question] How can auto completion auto insert space?

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#3339]
e.g. When I insert 'Feat'

![image](https://user-images.githubusercontent.com/32936898/131871614-ea9da384-a2bf-4fb2-b649-c426c8da0e1d.png)

Press `<C-N><C-N>` to select the second item:
![Screenshot from 2021-09-02 23-23-07](https://user-images.githubusercontent.com/32936898/131871981-fbd8176a-e5ab-4048-a099-28e9c6c42df0.png)

It only insert '!' not '! Refactor'

Only when I press `<C-Y>`, it will insert all text.

How can auto completion auto insert space? I have read the fine manual but found no similar options.

Thanks.

**Comment by fannheyward** [comment]
> Press <C-N><C-N> to select the second item:

How do you confirm the selection? I mapped `<cr>` to confirm selected, can't reproduce your issue.

**Comment by Freed-Wu** [comment]
Sorry:(

> Press `<C-N><C-N>` to select the second item.

> Only when I press `<C-Y>`, it will insert all text.

**Comment by chemzqm** [comment]
You need change `suggest.invalidInsertCharacters` configuration, it's intended to extract valid characters from `insertText` of CompleteItem.

**Comment by Freed-Wu** [comment]
Thanks!
