### ISSUE TITLE
Faster messages extension ?

### ISSUE THREAD

**Issue by LuisHenriqueFA14** [neoclide/coc.nvim#3341]
I really like the way that nvim-lsp shows error/warnings messages

Just like that:

![image](https://user-images.githubusercontent.com/72721283/131935541-f663c366-874d-49c2-816f-02bc95f35790.png)

How can i get the same result in coc ?

**Comment by fannheyward** [comment]
Check `:h coc-config-diagnostic`, you can display the messages in virtualText.
