### ISSUE TITLE
RFC: use nvim-treesitter's highlight groups as SemanticTokens highlight groups

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#3345]
> Yes, coc.nvim's semanticTokens highlighting is not stable by now, I just share my thoughts on the highlight groups.

With the release of nvim 0.5.0 that supports tree-sitter, lots of colorschemes have added `nvim-treesitter`'s highlight groups definitions, for example [sonokai](https://github.com/sainnhe/sonokai/blob/61b796d94e7b0110f1bdf321cc1d19a841697a42/colors/sonokai.vim#L331), these colorschemes can also work on Vim.

(You can get the highlight group names from `:h nvim-treesitter-highlights` if you've `nvim-treesitter` installed)

Now I've an idea: use the highlight group defined by nvim-treesitter for semanticTokens.

Pros:

1. we don't need colorschemes to define `CocSem_*` highlight groups, instead we reuse the `TS*` hi groups that many colorschemes would like to add.
2. if users are using nvim and `nvim-treesitter`'s highlighting, for example on C files, will get tree-sitter's highlighting at first when file opened, after coc+clangd does semanticTokens highlighting, the highlighting will be _improved_ base on tree-sitter's. There will not big flickering  changes, the experience will be better.   (demo images)
3. if users are using vim, the `TS*` highlight groups can also be used by coc semanticTokens highlighting.

Cons:

1. not all semantic tokens are defined by `nvim-treesitter`'s highlight groups, for example clangd provides `class` type, but there's no `TSClass`.
2. some colorschemes define `TS*` for nvim only, for example [dracula](https://github.com/dracula/vim/blob/d1ff992bf605c098577b7f0e632e3ea887b71520/after/plugin/dracula.vim#L70-L74) will check `g:loaded_nvim_treesitter`.

| | Before | After |
| ------------- |-------------  | ------- |
| C |  <img width="720" alt="截屏2021-09-02 下午6 19 25" src="https://user-images.githubusercontent.com/345274/131986836-7d7341aa-f2da-4f1d-b23f-a4779d0dc935.png"> |    <img width="720" alt="截屏2021-09-02 下午6 19 32" src="https://user-images.githubusercontent.com/345274/131986855-798487ac-1a92-47b7-840d-27f6958f8bfc.png">  |
| Rust |    <img width="720" alt="截屏2021-09-02 下午6 18 06" src="https://user-images.githubusercontent.com/345274/131986977-797264d5-404a-4f98-a66b-267e7a99c4fb.png">          | <img width="720" alt="截屏2021-09-02 下午6 17 46" src="https://user-images.githubusercontent.com/345274/131986957-9fbb830c-d945-4926-9131-6aaa1e973546.png">       |
| Go | <img width="1440" alt="截屏2021-09-03 下午5 56 12" src="https://user-images.githubusercontent.com/345274/131987292-c98dc07b-2e2a-4d4f-86ed-5614b419a05b.png"> | <img width="1440" alt="截屏2021-09-03 下午5 56 03" src="https://user-images.githubusercontent.com/345274/131987264-083b1f62-6d3d-4934-a680-c8bc080e1b3d.png"> |

**Comment by oblitum** [comment]
This would be really nice! :)

Related:
- https://github.com/neoclide/coc.nvim/issues/3048#issuecomment-842417449
- https://github.com/neoclide/coc.nvim/pull/3310#issuecomment-906486026

**Comment by fannheyward** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f

`TS*` highlight groups have been removed.
