### ISSUE TITLE
Autocomplete appear and disappear after each keystroke

### ISSUE THREAD

**Issue by raveltan** [neoclide/coc.nvim#3354]
## Result from CocInfo

versions

vim version: NVIM v0.5.0
node version: v14.17.4
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /home/vel/.config/nvim/plugged/coc.nvim
term: xterm-kitty
platform: linux

Log of coc.nvim

2021-09-06T12:50:24.169 INFO (pid:37015) [services] - registered service "languageserver.ccls"
2021-09-06T12:50:24.171 INFO (pid:37015) [services] - registered service "languageserver.elixirLS"
2021-09-06T12:50:24.524 INFO (pid:37015) [plugin] - coc.nvim 0.0.80-3086844413 initialized with node: v14.17.4 after 489ms
2021-09-06T12:50:26.883 INFO (pid:37015) [attach] - receive notification: showInfo []

## Describe the bug

Autocomplete appear and disappear after each keystroke.
for example if we type Text, 
T will trigger the autocoplete dialog
e will make it disappear
x will make it reappear
and so on
it can be seen here
[Ascii Cinema](https://asciinema.org/a/434247)

## Reproduce the bug
> I'm not sure about which part of  the config is causing the problem, so i uploaded the complete init.vim

""" init.vim
" Plugins
call plug#begin()
  Plug 'airblade/vim-gitgutter'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  Plug 'lifepillar/vim-gruvbox8'
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'glepnir/dashboard-nvim'
  Plug 'voldikss/vim-floaterm'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'leafgarland/typescript-vim'
  Plug 'peitalin/vim-jsx-typescript'
  Plug 'dart-lang/dart-vim-plugin'
  Plug 'honza/vim-snippets'
  Plug 'majutsushi/tagbar'
  Plug 'scrooloose/nerdcommenter'
  Plug 'andrewradev/splitjoin.vim'
  Plug 'vim-scripts/matchit.zip'
  Plug 'easymotion/vim-easymotion'
  Plug 'elixir-editors/vim-elixir'
  Plug 'ryanoasis/vim-devicons'
call plug#end()

" Configs
let mapleader = " "
filetype plugin on
set completeopt=menuone
set mouse=a
set nobackup
set nocompatible
set noswapfile
set nowritebackup
set number
set signcolumn=yes
set title
set wrap
setlocal wrap

" Set tab
:set shiftwidth=2
:set autoindent
:set smartindent

" Persist undos
set undofile
set undodir=~/.vim/undodir

" Persist cursor
autocmd BufReadPost *
  \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
  \ |   exe "normal! g`\""
  \ | endif
    
" Theme
syntax on
set termguicolors
colorscheme gruvbox8
set background=dark
set cursorline
set hidden
set laststatus=2

let g:gruvbox_transp_bg = 1
let g:gruvbox_italicize_strings = 0

set list

" Buffers
nmap <Leader>bn :bn<CR>
nmap <Leader>bp :bp<CR>
nmap <Leader>bl :Buffers<CR>
nmap <Leader>g :GFiles<CR>
nmap <Leader>e :Files<CR>
nmap <Leader>p :Rg<CR>

" Coc START
" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=100

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
if exists('*complete_info')
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
else
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocActionAsync('doHover')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <plug>(coc-format-selected)

" Codeaction for seleted text object
xmap <leader>u  <Plug>(coc-codeaction-selected)
nmap <leader>u  <Plug>(coc-codeaction-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Remap keys for applying codeAction to the current buffer.
nmap <leader>do  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocList diagnostics<cr>
" Show commands.
nnoremap <silent><nowait> <space>l  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>

" Dashboard settings
let g:dashboard_default_executive ='fzf'

" Floaterm
let g:floaterm_keymap_new    = '<Leader>tt'
let g:floaterm_keymap_prev   = '<Leader>tN'
let g:floaterm_keymap_next   = '<Leader>tn'
let g:floaterm_keymap_toggle = '<Leader>n'

" use alt+hjkl to move between split/vsplit panels
tnoremap <A-h> <C-\><C-n><C-w>h
tnoremap <A-j> <C-\><C-n><C-w>j
tnoremap <A-k> <C-\><C-n><C-w>k
tnoremap <A-l> <C-\><C-n><C-w>l
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l

" FZF
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-s': 'split',
  \ 'ctrl-v': 'vsplit'
  \}
let $FZF_DEFAULT_COMMAND = 'ag -g ""'

" Go auto import and tags helper
autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')

" Smartf config
nmap f <Plug>(coc-smartf-forward)
nmap F <Plug>(coc-smartf-backward)
nmap ; <Plug>(coc-smartf-repeat)
nmap , <Plug>(coc-smartf-repeat-opposite)

augroup Smartf
  autocmd User SmartfEnter :hi Conceal ctermfg=220 guifg=#d3869b
  autocmd User SmartfLeave :hi Conceal ctermfg=239 guifg=#504945
augroup end

" coc exploerer
nnoremap <Leader>ve :CocCommand explorer<CR>

" coc-snippets
" Use <C-l> for trigger snippet expand.
imap <C-l> <Plug>(coc-snippets-expand)

" Use <C-j> for select text for visual placeholder of snippet.
vmap <C-j> <Plug>(coc-snippets-select)

" Use <C-j> for jump to next placeholder, it's default of coc.nvim
let g:coc_snippet_next = '<c-j>'

" Use <C-k> for jump to previous placeholder, it's default of coc.nvim
let g:coc_snippet_prev = '<c-k>'

" Use <C-j> for both expand and jump (make expand higher priority.)
imap <C-j> <Plug>(coc-snippets-expand-jump)

" Tagbar
nmap <Leader>vt :TagbarToggle<CR>

" NERD Commenter
filetype plugin on
let g:UltiSnipsExpandTrigger="<leader>xp"
"""
- Start nvim with the config above
- trigger and autocomplete
- start typing and for every letter you type, it will either make the autocomplete dialog appear or disappear.

## Screenshots (optional)
[Ascii Cinema](https://asciinema.org/a/434247)

**Comment by fannheyward** [comment]
Can't reproduce, try minimal vimrc please.

**Comment by chemzqm** [comment]
Should be caused by some of your other vim plugin.

**Comment by raveltan** [comment]
hello @fannheyward , i'm not sure how to do that, can you explain a bit more?

**Comment by chemzqm** [comment]
Create vimrc file mini.nvim and open it by `nvim -u mini.vim`
