### ISSUE TITLE
gopls not working

### ISSUE THREAD

**Issue by arrowfeng** [neoclide/coc.nvim#3356]
## Result from CocInfo

![image](https://user-images.githubusercontent.com/20623365/132276846-97297c8a-c7ae-479d-be1f-611c4c5380a6.png)

## Describe the bug

i config gopls, but not working

## Reproduce the bug

- Create file `mini.vim` with：
```vim
set nocompatible

set nu

set hidden
set cursorline
set showmatch
set tabstop=4
set shiftwidth=4
set autoindent
set incsearch
set ignorecase
set paste

set encoding=utf-8
syntax enable
syntax on
au InsertLeave *.go,*.sh write
filetype plugin indent on

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
call plug#end() 
```

```json
{
    "languageserver": {
        "golang": {
            "command": "gopls",
            "rootPatterns": ["go.mod"],
            "filetypes": ["go"]
        }
    }
}
```

**Comment by fannheyward** [comment]
What do you mean `not working`? From the logs, gopls is running and working.

**Comment by arrowfeng** [comment]
I don’t know if I have overlooked any configuration. I use "fmt.Println" in a go project, and there is no any completion prompt.

**Comment by arrowfeng** [comment]
I find that set paste in .vimrc, completion not working.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
