### ISSUE TITLE
Enable language servers of main filetype with multiple filetypes filetype

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#3358]
**Is your feature request related to a problem? Please describe.**

`:h ft` states:

```
	|FileType| |filetypes|
	When a dot appears in the value then this separates two filetype
	names.  Example:
		/* vim: set filetype=c.doxygen : */ ~
	This will use the "c" filetype first, then the "doxygen" filetype.
	This works both for filetype plugins and for syntax files.  More than
	one dot may appear.
```

Multiple filetypes is a really cool native feature, and some things on coc.nvim side already work with that, like coc-snippets for example, which will provide snippets for all the particular filetypes listed.

The issue though, is that core coc.nvim LSP functionality will mostly stop, which means that LSP servers won't provide services for neither of the languages listed.

**Describe the solution you'd like**

I think that coc.nvim should provide LSP services for the first filetype in the multiple filetype list, this is how [n]vim decides how a file with multiple filetype is highlighted. If I `:set ft=markdown.tex`, the file isn't highlighted as LaTeX, it's highlighted as Markdown, if I name it `:set ft=tex.markdown` then the reverse happens. I think coc.nvim should follow that approach to provide LSP for the "main" filetype. In LSP point of view, `markdown.tex` == `markdown`.

**Describe alternatives you've considered**

I had thought before about this thinking about enabling two main language servers, but this is not technically possible, since there would be conflicts. But I think the above approach is okay.

**Additional context**

**Comment by yaegassy** [comment]
@chemzqm Let me ask you a question. 

I've created an extension called `coc-ansible`. https://github.com/yaegassy/coc-ansible

In this extension, it is intentionally activated only for `yaml.ansible` filetype.

Will this change cause the `yaml.ansible` filetype to act as a `yaml` filetype?

**Comment by chemzqm** [comment]
Yes, it won't be activated and you will have `yaml` as langaugeId in your language server.

**Comment by yaegassy** [comment]
@chemzqm  I see. Thank you for your answer. 🙇 

If the filetype is recognized as yaml, `coc-ansible` will not work... :(

I'll try to think of a way to handle this on the extension side...

**Comment by yaegassy** [comment]
The major Vim syntax plugin for ansible is `ansible-vim`, which sets the filetype to `yaml.ansible`. <https://github.com/pearofducks/ansible-vim>

Maybe we need to develop our own syntax plugin to solve this problem...

**Comment by yaegassy** [comment]
As a workaround, use `g:coc_filetype_map` to set a dedicated languageId.

```vim
let g:coc_filetype_map = {
  \ 'yaml.ansible': 'ansible',
  \ }
```

**Comment by oblitum** [comment]
@yaegassy IMO a mapping patch like that seems acceptable, it seems what's practiced regarding ansible is the reverse of what usually happens with multiple filetypes in vim, which expects first filetype as main one, not the latter, which is what you want.

**Comment by yaegassy** [comment]
Some of the other expansions may possibly be affected by this.

For example, coc-docker also needs to be adjusted. https://github.com/josa42/coc-docker/blob/master/package.json#L33

**Comment by chemzqm** [comment]
> Some of the other expansions may possibly be affected by this.
> 
> For example, `coc-docker` also needs to be adjusted. https://github.com/josa42/coc-docker/blob/master/package.json#L33

Should be fixed by 93ad3753

**Comment by oblitum** [comment]
> Should be fixed by 93ad3753

For ref, should be this one I think e95300ea1165f1a9b61ebfd8ff0152ad7d5824e4.

**Comment by yaegassy** [comment]
I updated coc.nvim and checked it. However, the "languageId" of `yaml.ansible` was still determined to be `yaml`.

**Comment by chemzqm** [comment]
> I updated coc.nvim and checked it. However, the "languageId" of `yaml.ansible` was still determined to be `yaml`.

Use 
```
let g:coc_filetype_map = {
  \ 'yaml.ansible': 'ansible',
  \ }
```

**Comment by Freed-Wu** [comment]
Comes from #4698.

> I think that coc.nvim should provide LSP services for the first filetype in the multiple filetype list, this is how [n]vim decides how a file with multiple filetype is highlighted. If I :set ft=markdown.tex, the file isn't highlighted as LaTeX, it's highlighted as Markdown,

I disagree, `:set ft=markdown.tex` will `:runtime! syntax/markdown.vim` then `:runtime! syntax/tex.vim`:

```vim
:scriptnames
...
/home/wzy/.local/share/nvim/repos/github.com/dracula/vim/after/syntax/markdown.vim|1| 431
/home/wzy/.local/share/nvim/.cache/ftplugin.vim/.dein/after/syntax/markdown.vim|1| 432
/home/wzy/.local/share/nvim/repos/github.com/lervag/vimtex/syntax/tex.vim|1| 433
/nix/store/ypc27qm8i9vp96yh1wk5aq3giibyi1f4-neovim-unwrapped-0.9.1/share/nvim/runtime/syntax/tex.vim|1| 434
/home/wzy/.local/share/nvim/repos/github.com/sheerun/vim-polyglot/after/syntax/tex.vim|1| 435
/home/wzy/.local/share/nvim/repos/github.com/dracula/vim/after/syntax/tex.vim|1| 436
...
```

The reason you only see markdown syntax highlight is in `syntax/XXX.vim`, it is usually:

```vim
if exists('b:current_syntax')
  finish
endif
let b:current_syntax = 'XXX'
```

So `syntax/markdown.vim` has set `b:current_syntax`, and `syntax/tex.vim` will `:finish`.

In some filetypes, like `doxygen` or some template language like `jinja`, they don't detect  `exists('b:current_syntax')` and just execute their `syntax/XXX.vim`, so you can see two syntax highlight. So why coc.nvim doesn't be like vim's syntax, enable both language servers for markdown and tex for `:set ft=markdown.tex`?

> I had thought before about this thinking about enabling two main language servers, but this is not technically possible, since there would be conflicts.

It depends on language servers. Sometimes `:set ft=a.b`, b is a subtype of a, which b just has some specific rule or some new built-in functions. So enable both language servers for a and b without conflict should be possible.
