### ISSUE TITLE
为什么我会有两个 gopls 在运行？

### ISSUE THREAD

**Issue by arrowfeng** [neoclide/coc.nvim#3361]
## Result from CocInfo

![image](https://user-images.githubusercontent.com/20623365/132538922-6920e44f-8098-4db7-b770-b7235f379714.png)

## Describe the bug
你好，我有个问题想请教一下，每次打开 go 项目，会启动两个 gopls，这个现象正常吗？
![image](https://user-images.githubusercontent.com/20623365/132539064-c62f213e-492f-4827-8491-687dac7cfbe9.png)

## Reproduce the bug
![image](https://user-images.githubusercontent.com/20623365/132539437-bb26d68f-ea1c-4105-a8b7-51dbc2443fca.png)

```coc-settings.json
{
	"languageserver": {
		"golang": {
			"command": "gopls",
			"rootPatterns": ["go.mod"],
			"filetypes": ["go"]
		}
	}
}
```

**Comment by fannheyward** [comment]
`ps aux | grep gopls` 就能看到， `gopls serve`, `gopls -remote`，这是正常的。

**Comment by arrowfeng** [comment]
非常感谢～
