### ISSUE TITLE
Have fixed height of preview window in CocList

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc.nvim#3365]
**Is your feature request related to a problem? Please describe.**

When I try to preview items with `CocList -A --normal yank`, the preview window height changing that make the thing harder to follow for me.

**Describe the solution you'd like**

I would like to set a fixed height for the preview window in CocList

**Comment by chemzqm** [comment]
You can hack the code at https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/list.vim#L303 if you really need it.
