### ISSUE TITLE
coc no longer expand the snippet by NeoSnippet

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc.nvim#337]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
```
## versions

vim version: NVIM v0.3.4
node version: v11.6.0
coc.nvim version: 0.0.46 // I use master branch
term: screen-256color
platform: darwin
```
**Describe the bug**
coc only complete the item and does not expand the snippet of NeoSnippet (suffix with [NS]

**To Reproduce**

1. in a typescript file, type `cl`, 
2. the complete list show the `cl~ [NS]` item,
3. press `<C-y>` to accept the item and expand the snippet. 

**Screenshots**

**Comment by sandangel** [comment]
I use the arrow key to navigate through the completion item, `<Tab>` to either trigger completion and jump placeholder. I also set preferCompleteThanJumpPlaceHolder = true

```
" Emmet
" Remap for expand with Tab
let g:user_emmet_leader_key = '<A-e>'
let g:user_emmet_expandabbr_key = '<A-x><A-e>'

" UltiSnips
" Not conflict with Coc
let g:UltiSnipsExpandTrigger = "<f6>"

" Coc
let g:coc_snippet_next = '<Tab>'
let g:coc_snippet_prev = '<S-Tab>'

" Use <Tab> for confirm completion.
" Coc only does snippet and additional edit on confirm.
imap <silent><expr> <Tab> <SID>expand_completion()

function! s:expand_completion()
  if pumvisible()
    return "\<C-y>"
  endif
  let col = col('.') - 1
  if !col || getline('.')[col - 1]  =~# '\s'
    return "\<Tab>"
  endif
  return coc#refresh()
endfunc
```

**Comment by chemzqm** [comment]
Try update coc-neosnippet extension.

**Comment by chemzqm** [comment]
Should be fixed now, run CocUpdate.

**Comment by sandangel** [comment]
hi @chemzqm , I updated the extension, expand snippet works now but only when there is no text on the current line.

![jan-16-2019 01-41-32](https://user-images.githubusercontent.com/22189661/51195888-54e69400-1931-11e9-8cec-0fd2e59b744d.gif)

**Comment by sandangel** [comment]
hi @chemzqm should We reopen this issue now?
