### ISSUE TITLE
Stricter/faster/safer/better workspace folders resolve

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#3375]
**Is your feature request related to a problem? Please describe.**

39c14a3 has improved a little bit on this area but we're still prone to lots of inconsistency. It's still present and it's pretty easy to prove. For example, [coc-sh](https://github.com/josa42/coc-sh) is a trivial extension to the bash-language-server, and it faced the home scan issue before at https://github.com/josa42/coc-sh/issues/53. After 39c14a3, that was fixed, because now home folder check is hard-coded if coc.nvim resolves to pick `cwd` (current working directory) as workspace folder, it will not because home folder will be ignored by default, and then coc.nvim will send `null` to bash-language-server. bash-language-server will keep working just fine despite that, it will work without a workspace folder at the given bash file opened in specific.

That's what happens if I'm at `~` and open a system bash file (e.g. `nvim /usr/bin/e2scrub`). I noticed though that the issue is back if I'm not at `~`, if I `cd ..`, or `cd /`, then this will cause coc.nvim to send the`cwd` to the `bash-language-server`, which will scan a huge amount of files and increase processor usage a lot, giving the impression that coc.nvim is slow or resource intensive, while imo, this is simply an implementation bug. That happens even given there's no root pattern files at `/` or `/home` (for obvious reasons).

I think this behavior is not wanted nor correct.

**Describe the solution you'd like**

To solve this in any situation what I have concluded is that the LSP spec should be followed wisely and strictly at this point:

```
	/**
	 * The workspace folders configured in the client when the server starts.
	 * This property is only available if the client supports workspace folders.
	 * It can be `null` if the client supports workspace folders but none are
	 * configured.
	 *
	 * @since 3.6.0
	 */
	workspaceFolders?: WorkspaceFolder[] | null;
```

The important points above that should be payed attention to are:

- workspace folders are _configured in the client_. Configuration can be:
  - Indirect:
       - the user has its files in a git repository, so the git repo becomes the workspace folder due to `rootPatterns` defaults
       - the user has a root pattern, like `compile_commands.json` in a parent directory of that file, so that becomes the workspace folder due to server specific `rootPatterns`
           - <sub>`clangd` recently started accepting `compile_commands.json` inside cmake's `build` directory (`build/compile_commands.json`). That indicates that coc.nvim root patterns could be more flexible than current state, to accept a file with a subdir as a root pattern, like `build/compile_commands.json`, or even a wildcard like `*/compile_commands.json`</sub>
  - _None_:
      - Either no root could be resolved, or if resolved, it's an `ignoredRootPaths`, so it should not be picked and
      - `requireRootPattern` is `false` or not set, then:
          - coc.nvim _should send `null`_ as workspace folder to the server, as all candidates were either not found or should be ignored, and the presence of a workspace folder has not been required
  - Direct:
       - Either no root could be resolved, or if resolved, it's an `ignoredRootPaths`, so it should not be picked and
       - `requireRootPattern` is `true`, then:
           - coc.nvim may prompt the user for a directory as workspace folder as the server in specific can't work without one. If the user clicks enter without setting one, then the server is not started
               - <sub> Another option is to simply provide a warning that a server won't be started because of the above conditions. It may be a bit smart at explanation, in case a root was found but is present in `ignoredRootPaths`, it may point that the dir is in `ignoredRootPaths` and that's why it's not used even though resolved as root </sub>

All root resolve should be decided around the values of `rootPatterns`, `ignoredRootPaths` and `requireRootPattern`, so that not just it all works better and more correct, but it becomes easily documented. coc.nvim shouldn't add home dir check hard-coded, home dir should be one of the defaults in `ignoredRootPaths`, another strong candidate is `/`, and these default values should be present in docs, and if the user wants to, it should be able to remove those and set their own `ignoredRootPaths` from scratch (a user on a container may have a small home dir and may wish to have it as root). coc.nvim should never send hard-coded `cwd` on its own because it was unable to resolve a root. The spec allows for servers to work without any workspace configured, so coc.nvim should not attempt to enforce one, unless it's requested by user configuration or 3rd party extension through `requireRootPattern`, if that's not the case, it should simply send `null`. Coc may have an option for a warn anytime a `null` as workspace happens, most certainly this should be part of `:CocInfo` logs by default at least. In the case the user/extension ever wishes `cwd` to be resolved as `rootPatterns`, it should add some special variable, like `"${cwd}"`, in the `rootPatterns` list. coc.nvim would need to add support for such variables, and maybe others, like `"${fileDirname}"` for file's parent directory, `"${tmp}"` for an empty unique temporary directory, etc. Those variable roots would either be used last, after normal root patterns fail or coc.nvim may have a `rootPatternsFallback`where the user/extension would use those variables instead of putting them at normal `rootPatterns`. `rootPatternsFallback` would then be used only after normal `rootPatterns` are not found. Notice though that leveraging such variables _can_ lead back to the scanning issues, etc., as reported here, but it wouldn't invariably be at coc.nvim's core fault anymore.

Improving this needs to pervade other related features that suffer from current situation, one such case is what happens with watchman support. coc.nvim can often put home folder or other large folders as watchman's watch-list. I've noticed that coc.nvim ~~for unknown reason~~(see [bellow](https://github.com/neoclide/coc.nvim/issues/3375#issuecomment-967752557)) puts home on watchman's watch-list even though coc.nvim doesn't set home as workspace folder at all. Having home dir as watchman watch-list is another relevant performance issue as it causes watchman to spike CPU and request a lot of memory, which may give the impression that coc.nvim requires too much RAM, while that is simply a bug. I think coc.nvim should put only workspace folders on watchman's watch-list, and these workspace folders should follow the restrictions described above on root resolve, this would then hardly cause home folder to ever be put on watchman's watch-list.

**Describe alternatives you've considered**

**Additional context**

**Comment by oblitum** [comment]
related: https://github.com/neovim/neovim/pull/15430#issuecomment-906179810 → 💬 → https://github.com/neovim/nvim-lspconfig/pull/1385#issuecomment-962890255

**Comment by oblitum** [comment]
The `watchman` issue is actually a `watchman`'s own problem:

- https://facebook.github.io/watchman/docs/cmd/watch-project.html#using-watch-project
- https://github.com/facebook/watchman/issues/705#issuecomment-967751482

**Comment by fannheyward** [comment]
@oblitum, for the watchman issue, what do you mean `it doesn't work when opening from subfolder`?

I don't have `.git` in my HOME, in my tests, open file in HOME or `$HOME/src` will not add into watchman. `watchman watch-list` didn't have any HOME dir

**Comment by oblitum** [comment]
Hi @fannheyward, assuming `coc-clangd` is installed:

```
$cd ~
$mkdir .git
$mkdir -p a/b/c
$touch a/a.cpp
$touch a/b/b.cpp
$touch a/b/compile_flags.txt
$touch a/b/c/c.cpp
```

### Test 1

`cwd == ~/a` + `nvim a.cpp`:

- `$watchman watch-del-all && watchman shutdown-server`
- `$cd ~/a`
- `$nvim a.cpp`
- `:CocCommand workspace.workspaceFolders` → `~/a` **(incorrect, it should be
  `null`, there's no root pattern up, except for `~/.git`, which should be
  ignored, because it's in `~`)**
- `:CocInfo` → No "[watchman]" log at first, because it's spinning scanning `~`.
  After CPU cools down a report comes: "[watchman] - watchman watching project:
  `~/a`" **(false information)**
- `$ watchman watch-list` → `~` **(incorrect, it should be empty, given it was
  supposed to not have any workspace folder set, but even with that not
  working, it would make more sense for it to be `~/a` as reported, which
  it isn't, it's `~`)**

### Test 2

`cwd == ~` + `nvim a/a.cpp`:

- `$watchman watch-del-all && watchman shutdown-server`
- `$cd ~`
- `$nvim a/a.cpp`
- `:CocCommand workspace.workspaceFolders` → empty **(correct, it should be
  `null` as it's at `~`, despite having a root pattern present)**
- `:CocInfo` → no `watchman` log **(correct information, not watching when
  there's no workspace set is expected)**
- `$ watchman watch-list` → empty **(correct)**

### Test 3

`cwd == ~/a/b` + `nvim b.cpp`:

- `$watchman watch-del-all && watchman shutdown-server`
- `$cd ~/a/b`
- `$nvim b.cpp`
- `:CocCommand workspace.workspaceFolders` → `~/a/b` **(correct)**
- `:CocInfo` → No "[watchman]" log at first, because it's spinning scanning `~`.
  After CPU cools down a report comes: "[watchman] - watchman watching project:
  `~/a/b`" **(false information)**
- `$ watchman watch-list` → `~` **(incorrect, it should be `~/a/b`)**

### Test 4

`cwd == ~/a` + `nvim b/b.cpp`:

- `$watchman watch-del-all && watchman shutdown-server`
- `$cd ~/a`
- `$nvim b/b.cpp`
- `:CocCommand workspace.workspaceFolders` → `~/a`
  **(incorrect, it should be `~/a/b` due to `~/a/b/compile_flags.txt`)**
- `:CocInfo` → No "[watchman]" log at first, because it's spinning scanning `~`.
  After CPU cools down a report comes: "[watchman] - watchman watching project:
  `~/a`" **(false information)**
- `$ watchman watch-list` → `~` **(incorrect, it should be `~/a/b`)**

### Test 5

`cwd == ~/a/b/c` + `nvim c.cpp`:

- `$watchman watch-del-all && watchman shutdown-server`
- `$cd ~/a/b/c`
- `$nvim c.cpp`
- `:CocCommand workspace.workspaceFolders` → `~/a/b/c`
  **(incorrect, it should be `~/a/b` due to `~/a/b/compile_flags.txt`)**
- `:CocInfo` → No "[watchman]" log at first, because it's spinning scanning `~`.
  After CPU cools down a report comes: "[watchman] - watchman watching project:
  `~/a/b/c`" **(false information)**
- `$ watchman watch-list` → `~` **(incorrect, it should be `~/a/b`)**

It can be noticed having a root pattern `compile_flags.txt` was not helpful
even for defining a workspace folder in `4` and `5`. Which is an issue on its
own. Let's put a `.git` there to see whether this pattern is respected, and how
it behaves.

- `$mkdir ~/a/b/.git`

### Test 6

`cwd == ~/a` + `nvim b/b.cpp`:

- `$watchman watch-del-all && watchman shutdown-server`
- `$cd ~/a`
- `$nvim b/b.cpp`
- `:CocCommand workspace.workspaceFolders` → `~/a/b` **(correct due to `~/a/b/.git`)**
- `:CocInfo` → "[watchman] - watchman watching project: `~/a/b`" **(correct information)**
- `$ watchman watch-list` → `~/a/b` **(correct)**

There are two main problems I see:

- `coc.nvim` workspace root resolution is, for some yet unknown reason,
  respecting `.git` root marker but not `compile_flags.txt` root marker.
- `watchman` is operating its own root resolution for deciding what to watch.
  __This should not happen__. By being driven by `coc.nvim`, which already does
  root resolution, `watchman` should just watch a directory directly and only,
  it should **simply** obey, without any heuristic of its own for additional
  root resolution. If `coc.nvim` can control that from its side, then it
  should, otherwise the only way out is for the user to restrict `watchman`
  manually by configuration.

`coc.nvim` attempts to treat `~` (and some other specific directories)
specially, to effectively make them some kind of internally hard-coded
"`ignoredRootPaths`". That works in some tests, but not in others.

This being "internal `ignoredRootPaths`", tests also need to be applied to
verify what's the behavior when a user-configured "`ignoredRootPaths`" is
present, so to test this again but instead of `~`, to pick some random
directory instead, and put it on "`ignoredRootPaths`".

I'd like to correct what I stated before about the other checked directories in
`isValidWatchRoot`. They're not checked with a simple equality check as `~` is,
there's further checks, so it should be more reliable for those.

**Comment by chemzqm** [comment]
> ### Test 1
> 
> `cwd == ~/a` + `nvim a.cpp`:
> 
> - `$watchman watch-del-all && watchman shutdown-server`
> - `$cd ~/a`
> - `$nvim a.cpp`
> - `:CocCommand workspace.workspaceFolders` → `~/a` **(incorrect, it should be `null`, there's no root pattern up, except for `~/.git`, which should be ignored, because it's in `~`)**

It's because `cwd` is used as fallback when coc.nvim can't find any match pattern, we will have `workspace.ignoredFolders` configuration to help.

> ### Test 4
> 
> `cwd == ~/a` + `nvim b/b.cpp`:
> 
> - `$watchman watch-del-all && watchman shutdown-server`
> - `$cd ~/a`
> - `$nvim b/b.cpp`
> - `:CocCommand workspace.workspaceFolders` → `~/a` **(incorrect, it should be `~/a/b` due to `~/a/b/compile_flags.txt`)**

Need fix this.

> - `coc.nvim` workspace root resolution is, for some yet unknown reason, respecting `.git` root marker but not `compile_flags.txt` root marker.

Nothing special with `.git`, seems you have other pattern match in your cwd which is matched first

**Comment by chemzqm** [comment]
> watchman is operating its own root resolution for deciding what to watch. This should not happen. By being driven by coc.nvim, which already does root resolution, watchman should just watch the directory being asked directly, it should simply obey without any heuristic of its own for additional root resolution

Watchman is a background server which can be used by other app as well so it should not fully controlled by coc.nvim, it simply use `watch-project` command.

**Comment by oblitum** [comment]
On `watchman` topic, I didn't mean it should be fully controlled by coc.nvim to the point of affecting other clients. Just that a conflicting root resolution shouldn't be present, so when coc.nvim uses it, `watchman watch` seems better than `watchman watch-project`, and that only affects the coc.nvim usage of it.

**Comment by oblitum** [comment]
> It's because `cwd` is used as fallback when coc.nvim can't find any match pattern, we will have `workspace.ignoredFolders` configuration to help.

1. that's what happens, and it's what I describe in the beginning on the feature-request, but this fallback is problematic, as explained, and as linked to other project that had to deal with the same issue.
2. even though `:CocCommand workspace.workspaceFolders` reports `~/a`, which a say is incorrect, regardless of that, that's not `watchman` is watching, which can be very tricky to deal and unexpected.

**Comment by chemzqm** [comment]
Use `workspace.workspaceFolderFallbackCwd` to avoid using cwd as fallback workspace folder.

**Comment by oblitum** [comment]
I'll try out the related updates tomorrow (late here). Thanks.

**Comment by oblitum** [comment]
At first I'm trying again my initial report with `coc-sh`, and it seems I still spins CPU for a while if I start it from `/home` instead of `/home/francisco` (which is my `~`). I tried to set `workspaceFolderFallbackCwd` to `false` (by doing so I'm actually expecting `null` to be sent when no root is detected), it didn't work to reduce initial CPU usage, then I've set `workspace.ignoredFolders` to `["$HOME", "/home"]`, but it also had no effect. So, at the moment I have to figure out whether it's coc-sh to blame or not.

**Comment by oblitum** [comment]
Besides that I was still able to hit `watchman` watching my `~`. At the moment I just hit it by opening a trivial rust sample code not under git at `~/Projects/samples/rust` (a simple `cargo init` project). My `~` is under git, `~/Projects/samples/rust` is not. I `cd` into this `~/Projects/samples/rust` directory and `nvim src/main.rs`, it makes my CPU 100% for a couple of seconds, `:CocCommand workspace.workspaceFolders` reports `/home/francisco/Projects/samples/rust`, but `watchman watch-list` reports `~`.

**Comment by chemzqm** [comment]
The watched folder of `watchman` doesn't have to be `root` of `watch-project`, you can check the worksapce folders by `:echo g:WorkspaceFolders` to see if it's expected.
