### ISSUE TITLE
Suggest window disapear after type new character or delete character in nvim 0.5.0

### ISSUE THREAD

**Issue by huibosa** [neoclide/coc.nvim#3376]
## Result from Cocinfo
```
## versions

vim version: NVIM v0.5.0
node version: v16.6.1
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /home/huibosa/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-09-13T14:09:34.980 INFO (pid:44) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v16.6.1 after 121ms
2021-09-13T14:09:34.989 INFO (pid:44) [services] - registered service "clangd"
2021-09-13T14:09:34.990 INFO (pid:44) [services] - clangd state change: stopped => starting
2021-09-13T14:09:34.994 INFO (pid:44) [language-client-index] - Language server "clangd" started with 57
2021-09-13T14:09:35.109 INFO (pid:44) [services] - clangd state change: starting => running
2021-09-13T14:09:35.140 INFO (pid:44) [services] - service clangd started
2021-09-13T14:09:35.422 INFO (pid:44) [attach] - receive notification: highlight []
2021-09-13T14:09:39.703 INFO (pid:44) [attach] - receive notification: showInfo []
```

## Describe the bug

I've test the problem in nvim 0.5.0 and nvim 0.4.4 with mininum vimrc, only the former has the bug:

When typing `fori` in `.cpp` file, there might be two cases:

* Enter `for` and pause, the suggest window show up, then enter `i`, the suggest window disapear.
* Enter `fori` rapidly, there will be a suggest window.

It seems that anytime you enter a key when there is a suggest window, the wiindow will disapear, whether you enter a character or a \<BS\>.

## Screenshots

https://user-images.githubusercontent.com/78707242/133034185-4ec9f8a9-79d4-4e02-934d-d836a1305834.mp4

**Comment by fannheyward** [comment]
What's your minimal vimrc? From your screenshot, you're not using a minimal vimrc.

Here's my tests:

mini.vim

```vim
set nocompatible
set runtimepath^=~/.config/nvim/plugged/coc.nvim
set runtimepath^=~/.config/nvim/plugged/vim-snippets
filetype plugin indent on
syntax on
set hidden
```

coc-settings.json

```
{
  "languageserver": {
    "clangd": {
      "command": "clangd",
      "rootPatterns": [
        "compile_flags.txt",
        "compile_commands.json"
      ],
      "filetypes": [
        "c",
        "cc",
        "cpp",
        "c++",
        "objc",
        "objcpp"
      ]
    }
  }
}
```

nvim version: 0.5.0 release from GitHub, can't reproduce this issue.

**Comment by huibosa** [comment]
> What's your minimal vimrc? From your screenshot, you're not using a minimal vimrc.
> 
> Here's my tests:
> 
> mini.vim
> 
> ```viml
> set nocompatible
> set runtimepath^=~/.config/nvim/plugged/coc.nvim
> set runtimepath^=~/.config/nvim/plugged/vim-snippets
> filetype plugin indent on
> syntax on
> set hidden
> ```
> 
> coc-settings.json
> 
> ```
> {
>   "languageserver": {
>     "clangd": {
>       "command": "clangd",
>       "rootPatterns": [
>         "compile_flags.txt",
>         "compile_commands.json"
>       ],
>       "filetypes": [
>         "c",
>         "cc",
>         "cpp",
>         "c++",
>         "objc",
>         "objcpp"
>       ]
>     }
>   }
> }
> ```
> 
> nvim version: 0.5.0 release from GitHub, can't reproduce this issue.

I've tried your config, sadly the "bug" is still there, with version 0.5.0. My nvim all have the same promblem in archlinux and wsl

**Comment by chemzqm** [comment]
Delete character would cancel completion (hide suggest window) by now.
For the case in your video, seems the language server returns empty result which canceled the completion.
