### ISSUE TITLE
Invoke coc-definition not auto jump to definition, need hit Enter always

### ISSUE THREAD

**Issue by Aben** [neoclide/coc.nvim#338]
**Result from CocInfo**
```bash
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2018 12:07:57)
node version: v10.14.1
coc.nvim version: 0.0.46
term: iTerm.app
platform: darwin
```

**Describe the bug**
Invoke `coc-definition` not auto jump to definition, Need hit Enter always, I guess the reason is `CocActionAsync`, I changed to `CocAction` work prefect.
https://github.com/neoclide/coc.nvim/blob/0a1373135f9b91e6ad9c877b6800d708c6f84b10/plugin/coc.vim#L218

Meanwhile I think you choose async maybe depends some reason, So I posted this.

Awesome plugin:)

**Comment by chemzqm** [comment]
It's not because async, it's your vim block somehow.
Use configurations:
```
set hidden
set cmdheight=2
set shortmess+=c
```
to avoid vim block.
