### ISSUE TITLE
How to change the indentation size when using the formatOnSave feature ?

### ISSUE THREAD

**Issue by ThomasTraineau** [neoclide/coc.nvim#3393]
Inside of my init.vim file I added `set shiftwidth=2` but when saving an html file, coc formats it correctly (as wanted) but it doesn't respect the indentation size written in my init.vim file.
Is it normal and if yes how can I change it ?

**Comment by xiyaowong** [comment]
you need to check available configurations supported by the formatter

**Comment by fannheyward** [comment]
coc.nvim will read `shiftwidth` and forward the settings as [FormattingOptions](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#formattingOptions) to LS, here is HTML, if the LS follows the FormattingOptions, it should work.

**Comment by ThomasTraineau** [comment]
#coc.nvim will read shiftwidth and forward the settings as FormattingOptions to LS, here is HTML, if the LS follows the FormattingOptions, it should work.

Thanks but in my case it doesn't work...

**Comment by fannheyward** [comment]
Do you use coc-html?

**Comment by ThomasTraineau** [comment]
yes

**Comment by fannheyward** [comment]
Tested with mini.vim + coc.nvim + coc-html

```
set nocompatible
set runtimepath^=~/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
set shiftwidth=8
set tabstop=8
```

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Test</title>
    link
  </head>
  <body>
    body
  </body>
</html>
```

`call CocAction('format')` will format the HTML file with 8 space indent.

**Comment by ThomasTraineau** [comment]
Thanks ! It worked by adding those two lines to my init.vim :
`set shiftwidth=8
set tabstop=8`

**Comment by chemzqm** [comment]
You should use command like:
```
autocmd FileType html setl shiftwidth=8
```
