### ISSUE TITLE
coc.nvim completions interrupt/conflict with auto indent from 'indentkeys'

### ISSUE THREAD

**Issue by lervag** [neoclide/coc.nvim#3394]
## Describe the bug

Completion menu from coc.nvim disrupts auto indentation triggered by `indentkeys`.

This bug was also raised [here](https://github.com/lervag/vimtex/issues/2179), but I don't believe there is a bug on the VimTeX side.

## Reproduce the bug

First: clone VimTeX repo: `git clone https://github.com/lervag/vimtex`. Now, create this minimal `test.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vimtex
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
set hidden
```

Also create this minimal LaTeX file (`test.tex`):

```tex
\begin{itemize}
  \item foo
  \item bar
\end{itemize}
```

Steps to reproduce:
- Start neovim with command: `nvim -u test.vim test.tex`.
- If `coc-vimtex` is not already installed, run `:CocInstall coc-vimtex`
- Type: `Gko\item` to add a new `\item` line below "bar".

Expected: Proper auto indent of `\item`

Observed: If the completion menu from coc.nvim is displayed, then auto indent is prevented. If one types very fast so that the menu is not displayed, then auto indent works.

**Comment by fannheyward** [comment]
https://github.com/ycm-core/YouCompleteMe/issues/1244

**Comment by lervag** [comment]
@fannheyward Thanks. In particular, the workaround suggested in [this comment](https://github.com/ycm-core/YouCompleteMe/issues/1244#issuecomment-92159476) is interesting. For convenience, the workaround idea is to reset the indentkeys option after loading the filetype. Essentially, one can do this after loading a tex file:

`:execute "setlocal indentkeys=" . &indentkeys`

Fascinatingly, this actually works. So, what is happening here? Well, it is actually quite simple. Resetting the indentkeys option in this way _changes_ it:

```
Before (set by VimTeX)
!^F,o,O,(,),],},&,=\item,=\else,=\fi,=\rangle,=\rbrace,=\rvert,=\rVert,=\rfloor,=\rceil,=\urcorner

After (set by the extra 'execute "setlocal ..."')
!^F,o,O,(,),],},&,=item,=else,=fi,=rangle,=rbrace,=rvert,=rVert,=rfloor,=rceil,=urcorner
```

Notice how the backslashes (`\`) are removed. And interestingly, the latter version works.

I believe the reason may be that `coc-vimtex` and `coc.nvim` triggers completion on `\`, and that the completion menu somehow interrups the insert mode. The result is that the `indentkeys` are only matched on what is typed _after_ the completion menu is displayed, i.e. `item` instead of `\item`.

I would be surprised if it is possible to fix this in a robust way. But perhaps it would be possible with some type of "hackish" workaround where the `indentkeys` option is temporarily changed after completion is triggered by `\`?

**Comment by hrsh7th** [comment]
I met the same problem before.
I don't know my solution has no pitfall or not but I'm now using this.
https://github.com/hrsh7th/nvim-cmp/blob/main/plugin/cmp.lua#L20

1. TextChangedI/P fired.
2. First, check indentkeys and the before text.
3. Feed `<Plug>` mapping if need.

**Comment by lervag** [comment]
Thanks, @hrsh7th. Based on your solution, I've found the following seems to adequatly work:

```vim
autocmd CompleteDone * call s:autoindent()
function! s:autoindent() abort
  let l:ve = &virtualedit
  set virtualedit=all
  normal! ==
  let &virtualedit = l:ve
endfunction
```

However, I notice that this event is fired all the time with coc.nvim. And so I'm worried it may lead to some undesired delays?

**Comment by hrsh7th** [comment]
Too many CompleteDone event is common thing in vim's autocompletion. no worries.

**Comment by lervag** [comment]
Does it make sense to add this type of workaround to a filetype plugin like VimTeX? I notice that the same issue is observed without autocomplete issues simply by using the omnicomplete directly. Perhaps I should add this autocommand with a buffer restriction, something like this:

```vim
augroup vimtex
  autocmd!
  autocmd CompleteDone <buffer> ...
augroup END
```

**Comment by fannheyward** [comment]
> same issue is observed without autocomplete issues simply by using the omnicomplete directly

I think this patch should be added in VimTeX.

**Comment by lervag** [comment]
Thanks for the useful input!

**Comment by clason** [comment]
> > same issue is observed without autocomplete issues simply by using the omnicomplete directly
> 
> I think this patch should be added in VimTeX.

I think this patch should instead be added to `coc-vimtex` since it introduces significant issues in other situations...

**Comment by chemzqm** [comment]
Probably fixed by 7f5cf023, can't reproduce the issue now.

**Comment by lervag** [comment]
Nah, the issue as described in the original description is still there. But to reproduce, I have to manually comment out the fix I've pushed to VimTeX for this particular issue, e.g. [these lines](https://github.com/lervag/vimtex/blob/3cd379482b3d680ddb5b13c484c5d6c4b5d5a028/autoload/vimtex/complete.vim#L22-L26).

**Comment by chemzqm** [comment]
It's issue on vim side, you can try:
```
set completeopt=noinsert,noselect,menuone
```
in your vimrc.
Type `\ite` and invoke keywords completion by `<C-n>`, then type `m`, indent doesn't work as well.

**Comment by lervag** [comment]
Yes, I agree, this is probably an issue with Vim. As I mentioned earler:

> I notice that the same issue is observed without autocomplete issues simply by using the omnicomplete directly. ...

So I don't consider this an issue with coc.nvim in particular. Still, it seems possible and perhaps sensible to implement a fix from the autocomplete backend similar to what I believe is done in nvim-cmp (see @hrsh7th's comment [here](https://github.com/neoclide/coc.nvim/issues/3394#issuecomment-926482558)).

**Comment by chemzqm** [comment]
But it works expected on vim file, you can type `end` with auto indent works for example.

**Comment by chemzqm** [comment]
@lervag I've tried to fix it.

**Comment by lervag** [comment]
Great, thanks! Appreciated; it seems like a good fix! However, for some reason, there now seems to be a problem with coc.nvim + Ultisnips. Don't have time now, but I'll investigate further when there is time.
