### ISSUE TITLE
A way of accessing the library file where the recommended function is declared 

### ISSUE THREAD

**Issue by rafaelmuynarsk** [neoclide/coc.nvim#3400]
Here I have a javascript file where I've imported the `Leaflet` library and I'm checking its functions:

![Screenshot_20210926_235026](https://user-images.githubusercontent.com/44415096/134838830-c9807360-cdf6-45c8-8a79-cd93460bb314.png)

I'm not sure if this feature is already implemented and I don't know how to use it... But I'd like to have a way of accessing the library file where this function is declared (from inside Vim). I think that opening a new file on the buffer would be ideal. Is it already possible while using CoC?

The recommendation feature is great, but sometimes just seeing the library function and its parameters is not enough to understand it well... I know that I can manually enter the library files and find the functions there but that's not very efficient to do while working... I think having an internal way of doing it inside Vim would be perfect.

**Comment by fannheyward** [comment]
Do you mean display the declared file in the floating document window? We can't because the language server didn't return this.

You can use `<Plug>(coc-definition)` to jump to the definitions.

**Comment by rafaelmuynarsk** [comment]
Thanks, I managed to do what I wanted by putting `map <silent> gt :call CocAction('jumpDefinition', 'tabe')<CR>` on my vimrc file...
