### ISSUE TITLE
Can coc vim display all message diagnostic in lines of code

### ISSUE THREAD

**Issue by KenChanForever** [neoclide/coc.nvim#3402]
Hello,

  Just wondering if current latest version of coc.nvim can display all message diagnostic inline with vim? It would be more convenient to read all of them instead of the cursor hover with line by line. I know vim-lsp has this default feature, but not sure if in coc.nvim as well. Below is the ui display I am trying to config in coc.
in CocConfig, below line is what I tried, but still far from the desired one.
"diagnostic.checkCurrentLine": true

Desired one:
![image](https://user-images.githubusercontent.com/45708068/135045184-b337338b-ac02-4c9a-b693-29ce606365f1.png)

Please tell me if we have this setting in current version or in the future. Thanks a lot.

Best regards,
Ken

**Comment by fannheyward** [comment]
Set `diagnostic.virtualTextCurrentLineOnly` to `false` in your coc-settings.json.

**Comment by houtaru** [comment]
> Set `diagnostic.virtualTextCurrentLineOnly` to `false` in your coc-settings.json.

Hi, I found this setting does not work anymore, Are there any suggestions for this?

**Comment by ngnijland** [comment]
@houtaru for me this works as expected. Make sure to also add: `"diagnostic.virtualText": true,` to the config. Without that is doesn't work for me neither.
