### ISSUE TITLE
Zindex popup bug

### ISSUE THREAD

**Issue by nicoaudy** [neoclide/coc.nvim#3403]
I have issue after upgrading coc, popup not close, this is the reason from nvim [coc.nvim]: UnhandledRejection: request error nvim_call_function - Vim(let):E5555: API call: Invalid key 'zindex' Error.

**Comment by fannheyward** [comment]
Check https://github.com/neoclide/coc.nvim/issues/3380 and https://github.com/neoclide/coc.nvim/commit/2fb58dc009d020bf441788ebc9dc1bd21cdb73cc#commitcomment-56403511, make sure you're using nvim 0.5.0+ stable release, 0.5.0-dev will have this issue.

**Comment by exapsy** [comment]
> Check #3380 and [2fb58dc#commitcomment-56403511](https://github.com/neoclide/coc.nvim/commit/2fb58dc009d020bf441788ebc9dc1bd21cdb73cc#commitcomment-56403511), make sure you're using nvim 0.5.0+ stable release, 0.5.0-dev will have this issue.

Just to confirm, I had glitchy popups getting stuck on my screen, and this "zindex" error appeard on my CocLogs. I had `NVIM v0.5.0-828-g0a95549d6 Build type: RelWithDebInfo` (nightly) and updated to `NVIM v0.5.1 Build type: Release`.

Updating nvim from 5.0 nightly to 5.1 stable fixed the issue. Thank you.
