### ISSUE TITLE
extensions sandbox can't require global module

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#3405]
## Reproduce the bug

Create `test.js` in `.config/nvim/coc-extensions`:

```js
exports.activate = context => {
  const u = new URL('https://github.com')
  console.log(u.host)
}
```

Launch vim, coc.nvim throw error `Error on active extension single-test: ReferenceError: URL is not defined`

If put `const URL = require('url').URL` at begin of test.js, the error gone away. The `URL` module is global from Node.js 10, it's not needed to require to use.

**Comment by chemzqm** [comment]
You can use `global.URL` instead.

**Comment by chemzqm** [comment]
Add `globalThis.URL = global.URL` before module import.
