### ISSUE TITLE
formatOnSaveFiletypes not working with vue.js

### ISSUE THREAD

**Issue by ThomasTraineau** [neoclide/coc.nvim#3408]
Here is my coc-settings.json file :
`{"coc.preferences.formatOnSaveFiletypes": ["css","markdown","javascript","html","json","python","vue","php"]}`

I works with all the other languages but not with vue. For example if I write a div inside of another one (in a template), without correctly indenting them, on save nothing will change. 
Any idea of what I am doing wrong ?

**Comment by yaegassy** [comment]
Which extension do you use as a formatter for vue files?  Is it `coc-prettier`?

The default setting of `coc-prettier` excludes vue files, so you need to change the setting.

**REF**:

- <https://github.com/neoclide/coc-prettier#prettierdisablelanguages-default-vue>

**Comment by ThomasTraineau** [comment]
I wasn't using any formatter (not that I specifically installed at least). 
I installed coc-vetur and now the problem is solved though
