### ISSUE TITLE
'intro' page disappears with nvim + coc

### ISSUE THREAD

**Issue by laggardkernel** [neoclide/coc.nvim#3409]
Update 1: caused by `coc-explorer`. I forgot the delete the `~/.config/coc` folder during former test.

---

Not a serious bug, opened the issues out of curious about the problem I experienced.

## Result from CocInfo

```
## versions

vim version: NVIM v0.6.0-dev+368-g9337fff8a
node version: v14.17.6
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/foobar/.local/share/nvim/plugged/coc.nvim
term: xterm-kitty
platform: darwin

## Log of coc.nvim

2021-10-01T16:59:39.667 WARN (pid:42132) [attach] - Plugin not ready when received "highlight" []
2021-10-01T16:59:39.758 INFO (pid:42132) [services] - registered service "languageserver.efm"
2021-10-01T16:59:39.859 INFO (pid:42132) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v14.17.6 after 176ms
2021-10-01T16:59:41.045 INFO (pid:42132) [attach] - receive notification: showInfo []
```

## Describe the bug

~~When using coc with nvim, the `:intro` page disappears on neovim startup. But the intro page sticks when using vim (not nvim) + coc. Seems to be related the `jobstart()` called in `autoload/coc/client.vim s:start()`, but not sure if it's a problem of coc or neovim.~~

~~All I see is there's a loading "loading snippets ..." and the intro page disappears.~~

~~The `:intro` page disappears if run coc with `nvim`, but not with `vim`. I've also removed all my coc extensions during following test with `mini.vim`.~~

- vim version: 8.2.3450
- nvim version: 0.6.0-dev+368-g9337fff8a

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  let g:python_host_prog="/path/to/python3"
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by oblitum** [comment]
FWIW, if you pick almost any fancy statusline plugin, this will happen regardless, because the intro gets cleared when the status gets refreshed.

**Comment by laggardkernel** [comment]
@fannheyward Thanks for your reply. You word reminds me that I forgot to delete the extensions folder during the former test. Just tested again by deleting `~/.config/coc` and enabling extension one by one with `let g:coc_global_extensions = ['coc-ext-name']`. It turns out the problem is caused by `coc-explorer`, not jobstart(), coc or coc-snippets.

**Comment by fannheyward** [comment]
I don't think this will be fixed in coc.nvim, any plugin reloads/redraws will clear the `:intro` page, and I think it's not a big problem, close for now.

**Comment by chemzqm** [comment]
Use `nvim -u NORC` when you need that intro page.

**Comment by mikesmithgh** [comment]
I was interested in this and took a look. After I found the issue, I realized it had already been fixed 😂 . This commit https://github.com/neoclide/coc.nvim/commit/6ff9af9e7e0648942f9d46382cd0583507242217 should fix this when it is released. The timer call was causing a delay and wiping out the buffer during highlight commands. 👍
