### ISSUE TITLE
CocAction("doHover") shows hover window only for a fraction of a second

### ISSUE THREAD

**Issue by vlad-tymoshchyk** [neoclide/coc.nvim#3420]
## versions

vim version: NVIM v0.5.1
node version: v12.22.2
coc.nvim version: 0.0.80-c90a07eec8
coc.nvim directory: /home/vtymoshchyk/.vim/plugged/coc.nvim
term: screen-256color
platform: linux

## Describe the bug

When I do `CocAction("doHover")` the hover window appears only for a very small time and closes

## Screenshots (optional)
![Peek 2021-10-07 11-03](https://user-images.githubusercontent.com/25420932/136344707-2acd8dd3-084c-4e1c-af92-e8b0862414ce.gif)

**Comment by matteha** [comment]
Same issue with native LSP it seems, e.g. using lspconfig with cmp autocomplete with:

  buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)

The window shows a second and then closes.

**Comment by vlad-tymoshchyk** [comment]
Fixed that by updating to master branch in coc.nvim
