### ISSUE TITLE
CJK string complete error

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#3425]
## Reproduce the bug

test.ts:

```ts
'work'
'中文'
```

Input `.` at the end of each line, the suggestions will be listed, choose a Snippet completion item, for example `includes`:

```ts
'work'.includes(searchString)
'中文'.inclincludes(searchString)
```

The problem is caused that the completion item is Snippet, coc.nvim will try apply textEdit `onCompleteDone`. If there's no textEdit, coc.nvim will create a textEdit with incorrect col. 

https://github.com/neoclide/coc.nvim/blob/03c9add7cd867a013102dcb45fb4e75304d227d7/src/sources/source-language.ts#L149-L154

https://github.com/fannheyward/coc-pyright/issues/640

**Comment by chemzqm** [comment]
Fixed by f59f77c
