### ISSUE TITLE
Win32 api syntax highlighting in Coc

### ISSUE THREAD

**Issue by 17Swagat** [neoclide/coc.nvim#3426]
I wish if **COC** could provide a proper syntax highlighting for Win32 api functions , structs and other win32 api stuff
it would be really cool. 

In vscode I've only seen only one plugin called "One Dark Pro" do a proper Win32 api syntax highlighting.

It would be great to have the same way of syntax highlighting with **COC**.

**Images for comparison :-->** 

### **In Vs code:--> **

<img width="959" alt="img1" src="https://user-images.githubusercontent.com/72545910/136689667-46f1fc3a-b6b7-471a-b2a8-055909318ec3.PNG">
<img width="960" alt="img2" src="https://user-images.githubusercontent.com/72545910/136689668-0da1f386-90d1-49cf-96ff-fcac1d105e24.PNG">
<img width="960" alt="img3" src="https://user-images.githubusercontent.com/72545910/136689669-1be86dc1-9b78-4231-8fb0-3fc0a81da9f6.PNG">
<img width="955" alt="img4" src="https://user-images.githubusercontent.com/72545910/136689670-b6387888-f105-4f43-aaff-604e7980fa26.PNG">

### **In Neovide with Coc :--> **

<img width="657" alt="j1" src="https://user-images.githubusercontent.com/72545910/136689702-0142a575-40e8-488a-b92d-e44f3bdd172d.PNG">
<img width="669" alt="j2" src="https://user-images.githubusercontent.com/72545910/136689703-566faae4-93a4-497d-a353-31046cab8b04.PNG">

**Comment by 17Swagat** [comment]
> coc.nvim can do highlighting if the language server supports, do you use `clangd` with coc.nvim? If you're using clangd 12, you can enable semanticTokens highlighting by `let g:coc_default_semantic_highlight_groups = 1`.
> 
> Note 1: clangd supports two semantic highlighting protocol, you can use `coc-clangd` + https://github.com/jackguo380/vim-lsp-cxx-highlight with the old protocol.
> 
> Note 2: the new semanticTokens highlighting protocol in coc.nvim is not stable by now.

Hello @fannheyward I wrote the following `let g:coc_default_semantic_highlight_groups = 1` in my **init.vim** file , just like you said and it worked pretty well. Far better than the last one. **BUT ITS NOT WORKING PROPERLY.**

### **SAMPLE IMAGES :--> **
<img width="960" alt="a1" src="https://user-images.githubusercontent.com/72545910/136824136-6cfab5ef-71e6-4d26-89a7-ac5cd13e7995.PNG">
<img width="909" alt="a2" src="https://user-images.githubusercontent.com/72545910/136824144-ccfd6bb5-d7d4-441f-87c4-a8598ff19781.PNG">
<img width="960" alt="a3" src="https://user-images.githubusercontent.com/72545910/136824146-2d8747eb-3a73-46a6-8d64-48c161dcd7a3.PNG">


### **PROBLEM THAT I'M FACING NOW **
1. Everything is working very slowly. During the startup it takes quite some time to show the properly colored **win32** stuff.
2. On scrolling up and down, the highlighting suddenly disappears. Also if I write something new on the file, the highlighting also disappears after some few seconds. I don't know why its happening.

**Is there anyway to solve these issues.**

### **SAMPLE IMAGES :--> **
<img width="960" alt="b1" src="https://user-images.githubusercontent.com/72545910/136824162-b4db3fc2-9c29-4790-b113-60e72b2c0da0.PNG">

**Comment by oblitum** [comment]
Bad coloring should have been fixed at https://github.com/neoclide/coc.nvim/pull/3314, are you using latest coc.nvim? You don't report your version / fill issue-template. With [feat/use-ts-hi-group](https://github.com/neoclide/coc.nvim/tree/feat/use-ts-hi-group) branch you can use semantic LSP together with tree-sitter. LSP servers may be slow to launch, so it's normal that LSP highlighting happens late, using a tree-sitter based colorscheme with that branch is a good solution, while LSP is initializing you get syntax highlighting up to what tree-sitter can do, then afterwards a few touch ups are applied by LSP tokens.

**Comment by 17Swagat** [comment]
> coc.nvim can do highlighting if the language server supports, do you use `clangd` with coc.nvim? If you're using clangd 12, you can enable semanticTokens highlighting by `let g:coc_default_semantic_highlight_groups = 1`.
> 
> Note 1: clangd supports two semantic highlighting protocol, you can use `coc-clangd` + https://github.com/jackguo380/vim-lsp-cxx-highlight with the old protocol.
> 
> Note 2: the new semanticTokens highlighting protocol in coc.nvim is not stable by now.

And also I'm using **clangd** and **vim-lsp-cxx-highlight** extension.

**Comment by 17Swagat** [comment]
> Bad coloring should have been fixed at #3314, are you using latest coc.nvim? You don't report your version / fill issue-template. With [feat/use-ts-hi-group](https://github.com/neoclide/coc.nvim/tree/feat/use-ts-hi-group) branch you can use semantic LSP together with tree-sitter. LSP servers may be slow to launch, so it's normal that LSP highlighting happens late, using a tree-sitter based colorscheme with that branch is a good solution, while LSP is initializing you get syntax highlighting up to what tree-sitter can do, then afterwards a few touch ups are applied by LSP tokens.

My coc.nvim version is **0.0.80-19ead882b9**

**Comment by chemzqm** [comment]
The semanticTokens highlight feature of coc.nvim is not stable, my suggesion is simply add syntax highlights commands to your vimrc.
