### ISSUE TITLE
coc.nvim is not working with python 3.10

### ISSUE THREAD

**Issue by hungpham3112** [neoclide/coc.nvim#3428]
I upgrade Python3.9 to Python 3.10 and see the messages:

> 

Messages maintainer: Bram Moolenaar <Bram@vim.org>
[coc.nvim] Error on execute python script: request error nvim_command - Vim(py3file):E370: Could not load library python39.dll

**Comment by chemzqm** [comment]
You have to recompile your vim after upgrade python, neovim doesn't have that issue with using remote protocol.
