### ISSUE TITLE
Add bash install script to fetch dependencies.

### ISSUE THREAD

**Issue by shawnohare** [neoclide/coc.nvim#343]
It would be nice if `CoC` came with a basic bash install script that handled all dependency fetching for those who do not require special JS or Node setups (i.e., do not have `yarn` or `nvm` installed). This way users do not have to write special installation code in their vim init file or install external dependencies.

This primarily benefits those of us who work in relatively ephemeral environments (e.g., AWS EMR nodes) and want `vim` to bootstrap all its dependencies on the first run.

**Comment by chemzqm** [comment]
The script could be different depends on your system and requirement, so I created an example:https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#automation-script

Which includes all your need for installation.
