### ISSUE TITLE
Does this amazing plugin stop development?

### ISSUE THREAD

**Issue by rockyzhang24** [neoclide/coc.nvim#3434]
Hello,
I have been using coc for a really long time and plan to consist on it, not switching to the native lsp. Recently I notice this is the first time for the author to stop submitting code for such a long period. I’m wondering whether this plugin has stopped developing new features and just bug fixes only?

Thank you very much.

**Comment by fannheyward** [comment]
No, the development is not stopped. @chemzqm is busy with his work these days, I'm working on some issues on separate branches, the master branch is slowly getting merged these days.
