### ISSUE TITLE
Question: Jump between source and interface

### ISSUE THREAD

**Issue by crackcomm** [neoclide/coc.nvim#3437]
Hey, sorry for creating an issue just to ask this question but I can't find an answer anywhere and I remember having this working before I lost my `init.vim`. I am trying to jump between source and interface file. I can do this easily with C++ and it works using `:CocCommand clangd.switchSourceHeader vsplit` but this doesn't work for OCaml `.ml`/`.mli` files and I remember it did before. It didn't use any additional scripts, just defining a keybinding to existing coc function. Could anyone help me find this function?

**Comment by fannheyward** [comment]
> :CocCommand clangd.switchSourceHeader vsplit

This is a feature provided by clangd, not all language server supports this, here is OCaml.

> I remember it did before

I don't think coc.nvim/coc-clangd/clangd did this.
