### ISSUE TITLE
FormatHandler class doesn't respect coc.preferences.willSaveHandlerTimeout

### ISSUE THREAD

**Issue by hazelweakly** [neoclide/coc.nvim#3441]
## Result from CocInfo

(the filetype is not important here)

```txt
[handler-format] - Format on type provider not found for buffer: file:// (omitted) /f.py
v--- result of save action --- does not respect willSaveHandlerTimeout
[handler-format] - Format on save file:// (omitted) /f.py timeout after 0.5s

[attach] - Request action: format []
v--- result of :call CocAction('format') --- works fine
[plugin] - Slow action "format" cost 533ms
```

## Describe the bug

[`src/handler/format.ts:51`](https://github.com/neoclide/coc.nvim/blob/fe7ba28af09edac24ff04544dbcf15450783aa7a/src/handler/format.ts#L51) has a hardcoded 500ms timeout, so it will timeout at 500ms regardless of what the willSaveHandlerTimeout is set to.

## Reproduce the bug

This is easiest to reproduce with a slow formatter like python's black on a large file and, eg, `coc-python`. Changing `willSaveHandlerTimeout` will not have any affect on the timeout of the formatOnSave.

Example coc-settings.json that can reproduce the issue.

  ```jsonc
{
  "coc.preferences.formatOnType": true,
  "coc.preferences.formatOnSaveFiletypes": ["python"], # I typically have this set to ["*"]
  "coc.preferences.willSaveHandlerTimeout": 2000, # any number > 500
  "python.formatting.provider": "black"
}
  ```

Setting willSaveHandlerTimeout to _less_ than 500 does work because `black` is still running and gets correctly canceled by its caller.

**Comment by laurentS** [comment]
I just got bitten by this. Your suggested fix does work, but it seems very unintuitive. Does this mean that coc.nvim will run the formatting (I use `coc-pyright`), cancel it and then run the CocAction above? Why not use the config setting instead of hardcoding the 500ms limit?

**Comment by fannheyward** [comment]
@laurentS you can disable formatOnSave for Python, run formatting from CocAction only.

> Why not use the config setting instead of hardcoding the 500ms limit?

coc.nvim can also increase the 500ms limit, but this will delay the saving event
