### ISSUE TITLE
multiple character width icons in PUM are rendered incorrectly with pumblend when there is a character behind the pum

### ISSUE THREAD

**Issue by ihasdapie** [neoclide/coc.nvim#3442]
## versions

vim version: NVIM v0.5.1
node version: v14.15.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /home/ihasdapie/.config/nvim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2021-10-23T23:36:59.863 INFO (pid:29769) [services] - registered service "languageserver.svls"
2021-10-23T23:37:00.018 INFO (pid:29769) [services] - registered service "highlight"
2021-10-23T23:37:00.133 INFO (pid:29769) [coc-tabnine] - Using tabnine from /home/ihasdapie/.config/coc/extensions/coc-tabnine-data/binaries/3.7.22/x86_64-unknown-linux-musl/TabNine
2021-10-23T23:37:00.153 INFO (pid:29769) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v14.15.0 after 442ms
2021-10-23T23:37:00.946 INFO (pid:29769) [attach] - receive notification: showInfo []

## Describe the bug

Two-wide unicode icons for `"suggest.competionItemKindLabels" get rendered as their one-width counterpart when `pumblend` > 0.

![Screenshot_20211023_234749](https://user-images.githubusercontent.com/54821716/138579785-0ed1bd16-6348-496d-a7a5-732433b145d5.png)
with `pumblend=0`

![Screenshot_20211023_233253](https://user-images.githubusercontent.com/54821716/138579513-fad87185-4fb4-4e3f-8af0-21b947b6b3d7.png)
with `pumblend=30`

## Reproduce the bug

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
set pumblend=15
  syntax on
  set hidden
  ```

coc-settings.json
``` json
        "suggest.completionItemKindLabels": {
                "keyword" : " ",
                "variable" : " ",
                "value" : " ",
                "function" : "ℱ",
                "operator" : "Ψ",
                "method" : "",
                "constructor" : " ",
                "reference" : "渚",
                "constant" : " ",
                "struct" : "\ufb44",
                "class" : " ",
                "interface" : " ",
                "text" : " ",
                "enum" : " ",
                "enumMember" : " ",
                "module":"全",
                "color" : " ",
                "property" : " ",
                "field" : "料",
                "unit" : " ",
                "event" : "鬒",
                "file" : " ",
                "folder" : " ",
                "snippet" : " ",
                "typeParameter" : " ",
                "default" : " ",
        }


```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by ihasdapie** [comment]
Yeah that seems like a good workaround for the time being. Seems like it has something to do with how `kitty` and `neovim` implement `wcswidth` https://github.com/kovidgoyal/kitty/issues/4094 and neovim's implementation being likely incorrect.

**Comment by oblitum** [comment]
[I've been there once](https://github.com/wez/wezterm/issues/1231#issuecomment-945141616).

**Comment by ihasdapie** [comment]
So no real good solution here... 

I'll just live with the inconsistent sizing, no big deal. Wonder if it would be worthwhile filing an issue to the neovim repo

**Comment by oblitum** [comment]
🤷🏽‍♂️
