### ISSUE TITLE
backspace and brackets not working after `:call coc#rpc#stop()`

### ISSUE THREAD

**Issue by Abh15h3k** [neoclide/coc.nvim#3444]
I use `:call coc#rpc#stop()` to disable coc when openning multiple nvim in a big java project (since jdtls starts up and takes up memory).

but i noticed the some keys in insert mode stopped working like backspace and bracket keys (i have coc-pairs installled).

imap shows that there keys are still mapped to coc functions.

```
i <BS>         * coc#_insert_key('request', 'iPGJzPg==0')
i  "           * coc#_insert_key('request', 'iIg==0')
i  '           * coc#_insert_key('request', 'iJw==0')
i  (           * coc#_insert_key('request', 'iKA==0')
i  )           * coc#_insert_key('request', 'iKQ==0')
i  <           * coc#_insert_key('request', 'iPA==0')
i  >           * coc#_insert_key('request', 'iPg==0')
i  [           * coc#_insert_key('request', 'iWw==0')
i  ]           * coc#_insert_key('request', 'iXQ==0')
i  `           * coc#_insert_key('request', 'iYA==0')
i  {           * coc#_insert_key('request', 'iew==0')
i  }           * coc#_insert_key('request', 'ifQ==0')
```

how can i clear these mapping (and any other mappings of coc) when running `:call coc#rpc#stop()`

**Comment by chemzqm** [comment]
Or use unmap command of vim.
