### ISSUE TITLE
How to fix code block misalignment caused by file tab

### ISSUE THREAD

**Issue by PendragonSaber** [neoclide/coc.nvim#345]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
![1](https://user-images.githubusercontent.com/41671631/51166586-05777800-18df-11e9-9ccd-b06bb6bbf830.png)

**Describe the bug**
The position of the code block is misplaced. Is the position of this code block fixed? I set up the tab of go, I found it misplaced, if I wrote it at the beginning of the location it is normal

**To Reproduce**
1. I  set tab for go 
```
au BufNewFile,BufRead *.go set filetype=go  noexpandtab tabstop=4 shiftwidth=4
```
2.and  fmt.
**Screenshots**
![ulite](https://user-images.githubusercontent.com/41671631/51167059-6a7f9d80-18e0-11e9-876b-2d6e7dfd32b7.gif)

**Comment by PendragonSaber** [comment]
> OK, I've reproduced it.

Hmm ,I commented on that line, I found it still not correct, I am not sure whether it is related to vim-go.

**Comment by chemzqm** [comment]
It's bug of column calculation.

**Comment by PendragonSaber** [comment]
> No, It's bug of column calculation.


I hope I can fix it as soon as possible

**Comment by PendragonSaber** [comment]
> No, It's bug of column calculation.

@chemzqm  it's works ok! thanks
