### ISSUE TITLE
Floating window would remain when exiting neovim.

### ISSUE THREAD

**Issue by jtroeth1** [neoclide/coc.nvim#3452]
Hi there,

I am often getting this message while using Coc for c++, when trying to exit. I have to do CocRestart to fix it, but it comes back.
![image](https://user-images.githubusercontent.com/37925036/139819132-789c5c94-4545-4d8a-b9c1-b4c9461bbc7a.png)

Coc seems to think I have a floating window open (the grey bar at the side?):
![screenshot_2021-11-02_18-44-49](https://user-images.githubusercontent.com/37925036/139819505-518a8c77-5bc1-44c0-b6ea-423c2fceccee.png)

Has anyone seen this issue, or know what could be causing it?

Thanks

**Comment by fannheyward** [comment]
What's your `:CocInfo`?

**Comment by jtroeth1** [comment]
## versions
vim version: NVIM v0.4.4
node version: v12.22.1
coc.nvim version: 0.0.79-230b8a7247
coc.nvim directory: /home/jtroeth/.vim/plugged/coc.nvim
term: alacritty
platform: linux

**Comment by fannheyward** [comment]
> coc.nvim version: 0.0.79-230b8a7247

You're using an old coc.nvim release, upgrade your coc.nvim please.
