### ISSUE TITLE
jedi error for python completion

### ISSUE THREAD

**Issue by Shuvadip-Ghosh** [neoclide/coc.nvim#3453]
This is the error I am facing
[coc.nvim] Jedi error: Traceback (most recent call last):
  File "C:\Users\Shuvadip_Ghosh\AppData\Local\coc\extensions\node_modules\coc-python\pythonFiles\completion.py", line 696, in <module>

This error pops up while staring to edit a python file followed by the error listed by

[coc.nvim] Jedi error: Traceback (most recent call last):
[coc.nvim] Jedi error:     import jedi^M

[coc.nvim] Jedi error:     import jedi
ModuleNotFoundError: No module named 'jedi'

[coc.nvim] Jedi error:     import jedi

I have tried using "pip install jedi"  but this doesn't work either
I have tried editing my coc-settings.json files and putting my python interpreter explicitly but nothing works
And I am also not getting autocompletion because of this.
I am totally new to neovim so any help will be appreciated

And this is my neovim version and all
NVIM v0.6.0-dev+544-g7ae86c1d4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-71

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

**Comment by Shuvadip-Ghosh** [comment]
Forgot to mention one thing 
I am not getting this when I am writing a python file in the directory which has the file init.vim
and I am using windows 10 by the way

**Comment by yaegassy** [comment]
[coc-python](https://github.com/neoclide/coc-python) has been stopped to maintain, try `coc-pyright` or `coc-jedi`.

**Comment by Shuvadip-Ghosh** [comment]
I understand what you are saying but can you give me the reason for the
auto complementation not working outside init.vim directory but working in
that directory and I am using windows

**Comment by chemzqm** [comment]
No idea,.should be issue with language server you're using.
