### ISSUE TITLE
Provide a mechanism to get the node path programmatically

### ISSUE THREAD

**Issue by arthropodSeven** [neoclide/coc.nvim#3458]
**Is your feature request related to a problem? Please describe.**
I use `coc.nvim` on different machines. At work, I use the version manager [`asdf`](https://github.com/asdf-vm/asdf). At home I use either [`n`](https://github.com/tj/n) or [`nvm`](https://github.com/nvm-sh/nvm). This can be an issue at times, as I can't always use the same explicit value for `g:coc_node_path`. 

**Describe the solution you'd like**
I would find it helpful if I could provide some kind of a script to determine the node path. 

My first thought is that I could get the path by evaluating a shell script, but I'm open to alternatives.

```viml
let g:coc_node_resolver = "asdf --global where nodejs latest"
```

**Describe alternatives you've considered**
- Configure the node path via an environment variable? 
- Configure the node path via an extension? 

**Additional context**
I don't think anything else is particularly relevant here. Thank you for your time!

**Comment by oblitum** [comment]
IMO,`g:coc_node_path` is the sufficient flexibility for this, which is already in. From either VimL or Lua you can run anything to set this variable to any dynamic value, so, I'm not sure what more you're looking for.

**Comment by arthropodSeven** [comment]
Thanks @oblitum and @fannheyward , I apologize for the silly request.
