### ISSUE TITLE
Does coc.nvim support 32 bit

### ISSUE THREAD

**Issue by SingularisArt** [neoclide/coc.nvim#3464]
Hello all. I was just wondering if coc.nvim is supported on 32-bit Linux.

**Comment by oblitum** [comment]
Yes, I've run it on Linux with ARMv7. No issues except my CPU was too barebones and these things are not made to run the absurdly heavy language servers in the LSP ecosystem. Careful if you try. Notice the client (coc.nvim, vim-lsp, nvim-lsp, etc) won't matter much.

**Comment by oblitum** [comment]
off-topic: @SingularisArt out of curiosity I've hit your page and [your LaTeX article](https://damrah.netlify.app/post/note-taking-with-latex-part-1/), it's cool. I also have extensive support for it [in my setup](https://codeberg.org/oblitum/dotfiles), which is [coc.nvim based](https://codeberg.org/oblitum/dotfiles/src/commit/daa705616a912a36ae96ce4d3d3863fb479c64d5/.config/nvim/init.lua#L996-L1021), you may be interested in looking around and borrowing some stuff.

**Comment by SingularisArt** [comment]
@oblitum Very cool. I will definitely take a look at it when I have the chance. Thanks for the suggestion.

**Comment by SingularisArt** [comment]
Quick question.
How do I install the newest nodejs version on 32 bit Ubuntu?

**Comment by oblitum** [comment]
@SingularisArt no idea, I install Arch Linux on all my devices.

**Comment by bryant-the-coder** [comment]
How to write the config in lua?

**Comment by oblitum** [comment]
My setup linked above has a `init.lua`, with coc configured inside it, you can either use `vim.g.coc_user_config` or `coc#config()`.
