### ISSUE TITLE
309f9540 causes vim-fugitive output to be cleared

### ISSUE THREAD

**Issue by Frederick888** [neoclide/coc.nvim#3465]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.1
node version: v17.0.1
coc.nvim version: 0.0.80-e7f0057852
coc.nvim directory: /Users/frederick.zhang/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2021-11-11T11:56:04.207 INFO (pid:26352) [services] - registered service "languageserver.ccls"
2021-11-11T11:56:04.209 INFO (pid:26352) [services] - registered service "languageserver.dockerfile"
2021-11-11T11:56:04.209 INFO (pid:26352) [services] - registered service "languageserver.bash"
2021-11-11T11:56:04.209 INFO (pid:26352) [services] - registered service "languageserver.cmake"
2021-11-11T11:56:04.209 INFO (pid:26352) [services] - registered service "languageserver.sql"
2021-11-11T11:56:04.210 INFO (pid:26352) [plugin] - coc.nvim 0.0.80-e7f0057852 initialized with node: v17.0.1 after 33ms
2021-11-11T11:56:09.147 INFO (pid:26352) [attach] - receive notification: showInfo []
```

## Describe the bug
309f9540 causes vim-fugitive output to be cleared when there's pop-up [pinentry](https://gnupg.org/related_software/pinentry/index.html) involved in vim-fugitive operations.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

Note that this issue is only reproducible if you tap on YubiKey ***immediately*** after providing PIN.

So one stable way to reproduce this issue I've found is to enable [Touch Cache](https://support.yubico.com/hc/en-us/articles/360016649139-YubiKey-5-2-Enhancements-to-OpenPGP-3-4-Support#h.t1ul9g4eswo7) on YubiKey so that the second PGP operation doesn't require a tap. Or alternatively I guess one can also disable tap or use NFC.

- Create file `mini.vim` with：

  ```vim
  set runtimepath^=~/.vim runtimepath+=~/.vim/after
  let &packpath = &runtimepath
  call plug#begin()
  Plug 'tpope/vim-fugitive'
  Plug 'neoclide/coc.nvim', { 'branch': 'release' }
  call plug#end()
  ```

- Run `gpgconf --kill scdaemon` to make sure SmartCard PIN is not cached.
- Start (neo)vim with command: `vim -u mini.vim`
- Open a random file in a Git repository and change something
- `:G`, go to the file and `s` to stage the change, <kbd>c</kbd><kbd>Enter</kbd>, then give it a commit message
- `:wq`, now `pinentry` should show up, provide PIN
- Tap on YubiKey, finish committing (if you're quick enough, `git commit` output is also cleared)
- `:G push` immediately, `pinentry` pops again, provide PIN
- Now cos it's within 15s Touch Cache, `git push` starts right away
- After `git push` the output in cmd area is cleared

---

PS:
I bisected on release branch and found 309f9540, then switched to master, reverted it and could confirm the problem was gone.

```
# bad: [287c743c9f227fdf0e1db452bbb8ae3c5caffc36] commit 03c9add7cd867a013102dcb45fb4e75304d227d7
# good: [ce448a6945d90609bc5c063577e12b859de0834b] Release 0.0.80
git bisect start 'release' 'HEAD'
# good: [f9c4fc96fd08f13f549c4bc0eb56f2d91ca91919] commit bf98939a8cdaee5a0d9dbc70610660e5298075d7
git bisect good f9c4fc96fd08f13f549c4bc0eb56f2d91ca91919
# bad: [34d9d52f4e030a7f1c5e15afa1928cad6d9d903d] commit 131f6b267f2c458f9413b3568338482cad451635
git bisect bad 34d9d52f4e030a7f1c5e15afa1928cad6d9d903d
# good: [17494990ab110b70aec3d7c97707448c6d3e72c9] commit 971c5f81b4564bbcb1f3d34e23149bd070dff127
git bisect good 17494990ab110b70aec3d7c97707448c6d3e72c9
# bad: [898335d52ed925e8dd5dd3da3c25470d352b2e11] commit b427b2ccfae10589044e187698804596344c9467
git bisect bad 898335d52ed925e8dd5dd3da3c25470d352b2e11
# good: [06d950e547e8fa1a775399ae5eeb70603084b109] commit 69e029ed9ee424cd9a34ae2b7085c37eaa1c11a1
git bisect good 06d950e547e8fa1a775399ae5eeb70603084b109
# bad: [3bf9a40bf7da355f67a86d5c7f9a14fe76b44818] commit a2978b3abdf5991766dbd5fcbacc948e503d28da
git bisect bad 3bf9a40bf7da355f67a86d5c7f9a14fe76b44818
# bad: [607b059e5502e71eacd9e911511fd9dce496cc2a] commit 509209a03fa51cdc04d7b8158269bcb79eb98a6d
git bisect bad 607b059e5502e71eacd9e911511fd9dce496cc2a
# first bad commit: [607b059e5502e71eacd9e911511fd9dce496cc2a] commit 509209a03fa51cdc04d7b8158269bcb79eb98a6d
```

**Comment by fannheyward** [comment]
Looks like it's `FocusLost` event, coc.nvim fired the autocmd on event.

**Comment by chemzqm** [comment]
Could be caused by some coc extension, try use `let $COC_NO_PLUGINS = '1'` in your vimrc.

**Comment by Frederick888** [comment]
@chemzqm I added `let $COC_NO_PLUGINS = '1'` to my original minimal vimrc (and also manually disabled all extensions and removed language server configurations from my `coc-settings.json` just to be safe), but I was still able to reproduce this issue.

```
## versions

vim version: NVIM v0.6.0
node version: v17.3.0
coc.nvim version: 0.0.80-bd1ad34df2
coc.nvim directory: /home/frederick/.vim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2021-12-26T22:49:29.940 INFO (pid:65523) [plugin] - coc.nvim 0.0.80-bd1ad34df2 initialized with node: v17.3.0 after 93ms
2021-12-26T22:49:32.364 INFO (pid:65523) [attach] - receive notification: showInfo []
```

**Comment by chemzqm** [comment]
FocusLost event does nothing by default try comment out that line in plugin/coc.vim

**Comment by Frederick888** [comment]
Just wanna drop a note that this was fixed by https://github.com/tpope/vim-fugitive/issues/1909.

Thanks for all the help.
