### ISSUE TITLE
'\' generates wrong path completion in windows

### ISSUE THREAD

**Issue by xvim64** [neoclide/coc.nvim#3470]
Windows 10 21H1 64bit
gVim v8.2.3614

## versions

```
vim version: VIM - Vi IMproved 8.2 8023614
node version: v14.18.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: C:\home\.vim\plugged\coc.nvim
term: undefined
platform: win32
```

## Log of coc.nvim

2021-11-18T16:05:00.913 INFO (pid:6208) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v14.18.0 after 162ms
2021-11-18T16:05:01.086 INFO (pid:6208) [attach] - receive notification: highlight []
2021-11-18T16:05:04.605 INFO (pid:6208) [attach] - receive notification: showInfo []

## Describe the bug

```
'\' generates wrong path completion in windows
```

## Reproduce the bug

  ```vim
set nocompatible
filetype plugin indent on
syntax on
set hidden

"set go=egt
"colo solarized
"set guifont=Ubuntu_Mono:h28
"autocmd GUIEnter * call libcallnr("gvimfullscreen.dll", "ToggleFullScreen", 0)

source ~/.vim/plug.vim
call plug#begin('~/.vim/plugged')
    "Plug 'vim-airline/vim-airline'
    "Plug 'vim-airline/vim-airline-themes'
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
  ```

  ```tree
D:\> tree a1
D:\A1
├─B1
│  ├─C1
│  ├─C2
│  ├─C3
│  ├─C4
│  └─C5
├─B2
├─B3
├─B4
└─B5
  ```

## Screenshots (optional)

![bug-coc-path-completion](https://user-images.githubusercontent.com/83569599/142372930-1b19fc52-3650-499a-9460-d58ce91f2f72.gif)

**Comment by fannheyward** [comment]
I don't have a Windows env to debug for this issue.
