### ISSUE TITLE
Inspect Semantic Token Under Cursor

### ISSUE THREAD

**Issue by acdifran** [neoclide/coc.nvim#3471]
Is there a way to inspect the semantic token for the word/symbol under the cursor? Something similar to the “Scope Inspector” in VS code?

If not, would it be possible to add this functionality? Currently, I can only find a way to list all of the semantic tokens being used by running `:call CocActionAsync('showSemanticHighlightInfo')`, but there’s no way to see which token is being used for a given symbol.

**Comment by damnskippy** [comment]
@acdifran https://github.com/jackguo380/vim-lsp-cxx-highlight might do this.
Specifically, this: https://github.com/jackguo380/vim-lsp-cxx-highlight/blob/master/doc/vim-lsp-cxx-highlight.txt#L92
It's another plugin I know and is not native to coc.nvim as your original question, but this might do it in the mean time.

**Comment by acdifran** [comment]
Thanks @damnskippy, I’ll check it out!

**Comment by fannheyward** [comment]
`vim-lsp-cxx-highlight` can do nothing about semanticTokens highlighting. I'll improve this after https://github.com/neoclide/coc.nvim/pull/3355

**Comment by chemzqm** [comment]
Fixed by 198aece3
