### ISSUE TITLE
Popup text colour matches background

### ISSUE THREAD

**Issue by ayroblu** [neoclide/coc.nvim#3473]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8023550
node version: v17.0.1
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/blu/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2021-11-20T16:04:09.397 INFO (pid:74127) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v17.0.1 after 435ms
2021-11-20T16:04:09.446 INFO (pid:74127) [services] - registered service "tsserver"
2021-11-20T16:04:11.111 INFO (pid:74127) [attach] - receive notification: showInfo []
```

## Describe the bug

Popup text colour matches background as per this image:

![image](https://user-images.githubusercontent.com/4915682/142733069-c1a3b45b-afe2-4da8-8277-495df804a7cc.png)

The text is there when I use tmux to select it: 

![image](https://user-images.githubusercontent.com/4915682/142733085-20b0144f-2012-4300-a2cf-5c1d65cfb443.png)

Documentation does show up though, so I'm not sure if it's a tsserver or something else issue

![image](https://user-images.githubusercontent.com/4915682/142733957-4dd55e90-74c1-4415-a531-5f49cf9f79c9.png)

## ~~Reproduce the bug~~ Asking for help

I'm not exactly sure how to debug this issue, but would love some hints, my vimrc is at:
https://github.com/ayroblu/dotfiles/blob/master/.vimrc#L679
with the coc settings specifically at:
https://github.com/ayroblu/dotfiles/blob/master/.vimrc-plugins#L495

I'm using alacritty with the solarised theme as described here: 
https://github.com/ayroblu/dotfiles/blob/master/.alacritty.yml

I do have the same issue on the normal terminal fwiw (different colours, but the text is still unreadable)

**Comment by oblitum** [comment]
This is difficult to ever happen, the colorscheme should be broken somehow regarding floating highlighting, check `:h CocFloating` for learning the highlighting groups you have to tweak.

**Comment by ayroblu** [comment]
I tried changing Pmenu based on the help, but it wasn't working for me
![image](https://user-images.githubusercontent.com/4915682/142741735-b26c1060-b2e0-464c-befe-c49e40d63093.png)
![image](https://user-images.githubusercontent.com/4915682/142741731-2464c310-d75a-485b-bc8f-5fda068fd265.png)

I tried all the CocFloating variations e.g. CocInfoFloat -> CocInfoSign etc but no effect

I see that it's yellow in gui vim (above screenshot is terminal)
![image](https://user-images.githubusercontent.com/4915682/142741626-2d65c748-09ec-4159-ae60-3209025e454c.png)

**Comment by oblitum** [comment]
Which colorscheme is this?

**Comment by ayroblu** [comment]
solarised light: https://github.com/altercation/vim-colors-solarized

**Comment by oblitum** [comment]
I wanted to try it but this colorscheme has not received an update in 10 years... just dead.

**Comment by ayroblu** [comment]
I see this looking at `:highlight` : 
![image](https://user-images.githubusercontent.com/4915682/142742089-6a75ee5a-d95e-4739-a0a5-f87f652664f6.png)

And that seems to change it
![image](https://user-images.githubusercontent.com/4915682/142742109-8044d34d-995a-478e-9545-615efd2e0b64.png)

**Comment by ayroblu** [comment]
> I wanted to try it but this colorscheme has not received an update in 10 years... just dead.

To be fair it's a colour scheme, it doesn't really need to change

**Comment by oblitum** [comment]
This is how it looks on my side:

![img-2021-11-20-192034](https://user-images.githubusercontent.com/1269815/142742459-898ca56d-0baf-4451-9b3c-6a7f5cdc8abe.png)

Got a hard time to figure out how to make it actually function, it was necessary to debug that I had to disable `termguicolors`, as it can't work with that. It still doesn't look great, the side docs are wholly bad. There's other solarized colorchemes, I suggest to move to something more recent/maintained, old software may break with time, even colorschemes.

**Comment by oblitum** [comment]
FWIW, this colorschemes recalls me [gruvbox material](https://github.com/sainnhe/gruvbox-material) [hard light](https://user-images.githubusercontent.com/37491630/75227137-8a50e880-57a5-11ea-90dc-b2646d8b0b55.png).

**Comment by ayroblu** [comment]
Colorschemes are such a pain generally, and though I might generally agree with the sentiment, in this case I don't think it's an issue with the colorscheme.

I noticed that if I call `:colorscheme solarized` after my buffer has loaded, that the text loads in the correct color

![image](https://user-images.githubusercontent.com/4915682/142743373-e5ea9e0e-276b-4fdc-bcd5-a5243d2eacc7.png)

imo, it's some kind of coc issue, cause the floating color is set by coc, and it's done after BufReadPost too (the latest autocmd I can think of), so coc is taking something that's working and literally overwriting it to something that doesn't work.

I've been using a similar config for a while, so I think it's a relatively recent regression as I was just setting up my new computer and noticed this issue

**Comment by oblitum** [comment]
This colorscheme in specific has quite a convoluted logic inside it though.

**Comment by oblitum** [comment]
Have you checked whether removing this line of your `.vimrc` changes anything?

https://github.com/ayroblu/dotfiles/blob/master/.vimrc#L685

**Comment by ayroblu** [comment]
> Have you checked whether removing this line of your `.vimrc` changes anything?
> 
> https://github.com/ayroblu/dotfiles/blob/master/.vimrc#L685

No effect from that

**Comment by ayroblu** [comment]
Do you know how `FgCocInfoFloatBgCocFloating` happens? I think if I know that, then we can find the root cause

**Comment by oblitum** [comment]
> Do you know how `FgCocInfoFloatBgCocFloating` happens?

Simply no idea, because I don't have that highlight group on my side (I changed back to my usual colorscheme, I also use nvim, and can't get this unusual highlighting group, it's the first time I've seen a mention to it).

**Comment by oblitum** [comment]
At this time, I'd just recommend to undo back instead of digging further. Make a minimal testcase as requested in issue template, with just minimal vimrc + coc.nvim + this colorscheme loaded, so that I can least reproduce the same easily on my side (either with vim or nvim). As of now I don't have correct reproduction instructions, so I can't do much at all.

**Comment by ayroblu** [comment]
Minimal test case `.vimrc-temp` using vim-plug:

```vimrc
set nocompatible

let mapleader=' '

call plug#begin('~/.vim/plugged')
Plug 'altercation/vim-colors-solarized'
autocmd BufReadPost <buffer> hi MatchParen cterm=bold,underline ctermbg=none ctermfg=red
autocmd VimEnter * ++nested silent! colorscheme solarized

Plug 'neoclide/coc.nvim', {'branch': 'release'}
let g:coc_global_extensions = [
      \'coc-tsserver'
      \]

call plug#end()

syntax enable

" Set color scheme
set background=light
```

My terminal is alacritty, which is just this config: https://github.com/ayroblu/dotfiles/blob/master/.alacritty.yml

And my project, which could be any typescript project, but I've been touching this one, make sure you have node and related tools already

```sh
git clone https://github.com/ayroblu/qmk-json-to-zmk
cd qmk-json-to-zmk
yarn
vi -u .vimrc-temp src/index.ts
```

Then add a function that isn't referenced, e.g.

```ts
function thing() {}
```

That is to my knowledge everything I have, let me know if I missed something

**Comment by ayroblu** [comment]
```sh
cd ~/.vim/plugged
mv coc.nvim{,.bak}
git clone git@github.com:neoclide/coc.nvim.git
cd coc.nvim
git checkout release

# verify it's broken

git checkout HEAD^

# verified it works
```

![image](https://user-images.githubusercontent.com/4915682/142744877-80a3c2e3-3241-4de8-9c40-b138e65b6aab.png)

**Comment by ayroblu** [comment]
Specifically, looks like it's here: https://github.com/neoclide/coc.nvim/commit/287c743c9f227fdf0e1db452bbb8ae3c5caffc36#diff-e8a53eb459c11e4f44c474b7d2ded76d2e57a245de816c7a770315c0de9a3932L334

**Comment by oblitum** [comment]
Thanks for the additional info, now yes I was able to reproduce it with Vim on my side. I'm using xfce4-terminal inside tmux, terminal emulator seems not relevant.

Indeed, it seems the bug comes from the dynamically generated highlighting, the generation seems to have some specific assumptions. This `FgCocInfoFloatBgCocFloating` is an self-evident composition of two highlighting groups, but as far as I've noticed, it indeed is generated at last instant, but the parts are not, so, what you need atm is to make bg of CocFloating different from fg of CocInfoFloat, then when this is generated, it'll have a different palette for that.

Now it's up to devs/contributors about what to do with this report, not sure whether this is worth a fix or not.

**Comment by oblitum** [comment]
Notice this only happens in specific "info" diagnostic float, it's because coc.nvim uses the same color of the diagnostic sign for the content of the float, but the diagnostic signs of this colorschemes have quite a strange looking, they have reversed background to the sign column (really ugly), that may explain why it ends up a mess with the floating popup, bc the logic for that is not expecting just one of bg or fg to be reverse colors, that gives a high chance of they annihilating when displaying, or becoming near invisible / very low contrast.

**Comment by oblitum** [comment]
This is how you correctly patch a colorscheme from your `.vimrc`:

```vim
autocmd VimEnter,ColorScheme * hi! link CocFloating CocHintFloat
```

Put that on your `.vimrc` and you'll notice floating will get different look. That's just a random change though, you should pick better link or custom color. Or simply a better colorscheme...

**Comment by ayroblu** [comment]
>  but the diagnostic signs of this colorscheme have quite a strange looking, they have reversed background to the sign column (really ugly), that may explain why it ends up a mess with the floating popup, bc the logic for that is not expecting just one of bg or fg to be reverse colors

So the issue is that original commit didn't factor in colorschemes with only one "reverse"? This seems like an easy fix

**Comment by ayroblu** [comment]
@oblitum You can checkout: #3477
