### ISSUE TITLE
I can't get these damn windows to change colors

### ISSUE THREAD

**Issue by ziidonato** [neoclide/coc.nvim#3478]
## Result from CocInfo

versions

vim version: NVIM v0.5.1
node version: v16.6.2
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /home/zii/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-11-21T17:51:30.573 INFO (pid:31511) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v16.6.2 after 33ms
2021-11-21T17:51:34.585 INFO (pid:31511) [attach] - receive notification: showInfo []

## Describe the bug

I can't get these colors to change no matter what I do. I've tried CocErrorHighlight, CocErrorFloat, and CocFloating but none of them work to change the color of the error window. changing Pmenu seems to do it, but I want different colors for different windows.

## Screenshots (optional)
![Screenshot_20211121_175627](https://user-images.githubusercontent.com/26052216/142782227-a3a6e09d-56d3-4649-bf32-7444c72e14cd.png)

**Comment by oblitum** [comment]
See https://github.com/neoclide/coc.nvim/issues/3473#issuecomment-974748337

**Comment by ziidonato** [comment]
> See [#3473 (comment)](https://github.com/neoclide/coc.nvim/issues/3473#issuecomment-974748337)

still not changing colors

**Comment by chemzqm** [comment]
`:h hl-PmenuSel`
