### ISSUE TITLE
What is the difference between coc and ale?

### ISSUE THREAD

**Issue by PendragonSaber** [neoclide/coc.nvim#348]
**Is your feature request related to a problem? Please describe.**

I am now coc and ale in use, I don't know how to choose now, they can be checked very well, I want to know the difference between coc and ale in inspection. How do I choose?

**Comment by chemzqm** [comment]
Why you need to choose? They can work together.

There is `coc.preferences.diagnostic.displayByAle` setting if you want ale to handle diagnostics.

**Comment by chemzqm** [comment]
Read https://github.com/neoclide/coc.nvim#why if you want to compare LSP features.

**Comment by Frydac** [comment]
From my perspective, as a relative new user of both ALE and coc (I use it for C++/Ruby/Python/VimL):
I think the lsp completion/goto is handled much better in coc: I especially like that it adds more sources than only the language servers (like adding symbols in open documents, which I don't think ALE supports), it has fuzzy search in the completion candidates (absolute must imo). Coming from youcompleteme there are some minor things I miss (though maybe because of my ignorance, or because the specific lsp server I'm using does not support it), but generally it feels very similar. And supports languagues like Ruby easily while I never succeeded to get proper ruby completion in youcompleteme (which atm does not support lsp).
ALE on the other hand has first class support for linters (not using lsp), which is not what coc aims at (afaik). And there are many, many linters available in ALE which do not support lsp.
I use both (ALE only in Ruby/Python though), and enjoy them very much :) And I didn't even know about the displayByAle option..

**Comment by PendragonSaber** [comment]
> Why you need to choose? They can work together.
>
There is `coc.preferences.diagnostic.displayByAle` setting if you want ale to handle diagnostics.
The emoji is the detection of ALE, and the detection of the unfinished statement mai is on the next line. Instead of which line is not completed, the COC does this very well. I am wondering if the grammar detection of COC can make me replace ale
![11](https://user-images.githubusercontent.com/41671631/51295225-92424300-1a51-11e9-8e01-2ead45aa78b3.png)

**Comment by PendragonSaber** [comment]
> From my perspective, as a relative new user of both ALE and coc (I use it for C++/Ruby/Python/VimL):
> I think the lsp completion/goto is handled much better in coc: I especially like that it adds more sources than only the language servers (like adding symbols in open documents, which I don't think ALE supports), it has fuzzy search in the completion candidates (absolute must imo). Coming from youcompleteme there are some minor things I miss (though maybe because of my ignorance, or because the specific lsp server I'm using does not support it), but generally it feels very similar, or better. And coc supports languagues like Ruby easily while I never succeeded to get proper ruby completion in youcompleteme (which atm does not support lsp).
> ALE on the other hand has first class support for linters (not using lsp), which is not what coc aims at (afaik). And there are many, many linters available in ALE which do not support lsp.
> I use both (ALE only in Ruby/Python though), and enjoy them very much :) And I didn't even know about the displayByAle option..


Thank you very much for your comments. I will consider it carefully.

**Comment by chemzqm** [comment]
>  I am wondering if the grammar detection of COC can make me replace ale

No, coc depending on diagnostics from language server, ale have more linters.

> Another question, warning that it should be silent, should not have any awareness

I can't understand.

> if I need to cancel some settings of my ale, let ale accept the coc send?

It should be on by default.

**Comment by PendragonSaber** [comment]
It should just warn me, instead of prompting me to `press enter to continue`, I have not encountered such a problem before, maybe what is the coc check? The default setting is that I don't need to set linter in ale?

**Comment by chemzqm** [comment]
>  instead of prompting me to press enter to continue

It's problem of your vim configuration, you should use `set cmdheight=2` `set shortmess=aFc` to avoid this kind of problem, that message is not from coc.

> The default setting is that I don't need to set linter in ale?

What do you mean? What default setting? Of cause you can use coc without ale.

**Comment by PendragonSaber** [comment]
另一个问题，我装了coc-neosnippet，它是基于Shougo/neosnippet的coc版本吗？还是它是一个中间件？安装coc-neosnippet之后我并没有得到任何的代码片段。

**Comment by chemzqm** [comment]
你自己研究吧，这里只解决 bug。

**Comment by PendragonSaber** [comment]
> 你自己研究吧，这里只解决 bug。

好吧 赵大佬。。很少看你在知乎活跃了。期待有个中文网啊。。

**Comment by jottr** [comment]
@taigacute @chemzqm please use English.

**Comment by Adityashaw** [comment]
> Read https://github.com/neoclide/coc.nvim#why if you want to compare LSP features.

This section seems to be missing.

**Comment by antony2025** [comment]
I believe it is a good idea to use both the plugins - Asynchronous Lint Engine (ALE) for it's linting functionality and Conqueror of Completion (coc.nvim) for its completion functionality.

See the ALE FAQ "How can I use ALE and coc.nvim together?" at https://github.com/dense-analysis/ale#faq-coc-nvim

It explains nicely that 
"If you want to run external programs on your files to check for errors, and also use the most advanced IDE features, you might want to use both plugins at the same time."
