### ISSUE TITLE
Highlight tokens that are marked as deprecated

### ISSUE THREAD

**Issue by TonalidadeHidrica** [neoclide/coc.nvim#3481]
Some language servers provides deprecation warnings only through semantic token's modifier.  It would be nice if such tokens are highlighted, such as drawing a strikethrough over them.

Reference: 
- https://github.com/neoclide/coc.nvim/issues/3188#issuecomment-974490202_ by @oblitum
- #3480

**Comment by oblitum** [comment]
Done on https://github.com/neoclide/coc.nvim/pull/3355#issuecomment-994508559.

Related https://github.com/neoclide/coc.nvim/pull/3188#issuecomment-994509178.

Not merged to master yet.

**Comment by chemzqm** [comment]
By default `CocSemDeprecated` would link to `TSStrike` and fallback to `CocDeprecatedHighlight`
