### ISSUE TITLE
gr feeze

### ISSUE THREAD

**Issue by zakalla** [neoclide/coc.nvim#3483]
Hello, thank you for your efforts firstly!
I use "PlugUpdate" to update the plug-in recently. When I use "gr" to choose one file, the CPU is full to 100%. I have to kill this process to continue. Wish to solve this problem. Thank you!

**Comment by fannheyward** [comment]
1. what's your `:CocInfo`?
2. what's language and language server do you use?
3. try minimal vimrc to reproduce this.

**Comment by zakalla** [comment]
I have solved the problem by upgrade nvim.
