### ISSUE TITLE
workspace/configuration support for dotted properties

### ISSUE THREAD

**Issue by charlespwd** [neoclide/coc.nvim#3486]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.1
node version: v17.0.1
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/charles/dotfiles/config/nvim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

## Irrelevant
```

## Describe the bug

Server->Client `workspace/configuration` requests do not support dotted properties in settings. I'm adding support for configurations to [Shopify/theme-check](/Shopify/theme-check) and it took me a while to figure out that this kind of configuration works:

```
  "languageserver": {
    "theme-check": {
      "command": "/Users/charles/bin/theme-check-language-server",
      "trace.server": "verbose",
      "filetypes": ["liquid", "liquid.html"],
      "rootPatterns": [".theme-check.yml", "snippets/*"],
      "settings": {
        "themeCheck": {
          "checkOnSave": true,
          "checkOnEnter": false,
          "checkOnChange": false
        }
      }
    }
```

But this doesn't:

```
  "languageserver": {
    "theme-check": {
      "command": "/Users/charles/bin/theme-check-language-server",
      "trace.server": "verbose",
      "filetypes": ["liquid", "liquid.html"],
      "rootPatterns": [".theme-check.yml", "snippets/*"],
      "settings": {
        "themeCheck.checkOnSave": true,
        "themeCheck.checkOnEnter": true,
        "themeCheck.checkOnChange": true
      }
    }
```

(And VS Code does supported properties set this way. Also all the coc.nvim config are all like this! In fact, I initially thought that those configs were supposed to live at the top level, but they did not work so I _eventually_ found the incantation that worked (the one without the dots in settings), but it wasn't entirely obvious how to get there. 

## Outputs from my server logs with the first config:

```
{
  "jsonrpc": "2.0",
  "method": "workspace/didChangeConfiguration",
  "params": {
    "settings": {
      "themeCheck": {
        "checkOnSave": true,
        "checkOnEnter": false,
        "checkOnChange": false
      }
    }
  }
}
{
  "id": 4,
  "method": "workspace/configuration",
  "params": {
    "items": [
      {
        "section": "themeCheck.checkOnEnter"
      },
      {
        "section": "themeCheck.checkOnSave"
      },
      {
        "section": "themeCheck.checkOnChange"
      }
    ]
  },
  "jsonrpc": "2.0"
}
{
  "jsonrpc": "2.0",
  "id": 4,
  "result": [
    false,
    true,
    false
  ]
}
```

Outputs from the dotted config:

```
{
  "jsonrpc": "2.0",
  "method": "workspace/didChangeConfiguration",
  "params": {
    "settings": {
      "themeCheck.checkOnSave": false,
      "themeCheck.checkOnChange": false,
      "themeCheck.checkOnEnter": false
    }
  }
}
{
  "id": 1,
  "method": "workspace/configuration",
  "params": {
    "items": [
      {
        "section": "themeCheck.checkOnEnter"
      },
      {
        "section": "themeCheck.checkOnSave"
      },
      {
        "section": "themeCheck.checkOnChange"
      }
    ]
  },
  "jsonrpc": "2.0"
}
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    null,
    null,
    null
  ]
}

```

**Comment by fannheyward** [comment]
How to trigger the `workspace/configuration` server -> client request?

**Comment by charlespwd** [comment]
The [PR is not merged yet](https://github.com/Shopify/theme-check/pull/511). So this is happening on unreleased code. 

The `workspace/configuration` request happens after a `workspace/didChangeConfiguration` client->server notification. Loosely based on how VS Code's language client sends that notification (they send it with settings: null).

So something like this:

![image](https://user-images.githubusercontent.com/4990691/143484604-cfb3d4f0-2147-4b53-bcfe-3f75b78153f2.png)

**Comment by fannheyward** [comment]
> And VS Code does supported properties set this way

I hadn't do a test for now, but from the source code, both coc.nvim and VSCode did the same logic: check whether dot in section, if not get configuration with the whole section, other wise get the first part and then last part.

https://github.com/neoclide/coc.nvim/blob/0480cbd9976529f69aeb692d8e1834d3edde90c5/src/language-client/configuration.ts#L54-L62

https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/configuration.ts#L48-L56

Will look into this later.
