### ISSUE TITLE
Conflict with clipboard=unnamed  on macOS

### ISSUE THREAD

**Issue by sys9kdr** [neoclide/coc.nvim#3488]
## Result from CocInfo

vim

```
## versions

vim version: VIM - Vi IMproved 8.2 8023455
node version: v17.0.1
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/ghnoda/.vim/dein/repos/github.com/neoclide/coc.nvim_release
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-11-27T14:33:01.311 INFO (pid:40260) [services] - registered service "languageserver.efm"
2021-11-27T14:33:01.729 INFO (pid:40260) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v17.0.1 after 606ms
2021-11-27T14:33:03.463 INFO (pid:40260) [attach] - receive notification: showInfo []

```

## Describe the bug

With .vimrc which has set clipboard=unnamed.
Execute CocInfo or CocList command would mess up the clipboard.

I found same issue #1136.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  set clipboard=unnamed
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

0. Copy some text to clipboard.
1. Run `:CocInfo` or `CocList`.
2. Clipboard is cleaerd.(I thougt `<CR>` is in)

**Comment by fannheyward** [comment]
Reproduced with vim, not nvim.
