### ISSUE TITLE
Dialog floatConfig

### ISSUE THREAD

**Issue by tibimunteanu** [neoclide/coc.nvim#3489]
Add dialog.floatConfig similar to signature.floatConfig, diagnostic.floatConfig, suggest.floatConfig, hover.floatConfig.
At the moment, there is no way to remove the dialog border, except for defining dialog.floatBorderHighlight and setting the color to match the background, but the dialog results in having more padding then if the border was actually disabled.

**Comment by chemzqm** [comment]
> there is no way to remove the dialog border

It's intended.

**Comment by chemzqm** [comment]
We will improve dialog for notifiation #2702
