### ISSUE TITLE
Disable coc.nvim per filetype (i.e. a filetype whitelist or blacklist)

### ISSUE THREAD

**Issue by mike-hearn** [neoclide/coc.nvim#349]
Hi folks, I'd like to propose a feature (or maybe it exists and I simply couldn't find how to invoke it).

I'd like to be able to enable/disable coc on a filetype-by-filetype basis.

**Why?** In my opinion, there are certain filetypes where YouCompleteMe handles completion better than than LSPs. But in most filetypes, coc is better. Ideally I'd like to use YouCompleteMe in the filetypes where it shines, and coc.nvim in other filetypes.

YouCompleteMe can already handle this with `g:ycm_filetype_whitelist` and `g:ycm_filetype_blacklist`, but I don't believe coc can do this.

There's also an alternative implementation, as seen in [ncm2](https://github.com/ncm2/ncm2), where you must `call ncm2#enable_for_buffer()`, which allows for `autocmd` entries on a filetype basis. This would also satisfy my feature request.

Is this feature already available in coc, or is it something that could possibly be implemented in the future?

Thank you!

**Comment by chemzqm** [comment]
It's designed to work with all your buffers, you can use plugin manager to load it on specific filetypes.

For enable/disable coc after plugin loaded ,use `:CocEnable` and `:CocDisable` commands.

**Comment by mike-hearn** [comment]
Ok, thank you for the guidance. I have something that seems to be working effectively:

Load coc.nvim on certain filetypes:
```vim
Plug 'neoclide/coc.nvim', {'tag': '*', 'do': 'yarn install', 'for': ['json', 'lua', 'vim', ]}
```

Blacklist those types for YCM:
```
let g:ycm_filetype_blacklist = {
            \ 'vim': 1,         
            \ 'lua': 1,         
            \ 'json': 1,        
            \ }
```

Enable on BufNew/BufEnter, disable on BufLeave:
```
autocmd BufNew,BufEnter *.json,*.vim,*.lua execute "silent! CocEnable"
autocmd BufLeave *.json,*.vim,*.lua execute "silent! CocDisable"
```

Closing. Thanks again.

**Comment by serussell** [comment]
Argh, don't close this!  Many of us are using something other than ... whatever you're using for plugins.  For example, I'm using the native vim package manager, and it's not clear how to have CoC *disabled* in every buffer *except* ones of a certain file type.

I don't want CoC to do anything with Markdown, but still want it to be enabled on Go files.  These are files in the same project and likely to be open in the same nvim instance.  Is the recommendation seriously that we add buffopen commands for every filetype for this behavior?

**Comment by ronakg** [comment]
I have a use-case where I want to disable CoC for diffs. The problem is, diff is a buffer type, not a file type. So this approach doesn't work.

**Comment by igor-dimi** [comment]
Is it possible to get the Language source in the completion list even if the file type is not appropriate?

E.g. I really want to have autocompletion for Latex formulas while I'm editing in Markdown. 
But even after manually activating the latex extension, auto-complete suggestion do not show up in the list? 

Is there any way to achieve this?

**Comment by oblitum** [comment]
@igor-dimi you can `:set ft=tex` temporarily, or setup a mapping for that.

**Comment by srearl** [comment]
Like others here, I am interested for CoC to be enabled only for certain file types. I attempted to address this with the `for` option in Plug (sensu `Plug 'neoclide/coc.nvim', {'branch': 'release', 'for': ['r', 'rmd']} )` but I get the following error when opening nvim.

```Error detected while processing CursorHold Autocommands for "*":```
```E117: Unknown function: CocActionAsync```

I get the same results even with the `autocmd` suggestions that @mike-hearn added.

For the time being, I will just disable CoC for all files (`autocmd BufNew,BufRead * execute "CocDisable"`) and enable manually with `CocEnable` when needed, but that is not ideal so any help or suggestions would be appreciated. Thanks!

**Comment by drk-mtr** [comment]
Thanks for the great plugin.

Being able to disable by default but whitelist certain filetypes would be top of my list in terms of feature requests too.

Getting coc.nvim and deoplete to play nice together is mind bending and I feel this would make it easier.

**Comment by omercsp** [comment]
If that helps anyone, this is how I did it:

```vim
let g:my_coc_file_types = ['c', 'cpp', 'h', 'asm', 'hpp', 'vim', 'sh', 'py']

function! s:disable_coc_for_type()
	if index(g:my_coc_file_types, &filetype) == -1
	        let b:coc_enabled = 0
	endif
endfunction
```
This way you don't disable/enable coc for entire vim sessions, but for buffers, so you can have one buffer with coc disabled and one where it is enabled.

**Comment by hl037** [comment]
Still marked as closed, but none of the previous solution works with jedi python :

When editing a python file (with pure vim-jedi) and another file (using coc), coc still throw : "[coc.nvim]: Some plugin change completeopt on insert mode: Modifié la dernière fois dans ~/.cache/vim/plugged/jedi-vim/autoload/jedi.vim line 690!"

**Comment by hl037** [comment]
My contribution (that fixed all my cases) (inspired by @omercsp ):
```
function! s:disable_coc_for_type()
  if index(g:coc_filetypes_enable, &filetype) == -1
    :silent! CocDisable
  else
    :silent! CocEnable
  endif
endfunction

augroup CocGroup
 autocmd!
 autocmd BufNew,BufEnter,BufAdd,BufCreate * call s:disable_coc_for_type()
augroup end
```
and somewhere in the vimrc, let a:
```
let g:coc_filetypes_enable = [ 'c', 'cpp' ...]
```
Containing a list of file types on which coc is enabled. You can reuse this list in the `for` key of Plug (or similar), to load coc only when necessary. The `silent!` permits to mask the error on :CocEnable/Disable not defined if coc has not been loaded at all.

...Each time you are entering a buffer, the check is made, and coc should be enabled/disabled automatically. Even if untested, it should also work with diffs...

**Comment by z0xyz** [comment]
Either alter 

> ```viml
> 	if index(g:my_coc_file_types, &filetype) == -1
> ```

The variable prefix should be altered from `g` should be altered to `s`, as it results in `Undefined variable g:my_coc_file_types` error

**Comment by z0xyz** [comment]
> 	if index(g:my_coc_file_types, &filetype) == -1

The variable prefix should be altered from `g` to `s` or vice versa, or even confined to the function itself, as it results in `Undefined variable g:my_coc_file_types` error

> let s:my_coc_file_types = ['c', 'cpp', 'h', 'asm', 'hpp', 'vim', 'sh', 'py']

The file type for `python` is `python` for vim, so with this `py` list item won't be detected as a valid python file, hence python files would get `coc` disabled for them. you can alternatively provide vim's preset file type. However i found it limiting, as `hpp` and `h` files were detected as being of `cpp` file type too . Instead, If you can rely on file extension check with `filename-modifiers` using  `if index(s:my_coc_file_types, expand('%:e')) == -1`

>  autocmd BufNew,BufEnter * call s:disable_coc_for_type()

Also having the `BufRead` event, would require less computational overhead, in contrast to `BufEnter` which would fire up each time you switch buffers to re-set the same already pre-set option .

Ultimately that's how it 'should' -as far as i can understand' be redefined
```vim
function! s:disable_coc_for_type()
        let l:my_coc_file_types = ['c', 'cpp', 'h', 'asm', 'hpp', 'vim', 'sh', 'py']
	if index(l:my_coc_file_types, expand('%:e')) == -1
		let b:coc_enabled = 0
	endif
endfunction
autocmd BufRead,BufNewFile * call s:disable_coc_for_type()
```

**Comment by kiteloopdesign** [comment]
Agree with @z0xyz above, I was also having same issues as him. Except that I prefer to whitelist (at least while I get used to all this extra info I am not used to). In this case you should do:

```
function! s:enable_coc_for_type()
        let l:filesuffix_whitelist = ['c', 'cpp', 'h', 'asm', 'hpp', 'vim', 'sh', 'py']
	if index(l:filesuffix_whitelist, expand('%:e')) == -1
		let b:coc_enabled = 0
	endif
endfunction
autocmd BufRead,BufNewFile * call s:enable_coc_for_type()
```
I can see how this plugin has for sure taken a lot of work to his creator, and I thank him for it, but, after reading several issues, I have to say that disabling a plugin should be really a no-brainer, and well explained on first lines of main doc page. Unfortunately I can't spend hours reading and debugging all the really detailed options this plugin has

**Comment by NullVoxPopuli** [comment]
how do you disable coc-tsserver for just a particular filetype? like maybe I want `typescript.jsx` to not use use tsserver, for example

**Comment by tan-wei** [comment]
I see many useful advices here. Thanks everyone.

**Comment by GianniGi** [comment]
Sorry to resurrect the thread. I see a lot of advices here.

I need to disable coc for all files and all buffers, and enable only it only in python files. What's the best way among the ten different ones? 

probably this?
[https://github.com/neoclide/coc.nvim/issues/349#issuecomment-850799867](by @hl037)
