### ISSUE TITLE
How to resize coc-references  window?  It's to small for me

### ISSUE THREAD

**Issue by zsj0613** [neoclide/coc.nvim#3493]
![image](https://user-images.githubusercontent.com/13030577/144178136-0e51b690-6ca5-4d88-af3b-a077e1b626c1.png)

I want the coc-references  window full screen?   somebody know how to do 

thanks !

**Comment by zsj0613** [comment]
or  just resize it bigger

**Comment by zsj0613** [comment]
Finaly  ,I got the answer

`diff --git a/data/schema.json b/data/schema.json
index 48dc97e..b4c0100 100644
--- a/data/schema.json
+++ b/data/schema.json
@@ -959,7 +959,7 @@
     },
     "list.height": {
       "type": "number",
-      "default": 10,
+      "default": 20,
       "description": "Height of split list window."
     },
     "list.statusLineSegments": {
@@ -999,7 +999,7 @@
     },
     "list.maxPreviewHeight": {
       "type": "number",
-      "default": 12,
+      "default": 22,
       "description": "Max height for preview window of list."
     },
     "list.previewSplitRight": {
`

**Comment by fannheyward** [comment]
You don't need to change the `data/schema.json` file, you can set `list.height` in your coc-settings.json

**Comment by zsj0613** [comment]
> You don't need to change the `data/schema.json` file, you can set `list.height` in your coc-settings.json

thanks bro!
