### ISSUE TITLE
Coc-html doesn't work in windows

### ISSUE THREAD

**Issue by JEHH1828** [neoclide/coc.nvim#3495]
I've installed coc correctly but if I want used it, the intellisense doesn't work.
I checked the plugins with ` :CocList` after that "extensios" and the coc-html looks like that

![WindowsTerminal_ommcVl3ZJf](https://user-images.githubusercontent.com/70662351/144311522-73de37fb-b533-4db1-b462-d283c23f4081.png)

**Comment by fannheyward** [comment]
Check the coc-html trace logs please: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by JEHH1828** [comment]
@fannheyward  it's done, thanks
