### ISSUE TITLE
Error in example vim configuration

### ISSUE THREAD

**Issue by dev7ba** [neoclide/coc.nvim#3496]
You have an error in the vim example configuration: 
This line:

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

Should be:
" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocActionAsync('runCommand', 'editor.action.organizeImport')

You have to call CocActionAsync because in case an import could have more than one posibility, a float window appears, and you can't select nothing because it's not Async!!!

**Comment by fannheyward** [comment]
PR is welcome.

**Comment by dev7ba** [comment]
PR is on #3499
