### ISSUE TITLE
gi, gy, gd, br not working as expected for c++ on Ubuntu 21.04

### ISSUE THREAD

**Issue by amandeepgautam** [neoclide/coc.nvim#3497]
I am running Ubuntu 21.04.
Have generated compile_commands.json using https://github.com/grailbio/bazel-compilation-database and it looks alright. My project is in c++ and I have clangd running.

There are a few issues that I am facing:

**On gd**
It seems to go to the header file declaration instead of the definition.

**On gy:**
[coc.nvim]: Error on "jumpTypeDefinition": typeDefinition provider not found for current buffer, your language server doesn't support it.

**On gi**
[coc.nvim] implementation not found

**On gr**
It only gives usages in the same file and not the whole repo.

**Comment by fannheyward** [comment]
Try minimal vimrc.

**Comment by fannheyward** [comment]
clangd's issue: https://github.com/clangd/clangd/issues/854, https://github.com/clangd/clangd/issues/367

**Comment by amandeepgautam** [comment]
@fannheyward I understand that gi and gy could clangd's issue.
why does **gd** not go to the definition but to the header?
Also, why does **gr** only show usage in the same file?

Can you answer those as well?

**Comment by darzok0914** [comment]
I'm having some issues that I didn't use to have with go to definition using coc and clangd. 
I'm using neovim 0.6.0 it might be related. 

basically when I use gd it seems like it doesn't jump to the right location, in general it will jump to the right location + a random offset
for example, doing a gd on test 
![image](https://user-images.githubusercontent.com/72544332/144765701-f2d25a2a-1611-4edb-a01f-d79aed011a17.png)

will bring here:
![image](https://user-images.githubusercontent.com/72544332/144765684-1e326b3a-49a7-455f-a4ee-d7ab8015c912.png)

instead of line 43, the problem is that it is hard to reproduce because it is really random, it works 60 % of the time and then without reason stop working well.

**Comment by darzok0914** [comment]
I just downgraded to nvim 0.5.1 and I still have the same issue so I don"t think it is a neovim issue.

**Comment by darzok0914** [comment]
so it seems like I can reproduce the bug consistently:


this is how I can reproduce the bug: 

1) I go to where the definition is 

![image](https://user-images.githubusercontent.com/72544332/144767487-f2e7dc9b-5aa4-4385-97f8-9b9b8fd40b10.png)

2) then I go to where this is used in the code (another file) 
![image](https://user-images.githubusercontent.com/72544332/144767500-8c68bdd9-53e1-40aa-a454-9ff47c1a875c.png)

3) I do gd and it works, it does jump to the definition
![image](https://user-images.githubusercontent.com/72544332/144767541-3e1e1b6f-cc66-4a29-b5ee-e74a1dd29047.png)

4) now in that same file, I go to the bottom of the file, as you can see it is line 755 so we cannot see the definition anymore
![image](https://user-images.githubusercontent.com/72544332/144767583-d28339d4-d189-4dae-9bc5-d8b98e1f0d7d.png)

5) I go back to the previous file where this was used in the code 
![image](https://user-images.githubusercontent.com/72544332/144767608-b0e8d219-16e8-4fa4-b701-746f3037ecd9.png)

6) I do a gd again and this time it jumps to the right file but not the right line
![image](https://user-images.githubusercontent.com/72544332/144767628-0c54ea45-3807-491e-b9fa-b77da94f839b.png)
 
as you can see it jumps to the top of the screen line 694. if I set the cursor back to the bottom of the file and try gd again and again it keeps going to the same line. However if I leave it to line 694 and then go back to the previous file and do a gd it will jump up to line 668, if I go back and to a gd it will jump to line 642 and so on until it actually finds the right location.

**Comment by cambp4** [comment]
it was actually a bug coming from another plugin called scrollview
