### ISSUE TITLE
msys/mingw install not working

### ISSUE THREAD

**Issue by dm19** [neoclide/coc.nvim#350]
**Result from CocInfo**
See below

**Describe the bug**
CocInfo and other commands missing after installing with vim-plug. Only available commands are: CocConfig CocInstall CocRebuild CocRestart CocUpdate

I'm trying to use ccls (which works with emacs lsp-mode on same computer), but ccls is not starting and extensions can be downloaded but also do not appear to run. 
Only error I can find:
```
cat /tmp/vim-node-rpc.log
2019-01-16T17:44:42.976 ERROR (pid:9100) [server] - socket error:  listen EACCES C:/msys64/tmp/vUuFAiL/1
```

**To Reproduce**
Up to date msys2 and mingw64
```
node--version v8.11.1
yarn --version 1.13.0
which vim-node-rpc /c/Users/[name]/AppData/Local/Yarn/bin/vim-node-rpc
vim --version Vi IMproved 8.1
```

.vimrc
```
call plug#begin('~/.vim/plugged')
 . . .
Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}
. . . 
call plug#end()
```
coc-settings.json
~/.vimrc  ~/.v/coc-settings.json                                              buffers
```
{
  "ccls": {
    "command": "ccls",
    "filetypes": ["c", "cpp", "objc", "objcpp", "cc"],
    "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
    "initializationOptions": {
      "cacheDirectory": "/tmp/ccls"
    }
  }
}
```

**Comment by dm19** [comment]
That returns `0`. `:echo has("unix")` returns `1` (I'm using vim installed with msys rather than vim downloaded for Windows. 

I went home last and got the same result as above on my Arch Linux install, but then I realized nodejs was not installed, which solved the problem.  Could using msys vim and mingw node be causing issues with the two working together?

**Comment by chemzqm** [comment]
What does `node -e 'console.log(process.platform)'` gives on that environment?

The socket address on windows should prefixed with `\\?\pipe\`

**Comment by dm19** [comment]
`win32`

It does looks like the issue is the msys vim. I just downloaded the vim self-installing executable for Windows, ran it from the msys/mingw shell and everything worked.

**Comment by chemzqm** [comment]
> . I just downloaded the vim self-installing executable for Windows

It should have `has("win32") || has("win64")` to be 1.

**Comment by dm19** [comment]
I don't know if it works here, but it looks like uname is the standard way for linuxy programs to detect if they're running on msys

```
$ uname -sm
MSYS_NT-6.1 x86_64
```
