### ISSUE TITLE
Compilation Error Box Showing up for Split Second 

### ISSUE THREAD

**Issue by GRMInteractive** [neoclide/coc.nvim#3500]
## versions

vim version: NVIM v0.5.1
node version: v15.14.0
coc.nvim version: 0.0.80-cf0e8400a4
coc.nvim directory: /home/trdat/.vim/plugged/coc.nvim
term: undefined
platform: linux

## Log of coc.nvim

2021-12-05T08:55:17.473 INFO (pid:34355) [plugin] - coc.nvim 0.0.80-cf0e8400a4 initialized with node: v15.14.0 after 468ms
2021-12-05T08:55:23.832 INFO (pid:34355) [attach] - receive notification: highlight []
2021-12-05T08:55:59.816 INFO (pid:34355) [attach] - receive notification: highlight []
2021-12-05T08:58:51.336 INFO (pid:34355) [attach] - receive notification: highlight []
2021-12-05T08:58:57.135 INFO (pid:34355) [attach] - receive notification: highlight []
2021-12-05T08:59:05.070 INFO (pid:34355) [attach] - receive request: CocAutocmd [ 'BufWritePre', 1 ]
2021-12-05T08:59:25.268 INFO (pid:34355) [attach] - receive notification: highlight []
2021-12-05T08:59:52.040 INFO (pid:34355) [attach] - receive notification: highlight []
2021-12-05T09:00:09.360 INFO (pid:34355) [attach] - receive notification: highlight []
2021-12-05T09:00:28.059 INFO (pid:34355) [attach] - receive notification: highlight []
2021-12-05T09:01:55.439 INFO (pid:34355) [attach] - receive notification: highlight []
2021-12-05T09:03:27.320 INFO (pid:34355) [attach] - receive notification: highlight []
2021-12-05T09:04:06.072 INFO (pid:34355) [attach] - receive notification: showInfo []

## Describe the bug

With my current vimrc, compilation errors show up in a box upon hovering on the highlighted area, but suddenly this stopped working and now they only show up for a split second and this is making things difficult. I put the vimrc bellow, I don't know what is wrong. 

## Reproduce the bug
call plug#begin("~/.vim/plugged")
Plug 'dracula/vim'
Plug 'scrooloose/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
let g:coc_global_extensions = ['coc-emmet', 'coc-css', 'coc-html', 'coc-json', 'coc-prettier', 'coc-tsserver', 'coc-pyright', 'coc-java', 'coc-phpls', 'coc-clangd', 'coc-snippets']
" Plugin Section
call plug#end()
"Config Section
if (has("termguicolors"))
	set termguicolors
endif

set mouse=a
syntax enable
colorscheme dracula
set number
set backup
set undofile
set backupdir=/home/trdat/Documents/vimtmp//
set directory=/home/trdat/Documents/vimtmp//
set undodir=/home/trdat/Documents/vimtmp//

let g:NERDTreeShowHidden = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeIgnore = []
let g:NERDTreeStatusline = ''
" Automaticaly close nvim if NERDTree is only thing left open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" Toggle
nnoremap <silent> <C-b> :NERDTreeToggle<CR>

" open new split panes to right and below
set splitright
set splitbelow
" turn terminal to normal mode with escape
tnoremap <Esc> <C-\><C-n>
" start terminal in insert mode
au BufEnter * if &buftype == 'terminal' | :startinsert | endif
" open terminal on ctrl+n
function! OpenTerminal()
	split term://bash
	resize 10
endfunction
nnoremap <c-n> :call OpenTerminal()<CR>

" use alt+hjkl to move between split/vsplit panels
tnoremap <A-h> <C-\><C-n><C-w>h
tnoremap <A-j> <C-\><C-n><C-w>j
tnoremap <A-k> <C-\><C-n><C-w>k
tnoremap <A-l> <C-\><C-n><C-w>l
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l

nnoremap <C-p> :FZF<CR>
let g:fzf_action ={
			\ 'ctrl-t': 'tab split',
			\ 'ctrl-s': 'split',
			\ 'ctrl-v': 'vsplit'
			\}

let $FZF_DEFAULT_COMMAND = 'ag -g ""'

"PHP UNTILL LINE 230
if executable('intelephense')
	augroup LspPHPIntelephense
		au!
		au User lsp_setup call lsp#register_server({
					\ 'name': 'intelephense',
					\ 'cmd': {server_info->[&shell, &shellcmdflag, 'intelephense --stdio']},
					\ 'whitelist': ['php'],
					\ 'initialization_options': {'storagePath': '/tmp/intelephense'},
					\ 'workspace_config': {
					\   'intelephense': {
					\     'files': {
					\       'maxSize': 1000000,
					\       'associations': ['*.php', '*.phtml'],
					\       'exclude': [],
					\     },
					\     'completion': {
					\       'insertUseDeclaration': v:true,
					\       'fullyQualifyGlobalConstantsAndFunctions': v:false,
					\       'triggerParameterHints': v:true,
					\       'maxItems': 100,
					\     },
					\     'format': {
					\       'enable': v:true
					\     },
					\   },
					\ }
					\})
	augroup END
endif

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
			\ pumvisible() ? "\<C-n>" :
			\ <SID>check_back_space() ? "\<TAB>" :
			\ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
	let col = col('.') - 1
	return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
" <cr> could be remapped by other vim plugin, try `:verbose imap <CR>`.
if exists('*complete_info')
	inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
else
	inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif

" Use `[g` and `]g` to navigate diagnostics
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
	if (index(['vim','help'], &filetype) >= 0)
		execute 'h '.expand('<cword>')
	else
		call CocAction('doHover')
	endif
endfunctionpopup 

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
	autocmd!
	" Setup formatexpr specified filetype(s).
	autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
	" Update signature help on jump placeholder.
	autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current line.
nmap <leader>ac  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Introduce function text object
" NOTE: Requires 'textDocument.documentSymbol' support from the language server.
xmap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap if <Plug>(coc-funcobj-i)
omap af <Plug>(coc-funcobj-a)

" Use <TAB> for selections ranges.
" NOTE: Requires 'textDocument/selectionRange' support from the language server.
" coc-tsserver, coc-python are the examples of servers that support it.
nmap <silent> <TAB> <Plug>(coc-range-select)
xmap <silent> <TAB> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

" Mappings using CoCList:
" Show all diagnostics.
nnoremap <silent> <space>a  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
nnoremap <silent> <space>p  :<C-u>CocListResume<CR>

Error:
![Screenshot_2021-12-05_09-09-38](https://user-images.githubusercontent.com/50970786/144750007-c8ae2502-e466-4d56-a3f8-2df0288cd700.png)
Usually a box with red text in it shows up and explains the error. Now it either doesn't show up or shows up for less then a second and it's unreadable. Really making it harder to program for me.

**Comment by fannheyward** [comment]
1. upgrade your coc.nvim, `0.0.80-cf0e8400a4` is an old release
2. try minimal vimrc
