### ISSUE TITLE
coc executes npm from the cwd which can result in npmrc files being applied

### ISSUE THREAD

**Issue by 43081j** [neoclide/coc.nvim#3503]
## Result from CocInfo

```md
## versions

vim version: VIM - Vi IMproved 8.2 8022300
node version: v17.1.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /vim/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-12-07T14:03:15.262 INFO (pid:40427) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v17.1.0 after 68ms
2021-12-07T14:03:18.014 INFO (pid:40427) [attach] - receive notification: showInfo []
```

## Describe the bug

If you execute something like `CocInstall` inside a directory which has an `.npmrc`, the npm process it launches will apply that config.

This means if you're working in a repo which has private registries setup, you cannot install coc extensions without first moving out of that directory (as you'll either get a 404 or a 401).

Maybe it should execute npm with the cwd as `~` or wherever coc's files live instead?

## Reproduce the bug

* Create a directory which has an `.npmrc` specifying the `registry` (e.g. `registry=wherever`)
* Open vim in that directory
* `CocInstall` something
* Observe that it will try install from the private registry

**Comment by fannheyward** [comment]
Reproduced.

**Comment by fannheyward** [comment]
The reason: coc.nvim will get npm registry by `rc`, used to fetch package info.
