### ISSUE TITLE
Enable ALE for specific filetype?

### ISSUE THREAD

**Issue by yetrun** [neoclide/coc.nvim#3504]
Nowdays I could set `"diagnostic.displayByAle": true` and `let g:ale_disable_lsp = 1` to disable diagnostic in coc.nvim and enable it in ale. However, it is a global setting, which is too radical for me now because I am using coc.nvim to take over all linting tasks. Now I am looking for bash linter and find `shellcheck` is fit to me, is there any way to enable ALE linter only with shell filetype?

**Comment by fannheyward** [comment]
1. `"diagnostic.displayByAle": true` will not disable diagnostics in coc.nvim
2. you can use https://github.com/iamcco/coc-diagnostic to bring `shellcheck` to coc.nvim

**Comment by kubil6y** [comment]
im using omnisharp-vim and ale + coc for c#. typescript and go seems to work fine like used to. its just diagnosis with ale. im curious is there too much performance hit?
