### ISSUE TITLE
Neovim version not satisfied

### ISSUE THREAD

**Issue by Richardspacejunkie** [neoclide/coc.nvim#3506]
So the issue is i wanted to use COC for nvim in a debian subsystem for windows and i couldnt find a solution to my problem. I have tried updating my nvim but coc still doesnt work i get 0 functionallity from it please help i can give these 2 screenshots
![nvim_checkhealth](https://user-images.githubusercontent.com/89737904/145650659-69889366-9fb6-43ff-bc8f-300459e5c505.PNG)
![nvim_messages](https://user-images.githubusercontent.com/89737904/145650661-cb83c5f6-1e58-4b6b-a9f3-87e1c93041e1.PNG)

**Comment by fannheyward** [comment]
1. what's your `:CocInfo`?
2. the second screenshot is not related to coc.nvim.

**Comment by chemzqm** [comment]
Check your nvim's version by `:version`, could be duplicated issue of #3388
