### ISSUE TITLE
Project wide next/prev diagnostic

### ISSUE THREAD

**Issue by NikosEfthias** [neoclide/coc.nvim#3507]
**Is your feature request related to a problem? Please describe.**
I need to open a terminal and see errors/warnings in my project then come back to vim and navigate manually to those files 

**Describe the solution you'd like**
I would like (coc-diagnostic-next/prev) commands to navigate project wide rather than finding problems only in the current file.
Much like vscode find next problem feature.
**Describe alternatives you've considered**
Having ability to run check command and load output to quickfix so using vim's native quickfix functionality would do the jumping.

**Comment by fannheyward** [comment]
You can use `:CocList diagnostics` to list workspace diagnostics, jump from the list view. You can also use https://github.com/kevinhwang91/nvim-bqf#integrate-with-other-plugins to output the diagnostics to quickfix.

**Comment by bikbah** [comment]
+1

it would be super handy feature without any other integrations

**Comment by chemzqm** [comment]
There is `:CocPrev` and `:CocNext`

**Comment by bikbah** [comment]
I guess before `:CocNext` / `CocPrev` it's required to invoke specific type of list, `CocList diagnostics`, `CocList symbols`
