### ISSUE TITLE
coc.nvim conflicts with fzf.vim

### ISSUE THREAD

**Issue by blackheaven** [neoclide/coc.nvim#3508]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8023451
node version: v14.18.1
coc.nvim version: 0.0.80-0219acc58d
coc.nvim directory: /home/black/.vim/bundle/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2021-12-13T11:59:14.139 INFO (pid:118660) [services] - registered service "languageserver.haskell"
2021-12-13T11:59:14.194 INFO (pid:118660) [coc-git] - Looking for git in: git
2021-12-13T11:59:14.202 INFO (pid:118660) [services] - registered service "highlight"
2021-12-13T11:59:14.216 INFO (pid:118660) [plugin] - coc.nvim 0.0.80-0219acc58d initialized with node: v14.18.1 after 123ms
2021-12-13T11:59:24.428 INFO (pid:118660) [attach] - receive notification: showInfo []
```

## Describe the bug

When I use fzf.nvim with coc.vim, arrowkeys are closing the fzf preview.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'neoclide/coc.nvim', {'branch': 'release'}
Plugin 'junegunn/fzf', {'rtp':  '~/.fzf' }
Plugin 'junegunn/fzf.vim'
call vundle#end()
filetype plugin indent on
syntax on
set hidden

" fzf
nnoremap <C-t> :Files<cr>
```

### Steps

1. Open vim in a folder with multiple files
2. Open the fzf preview window (`<C-t>` or `:Files`)
3. Types some characters to have at least 2 file
4. Press `<Up>`

The window is closed, instead of selecting the item above.

(I have the same behaviour with `<Left>`, `<Right>`, and `<Down>`)

**Comment by fannheyward** [comment]
<img width="654" alt="截屏2021-12-14 上午10 29 05" src="https://user-images.githubusercontent.com/345274/145922051-7eb99613-76b5-4326-a34e-74a11c9d08db.png">

Tested with latest coc.nvim and fzf.vim, can't reproduce, `<up>` works as expected.

**Comment by blackheaven** [comment]
What's your ViM/fzf version?

**Comment by blackheaven** [comment]
I get it, it's an extension

**Comment by blackheaven** [comment]
It was `coc-fzf-preview`

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#coclist-is-broken-when-holding-up-or-down-on-vim, my suggestion is avoid holding `<up>` and `<down>`
