### ISSUE TITLE
[coc-rename] confirm popup is unclickable

### ISSUE THREAD

**Issue by dotennin** [neoclide/coc.nvim#3509]
## Result from CocInfo
```
## versions

vim version: NVIM v0.6.0
node version: v14.13.1
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/dotennin-mac/.cache/dein/repos/github.com/neoclide/coc.nvim_release
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-12-14T01:19:11.328 INFO (pid:56781) [services] - registered service "highlight"
2021-12-14T01:19:11.710 INFO (pid:56781) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v14.13.1 after 446ms
2021-12-14T01:19:14.247 INFO (pid:56781) [attach] - receive notification: showInfo []
```

## Describe the bug

Unable to focus on the popup confirm window,  I can't press `y` to confirm, and I can't close the popup window.
It pops up a confirmation of the corresponding number of files If I use `coc-rename` to rename the function name

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=~/.config/nvim/init.vim
filetype plugin indent on
syntax on
set hidden
let mapleader = "\<Space>"
```

- Operate nvim.
- Open the typescript file
- rename the function name with `leader + r + n`
```vim
nmap <leader>rn <Plug>(coc-rename)
```
- Shows up the popup but no way to press `y` to confirm or click

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/18552970/145842451-a0f4c4e8-9196-4d72-b6cb-a404c5685841.png)Unable to focus on hover window

**Comment by fannheyward** [comment]
When the popup shows, press `y` did nothing for you? In my tests, pressed `y` will change all related files, and you need to `:wa` to save all.

**Comment by chemzqm** [comment]
No need to focus that window, just press `y` or `n`
