### ISSUE TITLE
Custom language server commands

### ISSUE THREAD

**Issue by alexeygolev** [neoclide/coc.nvim#351]
Reason lsp provides custom commands such as [this one](https://github.com/jaredly/reason-language-server/blob/d64a4ceca3bb720e5d7a5b0ecb059e3bb8b91c41/src/lsp/MessageHandlers.re#L672). Is there a way to call it? I tried `CocCommand` and `:call CocAction('runCommand', 'reason-language-server.showAst)` but it just gives me a "Command doesn't exist" error.

The rest of the functionality works with reason language server so my setup seems to be ok

**Comment by chemzqm** [comment]
Use `:CocCommand <tab>` to list exists commands, if client doesn't regist command to client, you can't use it by `:CocCommand`, then you have to use `CocRequest()` or `CocRequestAsync()` https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand

**Comment by alexeygolev** [comment]
Works like a charm, thank you!
