### ISSUE TITLE
Auto scroll  functionality when opening Output buffer 

### ISSUE THREAD

**Issue by aimen08** [neoclide/coc.nvim#3525]
when opening output buffer with `workspace.showOutput` i always find myself manually scrolling to EOF when the buffer change .

btw i saw old answer about using `bufenter autocmd` but can't figure out how , since output filetype is unknown.

**Comment by chemzqm** [comment]
It has `filetype` as `log`, you can use match the path pattern `output:///*`

**Comment by aimen08** [comment]
okay thank you 
`au BufEnter output:///* normal G`  did the trick .
after reading the docs , i replaced `BufEnter` with `TextChanged` event since it seems more what i was looking for .
