### ISSUE TITLE
coc#add_extension() can cause "Too Many arguments" error

### ISSUE THREAD

**Issue by docwhat** [neoclide/coc.nvim#353]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

**Describe the bug**
Given this vim script:

```viml
let s:coc_extensions = [
      \  'coc-css',
      \  'coc-emmet',
      \  'coc-highlight',
      \  'coc-html',
      \  'coc-dictionary',
      \  'coc-emoji',
      \  'coc-omni',
      \  'coc-tag',
      \  'coc-pairs',
      \  'coc-java',
      \  'coc-json',
      \  'coc-pyls',
      \  'coc-rls',
      \  'coc-snippets',
      \  'coc-solargraph',
      \  'coc-yaml',
      \  'coc-eslint',
      \  'coc-jest',
      \  'coc-prettier',
      \  'coc-tslint',
      \  'coc-tsserver',
      \ ]


call coc#add_extension(join(get(s:, 'coc_extensions', [])))
```

It causes these messages:

```
extension coc-css coc-emmet coc-highlight coc-html coc-dictionary coc-emoji coc-omni coc-tag coc-pairs coc-java coc-json coc-pyls coc-rls coc-snippets coc-solar
graph coc-yaml coc-eslint coc-jest coc-prettier coc-tslint coc-tsserver installed!
Error detected while processing function <lambda>6[1]..<SNR>77_OnExit[6]..<lambda>5[1]..<SNR>77_OnExtensionInstalled[3]..coc#rpc#notify[2]..<SNR>78_notify:
line    7:
E699: Too many arguments
Press ENTER or type command to continue
```

**To Reproduce**

1. Add the above vim script to your `.vimrc` to run after the plugins are installed.

**Comment by chemzqm** [comment]
I don't know what's wrong with your vim, just tried to fix it.
Paste `:CocInfo` if the problem still exists.

**Comment by docwhat** [comment]
```
## versions

vim version: NVIM v0.3.4
node version: v10.14.1
coc.nvim version: 0.0.46
term: tmux-256color
platform: darwin

## Error messages

```

After digging in a bit it looks like it blows up in `coc#rpc#notify(method, args)`.

It is called with `method = 'CocInstalled'` and the `args` are:

1. `coc-css`
1. `coc-emmet`
1. `coc-highlight`
1. `coc-html`
1. `coc-dictionary`
1. `coc-emoji`
1. `coc-omni`
1. `coc-tag`
1. `coc-pairs`
1. `coc-java`
1. `coc-json`
1. `coc-pyls`
1. `coc-rls`
1. `coc-snippets`
1. `coc-solargraph`
1. `coc-yaml`
1. `coc-eslint`
1. `coc-jest`
1. `coc-prettier`
1. `coc-tslint`
1. `coc-tsserver`

Note that 21 is 1 more than is allow by neovim/vim for its varargs (`...`):

> From `:h function-argument`:
>
> Up to 20 arguments can be given, separated by commas.  After the named
arguments an argument `...` can be specified, which means that more arguments
may optionally be following. 

It looks like `cos#util#install_extension(names)` is calling `coc#rpc#notify()` via the `s:OnExtensionInstalled(status, names)` function.

I can't think of a way, off hand, to modify this to send the args in chunks of 15 or so using VimL. :-/

**Comment by docwhat** [comment]
@chemzqm Okay, I figured it out. See PR #356 

I hope I formatted the commit message correctly. 😃

**Comment by docwhat** [comment]
PR #356 actually made it worse.

- `call coc#add_extension(join(get(s:, 'coc_extensions', [])))` causes the "Too Many arguments" problem again.
- `call coc#add_extension(get(s:, 'coc_extensions', []))` causes:

    ```
    extension coc-css,coc-emmet,coc-highlight,coc-html,coc-dictionary,coc-emoji,coc-omni,coc-tag,coc-pairs,coc-java,coc-json,coc-pyls,coc-rls,coc-snippets,coc-solargraph,coc-yaml,coc-eslint,coc-jest,coc-prettier,coc-tslint,coc-tsserver install failed!
    ```
- `call coc#add_extension([s:coc_extensions])` causes the same error as above.

**Comment by chemzqm** [comment]
I've fixed thus by pass string

**Comment by ahmedelgabri** [comment]
What is the difference between `coc#add_extension` & `coc#install_extension`?

**Comment by chemzqm** [comment]
add_extension doesn't install extension that already installed.

**Comment by Moshem123** [comment]
Is there a solution for this?
Installing many plugins is not working, I'm trying to automate plugin install and it's failing:
```
:call coc#util#install_extension(get(g:, 'coc_global_extensions', []))
Error detected while processing function coc#util#install_extension:
line    2:
E712: Argument of filter() must be a List or Dictionary
```

**Comment by chemzqm** [comment]
@Moshem123 it means your `g:coc_global_extensions` is not list.

**Comment by Moshem123** [comment]
> @

Sorry, the error is this:
```
Error on notify (installExtensions): Vim(call):E699: Too many arguments
```
