### ISSUE TITLE
Korean Autocompletion Error in Windows

### ISSUE THREAD

**Issue by xvim64** [neoclide/coc.nvim#3533]
Windows 10 21H2 64bit
gVim v8.2.3918

## versions

```
vim version: VIM - Vi IMproved 8.2 8023918
node version: v16.13.1
coc.nvim version: 0.0.80-f6a947a8eb
coc.nvim directory: C:\home\.vim\plugged\coc.nvim
term: undefined
platform: win32
```

## Log of coc.nvim

2021-12-29T09:00:47.682 INFO (pid:4312) [plugin] - coc.nvim 0.0.80-f6a947a8eb initialized with node: v16.13.1 after 177ms
2021-12-29T09:00:50.593 INFO (pid:4312) [attach] - receive notification: showInfo []

## Describe the bug

```
Korean Autocompletion Error in Windows
```

## Reproduce the bug

  ```vim
set nocompatible
filetype plugin indent on
syntax on
set hidden

"set go=egt
"colo solarized
"set guifont=Ubuntu_Mono:h60
"set number

source ~/.vim/plug.vim
call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
  ```

## Screenshots (optional)

These are all same inputs of "한글은(gksrmfdms)". But the results are different.

Is there a way, autocompletion for English only ?

![coc-bug-korean-autocompletion](https://user-images.githubusercontent.com/83569599/147616255-46c24643-b707-4041-94cd-5cf6b8ce36d7.gif)

**Comment by fannheyward** [comment]
Can you reproduce without coc.nvim? As your screenshot shows, you input without choose any suggestion completion item.

**Comment by xvim64** [comment]
> Can you reproduce without coc.nvim? As your screenshot shows, you input without choose any suggestion completion item.

mini-nococ.vim
```
set nocompatible
filetype plugin indent on
syntax on
set hidden

set go=egt
colo solarized
set guifont=Ubuntu_Mono:h60
set number

source ~/.vim/vim-plug/plug.vim
call plug#begin('~/.vim/plugged')
call plug#end()
```
![mini-nococ](https://user-images.githubusercontent.com/83569599/147622304-802419f8-3c84-4c08-9602-6f9267aba62f.gif)


mini-coc.vim
```
set nocompatible
filetype plugin indent on
syntax on
set hidden

set go=egt
colo solarized
set guifont=Ubuntu_Mono:h60
set number

source ~/.vim/vim-plug/plug.vim
call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```
![mini-coc](https://user-images.githubusercontent.com/83569599/147622302-5f18ff1d-85b5-4d0b-9306-71a5842ac890.gif)

**Comment by xvim64** [comment]
> Can you reproduce without coc.nvim? As your screenshot shows, you input without choose any suggestion completion item.

// without coc.nvim
![mini-nococ](https://user-images.githubusercontent.com/83569599/147623841-1bf32804-64b4-43af-8984-edc262a258d7.gif)

// with coc.nvim
![mini-coc](https://user-images.githubusercontent.com/83569599/147623840-9a9ef7a8-ba96-415c-a589-56b9547f4496.gif)
