### ISSUE TITLE
[Feature Request] Don't auto select only low priority source candidates

### ISSUE THREAD

**Issue by kevinhwang91** [neoclide/coc.nvim#3535]
**Is your feature request related to a problem? Please describe.**
I have configurated `coc-settings.json`,
```json
"suggest.enablePreselect": true,
"suggest.noselect": false,
```
I am lazy and love the autoselect and preselect feature, but `buffer` and `around` sources are annoyed me in some cases, like complete `number` for a variable before pressing `enter` to insert a new line, I must cancel the menu and press `enter`. However, I don't want to disable them because they are useful in some cases.

**Describe the solution you'd like**
Add an option to `noselect` for only low priority sources

**Describe alternatives you've considered**
Add an option for `coc.source` to filter out the useless items.

**Comment by chemzqm** [comment]
Just enable 'uggest.noselect'
