### ISSUE TITLE
Golang Import Filepath: Jump to Definition, Weird Behaviour

### ISSUE THREAD

**Issue by mrforlorn** [neoclide/coc.nvim#3537]
Goto definition on hovering an import line in Golang code, doesn't jump to the actual file path.
Would love that it jumped to the top of the file rather than some weird preview state.
The hack I currently have to do is to jump to a variable that is imported from that file to get this intended effect, and then gg to jump to top.

Using the basic README vimrc. Nothing special.

By goto definition I mean gd, where gd is mapped like so: nmap <silent> gd <Plug>(coc-definition)

**Comment by fannheyward** [comment]
The location of definition is came from gopls, coc.nvim is a client just jump to the location.

**Comment by chemzqm** [comment]
You may need to use coc-declaration
