### ISSUE TITLE
How to remove this window

### ISSUE THREAD

**Issue by karchz** [neoclide/coc.nvim#3538]
![2021-12-31 6 26 10](https://user-images.githubusercontent.com/3665531/147789150-af682db9-bdc4-47ba-9aed-9b0f4e81dacc.png)
I don't know the name of this window, so I don't know what to write in coc-settings.json.
What is the name of this window and how do I set it up to be removed?

**Comment by chemzqm** [comment]
You need confirm completion, read wiki
