### ISSUE TITLE
Can I search lsp config in custom dir?

### ISSUE THREAD

**Issue by fcying** [neoclide/coc.nvim#354]
I don't want to update config to team repo.
Can I put lsp config into `.git` dir?
ex
```
"command": "clangd",
"configPath": [".git/compile_flags.txt","$HOME/.project/projecta/compile_flags.txt"],
"rootPatterns": [".git/", ".hg/"],
```

**Comment by fcying** [comment]
It is useful for cleaning up out, obj files.

**Comment by chemzqm** [comment]
You can add `.vim` folder to parent folder when language server use `rootPatterns`

**Comment by fcying** [comment]
There will be conflicts when placed in the `rootPatterns`
`~/project/p1` `~/project/p2` `~/project/p3` use difference `compile_flags.txt`

**Comment by chemzqm** [comment]
Use `coc#config` with `VimEnter` autocmd.
