### ISSUE TITLE
Avoid workspace configuration creation

### ISSUE THREAD

**Issue by AleCandido** [neoclide/coc.nvim#3542]
Sorry for the noise, I haven't been able to find myself: I looked into Wiki, vim help, and Issues, but I didn't gather enough information to sort it out.

I'm not interested in per workspace configurations, but `coc` keeps creating `.vim/coc-settings.json` in every project, and when deleted it recreates.

I understand the logic on how it's working, but I'd like to opt out. I only found the `disableWorkspaceFolders`, but looks like it's a per-server settings, and I want to completely disable `.vim` creation (with a single configuration, if possible).

Is there a way?

**Comment by fannheyward** [comment]
What's the content of `.vim/coc-settings.json` in your project? coc.nvim will not create the local configuration by default.

**Comment by AleCandido** [comment]
Contains only the entry related to `python.pythonPath` (even though sometimes it seems to me that it was just the empty object `{}`, but this I can not reproduce).

Maybe at this point it's just `coc-python`, nevertheless I'd prefer the same an option to deny local config usage for all the servers.

Actual content:
```json
{
  "python.pythonPath": "/home/<user>/.cache/pypoetry/virtualenvs/<project>-_<hash>-py3.9/bin/python"
}
```

**Comment by fannheyward** [comment]
What's the version of coc-pyright are you using? You can get it from `:CocList extensions`. Older version coc-pyright will create this.

**Comment by AleCandido** [comment]
> What's the version of coc-pyright are you using? You can get it from `:CocList extensions`. Older version coc-pyright will create this.

Solved, you were right.

I usually update vim plugins by `PlugUpdate` (that in turn is run by `topgrade`), but `CocUpdate` doesn't run automatically.

With `topgrade` I can make a custom rule, but is there a way to have `PlugUpdate` running `CocUpdate` every time?

**Comment by fannheyward** [comment]
You can set `coc.preferences.extensionUpdateCheck` to `daily` or `weekly` to upgrade extensions.
