### ISSUE TITLE
TabNine completion limited to one word

### ISSUE THREAD

**Issue by OsKaR31415** [neoclide/coc.nvim#3543]
# Result from CocInfo

## versions

```
vim version: VIM - Vi IMproved 8.2 8023908
node version: v17.3.0
coc.nvim version: 0.0.80-f6a947a8eb
coc.nvim directory: /Users/oscarplaisant/.vim/plugged/coc.nvim
term: tmux
platform: darwin
```

## Log of coc.nvim

```
2022-01-03T20:20:05.723 INFO (pid:65921) [coc-tabnine] - Using tabnine from /Users/oscarplaisant/.config/coc/extensions/coc-tabnine-data/binaries/4.0.44/aarch64-apple-darwin/TabNine
2022-01-03T20:20:05.724 INFO (pid:65921) [plugin] - coc.nvim 0.0.80-f6a947a8eb initialized with node: v17.3.0 after 40ms
2022-01-03T20:20:09.969 INFO (pid:65921) [completion-complete] - Results from: tabnine
2022-01-03T20:20:10.610 INFO (pid:65921) [completion-complete] - Results from: around,tabnine
2022-01-03T20:20:16.609 INFO (pid:65921) [attach] - receive notification: showInfo []
```

# Description of the bug

TabNine Completion is limited to the first word, meaning that if TabNine shows the completion `match list with`, and i press `<c-n>`, i only get `match` written in my file.

# Steps to reproduce the bug

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start vim with command: `vim -u mini.vim`
- You need to have TabNine installe (since it is what makes the bug)
- Type a line (e.g.: `match list with`)
- go on a new line, start typing the same thing again, when you see the autocompletion, choose a completion with more than one word (in my example, TabNine should show `match list with` when you type `matc`).
- Then, the completion is only up to the end of the first word (in my example, it only completes the word `match`)

**Comment by fannheyward** [comment]
> the completion is only up to the end of the first word 

In my tests, when you do `<c-n>`, only the first word is shown, but after you confirm the completion, you will get the whole line. My confirm mapping:

```
inoremap <silent><expr> <CR> pumvisible() ? coc#_select_confirm()
      \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

**Comment by OsKaR31415** [comment]
Ok, thank you, indeed it works for me.
Is there a plan to extend that feature ? because i find it annoying to have to type <cr> or whatever other key each time to confirm...

**Comment by chemzqm** [comment]
It's intended for snippet to avoid unnecessary characters, you can adjust config `suggest.invalidInsertCharacters`
