### ISSUE TITLE
My neovim have a problem with coc.nvim

### ISSUE THREAD

**Issue by dapt4** [neoclide/coc.nvim#3544]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/67972962/147976961-66c85a25-a6f2-4f5e-a91a-b164f4a7fa6a.png)

**Comment by fannheyward** [comment]
What's your vim version? What's the output of `:CocInfo`?

**Comment by chris-paterson** [comment]
Hey! I'm also running into this issue. My `:CocInfo` is:

```
## versions

vim version: NVIM v0.6.1
node version: v17.3.0
coc.nvim version: 0.0.80-c90a07eec8
coc.nvim directory: /Users/chris-paterson/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-01-04T12:43:02.345 INFO (pid:86111) [plugin] - coc.nvim 0.0.80-c90a07eec8 initialized with node: v17.3.0 after 56ms
2022-01-04T12:43:04.592 INFO (pid:86111) [attach] - receive notification: showInfo []
```

Thanks!

**Comment by dapt4** [comment]
my neovim version is 
![image](https://user-images.githubusercontent.com/67972962/148111248-7e7d8962-1d2d-4b99-ab68-1f15f9f212a5.png)

my :CocInfo is
![image](https://user-images.githubusercontent.com/67972962/148111427-f5e2776d-b17c-4ee3-aeb8-d87ec3d36943.png)

thanks for the help

**Comment by fannheyward** [comment]
> 0.0.80-8cfed3b159

@dapt4 you're using an old release, upgrade your coc.nvim please.

**Comment by dapt4** [comment]
thanks, the problem was solve :)
