### ISSUE TITLE
Completion sort and  indent error with clangd.

### ISSUE THREAD

**Issue by jackhub** [neoclide/coc.nvim#3547]
I use the latest clangd, cos.nvim and Neovim. The completion sort results not happy with clangd objective-c language.
It should match the exactly same one, which is `NSString`.
<img width="701" alt="image" src="https://user-images.githubusercontent.com/4580635/148141295-0a88b302-d703-4a27-9b52-5f8ae37e7725.png">

And for cpp files, completion with lsp snippets do not auto indent as expected. see `public` example as below.
Also, the `if` snippets `statements` do not indent as expected.
I need to re-indent it manually every time, it's annoying.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/4580635/148141561-db59714c-e725-42bc-a9cf-dbbcfc00e18a.png">

Please help to fix those problems, thanks.

**Comment by fannheyward** [comment]
For the sorting issue, set `"suggest.defaultSortMethod": "none"` in your coc-settings.json and try again.

The indent issue is caused by clangd.

**Comment by jackhub** [comment]
> For the sorting issue, set `"suggest.defaultSortMethod": "none"` in your coc-settings.json and try again.
> 
> The indent issue is caused by clangd.

I have set `"suggest.defaultSortMethod": "none"` in my doc-settings.json. But it still works weird.

When I type after `NSLog...` line, it's OK.
<img width="439" alt="image" src="https://user-images.githubusercontent.com/4580635/148205469-a2dce270-a6a1-45c2-8e3f-ac31fd3b0dbf.png">

But when I type after `__weak NSString...` line, it's Not OK.
<img width="622" alt="image" src="https://user-images.githubusercontent.com/4580635/148205322-2f5ff711-e5e6-466f-b272-60097f66eef2.png">

**Comment by fannheyward** [comment]
`"suggest.defaultSortMethod": "none"` will follow the order from clangd, coc.nvim won't sort the suggestions. It's a clangd issue that returns unexpected sorting.

**Comment by chemzqm** [comment]
@jackhub Seems we need to improve the sort logic for completion items, could you help to create an example repo?
