### ISSUE TITLE
Clash between COC Auto Import and Delimitmate

### ISSUE THREAD

**Issue by eyaleizenberg** [neoclide/coc.nvim#3552]
I use use COC and Delimitmate. In order to use the auto import of COC, you need to add something like this to your init.vim
`inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"`
This allows you to use ENTER to select the currently highlighted item and to auto import it. However, this configuration overrides Delimitmate’s expand on CR…

Suggestions?

**Comment by chemzqm** [comment]
Avoid  that key-mapping and just use `<C-y>`.
