### ISSUE TITLE
Obtain type with selection

### ISSUE THREAD

**Issue by savanna** [neoclide/coc.nvim#3556]
**Is your feature request related to a problem? Please describe.**
I want to know the type of the currently selected text, it could be a complex expression in Typescript e.g. 
```typescript
Parameters<SomeComplexClass['some keyof said class']>
```

**Describe the solution you'd like**
Similar to the [example-vim-configuration](https://github.com/neoclide/coc.nvim#example-vim-configuration)
```vim
" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>
```
But also works on the current selection.

**Describe alternatives you've considered**
I have tried manually run 
```vim
call CocAction('doHover')
```
with selection, but that does not work as hoped, it only shows the result for the first word.

**Comment by fannheyward** [comment]
Does the language server, here is tsserver, can return the complex expression type info?

**Comment by chemzqm** [comment]
No, hover feature of LSP send only one position, you need to move your cursor under the desired symbol.

**Comment by kqvanity** [comment]
@chemzqm
Jetbrains' IDEs have this functionality with something like `vmap gk <Action>(ExpressionTypeInfo)`. I'm sure they're using standard LSP under the hood

**Comment by fannheyward** [comment]
> using standard LSP under the hood

What's the language server?

**Comment by kqvanity** [comment]
I'm currently using IntelliJ (somewhat black box) with Rust, Go, and Kotlin with its espective LSP
