### ISSUE TITLE
Floating window keeps changes sizes.

### ISSUE THREAD

**Issue by ShawnAli97** [neoclide/coc.nvim#3558]
Hello, I am using coc for c++. The issue i'm having is that the floating window keeps changing sizes. It becomes so big that it covers the whole screen. It randomly becomes small again. I would like to set it up so it stays a small size the whole time.

Thank you
I am using MacBook pro 2013.

**Comment by fannheyward** [comment]
1. `:CocInfo` please
2. what's language server do you use for c++?
3. screenshot please
4. minimal vimrc to reproduce this issue

**Comment by chemzqm** [comment]
Please try minimal vimrc.
