### ISSUE TITLE
Should be possible to cycle PUM and insert with same key (tab)

### ISSUE THREAD

**Issue by theonlygusti** [neoclide/coc.nvim#3566]
I'm always frustrated when I press tab and it only completes up to the first non-word character. If `List<int>` is suggested in the PUM, pressing tab until it is selected only inserts `List` but it should insert `List<int>`.

**Describe the solution you'd like**
It should be possible for tab to: go to next option in PUM, and whichever PUM suggestion is currently hovered should be FULLY inserted into the text (instead of, as is current, only partially inserted - up to the first non-word character).

**Describe alternatives you've considered**
I don't think it's even possible to implement this in my own config using mappings.

**Comment by chemzqm** [comment]
You have to confirm completion or configure `"suggest.invalidInsertCharacters"`

**Comment by theonlygusti** [comment]
Run `:CocConfig` and add the line `"suggest.invalidInsertCharacters": ""` to the top-level JSON object.

**Comment by chemzqm** [comment]
You should use array for that config, and it's recommended to add `(` at least.

**Comment by theonlygusti** [comment]
Oh, is the default value `[" ", "(", "<", "{", "[", "\r", "\n"]` ?
