### ISSUE TITLE
CocToggle besides CocDisable and CocEnable

### ISSUE THREAD

**Issue by ferdinandyb** [neoclide/coc.nvim#3567]
**Is your feature request related to a problem? Please describe.**
Many plugins support toggling, instead of two separate commands.

**Describe the solution you'd like**
Implement a `:CocToggle`

**Describe alternatives you've considered**
Add an example to the README how to create such a command? But if you have that it's probably just easier to put in the plugin.

**Comment by pjg** [comment]
For anyone stumbling here, here's how you can implement a `:CocToggle` function:

```vim
" Function to toggle Coc
function! ToggleCoc()
  if g:coc_enabled
    CocDisable
  else
    CocEnable
  endif
endfunction

" Map F2 to toggle Coc
nnoremap <F2> :call ToggleCoc()<cr>
```
