### ISSUE TITLE
Autocomplete text menu highlight like in VScode

### ISSUE THREAD

**Issue by Artificerio** [neoclide/coc.nvim#3568]
Is there any way to highlight the text in the autocomplete menu like in VScode as I'm typing ?
![Capture](https://user-images.githubusercontent.com/73526166/149412222-7146f50b-f557-4fa8-9e91-09dd646c6f6d.PNG)
Can this feature exist in coc or is there any coc-extension for this ? 

I know about the 'nvim-cmp' plugin, which provides custom highlight groups for this. 
https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance.
![1](https://user-images.githubusercontent.com/73526166/149412290-6b849881-0aaa-4f3b-9c15-e57ef90c51ed.PNG)

**Comment by chemzqm** [comment]
It's not hard to build, but we have to drop support for vim's builtin completion which means related key-mappings need changed and many suggest configurations need change as well.

**Comment by xiyaowong** [comment]
Looking forward to this feature😃

**Comment by oblitum** [comment]
> It's not hard to build, but we have to drop support for vim's builtin completion which means related key-mappings need changed and many suggest configurations need change as well.

I'd like to point further on that that, as far as I've checked last time I tried, they miss preselect from nvim's pum. I really like preselect, so I'd like coc to not to miss it too in case this ever gets implemented.

**Comment by oblitum** [comment]
Related issues:

- https://github.com/neoclide/coc.nvim/issues/3480#issuecomment-976735772

**Comment by tommyjcarpenter** [comment]
Hi - I see this issue was marked completed - how does it get enabled? Im using the latest coc plugin but I dont see this behavior

**Comment by fannheyward** [comment]
@tommyjcarpenter what's your `:CocInfo`? The custom completion menu is enabled in 0.0.82.

**Comment by tommyjcarpenter** [comment]
```
## versions

vim version: VIM - Vi IMproved 9.0 9000350
node version: v18.10.0
coc.nvim version: 0.0.82-f39f5f69 2022-10-07 23:24:25 +0800
coc.nvim directory: /Users/tommy/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-10-10T07:58:13.743 INFO (pid:10394) [coc-git] - Looking for git in: git
2022-10-10T07:58:13.748 INFO (pid:10394) [plugin] - coc.nvim initialized with node: v18.10.0 after 45ms
2022-10-10T07:58:14.824 INFO (pid:10394) [attach] - receive notification: showInfo []
```

**Comment by tommyjcarpenter** [comment]
@fannheyward is there something needed to add to vimrc to get this to work?

**Comment by fannheyward** [comment]
The custom competition menu displaying should work out of box, you may need to change your mappings for tab/cr.

**Comment by tommyjcarpenter** [comment]
@fannheyward  The completion box shows up and works - but the highlighting doesnt work. I dont think it has to do with tab/cr. Completion is fine but when navigating, it doesnt highlight the current row.

**Comment by chemzqm** [comment]
@tommyjcarpenter you may need to define highlight for `CocMenuSel` yourself, see `:h coc-highlights`, please provide the colorscheme you're using, so we can investigate

**Comment by tommyjcarpenter** [comment]
@chemzqm im using this for colorschemes: https://github.com/nanotech/jellybeans.vim
