### ISSUE TITLE
Default colorscheme seems not ok

### ISSUE THREAD

**Issue by r4v3n6101** [neoclide/coc.nvim#3569]
Use of the default neovim colorscheme shows us something like this (colours of types are invisible): 
![image](https://user-images.githubusercontent.com/30029970/149418472-fd89c1e2-5cc6-4b98-8678-865f9fbe2dca.png)

Should background colour of float window be changed to something less obscure, shouldn't it?

**Comment by chemzqm** [comment]
You have to tweak highlight group `NormalFloat` or `CocFloating`

**Comment by r4v3n6101** [comment]
Thanks for fast answer!
