### ISSUE TITLE
No matching autocommand since the last update

### ISSUE THREAD

**Issue by reaysawa** [neoclide/coc.nvim#357]
**Describe the bug**
When starting Neovim I get the following message

"No matching autocommands".

This is because [workspace.ts](https://github.com/neoclide/coc.nvim/blob/master/src/workspace.ts) is executing CocQuickfixChange

`await nvim.command('doautocmd User CocQuickfixChange')`

And it seems like this command no longer exists after the #347 changes.

**To Reproduce**

1. Upgrade the plugin to 8857ae4
2. Start Neovim
3. No matching autocommands message will be echoed

**Comment by chemzqm** [comment]
Code of #347 is not commited.
It's because you have `let g:coc_auto_copen=0` and didn't setup autocmd.
