### ISSUE TITLE
After go-to-defintion, two additonal windows appear. How to close them all at once?

### ISSUE THREAD

**Issue by Wei-Mao** [neoclide/coc.nvim#3583]
.

**Comment by fannheyward** [comment]
1. `:CocInfo`
2. how to reproduce this
3. screenshot please

**Comment by Wei-Mao** [comment]
> 1. `:CocInfo`
> 2. how to reproduce this
> 3. screenshot please

![image](https://user-images.githubusercontent.com/51208983/149732458-4f93b023-fe9a-4988-a069-fdcdabf0c051.png)

**Comment by Wei-Mao** [comment]
To be precise, my question is how to close these two splits all at once without pressing :q twice

**Comment by fannheyward** [comment]
By default, `<Esc>` will close the list view.

**Comment by chemzqm** [comment]
Checkout `:h CocLocationsChange` and `:h coc-list-mappings-custom`
