### ISSUE TITLE
Couldn't load correct replaced go.mod file

### ISSUE THREAD

**Issue by crazytaxi824** [neoclide/coc.nvim#3589]
I have reported this issue to vim-go as well, they have fixed it at https://github.com/fatih/vim-go/pull/3345. Hope this could help to locate the problem.

### Env

vim v8.2.4100

coc.nvim 3710b54c51ff8cf97fe6686dd6220734726c42bf

gopls v0.7.4

go version go1.17.6 darwin/amd64

`~/.vim/coc-setting.json`

```json
{
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod"],
      "filetypes": ["go"]
    }
  },
}
```

### Describe

1. I have a project foo

```
foo
├── go.mod
└── src
    └── main.go
```

2. run `go get github.com/hashicorp/consul/api` in `.../foo` project root directory.

3. run `go mod tidy` in `.../foo` project root directory.

4. my `.../foo/src/main.go` content

```go
package main

import (
	"log"

	"github.com/hashicorp/consul/api"
)

func main() {
	client, err := api.NewClient(&api.Config{
		Address: "xxx",
	})

	// ...
}
```

5. cursor on `NewClient()`, run `:call CocAction('jumpDefinition')`. it will jump to `$GOPATH/pkg/mod/github.com/hashicorp/consul/api@v1.12.0/api.go`

```go
// NewClient returns a new client
func NewClient(config *Config) (*Client, error) {
	// bootstrap the config
	defConfig := DefaultConfig()

	// ...
}
```

### Problem

My problem is when i try to `:call CocAction('jumpDefinition')` the `DefaultConfig()` in this function, it won't work. coc shows `[coc.nvim] definition not found`.

So I dig a little deeper, found that coc is trying to load `$GOPATH/pkg/mod/github.com/hashicorp/consul/sdk/go.mod` instead of `$GOPATH/pkg/mod/github.com/hashicorp/consul/sdk@v0.8.0/go.mod`, because `$GOPATH/pkg/mod/github.com/hashicorp/consul/api@v1.12.0/go.mod` file content is

```go
module github.com/hashicorp/consul/api

go 1.12

replace github.com/hashicorp/consul/sdk => ../sdk   (❌ this is where replace goes wrong)

require (
	github.com/hashicorp/consul/sdk v0.8.0
	//...
)
```

So I think it's the directory replacement problem.

**Comment by chemzqm** [comment]
Seems you need use `ignoredRootPaths` in language server config.

**Comment by chemzqm** [comment]
You can use `"workspace.ignoredFolders"` configuration now.

**Comment by crazytaxi824** [comment]
@chemzqm thanks a lot.
