### ISSUE TITLE
Can  add other sources to python?

### ISSUE THREAD

**Issue by taigacute** [neoclide/coc.nvim#359]
**Is your feature request related to a problem? Please describe.**
Can  add other sources to python? Pyls is not very friendly, my experience with deoplete-jedi was great, but switching coc to write python is incomplete.

**Comment by JoseAntonioTorre** [comment]
I have the same problem. I am using vim to program python and I don't know how to get good autocompletion with nvim and coc.

Is there any alternative?

**Comment by fannheyward** [comment]
Try https://github.com/neoclide/coc-jedi? From the README, only basic completion working by now.

**Comment by taigacute** [comment]
@fannheyward  I found that coc-jedi just completed the completion, and other important features were not completed.

**Comment by ebkalderon** [comment]
According to [this comment](https://github.com/neoclide/coc.nvim/issues/248#issuecomment-445517475), it seems that `coc-jedi` is no longer being developed in favor of [Microsoft/python-language-server](https://github.com/Microsoft/python-language-server) integration instead. This is the same language server used in VSCode, and it reportedly works great.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-python almost done, should be able to work soon, it's expected to have bugs at first.

**Comment by ebkalderon** [comment]
@chemzqm Awesome! I just came across [this thread](https://github.com/neoclide/coc.nvim/issues/419) in which you showed how to configure MPLS as a custom language server as well. Glad to hear that the official extension is nearing completion, though.

**Comment by chemzqm** [comment]
It could works with master of coc.nvim now.

**Comment by taigacute** [comment]
i  will try it

**Comment by ebkalderon** [comment]
I'm running into an issue where the `coc-python` extension fails to load with the following error:

```
[coc.nvim] Error loading extension from /Users/eyalkalderon/.config/coc/extensions/node_modules/coc-python/lib/index.js: Reflect.hasOwnMetadata is not a function
```

I've already removed the `'tag': '*'` from the relevant `Plug` command in my `init.vim` and have upgraded my `coc.nvim` to the latest master. Any idea what could be going wrong?
