### ISSUE TITLE
如何取消在=等号后，按tab键的补全弹出

### ISSUE THREAD

**Issue by gamark** [neoclide/coc.nvim#3591]
**Is your feature request related to a problem? Please describe.**
目前是默认设置，如下， 如何才能，取消等号后，按TAB键的补全弹出。
inoremap <silent><expr> <TAB>    
          \ pumvisible() ? "\<C-n>" :
          \ <SID>check_back_space() ? "\<TAB>" :
          \ coc#refresh()
    
    inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
                                                                                  
                                                                                  
    function! s:check_back_space() abort                                          
        let col = col('.') - 1                                                    
        return !col || getline('.')[col - 1]  =~# '\s'                            
    endfunction      
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
Create your own key-mapping
