### ISSUE TITLE
Bug in Sending completion request even when "isIncomplete" is "false"

### ISSUE THREAD

**Issue by yaegassy** [neoclide/coc.nvim#3598]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.0-dev+920-g7e2ce35e3
node version: v16.13.1
coc.nvim version: 0.0.80-2d5e9a12cb
coc.nvim directory: /Users/yaegassy/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug

This is a problem that I checked with `coc-volar` (`yaegassy/coc-volar`).

- <https://github.com/yaegassy/coc-volar/issues/110>

The "triggerCharacter" of the language server itself has been changed due to the upgrade of the language server.

As a result, when there are completion suggestions containing `-`, typing `-` will cancel the completion suggestions.

To solve this problem, I created a PR on the language server itself.

- <https://github.com/johnsoncodehk/volar/pull/890>

After that, the author of the language server told me that it might be a problem with `coc.nvim` itself, so I reported the issue to `coc.nvim`.

- <https://github.com/yaegassy/coc-volar/issues/110#issuecomment-1019453356>

## Reproduce the bug

- Create a "Vue" project and mini.vim

  ```
  cd /tmp
  yarn create vite sample-proj --template vue-ts

  cd sample-proj
  yarn

  cat <<EOF > /tmp/sample-proj/mini.vim
  set nocompatible
  set runtimepath^=/tmp/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  EOF
  ```

- Go to "/tmp/sample-proj" and start nvim:

  ```
  cd /tmp/sample-proj
  nvim -u mini.vim
  ```

- Open the `src/App.vue` file

  ```
  :e src/App.vue
  ```

- Enter `<p v-` in the `<template>` block

  When I type `v`, the completion suggestions are displayed, but when I type `-`, the suggestions disappear.

  ```
  // ...snip
  <template>
    // ..snip
    <p v-
  </template>
  // ...snip
  ```

### [NG] 

> :CocInstall @yaegassy/coc-volar

https://user-images.githubusercontent.com/188642/150523907-f04e5fbc-98ad-4711-8aaf-006108d3b817.mp4

### [OK]

This is the version before the "triggerCharacter" was changed in the Language Server.

> :CocUninstall @yaegassy/coc-volar 
> :CocInstall @yaegassy/coc-volar@0.8.1

https://user-images.githubusercontent.com/188642/150523970-f9f120d4-6146-4bc3-a6f8-e23204dd6f22.mp4

## Misc1

As a side note, there may be cases where adjusting iskeyword can solve the problem when the completion contains `-`.

I tried adding `-` to `iskeyword` and - to `b:coc_additional_keywords`, but these did not solve the problem.

## Misc2 (mp4)

"nvim's built-in lsp" + `nvim-cmp` worked fine. Of course, I did not set iskeyword either.

https://user-images.githubusercontent.com/188642/150718171-e423be80-01fa-43e5-bc1c-1cc745565fd0.mp4

**Comment by chemzqm** [comment]
The problem is we should avoid trigger completion when we could do filter.

**Comment by yaegassy** [comment]
Thank you for the fix and adjustment. 🙇

coc-volar issue has been resolved.

**DEMO (mp4)**:

https://user-images.githubusercontent.com/188642/150873470-8c7f8f69-0fc3-4954-aef3-554626e6302a.mp4

**Comment by chemzqm** [comment]
But it should trigger completion with result by `-`, I've tried on VSCode and it could work.

**Comment by yaegassy** [comment]
Yes, VSCode has no problems with `-`. coc-volar is now comfortable, thanks to chemzqm's fixes and tweaks to coc.nvim.
