### ISSUE TITLE
LS of coc-pyright does not work correctly from workspace related change commit

### ISSUE THREAD

**Issue by yaegassy** [neoclide/coc.nvim#3599]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.0-dev+920-g7e2ce35e3
node version: v16.13.1
coc.nvim version: 0.0.80-eb01206e30
coc.nvim directory: /Users/yaegassy/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug

This problem is currently occurring in `coc-pyright`.

After this commit, pyright's language server does not work properly, including completion and diagnostics and more... <https://github.com/neoclide/coc.nvim/commit/631948d940d9477f0ca8059b8b0499060a55d9a7>

**coc-pyright issue**:

- <https://github.com/fannheyward/coc-pyright/issues/693>
- <https://github.com/fannheyward/coc-pyright/issues/692>

If you rollback to an older commit than the one with the problem, it will work fine.

## Reproduce the bug

- Create a "Python" project and mini.vim

  ```
  #
  # sample python project
  #
  
  cd /tmp
  mkdir -p /tmp/pyright-check
  cd pyright-check
  
  cat <<EOF > /tmp/pyright-check/check.py
  import sys
  
  print(sys.path)
  EOF
  
  #
  # mini.vim
  #
  
  cat <<EOF > /tmp/pyright-check/mini.vim
  set nocompatible
  set runtimepath^=/tmp/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  EOF
  ```

- Go to "/tmp/pyright-check" and start nvim:

  ```
  cd /tmp/pyright-check
  nvim -u mini.vim
  ```

- Install coc-pyright

  ```
  :CocInstall coc-pyright
  ```

- Open the `check.py` file

  ```vim
  :e check.py
  ```

- Operate vim.

### [NG] 

https://user-images.githubusercontent.com/188642/150891475-90caa932-7842-4434-99b6-27fad254e9ee.mp4

### [OK] commit: https://github.com/neoclide/coc.nvim/commit/56f52b9c1c60499f76adb6dd31367009bf925768

https://user-images.githubusercontent.com/188642/150891651-cbd0be4a-07ff-441d-8764-a6d0af97f9c6.mp4

## Misc

In coc-pyright, there is a middleware related to workspace.

- <https://github.com/fannheyward/coc-pyright/blob/master/src/index.ts#L215-L218>

I thought this might be related to the problem, so I commented it out and tried to build and use it, but it still didn't solve the problem.

**Comment by fannheyward** [comment]
631948d940d9477f0ca8059b8b0499060a55d9a7 is the first bad commit.

**Comment by chemzqm** [comment]
```
[Warn  - 10:14:42 PM] stubPath /xxx/study/python/pyright-check/typings is not a valid directory.
```
Don't know why it's using a directory that not exists.

**Comment by lithammer** [comment]
> ```
> [Warn  - 10:14:42 PM] stubPath /xxx/study/python/pyright-check/typings is not a valid directory.
> ```
>
> Don't know why it's using a directory that not exists.

You can likely ignore that. It's just directory Pyright searches for custom type stub files. Unsure why it logs it as warning instead of information though.

**Comment by chemzqm** [comment]
Seems caused by bad event:
```
[Trace - 10:32:16 PM] Sending notification 'workspace/didChangeWorkspaceFolders'.
Params: {
    "event": {
        "added": [
            {
                "uri": "file:///Users/chemzqm/study/python/pyright-check",
                "name": "pyright-check"
            }
        ],
        "removed": [
            {
                "uri": "file:///Users/chemzqm/study/python/pyright-check",
                "name": "pyright-check"
            }
        ]
    }
}
```

**Comment by chemzqm** [comment]
The diff method
```
function arrayDiff<T>(left: ReadonlyArray<T>, right: ReadonlyArray<T>): T[] {
  return left.filter(element => !right.includes(element))
}
```
When we create new reference on property access.
