### ISSUE TITLE
autocomplete trigger when enter new line

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#36]
**Describe the bug**

the autocomplete menu popup after enter new line.

**To Reproduce**

```javascript
test test $
```
`$` is the cursor in normal mode, when i type `o` enter a new line.

```javascript
test test
$
```
the autocomplete popup.

**Comment by chemzqm** [comment]
It's useful sometimes, add `"coc.preferences.triggerAfterInsertEnter": false,` to disable it.
https://github.com/neoclide/coc.nvim/blob/master/history.md#2018-07-27
