### ISSUE TITLE
Neovim's virtual text for diagnostic messages

### ISSUE THREAD

**Issue by kristijanhusak** [neoclide/coc.nvim#360]
**Is your feature request related to a problem? Please describe.**
It's more nice to have, but a great one for me.
I would like to use Neovim's virtual text feature to show diagnostic messages.
ALE has a support for [this](https://github.com/w0rp/ale/blob/a50e049e747739c711198bd706c7340e16b182cc/doc/ale.txt#L1936) for some time now.

**Describe the solution you'd like**
This should be an option, the same way `codeLens` is.

**Describe alternatives you've considered**
Alternative is to install ALE, and pass down messages to it. I would like to avoid installing ALE only because of this, because `coc` covers everything that i need.

**Comment by Avi-D-coder** [comment]
I had the same thought. Working on it now!

**Comment by chemzqm** [comment]
Will add an option for that, but I have to say that redraw of virtual text could affect your type experience.

**Comment by Avi-D-coder** [comment]
@chemzqm I Have it almost done. I just have to add the finishing touches.

**Comment by kristijanhusak** [comment]
@chemzqm wouldn't triggering the virual text redraw on CursorHold fix the issue? Then it wouldn't redraw so often, at least not while typing.

**Comment by Avi-D-coder** [comment]
@kristijanhusak that's a great idea. I will change my prototype.

**Comment by chemzqm** [comment]
Another problem is how to deal with multiple lines diagnostic message?
What if there're several diagnostics at same line?

**Comment by Avi-D-coder** [comment]
Multiline for now is out of the scope of my implementation.
When there are several diagnostics at same line one of the highest severity should be shown.

**Comment by Avi-D-coder** [comment]
@kristijanhusak Any additional thoughts, or can the issue be closed?

**Comment by kristijanhusak** [comment]
@Avi-D-coder i left a comment on the PR https://github.com/neoclide/coc.nvim/pull/365#issuecomment-455888062. Could we add something like this?

**Comment by Avi-D-coder** [comment]
chemzqm added a one space prefix. I'll make a PR that allows you to set the prefix.

**Comment by Avi-D-coder** [comment]
@kristijanhusak how does https://github.com/neoclide/coc.nvim/pull/375 look?

**Comment by kristijanhusak** [comment]
Looks great, thanks!
