### ISSUE TITLE
`2c18827ac603841bcac2c540c85620647a007e74` broken `document.applyEdits`

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#3603]
Steps to reproduce:

1. setup rust-analyzer:

```
"rust": {
    "command": "rust-analyzer",
    "filetypes": ["rust"],
    "rootPatterns": ["Cargo.toml"]
  }
```

2. test rust code:

```
use std::io::Result;

fn main() {
    Error;
    println!("Hello, world!");
}
```

3. Put cursor on `Error`, fire codeAction and select "Import `std::io::Error`" to apply
4. Error result `use std::io{Result, Error}::;`, should be `use std::io::{Error, Result};`

**Comment by chemzqm** [comment]
Edit at same position have to be reversed.
