### ISSUE TITLE
Disable autoformat on current buffer

### ISSUE THREAD

**Issue by kiwiz** [neoclide/coc.nvim#3605]
**Is your feature request related to a problem? Please describe.**
On large files, the formatter might take a large amount of time to complete - I'd like to be able to disable format-on-save in those instances (without having to disable `coc` entirely).

**Describe the solution you'd like**
A function or variable I can toggle that controls formatting for the current buffer.

**Describe alternatives you've considered**
Perhaps a boolean like `coc.preferences.formatOnSave` in the config (there is a similarly functioned `coc.preferences.formatOnType`).

**Comment by chemzqm** [comment]
Use `:noa w` or configure `coc.preferences.willSaveHandlerTimeout`
