### ISSUE TITLE
UnhandledRejection: request error nvim_call_function

### ISSUE THREAD

**Issue by bosgithub** [neoclide/coc.nvim#3606]
Error pops out every time I save this file, I tried to CocUpdate and Plugupdate, still issue.

![Screen Shot 2022-01-29 at 1 01 38 PM](https://user-images.githubusercontent.com/50392230/151672080-d65e6db1-9d05-4488-a08a-6a0c52ae05ac.png)
![Screen Shot 2022-01-29 at 1 04 21 PM](https://user-images.githubusercontent.com/50392230/151672149-0e7d6871-7461-4ded-8788-d0217d5af790.png)

**Comment by chemzqm** [comment]
Avoid use coc-python which is not maintained any more.
