### ISSUE TITLE
In coc-lua and coc-sumneko-lua, completion for require duplicates the last character

### ISSUE THREAD

**Issue by statiolake** [neoclide/coc.nvim#3608]
## versions

vim version: VIM - Vi IMproved 8.2 8024014
node version: v17.3.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: C:\Users\dicen\workspace\daily\2022\0130\coc.nvim
term: WezTerm
platform: win32

## Log of coc.nvim

2022-01-30T22:03:16.038 INFO (pid:38976) [coc-git] - Looking for git in: git
2022-01-30T22:03:16.060 INFO (pid:38976) [services] - registered service "highlight"
2022-01-30T22:03:16.666 INFO (pid:38976) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v17.3.0 after 848ms
2022-01-30T22:03:22.561 INFO (pid:38976) [services] - registered service "sumneko-lua"
2022-01-30T22:03:22.561 INFO (pid:38976) [services] - Sumneko Lua Language Server state change: stopped => starting
2022-01-30T22:03:22.569 INFO (pid:38976) [language-client-index] - Language server "sumneko-lua" started with 58964
2022-01-30T22:03:22.770 INFO (pid:38976) [services] - Sumneko Lua Language Server state change: starting => running
2022-01-30T22:03:22.772 INFO (pid:38976) [services] - service sumneko-lua started
2022-01-30T22:03:23.811 INFO (pid:38976) [completion-complete] - Results from: sumneko-lua
2022-01-30T22:03:25.459 INFO (pid:38976) [completion-complete] - Results from: sumneko-lua
2022-01-30T22:03:27.647 INFO (pid:38976) [completion-complete] - Results from: sumneko-lua
2022-01-30T22:03:32.494 INFO (pid:38976) [completion-complete] - Results from: sumneko-lua
2022-01-30T22:04:08.340 INFO (pid:38976) [attach] - receive notification: showInfo []

## Describe the bug

With coc-lua and coc-sumneko-lua, completion for `require` duplicates the last character. I originally reported in [coc-sumneko-lua#17](https://github.com/xiyaowong/coc-sumneko-lua/issues/17).

The reason I report this here is that langauge server (<https://github.com/sumneko/lua-language-server>) itself is working normally on VSCode and Neovim built-in LSP (with nvim-cmp).

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=./coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  
  " coc-sumneko-lua also has issue
  let g:coc_global_extensions = ['coc-sumneko-lua']
  ```

- Start (neo)vim with command: `vim -u mini.vim test.lua`

- type `require '` and some alphabet suggesting some lua module.
  - It may depend on your environment, but for example: `require 'j` produces completion for `jit` module in my environment.

- Select and confirm completion by `<C-y>`.

- You'll see the last character is duplicated like: `require 'jitt`. The cursor is at correct position: `jit|t` (| represents cursor).

## Screenshots (optional)

Those screenshots are not taken in the above minimal environment but in usual my environment, but describing the same issue.

![image](https://user-images.githubusercontent.com/20490597/151693121-ef1018c7-7417-4e04-96b1-75c0dde1135a.png)

![image](https://user-images.githubusercontent.com/20490597/151693123-1867249d-feff-465e-85be-cc6262977ecb.png)

**Comment by statiolake** [comment]
I'm using the following settings. (I wanted to test in the clean environment but it seems coc-settings.json is read from usual config directory regardless.)

```json
{
  "Lua.runtime.version": "LuaJIT",
  "Lua.misc.parameters": ["--rpclog=true"],
  "sumneko-lua.logPath": "log"
}
```

This produces log files under `log/` directory. Note that it seems Lua language server does not support `Lua.server.trace` or the like, so you need to investigate those log files.

**Comment by chemzqm** [comment]
Reproduced on vim8

**Comment by statiolake** [comment]
Actually the screenshot is taken in Neovim, so it should reproduce in Neovim too.

The version details of Neovim I tested:

```
NVIM v0.7.0-dev+923-gecec95712
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-888

Features: -acl +iconv +tui
See ":help feature-compile"

      システム vimrc: "$VIM\sysinit.vim"
       省略時の $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by chemzqm** [comment]
I see, the server has bug as well, you can enable verbose output by `  "sumneko-lua.trace.server": "verbose"`

```
[Trace - 10:25:58 AM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 16,
        "uri": "file:///Users/chemzqm/vim-dev/coc.nvim/t.lua"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 9
                },
                "end": {
                    "line": 0,
                    "character": 9
                }
            },
            "rangeLength": 0,
            "text": "b"
        }
    ]
}


[Trace - 10:25:58 AM] Sending request 'textDocument/completion - (18)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/chemzqm/vim-dev/coc.nvim/t.lua"
    },
    "position": {
        "line": 0,
        "character": 10
    },
    "context": {
        "triggerKind": 1
    }
}
[Trace - 10:25:58 AM] Received response 'textDocument/completion - (18)' in 39ms.
Result: {
    "items": [
        {
            "detail": "Users/chemzqm/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/meta/Lua 5.4 en-us utf8/basic.lua",
            "documentation": {
                "kind": "markdown",
                "value": "* [[meta]](file:///Users/chemzqm/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/meta/Lua%205.4%20en-us%20utf8/basic.lua)"
            },
            "insertTextFormat": 2,
            "kind": 17,
            "label": "basic",
            "sortText": "0001",
            "textEdit": {
                "newText": "basic",
                "range": {
                    "end": {
                        "character": 9,
                        "line": 0
                    },
                    "start": {
                        "character": 9,
                        "line": 0
                    }
                }
            }
        },
   ]
}
```
The `textEdit.range.end.character` should be `10`, if you're using auto paris extension like `coc-pairs`, you will have correct range.

**Comment by chemzqm** [comment]
See
```
	/**
	 * An edit which is applied to a document when selecting this completion.
	 * When an edit is provided the value of `insertText` is ignored.
	 *
	 * *Note:* The range of the edit must be a single line range and it must
	 * contain the position at which completion has been requested.
	 * @since 3.16.0 additional type `InsertReplaceEdit`
	 */
	textEdit?: TextEdit | InsertReplaceEdit;
```
from https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion
