### ISSUE TITLE
enabling\disabling sources on demand

### ISSUE THREAD

**Issue by TxHawks** [neoclide/coc.nvim#361]
**Is your feature request related to a problem? Please describe.**
Not sure if this is a question or a feature request, but I'm wondering if there is a way to switch completion engines per buffer, in files of the same language.

I work on a lot of javascript code bases. Some of them use Flow for static typing, an in those I'd like to use the Flow Language Server. However, some projects do not have any static typing, in which case, I'd like to use `coc-tsserver`.

**Describe the solution you'd like**
I'd like to be able to map a key binding that will switch between the flow language server and `coc-tsserver` using . Alternatively, I'd like to use the flow language server only in files that have `// @flow` or `/* @flow */` as their first line.

**Comment by chemzqm** [comment]
You can configure coc for each of project, for your flow project, add `.vim/coc-settings.json` with:
```
  "tsserver.enable": false,
```
and your flow language server configuration.

If you're using code of master, you can use `requireRootPattern` option for your flow language server.

**Comment by TxHawks** [comment]
How would you do it in mixed projects, say during a migration from Flow to Typescript, that have both flow, typescript and untyped js files?

I'd like untyped js files to be checked using `tsserver.enableJavascript`, but that breaks flow typed files.
I think the best solution for this would be to somehow allow enabling/disabling `tsserver.enableJavascript` on the fly, preferably only for the active buffer

**Comment by chemzqm** [comment]
> tsserver.enableJavascript on the fly

It won't work, that configuration apply to tsserver not current buffer, buffer variable like `b:coc_tsserver_disable` could help.

**Comment by TxHawks** [comment]
Just so I'm clear, this needs to be implemented and doesn't work at the moment, right?

**Comment by chemzqm** [comment]
Yes, not supported yet.

**Comment by TxHawks** [comment]
Can we reopen this then?

**Comment by chemzqm** [comment]
Consider create issue at https://github.com/neoclide/coc-tsserver/issues

**Comment by TxHawks** [comment]
Will do. Thanks

**Comment by TxHawks** [comment]
Similarly, is there a way to disable a language server (per buffer or not) with a command? Obviously, one wouldn't want suggestions from the flow language server when `tsserver.enableJavascript` is enabled.

**Comment by chemzqm** [comment]
>  is there a way to disable a language server (per buffer or not) with a command? 

No, but you can use autocmd with `CocAction` to start/stop a service.

**Comment by TxHawks** [comment]
How can I stop the flow language server and start tsserver with CocAction (and vice versa)?

Thanks again for all the help and being so quick to answer

**Comment by chemzqm** [comment]
See `:h coc-action-toggleService`

**Comment by TxHawks** [comment]
I don't think I understand how to use it correctly.

Trying 
```
:call CocAction('toggleService tsserver')
:call CocAction('toggleService languageclient.flow')
```
but get an `[coc.nvim] unknown action toggleService tsserver/languageclient.flow` error

**Comment by iamcco** [comment]
@TxHawks  `:call CocAction('toggleService',  'tsserver')`

**Comment by TxHawks** [comment]
But how do toggle the flow language server?

**Comment by chemzqm** [comment]
Use the key in configuration object of `languageserver`

**Comment by TxHawks** [comment]
I have
```json
  "languageserver": {
    "flow": {
      "command": "flow",
      "args": ["lsp"],
      "filetypes": ["javascript", "javascriptreact", "javascript.jsx"],
      "initializationOptions": {},
      "requireRootPattern": true,
      "settings": {},
      "rootPatterns": [".flowconfig"]
    }
  },
```
and when I run `:call CocAction('toggleService', 'flow')`, I get `[coc.nvim] Service flow not found`

**Comment by chemzqm** [comment]
Should be `languageserver.flow`

**Comment by TxHawks** [comment]
👍 Thanks

**Comment by TxHawks** [comment]
So, I am able to use `:call CocAction('toggleService', 'languageserver.flow')` to disable the language server, but not to enable it back again. Or at least, I don't get any suggestions back.

When I do `:call CocAction('toggleService', 'tsserver')`, I get a `[coc.nvim] Srvice tsserver not found`.

Sorry to flood you with questions. I'm sure it's really just me that's doing something wrong.

These are the relevant settings I have enabled in `coc-settings.json`:
```js
{
  // Disable tsserver for javascript files
  // so that Flow can take over
  "tsserver.enable": false,
  "tsserver.enableJavascript": true,
  "languageserver": {
    "flow": {
      "command": "flow",
      "args": ["lsp"],
      "filetypes": ["javascript", "javascriptreact", "javascript.jsx"],
      "initializationOptions": {},
      "requireRootPattern": true,
      "settings": {},
      "rootPatterns": [".flowconfig"]
    },
  }
}
```

**Comment by chemzqm** [comment]
`"tsserver.enable": false,` disable tsserver to regist.

**Comment by TxHawks** [comment]
So there isn't really any way to start with it disabled, and enable it on the fly, right?
