### ISSUE TITLE
How to enable semantic highlights for coc-clangd?

### ISSUE THREAD

**Issue by ethan-enhe** [neoclide/coc.nvim#3611]
I've set "semanticTokens.filetypes" to ["*"] in my configuration, but symbols are not hightlighted.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Try `:CocCommand semanticTokens.checkCurrent`

**Comment by ethan-enhe** [comment]
> Try `:CocCommand semanticTokens.checkCurrent`

It said 'SemanticTokens provider not found, your languageserver may not support it'.

**Comment by damnskippy** [comment]
@ethan-enhe Make sure you're using recent/latest version of clangd.
