### ISSUE TITLE
Option to disable fuzzy matching in complete menu

### ISSUE THREAD

**Issue by apazzolini** [neoclide/coc.nvim#362]
Most of the time, suggestions from `tsserver` are garbage and get in the way more than help. For example,

![](https://cl.ly/f329de42720a/Image%202019-01-19%20at%201.15.43%20PM.png)

In the above screenshot, the only possible things I'd like completion for are the items that start with what I've already typed, `cur`. I get that those are presented at the top, but the remainder of the entries are always visually distracting.

Is there a way to restrict the options presented to those that have a prefix match?

Thank you for your work!

**Comment by chemzqm** [comment]
There used be to an option that, but it's removed, because you should get used to it for faster completion experience, for camel cased word, type first character of each component.

Use `"coc.preferences.maxCompleteItemCount"` to limit the count in completion menu.
