### ISSUE TITLE
diagnostic signs don't change after update

### ISSUE THREAD

**Issue by dunkeln** [neoclide/coc.nvim#3620]
![Screenshot 2022-02-04 at 2 15 30 PM](https://user-images.githubusercontent.com/46231179/152519957-cbbac6d9-c8d2-4b72-9390-2fd506bcd567.png)
added the following change in config but they don't reciprocate , default signs show up. Am I missing something?

**Comment by chemzqm** [comment]
There've removed for sometime, install coc-json and checkout `:h coc-config-diagnostic`

**Comment by dunkeln** [comment]
thank you , this works
