### ISSUE TITLE
Latest release always trigger configuration change event after change buffer.

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#3625]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.0-dev+f02a5a7bd
node version: v14.18.2
coc.nvim version: 0.0.80-1012cfa127
coc.nvim directory: /Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim
term: xterm-kitty
platform: darwin
```

## Describe the bug

for those extension listen to the event will become unavailable.

for example:

``` typescript
  const disposable = vscode.workspace.onDidChangeConfiguration(async (e: vscode.ConfigurationChangeEvent) => {
      if (!e.affectsConfiguration('angular')) {
        return;
      }
      const release = await mutex.acquire();
      await client.stop();
      await client.start();
      release();
    });
```

it will restart server after change buffer.

**Comment by Frederick888** [comment]
@chemzqm I've just updated to e7680fa7fda7f7abb075e54591ab40325bfa585f and noticed there were still some issues after I jumped from my project to standard library/external dependency:

- Using coc-rust-analyzer, every time I jump to code of a dependency in `~/.cargo/registry/src` or back, it asks me `Changing "rust-analyzer.cargo" requires a reload. Reload now? (y/n)`
- Using coc-go, the first time I jump to a dependency in `$GOPATH/src` or Go stdlib, gopls reloads
- `CocLocalConfig` tries to create `.vim/coc-settings.json` in `~/.cargo`/`$GOPATH`/`/usr/lib/go/src` when current buffer is a dependency or stdlib file
