### ISSUE TITLE
set noexpandtab, set tabstop=4, set shiftwidth=4 and COC casuse the wrong cursor position in bash shell script

### ISSUE THREAD

**Issue by xvim64** [neoclide/coc.nvim#3641]
## versions
```
vim version: VIM - Vi IMproved 8.2 8024350
node version: v16.14.0
coc.nvim version: 0.0.80-72aeffd7ab
coc.nvim directory: C:\home\.vim\plugged\coc.nvim
term: undefined
platform: win32
```

## Log of coc.nvim

2022-02-14T01:57:28.606 INFO (pid:10028) [plugin] - coc.nvim initialized with node: v16.14.0 after 171ms
2022-02-14T01:57:32.524 INFO (pid:10028) [attach] - receive notification: showInfo []

## Describe the bug

set noexpandtab, set tabstop=4, set shiftwidth=4 and COC cause the wrong cursor position in bash shell script.

## Reproduce the bug

  ```vim
set bomb
set enc=utf-8
set fenc=utf-8
set nocompatible
set guifont=Ubuntu_Mono:h60

set tabstop=4
set shiftwidth=8

source ~/.vim/vim-plug/plug.vim
call plug#begin('~/.vim/plugged')
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
  ```

and open *.sh

and type

```
case
esac

case
e(*)sac  // (*) : wrong cursor posion

case
e(*)sac  // (*) : wrong cursor posion
```

## Screenshots (optional)

This bug occurs not only Windows but also in debin linux.

https://user-images.githubusercontent.com/83569599/153766059-59b8256f-4e4f-4ed5-a5c3-4d802d6681dc.mp4

**Comment by xvim64** [comment]
coc-cl
coc-clangd
coc-css
coc-go
coc-html
coc-java
coc-json
coc-powershell
coc-pyright
coc-r-lsp
coc-sql
coc-sumneko-lua
coc-svg
coc-tsserver
coc-vimlsp
coc-xml

I do not use "coc-sh" because of the "Server sh failed to start: Error: spawn UNKNOWN" error in Windows.

**Comment by xvim64** [comment]
> Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

these are my coc-*

coc-cl
coc-clangd
coc-css
coc-go
coc-html
coc-java
coc-json
coc-powershell
coc-pyright
coc-r-lsp
coc-sql
coc-sumneko-lua
coc-svg
coc-tsserver
coc-vimlsp
coc-xml

I do not use "coc-sh" because of the "Server sh failed to start: Error: spawn UNKNOWN" error in Windows.

**Comment by chemzqm** [comment]
Tried vim with your configuration, can't reproduce, could be issue with https://github.com/neoclide/coc.nvim/blob/master/autoload/coc.vim#L221

**Comment by xvim64** [comment]
> Tried vim with your configuration, can't reproduce, could be issue with https://github.com/neoclide/coc.nvim/blob/master/autoload/coc.vim#L221

I commented the line.

And It works well.

![1](https://user-images.githubusercontent.com/83569599/154874633-4de8ad85-c2f3-4227-a622-e3feae45abee.jpg)
![2](https://user-images.githubusercontent.com/83569599/154874637-953ca381-2faa-4592-9363-cf325eb408c6.jpg)

**Comment by xvim64** [comment]
> Tried vim with your configuration, can't reproduce, could be issue with https://github.com/neoclide/coc.nvim/blob/master/autoload/coc.vim#L221

https://github.com/neoclide/coc.nvim/issues/3664


not 'call cursor(l:curpos[1:])'

'normal! ==' causes the wrong cursor position

https://github.com/neoclide/coc.nvim/issues/3664

**Comment by chemzqm** [comment]
Try upgrade your vim and minimal vimrc, I can't reproduce

**Comment by xvim64** [comment]
> Try upgrade your vim and use minimal vimrc, I can't reproduce


https://user-images.githubusercontent.com/83569599/155049077-6072c2d9-aa49-497e-9e72-98bd3cd07a7d.mp4



[coc-debian-vimrc.zip](https://github.com/neoclide/coc.nvim/files/8113055/coc-debian-vimrc.zip)

**Comment by xvim64** [comment]
> Try upgrade your vim and use minimal vimrc, I can't reproduce

coc-debian-vimrc-mp4.zip has a mp4 video and all the coc configurations including coc in debian linux

The mp4 video captured by ffmpeg is very small, and can be played in mpv or mpc-be. Maybe The other players can't play it properly and not in this github.


[coc-debian-vimrc-mp4.zip](https://github.com/neoclide/coc.nvim/files/8113101/coc-debian-vimrc-mp4.zip)

**Comment by xvim64** [comment]
And this is the NeoVim in debian linux with mini.vim and a mp4 video.

[coc-debian-neovim-minivim-mp4.zip](https://github.com/neoclide/coc.nvim/files/8113600/coc-debian-neovim-minivim-mp4.zip)

**Comment by xvim64** [comment]
> ... I can't reproduce

Are you using the COC auto completion when completing ?

If so, type all characters without using the COC auto compleiton.

**Comment by chemzqm** [comment]
No, I didn’t

**Comment by Starslayerx** [comment]
I have samilar issue:
<img width="385" alt="截屏2022-04-05 11 50 03" src="https://user-images.githubusercontent.com/53030987/161675283-11f6b219-9bdf-40b5-9161-15cceb2473fe.png">

<img width="311" alt="截屏2022-04-05 11 50 24" src="https://user-images.githubusercontent.com/53030987/161675314-87e01cf9-a8ca-4c99-9528-96f3db38be60.png">

Then I press `Tab`  , and I got this

<img width="303" alt="截屏2022-04-05 11 50 35" src="https://user-images.githubusercontent.com/53030987/161675330-92449f2e-9c3d-4cc5-98f3-87303a5cc52a.png">

This never happened before, and I updated all my vim plugs and changed python version to 3.8.  
I'm not sure what caused this.

**Comment by chemzqm** [comment]
@Starslayerx seems not related, you need paste your key-mapping for `<tab>` by `:verbose imap <tab>`

**Comment by Starslayerx** [comment]
I thought it could caused by my snippet.  
`:verbose imap <tab>`
```
<Tab>       * <C-R>=UltiSnips#ExpandSnippet()<CR>
```

**Comment by chemzqm** [comment]
It's an issue with your ultisnips.

**Comment by Cnly** [comment]
I think I'm having the same problem here. I did a bisect and the first bad commit seems to be 5efefb74b4622559c6205ba46e6c5dc9e2077741, but I'm not sure where to go from there.

**Comment by Cnly** [comment]
I can't reproduce with @xvim64's config either, but I can reproduce with this one:

```vim
set nocompatible

set tabstop=4 shiftwidth=4

set rtp+=~/.vim/vim-plug
call plug#begin('~/.vim/bundle')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

I'm on mac and `NVIM v0.6.1` with `coc.nvim version: 0.0.80-c6483d2f`.
