### ISSUE TITLE
Unknown function: `coc#highlight#clear_win_matches`

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#3646]
Steps:

1. `export NVIM_COC_LOG_LEVEL=debug && export NVIM_COC_LOG_FILE=/tmp/coc.log`
1. `nvim src/workspace.ts`
1. `Vexplore`
1. you'll get `Unknown function: coc#highlight#clear_win_matches` error in /tmp/coc.log

**Comment by fannheyward** [comment]
Looks like `coc#highlight#clear_win_matches` is called in coc-yank, but I didn't find in coc.nvim and node-client.

https://github.com/neoclide/coc-yank/blob/69fc2deea53c176bd0c95c6b822ed5a63ab469ec/src/index.ts#L23-L25

**Comment by chemzqm** [comment]
Fixed on coc-yank.
