### ISSUE TITLE
Something in Outline's buffer-switch check undoes autochdir's directory changes in nvim

### ISSUE THREAD

**Issue by cincodenada** [neoclide/coc.nvim#3651]
## versions

vim version: NVIM v0.6.1
node version: v14.19.0
coc.nvim version: 0.0.80-812c6fa685
coc.nvim directory: /Users/joel/.vim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin

## Log of coc.nvim

2022-02-17T17:50:37.521 INFO (pid:15015) [plugin] - coc.nvim initialized with node: v14.19.0 after 24ms
2022-02-17T17:50:41.816 INFO (pid:15015) [attach] - receive notification: showInfo []

## Describe the bug

With `autochdir` enabled in nvim and coc installed, autochdir's directory change will be reverted if there is a window-local or tab-local directory set.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
set autochdir
```
- Start neovim with command: `nvim -u mini.vim`
- Split to two windows. In the first window: 
  - `:e /path/to/some/file`
  - `:lcd /some/other/path`
- Focus the second window, and then focus back on the first.
- `:verbose pwd`

You should observe that the first window briefly displays its filename as `file`, indicating it has a working directory of `/path/to/some`, before switching to `/path/to/some/file`, indicating that it has changed directories outside of `/path`. `:verbose pwd` returns `[window] /some/other/path` when it should return `[autochdir] /path/to/some`.

## Screenshots (optional)

Here is a short recording demonstrating the issue, and that disabling coc solves the issue: https://asciinema.org/a/CGgDMDbWn3HrKPdt7sl2NmBBn 

And here is a longer recording demonstrating the issue in nvim, then demonstrating regular vim not having the issue, then demonstrating an nvim without any config not having the issue: https://asciinema.org/a/iQe3cw7kO6KIcozHVP3lvK2Fb

## Additional info

A temporary workaround is that setting `outline.checkBufferSwitch` to `false` stops this behavior, and leaves `autochdir`'s directory changes alone.

This was the result of further investigation that narrowed this down to something in outline's checkBufferSwitch behavior, probably something in `_onBufEnter()`.

**Comment by speakk** [comment]
Can confirm, this has been relatively frustrating issue.

**Comment by cincodenada** [comment]
This has continued to be very frustrating, so I just did some more diving in with verbose logging and digging through `index.js`, and narrowed the problem down to the Outline functionality - I am quite certain now that something in Outline's buffer change callback is overriding the directory and causing this bug.

As such, I have found a workaround that works for me: setting `outline.checkBufferSwitch` to false prevents this bug from happening - autochdir's directory changes are left alone, if I set it back to true COC starts overriding them again. @speakk can you see if that workaround works for you as well? In case you're not familiar, you can run `:CocConfig` to open the config file, and add `"outline.checkBufferSwitch": false` to the JSON object there (or create a JSON object with just that key/value if you don't have one).


@chemzqm Please take another look at this and reopen, this is most definitely not default Vim behavior. I've made a very short screen cast (10 seconds) that demonstrates the problem, and demonstrates that disabling `outline.checkBufferSwitch` is a functional workaround, indicating that the problem lies within the outline functionality:
[![asciicast](https://asciinema.org/a/NEGWwYFxzdLKKKn5quvy83qnt.svg)](https://asciinema.org/a/NEGWwYFxzdLKKKn5quvy83qnt)
Watch the file path at the bottom of the windows - notice that at first when I switch buffers, only the filename is shown because `autochdir` changes to the directory containing the file, but it is quickly replaced with a much longer path, indicating something has changed the working directory.

After I set `outline.checkBufferSwitch` to false, switching buffers no longer demonstrates this broken behavior - `autochdir`'s changes are left alone, as they should be.

Thanks for all your work on this project!

**Comment by speakk** [comment]
Yes!! @cincodenada you rock for digging into this! Changing `outline.checkBufferSwitch` to false indeed seems to completely fix this issue. (I don't know what other side effects that has, but nonetheless this is a marked improvement until this is fixed)

**Comment by chemzqm** [comment]
Vim's bug when you check window variable by timer on buffer enter (coc.nvim use notification works like timer)
```vim
set nocompatible
set autochdir

autocmd BufEnter * call timer_start(100, 'CheckWindow')

function! CheckWindow(...) abort
  for i in range(1, winnr('$'))
    let res = getwinvar(i, 'mykey')
    if res == '1'
      return win_getid(i)
    endif
  endfor
  return -1
endfunction
```

**Comment by cincodenada** [comment]
Wow, what a weird bug, but that sure does reproduce it, I appreciate you digging in, it would have taken me ages to track that one down.

I'll keep the workaround in place for now and file a bug upstream with nvim then. Thanks!
