### ISSUE TITLE
'normal! ==' causes the wrong cursor position

### ISSUE THREAD

**Issue by xvim64** [neoclide/coc.nvim#3664]
## Reproduce the bug

in coc.nvim/autoload/coc.vim

214: 'normal! ==' causes the wrong cursor position problem.

  ```vim
set enc=utf-8
set fenc=utf-8
set nocompatible

set tabstop=4
set shiftwidth=4

set guifont=Ubuntu_Mono:h80

source ~/.vim/vim-plug/plug.vim
call plug#begin('~/.vim/plugged')
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
  ```

run `gvim -u mini.vim t.vim`

## Screenshots (optional)

1. Not commented 'normal! =='

https://user-images.githubusercontent.com/83569599/154972741-34a8d41a-aff6-42dd-bfa4-f9000f8fba77.mp4

2. Commented 'normal! ==' to '  "normal! ==  '

https://user-images.githubusercontent.com/83569599/154972799-f72420a1-ab63-4398-921d-bdf11964daa8.mp4

**Comment by chemzqm** [comment]
You have to figure out what happened, since I can't reproduce with my vim on different systems.
