### ISSUE TITLE
Is there a way to automatically close the buffer after installing the missing extensions in g:coc_global_extensions?

### ISSUE THREAD

**Issue by hungpham3112** [neoclide/coc.nvim#3668]
```
let g:coc_global_extensions = ['coc-json',
            \'coc-vimlsp',
            \'coc-snippets',
            \'coc-powershell',
            \'coc-markdownlint',]

```

After installing `coc_nvim` vim can auto-download missing extensions, but still have a window after that. How can auto-close it, maybe download in `silent` way?

**Comment by chemzqm** [comment]
It rarely happens, there are other ways to install extensions please read doc
