### ISSUE TITLE
CocList Sorted Alphabetical

### ISSUE THREAD

**Issue by ds2606** [neoclide/coc.nvim#3677]
When I open CocList, the list appears in different order each time. (Based on frecency maybe? Not sure.) In any case, it would be easier to navigate for me if the list was simply alphebetized. This seems easy to implement, just showing coclist in alphabetical order. However I do not see any documentation for doing this. Is there a way to do this already or can it be added? Thanks.
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/2286295/156662309-1fece41b-37e5-48e3-9494-454d093e492d.png">

**Comment by chemzqm** [comment]
Most recently used is perfered.

**Comment by ds2606** [comment]
Isn't it trivial to create a flag for normal listing? I don't know node or the coc api so it'd be a big overhead to write an extension

**Comment by ds2606** [comment]
It's confusing for me and I imagine many other users who are new to node to have a shuffled list ordering every time this is opened.

**Comment by chemzqm** [comment]
> Isn't it trivial to create a flag for normal listing?

I don't think it's necessary, you should get used to the filter feature or create key bindings to open list.

**Comment by ds2606** [comment]
I have a key binding to open the list, which doesn't affect the sorting of entries. The filter feature also doesn't address the confusing ordering, which makes it hard to know what is available in CocList as a new user. But I suppose it's your extension and you are free not to add a very simple and helpful feature.
