### ISSUE TITLE
PHP-Language Server does not index remote Files (NFS)

### ISSUE THREAD

**Issue by hjanuschka** [neoclide/coc.nvim#368]
**Result from CocInfo**
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2018 12:07:57)
node version: v8.9.0
coc.nvim version: 0.0.46
term: iTerm.app
platform: darwin

## Output channel: languageserver.phplang
DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is not loaded
DEBUG     Listening on STDIN

**Describe the bug**
working on files that are mounted via NFS, does not index files in LSP

**To Reproduce**
install php-language-server, mount filesystem via NFS, edit a php file

is there any limitation with using network mounted filesystems?

when i copy the folder 1:1 to a local directory the php-lsp triggers and indexes.

**Comment by chemzqm** [comment]
Looks like issue of language server, consider report it to https://github.com/felixfbecker/php-language-server

**Comment by hjanuschka** [comment]
thx, did so, https://github.com/felixfbecker/php-language-server/issues/698
