### ISSUE TITLE
Interrupted when typing Chinese characters fast

### ISSUE THREAD

**Issue by draftman9** [neoclide/coc.nvim#3681]
## Describe the bug
It would be interrupted when I type Chinese characters fast.
## Reproduce the bug
Please see the movie about 7 seconds, you will understand what I am talking about.
I want to repeat the sentence above in the movie. When I am typing "较", the coc.nvim is also working to complete my sentence. Unfortunately coc.nvim interrupts my typing and append a "j". I want to type Chinese characters without interruption. Can you find out what's wrong with coc.nvim?

The movie:
![视频_2022-03-05_110152](https://user-images.githubusercontent.com/99490289/156867188-5c44c0d9-ea93-4eec-8879-6be66558160c.gif)

**Comment by chemzqm** [comment]
You have to avoid completion by `"suggest.asciiCharactersOnly": true` in your configuration file.

**Comment by draftman9** [comment]
> avoid chinese word completion

Exactly you partly resolve my problem by your method. At the same time I could not get the suggest prompt of Chinese characters at all. I do not think you have solved this problem completely. Then could you achieve the function that I could get the prompt of characters while I would not be interrupted?
