### ISSUE TITLE
[coc.nvim]: Error on "doAutocmd": doc.matchAddRanges is not a function

### ISSUE THREAD

**Issue by miguelmota** [neoclide/coc.nvim#3688]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.0-dev+1192-g8ed9c8448
node version: v17.3.0
coc.nvim version: 0.0.80-ccd0b050e0
coc.nvim directory: /home/mota/Dotfiles/dotvim/bundle/coc.nvim
term: tmux
platform: linux
```

## Describe the bug

```
[coc.nvim]: Error on "doAutocmd": doc.matchAddRanges is not a function
```

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
filetype off
filetype indent on
call plug#begin('~/.vim/bundle')
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
call plug#end()
syntax on
```

- Start neovim with command: `nvim -u mini.vim`

- Operate vim.

How I installed neovim and bundles

```bash
yay -S neovim-nightly-bin
vim +PlugInstall
```

## Screenshots (optional)

![DeepinScreenshot_select-area_20220308215827](https://user-images.githubusercontent.com/168240/157381491-92579614-78ad-4499-b16d-0def4ef02538.png)

This error shows up randomly. Any idea what it is and how to fix it? Thanks

**Comment by chemzqm** [comment]
Some of your coc.nvim extension is broken check the log by `:CocOpenLog`

**Comment by miguelmota** [comment]
@chemzqm Any suggestions on how to update? Running `vim +PlugUpdate` says `copilot.vim: Already up to date.`

![DeepinScreenshot_select-area_20220309000507](https://user-images.githubusercontent.com/168240/157398726-e70c8766-c63e-4762-84f7-0bd830d31f62.png)

**Comment by chemzqm** [comment]
Your coc-yank needs upgrade.

**Comment by miguelmota** [comment]
@chemzqm thanks for help, I re-installed it with `:CocInstall coc-yank` and also ran `:CocUpdate` so hopefully that fixes it.
