### ISSUE TITLE
Reproduceable but almost random crash with rightleft set and Hebrew text in buffer

### ISSUE THREAD

**Issue by doronbehar** [neoclide/coc.nvim#369]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
```
## versions

vim version: NVIM v0.3.4
node version: v11.6.0
coc.nvim version: 0.0.46
term: rxvt-unicode-256color
platform: linux

## Error messages
```

**Describe the bug**
I have a specific text document written in Hebrew mostly and when I edit it and I try to insert certain text (only when `rightleft` is set), suddenly Neovim exits with code 1 without any particular reason. This happens only with Neovim, Vim doesn't crash like that.

**To Reproduce**

1. Put the following text in a buffer:
```
שלום bla,

On Sat, Jan 12, 2019 at 10:21:38AM +0200, Someone wrote:

> היי דורון,
> להוסיף עוד 115 ש״ח הוא נכון.
> 
> תודה וסליחה על אי ההבנה,
> bla
> 
>


```

2. `:set rightleft`
3. Try to insert the letter `s` at the last empty line.

I have no idea from where this issue arises, I'm only sure coc.nvim has been proven guilty because I've tested it with a clean configuration. The text is partially taken from an email I was about to send via mutt. I've tried to debug this on my own but I couldn't find a clue. Here is the [debug](https://gist.githubusercontent.com/doronbehar/0b5d8e9bdb87784d3e7299320961a341/raw/2dd012fcc64d9fe5c3eebb63e2d687e2068c5041/coc.nvim-crash-debug.txt)

**Comment by chemzqm** [comment]
It happens whenever autocompletion is triggered, I've disabled trigger completion for rightleft window.

**Comment by doronbehar** [comment]
That's a good workaround for the meantime but what if I'd still want to have autocompletion even in `rightleft` is set? I use this mode regularly and it's a shame I won't enjoy coc.nvim just because of this.

**Comment by chemzqm** [comment]
You can trigger completion manually, sometime it doesn't crash, or ask neovim to fix this problem.

**Comment by doronbehar** [comment]
I understand this is probably a bug with Neovim and not coc.nvim but I was hoping we could have investigated this better so the bug report for Neovim could be more concise, I'm pretty sure that with the information I've got now they'll tell me to contact you. Do you have any tips as for how can I debug this further? One thing that still perplexes me is that the [debug](https://gist.githubusercontent.com/doronbehar/0b5d8e9bdb87784d3e7299320961a341/raw/2dd012fcc64d9fe5c3eebb63e2d687e2068c5041/coc.nvim-crash-debug.txt) has `--INSERT--` in it so it means Neovim is truly going nuts there..

**Comment by chemzqm** [comment]
I got `E41: Out of memory!`, I'm not familiar with this, need help of neovim team.

**Comment by doronbehar** [comment]
@chemzqm , thanks for advising to ask help from the neovim guys, it has been proven useful. as you can see in https://github.com/neovim/neovim/issues/9542 . I've tested it with the patch and the crash is gone.

As for your original fix, I'd like to humbly suggest that perhaps https://github.com/neoclide/coc.nvim/commit/5f2f72b9a8cbfeb6d946e9802184cbd8ab392fa9 should be reverted and this Neovim bug should be mentioned in the docs along with an optional workaround and the patch?

**Comment by chemzqm** [comment]
Ok, I've added it to https://github.com/neoclide/coc.nvim/wiki/F.A.Q

**Comment by doronbehar** [comment]
Excellent, I noticed you've reverted that commit as well, thanks a lot.
