### ISSUE TITLE
Question: Weird syntax highlighting on completion after upgrade

### ISSUE THREAD

**Issue by lmburns** [neoclide/coc.nvim#3695]
I noticed this morning that `coc.nvim` and `coc-snippets` were both updated, so I'm unsure which is causing this, but after clicking on a completion, instead of the background highlight color clearing out once typing begins, it stays highlighted until I go into insert mode again. 

The example below is not a snippet and is instead a completion suggested by `rust-analyzer`. I was wondering if this is how it is supposed to be? If so, is there a way I can turn it off without downgrading `coc.nvim`? 

By the way, I just upgraded `coc` this morning since commit `ad3a11638ff78c1`, so I am unsure if the issue occurred before then. I also looked through the documentation and didn't see anything that had changed in order for me to try and see if I somehow had my configuration wrong.

Here's what I'm talking about, and thanks.
![rec](https://user-images.githubusercontent.com/44355502/157805498-58aed779-cec7-4b8b-bf05-d28631f01780.gif)

**Comment by chemzqm** [comment]
Use `"coc.preferences.snippetHighlight": false` to disable highlights for current placeholders.
