### ISSUE TITLE
Forced inserted '^Z' when continue typing ignore (or not related with) a suggestion box.

### ISSUE THREAD

**Issue by JangLuna** [neoclide/coc.nvim#3702]
## Result from CocInfo
Mac M1, Monterey v12.2.1
with iterm + zsh + Ohmyzsh + powerlevel10k
```vim
## versions
  vim version: VIM - Vi IMproved 8.2 8023489
  node version: v16.13.2
  coc.nvim version: 0.0.80-fed2dc99 2022-03-13 20:32:59 +0800
  coc.nvim directory: /Users/jang-yeongjin/.vim/plugged/coc.nvim
  term: iTerm.app
  platform: darwin
 
 ## Log of coc.nvim
 
 2022-03-13T23:53:36.125 INFO (pid:4739) [plugin] - coc.nvim initialized with node: v16.13.2 after 26ms
 2022-03-13T23:53:40.245 INFO (pid:4739) [attach] - receive notification: showInfo []
```
## Describe the bug

`^Z` is forced inserted when I try to continue typing not related with suggestion box.
if suggestion box is opened, I just try to continue typing ignore a suggestion box, then `^Z` is force inserted.

## Screenshots (optional)

![suggestion box is open](https://i.stack.imgur.com/Xgsny.png)

![ignore box and continue typing](https://i.stack.imgur.com/CRQLn.png)

**Comment by martinLew** [comment]
same problem in ubuntu

## versions

vim version: VIM - Vi IMproved 8.1 8013741
node version: v16.14.0
coc.nvim version: 0.0.80-fed2dc99 2022-03-13 20:32:59 +0800
coc.nvim directory: /home/martin/.vim/bundle/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-03-13T15:49:04.436 INFO (pid:7196) [plugin] - coc.nvim initialized with node: v16.14.0 after 45ms
2022-03-13T15:49:07.823 INFO (pid:7196) [completion-complete] - 1 results from: around
2022-03-13T15:49:17.686 INFO (pid:7196) [completion-complete] - 1 results from: around
2022-03-13T15:49:25.373 INFO (pid:7196) [completion-complete] - 1 results from: around
2022-03-13T15:50:15.428 INFO (pid:7196) [completion-complete] - 1 results from: around
2022-03-13T15:50:17.259 INFO (pid:7196) [completion-complete] - 1 results from: around
2022-03-13T15:51:11.783 INFO (pid:7196) [attach] - receive notification: showInfo []

**Comment by JangLuna** [comment]
@martinLew  R U solved this problem?

**Comment by xiyaowong** [comment]
https://github.com/neoclide/coc.nvim/commit/ed45a07a641c7e14ea20df223fb62b233d8c2001

**Comment by codemaster138** [comment]
> [ed45a07](https://github.com/neoclide/coc.nvim/commit/ed45a07a641c7e14ea20df223fb62b233d8c2001) only happens in vim

I'm also experiencing the issue in neovim

**Comment by codemaster138** [comment]
Resetting to commit `03ac5936ffc2abeb6bd3b487949f3e7cdd0abfc3` (on branch `release`) seems to have solved this issue for me.

**Comment by JangLuna** [comment]
@codemaster138 then, Nvim is working well now? I wanna decide to change nvim from vim

**Comment by codemaster138** [comment]
> @codemaster138 then, Nvim is working well now? I wanna decide to change nvim from vim

Yep, Nvim is working just fine (on the older commit, as I said). FYI, I also tested it in regular vim and it seems to really be the commit that @xiyaowong mentioned, so, if you reset to any commit before that, it solves the issue.

Of course, this is just a very temporary workaround.

**Comment by JangLuna** [comment]
@codemaster138 Oh! Thanks a lot. Actually, This is the first time I try vim for my main IDE, so this is first time I try coc also. 
I think I should try NVIM ASAP until this bug fix.

thanks a lot @xiyaowong too.
Have a nice dev life.

For notice to coc team, I will remain this issue open.

**Comment by otavioschwanck** [comment]
https://github.com/neoclide/coc.nvim/issues/3700

**Comment by koallen** [comment]
I tried resettings to `03ac5936ffc2abeb6bd3b487949f3e7cdd0abfc3` with neovim and it works like a charm! :+1:

**Comment by chemzqm** [comment]
Reproduced on old vim but not 8.2 8023489

**Comment by richox** [comment]
reproduced on nvim v0.6.0-dev+80-gc818d8df3

**Comment by zekena2** [comment]
it still happening to me as well NVIM v0.6.0-dev+43-g02bf251bb
I installed neovim from the community repository https://archlinux.org/packages/community/x86_64/neovim/ long time ago using simple `pacman -S neovim`
