### ISSUE TITLE
"Trigger snippet expand" Redundant Characters

### ISSUE THREAD

**Issue by wp231** [neoclide/coc.nvim#3704]
## Result from CocInfo

[CocInfo.log](https://github.com/neoclide/coc.nvim/files/8246077/CocInfo.log)

## Describe the bug

"Trigger snippet expand" Redundant Characters

## Reproduce the bug

When I use Ctrl + L Trigger snippet, it generates an redundant "^Z"
And the same letter is entered continuously, additional characters will be generated when triggered.

My vimrc
```vim
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

set hidden
set nobackup
set nowritebackup
set cmdheight=1
set updatetime=100
set shortmess+=c

inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>" :
    \ <SID>check_back_space() ? "\<TAB>" :
    \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
endfunction

imap <C-l> <Plug>(coc-snippets-expand)
```
## Other

Version :
system : Ubuntu 20.04.4 LTS
vim : 8.1

Plug : coc-nvim

Coc extensions :
coc-vimlsp
coc-snippets
coc-json

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/56443833/158201211-d7ef4c91-55bd-44d5-9b56-94c01c1cfe77.png)
![image](https://user-images.githubusercontent.com/56443833/158201238-fac60243-6ee3-4111-9dea-2f2626a77c42.png)
![image](https://user-images.githubusercontent.com/56443833/158201270-12f391fe-4529-444a-98d1-8b33f228559a.png)

**Comment by chemzqm** [comment]
Upgrade your vim or coc.nvim

**Comment by wp231** [comment]
I can't use Ctrl + L trigger "vimlsp function snippet"
But it work in "ccls for loop snippet"
