### ISSUE TITLE
coc-phpls wrong replace

### ISSUE THREAD

**Issue by hjanuschka** [neoclide/coc.nvim#371]
**Result from CocInfo**
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 30 2018 13:09:20)
node version: v10.11.0
coc.nvim version: 0.0.46
term: iTerm.app
platform: darwin

## Output channel: watchman
[Info  - 20:57:20] watchman watching project /xxx/plugins/kmm-xxx
[Info  - 20:57:20] subscribing "**/*.php" in /xxxx/plugins/kmm-xxx

## Output channel: php
[Info  - 20:57:20] Initialising
[Info  - 20:57:20] Initialised in 358 ms

**Describe the bug**
having
```php
$variable = "aaa";
```

typing `$var`  selection suggestion replaces it with `$$variable`

also posted the bug there: https://github.com/marlonfan/coc-phpls/issues/1 since i am not sure if this is LS or plugin specific

**To Reproduce**

sample vimrc (using vim 8.1 (macvim))

```

set hidden
set cmdheight=2
set updatetime=300
set shortmess+=c
set signcolumn=yes

call plug#begin('~/.vim/plugged-test')
Plug 'neoclide/coc.nvim', {'tag': 'master', 'do': 'yarn install'}
call plug#end()
```
using `PlugInstall` to fetch/build current master and then do a `CocInstall coc-phpls`

**Comment by chemzqm** [comment]
You need to add $ to iskeyword for php

**Comment by hjanuschka** [comment]
sorry to ask again, many thx for your help!

adding in vimrc
```
set iskeyword=$
```

does not fix it, is there any further documentation about that iskeyword?

**Comment by hjanuschka** [comment]
nevermind it fixed it.
