### ISSUE TITLE
Using 'packadd coc.nvim' to load the plugin requires manually starting the coc service

### ISSUE THREAD

**Issue by fatjing** [neoclide/coc.nvim#3718]
## Environment
platform: Windows 10
nodejs: 16.14.2
gvim: 8.2.4594
coc.nvim: the latest e76e3c9 commit from release branch
coc.nvim installed to vimfiles\pack\bundle\opt\coc.nvim

## Reproduce the bug

- Start gvim with command: `gvim -Nu NONE`
- Run `:packadd coc.nvim`
- Run `:CocInfo`
- Message showing "coc.nvim service not started, checking environment...Service stopped for some reason, try :CocStart"

After running CocStart, everything seems to be working fine

**Comment by chemzqm** [comment]
You have `g:coc_start_at_startup` set to 0

**Comment by fatjing** [comment]
Hi, I double checked and I'm pretty sure I don't have `g:coc_start_at_startup` set to 0

Actually starting the program with `gvim -Nu NONE` will ignore all user settings, isn't it?

And I find out that `g:coc_start_at_startup` do not exist after loading the plugin with `packadd coc.nvim`

![image](https://user-images.githubusercontent.com/1171924/159245685-0f5a25d7-0edf-4ac0-a9b1-41645b97f10f.png)

**Comment by fatjing** [comment]
That's strange. Git blame shows that line was written three years ago. But I've been using `au InsertEnter * packadd coc.nvim` to load the plugin and all seems to work fine since I installed the plugin two years ago. Only recently did I find out that it requires manually service starting.

**Comment by xiyaowong** [comment]
#3678
