### ISSUE TITLE
coc-rename doesn't support open new buffer for confirm rename

### ISSUE THREAD

**Issue by ripperapid** [neoclide/coc.nvim#372]
I don't know if this is a bug, if it is not implemented or if I am just doing it wrong.

When I use LanguageClient-neovim with ccls and use the rename feature on a symbol that exist in several files, a buffer is openend for each changed file and I can review the changes and save them or undo.

When using coc.nvim with ccls, and issue coc-rename on the same symbol, it changes everything correctly in the current document, and I also get a message that says "3 documents changed", which is correct. However, I don't get to see which files those are, and when looking in them I there are no applied changes. 

So it seems that the call to the language server (ccls) is correct, and it seems to deliver the correct response (3 documents), but it only affects the current file.

**Comment by chemzqm** [comment]
No such feature, and I do think it only needed when your language server is buggy, but PR is welcome.

I used to implemented this kind of feature in https://github.com/neoclide/rename.nvim

**Comment by ripperapid** [comment]
Ok. Thanks. But when it says "3 documents changed", they are supposed to be already changed on disk?

**Comment by chemzqm** [comment]
If the document is not loaded, they will be saved on disk.

**Comment by nagua** [comment]
Hey @ripperapid I just had the same problem as you described and I could debug it down to ccls sending a not standard compliant `TextDocumentEdit`. I developed an ugly patch and filed an issue in the ccls repo: https://github.com/MaskRay/ccls/issues/387
With the patch rename operations are applied correctly to closed files.

**Comment by chemzqm** [comment]
The rename feature have changed to apply changes to buffer instead of disk files when file not opened in vim. 
You have to save changed buffers to disk after rename.

**Comment by nagua** [comment]
That was quick, thank you very much. I already noticed that it opens a new buffer, but it didn't do that without your pr my fix. Hopefully ccls also fixes the issue for other lsp clients.

**Comment by chemzqm** [comment]
`<Plug>(coc-refactor)` is supported on master now.

**Comment by horta** [comment]
Thanks a lot for the change on the coc-rename command. However, changed buffers there were not previously opened when the renaming has been applied appears as unlisted buffers. Shouldn't them be listed so I can switch to them to confirm modification? I can only see them when I type ":ls!".

I'm using neovim and ccls LSP. If that is indeed a bug, I can open a new issue to report it.

**Comment by tim-phillips** [comment]
I was worried about running coc-rename during a large refactor and in my research I found this issue. Just wanted to report that coc-rename walked me through the process, letting me know that it was opening buffers for the changes and that I needed to run `:wa` to save all files or `:copen` to review changes in open buffers. Very nice!

**Comment by chemzqm** [comment]
> letting me know that it was opening buffers for the changes and that I needed to run :wa to save all files or :copen to review changes in open buffers.

It's provided by `<Plug>(coc-refactor)`
