### ISSUE TITLE
<Tab> to expand the first expandable selection

### ISSUE THREAD

**Issue by DehanLUO** [neoclide/coc.nvim#3721]
**Is your feature request related to a problem? Please describe.**
I have loaded [coc-snippets](https://github.com/neoclide/coc-snippets/) and [vim-snippets](https://github.com/honza/vim-snippets) in my vimrc.

For some reasons, I use `<Tab>` to
1. Characters ahead and navigate
2. Autoexpand the first item if it is expandable and nothing is selected in pum 
3. Do snippets jump 

And I use `<CR>` to complete after a completion is confirmed
These come to the followings
```vimscript
ino <silent><expr> <Tab>
	\ pumvisible()
	\		? complete_info()["selected"] == "-1" && coc#expandable()
	\			? coc#_select_confirm()
	\			: "\<C-n>"
	\		: coc#jumpable()
	\			? "\<C-r>=coc#rpc#request('doKeymap',['snippets-expand-jump',''])\<CR>"
	\			: "\<Tab>"

ino <silent><expr> <cr> complete_info()["selected"]!="-1"
	\ ? coc#_select_confirm() : "\<C-g>u\<CR>"
```

Now, take the default markdown snippet [fnt](https://github.com/honza/vim-snippets/blob/9e5219ae92f9b1b2ee23aff067618a6008a74fa5/UltiSnips/markdown.snippets) for example
```
snippet fnt "Footnote"
[^${1:${VISUAL:Footnote}}]$0

[^$1]:${2:Text}
endsnippet
```

If I typed `fnt` in insert mode, I could see the `fnt~` be the first selection in pum. And the `coc#expandable()` returned true at this time. `<Tab>` expanded the snippet successfully.

However, if I typed `fn`, the `fnt~` would still be the first target in pum with nothing selected. And the `coc#expandable()` returned false. This made `<Tab>` navigate to the first item in the pum only. Nothing would be expanded.

**Describe the solution you'd like**
Is there any ways to make `coc#expandable()` works for the first item at pum list?

**Describe alternatives you've considered**
Moving the cursor to the first selection with <C-n> before excuting `coc#expandable()`. 
Something like:
```vimscript
ino <silent><expr> <Tab>
	\ pumvisible()
	\		? complete_info()["selected"] == "-1"
	\			?	"\<C-n>" 
	\				if coc#expandable()
	\					coc#_select_confirm()
	\				en
	\			: "\<C-n>"
	\		: coc#jumpable()
	\			? \<C-r>=coc#rpc#request('doKeymap',['snippets-expand-jump',''])\<CR>"
	\			: <SID>check_back_space()
	\				? "\<Tab>"
	\				: coc#refresh()
```
But I do not know how to merge the `<C-n>` with `coc#expandable()` in one key map.

Thanks.

**Comment by chemzqm** [comment]
Expandable only checks current inserted text.  Adjust the key-mapping to fit your need.

**Comment by DehanLUO** [comment]
> Expandable only checks current inserted text. Adjust the key-mapping to fit your need.

Is there any way to combine `<\C-n>` and `coc#expandable()` together in a key map?

**Comment by chemzqm** [comment]
You can write a function for that, but I'm sure it's bad idea.

**Comment by chemzqm** [comment]
And you should use `<C-y>` to expand selected complete item and disable suggest.noselect to avoid the need for `<C-n>`

**Comment by DehanLUO** [comment]
> suggest.noselect

I use <C-n> to make the pum list from nothing selected to the first item selected. And this will sync the inserted text to the first item, which leads `coc#expandable()` return true and actives the expanding.

**Comment by chemzqm** [comment]
It doesn't sync the inserted text to the first item

**Comment by DehanLUO** [comment]
> It doesn't sync the inserted text to the first item

Actually, <C-n> does sync the inserted text. You can have a try.

**Comment by DehanLUO** [comment]
> It doesn't sync the inserted text to the first item

<img width="242" alt="image" src="https://user-images.githubusercontent.com/53093688/159679146-b2be7f0a-5d33-48bc-8710-e9a108f48d7b.png">
Type `<C-n>`
<img width="348" alt="image" src="https://user-images.githubusercontent.com/53093688/159679360-3cbce37e-e5d2-46f4-b36e-2546cab47a59.png">

**Comment by DehanLUO** [comment]
> Expandable only checks current inserted text. Type `<C-n>` to insert word of complete item or adjust the key-mapping to fit your need.

```vimscript
ino <silent><expr> <Tab>
	\ pumvisible()
	\		? complete_info()["selected"] == "-1"
	\			? coc#expandable()
	\				? coc#_select_confirm()
	\				: "\<C-n>"
	\			: "\<C-n>"
	\		:	coc#jumpable()
	\			? "\<C-r>=coc#rpc#request('doKeymap',['snippets-expand-jump',''])\<CR>"
	\			:	"\<Tab>"
```
It seems that `coc#expandable()` can not go well with `<C-n>` in **a vim function**. `<C-n>` made the pum from no-select to first-select, and the characters in the buffer changed from `fn` to `fnt`. `coc#expandable()` still worked on the origin characters `fn` and returned false.
 
I adjusted my usage to make `<Tab>` expanding when both conditions met
1. inserted text expandable
2. no-select in the pum

Thanks again for your information and advice.
Have a good day.
