### ISSUE TITLE
node-ipc malware

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc.nvim#3722]
https://github.com/advisories/GHSA-97m3-w2cp-4xx6

Does `node-ipc` used in this project?

**Comment by fannheyward** [comment]
No, `node-ipc` is not used by coc.nvim and its dependencies, you can check https://github.com/neoclide/coc.nvim/blob/master/yarn.lock

```
yarn why node-ipc
yarn why v1.22.15
[1/4] 🤔  Why do we have the module "node-ipc"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.11s.
```
