### ISSUE TITLE
[Feature request]Expand C macro

### ISSUE THREAD

**Issue by zoumi** [neoclide/coc.nvim#3725]
Is it possible expand C macro like VS Code?:
https://github.com/clangd/vscode-clangd/issues/203

![](https://user-images.githubusercontent.com/19859882/122844620-e6068580-d2b6-11eb-95e6-cdf5a9110885.png)

**Comment by fannheyward** [comment]
Fire `<Plug>(coc-codeaction)` on the macro, you'll get `Expand macro` action.

**Comment by zoumi** [comment]
Thank you!

**Comment by fannheyward** [comment]
Put your cursor on `MAX`, `:call CocActionAsync('codeAction', 'cursor')`.

I'm using this mapping: `nmap <silent> ga <Plug>(coc-codeaction-cursor)`

**Comment by zoumi** [comment]
Got it, Thank you!

**Comment by xiyaowong** [comment]
recommend a little extension https://github.com/xiyaowong/coc-lightbulb-    💡
