### ISSUE TITLE
Just Installed to Neovim: "E117: Unknown funtion: CocActionAsync"

### ISSUE THREAD

**Issue by collins-self** [neoclide/coc.nvim#3728]
#### Neovim version -
NVIM v0.6.1 on Windows
### I installed with vim-plug:
`
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile', 'yarn install'} `
#### And added the source to init.vim:
`
source $HOME/.config/nvim/plug-config/coc.nvim
`
I put the example config into coc.nvim
### Issue
When I launch neovim I get the error:
> Error detected while processing CursorHold Autocommands for "*":
 E117: Unknown function: CocActionAsync

(new to this so any help is appreciated)

**Comment by chemzqm** [comment]
You don't have coc.nvim loaded by your vim.
