### ISSUE TITLE
Unable to load global extension at /home/myname/.config/coc/extensions/node_modules/global: can't find name & engines in packege.json

### ISSUE THREAD

**Issue by Vitaliylevchuk** [neoclide/coc.nvim#3730]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
run:
```
rm -rf /home/myname/.config/coc/extensions/node_modules/global
```

**Comment by Vitaliylevchuk** [comment]
Unable to load global extension at /home/myname/.config/coc/extensions/node_modules/global: packege.json not found
