### ISSUE TITLE
Auto location list is flaky 

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#374]
**Result from CocInfo**
vim version: NVIM v0.3.4
node version: v11.7.0
coc.nvim version: 0.0.47
term: xterm-256color
platform: linux

**Describe the bug**
Auto preview locations seems to randomly start and stop working. 
**To Reproduce**
goto references see that auto preview usually does not open.

**Comment by chemzqm** [comment]
I can't reproduce you problem. Do you mean `--auto-preview` in `:CocList` command?

**Comment by Avi-D-coder** [comment]
I have never gotten a preview when using  `:CocList location --auto-preview`
I have had a preview show up on this symbol when using `nmap <silent> gr <Plug>(coc-references)`

I tried `"list.autoPreview":true", but no luck.
![ezgif-2-cf078c9aeebb](https://user-images.githubusercontent.com/29133776/51633774-7262c180-1f20-11e9-8c00-14bfff763b99.gif)

**Comment by chemzqm** [comment]
You should not use `CocList location --auto-preview` but `CocList --auto-preview location` instead.

`"list.autoPreview":true"` it's true by default, it means change preview buffer on line change, but `--auto-preview` means start preview on list visible.

**Comment by chemzqm** [comment]
You press p on normal mode
