### ISSUE TITLE
typescript is not expanding LSP snippet

### ISSUE THREAD

**Issue by otavioschwanck** [neoclide/coc.nvim#3747]
Instead of going to snippet, it insert $1
![Kapture 2022-04-06 at 00 09 48](https://user-images.githubusercontent.com/9551316/161888410-52f92935-8f18-466b-9735-7638123fefc3.gif)

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Seems is not snippet.
