### ISSUE TITLE
COC doesnt work, I dont get any code completion

### ISSUE THREAD

**Issue by itsrxmmy** [neoclide/coc.nvim#3755]
## Describe the bug

None of my coc plugins work. The linter works and shows my errors, but no code completion appears.

## Reproduce the bug

Open a file with nvim, start typing

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by itsrxmmy** [comment]
what do you mean? Do you mean the config listed in this repository? Because that didnt fix it at all

**Comment by fannheyward** [comment]
Minimal vimrc means you only install coc.nvim to check it works or not.

**Comment by itsrxmmy** [comment]
So am I supposed to uninstall all my plugins?

**Comment by CharlieCheckpt** [comment]
Hi, in case this may help, I had the same issue. 
It seems that `set paste` in my init.vim was the culprit. I don't know exactly why, but removing it, I get back auto completion.
