### ISSUE TITLE
coc.nvim preventing me from using emmet vim. 

### ISSUE THREAD

**Issue by rlgn** [neoclide/coc.nvim#3759]
I have the coc-tsserver extension installed. In my .vimrc, I had this set as let g:user_emmet_leader_key='<C-s>'

Autocompleting does the following

`div<C-s>, -> div,`

There's seems to be something preventing the emmet vim from following its leader key.

What do I need to disable to get this to work?

**Comment by fannheyward** [comment]
Try https://github.com/neoclide/coc-emmet

**Comment by chemzqm** [comment]
The key-mapping is not controlled by coc.nvim, you have to adjust it
