### ISSUE TITLE
client coc abnormal exit with: -1

### ISSUE THREAD

**Issue by MacGuffinLife** [neoclide/coc.nvim#376]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
Service not started
**Describe the bug**
When I open the vim ,the bottom of vim show “client coc abnormal exit with: -1
**To Reproduce**
Open the vim

**Screenshots**

**Comment by MacGuffinLife** [comment]
Of course I have reinstall coc and rpc many times

**Comment by chemzqm** [comment]
The node process get killed, but I don't know why.
Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim to get the log of coc.

**Comment by MacGuffinLife** [comment]
I get in the plugged  folder ,and try `yarn install`and `yarn build`,then ,After I do CocRestart,the issue has missed.So, maybe the install.sh or network has some trouble

**Comment by MacGuffinLife** [comment]
I test the completion,all is OK now

**Comment by 30-silver** [comment]
Still having this problem on stock vim on stock Ubuntu. Therefore coc.nvim is broken out of the box and should be fixed. Idk what the cause of this error is but it's a pretty major one.

**Comment by chemzqm** [comment]
You have to provide detail information to make it reproducable for us.

**Comment by YadominJinta** [comment]
```
Error: coc.nvim requires node >= v12.12.0, current version: v10.19.0
```

Ubuntu focal still using node 10, so can't run the lastest coc.

**Comment by Diego27012001** [comment]
I had the same problem, I solved it by putting another version of node (nvm) by default, since the previous one had been accidentally removed.

**Comment by chemzqm** [comment]
> ```
> Error: coc.nvim requires node >= v12.12.0, current version: v10.19.0
> ```
> 
> @30-silver Ubuntu focal still using node 10, so can't run the lastest coc.

Install new version of nodejs or use old version coc.nvim.

**Comment by kevinzu007** [comment]
发现是因为node版本不够高，低于要求版本了
