### ISSUE TITLE
coc-tabnine's completion trigger twice instead of once

### ISSUE THREAD

**Issue by heqiliao** [neoclide/coc.nvim#3761]
## Result from CocInfo

<img width="1706" alt="image" src="https://user-images.githubusercontent.com/12890484/162953146-af6c1658-83d4-4d47-8db7-ea1af3e9b0e5.png">

## Describe the bug

coc-tabnine's completion trigger twice. 
eg.
I type `us` and expected result is `user`, but after I click `enter`, the result is `userer`

I think there may be some problem with newest release version of coc.nvim, b/c it didn't happen this case in earlier version which I installed last week.

After I used earlier release version folder(coc.nvim) to replace `~/.vim/plugged/coc.nvim`, then the completion will only trigger once which is what we expected.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

<img width="241" alt="image" src="https://user-images.githubusercontent.com/12890484/162953374-f39583f4-2b2c-47d9-8abd-c8085abc1da4.png">
<img width="256" alt="image" src="https://user-images.githubusercontent.com/12890484/162953407-6bbd6a76-68c9-4430-9a5e-39b4a11a0364.png">

<img width="291" alt="image" src="https://user-images.githubusercontent.com/12890484/162953528-6b2f1730-f3db-43a4-9365-b097c3864fe7.png">
<img width="234" alt="image" src="https://user-images.githubusercontent.com/12890484/162953760-96a0ef51-6f61-45cd-8e16-723d404c39ec.png">

<img width="249" alt="image" src="https://user-images.githubusercontent.com/12890484/162954175-44b0b1f3-9085-459d-9536-56ff70b3a026.png">
<img width="315" alt="image" src="https://user-images.githubusercontent.com/12890484/162954318-dc8c2848-434e-415e-a1b5-256f7c764ab7.png">

<img width="259" alt="image" src="https://user-images.githubusercontent.com/12890484/162954620-1b7bb948-66eb-4f86-bf87-408e2a442162.png">
<img width="163" alt="image" src="https://user-images.githubusercontent.com/12890484/162954733-c8afee4e-6e74-4ec0-bffb-8bd17149c2e2.png">

The content after the cursor shouldn't exist.

**Comment by chemzqm** [comment]
Reproduced on vim8

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by heqiliao** [comment]
Great! Tks
