### ISSUE TITLE
Trigger snippet failed

### ISSUE THREAD

**Issue by wp231** [neoclide/coc.nvim#3765]
## Result from CocInfo

```Info
## versions

vim version: VIM - Vi IMproved 8.1 8013741
node version: v16.14.0
coc.nvim version: 0.0.80-70658364 2022-04-15 23:21:57 +0800
coc.nvim directory: /home/samuel/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-04-16T13:58:34.870 INFO (pid:3091) [services] - registered service "languageserver.ccls"
2022-04-16T13:58:34.871 INFO (pid:3091) [services] - registered service "languageserver.bash"
2022-04-16T13:58:35.026 INFO (pid:3091) [plugin] - coc.nvim initialized with node: v16.14.0 after 216ms
2022-04-16T13:58:35.045 INFO (pid:3091) [services] - registered service "vimlsp"
2022-04-16T13:58:35.045 INFO (pid:3091) [services] - vim language server state change: stopped => starting
2022-04-16T13:58:35.193 INFO (pid:3091) [services] - vim language server state change: starting => running
2022-04-16T13:58:35.196 INFO (pid:3091) [services] - service vimlsp started
2022-04-16T14:01:06.899 INFO (pid:3091) [attach] - receive notification: showInfo []
```

## Describe the bug

"Ctrl + j" trigger snippet failed

## Reproduce the bug

When I see the trigger with `Ctrl + j` it produces an error

```vim
inoremap <silent><expr> <TAB>
  \ pumvisible() ? "\<C-n>" :
  \ <SID>check_back_space() ? "\<Tab>" :
  \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

let g:coc_snippet_next = '<c-j>'

imap <C-j> <Plug>(coc-snippets-expand-jump)
```

After removing the TAB key mapping and `coc-snippets-expand-jump`
it's work

```vim
let g:coc_snippet_next = '<c-j>'
```

## Screenshots (optional)
`Tab` to choose
![image](https://user-images.githubusercontent.com/56443833/163663651-f9453280-f0ca-437b-8d41-0cc49b1d0fb6.png)

`Ctrl + j` trigger
![image](https://user-images.githubusercontent.com/56443833/163663871-060652d6-8bd9-4142-98a4-af165a7f667e.png)

After removing the TAB key mapping and `coc-snippets-expand-jump`

![image](https://user-images.githubusercontent.com/56443833/163664070-55d8861f-64de-4e38-818e-8e7d7085c480.png)

![image](https://user-images.githubusercontent.com/56443833/163664146-31479374-f493-40f7-98e5-e552e91fcc86.png)

**Comment by chemzqm** [comment]
Check `:verbose imap <C-j>`, tried your vimrc and works expected on vim.

**Comment by chemzqm** [comment]
You should type full trigger characters for trigger snippets, you only typed `fun` from your screenshot.
You have to confirm completion instead if you want to expand snippet in your pum.

**Comment by wp231** [comment]
![image](https://user-images.githubusercontent.com/56443833/163670478-06cc8239-3aff-4651-8d50-03ce1e115cf7.png)

`Ctrl + j`

![image](https://user-images.githubusercontent.com/56443833/163670491-a7c5f0b6-b8c4-47f2-ac03-ae4b7e4b1b56.png)

when i use `tab`

![image](https://user-images.githubusercontent.com/56443833/163670505-507033b3-4ad2-411b-80c6-0afe69333d48.png)

It will automatically generate `tion`
`Ctrl + j`

![image](https://user-images.githubusercontent.com/56443833/163670549-ffd3e03a-d4a8-4d75-9551-9045f2aabb4d.png)
 
It can't be triggered either.


![image](https://user-images.githubusercontent.com/56443833/163670590-ecc23b0e-a9ad-4667-9ae7-ab8554ae7c46.png)

`Ctrl + j` is not occupied by other keys

**Comment by wp231** [comment]
The snippet provided by "language server" will fail

**Comment by wp231** [comment]
```vim
inoremap <silent><expr> <C-j>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ coc#refresh()
```

I use this method to map <C-j> and successfully fix the problem that cannot be triggered
