### ISSUE TITLE
[Question] Set coc_snippet_prev = '<S-Tab>' overwrite jump prev in the popup.

### ISSUE THREAD

**Issue by hungpham3112** [neoclide/coc.nvim#3766]
As coc-nvim document, this script used to map <S-tab> to jump the previous item in list

```
inoremap <silent><expr> <S-Tab>
  \ pumvisible() ? "\<C-p>" :
  \ coc#expandableOrJumpable() ?
  \ "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
  \ <SID>check_back_space() ? "\<S-Tab>" :
  \ coc#refresh()
```

It worked well but after `let g:coc_snippet_prev = '<S-Tab>'`, `<S-Tab>` only use for jump and expand snippet, not for jumping previous item in popup. `<Tab>` can use for both snippet jumping and popup next.

https://user-images.githubusercontent.com/75968004/163755537-22f545dd-4276-4fa3-8669-7eac00b7bbe1.mp4

How can I use `<S-Tab>` for both jumping previous item in popup and previous placeholder in snippet. Thanks

**Comment by chemzqm** [comment]
It's expected `g:coc_snippet_prev` is used to create buffer key-mapping when snippet activated, so it has higher priority.
You can use another key or empty string instead.

**Comment by chemzqm** [comment]
There's a check for `g:coc_snippet_next` https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/snippet.vim#L49
not checked for `g:coc_snippet_prev` since it doesn't make any sense to use the same key for snippet next and snippet prev.

**Comment by hungpham3112** [comment]
> There's a check for `g:coc_snippet_next` https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/snippet.vim#L49 not checked for `g:coc_snippet_prev` since it doesn't make any sense to use the same key for snippet next and snippet prev.

I don't say use same key for snippet next and snippet prev. I want to use snippet prev and prev item in popup as same key.
