### ISSUE TITLE
coc-references to a symbol has no preview window when the symbol appear in two places

### ISSUE THREAD

**Issue by persytry** [neoclide/coc.nvim#3768]
I use <plug>coc-references to a symbol work well when the symbol appeared more than three places:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/88146305/163903842-6499243e-ae08-4c3e-a910-91ca04da52a0.png">
There are preview window and it can jumped as expected.
But if the symbol appeared in two places, then may be some error, the preview window is gone, and can not jumped when I type \<CR>.
<img width="345" alt="image" src="https://user-images.githubusercontent.com/88146305/163904462-fba47a5d-9ea5-4452-b9a5-aef23204b8eb.png">
Is there some option to handle this situation? like this, the behavior of coc-references for appeared two place same as more than three places?

**Comment by chemzqm** [comment]
Try minimal vimrc.

**Comment by persytry** [comment]
I found the problem, that is `set noequalalways` option is on. 
And refer to #3012 , New window creation issues (for jump to definition etc) with noequalalways (E36) .
