### ISSUE TITLE
Taking too long to write a buffer

### ISSUE THREAD

**Issue by jmolero** [neoclide/coc.nvim#378]
Thanks for this awesome plugin! I've been using it for a while and I really like it.

I found the following issue. I was using coc-eslint and coc-tsserver in a javascript project.

**Result from CocInfo**

```
## versions

vim version: NVIM v0.3.4
node version: v8.11.3
coc.nvim version: 0.0.49
term: Apple_Terminal
platform: darwin

## Error messages

## Output channel: tsserver
[Info  - 8:40:02 PM] Forking TSServer
PATH: /usr/local/bin:/usr/local/sbin:/opt/local/sbin:/opt/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/X11/bin
[Info  - 8:40:02 PM] Started TSServer
{
  "path": "/Users/jorge/.config/coc/extensions/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.2.1",
    "version": "3.2.1"
  }
}

## Output channel: eslint
[Info  - 8:40:02 PM] ESLint server running in node v8.11.3
[Info  - 8:40:03 PM] ESLint library loaded from: /Users/jorge/myproject/node_modules/eslint/lib/api.js
(node:19858) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "airbnb-base")
```

**Describe the bug**

Takes too long to save a text file that should not be processed by coc.nvim because it's not javascript. I made my first profile and this is what I found: 

```
 FUNCTIONS SORTED ON TOTAL TIME
 
 count  total (s)   self (s)  function
 
     1  13.363702   0.000020  <SNR>91_SyncAutocmd()
     1  13.363682   0.000020  coc#rpc#request()
     1  13.363662  13.363654  <SNR>94_request()
```

It took 13 seconds to write the buffer.

**To Reproduce**

1. Open a javascript project
2. Open a long text file with numbers in that project. 
3. Use the sort command to sort all the lines in the file.
4. Save the file
5. Wait for 13 seconds until neovim responds

**Comment by chemzqm** [comment]
Can't reproduce, consider paste verbose output:  https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by jmolero** [comment]
I tried the verbose output and didn't see anything wrong. 
This is the profile function code. I think this is what's needed:
```
FUNCTION  <SNR>94_request()
Called 1 time
Total time: 234.550356
 Self time: 234.550348

count  total (s)   self (s)
    1   0.000015   0.000007   let chan_id = s:get_channel_id(self)
    1              0.000002   if !chan_id | return '' | endif
    1              0.000001   try
    1              0.000001     if s:is_vim
                                  return nvim#rpc#request(chan_id, a:method, a:args)
                                endif
    1            234.550310     return call('rpcrequest', [chan_id, a:method] + a:args)
                              catch /^Vim\%((\a\+)\)\=:E475/
                                echohl Error | echom '['.self.name.'] server connection lost' | echohl None
                                let name = self.name
                                call s:on_exit(name, 0)
                                execute 'silent do User ConnectionLost'.toupper(name[0]).name[1:]
                              endtry
```

It took even longer this time. I uninstalled coc-eslint and ts-lint since I'm using ale for now, so it must be from coc-tsserver. That problem doesn't happen when coc is disabled.
Any idea why the connection is lost?

Thanks for taking a look at this.

**Comment by chemzqm** [comment]
>  I uninstalled coc-eslint and ts-lint since I'm using ale for now, so it must be from coc-tsserver. 

coc-tsserver doesn't related with coc-eslint, does the problem exists with coc-tsserver or coc-eslint?
I don't think the connection is lost, check the output from `:messages`.
