### ISSUE TITLE
[coc.nvim] build/index.js not found, please install dependencies and compile coc.nvim by: yarn install - VIM8

### ISSUE THREAD

**Issue by santos3du** [neoclide/coc.nvim#3786]
I had installed nodejs <v17.8.0>, npm<8.5.5> and yarn<1.22.18>.
I've been removed all stuffs previously open this issue on my Manjaro and reinstalled all of this again.
But the error message of title appears again.
I follow documentartion of this [link](https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim) and used release branch
![Screenshot_20220426_110839](https://user-images.githubusercontent.com/11688158/165318989-130f218f-d20c-4cff-b974-cc48eca2b32b.png)
.

**Comment by chemzqm** [comment]
It's broken or no read access on your file system.

**Comment by santos3du** [comment]
Guys, I remove all stuffs  and reinstalled all again, so problem finally was solved.
Thanks for your time and help, @chemzqm. Please close this issue.
