### ISSUE TITLE
Show preview window side by side the code completion suggestion window.

### ISSUE THREAD

**Issue by LinArcX** [neoclide/coc.nvim#379]
In eclipse or another ide's when you type some charachters, a pop-up window appear and you can see documentation about every item in a side by side fashion. just like this:
https://www.kompf.de/java/images/firststeps-eclipse.png
Currently i can see preview buffer in top of nvim. and close it when completino done:
https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#improve-completion-experience
How can i set the position of pop-up(for documentation) like eclipse ide?
Is there any option already?

**Comment by chemzqm** [comment]
Checkout #38, floating window is not on master of neovim yet, and looks like vim is going to support popup window which is something similar.

**Comment by LinArcX** [comment]
Awesome. thank you.
