### ISSUE TITLE
How to style float window, set border and background?

### ISSUE THREAD

**Issue by seriiserii825** [neoclide/coc.nvim#3792]
In coc-settings.json i added dialog.floatBorderHighlight
https://i.imgur.com/s7ASxci.png

But nothing's happend. 

Also in schema.json i founded this setting https://i.imgur.com/srfiPUR.png

But i can't understand where to set them. 

Thank you for help.

**Comment by chemzqm** [comment]
`:h coc-config-float` in your coc-settings.json
