### ISSUE TITLE
Start a service programatically

### ISSUE THREAD

**Issue by dsirov** [neoclide/coc.nvim#3793]
I am trying to create a command that updates all my neovim plugins (incl. coc and its extensions) and 3rd party stuff as well (like language servers)

function! Update()
    PlugUpgrade
    PlugClean
    PlugUpdate --sync
    CocStart
    CocUpdateSync
    CocCommand clangd.update
    CocCommand java.updateLanguageServer
    UpdateRemotePlugins
endfunction

However, one cannot call CocCommand clangd.update when the clangd service is not running.
I have not found a way to start it programatically (tried to use CocAction("toggleService"), but to no avail).
I might be missing something here.

Currently my workaround is to open files that trigger related services (test.c, test.java) and then execute this.
I was wandering whether there was a cleaner solution.

Thanks!

**Comment by chemzqm** [comment]
To active extension checkout `:h CocAction('activeExtension')`.
You may also need `:call CocAction('runCommand', ...)` to replace `:CocCommand` which send notification to node.
