### ISSUE TITLE
Basic floating window support

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#38]
**Is your feature request related to a problem? Please describe.**

* Use floating window for documentation of completion item preview.
* Use floating window for showing message of hover action.
* Use floating window for diagnostic messages, instead of echo them.
* Use floating window for signature help, isntead of echo.

**Comment by chemzqm** [comment]
Done.

**Comment by purpleP** [comment]
@chemzqm Can't find in docs how to make coc.nvim to show signature help in floating window. Can you help?

**Comment by chemzqm** [comment]
@purpleP it should just work, but I don't what happened for you, checkout:
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by dakom** [comment]
Same... @purpleP did you figure it out?

I get floating windows for autocomplete but not other diagnostics 

For example, I have this set: 
```
nmap <silent> <Leader>i <Plug>(coc-diagnostic-info)
```

and doing `Leader-i` shows me the diagnostics in a bottom pane (forget which list this is - but it's not hover)

**Comment by purpleP** [comment]
It works for me now...

пн, 26 авг. 2019 г., 16:24 David Komer <notifications@github.com>:
