### ISSUE TITLE
coc-snippets: coc_nvim_1.workspace.createMru is not a function

### ISSUE THREAD

**Issue by docwhat** [neoclide/coc.nvim#380]
**Result from CocInfo**

``` markdown
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.49
term: tmux-256color
platform: darwin

## Error messages

## Output channel: watchman
[Info  - 12:04:38] watchman watching project /Users/docwhat/.dotfiles
[Info  - 12:04:38] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in /Users/docwhat/.dotfiles
[Info  - 12:04:38] subscribing "**/.eslintignore" in /Users/docwhat/.dotfiles
[Info  - 12:04:38] subscribing "**/package.json" in /Users/docwhat/.dotfiles
[Info  - 12:04:38] subscribing "**/{.prettierrc,.prettierrc.json,.prettierrc.yaml,.prettierrc.yml,.prettierrc.js,package.json,prettier.config.js}" in /Users/docwhat/.dotfiles

## Output channel: prettier

## Output channel: highlight
[Info  - 12:04:38] Highlight server running in node v8.9.0
```

**Describe the bug**

Upon neovim startup I get this message:

```
[coc.nvim] Error on active extension coc-snippets: coc_nvim_1.workspace.createMru is not a function
```

**To Reproduce**

1. Install `coc.nvim` version v0.0.49
2. Install `coc-snippets` 1.0.5
3. Start neovim

**Comment by docwhat** [comment]
This happened before with `coc-pairs`.

Maybe there is some way for `coc-snippets` to depend on the `coc.nvim` version. With proper npm dependency checks this wouldn't happen.

Could the `coc.nvim` npm package be moved entirely out of the vim plugin and installed as a dependency?  Both the vim plugin _and_ the extensions could depend on it the version that way?

**Comment by docwhat** [comment]
Workarounds:

1. Roll back `coc-snippets` to 1.0.4:

    ``` sh
    $ cd ~/.config/coc/extensions
    $ yarn add coc-snippets@1.0.4
    ```
2. Use the latest version of the `coc.nvim` plugin. e.g., if using `vim-plug`, then remove the `{ 'tag': 'v*' }`.

**Comment by chemzqm** [comment]
> Maybe there is some way for coc-snippets to depend on the coc.nvim version. 

There is `"engines"` in package.json, but it doesn't help for unpublished version.

CI could help to avoid this kind of problem, but it's not high priority for now.
