### ISSUE TITLE
Docs' example configuration crashes neovim when using it in lua file

### ISSUE THREAD

**Issue by brunobmello25** [neoclide/coc.nvim#3806]
Steps to reproduce:

Setup init.lua like this:

- Install neovim v0.7.0
- Install latest packer version
- Setup init.lua like this:

```
require('coc-config')

return require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use { 'neoclide/coc.nvim', branch = 'release' }
end)
```

- add lua folder in the same directory that init.lua is, and in this new directory add coc-config.lua with the following content:

```
vim.cmd([[
  -- Copy and paste docs example config here
]])
```

- See the following error:
![image](https://user-images.githubusercontent.com/29875060/167309006-4973b246-02d0-49fd-919b-50485bedc8d9.png)

**Comment by chemzqm** [comment]
Avoid use script scoped function in your lua.cmd

**Comment by brunobmello25** [comment]
what would be the proper way to setup coc with lua files then? Docs don't really specify this

**Comment by chemzqm** [comment]
Use global function should helps or maybe covert the function to lua function.
