### ISSUE TITLE
show JumpDefinition in floating preview window

### ISSUE THREAD

**Issue by nikkegg** [neoclide/coc.nvim#3817]
**Is your feature request related to a problem? Please describe.**
I have jumpDefinition keybinding which shows definitions of a function in CoCList
```nnoremap <silent><nowait> <space>d :call CocAction('jumpDefinition', v:false)<CR>```

**Describe the solution you'd like**
I would like to amend this mapping to open the definition in pop-up window, in the same way, that ```doHover``` does for documentation

**Describe alternatives you've considered**
I have tried passing different arguments to CocAction as well as changing ```coc.preferences.jumpDefinition``` but to no avail.

**Additional context**
<img width="1103" alt="Screenshot 2022-05-13 at 12 38 55" src="https://user-images.githubusercontent.com/64557473/168275754-a888677a-ec85-42f1-a086-bc245b714247.png">

**Comment by chemzqm** [comment]
You can use extensions like `coc-fzf`, `coc-telescope` if you don't want to use `CocList` or you can handle the locations yourself `:h CocLocationsChange`
