### ISSUE TITLE
Error with dein

### ISSUE THREAD

**Issue by taigacute** [neoclide/coc.nvim#382]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
```
## versions

vim version: NVIM v0.3.1
node version: v10.15.0
coc.nvim version: 0.0.49
term: xterm-256color
platform: linux

## Error messages
```
same as macos 10.13.6 neovim 0.3.3
**Describe the bug**
got some error message
```
[dein] Error generating helptags:
[dein] Vim(helptags):E154: Duplicate tag "coc-list-sources" in file /home/pendragon/.config/dein/.cache/init.vim/.dein/doc/coc.txt
[dein] function dein#install[1]..dein#install#_update[38]..<SNR>24_update_loop[5]..<SNR>24_install_async[9]..<SNR>24_done[7]..dein#install#_recache_runtimepath[19]..<SNR>24_helptags, line 12
```

**To Reproduce**

1. Install  coc with dein

**Screenshots**
![45](https://user-images.githubusercontent.com/41671631/51813433-3ef1af80-22f1-11e9-8a30-491fb6c4076d.png)

**Comment by chemzqm** [comment]
I've add test to avoid this issue.

**Comment by taigacute** [comment]
> I've add test to avoid this issue.

Do  you have fix it?

**Comment by taigacute** [comment]
> It's fixed

yeah  it works well
