### ISSUE TITLE
add similar option `coc.preferences.jumpCommand` for `do:defaultaction`

### ISSUE THREAD

**Issue by persytry** [neoclide/coc.nvim#3829]
My coc-setting.json:
```json
"coc.preferences.jumpCommand": "tab drop",
"list.insertMappings": {
    "<CR>": "action:drop"
}
```
I want all coc commands as default to jump to existing or new tab, except for the <CR> key to open file to this tab.
But 'action:drop' does not work on non-file commands, while 'do: defaultAction' does.
Could you add a similar ` coc. Preferences. JumpCommand ` options for ` do: defaultaction `? When the selected item is a file, the 'TAB drop' or 'drop' worked. If this option is not configured, the ` coc. Preferences. JumpCommand ` configuration would be work.

**Comment by chemzqm** [comment]
你先学学怎么表达吧，看不懂你说的啥
