### ISSUE TITLE
给`do:defaultaction`增加一个选项

### ISSUE THREAD

**Issue by persytry** [neoclide/coc.nvim#3830]
我的`coc-setting.json`有如下配置:
```vim
"coc.preferences.jumpCommand": "tab drop",
"list.insertMappings": {
    "<CR>": "action:drop"
}
```
我想要的效果是`<Plug>(coc-definition)`, `action:open`等coc关于跳转的命令,全都走默认`tab drop`的方式, 但是我希望按回车键走的的`drop`的方式(就是直接在当前tab下打开目标文件).
但是当我想要通过CocList窗口执行某个命令的时候, 会有`Action drop not found`的报错:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/88146305/169520695-24f2e365-425a-4751-97d2-2872a6287a38.png">

```vim
"list.insertMappings": {
    "<CR>": "do:defaultaction"
}
```
当我尝试把回车键变成`do:defaultaction`的时候,当然是没有上述的报错了,但是打开文件的时候却是以`tab drop`的方式,而我想要直接`drop`的方式.
所以能不能增加某个配置项来支持一下这种情况呢?或者已经有类似的解决方案了,拜请告知,谢谢

**Comment by chemzqm** [comment]
```json
  "list.source.location.defaultAction": "drop",
```
给每个支持 drop 的 list source 设置

**Comment by chemzqm** [comment]
或者你用 expr 写个 vim 函数返回 action name，`:h coc-list-mappings-custom`

**Comment by persytry** [comment]
```vim
"coc.preferences.jumpCommand": "tab drop",
"list.insertMappings": {
    "<CR>": "expr:MyCocDefaultAction",
    "<C-t>": "action:open",
}
```

```vim
function! MyCocDefaultAction(coc)
    "echomsg a:coc
    if a:coc.name == 'commands'
        return 'run'
    endif
    return 'drop'
endfunction
```

谢谢, 完美解决. coc灵活可定制,扩展性强,棒棒嗒
