### ISSUE TITLE
fatal: Could not read from repository

### ISSUE THREAD

**Issue by Mastergamer433** [neoclide/coc.nvim#3837]
Hi!

I did use the recomended way to install it with plug.vim but that didnt work so i did test with the build from source otion but that didnt work either.

Error:
Cloning into '/home/ubuntu/.config/nvim/autoload/plugged/coc.nvim'...

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by chemzqm** [comment]
Your network issue.

**Comment by Mastergamer433** [comment]
But it works for like 20 other plugins.

**Comment by chemzqm** [comment]
Don't know, it's your network problem.

**Comment by Mastergamer433** [comment]
Well it happens for rainbowi also if that can help you help me find the problem.

Here you have my nvim config: https://github.com/mastergamer434/vim-config i just have to push the latest changes to it.

**Comment by Mastergamer433** [comment]
WTH now when I am about to take a screenshot it's working. :( Always when you wanna show a problem to another person it's not a problem.
