### ISSUE TITLE
Tab not working when install ultisnips.

### ISSUE THREAD

**Issue by LinArcX** [neoclide/coc.nvim#387]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.50
term: xterm-kitty
platform: linux

## Error messages
```

**Describe the bug**
Install [ultisnips](https://github.com/SirVer/ultisnips/), after that when type something and hit the tab to select the item from the list, it doesn't work anymore. i create an issue for them too, but i'm not sure it relaed to which project:
https://github.com/SirVer/ultisnips/issues/1052

**To Reproduce**
Use exact these configurations:
https://github.com/neoclide/coc.nvim#example-vim-configuration

**Comment by chemzqm** [comment]
checkout `verbose imap <tab>`
