### ISSUE TITLE
Error highlighting disappears when navigating away from buffer and then back (gopls)

### ISSUE THREAD

**Issue by SentientClee** [neoclide/coc.nvim#3873]
## Describe the bug

1. Have a `.go` file open with errors highlighted
2. Navigate to a different buffer in some way (go to def, edit command, netrw navigation, etc.)
3. Come back to the buffer you were on `ctrl-o`
4. Error highlights are gone
5. Reproducible in vim and macvim

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

.vimrc
https://github.com/SentientClee/.vim/blob/master/.vimrc

coc-settings.json
https://github.com/SentientClee/.vim/blob/master/coc-settings.json

I am installing `gopls` through https://github.com/fatih/vim-go plugin using `GoInstallBinaries` and then setting `gopls` as the language server for golang files in `:CocConfig`.

## Screenshots (optional)
Before:
<img width="1765" alt="Screen Shot 2022-06-03 at 6 48 57 PM" src="https://user-images.githubusercontent.com/42755149/171971938-e5fb6a94-6097-40ad-9e29-d4364a21339e.png">

Navigate away and then back to the same buffer:
<img width="1761" alt="Screen Shot 2022-06-03 at 6 50 43 PM" src="https://user-images.githubusercontent.com/42755149/171971990-77ceb336-3f7c-4854-92c2-b475b7cb0f8f.png">

You can see that errors are no longer highlighted even though `E:2(L25)` is present at the bottom right hand corner. I am also unable to use `[g` or `]g` to navigate between errors. The errors eventually reappear once I start making edits to the file. Please advise. Thanks!

**Comment by chemzqm** [comment]
One possible reason is the buffer changed, but language server not send same diagnostics again.

Verbose output needed, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by fannheyward** [comment]
Tested with nvim and vim 8.2.5050, can't reproduce.

**Comment by chemzqm** [comment]
It seems caused by [vim-go](https://github.com/fatih/vim-go) replaced the buffer by `edit!`, try to avoid that bad behavior.

**Comment by SentientClee** [comment]
> It seems caused by [vim-go](https://github.com/fatih/vim-go) replaced the buffer by `edit!`, try to avoid that bad behavior.

Should I open an issue there or would verbose output solve this?

**Comment by chemzqm** [comment]
Verbose output needed to see what happened.
