### ISSUE TITLE
Support change some configure to set initializing message position.

### ISSUE THREAD

**Issue by yaocccc** [neoclide/coc.nvim#3875]
![5JUM2CQOV__H9C}ZR}%NZ_B](https://user-images.githubusercontent.com/53512609/172101558-4416a95e-b968-46fe-bda7-194659f110b1.gif)

Now initializing message position is buttom right floating.
I hope it could be set by myself.

floating, echo, or none

**Comment by chemzqm** [comment]
It should be disabled by default, seems coc-pyright enables it, send feature request to coc-pyright for configurtion to disable the notification.
@fannheyward

**Comment by yaocccc** [comment]
> It should be disabled by default, seems coc-pyright enables it, send feature request to coc-pyright for configurtion to disable the notification. @fannheyward

Hi, I tryed remove some coc plugin includes coc-pyright but this message is some.

I try go、vue、js/ts、py、lua and more filetype，It have some

**Comment by yaegassy** [comment]
@yaocccc If `progressOnInitialization` is `true` in the language server related part of the extension, the progress window will be displayed.

- coc-pyright
  - <https://github.com/fannheyward/coc-pyright/blob/master/src/index.ts#L223>

To change this behavior, a configuration must be added on the extension side that wraps `progressOnInitialization` to true/false.

**Comment by fannheyward** [comment]
@yaegassy @yaocccc coc-pyright will add a configuration to toggle the progress.

**Comment by yaocccc** [comment]
> 
Thanks, I get it

I set coc-go, coc-pyright, and coc-volar progressOnInitialization is false it worked.

Suggest coc could have a configuration to change this behavior on initialization. 

@chemzqm 

Please keep this issues

**Comment by yaegassy** [comment]
@yaocccc  `coc-volar` has just added a setting to control it. <https://github.com/yaegassy/coc-volar/pull/168>

**Comment by chemzqm** [comment]
We won't, you can change the code.

**Comment by yaocccc** [comment]
Thanks

**Comment by fannheyward** [comment]
@chemzqm there're two progress parts:

1. `progressOnInitialization`
2. `workDoneProgress`

For the first one, coc has disabled it by default, and extensions can provides configurations to enable or not, but coc can't disable the second by now.

**Comment by chemzqm** [comment]
>  but coc can't disable the second by now.

It could, add `"progress"` in `"disabledFeatures"`

**Comment by fannheyward** [comment]
Oh I missed `disabledFeatures`.

**Comment by zoumi** [comment]
clangd has same problem and the popup window is ugly..
![image](https://user-images.githubusercontent.com/5162901/172269236-06cfd5cd-f61f-4272-8ad3-379b56031b21.png)

**Comment by yaocccc** [comment]
> clangd has same problem and the popup window is ugly.. ![image](https://user-images.githubusercontent.com/5162901/172269236-06cfd5cd-f61f-4272-8ad3-379b56031b21.png)

Hi, I think we can commit issues to coc plugins repo

**Comment by fannheyward** [comment]
@zoumi coc-clangd will add configuration to disable the progress notifications.

**Comment by chemzqm** [comment]
> clangd has same problem and the popup window is ugly..
> ![image](https://user-images.githubusercontent.com/5162901/172269236-06cfd5cd-f61f-4272-8ad3-379b56031b21.png)

Fix the font in your terminal or configure notification

**Comment by chemzqm** [comment]
> @zoumi coc-clangd will add configuration to disable the progress notifications.

Don't think that's necessary, it could be configured or use autocmd to close it just after create.

**Comment by Seb-C** [comment]
What is the proper way to disable this popup permanently and for all languages? This started to appear since I've updated coc.vim and the extensions, and I find it highly bothersome.

I've tried many ways and syntaxes for `"progressOnInitialization": false` in my configuration file, but it's now seemingly enabled by default for all languages. It now appears for both golang and typescript.

**Comment by chemzqm** [comment]
> but it's now seemingly enabled by default for all languages.

It's not, `progressOnInitialization` is disabled by default.

**Comment by Seb-C** [comment]
@chemzqm 
> It's not, `progressOnInitialization` is disabled by default.

I'm on the latest `release` branch and the feature is enabled without any specific configuration.

Maybe the changes needs to be released?

**Comment by chemzqm** [comment]
It's already used by latest release branch, possible enabled by extension.
You can check the source of notification.

**Comment by Seb-C** [comment]
Just tried various other configuration syntaxes as well as setting the parameter to `false` in the source code of coc.vim, nothing works to disable this.

I've reverted back my configuration to a random earlier commit (1d85f511f9966b445b5200f35f8db8d4cc0af805) for now, and I don't see it anymore.

**Comment by untitaker** [comment]
I don't understand why this is a per-plugin setting at all? Why can't I disable this globally?

**Comment by chemzqm** [comment]
Use `"notification.disabledProgressSources": ["*"]` in coc-settings.json to disable all progress notifications.

**Comment by untitaker** [comment]
much apprechiated, works exactly as expected!

**Comment by narodnik** [comment]
Who thought this was a good idea? Damn this is ugly

**Comment by yaocccc** [comment]
much apprechiated, works exactly as expected!

**Comment by Seb-C** [comment]
Thank you very much for reconsidering and implementing it. I will update my setup ASAP 🙂.
