### ISSUE TITLE
Each time a c++ file is opened, a clangd will be started

### ISSUE THREAD

**Issue by jphz** [neoclide/coc.nvim#3877]
![image](https://user-images.githubusercontent.com/30751794/172543569-51874bdd-4c57-4b79-81ea-b359f724fea4.png)

I have deleted the configuration。
![image](https://user-images.githubusercontent.com/30751794/172543653-d2711c27-d493-4e8b-bb21-5867574f3074.png)

**Comment by oblitum** [comment]
It's not a process, it's a thread (green) in the main clang process (white).

**Comment by oblitum** [comment]
If you're using `htop`, hit <kbd>F5</kbd> to toggle tree view, hit <kbd>F2</kbd> for setup, mark "Tree view is collapsed by default". You'll notice in setup page there's also the information "Display threads in different color", which is marked by default.
