### ISSUE TITLE
Feature request: Rounded borders for float config

### ISSUE THREAD

**Issue by lmburns** [neoclide/coc.nvim#3879]
I looked through the `schema.json` file and didn't see that there was an option to the `border` field of any of the `floatConfig`'s besides just `true`. I was wondering if it would be possible to allow for all of the borders that `vim.api.nvim_open_win` accepts (i.e., `none`, `single`, `double`, `rounded`, `solid`, `shadow`, perhaps even the possibility of our own array of icons)

**Comment by oblitum** [comment]
rounded config will come in this PR: https://github.com/neoclide/coc.nvim/pull/3862.

**Comment by chemzqm** [comment]
We could support rounded borders, but we don't use border option of `nvim_open_win` which not exists on nvim 0.4.0
