### ISSUE TITLE
:CocList symbols doesn't work

### ISSUE THREAD

**Issue by daquexian** [neoclide/coc.nvim#388]
**Result from CocInfo**
vim version: NVIM v0.3.2
node version: v8.9.0
coc.nvim version: 0.0.50
term: screen-256color
platform: linux

**Describe the bug**
Typing `:CocList` and selecting `symbols` item works, but `:CocList symbols` doesn't work

**To Reproduce**

1. type :CocList symbols
2. type any keys
3. no symbol appears

But if you
1. type :CocList
2. select symbols
3. type any keys
4. you'll see the matching symbols

**Screenshots**
![image](https://user-images.githubusercontent.com/11607199/51956447-9f642680-2482-11e9-870a-c68d10c97fc0.png)

**Comment by chemzqm** [comment]
Looks like the language server you're using doesn't support workspace symbols feature.

**Comment by daquexian** [comment]
Thanks for your reply.

But when I only type ":CocList", and select "symbols" from the list, it works

**Comment by chemzqm** [comment]
You have to use `-I` or `--interactive` option for symbols, it works on interactive mode only, need a check for it.
