### ISSUE TITLE
Inserts a newline if the typed text matches the completion suggestion

### ISSUE THREAD

**Issue by turtureanu** [neoclide/coc.nvim#3884]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.0
node version: v18.3.0
coc.nvim version: 0.0.81-74f26199 2022-06-11 17:54:29 +0800
coc.nvim directory: /home/tux/.local/share/nvim/site/pack/packer/start/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2022-06-13T19:40:52.059 INFO (pid:11842) [plugin] - coc.nvim initialized with node: v18.3.0 after 103ms
2022-06-13T19:40:52.088 INFO (pid:11842) [services] - registered service "go"
2022-06-13T19:40:52.089 INFO (pid:11842) [services] - gopls state change: stopped => starting
2022-06-13T19:40:52.216 INFO (pid:11842) [services] - gopls state change: starting => running
2022-06-13T19:40:52.222 INFO (pid:11842) [services] - service go started
2022-06-13T19:47:12.146 INFO (pid:11842) [attach] - receive notification: showInfo []
```

## Describe the bug

I sometimes happen to type out the entire suggestion before actually selecting and using it.
If I happen to do just that, instead of continuing on the same line, a newline is created as though the suggestion menu and the selected item weren't there.

This isn't the only case when this happens (it can also happen mid-word), more dubious, is that it doesn't happen 100% of the time.

It's worth noting that toggling completion suggestions with `<C-n>` does **sometimes** behave in the desired way (see screenshots).

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Was able to successfully reproduce.**

## Screenshots (optional)
Typed the whole suggestion out manually
![image](https://user-images.githubusercontent.com/90131332/173417233-2687f228-a4ec-48d4-9471-43f33957b368.png)
Pressed `<CR>`

Expected behavior:
![image](https://user-images.githubusercontent.com/90131332/173419536-1e181682-b839-4d7f-9e27-e6dc6d49c863.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/90131332/173419621-fd69a3c6-2cfd-47f6-a5e9-440bfc880e5a.png)

**Comment by chemzqm** [comment]
Seems you need remap your `<CR>` which is not remapped by coc.nvim, checkout `:h popupmenu-keys`
