### ISSUE TITLE
CocHintHighlight does not change the color of the higlight

### ISSUE THREAD

**Issue by pure-bliss** [neoclide/coc.nvim#3885]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.0
node version: v16.15.0
coc.nvim version: 0.0.81-bacd91d 2022-06-03 10:34:52 +0800
coc.nvim directory: /home/${USER}/.local/share/nvim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2022-06-14T10:34:47.330 INFO (pid:122322) [services] - registered service "eslint"
2022-06-14T10:34:47.332 INFO (pid:122322) [services] - ESLint state change: stopped => starting
2022-06-14T10:34:47.782 INFO (pid:122322) [services] - registered service "tsserver"
2022-06-14T10:34:47.785 INFO (pid:122322) [plugin] - coc.nvim initialized with node: v16.15.0 after 532ms
2022-06-14T10:34:47.807 INFO (pid:122322) [services] - service tsserver started
2022-06-14T10:34:47.919 INFO (pid:122322) [services] - ESLint state change: starting => running
2022-06-14T10:34:47.923 INFO (pid:122322) [services] - service eslint started
2022-06-14T10:36:33.430 INFO (pid:122322) [attach] - receive notification: showInfo []
```

## Describe the bug

The highlight keyword `CocHintHighlight` does not work as expected.

## Reproduce the bug

 * Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

 * Install coc-tsserver

 * Create an example project, install an example package (Axios), and create a file:

  ```
  npm init
  npm i axios
  echo 'import { AxiosResponse } from "axios";' > index.ts
  nvim -u mini.vim index.ts
  ```

 * coc-tsserver highlights the import, and shows a hint popup.

![image](https://user-images.githubusercontent.com/83361786/173533469-e7d20260-12a5-4b20-acc2-e34ad34092b6.png)

 * Now try to change the highlight color:

  `:hi CocHintHighlight guibg=red ctermbg=red guifg=red ctermbg=red`

 * Nothing happens

### Expected:
 
 * The higlight color can be changed for hints

### Other:

Here you can see eslint showing a warning for the same reason. `:hi CocWarningHighlight guibg=blue ctermfg=blue guifg=blue ctermbg=blue` works here.

![image](https://user-images.githubusercontent.com/83361786/173533579-50e96b3e-bdcc-4a1f-9b6f-7822b79509f6.png)

Same here for a typescript warning: `:hi CocInfoHighlight guibg=blue ctermfg=blue guifg=blue ctermbg=blue` works.

![image](https://user-images.githubusercontent.com/83361786/173534138-5e4033e2-667f-4684-b18b-46cae804fd64.png)

**Comment by chemzqm** [comment]
Seems it's overwritten by `CocUnusedHighlight` which is expected.

**Comment by pure-bliss** [comment]
You are right, `CocUnusedHighlight` was the thing i looking for instead of `CocHintHighlight`. I couldn't figure out from `:h coc-highlights`, and the tooltip message shows `[H]`. Thats why I guessed that it should be a hint, and should use `CocHintHighlight`. Maybe it was just I who couldn't figure it out, but otherwise there could be a better documentation. Thanks!
