### ISSUE TITLE
[vim-node-coc]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

### ISSUE THREAD

**Issue by ruanyl** [neoclide/coc.nvim#389]
**Result from CocInfo**
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 30 2019 12:14:06)
node version: v8.9.0
coc.nvim version: 0.0.50
term: iTerm.app
platform: darwin

## Error messages
UnhandledRejection: exited with 1
Error: exited with 1
    at child_process_1.exec (/snapshot/coc.nvim/lib/util/index.js:118:24)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Describe the bug**
see `[vim-node-coc]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)` in command line when open vim

**Screenshots**
![image](https://user-images.githubusercontent.com/486382/51975775-c410cc00-248b-11e9-9f52-320ade18e00e.png)

**Comment by ruanyl** [comment]
`CocInfo` shows node version `8.9.0`, but I'm using `8.11.3`. What is the version `8.9.0` exactly here? Does it matter?

**Comment by chemzqm** [comment]
You're using binary release, it's bundled with node 8.9.0.
Your node process is killed by other software, it should be problem of your system.

**Comment by ruanyl** [comment]
Thanks for clarify.

> Your node process is killed by other software, it should be problem of your system.

Not sure how did this happen, I see the error message every time when I opened vim. But it seems coc.nvim is just working fine. No other issues found except this message.

**Comment by ruanyl** [comment]
Cool! thanks :)
