### ISSUE TITLE
CocInstall c++

### ISSUE THREAD

**Issue by vlocateli** [neoclide/coc.nvim#3890]
Operating System: Mac OSX 10.15
Vim version: version 8.1.2292
When running CocInstall c++ I get the following error:

1 Install finished
~                                      |  2 
~                                      |  3 - ✗ c++ Bad response from https://registry.npmjs.org/c++: 404

The guide version for Mac OSX doens't cover clang > 8.
When running CocInstall c++ coc-tsserver it has errors like
```cpp
#include<iostream> -> "iostream"  file not found

**Comment by xiyaowong** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#install-extensions

**Comment by xiyaowong** [comment]
did you read readme or wiki?

**Comment by vlocateli** [comment]
yes, I've tried coc-install clangd with clangd installed via homebrew

**Comment by xiyaowong** [comment]
`:CocInstall coc-clangd`

**Comment by fannheyward** [comment]
There's no c++ extension, it's `coc-clangd`.
