### ISSUE TITLE
Iostream file not found on mac osx 

### ISSUE THREAD

**Issue by vlocateli** [neoclide/coc.nvim#3891]
Hello I'm new to Coc and vim
I've installed coc c++ extension via CocInstalll coc-clangd
but when doing a simple hello world program
```cpp
#include<iostream>

int main()
{	

	std::cout << "Hello world\n";
}
````
it says "iostream" file not found
What am I doing wrong?
Operating System: Mac OSX 10.15
clang version: 12 
vim version: version 8.1.2292

**Comment by fannheyward** [comment]
Follow https://clangd.llvm.org/installation.html#project-setup to generate `compile_commands.json` for your project, this is needed for clangd to work.
