### ISSUE TITLE
Disable function parameters hints

### ISSUE THREAD

**Issue by damian-tomczak** [neoclide/coc.nvim#3892]
Hi,
Could somebody help me turn off hints about function parameters in vim?
![image](https://user-images.githubusercontent.com/43729842/174448755-f6a679a2-d214-4489-a2e9-05cd422c8540.png)
[I mean about this in blue font]

**Comment by fannheyward** [comment]
Do you use coc-rust-analyzer? You can disable it by `rust-analyzer.inlayHints.enable`.

**Comment by damian-tomczak** [comment]
Working, THANKS <3

**Comment by fannheyward** [comment]
@ahnafalnafis check `:h coc-inlayHint`, use the new configuration `inlayHint.enable`.

**Comment by ahnafalnafis** [comment]
Thanks <3. It's working now!

**Comment by hyt589** [comment]
> @ahnafalnafis check `:h coc-inlayHint`, use the new configuration `inlayHint.enable`.

I'm trying to turn this on, but it didn't work

**Comment by fannheyward** [comment]
@hyt589 `:CocInfo` please

**Comment by hyt589** [comment]
> @hyt589 `:CocInfo` please

`:CocInfo` prints:

```
## versions

vim version: NVIM v0.9.5
node version: v16.20.2
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /root/.local/share/nvim/site/pack/packer/start/coc.nvim
term: xterm
platform: linux

## Log of coc.nvim

2024-02-27T05:23:24.557 INFO (pid:30972) [plugin] - coc.nvim initialized with node: v16.20.2 after 254
2024-02-27T05:23:24.571 INFO (pid:30972) [services] - LanguageClient clangd state change: stopped => starting
2024-02-27T05:23:24.579 INFO (pid:30972) [language-client-index] - Language server "clangd" started with 30985
2024-02-27T05:23:24.625 INFO (pid:30972) [services] - LanguageClient clangd state change: starting => running
2024-02-27T05:23:24.632 INFO (pid:30972) [services] - service clangd started
2024-02-27T05:23:24.645 INFO (pid:30972) [attach] - receive notification: highlight []
2024-02-27T05:23:27.542 INFO (pid:30972) [attach] - receive notification: highlight []
2024-02-27T05:23:31.061 INFO (pid:30972) [attach] - receive notification: showInfo []
```

coc-settins.json:

```json
{
    "Lua.telemetry.enable": false,
    "rust.show_hover_context": true,
    "rust-analyzer.enable": true,
    "sumneko-lua.enableNvimLuaDev": true,
    "powershell.integratedConsole.showOnStartup": false,
    "semanticTokens.filetypes": [
        "*"
    ],
    "semanticTokens.highlightPriority": 2048,
    "Lua.workspace.library": [],
    "clangd.arguments": [
        "-header-insertion=never",
        "--inlay-hints=true"
    ],
    "coc.preferences.formatOnSave": true,
    "inlayHint.enable": true,
    "inlayHint.display": true,
    "inlayHint.enableParameter": true,
    "inlayHint.refreshOnInsertMode": true
}
```

**Comment by fannheyward** [comment]
> "inlayHint.enable": true,

You've already enabled inlayHint, maybe your `clangd` is outdated that didn't support inlay hint.

**Comment by hyt589** [comment]
> > "inlayHint.enable": true,
> 
> You've already enabled inlayHint, maybe your `clangd` is outdated that didn't support inlay hint.

I'm using clangd 17.0.6. The should have inlay hint support since [clangd 14](https://clangd.llvm.org/extensions#inlay-hints)

**Comment by fannheyward** [comment]
@hyt589  Got the issue, the inlayHint feature now requires nvim nightly(0.10+), you're using nvim 0.9.5.

- https://github.com/neoclide/coc.nvim/pull/4648
- https://stackoverflow.com/questions/77214955/coc-rust-analyzer-does-not-have-inlay-type-hint-anymore

**Comment by hyt589** [comment]
@fannheyward Thanks, I think I'll wait for nvim 0.10 stable release then
