### ISSUE TITLE
Disable bg highlight for hints

### ISSUE THREAD

**Issue by Aasim-A** [neoclide/coc.nvim#3897]
Hi, when there is a hint available, `coc` makes the background of the affected text gray as shown below:

![image](https://user-images.githubusercontent.com/23695024/174997599-fc381688-1d6e-4bb2-8e78-0681b02553c2.png)
![image](https://user-images.githubusercontent.com/23695024/174997630-aecae799-c08f-447e-a11c-350bd3c813fd.png)

I have disabled my theme to see if it's causing the issue but there's no difference when disabling it.

Is there a way to make it like other diagnostic types i.e just underline it and don't mess with the background color?
Also, is there a way to change `tsserver` diagnostics to show as errors? I'm using `coc-tsserver'

**Comment by xiyaowong** [comment]
`:h CocErrorHighlight`

**Comment by Aasim-A** [comment]
I have tried changing it, but it doesn't affect them

**Comment by xiyaowong** [comment]
```vim
function s:test() abort
  hi! clear CocErrorHighlight
  hi! CocErrorHighlight guifg=NONE
endfunction

call s:test()
```
if it doesn't work, you can add these autocmds

```vim
augroup Test
  autocmd!
  autocmd ColorScheme * call timer_start(200, { -> s:test()})
  autocmd User CocNvimInit call timer_start(200, { -> s:test()})
augroup END
```

**Comment by Aasim-A** [comment]
Thanks for the comment but unfortunately, after trying both, non of them seems to work.

**Comment by xiyaowong** [comment]
@Aasim-A What's `verbose highlight CocErrorHighlight` prints?

**Comment by oblitum** [comment]
Possible #1046 duplicate.

**Comment by Aasim-A** [comment]
>What's verbose highlight CocErrorHighlight prints?

Thats the output:
```vim
:verbose highlight CocErrorHighlight
CocErrorHighlight xxx links to CocUnderline
        Last set from ~/.local/share/nvim/plugged/coc.nvim/plugin/coc.vim line 422
```

**Comment by xiyaowong** [comment]
> ```viml
> function s:test() abort
>   hi! clear CocErrorHighlight
>   hi! CocErrorHighlight guifg=NONE
> endfunction
> 
> call s:test()
> ```

@Aasim-A I've tried vim and nvim, and this works

**Comment by xiyaowong** [comment]
```
augroup Test
  autocmd!
  autocmd ColorScheme * call timer_start(200, { -> s:test()})
  autocmd User CocNvimInit call timer_start(200, { -> s:test()})
augroup END
```

Need to be placed before setting the theme and loading coc

**Comment by Aasim-A** [comment]
Ok, turns out @oblitum was right, it is indeed the `CocUnusedHighlight` that's causing this issue, after adding this command:

```vim
autocmd ColorScheme *
    \ hi CocUnusedHighlight cterm=underline gui=underline guifg=#808080
```
it has resolved the issue, and now it looks like so:

![image](https://user-images.githubusercontent.com/23695024/175851732-50f85278-ae5d-4ced-9089-a5a4cab073a6.png)

And just for the record, it has to be added to the config file before setting the theme.

Thanks a lot for your help guys!
