### ISSUE TITLE
New layout for outline view

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#39]
**Is your feature request related to a problem? Please describe.**

Something like tagbar's replace the one of `denite coc-symbols.`

**Comment by liuchengxu** [comment]
Actually I have an unpublished plugin doing the exact thing. It's perfectly suitable for the data with hierarchical structure.

<img width="1680" alt="default" src="https://user-images.githubusercontent.com/8850248/47637089-843cfe80-db95-11e8-909e-4e6438ba599d.png">

It utilizes many modern API(async, timer etc) and take cares of lots of details to obtain a decent user experience. But it's not stable yet. When it's ready, I'm happy to add `coc-symbols` support as well.

**Comment by chemzqm** [comment]
@liuchengxu looking forward to your extension.

I'm not going to add this in coc.nvim itself, but maybe use a gui to render outline view for easier navigation.

**Comment by liuchengxu** [comment]
Hello, I have published my plugin: [vista.vim](https://github.com/liuchengxu/vista.vim), which could provide a tagbar like viewer for coc.

Open the vista siderbar supported by coc via `:Vista coc`:

![image](https://user-images.githubusercontent.com/8850248/52893899-53341880-31dc-11e9-90e8-cb3d0b02c88a.png)

I use coc-rls in the screenshot above.

For more usage, please see the README of vista.vim.
