### ISSUE TITLE
[coc.nvim] binary and build file not found

### ISSUE THREAD

**Issue by antaed** [neoclide/coc.nvim#390]
I must have done something wrong because i get this message every time I open MacVim
`[coc.nvim] binary and build file not found` and obviously, I can't get it to work.

What I did:
- I installed yarn with `brew install yarn` (I had node.js already installed)
- Then I ran `yarn global add vim-node-rpc`
- I've put `call minpac#add('neoclide/coc.nvim', {'do': 'yarn install'})` in my vimrc
- I ran `:call minpac#update() `in MacVim
- I also ran `:CocInstall coc-json coc-css` and checked that the extensions were installed successfully in ~/.config/coc/extensions/node_modules/

Any ideas? Thanks

**Comment by chemzqm** [comment]
Your build is failed or not work at all, use `:call coc#util#build()` and wait the build finish.

**Comment by chemzqm** [comment]
To avoid `[coc.nvim] service not started` , you should use `CocActionAsync` instead of `CocAction`, or make sure service started before `CocAction`.

> [vim-node-coc] at DecodeBuffer.DecodeStream.decoder.push (/Users/myuser/.vim/pack/minpac/start/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)

Please paste full messages from `:messages`

**Comment by chemzqm** [comment]
I think your node is too old, what's result from `:echo system('node --version')`

**Comment by antaed** [comment]
I figured it out, I had a typo in my coc-settings.json file.

One more question, if I may. Everything works as expected in MacVim but on my Windows machine I only get LS completion in CSS files. The setup is the same as on the Mac, I have coc-html, coc-phpls and coc-tsserver extensions installed. The completion menu opens but I don't get any LS suggestions in php, html and js files. Can you please tell me what should I check/do? Thanks

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim and https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by antaed** [comment]
Thanks, here are the log files:
[coc-nvim-tsc.log](https://github.com/neoclide/coc.nvim/files/2819164/coc-nvim-tsc.log)
[coc-nvim.log](https://github.com/neoclide/coc.nvim/files/2819165/coc-nvim.log)

**Comment by antaed** [comment]
I have no intention to annoy you and I apologize if I do but I have no idea what should I do next and I don't know who else could help me with this.
I have installed these extensions: coc-json, coc-html, coc-css, coc-tsserver and coc-phpls. I checked with `:CocList extensions` and all of them activate successfully but I only get LS suggestions in json and css files. I checked the log files attached above and I saw that there is no LSP completion source in html and php files and in javascript files I get this error: `Error processing request. No project.`. 
I only have these issues on a Windows machine, everything works just fine on MacOS, even though my setup is almost identical.
Can you please provide some guidance, thanks.

**Comment by antaed** [comment]
Updated and tested again but unfortunately the issues persist

**Comment by chemzqm** [comment]
Need rebuild, try `:call coc#util#build()` after pull latest master code

**Comment by chemzqm** [comment]
If it still not working, consider debug the uri at https://github.com/neoclide/coc.nvim/blob/master/src/model/document.ts#L132 by https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim.
I can't reproduce it on my windows.

**Comment by antaed** [comment]
Sir, I am happy to report it does work after rebuilding.
Thank you very much, you are beyond awesome! Do you have PayPal account where I could make a donation?

**Comment by antaed** [comment]
Ok, will do. And probably even switch to neovim sometime soon ;)
