### ISSUE TITLE
coc 占用了 Ctrl+i 的快捷键 <c-i>

### ISSUE THREAD

**Issue by distroy** [neoclide/coc.nvim#3902]
## Error Message of nvim
[coc.nvim] Error on notification "rangeSelect": selectionRange provider not found for current buffer, your language server doesn't support it.

## Screenshots (optional)
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/3428297/175896358-789bf63c-984e-47f2-9f39-80b2ac95647a.png">

**Comment by fannheyward** [comment]
coc didn't map this by default, it was mapped by your configurations. Check `:verbose map <c-i>`.

**Comment by fannheyward** [comment]
What's `:verbose map <c-i>` ?

**Comment by fannheyward** [comment]
> src/list/mappings.ts

It's used in `CocList`, not `rangeSelect`.
