### ISSUE TITLE
coc 占用了 Ctrl+i 的快捷键 <c-i>

### ISSUE THREAD

**Issue by distroy** [neoclide/coc.nvim#3903]
Error Message of nvim
[coc.nvim] Error on notification "rangeSelect": selectionRange provider not found for current buffer, your language server doesn't support it.

Screenshots (optional)
![image](https://user-images.githubusercontent.com/3428297/175902021-234e05e3-80f2-4842-a205-7e64fdecabf0.png)

请看下 coc 的 js 代码哈
src/list/mappings.ts
src/list/configuration.ts

![image](https://user-images.githubusercontent.com/3428297/175902122-52ac484a-a50f-4465-8fa6-2b3a647c709f.png)

**Comment by xiyaowong** [comment]
有啥关系？这个是coclist的映射

**Comment by distroy** [comment]
应该是 ts 代码捕捉了这个 快捷键了，在 vim 中 使用 map <c-i> 是看不到这个 映射的

**Comment by fannheyward** [comment]
`:verbose map <c-i>` 输出什么？

**Comment by distroy** [comment]
vim 中看不到这个映射，你们 ts 代码用了这按键

**Comment by xiyaowong** [comment]
<c-i>在大部分终端默认等于<tab>。你检查一下

**Comment by distroy** [comment]
tab 也是一样的错误提示

**Comment by xiyaowong** [comment]
检查这个`:verbose map <tab>`

**Comment by distroy** [comment]
确实，我把 2个 ts 相关的代码注释了，重新执行了 yarn install，问题也没有解决

**Comment by distroy** [comment]
@fannheyward 
我的配置文件放在了 https://github.com/distroy/profiles.git  的 vim 目录里
plugins 的放在了 vim/lib/10/plugins.vim 文件里
coc 的配置放在了 vim/lib/66/p-coc.vim  文件里

**Comment by distroy** [comment]
我尝试了把 coc 的 plugin 注释掉了 <c-i> 可以正常使用，一旦引入 coc <c-i> 就使用不了了

**Comment by distroy** [comment]
把 coc 的 extension 都注视了，也还用不了哈

**Comment by xiyaowong** [comment]
@distroy 
 https://github.com/distroy/profiles/blob/e6fb3f5ea8c73e9772c3ec064cefef1b1242199d/vim/lib/66/p-coc.vim#L182
