### ISSUE TITLE
Trouble with dhall-lsp-server

### ISSUE THREAD

**Issue by pleor** [neoclide/coc.nvim#3909]
## Describe the bug

```dhall-lsp-server``` provides diagnostics on file save.

I introduce auto commands to refresh diagnostics on write:

```
au BufRead,BufNewFile *.dhall setfiletype dhall
au BufWritePost,FileWritePost *.dhall call CocAction('diagnosticRefresh')
```

After I save, the diagnostics are not refreshed.

The call to refresh must be delayed for some reason:

```
au BufWritePost,FileWritePost *.dhall call timer_start(100, {-> CocAction('diagnosticRefresh')})
```

## Reproduce the bug

```coc-settings.json```:
```
"languageserver": {
	"dhall": {
		"command": "dhall-lsp-server",
		"filetypes": [
			"dhall"
		]
}
```

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
The delay is because diagnostics are `published` by server to client, as a client, we can't control the delay time.

You don't need to setup auto commands to do refreshing, after your content saving, coc will send `textDocument/didChange` to server, the server will publish diagnostics.

**Comment by pleor** [comment]
Without the auto commands, nothing happens when I save.

**Comment by chemzqm** [comment]
The buffer possible unloaded, try minimal vimrc.
