### ISSUE TITLE
Godot section in Language Servers wiki page is suggesting obsolete plugin

### ISSUE THREAD

**Issue by VPavliashvili** [neoclide/coc.nvim#3910]
As title says, suggested Godot lsp in wiki is obsolete. This is link to that [repository](https://github.com/mlvl42/coc-godot), where author says himself

> This extension is now useless since [https://github.com/godotengine/godot/issues/34523](https://github.com/godotengine/godot/issues/34523) has been closed in godot version 3.2.2.

**Comment by fannheyward** [comment]
Fixed.

```json
"languageserver": {
    "godot": {
      "host": "127.0.0.1",
      "filetypes": ["gd", "gdscript3"],
      "port": 6008
    }
}
```
