### ISSUE TITLE
`go to reference` causes high cpu usage and vim gets stuck

### ISSUE THREAD

**Issue by sify21** [neoclide/coc.nvim#3914]
## Result from CocInfo

vim version: VIM - Vi IMproved 9.0 9000000
node version: v16.9.1
coc.nvim version: 0.0.81-2522eee5 2022-06-14 19:03:29 +0800
coc.nvim directory: /Users/sifangyuan/.vim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin
## Describe the bug
I use coc-go and coc-rust-analyzer. Recently I upgraded vim and all its plugins and coc plugins to latest version. After the upgrade, iterating through the location list of `go to reference` becomes very slow, vim consumes more cpu and gets stuck.

 If I close the list preview (by pressing `p`), iterating through the location list is smooth as before. 

I don't know if this is a bug related to vim 9 on mac.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'majutsushi/tagbar'
Plug 'scrooloose/nerdcommenter'
Plug 'mkitt/tabline.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'tpope/vim-vinegar'
call plug#end()

color dracula
" disable sqlcomplete
let g:omni_sql_no_default_maps = 1
syntax on

" coc.nvim
source ~/.vim/coc.nvim

" netrw
" let g:netrw_liststyle = 3

" tabline
set showtabline=2

" statusline
set laststatus=2
set statusline=%F%m%r\ %h%w%y\ col:%c\ lin:%l\,%L\ buf:%n\ win:%{tabpagewinnr(tabpagenr())}\ reg:%{v:register}
hi StatusLine cterm=bold ctermbg=Brown
hi StatusLineNC cterm=NONE ctermbg=DarkBlue

" transparent
hi Normal guibg=NONE ctermbg=NONE

set noexpandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set nu rnu
set fileencodings=utf-8,chinese,latin-1
set termencoding=utf-8
set encoding=utf-8
set cursorline
set nobackup
set ignorecase
set completeopt-=preview
set splitright
set splitbelow


" folding
set foldmethod=syntax
set foldlevelstart=99

" autoclose
inoremap (<cr> (<cr>)<C-[>O
inoremap (, ()<C-[>i
inoremap {<cr> {<cr>}<C-[>O
inoremap {, {}<C-[>i
inoremap [, []<C-[>i
inoremap ", ""<C-[>i
inoremap ', ''<C-[>i

" ctags yaml
let g:tagbar_type_yaml = {
    \ 'ctagstype' : 'yaml',
    \ 'kinds' : [
        \ 'a:anchors',
        \ 's:section',
        \ 'e:entry'
    \ ],
  \ 'sro' : '.',
    \ 'scope2kind': {
      \ 'section': 's',
      \ 'entry': 'e'
    \ },
    \ 'kind2scope': {
      \ 's': 'section',
      \ 'e': 'entry'
    \ },
    \ 'sort' : 0
    \ }
" ctags xml support
let g:tagbar_type_xsd = {
    \ 'ctagstype' : 'XSD',
    \ 'kinds'     : [
        \ 'e:elements',
        \ 'c:complexTypes',
        \ 's:simpleTypes'
    \ ]
\ }
" ctags mapping
nmap <F8> :TagbarToggle<CR>
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
1. `cd /tmp`
2. `git clone --depth=1 git@github.com:seanmonstar/reqwest.git`
3. `/opt/homebrew/bin/vim src/redirect.rs`
4. `:228` to `ActionKind`
5. `gr`


<img width="821" alt="截屏2022-07-07 19 05 10" src="https://user-images.githubusercontent.com/345274/177759181-15d0a84f-753a-4d1f-9254-c6cc0642f945.png">

minimal vimrc:

```
syntax on

set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
set runtimepath^=~/src/coc-rust-analyzer
nmap <silent> gr <Plug>(coc-references)
```

```
vim version: VIM - Vi IMproved 9.0 9000000
node version: v16.15.1
coc.nvim version: 0.0.81-2522eee5 2022-06-14 19:03:29 +0800
coc.nvim directory: /Users/fannheyward/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

**Comment by sjx95** [comment]
I have the same problem both on macOS and Debian (with linuxbrew vim), and my vim config is on https://github.com/sjx95/.vim

When I open any `.go` files and call `go to reference`, the vim gets stuck.

**Comment by pfernandez** [comment]
@fannheyward I've been having the same issue with Typescript and Clojure, and finally figured out that it occurs when `set foldmethod=syntax` is present. The config that @sjx95 shared [also has this setting](https://github.com/sjx95/.vim/blob/main/vimrc#L31), as does the config in the OP.

**Comment by sjx95** [comment]
@fannheyward It really works by removing `set foldmethod=syntax`, thanks!!

**Comment by sify21** [comment]
@fannheyward I also confirm that commenting out `set foldmethod=syntax` solves the problem.

**Comment by pfernandez** [comment]
@fannheyward Are you sure this should be closed? The foldmethod should not cause Vim to freeze up when calling `<plug>(coc-references)`.
