### ISSUE TITLE
Error detected while processing function coc#rpc#start_server[17]

### ISSUE THREAD

**Issue by Maheerali-pk** [neoclide/coc.nvim#3916]
## Result from CocInfo

`coc.nvim service not started, checking enviroment...Service stopped for some unknown reason, try :CocStart`

## Describe the bug

Whenever I open a file I get an error regarding Coc that it has failed to start. Here is the exact thing which I am getting. I am also getting it when I use `:CocStart`

## Reproduce the bug

```
Error detected while processing function coc#rpc#start_server[17]..<SNR>16_start:
line   72:
E903: Process failed to start: unknown error: "C:\Program Files\nodejs\node.EXE"
Failed to start coc service
```

Here is my `init.vim`. Nothing is missing. Its my complete init.vim

```
call plug#begin()
Plug 'phaazon/hop.nvim'
Plug 'easymotion/vim-easymotion'
Plug 'marko-cerovac/material.nvim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
let mapleader = " "
imap jk <Esc> 
nnoremap <leader>s :w<CR>
nnoremap <leader>pl :PlugInstall<CR>
noremap <leader>sv :source $MYVIMRC<CR>
colorscheme material
set number
syntax on
let g:material_style = "palenight"
```
## Things I have already tried:

1. Reinstalling coc.nvim serveral times
2. User both the ways mentioned on the main page `{'branch': 'master', 'do': 'yarn install --frozen-lockfile'}` and `{'branch': 'release'}
`
3. Have check `build/index.js` it is always there
4. Tried to turn off my antivirus too.
5. Tried to use `:CocOpenLog` but it doesn't do anything.

Please help me out. I just started to work with neovim and I got stuck in the start

**Comment by fannheyward** [comment]
> Process failed to start: unknown error: "C:\Program Files\nodejs\node.EXE"

Looks like your Nodejs didn't work correctly, make sure your Nodejs installed successfully.

**Comment by fannheyward** [comment]
What's the `CocInfo`?

**Comment by Maheerali-pk** [comment]
> `coc.nvim service not started, checking enviroment...Service stopped for some unknown reason, try :CocStart`

coc.nvim service not started, checking enviroment...Service stopped for some unknown reason, try :CocStart

Mentioned that on the top of my first message.

**Comment by Maheerali-pk** [comment]
Ok the issue is fixed now. I don't know how but coc is working fine now
