### ISSUE TITLE
Share your CocList mappings? :D

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#392]
When using Denite for list manage, I made some mappings, for example:

```
nnoremap <silent> <space>w  :<C-u>Denite coc-symbols<CR>
```

Since coc has builtin list support, I've changed to use CocList, also changed mapping:

```
nnoremap <silent> <space>w  :<C-u>CocList symbols<CR>
```

But in https://github.com/neoclide/coc.nvim/issues/388, I found that `symbols` works on interactive mode only, you need to set `-I` option. So maybe my mappings are not correct? Here are my mappings:

```
nnoremap <silent> <space>a  :<C-u>CocList diagnostics<CR>
nnoremap <silent> <space>o  :<C-u>CocList outline<CR>
nnoremap <silent> <space>w  :<C-u>CocList symbols<CR>
nnoremap <silent> <space>b  :<C-u>CocList buffers<CR>
nnoremap <silent> <space>m  :<C-u>CocList mru<CR>
nnoremap <silent> <space>s  :exe 'CocList -I --normal --input='.expand('<cword>').' words'<CR>
nnoremap <silent> <space>S  :exe 'CocList --normal grep '.expand('<cword>').''<CR>
```

@chemzqm can you help check if the mappings is correct? Thanks!

And everyone else can also share your settings, thank you guys!

**Comment by chemzqm** [comment]
You will have error message and the list won't shown if something went wrong.
I use `--number-select` when possible.
