### ISSUE TITLE
Autocomplete for Javascript. MacOS M1 High CPU usage when tsserver.enableJavascript

### ISSUE THREAD

**Issue by ndr47** [neoclide/coc.nvim#3926]
## Result from CocInfo

  0 ## versions                                                                                                          
  1 vim version: VIM - Vi IMproved 9.0 9000000                                                                                     
  2 node version: v16.16.0                                                                                                         
  3 coc.nvim version: 0.0.81-2522eee5 2022-06-14 19:03:29 +0800                                                                    
  4 coc.nvim directory: ~/.vim/plugged/coc.nvim                                                                         
  5 term: Hyper                                                                                                                    
  6 platform: darwin                                                                                                               
  7                                                                                                                                
  8 ## Log of coc.nvim                                                                                                             
  9                                                                                                                                
 10 2022-07-19T19:28:34.014 INFO (pid:72734) [services] - registered service "eslint"                                              
 11 2022-07-19T19:28:34.019 INFO (pid:72734) [services] - ESLint state change: stopped => starting                                 
 12 2022-07-19T19:28:34.036 INFO (pid:72734) [services] - registered service "tsserver"                                            
 13 2022-07-19T19:28:34.037 INFO (pid:72734) [plugin] - coc.nvim initialized with node: v16.16.0 after 70ms                        
 14 2022-07-19T19:28:34.130 INFO (pid:72734) [services] - ESLint state change: starting => running                                 
 15 2022-07-19T19:28:34.132 INFO (pid:72734) [services] - service eslint started                                                   
 16 2022-07-19T19:28:44.937 INFO (pid:72734) [attach] - Request action: doAutocmd [ 1, 1 ]

## Describe the bug

I am trying to have autocomplete on a Javascript file.
I read the whole `:help coc-nvim` and the `README.md`.

The only way I thought it would work was to install `coc-tsserver` and set in `:CocConfig` the following:
```
"tsserver.enableJavascript": true
``` 
However when I open a Javascript file the `node` process can reach 300% of CPU and never go down.
I am using a Macbook Air with M1 chip. MacOS 12.4.

If I set 
```
"tsserver.enableJavascript": false
``` 
The `node` process use 1% of CPU.

Anyway in both case I cannot have autocomplete for Javascript.
I would like to have suggestions, for example if I type `Arr` I will get `Array` and if I type `Array.` I will get all the `Array` methods and attributes - Like in VSCode.

Is that possibile?

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
syntax on

call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

" use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()
```

- Start (neo)vim with command: `vim -u mini.vim`
- Install `:CocInstall coc-json coc-tsserver coc-eslint`
- Operate vim.

## Screenshots
![Screenshot 2022-07-19 at 19 07 28](https://user-images.githubusercontent.com/65710731/179814824-66d13246-0580-49d8-b1c8-7cb202273aa0.png)

**Comment by yoandresaav** [comment]
The same problem here, mac with intel 16gb 15inch 2017

**Comment by ndr47** [comment]
If it is `tsserver` why it doesn't happen on Visual Studio Code or any other IDE when opening the same project?

**Comment by ndr47** [comment]
Deleting `node_modules` and reinstalling with `yarn install` helped.
It takes a while, even on a small project, to start the autocompletion but then it seems to work. It was probably going in a loop somehow.

**Comment by chemzqm** [comment]
> If it is `tsserver` why it doesn't happen on Visual Studio Code or any other IDE when opening the same project?

Could be different tsserver version
