### ISSUE TITLE
Popup error message is unreadable (bad colors)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [neoclide/coc.nvim#3928]
![image](https://user-images.githubusercontent.com/3514015/180008305-8eba4d3d-2d7a-4758-bc9e-c439bdd0db9b.png)

**Comment by vitaly-zdanevich** [comment]
For future researchers: solved by

```
highlight Pmenu ctermbg=232 ctermfg=gray
```

**Comment by chemzqm** [comment]
Try to create highlight for `CocFloating` instead, which links to `Pmenu` on vim by default.
