### ISSUE TITLE
Can we filter references based on file path

### ISSUE THREAD

**Issue by jeroen-dhollander** [neoclide/coc.nvim#3935]
Hey all,

When browsing through the references of a given function/variable I often find myself wanting to restrict the results to only header files ("*.h*) or to exclude test files (exclude "*_unittest.cc").

Is there a way to achieve this? Ideally I'd want to tie this to a shortcut I can press inside the coc-list (so I press <c-t> and all test files are filtered out, or I press <c-h> and I only see headers). Some configurable exclude/include filter would be awesome.

Similarly (but mostly unrelated), when doing a global symbol lookup I often want to limit the type of symbols to only classes/functions. I know I can pass `-kind class` when spawning the list which is awesome, but is there a way to tie this to a shortcut inside the coc-list as well? So I'd open a normal symbol list, realize I only want methods so I press a shortcut and it's filtered.

Thanks in advance!

Jeroen

**Comment by Frederick888** [comment]
I use https://github.com/antoinemadec/coc-fzf and fzf supports things like `!unittest` to filter out files and `'.h` for strict match.

**Comment by chemzqm** [comment]
You need go to declaration for that case
