### ISSUE TITLE
auto completion not working when i set paste

### ISSUE THREAD

**Issue by Radius112** [neoclide/coc.nvim#3947]
how can i make it work with paste?

**Comment by chemzqm** [comment]
It's already fixed, please upgrade to the latest release branch of coc.nvim.

**Comment by josx** [comment]
I am on current [master HEAD](https://github.com/neoclide/coc.nvim/commit/8c0d3ef9781cc60a998b2d496e98989f2da9f997) and still happen to me. 
BTW I am using vim 8.1.2269

Any clue?
