### ISSUE TITLE
Link DiagnosticVirtualTextError to CocErrorVirtualText

### ISSUE THREAD

**Issue by WhyNotHugo** [neoclide/coc.nvim#3948]
**Is your feature request related to a problem? Please describe.**

As a plugin developer, it gets noisy to have to include these `if`s in every project:

```
+local HIGHLIGHTS = {
+  native = {
+    [vim.diagnostic.severity.ERROR] = "DiagnosticVirtualTextError",
+    [vim.diagnostic.severity.WARN] = "DiagnosticVirtualTextWarn",
+    [vim.diagnostic.severity.INFO] = "DiagnosticVirtualTextInfo",
+    [vim.diagnostic.severity.HINT] = "DiagnosticVirtualTextHint",
+  },
+  coc = {
+    [vim.diagnostic.severity.ERROR] = "CocErrorVirtualText",
+    [vim.diagnostic.severity.WARN] = "CocWarningVirtualText",
+    [vim.diagnostic.severity.INFO] = "CocInfoVirtualText",
+    [vim.diagnostic.severity.HINT] = "CocHintVirtualText",
+  },
+}
```

**Describe the solution you'd like**

Can coc include something like this?

```
:hi link DiagnosticVirtualTextError CocErrorVirtualText
```

If any plugin tries to use neovim's native style, and coc is installed, the highlight will work as expected.

This would also give better coc support to themes that don't explicitly target it (at least THOSE styles would improve).

**Describe alternatives you've considered**

I considered renaming CocErrorVirtualText into DiagnosticVirtualTextError, but that would be a breaking change for sooo many integrations.

**Additional context**

-

**Comment by xiyaowong** [comment]
@WhyNotHugo  No, coc is not a neovim only plugin. I sent you the patch about lsp_lines.nvim, if you are willing to accept that change, I will improve the section on coc today

**Comment by WhyNotHugo** [comment]
Hi! Patch looks good. It's [merged](https://git.sr.ht/~whynothugo/lsp_lines.nvim/commit/86df328abf2e7234c70926acebbb22e40d9f7df4), just forgot to push it. Also marked it as merged right now :+1:

**Comment by WhyNotHugo** [comment]
I hadn't realised you were the one submitting the patch BTW, thanks for the contribution!
