### ISSUE TITLE
I want to use `esc` to close float window

### ISSUE THREAD

**Issue by timsu92** [neoclide/coc.nvim#3949]
### Is your feature request related to a problem? Please describe.
When I issue commands like `:CocCommand document.checkBuffer`, a float window will show up. However, I can't close it intuitively.
I see there's a X button in the upper-right corner. Nevertheless, I use Vim in a terminal, and mice don't look like to work in Vim in many situations.

### Describe the solution you'd like
Press `ESC` to close it.

### Describe alternatives you've considered
* We can use `coc#float#close_all()` to close all the float windows. But some of them shouldn't be closed along with those we want to close. 
  An example would be status of plugins installation. We want to close the float window issued by `:CocCommand document.checkBuffer` but not the status. Otherwise, people will consider it completed.
* Another way to close them is to use `coc#float#close({winid})`. However, I don't know how to acquire proper window ids.

### Additional context
![image](https://user-images.githubusercontent.com/33785401/180977541-798be825-276d-43e2-b281-7eb95a70257b.png)

**Comment by fannheyward** [comment]
`C-w-w` to move your cursor to floating window, and `:q` to close it.

**Comment by timsu92** [comment]
Did you meant to hold ctrl and press w twice? Or ctrl-w and then w?
Both of them didn't work😭

**Comment by fannheyward** [comment]
Hold `Ctrl` and press `w` twice. Do you use vim? This may not works on vim.

**Comment by timsu92** [comment]
Yes, unfortunately, I use Vim and this just rang the bell character

**Comment by chemzqm** [comment]
You have to remap `<esc>` yourself.

**Comment by timsu92** [comment]
I'm thinking of these two ways. However, I'm facing questions on both of them:
> ### Describe alternatives you've considered
> * We can use `coc#float#close_all()` to close all the float windows. But some of them shouldn't be closed along with those we want to close. 
  An example would be status of plugins installation. We want to close the float window issued by `:CocCommand document.checkBuffer` but not the status. Otherwise, people will consider it completed.
> * Another way to close them is to use `coc#float#close({winid})`. However, I don't know how to acquire proper window ids.

Do you have any suggestions?

**Comment by chemzqm** [comment]
> An example would be status of plugins installation

What plugin use float window for plugin installation? My suggestion is close all float window, you can check variable w:kind if you want to.

**Comment by timsu92** [comment]
> What plugin use float window for plugin installation?

[`coc-ltex`](https://valentjn.github.io/ltex/vscode-ltex/installation-usage-coc-ltex.html) is one of the example.

After installing by coc, it downloads more stuffs when reopening vim with correct file types. while it's still busying, closing that causes crash.

## Steps to reproduce:

https://user-images.githubusercontent.com/33785401/182029942-90b6dda2-6a72-4b93-a0d2-df1554edad87.mp4
1. Install using `:CocInstall coc-ltex`
2. After finishing, open a file which triggers it, eg. markdown
3. While the bottom-right window (is it called notification?) is still there, execute `:CocCommand document.checkBuffer` and then `:call coc#float#close_all()`
----------------------------------------------------
> you can check variable w:kind if you want to

Is this a variable only on Neovim? Or local to the notification window which I don't know how to go to yet?
It's undefined in Vim 8.2 when my cursor is in the file I intend to edit.

----------------------------------------------------
## Additional info
### So... why I mentioned `coc#float#close_all()`?
Before asking, I took a look on Gitter, where someone happened to ask a question on Jul 21 00:20 which look similar.
