### ISSUE TITLE
CocAction && CocFix

### ISSUE THREAD

**Issue by dan4ik605743** [neoclide/coc.nvim#3950]
Is it possible to somehow use CocFix or CocAction? Or did you completely remove them?

**Comment by xiyaowong** [comment]
https://github.com/neoclide/coc.nvim/blob/43744ba82bd348ea971b87483a13f06f3e46c94b/doc/coc.txt#L1897

**Comment by dan4ik605743** [comment]
> https://github.com/neoclide/coc.nvim/blob/43744ba82bd348ea971b87483a13f06f3e46c94b/doc/coc.txt#L1897

how can it be used?

**Comment by chemzqm** [comment]
`:h CocAction('codeActionRange')`

**Comment by dan4ik605743** [comment]
> `:h CocAction('codeActionRange')`

i call the command but nothing happens

**Comment by dan4ik605743** [comment]
use <Plug>(coc-codeaction-selected)
work
