### ISSUE TITLE
Popup menu display broken after upgrade to 0.82 (makes it unusable)

### ISSUE THREAD

**Issue by gi1242** [neoclide/coc.nvim#3954]
## versions

vim version: NVIM v0.7.2
node version: v18.7.0
coc.nvim version: 0.0.81-43744ba8 2022-07-05 17:36:48 +0900
coc.nvim directory: /home/gautam/.local/share/nvim/site/pack/packer/start/coc.nvim
term: undefined
platform: linux

## Log of coc.nvim

2022-07-31T00:00:14.076 INFO (pid:348365) [plugin] - coc.nvim initialized with node: v18.7.0 after 65ms
2022-07-31T00:00:14.429 INFO (pid:348365) [attach] - receive notification: highlight []
2022-07-31T16:55:40.906 INFO (pid:348365) [core-watchman] - watchman watching project: /run/user/1000/firenvim
2022-07-31T16:55:41.396 INFO (pid:348365) [attach] - receive notification: highlight []
2022-07-31T16:55:45.430 INFO (pid:348365) [attach] - receive notification: showInfo []

## Describe the bug

Popup menu display is borked up after the recent upgrade. It starts showing correctly; then when you press tab once. When you press tab a second time a different menu shows, and words from that are completed. Makes it unusable on my system.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Install some extension (e.g. `CocInstall pyright`)

- Open a new python file

- Type `#!/usr/bin/python` in the first line

- Type `p` in the second line and press `tab`. You see a menu with first entry `pass`.

- Press `tab` again. A new menu is shown over the old menu. The new menu has different entries (`python` is first, `pass` is second).

It makes completion unusable; it was working fine before upgrade.

## Screenshots (optional)

![Screenshot_20220731_171155](https://user-images.githubusercontent.com/1884258/182045704-adb92b12-32cf-4b4b-8fd7-d6760412c9fa.png)

**Comment by gi1242** [comment]
PS: Same problem occurs with other servers / extensions I have. I just used pyright as an example.

**Comment by truongtx-vincss** [comment]
I'm having the same issue. Here is a screen capture of it:

https://user-images.githubusercontent.com/107167275/182064961-65d6f6b4-d0e7-4ea6-bc67-c7775e5babb4.mp4

**Comment by chemzqm** [comment]
> Edited: Fixed, the issue was that `coc.nvim` use highlight link for `CocMenuSel` by default. If you use lua config, you need to change the highlight AFTER coc.nvim loaded. Use something similar to this:
> 
> ```lua
>         use {
>             'neoclide/coc.nvim',
>             branch = 'release',
>             config = function()
>                 vim.cmd('hi link CocSearch PmenuSel')
>                 vim.cmd('hi link CocMenuSel PmenuSel')
>             end
>         }
> ```
It won't always work, you should not link CocSearch to PmenuSel and PmenuSel may not work as well.

**Comment by chemzqm** [comment]
@gi1242 seems you have `<tab>` remapped, checkout `:verbose imap <tab>` and `:h coc-completion-example`

**Comment by andy999111** [comment]
Same issue here, as soon as it started saying "coc.nvim switched to a custom pop menu from 0.0.82..." I can't tab to autocomplete, pressing the arrow keys moves the selection in the menu but pressing enter just enters a new line. 

I reverted to the previous version with vim plug and that works fine.

**Comment by chemzqm** [comment]
@andy999111 You have to remap your `<tab>` and `<cr>`, see `:h coc-completion-example`

**Comment by andy999111** [comment]
> @andy999111 You have to remap your `<tab>` and `<cr>`, see `:h coc-completion-example`

Even after remapping exactly as is shown in 'coc-completion-example' behaviour is not same as before update, tab doesn't work properly, arrow keys don't navigate completion popup etc. Makes plugin unusable.

**Comment by chemzqm** [comment]
Could be remapped by other vim plugin, use `:verbose imap <tab>` to check out.

**Comment by andy999111** [comment]
> Could be remapped by other vim plugin, use `:verbose imap <tab>` to check out.

It isn't.

`i  <Tab>       * pumvisible() ? "\<C-N>" : CheckBackspace() ? "\<Tab>" : coc#refresh()
        Last set from ~/.config/nvim/plug-config/coc.vim line 34`

Line 34 (before remap)

`inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ CheckBackspace() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
`

If I comment that out and remap to everything in `coc-completion example` nothing works, not tab, not enter(takes new line) or arrow keys.

**Comment by chemzqm** [comment]
You have copied wrong config, please checkout latest doc and README.

**Comment by andy999111** [comment]
Should I replace my config with the new one in the README?

**Comment by chemzqm** [comment]
Yes, if you use coc.nvim for completion.

**Comment by andy999111** [comment]
> Yes, if you use coc.nvim for completion.

That seems to have fixed it!

Sorry I'm pretty new to vim in general. 

Now there's a grey column on the left in some dark colour schemes. I guess I can have fun figuring out how to fix this now, all part of the learning experience.
