### ISSUE TITLE
Setting to disable auto update (and all telemetry)

### ISSUE THREAD

**Issue by narodnik** [neoclide/coc.nvim#3955]
**Is your feature request related to a problem? Please describe.**
The new popup menu is terrible and I can constantly annoyed by the update instrusions by Coc on my workflow. I can run this manually myself.

**Describe the solution you'd like**
Setting for coc-settings.json to disable the update prompt. Ideally I want to disable ALL telemetry.

**Describe alternatives you've considered**
I searched the docs and could not find anything in the README, internet search or the wiki on disabling telemetry and upgrade prompts.

**Comment by fannheyward** [comment]
1. there's no auto-updating in coc.nvim. It's your plugin manager to update coc.nvim.
2. there's no telemetry in coc.nvim

**Comment by chemzqm** [comment]
Could you describe what make you annoyed?
