### ISSUE TITLE
After upgrade 6810b0b <tab> broken in insert mode.

### ISSUE THREAD

**Issue by hunterlxt** [neoclide/coc.nvim#3957]
## Result from CocInfo

![image](https://user-images.githubusercontent.com/18193301/182133653-421dc17e-20ab-4a56-93a8-62c4eceec43b.png)

## Describe the bug

After upgrade 6810b0b <tab> broken in insert mode. when press <tab> for example indent it showed below:

```
E117: Unknown function: <SNR>1_CheckBackspace
```

## Reproduce the bug

  ```vim
" just paste 6810b0b version .vimrc config from readme
  ```

**Comment by chemzqm** [comment]
The example has bug, remove `<SID>` before `CheckBackspace()`

**Comment by hunterlxt** [comment]
> The example has bug, remove `<SID>` before `CheckBackspace()`

Can you fix that

**Comment by chemzqm** [comment]
It's fixed, you have to fix it in your vimrc.

**Comment by mkobayashime** [comment]
@chemzqm 
It's still not working with the `<SID>` removed, saying: `E117: Unknown function: CheckBackspace`.
Tested in 1d3c525e (v0.0.82), a4e800f5, cf651a31 (latest in release branch).
Could you look into it?

**Comment by chemzqm** [comment]
You should copy that function to your vimrc

**Comment by mkobayashime** [comment]
Oh I missed that, thanks a lot.
