### ISSUE TITLE
Weird code completion 

### ISSUE THREAD

**Issue by amgodoi** [neoclide/coc.nvim#3959]
### Steps to reproduce

1. "suggest.autoTrigger": "none",
2. Press Ctrl+Enter do suggest
3. Select the suggestion
4. Press <Enter>

Arrows keys does not navigate anymore.
<Enter> inserts a new line after selection.

### Expected behaviour

Use arrow keys to navigate and <enter> to select.

### Version of Vim

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2022 19:26:30)

### Environment

Ubuntu 22.04
rxvt-unicode-256color
bash

**Comment by fannheyward** [comment]
Post your minimal vimrc please.

**Comment by amgodoi** [comment]
Hi! I use TAB for another plugin, then I just added:

inoremap <silent><expr> <c-space>
      \ coc#pum#visible() ? coc#pum#next(1):
      \ CheckBackspace() ? "\<C-p>" :
      \ coc#refresh()
inoremap <expr><C-p> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

I am able to use <c-n> and <c-p> to navigate, but <cr> to select does not works anymore. It puts a new line and not complete the command properly (does not add a needed java import .. as example).

**Comment by chemzqm** [comment]
> , but "< cr >" to select does not works anymore.

You have to remap `<CR>` which is not remapped by coc.nvim, see `:h coc-completion-example` or README.

**Comment by amgodoi** [comment]
Worked!

Thanks a lot!!!
