### ISSUE TITLE
Disable incorrect "Update for the latest features" prompt

### ISSUE THREAD

**Issue by Piotr1215** [neoclide/coc.nvim#3960]
**Is your feature request related to a problem? Please describe.**
Installing the latest release with packer `use {'neoclide/coc.nvim', branch = 'release'}` causes following prompt to be displayed on every file open

```text
[coc.nvim] Version v0.12.0 of up is now available. Current version is v0.12.0-rc.0.45.gd38751e.
        Update for the latest features!
```

**Describe the solution you'd like**
The popup should not appear and the stable version should be installed.

**Describe alternatives you've considered**
N/A

**Additional context**

![image](https://user-images.githubusercontent.com/8086638/182183034-bf08c3a7-f054-402e-b910-a37d8624b23d.png)

**Comment by chemzqm** [comment]
Don't know what extension sends this prompt.

**Comment by Piotr1215** [comment]
I assumed it was sent by coc? How can I check what extension sends this?

**Comment by chemzqm** [comment]
Try disable extensions in `:CocList extensions`

**Comment by Piotr1215** [comment]
Thank you, I figured it out. This was not a plugin, but a LSP running from a CLI that I've added manually to the config.
I needed to downgrade it to stable release, but this is ok.
