### ISSUE TITLE
<CR> does not insert selected suggestion

### ISSUE THREAD

**Issue by njaczko** [neoclide/coc.nvim#3983]
## Result from CocInfo

vim version: NVIM v0.7.2
node version: v18.6.0
coc.nvim version: 0.0.82-ebe19461 2022-08-02 04:07:00 +0800
coc.nvim directory: /Users/nick/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

2022-08-01T21:53:48.555 INFO (pid:39962) [services] - registered service "languageserver.golang"
2022-08-01T21:53:48.556 INFO (pid:39962) [plugin] - coc.nvim initialized with node: v18.6.0 after 16ms
2022-08-01T21:54:04.232 INFO (pid:39962) [attach] - receive notification: showInfo []

## Describe the bug

After selecting a suggestion in the popup with `<Down>`, `<CR>` inserts a newline instead of the suggestion.

## Reproduce the bug

To reproduce, I just need to select a suggestion and press `<CR>`.

Minimal init.vim:
```
call plug#begin('~/.local/share/nvim/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

I am able to reproduce with tag `v0.0.82` as well, but `v0.0.81` works as expected (`<CR>` inserts the selected suggestion).

## Screenshots (optional)

Screen recording: https://imgur.com/a/jqg6zrV

In this clip I insert `w`, press `<Down>`, then press `<CR>`.

**Comment by fannheyward** [comment]
What's your output of `:verbose inoremap <CR>`? You need to remap your `<CR>`, check `::h coc-completion-example` or README.

**Comment by chemzqm** [comment]
coc.nvim doesn't remap your `<cr>` and `<tab>`, you have to remap them yourself.
