### ISSUE TITLE
Denied permissions when creating .config/coc directory

### ISSUE THREAD

**Issue by wateroverdose** [neoclide/coc.nvim#3986]
## Result from CocInfo

`coc.nvim service not started, checking environment...Service stopped for some unknown reason, try :CocStart`

Result from :CocStart:
```
[coc.nvim]: node:internal/fs/utils:348
    throw err;
    ^
Error: EACCES: permission denied, mkdir '/home/rootuser/.config/coc'
    at Object.mkdirSync (node:fs:1394:3)
    at cx.exports.makeDirSync (/home/rootuser/.local/share/nvim/plugged/coc.nvim/build/index.js:25:8410)
    at new ca (/home/rootuser/.local/share/nvim/plugged/coc.nvim/build/index.js:204:70347)
    at KZ.createMru (/home/rootuser/.local/share/nvim/plugged/coc.nvim/build/index.js:213:2767)
    at cte.init (/home/rootuser/.local/share/nvim/plugged/coc.nvim/build/index.js:278:22046)
    at new SC (/home/rootuser/.local/share/nvim/plugged/coc.nvim/build/index.js:302:7966)
    at tie (/home/rootuser/.local/share/nvim/plugged/coc.nvim/build/index.js:302:18316)
    at Object.<anonymous> (/home/rootuser/.local/share/nvim/plugged/coc.nvim/build/index.js:302:20128)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/rootuser/.config/coc'
}
Node.js v18.7.0
```

## Describe the bug

Whenever I start nvim, coc throws a denied permission error when creating a `coc` directory in `~/.config`. After continuing, node throws basically the same error, this time about `~/.config/coc/extensions`. I tried running nvim as superuser and no error is thrown, but now nvim is not recognizing the init.vim file.

## Reproduce the bug

I'm running Ubuntu wsl2 on win10 and have vim-plug correctly installed.

- create a mini.vim file:
```
call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```
- `❯ nvim -u mini.vim`
- run `:PlugInstall`
- `E739: Cannot create directory /home/rootuser/.config/coc: permission denied`

## Screenshots
![obraz](https://user-images.githubusercontent.com/96541955/182366256-7ccc1b05-1757-416b-a271-2004a6714fae.png)
![obraz](https://user-images.githubusercontent.com/96541955/182366296-d19f8dc8-4dff-485b-912f-21111fb49203.png)
- i tried reinstalling coc:
![obraz](https://user-images.githubusercontent.com/96541955/182367157-5bc82295-1674-43b7-a62b-ee9506074406.png)

**Comment by chemzqm** [comment]
Fix the permission issue or use `:h g:coc_config_home`

**Comment by wateroverdose** [comment]
> Fix the permission issue or use `:h g:coc_config_home`

Do you have any idea on how to fix the permission issue? I've been looking for a solution for a couple of hours now and I'm losing my mind.

**Comment by wateroverdose** [comment]
I think I managed to fix it. Changed g:coc_data_home to another directory.

**Comment by liamtimms** [comment]
Well, what are the current permissions on your `.config` directory? It's a little confusing how you seem to have both `root` and also a user account named `rootuser.` 

Run `stat ~/.config/` to see permissions. It should belong to your user account, not the root account.

**Comment by wateroverdose** [comment]
> Well, what are the current permissions on your `.config` directory? It's a little confusing how you seem to have both `root` and also a user account named `rootuser.`
> 
> Run `stat ~/.config/` to see permissions. It should belong to your user account, not the root account.

Hi! Sorry for responding late, I've taken a little break. I've used `chown` to claim the `.config` folder and it worked. Kinda weird how I already tried earlier and it did nothing. Still thanks for trying to help.
