### ISSUE TITLE
Cannot remap keys used for jump to next/previous position

### ISSUE THREAD

**Issue by benzwt** [neoclide/coc.nvim#3987]
## Result from CocInfo

vim version: VIM - Vi IMproved 9.0 9000124
node version: v12.22.9
coc.nvim version: 0.0.82-ebe19461 2022-08-02 04:07:00 +0800
coc.nvim directory: /home/anonymous/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-08-02T20:26:15.537 INFO (pid:19463) [plugin] - coc.nvim initialized with node: v12.22.9 after 90ms
2022-08-02T20:26:21.367 INFO (pid:19463) [attach] - receive notification: showInfo []

## Describe the bug
Cannot remap keys used for jump to next/previous position.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file .vimrc in ~/.vim/:

```vim
set nocompatible
syntax on
filetype plugin indent on
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
" or 
" Plug 'neoclide/coc.nvim', {'tag': 'v0.0.82'}
call plug#end()
```
- create coc-settings.json:
  - start vim
  - and enter command
```vim
:CocConfig
```
  - edit file as belows:
  ```json
{
	"cursors.nextKey": "<C-j>",
	"cursors.previousKey": "<C-k>"
}

```

- Start (neo)vim with command: `vim -u ~/.vim/vimrc`

- Operate vim.

**Comment by chemzqm** [comment]
Cursors configuration used for multiple cursor support, see `:h coc-completion` for completion of coc.nvim.
