### ISSUE TITLE
Completion no longer inserts [A] suggestions 

### ISSUE THREAD

**Issue by liamtimms** [neoclide/coc.nvim#3988]
## versions

vim version: NVIM v0.7.2
node version: v16.16.0
coc.nvim version: 0.0.82-ebe19461 2022-08-02 04:07:00 +0800
coc.nvim directory: /home/liam/.config/nvim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2022-08-02T08:57:54.946 INFO (pid:16924) [plugin] - coc.nvim initialized with node: v16.16.0 after 168ms
2022-08-02T08:57:58.660 WARN (pid:16924) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-08-02T09:00:24.951 INFO (pid:16924) [attach] - receive notification: showInfo []

## Describe the bug

Using current CoC configuration settings provided in the README, suggestions tagged [S] or [LS] work as expected and insert into the buffer with `<cr>`.  However, suggestions tagged [A] are no longer inserted.

## Screenshots

![Screenshot from 2022-08-02 09-08-52](https://user-images.githubusercontent.com/14281621/182382666-1e508953-a9aa-45c1-94af-1910d50f52a0.png)

![image](https://user-images.githubusercontent.com/14281621/182383576-4eb3ae10-a337-42fe-86f6-9cc70c899145.png)

Hitting `<cr>` works as expected for the suggestions in the screenshot (tagged [S] or [LS], presumably from coc-snippets and the language server) but not for [A] tagged suggestions using the words in the buffer.

**Comment by chemzqm** [comment]
See `:h coc#pum#insert()` and `:h coc#pum#confirm()`
Use `"suggest.noselect": false` to disable automatic selection.

**Comment by liamtimms** [comment]
It's not clear how from `h: coc#pum#insert()` and `:h coc#pum#confirm()` how they relate to the previous `coc#_select_confirm()` function. Do we need to call both now?

**Comment by chemzqm** [comment]
No, try minimal vimrc

**Comment by liamtimms** [comment]
As a workaround I removed:
 
```
set completeopt+=noinsert
```
From my config. It is odd that this was not an issue previously and affected some suggestions but not others but this mostly deals with it.

**Comment by chemzqm** [comment]
It has nothing to do with completion of coc.nvim
