### ISSUE TITLE
If opening files with Denite, kanguage server wont start.

### ISSUE THREAD

**Issue by Kazimazi** [neoclide/coc.nvim#399]
My usual workflow is `cd`-ing into a directory I need to work in, type `nvim` and then use FZF/Denite to find files.
When opening with Denite LS wouldn't activate while with FZF works properly. Tried for php and python projects with coc-phpls and coc-pyls... same symptoms.

CocInfo:

```
## versions

vim version: NVIM v0.3.4
node version: v11.8.0
coc.nvim version: 0.0.50
term: xterm-256color
platform: linux

## Error messages

## Output channel: snippets
... snippets loading ...

## Output channel: highlight
[Info  - 2:08:15 PM] Highlight server running in node v11.8.0

```

**Comment by chemzqm** [comment]
It happens sometime, because Denite would block other channel from receive events from neovim.
Try use:
```
set shortmess=aFc
set cmdheight=2
set hidden " allow buffer switch without saving
```
in your .vimrc, this would help most of time.

Or use https://github.com/neoclide/coc-lists instead.
