### ISSUE TITLE
suggest.completionItemKindLabels 能否支持macro宏

### ISSUE THREAD

**Issue by HaomingJu** [neoclide/coc.nvim#3990]

**Comment by HaomingJu** [comment]
![image](https://user-images.githubusercontent.com/24786568/182572887-4d2040c1-f226-467f-99f2-759e3cb2e677.png)

目前对于所有的宏定义，均判断为Text类型

**Comment by chemzqm** [comment]
No CompleteItemKind for `Macro`, need implemented by LSP and your language server.
