### ISSUE TITLE
Regression when using tab completion to complete first element

### ISSUE THREAD

**Issue by klement** [neoclide/coc.nvim#3997]
Hi,

I've upgraded coc.nvim today and see a regression. Got a popup that I need to modify <CR> and <TAB> mappings so I grabbed the example config.

Behaviour which I see as a regression is that irregardless of `"suggest.enablePreselect"` being `true` or `false`, first suggestion is highlighted, but **not inserted**.

So in situation where possible suggestions are 

AAA
AAB
AAC

and I type `A<TAB>`, it selects AAA, but **doesn't insert** it, 2nd press of `<TAB>` selects AAC and **inserts** it, 3rd `<TAB>` selects AAA and **inserts** it. 4th press of `TAB` selects AAA and **inserts** it this time.

Previous behaviour was AAA would be selected and inserted on first tab.

When there is only one suggestion say for example there is "a_very_long_and_unique_identifier" and I type `a_very_long_and_unique_<TAB>` I get a popup with only one suggestion: `a_very_long_and_unique_identifier`, but it's **not inserted**, then pressing `<TAB>` again, it gets deselected. Then third `<TAB>` selects it again and this time also **inserts it**.

I would like to have it inserted the moment it's selected on first push of TAB. 

I see no reason for first entry to be behaving differently from others.

Thanks,
Klement

**Comment by chemzqm** [comment]
It's expected since `"suggest.noselect"` changed to `false` by default, so that preselect and selection feature could work.

**Comment by klement** [comment]
Thanks for the insight.

Adding `"suggest.noselect": true` brings back old behaviour.

**Comment by bulletmark** [comment]
Odd change of default. I thought the new version was simply broken and expected a fix would come quickly. After another week or so I came here looking and found this issue to discover I was expected to change my configuration  :(

**Comment by drdavella** [comment]
I had this same issue. Am I mistaken or did it used to insert the first suggestion _without_ hitting <TAB> first? This was very useful behavior but I have no idea how to restore it after this update.

**Comment by klement** [comment]
> I had this same issue. Am I mistaken or did it used to insert the first suggestion _without_ hitting first? This was very useful behavior but I have no idea how to restore it after this update.

See my comment above:

https://github.com/neoclide/coc.nvim/issues/3997#issuecomment-1204104204

After invoking :CocConfig and adding mentioned line, I got the old behaviour back.

**Comment by drdavella** [comment]
@klement thanks, I did see your comment and it was helpful for me. My case is slightly different: my setup used to automatically complete the first selection _without_ hitting `<TAB>` first. This no longer seems to happen, regardless of configuration.
