### ISSUE TITLE
Is there a way to do import manually for coc-tsserver

### ISSUE THREAD

**Issue by ruanyl** [neoclide/coc.nvim#400]
It is possible to do import automatically by selecting autocomplete items. But how to do import manually? for example, if I want to import the class under the cursor.

**Comment by chemzqm** [comment]
Use codeAction, latest tsserver have support for that:
```
" Remap for do codeAction of selected region, ex: `<leader>aap` for current paragraph
vmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
```
