### ISSUE TITLE
unknown function coc#pum#visible()

### ISSUE THREAD

**Issue by ntapro1221** [neoclide/coc.nvim#4006]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by Tarbetu** [comment]
You might want to check the version of coc.nvim. In my setup, it fixed after an update.
