### ISSUE TITLE
can't change completion key (trying to switch it to <tab>)

### ISSUE THREAD

**Issue by Salomanuel** [neoclide/coc.nvim#4008]
Default CoC completes on Return, however, I want to complete only on pressing Tab and reserve Return for its normal behaviour which is entering a new line. How do I do that?

I did several attempts, but nothing of this works:

            inoremap <silent><expr> <tab> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<TAB>"
            inoremap <silent><expr> <cr> "\<c-g>u\<CR>"

            let g:coc_snippet_next = '<tab>'
            nmap <silent> gd <Plug>(coc-definition)
            nmap <silent> gD <Plug>(coc-implementation)
            nmap <silent> gr <Plug>(coc-references)

            function! CheckBackspace() abort
              let col = col('.') - 1
              return !col || getline('.')[col - 1]  =~# '\s'
            endfunction

            inoremap <silent><expr> <Tab>
                  \ coc#pum#visible() ? coc#pum#next(1) :
                  \ CheckBackspace() ? "\<Tab>" :
                  \ coc#refresh()
            inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

any ideas?

**Comment by Salomanuel** [comment]
this is the output from `:verbose imap <cr>`
```
i  <CR>        *@<CR>
        Last set from ~/.vim/bundle/vim-endwise/plugin/endwise.vim line 121
i  <CR>        & EndwiseAppend("\r")
        Last set from ~/.vim/bundle/vim-endwise/plugin/endwise.vim line 141
```

**Comment by chemzqm** [comment]
It's your vim-endwise plugin causing trouble

**Comment by Salomanuel** [comment]
I removed vim-endwise and that made absolutely no difference in the outcomes

but I found out that 
```
              inoremap <silent><expr> <tab>
                    \ coc#pum#visible() ? coc#pum#confirm()
                    \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```
does work, but then `<tab>` becomes `<CR>` in every instance of using vim, which is not acceptable in my workflow

any ideas?
