### ISSUE TITLE
Change coc warn and error in lightline

### ISSUE THREAD

**Issue by taigacute** [neoclide/coc.nvim#401]
**Is your feature request related to a problem? Please describe.**
can add option to change warning and error in lightline?

**Comment by chemzqm** [comment]
PR for better status is welcome, the function `coc#status` is a basic exmaple, create your own function if you don't like it.

**Comment by chemzqm** [comment]
I've add support for `g:coc_status_error_sign` and `g:coc_status_warning_sign`

**Comment by taigacute** [comment]
> I've add support for `g:coc_status_error_sign` and `g:coc_status_warning_sign`

i found them in coc.vim.thanks a lot

**Comment by taigacute** [comment]
@chemzqm  I think that defining a function like this is more efficient, it will appear when warnings and errors occur.
```
'component_function': {
      \   'cocstatus': 'LightLinecoc'

function! LightLineCoc() 
    if empty(get(g:, 'coc_status', '')) && empty(get(b:, 'coc_diagnostic_info', {})) 
        return ''
    endif 
    return trim(coc#status())
endfunction

```

**Comment by chemzqm** [comment]
ok，consider send a pull request.

**Comment by youssef-lr** [comment]
When using a custom sign how can I change its highlight? Thanks.

**Comment by chemzqm** [comment]
> When using a custom sign how can I change its highlight? Thanks.

See `:h coc-highlights`

**Comment by youssef-lr** [comment]
I did. It only controls the highlight of the signcolumn signs. I wanna style the error/warning signs in lighltline. Thank you.

**Comment by oblitum** [comment]
folks, I have a pretty setup for lightline in my dotfiles, works fine with coc.nvim, I guess I'm not missing anything. There's even feedback for quick fixes: https://github.com/oblitum/dotfiles/blob/ArchLinux/.vimrc

**Comment by oblitum** [comment]
Screenshots in README.

**Comment by oblitum** [comment]
![simplescreenrecorder](https://user-images.githubusercontent.com/1269815/53687952-72719080-3d1a-11e9-8be9-db8fd58ca67e.gif)

**Comment by youssef-lr** [comment]
Thanks! I'll take a look at your config.

**Comment by taigacute** [comment]
> 谢谢！我来看看你的配置。

@youssef-lr   you can see my config https://github.com/taigacute/ThinkVIm

**Comment by youssef-lr** [comment]
Thanks a lot @oblitum ! These are the bits I copied from your config to style the signs, if anyone else is interested.

```vim
let g:lightline = {
  ...
  \ 'colorscheme': 'Tomorrow_Night',
	\ 'active': {
	\   'left': [ [ 'mode', 'paste' ],
	\             [ 'readonly', 'filename', 'modified', 'coc_error', 'coc_warning', 'coc_hint', 'coc_info' ] ],
	\   'right': [ [ 'lineinfo',  ],
	\              [ 'percent' ],
	\              [ 'fileformat', 'fileencoding', 'filetype'] ]
	\ },

  \ 'component_expand': {
  \   'coc_error'        : 'LightlineCocErrors',
  \   'coc_warning'      : 'LightlineCocWarnings',
  \   'coc_info'         : 'LightlineCocInfos',
  \   'coc_hint'         : 'LightlineCocHints',
  \   'coc_fix'          : 'LightlineCocFixes',
  \ },
  ...
  \ }

```

```vim
let g:lightline.component_type = {
\   'coc_error'        : 'error',
\   'coc_warning'      : 'warning',
\   'coc_info'         : 'tabsel',
\   'coc_hint'         : 'middle',
\   'coc_fix'          : 'middle',
\ }

function! s:lightline_coc_diagnostic(kind, sign) abort
  let info = get(b:, 'coc_diagnostic_info', 0)
  if empty(info) || get(info, a:kind, 0) == 0
    return ''
  endif
  try
    let s = g:coc_user_config['diagnostic'][a:sign . 'Sign']
  catch
    let s = ''
  endtry
  return printf('%s %d', s, info[a:kind])
endfunction

function! LightlineCocErrors() abort
  return s:lightline_coc_diagnostic('error', 'error')
endfunction

function! LightlineCocWarnings() abort
  return s:lightline_coc_diagnostic('warning', 'warning')
endfunction

function! LightlineCocInfos() abort
  return s:lightline_coc_diagnostic('information', 'info')
endfunction

function! LightlineCocHints() abort
  return s:lightline_coc_diagnostic('hints', 'hint')
endfunction
\ }
```

![image](https://user-images.githubusercontent.com/9680864/53699862-85e92e00-3de4-11e9-95d6-d2b957061aed.png)

**Comment by oblitum** [comment]
@youssef-lr thanks for posting your excerpt, it's in good time, since I'm moving from GitHub.

**Comment by FelipeMarcelino** [comment]
The symbols aren't showing and I have them set in my coc-settings.json!

**Comment by chemzqm** [comment]
@FelipeMarcelino should be problem of your font.

**Comment by sbromberger** [comment]
It's not a font problem. `coc_user_config['diagnostic'][a:sign . 'Sign']` is where it's failing, because `g:coc_user_config` isn't defined. If you put something in the `catch` string, that displays.

**Comment by sbromberger** [comment]
```
  function! s:lightline_coc_diagnostic(kind, sign) abort
    let info = get(b:, 'coc_diagnostic_info', 0)
    if empty(info) || get(info, a:kind, 0) == 0
      return ''
    endif
    return printf('%s %d', a:sign, info[a:kind])
  endfunction
  function! LightlineCocErrors() abort
    return s:lightline_coc_diagnostic('error', 'E')
  endfunction
  function! LightlineCocWarnings() abort
    return s:lightline_coc_diagnostic('warning', 'W')
  endfunction
  function! LightlineCocInfos() abort
    return s:lightline_coc_diagnostic('information', 'I')
  endfunction
  function! LightlineCocHints() abort
    return s:lightline_coc_diagnostic('hints', 'H')
  endfunction
```
works for me (and simplifies things a bit).

**Comment by oblitum** [comment]
@sbromberger it could have been indeed a font problem for him, since he doesn't state whether he's basing his conf on that specific code excerpt or not.

**Comment by oblitum** [comment]
fwiw my settings have changed/improved/refactored since that time.
