### ISSUE TITLE
set document as signature in python

### ISSUE THREAD

**Issue by YuCao16** [neoclide/coc.nvim#4017]
**Is your feature request related to a problem? Please describe.**
I'm using `coc-pyright`, it support signature but not enought as it's a [static type checker](https://github.com/microsoft/pyright/issues/2855). For example, if I want to check signature for pandas.DataFrame(), it will return nothing.

**Describe the solution you'd like**
I have noticed that the first part of the document actually pretty useful:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/62466929/183312687-d6fb6524-732f-4073-baf4-8d62c2a1b006.png">
Is it possible to set this part as the signature, it at least better than nothing.

**Describe alternatives you've considered**
I have tried to create a keybinding to show document in insert mode, but it seem the popup window doesn't show out, I might be wrong.

**Additional context**
<img width="956" alt="image" src="https://user-images.githubusercontent.com/62466929/183312805-aec47b91-6225-4275-84c9-54861d12dd69.png">
Another thing a little bit confused me is, at you can see in the image above, the document is duplicated, it might because I install another language server `coc-jedi`. I think the second one is more readable, how can I config to show the second one at first?

**Comment by fannheyward** [comment]
For signature issue, you should use Type stubs to improve it. For the second issue, you can disable document from Pyright, check coc-pyright.
