### ISSUE TITLE
<CR> auto-complete the first popup item even not select it

### ISSUE THREAD

**Issue by omegahh** [neoclide/coc.nvim#4018]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.2
node version: v18.7.0
coc.nvim version: 0.0.82-d8561387 2022-08-07 04:42:37 +0800
coc.nvim directory: /home/omega/Codes/dotfiles/nvim/plugged/coc.nvim
term: tmux
platform: linux
```

## Describe the bug

Here is my coc.nvim configuration.
<img width="1032" alt="截屏2022-08-08 上午11 38 03" src="https://user-images.githubusercontent.com/5026687/183333571-1866292f-75fc-4062-9c39-7feca11ecc72.png">

I use \<tab\> for triggering completion, selecting candidates, and \<CR\> for confirming completion.
But when I didn't select any completion candidates, Pressing \<CR\> will expand the typed text to the first completion candidate, which I wish not.

Here is an example:
<img width="660" alt="截屏2022-08-08 上午11 12 08" src="https://user-images.githubusercontent.com/5026687/183334818-f1d179a5-c64e-485a-a3ae-4eb659c6534b.png">
I typed 'result' and the popup window showed up, But I didn't select any candidates (didn't press \<tab\>). I wanted to press \<CR\> for end this line, but \<CR\> expanded 'result' to 'result_blast_main'.

<img width="660" alt="截屏2022-08-08 上午11 12 08" src="https://user-images.githubusercontent.com/5026687/183335341-837253f0-69f0-427c-8de0-ee80bdbcc798.png">

## How do I fix it?

I found a workaround by modifying the key-mapping of \<CR\>, as shown in the following:

```
inoremap <silent><expr> <CR> complete_info()["selected"] != "-1" ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

Is it the right configuration for my preferring or just the current coc.nvim is dysfunctional in it

**Comment by xvim64** [comment]
Try this patch and disable 'inoremap <silent><expr> <CR> ...'

When pressing tab, 's:pum_index' starts from 0 not 1.

[pum.vim.patch.zip](https://github.com/neoclide/coc.nvim/files/9279097/pum.vim.patch.zip)

```
diff --git a/autoload/coc/pum.vim b/autoload/coc/pum.vim
index 58979af..301b1cc 100644
--- a/autoload/coc/pum.vim
+++ b/autoload/coc/pum.vim
@@ -2,6 +2,7 @@ scriptencoding utf-8
 let s:is_vim = !has('nvim')
 let s:pum_bufnr = 0
 let s:pum_winid = 0
+let s:pum_once = 1
 let s:pum_index = -1
 let s:inserted = 0
 let s:virtual_text = 0
@@ -34,6 +35,7 @@ function! coc#pum#close(...) abort
   if coc#float#valid(s:pum_winid)
     if get(a:, 1, '') ==# 'cancel'
       let input = getwinvar(s:pum_winid, 'input', '')
+      let s:pum_once = 1
       let s:pum_index = -1
       call s:insert_word(input)
       call s:on_pum_change(0)
@@ -56,6 +58,7 @@ endfunction
 
 function! coc#pum#select_confirm() abort
   if s:pum_index < 0
+    let s:pum_once = 1
     let s:pum_index = 0
     call s:on_pum_change(0)
   endif
@@ -272,6 +275,10 @@ endfunction
 function! s:get_index(next) abort
   let size = coc#compat#buf_line_count(s:pum_bufnr)
   if a:next
+    if s:pum_once && s:pum_index == 0
+      let s:pum_once = 0
+      let s:pum_index = -1
+    endif
     let index = s:pum_index + 1 == size ? -1 : s:pum_index + 1
   else
     let index = s:pum_index == -1 ? size - 1 : s:pum_index - 1
@@ -354,6 +361,7 @@ function! coc#pum#create(lines, opt, config) abort
     let firstline = s:get_firstline(lnum, len(a:lines), config['height'])
     call coc#compat#execute(s:pum_winid, 'call winrestview({"lnum":'.lnum.',"topline":'.firstline.'})')
   endif
+  let s:pum_once = 1
   let s:pum_index = get(config, 'index', -1)
   call coc#dialog#place_sign(s:pum_bufnr, s:pum_index + 1)
   call setwinvar(s:pum_winid, 'kind', 'pum')
```

**Comment by omegahh** [comment]
@xvim64 Thank you, I found my solution would disable the snippet expansion.

**Comment by omegahh** [comment]
@xvim64 Your patch is very useful for resolving my problem. But there is a new problem raised. 

Assuming that I have a variable name is 'foo_bar',  and I have typed 'bar' already. If I type a 'f' before 'bar',  then 'foo_bar' could be the first candidate in the auto popup window. When I press \<tab\>, the first candidate would be selected, and the text would be completed as 'foo_bar'. What we expect is that \<CR\> will confirm completion and jump to the end of this text. 
But comment "inoremap \<silent\> \<expr\> \<CR\>" would break this function, pass a real "\<CR\>" to editor, and the result becomes:

```
foo_
bar
```
 
To author of coc.nvim, who I appreciate a lot for this amazing plugin:
Before the new custom popup menu version published, All functions like \<tab\> for selecting candidates, \<CR\> for confirming selected candidates (including expand snippets), and completing items with a typed postfix worked well. I have no idea of how to fix it in this new version of coc.nvim.

This problem is pretty annoying especially when my script has a lot numeric numbers, like 1000, 1101, ....
If I want to type 
```
a = 1
b = 2
``` 
(which is very common in python codes) by typing `a<space>=<space>1<cr>b<space>=<space>2<cr>`, currently, the result would be

```
a = 1101
b = 2
```

**Comment by omegahh** [comment]
All right, I should use configuration showed from this repo's README file rather than from `help cot-completion-example`. I will close this issue.

**Comment by xvim64** [comment]
> All right, I should use configuration showed from this repo's README file rather than from `help cot-completion-example`. I will close this issue.

Restore to the original pum.vim

and add

"suggest.noselect":true,

in your coc-settings.json


I found the setting in

https://github.com/neoclide/coc.nvim/releases/tag/v0.0.82

**Comment by chemzqm** [comment]
@omegahh use
```vim
inoremap <silent><expr> <cr> coc#pum#visible() && coc#pum#info()['index'] != -1 ? coc#pum#confirm() : "\<C-g>u\<CR>"
```
You may also need
```
"suggest.noselect": true
"suggest.enablePreselect": false
```
in your coc-settings.json
