### ISSUE TITLE
An option to only lint/run diagnostics when you've left insert mode

### ISSUE THREAD

**Issue by joereynolds** [neoclide/coc.nvim#403]
**Is your feature request related to a problem? Please describe.**
When I am in insert mode in a large file (1000+ lines) and typing, there is a lag introduced from Coc running diagnostics

**Describe the solution you'd like**
I would like an option (Ale has `g:ale_lint_on_insert_leave`) to disable Coc linting while in insert mode.

**Comment by chemzqm** [comment]
The diagnostic refresh should be quite fast on neovim, I've tested it with file contains 10k+ lines.
I will add an option to disable diagnostic refresh on insert mode.

**Comment by chemzqm** [comment]
Thers is `"coc.preferences.diagnostic.refreshOnInsertMode"` and it's default to `false`, did you change to `true`?
If the language server is slow while your typing, it's problem of that server.

**Comment by chemzqm** [comment]
Need more information for the lag.

**Comment by andys8** [comment]
Hey @chemzqm, I'm having performance issues, because parsing is triggered a lot. I'm not sure, if it's a problem with coc or elm-language-server. Can you have a look and help me out? :)

https://github.com/elm-tooling/elm-language-server/issues/89

**Comment by chemzqm** [comment]
It's problem of elm-language-server
