### ISSUE TITLE
Hooks to handle uncaught errors

### ISSUE THREAD

**Issue by igbanam** [neoclide/coc.nvim#4037]
**Is your feature request related to a problem? Please describe.**

I'm using a remote LSP; sometimes this lsp could get disconnected. When that happens, there's an error message along the lines of 

```
[coc.nvim]: UnhandledRejection: Connection to server got closed. Server would not be restarted.
Error: Connection to server got closed. Server would not be restarted.
    at: Jf.handleConnectionClosed (path/to/coc.nvim/build/index.js:234:1006)
```

**Describe the solution you'd like**

Perhaps there could be some way in my `.vimrc` to define custom handlers for errors like these. I'd like to be able to do something like

```
let g:coc_error_handlers = { 'UnhandledRejection': MyCustomRejectionHandler(e) }

function! MyCustomRejectionHandler(e)
  " …where 'sc' denotes "server_connection"
  " if error message includes `Connection to server got closed`
  "   let b:coc_sc_error = 1
  "   let b:coc_sc_error_message = e.message
  return [b:coc_sc_error, b:coc_sc_error_message]
endfunction
```

Then somewhere down the line, I could use the output of this handler in a custom statusline message. 

**Describe alternatives you've considered**

nvim-lsp offers this; some ability to report on the state of a remote language server. 

I'm just trying not to switch my rig since I've grown accustomed to coc.nvim over the years. 

**Additional context**

The major ask here is a way to handle server errors myself rather than having to manually fox it every time the internet cuts off.

**Comment by igbanam** [comment]
Line number is `235` now; ~not 234~

**Comment by chemzqm** [comment]
That error won't be thrown with PR #4023

**Comment by igbanam** [comment]
Thanks for your work on the PR. I still see the error but it's manageable now. It goes off after some 3 to 4 errors.

I may have not been clear with the ask prior. What I meant was, is it possible for me to define a custom handler for events which happen in coc.nvim?

I know this isn't possible now, but are there plans to have it?

**Comment by chemzqm** [comment]
Create a coc.nvim extension should helps on most cases.
