### ISSUE TITLE
Autocomplete key...🔑Enter🔑... where are you???

### ISSUE THREAD

**Issue by Vanillma** [neoclide/coc.nvim#4038]
## Describe the bug
Hi bro
Recently, with the new update, I noticed that auto-completion no longer works after selecting an option from the suggested list (with the help of the up and down arrows) with the enter key!!
And I have to press the TAB key!!
Why did this happen and can it be changed??... How do I map "enter key" so that it both creates a new line and extands the snippets!?...
Thanks

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by lf-** [comment]
You need the bindings from `:h coc-completion-example` in your vimrc:

```vim
  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
  endfunction

  " Insert <tab> when previous text is space, refresh completion if not.
  inoremap <silent><expr> <TAB>
	\ coc#pum#visible() ? coc#pum#next(1):
	\ <SID>check_back_space() ? "\<Tab>" :
	\ coc#refresh()
  inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

  if has('nvim')
    inoremap <silent><expr> <c-space> coc#refresh()
  else
    inoremap <silent><expr> <c-@> coc#refresh()
  endif
 
  inoremap <expr> <cr> coc#pum#visible() ? coc#_select_confirm() : "\<CR>"

```

**Comment by chemzqm** [comment]
See #3985

**Comment by lf-** [comment]
btw @chemzqm the readme still has the old bindings

**Comment by chemzqm** [comment]
It's been updated

**Comment by Vanillma** [comment]
> See #3985

Thanks bro, You Rock!😃
Everything works great now with this config!
The new menus are very beautiful, precise, elegant and orderly and have a very, very high speed, they are with automatic selection of the first item from the list, just like VS-Code and famous IDEs.

---> and all this happens without installing heavy and additional Python!!! <---

Now working with vim is much sweeter and dreamier than before😋
Thanks to this project and its developers and maintainers...they finally managed to avoid the useless combination of vim and python for all developers (for example, I'm js) and give the community a taste of a pure vim (Vanilla) experience
----------------
And a few tips!!

1- The new update of vim was accompanied by the news of the expansion and development of the vim script and also the promise of adding classes in the future... was it through this update that the possibility of adding an automatic selector was added?... because I remember that before only with Python was possible :)

2- In my opinion, it is better to add this configuration to "enter map" to the readme, because the sudden change of this key will mess up the programmer's coding for a while... and it will take time to get used to the new key.
(although I When I updated yesterday, I was going crazy because of this change!!)

3- Do you welcome the translation of the readme into another language??...I might convert the readme into Persian for Iranians in the future!
-----------------
Sorry for taking so long
Thanks

**Comment by fannheyward** [comment]
> I might convert the readme into Persian for Iranians in the future

PR is welcome!
