### ISSUE TITLE
complete on <tab> broken

### ISSUE THREAD

**Issue by Salomanuel** [neoclide/coc.nvim#4043]
Default CoC completes on Return, however, I want to complete only on pressing Tab and reserve Return for its normal behaviour which is entering a new line. How do I do that?

I did several attempts, but nothing of this works:

            inoremap <silent><expr> <tab> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<TAB>"
            inoremap <silent><expr> <cr> "\<c-g>u\<CR>"

            let g:coc_snippet_next = '<tab>'
            nmap <silent> gd <Plug>(coc-definition)
            nmap <silent> gD <Plug>(coc-implementation)
            nmap <silent> gr <Plug>(coc-references)

            function! CheckBackspace() abort
              let col = col('.') - 1
              return !col || getline('.')[col - 1]  =~# '\s'
            endfunction

            inoremap <silent><expr> <Tab>
                  \ coc#pum#visible() ? coc#pum#next(1) :
                  \ CheckBackspace() ? "\<Tab>" :
                  \ coc#refresh()
            inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

I found out that 
```
              inoremap <silent><expr> <tab>
                    \ coc#pum#visible() ? coc#pum#confirm()
                    \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```
does work, but then `<tab>` becomes `<CR>` in every instance of using vim, which is not acceptable in my workflow

any ideas?

**Comment by fannheyward** [comment]
Try `inoremap <silent><expr> <tab> coc#pum#visible() ? coc#pum#confirm() : "\<tab>"`

**Comment by Salomanuel** [comment]
> Try `inoremap <silent><expr> <tab> coc#pum#visible() ? coc#pum#confirm() : "\<tab>"`

Complete works, but <tab> still becomes <CR> and it's impossible to insert tabulations :(

**Comment by fannheyward** [comment]
> inoremap <silent><expr> <tab> coc#pum#visible() ? coc#pum#confirm() : "\<tab>"

In my tests, `<tab>` won't becomes `<CR>`

**Comment by Salomanuel** [comment]
FIXED! Omg, thank you, I've been going crazy with this for weeks!
Works like a charm!

Turns out I didn't properly comment out the previous lines of the coc configuration, but your solution did the trick!

**Comment by tan-wei** [comment]
Ok, after disable two plugins `YouCompleteMe` and `ultisnipets`, what @fannheyward says works.

So is there anything I can do to ensure override the key map by other plugins instead of just disable them?

**Comment by chemzqm** [comment]
Use `:verbose imap` to checkout your insert key-mappings

**Comment by tan-wei** [comment]
> Ok, after disable two plugins `YouCompleteMe` and `ultisnipets`, what @fannheyward says works.
> 
> So is there anything I can do to ensure override the key map by other plugins instead of just disable them?

OK, I know, just change their key map.
