### ISSUE TITLE
Iterating through menu options jumps to second entry

### ISSUE THREAD

**Issue by niculaionut** [neoclide/coc.nvim#4044]
I've recently switched to the latest version of `coc.nvim`.
For iterating through the pop-up menu options, I have the following configuration (same as the one from `:h coc_completion_example`):

```vim
  inoremap <silent><expr> <TAB>
	\ coc#pum#visible() ? coc#pum#next(1):
	\ <SID>check_back_space() ? "\<Tab>" :
	\ coc#refresh()
  inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
```

The problem is that, in my previous vim config, pressing TAB when the pop-up menu was visible would start from the *first* entry, not jump to the *second*.

Example:

![image](https://user-images.githubusercontent.com/61749849/184133074-ea85b59c-a575-4640-9eba-45ae921a1d7a.png)

Now, after pressing TAB, it puts me on the second entry of the menu list:
![image](https://user-images.githubusercontent.com/61749849/184133576-7ea61f0e-7581-4b3d-b0f3-410835d889a3.png)

That's not the behavior I want. When I press the first TAB I want it to start from the first entry, like this:

![image](https://user-images.githubusercontent.com/61749849/184133737-30578905-99b9-484e-b0c9-2f44e526e3a2.png)

How can I configure it to do what I want?

**Comment by OkanEsen** [comment]
Set `"suggest.noselect": true` in `coc-settings.json`.

See: https://github.com/neoclide/coc.nvim/discussions/3985

**Comment by chemzqm** [comment]
You can enable `noselect` feature or use `coc#pum#insert()` to insert word or use  `coc#_select_confirm()` to confirm completion.
