### ISSUE TITLE
Dismissing indexing status window

### ISSUE THREAD

**Issue by xim** [neoclide/coc.nvim#4049]
I use ccls to index a huge project. This works quite well, but occasionally the status window gets stuck at 99% indexing:

![image](https://user-images.githubusercontent.com/169057/184363492-fc998441-6e51-48b9-b644-43faf6c60b49.png)

At the time the computer / ccls are idle.

This is a bit distracting and I would like to be able to dismiss it in general. Is there a way to manually dismiss it?

**Comment by chemzqm** [comment]
`:h coc-config-notification-disabledProgressSources`
