### ISSUE TITLE
error loading workspace

### ISSUE THREAD

**Issue by jackwiseman** [neoclide/coc.nvim#4063]
[coc.nvim]: UnhandledRejection: c is not iterable
TypeError: c is not iterable
    at /root/.local/share/nvim/plugged/coc.nvim/build/index.js:214:23865
    at async Promise.all (index 0)
    at async Bv.provideInlayHints (/root/.local/share/nvim/plugged/coc.nvim/build/index.js:214:23710)
    at async VC.renderRange (/root/.local/share/nvim/plugged/coc.nvim/build/index.js:303:2643)
    at async /root/.local/share/nvim/plugged/coc.nvim/build/index.js:303:3868

## Result from CocInfo

16T18:25:05.862 INFO (pid:6818) [attach] - receive notification: highlight []
   19 2022-08-16T18:25:08.544 INFO (pid:6818) [attach] - receive notification: highlight []
   18 2022-08-16T18:25:11.461 INFO (pid:6818) [services] - registered service "go"
   17 2022-08-16T18:25:11.464 INFO (pid:6818) [services] - gopls state change: stopped => starting
   16 2022-08-16T18:25:11.581 INFO (pid:6818) [services] - gopls state change: starting => running
   15 2022-08-16T18:25:11.594 INFO (pid:6818) [services] - service go started
   14 2022-08-16T18:25:12.400 ERROR (pid:6818) [server] - unhandledRejection  Promise {
   13   <rejected> TypeError: c is not iterable
   12       at /root/.local/share/nvim/plugged/coc.nvim/build/index.js:214:23865
   11       at async Promise.all (index 0)
   10       at async Bv.provideInlayHints (/root/.local/share/nvim/plugged/coc.nvim/build/index.js:214:23710)
    9       at async VC.renderRange (/root/.local/share/nvim/plugged/coc.nvim/build/index.js:303:2643)
    8       at async /root/.local/share/nvim/plugged/coc.nvim/build/index.js:303:3868
    7 } TypeError: c is not iterable
    6     at /root/.local/share/nvim/plugged/coc.nvim/build/index.js:214:23865
    5     at async Promise.all (index 0)
    4     at async Bv.provideInlayHints (/root/.local/share/nvim/plugged/coc.nvim/build/index.js:214:23710)                          ╭Error loading workspace ──────╮
    3     at async VC.renderRange (/root/.local/share/nvim/plugged/coc.nvim/build/index.js:303:2643)                                 │──────────────────────────────│
    2     at async /root/.local/share/nvim/plugged/coc.nvim/build/index.js:303:3868                                                  │err: exit status 1: stderr:@@@│
    1 2022-08-16T18:25:54.559 INFO (pid:6818) [attach] - receive notification: showInfo []                                           ╰──────────────────────────────╯
  44

**Comment by chemzqm** [comment]
Dup of  #4061
