### ISSUE TITLE
Deactivate completion in comment and in string

### ISSUE THREAD

**Issue by mnivoliez** [neoclide/coc.nvim#407]
**Is your feature request related to a problem? Please describe.**
When writting comments or string, I got suggestion of completion.

**Describe the solution you'd like**
Having a way to disable completion while in string or comment.

**Describe alternatives you've considered**

**Additional context**
As external exemple, deoplete allow that with:
`call deoplete#custom#source('_', 'diasbled_syntaxes', ['Comment', 'String'])`

**Comment by chemzqm** [comment]
I don't think that's needed for coc.nvim

* It always change completeopt to `menuone,noinsert` on completion.
* It's not triggered as often as deoplete, you can use `"coc.preferences.autoTrigger"` to change trigger behavior.
* Sometimes completion need to work in string or comment, like jsdoc completion and module name completion.
* If the source should not work in comment or string, it should do the check, coc-emmet does that.

If you don't like the flicking of popupmenu, use neovim instead.

**Comment by jsholmes** [comment]
I agree that it would be great for sources to do the check and not work in comments / strings, some sources (like TabNine) do not do this check.  It would be pretty nice for users to have a way for CoC to override the behavior of sources that don't do the right thing.

**Comment by chemzqm** [comment]
@jsholmes it's possible to configure TabNine to ignore comment lines.
