### ISSUE TITLE
[coc.nvim] build/index.js not found, please install dependencies and compile coc.nvim by yarn install

### ISSUE THREAD

**Issue by mshhlvxk** [neoclide/coc.nvim#4071]
![image](https://user-images.githubusercontent.com/89906980/185540967-5aab9af2-cc18-4b2b-92e9-120b22f1ba77.png)

I tried running `yarn install` in coc.nvim's directory, but it says:

![image](https://user-images.githubusercontent.com/89906980/185541038-a8190b21-4997-4377-a25d-7e2c2cf340e2.png)

When i try running `npm install` and `npm audit fix`, i get this error:

![image](https://user-images.githubusercontent.com/89906980/185542666-4aa64246-7c97-4110-b684-158b352f5c4c.png)

Please help, i am very new to neovim.

Currently running Debian 11.

**Comment by chemzqm** [comment]
You don't have the expected yarn executable, use release branch of coc.nvim to save your disk space and avoid the compilation.

**Comment by mshhlvxk** [comment]
> You don't have the expected yarn executable, use release branch of coc.nvim to save your disk space and avoid the compilation.

How do i do that?

**Comment by mshhlvxk** [comment]
> > You don't have the expected yarn executable, use release branch of coc.nvim to save your disk space and avoid the compilation.
> 
> How do i do that?

Nevermind.

**Comment by mshhlvxk** [comment]
Update: This happens now.
I've selected the release branch, even in my init.vim.

![image](https://user-images.githubusercontent.com/89906980/185581275-e441c40b-02ab-42e4-b30b-650cfffd5314.png)

**Comment by mshhlvxk** [comment]
Aaaaaand, this error exists again.
![image](https://user-images.githubusercontent.com/89906980/185581649-9fa7489a-ade1-473f-8b7a-a31f7b0c9f19.png)

**Comment by fannheyward** [comment]
What's your node version?

**Comment by mshhlvxk** [comment]
> What's your node version?
v12.22.9

**Comment by chemzqm** [comment]
You need at least node 14 https://nodejs.org/en/about/releases/

**Comment by mshhlvxk** [comment]
> You need at least node 14 https://nodejs.org/en/about/releases/

Can i use node.js v18 as well?
