### ISSUE TITLE
New release doesn't indent on either tab or space or enter

### ISSUE THREAD

**Issue by CypherX7** [neoclide/coc.nvim#4072]
## Result from CocInfo
```
## versions

vim version: VIM - Vi IMproved 8.2 8023995
node version: v16.14.2
coc.nvim version: 0.0.82-5fce9a51 2022-08-17 07:04:08 +0800
coc.nvim directory: /home/cyphr/.vim/autoload/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-08-19T11:05:44.039 INFO (pid:13583) [plugin] - coc.nvim initialized with node: v16.14.2 after 186ms
2022-08-19T11:05:59.610 INFO (pid:13583) [attach] - receive notification: showInfo []
```

## Bug

**So the thing is the current release of coc.nvim doesn't do code completion when pressed tab or enter. checked with both vim and neovim and also checked on qemu but code completion doesn't work. the pop menu shows up with suggestions and other stuff are working fine but even if changing the key mapping in coc.vim , auto-compilation on any of those primary keys doesn't work.**

**Comment by chemzqm** [comment]
You have to remap `<tab>` and `<cr>` for trigger completion https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources

**Comment by CypherX7** [comment]
I have done that before still doesn't work.
all I mean even with default settings it doesn't work.
