### ISSUE TITLE
How can deal with this problem?

### ISSUE THREAD

**Issue by T-TRz879** [neoclide/coc.nvim#4073]
I cannot find the solution from document.please complete it
<img width="485" alt="image" src="https://user-images.githubusercontent.com/50860504/185578440-aacace4f-8665-4554-b52b-217f03759cc6.png">

**Comment by fannheyward** [comment]
Checkout the configuration example in README.

**Comment by T-TRz879** [comment]
Thank you,but it do not work. Here is my `.vimrc`.I do not what's wrong
[vimrc.txt](https://github.com/neoclide/coc.nvim/files/9380588/vimrc.txt)

**Comment by T-TRz879** [comment]
@fannheyward

**Comment by T-TRz879** [comment]
@fannheyward @iamruinous @megalithic @kibs

**Comment by chemzqm** [comment]
Checkout `:h coc-completion`, don't send spam messages.
