### ISSUE TITLE
Add configuration options for inlay hints

### ISSUE THREAD

**Issue by frankplow** [neoclide/coc.nvim#4074]
**Is your feature request related to a problem? Please describe.**
The new inlay hints feature is quite visually noisy and can easily push lines over 80 characters. At present the only way to disable inlay hints is using the `disabledFeatures` configuration option. 

**Describe the solution you'd like**
It would be nice to have a way to conditionally show these inlay hints and/or a command to toggle its visability. I think the feature bears similarity to diagnostic info, hence a comparable `inlayHints.checkCurrentLine` option would be intuitive.

**Describe alternatives you've considered**
At the moment I have inlay hints disabled using the `disabledFeatures` option.

**Additional context**
![inlayHint_side-by-side](https://user-images.githubusercontent.com/6375868/185603053-b6c0f4f0-1534-4bdb-b3cb-fc188a75e552.png)
Left: without inlay hints
Right: with inlay hints

**Comment by frankplow** [comment]
Here are the set of inlay hints configuration options offered by [coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer):

Option | Description | Default Value
-- | -- | --
rust-analyzer.inlayHints.bindingModeHints.enable | Whether to show inlay type hints for binding modes. | `false`
rust-analyzer.inlayHints.chainingHints.enable | Whether to show inlay type hints for method chains. | `true`
rust-analyzer.inlayHints.closingBraceHints.enable | Whether to show inlay hints after a closing } to indicate what item it belongs to. | `true`
rust-analyzer.inlayHints.closingBraceHints.minLines | Minimum number of lines required before the } until the hint is shown (set to 0 or 1 to always show them). | `25`
rust-analyzer.inlayHints.closureReturnTypeHints.enable | Whether to show inlay type hints for return types of closures with blocks. | `false`
rust-analyzer.inlayHints.lifetimeElisionHints.enable | Whether to show inlay type hints for elided lifetimes in function signatures. | `never`
rust-analyzer.inlayHints.lifetimeElisionHints.useParameterNames | Whether to prefer using parameter names as the name for elided lifetime hints if possible. | `false`
rust-analyzer.inlayHints.maxLength | Maximum length for inlay hints. Set to null to have an unlimited length. | `25`
rust-analyzer.inlayHints.parameterHints.enable | Whether to show function parameter name inlay hints at the call site. | `true`
rust-analyzer.inlayHints.reborrowHints.enable | Whether to show inlay type hints for compiler inserted reborrows. | `never`
rust-analyzer.inlayHints.renderColons | Whether to render leading colons for type hints, and trailing colons for parameter hints. | `true`
rust-analyzer.inlayHints.typeHints.enable | Whether to show inlay type hints for variables. | `true`
rust-analyzer.inlayHints.typeHints.hideNamedConstructor | Whether to hide inlay type hints for constructors. | `false`

**Comment by fannheyward** [comment]
These configurations, for example `rust-analyzer.inlayHints.maxLength`, are very rust-analyzer limited and off-spec, they're not what LSP defined.

**Comment by aemonge** [comment]
Can we put the inline hints only visible for current line?

**Comment by fannheyward** [comment]
> inline hints only visible for current line?

@aemonge  no such feature yet. https://github.com/neoclide/coc.nvim/issues/4740

**Comment by alkeryn** [comment]
@aemonge i find it an odd timing that you wrote that comments just today, out of nowhere i started having types hint when i did not before, i don't think i changed anything, are you having the same issue.

not that they can't be useful but they make things less readable in some cases.

**Comment by aemonge** [comment]
Hey, @alkeryn it's probably written out in an update or changelog, but I think this happens because recently it's enabled by default :wink:

**Comment by aemonge** [comment]
@Maldus512 that's correct!, but latest version I prefer to:

```
    "inlayHint.enable": true,
    "inlayHint.enableParameter": true,
    "inlayHint.position": "eol"
```
