### ISSUE TITLE
coc-completion does not select the first entry

### ISSUE THREAD

**Issue by marcvs** [neoclide/coc.nvim#4080]
## versions

vim version: NVIM v0.7.2
node version: v18.6.0
coc.nvim version: 0.0.82-96700049 2022-08-21 17:45:20 +0800
coc.nvim directory: /home/marcus/.config/nvim/plugged/coc.nvim
term: rxvt-unicode-256color
platform: linux

## Log of coc.nvim

2022-08-22T10:23:55.728 INFO (pid:2508143) [extensions] - Skipped load vim plugin from "/home/marcus/.config/nvim/plugged/coc-jedi/", "coc-jedi" already global extension.
2022-08-22T10:23:55.793 INFO (pid:2508143) [services] - registered service "languageserver.bash"
2022-08-22T10:23:55.794 INFO (pid:2508143) [services] - registered service "languageserver.python"
2022-08-22T10:23:55.874 INFO (pid:2508143) [coc-git] - Looking for git in: git
2022-08-22T10:23:55.882 INFO (pid:2508143) [plugin] - coc.nvim initialized with node: v18.6.0 after 194ms
2022-08-22T10:23:56.493 INFO (pid:2508143) [attach] - receive notification: highlight []
2022-08-22T10:23:57.456 WARN (pid:2508143) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-08-22T10:23:58.978 INFO (pid:2508143) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-08-22T10:23:59.940 INFO (pid:2508143) [attach] - receive notification: highlight []
2022-08-22T10:24:06.770 INFO (pid:2508143) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_coc_helper_1',
  'BufWipeout',
  2
]
2022-08-22T10:24:06.771 INFO (pid:2508143) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'BufWipeout',
  2
]

## Describe the bug

`"suggest.noselect": false` (default) does select the first entry, but does not
actually put the text under the cursor. I.e. I have to cycle through the menu (or press tab shift-tab)
to select th first entry.
`"suggest.noselect": true` behaves much more as intended, since it does _not_ select the first
entry. Hence, a single `tab` gives me the first entry.

## Reproduce the bug

1. Enter three strings: `aaa`, `aab`, and `aac`
1. Enter `aa` and observe after how many `coc#pum#next` you can select the first one. (The 2nd one is the first to be selected)

- Create file `mini.vim` with：

```vim
set nocompatible              " be iMproved, required
let g:python3_host_prog = $HOME . '/.local/venv/nvim/bin/python'
call plug#begin('~/.config/nvim/plugged')

let g:ale_disable_lsp = 1
Plug 'neoclide/coc.nvim', {'branch': 'release'} " {{{

function! CheckBackSpace() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
endfunction
"inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
inoremap <silent><expr> <C-x><C-z> coc#pum#visible() ? coc#pum#stop() : "\<C-x>\<C-z>"

" remap for complete to use tab and <cr>

inoremap <silent><expr> <TAB>
    \ coc#pum#visible() ? coc#pum#next(1):
    \ CheckBackSpace() ? "\<Tab>" :
    \ coc#refresh()

inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
inoremap <silent><expr> <c-space> coc#refresh()

call plug#end()

```

**Comment by chemzqm** [comment]
It's expected, you can use `coc#pum#select()` or `coc#pum#confirm()` to insert word of selected item or complete completion.

**Comment by avalonv** [comment]
Had to dig through a few issues similar to this one to understand how to switch to the old tab behaviour since updating my config to match what's on the README >_>

Is there a particular reason `"suggest.noselect": true` is not the default? I think that's the type of behaviour the typical user would expect, since it's how most interfaces that use tab for both completion and navigation tend work -- off the top of my head, the URL bar in web browsers, but I suppose almost any piece of software that had a "search" bar with autocompletion behaves that way.

**Comment by chemzqm** [comment]
> Is there a particular reason "suggest.noselect": true is not the default

It's not work well with preselect and selection feature.

**Comment by avalonv** [comment]
I see. Perhaps a disclaimer, or even just a comment in the relevant section of the config that is in the README could be useful to people running into similar problems. I see #3981 is also related to this issue.

**Comment by avalonv** [comment]
```" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
" You may want to set '"suggest.noselect": true' in coc-settings.json if you don't plan
" to use <CR> to confirm selections.
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1):
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice.
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```
My config looks like this for example.
