### ISSUE TITLE
Floating Menu Selected Line matches background Color

### ISSUE THREAD

**Issue by TerenceNg03** [neoclide/coc.nvim#4081]
## Result from CocInfo
```
## versions

vim version: VIM - Vi IMproved 9.0 9000065
node version: v14.18.1
coc.nvim version: 0.0.82-master
coc.nvim directory: /Users/<USERNAME REMOVED>/.vim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin
```

## Describe the bug

Coc's floating menu use fixed Color for selected line and matched search result. Which may prevent user from reading the line when using specific color theme(especially for light mode theme).  The problem caused this is `CocMenuSel` does not use `PMenu`'s select color but use an hard coded one. The same is `CocSearch`. Perhaps they should be linked to `PMenuSel` and `Identifier`.

Below is a work around I am currently using
```vim
autocmd VimEnter,ColorScheme * hi! link CocMenuSel PMenuSel
autocmd VimEnter,ColorScheme * hi! link CocSearch Identifier
```
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

```
:hi CocSearch
:hi CocMenuSel
```
- You will notice that this two value is not linked to color theme.
## Screenshots (optional)

An example of hidden selected line:
<img width="1419" alt="Screen Shot 2022-08-22 at 6 43 29 PM" src="https://user-images.githubusercontent.com/63455223/185905823-b94960e7-ced8-4611-b688-a1c6b916cb87.png">
After linking the color:
<img width="1417" alt="Screen Shot 2022-08-22 at 7 02 13 PM" src="https://user-images.githubusercontent.com/63455223/185906167-cc433c35-85a7-4df9-bc01-8b523e16b789.png">

**Comment by chemzqm** [comment]
PMenuSel of many colorscheme use reverse which override other highlights, so we choose not use it

**Comment by huyz** [comment]
Hi, coc noob here. I'm also using vim and I have weird colors for the pum.  So what am I supposed to do? Link it myself as @TerenceNg03 has done once I confirmed that the linking works with my colorscheme?

**Comment by chemzqm** [comment]
Tell us where we can download the color schema, so we could inspect.

**Comment by huyz** [comment]
I got my theme from https://github.com/chriskempson/base16-vim
