### ISSUE TITLE
hitting enter results in new line instead of inserting selected hint

### ISSUE THREAD

**Issue by mrl5** [neoclide/coc.nvim#4082]
## Result from CocInfo

```
## versions
                                                                                                                               
vim version: VIM - Vi IMproved 9.0 9000228                                                                                     
node version: v18.7.0                                                                                                          
coc.nvim version: 0.0.82-cd5791ab 2022-08-22 22:32:45 +0800                                                                    
coc.nvim directory: /home/kuba/.vim.broken/plugged/coc.nvim                                                                    
term: dumb                                                                                                                     
platform: linux
```

## Describe the bug

Hitting enter creates new line instead of inserting currently selected hint. At first I thought that this is `coc-rust-analyzer` specific and reported it as https://github.com/fannheyward/coc-rust-analyzer/issues/1036 but then I realized that it's actually agnostic.

**I can't reproduce this bug with coc.nvim version: `0.0.80-c7d7756089`**

## Screenshots (optional)
![json before enter](https://i.ibb.co/4gZmsNk/Screenshot-2022-08-22-21-42-29.png)

![json after enter](https://i.ibb.co/7Spw6ZN/Screenshot-2022-08-22-21-42-44.png)

**Comment by uri** [comment]
You haven't posted your mapping for `<cr>` (as coc doesn't have a default mapping) but there was a recent change in 0.82

https://github.com/neoclide/coc.nvim/issues/4080#issuecomment-1222280839

See the example config in the README as well.

**Comment by fannheyward** [comment]
You need to change your `<cr>` mappings, check README or `:h coc-completion-example`.

**Comment by chemzqm** [comment]
It's vim's behavior that `<cr>` to insert word of complete item, not custom popup menu of coc.nvim.
We have to make some break changes sometimes, follow https://github.com/neoclide/coc.nvim/discussions/3886 to get update.

**Comment by mrl5** [comment]
that was my `mini.vim` for `0.0.82-cd5791ab`:
```
set nocompatible
set runtimepath^=/home/kuba/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

the bug is gone after introducing this change
```diff
--- a/mini.vim
+++ b/mini.vim
@@ -3,3 +3,4 @@ set runtimepath^=/home/kuba/.vim/plugged/coc.nvim
 filetype plugin indent on
 syntax on
 set hidden
+inoremap <expr> <cr> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"
```

thanks for quick response guys!

====
side note regarding:
> We have to make some break changes sometimes, follow https://github.com/neoclide/coc.nvim/discussions/3886 to get update.

I'm ok with it. esp. when there is such great support for people forgetting to check the readme like miself :D But for the future you can consider doing semver major increment if there is a breaking change: https://semver.org/#what-if-i-inadvertently-alter-the-public-api-in-a-way-that-is-not-compliant-with-the-version-number-change-ie-the-code-incorrectly-introduces-a-major-breaking-change-in-a-patch-release

**Comment by mishaszu** [comment]
I'm commenting here instead of creating a new bug because I have exactly the same problem but
```
inoremap <expr> <cr> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"
```
didn't help me. 

It doesn't insert a new line anymore, but in most cases also doesn't fill from the suggestion popup. There are some cases when it fills, usually if I try to use a variable that is not declared in scope, but for variables already defined, it just closes the popup and does nothing.

**Comment by chemzqm** [comment]
Selected item required to insert word see `:h coc#pum#confirm()`

**Comment by mishaszu** [comment]
Unfortunately, the doc doesn't  clarify much:
>         Confirm completion and close the customized pum, like <C-y> of vim. Return empty string.

I do select an item (or at least I believe it's selected, as it's highlighted and fills variables that are not in a scope).

**Comment by chemzqm** [comment]
If it's highlighted means it's selected, `coc#pum#confirm()` should insert the word of complete item and do addtional edits.
The text could be cleared by edits of something else, try minimal vimrc.
