### ISSUE TITLE
Have to press <Tab>, then <S-Tab> to get the first candidate

### ISSUE THREAD

**Issue by archibate** [neoclide/coc.nvim#4086]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I press Tab, it gives the **second candidate** instead of the first.
So in order to trigger completion for the first candidate, I have to **press Tab then S-Tab**, which is annoying.

Input `inorem`...
![image](https://user-images.githubusercontent.com/20640597/186209645-81c5f0e3-58ae-452f-83da-e3799fb86be5.png)
Press `<Tab>`...
![image](https://user-images.githubusercontent.com/20640597/186209697-d1d39698-63c6-4b9e-807a-26181673c6ac.png)
Press `<S-Tab>`...
![image](https://user-images.githubusercontent.com/20640597/186209921-ed0027c9-da89-4d8c-82d1-4933236653e1.png)

**Describe the solution you'd like**
I guess this is because the new version of coc.nvim selects the first candidate at the first place.
However, the first candidate hasn't been triggered at all.
And when I press Tab, it performs `coc#pum#next(1)` and goes to the second candidate and triggered completion via `coc#pum#refresh()`.
An old version coc.nvim selects no candidate at the first place (say 0th candidate), and when press Tab it normally completes the first candidate (I like this).
So may I have an option to get back the behavior as old version does, e.g. `let g:coc_select_0th_candidate = 1` to select no candidate at the first place, so that I can press `<Tab>` once to complete the first candidate?

**Describe alternatives you've considered**
Use the `<CR>` mapping mentioned in README.md may also works, so that I will use `<CR>` for the first candidate and `<Tab>` for the second candidate. But I have mapped `<CR>` for other plugins, and I still prefer `<Tab>` in muscle memory anyway :rofl: ...

**Additional context**
Here is what I used in `.vimrc` (copied from README.md of this repo):
```
" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

**Comment by koreanddinghwan** [comment]
I am also troubled by this problem these days.
Various problems in app have arisen since the recent plug-in update.

**Comment by chemzqm** [comment]
> " NOTE: There's always complete item selected by default, you may want to enable no select by `"suggest.noselect": true` in your configuration file.

From Readme
