### ISSUE TITLE
Cannot press Enter to pick the current selection from the popup

### ISSUE THREAD

**Issue by moonjava2005** [neoclide/coc.nvim#4089]
I have just updated to the latest Plugin and got the problem on Mac M1:
The new popup show with new style, however, after I press Enter, the VIM has the new line, instead of pick the current selected row from the showing popup
I have read from Home page and try many times for config like this

`inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"`

But currently, I'm only able to use TAB for selecting the focused row from popup.  How can I fix this issue?

**Comment by fannheyward** [comment]
Use

```
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

or

```
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```

Your mapping is incorrect with the `\` sign.

**Comment by fannheyward** [comment]
What's the output of `:verbose imap <cr>`?

**Comment by moonjava2005** [comment]
@fannheyward 
`EunuchNewLine(v:lua.MPairs.completion_confirm())
        Last set from ~/.vim/bundle/vim-eunuch/plugin/eunuch.vim line 478`

**Comment by fannheyward** [comment]
Your `<cr>` is re-mapped by vim-eunuch.

**Comment by moonjava2005** [comment]
@fannheyward Thanks! I will add to the bottom of config file
