### ISSUE TITLE
CocUpdate from command line broken

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#409]
`nvim +CocUpdate` is presently broken on master. I suspect https://github.com/neoclide/coc.nvim/commit/4cf01d03a36e7f042fb9a8388dd4d0bba3ea477e is the culprit.

This use case is very common for updating vim/the system all at once.

```sh
update_nvim() {
    trap 'return' INT

    #set rust environment variables
    export RUSTC_WRAPPER=$(which sccache)
    export RUSTUP_TOOLCHAIN='stable'

    #update vim-plug and extensions
    nvim +PlugInstall +UpdateRemotePlugins +PlugUpgrade +PlugUpdate +PlugDiff +'w ~/.PlugDiff' +CocUpdate +qa
    cat ~/.PlugDiff
    rm ~/.PlugDiff
    unset RUSTC_WRAPPER RUSTUP_TOOLCHAIN
}
```

**Comment by chemzqm** [comment]
how about make this command block and add CocUpdateAsync which is async？

**Comment by chemzqm** [comment]
It's not broken, but doesn't work when using notification for remote plugin.
It should not work even before that commit, since terminal would be killed with your `qa` command.

**Comment by chemzqm** [comment]
Will be resolved in #411

**Comment by Avi-D-coder** [comment]
@chemzqm It worked prior to a day ago. Each `+command` runs in order, so `qa` runs only after all previous commands finish.

**Comment by chemzqm** [comment]
I have tried, the terminal job would be terminated immediatelly after open by `qa` command, it won't work.

**Comment by Avi-D-coder** [comment]
I changed the order when trying to figure out what caused it to stop working.
I had been using this to update every day.
`nvim +CocUpdate +PlugInstall +UpdateRemotePlugins +PlugUpgrade +PlugUpdate +PlugDiff +'w ~/.PlugDiff' +qa`

**Comment by chemzqm** [comment]
It only matters whether the terminal job could be kill by `qa`, the answer is yes.
So it might work if your other job make `qa` to run after terminal job finished.
