### ISSUE TITLE
Question: adding dependencies in php

### ISSUE THREAD

**Issue by mostafaqanbaryan** [neoclide/coc.nvim#4092]
[simplescreenrecorder-2022-08-24_13.12.22.webm](https://user-images.githubusercontent.com/94293456/186373323-5086717a-8ec5-4536-b744-b68fe843975b.webm)

Hi.
I don't know what this feature is called, hence the title.
In a Laravel project, when I add a reference to some library, coc opens a suggestion list and after selecting one of them, it will add the necessary namespace.
So this works for autocomplete and using suggestion list. But how can I do that when I wrote the name before, and now I only want to add the namespace?
I mean in the video above, I want to write `AbstractDataLoader` completely, then add the necessary namespace via coc.
Is that possible?

**Comment by chemzqm** [comment]
Language server may provide code action to fix import, see `:h coc-code-actions`
