### ISSUE TITLE
dart language server

### ISSUE THREAD

**Issue by wwwdata** [neoclide/coc.nvim#41]
**Describe the bug**
I configured a custom language server for dart. It is starting up and displaying some auto completions. However it is just displaying auto completions when I type in a new line, not after i have some variable/instance and want to see methods. Then it does not recommend me anything. It seems that it is just auto completing global stuff.

**To Reproduce**
Configured the dart_language_server like this:

```json
{
  "languageserver": {
    "dart": {
      "command": "dart_language_server",
      "args": [],
      "filetypes": ["dart"],
      "cwd": "./lib",
      "initializationOptions": {},
      "settings": {
        "dart": {
          "validation": {},
          "completion": {}
        }
      }
    }
  }
}
```

**Expected behavior**
I get some completion suggestions for instance variables as well like with LanguageClient-Neovim

**Screenshots**
Here you see it completes global stuff

<img width="963" alt="screen shot 2018-08-05 at 21 48 45" src="https://user-images.githubusercontent.com/818880/43689354-70b665c4-98f9-11e8-89d7-cf54a3a4279c.png">

However, it does not find methods of a class instance like it should:
<img width="697" alt="screen shot 2018-08-05 at 21 49 07" src="https://user-images.githubusercontent.com/818880/43689356-7b83ccda-98f9-11e8-9c08-75a6a8febb8d.png">

**Desktop (please complete the following information):**
 - Terminal: [e.g. iTerm2]
 - Version: [e.g. v3.2.2]
- Neovim 0.3.1

**Comment by chemzqm** [comment]
Looks like the server need sometime to build the cache for completion, it works well after the server get started for a while.

I think this is unnecessary:
```
cwd": "./lib",
```

**Comment by wwwdata** [comment]
Hm, also after waiting a while it doesn't work for me. On the contrary, yes it seems to display completions after I type in the DOT so for example `variable.` and then I get other global completions and not completions of methods for the instance variable i am currently using.

**Comment by wwwdata** [comment]
Example: lots of global namespace stuff again and not completions for `context`

![screen shot 2018-08-06 at 17 17 32](https://user-images.githubusercontent.com/818880/43725371-a449c946-999c-11e8-8248-05183ae4df90.png)

**Comment by chemzqm** [comment]
I have increase the timeout for content sync, hope that could solve your issue.
You have to build from source right now it see the result.

**Comment by wwwdata** [comment]
no doesn't work for me, I still see a lot of global results. I am currently using vim-lsc which works just fine with the dart_language_server

**Comment by chemzqm** [comment]
@wwwdata I've figured it out, is's bug of dart language server, it claimed to support increment document sync, but it's buggy. vim-lsp could work because it doesn't support increment sync.

https://github.com/natebosch/dart_language_server/issues/50

**Comment by chemzqm** [comment]
Or add `"forceFullSync": true` to configuration section of dart languageserver.

**Comment by wwwdata** [comment]
thx, that `forceFullSync` was fixing it for me!

**Comment by chemzqm** [comment]
Figured out dart language server expect optional `rangeLength` field on document change params, I've added that field, so `forceFullSync` not needed any more.
