### ISSUE TITLE
Var type values

### ISSUE THREAD

**Issue by ElcomJ** [neoclide/coc.nvim#4103]
Good afternoon, I wonder if there is any highlight to be able to change the background color of this selected data, or if they would have a way to disable them.

![image](https://user-images.githubusercontent.com/37147897/186753470-94cc10ce-e2ef-4440-af45-276383478db7.png)

Thank you in advance.

**Comment by fannheyward** [comment]
The hi group is `CocInlayHint`.

**Comment by chemzqm** [comment]
`:h coc-inlayHint`

**Comment by chemzqm** [comment]
`:h coc-inlayHint`
