### ISSUE TITLE
Stray Literal types plastered over code

### ISSUE THREAD

**Issue by bulletmark** [neoclide/coc.nvim#4104]
## Result from CocInfo

Nothing. I run `:CocInfo` and I get a new empty split window.

## Describe the bug

Updated to current release and get stray Literal types plastered all over my code: See https://imgur.com/a/E3v7Lmx which shows screen capture before/after.

If I remove commit 2a62affa46a82b32042e0cad459e60073f199279 then works normally.

**Comment by fannheyward** [comment]
It's inlay hints feature. Are you using coc-pyright? You can disable it by `pyright.inlayHints.enable` to false.

**Comment by bulletmark** [comment]
Yes thanks, that fixes it.

Sorry, those popups/insertions were so intrusive and ugly I assumed it was a bug!

**Comment by bulletmark** [comment]
These inlay hints have reappeared again and are splattered all over my code. I still have `pyright.inlayHints.enable: false` and have changed nothing other than updating my plugins. Any hint how to fix it now?

**Comment by bulletmark** [comment]
Don't worry, just found this [commit](https://github.com/fannheyward/coc-pyright/commit/35028975a074e0f0d574970a21efa5e41ccee505).

**Comment by fannheyward** [comment]
Use `inlayHint.enable`, this configuration option same as coc.nvim, sorry for the breaking. :😞
