### ISSUE TITLE
@jest/create-cache-key-function load new one but not support node 14.14

### ISSUE THREAD

**Issue by shithead** [neoclide/coc.nvim#4108]
## Result from CocInfo

Error: javascript bundle not found, please compile code of coc.nvim by esbuild

## Describe the bug

If you new install coc.nvim, @jest/create-cache-key-function@27.5.0 try to install.
```
yarn install                                                                                                                                                                                           
yarn install v1.22.19                                                                                                                                                                                       
[1/5] Validating package.json...                                                                      
[2/5] Resolving packages...                                                                                                                                                                                 
[3/5] Fetching packages...                                                                                                                                                                                  
error @jest/create-cache-key-function@27.5.0: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.14.0"                            
error Found incompatible module.                                                                      
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## Reproduce the bug
- install node 14.14
- run yarn install

## Solution

try to use 
`"@jest/create-cache-key-function": "^26.6.2"` as dependency to support node 14.14.

**Comment by chemzqm** [comment]
The module is used for test purpose.
You need upgrade your node or use release branch of coc.nvim to avoid compile yourself.

**Comment by shithead** [comment]
@chemzqm in README.md, package.json and yarn.lock  is a node 14.14 as minimal dependency.

> The module is used for test purpose. You need upgrade your node or use release branch of coc.nvim to avoid compile yourself.

If I need to upgrade my node on 14.15, please change your minimal node dep in your project.

**Comment by chemzqm** [comment]
It has nothing to do with the running code, use latest node and release branch is recommended

**Comment by shithead** [comment]
ok no problem on release branch. :thumpup:
