### ISSUE TITLE
Make update command sync

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#411]
**Is your feature request related to a problem? Please describe.**
Current command like `:CocUpdate` and `:call coc#util#install()` use terminal feature, it prevent user from update by command like `nvim +CocUpdate +qa`.

**Solution**
Make then sync by default, while provide async version.

For `CocUpdate`, there would be `CocUpdateAsync`, for `coc#util#install()`, use `coc#util#install({terminal: 1})` to run command in terminal.

Feel free to comment if you have better idea.

**Comment by Avi-D-coder** [comment]
@chemzqm `nvim +CocUpdateSync` still produces:
![screenshot_20190208_085558](https://user-images.githubusercontent.com/29133776/52482498-68c39580-2b7f-11e9-8cac-db47fab3ac40.png)
