### ISSUE TITLE
Cannot start coc

### ISSUE THREAD

**Issue by Puperger** [neoclide/coc.nvim#4112]
## Result from CocInfo
Error: javascript bundle not found, please compile code of coc.nvim by esbuild.

## Describe the bug
I imported coc just as described in every tutorial I found so far but it shows I should run yarn install which ubuntu says "nah thats not a file"

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
call plug#begin("~/.vim/plugged")
    Plug 'neoclide/coc.nvim'
call plug#end()
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by lmburns** [comment]
You don't run the `yarn` command within vim. Firstly, install coc by running :PlugInstall within vim. 

After you do that, go to the directory where coc has been installed and run 'yarn install --frozen-lockfile'. 

Another option is to add this to your plugin 'Plug "neoclide/coc.nvim", {"do": "yarn install --frozen-lockfile"}. 

Sorry for formatting and not as much information, I am on mobile right now. But all of the installation instructions for both vim-plug and coc.nvim are very well documented. Start from the top of the documentation and read down. They both have several examples in their README.md's
