### ISSUE TITLE
doesn't play well with https://github.com/easymotion/vim-easymotion

### ISSUE THREAD

**Issue by bkerin** [neoclide/coc.nvim#4113]
## versions

vim version: VIM - Vi IMproved 9.0 9000000
node version: v16.17.0
coc.nvim version: 0.0.82-3ab29075 2022-08-26 00:21:58 +0800
coc.nvim directory: /home/bkerin/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-08-26T14:30:54.198 INFO (pid:177825) [extension:coc-tsserver] - 111
2022-08-26T14:30:54.201 INFO (pid:177825) [services] - registered service "tsserver"
2022-08-26T14:30:54.203 INFO (pid:177825) [plugin] - coc.nvim initialized with node: v16.17.0 after 96ms
2022-08-26T14:30:54.227 INFO (pid:177825) [services] - service tsserver started
2022-08-26T14:44:06.777 INFO (pid:177825) [attach] - receive notification: showInfo []

## Describe the bug

I noticed a bad interaction with https://github.com/easymotion/vim-easymotion
if you have a highlighted error word then try to move to it with easymotion (e.g. nmap ;j <Plug>(easymotion-bd-w) in my case)on arrival (after easymotion restores original state of the screen) the Coc highlighting is gone, so the error can't be seen. The maker in the signcolumn is still present
I don't know if this is Coc fault of easymotion fault or what
error can't be sen because in addition to not being highlighted the word is not sensitive anymore (doesn't show pop-up explanatory text)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

Fair enough.  At least you'll be aware the issue exists.

**Comment by chemzqm** [comment]
See https://github.com/neoclide/coc.nvim/wiki/F.A.Q#unexpected-diagnostics-when-using-easymotion
