### ISSUE TITLE
Completion popup width.

### ISSUE THREAD

**Issue by emrahc** [neoclide/coc.nvim#412]
**Is your feature request related to a problem? Please describe.**
Thanks for the addon. I gave up vscode due to that great addon. I use react/react native snippets inside neovim with tab completion.  But sometimes i can't read auto completion popup description. It's so small.

![screenshot_2019-02-08_04-08-28](https://user-images.githubusercontent.com/23315417/52453451-7c0f3a80-2b58-11e9-8a01-e22ebd361ef2.png)

 How can i increase the width so i can read whole definition ?. Or is there any way to see explanation another small split window. 
Thanks

**Comment by chemzqm** [comment]
The description is truncated, need an option for that.
