### ISSUE TITLE
InlayHints causes tsserver cannot report parameter type errors

### ISSUE THREAD

**Issue by qiqiboy** [neoclide/coc.nvim#4120]
## Describe the bug

If enable InlyHints parameterNames with `"typescript.inlayHints.parameterNames.enabled": "all"`, the tsserver cannot report the function parameter type errors.

## Reproduce the bug

Create file `a.ts` with：

```typescript
function set(v: boolean) {}
set(''); // should report a type error, but nothing happened
```
Neither vim9 or Neovim(installed coc-tsserver) report errors correctly. But if disabled InlayHints by ` "inlayHint.filetypes": []` or `"typescript.inlayHints.parameterNames.enabled": "none"`, tsserver could report the parameter type error: `Argument of type 'string' is not assignable to parameter of type 'boolean'`

##### "typescript.inlayHints.parameterNames.enabled": "none"

![截屏2022-08-29 15 27 57](https://user-images.githubusercontent.com/3774036/187147320-4cc68416-47c2-4fa2-8f96-64566d2276fd.png)
##### "typescript.inlayHints.parameterNames.enabled": "all"

![截屏2022-08-29 15 28 15](https://user-images.githubusercontent.com/3774036/187147308-9eda26ec-1ed3-48b7-87b4-d05d600e104d.png)

**Comment by chemzqm** [comment]
Try upgrade your vim.

**Comment by qiqiboy** [comment]
I test on vim9 
```vim
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 29 2022 10:56:13)
macOS version - arm64
Included patches: 1-312
```
and nvim
```vim
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```
the problem still exists.

**NOTE: Derectly open the reproduced file, the tsserver could report errors correctly. To reproduce this problem, you should switch to `insert mode`, and retype `set('')`.**

**Comment by chemzqm** [comment]
Diagnostics is not refreshed on insert mode by default.

**Comment by qiqiboy** [comment]
I have `"diagnostic.refreshOnInsertMode": true` in coc-settings.json.

**Comment by qiqiboy** [comment]
And when I switch back to `normal`, the error was still not reported.

**Comment by chemzqm** [comment]
Can't reproduce, works as expected for me.

**Comment by chemzqm** [comment]
Sometimes reproduced, should be issue with typescript.
