### ISSUE TITLE
请问有什么方式可以配置 CocMenuSel 么？

### ISSUE THREAD

**Issue by l-qing** [neoclide/coc.nvim#4123]
## Describe the bug

最近更新的这个 commit:https://github.com/neoclide/coc.nvim/commit/66ffea35a6827485af2c19df2a086a9f1c9e214c#diff-ee2e064648a0fe9e8fca9df56ca5180b37527596e89f67e557d29952cce7fb11R398-R402
虽然是兼容了原逻辑，即如果没有配置 PmenuSel 还是跟之前的行为一致。
```
  if hlexists('PmenuSel')
    execute 'hi default CocMenuSel '.coc#highlight#get_hl_command(synIDtrans(hlID('PmenuSel')), 'bg', '237', '#13354A')
  else
    hi default CocMenuSel       ctermbg=237 guibg=#13354A
  endif
```

但实际情况是我使用的主题：
https://github.com/flazz/vim-colorschemes/blob/fd8f122cef604330c96a6a6e434682dbdfb878c9/colors/hybrid.vim#L100
这里配置了 PmenuSel，实际作为 CocMenuSel 时看不清选中的内容。

<img width="617" alt="Shot 2022 08 30 at 18 23 35" src="https://user-images.githubusercontent.com/9499086/187413557-099882c1-51b4-4649-a37a-832aad186125.png">

使用 gruvbox 时，这个颜色也非常奇怪：
<img width="622" alt="Shot 2022 08 30 at 18 24 30" src="https://user-images.githubusercontent.com/9499086/187413808-831904f6-1f36-4091-b60f-bee36fd863eb.png">

作为对比，如果保留现在的配置：
```
hi default CocMenuSel       ctermbg=237 guibg=#13354A
```
那展示效果就是：
<img width="653" alt="Shot 2022 08 30 at 18 26 46" src="https://user-images.githubusercontent.com/9499086/187414161-2d0ad978-2a25-4ced-bbb1-c2f00785f55e.png">

<img width="655" alt="Shot 2022 08 30 at 18 27 05" src="https://user-images.githubusercontent.com/9499086/187414205-b75e63eb-362c-4e7c-9145-f977b533af93.png">

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
call plug#begin('~/.vim/bundlexxx')

Plug 'junegunn/vim-plug'
Plug 'neoclide/coc.nvim' , {'branch': 'release'}
" let g:coc_config_home = expand('~/.vim')

Plug 'morhetz/gruvbox'
Plug 'flazz/vim-colorschemes'

" Initialize plugin system
call plug#end()

set t_Co=256                  " Enable 256 colors
set background=dark           " Assume a dark background
colorscheme hybrid            " Load a colorscheme
" colorscheme gruvbox         " Load a colorscheme

set nocompatible
filetype plugin indent on
syntax on
set hidden

```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
You should not use `default`

**Comment by l-qing** [comment]
> Use ` autocmd ColorScheme * hi CocMenuSel ctermbg=237 guibg=#13354A` might helps

👍 This works for me::
```
autocmd ColorScheme * hi CocMenuSel ctermbg=237 guibg=#13354A
doautocmd ColorScheme
```

**Comment by l-qing** [comment]
最近 DiagnosticSignHint 在 3fe7a282264baf03fc70f2fbfc321b5cbc746638 中也改成了复用已有的。但我本地又变成白色了。所以我增加了一个配置：

```
  augroup cocmenusel_augroup
    autocmd!
    autocmd ColorScheme * highlight! default CocMenuSel ctermbg=237 guibg=#13354A
    autocmd ColorScheme * highlight! default DiagnosticSignHint ctermfg=Blue guifg=#15aabf guibg=NONE
    doautocmd ColorScheme
  augroup END
```
