### ISSUE TITLE
Issue while installing NodeJs..

### ISSUE THREAD

**Issue by yashwanth-mamilla** [neoclide/coc.nvim#4127]
while installing NodeJs for coc.nvim installation 
`$ curl -sL install-node.now.sh | bash`
bash: line 1: syntax error near unexpected token `newline`.
bash: line 1: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`

can anyone please help me with this?

**Comment by chemzqm** [comment]
Network issue, use https://nodejs.org/en/download/ instead.
