### ISSUE TITLE
coc-references missing references of override function for C++

### ISSUE THREAD

**Issue by jowu598** [neoclide/coc.nvim#4128]
**Is your feature request related to a problem? Please describe.**
coc-references  not able to find all references of a virtual function of base class. eg. drived class overriden function cannot be found.

**Describe the solution you'd like**
Qtcreator is able to find all references of both virtual function from base and drived.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by jowu598** [comment]
works for me,3q @chemzqm
