### ISSUE TITLE
show_documentation not working

### ISSUE THREAD

**Issue by ElcomJ** [neoclide/coc.nvim#4133]
Good morning, the function to sample the documentation is not working, it has always worked normally, but stopped today for no reason.

Code for the event call:

`nnoremap <silent> K :call <SID>show_documentation()<CR>`

```
function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
      execute 'h '.expand('<cword>')
    else
      call CocAction('doHover')
    endif
  endfunction
```

I would like to know how I can solve this ?

**Comment by fannheyward** [comment]
What's your `:CocInfo`? Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
