### ISSUE TITLE
[ERROR]: sudo npm install -g yarn 

### ISSUE THREAD

**Issue by GrozmanGit** [neoclide/coc.nvim#4138]
My Process: 

1. cd .local/share/nvim/plugged/coc.nvim ---> ~/.local/share/nvim/plugged/coc.nvim

2. ls (check for files in directory)

3. sudo npm install -g yarn
Error:
/usr/bin/node: 1: ELF: not found
/usr/bin/node: 2: �: not found
/usr/bin/node: 4: Syntax error: Unterminated quoted string

**Comment by chemzqm** [comment]
You nodejs is broken, install yarn from https://yarnpkg.com/

**Comment by GrozmanGit** [comment]
@chemzqm where do you install yarn on the website?

**Comment by GrozmanGit** [comment]
@chemzqm 
Website Process:

1. sudo apt remove yarn

2. curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

3. yarn install 
    Error:
    /usr/bin/yarn: 20: exec: node: Exec format error

**Comment by chemzqm** [comment]
Fix your Nodejs first, checkout https://nodejs.org/en/download/

**Comment by GrozmanGit** [comment]
Downloaded the LTS windows installer, yarn install shows the same error: /usr/bin/yarn: 20: exec: node: Exec format error

**Comment by chemzqm** [comment]
Try another way.
