### ISSUE TITLE
Completion suggestion takes a while to appear

### ISSUE THREAD

**Issue by marekdedic** [neoclide/coc.nvim#4140]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.2
node version: v18.8.0
coc.nvim version: 0.0.82-a5276d63 2022-09-01 20:10:57 +0800
coc.nvim directory: /home/user/.local/share/nvim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2022-09-03T17:48:50.686 INFO (pid:213027) [services] - registered service "tsserver"
2022-09-03T17:48:50.690 INFO (pid:213027) [plugin] - coc.nvim initialized with node: v18.8.0 after 119ms
2022-09-03T17:48:50.712 INFO (pid:213027) [services] - service tsserver started
2022-09-03T17:48:52.888 INFO (pid:213027) [attach] - receive notification: showInfo []
```

## Describe the bug

Hi, I have set the <CR> mapping as advised in the README:
```lua
vim.api.nvim_set_keymap('i', '<CR>', 'coc#pum#visible() ? coc#pum#confirm() : <CR><c-r>=coc#on_enter()<CR>', {silent = true, expr = true})
```

With this config, upon pressing enter, the cursor jumps to where the end of the suggestion should be, however, the suggestion itself only appears after a while, say a second.

## Reproduce the bug

- Create file `mini.lua` with：

```vim
local Plug = vim.fn['plug#']

vim.call('plug#begin', vim.fn.stdpath('data') .. '/plugged')

Plug('neoclide/coc.nvim', {branch = 'release'})
vim.api.nvim_set_keymap('i', '<CR>', 'coc#pum#visible() ? coc#pum#confirm() : <CR><c-r>=coc#on_enter()<CR>', {silent = true, expr = true})

vim.call('plug#end')
```

- Start (neo)vim with command: `vim -u mini.lua`

- Operate vim and try to confirm a suggestion.

**Comment by chemzqm** [comment]
> With this config, upon pressing enter, the cursor jumps to where the end of the suggestion should be, however, the suggestion itself only appears after a while, say a second.

The key-mapping for `coc#pum#confirm()` should only confirm completion, I don't understand what do you mean by `suggestion itself only appears after a while`

**Comment by marekdedic** [comment]
Ok, I'll try to describe the process in more detail.
I have the completion menu open,  I select an item.
1. Press Enter
2. The menu disappears
3. Nothing gets written in the open file/buffer
4. The cursor gets moved to approximately where the selected item would end
5. **~1s delay**
6. The actual text of the completion item appears in the file

**Comment by chemzqm** [comment]
Seem your vim or the node blocked for some reason, checkout:
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-could-i-profile-vim
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-get-log-of-cocnvim

**Comment by marekdedic** [comment]
I have tried profiling vim and there is no script that would take long enough to be responsible for the delay.
I tried looking into the log, nothing really interesting there - it tells me how long it took to find the completion suggestions - that is not my problem, my issue is when I select one of them...

**Comment by marekdedic** [comment]
[profile.log](https://github.com/neoclide/coc.nvim/files/9483244/profile.log)

**Comment by chemzqm** [comment]
Maybe you need `nowait`, checkout your key-mapping by `:imap <CR>`

**Comment by marekdedic** [comment]
Adding `nowait = true` doesn't chage the behaviour :(

**Comment by chemzqm** [comment]
You can check the trace log: https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-get-log-of-cocnvim

**Comment by marekdedic** [comment]
And the imap only shows the mapping I defined for CoC

**Comment by marekdedic** [comment]
I see a weird jum on line 115, is that it?
[coc-log.log](https://github.com/neoclide/coc.nvim/files/9483275/coc-log.log)

**Comment by marekdedic** [comment]
Hmm, I solved the issue incidentally by changing the mapping from
```lua
vim.api.nvim_set_keymap('i', '<CR>', 'coc#pum#visible() ? coc#pum#confirm() : <CR><c-r>=coc#on_enter()<CR>', {silent = true, expr = true})
```
to
```lua
vim.api.nvim_set_keymap('i', '<CR>', 'coc#pum#visible() ? coc#pum#confirm() : "<CR><c-r>=coc#on_enter()<CR>"', {silent = true, expr = true})
```

I don't know why that helped, but it did :shrug:
