### ISSUE TITLE
support environment variables in coc-settings.json

### ISSUE THREAD

**Issue by tqfx** [neoclide/coc.nvim#4144]
Can you support environment variables in `coc-settings.json` like VSCode does?

**coc-settings.json**

```json
"clangd.fallbackFlags": [
    "-I${env:VCPKG_INSTALLATION_ROOT}/installed/x64-windows/include",
    "-I${env:VCPKG_INSTALLATION_ROOT}/installed/x64-linux/include",
    "-I${cwd}/include",
],
```

**clangd output**

```
"C:\\dev\\LLVM\\bin\\clang" "-IC:\\dev\\vcpkg/installed/x64-windows/include" "-IC:\\dev\\vcpkg/installed/x64-linux/include" "-Id:\\dev\\tqfx\\liba/include" "-resource-dir=C:\\dev\\LLVM\\lib\\clang\\14.0.6"
```

**Comment by chemzqm** [comment]
We have the function `workspace.expand` for expand variables like VSCode, need  to checkout how VSCode handle it automaticlly.

**Comment by chemzqm** [comment]
It's converted by extensions https://github.com/clangd/vscode-clangd/blob/df56a9a058/src/config.ts#L57:10, send your feature request to coc-clangd.
