### ISSUE TITLE
Add Macro support to autocomplete

### ISSUE THREAD

**Issue by otavioschwanck** [neoclide/coc.nvim#4145]
Today, when macro is recording and you use autocomplete, on the next macro occurrences it just don't insert the selected word / macro.

Would be 1000/10 if when selecting something from macro (in the autocomplete), it insert the selected stuff into the recorded macro as if it was typed.  So when it runs again, the word will be correctly inserted.

A easier solution for now is disable autocomplete when macro is active

**Comment by chemzqm** [comment]
It should work when your use `coc#pum#insert()` instead of `coc#pum#confirm()`, which doesn't have edits.

**Comment by otavioschwanck** [comment]
I'm using:

```
    inoremap <silent><expr> <TAB>
          \ coc#pum#visible() ? coc#pum#next(1) :
          \ CheckBackspace() ? "\<Tab>" :
          \ coc#refresh()
    inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

    inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                                  \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

```


trying to do a macro:
![Kapture 2022-09-04 at 12 45 12](https://user-images.githubusercontent.com/9551316/188311702-f184b025-4258-4991-84e1-ed06cb1a593a.gif)

**Comment by chemzqm** [comment]
Text edit applied to vim by use setline or nvim_buf_set_text api, not normal commands, I don't think it's possible to work with macro. Use coc#pum#insert instead

**Comment by otavioschwanck** [comment]
How can i use coc#pum#insert ?

**Comment by chemzqm** [comment]
:h coc-completion

**Comment by chemzqm** [comment]
It works for repeat, it's not possible for auto completion works with macro.

**Comment by otavioschwanck** [comment]
@chemzqm i think the autocomplete should be canceled when macro us being recorded.
