### ISSUE TITLE
Unable to silence messages

### ISSUE THREAD

**Issue by tmillr** [neoclide/coc.nvim#4147]
## Is your feature request related to a problem? Please describe.

Via custom code in my .vimrc, I've setup coc to automatically do the "hover" action whenever the cursor moves. However, I am unable to silence messages when the cursor lands on a location that does not have hover info to display. As I move the cursor around, I _constantly_ see `[coc.nvim]: hover not found`. Not only can I not silence the messages at all in any easy and accurate way, but as far as I know, there's no way to check if hover info is available at a particular location in the document _before_ calling `CocActionAsync('definitionHover')`, so this message is practically unavoidable currently.

<img width="1280" alt="Screen Shot 2022-09-04 at 3 01 52 PM" src="https://user-images.githubusercontent.com/45028928/188335151-97c18acc-6462-468e-bcd7-cffb34c39f43.png">

Here is my code for automatic hover:

```vim
let s:hover_timer = -1

function s:Hover(calledFromTimer)
    if a:calledFromTimer
        if CocHasProvider('hover') && !coc#float#has_float()
            silent! call CocAction('definitionHover')
            " silent call CocActionAsync('definitionHover')
        endif
    else
        call timer_stop(s:hover_timer)
        let s:hover_timer = timer_start(500, {-> s:Hover(v:true)})
    endif
endfunction

autocmd CursorMoved * call s:Hover(v:false)
```

## Describe alternatives you've considered
- `:silent! CocActionAsync("definitionHover")` doesn't work
- `:silent! CocAction("definitionHover")` doesn't work either

It may be possible to use Vim's `:redir` command to redirect output into a variable for some amount of time after calling `CocAction("definitionHover")`, although trying to do that and either time just it just right, or, have to regex match the output in order only filter messages from `CocAction("definitionHover")`, would be extremely hacky/finicky, unreliable, slow, and racy. Another idea would be to simply clear Vim's message area every time I call this function, although this doesn't seem like it would be that reliable either (I haven't tried it yet though). 

Really what is needed is a sort of configuration setting or an extra arg that can be passed to these CoC functions to keep them from writing/printing/echoing to the message area on their own. Generally speaking however, I think that functions are meant to be called from other code/functions and should therefore usually throw or return their errors so that the caller can ultimately choose how to handle them. Otherwise, this sort of problem (that this issue describes) can happen, and the caller has no control. This is especially true in Vim and is likely the reason why there are **both** `functions` _and_ `commands`. Commands are meant to be used on the cmdline, while functions are used to package code for easy reuse from other code/functions. This implies that while it is normal for `commands` to unconditionally print/echo messages (which can usually be silenced with Vim's `:silent` command if needed), it is probably not best practice for `functions` to be doing so.

## Proposed Solutions

- A: accept an extra, optional argument that is a boolean that when provided makes the entire function call silent (and optionally makes it return its messages as a string whenever an error occurs)

For example:

```vim
function CocAction(action, silent = v:false)

function CocActionAsync(action, silent = v:false)
```

- B: throw errors that the caller can catch

...or something else along those lines instead of unconditionally printing/echoing messages every time. It may not be necessary to implement this feature for absolutely every CoC function exposed in the external api, but as you can see, this feature would be especially useful for certain functions such as `CocAction` and `CocActionAsync`.

In addition to improving the functions of CoC's external API, an additional idea could be to provide a configuration setting for enabling the automatic display of hover information on `CursorMoved` (currently it seems that CoC only does this for diagnostic messages).

**Comment by qiqiboy** [comment]
`:h coc-preferences-messageLevel`

**Comment by tmillr** [comment]
> @qiqiboy :h coc-preferences-messageLevel

Thanks I'll check that out. This only filters echoed messages from CoC right? Like this setting hopefully won't filter out diagnostics from a language server? I still think it'd be nice to have more granular control though as I only want to silence messages for certain function calls (e.g. `CocAction("definitionHover")`).

**Comment by chemzqm** [comment]
Use `silent! call CocAction('doHover')` which blocks

**Comment by tmillr** [comment]
> silent! call CocAction('doHover')

Thanks

This appears to work when used from the cmdline, but I couldn't get `:silent!` to do anything in my autocmd. Maybe it has something to do with the way autocmd's are executed? Or maybe I made a mistake without realizing it (e.g. defined another autocmd instead of overwriting the old one when I added `silent!` to it?). I'm not sure.

**Comment by tmillr** [comment]
> > silent! call CocAction('doHover')
> 
> Thanks
> 
> This appears to work when used from the cmdline, but I couldn't get `:silent! CocAction('definitionHover')` to be silent in my autocmd. Maybe it has something to do with the way autocmd's are executed? Or maybe I made a mistake without realizing it (e.g. defined another autocmd instead of overwriting the old one when I added `silent!` to it?). I'm not sure.

I started a fresh nvim and made sure there weren't any extra/erroneous autocmds and am still experiencing the issue. A couple things to note from my setup:

1. I'm calling `:silent! CocAction('definitionHover')` from within a timer callback, the timer is scheduled inside CursorMoved autocmd which triggers often. I'm manually debouncing (cancelling previous timer if next CursorMoved triggers within 500ms).

2. This message doesn't get printed all the time when landing on a location that does not have hover, only sometimes does it get printed (bypassing the `:silent` modifier).

Again here is my `.vimrc`:

```vim
function s:Hover(calledFromTimer)
    if a:calledFromTimer
        if CocHasProvider('hover') && !coc#float#has_float()
            silent! call CocAction('definitionHover')
            " silent call CocActionAsync('definitionHover')
        endif
    else
        call timer_stop(s:hover_timer)
        let s:hover_timer = timer_start(500, {-> s:Hover(v:true)})
    endif
endfunction

augroup vimrc
    autocmd!

    autocmd CursorMoved * call s:Hover(v:false)
augroup END
```
