### ISSUE TITLE
New update changed how pum works, completion mapping no longer works

### ISSUE THREAD

**Issue by Rofer11607** [neoclide/coc.nvim#4155]
## Describe the bug

coc#pum#visible() no longer works, changing the coc#pum#visible() call to 1 makes it so that the mapping now works. However I need to know when the menu is visible so that the mapping doesn't interfere with other mappings

## Reproduce the bug

This mapping no longer works

imap <silent><expr> <TAB>
      \ coc#pum#visible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

imap <expr><S-TAB> coc#pum#visible() ? "\<C-p>" : "\<C-h>"

**Comment by Rofer11607** [comment]
reverting to bdf75abf2d892ceaa6f0f56c15a388ec31236ad2 made it work again, however I needed to go back to the pumvisible() version of the function

**Comment by Rizhiy** [comment]
I had a similar problem. I just updated it to new definition from example config.
Perhaps consulting it will help you, here is the relevant bit:
```vim
" Use tab for trigger completion with characters ahead and navigate.
" NOTE: There's always complete item selected by default, you may want to enable
" no select by `"suggest.noselect": true` in your configuration file.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
```

**Comment by Rofer11607** [comment]
Hmm I use copilot, does this mean I have to pick between upgrading this and copilot?

**Comment by Rizhiy** [comment]
For me copilot works as well.

**Comment by chemzqm** [comment]
> coc#pum#visible() no longer works, 

Could be overwrite by other vim plugin, try minimal vimrc

**Comment by nicksherron** [comment]
Why is this closed? This is a deal breaker for me personally and I haven't seen a solution thus far

**Comment by nicksherron** [comment]
> > coc#pum#visible() no longer works,
> 
> Could be overwrite by other vim plugin, try minimal vimrc

I can confirm I am having the same issue (conflict with copilot) and the only plugin I have updated was coc..
I am surprised this is closed,  some recent changes in coc made one of its core features  stop working nicely with other plugins (copilot in my case) which I think is as good of an issue as any to resolve. Especially when it conflicts with something like copilot!

**Comment by chemzqm** [comment]
> some recent changes in coc made one of its core features stop working nicely with other plugins (copilot in my case)

It's not, the key-mapping for `<tab>` is created by yourself, and copilot override `<tab>` by default, you have to tweak your key-mapping or configure copilot.

**Comment by Rofer11607** [comment]
Hey guys,

I'm going to retake a look at this. I find it unlikely that it is overwritten by another plugin, as reverting to a previous commit fixes the problem. This indicates that the problem is somewhere in the codebase being reverted, not the general environment that the plugin is working in.

I also know that code is surprising sometimes, so this may be happening however unlikely. Can we please reopen the issue with the promise that I will post an update with a minimal .vimrc by 09/18/2022?

**Comment by chemzqm** [comment]
The problem is vim-copliot check pumvisible,  but not coc#pum#visible, you have to configure your tab

**Comment by Rizhiy** [comment]
It's possible to just disable copilot default key bindings and define your own.

**Comment by Rofer11607** [comment]
Am I missing something here? Is it possible to remap coc#pum#visible to pumvisible?

Using javascript because I have to look up the vim syntax, but you get the idea, lol.

in my vimrc:

```javascript
function pumvisible() {

return coc#pum#visible()

}

```

How would I be able to set up a test environment to test this? Is there a vim-script equivalent to jest?

**Comment by chemzqm** [comment]
@Rofer11607 It's hard coded at https://github.com/github/copilot.vim/blob/1bfbaf5b027ee4d3d3dbc828c8bfaef2c45d132d/autoload/copilot.vim#L477, but you can disable copilot.vim's overwrite and define the key-mapping yourself.

**Comment by chemzqm** [comment]
Here is an example https://github.com/neoclide/coc.nvim/wiki/F.A.Q#tab-not-working-well-with-copilotvim

**Comment by Rofer11607** [comment]
This works awesome! Thank you!

**Comment by Rofer11607** [comment]
Here is the final complete solution for anyone else struggling:

let g:copilot_no_tab_map = v:true

inoremap <silent><expr> <TAB>

\ coc#pum#visible() ? coc#pum#next(1):

\ exists('b:_copilot.suggestions') ? copilot#Accept("\<CR>") :

\ CheckBackSpace() ? "\<Tab>" :

\ coc#refresh()

inoremap <silent><expr> <S-TAB>

\ coc#pum#visible() ? coc#pum#prev(1):

\ exists('b:_copilot.suggestions') ? copilot#Accept("\<CR>") :

\ CheckBackSpace() ? "\<Tab>" :

\ coc#refresh()

**Comment by Rofer11607** [comment]
I hear you, however, I would like to keep my mappings the same

Would it be possible for me to define a function that wraps coc#pum#visible that is named pumvisible? That way, no further changes need to be made.

**Comment by chemzqm** [comment]
You can't name it `pumvisible` since user global function have to be start with upper case letter.
