### ISSUE TITLE
Disable prompt popup Error loading workspace

### ISSUE THREAD

**Issue by jicvi** [neoclide/coc.nvim#4160]
**Is your feature request related t
o a problem? Please describe.**

![2022-09-07_19-13](https://user-images.githubusercontent.com/14210650/188865426-8647d78d-7621-46a7-a016-293458121ece.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
`:h coc-config-notification-disabledProgressSources`
Prefer fix the issue instead of disable progress.

**Comment by fannheyward** [comment]
Check `:h coc-config-notification-disabledProgressSources`.
