### ISSUE TITLE
Support positionEncoding utf-8 (LSP 3.17)

### ISSUE THREAD

**Issue by christianparpart** [neoclide/coc.nvim#4162]
**Is your feature request related to a problem? Please describe.**

Yes, we're currently working on an LSP and it most likely won't support UTF-16 anytime soon but UTF-8. It would be nice if coc.nvim would advertise utf-8 as supported positionEncoding, too.

**Describe the solution you'd like**
LSP 3.17 introduced [positionEncoding](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#clientCapabilities) capability. Supporting UTF-8 here is what I'd like to see.

**Describe alternatives you've considered**
UTF-16 is IMHO a legacy and I can only imagine why it's the default for LSP. 

**Additional context**
not yet

**Comment by chemzqm** [comment]
We will not, as javascript use UTF-16 internally, other encoding would requires too many changes.

**Comment by christianparpart** [comment]
Interesting argument. I respect that.
