### ISSUE TITLE
Add Gui for LSP 3.17 type hierarchy

### ISSUE THREAD

**Issue by RedBeard0531** [neoclide/coc.nvim#4170]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to explore the hierarchy of types in my codebase. 

**Describe the solution you'd like**
LSP 3.17 [added support](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareTypeHierarchy) for this. clangd has supported it as an extension but as of clangd-15 it now uses the standard API. It looks like coc already has some internal support for this API, but there is no user-facing gui for it yet. This should be exposed in the tree similarly to the call hierarchy.

Personally, I'd love it if there was an easy way to see both parents and children of the type at the same time since I often want to know both (and it is one less binding to add and remember).

For languages with multiple inheritance, it would be really cool if you could show "sibling parents" for all subclasses that have a parent other than the parent used to discover them.

**Describe alternatives you've considered**
I [asked](https://github.com/clangd/coc-clangd/issues/502) about adding support for the clangd type hierarchy extension to coc-clangd, which is how I learned that clangd has switched to the new standard API. Given that the API is standardized, this feels like something that belongs in coc core rather than an extension.

**Additional context**
🤷 Thanks for all the work on coc!

**Comment by chemzqm** [comment]
Does latest clangd have type hierarchy support?

**Comment by RedBeard0531** [comment]
That's what the discussion in https://github.com/clangd/coc-clangd/issues/502 says. I haven't personally tested it though.
