### ISSUE TITLE
SPAM in the Wiki!?

### ISSUE THREAD

**Issue by tmillr** [neoclide/coc.nvim#4177]
What is this? How did it get there? (not sure if link below works, but go to coc.nvim wiki and look at TOC in righthand sidebar, also see image below). Sorry for creating an issue, I'm only trying to help.

> Bitcoin Bitcoin 2 Black letter B BBTC Bitcoin God BTCUSD market BTCCRC market cryptocurrency market reusable green energy ECO 2.0 token ETH. BSV lightting network USDT infinity BTC. Infinity reusable green energy of cryptocurrency marke.

https://github.com/neoclide/coc.nvim/wiki/Bitcoin-Bitcoin-2-Black-letter-B-BBTC-Bitcoin-God--BTCUSD-market--BTCCRC-market--cryptocurrency-market--reusable-green-energy-ECO-2.0-token--ETH.--BSV--lightting-network--USDT-infinity-BTC.--Infinity--reusable-green-energy-of-cryptocurrency-marke.

**Comment by tmillr** [comment]
<img width="322" alt="Screen Shot 2022-09-10 at 3 57 27 PM" src="https://user-images.githubusercontent.com/45028928/189504529-3deea49a-b00b-4579-8f05-52dec406e1f2.png">

**Comment by chemzqm** [comment]
It's removed.
