### ISSUE TITLE
cmdheight set to max when vim-peekaboo register preview window closes

### ISSUE THREAD

**Issue by gibfahn** [neoclide/coc.nvim#4178]
## Result from CocInfo

<details><summary>CocInfo Output</summary>

```
## versions

vim version: NVIM v0.7.2
node version: v16.17.0
coc.nvim version: 0.0.82-2a9f239e 2022-09-11 16:33:59 +0800
coc.nvim directory: /private/var/folders/kf/mtd6c3ys0tvb6ppy_8rdh5hr0000gn/T/nvim_4178/xdg_data_home/nvim/plugged/coc.nvim
term: xterm-kitty
platform: darwin

## Log of coc.nvim

2022-09-11T13:09:47.595 INFO (pid:68952) [plugin] - coc.nvim initialized with node: v16.17.0 after 60ms
2022-09-11T13:13:16.602 INFO (pid:68952) [attach] - receive notification: showInfo []
```

</details>

## Describe the bug

When I apply a macro, the cmdheight get set to the max, so that I can only see one line of the output.

Previously reported at: https://github.com/junegunn/vim-peekaboo/issues/74 and https://github.com/neoclide/coc.nvim/issues/2869 (seems like the same bug)

## Reproduce the bug

Plugins:
- [junegunn/vim-peekaboo](https://github.com/junegunn/vim-peekaboo)
- [neoclide/coc.nvim](https://github.com/neoclide/coc.nvim)

This works for me on my laptop screen.

```shell
export tmp=$TMPDIR/nvim_4178
rm -rf "$tmp"
export XDG_DATA_HOME=$tmp/xdg_data_home
export XDG_CONFIG_HOME=$tmp/xdg_config_home
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo "
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden

call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/vim-peekaboo'
call plug#end()
" >"$tmp/mini.vim"
curl -o "$tmp/CONTRIBUTING.md" https://raw.githubusercontent.com/Homebrew/brew/master/CONTRIBUTING.md
nvim -es -u "$tmp/mini.vim" -i NONE -c "PlugInstall" -c "qa"
nvim -u $tmp/mini.vim -c "CocInstall -sync coc-markdownlint|qa"
nvim -u "$tmp/mini.vim" "$tmp/CONTRIBUTING.md"
```

When you get the contributing.md open, press `w` till you get to the `/` of the `.github/` and then type:

- 	`"`
- `Esc`

And you should be left with 1 line at the top of the screen (and `set cmdheight?` should return something like `54`).

I mostly hit this while applying a macro that uses a register, but this seems like an easier reproduction.

I think the key is to open the window on a long line, so that the wrapping of the text changes when the peekaboo window opens/closes.

## Screenshots (optional)

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/15943089/189523328-bd37020f-e96a-4f52-a5ab-4139026de294.png">

**Comment by gibfahn** [comment]
I filed this under coc.nvim rather than vim-peekaboo because I can see that coc.nvim does do things with cmdheight and as far as I can tell vim-peekaboo doesn't.

**Comment by gibfahn** [comment]
Okay, I believe this is a minimal repro, and it works for me on my laptop screen.

```shell
export tmp=$TMPDIR/nvim_4178
rm -rf "$tmp"
export XDG_DATA_HOME=$tmp/xdg_data_home
export XDG_CONFIG_HOME=$tmp/xdg_config_home
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo "
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden

call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/vim-peekaboo'
call plug#end()
" >"$tmp/mini.vim"
curl -o "$tmp/CONTRIBUTING.md" https://raw.githubusercontent.com/Homebrew/brew/master/CONTRIBUTING.md
nvim -es -u "$tmp/mini.vim" -i NONE -c "PlugInstall" -c "qa"
nvim -u $tmp/mini.vim -c "CocInstall -sync coc-markdownlint|qa"
nvim -u "$tmp/mini.vim" "$tmp/CONTRIBUTING.md"
```

When you get the contributing.md open, press `w` till you get to the `/` of the `.github/` and then type:

- 	`"`
- `Esc`

And you should be left with 1 line at the top of the screen.

Given the repro nature, maybe it's an issue with coc-markdownlint.

**Comment by chemzqm** [comment]
Try `let $COC_NO_PLUGINS = '1'` in your vimrc to disable all coc.nvim extensions.
