### ISSUE TITLE
Exception not caught: bad term value

### ISSUE THREAD

**Issue by jbernardo95** [neoclide/coc.nvim#4180]
## Result from CocInfo

Can't run CocInfo, as coc crashes when I open vim. But I'm on the lastest version as of 12th September 2022.

## Describe the bug

```
Error detected while processing /Users/jb/.vim/plugged/coc.nvim/plugin/coc.vim[673]..function <SNR>18_Highlight[10]..coc#highlight#get_contrast[1]..coc#highlight#get_hex_color[2]..<SNR>22_to_hex_color[8]..coc#color#term2rgb[2]../Users/jb/.vim/plugged/coc.nvim/plugin/coc.vim[673]..function <SNR>18_Highlight[10]..coc#highlight#get_contrast[1]..coc#highlight#get_hex_color[2]..<SNR>22_to_hex_color[8]..coc#color#term2rgb:
line    2:
E605: Exception not caught: bad term value 232426
```

I get the error above when opening vim.

## Reproduce the bug

The issues seems to be this line I have in my `.vimrc`:

```
highlight Normal ctermbg=232426
```

If you put that in `vimrc` and then open vim with coc installed it should crash has vim is opening.

**Comment by chemzqm** [comment]
What is the result of your `:echo g:colors_name`

**Comment by jbernardo95** [comment]
`Tomorrow-Night`

**Comment by jbernardo95** [comment]
Thank you for the quick fix!
