### ISSUE TITLE
:call CocAction('jumpDefinition', v:false) get neovim frozen

### ISSUE THREAD

**Issue by hexh250786313** [neoclide/coc.nvim#4192]
## Env

- neovim 0.7.2 the release

## Reproduce

```shell
# tree of the debug project
.
├── coc
├── debug
│   ├── constant.js
│   └── index.js
└── mini.vim
```

```javascript
// -- debug/constant.js
const A = {};

module.exports = { A };
```

```javascript
// -- debug/index.js
const Constant = require('./constant');
//     ↑↑↑↑↑↑
// ** Cursor Here **
```

```vim
" -- mini.vim
set nocompatible
set runtimepath^=/path/to/coc.nvim/
filetype plugin indent on
syntax on
set hidden

let g:coc_data_home = './coc'

let g:coc_global_extensions = ['coc-tsserver']

let g:coc_user_config = {}

nnoremap <silent> <c-]> :call CocAction('jumpDefinition', v:false)<CR>
```

1. Run `nvim --clean -u ./mini.vim ./debug/index.js`
2. Wait for tsserver to finish initializing
3. Move cursor to the variable `Constant`
4. Press `C-]`
5. Get nvim frozen

**Comment by hexh250786313** [comment]
And if I have the `debug/constant.js` buffer opened, the coc works as expected and nvim will not be frozen.

**Comment by chemzqm** [comment]
Use `CocActionAsync`

**Comment by hexh250786313** [comment]
@chemzqm I know `CocActionAsync` can prevent nvim from being frozen, but it still does not work as expected. The command `:call CocActionAsync('jumpDefinition', v:false)` do nothing in this case. It can't open the locationlist or jump.

**Comment by chemzqm** [comment]
I can't reproduce, see https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by hexh250786313** [comment]
@chemzqm In my case, the program will enter this function to read the lines of an unopened file. But it seems that the variable `count` and `n` will not be same which causes the promise can not resolve or reject.

https://github.com/neoclide/coc.nvim/blob/72e283cef486262999117ff3b11fd4773f0260ac/src/util/fs.ts#L221-L248

Thas is part of my `CocOpenLog`:

```shell
2022-09-14T15:01:17.560 WARN (pid:376788) [util-fs] - {"n":0,"count":3}
2022-09-14T15:01:17.560 WARN (pid:376788) [util-fs] - {"n":1,"count":3}
2022-09-14T15:01:17.560 WARN (pid:376788) [util-fs] - {"n":2,"count":3}
2022-09-14T15:01:21.051 INFO (pid:376788) [attach] - receive notification: openLog []
```
