### ISSUE TITLE
Errors should indicate in which file the problem resides

### ISSUE THREAD

**Issue by vpfeiffer** [neoclide/coc.nvim#4196]
**Is your feature request related to a problem? Please describe.**
When I updated `coc-nvim` to version 2022-06-03, rev 102fe82be44e878d6eefdab2cb2fc4aaa5a346f3 I discovered
that my language servers weren't working. The error message indicated that I should check `:CocDiagnostics` .
When I did, the diagnostics window was blank. After asking around I found that others had the same issue and that 
it was because `.config/nvim/coc-settings.json` was missing commas after each language server entry. I.e. It should look
as follows:
```
  {
    "languageserver": {
      "haskell": {
        "command": "haskell-language-server-wrapper",
        "args": ["--lsp"],
        "filetypes": ["haskell", "lhaskell"],
        "rootPatterns": ["*.cabal", "stack.yaml", "cabal.project", "package.yaml", "hie.yaml"]
      },
      "rust": {
        "command": "rust-analyzer",
        "filetypes": ["rust"],
        "rootPatterns": ["Cargo.toml"]
      },
      "nix": {
        "command": "rnix-lsp",
        "filetypes": ["nix"]
      }
    }
  }
```
I no longer had the issue after updating this json file.

**Describe the solution you'd like**
It would be useful if the `coc-nvim` errors indicated in which file the problem had occured.

**Describe alternatives you've considered**
It is possible that there is some other issue with my version of `coc-nvim` which is why the diagnostics window
came up blank, otherwise this could be a feauture. (I'm not sure which.)

**Additional context**
Additionally the documentation for how to enable these language servers should be updated to include the required `,` after each one or otherwise indicate that this is necessary.

**Comment by fannheyward** [comment]
> missing commas

You can use `coc-json` to lint, and auto suggestions for your coc-settings.json.

**Comment by chemzqm** [comment]
> The error message indicated that I should check :CocDiagnostics

It should be `:CocLIst diagnoatics` not `:CocDiagnostics`

**Comment by vpfeiffer** [comment]
Thanks!
