### ISSUE TITLE
Post hook / install.sh failing

### ISSUE THREAD

**Issue by ssmithstone** [neoclide/coc.nvim#42]
**Describe the bug**
+PlugInstall / +PlugUpdate is returning exit code 1

**To Reproduce**
follow instructions for installation using Plug

**Expected behavior**
Post hook should not fail

**Desktop (please complete the following information):**
 - Nvim: v0.3.1

**Comment by chemzqm** [comment]
what platform are you using？

**Comment by ssmithstone** [comment]
OS X 10.12.6

**Comment by chemzqm** [comment]
Try `./install.sh` in folder of `coc.nvim`, it could take sometime to finish depends on your network.
<img width="827" alt="screen shot 2018-08-06 at 8 10 06 am" src="https://user-images.githubusercontent.com/251450/43691510-40819d54-9950-11e8-9b42-e7e043ad4f40.png">

**Comment by ssmithstone** [comment]
Fetching latest release.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1207    0  1207    0     0    516      0 --:--:--  0:00:02 --:--:--   516
 Downloading binary from https://github.com/neoclide/coc.nvim/releases/download/v0.0.5/coc-macos.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   607    0   607    0     0    674      0 --:--:-- --:--:-- --:--:--   675
100 15.4M  100 15.4M    0     0   709k      0  0:00:22  0:00:22 --:--:-- 1094kx coc-macos

chmod: coc-macos.tar.gz: No such file or directory

**Comment by ssmithstone** [comment]
running zsh and have yarn install globally on node 8.10
