### ISSUE TITLE
Completion Menu Selection no highlight anymore after update coc.nvim

### ISSUE THREAD

**Issue by jacklanda** [neoclide/coc.nvim#4201]
Completion Menu Selection no highlight anymore after update coc.nvim, using `gruvbox` colorscheme.
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/54089835/190554770-4ed7e2f0-73e8-4177-900b-79bd16a53b87.png">

However, when I type `:colorscheme gruvbox`, everything seem to be okay. It's so weired.
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/54089835/190554877-855baa6b-ee7e-47a1-b640-db96c2825fb1.png">

**Comment by chemzqm** [comment]
Use `set termguicolors` in your vimrc or configure highlight for `CocMenuSel`

**Comment by avalonv** [comment]
Did you recently change the highlight group CocMenuSel sources from? I also ran into this issue.
