### ISSUE TITLE
Ctrl-N jumps over the first candidate in the menu

### ISSUE THREAD

**Issue by balta2ar** [neoclide/coc.nvim#4202]
## Result from CocInfo

```
## versions

vim version: NVIM v0.8.0-dev-805-g512e0441f
node version: v16.16.0
coc.nvim version: 0.0.82-4d184f0d 2022-09-15 23:35:04 +0800
coc.nvim directory: /home/user/rc.arch/bz/.vim/plugged/coc.nvim
term: tmux
platform: linux
```

## Describe the bug

With the configuration suggested in the README, when pressing "ctrl-n" the second item is selected instead of the first one.

Sample text:
```
select primary_title,premiered,runtime_minutes||' (mins)'
from titles
li<cursor here>
where genres like '%Sci-Fi%'
order by runtime_minutes desc
limit 10
```
![image](https://user-images.githubusercontent.com/340676/190584596-076b8b05-cbbe-4346-8258-bafc437c466e.png)

When I'm in the state as shown on the screenshot and I press "ctrl-n", "limit" is selected. I expect "like" to be selected.
If I press "Enter" -- "like" is selected as expected, but I would like "ctrl-n" to not skip over the first item.

It's not necessarily a bug, it could as well be an error in my configuration. In that case -- could you please suggest a corresponding configuration change?

## Reproduce the bug

```
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

set completeopt=noinsert,menuone,noselect
set completeopt-=longest
set shortmess+=c
inoremap <expr> <CR> (pumvisible() ? "\<c-y>\<cr>" : "\<CR>")
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1):
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

**Comment by fannheyward** [comment]
Enable `suggest.noselect` in your coc-settings.json.
