### ISSUE TITLE
extension can't update configurations 

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#4207]
extensions can't update configurations after #4154

## Reproduce the bug

```ts
  const tsCfg = workspace.getConfiguration('tsserver')
  tsCfg.update('trace.server', "verbose", false) // tested with isUser=true, target = 1,  3, same error

  const jsonCfg = workspace.getConfiguration('json')
  jsonCfg.update('trace.server', "verbose", false)
```

User configurations or workspace configurations result:

```
{
  "json.trace.server": "verbose"
}e"
}
```

**Comment by chemzqm** [comment]
Can't reproduce.

**Comment by fannheyward** [comment]
Tested with latest master, still have this issue. Uninstalled all extensions and `:CocInstall coc-git coc-json` only for later test.

mini.vim:

```
set nocompatible
set runtimepath^=/Users/fannheyward/.local/share/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

set runtimepath^=~/src/coc-bug
```

coc-bug:

```
import { workspace } from 'coc.nvim';

export async function activate(): Promise<void> {
  const gitCfg = workspace.getConfiguration('git')
  gitCfg.update('addGBlameToVirtualText', true, false)

  const jsonCfg = workspace.getConfiguration('json')
  jsonCfg.update('trace.server', "verbose", false)
}
```

1. `mkdir -p ~/src/a4 && cd ~/src/a4`
2. `touch foo.txt`
3. `ls -lha` result

```
drwxr-xr-x    3 fannheyward  staff    96B  9 18 14:24 ./
drwxr-xr-x  129 fannheyward  staff   4.0K  9 18 14:24 ../
-rw-r--r--    1 fannheyward  staff     0B  9 18 14:24 foo.txt
```

`nvim -u ~/mini.vim foo.txt`

<img width="553" alt="截屏2022-09-18 14 26 54" src="https://user-images.githubusercontent.com/345274/190888878-950215c0-6fcc-4ae0-894d-bc11f3781d56.png">

`cat .vim/coc-settings.json`

```
{
  "json.trace.server": "verbose"
}ue
}
```

`:CocList extensions`

<img width="592" alt="截屏2022-09-18 14 35 50" src="https://user-images.githubusercontent.com/345274/190889139-8bcbf11d-67e6-4121-a7dd-8b696f3cc506.png">

**Comment by yaegassy** [comment]
The same problem seems to be occurring with `coc-volar`.

In `coc-volar`, there is a command to create a `.vim/coc-settings.json` at the workspace level and configure the necessary settings.

When I run it, I get an error message because of an invalid json file.

**DEMO**:

https://user-images.githubusercontent.com/188642/190889702-dc923b98-b65f-4710-89b4-c2551cae04df.mp4

**Comment by fannheyward** [comment]
> In coc-volar, there is a command to create a .vim/coc-settings.json at the workspace level and configure the necessary settings.

I came this because `coc-deno` needs to do same things.

https://github.com/fannheyward/coc-deno/blob/186e1b5060ea0a08c1ecebb7a2ebd19ff783f442/src/commands.ts#L69-L72

**Comment by chemzqm** [comment]
Could be issue on different node version

**Comment by fannheyward** [comment]
I'm using node 16 LTS latest release.

**Comment by js-writer** [comment]
Work only when I manually created .vim folder with coc-settings.json inside. Without it nothing happened and I still get this error: 
`[coc.nvim]: Unable to locate workspace folder configuration for` so I think that there is some problem with folder and file creation.
