### ISSUE TITLE
Omnisharp-vim not working with Ultisnips on Completion snippets after the coc version update

### ISSUE THREAD

**Issue by lubyrex** [neoclide/coc.nvim#4209]
## versions

vim version: NVIM v0.6.0-dev+525-ge921e98ce
node version: v16.16.0
coc.nvim version: 0.0.82-b9c208ef 2022-09-07 15:41:25 +0800
coc.nvim directory: C:\Users\youche\AppData\Local\nvim-data\plugged\coc.nvim
term: vtpcon
platform: win32

## Log of coc.nvim

2022-09-18T14:46:23.183 INFO (pid:25580) [coc-git] - Looking for git in: git
2022-09-18T14:46:23.332 INFO (pid:25580) [plugin] - coc.nvim initialized with node: v16.16.0 after 302ms
2022-09-18T14:46:23.899 WARN (pid:25580) [sources] - Recreate source OmniSharp
2022-09-18T14:47:28.510 INFO (pid:25580) [attach] - receive notification: checkJsonExtension []
2022-09-18T14:47:28.593 INFO (pid:25580) [services] - registered service "json"
2022-09-18T14:47:28.594 INFO (pid:25580) [services] - Json language server state change: stopped => starting
2022-09-18T14:47:30.199 INFO (pid:25580) [services] - Json language server state change: starting => running
2022-09-18T14:47:30.215 INFO (pid:25580) [services] - service json started
2022-09-18T14:51:52.778 INFO (pid:25580) [attach] - receive notification: showInfo []

## Describe the bug

pressing control-n on the code completion window will escape out of the window while selecting the first completion option

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：
-

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden

call plug#begin(stdpath('data') . '/plugged')
Plug 'OmniSharp/omnisharp-vim'
Plug 'SirVer/ultisnips' 
Plug 'neoclide/coc.nvim'
call plug#end()

let g:OmniSharp_want_snippet = 1
let g:OmniSharp_server_use_net6 = 1
let g:OmniSharp_timeout = 105
let g:OmniSharp_server_stdio = 1
let g:OmniSharp_completion_without_overloads=1

  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

https://user-images.githubusercontent.com/16534505/190889861-553b8fe1-8a00-404d-97c7-824e6c770240.mp4

**Comment by fannheyward** [comment]
coc.nvim 0.0.82 has changed to custom completion menu, you need to change your key mappings, check README or `:h coc-completion-example`

**Comment by lubyrex** [comment]
thanks for the response, the custom completion menu comes up just fine, however when I click C-N to select the options, it doesn't work since it expands on the snippet and exit out of the menu.
key mapping:
![image](https://user-images.githubusercontent.com/16534505/190890727-709dcb45-68df-47fd-aca2-7cc6fbc1adda.png)
if I set 
let g:OmniSharp_want_snippet = 0
everything goes smoothly

**Comment by chemzqm** [comment]
Because we have to use `complete()` to support repeat edit during navigation https://github.com/neoclide/coc.nvim/blob/e689bbf855a8c9d9eb3733456718875a21a16b58/autoload/coc/pum.vim#L304 which always fire CompleteDone.
you can use `coc#pum#next(0)` instead which doesn't insert word.

**Comment by lubyrex** [comment]
I've tried that but it's not what I would like. Is there a way to have this behave similar to coc-snippets where I press control-y to trigger the snippet?

**Comment by chemzqm** [comment]
You can bind `<C-y>` yourself.

**Comment by lubyrex** [comment]
since omnisharp-vim uses the custom source to provide completion items, is it possible to modify the custom source to include snippet support?

**Comment by chemzqm** [comment]
@lubyrex unfortunately, snippet support for complete item from vim sources is missing, consider open a feature request.
