### ISSUE TITLE
Coc shows me that stdio.h can't be found

### ISSUE THREAD

**Issue by PeterPancake666** [neoclide/coc.nvim#4211]
I have installed gcc, clang and clangd. I have compiled the code with clang and I didn't get any error messages.

![bruhhhhhhhhhhhhhhhh](https://user-images.githubusercontent.com/96543374/191055270-6131432e-7370-4d45-8dcf-67ef5b73691a.png)

This is my init.vim:

:set number
:set autoindent
:set tabstop=4
:set shiftwidth=4
:set smarttab
:set softtabstop=4
:set mouse=a

call plug#begin()

Plug 'http://github.com/tpope/vim-surround'
Plug 'https://github.com/preservim/nerdtree'
Plug 'https://github.com/tpope/vim-commentary'
Plug 'https://github.com/vim-airline/vim-airline' 
Plug 'https://github.com/ap/vim-css-color'
Plug 'https://github.com/rafi/awesome-vim-colorschemes'
Plug 'https://github.com/ryanoasis/vim-devicons'
Plug 'https://github.com/tc50cal/vim-terminal'
Plug 'https://github.com/terryma/vim-multiple-cursors' 
Plug 'https://github.com/neoclide/coc.nvim'
Plug 'https://github.com/jiangmiao/auto-pairs'

call plug#end()

nnoremap <C-f> :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>

" use <tab> for trigger completion and navigate to the next complete item
function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()

:set completeopt-=preview
let g:NERDTreeDirArrowExpandable="+"
let g:NERDTreeDirArrowCollapsible="~"
:colorscheme jellybeans

This is my coc-settings.json:

{
  "diagnostic.checkCurrentLine": true,
  "suggest.noselect": false
}

**Comment by chemzqm** [comment]
You need to configure your language server to find the header files needed.
