### ISSUE TITLE
coc-extension no longer activate due to coc.nvim update

### ISSUE THREAD

**Issue by yaegassy** [neoclide/coc.nvim#4212]
## Result from CocInfo

```
## versions

vim version: NVIM v0.8.0-dev-1114-g8dc61713d
node version: v16.17.0
coc.nvim version: 0.0.82-1e42d27 2022-09-19 23:03:24 +0800
coc.nvim directory: /Users/yaegassy/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug

I'm having this problem `@yaegassy/coc-tailwindcss3`. Since this commit, the extension is no longer activated.

- <https://github.com/neoclide/coc.nvim/commit/536be82a94afb3aa69801ea8b7dcd945596bcb7f>

I reverted to one previous commit and tried it and it was activated correctly.

- <https://github.com/neoclide/coc.nvim/commit/cf4c602445899297c94188be9be87deb9e17e72f>

## Reproduce the bug

**prepare1**:

```
:CocInstall @yaegassy/coc-tailwindcss3
```

**prepare2**:

```
mkdir -p $HOME/check
cd $HOME/check
npm init -y
npm i tailwindcss
npx tailwindcss init
```

**operate**:

```
nvim index.html
```

### [NG] coc.nvim (latest)

https://user-images.githubusercontent.com/188642/191158863-d1d58694-426c-4a3c-a25f-f80409f83494.mp4

### [OK] coc.nvim (cf4c602)

https://user-images.githubusercontent.com/188642/191158985-725b1a99-33a3-4f2d-bf88-5e6fefb085ee.mp4

**Comment by chemzqm** [comment]
```
  "activationEvents": [
    "workspaceContains:**/tailwind.js",
    "workspaceContains:**/tailwind.cjs",
    "workspaceContains:**/tailwind.config.js",
    "workspaceContains:**/tailwind.config.cjs"
  ],
```
The patterns are mixed to one for better performance, there's some issue with those patterns

**Comment by chemzqm** [comment]
You can use `**/?(tailwind.js|tailwind.cjs|tailwind.config.js|tailwind.config.cjs)` instead before the ifx.

**Comment by yaegassy** [comment]
Thanks for the reply. I understand about the performance issue. I tried the change, but the extension was not activated.

```
  "activationEvents": [
    "workspaceContains:**/?(tailwind.js|tailwind.cjs|tailwind.config.js|tailwind.config.cjs)"
  ],
```

After removing the `**/` pattern, the extension was actiavted.

```
  "activationEvents": [
    "workspaceContains:?(tailwind.js|tailwind.cjs|tailwind.config.js|tailwind.config.cjs)"
  ],
```

However, if `**/` is not available, configurations directly under the project root are detected, but if configurations exist in subdirectories, the extension is not activated...

**Comment by yaegassy** [comment]
Thanks for the fix!

**Comment by iamcco** [comment]
coc-angular still does not active with latest release. 

https://github.com/iamcco/coc-angular/blob/master/package.json#L28

```
  "activationEvents": [
    "workspaceContains:angular.json",
    "workspaceContains:node_modules/@angular/core/core.d.ts"
  ],
```

change `"workspaceContains:angular.json"` to `"workspaceContains:**/angular.json"` seems active.

**Comment by chemzqm** [comment]
> "workspaceContains:angular.json"

It should be direct child in workspace folder, `node_modules` is ignored for performance reason.

**Comment by iamcco** [comment]
> > "workspaceContains:angular.json"
> 
> It should be direct child in workspace folder, `node_modules` is ignored for performance reason.



The `angular.json` is direct child in workspace as below

![image](https://user-images.githubusercontent.com/5492542/191483180-0f6ecba5-2168-4023-be02-b5420fc410fd.png)

**Comment by chemzqm** [comment]
Workspace folder created after document creation, did you open files?

**Comment by iamcco** [comment]
open file still not active, use command `CocCommand workspace.workspaceFolders` shows that workspace is my project directory.

![image](https://user-images.githubusercontent.com/5492542/191548332-bcbaa651-4777-40a4-a47b-3a8cbe863739.png)

**Comment by chemzqm** [comment]
@iamcco fixed, join pattern with '/' not work.
