### ISSUE TITLE
Path configuration file for vim

### ISSUE THREAD

**Issue by miguebarbell** [neoclide/coc.nvim#4217]
Can you guys make the configuration file for vim user follow XDG patterns
In example, my vim config folder is at $XDG_CONFIG_HOME/vim, but my coc-settings.json is at ~/.vim
and yes, I have the ~/.vim folder just for the config file.

**Comment by fannheyward** [comment]
Check `:h coc_data_home`.

**Comment by chemzqm** [comment]
`$VIMCONFIG` is preferred, you can check the code https://github.com/neoclide/coc.nvim/blob/488d6ae762f905f58a362294bab0af2150d0c399/autoload/coc/util.vim#L516

**Comment by miguebarbell** [comment]
Thanks, @chemzqm, I write the environmental variable.
