### ISSUE TITLE
error highlighting in gvim/vim is not cleared

### ISSUE THREAD

**Issue by Frydac** [neoclide/coc.nvim#422]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 15 2019 00:11:27)
node version: v8.9.0
coc.nvim version: 0.0.52
term: dumb
platform: linux

## Error messages

## Output channel: snippets
[...]
## Output channel: languageserver.ccls
[...]
```
**Describe the bug**
Error highlighting is not cleared after the syntax error is corrected in gvim/vim, however, it works as expected in nvim/nvim-qt.
Been having this issue for a while, but could always be cleared by a quick `:w`, but since I last updated my system (including vim, and it had been a few months), this trick doesn't work anymore for me.
Things I found that do clear the error highlighting:
* changing buffers inside the same window, e.g. quickly switching between alternate file and back (which is what I do currently)
* opening a split with the same buffer (`<c-w><c-v>`), and then closing the current window (`<c-w>c`).

I haven't tried with any other language server than ccls.

**To Reproduce**
Probably best to see the screenshots.

**Screenshots**
I create a function and misspell `int` as `iant`, which is highighted with underlining and a sign in the gutter.
Then when I correct spelling, the sign in the gutter disappears, but the underlining does not.
![error](https://user-images.githubusercontent.com/2588526/52566601-7476bc80-2e0a-11e9-9f5d-902650a78237.png)
![error_fixed](https://user-images.githubusercontent.com/2588526/52566605-7771ad00-2e0a-11e9-9008-c65f7a0e44f6.png)

**Comment by chemzqm** [comment]
It's fixed on 0.0.53

**Comment by Frydac** [comment]
Thanks, it is :) 

I guess I was just too early with my update yesterday, should have tried again today.. or checked the commits, would have saved me some time.

**Comment by philippludwig** [comment]
I still encounter this in version 0.0.78. For example:

![image](https://user-images.githubusercontent.com/3770792/96560580-c863c500-12be-11eb-8ce5-3f833fa6d075.png)

The workaround with opening the same buffer in a split window and closing the original one works, but it is still annoying. Since this has been marked as a duplicate, is there an original issue with more information?

**Comment by chemzqm** [comment]
@philippludwig please use latest release first.

**Comment by philippludwig** [comment]
I was not aware that a new version existed, thank you for this hint. I updated to `0.0.79-a900a8535c`, but sadly the problem persists. I am using Vim 8.1 by the way.

**Comment by philippludwig** [comment]
I have switched to nvim 0.5 and it works as expected.
