### ISSUE TITLE
Timeout after 60s when `:w` various git file formats

### ISSUE THREAD

**Issue by pharmpy-dev-123** [neoclide/coc.nvim#4222]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9000472
node version: v18.9.0
coc.nvim version: 0.0.82-488d6ae7 2022-09-22 01:50:53 +0800
coc.nvim directory: ~/.vim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin

## Log of coc.nvim

2022-09-22T16:58:28.365 INFO (pid:28742) [services] - registered service "pyright"
2022-09-22T16:58:28.379 INFO (pid:28742) [plugin] - coc.nvim initialized with node: v18.9.0 after 99724ms
2022-09-22T16:58:28.394 INFO (pid:28742) [core-watchman] - watchman watching project: ~/dev/pharmpy/pharmpy
2022-09-22T17:00:28.180 INFO (pid:28742) [attach] - receive notification: showInfo []
```

## Describe the bug

I get a very long response time on `:w` (`vim` hangs for roughly 1 minute) on `COMMIT_EDITMSG` and also on `git rebase -i` plan writing.

```
Error on request (CocAutocmd): request CocAutocmd ['BufWritePre', 1, '/.../COMMIT_EDITMSG', 3] timeout after 60s 
```

If I try to do `:CocDisable` before `:w` I get a similar error: `Error on request (detach): request detach [] timeout after 60s`. `:q` on an unedited file works fine. Any idea what is going on?

## Reproduce the bug

WIP

**Comment by chemzqm** [comment]
Seems the node process not responding for some reason, checkout the CPU usage of `:echo g:coc_process_pid`

**Comment by matt-fff** [comment]
I ran into this as well. Downgrading to the `v0.0.81` tag alleviated the issue.

**Comment by lanza** [comment]
Same here!

**Comment by chemzqm** [comment]
> request CocAutocmd ['BufWritePre', 1, '/.../COMMIT_EDITMSG', 3

That autocmd should be created by some coc.nvim extension, what extensions you're using?

**Comment by chemzqm** [comment]
Added trace for slow hanlder at 73bd75a7

**Comment by pharmpy-dev-123** [comment]
Can confirm downgrading to `v0.0.81` and removing `coc-tsserver` works. Will try to troubleshoot `master` later.

**Comment by mkastner** [comment]
Unfortunately I can't add any information on the issue except that I've wrangling with the slow writing for hours now.

Using **branch master** and and setting the **tag v0.0.81** actually got me going again.

**Comment by chemzqm** [comment]
Use `:noa w` to avoid the sync autocmd.

**Comment by chemzqm** [comment]
Should be caused by the glob when the workspace folder contains too many files.

**Comment by pharmpy-dev-123** [comment]
> Should be caused by the glob when the workspace folder contains too many files.

Does the glob ignore what is ignored by `git`?

**Comment by oliviertilmans** [comment]
> Should be caused by the glob when the workspace folder contains too many files.

Upgrading coc.nvim to > 043b431 addressed this issue on my end
