### ISSUE TITLE
Cannot install plugins behind a proxy

### ISSUE THREAD

**Issue by EnricoSteez** [neoclide/coc.nvim#4229]
## versions

vim version: NVIM v0.7.0
node version: v16.17.0
coc.nvim version: 0.0.82-488d6ae7 2022-09-22 01:50:53 +0800
coc.nvim directory: /..../nvim/plugged/coc.nvim
term: tmux
platform: linux

 Log of coc.nvim
2022-09-23T16:00:31:437 INFO (pid:...) [plugin] coc.nvim initialised with node: v16.17.0 after 29ms
2022-09-23T16:00:31:437 INFO (pid:...) [attach] receive notification: highlight []
2022-09-23T16:00:31:437 INFO (pid:...) [attach] receive notification: show Info []

## Describe the bug
I recently started working inside a VM rather than on my personal machine. So I ported my vim config to the machine. I now need to install a coc extension for c++.
Running :CocInstall coc-clangd (but any other plugin, really) runs into:
Install finished

-  coc-clangd Request failed using proxy [...]: unable to verify the first certificate

## Reproduce the bug

Works with any vimrc and the issue is just that CocInstall cannot download stuff from behind the proxy
Even if I do `let g:coc_global_extensions = [coc-clangd]`, the outcome is the same because neovim tries to fetch it in the same way to install it.
If I install the plugin through vim-plug (and then run :PlugInstall), I get:
x Post-update hook for coc-clangd ... Exit status: 127

Turns out my company's proxy is blocking https://registry.npmjs.org/
Is there a workaround to avoid fetching the plugins from there?
For instance, if only there was a way to copy the plugins themselves from my workstation, I could transfer them via SCP to the VM and install them manually without the need to fetch from the rpm registry. I don't know if that's even possible

**Comment by humrochagf** [comment]
I just got the same issue here, my workaround hack was to replace all of the occurrences of `https://registry.npmjs.org` with my proxy URL inside the file `build/index.js`.

The plugin is probably ignoring both the `HTTP_PROXY` env var and the `registry` set up to the global npm config in `.npmrc` file.

**Comment by EnricoSteez** [comment]
Yes but that's kinda illegal to do, since I cannot even curl that page nor browse it from my main workstation. It's completely forbidden.
I was wondering if there's a manual way, i.e. "copying stuff"

**Comment by chemzqm** [comment]
`HTTP_PROXY` should be working, use `coc.nvim:registry` in your .npmrc, `:h coc-extensions-npm`

**Comment by chemzqm** [comment]
Go to the folder `echo coc#util#get_data_home()` and do the following:
```sh
mkdir extensions
cd extensions
echo '{"dependencies": {"coc-clangd": ">=0.25.0"}}' > package.json
mkdir node_modules
cp -r /path/to/coc-clangd node_modules
```

**Comment by humrochagf** [comment]
Oh it was in the coc-extensions-npm docs, thanks I was digging code to find the [line about it](https://github.com/neoclide/coc.nvim/blob/fb76b638d317a04403eb2f55dd12fe8b2b8942bd/src/extension/installer.ts#L45) :smile:

**Comment by EnricoSteez** [comment]
Actually I don't have a coc-extensions-npm section in the help, just coc-extensions...
Anyways, @chemzqm /path/to/clangd means that I should clone the repo?

**Comment by humrochagf** [comment]
> 
About the blocking, often is the other way around. Normally is npm that is blocking your company's proxy from reaching them due to the volume of requests.

You can check with your company if they offer any kind of repository manager solution like Artifactory to solve this issue and configure your setup the way @chemzqm said.

Because if your company really doesn't want you using anything from npm then manual copying will be "kind of illegal" as well :stuck_out_tongue_winking_eye:

**Comment by chemzqm** [comment]
> Actually I don't have a coc-extensions-npm section in the help, just coc-extensions...
> Anyways, @chemzqm /path/to/clangd means that I should clone the repo?

Copy the files extracted from npm release

**Comment by EnricoSteez** [comment]
> > Actually I don't have a coc-extensions-npm section in the help, just coc-extensions...
> > Anyways, @chemzqm /path/to/clangd means that I should clone the repo?
> 
> Copy the files extracted from npm release

But I cannot download it from npm `npm i coc-clangd`, I get the same error as it's blocked by the proxy:
reason: unable to verify the first certificate
If I do `cp -r /path/to/clangd node_modules` (and by clangd I mean coc-clangd, the Git Repo), it doesn't work afterwards.

**Comment by EnricoSteez** [comment]
@chemzqm one thing that I could do is to install the plugins on my machine and then push everything to the remote machine. Is that possible? To avoid downloading anything from npm registry.
If so, which folders should I move and which commands (if any) should I run after I copied all the folders?

**Comment by chemzqm** [comment]
See https://github.com/neoclide/coc.nvim/issues/4229#issuecomment-1256611185 you have to find out the way to copy the files to the right place.

**Comment by EnricoSteez** [comment]
I get it. The problem is to GET the files, rather than COPY the files to the right place.
Putting the files in place according to [your comment](https://github.com/neoclide/coc.nvim/issues/4229#issuecomment-1256611185) is not a problem.

**Comment by EnricoSteez** [comment]
I think I will try to download it via `npm i coc-clangd` on my machine and then copy it to the remote machine, and then follow your advice to copy them in the right place
