### ISSUE TITLE
coc list: create empty buffers on location change for preview window

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc.nvim#423]
Reproduce:

- Open call `<Plug>(coc-reference) for a symbol in typescript
- Navigate through list items.

![feb-11-2019 23-58-46](https://user-images.githubusercontent.com/22189661/52571528-0f968300-2e59-11e9-82f3-a4129abe7b37.gif)

Expected:
- Coc list should not create an empty buffer for the preview window.

I think the function `previewLocation` does not work as expected.
Also notice that coc list preview load items to buffers even I'm just circling through the list. How can I disable this behaviour?

I use the default coc-list configuration.

**Comment by ArnaudValensi** [comment]
@sandangel do you have a solution?

I have the same issue, should we re-open?

**Comment by sandangel** [comment]
update to latest fixed for me
