### ISSUE TITLE
Rewrite Frontend Vimscript in Lua

### ISSUE THREAD

**Issue by mikeslattery** [neoclide/coc.nvim#4230]
**Is your feature request related to a problem? Please describe.**
Better performance and possibly better integration wtih Neovim's ecosystem.

**Describe the solution you'd like**
Rewrite coc.nvim in Lua using NeoVim's APIs.   Keep existing Javascript backend and extension ecosystem.

**Describe alternatives you've considered**
Rewrite in Vimscript9 and/or rewrite just a few speed-critical parts.

**Additional context**
This effort could be made a lot easier by leveraging the existing Neovim's native APIs and common library plugins.  The resultant lua code could be a fraction of the current vimscript size (9.7KLOC).

Perhaps, this plugin could become an LSP provider via [null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim), at which point much of this plugins features could be redundant, instead making use of Neovim's internal APIs, tree-sitter, and LSP plugins (e.g. for autocompletion, syntax highlighting, snippets, floating windows, terminal, dialogs, rpc).

Of course, a big downside is that this rewrite would only work on Neovim.

**Comment by kevinhwang91** [comment]
For now, I think only some modules like floatwin and extmark should be rewritten because of the difference in API between Vim and Neovim.

The two modules I mention have covered much of the Vimscript.

**Comment by chemzqm** [comment]
We will not, the logic of coc.nvim runs in a separated node process which can't worked closely with lua plugins.

**Comment by mikeslattery** [comment]
@chemzqm Thanks for the response.  I was only talking about rewriting viml, not any of the javascript.  Are you saying Lua can't do what the viml does?   You know more than I, but that's surprising and hard to beleive.

 I'm asking for my education; I'm okay with closing of this ticket, if that's the right thing to do.

**Comment by chemzqm** [comment]
> Are you saying Lua can't do what the viml does?

No, I mean it does make sense to rewrite all viml code for coc.nvim.

**Comment by mikeslattery** [comment]
I'm confused.  Then why was this ticket closed?   This ticket was only about viml to lua.
