### ISSUE TITLE
Unable to accept completion from dropdown after update

### ISSUE THREAD

**Issue by kelnos** [neoclide/coc.nvim#4231]
## versions

vim version: NVIM v0.7.2
node version: v18.7.0
coc.nvim version: 0.0.82-a315ad6c 2022-09-24 00:13:50 +0800
coc.nvim directory: /home/brian/.dotfiles/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-09-24T00:56:05.953 INFO (pid:1634363) [services] - registered service "languageserver.metals"
2022-09-24T00:56:05.966 INFO (pid:1634363) [coc-git] - Looking for git in: git
2022-09-24T00:56:05.973 INFO (pid:1634363) [plugin] - coc.nvim initialized with node: v18.7.0 after 73ms
2022-09-24T00:56:08.854 INFO (pid:1634363) [attach] - receive notification: showInfo []

## Describe the bug

I just updated coc today (not sure what version I was previously running), and the completion dropdown is no longer working as expected.  Previously, I would start typing, and a dropdown would appear with possible completions.  I could use the up and down arrows to pick a completion, and then hit <enter> to cause the rest of the selected completion to be "typed out" in my editor.  Now when I hit <enter> it doesn't insert any more text, it just inserts a newline as if the completion box wasn't there at all.

I've tried this with both a C source file (coc-clangd) and a rust source file (coc-rust-analyzer), and both exhibit the issue.

Not sure if this is useful, but I have the following coc plugins installed:

```
- ✓ coc-clangd Current version 0.25.0 is up to date.
- ✓ coc-css Current version 1.3.0 is up to date.
- ✓ coc-git Current version 2.5.3 is up to date.
- ✓ coc-html Current version 1.6.1 is up to date.
- ✓ coc-java Current version 1.5.5 is up to date.
- ✓ coc-json Current version 1.6.1 is up to date.
- ✓ coc-kotlin Current version 0.0.9 is up to date.
- ✓ coc-python Current version 1.2.13 is up to date.
- ✓ coc-rust-analyzer Current version 0.68.2 is up to date.
- ✓ coc-tsserver Current version 1.11.11 is up to date.
- ✓ coc-xml Current version 1.14.1 is up to date.
- ✓ coc-yaml Current version 1.8.0 is up to date.
```

And my `coc-settings.json` file contains:

```json
{
  "languageserver": {
    "metals": {
      "command": "metals-vim",
      "rootPatterns": ["build.sbt"],
      "filetypes": ["scala", "sbt"]
    }
  },
  "java.home": "/usr/lib/jvm/zulu8",
  "java.errors.incompleteClasspath.severity": "ignore",
  "python.linting.pylintEnabled": false,
  "python.linting.flake8Enabled": true,
  "python.linting.enabled": true,
  "rust-analyzer.inlayHints.refreshOnInsertMode": true,
  "rust-analyzer.lens.methodReferences": true
}
```

## Reproduce the bug

I have reproduced the issue with the suggested minimal config (my path to `coc.vim` is different, of course):

  ```vim
set nocompatible
set runtimepath^=~/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
  ```
## Screenshots (optional)

n/a

**Comment by chemzqm** [comment]
Custom popup menu is used after 0.0.82, see `:h coc-completion-example` for example

**Comment by kelnos** [comment]
Ah, understood.  Is this called out in some sort of prominent update release note somewhere that's displayed on startup after upgrading?  Seems like a big change to not be loudly called out.  I just looked at the GitHub release notes, and I don't think that would have made me realize I need to take some action.

Otherwise, thanks for the quick reply, and sorry about the noise!

**Comment by chemzqm** [comment]
>  update release note somewhere that's displayed on startup after upgrading? 

There used to be, but people complained as the popup shown every time on vim start, and we can't detect the update event like IDE does.
Follow https://github.com/neoclide/coc.nvim/discussions/3886 for all break changes.
