### ISSUE TITLE
Issue with `workspace/didChangeConfiguration`

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#4235]
## Result from CocInfo

```
vim version: NVIM v0.8.0-dev+57a296d89
node version: v14.20.0
coc.nvim version: 0.0.82-a315ad6c 2022-09-24 00:13:50 +0800
coc.nvim directory: /Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim
term: xterm-kitty
platform: darwin
```

## Describe the bug

change language server settings will send `null` to the server.

![image](https://user-images.githubusercontent.com/5492542/192133543-a215bcc1-9f79-448a-8d5b-d7eac6a6a073.png)

## Reproduce the bug

Open language server output channel, then change the settings section of the language server.

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/192138237-0c93fcdd-0414-42c5-a5f7-a65b01841100.png)


After update to latest release. Change config will send the change but with  a `null` request. Don't know if it is necessary to send a more `null` request.

**Comment by chemzqm** [comment]
Could happen when the configuration feature registered twice.
