### ISSUE TITLE
Show prefix icons in autocomplete window

### ISSUE THREAD

**Issue by TENX-S** [neoclide/coc.nvim#4240]
**Is your feature request related to a problem? Please describe.**
I don't know yet

**Describe the solution you'd like**

https://vi.stackexchange.com/questions/36640/enable-icons-for-nvim-lsp
or
<img width="727" alt="26e978abbe7342ec5083ffeb687f5365" src="https://user-images.githubusercontent.com/40336192/192672074-31dcef24-1a4a-4319-a6dd-85a9d325ed9c.png">

**Comment by chemzqm** [comment]
`:h coc-config-suggest-formatItems`
