### ISSUE TITLE
Question: how to specify a "language-overidable" value in settings?

### ISSUE THREAD

**Issue by nbn22385** [neoclide/coc.nvim#4242]
I was updating my config from `semanticTokens.filetypes` to `semanticTokens.enable` and would like to enable this for only one language (`cpp`). 

Old:
``` jsonc
  "semanticTokens.filetypes": ["cpp"],

```

New:
``` jsonc
  "semanticTokens.enable": true, // Want to specify language(s)
```

I see that many settings are "language-overridable" but I don't know how to set this in the `coc-settings.json` file. Any help is appreciated.

```
"semanticTokens.enable"					*coc-config-semanticTokens-enable*

	Enable semantic tokens support.

	Scope: `language-overridable`, default: `false`
```

**Comment by chemzqm** [comment]
See https://github.com/neoclide/coc.nvim/discussions/4185
