### ISSUE TITLE
Ignore LS with missing command/module

### ISSUE THREAD

**Issue by heftig** [neoclide/coc.nvim#425]
I have several machines sharing the same CoC config, but with different language servers installed.

It would be nice if I could configure CoC to ignore missing servers without printing an error message.

**Comment by chemzqm** [comment]
It's feature, you can use `coc#config()` to dynamic regist language server configuration.
See `:h coc#config()`

**Comment by chemzqm** [comment]
Set `g:coc_user_config` if you can't use that function in vimrc.

**Comment by heftig** [comment]
For posterity:

To do this, disable the custom languageserver in the static config (`"enable": false`) like:

```json
{
    "languageserver": {
        "ccls": {
            "enable": false,
            "command": "ccls",
            "filetypes": ["c", "cpp", "cuda", "objc", "objcpp"],
            "initializationOptions": {
                "cacheDirectory": "/var/tmp/ccls-cache"
            },
            "revealOutputChannelOn": "never"
        }
    }
}
```
and enable it in an `*-after.vim` script like:
```vim
if executable('ccls')
    call coc#config('languageserver.ccls.enable', v:true)
endif
```
