### ISSUE TITLE
signature disappear when pressing space

### ISSUE THREAD

**Issue by zdszero** [neoclide/coc.nvim#4250]
## Describe the bug

This problem appears in lastest coc. When I checkout to previous coc commit, the bug disappears

When I input `,`  the signature popup window appears as expected.

![image](https://user-images.githubusercontent.com/49243215/193398326-e134e25e-b561-488f-b745-b5dd7765e6b8.png)

Then I press `<space>`, the signature popup window disappears

![image](https://user-images.githubusercontent.com/49243215/193398380-bc61cf5d-9760-4e5a-a00e-29ee2a8142b7.png)

## Reproduce the bug

my `coc-settings.json`

  ```vim
{
    "signature.enable": true,
    "signature.target": "float"
}
  ```

there is no extra settings about signature

**Comment by nullromo** [comment]
I'm having the same issue. Can you elaborate on how you fixed this please?

**Comment by fannheyward** [comment]
It's expected, language server will register triggerCharacter for signtaturehelp to be fired.

Here is clangd's triggerCharacter: `"triggerCharacters": [ "(", ")", "{", "}", "<", ">", "," ]`, `<space>` won't trigger signatureHelp.

**Comment by nullromo** [comment]
I have been using coc for over a year and the signature help never used to disappear after typing `myFunc(foo,<space>`, so I would say this new behavior is certainly unexpected. Yes, the help should _appear_ only when typing a trigger character, but I don't think it should _disappear_ after typing a space right after the comma. I'm fairly certain it is common practice to include spaces between arguments in function calls for most languages.

### Type everything up to the comma
![image](https://user-images.githubusercontent.com/8991581/194107580-0dc2e349-d530-459a-96e2-9f12b53e7828.png)

### After typing the space
![image](https://user-images.githubusercontent.com/8991581/194107635-5885ef93-ebef-450e-a752-24bc748806dc.png)

**Comment by nullromo** [comment]
The fix is implemented correctly. Great work and thanks!
