### ISSUE TITLE
coc#pum functions doesn't work properly in nvim 0.8

### ISSUE THREAD

**Issue by carlosala** [neoclide/coc.nvim#4251]
## Result from CocInfo

```
## versions

vim version: NVIM v0.8.0
node version: v16.16.0
coc.nvim version: 0.0.82-93852e6c 2022-09-30 21:54:52 +0800
coc.nvim directory: /home/carlo/.local/share/nvim/site/pack/packer/start/coc.nvim
term: xterm-kitty
platform: linux
```
## Describe the bug

Triggering the following maps end on adding a `<80>` and get nvim stuck for some seconds. This doesn't happen in nvim `0.7.2`, latest one before `0.8`.

```lua
vim.keymap.set("i", "<C-Space>", "coc#pum#visible() ? coc#pum#stop() : coc#refresh()", { expr = true, noremap = true, silent = true })
vim.keymap.set("i", "<Tab>", "coc#pum#visible() ? coc#pum#next(1) : '<Tab>'", { expr = true, noremap = true, silent = true })
vim.keymap.set("i", "<S-Tab>", "coc#pum#visible() ? coc#pum#prev(1) : '<C-h>'", { expr = true, noremap = true, silent = true })
vim.keymap.set("i", "<CR>", "coc#pum#visible() ? coc#pum#confirm() : '<C-g>u<CR>'", { expr = true, noremap = true, silent = true })
```

Any other keymap to execute a `coc#pum` function have the same result, for example, one easier:
```lua
vim.keymap.set("i", "<CR>", "coc#pum#confirm()", { expr = true, noremap = true, silent = true })
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with:

That one is enough just adding those keymaps from above!
  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

https://asciinema.org/a/Dm9vFe6WknIzqN7JQhGj9Z1eu

**Comment by chemzqm** [comment]
Bug with neovim's lua configuration, the viml key-mappings work as expected.

**Comment by chemzqm** [comment]
Same issue with other nvim pluign.

**Comment by carlosala** [comment]
For anyone facing this, adding `replace_keycodes = false` in options!

**Comment by clotodex** [comment]
@carlosala how do I do that? (Might be a stupid question)
If I add it to the opts table, the behavior is still broken, and afaik their is no global vim option replace_keycodes
```
local opts = {silent = true, noremap = true, expr = true, replace_keycodes = false}
keyset("i", "<TAB>", 'coc#pum#visible() ? coc#pum#next(1) : v:lua.check_back_space() ? "<TAB>" : coc#refresh()', opts)
keyset("i", "<S-TAB>", [[coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"]], opts)
```

**Comment by carlosala** [comment]
for the last one, you don't need that \

**Comment by clotodex** [comment]
@carlosala sadly it is still not working (removing the slashes did not help & FYI the lua example config should be adapted then)

**Comment by carlosala** [comment]
What does keyset means there? Which is the function defining?

**Comment by clotodex** [comment]
`local keyset = vim.keymap.set`
Like in the example config https://github.com/neoclide/coc.nvim/blob/release/Readme.md

**Comment by richardwzp** [comment]
I had similar issue with this, and it ended up being a plugin conflict. If setting `replace_keycodes` does not work, run `:verbose inoremap <silent><expr> <CR>` in your neo-vim, and see if there's anything other than `coc` that pops up. For me it's the damn pear-tree plugin.
