### ISSUE TITLE
Javascript entry not found

### ISSUE THREAD

**Issue by asnahu** [neoclide/coc.nvim#4252]
system environments:
- MacOS 
- NVIM v0.7.2
- node: stable 18.10.0 (bottled), HEAD

Errors:
`coc: health
========================================================================
  - OK: nvim version satisfied
  - OK: Environment check passed
  - ERROR: Javascript entry not found, please compile coc.nvim by esbuild.
  - ERROR: service could not be initialized
    - ADVICE:
      - Use command ":messages" to get error messages.
      - Open a issue at https://github.com/neoclide/coc.nvim/issues for feedback.
`

when reinstall coc.vim will get some errors like `4_nvim_cb`. how to solve this problem?

**Comment by chemzqm** [comment]
See https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L116
