### ISSUE TITLE
<C-c> during CocLists fuzzy search sets insert mode cursor semi-permanently

### ISSUE THREAD

**Issue by thisisrandy** [neoclide/coc.nvim#4261]
## Result from CocInfo

vim version: NVIM v0.7.2
node version: v16.17.1
coc.nvim version: 0.0.82-354c751a 2022-10-01 23:51:05 +0800
coc.nvim directory: /home/randy/.local/share/nvim/plugged/coc.nvim
term: tmux-256color
platform: linux

## Describe the bug

During a CocList fuzzy search, if the user presses `<C-c>` to leave the search, the cursor in the open buffer remains as the insert mode cursor (thin line instead of the normal mode block cursor). This persists even when insert mode is entered and left, and even if one exits vim back to the terminal. Restarting vim restores the normal mode cursor, as does viewing another CocList and pressing `<Esc>`.

## Reproduce the bug

1. Type `:CocList extensions` (any list will do)
2. Type `<C-c>`
3. Observe that the cursor is now the insert mode cursor, even though you are in normal mode.

## Screenshots (optional)

![coc-nvim-cursor](https://user-images.githubusercontent.com/22106562/193980348-a4b1ae9d-239b-4767-8014-02b892712fd8.gif)

**Comment by fannheyward** [comment]
You should avoid to use `<C-c>` to cancel because `C-c` just stop and won't trigger autocmd event, may cause some unexpected effects.

**Comment by thisisrandy** [comment]
@fannheyward I understand that, but don't you think this warrants any investigation? I'm not aware of any other plugin that, when canceled using `<C-c>`, changes the cursor. Also, using `<C-c>` as a preferred way to cancel is not unprecedented. The widely-used [fzf.vim](https://github.com/junegunn/fzf.vim) correctly exits on `<C-c>` but awkwardly leaves insert mode but stays focused on `Esc`.

**Comment by thisisrandy** [comment]
@chemzqm That looks great, thanks.
