### ISSUE TITLE
Adopt JSON5 for configurations

### ISSUE THREAD

**Issue by mamins1376** [neoclide/coc.nvim#4264]
**Is your feature request related to a problem? Please describe.**
It's not precisely a problem, but a good improvement on user experience.

**Describe the solution you'd like**
Using [JSON5](https://json5.org) for hand-written configurations (like `:CocConfig`) will ease configuration, like having comments or being a bit less strict on the syntax. Refer to the link for the benefits.

**Describe alternatives you've considered**
Currently, `jsonc` is being used, which is a superset of `json` but just with comments and nothing more, like trailing commas or anything like that. Since JSON5 can be considered as a superset of `jsonc` (I suppose), there won't be any breaking changes.

**Additional context**
None.

**Comment by chemzqm** [comment]
> At the very least it would be nice to go back to the old jsonc that allowed trailing commas.

Need fix coc-json for the languageId used by coc-settings.json.

**Comment by chemzqm** [comment]
Trailing commas support have come back.
Seems the json5 parser missing something we use from `jsonc-parser`, including visitor API and errors report.
