### ISSUE TITLE
i can not format whole json buffer. 

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [neoclide/coc.nvim#427]
sorry to ask this question, but i can't format whole json file with CocAction('format'). i have installed coc-json and the buffer filetype is json, i get ` provider not found for current document` info.
by the way, `vmap <leader>f  <Plug>(coc-format-selected)` works fine.

**Comment by chemzqm** [comment]
It's expected, because json language server doesn't support it, it's same code of VSCode's json extension.

**Comment by chemzqm** [comment]
I can add support for it.

**Comment by FinallyFinancialFreedom** [comment]
> I can add support for it.

thanks, it would be great if you support this feature.
I hope there is a consistent way to format all file types.

**Comment by chemzqm** [comment]
Fixed, upgrade coc-json
