### ISSUE TITLE
Notify extensions if coc detach 

### ISSUE THREAD

**Issue by kevinhwang91** [neoclide/coc.nvim#4271]
**Is your feature request related to a problem? Please describe.**
The command provided by extension may be invoked during restarting and get `Plugin not ready` error.

**Describe the solution you'd like**
Invoke `disposeAll(subscriptions)` at the end of detach.

**Comment by chemzqm** [comment]
> `Plugin not ready` error.

Only happens when send request to coc.nvim, it's generally bad idea to send request, the extension should use api instead.

**Comment by kevinhwang91** [comment]
There're some stateful resources in Lua if the coc extension is initialized and the extension exposes a command.
Lua will request the command to a coc extension if some Neovim events are fired. 
However, coc restarts without notifying the extensions, and the resources in Lua can't be disposed.
Because the stateful resources exist on the Lua side,  it misunderstands the coc extension is working even if coc is restarting.

**Comment by chemzqm** [comment]
The request to coc.nvim should check `g:coc_service_initialized`
