### ISSUE TITLE
How to set the syntax highlight or filetype on popup preview of custom source

### ISSUE THREAD

**Issue by disanman** [neoclide/coc.nvim#4281]
Hello, thanks a lot for this awesome plugin!

I am setting up a [custom source](https://github.com/neoclide/coc.nvim/wiki/Create-custom-source) and I noticed you can return the field *info* (as described in `:h complete-items`). The text passed in that *info* field will be displayed in a preview pop-up. But the issue is that the result is displayed as just plain text, I would like to set the filetype or syntax of that preview window to for example Markdown. Is there a way to do that? 

I saw a similar issue [here](https://github.com/neoclide/coc.nvim/issues/1704), but its not about custom sources.

Thanks a lot for your help!

A sample code:
```vim
function! coc#source#mysource#init() abort
  return {
        \ 'priority': 9,
        \ 'shortcut': 'mysource',
        \ 'triggerCharacters': ['|']
        \}
endfunction

function! coc#source#mysource#complete(opt, cb) abort
    let items = [{'word': 'option1_with_markdown', 'info': '# This should be a markdown title \nand this some code:```python\nprint("Hello")\n```'}, 'option2_plain_text']
  call a:cb(items)
endfunction
```
And this is what is displayed in the popup when selecting the first option:
<img width="1406" alt="Screenshot 2022-10-12 at 07 55 50" src="https://user-images.githubusercontent.com/35890571/195261608-08e14caa-5a32-4d1d-bba9-1d0b99197458.png">

**Comment by fannheyward** [comment]
coc.nvim 0.0.82 uses custom completion menu instead of native completion menu, there's no highlighting for custom source for now.

**Comment by fannheyward** [comment]
Test this:

```
  let items = [{'word': 'option1_with_markdown', 'documentation': [{'filetype': 'markdown', 'content': '# This should be a markdown title \\nand this some code:```python\\nprint("Hello")\\n```'}]}]
```

There's something broken in markdown rendering, still debugging on this.

**Comment by disanman** [comment]
hey @fannheyward, It actually worked! 

I was just having another issue with the line breaks and the use of single quotes: didn't know in VimL for the line breaks to work, the string should be defined in double quotes:
```vim   
let items = [{'word': 'option1_with_markdown', 'documentation': [{'filetype': 'markdown', 'content': "# This should be a title \n\rand this some code:\n```python\nprint('Hello')\n```"}]}]
```
<img width="762" alt="Screenshot 2022-10-13 at 10 05 03" src="https://user-images.githubusercontent.com/35890571/195538917-3cd8ee9d-55d1-4376-9176-e4d5b9bfb235.png">

Thanks a lot for your help.
