### ISSUE TITLE
set filetype_map dynamically

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#4282]
```
g:coc_filetype_map					*g:coc_filetype_map*

	Map for document filetypes so the server could handle current document
	as another filetype, example: >

	let g:coc_filetype_map = {
		\ 'html.swig': 'html',
		\ 'wxss': 'css',
		\ }
<
	Default: {}


Filetype map:~
							*coc-document-filetype*

Some filetypes are mapped to others to match the languageId used by VSCode,
including:

- javascript.jsx -> javascriptreact
- typescript.jsx -> typescriptreact
- typescript.tsx -> typescriptreact
- tex -> latex

Use |g:coc_filetype_map| to create additional filetype maps.

Use `:CocCommand document.echoFiletype` to echo mapped filetype of current
document.
```

For some filetype, e.g., liquid, it is a template language to generate html/css/json/etc.
[tpope/vim-liquid](https://github.com/tpope/vim-liquid) will set `b:liquid_subtype` to `html`/`css`/`json`/etc.
How to set it dynamically? Thanks.

## Describe the solution you'd like

```vim
" ~/.config/nvim/ftplugin/liquid.vim
let b:coc_filetype = b:liquid_subtype
```

## Alternative Solution

```vim
	let g:coc_filetype_map = {
		\ 'liquid': '%{get(b:, "liquid_subtype", "html")}',
		\ }
```

## Similar Problem

<https://github.com/nvim-treesitter/nvim-treesitter/discussions/3628#discussioncomment-3857484>

**Comment by fannheyward** [comment]
No such feature yet, may be we can add this in `convertFiletype`:

https://github.com/neoclide/coc.nvim/blob/e1d9f74265a9082901d2623e95ca128a1b801c25/src/model/document.ts#L145-L160

**Comment by chemzqm** [comment]
The language server won't work as expected on such case, you will need notebook document support https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notebookDocument_synchronization
