### ISSUE TITLE
How to turn off filename completion for certain filetype?

### ISSUE THREAD

**Issue by huweiATgithub** [neoclide/coc.nvim#4285]
When working with LaTex, `\\` is often used as a new-line symbol. Therefore, it is quite often to type: `\\<CR>` in a sequence.

But then, in Windows, `\\` will have the auto-completion window pop-up. Then, `<CR>` will accept the first completion which is not what we wanted.

Besides, it is quite rare to write a filename in LaTex. The best solution might be disabling filename completion for filetype `tex`.

**Comment by huweiATgithub** [comment]
It is the `file` source that provides completion for filenames.
In  `coc.source.file.*` from the [schema](https://github.com/neoclide/coc.nvim/blob/master/data/schema.json), I had no idea if those options are related to filetypes filter.

**Comment by fannheyward** [comment]
No such feature yet, you can change `coc.source.file.triggerCharacters` to remove `\\` for now.

**Comment by huweiATgithub** [comment]
OK. but then that will turn off `\\` for all types.
I might take a look. This might be an almost-ready feature? e.g. the [coc-vimtex](https://github.com/neoclide/coc-vimtex) has option `coc.source.vimtex.filetypes`.

**Comment by chemzqm** [comment]
This is filetypes support, but whitelist only, need fix the json schema support.
```json
  "coc.source.file.filetypes": ["vim", "javascript"],
```
