### ISSUE TITLE
build/index.js not found, please install dependencies and compile coc.nvim by: yarn install

### ISSUE THREAD

**Issue by OmniQuarck** [neoclide/coc.nvim#4292]
Everytime I open Neovim, I get this error. I was wordering if someone could help me pls?
<img width="819" alt="Screen Shot 2022-10-15 at 8 27 27 PM" src="https://user-images.githubusercontent.com/112669750/196012553-6b434fbd-f4a3-46dd-b7e4-47779bc37463.png">

**Comment by fannheyward** [comment]
You didn't install coc.nvim successfully, use `release` branch is recommend. If you want you use `master` branch, make sure you have yarnpkg installed. Check https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#add-cocnvim-to-vims-runtimepath

**Comment by chemzqm** [comment]
> I installed the release branch

When you get that message, it means you're not using release branch or the necessary javascript file was moved.

**Comment by tvannahl** [comment]
FYI: I ran into the same issue after upgrading my plugins.

I'm using the package manager `dein` and it seem the configuration there did change.

I did remove my current installation of coc from my dein cache and adjusted the configuration as follows:

```diff
-  call dein#add('neoclide/coc.nvim', {'branch': 'release'})
+  call dein#add('neoclide/coc.nvim', {'rev': 'release'})
```

It fixed the issue for me.

**Comment by troystauffer** [comment]
I was using Vundle, which as far as I can tell ignores the specified branch/rev. Once I switched to vim-plug, this error went away.
