### ISSUE TITLE
no HieAst exist for file

### ISSUE THREAD

**Issue by ehzawad** [neoclide/coc.nvim#4301]
## Result from CocInfo

[coc.nvim] Error condition, please check your setup and/or the [issue tracker](h
ttps://github.com/haskell/haskell-language-server/issues): 
**no HieAst exist for file**

## Describe the bug
The weird thing is that when I have hie.yaml generated by **hie-implicit,**  in that case no error but NO auto completion.

````yaml
cradle:
  stack:
````

  ```json
{
  "languageserver": {
    "haskell": {
      "command": "haskell-language-server-wrapper",
      "args": ["--lsp"],
      "rootPatterns": [ "*.cabal", "stack.yaml", "cabal.project", "package.yaml", "hie.yaml" ],
      "filetypes": ["haskell", "lhaskell"],
      "settings": {
        "haskell": {
          "checkParents": "CheckOnSave",
          "checkProject": true,
          "maxCompletions": 40,
          "formattingProvider": "ormolu",
          "plugin": {
            "stan": { "globalOn": true }
          }
        }
      }
    }
  }
}

  ```

**Comment by fannheyward** [comment]
> no HieAst exist for file

This error is came from haskell-language-server, coc.nvim as client side can do nothing about this.
