### ISSUE TITLE
Additional semantic token highlight groups

### ISSUE THREAD

**Issue by caro0071** [neoclide/coc.nvim#4304]
I just moved from ccls to running coc-clangd with semantic token highlighting and found that now I don't get any distinction between global variables and local variables.  It also highlights constexpr variables as normal variables (with readonly modifier) highlighted with CocSemVariable.

It seems that the appropriate information is already available, `:CocCommand semanticTokens.inspect` shows scope and readonly.  Is it possible to create separate highlight groups based on some of the modifiers?

Minimally I would like to handle read-only variables as constants and have a separate highlight group for global scope variables (could simply add bold similar to how CocSemDeprecated adds strikethrough).

**Comment by chemzqm** [comment]
You can define highlight groups `CocSem[Kind][Modifier]`, see `:h CocSem` for example.
