### ISSUE TITLE
How to write SAFE confirm onEnter function for Coc?

### ISSUE THREAD

**Issue by ProgrammingLife** [neoclide/coc.nvim#4312]
**Is your feature request related to a problem? Please describe.**
I want to use Enter key as a confirm key. So I used this line from the Coc documentation (main page here on github):
```
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```
It works only when Coc is started. But I don't start it on large TXT files, etc. So this line doesn't work because coc#pum#visible is not declared.

More details:
```
	Plug 'neoclide/coc.nvim', { 'branch': 'release', 'for': [ 'typescript', 'javascript', 'html', 'cs', 'dart', 'gd', 'godot', 'yaml', 'python', 'rust', 'sh' ] }
```

**Describe the solution you'd like**
My failed attempt is that:
```
function! s:SafeCocConfirm()
	if !exists('*CocTagFunc') | return "\<CR>" | endif
	" return pumvisible() ? coc#pum#confirm() : "\<CR>"
	" return pumvisible() ? "\<C-g>u\<CR>\<c-r>=coc#on_enter()" : "\<CR>"
	" return pumvisible() ? "\<c-r>=coc#on_enter()" : "\<CR>"
	return pumvisible() ? coc#pum#confirm()
                         \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
endfunction

inoremap <silent><expr> <CR> <SID>SafeCocConfirm()
```

**Describe alternatives you've considered**
How to create safe working function of Coc Confirm when it's already loaded whithout replacing cursor on new line? I wanna cursor to stay in-place after confirming.

**Additional context**
n/a

**Comment by chemzqm** [comment]
```vim
inoremap <silent><expr> <CR> pumvisible ? "\<C-y>" : coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```
should works
