### ISSUE TITLE
Coc Auto complete not working correctly

### ISSUE THREAD

**Issue by Drew138** [neoclide/coc.nvim#4314]
## Result from CocInfo

![image](https://user-images.githubusercontent.com/58788781/197318601-a9e40cf9-c44e-4e18-8efc-54435906e540.png)

## Describe the bug

Coc auto complete is not working correctly whenever I try to trigger it via keymap. It is instead auto completing with the characters <80>.
my current keymap for auto completion is as follows.

```lua
vim.keymap.set('i', '<Tab>', 'coc#pum#visible() ? coc#pum#confirm() : "<Tab>"', { silent = true, expr = true })
```

other coc related config can be found here: https://github.com/Drew138/.dotfiles/blob/main/.config/nvim/lua/extensions/coc.lua

## Reproduce the bug

press tab on an auto completion suggestion.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/58788781/197319036-cb7bcc84-01e3-4b88-8310-3156f47d5a68.png)

**Comment by fannheyward** [comment]
Add `replace_keycodes = false` to your key mapping's option. Check README for example.

**Comment by Drew138** [comment]
It worked, Thanks a lot :)
