### ISSUE TITLE
Arrow keys not working in insert mode since the last release ( v0.0.82)

### ISSUE THREAD

**Issue by edilson258** [neoclide/coc.nvim#4316]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
You may need update your key-mappings, see `:h coc-completion`

**Comment by edilson258** [comment]
Still not working

**Comment by chemzqm** [comment]
I see, should be something wrong on your vim.

**Comment by chemzqm** [comment]
Tried vim 9000750, but can't reproduce.

**Comment by curkan** [comment]
Same problem

**Comment by chemzqm** [comment]
Make sure use `replace_keycodes = false` if you're using lua configuration for expr key-mappings.

**Comment by chemzqm** [comment]
Can't reproduce, you can remap `<up>` and `<down>` in your vimrc  to avoid this issue.

**Comment by curkan** [comment]
I had to disable mappings.
```
inoremap <silent> <expr> <up> <Up>
inoremap <silent> <expr> <down> <Down>

```
of course, now the selection through the arrows does not work, but it's better than inserting unnecessary messages

**Comment by fantonangeli** [comment]
@curkan @edilson258 
I had the same issue.
Running `:verbose imap <Up>` I saw a conflict with the plugin `vim-autoclose`.
Removing that plugin, everything works perfectly.

**Comment by edilson258** [comment]
THANKS IT WORKED.
 I removed vim-autoclose and everything worked well

**Comment by flimofly** [comment]
Same here. Removing the autoclose plugin (command 'PlugClean') did the job.
