### ISSUE TITLE
Freezing for a while after completion has shown

### ISSUE THREAD

**Issue by NSLog0** [neoclide/coc.nvim#432]
**Result from CocInfo**
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct  3 2018 05:42:35)
node version: v8.9.0
coc.nvim version: 0.0.52
term: iTerm.app
platform: darwin

## Error messages

## Output channel: prettier

## Output channel: solargraph
Solargraph is listening on stdio PID=33985
warning: parser/current is loading parser/ruby25, which recognizes
warning: 2.5.1-compliant syntax, but you are running 2.5.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
[ANY] Solargraph initialized (6.378046000143513 seconds)
```

**Describe the bug**
While I'm typing code sometime when a completion has shown down, Vim is freeze for 5s. 

**Screenshots**
<img width="1186" alt="screen shot 2562-02-13 at 11 11 49" src="https://user-images.githubusercontent.com/1640817/52686465-66e34300-2f80-11e9-869b-92733ef96a15.png">

**Comment by NSLog0** [comment]
### Update:
 I noticed once a completion show with `[B]` then vim will be always freeze

**Comment by chemzqm** [comment]
Consider upgrade your coc.nvim, and checkout https://github.com/neoclide/coc.nvim/wiki/F.A.Q

**Comment by chemzqm** [comment]
Make sure you don't use `CocAction` with your autocmds like `CursorHoldI` `TextChangedI` `CursorMovedI`
