### ISSUE TITLE
This simple JS code breaks CoC highligting

### ISSUE THREAD

**Issue by ProgrammingLife** [neoclide/coc.nvim#4320]
## Result from CocInfo
```
vim version: NVIM v0.5.0-dev+1122-g8f4b9b8b7
node version: v17.0.1
coc.nvim version: 0.0.82-a0fd4ae1 2022-10-15 23:50:48 +0800
coc.nvim directory: /home/denis/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux
```

## Describe the bug
Seems CoC works bad with regexps

## Reproduce the bug
This simple line:
```
const str = "test".replace( /"/g, "&quot;" );
```
breaks all the highlighting of the JS file til its end.
There is some issue with: **"** symbol.

## Screenshots (optional)
n/a

**Comment by fannheyward** [comment]
Can you post a screenshot of your code? I didn't find any highlighting breaks in my test:

<img width="418" alt="截屏2022-10-23 11 06 44" src="https://user-images.githubusercontent.com/345274/197371373-82bd9112-7558-4146-a073-fbf44a65e5ef.png">

**Comment by chemzqm** [comment]
Syntax highlights are provided by your syntax plugins, not coc.nvim
