### ISSUE TITLE
Resizing coc-list for coc-references is temporary and forgotten

### ISSUE THREAD

**Issue by gwpl** [neoclide/coc.nvim#4322]
**Is your feature request related to a problem? Please describe.**

* I open references for a symbol with `<gr>`...
* then I resize windows/views with mouse,
* as soon as I move to another reference (using [up]/[down]) sizes of windows revert

**Describe the solution you'd like**

I would love it to remember sizes that I set with mouse at least for this references search. 
(next `<gr>` shall start from safe defaults)

**Describe alternatives you've considered**
probably there are ways to configure sizes from keyboard, but unfortunately I couldn't find how.

**Comment by chemzqm** [comment]
Use `:h coc-config-list-height` to change the default height of CocList

**Comment by chemzqm** [comment]
Added `height` option to CocList, you can make use of that option, see `:h CocLocationsChange`
