### ISSUE TITLE
Suggested ways to add support for a non-standard LSP RPC method ("textDocument/compose")?

### ISSUE THREAD

**Issue by YangchaoYi** [neoclide/coc.nvim#4323]
**Is your feature request related to a problem? Please describe.**
I have a language server which support an extra non-standard LSP RPC method "textDocument/compose" whose request & response format is identical to "textDocument/completion". The only difference is the RPC method name. 

**Describe the solution you'd like**
Ideally, whenever the completion action is triggered, coc.nvim can
1. send both "textDocument/completion" and "textDocument/compose" to the server.
2. merge their response.
3. show the merged response in the completion list.

**Describe alternatives you've considered**
I was thinking about writing a small extension to achieve that. Several options in my mind:
1. Adding an RPC call in the clientOptions.middleware.provideCompletionItems function. But I'm not sure how to do that.
2. Implement my own `CompletionItemFeature` and calls 
  ```    
  client.registerFeature(new CompletionItemFeature(this), 'completion')
  ```
  But it seems many dependencies of `CompletionItemFeature` are not exposed.

**Additional context**
I'm still pretty new to both javascript and this plugin and I might have missed some obvious solutions so I'd like some suggestions/directions about how I can add such support.

**Comment by fannheyward** [comment]
I prefer to use `middleware`, check https://github.com/fannheyward/coc-rust-analyzer/blob/master/src/client.ts#L79 (it's not provideCompletionItems, but provideHover)

1. call `next` to request `textDocument/completion`
2. RPC to your `textDocument/compose`
3. merge results

**Comment by chemzqm** [comment]
You have to use the middleware of LanguageClient or use the API`langauges.registerCompletionItemProvider` for custom completion source, coc.nvim doesn't support non-standard LSP method itself.

**Comment by YangchaoYi** [comment]
Thanks for the help! Using middleware works well :)
