### ISSUE TITLE
rg搜索经常卡死

### ISSUE THREAD

**Issue by sunxin18** [neoclide/coc.nvim#4326]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
1. vim or nvim? what's the version?
2. Windows or Linux or macOS?

**Comment by chemzqm** [comment]
如何操作的你都不说，如果你不会提问或者懒得打字，以后别在 issues 里面浪费他人时间
