### ISSUE TITLE
Disable automatically inserting function parameters

### ISSUE THREAD

**Issue by petersohn** [neoclide/coc.nvim#4331]
**Is your feature request related to a problem? Please describe.**
For example, I have a function `void foo(int x)`. When I autocomplete the function, coc will automatically insert the parameter(s) and the closing parenthesis. However, if I want to continue editing, I have to move past the closing parenthesis, which disrupts my workflow. What's wore, if there are multiple parameters, the other parameters are left there and I have to manually delete them.

The feature works in Visual Studio because when you keep typing, it automatically replaces the placeholders. If you press `)`, it will move past the closing parenthesis instead of inserting a new one. If you press `,`, it moves past the comma and selects the content of the next parameter, which will be automatically replaced. It can be problematic even in VS, because if I do any other editing then typing, all those placeholders will be left there. COC, however does none of it, which makes the feature completely unusable.

**Describe the solution you'd like**
I do not need this feature, I want an option to turn it off. When I auto-complete a function, only the opening parenthesis should be inserted.

**Describe alternatives you've considered**
I considered filing a bug report to fix this feature, but I'd be better off without it.

**Comment by chemzqm** [comment]
>  coc will automatically insert the parameter(s) and the closing parenthesis

**Comment by chemzqm** [comment]
You can use `coc#pum#insert` instead.
