### ISSUE TITLE
coc-diagnostic-prev and coc-diagnostic-next should maybe add the current position to the jump list

### ISSUE THREAD

**Issue by adriafarres** [neoclide/coc.nvim#4332]
**Is your feature request related to a problem? Please describe.**
Hello. I'm opening this as discussion more than a request. I noticed that these commands

```
<Plug>(coc-diagnostic-prev)
<Plug>(coc-diagnostic-next)
```
do not add to the jump list the position the cursor is in before jumping. In other words, if you are at a certain position *x* and jump to a highlighted diagnostic line with one of the aforementioned commands, upon pressing Ctrl+o you don't come back to *x*. Do we want to keep the behavior like that?

**Comment by chemzqm** [comment]
You can do that in the callback of `CocActionAsync` function.

**Comment by adriafarres** [comment]
Thank you for the reply, @chemzqm. I don't know if that's an idiomatic way to do that, but I ended up mapping them as follows:

```
m'<Plug>(coc-diagnostic-prev)
m'<Plug>(coc-diagnostic-next)
```
