### ISSUE TITLE
Rename a file and update all references.

### ISSUE THREAD

**Issue by ElcomJ** [neoclide/coc.nvim#4336]
Good morning, I recently discovered the `:CocSearch` command, which can rename something in several files at once, and I just love it.

However, I wonder if there is a way to rename a file as `foo.py` and update the new name in the other files where it is referenced.

I see the same question in the issue #1135, I decided to test the `:CocCommand workspace.renameCurrentFile` command and it didn't work as it should.

**Comment by chemzqm** [comment]
It's supported by coc-tsserver with watchman installed in your $PATH, other language servers can support it by send workspace edits to coc.nvim.

**Comment by ElcomJ** [comment]
I read about this also in #1135 , but I work with python.

I don't know if there is a way to do this functionality, but is there a way to get `:CocSearch` to accept files like ` foo.py` in its search engine and rename other files like it does other words?

**Comment by chemzqm** [comment]
It can't, that would require to analyze code which should be the job of language server.

**Comment by fannheyward** [comment]
The language server need to implement `willRenameFiles` or `didRenameFiles`. https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles
