### ISSUE TITLE
E109: Missing  ':' after '?'

### ISSUE THREAD

**Issue by Poyso** [neoclide/coc.nvim#4337]
Whenever i press enter to complete a key through the popup menu, this error comes up.

I have just installed the plugin and insert the "Example vim configuration" in my .vimrc.

![ss](https://user-images.githubusercontent.com/72195084/199231107-c4cb2f1c-dd8e-467b-8f4d-fa70b7ba6dc3.png)

**Comment by chemzqm** [comment]
Bad copied configuration, check your vimrc.
