### ISSUE TITLE
Unable to switch from master to release branch - breaks vim-plug installations

### ISSUE THREAD

**Issue by michaelrommel** [neoclide/coc.nvim#4339]
## Environment info
macOS Ventura 13.0 on Apple Silicon
git version 2.37.1 (Apple Git-137.1)
Filesystem: Mac OS Extended (Journaled)
coc.vim version: commit a182d957e9643b0d79d6da918230e899be7ec1c9 (HEAD -> master, origin/master, origin/HEAD)

## Describe the bug

vim plug installation can specify the branch to checkout.

Even if I try to checkout this branch manually, it does not work. Probably because of filesystem differences regarding case sensitivity.
If I remove the offending file, I can checkout the branch. I do not know, how this can be corrected or how it was produced in the first place.

## Reproduce the bug

```
❯ mkdir tmp
❯ cd tmp
❯ git clone https://github.com/neoclide/coc.nvim
Cloning into 'coc.nvim'...
remote: Enumerating objects: 50033, done.
remote: Counting objects: 100% (50033/50033), done.
remote: Compressing objects: 100% (11535/11535), done.
remote: Total 50033 (delta 36200), reused 49921 (delta 36182), pack-reused 0
Receiving objects: 100% (50033/50033), 55.12 MiB | 13.44 MiB/s, done.
Resolving deltas: 100% (36200/36200), done.
❯ cd coc.nvim
❯ git checout release
WARNING: You called a Git command named 'checout', which does not exist.
Continuing in 0.1 seconds, assuming that you meant 'checkout'.
error: The following untracked working tree files would be overwritten by checkout:
	Readme.md
Please move or remove them before you switch branches.
Aborting
❯ git checkout release
error: The following untracked working tree files would be overwritten by checkout:
	Readme.md
Please move or remove them before you switch branches.
Aborting
❯ ls -la README.md
-rw-r--r--@ 1 rommel  staff  93315 Nov  2 15:54 README.md
❯ ls -la Readme.md
-rw-r--r--@ 1 rommel  staff  93315 Nov  2 15:54 Readme.md
❯ rm Readme.md
❯ git checkout release
branch 'release' set up to track 'origin/release' by rebasing.
Switched to a new branch 'release'
```

**Comment by chemzqm** [comment]
Use `git reset head --hard` to clean up, don't use that command on project your're working at.

**Comment by michaelrommel** [comment]
Thanks for the quick response! Just for completeness: it is actually tied to a case-insensitive filesystem.

I cloned the latest version again on
1. a case insensitive APFS filesystem (as opposed to HFS+): fails with the same error, the `git reset head --hard` did not make any change
2. on a case sensitive HFS+ filesystem: works without any problem.

For me that is not an issue, because it probably will be used once, at an initial install, so a manual step is no issue for me. It just took some time, to figure out, what went wrong.
