### ISSUE TITLE
How to add bindings for LSP `executeCommand` request?

### ISSUE THREAD

**Issue by andrhua** [neoclide/coc.nvim#4345]
I'm looking for a way to bind keymaps for sending `executeCommand` [requests](https://github.com/elixir-lsp/elixir-ls/blob/master/apps/language_server/lib/language_server/protocol.ex#L186) to elixir-ls, but can't find anything related in docs.

**Comment by andrhua** [comment]
found it [here](https://github.com/neoclide/coc.nvim/issues/442#issuecomment-464336336), but maybe this could get included in help?

**Comment by chemzqm** [comment]
Use extension like coc-clojure is recommended since it provides some convenient key-mappings and more configurations.
