### ISSUE TITLE
Possible to not use cmdheight=2 & wrap message text & ale?

### ISSUE THREAD

**Issue by tomspeak** [neoclide/coc.nvim#435]
Hi,

1. I was wondering if it's possible to not have to set `cmdheight=2` without having to deal with the message `Press enter to continue`?

2. Is it possible to have the content put into the command status wrap? It currently cuts off. Flow seems to have very long messages.

3. Can you explain how this works in conjunction with Ale? Some of the functionality is blurred between the two plugins. I have seen you use Ale (if that's still true), do you have any advice on how to get the best out of each plugins strengths?

Thank you!

**Comment by chemzqm** [comment]
1. `cmdheight=1` is not required, let me know how to trigger `1. Press enter to continue` when it's 1.

2. What content do you mean?

3. I've disabled ale from lint the files that coc could handle, but you can disable coc diagnostic if your language server is slow, or make ale display diagnostics from coc by settings.

**Comment by tomspeak** [comment]
1. Odd! `cmdheight=1` being set seems to fix the issue? It would only work with `cmdheight=2` last night. Now the error message `Press enter to continue` does not appear.

2. Sorry, that was not very clear. For long text (mostly Flow errors), the messages are cut off, not wrapped.
![screenshot 2019-02-14 at 10 44 37 am](https://user-images.githubusercontent.com/2415569/52782329-b4c27e80-3046-11e9-9597-66d6ae84b974.png)

3. Thank you!

**Comment by chemzqm** [comment]
> 2\. the messages are cut off, not wrapped.

It would be truncated on CursorHold, but the picture you give shows full message.
Checkout `:h coc-action-diagnosticInfo` or use `<Plug>(coc-diagnostic-next)` and `<Plug>(coc-diagnostic-prev)` when you need diagnostic messages without truncate.

**Comment by tomspeak** [comment]
Sorry, I should have shown a message being cut off. 

Your fix works. Thanks for your help.

**Comment by tomspeak** [comment]
![screenshot 2019-02-14 at 3 02 49 pm](https://user-images.githubusercontent.com/2415569/52795450-b81b3180-3069-11e9-8674-ff9381f1e044.png)

I seem to have spoken too soon.

When hovering over a warning with `cmdheight=1`, this prompt appears and forces you to press "Enter" — is this possible to get around without increasing `cmdheight`?

Lastly, you can see the text being cut off, I assume there's no way for this to automatically wrap with `cmdheight=1`?

**Comment by chemzqm** [comment]
I can't reproduce the problem, it's possbile that your echo area has some other messages that shown at the same time of diagnostic message.
