### ISSUE TITLE
[coc.nvim] e.forEatch is not a function use :CocOpenLog for details

### ISSUE THREAD

**Issue by sentakuhm** [neoclide/coc.nvim#4353]
i used two methods to install:

- release branch, error message was:

`[coc.nvim] e.forEatch is not a function use :CocOpenLog for details`

- and build from source code message error was:

`[coc.nvim] names.forEatch is not a function use :CocOpenLog for details` 

- when try: `CocOpenLog` and `CocInfo` both wont open.
- when try to install plugins with `CocInstall` nothing happen.

- All requirements were installed (nodejs npm yarn).

- Arch linux with vim (9) latest version from repositories.

**Comment by chemzqm** [comment]
You should configure `coc_global_extensions` as array, try `:echo g:coc_global_extensions`

**Comment by sentakuhm** [comment]
> You should configure `coc_global_extensions` as array, try `:echo g:coc_global_extensions`

thank you very much!!, its working now i removed:
`let g:coc_global_extensions = 1` from .vimrc.
