### ISSUE TITLE
record jump stack on each jump

### ISSUE THREAD

**Issue by jlmxyz** [neoclide/coc.nvim#4358]
**Is your feature request related to a problem? Please describe.**
I'm used to VIM tag behavior, which is AWESOME (compared to other lame jumping like Vscode, eclipse, that got messed with user clicks and movement)
what I love is that on a jump, the source location is recorded, and whatever I do in the jumped file, a Ctrl+T jump back to the location, this allow to set "jump markers" and come back 
what I disliked on VIM tag behavior is that there is no "easy way" to go back and forward into this "jump stack" eg : perform a jump, begin to modify, go back to where jump was done, do some modification, go forward, continue to modify... and so on

**Describe the solution you'd like**
I would like that on each coc-definition, coc-type-definition, coc-implementation, coc-references, the origin of the jump (file,function,line/pattern) is stored in the stack.
I'd like that the last element of the stack be the last jump destination
I'd like to have coc-jump-stack-next and coc-jump-stack-previous function to navigate into the jump stack
I'd like to have CocList jumpStack display the stack as CocList outline behave
I'd like to have the jump from line highlighted 
I'd like to have a "jump from preview window" displayed and maybe "jump next preview window" (user options)

**Describe alternatives you've considered**
I've done a similar behavior with
```
{
    "coc.preferences.jumpCommand": "split +res"
}
```
however : 

1. this use a lot of space display (2 lines per jump are lost)
2. the from jump information isn't accurate, if going into previous window and modifying 
3. when moving around the windows, the size might be ackward (closing a window does not keep the "full screen state" of current window) 

**Additional context**
![Untitled](https://user-images.githubusercontent.com/40383940/201525867-fd905823-8053-4c77-8acd-c23db1d46eea.png)

**Comment by chemzqm** [comment]
Jump list already modified when using `edit` as jump command, checkout `:h CocTagFunc` if you want to use tags list.

**Comment by chemzqm** [comment]
You can create your own function which call the locations API `:h coc-locations-api` and change the jump list as you would like to.

**Comment by jlmxyz** [comment]
in fact the vim jump stack isn't helpfull, because poping from a jump (ctrl+T) do loose the information from where we came from and also undisplay the buffer....

I managed to create somehow a usable version by doing 
```

nmap <silent> gd :call JmpDefinition()<CR>
nmap <silent> gy :call JmpTypeDefinition()<CR>
nmap <silent> gi :call JmpImplementation()<CR>
nmap <silent> gr :call JmpReferences()<CR>


nmap <silent> gb :call JmpStackPrevious()<CR>
nmap <silent> gn :call JmpStackNext()<CR>

function! AutosizeAboveBelow()
    let this_window = winnr()
    let above_window = winnr('k')
    let below_window = winnr('j')
    :res
    "let bwRcmd = below_window "res +3"
    "echom "above_window : " above_window " below_window : " below_window
    if below_window != 0
        execute below_window "res +5"
    endif
    if above_window != 0 && this_window != above_window
        execute above_window "res +5"
    endif
endfunction



function! JmpDefinition()
    call CocAction('jumpDefinition')
    call AutosizeAboveBelow()
endfunction

function! JmpTypeDefinition()
    call CocAction('jumpTypeDefinition')
    call AutosizeAboveBelow()
endfunction

function! JmpReferences()
    call CocAction('jumpReferences')
    call AutosizeAboveBelow()
endfunction

function! JmpImplementation()
    call CocAction('jumpImplementation')
    call AutosizeAboveBelow()
endfunction

function! JmpStackPrevious()
    :wincmd j
    call AutosizeAboveBelow()
endfunction

function! JmpStackNext()
    :wincmd k
    call AutosizeAboveBelow()
endfunction

``` 

this isn't exaclty a jump stack (I must add some records) but it behave the way I wanted at window point of view...
