### ISSUE TITLE
Display header in status line for coc-list

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#4360]
**Describe the solution you'd like**
![screen-2022-11-15-20-08-32](https://user-images.githubusercontent.com/32936898/201916284-6e7f78a1-1864-46ad-a3dd-239acb9a064e.jpg)

Such as display `name shortcut triggers priority filetypes` in statusline of `list:///sources`

**Comment by fannheyward** [comment]
Why do you want to display `name shortcut triggers priority filetypes` in stautusline? This will make the statusline very crowd and unreadable.

**Comment by Freed-Wu** [comment]
Just let user know every column's function. The current status line don't provide any valuable information about this list.

**Comment by fannheyward** [comment]
Got your point, but I think it's still crowd on statuslinie to display the header. There's already many items on statusline now.

**Comment by chemzqm** [comment]
Hard to align the items and no click support, don't think it's necessary.

**Comment by Freed-Wu** [comment]
> it's still crowd on statuslinie to display the header. 

I means only display header name, like

![screen-2022-11-18-20-24-12](https://user-images.githubusercontent.com/32936898/202704771-8249a2d0-9c2a-4dfa-a8ed-7a0317521a5f.jpg)

It is not crowd. a1, a2, a3, a4 will be `name	shortcut	triggers	priority`

> Hard to align the items

Understand. I only found [some plugin](https://github.com/mechatroner/rainbow_csv) has this function and want to know whether coc can do.

> no click support,

Did you mean click the header? I think it is unnecessary.
