### ISSUE TITLE
Vim doesn't see Coc-specific help entries

### ISSUE THREAD

**Issue by GOKOP** [neoclide/coc.nvim#4362]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9000813
node version: v19.1.0
coc.nvim version: 0.0.82-7817ea67 2022-11-13 01:53:04 +0800
coc.nvim directory: /home/gokop/dotfiles-git/.vim/pack/plugins/start/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-11-15T15:05:47.183 INFO (pid:11528) [plugin] - coc.nvim initialized with node: v19.1.0 after 56ms
2022-11-15T15:05:54.081 INFO (pid:11528) [attach] - receive notification: highlight [] true
```

## Describe the bug

Vim can't find any Coc-related help entry I've tried. For example, `:h coc-semantic-highlights` tells me that there's no help about it. I assume it should work ootb because patch notes casually mention it

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start vim with command: `vim -u mini.vim`

- Try: `:h coc-semantic-highlights`; it can't find it.

**Comment by fannheyward** [comment]
Try `:helptags ALL`, check `:h :helptags`.
