### ISSUE TITLE
Improve startup debugging experience

### ISSUE THREAD

**Issue by lf-** [neoclide/coc.nvim#4363]
**Is your feature request related to a problem? Please describe.**

There is a bug (which I've not investigated further yet) in coc-rust-analyzer, which results in it not starting up properly in some conditions (starting up with a `:mksession` file is one of them; so is `:CocRestart`), which then holds up the startup of coc.nvim, which ends up starting in a degraded state with only some features working.

I had a lot of trouble debugging the Coc side of this though! There's not really very good logging of extension startup. To make matters more fun, `:CocOpenLog` (silently) doesn't work in this condition since `g:coc_service_initialized` is 0 so RPCs to the service don't work yet.

I believe that "extension.activate()" is not completing, which is the presentation of this extension issue on the Coc side:

https://github.com/neoclide/coc.nvim/blob/f5310ce85f0ea50c47c15e46c9a113daa5131f55/src/extension/manager.ts#L340-L347

**Describe the solution you'd like**

`:CocOpenLog` should ideally work even if the extension is not yet initialized, to debug startup issues. Extension startup should be logged such that extensions breaking startup can be identified.

**Describe alternatives you've considered**

Maybe suggest setting a custom log location with `NVIM_COC_LOG_FILE` in an error message that CocOpenLog outputs.

**Additional context**

**Comment by iamcco** [comment]
> which ends up starting in a degraded state with only some features working

If there some features working, I think the  coc-rust-analyzer extension is actived. It more sounds like workspace detect problem.

**Comment by iamcco** [comment]
try test with below setting in you coc-settings.json.

```
  "workspace.bottomUpFiletypes": ["rust"]
```

**Comment by lf-** [comment]
> > which ends up starting in a degraded state with only some features working
> 
> If there some features working, I think the coc-rust-analyzer extension is actived. It more sounds like workspace detect problem.

I am certain it's not: I hacked in logging statements between very early start up and setting coc_service_initialized, which confirmed it didn't get past initializing plugins. I then logged which plugins finished initializing and got no log for coc-rust-analyzer. I uninstalled it and the problem no longer reproduces. 

(for context this is a haskell project with no rust in it; the stuff working is language server warnings, and the stuff not working is anything that does CocAction, since that checks if coc is ready and fails if not)

**Comment by fannheyward** [comment]
> suggest setting a custom log location with NVIM_COC_LOG_FILE in an error message that CocOpenLog outputs

1. `export NVIM_COC_LOG_FILE=/tmp/coc.log`
2. `tail -f /tmp/coc.log`

Is this what you want?

**Comment by lf-** [comment]
yeah, but I would like to be suggested to do that by :CocOpenLog, which, currently, if the service doesn't initialize, silently does nothing instead.

**Comment by chemzqm** [comment]
The initialization have improved, the plugin would not wait for `checkAutoActivate` any more.
It's recommended to use `NVIM_COC_LOG_FILE` environment variable, if the node is blocked, `:CocOpenLog` won't work.
