### ISSUE TITLE
Completion confusing

### ISSUE THREAD

**Issue by yinghaoyu** [neoclide/coc.nvim#4364]
## What I have done ?

Updating coc.nvim plugin in neovim

## How to reproduce?

In c++ files, when I input `#incl` and use tab to  trigger completion. 
```cpp
#include "head"
```
There are extra string `"head"` which drives me confusing.

Also like this, input `vec` and use tab to  trigger completion. 
```cpp
vector()
```
There are extra string `()`, but I want to input `vector<int>` in fact.

 It's differet from previous coc version, whether is this a bug or a new feature?

**Comment by fannheyward** [comment]
How do you map your `tab` to trigger completion?

`inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"`

I'm using this, `<CR>` after you input `#incl`, you got `#include "|"` where `|` is the cursor.

**Comment by yinghaoyu** [comment]
Here is my configuation as below
```vim
  " use tab for trigger completion with characters ahead and navigate.
  inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1):
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
  inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

  " make <CR> to accept selected completion item or notify coc.nvim to format
  " <C-g>u breaks current undo, please make your own choice.
  inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

  function! CheckBackspace() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
  endfunction
```

**Comment by fannheyward** [comment]
Can't reproduce.

**Comment by yinghaoyu** [comment]
Perhaps the following example is more clearer.
Input `incl` and use tab to trigger completion. It choice the first candidate that is `include "header"`.
**egg 1:**
```
#include "header" 
    include "header"      {} [LS]
    include <header>      {} [LS]
    include_next <header> {} [LS]
    include_next "header" {} [LS]
    include                 [A]
```
**egg 2:**
```
vector()
  vector(…)                             f [LS]  [12 overloads]
  vector<typename _Tp, typename _Alloc> [LS]
  vector                                  [A]
  •va_end(ap)                          [LS]
```
In **egg 1**, previous version choices `include` as the first candidate.
In **egg 2**, previous version choices `vector` as the first candidate.

**Comment by chemzqm** [comment]
The results from language server should be preferred by default, you can use `suggest.invalidInsertCharacters` to have better insert word.

The default value was changed, see the change log.

**Comment by chemzqm** [comment]
Seems to configure `suggest.invalidInsertCharacters` is what you need.

**Comment by yinghaoyu** [comment]
Maybe it's a good change, but it take some time getting used to.

**Comment by chemzqm** [comment]
You can make the decision, or you can disable word insert when navigating completion item
