### ISSUE TITLE
Latest release branch breaks coc-definition and other commands

### ISSUE THREAD

**Issue by sdroege** [neoclide/coc.nvim#4366]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9000813
node version: v18.12.1
coc.nvim version: 0.0.82-7817ea67 2022-11-13 01:53:04 +0800
coc.nvim directory: /home/slomo/.vim/pack/coc/start/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-11-16T10:17:19.242 INFO (pid:1008860) [extension:coc-git] - Looking for git in: git
2022-11-16T10:17:19.269 INFO (pid:1008860) [plugin] - coc.nvim initialized with node: v18.12.1 after 170ms
2022-11-16T10:17:19.269 INFO (pid:1008860) [attach] - receive notification: highlight [] true
2022-11-16T10:17:21.441 INFO (pid:1008860) [attach] - receive notification: showInfo [] true
```

## Describe the bug

With the latest `release` branch, `coc-definition` and other commands seem to be simply ignored in vim. `git bisect` pointed to 89cd42aea4cb91cac40fe96b756d43a34b442a64 and reverting that makes it work again.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  nmap <silent> gd <Plug>(coc-definition)
  ```

- Start vim with command: `vim -u mini.vim`

- Open some source file where `coc-definition` would usually work and do `gd`. Reverting above commit alone makes it work again.

**Comment by sdroege** [comment]
I was testing with clangd (14.0.6). That's actually a good point, it works fine with rust-analyzer.

**Comment by fannheyward** [comment]
Tested with clangd 15.0.1, works as expected.

**Comment by sdroege** [comment]
Do you have any suggestions how I can provide more information to pinpoint the problem?

**Comment by fannheyward** [comment]
Maybe this commit https://github.com/neoclide/coc.nvim/commit/f5310ce85f0ea50c47c15e46c9a113daa5131f55 related, still debug on this.

**Comment by sdroege** [comment]
Let me bisect on the master branch. f5310ce85f0ea50c47c15e46c9a113daa5131f55 doesn't work but the commit before that (c41c5733) also doesn't.

**Comment by sdroege** [comment]
Yes, I can confirm that it works in c41c5733 but the next commit f5310ce8 breaks it.

**Comment by smancill** [comment]
I seem to observe something related, with latest release 89cd42ae, which includes f5310ce8.

I have the following (I use this to fallback to Vim's `gd` if CoC returns no definitions):

``` vim
function! s:coc_overwrite_map(action, map)
  if coc#rpc#ready() && CocAction('getCurrentFunctionSymbol') isnot v:null
    call CocActionAsync(a:action)
  else
    call feedkeys(a:map, 'n')
  endif
endfunction

nmap  <silent>  K           :<C-U>call <SID>coc_overwrite_map('doHover', 'K')<CR>
nmap <silent>   gd          :<C-U>call <SID>coc_overwrite_map('jumpDefinition', 'gd')<CR>
```

Which was working fine until now. But the maps now fail with:

```
Error detected while processing function <SNR>3_coc_overwrite_map[1]..CocAction[2]..function <SNR>3_coc_overwrite_map[1]..CocAction:
line    2:
E605: Exception not caught: coc.nvim not ready when invoke CocAction "getCurrentFunctionSymbol"
```

Doing the calls manually in the command-line results in this:

```
:echo coc#rpc#ready()
1

:call CocAction('getCurrentFunctionSymbol')
Error detected while processing function CocAction[2]..function CocAction:
line    2:
E605: Exception not caught: coc.nvim not ready when invoke CocAction "getCurrentFunctionSymbol"
```

If I revert to previous release 040f3a9a, it works again.


Both NeoVim and Vim have the same error.

``` bash
$ nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by _nixbld1

Features: +acl +iconv +tui

$ vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 01 1980 00:00:00)
macOS version - x86_64
Included patches: 1-609
Compiled by smancill
Huge version without GUI.
```

**Comment by smancill** [comment]
Actually, `CocUpdate` just fixed my issues.

**Comment by sdroege** [comment]
Indeed, I can confirm that the coc-clangd update some time between when I created the issue and now fixed it :)
