### ISSUE TITLE
Hard-to-read colors when using Solarized colorscheme

### ISSUE THREAD

**Issue by jasper1378** [neoclide/coc.nvim#4371]
Hello all,

When using coc.nvim with the [Solarized colorscheme](https://github.com/altercation/vim-colors-solarized), the colors in the completion dialog are very difficult to read ([image](https://imgur.com/a/D674blc)). The FAQ has a couple of topics relating to colors and highlights, but none of them completely fixed the problem.

Any help would be greatly appreciated!

**Comment by chemzqm** [comment]
Seems you have changed `background` option after coc.nvim initialize, use`set background=dark` before coc.nvim loaded.
`

**Comment by jasper1378** [comment]
Thank you!

**Comment by jasper1378** [comment]
Unfortunately, setting the background before loading coc.nvim does not solve the problem.

**Comment by chemzqm** [comment]
Can't reproduce, you can define the highlight groups yourself.

**Comment by jasper1378** [comment]
Ok, will do. Thank you for your help.
I should have included my `init.vim` when opening the issue, but here it is anyways: [https://gist.github.com/jasper1378/3e9739100ba486033586d2a401749270](https://gist.github.com/jasper1378/3e9739100ba486033586d2a401749270)

**Comment by chemzqm** [comment]
Seems you have made the colorshcme changed current colors after coc.nvim loaded, I've made the highlights created after VimEnter, might helps.

**Comment by chemzqm** [comment]
Seems you have made the colorshcme changed current colors after coc.nvim loaded, I've made the highlights created after VimEnter, might helps.

**Comment by jasper1378** [comment]
I really appreciate your help and the fact that you pushed a commit just for me, but unfortunately it didn't fix the problem. However, telling solarized to degraded it's colors (through `let g:solarized_termcolors=256`) does fix it; however degraded colors aren't ideal for obvious reasons.
