### ISSUE TITLE
After executing `CocRestart`, an error occurs and it cannot be used.

### ISSUE THREAD

**Issue by yaegassy** [neoclide/coc.nvim#4373]
## Result from CocInfo

```
## versions

vim version: NVIM v0.9.0-dev-341+gba04fffe9
node version: v18.12.1
coc.nvim version: 0.0.82-14e9410 2022-11-18 13:00:09 +0800
coc.nvim directory: /Users/yaegassy/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug

This problem seems to have occurred since this commit.

- <https://github.com/neoclide/coc.nvim/commit/b1867763043348d63c732147b34bd037509f39ee>

## Reproduce the bug

Please check the DEMO.

## DEMO (mp4)

https://user-images.githubusercontent.com/188642/202657127-59e91f7f-98eb-42de-ab90-33625a27bac5.mp4

**Comment by fannheyward** [comment]
Reproduced.
