### ISSUE TITLE
Add separators to code-lens items in vim

### ISSUE THREAD

**Issue by ArtAndreev** [neoclide/coc.nvim#4375]
**Is your feature request related to a problem? Please describe.**
First of all, thanks for implementing https://github.com/neoclide/coc.nvim/issues/4265! Looks cool! I have one request: add separators to code-lens items, for example, `|`. It will increase readability.

**Describe the solution you'd like**
Add `|` between code-lens items.

**Describe alternatives you've considered**
Not applicable.

**Additional context**
Code-lens in VSCode:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/26388769/202868569-9cd9a5c1-4295-4357-a53b-abde4214b6f2.png">

**Comment by ArtAndreev** [comment]
In vim now:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/26388769/202868659-bffb4e5a-7f40-410c-ad39-2344e9e3475a.png">

**Comment by chemzqm** [comment]
Try configuration like `"codeLens.subseparator": " | "`

**Comment by ArtAndreev** [comment]
Thanks!
Maybe set it by default?
