### ISSUE TITLE
Autocomplete doesn't work with sources around, buffer

### ISSUE THREAD

**Issue by curkan** [neoclide/coc.nvim#4379]
Hello, autocompletion does not work for me, but only with around, buffer, file 
As in this plate

Name | Shortcut | Description
-- | -- | --
around | [A] | Words of the current buffer.
buffer | [B] | Words of other open buffers.
file | [F] | Filename completion, auto-detected.

I am attaching a video where you can see that after confirmation (pressing enter) nothing happens if type A, B

https://user-images.githubusercontent.com/1681501/203013426-c63df486-97f0-46a3-8f53-c0299452e786.mp4

**Comment by chemzqm** [comment]
Seems problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
On old version coc.nvim, the completion is canceled when completing incomplete request,it should be fixed, please provide your coc.nvim version.

**Comment by curkan** [comment]
> On old version coc.nvim, the completion is canceled when completing incomplete request,it should be fixed, please provide your coc.nvim version.

coc.nvim version: 0.0.82-4929909 2022-11-07 05:12:04 +0800

**Comment by curkan** [comment]
Log :CocInfo
[log.txt](https://github.com/neoclide/coc.nvim/files/10056241/log.txt)

**Comment by yaegassy** [comment]
@curkan I have one concern that I would like to comment.

It seems that your environment has `intelephense` registered in the languageserver section of `coc-settings.json` and also has the `@yaegassy/coc-intelephense` extension installed.

I think you have two `intelephense` language servers running. Please try to reduce it to one, as having two of the same language servers running is a source of problems.

Also, if you can update coc.nvim to the latest version, we recommend that you do so, as the problem may have already been resolved.

**Comment by curkan** [comment]
> @curkan I have one concern that I would like to comment.
> 
> It seems that your environment has `intelephense` registered in the "languageserver" section of `coc-settings.json` and also has the `@yaegassy/coc-intelephense` extension installed.
> 
> I think you have two `intelephense` language servers running. Please try to reduce it to one, as having two of the same language servers running is a source of problems.
> 
> Also, if you can update coc.nvim to the latest version, we recommend that you do so, as the problem may have already been resolved.

Okay, I'll try it then and report back.

**Comment by chemzqm** [comment]
It should be fixed by

commit cfbaa7fed925aa25809bb9b936edb04c244edeb3
Author: Qiming Zhao <chemzqm@gmail.com>
Date:   2022-11-12 02:41:39 +0800

    feat(completion): complete for inComplete not cancel

**Comment by curkan** [comment]
> It should be fixed by
> 
> commit [cfbaa7f](https://github.com/neoclide/coc.nvim/commit/cfbaa7fed925aa25809bb9b936edb04c244edeb3) Author: Qiming Zhao [chemzqm@gmail.com](mailto:chemzqm@gmail.com) Date: 2022-11-12 02:41:39 +0800
> 
> ```
> feat(completion): complete for inComplete not cancel
> ```

Yeah, updated to today's changes, everything worked out, thanks, best
If anyone else comes across:
`git pull`
`npm i`
