### ISSUE TITLE
Failed to install coc ccls

### ISSUE THREAD

**Issue by yazigegeda** [neoclide/coc.nvim#4383]
![Screenshot_2022-11-22-23-32-32-71_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/63853093/203355334-4a957698-66d3-4277-942c-0c7a3d63f2db.jpg)

I successfully installed apt install ccls, but an error occurred when using coc_install coc ccls. What should I do😥

**Comment by chemzqm** [comment]
That package published typescript source code instead of javascript code, so you can't install it by `:CocInstall`.
Install from git or use coc-clangd.
