### ISSUE TITLE
improve for notification 🌈.

### ISSUE THREAD

**Issue by allinu** [neoclide/coc.nvim#4386]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
just what a beautiful notify tool, now the plugin's so simple

<img width="697" alt="image" src="https://user-images.githubusercontent.com/32992109/203552703-a6949680-0289-4916-ba65-b994de01f0ae.png">

maybe can make a more beautiful style like the image bottom, have a border, some padding size or some color.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/32992109/203553023-b57ca8ce-dc64-41d8-bd22-b1e37c38c345.png">

**Describe alternatives you've considered**

i read the wiki of this repo, i have read [this page](https://github.com/neoclide/coc.nvim/wiki/Nvim-notifications-integration), but it still hard for me to use it, my config basic on lua, but i just know a little about lua, i think ... if there some lua script can do like this page's result.

**Additional context**

Nothing else but respect for you ❤️

**Comment by chemzqm** [comment]
On neovim, my suggestion is use 
```json
  "floatFactory.floatConfig": {
    "winblend": 15
  },
```
See `:h coc-config-floatFactory` for details, checkout `:h coc-completion-customize` for customize popup menu of coc.nvim.
