### ISSUE TITLE
CocDiagnostics error

### ISSUE THREAD

**Issue by amgodoi** [neoclide/coc.nvim#4389]
vim version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 10 2022 11:21:20)
Included patches: 1-854

nodejs version
Welcome to Node.js v16.17.0.

When I type de :CocDiagnostics command I get the error below (image).

Btw, :CocList diagnostics works fine.

![image](https://user-images.githubusercontent.com/78377022/203617141-0a301fc8-313b-4a1a-9aa1-6a55bfe9a744.png)

**Comment by chemzqm** [comment]
Seems limitation on latest vim.

**Comment by amgodoi** [comment]
Hi!

I found the problem. I use nerdtree plugin and put it inside my .vimrc

" Open the existing NERDTree on each new tab.
autocmd BufWinEnter * if getcmdwintype() == '' | silent NERDTreeMirror | endif

This is the problem. I removed it and worked.

Thanks a lot.
