### ISSUE TITLE
:CocAction command (or some other autocomplete-friendly way to invoke CocActions)

### ISSUE THREAD

**Issue by RedBeard0531** [neoclide/coc.nvim#4390]
**Is your feature request related to a problem? Please describe.**
There are a bunch of helpful things that are only exposed by doing `call CocAction("someString", other, args...)` or `echo CocAction(...)`. So many in fact, that I don't have mappings for all of them because I don't use all of them enough to commit them to memory. Unfortunately, because the command name is a string, there is no way for it to be autocomplete in the vim command line. So I end up either needing to search through my history to see if I find what I'm looking for, or pull up the docs and try to either correctly type out the command name or go through the process of copying and pasting it. Every time.

**Describe the solution you'd like**
Some way to autocomplete command names, and ideally args, but that is less important. Adding a `:CocAction` (and possibly a `:CocActionAsync`) command feels the most consistent with how `:CocCommand` is exposed (which works really well for discoverability FWIW). I suppose `:CocCommand action.ACTION_NAME` would also work mostly equivalently and may be easier to hook up to the current mechanism. Ideally, for  `CocAction` calls that return data rather than preforming some action it should at least echo the result automatically (hopefully with pretty-printing (I sometimes use [tpope's `:PP`](https://github.com/tpope/vim-scriptease) for this)).

**Describe alternatives you've considered**
* Put action functions in a vim dictionary. Unfortunately, this doesn't seem to autocomplete correctly, which defeats the point.
* Add autofuctions like `:call coc#actions#doFoo(...)`. I think this would work, but seems unwieldy to me. Also requires different syntax for `:call` vs `:echo`
* Live with the mild annoyances 🙂

**Additional context**
Thanks for the awesome plugin!

**Comment by chemzqm** [comment]
`CocAction` does request which blocks vim, use `CocActionAsync` is recommended.

You can create key-mappings and vim commands by `call CocActionAsync`, use `coc#add_command()` to add custom vim command to command list of coc.nvim.
