### ISSUE TITLE
[Feature] Underline LSP document links

### ISSUE THREAD

**Issue by oxalica** [neoclide/coc.nvim#4391]
**Is your feature request related to a problem? Please describe.**

LSP document links `textDocument/documentLink` can be opened by `CocAction("openLink")` or selected by `:CocList links`, but users should first know there are links. Currently links don't have any special styles and may NOT be intuitive to users. There should be a way to hint users some text are open-able.

For example, [my LSP server `nil`](https://github.com/oxalica/nil) implements documentLink for flake url strings. I'm expecting these strings are somehow distinguishable from plain strings.
```nix
{
  inputs = {
    flake-utils.url = "github:numtide/flake-utils"; # <- This is a link to https://github.com/numtide/flake-utils
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable"; # <- So does this.
  };
}
```

**Describe the solution you'd like**
Add `CocUnderline` to all document links, if available.

**Describe alternatives you've considered**
Apply other highlight groups, or add a new one like `CocLink`.

**Additional context**

VSCode renders underlines for document links from LSP server.
![screenshot-2022-11-24-20-29-15](https://user-images.githubusercontent.com/14816024/203784894-2b39602e-42b0-48f4-b46a-41f3a816ce48.png)

**Comment by fannheyward** [comment]
When your cursor on the document link, a tooltip float will be displayed. Yes, an underline hi will be better.
