### ISSUE TITLE
[Feature Request] hide API keys

### ISSUE THREAD

**Issue by pendragons-code** [neoclide/coc.nvim#4394]
I'm new to COC as a whole, so if i get anything wrong and end up wasting your time , I apologize in advance. I just can't seem to find anything. I really am sorry if i end up wasting your time. I truly am and i deserve punishment for doing so.

I'm not sure if this is an existing feature, or if there is already a method to do this. But when the COC-box appears, you can actually get api keys from dotfiles. Specifically `.env`.

**Background:**
I'm learning from a circle of friends that exchange notes for simple projects. So I'm not very good at things, in contrast to a person who has went through some tech course from a school or has experience as a professional. So once in a while I would stream on platforms like discord or zoom to demonstrate or ask one of the guys to help me identify something wrong, but when I type, COC seems to expose my API keys.

**Existing solutions:**
Im using terrible keywords, but i really can't find anything with the words i use. I have tried moving the `.env` file somewhere else, or just don't open it at all so that it would not get loaded and it is unlikely to beome an option in the box.
But as described in the problem, I need to be able to access the .env file for demonstrations, especially to update keys (stop the stream, rename stuff or change values and resume stream).

**Describe the solution you'd like**
If there isn't a solution, which I doubt. But maybe we can make something like a `.COCconfig` file or something like that similar to that of a `.vscode` file. This will file will go along the lines of removing the api keys from the COC box. Either that or just don't allow `.env` values to be shown. I'm not sure about the solutions, because i lack real world experience of a developer with a job, im just a teen with no experience at all.

**Setup:**
Simple and terribly made config file all in one inti.vim file, which i am more than happy to change.

I am running neovim on linux (debian (also in the form of rpi) and arch linux , but i have the unstable repos on for debian so i get the latest packages/releases.)

**Describe alternatives you've considered**
I apologize, but i lack real world experience and therefor I cannot say much.

**Additional context**
If there is a solution, and that i am not aware of, I apologize  again.

Once again, Thank you
Pendragon

(Edits I made are to fix the technical specifications, format and grammar, cherrio! Gotta work on my linguistic capabilities :( )

**Comment by pendragons-code** [comment]
Oh yes, my stupidity and my lacking of cognitive capacity to possess and linguistic capacity means that I in fact seem to keep referring `popup menus` (in accordance to the project readme's naming) and `box`. I apologize if that causes any confusion.

**Comment by chemzqm** [comment]
> COC seems to expose my API keys.

Do you mean when you open file contains API keys and coc.nvim show completion for the keys?

**Comment by pendragons-code** [comment]
Yes that is what i meant.

**Comment by fannheyward** [comment]
There're two cases:

1. disable completion suggestion when you edit `.env` file
2. vim opens two  buffers: `.env` and your real code file like `main.py`, you want to disable `.env` content to show in `main.py` editing

For case one, you can disable completion by `b:coc_suggest_disable`.

For case two, you can disable `buffer` completion source with `coc.source.buffer.enable` to false.

**Comment by pendragons-code** [comment]
Would that remove other stuff?
Also, i would like to know the name of the keys.

**Comment by chemzqm** [comment]
It's display only, coc.nvim have no support for things like telemetry.

To prevent coc.nvim get the content of buffer, see `:h b:coc_enabled`
