### ISSUE TITLE
what is the option to disable auto include on complete

### ISSUE THREAD

**Issue by atrosekta** [neoclide/coc.nvim#4395]
when i coc complete something it automatically include what is needed , for exemple if in a cpp file if i type `print` and let coc complete it to `printf()` it add `#indlude <cstdio>` at the top of the file,
what is the option to disable that? so i need to manally call `<Plug>(coc-fix-current)` to add it,
im pretty shure there is already an option for that but i cant find it in the documentation or issues about that, 
but if there is not i can rewrite a better issue / edit this one to fit as `feature-request` and maybe try to make a PR that add it

**Comment by fannheyward** [comment]
This needs language server support. Are you using `clangd`? Add `-header-insertion` argument, check https://github.com/clangd/clangd/issues/55.

**Comment by chemzqm** [comment]
Use `coc#pum#insert()` to avoid snippet expand and additional edits.

**Comment by atrosekta** [comment]
thanks a lot, 
so the `--header-insertion` argument for clangd worked as intended,
but `coc#pum#insert()` seems to behave the same way as `coc#on_enter()` and add the corresponding header,
it was to make a mapping for toggling it, i'll search into that but i don't thinks there is currently a way to restart the language server with arguments from a command and not the config file

**Comment by sim590** [comment]
I'm trying to avoid opening an issue if not necessary. I'm having the same issue with haskell-language-server and I don't know if I need to configure HLS or configure COC.vim... Here's my original issue:

https://github.com/haskell/haskell-language-server/issues/4514

I would greatly appreciate help. Thanks.

**Comment by sim590** [comment]
> Use coc#pum#insert() to avoid snippet expand and additional edits.

I tried that:
```vim
inoremap <silent><expr> <c-y> coc#pum#visible() ? coc#pum#insert() : "\<C-Y>"
```
and it works.

But, what if I want to disable that only for HLS?

**Comment by fannheyward** [comment]
@sim590 Try to add `settings` section in languageserver configuration

```
"settings": {"haskell.plugin.ghcide-completions.config.autoExtendOn": false }
```

**Comment by sim590** [comment]
@fannheyward: I replaced the `inoremap` setting to the default to use `coc#pum#confirm()`, and the following settings:

<details>
<summary>My config</summary>

```json
{
  "languageserver": {
    "haskell": {
      "command": "haskell-language-server-wrapper",
      "args": ["--lsp", "--debug", "-l", "/tmp/hls.log"],
      "rootPatterns": ["*.cabal", "stack.yaml", "cabal.project", "package.yaml", "hie.yaml"],
      "filetypes": ["haskell", "lhaskell"],
    },
    "settings": {
      "haskell.plugin.ghcide-completions.config.autoExtendOn" : false
    }
  },
  "coc.preferences.useQuickfixForLocations": true,
  "inlayHint.enable": false,
}
```

</details>

And it still doesn't work.

**Comment by sim590** [comment]
I just realized that you meant inside the `haskell` subsection of the `languageserver` section. I tried it and it works. Dang. Thanks!
