### ISSUE TITLE
 Inserting text in a split window causes the cursor to jump to another split

### ISSUE THREAD

**Issue by Heptite** [neoclide/coc.nvim#4396]
## versions

vim version: VIM - Vi IMproved 9.0 9000954
node version: v18.12.1
coc.nvim version: 0.0.82-12d7aaf3 2022-11-24 05:54:32 +0800
coc.nvim directory: C:\Users\Heptite\vimfiles\pack\neoclide\opt\coc.nvim
term: undefined
platform: win32

## Log of coc.nvim

2022-11-26T18:41:20.672 INFO (pid:12568) [plugin] - coc.nvim initialized with node: v18.12.1 after 197
2022-11-26T18:41:53.487 INFO (pid:12568) [services] - service tsserver started
2022-11-27T11:15:49.696 INFO (pid:12568) [attach] - receive notification: showInfo []

## Describe the bug

With multiple splits, inserting text text will cause a completion menu to open, which is expected, but continuing to type will cause the cursor to jump to another split, usually one overlapped by the completion menu.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

See above description of bug and below the screen capture.

## Screenshots (optional)

https://youtu.be/MIJI2ea5tKI

See also this reddit post: https://old.reddit.com/r/vim/comments/z5dz5f/inserting_text_in_a_split_window_causes_the/

**Comment by Heptite** [comment]
Bram _just_ released patch 9.0.961 and it appears to have fixed this issue. I'll do some more testing to be sure.

**Comment by adolfgatonegro** [comment]
I'm seeing the same issue on `vim` 9.0 on Arch Linux.

# Results from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9000910
node version: v19.1.0
coc.nvim version: 0.0.82-c58e398b 2022-11-28 04:05:08 +0800
coc.nvim directory: /home/gatonegro/.config/vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-11-27T14:40:16.399 INFO (pid:249105) [plugin] - coc.nvim initialized with node: v19.1.0 after 93
2022-11-27T14:40:21.682 INFO (pid:249105) [attach] - receive notification: showInfo []

```
## Describe the bug

Same deal. If you type something in one buffer, and `coc.nvim` finds a related suggestion in a different buffer, the autocomplete pop-up will jump to said split instead of remaining in the active one.

## Reproduce the bug

Using a simple `.vimrc` with `coc.nvim` loaded is enough to reproduce.

```
set nocompatible
set runtimepath^=$XDG_CONFIG_HOME/vim/autoload/coc.nvim
filetype plugin indent on
syntax on
```

## Screenshots

[Quick video showing the issue.](https://www.youtube.com/watch?v=tJWpl1DNyKI)

**Comment by Heptite** [comment]
Since patch 9.0.961 appears to fix this to the best of my ability to test, I'm closing this issue.
