### ISSUE TITLE
Make coc#ui#open_url configurable

### ISSUE THREAD

**Issue by choueric** [neoclide/coc.nvim#4399]
I was trying to figure out how to show the rust doc inside vim rather than opening the browser using coc-rust-analyzer's `openDocs` method. Digged into the code, guess the invoke chain is `openDocs2` -> `vscode.open` -> `coc#ui#open_url`. However, seems like `coc#ui#open_url`  is not able to be configured inside the vim configuration as a global function/variable, like other configurations.

It would be nice to add a global one for it and improve the extendibility.

**Comment by fannheyward** [comment]
When you do `openDocs`, coc-rust-analyzer will request to rust-analyzer with current cursor function to rust-analyzer, rust-analyzer returns an url to doc.rust-lang.org, then coc.nvim opened it in your browser. In this command, we can't show doc because rust-analyzer only returns an url.

> show the rust doc inside vim

You can use hover document to show doc with float window, check `:h coc-hover`.

**Comment by choueric** [comment]
that's why it would be helpful to have coc#ui#open_url can be defined by user, e.g. "!w3m", to open the returned URL. But thanks for the suggestion, I will have a try.

**Comment by fannheyward** [comment]
By default, `coc#ui#open_url` uses `open` on macOS, `xdg-open` if available and `cmd` on window.

Do you use `w3m` on macOS or Linux? I didn't use this yet.

**Comment by choueric** [comment]
I'm using Linux. Here is the screenshot if I replace `coc#ui#open_url` with command `:term w3m <url>`:
![image](https://user-images.githubusercontent.com/789292/204437846-99b976f5-e39b-4ab5-8c91-141bea142546.png)

**Comment by choueric** [comment]
A possible approach is like
```diff
diff --git a/autoload/coc/ui.vim b/autoload/coc/ui.vim
index 02656c0b..89afb49f 100644
--- a/autoload/coc/ui.vim
+++ b/autoload/coc/ui.vim
@@ -4,6 +4,7 @@ let s:is_mac = has('mac')
 let s:sign_api = exists('*sign_getplaced') && exists('*sign_place')
 let s:sign_groups = []
 let s:outline_preview_bufnr = 0
+let g:coc#open_url = get(g:, 'coc#open_url', '')

 " Check <Tab> and <CR>
 function! coc#ui#check_pum_keymappings(trigger) abort
@@ -326,6 +327,10 @@ function! coc#ui#change_lines(bufnr, list) abort
 endfunction

 function! coc#ui#open_url(url)
+  if g:coc#open_url !=# ''
+    execute g:coc#open_url a:url
+    return
+  endif
   if has('mac') && executable('open')
     call system('open '.a:url)
     return
```

And in vimrc, add 
```vim
let g:coc#open_url = 'term w3m'
autocmd FileType rust map <buffer> K :CocCommand rust-analyzer.openDocs<CR>
```
