### ISSUE TITLE
Cursor vanishes in vim after coc-implementation

### ISSUE THREAD

**Issue by jiahaowu** [neoclide/coc.nvim#440]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 14 2019 12:32:11)
node version: v8.9.0
coc.nvim version: 0.0.54
term: iTerm.app
platform: darwin

## Error messages

**Describe the bug**
After executing the coc-implementation command for a Golang interface and enter a file from the pop-out pane, the cursor disappeared. Tested on another Ubuntu machine the same thing appends.  It looks like the vim version has nothing to do with this strange behavior. 

Vim on MacOS:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 14 2019 12:32:11)                                                                                    
macOS version                                                                                                                                         
Included patches: 1-918

Vim version on Ubuntu:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 16 2018 19:28:47)                                                                                    
Included patches: 1-481 

I can bring back the cursor by running `:source ~/.vimrc` even though  `redraw` doesn't help. 

**To Reproduce**

Using the suggested bingo backend:

```json
"languageserver": {
    "golang": {
      "command": "bingo",
      "args": ["--diagnostics-style=instant"],
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
  }
```

Let's using the following small go example:

```go
package main

import "fmt"

type resolver interface {
	foo()
}

type stA struct {
	x string
}

type stB struct {
	y string
}

func (s *stB) foo() {
	fmt.Println(s.y)
}
func (s *stA) foo() {
	fmt.Println(s.x)
}

func main() {
	X := &stA{"TEST"}
	Y := &stB{"TEST"}
	X.foo()
	Y.foo()
	fmt.Println("vim-go")
}
```
1. move to `type resolver interface` to get the implementations of `resolver`
2. I used the suggested key-binding (gi) for `coc-implementation`, then I get a window to select implementations from:

![image](https://user-images.githubusercontent.com/9004183/52823024-8746f680-3081-11e9-9fd2-ef4550ad76a6.png)

3. Once I select a file from the list to open it, the cursor disappeared....

![image](https://user-images.githubusercontent.com/9004183/52823049-a04fa780-3081-11e9-81f3-2226020e6a45.png)

**Screenshots**
![screen recording 2019-02-14 at 5 56 08 pm](https://user-images.githubusercontent.com/9004183/52823320-8793c180-3082-11e9-8021-7819d3a64d95.gif)

**Comment by fannheyward** [comment]
nvim+coc+bingo is worked.

```
vim version: NVIM v0.4.0-263-g969cc5599
node version: v11.9.0
coc.nvim version: 0.0.54
term: iTerm.app
platform: darwin
```

**Comment by jiahaowu** [comment]
Tried neovim as suggested by @fannheyward, it worked. 

```
vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.54
term: iTerm.app
platform: darwin
```

**Comment by chemzqm** [comment]
@jiahaowu what's result of `:echo &splitbelow` ?

**Comment by chemzqm** [comment]
Try add `set updatetime=300` to your .vimrc.

**Comment by jiahaowu** [comment]
> @jiahaowu what's result of `:echo &splitbelow` ?

This command returns number 1.

![image](https://user-images.githubusercontent.com/9004183/52860730-493be800-30fe-11e9-9b81-d4484bc18d14.png)

> Try add `set updatetime=300` to your .vimrc.

![image](https://user-images.githubusercontent.com/9004183/52860621-e9454180-30fd-11e9-8193-0309c9b157de.png)

I had added this in vimrc from very beginning. The configuration for COC in my vimrc is the same as the one suggested in neoclide/coc.nvim repository [readme](https://github.com/neoclide/coc.nvim#example-vim-configuration).

**Comment by lwhorton** [comment]
for anyone following up -- i also get the exact issue described. what was causing it was escaping the preview window of coc-implementation (or coc-references, etc) by using ctrl-c instead of escape. the cursor will completely disappear until exiting and restarting my vim session if I fail to exit via escape.
