### ISSUE TITLE
coc#pum#visible() entered into editor when I press up arrow

### ISSUE THREAD

**Issue by churcho** [neoclide/coc.nvim#4403]
Not sure what changed, anytime I press the up button the above text gets inserted into my editor.
I can see them in the default key mappings but I don't understand why it's inserting the text into my editor. No highlight is made, it just adds the [entire](https://github.com/neoclide/coc.nvim/blob/db33b73f8f643e792d08b9a555b6a05cfe1923dd/doc/coc.txt#L494) mapping onto whatever I am typing.

The same applies for the down arrow.

**Comment by chemzqm** [comment]
Make sure you have `replace_keycodes` set to `false` if you're using lua https://github.com/neoclide/coc.nvim/blob/16a65b38a5125f4672cb4b426c1b82164cd7b4c4/README.md#L289

**Comment by churcho** [comment]
> Make sure you have `replace_keycodes` set to `false` if you're using lua
> 
> https://github.com/neoclide/coc.nvim/blob/16a65b38a5125f4672cb4b426c1b82164cd7b4c4/README.md#L289

I am not using lua, is there a different option for non Lua configs?

**Comment by chemzqm** [comment]
Try `:verbose imap <up>` in your vim, seems it's badlly rempped.
