### ISSUE TITLE
Alternative for `fixInsertedWord`

### ISSUE THREAD

**Issue by tbo** [neoclide/coc.nvim#4406]
The preference `suggest.fixInsertedWord` got removed in [this commit](https://github.com/neoclide/coc.nvim/commit/7c6db7546dfa29f1167c53111a00abac4e86e383). I find the default behavior very annoying. Is there an alternative way to achieve the same behavior?

**Comment by chemzqm** [comment]
You mean current word get replaced when confirm completion?

**Comment by tbo** [comment]
Correct.

**Comment by tbo** [comment]
@chemzqm Works like a charm. Thanks!
