### ISSUE TITLE
coc-settings.json shared between vim and nvim

### ISSUE THREAD

**Issue by amgodoi** [neoclide/coc.nvim#4407]
Is there any way to get coc-settings.json shared between vim and nvim?

I tried in init.vim:
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc

Works fine, but coc-settings.json is not loaded.

I solved using a symbolic link, but there is a better way?

**Comment by chemzqm** [comment]
Use `:h coc_config_home` or use `$VIMCONFIG` variable.

**Comment by amgodoi** [comment]
Hi!

coc_config_home worked.

Thanks a lot.
