### ISSUE TITLE
Since one can not have virtual texts in the middle, can one has all the inlay hints in the end?

### ISSUE THREAD

**Issue by judecumt** [neoclide/coc.nvim#4409]
**Is your feature request related to a problem? Please describe.**
I found inlay hints are very useful, but recently the inlay hints in the end are missing some members.
![image](https://user-images.githubusercontent.com/18454206/205430670-3c1f6339-a67d-4d8f-a4b4-ba023170ba89.png)
In the image above, only the middle paramter is displayed. If virtual texts are displayed in the middle, this is fine, but when they are in the end, it's confusing.

**Describe the solution you'd like**
Can one has all the inlay hints displayed in the end ?
Thanks.

**Comment by fannheyward** [comment]
Do you use clangd? Can't reproduce your issue.

<img width="370" alt="截屏2022-12-03 16 02 53" src="https://user-images.githubusercontent.com/345274/205431162-d776e0bf-c2e5-44c4-9bff-a8189b616506.png">

**Comment by judecumt** [comment]
Thanks for you reply.
Yes, I am using coc-langd and nvim.
![image](https://user-images.githubusercontent.com/18454206/205431730-b3f77827-21d7-4aa1-a583-5a882c920798.png)
In this picture, if parameter and variable have the same name, then the related inlay hints are missing.

**Comment by fannheyward** [comment]
> if parameter and variable have the same name, then the related inlay hints are missing

Reproduced, but this's clangd's issue, clangd doesn't returns hints in this case, same in VSCode + clangd.

**Comment by judecumt** [comment]
Thanks!
I should switch to vim for now.
