### ISSUE TITLE
Extensions list meaning

### ISSUE THREAD

**Issue by himat** [neoclide/coc.nvim#4411]
When I go into :CocList extensions
<img width="559" alt="image" src="https://user-images.githubusercontent.com/1156974/205486813-1a90c09c-0f07-4123-b72b-b10d6516329b.png">

what do the `*` vs `+` mean?

Is there somewhere I can read about what they mean for more help?

**Comment by fannheyward** [comment]
- `*`: activated
- `+`: loaded
- `-`: disabled
