### ISSUE TITLE
coc.nvim seems to change focussed pane when encountering linting error

### ISSUE THREAD

**Issue by fredrivett** [neoclide/coc.nvim#4415]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9000950
node version: v16.18.1
coc.nvim version: 0.0.82-068d135d 2022-12-02 22:53:01 +0800
coc.nvim directory: /Users/frivett/.vim/bundle/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2022-12-06T18:26:12.793 INFO (pid:57395) [plugin] - coc.nvim initialized with node: v16.18.1 after 57
```

## Describe the bug

When a linting error appears `coc.nvim` seems to change the focussed pane.

## Reproduce the bug

- Create file `vimrc` with:

```vim
set nocompatible                  " Must come first because it changes other options.
syntax on                         " Enable syntax highlighting
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'             " let Vundle manage Vundle, required
Plugin 'neoclide/coc.nvim'                " make vim act like an IDE

call vundle#end()
```

- Open vim into a project

- Open multiple vertical split panes with `:Vexplore`

- Navigate to a linting error

- See the focussed pane change automatically or on insert mode (I haven't got it reproducible 100% of the time but it's happening more often than not)

## Screenshots (optional)
<img width="698" alt="Screenshot_2022-12-06_at_18_50_10" src="https://user-images.githubusercontent.com/1713859/205997756-29a40a91-d794-4189-8e34-cc236f29bae4.png">

![Untitled](https://user-images.githubusercontent.com/1713859/205999430-81d8b1f4-0bbd-4563-bf15-2f71b16aefdf.gif)

**Comment by chemzqm** [comment]
Should be dup of #4396, try upgrade your vim.
