### ISSUE TITLE
[coc.nvim] Restarting server failed

### ISSUE THREAD

**Issue by geofflangenderfer** [neoclide/coc.nvim#4419]
## Result from CocInfo

```
## versions

vim version: NVIM v0.8.1
node version: v17.5.0
coc.nvim version: 0.0.82-33a68756 2022-11-29 02:29:36 +0800
coc.nvim directory: /Users/lgeoff/.config/nvim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-12-07T18:51:15.276 INFO (pid:43919) [plugin] - coc.nvim initialized with node: v17.5.0 after 87

```

## Describe the bug

unable to start haskell language server. I think this is an issue with trusting third party software on m1 mac. I'm not sure how to fix it. But i hope this a good way to gather info on how to. I think others will be having the same issue to. So collecting info to solve it will be helpful to many coc.nvim users

## Reproduce the bug

my vimrc is a mess and 800 lines long. Not sure how to reproduce it minimally besides starting from 0.

**Comment by geofflangenderfer** [comment]
looks like there's an issue in haskell language server repo: https://github.com/haskell/haskell-language-server/issues/2008

**Comment by fannheyward** [comment]
How do you setup haskell language server with coc.nvim? You can enable the verbose trace logs to debug the errors. https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

This properly is an issue with the server, coc.nvim is a client that just request to server.
