### ISSUE TITLE
Help with clojure-lsp workspace/executeCommand

### ISSUE THREAD

**Issue by Kazimazi** [neoclide/coc.nvim#442]
I've successfully got closuje-lsp running with coc. I've seen [here](https://github.com/snoe/clojure-lsp#refactorings) that it has some refactoring options. I've played around with `:call CocRequest()` tring to implement lsp specific commands... without any results. Can someone show how it's supposed to be done?

**Comment by chemzqm** [comment]
Something like:
```
	call CocRequest('clojure-lsp', 'workspace/executeCommand',
		\  {'command': 'introduce-let', 'arguments': [Expand('%:p'), line('.') - 1, col('.') - 1, input('Binding name: ')]})
```
Checkout https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand

**Comment by Kazimazi** [comment]
Thank you, it works.
