### ISSUE TITLE
echo language server messages to command line

### ISSUE THREAD

**Issue by marianpopeanga** [neoclide/coc.nvim#4420]
Is there a way to print the messages from the language servers with the progress on the command line instead of statusline ?
I am using vim-airline plugin and the status line is already in use and the language server messages won't show complete.

thanks

**Comment by fannheyward** [comment]
Try `notification.statusLineProgress` to false in your coc-settings.json, this will make progress showing in floating window.

**Comment by marianpopeanga** [comment]
Messages are still going to the status line even when setting notification.statusLineProgress to false in your coc-settings.json. 
I've disabled also the airline integration, but in this case is not showing any progress.

**Comment by fannheyward** [comment]
What type of the messages? Can you give some samples?

**Comment by chemzqm** [comment]
No, command line message might cause `press enter to continue`, the progress message could be created by StatusItem from coc extension.

**Comment by marianpopeanga** [comment]
There are many info messages from the LS with the progress, specially on large projects which can take minutes.
If the path with the file name is big enough, the status line using airline it doesn't have enough space to print these complete messages which also can print different paths with progress.
I haven't seen an issue with messages on the command line from the other plugins (e.g ALE or nvim-lsconfig)

**Comment by marianpopeanga** [comment]
Just don't close these tickets random.

**Comment by iamcco** [comment]
If the progress message echo to commamd line, your vim will be block by `press enter to continue` for each time the progress update.

**Comment by marianpopeanga** [comment]
@iamcco See the linked ticket. I've never got that message.
