### ISSUE TITLE
CocCommand:  xx not found

### ISSUE THREAD

**Issue by hongliang5316** [neoclide/coc.nvim#4429]
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/13626322/206900071-2238d861-a293-4d52-aae1-feccd81c8683.png">

**Comment by chemzqm** [comment]
`coc-lua` on npm registry is broken, use `coc-sumneko-lua` instead.

**Comment by chemzqm** [comment]
It's expected, coc-lua takes too long to activate.
