### ISSUE TITLE
coc-cmdline

### ISSUE THREAD

**Issue by yaocccc** [neoclide/coc.nvim#4440]
**Describe the solution you'd like**
请问 coc 是否类似于 https://github.com/hrsh7th/cmp-cmdline 的实现，我大致看了一下cmp的这个插件，但没看太懂

![1](https://user-images.githubusercontent.com/53512609/207544215-b889d7f8-f420-4d49-85dd-36656d70f20b.jpg)

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
目前应该没有

**Comment by yaocccc** [comment]
> 目前应该没有

好的赵哥，我来研究下是否有可能来实现类似的
