### ISSUE TITLE
Show full inline suggestion for completion items that have multiple lines

### ISSUE THREAD

**Issue by YangchaoYi** [neoclide/coc.nvim#4448]
**Is your feature request related to a problem? Please describe.**
When a completion item is a multiline string/code block, inline suggestion (pressing `<TAB>`) only shows the first line. For example, if a language server gives two completion items
1.  ```
    int a() {
      return 1;
    }
    ```
2.  ```
    int a() {
      return 2;
    }
    ```
The inline suggestion only shows `int a() {` for both items. 

**Describe the solution you'd like**
Ideally the entire completion item (code block) should be inserted in place after pressing `<TAB>` to give people a clearer preview. In the above example, after pressing `<TAB>`, inline suggestion would show
```
int a() {
  return 1;
}
```
Pressing `<TAB>` again would give
```
int a() {
  return 2;
}
```

**Describe alternatives you've considered**
None.

**Additional context**
Pressing `<CR>` (calling `coc#_select_confirm()`) does insert the entire item.
The text showing in the popup list for the code block is
```
int a() {^@  return 2;^@}
```

**Comment by chemzqm** [comment]
Insert line break would break undo/redo and make the completion unusable, you have to confirm completion.
