### ISSUE TITLE
Show docs automatically on cursor hover 

### ISSUE THREAD

**Issue by danebulat** [neoclide/coc.nvim#4449]
**Problem**

The configuration example provides a mechanism to show documentation for the symbol under the cursor via the `_G.show_docs()` function mapped to the `K` key. For developers who want to see the documentation popup automatically, immediately when the cursor hovers over part of the symbol, pressing `K` (or another key mapping) every time is not viable.

**Needed Solution**

As a Neovim user, I'd like an auto-command, or solution written in LUA, that automatically displays documentation for symbols when the cursor is over said symbols. This would be the same behaviour as pressing a key mapped to the `_G.show_docs()` command, but automatic, without having to press anything.

**Comment by chemzqm** [comment]
It seems there's no mouse hover on neovim, you can checkout `balloon-eval` which exits on gvim.
You can create a `CursorHold` autocmd with `CocAction('doHover')`

**Comment by vitaly-zdanevich** [comment]
Tried `autocmd CursorHold * CocAction('doHover')`

got

> E492: Not an editor command: CocAction('doHover')

**Comment by fannheyward** [comment]
@vitaly-zdanevich `autocmd CursorHold * call CocActionAsync('doHover')`

Make sure coc.vim is ready before call this action.

**Comment by chemzqm** [comment]
Checkout `:h CursorHold`
