### ISSUE TITLE
Is there any way to switch LSPs for one language at runtime?

### ISSUE THREAD

**Issue by lanza** [neoclide/coc.nvim#4452]
e.g. with ccls and clangd, I typically use ccls by default and always have it enabled. clangd is set to `"clangd.enable": false`. 

Occasionally I want to access some of clang's features at runtime and would like to bind something like

```
function g:ToggleBetwenClangdAndCCLS()
  ...
endfunction
```

but I haven't figured out how to make this work. Is this possible?

**Comment by fannheyward** [comment]
Maybe you can change configuration with `coc#config()` and call `CocRestart`?

**Comment by chemzqm** [comment]
Use `:h CocAction('toggleService')` and `:h CocAction('services')`
