### ISSUE TITLE
LocalConfig directory resolution confusion

### ISSUE THREAD

**Issue by flumm** [neoclide/coc.nvim#4453]
## Result from CocInfo

```
## versions

vim version: NVIM v0.8.1
node version: v16.18.1
coc.nvim version: 0.0.82-4ccdb97f 2022-12-22 22:33:20 +0800
coc.nvim directory: /home/flumm/.local/share/nvim/plugged/coc.nvim
term: screen-256color
platform: linux

## Log of coc.nvim

2022-12-23T09:43:56.499 INFO (pid:755337) [plugin] - coc.nvim initialized with node: v16.18.1 after 83
2022-12-23T09:44:00.143 INFO (pid:755337) [attach] - receive notification: showInfo []
```

## Describe the bug

Not completely sure if it's a but in the code or a bug in the documentation, but
the docs about configuration file says the following about the LocalConfig: 

> After a file is opened in vim, this directory is resolved from the parent directories of that file.

But it seems it does not iterate from the path of the opened file, but from the current working directory.

## Reproduce the bug

Have the following directory Structure

```
current_working_directory/
├─ A/
│  ├─ .vim/
│  │  ├─ coc-settings.json
│  ├─ B/
│  │  ├─ File
```
From the 'current_working_directory` open 'File' via

```
vim A/B/File
```

See that it did not load the settings from `current_working_directory/A/.vim/coc-settings.json`

Also using `:CocLocalConfig` tries to open `current_working_directory/.vim/coc-settings.json`

**Comment by fannheyward** [comment]
Document issue, the local configuration `.vim` is located in the root directory of the workspace.

**Comment by flumm** [comment]
Ok, so to understand the 'workspace' is always the current working directory where i opened the editor?

I have some projects where it would be nice to have different configs in different dirs, but i guess that is not really doable anyway with one editor instance, so i just have to change dir before i open the files.

**Comment by fannheyward** [comment]
The workspace isn't where you open vim, but the root resolved by coc.nvim with rootPatterns.

**Comment by chemzqm** [comment]
Current working directory is used first by default, see `:h coc-workspace-folders`
