### ISSUE TITLE
How to import component in react?

### ISSUE THREAD

**Issue by seriiserii825** [neoclide/coc.nvim#4456]
Hi.
GoodsPage code
```
const GoodsPage = () => {
  const [goods, setGoods] = useState([]);
  return (
    <div className="goods mt4">
      <div className="container">
        <h1>Goods</h1>
      </div>
    </div>
  );
};
export default GoodsPage;



```

useState is not imported. 
When cursor is under useState, i call this action `nmap ca <Plug>(coc-codeaction)`

And in popup i have those suggestion
https://imgur.com/4845IkF

But don't have import?

How can i do this? Thanks.

**Comment by chemzqm** [comment]
The server not send the fix you need, you may forget to install required typing in your project.

**Comment by chemzqm** [comment]
Or try `<Plug>(coc-codeaction-cursor)` and `<Plug>(coc-fix-current)` instead.
