### ISSUE TITLE
how to turn off function argument hints in c++

### ISSUE THREAD

**Issue by leaf-potato** [neoclide/coc.nvim#4458]
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/49188857/209458991-24d10a24-8a3c-465f-94b8-3411bce467b5.png">

**Comment by chemzqm** [comment]
`:h coc-config-inlayHint`

**Comment by oblitum** [comment]
They're indeed worth disabling in neovim, but should be **much** better in vim now.
