### ISSUE TITLE
Additional display of information from vscode

### ISSUE THREAD

**Issue by dan4ik605743** [neoclide/coc.nvim#4460]
There is a cool feature in vscode, hovering over any variable shows its data type.
![image](https://user-images.githubusercontent.com/86075850/209917862-82801185-8d84-46b9-9d6f-c5ed9f187cb8.png)
![image](https://user-images.githubusercontent.com/86075850/209917819-9eb8a508-13f8-4971-adfc-8ef40a215917.png)

![image](https://user-images.githubusercontent.com/86075850/209917931-c675e5c8-8c3d-40c7-aa82-485200f4dfb6.png)
![image](https://user-images.githubusercontent.com/86075850/209918028-d1e3bcf5-2813-4333-837c-b6ce1f986104.png)
And if you try to point to other things, there may also be useful information, I would like the same thing in coc-nvim, using a hotkey.

**Comment by fannheyward** [comment]
Check `:h coc-hover`.

**Comment by dan4ik605743** [comment]
THX!
