### ISSUE TITLE
TextYankPost and CocActionAsync("highlight") conflict on neovim

### ISSUE THREAD

**Issue by sabah1994** [neoclide/coc.nvim#4462]
I am trying to solve this issue https://github.com/neoclide/coc.nvim/issues/2452

I want to cancel the highlight and my assumption was it would work on ```doautocmd CursorMoved```. 
It doesn't but strangely, If I do ```doautocmd CursorMovedI``` (I at the end), it does work but only once. If the cursor position remains same it no longer works.

You mentioned ```vim.highlight``` how exactly can I do it?

**Comment by fannheyward** [comment]
> increase priority for vim.highlight

It's `vim.highlight.priorities`, check `:h vim.highlight.priorities`.

**Comment by chemzqm** [comment]
`:h coc-config-documentHighlight-priority`, you need use `matchadd` to add window highlight with higher priority.

**Comment by chemzqm** [comment]
Or check if highlight for yank region exists before `call CocActionAsync('highlight')`
