### ISSUE TITLE
vim9.0 使用 coc-clangd inlayHints 总是显示在末尾。

### ISSUE THREAD

**Issue by yangyagami** [neoclide/coc.nvim#4464]
vim9.0 使用 coc-clangd inlayHints 总是显示在末尾。
![image](https://user-images.githubusercontent.com/45322657/210505136-667e3186-ac34-48da-936d-397ced64f7e0.png)

**Comment by fannheyward** [comment]
你的 vim 9 具体版本是多少？

**Comment by yangyagami** [comment]
> 



> 你的 vim 9 具体版本是多少？

9.0.1140

**Comment by fannheyward** [comment]
你的 clangd 版本是多少？请升级到 clangd 15，clangd 支持两种 inlayHint 协议，coc-clangd 都进行了支持，其中 14 版本是 clangd 私有协议，coc-clangd 自己进行设置在行末，15版本开始是 coc.nvim 进行设置展示。

**Comment by yangyagami** [comment]
谢谢



---- 回复的原邮件 ----
| 发件人 | Heyward ***@***.***> |
| 日期 | 2023年01月05日 09:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [neoclide/coc.nvim] vim9.0 使用 coc-clangd inlayHints 总是显示在末尾。 (Issue #4464) |

你的 clangd 版本是多少？请升级到 clangd 15，clangd 支持两种 inlayHint 协议，coc-clangd 都进行了支持，其中 14 版本是 clangd 私有协议，coc-clangd 自己进行设置在行末，15版本开始是 coc.nvim 进行设置展示。
