### ISSUE TITLE
Can coc-rename auto save changed files?

### ISSUE THREAD

**Issue by whitelilis** [neoclide/coc.nvim#4470]
**Is your feature request related to a problem? Please describe.**
After call (coc-rename) on a function , if the change happen in multiple files, then LSP go-to-define and go-to-reference  will not work right. Now run cmd "wa" save all files, the LSP will work well.

**Describe the solution you'd like**
So can (coc-rename) auto save changed files?

**Describe alternatives you've considered**
I nmap a key like the following:
```
<Plug>(coc-rename) <cmd>wa<cr>
```
but no effect

**Additional context**

**Comment by fannheyward** [comment]
No such feature yet, you need to `wa` after rename action.

**Comment by chemzqm** [comment]
You can use callback function for `CocActionAsync()` as the last argument.
