### ISSUE TITLE
signcolumn is drawn on popup menu and documentation after setting statuscolumn (stc) in v9.0

### ISSUE THREAD

**Issue by huibosa** [neoclide/coc.nvim#4471]
## Describe the bug

With the new `statuscolumn` introduced in neovim 0.9, to have signcolumn displayed right of line number, I've set:

```
let &stc='%=%{v:lnum}%s'
```

which makes a signcolumn to displayed on popup menu and documentation.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden

  let &stc='%=%{v:lnum}%s'
  ```

## Screenshots (optional)
Screenshots on mini.vim:

![image](https://user-images.githubusercontent.com/78707242/212078482-500ee72d-8b97-4f3e-a80e-639a5e643d29.png)

![image](https://user-images.githubusercontent.com/78707242/212076374-b81d66a6-1067-4118-b403-a7fa0f8be7b3.png)
![image](https://user-images.githubusercontent.com/78707242/212076483-cdeb5339-a900-4675-a64c-ce1839612c01.png)

**Comment by fannheyward** [comment]
Reproduced.
