### ISSUE TITLE
[help wanted] how to set the floating window text color?

### ISSUE THREAD

**Issue by zl03jsj** [neoclide/coc.nvim#4473]
hi, guys, the text color of method doc floating window seems weird.
i wander how to change it, thanks.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/10127848/212273029-0627bbb3-68db-499e-9a90-7cba842505c1.png">

**Comment by fannheyward** [comment]
It's `CocErrorFloat`, for error text in floating windows/popups, check `:h coc-highlights-float`.

**Comment by chemzqm** [comment]
`:h coc-highlights-float`
