### ISSUE TITLE
Question: Golang Folding behavior in COC

### ISSUE THREAD

**Issue by pradyumnac** [neoclide/coc.nvim#4474]
Currently, Folding for gofiles leaves the end "}" out of the fold
Same with import

Is this designed Intentionally like this? I am triggering folding using :

```vimL
" Add `:Fold` command to fold current buffer
command! -nargs=? Fold :call     CocAction('fold', <f-args>)
nnoremap <silent><nowait> <space>F  :Fold<cr> 
```

![image](https://user-images.githubusercontent.com/1647108/212466717-07acdcbd-a334-489a-b5cd-2847ec3845b9.png)

**Comment by fannheyward** [comment]
The `CocAction('fold')` will request `foldingRange` from LS, here's `gopls`, then fold codes in vim, with the same fold style like VSCode, leaving `}` in new line.

**Comment by chemzqm** [comment]
Use `:h 'foldtext'` for better fold text.
