### ISSUE TITLE
Have `diagnostic.refreshOnInsertMode` also not refresh during snippet mode

### ISSUE THREAD

**Issue by lanza** [neoclide/coc.nvim#4478]
When `diagnostic.refreshOnInsertMode` is `false`, you still get diagnostics refreshing due to the snippet insertion mechanism. See here:

https://user-images.githubusercontent.com/12656790/212824619-a4dcd7fc-093c-4662-84d7-ec9f860c9b12.mov

The snippet mechanism first moves to `visual` and then `select` modes and thus the diagnostics are refreshed.

My feature request would to extend `diagnostic.refreshOnInsertMode`'s behavior to also exclude the snippet mechanism. Perhaps a proper description would be `diagnostic.refreshOnlyInNormalMode`?

**Comment by lanza** [comment]
Also, as a secondary request would it be reasonable to implement the snippet expansion mechanism in fewer UI updates? I imagine it's probably pretty clunky to actually handle that. But you can observe in this clip if you go frame by frame that we end up with one action (accepting the snippet) being implemented across 4 frames

1: text inserted
<img width="319" alt="image" src="https://user-images.githubusercontent.com/12656790/212826007-5b64f69e-12c4-45c9-b385-2a4966c98535.png">

2: snippet expanded
<img width="598" alt="image" src="https://user-images.githubusercontent.com/12656790/212826071-ff12a167-672b-4f67-bcb1-e51f08d826bd.png">

3: signature panel shown
<img width="872" alt="image" src="https://user-images.githubusercontent.com/12656790/212826121-c6364602-e6b2-477d-bdf5-83acd3bc7a1e.png">

4: diagnostic inserted
<img width="933" alt="image" src="https://user-images.githubusercontent.com/12656790/212826160-5f1064bd-b949-4d27-994f-f57af44d0258.png">

**Comment by fannheyward** [comment]
Will check this later.

**Comment by chemzqm** [comment]
It's expected to refresh on select mode, you will have to use `:h b:coc_diagnostic_disable` and `:h ModeChanged` autocmd which may not exists on your vim.
