### ISSUE TITLE
My NeoVim freezes when editing file

### ISSUE THREAD

**Issue by zezic** [neoclide/coc.nvim#448]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.3.1
node version: v11.0.0
coc.nvim version: 0.0.55
term: xterm
platform: linux

## Error messages

## Output channel: languageserver.ccls
...
```

**Describe the bug**
Every time I edit file with enabled coc.nvim I get freeze after ~25 or maybe 30 keystrokes. I tried to edit cpp and pug files. Every time my NeoVim is in freeze I see `node ... /coc.nvim/bin/server.js` is eating 100% of CPU core, if I kill that process my NeoVim will become responsive again.

**To Reproduce**
1. Open file in NeoVim with coc.nvim enabled
2. Start editing file

Looks like this problem is only specific for my setup. How can I debug it?

**Comment by chemzqm** [comment]
> node version: v11.0.0

Is known to be buggy, change to use binary release or upgrade your node, or set `g:coc_node_path` to another node executable.

**Comment by zezic** [comment]
Thank you for fast reply! It looks like upgrading Node to v11.10.0 solved this issue.
