### ISSUE TITLE
formatOnType not working for cpp

### ISSUE THREAD

**Issue by XJDKC** [neoclide/coc.nvim#4482]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9001200
node version: v16.15.0
coc.nvim version: 0.0.82-b11a93ba 2022-12-25 15:19:13 +0800
coc.nvim directory: /Users/xjdkc/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2023-01-23T02:22:04.103 INFO (pid:75417) [plugin] - coc.nvim initialized with node: v16.15.0 after 96
2023-01-23T02:22:06.984 INFO (pid:75417) [services] - LanguageClient clangd state change: stopped => starting
2023-01-23T02:22:06.987 INFO (pid:75417) [language-client-index] - Language server "clangd" started with 75419
2023-01-23T02:22:07.022 INFO (pid:75417) [services] - LanguageClient clangd state change: starting => running
2023-01-23T02:22:07.027 INFO (pid:75417) [services] - service clangd started
```

## Describe the bug

formatOnType option doesn't work for cpp files.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Install coc-clangd extension
  ```
  :CocInstall coc-clangd
  ```

- enable formatOnType in coc-settings
  ```json
  {
    "coc.preferences.formatOnType": true,
    "coc.preferences.formatOnTypeFiletypes": [
      "cpp"
    ]
  }
  ```

- Start vim with command: `vim -u mini.vim`

- Operate vim.
  - Create a cpp file and enter 
    ```c++
    #include <iostream>
    int main() {
      for (int i=0;i<5;++i){<CURSOR><CR>}
    }
    ```
  - Expected result
    ```c++
    #include <iostream>
    int main() {
      for (int i = 0; i < 5; ++i) {
        <CURSOR>
      }
    }
    ```

**Comment by chemzqm** [comment]
Seems coc-clangd not support format on type by default `:h coc-format-ontype`

**Comment by chemzqm** [comment]
Your key-mapping not work or you have disabled `coc.preferences.bracketEnterImprove`

**Comment by XJDKC** [comment]
> Your key-mapping not work or you have disabled `coc.preferences.bracketEnterImprove`

The output of `:verbose imap <cr>`:
```vim
Kitty keyboard protocol: Cleared
i  <CR>        * coc#pum#visible() ? coc#pum#confirm() : "\<C-G>u\<CR>\<C-R>=coc#on_enter()\<CR>"
        Last set from ~/.vim/mini.vim line 6
```

Updated coc-settings.json
```json
{
  "coc.preferences.bracketEnterImprove": true,
  "coc.preferences.formatOnType": true,
  "coc.preferences.formatOnTypeFiletypes": [
    "cpp"
  ]
}
```

The line where for loop is located is still not formatted.

I'm not familiar with coc.nvim, but after I add `await self.formatCurrentBuffer()` below [format.ts#L118](https://github.com/neoclide/coc.nvim/blob/master/src/handler/format.ts#L118) or [format.ts#L124](https://github.com/neoclide/coc.nvim/blob/master/src/handler/format.ts#L124), I get the expected result. But it will format the whole document, I think this's not the intent of formatOnType.

**Comment by chemzqm** [comment]
Can't reproduce with vim 9.0.1200, `bracketEnterImprove` work as expected for me.
