### ISSUE TITLE
Coc Cmdline Support

### ISSUE THREAD

**Issue by UnrealApex** [neoclide/coc.nvim#4487]
**Is your feature request related to a problem? Please describe.**
It would be nice if Coc had command line completion similar to [cmp-cmdline](https://github.com/hrsh7th/cmp-cmdline).

**Describe the solution you'd like**
A solution would be a Coc extension for this.
**Describe alternatives you've considered**
An alternate option is using [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) with [cmp-cmdline](https://github.com/hrsh7th/cmp-cmdline).

**Comment by chemzqm** [comment]
My suggestion is use another plugin like https://github.com/smolck/command-completion.nvim
