### ISSUE TITLE
能否提供coc美化的设置

### ISSUE THREAD

**Issue by xinghe98** [neoclide/coc.nvim#4493]
感谢作者的创作，近日尝试lsp+cmp，发现体验上不如coc，但是很遗憾我阅读文档没有找到coc里面有类似于lsp那样的美化插件，目前只找到function之类的图标设置，但是提示框没有边框之类的，是有我没找到吗？

**Comment by fannheyward** [comment]
`:h coc-config-float`, supports `diagnostic.floatConfig`, `hover.floatConfig`, `suggest.floatConfig` etc.
