### ISSUE TITLE
How to make diagnosticc print only in virtual text？

### ISSUE THREAD

**Issue by gitzhangzhao** [neoclide/coc.nvim#4503]
Hello, I have set diagnostic to use virtual text to display at the end of each line. I do not want diagnostic to be displayed on the cmd line and float, is there any way?

**Comment by Wadekiny** [comment]
`coc-settings.json`:

```
"diagnostic.enableMessage": "never",
```

**Comment by gitzhangzhao** [comment]
thank you.👍
