### ISSUE TITLE
Unknown function: coc#util#editor_winids on api "eval"

### ISSUE THREAD

**Issue by ChenDaxia-Sudo** [neoclide/coc.nvim#4508]
![image](https://user-images.githubusercontent.com/52773833/217243946-911cf166-2630-4d2a-98ba-5f902df02d7d.png)

I upgraded the coc.nvim just now, and the bug above occurs.

**Comment by fannheyward** [comment]
What's your `:CocInfo`? Upgrade your coc.nvim to latest release.
