### ISSUE TITLE
Using a non-ascii snippet indicator results in misaligned popup data

### ISSUE THREAD

**Issue by ilAYAli** [neoclide/coc.nvim#451]
**To Reproduce**
put e.g the following in `coc-settings.json`:
coc.preferences.snippetIndicator": "⭐︎",

(observe right column)
**Screenshots**
![screenshot 2019-02-18 at 11 57 59](https://user-images.githubusercontent.com/1106732/52946593-a50fa680-3374-11e9-924a-e15d64820092.png)

**Comment by chemzqm** [comment]
Should be problem of your vim with your terminal, I don't have this issue on vim8 and neovim.
Consider upgrade vim/neovim.

**Comment by ilAYAli** [comment]
👍🏻
I verified this with both iTerm2 and Alacritty on MacOS Mojave, but you are correct, I was able to solve the problem in iTerm2 by enabling:
`Preferences` -> `Profiles` -> `Text` -> `Use Unicode version 9 widths`
