### ISSUE TITLE
The map of <TAB> and coc not works

### ISSUE THREAD

**Issue by zzReno** [neoclide/coc.nvim#4512]
-- Use Tab for trigger completion with characters ahead and navigate
-- NOTE: There's always a completion item selected by default, you may want to enable
-- no select by setting `"suggest.noselect": true` in your configuration file
-- NOTE: Use command ':verbose imap <tab>' to make sure Tab is not mapped by
-- other plugins before putting this into your config
local opts = {silent = true, noremap = true, expr = true, replace_keycodes = false}
keyset("i", "<TAB>", 'coc#pum#visible() ? coc#pum#next(1) : v:lua.check_back_space() ? "<TAB>" : coc#refresh()', opts)
keyset("i", "<S-TAB>", [[coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"]], opts)

-- Make <CR> to accept selected completion item or notify coc.nvim to format
-- <C-g>u breaks current undo, please make your own choice
keyset("i", "<cr>", [[coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"]], opts)

The configuration above not work!

This is my init.lua
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/47785806/218266438-4bceebde-1054-472c-90ae-15ed8244a4d4.png">

All my files(not configured TAB at other place):
<img width="287" alt="image" src="https://user-images.githubusercontent.com/47785806/218266518-81e45b2f-451a-473f-94ca-cb9abbf768b2.png">

**Comment by fannheyward** [comment]
Check `:verbose imap <tab>`, should be problem of your configuration.
