### ISSUE TITLE
<TAB> is not work, but <S-TAB> is working

### ISSUE THREAD

**Issue by ttzorztt** [neoclide/coc.nvim#4513]
## Result from CocInfo

![2023-02-12 15-08-00 的屏幕截图](https://user-images.githubusercontent.com/95260255/218297864-a747ee02-a2cc-4231-ad3b-8a83188fcd91.png)

## Describe the bug

<TAB>Shortcut keys have no effect, but shortcut<S-TAB> keys do. It shouldn't be an issue with shortcut key conflicts.

## Reproduce the bug

- Create file `mini.vim` with：
  > I don't know if it's a shortcut key violation, so I provided the full .vimrc

let g:mapleader=' '
set termencoding=utf-8
set encoding=utf-8
set number "设置行号
set modifiable " 可修改的
syntax enable " 语法高亮
set autoindent "自动缩进
set tabstop=2 "top所等同的空格长度
set shiftwidth=2 "自动缩进所使用的空格长度，建议与tabstop相同
set softtabstop=2
set list
set tw=0
set indentexpr=
set backspace=indent,eol,start
set foldmethod=indent
set foldlevel=99
au BufReadPost * if line("'\'") > 1 && line("'\'") <= line("$") | exe "normal! g'\'" | endif
set showmatch "匹配模式，类似当输入一个左括号时会匹配相应的右括号
"set guioptions+=m "显示菜单栏
"set guioptions+=T "显示工具栏
set ruler "启动标尺
"set nohls "关闭寻找匹配高亮显示
set hlsearch
set incsearch "递进搜索，随着你的输入不断更新
set ignorecase "搜索不区分大小写
set autoread "当文件被改动时自动载入
"set laststatus=2 "显示文件名
filetype plugin on "允许插件
set clipboard^=unnamed,unnamedplus "yp与系统剪贴板打通
" set makeprg=g++\ -Wall\ \ % ”make设置
set autowrite "自动保存
set cursorline "高亮显示当前行
set magic "正则表达式
set nocompatible "关闭兼容vi
set tags=/media/tmd/CODE/git/tmdsql/tags "ctags
"set bg=dark "背景色
"colorscheme one "主题
set relativenumber "添加前后几行
let g:coc_disable_startup_warning = 1 "取消警告
"大写S保存
map <C-s> :w<CR>
"删除小写s的功能
map s <nop>
" 刷新
map R :source $MYVIMRC<CR>
map q :q<CR>
" 搜索下一个
noremap = nzz
" 搜索上一个
noremap - Nzz
" ctrl + N转换 TAB
set scrolloff=6 "使得光标剧中
"map <LEADER>sc :set spell!<CR> "拼写检查
"保存
map Q :wq<CR>
"注释
map c# :normal I//<CR>
map p# :normal I#<CR>

map <C-h> :set nosplitright<CR>:vsplit<CR>
map <C-j> :set nosplitbelow<cR>:split<CR>
map <C-k> :set splitbelow<CR>:split<CR>
map <C-l> :set splitright<CR>:vsplit<CR>

map J <C-W>j
map H <C-W>h
map K <C-W>k
map L <C-W>l

map <up> :res +5<CR>
map <down> :res - 5<CR>
map <left> :vertical resize -5<CR>
map <right> :vertical resize +5<CR>

map > :+tabnext<CR>
map < :-tabnext<CR>

call plug#begin('~/.config/nvim/plugged')
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'neoclide/coc.nvim', {'tag': '*', 'branch': 'release'}
Plug 'Chiel92/vim-autoformat'
Plug 'scrooloose/nerdtree'
Plug 'SirVer/ultisnips'
Plug 'vim-scripts/DoxygenToolkit.vim'
Plug 'honza/vim-snippets'
Plug 'Yggdroot/indentLine'
Plug 'vim-airline/vim-airline-themes'
Plug 'bling/vim-airline'
Plug 'connorholyday/vim-snazzy'
Plug 'dense-analysis/ale'
Plug 'majutsushi/tagbar'
Plug 'iamcco/markdown-preview.nvim'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
Plug 'luochen1990/rainbow'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'tpope/vim-commentary'

"leaderf 配置
map ff :LeaderfFunction<CR>
map fl :LeaderfLine<CR>

"rainbow 配置
let g:rainbow_active = 1
let g:rainbow_conf = {
\   'guifgs': ['darkorange3', 'seagreen3', 'royalblue3', 'firebrick'],
\   'ctermfgs': ['lightyellow', 'lightcyan','lightblue', 'lightmagenta'],
\   'operators': '_,_',
\   'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
\   'separately': {
\       '*': {},
\       'tex': {
\           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
\       },
\       'lisp': {
\           'guifgs': ['darkorange3', 'seagreen3', 'royalblue3', 'firebrick'],
\       },
\       'vim': {
\           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
\       },
\       'html': {
\           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
\       },
\       'css': 0,
\   }
\}

"vim-indent-guides 配置
let g:index_guides_guide_size=1
let g:index_guides_start_level=2
let g:index_guides_enable_on_vim_startup=1

"preview配置

map M :MarkdownPreview<CR>
let g:mkdp_browser = 'chromium'
"tagbar配置
let g:tagbar_ctags_bin='/usr/bin/ctags'  " 设置ctags所在路径
let g:tagbar_width=30 " 设置tagbar的宽度
map tb :TagbarToggle<CR>

"ale配置
let g:ale_set_highlights = 0
"自定义error和warning图标
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚡'
"在vim自带的状态栏中整合ale
let g:ale_statusline_format = ['✗ %d', '⚡ %d', '✔ OK']
"显示Linter名称,出错或警告等相关信息
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
"打开文件时不进行检查
let g:ale_lint_on_enter = 0

"普通模式下，sp前往上一个错误或警告，sn前往下一个错误或警告
nmap sp <Plug>(ale_previous_wrap)
nmap sn <Plug>(ale_next_wrap)
"<Leader>s触发/关闭语法检查
nmap <Leader>s :ALEToggle<CR>
"<Leader>d查看错误或警告的详细信息
nmap <Leader>d :ALEDetail<CR>
"使用clang对c和c++进行语法检查，对python使用pylint进行语法检查
let g:ale_linters = {
\   'c++': ['clang'],
\   'c': ['clang'],
\   'python': ['pylint'],
\}

"vim-snazzy配置
color snazzy
"let g:SnazzyTransparent = 1
"airline配置
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
" indentLine 配置
let g:index_guides_guide_size = 1
let g:index_guides_start_level = 1

"ultisnips的配置
" let g:UltiSnipsExpandTrigger="<tab>"
" let g:UltiSnipsEditSplit="vertical" "使用 UltiSnipsEdit 命令时垂直分割屏幕
" let g:UltiSnipsJumpForwardTrigger="<tab>"
" let g:UltiSnipsJumpBackwardTrigger="<S-tab>" " 使用 tab 切换下一个触发点，shit+tab 上一个触发点
" let g:UltiSnipsSnippetDirectories=["/media/tmd/CODE/git/snippets/vim-snippets"] "片段路径

"DoxygenToolkit配置
let g:DoxygenToolkit_briefTag_pre="@brief "
let g:DoxygenToolkit_paramTag_pre="@Param "
let g:DoxygenToolkit_returnTag="@Return "
let g:DoxygenToolkit_authorName="TMD"
let g:DoxygenToolkit_licenseTag="TMDSQL 1.3"
let g:doxygen_enhanced_color = 1
let g:load_doxygen_syntax = 1
map df :Dox<CR>
map da :DoxAuthor<CR>
map db :DoxBlock<CR>
"autoformat 配置
let g:autoformat_indent = 2

"nerdtree 配置
"autocmd vimenter * NERDTree "自动打开
map tt :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif "当NERDTree为剩下的唯一窗口时自动关闭
"关闭nerdtree
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'
let NERDTreeAutoCenter=1
let NERDTreeShowLineNumbers=1 " 显示行号
let NERDTreeShowHidden=1 " 是否显示隐藏文件
let NERDTreeWinSize=20 "设置宽度
let NERDChristmasTree=1       "显示增强
let g:nerdtree_tabs_open_on_console_startup=1 "在终端启动vim时，共享NERDTree
let g:NERDTreeIndicatorMapCustom = {
			\ "Modified"  : "✹",
			\ "Staged"    : "✚",
			\ "Untracked" : "✭",
			\ "Renamed"   : "➜",
			\ "Unmerged"  : "═",
			\ "Deleted"   : "✖",
			\ "Dirty"     : "✗",
			\ "Clean"     : "✔︎",
			\ 'Ignored'   : '☒',
			\ "Unknown"   : "?"
			\ }

"cocSetting
" :CocList marketplace 来查看可以安装的coc的插件
let g:coc_global_extensions = [
			\ 'coc-vimlsp',
			\ 'coc-marketplace',
			\ 'coc-json',
			\ 'coc-pyright',
			\ 'coc-clangd',
			\ '@yaegassy/coc-marksman',
			\ 'coc-snippets',
			\ 'coc-git',
			\ 'coc-highlight',
			\'coc-vimlsp']
set hidden "TextEdit might fail if hidden is not set.  Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable delays and poor user experience.  set updatetime=100 Don't pass messages to |ins-completion-menu|.  set shortmess+=c Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("nvim-0.5.0") || has("patch-8.1.1564")
	" Recently vim can merge signcolumn and number column into one
	set signcolumn=number
else
	set signcolumn=yes
endif
inoremap <expr><TAB>
			\ coc#pum#visible() ? coc#pum#next(1) :
			\ CheckBackspace() ? "\<Tab>" :
			\ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

function! s:check_back_space() abort
	let col = col('.') - 1
	return !col || getline('.')[col - 1]  =~# '\s'
endfunction

inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                             \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
	let col = col('.') - 1
	return !col || getline('.')[col - 1]  =~# '\s'
endfunction

nmap <silent> <LEADER>- <PLug>(coc-diagnostics-prev)
nmap <silent> <LEADER>= <PLug>(coc-diagnostics-next)

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use T to show documentation in preview window
nnoremap <silent> T :call ShowDocumentation()<CR>

function! ShowDocumentation()
	if CocAction('hasProvider', 'hover')
		call CocActionAsync('doHover')
	else
		call feedkeys('K', 'in')
	endif
endfunction

function! s:cocActionsOpenFromSelected(type) abort
	execute 'CocCommand actions.open '. a:type
endfunction
xmap <silent> <lender>a :<C-u>execute 'CocCommand actions.open ' . visualmode() <CR>
nmap <silent> <leader>a :<C-u>set operatorfunc=<SID>cocActionsOpenFromSelected<CR>g@

" other plugin before putting this into your config.
" Highlight the symbol and its references when holding the cursor.

" Symbol renaming.
augroup mygroup
	autocmd!
	" Setup formatexpr specified filetype(s).
	autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
	" Update signature help on jump placeholder.
	autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end
" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')
" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)
" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')
" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
call plug#end()

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

> '>' The symbol '>' is one of the plugin prompts, meaning I entered a <TAB>key here
![1](https://user-images.githubusercontent.com/95260255/218297501-83684db6-cb90-4128-a24d-5a1294dc1a77.png)
![2](https://user-images.githubusercontent.com/95260255/218297503-6117abc3-6d07-432d-9ca2-f94ea0bd9f9d.png)

**Comment by fannheyward** [comment]
Check `:verbose imap <tab>`, should be problem of your configuration.

**Comment by ttzorztt** [comment]
After I executed the instructions you provided, it showed the following, another photo is the content of the target file, I tried to remove that plugin and reinstall it, but it still prompts to be modified.

![2023-02-13 16-01-11 的屏幕截图](https://user-images.githubusercontent.com/95260255/218402453-8f30b92b-ecee-47f6-b634-93889cc47890.png)
![2023-02-13 16-01-06 的屏幕截图](https://user-images.githubusercontent.com/95260255/218402440-5fc195fb-b355-4f51-97bc-68f68b029198.png)

**Comment by fannheyward** [comment]
Your `<tab`> is remapped by UltiSnips.

**Comment by ttzorztt** [comment]
我将这个插件删除后运行正常，谢谢您的帮助
