### ISSUE TITLE
Semantic Highlighting in comments only

### ISSUE THREAD

**Issue by SeniorMars** [neoclide/coc.nvim#4517]
**Is your feature request related to a problem? Please describe.**
Today I messed around with semantic highlighting, and I love it for highlighting rust code inside doc comments. However, I found the highlighting to conflict with many of my tree sitter highlights. I understand I can change all the highlights, but I realized that it would be better for me if there was a way to enable semantic highlighting in comments or to change the priority of particular highlights.

**Describe the solution you'd like**
Allow changing priority for some highlights or allow semantic highlighting in comments only.

**Describe alternatives you've considered**
Changing my highlights to work with tree-sitter.

**Additional context**
I wasn't sure to post it here or in coc-rust-analyzer

**Comment by fannheyward** [comment]
> conflict with many of my tree sitter highlights

coc's semanticToken highlighting can use nvim-treesitter's highlight groups, there shouldn't any conflicts, check `:h CocSem`.

> changing priority for some highlights

Check `:h coc-config-semanticTokens-highlightPriority`.

**Comment by SeniorMars** [comment]
Thank you, i'll look more into these!
