### ISSUE TITLE
Force fold again when completion is triggered

### ISSUE THREAD

**Issue by laggardkernel** [neoclide/coc.nvim#452]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

```
## versions

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.55
term: iTerm.app
platform: darwin
## Error messages
```

**Describe the bug**
I use fold in my neovim config `init.vim` and the config is folded by default with

```vim
" vim:foldmethod=marker:foldlevel=0:shiftwidth=2
```

After installing coc.nvim. Whenever completion is triggered (basically whenever I switch to Insert Mode in `init.vim`), all the content is folded again.

It seems it's related a low `updatetime`. Use the config below, unfold the content, insert text in the fold part. This should reproduce the behavior.

```vim
if has('nvim')
  call plug#begin('~/.local/share/nvim/plugged')
else
  call plug#begin('~/.vim/plugged')
endif
" coc {{{
" vim-node-rpc is needed for Vim
Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}

" }}}
" Initialize plugin system
call plug#end()
set updatetime=300

" vim:foldmethod=marker:foldlevel=0:shiftwidth=2
```

Set `updatetime` higher (default 4000) could avoid the problem.

**To Reproduce**

**Screenshots**

**Comment by chemzqm** [comment]
Please provide minimal init.vim.

**Comment by laggardkernel** [comment]
@chemzqm Just updated the issue. It seems the behavior is related to low `updatetime` value.

**Comment by chemzqm** [comment]
It's caused by  triggered by coc, I think it should be removed.

**Comment by vignesh0025** [comment]
I am facing the same issue. Everything was working file until a while ago. I am facing the exact same issue under the exact same condition. Settting updatetime to 4000 did not solve the issue. How should I proceed ?

**Comment by comfortablynick** [comment]
I am experiencing the same issue with folds opening and closing while typing in insert mode in my init.vim. It renders coc unusable unless I disable the folding.

My init.vim modeline:
```vim
" vim:fdm=marker:fdl=1:
```

Minimal init.vim:
```vim
set nocompatible
set runtimepath=$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after
let g:python3_host_prog = $NVIM_PY3_DIR

" coc.nvim is installed at ~/vim-test/pack/test/start/coc.nvim
set runtimepath^=~/vim-test
let &packpath=&runtimepath

filetype plugin indent on
syntax enable
```

**Comment by oblitum** [comment]
Maybe this should be reopened? It's not clear at which point it was supposed to have been fixed. I cannot reproduce this issue, maybe another issue should be open with issue template filled with new details.

**Comment by tomtomjhj** [comment]
Putting `nomodeline` on the modeline worked for me. 
```vim
" vim: set foldmethod=marker foldlevel=0 nomodeline:
```

**Comment by comfortablynick** [comment]
> Putting `nomodeline` on the modeline worked for me. 

This seems to work for me. I wonder why this is needed? Without this coc is unusable inside folds if I have `fdl` set in the modeline.

So I guess I have to edit all my files to add `noml` to every modeline...

**Comment by tomtomjhj** [comment]
#2292 fixes this issue.
