### ISSUE TITLE
Very Slow BufWritePre (> 10 [sec]) even without extensions

### ISSUE THREAD

**Issue by JJdeVries** [neoclide/coc.nvim#4527]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9000749
node version: v16.14.2
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /home/jorik/.vim/bundle/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2023-02-17T16:37:13.448 INFO (pid:214808) [plugin] - coc.nvim initialized with node: v16.14.2 after 142
2023-02-17T16:37:15.172 INFO (pid:214808) [attach] - receive notification: showInfo []
```

## Describe the bug
When writing some files (reproducible for YAML, JSON, rosmsg, git commit message) the BufWritePre method of coc can take very long and sometimes even timeout (after 60 seconds). This even occurs on file types where there are no formatters or language servers installed (e.g. ros message files, which are small text files describing a message structure).

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

The above `mini.vim` already reproduces the error for me.

## Logs
I've inserted a small section of the logging of coc.vim:
``` 

  9.790703 : SafeState: reset: key typed
  9.790905 SEND on 0(in): '[1,["CocAutocmd",["BufWritePre",1,"Axis.msg",4]]]
'
  9.790917 on 0: Blocking read JSON for id 1
  9.790920 : looking for messages on channels
  9.790923 on 0: Waiting for up to 60000 msec
 13.117816 RECV on 0(out): '["call","coc#api#call",["call_function",["coc#util#get_buf_lines",[1,3]]],-6]
'
 13.117832 : looking for messages on channels
 13.117846 on 0: Calling 'coc#api#call'
 13.117948 SEND on 0(in): '[-6,[null,{"changedtick":4,"lines":["# The message defaults to zero, so UNKNOWN is 0","","uint8 UNKNOWN     = 0","uint8 FORWARD     = 1","uint8 RIGHT       = 2","uint8 UP          = 3","uint8 YAW         = 4   # Opposite of heading!","uint8 PITCH       = 5   # Bow up","uint8 ROLL        = 6   # Port up","uint8 WINCH_SPEED = 7","uint8 CAMERA_ZOOM = 8","uint8 CAMERA_TILT = 9","","uint8 COUNT       = 10","","uint8 id"]}]]
'
 13.117961 : looking for messages on channels
 13.117964 on 0: Waiting for up to 60000 msec
 32.426590 RECV on 0(out): '[1,[null,null]]
'
 32.426607 on 0: Getting JSON message 1
 32.426630 on 0: Received JSON for id 1
 32.426807 RECV on 0(err): 'Slow "BufWritePre" handler detected s
    at sk.on (/home/jorik/.vim/bundle/coc.nvim/build/index.js:58:4295)
    at bp.attach (/home/jorik/.vim/bundle/coc.nvim/build/index.js:177:4856)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async vR.init (/home/jorik/.vim/bundle/coc.nvim/build/index.js:198:621)
    at async _b.init (/home/jorik/.vim/bundle/coc.nvim/build/index.js:281:45514)
    at async EventEmitter.<anonymous> (/home/jorik/.vim/bundle/coc.nvim/build/index.js:281:47310)
'
 32.426812 : raw key input: "OBOBOBOB[O[IOAOBOBOAOBOAOBOAOBOAOB"
```

## Screen recording
![bufwritepre-slow](https://user-images.githubusercontent.com/43748187/220080798-7f771c8e-8836-4aa6-b17d-9e1f621369dc.gif)

I've added an interesting screen recording. From this it seems that in a (relatively) empty folder the write is still as quick as expected. Wheres opening and writing a YAML file in a git repo causes the write to be very slow.

I'm not too experienced in js / vimscript, but I would like to assist in finding the issue as I'm very happy with the plugin. Are there for examples ways for me to debug what methods are actually executing during the `BufWritePre` to find the specific case that causes the delays? There seem to be some relevant lines referenced in the slow handler logging, but they refer back to the minified `index.js` from which it's hard to determine what is happening (at least for me).

**Comment by yaegassy** [comment]
@JJdeVries Hi, Could this be a situation where this problem is occurring again?

- <https://github.com/neoclide/coc.nvim/issues/3824>

**Comment by JJdeVries** [comment]
> Looks like the formatting blocks this, but tested on YAML with coc-yaml, can't reproduce this.
> 
> I've enabled `coc.preferences.formatOnSave`. Can you provide a minimal vimrc to debug ?

@fannheyward I've added a mini.vim that is exactly the example. That one is also used in the screen recording to show what is happening. I've not enabled `coc.preferences.formatOnSave`, also I'm not expecting that it's a `coc-yaml` issue, I've seen the issue also appear for example when editing a git commit message (for which there should be no formatting happening i think? At least not any addon that I've installed should do something).



> @JJdeVries Hi, Could this be a situation where this problem is occurring again?
> 
>     * [vim blocks for a few seconds while saving a file #3824](https://github.com/neoclide/coc.nvim/issues/3824)

@yaegassy This sounds exactly like my problem. The folder in question is a git repo which can contain a build folder of ~ 50-100 Gb. I've also installed the `coc-pyright` add-on which defines a number of `workspaceContains` (although without any actual globbing (`**`)). I should be running the latest release version (see also the `CocInfo` output, which mentions the version being on commit `b7375d5f ` which is the latest release commit.


@fannheyward @yaegassy 
Interestingly enough I no longer seem to be able to reproduce the issue myself? I don't think I have changed anything in my setup between seeing the issue (consistently), and now, but taking the same steps, or editing existing files does not cause the issue anymore.

I'll thus close this issue, but if you have any idea's on how I can obtain more information if the issue arises again please let it know in a comment and I'll do that. In any case thanks for the input, and at least it works again! :-).

**Comment by yaegassy** [comment]
I have tried the steps described in my comment about the link problem, but the problem seems to be recurring...

- <https://github.com/neoclide/coc.nvim/issues/3824#issuecomment-1128817630>
