### ISSUE TITLE
Coc-snippet的些许疑惑

### ISSUE THREAD

**Issue by ttzorztt** [neoclide/coc.nvim#4528]
## Result from CocInfo

>  听说coc是中国人开发，斗胆使用中文提问
无

## Describe the bug

1. 我之前使用另外一个vim的插件，是做snippet的插件，但是似乎coc的coc-snippet插件效果不足或我本身配置有问题，vim-snippets中的\<TAB\>键是触发snippet，再次按压\<TAB\>可以跳转到snippet语法中的$1和$2的效果。但是在coc-snippet中，由于在您默认github中的配置，将<\TAB\>设置为选择下一个提示。所以我不知道您是否有这方面的开发想法。
2. 您在<TAB>中的设置，您似乎与<CR>配合，按下<TAB>默认coc#pum#next(1)，也就是补全了第一个，对<CR>进行了配置，按下Enter补全第0个。但是实际上，按下Enter补全似乎对我来说并不是一个好的方案。因为在某些时候，我想输入的部分是触发补全的子集，同时我想要跳转到下一行，此时我就需要按下方向键<Right>或返回normal。但如果我取消您对于<CR>的配置。我就同时消失了补全第0个的功能。或许是我的配置问题。

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：
> 我觉得应该不是配置的问题，是逻辑问题。或者是在您在github中的Readme中没有体现的配置项。
  ```vim

  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
第一个问题，coc-snippet 的 READNE 就有，支持展开并跳转。

第二个问题，可以用 `c-e` 取消补全。

**Comment by ttzorztt** [comment]
抱歉，我似乎忽略了coc-snippet的readme......
关于第二个疑惑:
\<C-e\>似乎可以取消补全，但是假设我需要补全第0个，按下tab后却补全第0个，那么当我想要补全第0个的时候，我需要按下tab和s-tab返回第0个，或者完全手工输入。但同时我不想开启您配置中的<CR>,因为我想达到按下CR直接回车而非补全第0个。因为有时候输入的内容是补全的子集。

**Comment by fannheyward** [comment]
> 但是假设我需要补全第0个，按下tab后却补全第0个

没明白

c-e 是取消补全提示显示，这时候你可以继续 cr 回车换行。

**Comment by ttzorztt** [comment]
> 但是假设我需要补全第0个，按下tab后却补全第0个
这个是写错了，**就是我当前的配置是取消您对于Enter的配置**。原本的意思是： 您对于tab的定义，初次按下后直接跳转到第1个的代码提示，就相当于跳过了第0个，您的解决方案是定义了Enter来补全第0个。
这似乎是两种思路，
您的想法的在需要补全的时候按tab，然后需要回车的时候按c-e,就相当于一般情况下，需要Enter补全第0个或当前选项（我的想法是这么做似乎将Enter绑死在这里了），用c-e来取消补全，然后Enter回车。即\<c-e\> + <tab> + <cr>
举个例子，我输入ma,提示信息有三个，
1. maa
2. mas
3. main
但是我输入ma后，只想回车，如果按下回车的话(如果设定<CR>)，就会选择maa补全，然后退格删除a后回车，或使用c-e取消补全，然后再按enter。
我的想法是取消c-e,仅使用tab就可以。只要初次按压tab可以从第0个开始补全，然后取消对Enter的设定，也就是按下Enter直接回车就可以。<tab> + <cr>
这可以算是一个建议吧。。。。因为我没参与开发，也不知道是否会对别的模块起冲突。甚至还有可能我忽略了哪块Readme的注释。

这个其实问题不是很明显。现在的问题是我重定义了您关于coc-snippet对于tab的设定。导致coc本身对于tab的设置与coc-snippet对于tab的设置冲突，但coc-snippet的优先级似乎比coc本身对于tab的高一些。按下tab后，直接展开snippet，而不会跳转到下一个代码提示。这是否只能通过重定义coc-snippet的快捷键来解决?

**Comment by fannheyward** [comment]
你可以不设置 CR mapping，这样回车就不会补全。

**Comment by ttzorztt** [comment]
如果我不设置CR的快捷键的话，似乎要选默认的第0个选项的补全，就很麻烦，不过还是谢谢您的解答。

**Comment by fannheyward** [comment]
我大概知道你说的第0个补全的问题，enable `suggest.noselect` 试试。

**Comment by ttzorztt** [comment]
> enable suggest.noselect
谢谢您，问题完美解决。奥力给!
