### ISSUE TITLE
turn off autocommenting on lint errors (is this the right repo?)

### ISSUE THREAD

**Issue by tommyjcarpenter** [neoclide/coc.nvim#4529]
I did a plugin update today - I use coc-vim combined with Ale. Not exactly sure where this change is coming from. 

After this update, vim is now autocommenting all errors, they look like this:

```
from m3 import config, m3_base_runner, m3_daemon$ # E: No name 'm3_daemon' in module 'm3' # E: "m3_daemon" is unknown import symbol
```

that `# E` is being automatically injected on saving the file 

is this coming from coc-vim, and if so, is there a way to turn this off? Otherwise I appologize and maybe it's related to a recent Ale update.

**Comment by fannheyward** [comment]
Are you using python extensions? For example coc-pyright? Disable it and try again.

**Comment by fannheyward** [comment]
> that # E is being automatically injected on saving the file

This shouldn't been came from coc.nvim.

**Comment by tommyjcarpenter** [comment]
ok, some clarity: those comments are not actually being saved into the file, but they are now being shown as if they are comments. Yes, I am using extensions like coc-pyright and those are linting errors.

**Comment by fannheyward** [comment]
Screenshot please, looks like you're talking about diagnostic virtualText and inlayHint.

> they are now being shown as if they are comments

Do you have enabled `diagnostic.virtualText`?

**Comment by tommyjcarpenter** [comment]
@fannheyward screenshot attached. I want to note I didn't change any settings, or add any new plugins, I just did a plugin-update. Something in coc-vim or one of it's extensions recently added this.

**Comment by fannheyward** [comment]
Which part do you want to disable?

The diagnostic format isn't like coc-pyright's.

**Comment by tommyjcarpenter** [comment]
before update: linting errors would show in red

after update: all this grey text all over the screen as "fake comments" but they arent actually _in_ the file

i want to go back to the way it was

**Comment by fannheyward** [comment]
Sorry but I still can't get your point of the diagnostics.

The `left hand bar`, do you mean the signcolumn?

Coc didn't change the diagnostic UI, try minimal Vimeo, only coc plugin.

**Comment by tommyjcarpenter** [comment]
@fannheyward ok I will try to be super clear. 

do you see all of the grey text starting with `#` in the screenshot? all of that is new, and I want all of it gone. 

by left column I mean the red text `>>` here 

![Screen Shot 2023-02-24 at 8 12 59 AM](https://user-images.githubusercontent.com/9419125/221187209-5590434a-c5a5-42b9-9695-d102b6574533.png)

I want *just* the red >> like it used to be before update, and all of the grey comments to go away

**Comment by tommyjcarpenter** [comment]
this seems related, but im using `vim` (vim vim) not nvim, and this didnt seem to work, but this user had the same issue: https://github.com/neoclide/coc.nvim/issues/1667

**Comment by fannheyward** [comment]
As I said before, the grey comments' format isn't like coc-pyright's, disable ALE and try again.

**Comment by tommyjcarpenter** [comment]
@fannheyward is coc now a replacement for Ale? I was/am using ale to run a variety of linters, is coc supposed to replace all those features?

**Comment by fannheyward** [comment]
Do you have enabled another Python linter like pylint/flake8 etc?

**Comment by tommyjcarpenter** [comment]
![Screen Shot 2023-02-24 at 8 26 30 AM](https://user-images.githubusercontent.com/9419125/221189917-8dd8e43f-83fa-4f33-b049-16c32a5d85ce.png)
this is somewhat closer, but now i have the floating box (good!) alongside the comments..

**Comment by fannheyward** [comment]
The floating window is came from coc to display the diagnostic, but the grey comment isn't from coc.

**Comment by tommyjcarpenter** [comment]
@fannheyward ok thanks for your help, i will try to look through recent ale updates

here is and was (hasnt chznged) my ale config
```
" ALE flags
" https://stackoverflow.com/questions/64859920/how-to-run-isort-via-ale-in-vim
"https://github.com/ascandella/ale/commit/de29ff26ff536dbb99c57fc5f20ec6ee0b17a6c6
let g:ale_fixers = {'go': ['goimports'], 'python': ['autoflake', 'isort', 'black'], '*': ['remove_trailing_lines', 'trim_whitespace']}
let g:ale_fix_on_save = 1
let g:ale_python_autoflake_options = "--remove-all-unused-imports"

```

**Comment by tommyjcarpenter** [comment]
hmmm this seems relevent: https://github.com/dense-analysis/ale#5iii-how-can-i-use-ale-and-cocnvim-together

**Comment by tommyjcarpenter** [comment]
OK! I solved this. 

On COC side:

```
"diagnostic.displayByAle": true
```

in vimrc
```
let g:ale_virtualtext_cursor = 1
```

and
 
```
let g:ale_disable_lsp = 1
``` 

at the top

produces 

![Screen Shot 2023-02-24 at 10 55 47 AM](https://user-images.githubusercontent.com/9419125/221225116-948e0784-616d-4a80-ae54-7339a5d3d46b.png)

which is exactly what I wanted. Thanks for your help @fannheyward !
