### ISSUE TITLE
Coc.nvim's semantic highlighting should match Nvim's semantic tokens.

### ISSUE THREAD

**Issue by SeniorMars** [neoclide/coc.nvim#4531]
**Is your feature request related to a problem? Please describe.**
Recently, in nvim nightly this was merged: https://github.com/neovim/neovim/pull/21100, which adds semantic tokens support.

Specifically, we see in https://github.com/jdrouhard/neovim/blob/9f035559defd9d575f37fd825954610065d9cf96/src/nvim/highlight_group.c#L267 and https://github.com/theHamsta/nvim-semantic-tokens/blob/master/lua/nvim-semantic-tokens/presets/default.lua

```c
  // LSP semantic tokens
  "default link @class Structure",
  "default link @struct Structure",
  "default link @enum Type",
  "default link @enumMember Constant",
  "default link @event Identifier",
  "default link @interface Identifier",
  "default link @modifier Identifier",
  "default link @regexp SpecialChar",
  "default link @typeParameter Type",
  "default link @decorator Identifier",
```
I was thinking that coc semantic highlighting should match the highlight groups of LSP's

**Describe the solution you'd like**
Highlight groups should match.

**Describe alternatives you've considered**
Modified Coc semantic groups on my own.

**Additional context**
None

**Comment by fannheyward** [comment]
coc.nvim already support this https://github.com/neoclide/coc.nvim/blob/79e9e048dfedbfc8b91330059fec5470f8b68f14/plugin/coc.vim#L558

https://github.com/neoclide/coc.nvim/pull/4384
