### ISSUE TITLE
CocRestart doesn't reset coc_status

### ISSUE THREAD

**Issue by liferooter** [neoclide/coc.nvim#4535]
## Result from CocInfo

```
## versions

vim version: NVIM v0.9.0-dev-1d8b77d
node version: v18.14.1
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /nix/store/qhms8i0anqlg6mcz167d2wl11r83waa6-vimplugin-coc.nvim-2023-01-29
term: undefined
platform: linux

## Log of coc.nvim

2023-02-27T11:07:32.086 INFO (pid:183634) [extension:coc-git] - Looking for git in: git
2023-02-27T11:07:32.105 INFO (pid:183634) [plugin] - coc.nvim initialized with node: v18.14.1 after 691
```

## Describe the bug

`coc.nvim` doesn't reset `g:coc_status` after restart.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Open any file which uses language server that affects `coc_status`. Enable that LSP before.
- Close that file to prevent language server from restarting.
- Run `:echo coc_status` to see that language server still works and sets the status
- Run `:CocRestart`
- Run `:echo coc_status` to see that the status wasn't reset. But it should be, because language server is dead. It's a bug.

## Screenshots (optional)

![изображение](https://user-images.githubusercontent.com/54807745/221510319-e2d79ee1-f07a-44ff-b607-8df404d5e47d.png)

**Comment by fannheyward** [comment]
Tested with coc-tsserver:

1. open an ts file, `coc_status` outputs `TSC 4.9.5`, this is expected
2. `bd` to close the ts file buffer
3. `:echo coc_status` is empty
4. `:CocRestart`
5. `:echo coc_status`, still empty

> Close that file to prevent language server from restarting

How do you close the file?
