### ISSUE TITLE
Starting vim with  +'norm o' causes an error

### ISSUE THREAD

**Issue by omnster** [neoclide/coc.nvim#4541]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9001358
node version: v16.17.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /home/omn/.vim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2023-02-28T23:17:17.002 INFO (pid:469824) [extension:coc-git] - Looking for git in: git
2023-02-28T23:17:17.207 INFO (pid:469824) [plugin] - coc.nvim initialized with node: v16.17.0 after 1360

```

## Describe the bug

I have a file that I want to open at the last line, append a new line below, and start vim in the insert mode on that new line.  When I do so using the command below, I see the error:

```
Error detected while processing command line..InsertLeave Autocommands for "*"..function <SNR>10_HandleInsertLeave[1]..script /home/omn/.vim/plugged/coc.nvim/autoload/coc/pum.vim:
line   23:
E970: Unknown highlight group name: 'CocPumVirtualText'
```

## Reproduce the bug

- I created `/tmp/mini.vim` with：

  ```
  set nocompatible
  set runtimepath^=/home/omn/.vim/plugged/coc.nvim/
  filetype plugin indent on
  syntax on
  set hidden
  ```

- I am starting vim with `vim -u /tmp/mini.vim /tmp/1 + +'norm o' +startinsert`, which throws an error above, but the problem persists with simply `vim -u /tmp/mini.vim /tmp/1 +'norm o'`

I guess, 'norm o' opens a line and immediately leaves insert mode, which fires the autocommand which fails.

**Comment by fannheyward** [comment]
Reproduced with vim, not nvim.

**Comment by fannheyward** [comment]
maybe same https://github.com/neoclide/coc.nvim/issues/4665
