### ISSUE TITLE
Why "client coc abnormal exit with: 139" appear?

### ISSUE THREAD

**Issue by DxytJuly3** [neoclide/coc.nvim#4546]
### However, the problem will still exist.

# Help!   Help!   I need help!

```vim

node --version 
v16.17.0
yarn --versions
1.22.19
```

**Comment by fannheyward** [comment]
coc failed to run with your vim or node or OS, try to debug with your env https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by xuzixx** [comment]
我遇到同样的问题，只有打开包含中文的文件的时候会client coc abnormal exit with: 139 
我将coc 指定到0.0.82 版本时候没有这个问题。

**Comment by DxytJuly3** [comment]
> 我遇到同样的问题，只有打开包含中文的文件的时候会client coc abnormal exit with: 139 我将coc 指定到tag = 'v0.0.82' 版本时候没有这个问题。
怎么指定版本安装呢？求教

**Comment by DxytJuly3** [comment]
> 我遇到同样的问题，只有打开包含中文的文件的时候会client coc abnormal exit with: 139 我将coc 指定到tag = 'v0.0.82' 版本时候没有这个问题。

可不可以教一下指定版本安装的方法？求教

**Comment by xuzixx** [comment]
> > 我遇到同样的问题，只有打开包含中文的文件的时候会client coc abnormal exit with: 139 我将coc 指定到tag = 'v0.0.82' 版本时候没有这个问题。
> 
> 可不可以教一下指定版本安装的方法？求教

    use {
      'neoclide/coc.nvim',
      -- branch = 'release',
      tag = 'v0.0.82',
    }

**Comment by xuzixx** [comment]
> coc failed to run with your vim or node or OS, try to debug with your env https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

https://github.com/neoclide/coc.nvim/commit/9181a83f14929e7cb62069d4c61c7515e78674e4

大佬我回退版本，发现这个commit 之前是ok的，怀疑是这里引入的

**Comment by fannheyward** [comment]
@xuzixx 你的 Node.js 版本是多少？

**Comment by essayZW** [comment]
16.17.0版本的nodejs会出现这个问题，升级到16.19.1版本，可以解决

**Comment by fannheyward** [comment]
若无特殊情况，一般建议使用当前 LTS 版本，现在是 18.x.

**Comment by xuzixx** [comment]
> 若无特殊情况，一般建议使用当前 LTS 版本，现在是 18.x.

应该也是node版本比较老的问题，升级了下node 可以了，感谢
