### ISSUE TITLE
Support custom autocompletion functions

### ISSUE THREAD

**Issue by zeyadhany98** [neoclide/coc.nvim#4547]
Is there a way to define a user-defined api file or something to add custom functions to my Coc.nvim to appear in the auto-completion list
for example:-
I would like to define this function:
ndif2(abstol,reltol,reference,result)
so when I type "n", it appears a drop-down menu choice like that: "ndif2(abstol,reltol,reference,result)" and so on.

something like that that I implemented using the Qscintilla editor module in python.
That's a snapshot of it:
![image](https://user-images.githubusercontent.com/125281494/222524542-dd491336-6bbc-47bd-b76c-fdc6988a99d7.png)

Thanks & Regards

**Comment by fannheyward** [comment]
You can use custom source `:h coc-api-vim-source`, or extension `:h coc-api-extension` to add custom completions.

**Comment by zeyadhany98** [comment]
Where can i find the documentatio for that ?
Need to learn more about this feature

**Comment by fannheyward** [comment]
The `:h coc-api-vim-source` contains the documentation and example.

**Comment by zeyadhany98** [comment]
@fannheyward could you just point me to it? , as I could not find it 

Sorry for any inconvenience

**Comment by zeyadhany98** [comment]
Thanks
