### ISSUE TITLE
Hint bug

### ISSUE THREAD

**Issue by yinghaoyu** [neoclide/coc.nvim#4548]
As usual I create a cpp file, and write `vector<int> arr = {1, 2, 3, 4, 5, 6};`, but neovim shows as below,
```cpp
vector<int> arr = {1, 2, 3, 4, 5, 6}; [0]= [0]= [1]= [2]= [1]=
```
There are many extra characters `[0]= [0]= [1]= [2]= [1]=`  ,which can't be selected or edited. They will disappear after I run `CocDisable`.

**Comment by yinghaoyu** [comment]
In Arch Linux, I just update Coc.

**Comment by fannheyward** [comment]
Check `:h coc-inlayHint`.
