### ISSUE TITLE
[Bug] Path autocompletion works only once per line

### ISSUE THREAD

**Issue by MahdiNazemi** [neoclide/coc.nvim#4549]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9001350
node version: v19.7.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /Users/mahdi/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2023-03-04T11:42:29.890 INFO (pid:72250) [plugin] - coc.nvim initialized with node: v19.7.0 after 224
2023-03-04T11:42:31.351 INFO (pid:72250) [attach] - receive notification: highlight []
2023-03-04T11:42:37.687 INFO (pid:72250) [attach] - receive notification: showInfo []
```

## Describe the bug

Path completion works only once per line. No autocomplete suggestions will be shown for any subsequent paths written in the same line.

## Reproduce the bug

- Create a file named `mini.vim` with the following contents:

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start vim with the command `vim -u mini.vim`.

- Write `python $PWD/` and see autocomplete suggestions after writing `$PWD/`.

- Continue the command with something like

    - `python $PWD/script.py -a $PWD/` or
    - `python $PWD/script.py -a $HOME/` or
    - `python $PWD/script.py -a ./`.

- No autocomplete suggestions will be shown after writing `$PWD/`, `$HOME/`, or `./`.

**Comment by MahdiNazemi** [comment]
@chemzqm, I built the plugin from source today and ran `npm install` afterward (`yarn install` did not work on my Ubuntu 22.04). I completely lost path auto-completion after the update. Can you please run the tests for the PR associated with this bug report one more time?

**Comment by chemzqm** [comment]
Tested vim 9.0.1189 on Ubuntu 23.04, path completion works as expected for me.

**Comment by MahdiNazemi** [comment]
Thanks for taking the time to test this.

It works for me too in shell scripts, but not inside Python strings.

**Comment by chemzqm** [comment]
> It works for me too in shell scripts, but not inside Python strings, e.g. in `argparse`, when using `default="/path/to/default"`.

Reproduced, need some fix.
