### ISSUE TITLE
coc.nvim service not started 

### ISSUE THREAD

**Issue by tnekent** [neoclide/coc.nvim#455]
**Describe the bug**
coc.nvim fails at vim startup. It just spits out:
```
[vim-node-coc]: Plugin initialized error: Error: request nvim_command - call nvim_command: Vim:Interrupt
[vim-node-coc]:     at transport.request (/home/.vim/pack/foo/start/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:33:28)
[vim-node-coc]:     at Transport.parseMessage (/home/.vim/pack/foo/start/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:134:17)                 
[vim-node-coc]:     at DecodeStream.Transport.decodeStream.on (/hom e/.vim/pack/foo/start/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:43:18)
[vim-node-coc]:     at DecodeStream.emit (events.js:197:13)
[vim-node-coc]:     at addChunk (_stream_readable.js:288:12)                                  
[vim-node-coc]:     at readableAddChunk (_stream_readable.js:269:11)
[vim-node-coc]:     at DecodeStream.Readable.push (_stream_readable.js:224:10)
[vim-node-coc]:     at DecodeStream.Transform.push (_stream_transform.js:151:32)
[vim-node-coc]:     at DecodeBuffer.DecodeStream.decoder.push (/hom e/.vim/pack/foo/start/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)         
[vim-node-coc]:     at DecodeBuffer.flush (/home/.vim/pack/foo/start/coc.nvim/node_modules/msgpack-lite/lib/flex-buffer.js:57:12)
```

**Comment by chemzqm** [comment]
Need minimal .vimrc to reproduce the problem.

**Comment by tnekent** [comment]
I don't know why, but when I deleted vim and recompiled and installed this, the error vanished..

**Comment by Polish-Civil** [comment]
Hello, I'm using spacevim and this error occurs when im calling the gotoReferences action.
I'm using my custom LSP and i'm sure that i receive the request as well as im sending the response.
Code completion works just fine, so I'm stuck
as @tnekent pointed out, recompiling helps but then it gets randomly stuck again.

If there are any logs i could publish, please give me an info how to and i'll be happy todo so.

**Comment by chemzqm** [comment]
@Polish-Civil https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by Polish-Civil** [comment]
@chemzqm 

For :CocCommand workspace.showOutput it says service not started and freezes whole vim process

For coc#util#build()

![image](https://user-images.githubusercontent.com/10587799/54333085-fd0a9780-4618-11e9-9f98-e8fd5e0ef861.png)

**Comment by chemzqm** [comment]
Just fixed that bug problem.

**Comment by Polish-Civil** [comment]
@chemzqm 
Works like charm now, probably the binary version was not compatible with my setup

**Comment by chemzqm** [comment]
Try not use master code with binary release, since the vim api could change, use `"tag":*` with `Plug` command of vim-plug to use released version.
