### ISSUE TITLE
[Feature Request] Set `list.maxPreviewHeight` as a function of the number of lines of the Vim window

### ISSUE THREAD

**Issue by MahdiNazemi** [neoclide/coc.nvim#4557]
**Is your feature request related to a problem? Please describe.**
One can change the number of lines shown in a reference's preview by setting `list.maxPreviewHeight` in `CocConfig`. In cases where Vim's configurations are synced across multiple machines, this setting can take a different fraction of the number of lines returned by `:set lines?`. For example, on a display where the Vim window has 58 lines, the preview takes about 1/3 of the screen while on a display where the Vim window has 30 lines, the preview takes 2/3 of the screen.

**Describe the solution you'd like**
Set `list.maxPreviewHeight` as a fractional number, e.g., 0.5, so that the preview always takes half the Vim window.

**Comment by MahdiNazemi** [comment]
Here is a hacky solution until we can find a better one:

```vim
autocmd VimEnter * call coc#config('list.height', &lines * 2 / 10)
autocmd VimEnter * call coc#config('list.maxPreviewHeight', &lines * 6 / 10)
```

**Comment by chemzqm** [comment]
Use `coc#config` for that purpose.
