### ISSUE TITLE
E1004: White space required before and after ':' at ": "\^Gu\^M\^R=coc#on_enter()\^M""

### ISSUE THREAD

**Issue by bj-edward** [neoclide/coc.nvim#4559]
vim release: 9.0.1157
The following error message appeared when I type Enter:
E1004: White space required before and after ':' at ": "\^Gu\^M\^R=coc#on_enter()\^M""

**Comment by fannheyward** [comment]
How do you map your enter key?

**Comment by bj-edward** [comment]
It seems conflict with the below:

 inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
       \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

**Comment by bj-edward** [comment]
@fannheyward 
No, I don't make any map for my Enter key.

**Comment by fannheyward** [comment]
Something broken with your `<cr>` mapping, check README or doc.

**Comment by bj-edward** [comment]
The setting is from the official:
https://github.com/neoclide/coc.nvim

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice

inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

**Comment by bj-edward** [comment]
The issue disappeared after I comment out it.

**Comment by fannheyward** [comment]
Yes, make sure the mapping in your vimrc is same as the README. This issue is a setting error in your vimrc.
