### ISSUE TITLE
Add support for Unicode LSP identifiers

### ISSUE THREAD

**Issue by Andrew15-5** [neoclide/coc.nvim#4564]
**Is your feature request related to a problem? Please describe.**
When using `coc-texlab` autocompletion isn't triggered when pasting non-Latin/digit character (from the clipboard) (which represent 1st char of a defined macro). See https://github.com/latex-lsp/texlab/issues/864#issuecomment-1464630744 for (a lot) more information (including MWE from the 1st comment and the test from the linked comment).

**Describe the solution you'd like**
I want for the autocompletion to be triggered when pasting any character from clipboard, not only Latin/digit characters.

**Describe alternatives you've considered**
I don't think there are alternatives.

**Additional context**
I also opened a similar issue here https://github.com/fannheyward/coc-texlab/issues/251 because I'm not sure if the definition of ["identifier characters"](https://github.com/latex-lsp/texlab/issues/864#issuecomment-1464858109) take place in the core `coc.nvim` or the extension `coc-texlab`.

**Comment by fannheyward** [comment]
Set `suggest.asciiMatch` to `false` and try again.

**Comment by Andrew15-5** [comment]
Indeed, after hitting `\` and `<C-Space>` whichever (Unicode) character is a "start of a macro" it triggers the update of suggested items. Thank you.

P.S. The exception is a compound character like `👨‍👩‍👦‍👦`. But the problem could be with Neovim (see screenshot here https://github.com/latex-lsp/texlab/issues/864#issuecomment-1464560856).
