### ISSUE TITLE
Trigger autocompletion after inserting text from clipboard (without prior press of `<C-Space>`)

### ISSUE THREAD

**Issue by Andrew15-5** [neoclide/coc.nvim#4568]
**Is your feature request related to a problem? Please describe.**
This "issue/feature request" is closely related to https://github.com/neoclide/coc.nvim/issues/4564. [There](https://github.com/neoclide/coc.nvim/issues/4564), the condition is to press `\` and then `<C-Space>` before pasting character/text from clipboard (for LaTeX autocompletion with `coc-texlab`). But here the condition is to just press `\`.

So, when you press `\` and then start **typing** macro name yourself (for macros such as `\a`, `\1`, `\р`, `\あ` — doesn't matter) the language server (LS; `coc-texlab`) will show (send) suggestions, but when you press `\` and then **paste** macro name (or its part with which the macro begins) the LS does nothing. Hence, you have to either paste text _after suggested menu appeared_ or manually create it (after pasting) by calling `coc#refresh()` (`<C-Space>`).

**Describe the solution you'd like**
I would like for `coc.nvim` to show/trigger suggestions after pasting text from clipboard (or by other means, e.g., [`kitty`'s `ctrl+shift+u`](https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Unicode-input)).

**Describe alternatives you've considered**
Maybe it can be done by using Vimscript's `autocmd` (`TextChanged` or something). But this may introduce some issues with some plugins (I'm not sure how each plugin will react to this). Maybe it's safe, idk.

**Additional context**
Tried the same steps with `coc-pyright` — same problem. I didn't find anything close under `suggest.*` in `:CocConfig`.

**Comment by chemzqm** [comment]
There's no paste autocmd, so seems not possible to detect text paste, you have to trigger `coc#refresh()` manually.
