### ISSUE TITLE
"replace_keycodes" breaks backwards compatibility with Neovim v0.72

### ISSUE THREAD

**Issue by dseeni** [neoclide/coc.nvim#4574]
Hello,

I'm limited to Neovim 0.7.2, on my work machine, can't update beyond that due to OS.

"replace_keycodes" breaks coc-snippets if I use Coc v0.82.

Would it be possible to opt in for the replace keycodes mapping? I don't care about Tui keycodes.

I'd like to use the newer version of Coc.nvim.

Thanks!

## versions
vim version: NVIM v0.7.2
node version: v19.7.0
coc.nvim version: **0.0.82**-b7375d5f 2023-01-30 05:09:03 +0800
term: undefined
platform: win32

## Log of coc.nvim
2023-03-18T18:20:42.831 ERROR (pid:676) [node-client] - Error event from nvim: 1 Invalid key: **'replace_keycodes'**

**Comment by fannheyward** [comment]
You're using Lua to setup your mappings, with `replace_keycodes` in your keyset options, but `replace_keycodes` is not available in nvim 0.7.2. It's not coc.nvim's issue.  

You can use vimL to setup your mappings.
