### ISSUE TITLE
Neovim freezes on very long lines with CocActionAsync('highlight') autocmd

### ISSUE THREAD

**Issue by gibfahn** [neoclide/coc.nvim#4577]
## Result from CocInfo

vim version: NVIM v0.8.3
node version: v18.15.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /Users/gib/.local/share/nvim/site/pack/packer/start/coc.nvim
term: xterm-kitty
platform: darwin

## Describe the bug

When I move the cursor on the first `2023` in the attached file, nvim hangs using 100% CPU for about 30 seconds. this is a cut-down log, the real file hangs for a lot longer. Every time you hover over another 2023 it hangs again.

## Reproduce the bug

I think this should be enough to reproduce. If not I will pare down my `init.lua`:

```lua
vim.cmd([[
  augroup 
    autocmd!
    " Highlight symbol under cursor on CursorHold (show other instances of current word).
    autocmd CursorHold * silent call CocActionAsync('highlight')
  augroup end
]])
```

```console
nvim coc-nvim-repro.log
```

[coc-nvim-repro.log](https://github.com/neoclide/coc.nvim/files/11019024/coc-nvim-repro.log)

**Comment by fannheyward** [comment]
Reproduced.

**Comment by chemzqm** [comment]
Should be issue with coc-highlight.
