### ISSUE TITLE
Auto-completion popup automatically scrolls a buffer.

### ISSUE THREAD

**Issue by your-diary** [neoclide/coc.nvim#4583]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9001400
node version: v19.7.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /Users/user/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2023-03-22T19:48:34.687 INFO (pid:34764) [configurations] - Add folder configuration from cwd: /Users/user/dir/.vim/coc-settings.json
2023-03-22T19:48:35.151 INFO (pid:34764) [plugin] - coc.nvim initialized with node: v19.7.0 after 497
2023-03-22T19:48:40.471 INFO (pid:34764) [attach] - receive notification: showInfo []
```

## Describe the bug

As recorded in the movie below, when a popup window for auto-completion appears or its contents change, the buffer is automatically scrolled up (until the current line finally becomes the first line of the buffer).

If I execute `:CocDisable`, this bug disappears.

https://user-images.githubusercontent.com/58146437/226880195-03311944-13d3-4b44-8c5f-2715fe312a35.mov

## Reproduce the bug

1. Create file `mini.vim`:
    ```vim
    set nocompatible
    set runtimepath^=/path/to/coc.nvim
    filetype plugin indent on
    syntax on
    set hidden
    ```

2. Start vim.
    ```bash
    $ vim -u mini.vim <file>
    ```

3. Type something in insert mode.

## Possible Cause

As seen in the movie above, I'm editing a file whose lengths of lines are very long (at most 500-1000 Unicode characters per line).

- When I execute `:set nowrap`, which is NOT default, the bug disappeared.

- When `:set wrap` (default) but no long line is displayed in the current viewport, the bug disappered.

So I suspect `coc.nvim` cannot handle a buffer with a long line displayed when `:set wrap`.

**Comment by fannheyward** [comment]
Vim's bug, set `set splitkeep=screen` as temporary solution.

- https://github.com/neoclide/coc.nvim/issues/4544
- https://github.com/vim/vim/issues/12085
