### ISSUE TITLE
CocSearch with `--` option return duplicates when the cwd is within the `--`dir

### ISSUE THREAD

**Issue by GodefroyClair** [neoclide/coc.nvim#4590]
Hi,
Device: Mac
OS: 12.6.3
vim version: NVIM v0.8.3
node version: v19.3.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /Users/godefroy.clair/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

# Description of the bug

after trying I found something weird...
Imagine the following dir substructure :
foo
├── bar
 │       └── baz.c
└── qux.c
with the word "hello" in baz.c and qux.c

If I do
```
$ cd foo
$ vim  bar/baz.c
```
Then
`:CocSearch hello`
I get :
```
Save current buffer to make changes
Files: 1 Matches: 1 Duration: 43ms

baz.c 1:2
hello
```
But if I do:
`:CocSearch hello -- ..`

the result is:
```
Save current buffer to make changes
Files: 3 Matches: 3 Duration: 37ms

/Users/xxxxx/test/foo/qux.c 1:1
hello
　
baz.c 1:2
hello

baz.c 1:2
hello
```

Hence there are duplicates : it seems like it returns the result of _both_ requesting the current directory and the directory after `--` and if the current directory is in the directory given after `--`

Whereas, from command line, there are no duplicate:
```
$ cd foo/bar
$  rg -i hello
baz.c
1:hello
$ rg -i hello -- ..
../bar/baz.c
1:hello

../qux.c
1:hello
```

**Comment by fannheyward** [comment]
What's your `test` folder? A project root folder?

My test steps:

1. `cd ~ && mkdir test && cd test`
2. `mkdir -p foo/bar`
3. `echo 'hello' > foo/bar/baz`
4. `echo 'hello' > foo/qux`

now we're in `test` folder, `pwd` is `/Users/fannheyward/test`, and `tree`:

<img width="239" alt="截屏2023-04-21 19 02 41" src="https://user-images.githubusercontent.com/345274/233620473-146c7323-d919-472b-8597-6639860e219f.png">

next:

```
cd foo
vim bar/baz
```

`:CocSearch hello`:

<img width="796" alt="截屏2023-04-21 18 52 54" src="https://user-images.githubusercontent.com/345274/233618579-907ceda2-7bd8-4374-81a5-531a27789307.png">

Different with you. When you `:CocSearch hello`, coc runs

```
rg -A 3 -B 3 --color ansi --colors path:fg:black --colors line:fg:green --colors match:fg:red --no-messages --heading -n hello -- ./
```

From command line:

```
✦ ❯ rg -A 3 -B 3 --color ansi --colors path:fg:black --colors line:fg:green --colors match:fg:red --no-messages --heading -n hello -- ./
./qux
1:hello

./bar/baz
1:hello
```

Same result.

`:CocSearch hello` is not `rg -i hello`.
