### ISSUE TITLE
Completion of type for parameter is not show in front of parameters.

### ISSUE THREAD

**Issue by TimerLinker** [neoclide/coc.nvim#4592]
versions
vim version: NVIM v0.8.3
node version: v14.21.3
coc.nvim version: 0.0.82-master
coc.nvim directory: /home/shw/.config/nvim/plugged/coc.nvim
term: tmux
platform: linux

Hi, I confuse about type complete for parameter. Please look picutures.

In coc.nvim
![1](https://user-images.githubusercontent.com/48616483/228848466-b51b6617-6b44-4c46-903c-c60c2d11a4fb.png)
In vscode
![2](https://user-images.githubusercontent.com/48616483/228848558-bc0f67cb-ccdd-4ce0-8b7a-f8dc1f531dbb.png)

I think complete in vscode is right. Is any options to fix it ?

**Comment by fannheyward** [comment]
Its nvim's limit, vim 9 can display this same as VSCode.
