### ISSUE TITLE
is there a way to disable type declarations in :messages?

### ISSUE THREAD

**Issue by blockchainian** [neoclide/coc.nvim#4600]
hey there,

the type declaration for the symbol under the cursor goes to `:messages`. see below:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/1897055/230808564-789067cb-be8c-4da7-9213-8f2fecac39e3.png">

curious if there is a way to disable this behavior? if not, could you point me to the code? happy to fork it and send a pr if that works for you.

thanks!

**Comment by fannheyward** [comment]
Do you have `signature.target` setting  in your coc-settings.json? By default, signature is displayed in floating, maybe you've changed to `echo`.

**Comment by blockchainian** [comment]
thanks @fannheyward!

i set `signature.enable` to `false`. just found out this option was causing the above-mentioned behavior. i have just removed the option (to replace YCM completion with CoC's.) now everything works like a blast!

**Comment by blockchainian** [comment]
hey @fannheyward!

sorry! actually i spoke too soon. it still happens. here is my CoC Config:

```json
{
    "callHierarchy.enableTooltip": false,
    "callHierarchy.splitCommand": "topleft 42vs",
    "coc.preferences.currentFunctionSymbolAutoUpdate": true,
    "coc.preferences.extensionUpdateCheck": "weekly",
    "diagnostic.enable": false,
    "hover.floatConfig.border": true,
    "inlayHint.enable": false,
    "outline.previewMaxWidth": 100,
    "outline.showLineNumber": false,
    "outline.splitCommand": "topleft 42vs",
    "outline.togglePreviewKey": "?",
    "pullDiagnostic.onChange": false,
    "signature.floatConfig.border": true,
    "signature.floatConfig.borderhighlight": "PmenuBorder",
    "suggest.completionItemKindLabels": {
	  "text": "v",
	  "method": "ƒ",
	  "function": "ƒ",
	  "constructor": "⊕",
	  "field": "∙",
	  "variable": "∙",
	  "class": "∑",
	  "interface": "I",
	  "module": "M",
	  "property": "∙",
	  "unit": "U",
	  "value": "v",
	  "enum": "E",
	  "keyword": "k",
	  "snippet": "S",
	  "color": "v",
	  "file": "F",
	  "reference": "r",
	  "folder": "F",
	  "enumMember": "m",
	  "constant": "≡",
	  "struct": "S",
	  "event": "E",
	  "operator": "O",
	  "typeParameter": "T",
	  "default": ""
	},
    "suggest.floatConfig.border": true,
    "suggest.floatConfig.borderhighlight": "PmenuBorder",
    "suggest.preferCompleteThanJumpPlaceholder": true,
    "tree.openedIcon": "▾",
    "tree.closedIcon": "▸",
    "tree.key.invoke": "<F7>",
    "tree.key.toggle": "o"
}
```

i tried `"signature.target": "float"` as well. the above-mentioned behavior hasn't changed.

**Comment by fannheyward** [comment]
The type declaration shows in `:messages` are not displayed by coc.nvim, try minimal vimrc.

**Comment by fannheyward** [comment]
You've have enabled `coc.preferences.currentFunctionSymbolAutoUpdate`, but this only put function name to `b:coc_current_function`, never display it to `:messages`, properly caused by other plugins.

**Comment by chemzqm** [comment]
Messages from coc.nvim mostly starts with `[coc.nvim]` prefix
