### ISSUE TITLE
how to turn off the diagnostic virtual text displayed on my code?

### ISSUE THREAD

**Issue by pinggit** [neoclide/coc.nvim#4602]
the diagnostic virtual text is sometimes annoying.
I've tried everything I could to turn it off but nothing works.
is there anyway to turn it off? or ideally toggle?

**Comment by fannheyward** [comment]
Have you enabled `diagnostic.virtualText`? It's disabled by default.

**Comment by pinggit** [comment]
No I did not enable that.
actually I have these in ~/.vim/coc-settings.json, still I see virtual texts.

```
{
    "diagnostics.enable": false,
    "diagnostic.displayByAle": false,
    "diagnostic.virtualText": false,
    "suggest.noselect": true,
    "suggest.autoTrigger": "none",
    //"suggest.autoTrigger": "trigger"
}
```
![image](https://user-images.githubusercontent.com/2038044/235334700-295db1bf-fd0e-43a4-a63b-459ed32d5689.png)

**Comment by fannheyward** [comment]
Check `:h coc-inlayHint`.
