### ISSUE TITLE
Popup to completion is freezing on Vim screen

### ISSUE THREAD

**Issue by jerome-diver** [neoclide/coc.nvim#4605]
## Result from CocInfo
Nothing...

empty result

## Describe the bug

When open a ".rs" file (Rust file), it should start rust-analyzer (that i did install from coc-rust-analyzer), but it does not. When i'm going to check what's happening in "htop" tool, i can see  coc.nvim running, but nothing about rust-analyzer. And CocInfo command doesn't open a tab or anything else (no reaction).

## Reproduce the bug

Vim-8.2 installed from Pop!_OS-22.04 packages who are from Ubuntu based distro like)
coc.nvim installed from PlugInstall with coc.ultisnips and some coc lsp integrations (but anyway, it did it from start)

If i kill coc.nvim pid from htop, then restart them from CocStart Vim command, it restart and then autoload rust-analyzer on the opened main.rs file i restart coc.nvim from... then load the rust-analyzer workspace and completion code is workjing half... half because the popup completion still stay open for any reason. 

## CocRestart error
`
Error detected on function coc#rpc#restart[10]..coc#rpc#reaquest[4]..<SNR>39_request[34]..function coc#rpc#restart[10]..coc#rpc#request[4]..>SNR>39_request :
line 29 : 
E605 Exception not intercepted : Eror on "detach" request: Plugin not ready
Error detected on running function coc#rpc#restart : 
line 10 : 
E171: :endif missing
`
still no CocInfo output but coc.nvim/build/index.js running 11 pid in htop view

I have to kill pid from htop the CocStart to get something "working" with coc extention rust-analyzer autostart too... 

## CocInfo when can rich coc.nvim to run
Doesn't show any error and show node version 18.16.0 used
coc.nvim  version 0.0.82-3014125 2023-04-11 14:28:54
and so on with no error logged

- Start (neo)vim with command: `vim -u mini.vim`
It just start vim and show version 8.2.4919, no coc.nvim running, nothing about coc can start.

**Comment by fannheyward** [comment]
> It just start vim and show version 8.2.4919, no coc.nvim running, nothing about coc can start.

Looks like coc.nvim didn't run correctly on Pop!_OS. Have no idea about this, upgrade your vim and try again.

**Comment by fannheyward** [comment]
Close for now.
