### ISSUE TITLE
Prevent `coc#on_enter` putting backslashes inside of braces in Vim9

### ISSUE THREAD

**Issue by ahnafalnafis** [neoclide/coc.nvim#4607]
**Is your feature request related to a problem**
I like `coc#on_enter()`'s cool features. But recently, I've discovered that putting `\` (backslash) while continuing lines in braces is no longer required anymore in Vim9. So, I decided to change this behavior. First off, I thought that it was [lexima.vim](https://github.com/cohama/lexima.vim) which was doing this. But then I realized that it was `coc#on_enter()` instead.

**Describe the solution you'd like**
I want there should no `\` being inserted after pressing `<CR>` inside of braces for Vim9Script like `coc#on_enter` would do for other languages.

**Describe alternatives you've considered**

**Additional context**
**NOTE:** `|` is used to refer the cursor.

**Current behavior:**
```vim
vim9script

var blah = {
  \ |
  \ }
```

**Expected behavior:**
```vim
vim9script

var blah = {
  |
}
```

**Comment by fannheyward** [comment]
Disable `coc.preferences.bracketEnterImprove` and try again.

**Comment by ahnafalnafis** [comment]
Almost solved but it doesn't do the thing that I was expecting.
Disabling `coc.preferences.bracketEnterImprove` results this:
```vim
vim9script

var blah = {
|}
```

**Comment by fannheyward** [comment]
Yes, this disabled formatOnType too.

**Comment by ahnafalnafis** [comment]
Is there other ways to solve this other than that?
