### ISSUE TITLE
How to auto fill a struct

### ISSUE THREAD

**Issue by raiansantos** [neoclide/coc.nvim#4609]
There is a very cool feature in vim-go `:GoFill` which allows you to auto fill a struct.

Is there something like that in coc.vim?

The idea is to use it to auto fill TS objects with type`s default value.
It would be cool to have that for another languages too.

**Comment by fannheyward** [comment]
This needs the language server to support this, maybe from code action, coc.nvim is just a LSP client, if the language server supports this, coc.nvim can apply to fill the struct.

Or, a coc.nvim extension to do this.
