### ISSUE TITLE
Unable to install on vim

### ISSUE THREAD

**Issue by Joellidin** [neoclide/coc.nvim#461]
**Result from CocInfo**
``[coc.nvim] service not started``

**Describe the bug**
Get this error message when entering my .vimrc:
```
Error detected while processing function coc#rpc#init_vim_rpc[1]..coc#rpc#vim_rpc_folder:
line   25:
E121: Undefined variable: p
E116: Invalid arguments for function empty(p)
```

Also when trying to do ``:PlugUpdate`` I get the same error:
```
x Post-update hook for coc.nvim ... Vim(if):E121: Undefined variable: p
```
**To Reproduce**
I am on:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 13 2019 17:40:48)
```

**Comment by chemzqm** [comment]
It's fixed on master, you can install yarn by follow https://yarnpkg.com/en/docs/install to fix this issue.

**Comment by Joellidin** [comment]
Thank you!
