### ISSUE TITLE
我想在statusline显示当前类名函数名，该怎么配置呢

### ISSUE THREAD

**Issue by gamark** [neoclide/coc.nvim#4611]
![acdb4501b1e53a1e04f37085ec8a641](https://user-images.githubusercontent.com/11284639/233599636-fcdc978e-9103-4245-9f60-e37e8ae80a3b.png)
就像这样的显示，用coc.nvim能取到吗

**Comment by fannheyward** [comment]
1. enable `coc.preferences.currentFunctionSymbolAutoUpdate`
2. add `b:coc_current_function` to statusline.

Check `:h coc_current_function`.

**Comment by gamark** [comment]
> 1. enable `coc.preferences.currentFunctionSymbolAutoUpdate`
> 2. add `b:coc_current_function` to statusline.
> 
> Check `:h coc_current_function`.

感谢大佬
