### ISSUE TITLE
how to toggle (enable/disable) coc without reinstall/remove the plugin

### ISSUE THREAD

**Issue by pinggit** [neoclide/coc.nvim#4619]
I've tried COC but ran into a lot of issues without a easy solution.
it might not be the plugin issue, sometimes I just don't know how to fine tune and it takes time to figure things out.
will be good to be able to toggle turning on/off this plugin without remove it or reinstall.

**Comment by fannheyward** [comment]
There're `CocEnable` and `CocDisable`.

**Comment by pinggit** [comment]
thanks!
