### ISSUE TITLE
[NOTICE] rename of builtin configurations.

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#462]
Some configurations are renamed, the old configurations will still work until v0.1 release, so it won't break.

All completion related configuration will be start with `suggest` instead of `coc.preferences`:

* `coc.preferences.autoTrigger` => `suggest.autoTrigger`
* `coc.preferences.languageSourcePriority` => `suggest.languageSourcePriority`
* `coc.preferences.numberSelect` => `suggest.numberSelect`
* `coc.preferences.snippetIndicator` => `suggest.snippetIndicator`
* `coc.preferences.maxCompleteItemCount` => `suggest.maxCompleteItemCount`
* `coc.preferences.preferCompleteThanJumpPlaceholder` => `suggest.preferCompleteThanJumpPlaceholder`
* `coc.preferences.invalidInsertCharacters` => `suggest.invalidInsertCharacters`
* `coc.preferences.fixInsertedWord` => `suggest.fixInsertedWord`
* `coc.preferences.localityBonus` => `suggest.localityBonus`
* `coc.preferences.triggerAfterInsertEnter` => `suggest.triggerAfterInsertEnter`
* `coc.preferences.timeout` => `suggest.timeout`
* `coc.preferences.minTriggerInputLength` => `suggest.minTriggerInputLength`
* `coc.preferences.triggerCompletionWait` => `suggest.triggerCompletionWait`
* `coc.preferences.echodocSupport` => `suggest.echodocSupport`
* `coc.preferences.acceptSuggestionOnCommitCharacter` => `suggest.acceptSuggestionOnCommitCharacter`
* `coc.preferences.noselect` => `suggest.noselect`
* `coc.preferences.keepCompleteopt` => `suggest.keepCompleteopt`
* `coc.preferences.detailMaxLength` => `suggest.detailMaxLength`

All diagnostic related configurations would be starts with `diagnostic` instead of `coc.preferences.diagnostic`:

* `diagnostic.level`
* `diagnostic.refreshOnInsertMode`
* `diagnostic.enable`
* `diagnostic.displayByAle`
* `diagnostic.virtualText`
* `diagnostic.virtualTextPrefix`
* `diagnostic.virtualTextLines`
* `diagnostic.virtualTextLineSeparator`
* `diagnostic.enableMessage`
* `diagnostic.locationlist`
* `diagnostic.highlightOffset`
* `diagnostic.signOffset`
* `diagnostic.errorSign`
* `diagnostic.warningSign`
* `diagnostic.infoSign`
* `diagnostic.hintSign`

`codeLens` related configuration would be starts with `codeLens` instead of `coc.preferences.codeLens`:

* `codeLens.enable`
* `codeLens.separator`

If you're using coc-json, it would show warnings for invalid configuration keys after open configuration file by `:CocConfig`.

**Comment by kutsan** [comment]
Why prefer `suggest` instead of just `completion`, eg. `completion.autoTrigger`? It's better IMO.

**Comment by chemzqm** [comment]
Because it's used by VSCode

**Comment by kutsan** [comment]
Ah! Thanks for the answer.
