### ISSUE TITLE
Py-right always complain: xx is not accssed

### ISSUE THREAD

**Issue by pinggit** [neoclide/coc.nvim#4620]
```
  >>  2 import re
        3          "re" is not accessed (Pyright)
```

I've read https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders
but still could not have any idea.
which exact configuration I need to put in my .vimrc or coc-settings.json config file?

**Comment by fannheyward** [comment]
`not accessed` means you imported this module but never used it in your code.

**Comment by pinggit** [comment]
Oh got it. thanks!
