### ISSUE TITLE
pyright "import xxx could not be resolved"

### ISSUE THREAD

**Issue by pinggit** [neoclide/coc.nvim#4621]
I got a whole bunch of these errors:

```
Import "a.b.c.d" could not be resolved
(Pyright reportMissingImports)
────────────────────────────────────────────────────────────────────────────
https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports
```
I've set PYTHONPATH env correctly, and my python script actually runs without a problem.
I'm feeling I need to configure pyright in coc to recognize my PYTHONFILE env. 
how to resolve this please?

**Comment by fannheyward** [comment]
Pyright requires packages to be type annotated and/or have stub files to work, you can install type-stubs for your module. 

And, this is NOT coc.nvim's issue, don't creat issue here.

**Comment by pinggit** [comment]
for anyone else who ran into same issue, this previous suggestion by you @fannheyward helps to resolve my problem:

https://github.com/fannheyward/coc-pyright/issues/521#issuecomment-858530052

so just put this in .vimrc and it works for me, magically:

```
autocmd FileType python let b:coc_root_patterns = ['.git', '.env', 'venv', '.venv', 'setup.cfg', 'setup.py', 'pyproject.toml', 'pyrightconfig.json']
```
I guess coc is helping pyright to locate the "project root" and after that it works. correct me if I'm wrong.
thanks for all the helps.

**Comment by shaoran** [comment]
@pinggit wow, that really works. The pyright instances launched by COC was ignoring my `pyrightconfig.json` at the root of the project. With the variable `b:coc_root_patterns` it is now working.  What does `coc_root_patterns` do?

**Comment by chemzqm** [comment]
> [@pinggit](https://github.com/pinggit) wow, that really works. The pyright instances launched by COC was ignoring my `pyrightconfig.json` at the root of the project. With the variable `b:coc_root_patterns` it is now working. What does `coc_root_patterns` do?

It helps to resolve workspace folder, see `:h coc-workspace-folders`

**Comment by vitaly-zdanevich** [comment]
> so just put this in .vimrc and it works for me, magically:

not for me :(

**Comment by vitaly-zdanevich** [comment]
> :h coc-workspace-folders

    E149: Sorry, no help for coc-workspace-folders

**Comment by chemzqm** [comment]
Update your coc.nvim and run `:helptags doc`

**Comment by vitaly-zdanevich** [comment]
> :helptags doc

    E150: Not a directory: doc

**Comment by vitaly-zdanevich** [comment]
> Update your coc.nvim

What update do you mean?

**Comment by chemzqm** [comment]
Update extensions and generate docs should be done by yourself or your vim plugin manager, please google or ask AI.

**Comment by vitaly-zdanevich** [comment]
> run `:helptags doc`

Ah, I need to run inside coc folder, done.

**Comment by vitaly-zdanevich** [comment]
> What update do you mean?

Oh, you mean just plugin update - ok I did it, `git pull`, `:CocUpdate`

**Comment by vitaly-zdanevich** [comment]
So, please - any advice? :(

![Image](https://github.com/user-attachments/assets/bed4d33f-7b85-4654-a4da-bd36d85a1c09)

`sqlalchemy` is installed to Python 3.11
`sqlalchemy-stubs` is also installed - also for Python 3.11

pyrightconfig.json:
```
{
	"pythonVersion": "3.11"
}
```
And in Vim config I have

    call coc#config('python', { 'pythonPath': '/usr/bin/python3.11' })

What else should I do?
