### ISSUE TITLE
Add coc-diagnostic-first and coc-diagnostic-last

### ISSUE THREAD

**Issue by fvictorio** [neoclide/coc.nvim#4626]
**Is your feature request related to a problem? Please describe.**
I mapped `[q` and `]q` to `<plug>(coc-diagnostic-prev)` and `<plug>(coc-diagnostic-next)`, which is really useful. I would also like to map `[Q` and `]Q` so that they jump to the first and last diagnostics.

**Describe the solution you'd like**
Add two new mappings: `<plug>(coc-diagnostic-first)` and `<plug>(coc-diagnostic-last)`. Perhaps adding `<plug>(coc-diagnostic-first-error)` and `<plug>(coc-diagnostic-last-error)` for completeness would be useful too.

**Describe alternatives you've considered**
The alternative is to run `:CocDiagnostics` so that the location list is filled, and then use mappings for `:lfirst` and `:llast`, but this has too much friction IMO.

---

This seems like an easier thing to do, so I'm happy to send a PR for this if the feature makes sense and external contributions are accepted.

**Comment by fannheyward** [comment]
Got your point, you can custom function for this, for example:

```
function FirstDiagnostic() abort
  call coc#rpc#request('fillDiagnostics', [bufnr('%')])
  exec 'lopen | lfirst'
endfunction
```
