### ISSUE TITLE
paste function name in CocList -I symbols, the function name display incomplete

### ISSUE THREAD

**Issue by niexin-dev** [neoclide/coc.nvim#4638]
Guys, after I use CocList -I symbols, I use ctrl+shift+v to paste the function, and I can find the corresponding function, but the input column only shows the incomplete function name here, will yours be like this?
![image](https://github.com/neoclide/coc.nvim/assets/8086937/0d490ee2-dcd6-4681-9dd2-75bfe10d8de1)

**Comment by niexin-dev** [comment]
I copied the function name uart_recv_thread_mc665, after using ctrl+shift+v to paste the function, the display is incomplete

**Comment by fannheyward** [comment]
Similar https://github.com/neoclide/coc.nvim/issues/2536

**Comment by niexin-dev** [comment]
https://github.com/neoclide/coc.nvim/assets/8086937/4c57be48-2e01-4f36-8275-6ef4d04a3c72

我认为是插件没反应过来。我粘贴了三次同样的字符串，有时候在输入栏可以显示完整，有时候只显示部分，有时候只显示一个字符。当我再按一个空格键，我粘贴的字符串会显示完整。

**Comment by chemzqm** [comment]
Make sure your clipboard works on your neovim, see `:h clipboard`.
Use `<C-v>` to paste or create custom key-mappings see `:h coc-list-mappings-custom`
