### ISSUE TITLE
Error detected while processing function coc#_complete

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#464]
**Result from CocInfo**
vim version: NVIM CocFloatingWindow
node version: v11.10.0
coc.nvim version: 0.0.56
term: xterm-256color
platform: linux

![ezgif-2-d435c0e78940](https://user-images.githubusercontent.com/29133776/53292431-6cb30280-3790-11e9-8347-1dd515eb5f88.gif)

**Comment by chemzqm** [comment]
Looks like your neovim is broken, I can't reproduce it.

**Comment by Avi-D-coder** [comment]
It was a fork of master. I will reopen if I experience it on the latest release.
