### ISSUE TITLE
 How to use `let g:coc_global_extensions = ['coc-json', 'coc-git']` in lua config

### ISSUE THREAD

**Issue by wen-nan** [neoclide/coc.nvim#4641]
## Describe the bug

I hope to automatically install the coc extensions in my lua configuration, like `let g:coc_global_extensions = ['coc-json', 'coc-git']`, but I don't know how to set it up.

The code I configure below doesn't seem to be working.
`_G.coc_global_extensions = { 'coc-json', 'coc-git'}`

**Comment by ycycyyc** [comment]
vim.g.coc_global_extensions = {'coc-json', 'coc-git'}
