### ISSUE TITLE
vim: scrolling of the floating preview window of CocList doesn't work

### ISSUE THREAD

**Issue by monkoose** [neoclide/coc.nvim#4643]
**EDIT**: because it doesn't work in normal mode too.

## Result from CocInfo
vim version: VIM - Vi IMproved 9.0 9001506
node version: v19.9.0
coc.nvim version: 0.0.82-3014125 2023-04-11 14:28:54 +0800
coc.nvim directory: /home/monkoose/.vim/pack/minpac/opt/coc.nvim
term: dumb
platform: linux

## Describe the bug
In vim  when `"list.floatPreview": true` is set it is impossible to scroll preview window with `do:previewup` or `do:previewdown`.

## Reproduce the bug

Add to your `coc-settings.json` this code
```json
{
  "list.floatPreview": true,
  "list.insertMappings": {
     "<C-n>": "do:previewdown",
     "<C-p>": "do:previewup"
  },
  "list.normalMappings": {
     "<C-n>": "do:previewdown",
     "<C-p>": "do:previewup"
  }
}
```
Open some list in insert mode that can have preview window like `:CocList outline`, toggle preview window and try your mappings to scroll it. Nothing happens.

**Comment by fannheyward** [comment]
Yes, the scrolling of preview only works in normal mode.

**Comment by fannheyward** [comment]
Do you mean scroll the preview window with `C-f`?

**Comment by fannheyward** [comment]
> `C-f` scrolls list window itself 

Yes.

**Comment by fannheyward** [comment]
Reproduced with vim, nvim works as expected.

**Comment by fannheyward** [comment]
> In normal mode it is working.

Does scrolling work in normal mode with `list.floatPreview = true` in vim?

In my tests, when `list.floatPreview = true`, scrolling of the float preview didn't work in insert or normal in vim.

**Comment by monkoose** [comment]
> > In normal mode it is working.
> 
> Does scrolling work in normal mode with `list.floatPreview = true` in vim?
> 
> In my tests, when `list.floatPreview = true`, scrolling of the float preview didn't work in insert or normal in vim.

Oops. Sorry for confusion. Yes it doesn't work (I in my config just have some general floating window scroll mappings that are mapped to `<C-n>` and `<C-p>` so because of this it worked in normal mode for me. 
Can confirem now that it doesn't work in either mode: normal or insert.
