### ISSUE TITLE
Language server incorrectly treats netrw buffer as a file

### ISSUE THREAD

**Issue by wgwz** [neoclide/coc.nvim#4649]
## Result from CocInfo

```
vim version: VIM - Vi IMproved 9.0 9001550
node version: v20.2.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /Users/kyle/.vim/plugged/coc.nvim
term: tmux
platform: darwin
```

## Describe the bug

When I use `:Explore` in a window where a file that was using a language server, `coc.nvim` seems to think the file is open.
It still tries to process the netrw buffer as if it is a file that needs to be processed.

![Screen Shot 2023-05-23 at 3 51 44 PM](https://github.com/neoclide/coc.nvim/assets/10120306/ac6b8657-7eb1-4925-9e72-8069a131e1ca)

## Reproduce the bug

- Create file `mini.vim` with：

```vim
filetype plugin indent on
set tabstop=4
set shiftwidth=2
set expandtab

nmap <C-P> :FZF<CR>

call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug '/opt/homebrew/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'lifepillar/pgsql.vim'
Plug 'godlygeek/tabular'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'tpope/vim-fugitive'
Plug 'junegunn/goyo.vim'
call plug#end()

" highlight all sql files as pgsql
let g:sql_type_default = 'pgsql'

" Set internal encoding of vim, not needed on neovim, since coc.nvim using some
" unicode characters in the file autoload/float.vim
set encoding=utf-8

" TextEdit might fail if hidden is not set.
set hidden

source ~/.vimrc-coc-new

set backspace=indent,eol,start

let g:go_highlight_debug = 1

au BufRead,BufNewFile *.jsonld setfiletype json
let g:coc_filetype_map = {
  \ 'jsonld': 'json',
  \ }
```

where `~/.vimrc-coc-new` is nearly exactly what [the config docs](https://github.com/neoclide/coc.nvim#example-vim-configuration) show.
aside from these small differences:
```
...
-set signcolumn=yes
+set signcolumn=no
...
-set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
+" set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
Tested with same Vim version with latest coc.nvim, but I can't reproduce this.

1. open a TS file, for example `src/workspace.ts`
2. coc-tsserver started
3. `:Explore` to open netrw
4. move to any ts file, tsserver didn't report errors

<img width="436" alt="截屏2023-05-24 15 26 47" src="https://github.com/neoclide/coc.nvim/assets/345274/22e40c71-0156-4eb5-a949-33857176ba35">

**Comment by fannheyward** [comment]
<img width="1222" alt="截屏2023-05-24 17 33 48" src="https://github.com/neoclide/coc.nvim/assets/345274/74e28dfd-8deb-4177-9a01-f1a81f20fbe1">

**Comment by wgwz** [comment]
Thanks for taking a look @fannheyward , I'll try to see if I can figure out how to reproduce it and share back here if I can figure it out. I'll have some time in the next few days to do that. Either way I'll post an update here.

**Comment by jiangtianli91** [comment]
I have also encountered this issue. I think this is due to a [bug](https://github.com/neovim/neovim/issues/23515) in Vim 9.
