### ISSUE TITLE
coc#pum#next(1) switch is very stuttering

### ISSUE THREAD

**Issue by chaozwn** [neoclide/coc.nvim#4653]
## Describe the bug

coc#pum#next(1) switch is very stuttering

https://github.com/neoclide/coc.nvim/assets/51357674/b909c421-f1f6-4bcf-a80c-627108e1f7cc

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

**Comment by fannheyward** [comment]
Tested with Lua, can't reproduce this, try minimal vimrc, looks like some insert mode mappings interfere it.

**Comment by chaozwn** [comment]
> Tested with Lua, can't reproduce this, try minimal vimrc, looks like some insert mode mappings interfere it.

tmux plugin cause it.

**Comment by chaozwn** [comment]
closed

**Comment by chaozwn** [comment]
close.
