### ISSUE TITLE
Log files are created along side the files being opened!

### ISSUE THREAD

**Issue by jikkujose** [neoclide/coc.nvim#4655]
### `:CoCInfo`

``` txt
## versions

vim version: NVIM v0.9.0
node version: v14.17.6
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/username/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2023-05-28T15:39:22.473 INFO (pid:66915) [services] - registered service "tsserver"
2023-05-28T15:39:22.584 INFO (pid:66915) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v14.17.6 after 826ms
2023-05-28T15:39:22.899 INFO (pid:66915) [services] - service tsserver started
2023-05-28T15:39:24.062 INFO (pid:66915) [attach] - receive notification: showInfo []
```

### Bug

Following log files are being created in the directory of the file being edited.

``` text
coc-nvim-tsc.log
coc.nvim-65887
coc.nvim-66915
node-client-65887.log
node-client-66915.log
ti-65893.log
ti-66923.log
```

### Expectation

Log files won't be created in the same folder as code.

### Vim Config

[init.vim](https://github.com/jikkujose/dotfiles/blob/v-2023/nvim/legacy/init.vim)

**Comment by fannheyward** [comment]
> coc.nvim version: 0.0.80-03c9add7cd

You're using an outdated coc.nvim, upgrade and try again.

**Comment by jikkuatwork** [comment]
But I did a fresh start. Anyways, I tried the following:

- `:CocUpdate` (All plugins were shown as latest)
- `:PlugUpdate` (All plugins were shown as latest)
- `:PlugUpdate` (Errored, but then I went and manually updated vim-plug)

Is there anything more to do to update `CoC`? Whats the latest version? Where can I find the current project version? How can I update to it?

**Comment by fannheyward** [comment]
Still can't reproduce the tscancellation temp files issue, and I didn't find anyone report this, have no idea about this.

Does the `animals.js` located in tmp dir? by default, coc-tsserver will create `coc-tsserver` folder in tmp dir to save tscancellation files.

**Comment by jikkuatwork** [comment]
Thanks for helping, I know it sounds terribly weird! 

I just nuked my entire init.vim and placed the following 3 lines alone:

``` vimscript
call plug#begin('~/.fresh/plugged')
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```
Still that folder is created!!

### Note

- I am placing the config at `~/config/nvim/fresh` and refrencing it via `NVIM_APPNAME` (=nvim/fresh)
- `~/.fresh/plugged` only contains coc plugin
- I use asdf for node
- nvim is 0.9
- I have three extensions in coc: `coc-prettier`, `coc-tsserver` and `coc-extensions`

### OS

``` text
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.04
DISTRIB_CODENAME=lunar
DISTRIB_DESCRIPTION="Ubuntu 23.04"
```

### Questions

1. Is there any config that specifies the location of the tmp files?
2. Is it possible to install coc without vim-plug (I can't think of any other possibilities)

**Comment by jikkuatwork** [comment]
# Update!

I removed the `NVIM_APPNAME` reference and placed the config in default path and the issue went away! I wonder I won't be able to create multiple profiles with the environment variable!

Thats sad, but at least we know the problem. 

Perhaps you can now find out why this happened.

**Comment by fannheyward** [comment]
> Is there any config that specifies the location of the tmp files?

No, the temp `dir = path.join(os.tmpdir(), `coc-tsserver`)`

https://github.com/neoclide/coc-tsserver/blob/d8a2f44d64fcefaf6a2087cd5d0b7783393b73d7/src/server/utils/temp.ts#L24

> Is it possible to install coc without vim-plug 

Yes, try any another plugin manager

> removed the NVIM_APPNAME reference and placed the config in default path and the issue went away

Have no idea about `NVIM_APPNAME`, but I don't think this change the `os.tmpdir()` dir.

Close for now cause this is not coc.nvim's issue.
