### ISSUE TITLE
Support nodejs 20

### ISSUE THREAD

**Issue by MoetaYuko** [neoclide/coc.nvim#4656]
**Is your feature request related to a problem? Please describe.**
Some dependencies don't support nodejs 20, e.g.,
```
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error eslint-plugin-jsdoc@39.6.4: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.2.0"
error Found incompatible module.
```

**Describe the solution you'd like**
Updated outdated dependencies to the latest version to support nodejs 20, and fix incompatible parts of coc itself (if any)

**Describe alternatives you've considered**

**Additional context**

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/pull/4627
