### ISSUE TITLE
`coc-definition` Can I split the screen and open it?

### ISSUE THREAD

**Issue by JiehuiSun** [neoclide/coc.nvim#4657]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this feature is available

**Describe the solution you'd like**
`.vimrc config` nmap <silent> gd <Plug>(coc-definition)
At new split screen  jump to definition 

**For Example**
![image](https://github.com/neoclide/coc.nvim/assets/32083752/68bb2309-a540-4ad6-aea8-bde3f53f2397)

**Comment by fannheyward** [comment]
`:h coc-preferences-jumpCommand`.

**Comment by JiehuiSun** [comment]
Yes, your answer is of no use at all, because I asked without knowing.

**Comment by chemzqm** [comment]
`:h CocAction('jumpDefinition')`, use open command argument.

**Comment by JiehuiSun** [comment]
您好，邮件已收到。
