### ISSUE TITLE
g:coc_user_config doesn't work with new renamed options

### ISSUE THREAD

**Issue by kutsan** [neoclide/coc.nvim#466]
**Result from CocInfo**
vim version: NVIM v0.4.0-dev
node version: v11.10.0
coc.nvim version: 0.0.56
term: xterm-256color
platform: darwin

**Describe the bug**
Configuration object `g:coc_user_config` doesn't work if I put options that starts with `suggest` and such in it but `coc.preferences` ones do work.

**To Reproduce**

Doesn't work:

```vim
let g:coc_user_config = {
	\ 'suggest': {
		\ 'numberSelect': v:true
	\ }
\ }
```

Does work:

```vim
let g:coc_user_config = {
	\ 'coc.preferences': {
		\ 'numberSelect': v:true
	\ }
\ }
```

**Comment by chemzqm** [comment]
Tested works as expected for me.

**Comment by kutsan** [comment]
Yeah, that was the case, I forgot a build needed.

**Comment by leosmaia21** [comment]
Hello 
Does anyone know how to fix this?
 \'explorer.keyMappings': {            
         \ '<cr>' : '["expandable?", "expand", "open"]'                  
     \ },                                                             
its not working
