### ISSUE TITLE
Support inline virtual text

### ISSUE THREAD

**Issue by chaozwn** [neoclide/coc.nvim#4660]
**Is your feature request related to a problem? Please describe.**
neovim 0.10 support inline virtual text. so we can make lsp hints show before parmeters , which is always show as last before.
you can get help from link: https://github.com/lvimuser/lsp-inlayhints.nvim/issues/46

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chaozwn** [comment]
<img width="370" alt="3a850084447aa2d91751b0e95610fc5" src="https://github.com/neoclide/coc.nvim/assets/51357674/c68623b7-08cb-48d1-9172-59d6acd4ccb0">

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/pull/4648
