### ISSUE TITLE
Cannot disable inlayHint default feature

### ISSUE THREAD

**Issue by victorfeijo** [neoclide/coc.nvim#4663]
Current coc config file `~/.vim/coc-settings.json`:

```
{
  "inlayHint.enable": false,
  "inlayHint.display": false,
  "inlayHint.enableParameter": false
}
```
I'm still seeing them everywhere. Am I using the wrong config? I've just updated my Mac and seems like CoC has this enabled by default but its quite annoying.

<img width="938" alt="image" src="https://github.com/neoclide/coc.nvim/assets/8865899/8c498333-9274-4dc8-89d9-993e88248e39">

**Comment by fannheyward** [comment]
This isn't inlayHint, but diagnostics displayed in virtual text.
