### ISSUE TITLE
Cannot install extensions in command line with `-sync`

### ISSUE THREAD

**Issue by juxuny** [neoclide/coc.nvim#4665]
## versions                   
                                                                                                                          
vim version: VIM - Vi IMproved 9.0 9000749                                                                                
node version: v16.20.0                                                                                                    
coc.nvim version: 0.0.82-2a0e5546 2023-06-03 04:13:22 +0800                                                               
coc.nvim directory: /root/.vimpkg/bundle/coc.nvim                                                                         
term: dumb                                                                                                                
platform: linux

## Describe the bug

I can't install extensions in command line with `vim +'CocInstall -sync coc-tabline' +qall`, it show me some errors:

```bash
Error detected while processing command line..function coc#util#install_extension[4]..coc#rpc#request[4]..<SNR>20_request[34]..command line..function coc#util#install_extension[4]..coc#rpc#request[4]..<SNR>20_request:
line   29:
E605: Exception not caught: Error on "installExtensions" request: call_atomic request error on "nvim_call_function": Vim(return):E28: No such highlight group name: CocListFgCyan on function "call_function"
Press ENTER or type command to continue

```

## Reproduce the bug

1. create a Dockerfile

```
FROM registry.cn-shenzhen.aliyuncs.com/juxuny-public/vim:base-v1.1.0
ADD node-v16.20.0-linux-x64.tar.gz /root/
ENV PATH=${PATH}:/root/node-v16.20.0-linux-x64/bin
RUN mkdir -p ~/.vim/autoload ~/.vim/bundle /root/gopath 
COPY ./pathogen.vim /root/.vim/autoload/pathogen.vim
COPY .vimrc /root/.vimrc
RUN cd /usr/local/lib && git clone https://github.com/egalpin/apt-vim.git
ADD go1.18.10.linux-amd64.tar.gz /root/
ENV GOPATH=/root/gopath
ENV GOPROXY=https://goproxy.cn
ENV GOROOT=/root/go
ENV TERM=xterm-256color
ENV PATH=$PATH:/usr/local/lib/apt-vim:/root/.vimpkg/bin:$GOPATH/bin:$GOROOT/bin
RUN cd /usr/local/lib/apt-vim && apt-vim init
RUN apt-vim install -y https://github.com/altercation/vim-colors-solarized.git
RUN apt-vim install -y https://github.com/vim-scripts/mayansmoke.git
RUN apt-vim install -y https://github.com/mileszs/ack.vim.git
RUN apt-vim install -y https://github.com/itchyny/lightline.vim.git
RUN apt-vim install -y https://github.com/junegunn/fzf.vim.git
RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
RUN echo "\n\n\n" | ~/.fzf/install
RUN npm -g install js-beautify
RUN apt-vim install -y https://github.com/fatih/vim-go.git
RUN apt-get install -y python3-pip
RUN pip3 install jedi
RUN apt-vim install -y https://github.com/neoclide/coc.nvim.git
RUN npm config set registry http://registry.npmmirror.com
RUN npm install -g yarn
RUN cd /root/.vim/bundle/coc.nvim && yarn install
RUN vim +'GoInstallBinaries' +qall
RUN vim +'CocInstall -sync coc-tsserver coc-go coc-tabnine' +qall
```

2. build the image
```bash
docker build -t coc.nvim -f Dockerfile .
```

the full respository is here [https://github.com/juxuny/vim/tree/coc.nvim](https://github.com/juxuny/vim/tree/coc.nvim
)
3. run into the container
```bash
docker run -it --rm --entrypoint bash coc.nvim 
vim +'CocInstall -sync coc-tsserver coc-go coc-tabnine'
```
then I got the errors:
![image](https://github.com/neoclide/coc.nvim/assets/3386613/5fb20aa7-8972-4e5a-9ab2-5fbe77e15733)

**Comment by fannheyward** [comment]
Reproduced with vim 9+, works as expected in nvim. coc will create highlight groups after `VimEnter`, looks like this fails/blocked in vim.

A temporary solution: define the `CocListFgCyan` `CocListFgGreen` and `CocListFgRed` highlight group in your vimrc like:

```
hi default CocListFgCyan guifg=#8BE9FD ctermfg=Cyan
hi default CocListFgGreen guifg=#50FA7B ctermfg=Green
hi default CocListFgRed guifg=#cc241d ctermfg=Red
```

You can get the RGB value by `:verbose hi CocListFgRed`.

**Comment by juxuny** [comment]
I found another temporary solution: 

1. create init.vim file with content: 
```bash 
:CocInstall -sync coc-tabnine coc-tsserver coc-json coc-html coc-sql coc-lua coc-css coc-less coc-sass coc-eslint coc-wxml coc-xml coc-stylelint coc-tslint coc-go coc-php coc-sh coc-flutter coc-dlang coc-java coc-markdownlint coc-pylsp coc-snippets|q
```
2. run `vim -s init.vim`
