### ISSUE TITLE
Coc PMenu allow user select item not replace input chars.

### ISSUE THREAD

**Issue by chaozwn** [neoclide/coc.nvim#4666]
**Is your feature request related to a problem? Please describe.**
when i use autocompletion, i input something, when i choose next-item, my source input will be replace by recommend items. 

**Describe the solution you'd like**
can you provide behavior like select not replace. just like idea or vscode.

**Describe alternatives you've considered**

**Additional context**

**Comment by fannheyward** [comment]
Check `:h coc#pum#next()`, the `insert` param is used to control insert word or not.

**Comment by chaozwn** [comment]
> Check `:h coc#pum#next()`, the `insert` param is used to control insert word or not.

thanks.
