### ISSUE TITLE
Select/unselect itens is not working with vim (just works with nvim)

### ISSUE THREAD

**Issue by amgodoi** [neoclide/coc.nvim#4673]
After type ":CocAction" I choose "Generate Constructors...", but I am not able to select anything (image bellow).
I tried other keys, but unsuccessfully. Everything I type is used as a filter in the text box.

CocAction is defined like this in .vimrc:
command! -nargs=* -range CocAction :call CocActionAsync('codeActionRange', <line1>, <line2>, <f-args>)

This kind of selection works only using "neovim", but not with "vim".

![image](https://github.com/neoclide/coc.nvim/assets/78377022/3ea1ffb8-9995-4821-ba0f-bf421f681fd4)

**Comment by fannheyward** [comment]
`:CocInfo` please, tested with `Vi IMproved 9.0 9001600`, works as expected.

<img width="241" alt="image" src="https://github.com/neoclide/coc.nvim/assets/345274/113634f6-0328-4e51-975b-be7b6917954f">

**Comment by amgodoi** [comment]
I have found this documentation:

![image](https://github.com/neoclide/coc.nvim/assets/78377022/81d3b765-838a-4f6d-9148-5a3d5e37f095)

But "<C-space>" does not work inside vim, just works with neovim.

**Comment by fannheyward** [comment]
@amgodoi hello, tested vim 9.0 9001650 and 9.0 9000472, `C-space` can do multiple items

<img width="921" alt="image" src="https://github.com/neoclide/coc.nvim/assets/345274/385353a4-0163-4722-ad7a-4743a9445c0c">

(hack `workspace.showOutput` command to allow `canPickMany`, for debugging.

**Comment by amgodoi** [comment]
hi @fannheyward

I am yet not able to select multiple options.

A tried a new vim version, minimum .vimrc, new node version, and just coc.nim plugin, but not working yet.

I did not understand "workspace.showOutput". What can I do with that?

![image](https://github.com/neoclide/coc.nvim/assets/78377022/049f0bcd-069c-4559-bc52-015fbae3318f)

**Comment by amgodoi** [comment]
Another observation.

With gvim I able to select/unselect items.

I wonder that I am missing some configuration. Maybe some key configuration?

![image](https://github.com/neoclide/coc.nvim/assets/78377022/c1978ff6-711b-424c-bdc0-7557a2f9e352)

**Comment by amgodoi** [comment]
hi @fannheyward

This source file:
./src/model/quickpick.ts

At this point:
![image](https://github.com/neoclide/coc.nvim/assets/78377022/df339860-bbac-45cf-bedd-9336ee55e9cd)

For some reason the event is never triggered with <C-space> using vim. With neovim and gvim it works.

I known that vim has some problems with <C-space> because it is not ASCII character, but with nevim it works.

I am using urxvt as my terminal. I tried "xfce terminal", "gnome terminal" and not worked too. But ... with xterm, for some reason, <C-space> was triggered and worked.

I am not sure yet about the problem. Maybe something with vim + terminal, but this problem does not appear with neovim + terminal.

Any idea?

**Comment by amgodoi** [comment]
Hi!

I think this is not a vim problem. Rxvt terminal does not send <C-space> to vim, it sends <NUL> instead. For some reason it is not handled.

I figured out configuring rxvt to send <C-space> and worked, but it is a pity that <NUL> cannot be handled.

Thanks a lot.

**Comment by luocm03** [comment]
I tried gvim version with 9001677, 900475, but nothing helps. I still can't select anything in the quickpick box.
<img width="959" alt="重载方法无法选择" src="https://github.com/user-attachments/assets/35945a5e-23f1-4083-9630-881611cb6651">
