### ISSUE TITLE
Set filetype in list previews

### ISSUE THREAD

**Issue by andrhua** [neoclide/coc.nvim#4674]
**Is your feature request related to a problem? Please describe.**
For `:CocList -A outline` neither preview splits or floats have set filetype, and so treesitter highlighting won't work there

**Describe the solution you'd like**
List previews should preserve filetypes so it possible to have all the bells and whistles improving code readability

**Describe alternatives you've considered**
coc-outline previews do have proper filetype, but IMO the concept of persistent buffer doesn't make much sense in vim, so I prefer quicklist instead

**Comment by fannheyward** [comment]
The preview window already has `filetype` info, also highlighting works too.

<img width="423" alt="image" src="https://github.com/neoclide/coc.nvim/assets/345274/d55cd7a5-55cf-40e3-be47-1477f9dbac41">

**Comment by andrhua** [comment]
interesting, for me it doesn't have filetype, see output of `:set filetype?`
![image](https://github.com/neoclide/coc.nvim/assets/15843809/4caed21a-a3ad-404b-8ad7-20ff78e14ef7)
but it has fallback regex-based syntax highlighting

**Comment by chemzqm** [comment]
The buffer have syntax highlight only,  to avoid issues with filetype.
