### ISSUE TITLE
Every time you close the manage extension page, the cmd-height value will increase by 1.

### ISSUE THREAD

**Issue by chaozwn** [neoclide/coc.nvim#4677]
## Describe the bug

Every time you close the manage extension page, the cmd-height value will increase by 1

https://github.com/neoclide/coc.nvim/assets/51357674/925cb717-3a75-497b-aead-3a46d808f4d7

## Reproduce the bug

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
`winbar` setting related https://github.com/neoclide/coc.nvim/issues/4555

**Comment by chemzqm** [comment]
Fixed by 0c2c64c6
