### ISSUE TITLE
Adding nixd as a nix language server as rnix-lsp seems no longer actively maintained since Nov. 2022

### ISSUE THREAD

**Issue by AkechiShiro** [neoclide/coc.nvim#4688]
**Is your feature request related to a problem? Please describe.**
It seems the only language server as an extension for the Nix language is not maintained anymore or doesn't look like it's actively maintained.

**Describe the solution you'd like**
I'd like a new coc extension named coc-nixd that relies on [nixd](https://github.com/nix-community/nixd).

**Describe alternatives you've considered**
Using only [rnix-lsp](https://github.com/nix-community/rnix-lsp) as a language server for nix support despite it not having active commits/maintenance.

**Additional context**
[Latest commit in rnix-lsp](https://github.com/nix-community/rnix-lsp/commit/95d40673fe43642e2e1144341e86d0036abd95d9) (27 November 2022)
[Latest commit in nixd](https://github.com/nix-community/nixd/commit/912e7733bb76eab474398f22dec513cc917d077c) (26 June 2023)

If there is anything I could help with to help making this happen, I'll be happy to give it a try, I'll first go read the contributions guidelines.

**Comment by fannheyward** [comment]
Try this in your coc-settings.json (not tested)

```json
"languageserver": {
  "nixd": {
    "command": "nixd",
    "rootPatterns": [".nixd.json"],
    "filetypes": ["nix"]
  }
}
```

**Comment by AkechiShiro** [comment]
That didn't seem to work alright actually, there is a config mentioned in the readme of rnix-lsp : https://github.com/nix-community/rnix-lsp#cocnvim
```json
{
  "languageserver": {
    "nix": {
      "command": "rnix-lsp",
      "filetypes": [
        "nix"
      ]
    }
  }
}
``` 
I believe this should be documented, let me know if I can open up a PR with this documentation or maybe just adding a link towards this README section.
I'm not sure where this would go since this isn't a coc-extension but more a language-server config.

**Comment by AkechiShiro** [comment]
There is also a nixd configuration which is another nix LSP, actively maintained : https://github.com/nix-community/nixd/blob/main/docs/editor-setup.md#cocnvim

**Comment by AkechiShiro** [comment]
I'm still trying to make it work maybe I have an issue, do the file .nixd.json need to exist for the LSP to start showing errors ?
