### ISSUE TITLE
Only able to see definitions and references of default exports

### ISSUE THREAD

**Issue by blkwtkns** [neoclide/coc.nvim#469]
I have found that in certain projects, I can only get definitions and references of external functions/symbols if they are a default export. I found this issue, https://github.com/neoclide/coc.nvim/issues/86, and can confirm that I can see references that have the same sort of syntax. But if a symbol has been imported like `import { foo} from 'bar';` I only get bounced around the current buffer. Is this ever expected? In the specific project I'm referring to, it is currently restricted to an older version of Node. This is the only thing I can find that might be causing the issue, but I wanted to see if I could verify this. 

Heres the `:CocInfo` output as well:
## versions

vim version: NVIM v0.3.3
node version: v8.9.0
coc.nvim version: 0.0.57
term: screen-256color
platform: darwin

## Output channel: tsserver
[Info  - 16:01:07] TSServer log file :
/var/folders/fv/d4275tv15rq56j2kltbfvsc00000gp/T/coc-nvim-tsc.log
[Info  - 16:01:07] Forking TSServer
PATH: /Users/bwatkins/.nvm/versions/node/v6.10.2/bin:/Users/bwatkins/.nvm/versions/node/v11.6.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/python@2/libexec/bin:/Users/bwatkins/.gem/ruby/2.3.0/bin:/Users/bwatkins/bin:/Users/bwatkins/go/bin:/Users/bwatkins/.cargo/bin:/Users/bwatkins/.local/bin:/usr/local/bin:/usr/local/sbin:/Users/bwatkins/bin:/Users/bwatkins/.yarn/bin:/Users/bwatkins/.config/yarn/global/node_modules/.bin:/Users/bwatkins/.cargo/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bwatkins/.nvm/versions/node/v11.6.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/python@2/libexec/bin:/Users/bwatkins/.gem/ruby/2.3.0/bin:/Users/bwatkins/go/bin:/Users/bwatkins/.local/bin:/Users/bwatkins/Documents/Projects/docker-mercury/bin:/Users/bwatkins/.fzf/bin 
[Info  - 16:01:07] Started TSServer
{
  "path": "/Users/bwatkins/.config/coc/extensions/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.3.3333",
    "version": "3.3.3333"
  }
}

## Output channel: highlight
[Info  - 16:01:07] Highlight server running in node v8.9.0

I just started using your plugin last night, and it's quite a gem. Many thanks, it's really fantastic!

**Comment by chemzqm** [comment]
One possible reason is project root is wrong, try create a `.git` folder in your project root to see if the problem still exists, you can change `"coc.preferences.rootPatterns"` in settings file to fix the root.

Checkout verbose output of tsserver https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel for the project root information.

**Comment by blkwtkns** [comment]
I think I understand what is occurring on my system, and I think I need to change my question now. The project root is correct, for the project, but paths being used for JS modules are relative to a `js` directory which sits in the root directory via aliasing using SystemJS. Would I still need to directly change the `"coc.preferences.rootPatterns" property, or is another way to go about this?

**Comment by chemzqm** [comment]
If you're using alias you should create jsconfig.json file and configure it to make tsserver understand your path resolve.

**Comment by blkwtkns** [comment]
This works! Issue now is that I think my config is wrong, and while it's enabling definition to work, I can't access references now. Here's the jsconfig.json right, which is sitting in my `js` directory:

```
{
  "compilerOptions": {
    "baseUrl": "."
  },
  "exclude": [
    "node_modules",
    "tmp",
    "compiled",
    "temp"
  ]
}
```

**Comment by blkwtkns** [comment]
The following actually seems to be working for me (located in same directory `<rootDir>/js`:
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "module": "es6",
    "paths": {
      "*": ["./**/*"]
    }
  },
  "exclude": [
    "node_modules",
    "bower_components",
    "jspm_packages",
    "tmp",
    "temp",
    "compiled",
    "deprecated"
  ]
}
```

**Comment by danielo515** [comment]
Ok, I had to create a jsconfig.json file to make coc work properly.
I guess this is something required when you work on a project that has javascript projects under a sub-directory (ej, a fullstack project with backend and frontend). Is it on the docs? I would love to check against them to validate my config.

**Comment by chemzqm** [comment]
Google jsconfig.json it's used by tsserver

**Comment by danielo515** [comment]
> Google jsconfig.json it's used by tsserver

Sure, I'll do it. But is it documented that COC requires it?

**Comment by chemzqm** [comment]
it's used by tsserver

**Comment by danielo515** [comment]
> it's used by tsserver not always required

OK, that's a technically correct. But issues like this will require a jsconfig to make COC work properly. I think it is and edge case it's worth documenting.

**Comment by chemzqm** [comment]
You can send PR to coc-tsserver project
