### ISSUE TITLE
set filetype=a.b to use both lanuagesevers for a and b

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#4698]
**Describe the solution you'd like**
set filetype=a.b to use both lanuagesevers for a and b

**Additional context**
vim allows user to `:set filetype=foo.bar`. However, it looks only languagesever for foo can be enabled on coc.nvim.

**Comment by yaegassy** [comment]
Try using `coc_filetype_map`. For example, to make `foo.bar` recognized as an `baz` file type, set it like this

**e.g.**:

> .vimrc/init.vim

```vim
let g:coc_filetype_map = {
  \ 'foo.bar': 'baz',
  \ }
```

**Comment by Freed-Wu** [comment]
I think it is not a same thing. For example, if there are two language servers, one for `c`, another is to complete `doxygen`'s special words, I hope `set filetype=c.doxygen` to use both of them. In fact, c is not the only one language which doxygen supported, it can have `set filetype=XXX.doxygen` for many languages.

**Comment by fannheyward** [comment]
> filetype=foo.bar

Yes, coc will only enable language server for _main_ filetype `foo`, https://github.com/neoclide/coc.nvim/issues/3358.

**Comment by Freed-Wu** [comment]
I found the issue is a repetition of #3358. Sorry!
