### ISSUE TITLE
Complete list sources

### ISSUE THREAD

**Issue by ssmithstone** [neoclide/coc.nvim#47]
**Describe the bug**
Not a bug report or feature request most of a question about the completion list

Given i have used a js/ts builtin type console when popup menu appears i current see a selection from the actual module but also the File how do I make is so that the only options available in the menu are from that actual module and no-other sources.

![1__tmux__tmux_](https://user-images.githubusercontent.com/140544/43807342-545e4efc-9aeb-11e8-8b26-3b50bbf9229d.jpg)

**Comment by chemzqm** [comment]
> i current see a selection from the actual module but also the File

What does this mean, the picture uploaded only shown completion items from tsserver.

**Comment by ssmithstone** [comment]
I would only expect to see the Method options and not the File options on completion of console.l

**Comment by chemzqm** [comment]
It works as expected for typescript files:
<img width="337" alt="screen shot 2018-08-08 at 8 30 30 am" src="https://user-images.githubusercontent.com/251450/43809593-9fd91af2-9ae5-11e8-9aa1-b96b3e2f251f.png">
But I could get much more complete items for javascript files. 
Are you using javascript?

**Comment by ssmithstone** [comment]
Ah yes , using javascript with a tsconfig.json inside vim and the same files inside of vscode

**Comment by ssmithstone** [comment]
so I get the issue inside __tests__/**/*.spec.js files and not src/*.js files , something must be wrong with my setup , keep up the good work on the plugin

**Comment by chemzqm** [comment]
It's not problem of your setup, I have fixed that.

**Comment by ssmithstone** [comment]
ok i've reopened this so we can continue conversation

**Comment by ssmithstone** [comment]
odd , just gone back into .spec file and its working now as expected
