### ISSUE TITLE
Yarn executable not found on Fedora

### ISSUE THREAD

**Issue by dm19** [neoclide/coc.nvim#470]
[On Fedora 29](https://developer.fedoraproject.org/tech/languages/nodejs/nodejs.html) the executable for yarn is `nodejs-yarn`, which does not seem to be found by coc. Linking the executable to `/usr/bin/yarn` or somewhere else in your path is a trivial workaround, but I thought I'd mention it.

**Comment by oblitum** [comment]
That's simply Fedora to blame.
