### ISSUE TITLE
Combine documents of same completion item

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#4702]
**Describe the solution you'd like**

For `cl`, it complete two class, one is provided by a language server, another is provided by another language server:

![Screenshot from 2023-07-13 17-14-21](https://github.com/neoclide/coc.nvim/assets/32936898/3294d215-1a1e-4293-9817-7e41bd4cc96e)
![Screenshot from 2023-07-13 17-14-13](https://github.com/neoclide/coc.nvim/assets/32936898/8e765e39-0259-4280-984c-4d371726823d)

Can we combine documents of same completion item? That is there is only one `class` and it have both documents of two language servers.

**Comment by fannheyward** [comment]
Enable `suggest.removeDuplicateItems` and try again.

**Comment by Freed-Wu** [comment]
After removeDuplicateItems, the document of completion only display the document provided by one language server. Can it provide a combination of all documents provided by all language servers?

**Comment by fannheyward** [comment]
No such feature yet.

**Comment by Freed-Wu** [comment]
So can we reopen the issue as a feature request? Thanks!

**Comment by fannheyward** [comment]
This will add some complex work. The steps:

1. coc fires all sources to `doComplete`
2. sources, LS/buffer/dict/tags etc, return completion items
3. with `removeDuplicateItems`, coc combines all items by `item.word`
4. when do completing, coc will get document from `item`, to show with floating window 

We can only merge documents in step3, but: large number of items to do merging may be slow, and which document is preferred? we can only first-come-first-served.

**Comment by Freed-Wu** [comment]
> which document is preferred

Can it be decided by coc sources' priority?

**Comment by fannheyward** [comment]
LS sources with same priority.
