### ISSUE TITLE
Should not add completion that is identical to the word before the cursor

### ISSUE THREAD

**Issue by jonashaag** [neoclide/coc.nvim#4704]
### versions

vim version: NVIM v0.10.0-dev-497+g4229bbe51
node version: v20.4.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /Users/j/.local/share/nvim/lazy/coc.nvim
term: iTerm.app
platform: darwin

## Describe the bug

In the screenshot I'm looking to get md5_flag so I start typing m, d, which suggests md5 as first entry which is fine, then I continue and have m, d, 5 typed, now IMO there is no point of suggesting md5 anymore because I have typed it completely by hand already
If I wanted md5 I'd have stopped after m, d, and accepted the suggestion. If I'm continuing to type I probably don't want that suggestion, and in any case there is no point to suggest it because it's already 100% typed

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

I can reproduce with the `mini.vim` config.

## Screenshots (optional)

<img width="199" alt="Screenshot 2023-07-13 at 12 30 16" src="https://github.com/neoclide/coc.nvim/assets/175722/ce8539b7-014a-42c6-9d95-ab8821975e17">

**Comment by jonashaag** [comment]
@fannheyward did you have time to look into this by any chance?

**Comment by jonashaag** [comment]
Thanks for working on this! It doesn't seem to work though (sorry for the colors, I need to fix dark mode colors)

<img width="289" alt="Screenshot 2023-09-15 at 23 14 10" src="https://github.com/neoclide/coc.nvim/assets/175722/f42231fe-53f7-48d0-bbfc-3e5951ad44d5">

I have

```
  "suggest.removeCurrentWord": true
```

in my settings and latest coc.nvim.

**Comment by chemzqm** [comment]
Only complete items from around and buffer source are removed.

**Comment by jonashaag** [comment]
But why?

**Comment by chemzqm** [comment]
Complete items from language server could be snippet or contains documentation that could be useful.

**Comment by jonashaag** [comment]
Ok, I’ll maintain my own fork of coc.nvim then, because this is really bad UX for me personally
