### ISSUE TITLE
An option to only lint/run diagnostics when the file is saved

### ISSUE THREAD

**Issue by Emigre** [neoclide/coc.nvim#471]
**Is your feature request related to a problem? Please describe.**
When editing the code the constant update of the diagnostics can be annoying. Some times the errors shown at that point appear only because you have just not finished typing the code.

**Describe the solution you'd like**
With ALE you can run only on save (`let g:ale_lint_on_save = 1`) which avoids that issue. Having that option in coc would be great.

**Comment by chemzqm** [comment]
It doesn't refresh on insert mode by default.

**Comment by chemzqm** [comment]
Added `refreshAfterSave`, but I have to say it doesn't works well with lanuage server, because language server need time to generate diagnostics and client don't know how long it takes, so the disagnostics could be wrong.

**Comment by chemzqm** [comment]
There's no way to make language server run diagnostics after save, most language servers doesn't have that support.

**Comment by Emigre** [comment]
Ah, I see, I had no idea. Thanks in any case.

To be honest, as you say, diagnostics don't run until insert mode ends, and at that point most of the times the file won't have diagnostic errors. What it could have is linting errors: many times these are auto-corrected via the formatter before saving the file, so for ALE it makes sense to delay linting until after the file is saved.

Your plugin integrates very well with ALE, which is something that I think is great, so one could, for example, run code diagnostics continuosly and the handle linting with ALE on file save so it creates less noise during edit.

Thanks a lot for your hard work, the plugin is really complete and a pleasure to use.

**Comment by chemzqm** [comment]
> diagnostics don't run until insert mode ends

It's not doesn't run, it just's not shown on insert mode by default.

If you don't want the noise before save the buffer, I think the best thing you can do is turn off linting feature of the language server you're using.

**Comment by Emigre** [comment]
You are right. Thanks again.
