### ISSUE TITLE
`coc#pum#confirm` inserts extra characters on C language case statements

### ISSUE THREAD

**Issue by shyun3** [neoclide/coc.nvim#4713]
## Result from CocInfo

```
## versions

vim version: NVIM v0.8.0-1210-gd367ed9b2
node version: v16.13.0
coc.nvim version: 0.0.82-3dc6153a 2023-07-21 00:22:17 -0500
coc.nvim directory: /home/shyun3/.config/nvim/bundle/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2023-07-25T10:37:59.567 INFO (pid:8928) [plugin] - coc.nvim initialized with node: v16.13.0 after 162
2023-07-25T10:37:59.577 INFO (pid:8928) [services] - LanguageClient clangd state change: stopped => starting
2023-07-25T10:37:59.581 INFO (pid:8928) [language-client-index] - Language server "clangd" started with 8946
2023-07-25T10:37:59.594 INFO (pid:8928) [services] - LanguageClient clangd state change: starting => running
2023-07-25T10:37:59.599 INFO (pid:8928) [services] - service clangd started
2023-07-25T10:39:51.712 INFO (pid:8928) [attach] - receive notification: showInfo []
```

## Describe the bug

When using a mapping for `<CR>` which enters `coc#pum#confirm` (like in the [README](https://github.com/neoclide/coc.nvim/blob/edcc37677fedf5aea3a5d108ba407a65b52dca78/README.md?plain=1#L123-L126)), some extra characters get inserted when entering certain C language case statements.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  
  inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                                \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
  ```

- Create file `test.c` with:
  ```c
  typedef enum
  {
      Test_Example,
      Test_AnotherExample,
  } Test;
  
  int main(int argc, char* argv[])
  {
      Test t = argc;
      switch (t)
      {
          case Test_Example:
              break;
      };
  }
  ```

- Start (neo)vim with command: `vim -u mini.vim test.c`

- Optionally, disable all language servers and extensions. These are not required to reproduce the issue.

- Type `13G` to go to the line containing `break;`
- Type `o` to insert a new line below and enter Insert mode
- Type `case t` to begin a case statement and open the pop-up menu for autocompletion
- Press `Ctrl-N` until `Test_AnotherExample` is highlighted
- Type `:` and note how the pop-up menu is still open:
![image](https://github.com/neoclide/coc.nvim/assets/37260523/13b1159e-7daa-4b01-b24c-75254120a9e1)

- Press `Enter` and note how the auto-completed word was changed to `TestTest_AnotherExample`:
![image](https://github.com/neoclide/coc.nvim/assets/37260523/803d5885-15a8-4067-a4d4-c2df8a496bc6)

**Comment by zxinlog** [comment]
This also happens when I #include header files, and then I can't use the auto-complete.

**Comment by fannheyward** [comment]
> Type : and note how the pop-up menu is still open:

Instead typing `:`, use `<CR>` to confirm the selected suggestion, will close the pop-up, and no extra characters.

Still debugging on this.

**Comment by UncleBill** [comment]
Sometime also happens in JSX auto-complete.

**Comment by shyun3** [comment]
> > Type : and note how the pop-up menu is still open:
> 
> @shyun3 Instead typing `:`, use `<CR>` to confirm the selected suggestion, will close the pop-up, and no extra characters.
> 
> Still debugging on this.

Thanks for looking into this. I was aware of the workaround but muscle memory oftentimes gets the better of me ☹

**Comment by fannheyward** [comment]
The cause of this issue:

1. vim/nvim will `setlocal cindent` in `runtime/indent/c.vim`
2. after typing `:`, vim will indent the `case Test_AnotherExample` line, this happens with or without coc.nvim, you can test with `nvim --clean test.c`
3. coc.nvim will retrigger after indent change https://github.com/neoclide/coc.nvim/blob/c7e92a70738e17d819eb8fcbe5176e1fd89bb0a8/src/completion/index.ts#L266-L270
4. the floating pum window didn't close, the completion list refreshed
5. `coc#pum#confirm` will replace and insert selected word from the `start_col`.

The fixes:

1.  change the `start_col`, but this will bring other issues: the `start_col` is used to specify the column from which the pum should be displayed, change this will break the position.
2. `setlocal nocin` to disable indenting, maybe break user's except
3. add `suggest.reTriggerAfterIndent` configuration to disable the coc.nvim's re-trigger behavior
