### ISSUE TITLE
Word wrapping for inlay hints

### ISSUE THREAD

**Issue by riojosdev** [neoclide/coc.nvim#4715]
**Is your feature request related to a problem? Please describe.**
So, word wrapping works for the text inside a file. But it doesn't work for the inlay hints provided. And to see them you have to adjust the window size, or add random characters to get to that view point for longer inlay hints.

**Describe the solution you'd like**
Word-wrapping for inlay hints, is a valid solution.

**Describe alternatives you've considered**
* Add random characters (have to delete them afterwards)
* Increase window size (have to resize window size afterwards)

**Additional context**
Inlay hints partially hidden
![image](https://github.com/neoclide/coc.nvim/assets/62337699/1e51d75d-8632-412c-86c3-3d17eb85fb99)
Inlay hints fully visible, but second window sacrifices it's size.
![image](https://github.com/neoclide/coc.nvim/assets/62337699/6a39147e-339e-4dba-b860-4482b5c303dc)

**Comment by riojosdev** [comment]
I added each type defined variables/structures onto a new line. It makes the inlay-hints to hint their type definitions separately. The code now seems easier to understand. And the inlay hints are shortened.

![image](https://github.com/neoclide/coc.nvim/assets/62337699/b0407832-9709-4430-8192-331fed2ebfee)

This word wrapping inability for inlay hints causes to rewrite **readable code**, but still **consuming too much display area** 🖥️.

**Comment by fannheyward** [comment]
> Word-wrapping for inlay hints

Needs vim/nvim to support this.

>  consuming too much display area

language server returns hints, coc displayed them, I don't think plugins can do anything to improve this.

**Comment by chemzqm** [comment]
```
		   text_wrap	when "text" is present and {col} is zero,
				specifies what happens if the text doesn't
				fit:
				   wrap      wrap the text to the next line
				   truncate  truncate the text to make it fit
		   		When omitted "truncate" is used.
				Note that this applies to the individual text
				property, the 'wrap' option sets the overall
				behavior
```
It's possible to wrap on vim.
