### ISSUE TITLE
adjust the keymap

### ISSUE THREAD

**Issue by HandsomeShaodi** [neoclide/coc.nvim#4720]
## versions
vim version: NVIM v0.9.1
node version: v18.0.0
coc.nvim version: 0.0.82-3dc6153a 2023-07-21 00:22:17 -0500
coc.nvim directory: /data/shaodi/.local/share/nvim/lazy/coc.nvim
term: xterm-256color
platform: linux
2023-08-05T12:02:42.187 INFO (pid:2911778) [plugin] - coc.nvim initialized with node: v18.0.0 after 130

## keymap files
How to adjust the keymap, I can't find the file to adjust the keymap

Thank you!

**Comment by fannheyward** [comment]
coc.nvim didn't set keymaps, you need to set in your vimrc/init.vim/init.lua by yourself.

**Comment by HandsomeShaodi** [comment]
How to close the prompted window during code prompting. I press <ESC> or <C-c> and it takes me right out of edit mode.

**Comment by HandsomeShaodi** [comment]
> coc.nvim didn't set keymaps, you need to set in your vimrc/init.vim/init.lua by yourself.

How to close the prompted window during code prompting. I press or and it takes me right out of edit mode.

**Comment by chemzqm** [comment]
> > coc.nvim didn't set keymaps, you need to set in your vimrc/init.vim/init.lua by yourself.
> 
> Thank you! How to close the prompted window during code prompting. I press or and it takes me right out of edit mode.

Checkout `:h coc-completion-default`
