### ISSUE TITLE
Is it possible to disable exact match

### ISSUE THREAD

**Issue by hanspinckaers** [neoclide/coc.nvim#4724]
Often coc.nvim autocomplete the exact text I typed.
<img width="376" alt="Screenshot 2023-08-11 at 13 12 10" src="https://github.com/neoclide/coc.nvim/assets/70747/93b5850f-8bcd-478e-9321-498ff47718e0">

**Describe the solution you'd like**
I want to hide this. Because i can just type <Space>

**Describe alternatives you've considered**
Changing source priorities doesn't seem to work.

**Comment by fannheyward** [comment]
Same issue https://github.com/neoclide/coc.nvim/issues/4704, no such configuration yet, will work on this next week.
