### ISSUE TITLE
better local coc.setting override

### ISSUE THREAD

**Issue by laoshaw** [neoclide/coc.nvim#4725]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to create .vim/coc-settings.json for many sub-dir

**Describe the solution you'd like**

just like .clangd, .clang-format etc, that I can find .coc-settings.json(or just coc-settings.json) all the way back to root directory(/), so I do not need lots of .vim/coc-settings to override global settings

**Describe alternatives you've considered**

coc.nvim can search reversibly for coc-settings.json to override global coc-settings, instead of local .vim/coc-settings.json

**Additional context**

**Comment by fannheyward** [comment]
> can all of them share the project file: .vim/coc-settings.json under dir1/

Of cause you can. If `dir1` is your project root, `:CocLocalConfig` will open `.vim/coc-settings.json` in this path.

How do you open your cpp file in vim? Run `vim` in dir1 or `cd` to every sub-directory then `vim`?

**Comment by fannheyward** [comment]
> under dir1/dir12/dir121 then vi dir12.cpp

After you launch vim, check `:CocCommand workspace.workspaceFolders`, if project root detection correctly, this should be `dir1`.
