### ISSUE TITLE
question: how to use coc.nvim to fix a warning ?

### ISSUE THREAD

**Issue by ssh352** [neoclide/coc.nvim#4727]
Hello:  Is it possible to  have coc fix this clangd warning with certain hotkey, just like the IDE, instead of me manually inserting the int? Thanks!

<img width="636" alt="Screenshot 2023-08-17 at 16 30 24" src="https://github.com/neoclide/coc.nvim/assets/41779116/e0f764f6-b381-4a84-bf0e-748a1513af64">

**Comment by fannheyward** [comment]
Try `:h coc-code-actions`, for example , some language server provides code actions to do fixes.

**Comment by chemzqm** [comment]
Create key-mapping like:
```
  nmap <silent> <leader>qf <Plug>(coc-fix-current)
```
is recommended for quick fix action at cursor position.
