### ISSUE TITLE
Can not install with nvim

### ISSUE THREAD

**Issue by kaldown** [neoclide/coc.nvim#473]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.3.4
node version: v11.10.0
coc.nvim version: 0.0.57
term: screen-256color
platform: linux

## Error messages

```

**Describe the bug**
1. > echo exists('##PumRender') should echo 1.
echo exists('*nvim_open_win') should echo 1.

but returns 0

2. nothing changed when I trying to write go code, like:
`log.Printf(`

no floating window appears

**To Reproduce**
[FAQ](https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-make-preview-window-shown-aside-with-pum)
try to follow stepps, stuck at the start 

**Additional:**
1. 
```
health#coc#check
========================================================================
  - OK: Environment check passed
  - OK: Build javascript found
  - OK: Service started
```

2. Use vim-go also: https://github.com/neoclide/coc.nvim/issues/53

**Comment by chemzqm** [comment]
In your CocInfo I can't see any go language server started, if you're using vim-go for completion, that's not related to coc.nvim, it won't show documentation of complete items that not triggered by coc itself.

**Comment by kaldown** [comment]
Sorry, it's really hard to guess what to do next.

I pasted the following into `:CocConfig`
```
  "languageserver": {
    "golang": {
      "command": "bingo",
      "args": ["--diagnostics-style=instant"],
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
  }
```
and no I got `[coc.nvim] The "path" argument must be of type string. Received type undefined`

**Comment by chemzqm** [comment]
Seems bingo needs `go.mod` to work.

**Comment by kaldown** [comment]
how can I test it on something?
I just don't understand how to start "server", and when CoC will send request into.
In addition:
>echo exists('##PumRender') should echo 1.
echo exists('*nvim_open_win') should echo 1.

what about this?

**Comment by chemzqm** [comment]
You can test floating window with coc extension, like coc-tsserver.
I can't understand what your problem is.

**Comment by kaldown** [comment]
No problem anymore
Thanks
