### ISSUE TITLE
after install ,vim .vimrc occurs errors

### ISSUE THREAD

**Issue by jeffreycsj** [neoclide/coc.nvim#4731]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 22 2021 11:10:49)
coc.nvim:0.0.82
errors:
  Error detected while processing function coc#rpc#start_server[57]..coc#util#get_data_home[18]..coc#notify#create[87]..coc#float#create_float_win[4]..coc#float#create_buf:
  line    5:
  E117: Unknown function: bufadd
  E15: Invalid expression: bufadd('')
  Error detected while processing function coc#rpc#start_server[57]..coc#util#get_data_home:
  line   18:
  E171: Missing :endif
  Error detected while processing function coc#rpc#start_server:
  line   57:
  E171: Missing :endif
  Error detected while processing /home/jeffreychen/.vim/plugged/coc.nvim/plugin/coc.vim:
  line   56:
  E171: Missing :endif
  Press ENTER or type command to continue
.vimrc:（too long, so I just print the top of them）
  "plug begin
    call plug#begin('~/.vim/plugged/')
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    Plug 'preservim/nerdtree'
    Plug 'majutsushi/tagbar'
    Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
    Plug 'Yggdroot/LeaderF'
    Plug 'vim-scripts/a.vim'
    Plug 'vim-scripts/DoxygenToolkit.vim'
    Plug 'honza/vim-snippets'
    "Plug 'luchermitte/lh-cpp'
    let g:coc_global_extensions = ['coc-json', 'coc-pairs', 'coc-clangd','coc-python', 'coc-go']
    autocmd FileType cpp let b:coc_pairs_disabled = ['<']
    call plug#end()
    "plug end

**Comment by fannheyward** [comment]
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 22 2021 11:10:49)

You're using vim 8.0, an outdated release, upgrade your vim to latest version. https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#requirements

**Comment by jeffreycsj** [comment]
ok，thx a lot

**Comment by jeffreycsj** [comment]
that works,thx a lot
