### ISSUE TITLE
How do I modify the npm source

### ISSUE THREAD

**Issue by dingjingmaster** [neoclide/coc.nvim#4736]
I hope that the npm source is available when the coc is downloaded, so that some areas can use the mirror source and update the plugin faster.

**Comment by fannheyward** [comment]
You can use the `master` branch, modify the source, build with `yarn build` to use locally.

**Comment by chemzqm** [comment]
Source code of coc.nvim is not available on npm, which provide type only.
It's recommended to use release branch on github.

**Comment by gresces** [comment]
[using-custom-registry](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#using-custom-registry)
In this page, you may find the answer.
Just add `coc.nvim:registry=registry-address` in `~/.npmrc` file.
