### ISSUE TITLE
Autocomplete of parameters

### ISSUE THREAD

**Issue by vkatasonov** [neoclide/coc.nvim#4737]
**Is your feature request related to a problem? Please describe.**
Hey guys, I need to switch off that stuff, but i don't know how. Everytime I open a recently created file COC changes it inserting variables values
for example, instead of standard 
`write (1, &c, 1)` function with usual params you can see this 🤦‍♂️ --> `write(fd: 1, buf: "\n", nbyte: 1)`. 

**Describe the solution you'd like**
It would be nice to be able to swith it off. Because as soon as you start changing values, those "tips" don't desappear. 

**Additional info**

Here is my config of vimrc. 

```
" COC stuff
" Use the clangd language server for C and C++
let g:coc_global_extensions = ['coc-clangd']

" Enable diagnostics (errors and warnings)
let g:coc_global_extensions = ['coc-clangd', 'coc-diagnostic']

" Show diagnostics in the sign column
autocmd CursorHold * silent call CocActionAsync('diagnosticRefresh')
autocmd CursorHoldI * silent call CocActionAsync('diagnosticRefresh')

" Enter to select suggestion
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<CR>"

" Use a lighter sign column
highlight SignColumn ctermbg=NONE
highlight SignColumn guibg=NONE

" Configure coc-clangd
let g:coc_clangd_binary = 'clangd' " Path to clangd binary
let g:coc_clangd_args = ['-header-insertion=never'] " Arguments for clangd

" Set the syntax highlighting for C warnings
autocmd Syntax c syn keyword cWarn contained warning

" Set error color and sign
let g:coc_error_sign = '>>'
highlight CocErrorSign guifg=red ctermfg=red

"Set warning color and sign
highlight CocWarningSign guifg=red ctermfg=red
let g:coc_user_config = {
\ 'diagnostic': {
\   'warningSign': '!!'
\   }
\}

" For NERDtree
inoremap <c-_> <Esc> :NERDTreeToggle<CR>
nnoremap <c-_> <Esc> :NERDTreeToggle<CR>
```

It suppose that this string should switch off this "autocomplete", but it's not 

`let g:coc_clangd_args = ['-header-insertion=never'] " Arguments for clangd`

**Comment by fannheyward** [comment]
Check `:h coc-inlayHint`.

**Comment by chemzqm** [comment]
`:h coc-config-inlayHint`
