### ISSUE TITLE
Is it possible to open coc refactor buffer readonly?

### ISSUE THREAD

**Issue by your-diary** [neoclide/coc.nvim#4738]
I always use `:CocSearch` command to recursively search for string in a whole project directory.

In the current implementation, the result is opened in a coc refactor buffer. As my purpose is only to *read* the result, I want to always set `readonly` and `nomodifiable` for the buffer to avoid unconscious edits.

I tried to use `au FileType` command, but it seems `filetype` is empty in the coc refactor buffer.

ChatGPT suggests to use `au BufNewFile * if (match(expand('%'), '__coc_refactor__') != -1) | setlocal readonly nomodifiable | endif` but I don't like it as this `au` is evaluated for all buffers of any type.

**Comment by fannheyward** [comment]
No such feature yet, maybe we can add something like `CocSearch --read-only`.

**Comment by your-diary** [comment]
Thank you.

`CocSearch --read-only` would be extremely helpful because

- `CocSearch` is very handy and powerful (at least smoother than creating a new terminal window and executing `rg` command)

- The name Coc*Search* intuitively feels like a readonly operation (Thus I even think `CocSearch --read-only` should be default if I can ignore backward compatibility.)

By the way, the suggested workaround in the OP didn't work with the error message

> *[coc.nvim]: Error on notification "search": call_atomic request error on "nvim_call_function": Vim(return):E21: Cannot make changes, 'modifiable' is off on function "call_function"*

, meaning it seems `coc.nvim` first opens a blank buffer and programmatically fills its contents.

For the time being (or perhaps forever), I'll manually set `readonly` and `nomodifiable`.

**Comment by chemzqm** [comment]
The buffer changed with results from rg from time to time.
It's designed to change multiple buffers and files at once.
