### ISSUE TITLE
How To Integrate it with ternjs

### ISSUE THREAD

**Issue by stkevintan** [neoclide/coc.nvim#474]
Sorry for the fool question, I'm a new vimer and have tried to google it but get nothing helpful.
After install tern-for-vim, should I install coc.omni plugin?

**Comment by iamcco** [comment]
Why not use coc-tsserver and it's more powerful than ternjs. Also you should install coc.omni because tern_for_vim use omni for js.

**Comment by chemzqm** [comment]
You can use coc-omni extension and enable it for javascript.
However, coc-tsserver should be better, it provide same features as VSCode, you need to configure for javascript https://code.visualstudio.com/docs/languages/jsconfig sometimes.

**Comment by stkevintan** [comment]
@chemzqm It's GREAT! thanks for your work. but I am still confuse. as the doc says, it supports `go to defines` `find references` `rename`, but how can I do this in vim?  Its there some docs ?

**Comment by chemzqm** [comment]
>  it supports go to defines find references rename

Sure, key-mappings and functions are provided for those feature: https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L157
