### ISSUE TITLE
Inlay hint configurable option

### ISSUE THREAD

**Issue by lmburns** [neoclide/coc.nvim#4740]
**Is your feature request related to a problem? Please describe.**
I do not like the inline inlay hints.

**Describe the solution you'd like**
Make it a configuration option on whether or not separators are used, or where the inlay hint is located. Similar to how the code-lens option is given to choose.

**Describe alternatives you've considered**
Disabling them, but I'd prefer not to.

**Additional context**

**Comment by chemzqm** [comment]
Separator of inlay hint have removed, not needed any more, see https://github.com/neoclide/coc.nvim/blob/master/history.md#2023-08-31

**Comment by lmburns** [comment]
Yeah I saw that it was removed. That's why I created this feature request. But I couldn't find out how to place the inlay-hints at the end of the line like they were before, instead of them mandatorily being inline. Is there a way to do this? I searched through the documentation

**Comment by chemzqm** [comment]
> But I couldn't find out how to place the inlay-hints at the end of the line like they were before.

No such support as we don't think it's a good idea compare to inline ext markers.

**Comment by SeniorMars** [comment]
I'm sure you have your reasons, but I would still like to request this feature. I'm not used to inline markers at all, and would prefer the old style.

**Comment by Awpteamoose** [comment]
It's an opensource project and as authors you can do whatever you want, but I don't understand why are you so eager to break established habits of your users. It was the same with the floating status notifications around a year ago.

**Comment by SeniorMars** [comment]
No, thank you for your work on this awesome project!

**Comment by aemonge** [comment]
Just for keeping track on the other issue:

> Can we put the inline hints only visible for current line?

Ref. https://github.com/neoclide/coc.nvim/issues/4074?notification_referrer_id=NT_kwDOABQtbLI0MjI4NTE2NTU5OjEzMjIzNDg#issuecomment-2150493218

**Comment by awused** [comment]
You can get the old hints by pinning 3dc6153.

Neovim 0.10.0 was only released a month ago, so I only just updated coc, but after seeing these new inlay hints I had to roll it back to 3dc6153 immediately.

**Comment by fannheyward** [comment]
#5060 added `inlayHint.position` configuration, supports `inline` and `eol`.

**Comment by fannheyward** [comment]
For the separator configuration, some language server returns with separator but some not, it's complex for the client to control separators, have no plan to add this.

Close as completed.
