### ISSUE TITLE
Change CursorHold to CursorMove for coc_current_function calculation

### ISSUE THREAD

**Issue by 3ximus** [neoclide/coc.nvim#4743]
**Is your feature request related to a problem? Please describe.**

I'm a bit frustrated when the current function displayed is not updated immediately. It has to wait for a CursorHold depending on my updatetime. I would rather have at least the option of not relying on updatetime for this.

**Describe the solution you'd like**

A solution would be to change the `CursorHold` autocmd to `CursorMoved`, however I wanted to know from you if this could cause a big performance impact. I've tested on a big project with tsserver and there doesn't seem to be any implications.

I can make a PR with the change if you think it's not a problem, or we could expose a config option to set the desired autocmd.

Cheers!

**Comment by chemzqm** [comment]
Use command like `set updatetime=300` in your vimrc should be good enough.

**Comment by chemzqm** [comment]
OK, changed to use CursorMoved event.

**Comment by 3ximus** [comment]
Perfect :+1:
Thank you!
