### ISSUE TITLE
i used coc-definiton jump to define, is not right result . 

### ISSUE THREAD

**Issue by xpbluesmile** [neoclide/coc.nvim#4746]
#define TxAEdidRam(port)       (User_GSV_Device_GSV2K8->InternalResource.TxAEdidRam)

When my cursor is at the end of the line tail "TxAEdidRam", I used coc-definition , could't go to the define of TxAEdidRam, but jump to TxAEdidRam(port) that was not right result fot me.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by fannheyward** [comment]
Language server'd issue.
