### ISSUE TITLE
Coc creates unexpected white spaces in the sign column/number lines when `set signcolumn=number` is enabled.

### ISSUE THREAD

**Issue by thunderbird-1990** [neoclide/coc.nvim#4747]
### versions

vim version: VIM - Vi IMproved 9.0 9001848
node version: v20.6.0
coc.nvim version: 0.0.82-bf42a827 2023-09-06 11:47:03 +0800
coc.nvim directory: /home/user/.vim/plugged/coc.nvim
term: dumb
platform: linux

### Log of coc.nvim

2023-09-06T11:38:54.597 INFO (pid:21453) [plugin] - coc.nvim initialized with node: v20.6.0 after 612
2023-09-06T11:38:54.599 INFO (pid:21453) [services] - LanguageClient ESLint state change: stopped => starting
2023-09-06T11:38:54.610 INFO (pid:21453) [language-client-index] - Language server "eslint" started with 21494
2023-09-06T11:38:54.619 INFO (pid:21453) [language-client-index] - Language server "ltex" started with 21495
2023-09-06T11:38:54.753 INFO (pid:21453) [services] - LanguageClient ESLint state change: starting => running
2023-09-06T11:38:54.758 INFO (pid:21453) [services] - service eslint started

## Describe the bug

My colour scheme is [PaperColor](https://github.com/NLKNguyen/papercolor-theme).

Coc creates unexpected white spaces in the sign column/number lines when `set signcolumn=number` is enabled.

![01](https://github.com/neoclide/coc.nvim/assets/88970199/2c85de87-54d6-448d-aca1-8acb4a1f3693)

This seems to be caused by the highlight groups `Coc[x]Line`. For instance, with:

```
highlight CocErrorLine guibg=red
highlight CocWarningLine guibg=red
highlight CocInfoLine guibg=red
highlight CocHintLine guibg=red
```
![02](https://github.com/neoclide/coc.nvim/assets/88970199/ababaf2d-2f03-4b70-86d6-3253e4b3bb5b)

The red background colour clearly goes into the sign column/number lines.

This is not an issue when using `set signcolumn=auto`:

![03](https://github.com/neoclide/coc.nvim/assets/88970199/3f9dfba4-0d32-4ee6-b6b9-91e8f9bbff51)

I mostly use gVim, but this also affects terminal Vim:

```
highlight CocErrorLine ctermbg=160
highlight CocWarningLine ctermbg=160
highlight CocInfoLine ctermbg=160
highlight CocHintLine ctermbg=160
```

![04](https://github.com/neoclide/coc.nvim/assets/88970199/1148aca3-c192-4a83-b36f-4f0939183663)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- The minimal vimrc should be：

 ```vim
set nocompatible
syntax enable
set signcolumn=number
" Terminal
highlight CocErrorLine ctermbg=160
highlight CocWarningLine ctermbg=160
highlight CocInfoLine ctermbg=160
highlight CocHintLine ctermbg=160
" gVim
highlight CocErrorLine guibg=red
highlight CocWarningLine guibg=red
highlight CocInfoLine guibg=red
highlight CocHintLine guibg=red
 ```

**Comment by chemzqm** [comment]
Should be bug of vim.
