### ISSUE TITLE
ERROR (pid:6608) [events] - Error on event: Enter TypeError: Cannot read properties of      at .config/plugged/coc.nvim/build/index.js:261:26091        

### ISSUE THREAD

**Issue by jicvi** [neoclide/coc.nvim#4748]
## Describe the bug
![2023-09-06_22-27](https://github.com/neoclide/coc.nvim/assets/14210650/5cecb52d-b7bc-4845-8360-e133dcb5bbe3)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
`CocInfo` and `CocOpenLog` please.

**Comment by fannheyward** [comment]
Close for now.
