### ISSUE TITLE
uncaughtException Error: write EPIPE

### ISSUE THREAD

**Issue by YuanBLQ** [neoclide/coc.nvim#4750]
## versions

vim version: NVIM v0.9.2
node version: v20.6.0
coc.nvim version: 0.0.82-6e4e6eaf 2023-09-08 01:05:35 +0800
coc.nvim directory: /Users/xxx/.config/nvim/plugs/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2023-09-08T13:00:35.838 INFO (pid:31174) [configurations] - Add folder configuration from cwd: /Users/xxx/code/abc/.vim/coc-settings.json
2023-09-08T13:00:36.028 INFO (pid:31174) [plugin] - coc.nvim initialized with node: v20.6.0 after 258
2023-09-08T13:00:38.882 INFO (pid:31174) [services] - LanguageClient Pyright Server state change: stopped => starting
2023-09-08T13:00:38.891 INFO (pid:31174) [language-client-index] - Language server "pyright" started with 31466
2023-09-08T13:00:39.131 INFO (pid:31174) [services] - LanguageClient Pyright Server state change: starting => running
2023-09-08T13:00:39.136 INFO (pid:31174) [services] - service pyright started
2023-09-08T13:00:41.529 ERROR (pid:31174) [server] - uncaughtException Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)

## Describe the bug

Installed with coc.nvim & coc-pyright, when i open a `.py` file or enter `:w` to save the `.py` file, error message turns up.

<img width="349" alt="image" src="https://github.com/neoclide/coc.nvim/assets/18660424/46202486-446f-4f16-9cae-6ce0be9f51ac">

extra packages installed:
```
pyright==1.1.326
jedi==0.19.0
```

## Reproduce the bug

related config in my `init.vim`:
```
" Ref: https://github.com/neovim/neovim/issues/2437
let g:python_host_prog  = '~/.pyenv/shims/python'
let g:python3_host_prog = '~/.pyenv/shims/python'

call plug#begin('~/.config/nvim/plugs')
Plug 'lukas-reineke/indent-blankline.nvim'

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'dense-analysis/ale'
Plug 'ranelpadon/python-copy-reference.vim'
call plug#end()


inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

inoremap <silent><expr> <a-cr> coc#refresh()
nnoremap <silent><nowait> <space>a :CocDiagnostics<cr>
nnoremap <silent><nowait> <space>k <Plug>(coc-diagnostic-prev)
nnoremap <silent><nowait> <space>j <Plug>(coc-diagnostic-next)

au FileType go,python,c,javascript nmap <silent> gd :call CocAction('jumpDefinition', 'split')<CR>
au FileType go,python,c,javascript nmap <silent> gv :call CocAction('jumpDefinition', 'vsplit')<CR>
au FileType go,python,c,javascript nmap <silent> gl :call CocAction('jumpDefinition')<CR>
au FileType go,python,c,javascript nmap <silent> rf <Plug>(coc-refactor)
au FileType go,python,c,javascript nmap <silent> gr <Plug>(coc-references)
au FileType go,python,c,javascript nmap <silent> gi <Plug>(coc-implementation)
au FileType go,python,c,javascript nmap <silent> gt <Plug>(coc-type-definition)
au FileType go,python,c,javascript inoremap <silent> <A-k> <C-r>=CocActionAsync('showSignatureHelp')<CR>
au FileType go,python,c,javascript nmap <silent>  K :call ShowDocumentation()<CR>
function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction
```

I find the similar issue [here](https://github.com/neoclide/coc.nvim/issues/1833), but it seems not work for me.

**Comment by fannheyward** [comment]
You don't need to install pyright and jedi with coc-pyright. 

Have you enabled formatOnSave?

**Comment by YuanBLQ** [comment]
> You don't need to install pyright and jedi with coc-pyright.
> 
> Have you enabled formatOnSave?

coc only format `json` file, `ale` will handle `.py` files
`coc-settings.json`
```json
{
    "diagnostic.displayByAle": false,
    "coc.preferences.formatOnSave": false,
    "json.format.enable": true,
    "[json]": {
        "coc.preferences.formatOnSave": true
    },
    "coc.preferences.useQuickfixForLocations": true,
    "coc.preferences.jumpCommand": "edit",
    "pyright.disableDiagnostics": false,
    "pyright.enable": true,
    "python.formatting.provider": "none",
}
```

**Comment by YuanBLQ** [comment]
full configure:
- init.vim: https://github.com/YuanBLQ/dotfiles/blob/master/nvim/vimscript/init.vim
- coc-settings.json: https://github.com/YuanBLQ/dotfiles/blob/master/nvim/coc-settings.json

**Comment by YuanBLQ** [comment]
It has been solved!  My fault :(

I have configed `ruff` in `coc-settings.json`, but I forgot to install `ruff` in my python env.
