### ISSUE TITLE
Placement of floats

### ISSUE THREAD

**Issue by coot** [neoclide/coc.nvim#4759]
**Is your feature request related to a problem? Please describe.**
Some floating messages are large and when they are attached to a range of lines, the float window will not allow one to see the code behind the floating window.

**Describe the solution you'd like**
I would like to configure `coc.nvim` to place floats below the last line range rather than bellow the cursor position.

**Describe alternatives you've considered**
Closing floats is a workaround, but this is not ideal as this prevents one to see both: the code and the message.  This is especially useful when fixing a compiler error.

**Additional context**
![image](https://github.com/neoclide/coc.nvim/assets/698209/14eeecde-a09e-4925-a260-ac9b8e4ee1fe)

**Comment by Nefasque** [comment]
![Uploading shot-2023-08-14_04-13-57.jpg…]()
Hola soy nuevo usando coc. Y quisiera configurar un aspecto de la sugerencia pero no sé cómo lograrlo. Quisiera que el texto virtual me sugiriera la primera opción pero si la lista de sugerencia. Solamente el texto virtual. Y cuando pulse <control> <space> me muestre aparezca la lista sugerencia.  

Agradezco la ayuda

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/pull/5217
