### ISSUE TITLE
No colors in popup autocompletion window when auto-reloading .vimrc and color scheme

### ISSUE THREAD

**Issue by luizpara** [neoclide/coc.nvim#4762]
## versions

vim version: VIM - Vi IMproved 9.0 9000749
node version: v20.5.0
coc.nvim version: 0.0.82-0e6ec7dc 2022-08-23 17:47:29 +0800
coc.nvim directory: /users/luiz/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2023-09-19T23:45:46.449 INFO (pid:644143) [plugin] - coc.nvim initialized with node: v20.5.0 after 126ms
2023-09-20T00:24:58.229 INFO (pid:644143) [attach] - receive notification: showInfo []

## Describe the bug

I just installed COC to use for C++ auto-completion (with clangd). Everything worked fine, except that the pop-up window with auto-completion options had only two colors: the background and the text colors. No selection highlighting,  so I cannot see which auto-completion is currently selected. No different color for the first two letters of auto-completion items. No different colors for different types of auto-completion items.

After erasing my .vimrc line by line, I found that this is being caused the combination of two lines offending lines:
`colorscheme seoul256`
and
` autocmd VimEnter * :exec 'source $MYVIMRC'`

If either is deleted, the auto-completion pop-up menu works as intended, with the intended color differentiation. Of course, then I loose my color theme (which I downloaded from [here](https://github.com/junegunn/seoul256.vim)) or I need that other line - which I need due to some plugins and tweaks requiring this auto reload of .vimrc.

Note that although my color scheme is the one from that link, I tried a few others and the same problem arises.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  colorscheme seoul256
  autocmd VimEnter * :exec 'source /path/to/mini.vim'
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
> due to some plugins and tweaks requiring this auto reload of .vimrc.

What's plugin and tweaks needs this? Why these plugins couldn't be loaded by default?

**Comment by chemzqm** [comment]
Use 
```
autocmd VimEnter * ++nested :exec 'source /path/to/mini.vim'
```
instead, to trigger ColorScheme autocmd
