### ISSUE TITLE
C语言补全时，如何设置字符串内不补全

### ISSUE THREAD

**Issue by djfyz** [neoclide/coc.nvim#4763]
如何禁用字符串内不补全，遇到的问题：

使用coc.nvim补全时，如果c文件中定义了以n开头的变量，比如“new”， 字符串内在输入"\n"时就会弹出new的补全提示，很不方便~
![截图](https://github.com/neoclide/coc.nvim/assets/8026734/54f1e20b-70be-42f2-be39-24e4a242c39a)

**Comment by chemzqm** [comment]
Use
```
  "coc.source.around.disableSyntaxes": ["comment"],
```
in coc-settings.json
