### ISSUE TITLE
Weird behaviour with completions containing spaces

### ISSUE THREAD

**Issue by Xandaros** [neoclide/coc.nvim#4764]
## Result from CocInfo

```
## versions

vim version: NVIM v0.9.0-dev-1257+g4cba53e09e
node version: v20.4.0
coc.nvim version: 0.0.82-2a73b9dc 2023-09-21 23:24:13 +0800
coc.nvim directory: /home/xandaros/dotfiles/config/nvim/bundle/coc.nvim
term: alacritty
platform: linux

## Log of coc.nvim

2023-09-24T02:18:38.615 INFO (pid:292447) [plugin] - coc.nvim initialized with node: v20.4.0 after 314
2023-09-24T02:18:38.621 INFO (pid:292447) [services] - LanguageClient ic10 state change: stopped => starting
2023-09-24T02:18:38.621 INFO (pid:292447) [services] - languageserver "languageserver.ic10" connecting to 127.0.0.1:9257
2023-09-24T02:18:38.624 INFO (pid:292447) [attach] - receive notification: highlight []
2023-09-24T02:18:38.645 INFO (pid:292447) [services] - LanguageClient ic10 state change: starting => running
2023-09-24T02:18:38.653 INFO (pid:292447) [services] - service languageserver.ic10 started
2023-09-24T02:18:40.286 INFO (pid:292447) [attach] - receive notification: highlight []
```

## Describe the bug

Completions containing spaces behave very strangely. After the first word, it will sometimes highlight the wrong characters (the highlighting that shows the prefix in the completion list), the completions might just seemingly randomly (but consistently in the same places) disappear, only to reappear on the next word, etc.

You can see an example of this happening here:
https://asciinema.org/a/I5JKUDURMcIjs5sbHoWpmEJkw

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start neovim with command: `nvim -u mini.vim` (I didn't test with non-neo vim)

- Install [ic10lsp](https://github.com/Xandaros/ic10lsp)

- Use `:CocConfig` and set you config to:
```json
{
    "languageserver": {
        "ic10": {
            "command": "/path/to/ic10lsp",
            "filetypes": ["ic10"]
        }
    }
}
```

- Open a file and set the filetype to `ic10`

- Type in `move r3 HASH("Access Card ` and observe what happens. Typing in the last a will highlight the prefix incorrectly, and typing in the r will break completion entirely. Once you get to the space at the end, completion works again.

## Additional comment
I discovered this while developing my own language server. It is, of course, entirely possible that this is somehow the server's fault. However, both VSCode and the neovim built-in LSP seem to handle this just fine - it is only coc where I can observe this weird behaviour.

Unfortunately, I do not know of any other language server that offers completion items that contain a space, so I could not test this with other language servers.

## Screenshots

A screencast of this happening can be viewed here: https://asciinema.org/a/I5JKUDURMcIjs5sbHoWpmEJkw

**Comment by chemzqm** [comment]
Got error with the language server 
```
Connection to server ic10 is erroring, Header must provide content-length property.
```

**Comment by Xandaros** [comment]
Hmm... I don't know what to tell you. Were you using the Windows or the Linux build, or did you build it from source?

I just tried it again, renamed my `~/.config/nvim` folder, downloaded the ic10lsp build from GitHub, and cloned coc.nvim into a new place. Ran `npm ci` in the coc folder, and opened vim using the `mini.vim` file.

Actual `mini.vim` I used:
```vim
set nocompatible
set runtimepath^=/home/xandaros/workspace/ic10lsp/test/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

I then used `:CocConfig` to create a new coc config. Actual coc config I used:
```json
{
    "languageserver": {
        "ic10": {
            "command": "/tmp/ic10lsp",
            "filetypes": ["ic10"]
        }
    }
}
```

I then went back to a blank file, did `:set ft=ic10` and `:CocRestart` and I had a working language server.

I honestly don't know what else I could do to figure out what causes your issue.

**Comment by chemzqm** [comment]
I built the server from source code, seems the server has some output to stdio.

**Comment by Xandaros** [comment]
Indeed, looks like I left in a print. That's what I get for only testing over TCP...

Sorry for wasting your time, it's fixed now. (At least in the source)

**Comment by Xandaros** [comment]
I think there may have been a misunderstanding. I meant that the invalid output of ic10lsp is fixed - I can still observe the odd behaviour in coc.

**Comment by fannheyward** [comment]
> typing in the r will break completion entirely

Reproduced.
