### ISSUE TITLE
Pressing the enter key to go to the next line inserts extra characters

### ISSUE THREAD

**Issue by MahdiNazemi** [neoclide/coc.nvim#4766]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9001435
node version: v20.5.1
coc.nvim version: 0.0.82-d9dce16 2023-09-25 10:57:25 +0800
coc.nvim directory: /home/nazemi/.vim/plugged/coc.nvim
term: tmux
platform: linux
```

## Describe the bug

My CoC settings are set such that no item from the pop-up menu is selected by default and pressing the enter key takes the cursor to the next line unless a suggestion is selected. More formally, I have set `"suggest.noselect": true,` and have the following lines in my `~/.vimrc`:
```
inoremap <silent><expr> <CR> coc#pum#visible() && coc#pum#info()['index'] == -1
  \ ? "\<C-e>\<CR>"
  \ : coc#pum#visible()
    \ ? coc#_select_confirm()
    \ : "\<CR>"
```

When I see suggestions by CoC and do not select any of them, and press the enter key, CoC inserts a character at the end of the line before going to the next line.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  
  inoremap <silent><expr> <CR> coc#pum#visible() && coc#pum#info()['index'] == -1
    \ ? "\<C-e>\<CR>"
    \ : coc#pum#visible()
      \ ? coc#_select_confirm()
      \ : "\<CR>"
  ```

- Set `"suggest.noselect": true,`

- Start vim with command: `vim -u mini.vim`.

- Operate vim.

Please note that I encounter this behavior almost all the time, but there are exceptions. If you cannot reproduce the issue on your first try, please retry modifying files at different indentation levels, different files, etc.

**Comment by chemzqm** [comment]
`inoremap` with `<C-e>` won't hide the custom pum created by coc.nvim, you have to use something like:
```vim
inoremap <silent><expr> <CR> coc#pum#visible() && coc#pum#info()['index'] == -1
  \ ? "\<C-r>=coc#pum#cancel()\<CR>\<CR>"
  \ : coc#pum#visible()
    \ ? coc#_select_confirm()
    \ : "\<CR>"
```
