### ISSUE TITLE
openlinks cannot open file under cursor

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#4771]
## Describe the bug

In the doc it says openlinks should work for both files and links, but now it seems only works with links

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
The link(s) URL was came from language server, if LS didn't return URL for file, coc can't open it.

Which language server do you use?

**Comment by fannheyward** [comment]
Language server issue.

<img width="851" alt="image" src="https://github.com/neoclide/coc.nvim/assets/345274/e7e21c86-b7c2-46a2-ab6c-5d1c5b78342d">
