### ISSUE TITLE
[coc.nvim]: UnhandledRejection: Error: <semantic> TypeScript Server Error ([object Object])

### ISSUE THREAD

**Issue by houming818** [neoclide/coc.nvim#4773]
## Result from CocInfo

![image](https://github.com/neoclide/coc.nvim/assets/5498826/4ce8cc6e-8b4a-4ac7-ac43-d48db0136e7c)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.
don't show with min.vim

## Screenshots (optional)
![image](https://github.com/neoclide/coc.nvim/assets/5498826/011abf16-92e3-461d-a20f-cc3b3f4ed3c2)

**Comment by fannheyward** [comment]
The error message was came TypeScript tsserver, what's your TypeScript version?
