### ISSUE TITLE
Can I remove diagnostic info of coc#status() ?

### ISSUE THREAD

**Issue by shy-robin** [neoclide/coc.nvim#4775]
I use `coc#status()` to show lsp info in lualine. But it returns `b:coc_diagnostic_info` which I don't want to display. 

![image](https://github.com/neoclide/coc.nvim/assets/59857729/f6d406b4-682e-4a9e-85a6-0f68fde8d85d)

I have used `:h coc#status()` to get some help, and it says:
```
Return a status string that can be used in the status line, 
the status includes diagnostic information from |b:coc_diagnostic_info| and
extension contributed statuses from |g:coc_status|. 
```
And how to make it only return `g:coc_status`??

**Comment by fannheyward** [comment]
No such feature yet.

You can custom your own `coc#status()` like, check `:h coc-status-manual`.
