### ISSUE TITLE
hope to support format modifications

### ISSUE THREAD

**Issue by jh244212647** [neoclide/coc.nvim#4785]
when enable format-on-save, coc will auto format modifications ,not format file.
example lsp plug: [joechrisellis/lsp-format-modifications.nvim](https://github.com/joechrisellis/lsp-format-modifications.nvim)

**Comment by fannheyward** [comment]
It's range formatting, select the changed content and `<Plug>(coc-format-selected)`.

**Comment by fannheyward** [comment]
It's range formatting, select the changed content and `<Plug>(coc-format-selected)`.

**Comment by fannheyward** [comment]
It's range formatting, select the changed content and `<Plug>(coc-format-selected)`.

**Comment by fannheyward** [comment]
It's range formatting, select the changed content and `<Plug>(coc-format-selected)`.
