### ISSUE TITLE
Question: How to select method on code action menu?

### ISSUE THREAD

**Issue by rhaehfaos23** [neoclide/coc.nvim#4789]
I tried various things like pressing the space bar and the enter key, but none of them worked.

When I press the space bar, it just enters a blank space in the search bar.

I am currently using the example settings you provided as is, and I have changed the leader key from the backslash to the space bar.

![image](https://github.com/neoclide/coc.nvim/assets/18699655/af1ab027-5d92-45a5-a8b9-2e91641c92cd)

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/discussions/4788
