### ISSUE TITLE
Keep the cursor position when refactor

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#4790]
Currently, cursor is on `K`

![Screenshot from 2023-10-22 22-09-12](https://github.com/neoclide/coc.nvim/assets/32936898/56d82be2-24d9-44b9-a36a-941c735931cf)

When we press `<Plug>(coc-refactor)`, A new window is split, the cursor has gone to `U`, the first letter of current node.

![Screenshot from 2023-10-22 22-09-44](https://github.com/neoclide/coc.nvim/assets/32936898/be0fd8b1-b6f1-4523-89ac-8f5b2e767599)

Is it possible to keep cursor position?

**Comment by fannheyward** [comment]
You can't.

When you do `coc-refactor`, coc requests `textDocument/rename` from LS, LS returns textEdit that contains the range of text to be changed, coc uses this range to display the refactor buffer.

Why do you want to keep the cursor position in refactor? In my workflow, move the cursor to the beginning is _better_ cause I can directly run `cw` to do refactoring.

**Comment by Freed-Wu** [comment]
In my workflow, I press `gr` to refactor the function names, then press `r` or `R` to rename them. So moving the cursor to the beginning make me have to remove the cursor to the correct position.
