### ISSUE TITLE
path exclude for auto complete

### ISSUE THREAD

**Issue by onns** [neoclide/coc.nvim#4798]
I don't know if this feature should powered by plugin or neovim itself.

I have a large project just like golang/go(for example, just the file size), and if I load the project, the memory use of  gopls would be like 10GB more.

Is there any method I can use like goland to exclude dir so these files should not be index, and not be used by auto complete.

**Comment by fannheyward** [comment]
It's not coc.nvim or neovim's issue, but gopls, needs gopls to support exclude dirs to index.
