### ISSUE TITLE
Error when CocAction('diagnosticRefresh') triggers an invocation of CocAction('diagnosticList')

### ISSUE THREAD

**Issue by dstein64** [neoclide/coc.nvim#4806]
## Result from CocInfo

```text
## versions

vim version: NVIM v0.9.1
node version: v18.18.1
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /home/dstein64/.vim/pack/plugins/start/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2023-11-09T23:33:31.644 INFO (pid:11295) [plugin] - coc.nvim initialized with node: v18.18.1 after 116
```

## Describe the bug

An uncaught error results when `CocAction('diagnosticRefresh')` triggers an invocation of `CocAction('diagnosticList')`.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start Neovim with command: `nvim -u mini.vim`
   * The issue occurs on Neovim, but not Vim.
- Create an autocommand to output the diagnostic list when diagnostics change.
    * `:autocmd User CocDiagnosticChange echom CocAction('diagnosticList')`
- The following command works:
    * `:call CocActionAsync('diagnosticRefresh')`
- The following command results in an error:
    * `:call CocAction('diagnosticRefresh')`

## Error

```
Error detected while processing function CocAction[4]..coc#rpc#request[4]..<SNR>10_request[34
]..function CocAction[4]..coc#rpc#request[4]..<SNR>10_request:
line   31:
E605: Exception not caught: Error on request: Vim(return):Error invoking 'diagnosticRefresh' 
on channel 3 (coc):^@ch 3 returned a response with an unknown request id. Ensure the client i
s properly synchronized
```

**Comment by fannheyward** [comment]
Reproduced with nvim.

I want to know your workflow run `diagnosticRefresh` after `diagnosticList`.

1. `diagnosticList` will fetch and returns all diagnostics for all collections for current project
2. `diagnosticRefresh` will fetch and refresh diagnostics displaying, for current buffer only
3. they all get from same sources
4. `diagnosticRefresh` won't refresh `diagnosticList`

**Comment by dstein64** [comment]
> "I want to know your workflow run `diagnosticRefresh` after `diagnosticList`."

I encountered the error during development of a plugin that shows scrollbars ([nvim-scrollview](https://github.com/dstein64/nvim-scrollview)). `diagnosticList` is used to retrieve diagnostics for display on the scrollbar. `diagnosticRefresh` is used for its side-effect of triggering `CocDiagnosticChange`, since the preparation of diagnostic signs for the scrollbar is triggered by that event.

I [worked around](https://github.com/dstein64/nvim-scrollview/blob/74ab63b598cca206888e83090ed6312aac324b4c/lua/scrollview/contrib/coc.lua#L141-L148) the error by using `CocActionAsync` instead of `CocAction`.

**Comment by fannheyward** [comment]
Got your point, I think we should use `CocActionAsync` here for non-blocking, and I don't think `CocActionAsync` will cause any other errors.

Close for now.
