### ISSUE TITLE
Jump to selection in list not working 

### ISSUE THREAD

**Issue by fftyjw** [neoclide/coc.nvim#481]
Has to do twice when jump to select location in list. The first time always not working.

**To Reproduce**
1. :call CocAction("jumpReferences")<cr>
2. use 'j' or 'k' to select a location.
3. use '\<cr\>' to jump to selected location.

**Comment by chemzqm** [comment]
Try add `set hidden` and `set shortmess=aFc` to your .vimrc.

If still have issue, please provide minimal .vimrc that could reproduce your problem.

**Comment by fftyjw** [comment]
I found the problem while write golang program with macvim. So maybe you could use macvim to reproduce it.

**Comment by chemzqm** [comment]
I tried macvim and can't reproduce, try disable other plugins.

**Comment by fftyjw** [comment]
Sorry, my bad. It did jump, but after at least 3 second.

**Comment by chemzqm** [comment]
Try start upgrade macvim and start it with minimal .vimrc, like:
``` vim
set nocompatible
set runtimepath^=/path/to/coc.nvim

filetype plugin indent on
syntax on
set updatetime=300
set hidden
```
start macvim with `mvim -u mini.vim`

**Comment by fftyjw** [comment]
I followed you steps, and now the time is down to about 0.6s
