### ISSUE TITLE
Move to existing file with ts-server

### ISSUE THREAD

**Issue by edi9999** [neoclide/coc.nvim#4811]
**Is your feature request related to a problem? Please describe.**

I'd like to move code from file a.js to b.js

**Describe the solution you'd like**

After selecting the code visuall, and hitting <leader>r, I would expect to see in the list of actions : move to existing file, and be able to select the file where I want to move my code to.

But what I get currently is the following : 

![Selection_008](https://github.com/neoclide/coc.nvim/assets/2071336/43296aad-adab-4c81-8bfa-90ad014e33d6)

So I only got the option to move to a new file.

**Describe alternatives you've considered**

Haven't found any.

**Additional context**

Using coc.nvim master

It seems to be possible to move some code to a specified file in tsserver, as shown here in a typescript test case : 

https://github.com/microsoft/TypeScript/blob/main/tests/cases/fourslash/moveToFile_requireImport.ts

**Comment by edi9999** [comment]
Note that this works from vscode, so I guess it must be feasible to connect it with coc.nvim 

![Selection_009](https://github.com/neoclide/coc.nvim/assets/2071336/fa31a504-e544-47a8-bcdc-884e28112151)

**Comment by fannheyward** [comment]
Working on this.

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc-tsserver/pull/445

**Comment by fannheyward** [comment]
This feature has been released in `coc-tsserver-dev`, try `:CocUninstall coc-tsserver` and `:CocInstall coc-tsserver-dev`.

Note: coc-tsserver-dev is only used for unmerged PRs, and after PR merged into coc-tsserver, you should use coc-tsserver instead.
