### ISSUE TITLE
Customizing the popup for snippets

### ISSUE THREAD

**Issue by Ssionn** [neoclide/coc.nvim#4815]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It'd be nice to add some padding to the popup/docs hinting or making the border round

**Describe alternatives you've considered**
🚫

**Additional context**
![CleanShot 2023-11-22 at 09 09 15@2x](https://github.com/neoclide/coc.nvim/assets/90753599/5e816684-a3fc-4e24-8e00-abe1e524758f)

**Comment by fannheyward** [comment]
```json
  "hover.floatConfig": {
    "border": true,
    "rounded": true
  },
```

Try this in your coc-settings.json, check `:h coc-config-float` for more.
