### ISSUE TITLE
Diagnostics wrong buffer when starting with multiple tabs

### ISSUE THREAD

**Issue by DanielViberg** [neoclide/coc.nvim#4817]
## versions

vim version: VIM - Vi IMproved 9.0 9002127
node version: v18.13.0
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /home/daniel/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2023-11-24T08:30:17.805 INFO (pid:1302706) [plugin] - coc.nvim initialized with node: v18.13.0 after 1130
2023-11-24T08:30:17.808 INFO (pid:1302706) [services] - LanguageClient intelephense state change: stopped => starting
2023-11-24T08:30:17.825 INFO (pid:1302706) [language-client-index] - Language server "languageserver.intelephense" started with 1302877
2023-11-24T08:30:19.000 INFO (pid:1302706) [services] - LanguageClient intelephense state change: starting => running
2023-11-24T08:30:19.004 INFO (pid:1302706) [services] - service languageserver.intelephense started
2023-11-24T08:30:25.793 INFO (pid:1302706) [attach] - receive notification: showInfo []
2023-11-24T08:30:55.540 INFO (pid:1302706) [attach] - receive notification: showInfo []

## Describe the bug

Diagnostics in virtual text are in the wrong buffer when opening vim with two tabs at launch.

## Reproduce the bug

Used mini.vim

```
set nocompatible
set runtimepath^=/home/daniel/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

"Confirm completion with enter
inoremap <expr> <cr> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"

"GoTo definition
nnoremap <silent> <C-m> :call CocAction('jumpDefinition')<CR>

"Config file dir
let g:coc_config_home = $HOME . '/repos/DanielViberg/vim_config'

"Snippets
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ CheckBackspace() ? "\<TAB>" :
      \ coc#refresh()

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

let g:coc_snippet_next = '<tab>'

```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)
Notice $model and $relationName that is in the other tab.

![Screenshot from 2023-11-24 09-01-40](https://github.com/neoclide/coc.nvim/assets/27137435/08e5610f-e940-4c72-b72b-b20c24f42403)
![Screenshot from 2023-11-24 09-03-58](https://github.com/neoclide/coc.nvim/assets/27137435/2866f1a7-d9ee-4b8d-8984-da2781574f1c)

**Comment by fannheyward** [comment]
>  when opening vim with two tabs at launch.

What't the steps? Use `vim -p file1 file2`?

**Comment by DanielViberg** [comment]
vim -u mini.vim -p file1 file2

**Comment by fannheyward** [comment]
My tests: `file2` with diagnostics

`vim -p file1 file2`, can't reproduce this

<img width="761" alt="image" src="https://github.com/neoclide/coc.nvim/assets/345274/5e8edd19-d691-4391-a868-dec5d333a497">
<img width="825" alt="image" src="https://github.com/neoclide/coc.nvim/assets/345274/b9119b07-5c15-4878-995d-b60a30fa9ef7">

But reproduced with vim with this steps:

1. `vim file2`, diagnostics displayed with virtual text
2. `:tabnew` to open another tab
3. `:e file1`, the diagnostic of file1 displayed, and disappeared after cursor move

**Comment by DanielViberg** [comment]
Should I provide further test samples for this issue?
