### ISSUE TITLE
CocList preview window cursorline not showing

### ISSUE THREAD

**Issue by jackielii** [neoclide/coc.nvim#4819]
## Result from CocInfo

```
## versions

vim version: NVIM v0.9.4
node version: v21.2.0
coc.nvim version: 0.0.82-9c3723a0 2023-11-14 10:51:35 +0800
coc.nvim directory: /Users/jackieli/personal/coc.nvim
term: xterm-kitty
platform: darwin

## Log of coc.nvim

2023-11-26T22:14:02.551 INFO (pid:41928) [attach] - receive notification: updateConfig [ 'python.formatting.blackPath', '/opt/homebrew/bin/black' ]
2023-11-26T22:14:02.658 INFO (pid:41928) [extension:coc-git] - Looking for git in: git
2023-11-26T22:14:02.792 INFO (pid:41928) [plugin] - coc.nvim initialized with node: v21.2.0 after 302
2023-11-26T22:14:02.794 INFO (pid:41928) [attach] - receive notification: highlight []
2023-11-26T22:14:04.007 INFO (pid:41928) [attach] - receive notification: showInfo []

```

## Describe the bug

This was an issue for me for quite a while. It use to work but now not.

In `CocList --auto-preview grep ...` result I use to see the cursorline highlighting the matched line. But now it's gone. My request was similar to issue: https://github.com/neoclide/coc.nvim/issues/2039

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Enter `:CocList --auto-preview grep hello`

I tracked the issue down and it looks like it's set on purpose: https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/list.vim#L444 . And the highlights are latter on handled in [s:preview_highlights](https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/list.vim#L362). However I don't quite get what this is doing. And it's probably not working.

Can I request to bring back the cursorline for the preview window? or add an option for user to set it to a different highlight group. Or maybe the original `s:preview_highlights` are meant to work. Whichever it is, I just would like to see what's the matched line.

## Screenshots (optional)

![image](https://github.com/neoclide/coc.nvim/assets/360983/52c697c5-5358-4cef-a290-ebae7808bfa3)

**Comment by hexh250786313** [comment]
My hack: 

```
sd 'range: emptyRange\(range\) \? null' 'range: emptyRange(range) ? { start: range.start, end: { line: range.end.line, character: range.end.character + 1 } }' ~/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js
```

(`sd` is https://github.com/chmln/sd)

The matching in `grep` is not just single-line, so I think its implementation does not rely on `cursorline`, but rather on a kind of highlighting that changes the background color, similar to what's in `jumpDefinition`.

For technical reasons, it's quite challenging for `grep` to highlight the entire matching string, which might be the reason Zhao mentioned about not having the time to implement it.

Therefore, my hack only allows it to tell you where the first character of the match is, which is not difficult to implement.

https://github.com/neoclide/coc.nvim/assets/26080416/e0ecc72a-f06c-4a9f-b2aa-9410eab32fa2

**Comment by fannheyward** [comment]
<img width="763" alt="image" src="https://github.com/neoclide/coc.nvim/assets/345274/0b88f326-f775-409b-80b4-6f6b686f642c">

Changes in `coc-lists` only, working for `CocList --auto-preview grep hello`, but failed on `CocList --auto-preview grep hello[AB]`, working on this.

The core issue: extract `hello[AB]` to `hello`, remove regex-related characters.

**Comment by fannheyward** [comment]
Closing this issue in favor of https://github.com/neoclide/coc-lists/pull/151
