### ISSUE TITLE
typescript autocomplete drop list quick disappear  when use with plugin leafgarland/typescript-vim.

### ISSUE THREAD

**Issue by fftyjw** [neoclide/coc.nvim#482]
**Describe the bug**
The autocomplete drop list showed and then disappeared  when typing typescript code with plugin leafgarland/typescript-vim and coc-tsserver installed. When it happened, the status bar show message "omni completion pattern not found". And my environment is macvim.

**To Reproduce**
Just type any code than can invoke autocomplete will reproduce the bug.

**Comment by chemzqm** [comment]
I use leafgarland/typescript-vim and macvim, but I can't reproduce your problem.
Please provide detail information from `:CocInfo` and the minimal `.vimrc` that could help to reproduce.

**Comment by chemzqm** [comment]
> "omni completion pattern not found".

You're triggering omni completion, so maybe you're using other completion plugin.

**Comment by fftyjw** [comment]
:CocInfo got error msg:
Some plugin change completeopt on insert mode!

**Comment by chemzqm** [comment]
You have to disable completion of coc.nvim or other completion plugin.
You can disable completion of coc.nvim by add `  "suggest.autoTrigger": "none",` to your settings file.

**Comment by fftyjw** [comment]
I have found what trigger omni completion, it's ale with g:ale_completion_enabled option set to 1. Now it's work perfectly. Thanks for your help.
