### ISSUE TITLE
[coc.nvim]_Server languageserver.ccls failed to start: Error: expected rootUri

### ISSUE THREAD

**Issue by DorLM2** [neoclide/coc.nvim#4825]
platform: mac os 
Terminal: iterm2

<img width="856" alt="截屏2023-12-07 13 36 55" src="https://github.com/neoclide/coc.nvim/assets/152785825/448cf71d-8dc2-4b5f-9d1d-66afe6aa8927">
<img width="307" alt="截屏2023-12-07 13 36 31" src="https://github.com/neoclide/coc.nvim/assets/152785825/919f63ea-8686-4926-952c-e50c3e6bab29">

**Comment by DorLM2** [comment]
can you help me ?

**Comment by fannheyward** [comment]
`CocInfo` and `CocOpenLog` please .
