### ISSUE TITLE
Open my own java project and get an error when jumping

### ISSUE THREAD

**Issue by felixwluo** [neoclide/coc.nvim#4826]
errlog：[coc.nvim]: Error on notification "jumpDefinition": definition provider not found for current buffer, your language server doesn't support it

coc.nvim and coc-java they're all the latest versions

**Comment by fannheyward** [comment]
Language server issue, the server didn't respond for definitionProvider. Make sure the `jdtls` server installed successfully and run for your project.

Check `:CocOpenLog` and https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by felixwluo** [comment]
> Language server issue, the server didn't respond for definitionProvider. Make sure the `jdtls` server installed successfully and run for your project.
> 
> Check `:CocOpenLog` and https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

Thank you for your answer, I have solved
