### ISSUE TITLE
Irrelevant completion items before correct completion items

### ISSUE THREAD

**Issue by kabouzeid** [neoclide/coc.nvim#483]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.3.4
node version: v11.10.0
coc.nvim version: 0.0.58
term: iTerm.app
platform: darwin

## Error messages

## Output channel: highlight
[Info  - 5:20:59 PM] Highlight server running in node v11.10.0
```

**Describe the bug**
Irrelevant fuzzy completion items appear **before** the correct completion items.
When deleting a character, suddenly only the correct completion items remain.
In the attached GIF, first the completion items are correct, then I delete the input and type it again, suddenly the completion items are completely out of order. After deleting a character, everything is fine again.

**To Reproduce**
Choose a large file with many different words.

**Screenshots**
Please watch the whole GIF!

![problem](https://user-images.githubusercontent.com/7303830/53748719-3834fa00-3ea6-11e9-9a65-678a557995f2.gif)

**Comment by chemzqm** [comment]
Have not idea of how could this happen, consider try comment out this line: https://github.com/neoclide/coc.nvim/blob/afd005eb6a9cef1ab29f9024c4c13f1c325bc359/autoload/coc.vim#L40

**Comment by kabouzeid** [comment]
Thanks for the quick answer. That fixed it! Any drawbacks in keeping this line commented out?

**Comment by chemzqm** [comment]
I've removed the call to that function, it's not really necessary.

**Comment by chemzqm** [comment]
That function is necessary to avoid  pum flicking on neovim, use `"suggest.reloadPumOnInsertChar": true` if you still need it.
