### ISSUE TITLE
After I enter chinese characters, this error message appeares: “client coc abnormal exit with：-1”.

### ISSUE THREAD

**Issue by wuzhijiexia** [neoclide/coc.nvim#4836]
After I enter chinese characters, this error message appeares: “client coc abnormal exit with：-1”. 
If only english characters, the coc will normally works.

**Comment by wuzhijiexia** [comment]
There is nothing after CocOpenLog

**Comment by fannheyward** [comment]
How to reproduce this? Try minimal vimrc.

**Comment by fannheyward** [comment]
And your `CocInfo` please.

**Comment by fannheyward** [comment]
Should be fixed already in master branch, close for now.
