### ISSUE TITLE
How to exclude files (ex : *pb.h, *pb.cc) by using gr (gotoreferences) ?

### ISSUE THREAD

**Issue by zakalla** [neoclide/coc.nvim#4837]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fannheyward** [comment]
coc.nvim is an LSP client, sends `textDocument/references` to language server, displays the respond locations.

For this excluding feature, requires the language sever support not to return.
