### ISSUE TITLE
input tab when set tab as the trigger

### ISSUE THREAD

**Issue by gorliver** [neoclide/coc.nvim#4838]
Inserting tabs doen't work when setting tab as the trigger of completion.
This is not a bug but I can't find a configuration to solve it.
Many thanks for your help!
<img width="206" alt="image" src="https://github.com/neoclide/coc.nvim/assets/15271446/64ca6ed7-f830-42b5-8ec6-4b15f46d1a18">

**Comment by fannheyward** [comment]
You need to add `CheckBackspace` function to your vimrc, check `:h coc-completion-example` or search `CheckBackspace` in https://github.com/neoclide/coc.nvim#example-vim-configuration.
