### ISSUE TITLE
chained pointer does not autocomplete

### ISSUE THREAD

**Issue by laoshaw** [neoclide/coc.nvim#4842]
## versions                                                                      
   10                                                                                  
    9 vim version: VIM - Vi IMproved 9.0 9000749                                       
    8 node version: v18.12.1                                                           
    7 coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800                      
    6 coc.nvim directory: /home/tester/.vim/plugged/coc.nvim                            
    5 term: dumb                                                                       
    4 platform: linux                                                                  
    3                                                                                  
    2 ## Log of coc.nvim                                                               
    1                                                                                  
  12  2023-12-28T11:52:08.814 INFO (pid:32205) [configurations] - Add folder configuration from cwd: /home/tester/devel/code/.vim/coc-settings.json
    1 2023-12-28T11:52:11.285 INFO (pid:32205) [plugin] - coc.nvim initialized with node: v18.12.1 after 2551
    2 2023-12-28T11:52:11.326 INFO (pid:32205) [services] - LanguageClient clangd state change: stopped => starting
    3 2023-12-28T11:52:11.342 INFO (pid:32205) [language-client-index] - Language server "clangd" started with 32246
    4 2023-12-28T11:52:11.380 INFO (pid:32205) [services] - LanguageClient clangd state change: starting => running
    5 2023-12-28T11:52:11.390 INFO (pid:32205) [services] - service clangd started     
    6 2023-12-28T11:52:11.795 INFO (pid:32205) [core-watchman] - watchman watching project: /home/tester/code
    7 2023-12-28T11:52:22.000 INFO (pid:32205) [attach] - Request action: doKeymap [ 'i-PGJzPg==' ]
    8 2023-12-28T11:52:22.395 INFO (pid:32205) [attach] - Request action: doKeymap [ 'i-Pg==' ]
    9 2023-12-28T11:52:33.293 INFO (pid:32205) [attach] - Request action: doKeymap [ 'i-Pg==' ]
   10 2023-12-28T11:52:34.813 INFO (pid:32205) [attach] - Request action: doKeymap [ 'i-PGJzPg==' ]
   11 2023-12-28T11:52:34.981 INFO (pid:32205) [attach] - Request action: doKeymap [ 'i-PGJzPg==' ]
   12 2023-12-28T11:52:36.637 INFO (pid:32205) [attach] - Request action: doKeymap [ 'i-PGJzPg==' ]
   13 2023-12-28T11:52:39.957 INFO (pid:32205) [attach] - Request action: doKeymap [ 'i-PGJzPg==' ]
   14 2023-12-28T11:52:42.333 INFO (pid:32205) [attach] - Request action: doKeymap [ 'i-Pg==' ]
   15 2023-12-28T11:53:36.861 INFO (pid:32205) [attach] - receive notification: showInfo []
   16                                                                                  

## Describe the bug

When I do mypointer->  I will see all hints on a drop list, however when I do mypointer->chainedpointer-> I see no hints

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

same problem, chained pointers give no hints

**Comment by fannheyward** [comment]
> vscode does not work either

`clangd`'s issue, no completions returned for chained pointer case.

>  can coc.nvim just build its own index db somehow

coc.nvim is an LSP client, it requests from language server, here is clangd, for completions or code actions or diagnostics etc, clangd handles the requests, analyzes codes, returns the results, and coc.nvim displays the suggestions/diagnostics or applies the changes. Building an index db is clangd's job.
