### ISSUE TITLE
Highlight groups not reset after colorscheme change

### ISSUE THREAD

**Issue by egorbn** [neoclide/coc.nvim#4857]
### versions

vim version: VIM - Vi IMproved 9.1 9010000
node version: v21.5.0
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /Users/esbn/.vim/pack/coc/start/coc.nvim
term: tmux
platform: darwin

## Describe the bug

Coc* highlight groups are not reset after colorscheme change.

When vim is started, Coc sets various highlight groups such as:
<img width="654" alt="image" src="https://github.com/neoclide/coc.nvim/assets/116128944/c99b670f-1a94-403b-9777-88aca8b7159c">

If a colorscheme command is triggered to change the colorscheme, some of these groups are cleared, and not restored:
<img width="398" alt="image" src="https://github.com/neoclide/coc.nvim/assets/116128944/ac680ee3-37ee-4774-b990-e59873fd50bc">

I see that there is an autocommand that runs `s:Highlight()` on colorscheme change:
<img width="669" alt="image" src="https://github.com/neoclide/coc.nvim/assets/116128944/5551a7d8-7542-4640-b26e-6d519a7b462a">

But this does not restore some of the cleared groups.

What I understand the function `s:Highlight()` to do is to set all the highlighting for coc, however, not all groups look like they get reset.

coc sets highlight groups when it is loaded -- how can this be triggered again after a colorscheme change?

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

I used the mini.vim given in the template:

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- run `:highlight`
- See schreenshots above for output
- run `:colorscheme solarized8`
- It doesn't matter what the colorscheme is, what is important is that it runs `:hi clear`
- run `:highlight` again
- See screenshots above for new output with many groups not restored after clear

**Comment by fannheyward** [comment]
After `:hi clear` or `:colorscheme default` etc, coc.nvim's custom hi group like `CocSearch` was cleared, but `CocFloatActive` was still linked to `CocSearch`. My question: does _linked_ hi group also be cleared after `:hi clear`? I did some search in vim doc etc, didn't find any resource for this. In my understanding,  `CocFloatActive` linked to `CocSearch` which one was cleared, `CocFloatActive` won't work any more.

**Comment by fannheyward** [comment]
coc.nvim set hi groups with `default` argument, like `hi default link CocFloatActive CocSearch`.

The `default` argument in coc.nvim allows custom highlighting groups to be retained when switching color schemes. Refer to `:h :hi-default` for more information.
