### ISSUE TITLE
Show signature help in floating window

### ISSUE THREAD

**Issue by purpleP** [neoclide/coc.nvim#486]
Now that floating window merged into master can you consider showing signature help inside floating window instead of command line?

For what it's worth its how jetbrains products doing it (above current line usually). I think it's better than using command line mainly because it's closer to cursor.

**Comment by oblitum** [comment]
At this moment, I think it's worth considering what to do about overloads (see #305 for trade-offs).

**Comment by oblitum** [comment]
Hmm, looks like this issue is already covered by #38, and could be closed as duplicate.
