### ISSUE TITLE
outline.autoWidth doesn't work

### ISSUE THREAD

**Issue by yimingwangdell** [neoclide/coc.nvim#4864]
## Describe the bug
I cannot change width with "outline.autoWidth", and there is no "outline.Width" configuration.
the only way to change width is modify outline.splitCommand, which is not obvious. 
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
The `outline.autoWidth` is used to increase window width to avoid wrapped line, only work for buffer contains more than 2 lines. Can you provide a screenshot for your case?

**Comment by banyard-ibm** [comment]
I was also having problems getting `autoWidth` working, when it was enabled my `outline.splitComand` value was being ignored. Checking the code I found `autoWidth` is bound by `g:coc_max_treeview_width`, in the end I just needed to increase this value.
