### ISSUE TITLE
Complaints about completeopt interference even when suggest.keepCompleteOpt is enabled

### ISSUE THREAD

**Issue by reaysawa** [neoclide/coc.nvim#487]
**Describe the bug**

Even having set   `"suggest.keepCompleteOpt": true`, CoC still complains when completeopt is changed during insert mode.

```
lib/workspace.js:119:  console.error(`Some plugin change completeopt on insert mode!`); // tslint:disable-line
src/workspace.ts:132:  if (mode.startsWith('i')) console.error(`Some plugin change completeopt on insert mode!`) // tslint:disable-line
```

CoC should not care about completeopt when `suggest.keepCompleteOpt` is enabled.

**Comment by chemzqm** [comment]
It should not care the change when `suggest.autoTrigger` is not `always`, just fixed it.
