### ISSUE TITLE
error messages if semanticTokens are enabled

### ISSUE THREAD

**Issue by cridemichel** [neoclide/coc.nvim#4872]
## versions

vim version: VIM - Vi IMproved 9.1 9010050
node version: v21.6.1
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /Users/demichel/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2024-01-27T18:46:11.210 INFO (pid:38752) [plugin] - coc.nvim initialized with node: v21.6.1 after 518
2024-01-27T18:46:11.236 INFO (pid:38752) [services] - LanguageClient clangd state change: stopped => starting
2024-01-27T18:46:11.241 INFO (pid:38752) [language-client-index] - Language server "clangd" started with 38754
2024-01-27T18:46:11.441 INFO (pid:38752) [services] - LanguageClient clangd state change: starting => running
2024-01-27T18:46:11.451 INFO (pid:38752) [services] - service clangd started
2024-01-27T18:46:14.656 INFO (pid:38752) [attach] - receive notification: showInfo []

## coc-settings.json
```json
{
  "diagnostic.refreshOnInsertMode": true,
  "semanticTokens.enable": true,
  "diagnostic.checkCurrentLine": true,
  "suggest.enablePreview": true,
  "suggest.triggerAfterInsertEnter": true,
  "diagnostic.messageTarget": "float",
  "diagnostic.enable": false,
  "inlayHint.enable" : true,
  "suggest.noselect": true,
  "suggest.minTriggerInputLength": 2,
  "inlayHint.enableParameter": false,
  "coc.source.vimtex.priority": 99,
  "python.pythonPath": "/usr/local/bin/python3",
  "markdown-preview-enhanced.enableScriptExecution": true,
  "coc.preferences.diagnostic.displayByAle": true,
  "list.source.files.args": ["--hidden", "--files"],
  "yank.highlight.enable": false,
  "pyright.inlayHints.parameterTypes": false,
  "pyright.inlayHints.variableTypes": false,
  "pyright.disableDocumentation": false,
  "pyright.enable": true,
  "semanticTokens.enable": true,
  "colors.enable": true,
  "links.enable": false,
  "links.highlight": false,
  "links.tooltip": false,
  "suggest.floatConfig": {"border": false, "rounded": false}
}
```

## Describe the bug

vim produces several error messages by jumping back and forth between two files
if semantic tokens are enabled and "hidden" vim options is false (see minimal vimrc below)
Note that if "set hidden" is used the bug diasappears. I also noticed that with semantic tokens
enable vim "stutters" on scrolling by pressing \<PgUp\> or <PgDown\>.

## Reproduce the bug

1) open the "molgl.c" which you can find below

2) jump to the definition of an opengl function by typing "<leader>gd" (see the minimal vimrc used posted below)

3) jump back and forth with \<c-o\> and \<c-i\>
 
# minimal vimrc file used to reproduce the bug
  ```vim
 set nocompatible
set runtimepath^=/Users/demichel/.vim/plugged/coc.nvim/
filetype plugin indent on
let mapleader = ' '
let maplocalleader=' '
nmap <leader>gd <Plug>(coc-definition)
syntax on
set nohidden
  ```
### vim version

:version
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jan 23 2024 22:19:02)
macOS version - x86_64
Included patches: 1-50
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +comments          +find_in_path      +lispindent        +multi_byte        +rightleft         +terminal          +wildignore
+arabic            +conceal           +float             +listcmds          +multi_lang        +ruby              +terminfo          +wildmenu
+autocmd           +cryptv            +folding           +localmap          -mzscheme          +scrollbind        +termresponse      +windows
+autochdir         +cscope            -footer            +lua               +netbeans_intg     +signs             +textobjects       +writebackup
-autoservername    +cursorbind        +fork()            +menu              +num64             +smartindent       +textprop          -X11
-balloon_eval      +cursorshape       +gettext           +mksession         +packages          +sodium            +timers            -xattr
+balloon_eval_term +dialog_con        -hangul_input      +modify_fname      +path_extra        +sound             +title             -xfontset
-browse            +diff              +iconv             +mouse             +perl              +spell             -toolbar           -xim
++builtin_terms    +digraphs          +insert_expand     -mouseshape        +persistent_undo   +startuptime       +user_commands     -xpm
+byte_offset       -dnd               +ipv6              +mouse_dec         +popupwin          +statusline        +vartabs           -xsmp
+channel           -ebcdic            +job               -mouse_gpm         +postscript        -sun_workshop      +vertsplit         -xterm_clipboard
+cindent           +emacs_tags        +jumplist          -mouse_jsbterm     +printer           +syntax            +vim9script        -xterm_save
-clientserver      +eval              +keymap            +mouse_netterm     +profile           +tag_binary        +viminfo
+clipboard         +ex_extra          +lambda            +mouse_sgr         -python            -tag_old_static    +virtualedit
+cmdline_compl     +extra_search      +langmap           -mouse_sysmouse    +python3           -tag_any_white     +visual
+cmdline_hist      -farsi             +libcall           +mouse_urxvt       +quickfix          -tcl               +visualextra
+cmdline_info      +file_in_path      +linebreak         +mouse_xterm       +reltime           +termguicolors     +vreplace
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang -L/usr/local/lib -o vim -lm -lncurses -lsodium -liconv -lintl -framework AppKit -L/usr/local/opt/lua/lib -llua5.4 -mmacosx-version-min=14.2
 -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/perl/lib/perl5/5.38/darwin-thread-multi-2level/CORE -lperl -L/usr/local/opt/python@3.12/Framew
orks/Python.framework/Versions/3.12/lib/python3.12/config-3.12-darwin -lpython3.12 -framework CoreFoundation -lruby.3.3 -L/usr/local/Cellar/ruby/3.3.0/l

## Screenshots 

<img width="1441" alt="Senza nome" src="https://github.com/neoclide/coc.nvim/assets/15322138/19123e2c-bfb1-467b-94e3-e5b29ebbf8d9">

https://github.com/neoclide/coc.nvim/assets/15322138/35cee4ec-2585-4b51-a73b-54d70d69888a

### file used to reproduce the bug

[molgl.c.zip](https://github.com/neoclide/coc.nvim/files/14073269/molgl.c.zip)

**Comment by cridemichel** [comment]
**FOLLOW UP**

Considering the error message and the fact that "hidden" option is false, it seems that coc is trying to add highlights to a non existing buffer, indeed if the function  "s:add_highlights_timer" in "autoload/coc/highlight.vim", i.e.
```viml
function! s:add_highlights_timer(bufnr, ns, highlights, priority) abort
  let hls = []
  let next = []
  for i in range(0, len(a:highlights) - 1)
    if i < g:coc_highlight_maximum_count
      call add(hls, a:highlights[i])
    else
      call add(next, a:highlights[i])
    endif
  endfor
  call s:add_highlights(a:bufnr, a:ns, hls, a:priority)
  if len(next)
    call timer_start(30, {->s:add_highlights_timer(a:bufnr, a:ns, next, a:priority)})
  endif
endfunction
```
is changed as follows:
```viml

function! s:add_highlights_timer(bufnr, ns, highlights, priority) abort
  let hls = []
  let next = []
  for i in range(0, len(a:highlights) - 1)
    if i < g:coc_highlight_maximum_count
      call add(hls, a:highlights[i])
    else
      call add(next, a:highlights[i])
    endif
  endfor
  if bufwinnr(a:bufnr)!=-1   " check if buffer still exists     
    call s:add_highlights(a:bufnr, a:ns, hls, a:priority)
  endif
  if len(next) && bufwinnr(a:bufnr) != -1 "check if buffer still exists
    call timer_start(30, {->s:add_highlights_timer(a:bufnr, a:ns, next, a:priority)})
  endif
endfunction
```
error messages disappear.
I do not if this is an appropriate fix but I hope this helps fixing this issue,

best Cristiano

**Comment by fannheyward** [comment]
Thank you for your report. Reproduced in vim with `set nohidden`, and made a PR with fix.

**Comment by cridemichel** [comment]
Hi, 
there are still problems, if you open the file molgl.c with vim
(using the minimal vimrc file which I uploaded) and just after having open it:

1) press arrow down key

2) press 'o' to enter a new line and to switch to "insert mode"

you will get again error messages,

unfortunately, I do not any fix to suggest yet,
best C.

**Comment by cridemichel** [comment]
***FOLLOW UP:***

the only fix which I found is to ignore error E964 by modifying  the function  "s:funcs.buf_add_highlight" in 
autoload/coc/api.vim as follows:

```viml
function! s:funcs.buf_add_highlight(bufnr, srcId, hlGroup, line, colStart, colEnd, ...) abort
  if a:srcId == 0
    let srcId = s:max_src_id + 1
    let s:max_src_id = srcId
  else
    let srcId = a:srcId
  endif
  let bufnr = a:bufnr == 0 ? bufnr('%') : a:bufnr
  let type = srcId == -1 ? a:hlGroup : a:hlGroup.'_'.srcId
  let types = get(s:id_types, srcId, [])
  if index(types, type) == -1
    call add(types, type)
    let s:id_types[srcId] = types
    if empty(prop_type_get(type))
      call prop_type_add(type, extend({'highlight': a:hlGroup}, get(a:, 1, {})))
    endif
  endif
  let end = a:colEnd == -1 ? strlen(get(getbufline(bufnr, a:line + 1), 0, '')) + 1 : a:colEnd + 1
  if end < a:colStart + 1
    return
  endif
  let id = s:generate_id(a:bufnr)
  try
    call prop_add(a:line + 1, a:colStart + 1, {'bufnr': bufnr, 'type': type, 'id': id, 'end_col': end})
  catch /^Vim\%((\a\+)\)\=:\(E967\|E964\)/ 
    " ignore 967 and 964
  endtry
  if a:srcId == 0
    " return generated srcId
    return srcId
  endif
  return v:null
endfunction
```
where in the regexp of catch statement I replaced
```viml
 /^Vim\%((\a\+)\)\=:E967/
```
with
```viml
 /^Vim\%((\a\+)\)\=:\(E967\|E964\)/
```
I am also wondering whether in the previous fix which I suggested is better to replace the conditions
```viml
bufwinnr(a:bufnr)!=-1
```
with

```viml
bufexists(a:bufnr)
```

best C.

**Comment by cridemichel** [comment]
Finally, concerning the stuttering on scrolling, it can be significantly mitigated by increasing the time of the timer in function  "s:add_highlights_timer", e.g.

```viml
function! s:add_highlights_timer(bufnr, ns, highlights, priority) abort
  let hls = []
  let next = []
  for i in range(0, len(a:highlights) - 1)
    if i < g:coc_highlight_maximum_count
      call add(hls, a:highlights[i])
    else
      call add(next, a:highlights[i])
    endif
  endfor
  if bufwinnr(a:bufnr)!=-1 " check if buffer exists 
     call s:add_highlights(a:bufnr, a:ns, hls, a:priority)
  endif
  if len(next) && bufwinnr(a:bufnr)!=-1
    call timer_start(500, {->s:add_highlights_timer(a:bufnr, a:ns, next, a:priority)}) " previously it was 30 milliseconds
  endif
endfunction

```
it would be possibile to have this time as a coc setting in .vimrc?
For example
```
let g:coc_highlights_timer=500
```
