### ISSUE TITLE
keep list open when jumping to references.

### ISSUE THREAD

**Issue by yimingwangdell** [neoclide/coc.nvim#4886]
is it possible?

**Comment by fannheyward** [comment]
Use https://github.com/kevinhwang91/nvim-bqf for this feature.

**Comment by yimingwangdell** [comment]
@fannheyward the references list is not created by quickfix, it's created by coc list. will "bqf" work?

**Comment by fannheyward** [comment]
nvim-bqf can integrate with coc.nvim, to list coc's references to quickfix.
