### ISSUE TITLE
commit related to issue #4872

### ISSUE THREAD

**Issue by cridemichel** [neoclide/coc.nvim#4903]
Hi,
the commit https://github.com/neoclide/coc.nvim/commit/c91fddfc23606647fe7e2aef80dfd4c74c211603 related to issue #4862  has not been merged, but apparently it has been discarded, why?

best Cristiano

**Comment by fannheyward** [comment]
My mistake, I thought https://github.com/neoclide/coc.nvim/pull/4885 was included this, so I closed https://github.com/neoclide/coc.nvim/pull/4874

**Comment by cridemichel** [comment]
ok I figured that

**Comment by cridemichel** [comment]
great!
