### ISSUE TITLE
coc.nvim code completion, can not switch each element in the completion code box

### ISSUE THREAD

**Issue by Yeatsflee** [neoclide/coc.nvim#4905]
When code completion (click tab/shift-tab), the code selection does not toggle in the selection box, but only switch each element in current line directly

**Comment by Yeatsflee** [comment]
https://github.com/neoclide/coc.nvim/assets/53549627/467aca54-875f-4387-b5ed-7ba6f18614b9

The detailed phenomenon is shown as above

**Comment by fannheyward** [comment]
Can't reproduce, `:CocInfo` and how do you setup coc.nvim mappings?
