### ISSUE TITLE
Add example vim configuration as file instead of inlining it in the README.md

### ISSUE THREAD

**Issue by r10r** [neoclide/coc.nvim#4914]
**Is your feature request related to a problem? Please describe.**

I'm installing and updating coc.nvim release in our devcontainer from the release branch:

```Dockerfile
WORKDIR /vim/plugins  
RUN git clone --depth=1 --branch=release https://github.com/neoclide/coc.nvim.git 
```
I noticed that the [default vim configuration](https://github.com/neoclide/coc.nvim?tab=readme-ov-file#example-vim-configuration) changes over time should be updated along with the coc.nvim plugin. 
Not updating it may cause unexpected issues.

I'd like to update the example vim config within the Dockerfile e.g:

```Dockerfile
ADD https://raw.githubusercontent.com/neoclide/coc.nvim/release/package.json /etc/vim/vimrc.coc
```

**Describe the solution you'd like**

Instead of inlining the default vim configuration in the *README.md*  it could be added as file to repository e.g to *example-vim-configuration*  and referenced from the *README.md*

**Comment by fannheyward** [comment]
https://raw.githubusercontent.com/neoclide/coc.nvim/master/doc/coc-example-config.vim

**Comment by r10r** [comment]
Thanks!
