### ISSUE TITLE
language specified rootPatterns would be overwritten by coc.preferences.rootPatterns

### ISSUE THREAD

**Issue by kaijajan** [neoclide/coc.nvim#493]
use coc.nvim with ccls and specified compile_commands.json in ccls settings (coc-settings.json)
while open nvim under folder which contains compile_commands.json, coc.nvim passes the parent folder which contains .git folder to ccls
this caused ccls unable to work with compile_coomands.json

folder structure
```
project root/
  .git/
  linux/
    compile_commands.json
```

**Comment by chemzqm** [comment]
Checkout: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel,
 looks like the filename doesn't match the one you have specified in coc-settings.json.
