### ISSUE TITLE
How to select an item

### ISSUE THREAD

**Issue by guest73** [neoclide/coc.nvim#4939]
I am using coc-java and when I want to generate getters/setters I trigger a list where particular fields can be selected. I have no idea how to make a selection there. Is it mentioned somewhere in the docs? I cannot find what key combinations selects/unselects an item.

![selection](https://github.com/neoclide/coc.nvim/assets/4907799/8e0baf1c-f04a-4dc7-ac35-b29e90be5a67)

**Comment by fannheyward** [comment]
What's your `:CocInfo`? The menus can be selected by space.

**Comment by guest73** [comment]
Unfortunately space does not work. When I type space it filters the input ;(

![Screenshot at 2024-03-13 14-44-36](https://github.com/neoclide/coc.nvim/assets/4907799/1b65e9d5-bb43-4cd1-812f-1dc03c1f05bd)

**Comment by guest73** [comment]
@fannheyward , Thanks, will try.

**Comment by guest73** [comment]
Switching to Vim 9 did not help. Right now I am switching to Debian based distro, maybe there Vim 9 has a newer version.
