### ISSUE TITLE
Behavior of the preview window

### ISSUE THREAD

**Issue by monkoose** [neoclide/coc.nvim#494]
Hello, thanks for a great plugin.
I have the question about preview window of doHover. By default it automatically closes when you press any key, even with the cursor move by hjkl, how I can prevent this? I want to close it only by pclose or C-w z when I need to.

**Comment by chemzqm** [comment]
Add `"coc.preferences.previewAutoClose": true` to coc-settings.json.

**Comment by monkoose** [comment]
Is it mentioned in the docs? I searched for some config option but haven't found it.

**Comment by chemzqm** [comment]
It's in `data/schema.json`, need a script to generate them in help file.

**Comment by monkoose** [comment]
Ok, thanks.
