### ISSUE TITLE
Display codeLens on an empty line.

### ISSUE THREAD

**Issue by NJichev** [neoclide/coc.nvim#495]
**Is your feature request related to a problem? Please describe.**
When using neovim virtual text code lens for suggesting type definitions they get displayed on
the same line as the function declaration. This leads to the problem of having 200+ characters per line which makes it hard to read.

**Describe the solution you'd like**
The solution I am suggesting is adding a new `codeLens.` option that lets users specify messages starting with a string or patterns to be put above or below on the first empty line.

Example how it would look like, consider this Elixir code:
```elixir
defmodule Test do
  # ...

  def foo do
    :bar
  end
end
```

The code lens will do something like this(after > is virtual text):
```elixir
defmodule Test do
  # ...

  def foo do > @spec foo() :: :bar
    :bar
  end
end
```

With the solution this will look like this:
```elixir
defmodule Test do
  # ...
 > @spec foo() :: :bar
  def foo do
    :bar
  end
end
```

The new option in the schema could look something like this:
```
  "codeLens.displayMessagesAboveOnEmptyLine": ["@spec"]
```

**Describe alternatives you've considered**
I've considered just setting to put all code lens messages above one line, but this will probably break a lot of other code.
Other alternatives are changing this in the elixir server's behaviour and sent information, but it seems that VSCode does the same since they use the same language server but display the information above the function definition.

**Additional context**
I am using the Elixir language server and build coc from master. The language server is this one https://github.com/elixir-lsp/elixir-ls/

**Comment by gugahoa** [comment]
This seems like a great feature to have, why not re-open?

Although what I want is not that complicated, I just want the option to show all `codeLens` virtual texts on the line above

**Comment by chemzqm** [comment]
There's no such support with vim or neovim.
