### ISSUE TITLE
Move across symbol usage highlights

### ISSUE THREAD

**Issue by asmodeus812** [neoclide/coc.nvim#4951]
**Is your feature request related to a problem? Please describe.**
It would be great if along with the usage / symbol highlight action we can actually move between the highlighted symbols, and while we move with next_/prev_usage the highlights should not be cleared

**Describe the solution you'd like**
Have an interface with next_usage / prev_usage that triggers the highlight for the current symbol under the cursor, if not already triggered, moves to the prev/next/first/last usage and does not clear the highlights while the user moves with next/prev usage api. (e.g. if we have them bound to `]r` and `[r`)

**Describe alternatives you've considered**
It could be possible to use the response of highlight, to resolve where the next and prev positions are.

**Additional context**
None

**Comment by asmodeus812** [comment]
Probably not worth the effort, one could simply fetch the symbol ranges and do something simple like that, for future reference to whoever comes around this issue of moving to next/prev usage in the buffer

```lua
local function lsp_moveto_usage(dir, pin)
    usages = vim.tbl_map(function(r)
        return {
            start = { row = r.start.line, col = r.start.character },
            finish = { row = r["end"].line, col = r["end"].character },
        }
    end, vim.fn.CocAction("symbolRanges") or {})

    local cursor = vim.api.nvim_win_get_cursor(0)
    local row = cursor[1] - 1; local col = cursor[2]

    local oldignore = vim.o.eventignore
    vim.o.eventignore = "CursorMoved"

    usages = usages.result -- usages
    for idx, pos in ipairs(usages) do
        local new_position = nil
        if dir > 0 and pin == 1 then
            new_position = usages[#usages]
        elseif dir < 0 and pin == 1 then
            new_position = usages[1]
        elseif row >= pos.start.row and row <= pos.finish.row and col >= pos.start.col and col <= pos.finish.col then
            if dir < 0 and idx == 1 then
                new_position = usages[#usages]
            elseif dir > 0 and idx == #usages then
                new_position = usages[1]
            else
                new_position = usages[idx + dir]
            end
        end

        if type(new_position) == "table" then
            vim.cmd.normal({ args = { "m'" } }) -- remember pos into the jumplist
            local new_cursor = { new_position.start.row, new_position.start.col }
            vim.api.nvim_win_set_cursor(0, { new_cursor[1] + 1, new_cursor[2] })
            vim.cmd.normal({ args = { "m'" } }) -- remember pos into the jumplist
            break
        end
    end

    vim.schedule(function()
        -- optionally highight also
        vim.o.eventignore = oldignore
    end)
end
```

**Comment by chemzqm** [comment]
Use `:CocCommand document.jumpToPrevSymbol` and `:CocCommand document.jumpToNextSymbol` see `:h coc-document-highlights`

**Comment by chris-morgan** [comment]
Didn’t know about those commands. But after trying it, I’ll stick with mine, because those commands don’t update the `'` mark, so things like <CTRL-O> to jump back don’t work.

Thinking more about it because of this, I also realised both solutions were missing count support. I’ve updated [my implementation](https://github.com/neoclide/coc.nvim/issues/4951#issuecomment-2429774874) to use `v:count`, so now `3gl` will step three forward. This makes it match things like search and spelling (e.g. `2n`, `3]s`), though I don’t take the possibility of `'nowrapscan'` into account.

Should probably go through and make things like `<Plug>(coc-diagnostic-prev)` take counts, too. Really, this whole prev/next thing is dubious, better to take a count which is not just limited to -1 and 1.

**Comment by chemzqm** [comment]
> because those commands don’t update the ' mark, so things like to jump back don’t work.

Consider create a feature request issue, so we can remember to look into it.
