### ISSUE TITLE
hover always shows in floating window, even already set to echo

### ISSUE THREAD

**Issue by fannheyward** [neoclide/coc.nvim#496]
`"coc.preferences.hoverTarget": "echo"`, hover target is already set to echo, but when do `K` for document, floating window shows the doc, not echo.

https://github.com/neoclide/coc.nvim/blob/79ffadd4f9fa562777427d03d95d91d0b32ec162/src/handler/index.ts#L804-L806

It seems that hover target is set to floating if `workspace.env.floating`.

**Comment by iamcco** [comment]
`data/scheme.json` should also add a floating enum value for `coc.preferences.hoverTarget`.
