### ISSUE TITLE
Unable to correctly select the first parameter of the function

### ISSUE THREAD

**Issue by SailYoungCodeGod** [neoclide/coc.nvim#4968]
When using coc-clangd, it is not possible to correctly select the first parameter when completing the function within the function. When I remove the parentheses of the outer function, I can correctly select the first parameter.

https://github.com/neoclide/coc.nvim/assets/165667274/2c43e387-b71f-47b4-b917-1c97956dc109

**Comment by fannheyward** [comment]
`:CocInfo` please

**Comment by fannheyward** [comment]
Upgrade your Vim and try again, 8.2 is too old release.
