### ISSUE TITLE
Is it able to open multiple list window.

### ISSUE THREAD

**Issue by aispeaking** [neoclide/coc.nvim#4970]
**Is your feature request related to a problem? Please describe.**
When using the grep list, the list window always shows the result of last searching.
I hope there is a way to access the history searching  result.
Notepadd++ search panel is a example.

**Describe the solution you'd like**
Maybe a argument to specify 'open the list in a new window/tab'.
Or, using a treeview to list results of each invoke.
Or, just a argument to 'append the result to the previous list'.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fannheyward** [comment]
No such feature, and no plan to add this.
