### ISSUE TITLE
List not work after some operation

### ISSUE THREAD

**Issue by aispeaking** [neoclide/coc.nvim#4971]
## Result from CocInfo

The `CocInfo` seems broken, I don't know why. 
coc.nvim is the latest master. 
vim 9.0.1563/ nvim v0.9.0
> [coc.nvim]: Error on notification "showInfo": stripAnsi3 is not a function

## Describe the bug

Some keymaps not work in list window. `Enter` do not open the file (for files list), `TAB` no not show the action.

## Reproduce the bug

case 1:

- Type `:CocList files` to open files list.
- Type `Ctrl-o` to switch to NORMAL model.
- Type `:` and then `<ESC>`.
- Press `<Enter>` and can't open the file under cursor.

case 2:

- `:CocList files` to open files list and then open one file.
- `:CocList grep int` to open grep list and then open one file location.
- `:CocListResume files`, can't open files.

## Screenshots (optional)

NULL

**Comment by fannheyward** [comment]
Your coc.nvim is broken, how do you install it?

**Comment by aispeaking** [comment]
@fannheyward I just use the "PlugUpdate" command few days ago and it says my nodejs v18.12.1 is too old, so I upgraded it to 20.12.0 and every thing works fine.  I'm just using the CocListResume command and found it not working in somecase, not sure if it is ok before.

> Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn --install --frozen-lockfile'}

**Comment by fannheyward** [comment]
It's recommended to use `Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'npm ci'}`, https://github.com/neoclide/coc.nvim?tab=readme-ov-file#quick-start

Will check the CocListResume issue.

**Comment by aispeaking** [comment]
CocInfo is ok now after reinstall with the new command.

> ## versions
> 
> vim version: VIM - Vi IMproved 9.0 9001563
> node version: v20.12.0
> coc.nvim version: 0.0.82-ede39ea 2024-03-28 17:57:50 +0800
> coc.nvim directory: /home/liyt/code/extern/vim-runtime/plugged/coc.nvim
> term: dumb
> platform: linux
> 
> ## Log of coc.nvim
> 
> 2024-04-07T17:22:27.540 INFO (pid:45548) [configurations] - Add folder configuration from cwd: /home/liyt/code/extern/vim-runtime/plugged/coc.nvim/.vim/coc-settings.json
> 2024-04-07T17:22:27.735 INFO (pid:45548) [extension:coc-git] - Looking for git in: git
> 2024-04-07T17:22:27.768 WARN (pid:45548) [workspace] - Extension "coc-lists" registered synchronized autocmd "VimLeavePre", which could be slow.
> 2024-04-07T17:22:28.102 INFO (pid:45548) [plugin] - coc.nvim initialized with node: v20.12.0 after 630

**Comment by fannheyward** [comment]
case 1 is by designed, `:` cancels the list,  `<CR>` does line downward same as normal vim buffer.

https://github.com/neoclide/coc.nvim/blob/48bae5f48c274e41637b8d7e4cfede1a0fe15dea/src/list/mappings.ts#L69-L72
