### ISSUE TITLE
change `codeLens.separator` accoding to filetype comment char

### ISSUE THREAD

**Issue by leoatchina** [neoclide/coc.nvim#4978]
**Is your feature request related to a problem? Please describe.**
s there any way to change  code lens symbol like a coment string ， according to buffer's filetype.

**Describe the solution you'd like**
For examples,  `Python` use `#`,   c/cpp/rust use `//` as codeLens.separator

**Describe alternatives you've considered**
No

**Comment by fannheyward** [comment]
Changed the scope of codeLens configurations to `language-overridable`, we now can set different separator for different languages.

```json
  "[python]": {
    "codeLens.separator": "#"
  },
  "[c][typescript]": {
    "codeLens.separator": "//"
  },
```

**Comment by leoatchina** [comment]
Ok， thanks
