### ISSUE TITLE
Long delay on hover, highlight on hover & cut off messages

### ISSUE THREAD

**Issue by tomspeak** [neoclide/coc.nvim#498]
**Result from CocInfo**

```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.58
term: tmux-256color
platform: darwin

## Error messages

## Output channel: highlight
[Info  - 15:21:09] Highlight server running in node v8.9.0

## Output channel: tsserver
[Info  - 15:21:11] Forking TSServer
PATH: /opt/twitter_mde/bin:/opt/twitter_mde/homebrew_minimal/mde_bin:/opt/twitter_mde/homebrew/mde_bin:/Users/tspeak/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-caarlos0-SLASH-open-pr:/usr/local/heroku/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/opt/twitter_mde/bin:/opt/twitter_mde/homebrew_minimal/mde_bin:/opt/twitter_mde/homebrew/mde_bin:/Users/tspeak/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-caarlos0-SLASH-open-pr:/usr/local/heroku/bin:/usr/local/sbin:/Applications/kitty.app/Contents/MacOS:/opt/twitter_mde/data/node/bin:/Users/tspeak/.npm-global/bin:/opt/twitter_mde/data/node/bin:/Users/tspeak/.npm-global/bin 
[Info  - 15:21:11] Started TSServer
{
  "path": "/Users/tspeak/.config/coc/extensions/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.3.3333",
    "version": "3.3.3333"
  }
}
```

**Describe the bug**
When there is an error or warning from `tsserver` displayed in the gutter, it takes 3-6 seconds of hovering over the error for it to be displayed.

After hovering, it highlights all matching words and will not unhighlight.

If the message cuts off, it does not wrap.

**Screenshots**

Showing a cut off message
![cut off](https://user-images.githubusercontent.com/2415569/54038066-8c4a2200-41b7-11e9-88e1-00c0d00f5347.png)

A gif showing how long it takes for the message to appear
![taking a long time to display](https://user-images.githubusercontent.com/2415569/54038657-f1eade00-41b8-11e9-8ef2-003541b6c040.gif)

Are my settings wrong? Ideally the messages would appear instantly over hover, the highlighting would disappear if I move & the error messages would not be cut off.

Cheers

**Comment by chemzqm** [comment]
Add `set cmdheight=2` to vimrc to prevent press enter, it's fixed on master.

Add `set updatetime=300` to vimrc to make message shown faster, it's improved on master.

**Comment by tomspeak** [comment]
Major, major speed increase, thank you.

Some error messages are even too long for `cmdheight=2`. But they are few and far between!
