### ISSUE TITLE
How to stop annoying prompt?

### ISSUE THREAD

**Issue by zakalla** [neoclide/coc.nvim#4989]
When opening a lua file, a buffer appears showing this:

Do you need to configure your work environment as `luafilesystem`?
(1)Apply and modify settings, (2)Apply but do not modify settings, (3)Don't show again:

It doesn't matter which option you choose because it keeps popping up.

I add it in CocConfig like this:
"Lua": {
     "workspace.checkThirdParty": false
}
But it doesn't work. Please tell me how to fix it. Thank you!

**Comment by fannheyward** [comment]
This prompt is coming from https://github.com/LuaLS/lua-language-server, are you using [coc-sumneko-lua](https://github.com/xiyaowong/coc-sumneko-lua) ? Try "Lua.workspace.checkThirdParty": false`, or `"Lua.workspace.checkThirdParty": "Disable"`
