### ISSUE TITLE
打开rust文件时, coc报错

### ISSUE THREAD

**Issue by persytry** [neoclide/coc.nvim#4998]
CocOpenLog的日志报错如下:
![image](https://github.com/neoclide/coc.nvim/assets/88146305/6a934467-4c27-4761-8a4b-f5c03fbf8c56)
Coc插件如下:
![image](https://github.com/neoclide/coc.nvim/assets/88146305/92b82eb8-4ae0-4850-b339-69db7d914921)
CocInfo的日志如下:
![image](https://github.com/neoclide/coc.nvim/assets/88146305/7f014098-2d41-4cfd-b249-c75e552daf3b)
系统版本:
![image](https://github.com/neoclide/coc.nvim/assets/88146305/ed18195c-257c-4fe7-b5f0-b7f19668c67c)
debian是运行在VMware虚拟机里的:
![image](https://github.com/neoclide/coc.nvim/assets/88146305/d19e8858-1853-43d9-8e12-c0846093af1a)
谢谢

**Comment by fannheyward** [comment]
你的 rust-analyzer 是怎么安装的？通过 coc-rust-analyzer 还是自己安装的？如果是通过 coc-rust-analyzer，请检查

 `~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer --version`

**Comment by persytry** [comment]
谢谢，问题已经解决，原因是存在`~/.cargo/bin/rust-analyzer`，删掉`~/.cargo/bin/rust-analyzer`，让`coc-rust-analyzer`去自己安装`~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer`就好了

**Comment by persytry** [comment]
> 谢谢，问题已经解决，原因是存在`~/.cargo/bin/rust-analyzer`，删掉`~/.cargo/bin/rust-analyzer`，让`coc-rust-analyzer`去自己安装`~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer`就好了

上述解决方法是错误的，正确的方法是用`rustup component add rust-analyzer`安装rust-analyzer， 默认安装到`~/.cargo/bin/rust-analyzer`中，然后可以选择把`~/.config/coc/extensions/coc-rust-analyzer-data/rust-analyzer`删掉
