### ISSUE TITLE
[coc.nvim] Initialize failed, try :UpdateRemotePlugins and restart

### ISSUE THREAD

**Issue by bbtdev** [neoclide/coc.nvim#5]
Tried everything, does want to work: 

**Minimal init.vim**
```
if &compatible
 set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
 call dein#begin('~/.cache/dein')

 call dein#add('~/.cache/dein')
 call dein#add('Shougo/deoplete.nvim')
 if !has('nvim')
   call dein#add('roxma/nvim-yarp')
   call dein#add('roxma/vim-hug-neovim-rpc')
 endif

 call dein#add('neoclide/coc.nvim', {
   \ 'build': 'npm install'
   \})

 call dein#end()
 call dein#save_state()
endif

filetype plugin indent on
syntax enable
```
UpdateRemote
```
remote/host: node host registered plugins ['coc.nvim']
remote/host: python3 host registered plugins ['deoplete']
remote/host: generated rplugin manifest: /Users/bogdan/.local/share/nvim/rplugin.vim
```

**Comment by chemzqm** [comment]
Check out `/Users/bogdan/.local/share/nvim/rplugin.vim`

And run `npm install` at the folder of coc.nvim

**Comment by chemzqm** [comment]
Looks like npm is checking the dependencies strictly, I'm using typescript 3.0 for new features, so looks like I should use typescript 2.8.0 .

**Comment by iamcco** [comment]
I update the neovim nodejs module and UpdateRemotePlugins fix the error

**Comment by chemzqm** [comment]
The reason could be npm build error, it's recommended to use yarn.
Or neovim module is outdated.
I've add a detailed installation documentation at https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim
