### ISSUE TITLE
Hover/docstring information with custom sources

### ISSUE THREAD

**Issue by NoahTheDuke** [neoclide/coc.nvim#5003]
Hey friends,

I have a custom source created with `sources.createSource`. It implements `‎Source.doComplete` to return vim completion items. I'm generating the completion items with doc strings, but there doesn't seem to be a way to display those on hover, like with LanguageSources.

`LanguageSource.onCompleteResolve` calls `provider.resolveCompleteItem` ([here](https://github.com/neoclide/coc.nvim/blob/48bae5f48c274e41637b8d7e4cfede1a0fe15dea/src/completion/source-language.ts#L90)) which transforms the results from the server ([here](https://github.com/neoclide/coc.nvim/blob/48bae5f48c274e41637b8d7e4cfede1a0fe15dea/src/language-client/completion.ts#L136C7-L136C28)) to provide the lsp's fancy `completionItem/resolve` results.

I would like to be able to return similarly fancy results from my custom source, hovering docstrings and function signatures and whatever else. From looking at the code, it seems like it should be possible to just return the results of `Source.onCompleteResolve` instead of discarding them.

Would y'all be interested in a patch to support this?

**Comment by fannheyward** [comment]
Hello, correct me if I misunderstand your request.

You want to get the hover doc from `completionItem` that from your custom source, right? You don't need to use the results of `source.onCompleteResolve`, the resolved informations already added the `item` parameter.

And, how do you want to use the `completionItem` for hover docstring?

**Comment by NoahTheDuke** [comment]
My apologies, the issue was actually coming from the source. It wasn't returning hover info if the functions had no doc strings, which isn't any issue in coc.nvim.

Thanks and sorry!
