### ISSUE TITLE
为什么会代码提示会提示两次？

### ISSUE THREAD

**Issue by SkywardSky** [neoclide/coc.nvim#5004]
请问为什么代码提示两次了。
![image](https://github.com/neoclide/coc.nvim/assets/19143486/bd1f0699-8e6d-4aec-88f0-e7b34c4dd2e1)

环境信息：
![image](https://github.com/neoclide/coc.nvim/assets/19143486/851edd63-7dbc-40d4-9808-940373f71895)

**Comment by fannheyward** [comment]
你重复配置了 gopls，检查 `:CocList services`。

**Comment by SkywardSky** [comment]
![image](https://github.com/neoclide/coc.nvim/assets/19143486/764b6677-8b67-47b1-b942-47190bc382c6)

![image](https://github.com/neoclide/coc.nvim/assets/19143486/bf43feb2-c917-459a-97fa-5ac51e74a0e6)

**Comment by fannheyward** [comment]
你应该是同时也安装了 coc-go，有 coc-go 的时候就不需要再 coc-settings.json 配置。

**Comment by SkywardSky** [comment]
![Uploading image.png…]()
是的，安装了 coc-go
