### ISSUE TITLE
The documentation has incorrect installation instructions for NeoBundle

### ISSUE THREAD

**Issue by mikev9** [neoclide/coc.nvim#5013]
Incorrect(an outdated version will be installed) instructions here: https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#using-neobundle

Which leads to such problems:
https://github.com/fannheyward/coc-pyright/issues/1078

Apparently, for NeoBundle in the vim config, you need to write the following line: `NeoBundle 'neoclide/coc.nvim', {'branch': 'master', 'build': 'npm ci'}`

**Comment by fannheyward** [comment]
Updated
