### ISSUE TITLE
How to remove the highlights when using go references

### ISSUE THREAD

**Issue by Kaiser-Yang** [neoclide/coc.nvim#5015]
I find when I use go references, the window's highlight is under the cursorline which cause it is hard to see.

I wonder how can I let the cursor line under the highlight or how can I remove the highlights.

![image](https://github.com/neoclide/coc.nvim/assets/58209855/17ddec10-bfe6-429c-a392-882796f89c39)

**Comment by fannheyward** [comment]
You can override with custom hi group, check `:h CocList` for the hi groups used.

- `CocListLine` is used for current cursor line
- `CocListSearch` for the matched characters, here's `fill` in your case

**Comment by Kaiser-Yang** [comment]
> You can override with custom hi group, check `:h CocList` for the hi groups used.
> 
> * `CocListLine` is used for current cursor line
> * `CocListSearch` for the matched characters, here's `fill` in your case

Thank you a lot.

**Comment by Kaiser-Yang** [comment]
> You can override with custom hi group, check `:h CocList` for the hi groups used.
> 
> * `CocListLine` is used for current cursor line
> * `CocListSearch` for the matched characters, here's `fill` in your case

I add this below after my `colorscheme`:
```vim
highlight CocListSearch ctermfg=blue ctermbg=237
```
The mached words did not change:
![image](https://github.com/neoclide/coc.nvim/assets/58209855/8da4d478-df92-4012-bb9e-39c9ae5779e1)

And I've found that `list.previewHighlightGroup` in `coc-settings.json` can change the the matched word (`fill` here) in preview window.

I test `CocListLine` can change current line (with `highlight CocListLine ctermfg=blue ctermbg=237)`:
![image](https://github.com/neoclide/coc.nvim/assets/58209855/75fda02f-f68a-4c9a-a4cb-39b5e50c92a3)

Actually, I just want the matched item be blue (`fill` here). Could you just help me more?
