### ISSUE TITLE
ID's for Language Servers

### ISSUE THREAD

**Issue by Maxattax97** [neoclide/coc.nvim#502]
I come from the SpaceVim community, and I really like what coc.nvim brings to the table compared to other language server clients!

However, we've ran into some compatibility problems which we've tried to address in the past with workarounds. These have come up again with some breaking changes, and I was hoping we could figure something out between us.

The problem lies in how language servers are ID'ed. I'll keep this concise and simply [link here](https://github.com/SpaceVim/SpaceVim/pull/2415#issuecomment-471217895) for the rest.

So I guess the first solution that comes to mind is to simply allow a wider set of characters, but perhaps there is a better way. Open to discussion.

**Comment by chemzqm** [comment]
It designed to be configured by use.

**Comment by Maxattax97** [comment]
Thanks for this fix, it's working great now!
