### ISSUE TITLE
coc.nvim takes up two shortcut keys that I prefer to use.

### ISSUE THREAD

**Issue by aszswaz** [neoclide/coc.nvim#5022]
## Result from CocInfo

vim version: NVIM v0.9.5
node version: v18.19.0
coc.nvim version: 0.0.82-2c7e7156

## Describe the bug

I like to use <C-Y> to copy lines and <C-P> to paste text, however coc.nvim takes them and I didn't find a way in `:help coc-config` to not let coc.nvim use them. Now I can only delete coc.nvim to bind them, and then register my own shortcut keys.

## Reproduce the bug

  ```vim
  verbose imap <C-Y>
  verbose imap <C-P>
  ```

I think <C-y> and <C-p> are commonly used shortcut keys. Can you please keep them occupied?

coc.nvim binds <C-y> and <C-p> as 'coc#pum#confirm()', I think it is more appropriate to bind this function to <CR>.

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/blob/c3ae5c3bf4ccf2bbd79405521c63f5ffc151ab8e/plugin/coc.vim#L743-L745

You can set your `<C-Y>` mapping, coc.nvim will only set the mapping if not mapping found on it.
