### ISSUE TITLE
When the preview window is opened, further writing does not refine the results

### ISSUE THREAD

**Issue by Emigre** [neoclide/coc.nvim#503]
_Sorry if this is an expected behaviour. I have the impression that it isn't and have not found a related configuration to modify this or something similar._

**Describe the bug**

Trigger mode is ‘none’. Once the preview window is opened for autocomplete, further writing does not refine the results.

**To Reproduce**

Actual behaviour

* After triggering completion and continue typing, the preview window's results are not updated 
 and filtered, as can be seen in the animated gif below.

* Then, in that same gif, when using backspace to delete characters, the results are updated and filtered as expected.

Expected behaviour

* I would expect that as the user continues to type the word `onerror`, the result list would be filtered until only the only possible match is available, in the same way it does when the user deletes with backspace.

**Screenshots**

![gif showing the issue](https://s2.gifyu.com/images/typing-coc-nvim.gif)

**Comment by chemzqm** [comment]
Please provide result of CocInfo

**Comment by Emigre** [comment]
> Please provide result of CocInfo

I've updated the description with the result of running CocInfo

**Comment by chemzqm** [comment]
@Emigre Should be same issue of #483, it's fixed on master branch.

**Comment by Emigre** [comment]
Hi, thanks for your quick reply. I am testing it on `master` (`cba8062`) and it doesn't seem to be fixed there.

Commenting [this line](https://github.com/neoclide/coc.nvim/blob/afd005eb6a9cef1ab29f9024c4c13f1c325bc359/autoload/coc.vim#L40) as you suggest in #483 fixes the issue. Setting `suggest.reloadPumOnInsertChar` to true or false doesn't seem to have any effect.

Just in case, here is a gif of the behaviour when `call feedkeys("\<Plug>_", 'i')` is commented.

![gif showing the commented-line behaviour](https://s2.gifyu.com/images/01e76f4db4036f5ad2.gif)

The list is updated as the user types. Without that commented line this is what happens:

![gif showing the uncommented, usual behaviour](https://s2.gifyu.com/images/025d6f87b9d8364467.gif)

The list doesn't seem to be updated.

**Comment by chemzqm** [comment]
>  I am testing it on master (cba8062) and it doesn't seem to be fixed there.

It's possible you didn't compile the code by `yarn install`.
If comment that line works, it should works on master.

**Comment by Emigre** [comment]
> > I am testing it on master ([cba8062](https://github.com/neoclide/coc.nvim/commit/cba806245037277e43855747827c1e949061203b)) and it doesn't seem to be fixed there.
> 
> It's possible you didn't compile the code by `yarn install`.
> If comment that line works, it should works on master.

That's right, I had not built - my mistake. 

I can confirm that the issue goes away when building the latest from `master`, although the plugin then throws a number of errors on `insertLeave`:

![first error](https://i.ibb.co/sydjNBJ/error.png)

![another error](https://i.ibb.co/n1GF8Sg/error2.png)

**Comment by chemzqm** [comment]
Please paste result from `:CocInfo`, or messages from `:messages`.

**Comment by Emigre** [comment]
**Result from CocInfo**

```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.58
term: iTerm.app
platform: darwin

## Error messages
UnhandledRejection: diagnostics.map is not a function
TypeError: diagnostics.map is not a function
    at __dirname.refreshBuffer.Object.keys.forEach.key (/snapshot/coc.nvim/lib/diagnostic/manager.js:468:48)
    at Array.forEach (<anonymous>)
    at DiagnosticManager.refreshBuffer (/snapshot/coc.nvim/lib/diagnostic/manager.js:466:36)
    at __dirname.create.collection.onDidDiagnosticsChange (/snapshot/coc.nvim/lib/diagnostic/manager.js:166:18)
    at CallbackList.invoke (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at Collection.set (/snapshot/coc.nvim/lib/diagnostic/collection.js:42:38)
    at DiagnosticsManager.updateCurrentDiagnostics (/Users/gasparrey/.config/coc/extensions/node_modules/coc-tsserver/lib/server/features/diagnostics.js:117:34)
    at Timeout._pendingUpdates.set.setTimeout (/Users/gasparrey/.config/coc/extensions/node_modules/coc-tsserver/lib/server/features/diagnostics.js:101:65)
    at ontimeout (timers.js:475:11)
## Output channel: prettier

## Output channel: watchman
[Info  - 19:10:46] watchman watching project: /Users/gasparrey/code/web/project-name
[Info  - 19:10:46] subscribing "**/{.prettierrc,.prettierrc.json,.prettierrc.yaml,.prettierrc.yml,.prettierrc.js,package.json,prettier.config.js}" in /Users/gasparrey/code/web/project-name
[Info  - 19:10:46] subscribing "**/[tj]sconfig.json" in /Users/gasparrey/code/web/project-name
[Info  - 19:10:46] subscribing "**/package.json" in /Users/gasparrey/code/web/project-name
[Info  - 19:10:46] subscribing "**/*.ts" in /Users/gasparrey/code/web/project-name
[Info  - 19:10:46] subscribing "**/*.js" in /Users/gasparrey/code/web/project-name

## Output channel: tsserver
[Info  - 19:10:46] Forking TSServer
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/go/libexec/bin:/Users/gasparrey/code/go/bin:/Users/gasparrey/.node/bin:/Users/gasparrey/.yarn/bin:/Users/gasparrey/.cargo/bin:/Users/gasparrey/scripts:/usr/local/opt/go/libexec/bin:/Users/gasparrey/code/go/bin:/Users/gasparrey/.node/bin:/Users/gasparrey/.yarn/bin:/Users/gasparrey/.cargo/bin:/Users/gasparrey/scripts 
[Info  - 19:10:46] Started TSServer
{
  "path": "/Users/gasparrey/code/web/project-name/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.3.3",
    "version": "3.3.3"
  }
}
```

**Result from messages**

```
[coc.nvim] Error on InsertLeave: diagnostics.map is not a function
[vim-node-coc]: UnhandledRejection: diagnostics.map is not a function
TypeError: diagnostics.map is not a function
    at __dirname.refreshBuffer.Object.keys.forEach.key (/snapshot/coc.nvim/lib/diagnostic/manager.js:468:48)
    at Array.forEach (<anonymous>)
    at DiagnosticManager.refreshBuffer (/snapshot/coc.nvim/lib/diagnostic/manager.js:466:36)
    at __dirname.create.collection.onDidDiagnosticsChange (/snapshot/coc.nvim/lib/diagnostic/manager.js:166:18)
    at CallbackList.invoke (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at Collection.set (/snapshot/coc.nvim/lib/diagnostic/collection.js:42:38)
    at DiagnosticsManager.updateCurrentDiagnostics (/Users/gasparrey/.config/coc/extensions/node_modules/coc-tsserver/lib/server/featur
es/diagnostics.js:117:34)
    at Timeout._pendingUpdates.set.setTimeout (/Users/gasparrey/.config/coc/extensions/node_modules/coc-tsserver/lib/server/features/di
agnostics.js:101:65)
    at ontimeout (timers.js:475:11)
```

**Comment by chemzqm** [comment]
@Emigre `/snapshot/coc.nvim` means you're still using binary release, you will have issues if you pull code from master and use binary release.

**Comment by Emigre** [comment]
Thank you for that, I didn't know that that was the case.

An error related to `diagnostics.map` seems to remain, though.

**Result from CocInfo**

```
## versions

vim version: NVIM v0.3.4
node version: v11.11.0
coc.nvim version: 0.0.58
term: iTerm.app
platform: darwin

## Error messages

## Output channel: prettier

## Output channel: watchman
[Info  - 7:40:23 PM] watchman watching project: /Users/gasparrey/code/web/project-name
[Info  - 7:40:23 PM] subscribing "**/{.prettierrc,.prettierrc.json,.prettierrc.yaml,.prettierrc.yml,.prettierrc.js,package.json,prettier.config.js}" in /Users/gasparrey/code/web/project-name
[Info  - 7:40:23 PM] subscribing "**/[tj]sconfig.json" in /Users/gasparrey/code/web/project-name
[Info  - 7:40:23 PM] subscribing "**/package.json" in /Users/gasparrey/code/web/project-name
[Info  - 7:40:23 PM] subscribing "**/*.ts" in /Users/gasparrey/code/web/project-name
[Info  - 7:40:23 PM] subscribing "**/*.js" in /Users/gasparrey/code/web/project-name

## Output channel: tsserver
[Info  - 7:40:23 PM] Forking TSServer
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/gasparrey/scripts:/usr/local/opt/go/libexec/bin:/Users/gasparrey/code/go/bin:/Users/gasparrey/.node/bin:/Users/gasparrey/.yarn/bin:/Users/gasparrey/.cargo/bin:/Users/gasparrey/scripts 
[Info  - 7:40:23 PM] Started TSServer
{
  "path": "/Users/gasparrey/code/web/project-name/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.3.3",
    "version": "3.3.3"
  }
}
```

**Result from messages**

```
[coc.nvim] Error on InsertLeave: diagnostics.map is not a function
```

**Comment by chemzqm** [comment]
@Emigre It's a bug related to displayByAle, thanks for report.

**Comment by Emigre** [comment]
> @Emigre It's a bug related to displayByAle, thanks for report.

Thank you very much @chemzqm. coc.nvim is great. Thanks for your work!
