### ISSUE TITLE
Change timeout value of CocTagFunc

### ISSUE THREAD

**Issue by jrmd54** [neoclide/coc.nvim#5049]
**Is your feature request related to a problem? Please describe.**
I work on multiple c++ projects and uses vim with coc and clangd.
I have the following line in my .vimrc:
`
set tagfunc=CocTagFunc
`

However there is one project in which the following issue happens:
- I press <c-]> when on a struct/function declaration
- In some cases, vim becomes unresponsive, and after 60 secs the following error message appears:

[vim.log](https://github.com/user-attachments/files/15900806/vim.log)

The output of CocInfo is:

[CocInfo.log](https://github.com/user-attachments/files/15900801/CocInfo.log)

**Describe the solution you'd like**
Being able to change the timeout of getTagList function.
While it does not solve the root of the problem, it should prevent vim to freeze.
On regular projects <c-]> never takes more than 1sec so being able to do that would already be a great improvement.

**Describe alternatives you've considered**
Is there any additional info i can provide to help pinpoint the root of the issue?

Thank you very much for your insight.

**Comment by fannheyward** [comment]
What's your `coc.preferences.tagDefinitionTimeout` setting? By default it's 0, won't timeout the function.

Check `:h coc-preferences-tagDefinitionTimeout`.

**Comment by jrmd54** [comment]
You are right, adding
`    "coc.preferences.tagDefinitionTimeout": 1000`
to coc-settings.json solves the issue, thank you!
