### ISSUE TITLE
Language keyword completion source

### ISSUE THREAD

**Issue by shyun3** [neoclide/coc.nvim#506]
**Is your feature request related to a problem? Please describe.**
When working in a language without LSP support, it would still be nice to be able to auto-complete commonly used language constructs.

**Describe the solution you'd like**
A completion source that scans the current buffer's file type Vim syntax file for keywords.

**Describe alternatives you've considered**
YouCompleteMe has an option `g:ycm_seed_identifiers_with_syntax` that does what is requested.

**Comment by wbthomason** [comment]
Perhaps an extension to adapt https://github.com/Shougo/neco-syntax, analogous to https://github.com/neoclide/coc-neco?

**Comment by chemzqm** [comment]
I've added coc-syntax to https://github.com/neoclide/coc-sources
