### ISSUE TITLE
Multiple vim tasks invoke mutiple clangd processes with coc-clangd plugin

### ISSUE THREAD

**Issue by Gwan-He** [neoclide/coc.nvim#5065]
Hi, I use vim with coc.nvim and with coc-clangd plugin installed, when I start multiple vim tasks, each vim process seems to invoke one node process and one clangd process, just like below screenshot:
<img width="762" alt="image" src="https://github.com/neoclide/coc.nvim/assets/11644714/72e475d5-4535-44dd-8336-a0727a73aba6">
these processes occupy quit a lot cpu, is there any way to improve such circumstance?

**Comment by fannheyward** [comment]
> each vim process seems to invoke one node process and one clangd process

It's expected, and no sharing way for LSP client.

**Comment by Gwan-He** [comment]
> > each vim process seems to invoke one node process and one clangd process
> 
> It's expected, and no sharing way for LSP client.

If so, is there any way to limit the cpu usage of clangd processes through coc config?
