### ISSUE TITLE
How to close the document window in insert mode？

### ISSUE THREAD

**Issue by Kaiser-Yang** [neoclide/coc.nvim#5066]
I've tried to set this `suggest.enableFloat` to `false` but this only close the preview beside the pum menu.

I want to close the preview window when I'm inserting. For example, I want to disable the window above the `sort`:

![423300eb0ce1878a3068096ce4ad8bd3](https://github.com/neoclide/coc.nvim/assets/58209855/f5c58cb4-f9bb-493b-a615-7793bc435591)

**Comment by fannheyward** [comment]
It's singnatureHelp, check `:h coc-signature`, you can set `signature.target` to `echo` to display it on messages view. Check `:h coc-config-signature` for more.

**Comment by Kaiser-Yang** [comment]
Thanks, that works.
