### ISSUE TITLE
Ignoring `$NVIM_APPNAME` to generate files and directories

### ISSUE THREAD

**Issue by uga-rosa** [neoclide/coc.nvim#5070]
## Describe the bug

In Neovim, `$NVIM_APPNAME` affects rtp, so the results of `stdpath('config')`, etc. also change. The configuration file `~/.config/${NVIM_APPNAME}/init.lua` will be used, and so on.
However, coc.nvim does not seem to take this into account, and `:CocConfig` opens `~/.config/nvim/coc-settings.json`.
Probably all the files and directories that coc.nvim automatically creates, besides `:CocConfig`, do not take `$NVIM_APPNAME` into account as well.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Place mini.vim into `~/.config/test/init.vim`
- Start (neo)vim with command: `NVIM_APPNAME=test nvim`
- `:CocConfig`
- `:echo expand('%')` shows the path of the configration file.

**Comment by fannheyward** [comment]
`coc-settings.json` is located in `stdpath('config')`, other files created by coc.nvim are located in `~/.config/coc`.
