### ISSUE TITLE
Remove ansi escape sequence from code lens

### ISSUE THREAD

**Issue by sevenc-nanashi** [neoclide/coc.nvim#5075]
**Is your feature request related to a problem? Please describe.**
[coc-pretty-ts-errors](https://github.com/hexh250786313/coc-pretty-ts-errors) uses ansi escape for error messages, but ansi escape sequences in these messages are shown in code lens, and it makes difficult to read error messages via code lens:
![image](https://github.com/neoclide/coc.nvim/assets/59691627/23900963-2bf8-45ae-8948-852f5f4e0b82)

**Describe the solution you'd like**
Remove ansi escape sequences.

**Describe alternatives you've considered**
(None)

**Additional context**
(None)

**Comment by fannheyward** [comment]
Hello @hexh250786313 , can you take a look at this? Does the ansi character added by the extension?

**Comment by hexh250786313** [comment]
@fannheyward Yes. Cause I haven't found another good way to highlight the specific inline code in coc markdown parser.

https://github.com/neoclide/coc.nvim/pull/5077 may help.
