### ISSUE TITLE
Open coclist diagnostics in a split pane

### ISSUE THREAD

**Issue by ic-768** [neoclide/coc.nvim#5079]
Right now running `Coclist diagnostics` opens the diagnostics of the project at the very bottom of the window.

It would be helpful if there was an easy way to open it as a separate pane, like in the screenshot, and keep it open there, so as to be able to see all project errors in real-time. 

![coc](https://github.com/neoclide/coc.nvim/assets/83115125/6da4930e-b5d3-4005-add5-46cb9d77c32d)

Manually setting it up like this leads to bugs like not going to the error when pressing <CR> on an item.
It would be great if `<Esc>` didn't quit the list and close the pane.

**Comment by fannheyward** [comment]
Add `--no-quit` to keep the CocList window, `:CocList --no-quit diagnostics`.

**Comment by ic-768** [comment]
> Add `--no-quit` to keep the CocList window, `:CocList --no-quit diagnostics`.

It is very buggy, please try it. If you make it a pane and select an item it breaks stuff like coc-explorer.
It also breaks my window layouts, see all the empty space it created underneath the panes.

![image](https://github.com/neoclide/coc.nvim/assets/83115125/0bf0ec3f-8350-4359-aeac-eb483f913529)

**Comment by fannheyward** [comment]
CocList window doesn't support to split as pane by now, and have no plan to support this.
