### ISSUE TITLE
`"diagnostic.separateRelatedInformationAsDiagnostics"` makes everything of customized typescript LS super lag in the file with lots of diagnostics

### ISSUE THREAD

**Issue by hexh250786313** [neoclide/coc.nvim#5086]
## Result from CocInfo

<details>
<summary>Click to see</summary>

```txt
## versions

vim version: NVIM v0.10.0
node version: v18.20.0
coc.nvim version: 0.0.82-6e1efbf5 2024-07-11 17:12:22 +0800
coc.nvim directory: /home/hexh/workspace/hexh/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2024-07-12T11:44:24.571 INFO (pid:164413) [configurations] - Add folder configuration from file: /home/hexh/workspace/hexh/coc.nvim/.vim/coc-settings.json
2024-07-12T11:44:24.761 INFO (pid:164413) [plugin] - coc.nvim initialized with node: v18.20.0 after 345
2024-07-12T11:44:24.765 INFO (pid:164413) [services] - LanguageClient typescript state change: stopped => starting
2024-07-12T11:44:24.770 INFO (pid:164413) [language-client-index] - Language server "languageserver.typescript" started with 164456
2024-07-12T11:44:24.858 INFO (pid:164413) [services] - LanguageClient typescript state change: starting => running
2024-07-12T11:44:24.869 INFO (pid:164413) [services] - service languageserver.typescript started
2024-07-12T11:44:35.982 INFO (pid:164413) [attach] - Request action: jumpDefinition []
2024-07-12T11:44:38.982 ERROR (pid:164413) [timing] - Request timeout after 3000ms
2024-07-12T11:45:05.163 INFO (pid:164413) [attach] - receive notification: showInfo []
```
</details>

## Describe the bug

`"diagnostic.separateRelatedInformationAsDiagnostics"` makes everything of customized typescript LS super lag in the file with lots of diagnostics.

## Reproduce the bug

```
npm install -g typescript-language-server typescript # or vtsls
git clone https://github.com/hexh250786313/test-coc
cd test-coc
```

Change the following lines to the actual file and directory in `mini.vim`.

```
let g:test_coc_path = '/path/to/test-coc'
set runtimepath^=/path/to/coc.nvim
```

- Start nvim with command: `nvim --clean -u ./mini.vim /path/to/coc.nvim/build/index.js`.
- Wait for the language server to finish initializing.
- Go to line 179 and move cursor to `module2`.
- Press `gr` for `call CocAction('jumpReferences')`.
- Nvim becomes super slow or even freezes.

Then change the `"diagnostic.separateRelatedInformationAsDiagnostics"` back to `0` (false) in `mini.vim`. Everything of the customized typescript LS work fine even though it's not as fast as coc-tsserver.

**Comment by fannheyward** [comment]
In that case, do not enable `separateRelatedInformationAsDiagnostics`.

The LSP defined the `Diagnostic.relatedInformation` only, the client should decide how to display them. coc.nvim provides `separateRelatedInformationAsDiagnostics` and disables it by default. If enable it, coc.nvim will expand the array to diagnostics to use.

In this case, the server returns _lots_ of `relatedInformation`, makes the client slow to work. What can the client do?

1. limit the count of `relatedInformation`, I don't think it's the way, client shouldn't omit any of them
2. improve the displaying performance, depends on vim/nvim, lots of ext marks always cause lagging.

**Comment by hexh250786313** [comment]
@fannheyward Thank you for the detailed explanation.

> The LSP defined the Diagnostic.relatedInformation only, the client should decide how to display them. coc.nvim provides separateRelatedInformationAsDiagnostics and disables it by default.

In that case, I'd suggest providing an additional, better performing way of displaying related info. For example, to modify only the contents of the message without creating additional ext marks, as in this part of the separateDiagnostics code:

https://github.com/neoclide/coc.nvim/blob/33d0a5233cf68e6f54a78e3c3c20958c96f3e4cc/src/language-client/client.ts#L1584-L1590

Or, as in vsc, provide path information:

![image](https://github.com/user-attachments/assets/07983b2b-80e1-49d8-99d9-a79a1e6b47d3)

[coc-pretty-ts-errors](https://github.com/hexh250786313/coc-pretty-ts-errors) achieves a similar effect, but it only works for typescript LS:

![image](https://github.com/user-attachments/assets/f1f641a4-3252-472b-9ff9-96a382d39846)

If it is possible, I will create a related PR for coc.nvim to provide a new option to display this information shortly.

**Comment by fannheyward** [comment]
> modify only the contents of the message without creating additional ext marks

This sounds a better way.
