### ISSUE TITLE
Text edits with the same start position are applied in reverse

### ISSUE THREAD

**Issue by kyoh86** [neoclide/coc.nvim#5087]
## Result from CocInfo

```
## versions

vim version: NVIM v0.11.0-dev-bcb1768
node version: v22.2.0
coc.nvim version: 0.0.82-33d0a523 2024-07-12 09:31:17 +0800
coc.nvim directory: /home/kyoh86/Projects/github.com/kyoh86/dotfiles/nvim-app/i29392/rtp/coc.nvim
term: WezTerm
platform: linux

## Log of coc.nvim

2024-07-15T14:23:28.200 INFO (pid:30949) [plugin] - coc.nvim initialized with node: v22.2.0 after 90
2024-07-15T14:23:28.203 INFO (pid:30949) [services] - LanguageClient efm state change: stopped => starting
2024-07-15T14:23:28.232 INFO (pid:30949) [language-client-index] - Language server "languageserver.efm" started with 30960
2024-07-15T14:23:28.257 INFO (pid:30949) [services] - LanguageClient efm state change: starting => running
2024-07-15T14:23:28.260 INFO (pid:30949) [services] - service languageserver.efm started
```

## Describe the bug

Text edits returned from the LSP that have the same start position are being applied in reverse.
According to the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEditArray), text edits with the same start position should be applied in the order received.

Recently, the language server client included with Neovim has fixed this bug (https://github.com/neovim/neovim/issues/29202)

Accordingly, using some servers (e.g. [efm-langserver](https://github.com/mattn/efm-langserver)) with the client included with Neovim, the formatted lines of the result may be reversed.
So I tried to ask the server to fix it (https://github.com/mattn/efm-langserver/issues/281), but the fix causes problems with other (non-specified) clients such as coc.nvim.
Therefore, I would like you to implement a fix in coc.nvim that follows the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEditArray), as well as Neovim.

## Reproduce the bug

1. Install efm-langserver with patch to follow the LSP spec.

```console
$ git clone --branch fix-281 https://github.com/kyoh86/efm-langserver.git
$ cd efm-langserver
$ go install .
```

2. Install the coc.nvim

```console
$ git clone https://github.com/neoclide/coc.nvim.git --branch release ~/.config/nvim-app/i29392/rtp/coc.nvim
```

3. Configure the Neovim

~/.config/nvim-app/i29392/init.vim

```vim
set rtp+=~/.config/nvim-app/i29392/rtp/coc.nvim
```

4. Configure the coc.nvim

~/.config/nvim-app/i29392/coc-settings.json

```json
{
  "coc.preferences.formatOnSave": true,
  "html.filetypes": ["html"],
  "html.format.templating": true,
  "languageserver": {
    "efm": {
      "command": "efm-langserver",
      "args": [],
      "filetypes": ["html"]
    }
  }
}
```

5. Configure the efm-langserver

~/.config/efm-langserver/config.toml

```
version: 2

tools:
  echo-fix: &echo-fix
    format-command: zsh -c 'print "foo\nbar\nbaz"'
    format-stdin: true

languages:
  html:
    - <<: *echo-fix
```

6. Set the envar

```console
$ export PATH="$(go env GOPATH)/bin:$PATH"
$ export NVIM_APPNAME=nvim-app/i29392
```

7. Open Neovim

```console
$ nvim foo.html
```

9. Call `:w`

Expected result: 

```
foo
bar
baz
```

But actual result:

```
baz
bar
foo
```

If you install the efm-langserver without the patch, this doesn't happen.

**Comment by kyoh86** [comment]
I'm having quite a bit of trouble, can anyone at least give me the maintainer's opinion?

**Comment by fannheyward** [comment]
coc.nvim follows the spec, but the `applyEdits` function follows how VSCode does. VSCode becomes the de-facto implementation and the servers responded in order, the client shouldn't do re-ordering. This change will break all servers.

**Comment by kyoh86** [comment]
Now the coc.nvim client may do re-ordering.

**Comment by kyoh86** [comment]
It has fixed in Neovim, thanks.
