### ISSUE TITLE
Why does it not work to use <c-space> to refresh in vim?

### ISSUE THREAD

**Issue by Staten-Wang** [neoclide/coc.nvim#5092]
Why does it not work to use <c-space> to refresh in vim? Of course, you suggest using <c-@>. However, it seems that <c-space> is a shortcut key that will not be responded to in vim.

I am a new user of vim, so I don't understand something. Is it because vim has a limitation on <c-space>?

I don't know if it's the right place to ask this question here, but it would be great if someone could answer it.

**Comment by fannheyward** [comment]
Your terminal didn't send that key codes to vim, it's not coc.nvim or vim's issue.
