### ISSUE TITLE
[Feature Request] Call custom function when navigating the CocList

### ISSUE THREAD

**Issue by MahdiNazemi** [neoclide/coc.nvim#5093]
I use [context.vim](https://github.com/wellle/context.vim) to show some context (class name, function name, loop information, etc.) at the top of the buffer. When using `coc-references` and navigating the results opened in the lower split, the context on the upper split does not get updated.

To solve this issue, I assume I should `call context#update('BufEnter')` (or one of the other triggers mentioned [here](https://github.com/wellle/context.vim?tab=readme-ov-file#auto-commands)) on the upper split where the actual file contents are shown. It would be nice to have some trigger I can use in an `autocmd` to know a new item in the lower split is selected and call the said function in the upper split.

Ideally, this should work with <kbd>j</kbd>, <kbd>k</kbd>, arrow keys, `CocNext`, and all other keys or mappings used to navigate the list.

The requested feature may exist already, but I was not able to find it.

**Comment by fannheyward** [comment]
Something like `CocListMoved` autocmd is enough for this case?

**Comment by niexin-dev** [comment]
> Yes, it should be.

Can you please refer to your autocmd? Mine will give an error.

**Comment by fannheyward** [comment]
The release branch has been updated with this event.
