### ISSUE TITLE
what is `menu` in `suggest.formatItems` ?

### ISSUE THREAD

**Issue by xinghe98** [neoclide/coc.nvim#5094]
what is `menu` option in `suggest.formatItems` ?
I don't notice any difference whether I set the menu or not, what's going on?
![image](https://github.com/user-attachments/assets/7e9317fa-c846-4898-ac8f-11b17d97b2d8)
![image](https://github.com/user-attachments/assets/86e4bb7c-4daf-42b7-b680-6bf41806e366)

If it needs to be set up separately, I didn't find the relevant content in the config documentation or wiki.

**Comment by fannheyward** [comment]
The completion source can set `menu` value, and coc.nvim display it in the pum window. From your screenshot, the JSON server didn't provide this.
