### ISSUE TITLE
New command named CocStop

### ISSUE THREAD

**Issue by amgodoi** [neoclide/coc.nvim#5096]
Is it possible to create a command named CocStop?

This command should be the opposite of CocStart.

I think this command may be helpful with various instances of vim. Using coc-java is "only possible" with one server enabled at the same time. Then, to choose between instances CocStop/CocStart could be helpful.

**Comment by fannheyward** [comment]
Use `:call coc#rpc#stop()`.

**Comment by amgodoi** [comment]
I did know that.

Worked!

Thanks a lot!

**Comment by amgodoi** [comment]
Just one more question.

![image](https://github.com/user-attachments/assets/787e1fb1-13ac-4ef6-aa4b-83b81d35fdbb)

Is there any way to remove this signs before/after Coc stopped?

**Comment by fannheyward** [comment]
Does `:e` work?

**Comment by amgodoi** [comment]
Worked partially.

![image](https://github.com/user-attachments/assets/900a157e-465d-4321-85fd-24217e63d4ed)

The sign column keeps it yet.
