### ISSUE TITLE
Unhandled Rejection Error: "Can't find directory 'list:' in cdpath" when Using :CocList Commands

### ISSUE THREAD

**Issue by talia523** [neoclide/coc.nvim#5099]
## Describe the bug

When using `coc.nvim` to execute list-related commands such as `:CocList references`, an error is thrown indicating "Can't find directory 'list:' in cdpath on api call_function". This error occurs consistently across different list-related commands and seems to involve a misinterpretation of parameters or an incorrect API call.

## Reproduce the bug

- Create a file `mini.vim` with:

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
![JT%L6@UM4X(_6Q7)LTA 81M](https://github.com/user-attachments/assets/dd0258c2-b795-4843-87c7-791a3923367b)

![ST2_J G7{N{{N@ECLMYL%1J](https://github.com/user-attachments/assets/d25a5ec4-e821-4978-9c68-1727f2f3df22)

**Comment by fannheyward** [comment]
`:CocInfo` please, and steps to reproduce this issue.

**Comment by talia523** [comment]
I'm encountering an new issue with coc.nvim where the :CocInfo command fails with the error Error on notification "showInfo": Vim(loadview):E32: No file name on api "command" ["vnew setl\ buftype=nofile\ bufhidden=wipe\ nobuflisted"], preventing me from accessing plugin logs and status. This issue persists across different files and buffer states, and I am looking for a solution or further debugging assistance.
![image](https://github.com/user-attachments/assets/ee539828-947a-4734-b302-f83e62613e33)

**Comment by fannheyward** [comment]
What's your vim version?

**Comment by talia523** [comment]
vim9.1

**Comment by fannheyward** [comment]
Have no idea about this, cant' reproduce. Try upgrade your coc.nvim, use the latest release.
