### ISSUE TITLE
coc-codeaction-selected throws cannot cannot destructure property `line` of `undefined` or `null`

### ISSUE THREAD

**Issue by JamesApple** [neoclide/coc.nvim#51]
**Describe the bug**
`<Plug>(coc-codeaction-selected)` results in vim trying to reload the file immediately afterwards as well as throwing an error.

**To Reproduce**
1. Create `myfile.js`
2. Add these contents
```
function myFunction(x) {
  const a = 1
  return x + a
}
```
3. Visual select line 2 and run `<Plug>(coc-codeaction-selected)` through the provided binding.
4. Select any combination of the next results (1 -> 1 -> <cr> for this example) 
5. Results in an error (see below) and *vim trying to reload the file* from the state before while only changing the current buffer to:
```
function myFunction(x) {
  const a = newFunction()
  return x + a

        function newFunction() {
                return 1;
        }
}
```

And throws [coc.nvim] Command error: cannot destructure property `line` of `undefined` or `null`

**Expected behavior**
Would hope for no error and vim not try and reload the file from system. Ideally refactoring tools would be able to select a name instead of defaulting to `newFunction`. Would also be cool if the scope was more than constant_scope_1 and the refactoring was placed on the correct level of indentation

**Screenshots**
<img width="703" alt="screen shot 2018-08-16 at 9 20 24 pm" src="https://user-images.githubusercontent.com/12153188/44205593-3b7ec780-a19a-11e8-965d-29b7950aacbe.png">

**Desktop (please complete the following information):**
 - latest iTerm2, Neovim, all green in checkhealth
 - Version: v0.0.10

**Additional context**
Attempted in home directory, and in a project directory as well.

**Comment by chemzqm** [comment]
I have the same error message, but the reload seems not to be triggered by coc, something else may changed that file.

**Comment by JamesApple** [comment]
I'll add that I usually keep `set autoread` on to minimize issues with git but even with autoread off, navigating out of the buffer then back into the buffer (using dirvish or any buffer command) wants to reload the file. I assume it's because the refactor is applied directly to the instead of the buffer?

**Comment by chemzqm** [comment]
The refactor should change the buffer instead of file when the buffer is loaded.
I can see the file get changed, there's something wrong.
