### ISSUE TITLE
Haxe support 

### ISSUE THREAD

**Issue by vushu** [neoclide/coc.nvim#510]
**Result from CocInfo**
```
## versions
vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.59
term: xterm-kitty
platform: linux

## Error messages

## Output channel: languageserver.haxe
[Error  - 23:43:02] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601 
[Error  - 23:43:03] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601 
```

**Describe the bug**
Language server doesn't work with coc, I think I need to set it up probably, but not sure how to

**To Reproduce**
download visual code install haxe support

install coc.nvim
add to CocConfig
```

{
  "languageserver": {
      "haxe": {
      "command": "node",
      "args": ["$HOME/.vscode/extensions/nadako.vshaxe-2.7.0/server/bin/server.js"],
      "filetypes": ["haxe"],
      "trace.server": "verbose",
      "initializationOptions": {
        "cacheDirectory": "/tmp/haxelog"
      }
    }
  }
}
```

**Comment by chemzqm** [comment]
Could you paste full content from output channel of language server?
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by vushu** [comment]
here you go :)
[output_channel.txt](https://github.com/neoclide/coc.nvim/files/2954614/output_channel.txt)

**Comment by chemzqm** [comment]
Should be problem of language server, it doesn't response to completion request.
I can't do nothing for it.
