### ISSUE TITLE
CocActionAsync('format') for python file

### ISSUE THREAD

**Issue by maxchou0205** [neoclide/coc.nvim#5103]
Hello, Everyone, 

when i call **CocActionAsync('format')** for **python** file, the following message always popup (even the formation will be completed). 
is there any way to avoid such message since it seems to me a kind of bug...??
Thank you very much...
![image](https://github.com/user-attachments/assets/9813acf5-1f84-41bf-ae52-ad29b2dd5cd6)

**Comment by fannheyward** [comment]
You're using coc-python which was broken and ended of support. You can use other Python extensions like coc-pyright or coc-ruff.

**Comment by maxchou0205** [comment]
Hi fannheyward, thank you so much... yes, i will... thanks.

**Comment by maxchou0205** [comment]
yes, it works just fine... thank you so much. 
![image](https://github.com/user-attachments/assets/dff61761-9f37-4ab6-aed0-d3b5fb7fa10f)

**Comment by maxchou0205** [comment]
Hi fannheyward, i try to apply the format on save... but it did not work. could you please enlighten a bit??
thank you very much... 
![image](https://github.com/user-attachments/assets/3d1f29f1-3a60-4448-a861-5e1132d1990c)

**Comment by maxchou0205** [comment]
Hi fannheyward, i put the following mapping into the .vimrc and it works...
nnoremap <silent><nowait> <F3> :call CocAction('format')<cr>:w<cr>
thank you so much...

**Comment by Lmills71** [comment]
Thank you.


Sent from Yahoo Mail for iPhone


On Saturday, August 3, 2024, 12:16 AM, maxchou0205 ***@***.***> wrote:




Hi fannheyward, thank you so much... yes, i will... thanks.
