### ISSUE TITLE
No highlight for code blocks in floating documentation 

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#511]
Currently floating documentation has a different background color and incorrect highlighting. This breaks markdown code block syntax highlighting.

**Comment by chemzqm** [comment]
>  floating documentation has a different background color

You can change the highlights used by float window, it should be different since we don't have border support for float window.

**Comment by chemzqm** [comment]
I don't prefer to use code blocks in the documentation since it takes more lines.
Will have a try with tree-sister for highlight codes, hope neovim could provide api for code highlights.

**Comment by Avi-D-coder** [comment]
![Screenshot_20190311_204133](https://user-images.githubusercontent.com/29133776/54166995-26230080-443e-11e9-8a3d-094aa6dcd9db.png)

This does not seem like a good default setting.

**Comment by Avi-D-coder** [comment]
For comparison
![Screenshot_20190311_204619](https://user-images.githubusercontent.com/29133776/54167162-c416cb00-443e-11e9-8d9c-f31df3030291.png)

**Comment by chemzqm** [comment]
It use `Pmenu` by default because it at least provide color contrast, you can overwrite `CocFloating` higlight group.

**Comment by Avi-D-coder** [comment]
`hi link CocFloating markdown` works

**Comment by Avi-D-coder** [comment]
@chemzqm Do you know if floating window will get border support?

**Comment by chemzqm** [comment]
I've requrested for it before, you can create a feature request issue on neovim.

**Comment by Avi-D-coder** [comment]
will do

**Comment by Avi-D-coder** [comment]
https://github.com/neovim/neovim/issues/9718

**Comment by Avi-D-coder** [comment]
@bew I use neovim with the following in my vimrc. I think vim also supports it.
```vim
let g:markdown_fenced_languages = ['html', 'vim', 'ruby', 'python', 'bash=sh', 'rust', 'haskell', 'c', 'cpp']
```

**Comment by Avi-D-coder** [comment]
@chemzqm `hi! link CocPumFloatingDetail markdown`and `hi! link CocPumFloating markdown` don't work?

**Comment by chemzqm** [comment]
`CocPumFloatingDetail` contains detail of CompleteItem, it's not markdown.

**Comment by chemzqm** [comment]
Also the floating preview window of pum doesn't have filetype markdown, so your link could not work.

**Comment by Avi-D-coder** [comment]
My mistake with detail, but the [LSP spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion) says `documentation?: string | MarkupContent;` so in this case shouldn't the file type be markdown.

**Comment by chemzqm** [comment]
`detail` is not `documentation`, it's just string, but possbile valid code of current filetype that can be highlighted.

I'll remove `CocPumFloatingDetail `, `b:coc_detail_filetype` can be used to indicate filetype used for highlight detail.

**Comment by Avi-D-coder** [comment]
What I am referring to is:
`documentation`:
![Screenshot_20190313_025743](https://user-images.githubusercontent.com/29133776/54259406-02de7b00-453c-11e9-93b1-d90fb99a0795.png)
not `detail`:
![Screenshot_20190313_025821](https://user-images.githubusercontent.com/29133776/54259412-05d96b80-453c-11e9-8b7e-4ec0db2e844c.png)

I am trying to get the first image to be highlighted as markdown.

**Comment by chemzqm** [comment]
I'm going to rework the highlight for floating windows, don't worry.

**Comment by Avi-D-coder** [comment]
@chemzqm Thank you.

**Comment by chemzqm** [comment]
<img width="850" alt="Screen Shot 2019-03-14 at 3 20 12 PM" src="https://user-images.githubusercontent.com/251450/54338380-b2b30600-466c-11e9-8854-84a1b5f54e07.png">
Highlight code blocksj ust works without configurations.

**Comment by AlanWarren** [comment]
Hey guys,  this is what I'm getting with solargraph in the latest commit.  
![Screen Shot 2019-03-19 at 2 28 12 PM](https://user-images.githubusercontent.com/294606/54642256-29337780-4a62-11e9-8f1a-e4a84ac3df9c.png)

Is there anyway to modify ths?  It looks like the documentation popup is getting the ruby filetype's highlighting, instead of being processed as markdown.   

Thanks!

**Comment by rlisowski** [comment]
@AlanWarren I have the same issue, and I think it's because of https://github.com/neoclide/coc.nvim/blob/master/src/languages.ts#L536

```typescript
if (documentation) {
  if (typeof documentation == 'string') {
    let isText = /^[\w-\s.,\t]+$/.test(documentation)
    docs.push({
      filetype: isText ? 'txt' : doc.filetype,
      content: documentation
    })
  } else {
    docs.push({
      filetype: documentation.kind == 'markdown' ? 'markdown' : 'txt',
      content: documentation.value
    })
  }
}
```

Solargraph provides docs as a plain string so coc fallback to document (buffer) filetype.
It looks like it's not configurable.

```
[Trace - 01:50:56] Received response 'completionItem/resolve - (8)' in 94ms.
Result: {
    "label": "ljust",
    "kind": 2,
    "detail": "(*args) => String",
    "data": {
        "path": "String#ljust",
        "return_type": "String",
        "location": null,
        "deprecated": false,
        "uri": "file:///Users/rlisowski/workspace/packhelp/creator/app/jobs/zpkj/segment_mailer/custom_order_notifier_job.rb"
    },
    "textEdit": {
        "range": {
            "start": {
                "line": 32,
                "character": 3
            },
            "end": {
                "line": 32,
                "character": 7
            }
        },
        "newText": "ljust"
    },
    "sortText": "0000ljust",
    "documentation": "[String#ljust](solargraph:/document?query=String%23ljust)\n\nIf _integer_ is greater than the length of _str_, returns a new\n`String` of length _integer_ with _str_ left justified\nand padded with _padstr_; otherwise, returns _str_.\n\n```\n\"hello\".ljust(4) #=> \"hello\"\n\"hello\".ljust(20) #=> \"hello \"\n\"hello\".ljust(20, '1234') #=> \"hello123412341234123\"\n```"
}
```

So I see two options here. Force coc to fallback to markdown or update solargraph to provide an object with filetype property.

**Comment by Avi-D-coder** [comment]
As far as I can tell Solargraph is in error here. Since it's sending plain text with markdown backticks code blocks. It should be sending markdown.

Floating highlights can be disabled in config for now.

**Comment by lorenzo** [comment]
I'm unable to get syntax highlighting to work in the floating window, Is there any extra configuration I need to set up? This is how it looks like for me:

![Screenshot 2019-04-05 at 11 18 22](https://user-images.githubusercontent.com/37621/55617541-a1a17480-5794-11e9-9025-945af3cdd553.png)

**Comment by chemzqm** [comment]
@lorenzo which language server are you using?

**Comment by lorenzo** [comment]
I'm using the `coc-python` extension, but I can replicate the problem with the Haskell (hie) and go (bingo) language servers.

**Comment by chemzqm** [comment]
@lorenzo try upgrade to master code.

**Comment by lorenzo** [comment]
@chemzqm I did it before commenting in this ticket

**Comment by lorenzo** [comment]
Updated to master one more time just to make sure, still the same behaviour

**Comment by esn89** [comment]
@lorenzo  I am experiencing the same problem with you.  Although I see the floating window, the microsoft python language server has bad word wrap and no syntax highlighting.

**Comment by AlanWarren** [comment]
> Updated to master one more time just to make sure, still the same behaviour

Just to confirm, does vim properly highlight python inside of a normal markdown file?  You should be able to copy + paste the documentation snippet from the language server's trace log, and save it as an .md file to test.

**Comment by chemzqm** [comment]
The documentation from MPLS is not markdown, so no highlight for now.

**Comment by lorenzo** [comment]
I discovered that this has to do with the light colorscheme, if I switch to dark it highlights properly. Is this a problem with the highlight group being applied?

**Comment by esn89** [comment]
Aww what, seriously?  Do you have screenshots of what it is supposed to look like?  Btw, which language server are you using?  Pyls palantir or the microsoft one, @lorenzo

**Comment by lorenzo** [comment]
@esn89 I'm using the one from microsoft

@chemzqm Should I open a new ticket about the syntax highlighting when using a light colorscheme?

**Comment by chemzqm** [comment]
It's not problem of light colorscheme, it's problem of CocFloat highlight, it would not look good when it use high constract color of default background.

**Comment by chemzqm** [comment]
Change CocFloat to similar colors of your default background would fix it.

**Comment by lorenzo** [comment]
@chemzqm could you please point me at some docs on what I can change? I'm not familiar with that

**Comment by chemzqm** [comment]
`:h coc-highlights`

**Comment by HerringtonDarkholme** [comment]
The reverse color problem in floating window is caused by Solarized indeed. 
Solarized set front color to reverse in Pmenu.
```
Pmenu          xxx cterm=reverse ctermfg=11 ctermbg=7 guibg=LightMagenta
```
Change it to 

`hi CocFloating ctermbg=8` 

should fix it.
