### ISSUE TITLE
Example configuration prevents typing of tab character in insert mode

### ISSUE THREAD

**Issue by Tarinaky** [neoclide/coc.nvim#5113]
**Is your feature request related to a problem? Please describe.**
The example configuration appears to prevent the typing of the tab character in insert mode, even if autocomplete suggestions are not displayed the tab key will not do anything.

**Describe the solution you'd like**
If completions are open, tab should cycle between them, if the completions window is not open, then a tab character should be typed.

**Describe alternatives you've considered**
N/A

**Additional context**
The message "Unknown Function CheckBackspace" appears, if I comment that line out however I still don't get tab characters.

**Comment by fannheyward** [comment]
> Unknown Function CheckBackspace

Your configuration was incomplete, please check `:h coc-completion-example` to add the `CheckBackspace` function. https://github.com/neoclide/coc.nvim/blob/aabfc231c195139714d18c5b245378cd49dc73ea/doc/coc-example-config.vim#L34
