### ISSUE TITLE
Extra opening angle bracket when auto completing html.

### ISSUE THREAD

**Issue by pkradiator** [neoclide/coc.nvim#5119]
## versions

vim version: VIM - Vi IMproved 9.1 9010000
node version: v20.16.0
coc.nvim version: 0.0.82-c5ffbb3c 2024-08-01 17:40:42 +0800
coc.nvim directory: /Users/macpc/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2024-08-20T16:05:50.762 INFO (pid:80868) [plugin] - coc.nvim initialized with node: v20.16.0 after 180
2024-08-20T16:05:50.769 INFO (pid:80868) [language-client-index] - Language server "html" started with 80871

## Describe the bug

When you try to complete html tags (coc-html) using tab and then enter you get an extra opening bracket.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
inoremap <silent><expr> <TAB> coc#pum#visible() ? coc#pum#next(1) : "\<TAB>"
inoremap <silent><expr> <S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<S-TAB>"
  ```
- Add the following to CocConfig
  ```
  {
    "suggest.noselect": true
  }
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Type <ht and suggestions will popup.
- Hit tab to select first completion which will turn <ht into <html
- Hit Enter and you will get complete completion but with an extra opening angle bracket as shown in screenshots below.

## Screenshots (optional)

https://github.com/user-attachments/assets/6c2acc9b-d31c-4c4e-ab4e-514c72fe4249

P.S - If you add this to your vimrc or mini.vim 
  ```
  " Make <CR> to accept selected completion item or notify coc.nvim to format
  " <C-g>u breaks current undo, please make your own choice
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
  ```
You will not get complete completion after hitting enter. That is completion will stay till the point you hit tab ,i.e., <html

**Comment by fannheyward** [comment]
> Hit Enter and you will get complete completion but with an extra opening angle bracket as shown in screenshots below.

In my test, I can only get `<html` after Enter, do you have any another snippet plugin?

**Comment by pkradiator** [comment]
> Mostly you've another plugin maps your `<CR>`, check `:verbose imap <cr>`

Just checked and you are right <CR> was mapped to ultisnip's completion. This solves the issue and my behaviour is exactly similar as yours. But is there a way to get that style of completion. Like after <html , I hit enter and

```
<html>
  |  // Cursor here
</html>
```

**Comment by fannheyward** [comment]
The HTML language server didn't provide that completion.
