### ISSUE TITLE
Coc reopens folds after opening buffer with vim-lastplace

### ISSUE THREAD

**Issue by comfortablynick** [neoclide/coc.nvim#513]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
```
## versions

vim version: NVIM v0.4.0-370-gc0a29c365
node version: v10.15.0
coc.nvim version: 0.0.59
term: screen-256color
platform: linux

## Error messages
```
**Describe the bug**
I have used [vim-lastplace](https://github.com/farmergreg/vim-lastplace) for some time, to automatically return to the same spot in the buffer when re-opening in Vim. When `let g:lastplace_open_folds = 1`, the plugin also opens any folds to display where the cursor is. 

coc.nvim closes the folds about 0.5 sec after opening the buffer.

**To Reproduce**

1. Open a vim buffer with many nested folds (with vim-lastplace and coc.nvim loaded)

Note: it doesn't seem to do it with *every* file, but it's never happened before installing coc.nvim.

**Screenshots**

Here is a recording: [![asciicast](https://asciinema.org/a/y3DTtDXC2UavDtim4D8tQ2MFC.svg)](https://asciinema.org/a/y3DTtDXC2UavDtim4D8tQ2MFC)

**Comment by chemzqm** [comment]
The problem happens on trigger user autocmd, I've made it not trigger when possible.
