### ISSUE TITLE
Some characters cannot be deleted with <C-w> in CocList

### ISSUE THREAD

**Issue by statiolake** [neoclide/coc.nvim#5134]
## Result from CocInfo

```
## versions

vim version: NVIM v0.10.1
node version: v18.17.1
coc.nvim version: 0.0.82-aabfc231 2024-08-26 07:41:08 +0100
coc.nvim directory: /home/(user)/.local/share/nvim/lazy/coc.nvim
term: tmux
platform: linux
```

## Describe the bug

Some characters (CJK characters and whitespaces) cannot be deleted with `<C-w>` in CocList.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Open some list by e.g. `:CocList files`
- Press `<Space>` key (or put CJK characters like `あ`)
- Pressing `<C-w>` does not delete the character. `<BS>` normally works.

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/blob/b3bcdcbfb3448e998305f5e3c97425e2f9816d88/src/list/prompt.ts#L170

Maybe this regex related.

**Comment by fannheyward** [comment]
@statiolake please give this regex a try

```
pre.replace(/[\w$\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]+([^\w$\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]+)?$/u, '')
```

**Comment by statiolake** [comment]
@fannheyward Thanks! Sorry for the late reply.

I tried current master branch and confirmed that it actually removes CJK characters. But now the entire text including the whitespace is removed, e.g. `Hello world<C-w>` removes entire `Hello world`.

I tried the regex of your last comment and it works just fine.

> @statiolake please give this regex a try
> 
> ```
> pre.replace(/[\w$\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]+([^\w$\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]+)?$/u, '')
> ```

It seems this is because the final commit contains extra `\s` compared to your last comment. Are there any reason to have `\s`?

https://github.com/neoclide/coc.nvim/blob/640544d52afa211fd162590b1bbc7d65bed2813a/src/list/prompt.ts#L170

**Comment by fannheyward** [comment]
> Press <Space> key

As in your step I added `\s` to include the space.

Can you make a PR to remove it?

**Comment by statiolake** [comment]
> As in your step I added \s to include the space.

Oh, I got it. As you say, the commented regex does not remove the initial spaces. Thanks for pointing this out.

So, all things considered, we can achieve the desired result like this:

1. pre.trimEnd() to remove last whitespaces, and then
2. remove the last word with this simplified regex: `/[\w$\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]+$/u`

I'll open a PR soon.
