### ISSUE TITLE
Organize Imports feature sort order disagrees with eslint

### ISSUE THREAD

**Issue by nullromo** [neoclide/coc.nvim#5136]
## Result from CocInfo

<details>

```
## versions

vim version: NVIM v0.11.0-dev
node version: v18.7.0
coc.nvim version: 0.0.82-33d0a523 2024-07-12 09:31:17 +0800
coc.nvim directory: /home/kkovacs/.local/share/nvim/lazy/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2024-09-03T15:34:57.911 INFO (pid:29163) [extension:coc-git] - Looking for git in: git
2024-09-03T15:34:58.154 INFO (pid:29163) [plugin] - coc.nvim initialized with node: v18.7.0 after 429
2024-09-03T15:34:58.155 INFO (pid:29163) [services] - LanguageClient ESLint state change: stopped => starting
2024-09-03T15:34:58.157 INFO (pid:29163) [attach] - receive notification: highlight []
2024-09-03T15:34:58.179 INFO (pid:29163) [services] - service tsserver started
2024-09-03T15:34:58.190 INFO (pid:29163) [language-client-index] - Language server "eslint" started with 29190
2024-09-03T15:34:58.276 INFO (pid:29163) [core-watchman] - watchman watching project: /home/kkovacs/oss_97542
2024-09-03T15:34:58.308 INFO (pid:29163) [services] - LanguageClient ESLint state change: starting => running
2024-09-03T15:34:58.313 INFO (pid:29163) [services] - service eslint started
2024-09-03T15:35:00.558 INFO (pid:29163) [attach] - receive notification: showInfo []
2024-09-03T15:35:00.672 INFO (pid:29163) [attach] - receive notification: highlight []
2024-09-03T15:35:02.658 INFO (pid:29163) [attach] - receive notification: highlight []
2024-09-03T15:35:05.244 INFO (pid:29163) [attach] - receive notification: showInfo []
```

</details>

## Describe the bug

When using `editor.action.organizeImport`, the result does not follow the expected result from eslint. Is there any way to customize the import sort order?

## Reproduce the bug

1. Use this in nvim setup:

```lua
-- add command for organizing imports
vim.api.nvim_create_user_command(
    'OrganizeImports',
    ":call CocAction('runCommand', 'editor.action.organizeImport')",
    { bang = true, nargs = 0, desc = 'CoC organize imports' }
)
```

2. Create the file:

```typescript
import net from 'net';
import chalk from 'chalk';

net.createServer();
console.log(chalk.red('a'));
```

3. Enable the [eslint rule](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md)

```json
"import/order": [
    "error",
    { "groups": ["builtin", "external", "parent", "sibling", "index"] }
],
```

4. There are no eslint errors in the file. Now run `:OrganizeImports`. The file will change to

```typescript
import chalk from 'chalk';
import net from 'net';

net.createServer();
console.log(chalk.red('a'));
```

5. Now there is an eslint error on line 2: `'net' import should occur before import of 'chalk' (eslint import/order)`

## Screenshots (optional)

Video demo

https://github.com/user-attachments/assets/cf3df8e9-7a11-4e0e-a726-056d50cab5b9

**Comment by nullromo** [comment]
Just a note: the command

```
:exec "!npx eslint --no-eslintrc --parser @typescript-eslint/parser --plugin import --fix --rule '\"import/order\": [ \"error\", { \"groups\": [\"builtin\", \"external\", \"parent\", \"sibling\", \"index\"] } ]' %"
```

can fix the problem after the imports are messed up.

**Comment by fannheyward** [comment]
Reproduced. The problem of this issue: tsserver provides code action of `source.organizeImports` to sort order, but the order didn't follows the rule you set with eslint.

The organize imports steps:

1. server provides code actions, like error fix/sort imports/refactor etc
2. coc.nvim command filters all code actions with kind `source.organizeImports`, in this case, tsserver provides an action with kind `source.organizeImports`, but eslint not, because the order is correct in eslint side
3. apply the action from tsserver

To fix this, we need tsserver follows the rule of eslint, I don't it's possible.

**Comment by nullromo** [comment]
Ok, so the actual implementation of `source.organizeImports` is in `tsserver`. Good to know. Is [this](https://github.com/typescript-language-server/typescript-language-server) the repo for tsserver? Maybe I can open an issue there to see if it's possible to apply the eslint sort order to the `source.organizeImports` action.

**Comment by nullromo** [comment]
Oh, I think [this](https://github.com/microsoft/TypeScript/blob/31afb988d1c6857ce4d1ab3b2558385e68a565a8/src/services/organizeImports.ts#L76) is actually the source code that actually does the organizing of the imports.

**Comment by nullromo** [comment]
@fannheyward I got this comment from @RyanCavanaugh 

https://github.com/microsoft/TypeScript/issues/59883#issuecomment-2334820208

Is there a way that CoC could use the eslint organize imports instead of the tsserver organize imports?

**Comment by fannheyward** [comment]
> in this case, tsserver provides an action with kind source.organizeImports, but eslint not, because the order is correct in eslint side

As I said, eslint didn't provide code action as the order was correct.

**Comment by fannheyward** [comment]
> execute them both in order

coc.nvim already supports this.

**Comment by nullromo** [comment]
> coc.nvim already supports this

That's great! Could you please provide an example of how to set this up?

This is what my config looks like right now.

```lua
-- add command for organizing imports
vim.api.nvim_create_user_command('OrganizeImports', function()
    vim.cmd(
        "call CocAction('runCommand', 'editor.action.organizeImport')"
    )
    -- TODO: make coc-eslint auto-fix all the import order problems in the buffer
end, {
    bang = true,
    nargs = 0,
    desc = 'CoC organize imports',
})
```

And here's a video showing the organize action followed by the single auto-fix action.


https://github.com/user-attachments/assets/8098b96d-7daf-415d-b967-b2cc3d8e6de4

What would be the lua command that causes coc to auto-fix the import order issues?

**Comment by nullromo** [comment]
> Try to run the command two times

Running `OrganizeImports` multiple times does ends with the same result as running it once.

> coc.nvim supports run actions in order

The two actions I want to run in order are
(1) `source.organizeImports` to get the tsserver action of alphabetizing all the imports, and
(2) quickfix action for the import issues.

For (2), I have tried `vim.cmd("call CocAction('fixAll')")`, but that did not do anything.

Right now I have
```lua
vim.api.nvim_create_user_command(
    'CocAction',
    'normal <Plug>(coc-codeaction)',
    { bang = true, desc = 'CoC action' }
)
vim.api.nvim_create_user_command(
    'TryQuickFix',
    "call CocAction('fixAll')",
    { bang = true }
)
```

When I run `:TryQuickFix`, it does nothing. When I run `:CocAction` and then select the option like `5. Fix all auto-fixable problems`, it works.

**Comment by fannheyward** [comment]
Enable `eslint.autoFixOnSave` in your coc-settings.json, this will run eslint's fix action on saving. 

Now you run the command to sort imports, automatically run eslint fix on saving.

**Comment by fannheyward** [comment]
Or write a command to run two commands:

1. editor.action.organizeImport
2. eslint.executeAutofix

**Comment by nullromo** [comment]
> Or write a command to run two commands

Yes, this is exactly what I’m trying to do. I just don’t know the Lua command for executing the autofixes.

**Comment by nullromo** [comment]
Ok I figured it out

```lua
vim.cmd("call CocAction('runCommand', 'eslint.executeAutofix')")
```

This will work on its own.


However, this will not work.

```lua
vim.api.nvim_create_user_command('OrganizeImports', function()
    vim.cmd("call CocAction('runCommand', 'editor.action.organizeImport')")
    vim.cmd("call CocAction('runCommand', 'eslint.executeAutofix')")
end, { bang = true, nargs = 0, desc = 'CoC organize imports' })
```

I think there needs to be some time between the organize action and the autofix, otherwise CoC will not have any eslint action to fix.

For now I guess I can just use `eslint.autoFixOnSave`, and run organizeImport followed by `:w`. But it would be nice if it worked without saving, and without having to auto-fix the rest of the potential problems that I might not want to auto-fix.
