### ISSUE TITLE
Cannot read properties of undefined (reading 'stubPath')

### ISSUE THREAD

**Issue by tahseenjamal** [neoclide/coc.nvim#5139]
Link to my [.vimrc](https://github.com/tahseenjamal/vimrc/blob/main/vimrc) configuration

Steps to repeat
1. Install VIM (vim editor)
2. Use my [.vimrc](https://github.com/tahseenjamal/vimrc/blob/main/vimrc) file config
3. Then run `:PluginInstall` inside vim and then exit
4. After this you would have to run `npm install` inside `~/.vim/bundle/coc.nvim` folder
5. Now install miniconda `https://docs.anaconda.com/miniconda/`
6. Created new environment with `python 3.11` and masonite 4 framework (`pip install masonite==4.20.0`)
7. Switch to this new environment
8. Create a new project using command `project start blog`
9. Then go into the blog folder
10. Open vi and run inside it `:CocInstall coc-basedpyright`
11. Now open `blog/app/controllers/WelcomeController.py` and you would see

I get below error

`[coc.nvim] Request workspace/configuration failed with message: Cannot read properties of undefined (reading 'stubPath')`

**Comment by fannheyward** [comment]
Fixed in coc-basedpyright.
