### ISSUE TITLE
Don't trigger suggestions after user-defined blacklisted words

### ISSUE THREAD

**Issue by promisedlandt** [neoclide/coc.nvim#514]
**Is your feature request related to a problem? Please describe.**

In Ruby, `do` is used to open a block, like `{` in many other languages. Even with `"suggest.autoTrigger": "always"`, I never want to the PUM to open after "do". 
But, I still want suggestions after "undo" or "dot" for example.

**Describe the solution you'd like**

A configuration option, by filetype, that lets me set an array of words after which autoTrigger does not happen, regardless of settings.
Ideally, it will close the PUM if it is open and the blacklisted word is reached (not so important to me, as I use minTriggerInputLength 2).

**Describe alternatives you've considered**

Currently, with mucomplete, I hacked together something that allows blacklisting words by filetype.
When I try Coc (every few weeks), I use `<c-e>` to close the PUM after `do`, and it hurts.

**Comment by chemzqm** [comment]
What is the problem when the pum is opened at that time?
`<cr>` can be used to break the line when pumvisible, unless you remap it.

**Comment by promisedlandt** [comment]
Just tried `b:coc_suggest_blacklist`, it works perfectly, thank you very much!
