### ISSUE TITLE
command to sync with coc_global_extensions

### ISSUE THREAD

**Issue by laoshaw** [neoclide/coc.nvim#5141]
**Is your feature request related to a problem? Please describe.**
coc_global_extensions helps to auto install which is great, however when I remove some extensions from it, I frequently forgot to run 'CocUninstall' manually. it will be great if there is a flag that let me always keep my coc extensions in sync with coc_global_extensions, for example, if an extension is removed from coc_global_extension, it will either be uninstalled, or disabled when I open vim, so I always know what extensions is currently loaded and active.
This works just like vim's Plug installer, once I disabled/commented out that 'Plug' line, even though the Plug is still on my hard drive, it will not be loaded at least.

**Describe the solution you'd like**

my action coc extensions is also consistent with the list from coc_global_extensions

**Describe alternatives you've considered**

**Additional context**

**Comment by fannheyward** [comment]
Previous discussions

- https://github.com/neoclide/coc.nvim/issues/2857
- https://github.com/neoclide/coc.nvim/issues/3908
