### ISSUE TITLE
Is there any way I can check the type of a rvalue in C++?

### ISSUE THREAD

**Issue by 0BananaBig0** [neoclide/coc.nvim#5143]
**Is your feature request related to a problem? Please describe.**
Is there any way I can check the type of a rvalue in C++? I want to check the type of an rvalue, like a variable. However, when I call the ShowDocumentation() function to check the rvalue, coc.nvim reports “hover not found”. For example, std::string a_string = "hello";, I want to check the type of ”hello“，not a_string, but coc.nvim only reports “hover not found”.
**Describe the solution you'd like**
Check the type of a right value like a variable

**Comment by fannheyward** [comment]
You need to setup a language server for this, coc.nvim is a client that requests and displays the result.

The `hover not found` means no language server return hover document for this.

**Comment by 0BananaBig0** [comment]
> You need to setup a language server for this, coc.nvim is a client that requests and displays the result.
> 
> The `hover not found` means language server returns empty hover document.

I have set up a language server and installed coc-clangd. It works when I check the lvalue. However, when I check the rvalue, it does not work and reports “hover not found.”

**Comment by 0BananaBig0** [comment]
> You need to setup a language server for this, coc.nvim is a client that requests and displays the result.
> 
> The `hover not found` means language server returns empty hover document.

I have set up a language server and installed coc-clangd. It works when I check the lvalue. However, when I check the rvalue, it does not work and reports “hover not found.”

**Comment by fannheyward** [comment]
> check the rvalue, it does not work and reports “hover not found.”

clangd didn't returns any result for this, coc.nvim reported `hover not found`. Does clangd support checking type of rvalue?

**Comment by 0BananaBig0** [comment]
> You need to setup a language server for this, coc.nvim is a client that requests and displays the result.
> 
> The `hover not found` means language server returns empty hover document.

Maybe I know the issue. I changed the version of clangd from 14 to 16, and it works now. Thanks very much.
