### ISSUE TITLE
gr conflicts with neovim built in mappings

### ISSUE THREAD

**Issue by Asheq** [neoclide/coc.nvim#5147]
**Is your feature request related to a problem? Please describe.**

The sample config recommends this mapping:

```
nmap <silent> gr <Plug>(coc-references)
```

However, neovim already has the following conflicting mappings:
```
:map gr

n  grr         * <Lua 17: vim/_defaults.lua:0>
                 vim.lsp.buf.references()
x  gra         * <Lua 16: vim/_defaults.lua:0>
                 vim.lsp.buf.code_action()
n  gra         * <Lua 15: vim/_defaults.lua:0>
                 vim.lsp.buf.code_action()
n  grn         * <Lua 14: vim/_defaults.lua:0>
                 vim.lsp.buf.rename()
```

In order to invoke `<Plug>(coc-references)`, I have to type `gr<Esc>`

**Describe the solution you'd like**

What is the recommended approach for dealing with this?

**Describe alternatives you've considered**

Is adding the `<nowait>` the best approach?

```
nmap <silent> <nowait> gr <Plug>(coc-references)
```

If so, may be we should include it in the sample config.

**Comment by fannheyward** [comment]
You can override nvim default LSP key-mappings, check `:h gr-default`. 

`nnoremap <silent><nowait> gr <Plug>(coc-references)`
