### ISSUE TITLE
Tab just to second instead of first result

### ISSUE THREAD

**Issue by Brutus11111** [neoclide/coc.nvim#5153]
I know this is a common question:

https://github.com/neoclide/coc.nvim/issues/4202
https://github.com/neoclide/coc.nvim/issues/4166
https://github.com/neoclide/coc.nvim/issues/4283
https://github.com/neoclide/coc.nvim/issues/4166
https://github.com/neoclide/coc.nvim/issues/4364

One of the issue has a link to this changelog that's causing the issue:

https://github.com/neoclide/coc.nvim/releases/tag/v0.0.82

I still don't know what to do to fix the problem. The suggestion below the issues is to add the line, but not where. I've never changed anything in the coc configuration. I've tried to find the solution in the coc help file as suggested using :h coc-config and put this in my coc-settings.json:

```{
    "languageserver": {
        "suggest.noselect": true                
    "bash": {
        "command": "bash_language-server",
        "args": ["start"], 
        "filetypes": ["sh"],                    
        "suggest.noselect": true                
        "ignoredRootPaths": ["~"]               
        }                                       
    }                                           
}                                               
```

That doesn't seem to work. 

In the help file I found this line:

`let g:coc_user_config['suggest.noselect'] = v:true`

I've tried that as the command `:let g:coc_user_config['suggest.noselect'] = v:true` but that doesn't work either. 

Can you please help me fix this issue?

**Comment by fannheyward** [comment]
```json
{
  "suggest.noselect": true,
  "languageserver": {
    "bash": {
      "command": "bash_language-server",
      "args": [ "start" ],
      "filetypes": [ "sh" ],
      "ignoredRootPaths": [ "~" ]
    }
  }
}
```
