### ISSUE TITLE
Link to this plugin in docs?

### ISSUE THREAD

**Issue by davidosomething** [neoclide/coc.nvim#5158]
Made a plugin to convert coc.nvim diagnostics to vim.diagnostic without installing entire ALE system:

https://github.com/davidosomething/coc-diagnostics-shim.nvim

It provides only the bare minimum autoload function:
https://github.com/davidosomething/coc-diagnostics-shim.nvim/blob/main/autoload/ale/other_source.vim

**Comment by fannheyward** [comment]
Great work! You're welcome to make a PR to add this to the docs.

**Comment by fannheyward** [comment]
Closed by https://github.com/neoclide/coc.nvim/pull/5159

**Comment by Lmills71** [comment]
That's amazing!! Thank you
