### ISSUE TITLE
disable floating windows / virtual text for coc-eslint

### ISSUE THREAD

**Issue by cvlmtg** [neoclide/coc.nvim#517]
Hi, is there a way to have eslint errors back in the status line instead of floating windows or virtual text? (tbh I'm not sure which one of those is used)

Anyway they are still buggy and sometimes the error gets "stuck" over my code. If I run `:CocConfig` the autocomplete suggests me "diagnostic.virtualText", but even if I set it to false I still get the error messages over the code. I haven't found anything else in docs or readme to disable them...

Thanks!

**Comment by chemzqm** [comment]
Added `"diagnostic.messageTarget"`

**Comment by typetetris** [comment]
With
```
nmap <leader>1 :call coc#config('diagnostic.messageTarget', 'echo')<CR>
nmap <leader>2 :call coc#config('diagnostic.messageTarget', 'float')<CR>
```
in your `~/.config/nvim/init.vim`
you can turn off floating diagnostics with `<leader>1` and turn them on again with `<leader>2`.

For a lot of people `<leader>` is still the default `\`.
