### ISSUE TITLE
Alternative keybinding for coc-dialog-input toggle-slection

### ISSUE THREAD

**Issue by laktak** [neoclide/coc.nvim#5184]
**Is your feature request related to a problem? Please describe.**

My terminal has problems recognizing `<C-space>`. 

This means that I cannot use

>    <C-space>           - toggle selection of current item in quickpick list when canSelectMany is supported.

**Describe the solution you'd like**

Please provide an alternative keybinding (e.g. `<C-t>`) like you do with "move to next item in quickpick list".

**Describe alternatives you've considered**

I have to use Windows Terminal with WSL and vim ... I'm unable to fix the terminal/vim/whatever is causing this.

I've tried the suggestions in  #4673. Commenters there and in #4939 also mention having problems with this keybinding.

**Additional context**

See

```
							*coc-dialog-input*
[...]
<C-j> <C-n> <down>  - move to next item in quickpick list.
<C-k> <C-p> <up>    - move to previous item in quickpick list.
<C-space>           - toggle selection of current item in quickpick list when
canSelectMany is supported.
```

**Comment by ahnafalnafis** [comment]
Apologies, I'm not really sure what are you talking about. If you want to bind something to `Ctrl + Space` in `Vim`, you can use `<C-@>`. `<C-@>` is equivalent to `<C-Space>` in `Vim`.

**Comment by laktak** [comment]
Well, the `coc-dialog-input` is the popup where you can select, for example what overrides to implement. You need to press `<C-Space>` (aka `<C-@>`) there, it's hardcoded:

https://github.com/neoclide/coc.nvim/blob/master/src/model/quickpick.ts#L146

**Comment by ahnafalnafis** [comment]
@laktak, is the issue resolved?

**Comment by laktak** [comment]
No, how could it? Like I explained above, the keybinding is hardcoded.

        } else if (this.canSelectMany && key == '<C-@>') {
