### ISSUE TITLE
In China, we cannot reach "https://registry.npmjs.org/"

### ISSUE THREAD

**Issue by AFUL1991** [neoclide/coc.nvim#5185]
## Describe the bug

I'm from China, but I cannot use the command of `:CocInstall coc-clangd` to install coc-clangd. Because of the GFW, we cannot reach "https://registry.npmjs.org/", and I don't know how to change the source to the mirror source in China.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
You can setup proxy, check :h coc-config-http, or change npm register, check :h coc-config-npm.

**Comment by AFUL1991** [comment]
> You can setup proxy, check :h coc-config-http, or change npm register, check :h coc-config-npm.

thank you, i will try it tomorrow

**Comment by chemzqm** [comment]
你可以设置 coc.nvim 使用的 registry `:h coc-extensions-npm`
