### ISSUE TITLE
Pum sometimes gets stuck open.

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#519]
Not sure if this is a Coc bug or a Neovim bug.

**Result from CocInfo**
vim version: NVIM v0.4.0-374-g21ad043be
node version: v11.11.0
coc.nvim version: 0.0.59
term: xterm-256color
platform: linux

**Describe the bug**
Pum sometimes gets stuck open.
Resizing the window sometimes hides it.

**To Reproduce**
Not yet sure.

![Screenshot_20190313_072748](https://user-images.githubusercontent.com/29133776/54275951-6380ae80-4562-11e9-96e8-534ea7ccd7fe.png)

**Comment by chemzqm** [comment]
It's problem of your neovim, make sure you don't have `  "suggest.reloadPumOnInsertChar": true,` probably avoid it.

**Comment by Avi-D-coder** [comment]
thanks
