### ISSUE TITLE
Disable spellcheck in floating window

### ISSUE THREAD

**Issue by kristijanhusak** [neoclide/coc.nvim#520]
**Is your feature request related to a problem? Please describe.**
Kind of. It's annoying and not useful at all, because there's nothing to fix.

**Describe the solution you'd like**
Solution to disable spellcheck by default or expose option to do it myself.

**Describe alternatives you've considered**
I don't know any.

**Additional context**
Here's the screenshot how it looks for me with Nord colorscheme:

![screenshot](https://i.imgur.com/Vcx1OQ7.png)

**Comment by bfredl** [comment]
What does `:verbose set spell?` show within the floating window? (need to make it current, maybe some hack is needed for that).

**Comment by kristijanhusak** [comment]
I'm not sure how can i access floating window.

The red highlight in my screenshot is definitely spell highlight because i tried changing it to make sure (`hi SpellBad guibg=NONE`)

**Comment by Avi-D-coder** [comment]
`:set spell!` should disable spellcheck globally.
@bfredl am I correct in saying there is no way to disable spelling on a per buffer basis?

**Comment by kristijanhusak** [comment]
I found an issue. I have this in my init.vim:

```vimL
autocmd FileType markdown setlocal spell
```

Didn't knew that floating window has markdown filetype. Why is that the case?

**Comment by Avi-D-coder** [comment]
@kristijanhusak LSP documentation is usually markdown. There are some issues with when it is markdown or a string.

**Comment by Avi-D-coder** [comment]
@kristijanhusak I'm not sure how it can be force disabled at a buffer level.

**Comment by kristijanhusak** [comment]
@Avi-D-coder I think this should do the trick:

```vimL
call nvim_win_set_option(winid, 'spell', v:false)
```

**Comment by Avi-D-coder** [comment]
@kristijanhusak  great!

**Comment by chemzqm** [comment]
I will not markdown for filetype to avoid issues with other markdown plugins, the highlights would be provided from background running neovim instance.

**Comment by bfredl** [comment]
@chemzqm I think you can set 'syntax' option of buffer to "markdown" instead of 'filetype', to only get syntax highlight but no filetype plugins.

**Comment by chemzqm** [comment]
The buffer would probably contains text of different syntax types and I can add highlights for fency code blocks without the need of markdown plugin.

**Comment by chemzqm** [comment]
> let g:markdown_fenced_languages

It requires vim-markdown installed and filetype to be markdown to work, and the performance is bad.

**Comment by Avi-D-coder** [comment]
vim-markdown comes by default, is a background neovim really going to provide better performance?

**Comment by chemzqm** [comment]
> is a background neovim really going to provide better performance?

Sure, all code blocks with makdown all parsed in parallel and cached.

**Comment by chemzqm** [comment]
Fixed, not use markdown as filetype any more.
