### ISSUE TITLE
workspace.onDidOpenTextDocument cannot work

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#5200]
## versions

vim version: NVIM v0.10.2
node version: v20.18.0
coc.nvim version: 0.0.82-9fd85781 2024-09-21 00:59:00 +0900
coc.nvim directory: /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
term: tmux
platform: linux

## Log of coc.nvim

2024-11-24T22:30:58.650 INFO (pid:1067148) [plugin] - coc.nvim initialized with node: v20.18.0 after 78
2024-11-24T22:30:58.669 INFO (pid:1067148) [core-watchman] - watchman watching project: /dev/shm/coc-test

## Describe the bug

```typescript
import { ExtensionContext, window, workspace } from 'coc.nvim';

export async function activate(context: ExtensionContext): Promise<void> {

  context.subscriptions.push(workspace.onDidOpenTextDocument(event => {
    window.showInformationMessage("test");
  }));

}
```

```vim
#!/usr/bin/env -S vi -u
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
let s:root = fnamemodify(expand('<sfile>'), ':p:h:h')
execute 'set runtimepath+=' . s:root
let g:coc_config_home = '.'
let g:coc_data_home = s:root . '/node_modules/coc'
set formatexpr=CocAction('formatSelected')
```

Then

```
tests/test.vim tests/test.vim
```

Expected:

Display test after open test.vim

Actually:

Nothing happened.

**Comment by fannheyward** [comment]
I encountered this before; I remember that the event was fired before the extension was activated.

**Comment by fannheyward** [comment]
A workaround for this:

```ts
export async function activate(context: ExtensionContext): Promise<void> {
  context.subscriptions.push(
    workspace.onDidOpenTextDocument(didOpenTextDocument),
  );

  workspace.documents.map((doc: Document) => {
    didOpenTextDocument(doc.textDocument);
  });
}
```

**Comment by Freed-Wu** [comment]
Where is didOpenTextDocument?

**Comment by fannheyward** [comment]
> didOpenTextDocument

Custom example function.

The `workspace.documents` contains opened documents.

**Comment by Freed-Wu** [comment]
Can you provide an entire solution includes `didOpenTextDocument`? I cannot make it work :cry:

**Comment by fannheyward** [comment]
https://github.com/fannheyward/coc-markdownlint/blob/master/src/index.ts
