### ISSUE TITLE
WebAssembly out of memory cannot allocate wasm memory for new instance

### ISSUE THREAD

**Issue by ihtycm** [neoclide/coc.nvim#5227]
## Result from CocInfo

![image](https://github.com/user-attachments/assets/d6df5806-d3c6-4b19-a1a1-390fb15fa021)

## Describe the bug

When i just open the vim with no any file , the coc.nvim tell the error.

![image](https://github.com/user-attachments/assets/795afaea-a46b-4c85-bd17-a710adbc1b8d)

This is the `ulimit -a` result

![image](https://github.com/user-attachments/assets/0c3d6d62-2ed4-4ac2-9f45-ed676e65e6b5)

## Reproduce the bug

i use the same configure git repo. one is ok, but the server's vim is bad.

**Comment by fannheyward** [comment]
Try this solution https://medium.com/code-art/vim-the-whole-process-to-solve-coc-nvim-b6f3b3f68ebe
