### ISSUE TITLE
Compatible with blink.cmp

### ISSUE THREAD

**Issue by zruhao** [neoclide/coc.nvim#5228]
I use blink.cmp as a completion plugin for Neovim, but I also need to use plugins from coc.nvim to provide completion suggestions. How can I set up coc.nvim as a source for blink.cmp, so that the completion suggestions from coc.nvim are sent to blink.cmp for completion? Or is there any way to make coc.nvim and blink.cmp compatible?

**Comment by fannheyward** [comment]
You can't setup coc.nvim as a source for now, and it's not easy to make coc.nvim's suggestions to be sent to blink because coc.nvim also needs to re-trigger on input/backspace deleting/suggestions selecting etc. We can provide suggestions list based on position, but it's not a good list.

**Comment by chemzqm** [comment]
It's quite hard to make two different completion plugin work well together.
