### ISSUE TITLE
Switching sessions multiple times will cause nvim to be in a suspended state

### ISSUE THREAD

**Issue by zhruith** [neoclide/coc.nvim#5230]
Switching session multiple times(two or more, random), when exit nvim will cause nvim to be in a suspended state, can't exit. have to close the terminal.
Test platform: windows 11 and wsl(Ubuntu) both.
Switch command: CocCommand session.load

cocinfo:
## versions

vim version: NVIM v0.10.2
node version: v23.4.0
coc.nvim version: 0.0.82-aacbbcad 2024-11-23 13:34:02 +0800
coc.nvim directory: C:\Users\zhrui\.vim\plugged\coc.nvim
term: xterm-256color
platform: win32

## Log of coc.nvim

2024-12-21T19:13:28.548 WARN (pid:12436) [workspace] - Extension "coc-lists" registered synchronized autocmd "VimLeavePre", which could be slow.
2024-12-21T19:13:28.575 INFO (pid:12436) [plugin] - coc.nvim initialized with node: v23.4.0 after 185
2024-12-21T19:13:30.731 INFO (pid:12436) [attach] - receive notification: openList [ 'commands' ]
2024-12-21T19:13:32.744 INFO (pid:12436) [attach] - receive notification: openList [ 'vimcommands' ]

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the coc#rpc#stop() function in autoload/coc/rpc.vim to add a more robust cleanup process. This should help prevent Neovim from getting stuck in a suspended state after switching sessions multiple times.

You can review changes in this commit: https://github.com/wwqwq2313/neoclide-coc.nvim-5230/commit/28c31bce09e7af65db4aadff9f15c8196e26fa58.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by zhruith** [comment]
@wwqwq2313 I change the coc#rpc#stop() function as your direction commit, but it's still not working for me. suspended state when :exit nvim

**Comment by zhruith** [comment]
And sometimes got this error when load session:
[coc.nvim]: UnhandledRejection: transport disconnected
Error: request error on "nvim_eval" - transport disconnected                                                                                                                                                             at MruList._addRecentFile (C:\Users\zhrui\AppData\Local\coc\extensions\node_modules\coc-lists\lib\index.js:3606:35)                                                                                                  at C:\Users\zhrui\AppData\Local\coc\extensions\node_modules\coc-lists\lib\index.js:3590:19

**Comment by fannheyward** [comment]
Can't reproduce on macOS and Linux, looks like the nvim instance on WSL slow to respond.

Disable `session.saveOnVimLeave` and try again.

**Comment by zhruith** [comment]
Disable session.saveOnVimLeave still been suspended when exit.
Switch two session is ok, three and more will suspend.

**Comment by zhruith** [comment]
My config is here: https://github.com/zhruith/nvim

**Comment by zhruith** [comment]
If have two session switch in cycle for three times, will suspend again.

**Comment by fannheyward** [comment]
Try minimal vimrc, only coc.nvim + coc-lists.

Guess that nvim has some performance issues on Windows.

**Comment by zhruith** [comment]
Oh yeah, is working now. just have lazy.nvim and coc.nvim. thanks for your help.

**Comment by zhruith** [comment]
The reason is  'lewis6991/gitsigns.nvim', disabled it will working well.
