### ISSUE TITLE
Is it possible to optimize performance for coc.nvim first startup in windows?

### ISSUE THREAD

**Issue by zhruith** [neoclide/coc.nvim#5233]
First startup:
![image](https://github.com/user-attachments/assets/4031e217-b117-49da-b1f7-60a91cf3aaaf)

Subsequent startup：
![image](https://github.com/user-attachments/assets/cb983126-4586-4140-bf32-d54f5775e160)

## versions

vim version: NVIM v0.10.3
node version: v23.5.0
coc.nvim version: 0.0.82-a6e54aed 2024-12-18 12:26:34 +0800
coc.nvim directory: C:\Users\zhrui\AppData\Local\nvim-data\lazy\coc.nvim
term: xterm-256color
platform: win32

## Log of coc.nvim

2024-12-27T12:39:16.487 WARN (pid:16012) [workspace] - Extension "coc-lists" registered synchronized autocmd "VimLeavePre", which could be slow.
2024-12-27T12:39:16.515 INFO (pid:16012) [plugin] - coc.nvim initialized with node: v23.5.0 after 179
2024-12-27T12:40:20.349 INFO (pid:16012) [attach] - receive notification: openList [ 'commands' ]
2024-12-27T12:40:22.798 INFO (pid:16012) [attach] - receive notification: openList [ 'vimcommands' ]

**Comment by fannheyward** [comment]
coc.nvim uses nvim's jobstart function to spawn Node.js process, looks like this is the expensive in Windows.

**Comment by chemzqm** [comment]
Seems issue with your node, your nvim takes too much time to find node executable, you can configure full path to speed it up, see `:h g:coc_node_path`

**Comment by zhruith** [comment]
I've got the reason of delay by many time testing. 
when execute a file first startup, file hash value will upload to cloud and check it. that's the reason of delay.  just close the cloud Protect in Microsoft Defender will fix this delay.  for windows 10 and windows 11. this sort of delay not just for nvim, but all the executable files in Windows.
