### ISSUE TITLE
Custom path to coc-settings.json

### ISSUE THREAD

**Issue by xvoidee** [neoclide/coc.nvim#528]
Hello,

Is there a way to manually specify custom path to coc-settings.json file? I do not want to read settings file from ~/.config/nvim.

**Comment by chemzqm** [comment]
You can't, but you have options:

* Link other folder like `~/.vim` to `~/.config/nvim`
* Use viml for configuration, checkout `:h coc#config()`

**Comment by ydhamija96** [comment]
Would this make a good enhancement request? I also would like to do this. `coc#config()`, while awesome, isn't ideal.

**Comment by jerry901** [comment]
now supports ```let g:coc_confing_home = '~/path/to/coc-settings.json```

**Comment by 0MR4N** [comment]
> now supports `let g:coc_confing_home = '~/path/to/coc-settings.json' `

it's **g:coc_config_home** bro fix it bro cz we are blind copiers 😄, and the value should be **directory** of where coc-settings should be and coc related files ?

**Comment by chemzqm** [comment]
> and the value should be directory of where coc-settings should be

The value should the directory contains coc-settings.json see `:h coc-configuration`
