### ISSUE TITLE
How do I load a custom snippet file?

### ISSUE THREAD

**Issue by faurehu** [neoclide/coc.nvim#529]
Hi, I want to load my own custom vscode style snippet file. I know that I can install them by pointing to their github repository but I want to work with one that is only mine and stored locally.

How can I run `:CocInstall` so that it loads a simple `snippets.json` file?

**Comment by chemzqm** [comment]
Not yet, but it's planned https://github.com/neoclide/coc-snippets/issues/13

**Comment by faurehu** [comment]
Cheers, I'll subscribe over there

**Comment by kintsugi** [comment]
In the meantime, you can use [this tool](https://github.com/VincentCordobes/convert-snippets) to convert a vscode [snippets.json](https://github.com/kintsugi/vscode-es7-javascript-react-snippets/blob/master/snippets/snippets.json) into an ultisnips [javascript.snippets](https://github.com/kintsugi/vscode-es7-javascript-react-snippets/blob/master/snippets/javascript.snippets)
