### ISSUE TITLE
How to configure vetur language server when using coc-vetur?

### ISSUE THREAD

**Issue by AgentCosmic** [neoclide/coc.nvim#530]
I tried so many ways to configure vetur but I keep getting errors. I want to change things like tabSize. Is there any sample code I can reference? Thanks!

**Comment by chemzqm** [comment]
It's https://github.com/neoclide/coc-vetur/blob/master/package.json#L73

Run `CocInstall coc-json` to get completion support for coc-settings.json.

**Comment by AgentCosmic** [comment]
Hi chemzqm,
Thank you for your prompt response. I'm getting an error that I need to specify things like command and filetypes etc but I already have coc-vetur installed. Since coc-vetur is already responsible for those config do I need to set them again? And I can't specify the command as a full path.

```
{
	"languageserver": {
		"vetur": {
			"filetypes": ["vue"],
			"command": "D:/Applications/Vim/home/AppData/Local/coc/extensions/node_modules/vue-language-server/bin/vls",
			"configuration": {
				"vetur.format.options.tabSize": 4
			}
		}
	}
}
```

**Comment by chemzqm** [comment]
You should not configure vetur language server when you have coc-veture installed.

**Comment by AgentCosmic** [comment]
That's the part that confused me. If i'm using coc-vetur, I'm not allowed to configure vetur. So if I want to configure vetur I have to uninstall coc-vetur and configure it manually?

**Comment by chemzqm** [comment]
> If i'm using coc-vetur, I'm not allowed to configure vetur.

Not true, you can configure it by configurations starts with `vetur`

**Comment by AgentCosmic** [comment]
Oh I get now! You're supposed to add it to the root of the config file like so. For anyone else wondering:

```
{
	...  
	"vetur.format.options.tabSize": 4,
	"vetur.format.options.useTabs": true,
	"vetur.format.defaultFormatterOptions": {
		"prettier": {
			"singleQuote": true,
			"semi": false,
			"trailingComma": "es5"
		}
	}
}
```
Thanks chemzqm!
