### ISSUE TITLE
Disable floating window for signature help

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#532]
With new version of coc.nvim, by default floating window is enabled for signature help in neovim 0.4.0, any option for disable it?

Sorry for my bad English!

**Comment by mihaelartz** [comment]
Floating window is very very slow... But is cool

**Comment by chemzqm** [comment]
Float window should be fast, it should be your server that quite slow.

**Comment by chemzqm** [comment]
Set `coc.preferences.signatureHelpTarget` to `echo`.
