### ISSUE TITLE
Signature help not updating

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#533]
When accept function completion i get information about it, but problem is when change param signatureHelp still stay on first.

e.g.:
```php
<?php

$pdo = new PDO;

// ($statement, array $driver_options = array()) signatureHelp results
$pdo->prepare('', ['\/']) // \/ = cursour, still stay on first / $statement  

```

Sorry for my bad English!

**Comment by chemzqm** [comment]
Looks like problem of your language server, need output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel to verify that problem.

**Comment by mihaelartz** [comment]
@chemzqm Now signatureHelp not working...

Output: https://gist.github.com/mihaelartz/439d51dd5a41958048407d2556e27e84

**Comment by chemzqm** [comment]
The output seems all right, the signature help is triggered and returned as expected.

**Comment by mihaelartz** [comment]
@chemzqm Hmm... after last commit signatureHelp not working tested on neovim 0.3.4 echo mode.
Is it possible to totally exclude the coc.nvim signatureHelp, and use echodoc as alternative?

**Comment by chemzqm** [comment]
My bad, last commit is broken, should be fixed now.

**Comment by mihaelartz** [comment]
@chemzqm 
![2019-03-16-112608_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/54473908-70113b00-47de-11e9-916c-f1c98c78c0d4.png)

**Comment by mihaelartz** [comment]
@chemzqm echo mode
![2019-03-16-113407_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/54473986-7b189b00-47df-11e9-98b5-386b0bfa3eac.png)

**Comment by chemzqm** [comment]
Looks like active parameter index return from your language server is wrong.

**Comment by mihaelartz** [comment]
@chemzqm I open issue in intelephense repo, for now closing. Thanks

**Comment by mihaelartz** [comment]
@chemzqm my bad, coc.preferences.triggerSignatureHelp i set it to be false but it should be true...
