### ISSUE TITLE
Index new files without restart language server or vim

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#535]
When install packages for rust i must to restart vim to get completions for that package I installed.

Can you add an option like VSCode when workspace change, language server check new files if they are the same type e.g. if language server is rls (rust), server check if new file is rust if is index them.

This is an example for rust, but this problem also occurs in others languages

Sorry for bad English.

**Comment by chemzqm** [comment]
>  i must to restart vim.

Not needed, you can use `:CocRestart` to restart coc service.

**Comment by chemzqm** [comment]
It's problem of your language server, coc-tsserver doesn't requires restart after new module installed.
