### ISSUE TITLE
Show signatureHelp on accept completion

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#537]
## Hello!

- I have a problem about signatureHelp, when accept completion i don't get a info about e.g. function, only get info when trigger completion e.g. document.writeline( // then get a info about function params, any suggestions?

**Comment by chemzqm** [comment]
* Use plugin like https://github.com/Shougo/echodoc.vim and set `suggest.echodocSupport` to `true`.
* If the server provide function completion as snippet feature, add 

```
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
```
to your vimrc.
