### ISSUE TITLE
Expanding snippets that start with `:` doesn't work

### ISSUE THREAD

**Issue by filipekiss** [neoclide/coc.nvim#547]
**Result from CocInfo**
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.58
term: iTerm.app
platform: darwin

**Describe the bug**
A have a few snippets in Ultisnips that start with `:`, for example: `:opt` returns `⌥`. If I try to complete using `coc.nvim`, I type, for example `:o` and <KBD>Tab</KBD> until the `:opt` from UltiSnips is selected and press <KBD>Enter</KBD>, the resulting text is `:⌥`. If it's a snippet that needs to be at the beggining of the line, the expansion won't work unless I deleted the leading `:` and expand using UltiSnips trigger.

**To Reproduce**
1. Create a snippet in Ultsnipps whith the trigger starting with `:`
2. Try to expand using the `pum` from `Coc.nvim`

**Screenshots**
Here's a gif of said problem:

![CleanShot 2019-03-18 at 10 44 25](https://user-images.githubusercontent.com/48519/54534463-2a35ad80-496b-11e9-84db-b4154f8abaee.gif)

**Comment by chemzqm** [comment]
The problem is because ultisnip return trigger that starts with `:` but it's not keyword, no you get double `:` inserted, add `:` to your buffer's `iskeyword` option or use [coc-snippets](https://github.com/neoclide/coc-snippets) to fix it.

**Comment by filipekiss** [comment]
Great! Adding `:` to the 'iskeyword` option worked as intended! Thanks, @chemzqm!
