### ISSUE TITLE
Failed to install in Ubuntu server 18.04

### ISSUE THREAD

**Issue by lzfmars** [neoclide/coc.nvim#548]
**Result from CocInfo**
:PlugInstall

init.vim:
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}

**Describe the bug**
It's failed to install coc.vim in Ubuntu server 18.04 with neovim

**To Reproduce**
1.Set Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}} in init.vim;
2.run :PlugInstall.

**Screenshots**
![image](https://user-images.githubusercontent.com/10499701/54542309-8b469b00-49d6-11e9-8306-2bdecfe4bc4d.png)

**Comment by chemzqm** [comment]
It's just warning, it means server started as expected.

**Comment by lzfmars** [comment]
Hi, I removed coc.nvim, and reinstall this plug. It's error when install nodejs.

![image](https://user-images.githubusercontent.com/10499701/54600252-50487400-4a77-11e9-9a9a-6b1a8c5f6dd1.png)

**Comment by chemzqm** [comment]
The script for install nodejs doesn't work for you, checkout https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
