### ISSUE TITLE
how to setting format style in coc

### ISSUE THREAD

**Issue by juxiemaotu** [neoclide/coc.nvim#550]
How can i setting custom formatting style like webkit ,google or mozilla? In vimrc or coc-settings.json?

**Comment by chemzqm** [comment]
Coc knows nothing about the format style, consult the documentation of language server you're using.

**Comment by xayjin** [comment]
@juxiemaotu if you use ccls for c, touch .clang-format in your project root, then follow [llvm Clang-Format Style Options](http://clang.llvm.org/docs/ClangFormatStyleOptions.html) to config.
