### ISSUE TITLE
Cursorline and snippets

### ISSUE THREAD

**Issue by sunjon** [neoclide/coc.nvim#552]
I use an auto command that turns on cursorline in normal mode, and disables it in insert mode. When in select mode and navigating through the jump points of a snippet, flickering is caused by the cursorline autocommand triggering on /off.

Do you have any suggestions on how to work around this?

**Comment by chemzqm** [comment]
I suggest not use cursorline since it's slow.
You can check `b:b:coc_snippet_active` when it's `1`, not trigger command for cursorline change.
