### ISSUE TITLE
Completion popup max width

### ISSUE THREAD

**Issue by ghost** [neoclide/coc.nvim#554]
Hey!

Any suggestions how to change completion popup width?

**Comment by chemzqm** [comment]
You can't, but you can use `"suggest.detailMaxLength"` to limit detail field of complete item shown in popup menu.

**Comment by chemzqm** [comment]
There is `pumwidth` option with vim: https://github.com/adizero/vim/commit/0016ac198897bd4a5edce023fd6972d1ce9cf2b1

But not ported to neovim yet.
