### ISSUE TITLE
Error: write EPIPE  at WriteWrap.afterWrite

### ISSUE THREAD

**Issue by reaysawa** [neoclide/coc.nvim#556]
**Result from CocInfo**

I've been able to reproduce this consistently with coc-tsserver.

```
## versions

vim version: NVIM v0.4.0-420-g29d6993cc
node version: v8.12.0
coc.nvim version: 0.0.61
term: xterm-kitty
platform: linux
```

**Describe the bug**

Today I updated from v0.0.58 to v0.0.61 and this error began appear around completions.

More information about the error is here
https://stackoverflow.com/a/35641655/8401696

```
## Error messages
Uncaught exception: Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
Uncaught exception: Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
Uncaught exception: Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
```

**To Reproduce**
The exception is also thrown during normal completion.

1. call CocAction('showSignatureHelp')
2. The error will come up on the first try and not appear as often afterwards.

I'm unsure if upgrading to Node 10 will solve it so I wanted to confirm here first.
I'm unsure if this should be opened at https://github.com/neoclide/neovim instead.

**Comment by chemzqm** [comment]
Can't reproduce, consider use `call CocActionAsync('showSignatureHelp')` instead of `call CocAction('showSignatureHelp')`.

**Comment by reaysawa** [comment]
@chemzqm This seems to be the offending function

![image](https://user-images.githubusercontent.com/17429390/54719919-e1355300-4b3c-11e9-93ac-60f5c6f36661.png)

Given what's said [here](https://stackoverflow.com/questions/35641332/node-js-events-js154-throw-err-write-epipe-program-crashing/35641655#35641655) it seems like COC is trying to write to the spawned Neovim instance after it has closed.

Another error message: `"This socket is closed"`

Do you know of a way to debug further on what might be happening?

**Comment by reaysawa** [comment]
Disabling float window highlighting with:

`coc.preferences.enableFloatHighlight: false`

Stops the errors for now.
