### ISSUE TITLE
gopls: "cannot find an enclosing function"

### ISSUE THREAD

**Issue by flowchartsman** [neoclide/coc.nvim#558]
**Result from CocInfo**
## versions

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.61
term: iTerm.app
platform: darwin

## Output channel: languageserver.go-langserver
[Trace - 00:44:06] Sending request 'initialize - (0)'.
Params: {
    "processId": 43933,
    "rootPath": "/Users/awalker/go",
    "rootUri": "file:///Users/awalker/go",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "declaration": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            }
        }
    },
    "initializationOptions": {
        "diagnosticsEnabled": true
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///Users/awalker/opsgo/src/opsgo",
            "name": "opsgo"
        }
    ]
}
//...//
[Trace - 12:44:24 AM] Sending request 'textDocument/signatureHelp - (6)'.
Params: {"textDocument":{"uri":"<redacted>"},"position":{"line":42,"character":29}}

[Error - 12:44:24 AM] send textDocument/signatureHelp#6 cannot find an enclosing function

[Trace - 00:44:24] Received response 'textDocument/signatureHelp - (6)' in 0ms. Request failed: cannot find an enclosing function (0).
[Error  - 00:44:24] Request textDocument/signatureHelp failed.
  Message: cannot find an enclosing function
  Code: 0 

**Describe the bug**
Code: 0 displayed in command line instead of function signature

**To Reproduce**

1. install [gopls](https://godoc.org/golang.org/x/tools/cmd/gopls)
2. edit coc-settings.json to contain the excerpt below
3. autocomplete a function
4. select it

```
{
  "coc.source.gocode.enable": false,

  "languageserver": {

    "go-langserver": {
      "command": "gopls",
      "args": ["serve"],
      "filetypes": ["go"],
       "trace.server": "verbose",
      "enable": true,
      "initializationOptions": {
          "diagnosticsEnabled": true
      }
    }
  }
}
```

Result:
`Code: 0` displayed in command line

Expected:
function signature

**Comment by chemzqm** [comment]
Looks like the server failed to parse your code, you can use autopair plugin of vim  or use https://github.com/neoclide/coc-pairs to insert pairs for you.

**Comment by flowchartsman** [comment]
Hmm. Pairs are working when typing normally, but when I hit enter to select, they parenthesis are not getting added.

Relevant mappings:

```
inoremap <expr><TAB> pumvisible() ? "\<C-n>": "\<TAB>"
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```

**Comment by flowchartsman** [comment]
I've just realized that vim-go was the extension displaying the signature before, and it does so without a parenthesis being there. When I switch over to using the langserver with coc it doesn't work until I type the paren, so this may be operating as intended, however if there's a way to start that paren on selection, it would be great.

**Comment by chemzqm** [comment]
Signature help is triggered by type specified characters, that's how it works.

> however if there's a way to start that paren on selection, it would be great.

The language server could provide snippet for functions, function would be inserted aftered after confirm completion, but I don't know if the language server you're using have that feature or how to turn it on.

**Comment by flowchartsman** [comment]
Or you could add an option (maybe on a per-language basis) to insert the parenthesis when a function is the option selected?

**Comment by chemzqm** [comment]
Not with coc itself, it should be done with language server or an extension.

**Comment by flowchartsman** [comment]
Makes sense as an extension. I'll look into it. Any pointers on where to hook it in?

**Comment by chemzqm** [comment]
You can hack this method: https://github.com/neoclide/coc.nvim/blob/master/src/languages.ts#L646 to add snippet textEdit to CompletionItem.

But I don't recommend it.

**Comment by flowchartsman** [comment]
What *would* you recommend? Basically Id just like to optionally hook the function selection in a sane way with an extension.

**Comment by chemzqm** [comment]
> What would you recommend?

Make an extenison for it, but it would takes more efforts.

**Comment by flowchartsman** [comment]
Okay, is it time to mark this one as closed, or do you still see evidence of a langserver bug?

**Comment by chemzqm** [comment]
It's error from server, consider provide full content of output to the devs of gopls.
