### ISSUE TITLE
How to install coc.nvim on nixos?

### ISSUE THREAD

**Issue by LinArcX** [neoclide/coc.nvim#559]
**Is your feature request related to a problem? Please describe.**
Hi. i'm currently on [nixos](https://nixos.org/).
It's file system isn't follow [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard).
And when i want to use coc, i get an [error](https://raw.githubusercontent.com/LinArcX/Ganje/master/Images/LinArcx/Screenshot%20from%202019-03-20%2009-41-33.png):
Edit: i'm using vim-plug as plugin manager and this method works fine in arch linux:
`Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}`

**Comment by chemzqm** [comment]
It use https://github.com/zeit/pkg for build binary, but it doesn't provide prebuild nodejs for your system, so you have to build from source code.

**Comment by LinArcX** [comment]
I can actually figure out how to install coc.nvim on nixos:
1. Install nodejs and yarn via `nix-env` or put them on `/etc/nixos/configurations.nix`, then `sudo nixos-rebuild switch`
2. change a little bit in __install.sh__ script, so we don't want to download nodejs and yarn anymore, comment this line in __download()__ function:
`install_yarn`
3. Run: `./install.sh`
Can i send this approach as PR for you?

**Comment by chemzqm** [comment]
> Can i send this approach as PR for you?

Sure.

**Comment by earksiinni** [comment]
For anyone coming in from Google, the README.md advice as of writing is outdated. Coc and many Coc plugins are now distributed through Nix itself and you can use Nix to manage everything.

Coc itself is packaged as `nixpkgs.vimPlugins.coc-nvim (vimplugin-coc-nvim)` and can be installed using home-manager (just add `pkgs.vimPlugins.coc-nvim` to `programs.neovim.plugins` in your home-manager config). Alternatively, if you don't want to use home-manager, try this: https://www.mpscholten.de/nixos/2016/04/11/setting-up-vim-on-nixos.html

For a list of Coc plugins, [see the master plugins list](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/vim-plugin-names) and search for `coc-`. You can use `nix search` to find more details about each package.

The traditional methods using vim plug, Pathogen, etc. still work. Pick your poison.

**Comment by grantzvolsky** [comment]
Here's my `neovim-python-coc` configuration for anyone who's just looking for a plain old derivation to get started. Feel free to use it under the MIT license.

https://github.com/grantzvolsky/skel/blob/e5998a02b999103ae864d5bc637f341eb1399cf6/skels/xubuntu-2004/home/wx/.nixpkgs/vim/neovim/neovim-python-coc.nix
