### ISSUE TITLE
Easier way to backup and sync extensions list and config

### ISSUE THREAD

**Issue by talha131** [neoclide/coc.nvim#560]
Awesome plugin. I was forced to switch to VS Code due to lack of a decent completion plugin. After discovering Coc.nvim, I have switched back to NeoVim as my primary editor. Thanks a lot for your great work.

# Problem

I have installed couple of extensions and used `:CocConfig` to configure ccls. Now when I move my setup to a different computer, how do I make sure that my extensions are installed and config is present automatically?

Extension list is in `~/.config/coc/extensions/package.json` and configuration is in `~/.config/nvim/coc-settings.json`. Two different folders. 

Related to #118.

## Request

My request is to add an alternative way that makes it easier to keep the NeoVim configuration in sync with all computers.

For example, if extension list is also present inside `~/.config/nvim/` Or in `init.vim` then Git tracking `~/.config/nvim/` folder would be enough.

## Why workaround is not ideal

I can move `package.json` file into `nvim` folder and create a symlink inside `coc` folder. But this means on every new computer, I will have to manually create `/.config/coc` folder and then create a symbolic link inside it to `package.json` file inside `nvim` folder.

That wouldn't be the case, if extension list is stored inside `nvim` folder or `init.vim` file; perhaps not in `package.json` format but as a simple list in json format.

**Comment by chemzqm** [comment]
For extensions, you can configure `g:coc_global_extensions` in your vimrc, coc will install missing extensions for you after server started.

For settings file, you can sync the settings file to your git repo and use link, or use `g:coc_user_config` or `coc#config()` to add configurations.

**Comment by talha131** [comment]
Thank you for the prompt response. This is solves the issue for me.

**Comment by adoyle-h** [comment]
How about maintain an "extensions" field in `coc-settings.json` when `:CocInstall` extension? COC will check and install missing extensions at start.

```
// coc-settings.json
{
  "extensions": {
    "coc-json": "1.2.4",
    "coc-snippets": "2.1.13"
  }
}
```

**Comment by bigzhu** [comment]
> How about maintain an "extensions" field in `coc-settings.json` when `:CocInstall` extension? COC will check and install missing extensions at start.
> 
> ```
> // coc-settings.json
> {
>   "extensions": {
>     "coc-json": "1.2.4",
>     "coc-snippets": "2.1.13"
>   }
> }
> ```

Show warning `[json] [W] Property extensions is not allowed.`

**Comment by adoyle-h** [comment]
@bigzhu It is just a suggestion which has not been implemented.

**Comment by bigzhu** [comment]
> @bigzhu It is just a suggestion which has not been implemented.

I use `g:coc_global_extensions` it is work fine
```vim

let g:coc_global_extensions = [
      \'coc-markdownlint',
      \'coc-highlight',
      \'coc-vetur',
      \'coc-go',
      \'coc-python',
      \'coc-explorer',
      \'coc-flutter', 
      \'coc-json', 
      \'coc-git'
      \]
```

**Comment by ricardoseriani** [comment]
> How about maintain an "extensions" field in `coc-settings.json` when `:CocInstall` extension? COC will check and install missing extensions at start.
> 
> ```
> // coc-settings.json
> {
>   "extensions": {
>     "coc-json": "1.2.4",
>     "coc-snippets": "2.1.13"
>   }
> }
> ```

Sounds good to me, so it's managed automatically  by coc.nvim when using `:CocInstall` and by `https://github.com/fannheyward/coc-marketplace`, becoming much easier to backup settings and extensions in just one place.

**Comment by oblitum** [comment]
Alternatively you can have settings and extension list and all your vim conf in just one place already, by using `coc#config` from `.vimrc`.

**Comment by sumnerevans** [comment]
How would the `"extensions"` field work in project-specific `coc-settings.json` files?

**Comment by richtong** [comment]
> > @bigzhu It is just a suggestion which has not been implemented.
> 
> I use `g:coc_global_extensions` it is work fine
> 
> ```viml
> let g:coc_global_extensions = [
>       \'coc-markdownlint',
>       \'coc-highlight',
>       \'coc-vetur',
>       \'coc-go',
>       \'coc-python',
>       \'coc-explorer',
>       \'coc-flutter', 
>       \'coc-json', 
>       \'coc-git'
>       \]
> ```

Wow that's great, wish it was in the main documentation :-)

**Comment by Archie-2021** [comment]
> > @bigzhu It is just a suggestion which has not been implemented.
> 
> I use `g:coc_global_extensions` it is work fine
> 
> ```viml
> let g:coc_global_extensions = [
>       \'coc-markdownlint',
>       \'coc-highlight',
>       \'coc-vetur',
>       \'coc-go',
>       \'coc-python',
>       \'coc-explorer',
>       \'coc-flutter', 
>       \'coc-json', 
>       \'coc-git'
>       \]
> ```

I am trying to set it up like this but apparently doesn't install automatically. should I run a commmand after each update? Like how vimplug works for example? I tried ':CocInstall' but nothing happened.

**Comment by chemzqm** [comment]
Restart vim after set `let g:coc_global_extensions`

**Comment by Archie-2021** [comment]
> Restart vim after set `let g:coc_global_extensions`

thanks

**Comment by d3vus** [comment]
Hi @bigzhu, Can you please suggest how can I write it in lua so that i can use in my neovim config.

**Comment by jdandrea** [comment]
Building off the [suggestion](#issuecomment-548738671) @adoyle-h made, perhaps there could be a way to selectively activate/deactivate CoC extensions based on the active file extensions, just like at the `vim-plug` level. (Unless this already exists and I'm just missing it.)

```
{
  "extensions": {
    "coc-EXTENSION": {
      "version": "X.Y.Z",
      "filetypes": ["TYPE1", "TYPE2", ...]
    }
  }
}
```
