### ISSUE TITLE
CocList ignores some options

### ISSUE THREAD

**Issue by TxHawks** [neoclide/coc.nvim#561]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.8.0
coc.nvim version: 0.0.61
term: iTerm.app
platform: darwin

## Error messages
```

**Describe the bug**
CocList ignores some of the options passed to it. For instance, `CocList files --normal --top --autopreview` will start in normal mode, as per `--normal`, but at the bottom and without the preview window.

**Comment by chemzqm** [comment]
`CocList files --normal --top --autopreview` to have to be `CocList --normal --top --autopreview files`.
Should have some warnings for that.

**Comment by TxHawks** [comment]
Tried that as well... Still same result

**Comment by chemzqm** [comment]
There's no `--autopreview` option, you should use `--auto-preview`

**Comment by chemzqm** [comment]
It throw error for invalid options.

**Comment by TxHawks** [comment]
oops... sorry
