### ISSUE TITLE
CocList grep doesn't work

### ISSUE THREAD

**Issue by TxHawks** [neoclide/coc.nvim#562]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.8.0
coc.nvim version: 0.0.61
term: iTerm.app
platform: darwin

## Error messages
```

**Describe the bug**
`CocList grep` generates an empty list

**To Reproduce**

1. install `coc-lists`
2. cd to a directory that has files in it
3. `:CocList grep`
4. Get unpopulated list

**Screenshots**
<img width="404" alt="Screen Shot 2019-03-20 at 10 07 27" src="https://user-images.githubusercontent.com/5658514/54668636-018eee80-4af8-11e9-8cef-694bb3fecd60.png">

**Comment by chemzqm** [comment]
You must provide `--interactive` for interactive grep.

**Comment by TxHawks** [comment]
Tried that. Unfortunately, it yields the same result:
![Screen Shot 2019-03-20 at 10 37 05](https://user-images.githubusercontent.com/5658514/54670392-3d2bb780-4afc-11e9-9972-4a537b7d0515.png)

**Comment by chemzqm** [comment]
@TxHawks it's expected, you need to provide input by type character.

**Comment by TxHawks** [comment]
Thanks!
 I expected to see `1/{number of files in the directory}`.
