### ISSUE TITLE
Allow switching between matching modes in lists

### ISSUE THREAD

**Issue by TxHawks** [neoclide/coc.nvim#563]
**Is your feature request related to a problem? Please describe.**
I'd like to set key mappings for common tasks, like opening files or grepping. Most of the times, I want results to be fuzzy matched, but depending on the context, I sometimes want results to be strict or to use a regex. I'd like to avoid having to set up different mappings for different matching strategies.

**Describe the solution you'd like**
I'd like to be able to set the matching strategy as an action

**Describe alternatives you've considered**
As mentioned above, I could set extra mappings or call the command directly, but this is cumbersome.
fzf offers the use of `'` to signal strict matching:
`soPa` -> matches **so**me**Pa**ttern 
`'soPa' -> matches **soPa**ttern but not somePattern

**Comment by chemzqm** [comment]
You mean the ability to switch the match mode for filter after list is opened, is that right?

**Comment by TxHawks** [comment]
Yes, exactly

**Comment by TxHawks** [comment]
This is great. Thank you!

**Comment by balta2ar** [comment]
@chemzqm One little downside that ruins experience is that

1. filtering mode is not saved between calls to CocList -- if I switch from fuzzy to strict, quit CocList, and open it again, the mode is gonna be fuzzy again
2. filtering mode is not saved when navigating between menus, e.g. if you open CocList, switch to strict, select "extensions", it's gonna be fuzzy again.

**Comment by chemzqm** [comment]
It's not designer to be persist, use list options for default match mode.
