### ISSUE TITLE
Add PHP, C#, C++ support

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#565]
Do you plan to add one of these vscode extensions (like coc-rls, coc-java...) in the near future?

https://github.com/OmniSharp/omnisharp-vscode
https://github.com/Microsoft/vscode-cpptools

**Comment by chemzqm** [comment]
I plan to migrate those extensions:

https://github.com/Microsoft/vscode-python
https://github.com/MaskRay/vscode-ccls
https://github.com/Microsoft/vscode-go

I've checked vscode-cpptools, it's powerful but too complicated to migrate.
For omnisharp-vscode, it's also not easy to migrate and I don't know how many people use vim for C#.

**Comment by mihaelartz** [comment]
@chemzqm What do you think about this extension? This is very, very small extension, has about 650+-50 lines of code, can you add it? Definitely the best vscode php extension.

**Comment by iamcco** [comment]
@mihaelartz there is already an extension for that

**Comment by iamcco** [comment]
https://www.npmjs.com/package/coc-phpls

**Comment by mihaelartz** [comment]
@iamcco Yes, coc-phpls, but there are some problems like: uses the old version of intelephense, no caching, no index on workspace change, old intelephense version not intended for standalon usage... Sorry for my bad English.

**Comment by tomspeak** [comment]
Would be amazing to have `coc-phpls` brought up to speed. Ditching PHPStorm would be fantastic.

**Comment by fannheyward** [comment]
@chemzqm I don't think it's necessary to migrate `vscode-go`, maybe you can make it lower priority. Since go team is working official language server, `gopls`, which is 60-70% completion. Also there is another language server `bingo`, which is equal to gopls + tools. The only advantage of vscode-go is debug, but I think it's not very easy to migrate for coc+vim.

The most needed extension IMO is `vscode-python`, pyls is not working very well for large project, MSPYLS is the key tool for Python development.

Thanks for your work.

**Comment by taigacute** [comment]
> @chemzqm I don't think it's necessary to migrate `vscode-go`, maybe you can make it lower priority. Since go team is working official language server, `gopls`, which is 60-70% completion. Also there is another language server `bingo`, which is equal to gopls + tools. The only advantage of vscode-go is debug, but I think it's not very easy to migrate for coc+vim.
> 
> The most needed extension IMO is `vscode-python`, pyls is not working very well for large project, MSPYLS is the key tool for Python development.
> 
> Thanks for your work.

agree. Google will fully promote `gopls`, the current `vscode-go` ` gotools` and `vim-go  gotools`  no different. The adaptation of vscode to gocode which provides the `go.autobuildonsave` option.

**Comment by artkpv** [comment]
@chemzqm 
> For omnisharp-vscode, it's also not easy to migrate and I feel that rarely people use vim for C#.

Well, I want to use vim for C#. Not easy task to make it some IDE though.

**Comment by martin-braun** [comment]
@chemzqm Is it possible to use the language server of vscode-cpptools via `languageserver` option in the `coc-settings.json`? I know that it will only provide linting and no extensive features, but my current problem is that I have to edit a cpp project for a different target platform and ccls and clang are too strict and complaining about errors that are none on the target platform.

I had the very best result by using Microsoft's own Cpp tools, despite it being closed-source, which is just a shame. Their plugin seems to scan the directory and assumes things in a broad fashion that allows to avoid false errors for my target platform somehow.

**Comment by fannheyward** [comment]
@martin-braun from https://github.com/microsoft/vscode-cpptools/blob/27cd52a1b95afb3eeda4d9404813a20285483de4/Extension/src/LanguageServer/client.ts#L1592-L1595 , I think it's possible to run `cpptools` bin by `languageserver` command mode, you need to get the full path to cpptools bin.
