### ISSUE TITLE
Create videos of workflows

### ISSUE THREAD

**Issue by tomspeak** [neoclide/coc.nvim#567]
**Is your feature request related to a problem? Please describe.**
I think CoC is by far one of the best plugins I have used, and I feel that I am using about 10% of its power. The documentation is good, but it's quite hard to understand the _why_ in some of the features.

**Describe the solution you'd like**
A set of short videos explaining some of the core features via real day to day use case.

I think a few minutes of video could be worth pages of documentation. 

https://github.com/Shougo/deoplete.nvim - Deoplete uses wildly varying quality GIFs to convey some of its features.

**Describe alternatives you've considered**
Overhauling the documentation to sell features from a _why_ stand point, rather than a raw explanation. 

**Additional context**
We discussed this briefly on Gitter, wanted to add this for permanence.

**Comment by tomaskallup** [comment]
I'd actually be interested in this. I use coc every day and I feel like I use quite a few of the features.
The main problem is the format of videos, I feel like me talking would end up in a horrible unwatchable video and combining text screens with short clips is probably not the solution
Also this could split into 2 parts:

1. Short videos/gifs for every feature/command
2. Some longer video(s) with the actual workflow - basically 1 but composed as longer videos.

Maybe even videos for configurations part - how to (un)install extesions, opening & editting settings etc.

**Comment by chemzqm** [comment]
There're some videos on youtube, like https://www.youtube.com/watch?v=gnupOrSEikQ&feature=youtu.be&t=389
