### ISSUE TITLE
Create release and development versions AUR packages

### ISSUE THREAD

**Issue by gbrlsnchs** [neoclide/coc.nvim#568]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an easy way to install a release or development version of coc.nvim from Arch Linux's AUR.

**Describe the solution you'd like**
Release is packaged in AUR as `coc-nvim` and development version packaged as `coc-nvim-git`.

**Describe alternatives you've considered**
I currently install it via `vim-plug`, but just like FZF, I'd rather install it from outside Vim.

Maybe it's overkill, but still helpful. Thanks anyway!

**Comment by gbrlsnchs** [comment]
According to #626, there won't be any binary distributions anymore, thus rendering this issue useless. Using a Vim plugin manager is the de facto way of managing coc.nvim versions now.

**Comment by chemzqm** [comment]
Unlike fzf, coc.nvim can't work with the binary only, while the binary is big and can't load extensions that use addons build by node-gyp.

**Comment by gbrlsnchs** [comment]
Fair enough. Thanks!

**Comment by sainnhe** [comment]
I just added [4 packages](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=vim+coc&outdated=&SB=l&SO=d&PP=50&do_Search=Go) to AUR, including development version and stable release for vim & neovim.
