### ISSUE TITLE
UltiSnip auto-exansion not woking if autocomplete is visible

### ISSUE THREAD

**Issue by albertorestifo** [neoclide/coc.nvim#572]
**Result from CocInfo**

```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.61
term: xterm-256color
platform: linux

## Error messages

## Output channel: prettier

## Output channel: highlight
[Info  - 11:56:23] Highlight server running in node v8.9.0
```

**Describe the bug**

I have a UltiSnip set to autoexpand. If the Coc compeltion menu is open, the autoexpansion doesn't work.

I can however press `<C-y>` to accept the snippet suggestion.

Also, if I press backspace and insert the last letter of the snippet, the autocomplete menu won't show up (expected behavior) and the snippet correctly expands.

**To Reproduce**

1. Have UltiSnip installed, with an auto-expand snippet configured
2. Try triggering the snippet
3. Press backspace to delete the last letter of the snippet
4. Type again that letter

**Screenshots**

To reproduce the below recording, I created the follwing snippet:

```
snippet demo "Bug demo snippet" bA
Hello,
My snippet correctly auto-expanded.
endsnippet
```
And did not press any shortcuts other than typing the characters and pressing backspace.

[![asciicast](https://asciinema.org/a/jKEsiKRxCxWACP71r4BJ2iFr3.svg)](https://asciinema.org/a/jKEsiKRxCxWACP71r4BJ2iFr3)

**Comment by chemzqm** [comment]
It's limitation of ultisnips, https://github.com/SirVer/ultisnips/pull/986

https://github.com/neoclide/coc-snippets support trigger auto trigger snippet on TextChangedP.

**Comment by albertorestifo** [comment]
Amazing, thanks for the pointers!
