### ISSUE TITLE
CocLocations + ccls reordering `:jumps` improperly

### ISSUE THREAD

**Issue by lanza** [neoclide/coc.nvim#576]
Imagine a C++ class hierarchy `C -> B -> A` where `->` denotes inheritance. Starting at 

    class C : public B {

use `<Plug>(coc-definition)` to go to `B` 

    class B : public A {

and then again to go to `A`. 

    class A {

Now use `ctrl-o` to jump back to `B`. 

    class B : public A {

Your `:jumps` should be 

    1 C
    0 B
    1 A

Now, use a `CocLocation` call to jump to another target, e.g. I'll use `:call CocLocation('ccls', '$ccls/member')<cr>` to jump to a member variable defined in `B.` At this point, your jumplist has been screwed up and is now

    3 C
    2 A
    1 B
    0 the member variable you just jumped to

The jumplist element pointing to `A` was moved above `B` due to calling `CocLocations`. 

I was able to reproduce this in both `vim` and `neovim`.

**Comment by chemzqm** [comment]
That's how jumps of vim works, what would you expect?

**Comment by lanza** [comment]
I guess I didn't explain it well enough. Look at how the first chunk of code I wrote to display the jumplist has the order CBA with the current location being at B. 

If you do another jump normally (e.g. via (coc-definition)) the order becomes CBD with the current location becoming D. A is removed from the list and D is appended. 

What's happening here is that `CocLocations(ccls...)` to D is somehow inserting A before B so you get CABD with location D.

**Comment by chemzqm** [comment]
The handler code for `coc-definition` and `CocLocations` are same, when should be the jump item removed is managed by vim, coc only use `m'` to add current location to jumplist before jump.

**Comment by lanza** [comment]
Hmm, I'll see if I can look into this myself. Can you point me to the chunk of code responsible for the CocLocation command as well as the code that runs when you select an entry in the CocLocation list?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/blob/master/src/workspace.ts#L629

I can just reproduce it by use `m'` and `cursor()` function.

**Comment by lanza** [comment]
@chemzqm Would `keepjumps normal m'` be sufficient for coc.nvim's usages?

**Comment by garfunklett** [comment]
I got the same problem. I think it is a conflict with someother plugin or init_settings. Have not figured it out yet.

**Comment by garfunklett** [comment]
still got the same problem even when I uninstall all the other vim-plugins, and mute all the vimrc settings. Currently, I am using neovim 0.4.2 + Coc (commit 3578ab5507b2c358ccd685b8c28229ecf4cf2433) + ccls (tried both homebrewed and manually compiled) Everything except this Ctrl+o issue is just fantastic. Really want this get fixed.

**Comment by chemzqm** [comment]
It's vim's behavior, can't help

**Comment by garfunklett** [comment]
can we use tag stack instead of jumplist? I think tag stack's behavior might make more sense for cross-reference code browsing.

**Comment by chemzqm** [comment]
Vim's tag is used for definition location and it can't work with location list, I use coc list for references

**Comment by garfunklett** [comment]
I see. thx

**Comment by tammersaleh** [comment]
I believe I have this working by manually manipulating the tag stack.  I got most of the code from `:h tagstack-examples`:

``` viml
function! s:coc_definition_with_tag_list()
  " Cribbed from :h tagstack-examples
  let tag = expand('<cword>')
  let pos = [bufnr()] + getcurpos()[1:]
  let item = {'bufnr': pos[0], 'from': pos, 'tagname': tag}
  call CocActionAsync('jumpDefinition')
  " Jump was successful, write previous location to tag stack.
  let winid = win_getid()
  let stack = gettagstack(winid)
  let stack['items'] = [item]
  call settagstack(winid, stack, 't')
endfunction
```

The only weird bit is that I don't believe that `CocActionAsync('jumpDefinition')` returns different values if it's successful or not - it'd be nice to wrap that in an `if` like the example.  I suppose I could test that `pos` didn't change, but that's a tad beyond my vim skills.

**Comment by lanza** [comment]
This is fixed in neovim master. Helpgrep jumpoptions or something like that.

**Comment by tammersaleh** [comment]
Actually, it turns out I should have been using `CocAction()` instead of `CocActionAsync` 😬 This code works a charm:

``` vimscript
function! s:coc_definition_with_tag_list() abort
  " Cribbed from :h tagstack-examples
  let tag = expand('<cword>')
  let pos = [bufnr()] + getcurpos()[1:]
  let item = {'bufnr': pos[0], 'from': pos, 'tagname': tag}
  if CocAction('jumpDefinition')
    " Jump was successful, write previous location to tag stack.
    let winid = win_getid()
    let stack = gettagstack(winid)
    let stack['items'] = [item]
    call settagstack(winid, stack, 't')
  endif
endfunction

```

**Comment by mikaelmedina** [comment]
> Actually, it turns out I should have been using `CocAction()` instead of `CocActionAsync` 😬 This code works a charm:
> 
> ```viml
> function! s:coc_definition_with_tag_list() abort
>   " Cribbed from :h tagstack-examples
>   let tag = expand('<cword>')
>   let pos = [bufnr()] + getcurpos()[1:]
>   let item = {'bufnr': pos[0], 'from': pos, 'tagname': tag}
>   if CocAction('jumpDefinition')
>     " Jump was successful, write previous location to tag stack.
>     let winid = win_getid()
>     let stack = gettagstack(winid)
>     let stack['items'] = [item]
>     call settagstack(winid, stack, 't')
>   endif
> endfunction
> ```

Commenting three years after the fact to say that this is exactly what I had been looking for, i was a couple failed google queries away from writing it myself, thank you 👍
