### ISSUE TITLE
echo exists('##MenuPopupChanged') && exists('*nvim_open_win') return 0

### ISSUE THREAD

**Issue by Joellidin** [neoclide/coc.nvim#579]
**Result from CocInfo**

```bash
## versions

vim version: NVIM v0.4.0-dev
node version: v8.9.0
coc.nvim version: 0.0.61
term: xterm-kitty
platform: darwin

## Error messages

## Output channel: snippets

## Output channel: highlight
[Info  - 20:50:48] Highlight server running in node v8.9.0
```

**Describe the bug**
I am trying to follow the [F.A.Q](https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-make-preview-window-shown-aside-with-pum) to get the floating windows but when typing `:echo exists('##MenuPopupChanged') && exists('*nvim_open_win')` it echoes `0`. I have searched for a fix for this for a while but I can't find anything. So I was hoping anyone here could help me.

**Edit:** I have noticed that `call CocAction('doHover')` does not work when trying to show documentation. I recently switched from vim to Neovim. Might there be an issue with how I have things set up?

**Comment by iamcco** [comment]
update your neovim

**Comment by chemzqm** [comment]
You have to use nightly build.
