### ISSUE TITLE
Hide virtual text diagnostic when floating diagnostic is open

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#580]
The virtual text should be cleared when the floating diagnostic is open and restored when the float is closed

![Screenshot_20190322_181319](https://user-images.githubusercontent.com/29133776/54855921-98150880-4cce-11e9-8eeb-7b19df4b37b0.png)

**Comment by oblitum** [comment]
Personally I'm don't like this idea, it generates noise/distraction when hovering cursor and multiple stuff are turned ON and OFF.

**Comment by Avi-D-coder** [comment]
I was going to implement this, but I'll wait to hear other opinions.

**Comment by comfortablynick** [comment]
I like this idea too; it could at least be an option. Before Coc I was using ALE virtual text and I like it for some things, but also really like the pum we have now.

**Comment by chemzqm** [comment]
> the float is closed

But there's no way to detect window close for now, it could be closed by user or neovim for some reason.

**Comment by chemzqm** [comment]
The real problem is why you still want to use virtual text when you already have floating window?
There would a lot flicking if we hide and show the virtual text on floating window change.

**Comment by Avi-D-coder** [comment]
@chemzqm virtual text is still useful for knowing what errors are present at a glance.

For the time being there don't seem to be enough of us wanting this feature to go thru with it.
