### ISSUE TITLE
Highlight backticked blocks in diagnostics.

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#581]
It would be great if something like `ropey::iter::Lines<'_>: std::clone::Clone` was highlighted as the buff filetype.
```
 [rustc E0277] [E] the trait bound `ropey::iter::Lines<'_>: std::clone::Clone`  
 is not satisfied                                                               
                                                                                
 the trait `std::clone::Clone` is not implemented for `ropey::iter::Lines<'_>`  
                                                                                
 note: required because of the requirements on the impl of `std::clone::Clone`  
 for `std::iter::Enumerate<ropey::iter::Lines<'_>>`
```

**Comment by oblitum** [comment]
Backquotes are not guaranteed as a idiom for quoting code, rust compiler may do that, others may use it for other things, which would make their highlighting broken. This is some hard-coded requested.

**Comment by Avi-D-coder** [comment]
@oblitum a config whitelist could be added.

**Comment by oblitum** [comment]
@Avi-D-coder IMO, needless complexity.

**Comment by Avi-D-coder** [comment]
@oblitum It's only needless for people who would not use it. 
When staring at a multi line rust type error I would find highlighting very useful.

**Comment by oblitum** [comment]
@Avi-D-coder I'm just pointing that it brings a lot of variables:

- can provide broken highlighting
- needs new configurable options
- needs flag for enabling/disabling
- needs syntax awareness, since backticks (or other character) can be part of code comments and strings, or even syntax.
- I don't know but there may be more.

**Comment by Avi-D-coder** [comment]
Just enable markdown float highlights for diagnostics of lsps known to produce markdown like diagnostics.

**Comment by oblitum** [comment]
@Avi-D-coder ok, so it's not buff filetype highlight anymore, it's markdown highlight. That's better as an option for the user to do then, or coc extensions, not case by case.

**Comment by oblitum** [comment]
@Avi-D-coder your original error message is not proper markdown, so it's broken as markdown already.

**Comment by Avi-D-coder** [comment]
@oblitum Miscommunication. I always intended only code blocks be highlighted. E.g:`ropey::iter::Lines<'_>: std::clone::Clone`
The diagnostic buffer should not be set to markdown. Only the code blocks would be highlighted just as how code blocks are highlighted in markdown.

**Comment by oblitum** [comment]
@Avi-D-coder doesn't make sense for me, backtick quotation is proper of markdown, and it happens on  the outside of the code, not the inside, do you want the inside as markdown highlight not code highlight? If you want it as markdown highlight, doesn't seem useful, if you want it as code highlight, backticks quotes are not part of that syntax, it's part of the outer syntax, and still needs to be handled.

**Comment by Avi-D-coder** [comment]
@oblitum `ropey::iter::Lines<'_>: std::clone::Clone` should be highlighted as rust in the following, just as it would be if the whole diagnostic was markdown.
```
 [rustc E0277] [E] the trait bound `ropey::iter::Lines<'_>: std::clone::Clone`  
 is not satisfied                                                               
                                                                                
 the trait `std::clone::Clone` is not implemented for `ropey::iter::Lines<'_>`  
                                                                                
 note: required because of the requirements on the impl of `std::clone::Clone`  
 for `std::iter::Enumerate<ropey::iter::Lines<'_>>`
```

**Comment by oblitum** [comment]
@Avi-D-coder I'm trying to tell you, if the whole diagnostics was markdown, it would be broken as markdown, so it's not markdown. It's a coincidence that your diagnostics and markdown use the same backticks for code spans, but Markdown already have parsers and proper a stable syntax, your diagnostics, and even less many others, don't. Your comparison of diagnostics output to Markdown seems as a tentative to make things simple but it doesn't make sense, it makes less sense than for docstrings which already easily get broken, diagnostics output vary widely and often have zero resemblance to Markdown. Again, if it's to go about having a proper syntax for quotes, some non-trivial and flexible syntax (not Markdown) will have to be assumed.

**Comment by Avi-D-coder** [comment]
@oblitum Care to shed some light on why the provided diagnostic would be broken with the rule highlight as `&filetype` anything in outer pair of backticks?

Yes, not all servers use backticks, so this won't work for all language servers. A config map between language and regexes for finding code blocks in diagnostics would be an end goal, however since the code for backticks already exists for markdown, highlighting in diagnostics like the one provided is relatively easy.

**Comment by oblitum** [comment]
@Avi-D-coder I just said it is broken if viewed as Markdown, not as simply considering just quotes. I didn't say it's broken when considering just quotes, I said it's very easy to get broken for reasons already explained. Another thing to the list is that I suppose it's not as easy to highlight fragments as `filetype`, I know that exist just a few plugins that mix highlight like that.

**Comment by chemzqm** [comment]
Will not add highlight for specific characters in diagnostics.

* If you need highlight for errors, run your compiler in terminal with ansi support.
* It's hard to recompute the positions for highlights, while it's not really necessary.
* We don't know the text & background color of diagnostic text, it's hard to make the highlight looks nice.
