### ISSUE TITLE
incorect floating highlight for js and ts

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#582]
vim version: NVIM v0.4.0-430-g8698830cb
node version: v11.12.0
coc.nvim version: 0.0.61
term: xterm-256color
platform: linux

![Screenshot_20190322_182937](https://user-images.githubusercontent.com/29133776/54856398-bd0a7b00-4cd0-11e9-9bf0-fc6375b729f5.png)

**Comment by chemzqm** [comment]
Can't fix, no way to detect screen scroll.

**Comment by Avi-D-coder** [comment]
What do you mean by screen scroll?
Thanks

**Comment by chemzqm** [comment]
If it's not caused by scroll, please provide minimal vimrc to reproduce the problem.

**Comment by Avi-D-coder** [comment]
@chemzqm Try adding https://github.com/jparise/vim-graphql.

**Comment by chemzqm** [comment]
Got the reason, it doesn't check global variable existance in syntax file.

```
let s:tags = '\%(' . join(g:graphql_javascript_tags, '\|') . '\)'
```

coc only load syntax files for highlight, so it throws.
