### ISSUE TITLE
Error when change filename e.g. main.ts => Main.ts

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#584]
Hello!

When change filename from NerdTree like in example main.ts => Main.ts i get a error message:
![2019-03-23-155847_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/54867791-c8b77980-4d84-11e9-8474-9b4f0a634bfc.png)

**Comment by chemzqm** [comment]
It's nerdtree's problem that it prevent BufUnload event on file rename, so coc can't detect the rename.

The issue doesn't exists when you rename the file in shell.
