### ISSUE TITLE
Something like split-if-not-open for coc.preferences.jumpCommand

### ISSUE THREAD

**Issue by damnever** [neoclide/coc.nvim#586]
I want to split the window only if the target is not in the open files, none of `edit`, `split`, `vsplit`, `tabe`, `drop` and `tab drop` can make it done right, could we supply an option to do that?

**Comment by chemzqm** [comment]
> the target is not in the open files

What does open means? Buffer loaded or shown in window?

**Comment by chemzqm** [comment]
Try use `<C-o>` and `<C-i>` for jump list.

**Comment by damnever** [comment]
Jump to definition will split the window if I using `coc.preferences.jumpCommand="split"` and the definition already in the open files.

I only want to split the window if the definition is not in the open files.

**Comment by chemzqm** [comment]
You can use drop if you want to use exists windows, it  doesn't split but reuse current window so you can make use of jump list.

The behavior is not hard to implemented but I don't think it's necessary.

**Comment by damnever** [comment]
Yeah, but sometimes reopens the old one and closes the new one drive me crazy...

**Comment by chemzqm** [comment]
You can use `:bd` or use plugin like https://github.com/moll/vim-bbye if you want to remove current buffer and jump to previous one.

**Comment by chemzqm** [comment]
`split-if-not-open` could be confusing, you can create your own command for open files, and set it to `"coc.preferences.jumpCommand"`

**Comment by ramsgoli** [comment]
@damnever I too had the same wish and figured out a solution that I wrote about here https://ramgo.li/posts/coc.nvim_split_if_not_open/ 😄

**Comment by damnever** [comment]
@ramsgoli Thanks a lot! 👍 

I modified it to suit my need 😅 
```vim
function! CocSplitIfNotCurrentFile(call, fname)
    if a:fname != fnamemodify(expand('%'), ':p:~:.')
        exec 'split '.a:fname
    endif
    exe a:call
endfunction
```

**Comment by jack0son** [comment]
> @damnever I too had the same wish and figured out a solution that I wrote about here https://ramgo.li/posts/coc.nvim_split_if_not_open/

This function kept giving me a "not enough arguments" error when there were multiple definitions (causing the locations list to open), for example in a destructured require in Nodejs.

I modified it to detect which arguments were available, similar to @damnever's solution, which seems to fix the problem.

```vimscript
function! SplitIfNotOpen(...)
	let fname = a:1
	let call = ''
	if a:0 == 2
		let fname = a:2
		let call = a:1
	endif
    let bufnum=bufnr(expand(fname))
    let winnum=bufwinnr(bufnum)
    if winnum != -1
	" Jump to existing split
	exe winnum . "wincmd w"
    else
	" Make new split as usual
	exe "vsplit " . fname
    endif
    " Execute the cursor movement command
    exe call
endfunction

command! -nargs=+ CocSplitIfNotOpen :call SplitIfNotOpen(<f-args>)
```

**Comment by casprwang** [comment]
@jack0son Nice! 

It can be mapped with `:call CocAction('jumpDefinition')`. Works like a charm!

**Comment by Iceber** [comment]
@jack0son Hello, I am a beginner, how do I use this function?

**Comment by Iceber** [comment]
> > @damnever I too had the same wish and figured out a solution that I wrote about here https://ramgo.li/posts/coc.nvim_split_if_not_open/
> 
> This function kept giving me a "not enough arguments" error when there were multiple definitions (causing the locations list to open), for example in a destructured require in Nodejs.
> 
> I modified it to detect which arguments were available, similar to @damnever's solution, which seems to fix the problem.
> 
> ```viml
> function! SplitIfNotOpen(...)
>     let fname = a:1
>     let call = ''
>     if a:0 == 2
> 	let fname = a:2
> 	let call = a:1
>     endif
>     let bufnum=bufnr(expand(fname))
>     let winnum=bufwinnr(bufnum)
>     if winnum != -1
> 	" Jump to existing split
> 	exe winnum . "wincmd w"
>     else
> 	" Make new split as usual
> 	exe "vsplit " . fname
>     endif
>     " Execute the cursor movement command
>     exe call
> endfunction
> 
> command! -nargs=+ CocSplitIfNotOpen :call SplitIfNotOpen(<f-args>)
> ```

@jack0son After jumping in the current file, the cursor is missing, what can be optimized?
