### ISSUE TITLE
Boolean that shows if coc.nvim has been compiled

### ISSUE THREAD

**Issue by alesandar** [neoclide/coc.nvim#587]
For those of us who use the native packaging system, it may be hard to detect if coc.nvim has been compiled (not to be confused with simply being added to the packpath).

Plugin managers provide solutions, such as wrapper functions and hooks, which make the whole process a lot easier, but a single global variable, such as `coc#util#installed` may be very handy to know if it is required to run `coc#util#install`. Is there any other way to do so? Right now, issuing the command will always try to download and recompile the binaries. I was unable to find another method to see if coc.nvim has been actually compiled.

If anyone finds that useful and does not have a better option to perform a similar testcase, I would be glad to make a PR.

**Comment by chemzqm** [comment]
If you're using vim-plug, you should `'tag': '*'` to upgrade only with new release, if you can't, please compile from source code instead.

**Comment by alesandar** [comment]
Thank you, but I was not looking for a solution that requires a package manager.

Actually, I am preparing a setup that will have to be bootstrapped frequently, so I do not really care if there's newer source or not. I am closing the issue, since I have found a way to do what I needed.

```vim
if !filereadable(coc#util#binary())
  call coc#util#install()
endif
```
