### ISSUE TITLE
signatureHelp / floating windows break Undo history

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#588]
**Result from CocInfo**

## versions

vim version: NVIM v0.4.0-426-gfa6ed5f75
node version: v11.12.0
coc.nvim version: 0.0.62
term: tmux-256color
platform: linux

**Describe the bug**
I'm not sure this is a coc.nvim issue or NeoVim. After floating windows for signatureHelp, undo points is getting broken.

**To Reproduce**

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create a minimal mini.vim with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start vim with command: `vim -u mini.vim`

- Start neovim with command: `nvim -u mini.vim`

- Type until a trigger for signatureHelp to pop up

- Press enter for a new line and type anything

- Undo as much as you want, it won't undo the line just added

**Screenshots**

![simplescreenrecorder](https://user-images.githubusercontent.com/1269815/54884198-d0daec00-4e4c-11e9-8eaf-cb98c33438b1.gif)

**Comment by chemzqm** [comment]
It works as expected for me.

**Comment by oblitum** [comment]
Ops, sorry. With minimal `.vimrc` it actually doesn't happen, so, it must related with something else.

**Comment by oblitum** [comment]
Ops, my bad, it's actually reproducing with minimal vimrc.

**Comment by oblitum** [comment]
This is my minimal `.vimrc`:

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !mkdir -p "$HOME/.vim/autoload"
  silent !curl -fLo "$HOME/.vim/autoload/plug.vim" 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
call plug#load('vim-sensible')
Plug 'honza/vim-snippets'
function! PlugCoc(info) abort
  if a:info.status ==? 'installed' || a:info.force
    !yarn install
    if exists('s:coc_extensions')
      call call('coc#add_extension', s:coc_extensions)
    endif
  elseif a:info.status ==? 'updated'
    !yarn install
    call coc#util#update()
  endif
  call PlugRemotePlugins(a:info)
endfunction
let s:coc_extensions = [
\   'coc-pyls',
\   'coc-snippets'
\ ]
Plug 'neoclide/coc.nvim', {'do': function('PlugCoc')}
call plug#end()

augroup vimrc | autocmd! | augroup end

function! s:coc_config() abort
  let root_patterns = ['.vim/', '.git/', '.hg/', '.projections.json']

  let languageservers = {}

  if executable('ccls')
    let languageservers['ccls'] = {
    \   'command': 'ccls',
    \   'filetypes': ['c', 'cpp', 'objc', 'objcpp'],
    \   'rootPatterns': ['.ccls', 'compile_commands.json'] + root_patterns,
    \   'initializationOptions': {
    \     'cache': {
    \       'directory': '/tmp/ccls'
    \     }
    \   }
    \ }
  endif

  if !empty(languageservers)
    call coc#config('languageserver', languageservers)
  endif
endfunction

autocmd vimrc VimEnter * if exists('g:did_coc_loaded') | call s:coc_config() | endif

autocmd vimrc User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
```

**Comment by chemzqm** [comment]
It should be a bug of neovim, but could be avoided by send `<C-g>u` to break the undo chain.

**Comment by oblitum** [comment]
Nice, thanks for the info.
