### ISSUE TITLE
show document at bottom of window(not the top preview)

### ISSUE THREAD

**Issue by IndexXuan** [neoclide/coc.nvim#589]
Great Plugin !
using it to replace my YCM already；Thanks!

**Is your feature request related to a problem? Please describe.**
show document now at the top of the window in termial vim, can be it like tsuquyomi#tooltip show at the bottom of the window ?

**Describe the solution you'd like**
show anything at the bottom of window for better code writing experience

**Additional context**
like https://github.com/Quramy/tsuquyomi#tooltip do

**Comment by chemzqm** [comment]
If the document you mean is signature, you can use `"signature.preferShownAbove": false` in your coc-settings.json, it prefer above by default so you can have it shown when pumvisible most of time, like VSCode.

**Comment by IndexXuan** [comment]
@chemzqm thanks very much. It not works. I mean
```viml
" Use K for show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>
```

In terminal Vim, it always show at the top of the code window, I want is trigger and show info at the bottom of the window, like tsc error or something. any help ?

**Comment by chemzqm** [comment]
>  it always show at the top of the code window

It should be shown below cursor when possible.

>  I want is trigger and show info at the bottom of the window.

I think you need `"coc.preferences.hoverTarget": "echo"`

**Comment by IndexXuan** [comment]
@chemzqm 大佬为何如此优秀，it works
