### ISSUE TITLE
Optimal PHP set up?

### ISSUE THREAD

**Issue by tomspeak** [neoclide/coc.nvim#590]
Hi,

I'm new to PHP and am trying to get my wonderful nvim setup that works with TS, JS & Go to work as well as for PHP.

Could someone share which LS they are using, and maybe some additional plugins, `.vimrc` config, or `coc.vim` config to get a better experience? Thanks.

**Comment by mihaelartz** [comment]
@tomspeak Hello!

This is my Neovim configuration, you have everything here for: PHP, HTML, CSS, JS, TS, RUST, CPP, C
```vim
" ========== Plugins ==========
if !empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
    call plug#begin('~/.config/nvim/plugged')

    " Completion
    if executable('yarn')
        Plug 'neoclide/coc.nvim', { 'do': 'yarn install' }
    endif

    Plug 'jiangmiao/auto-pairs'
    Plug 'mattn/emmet-vim'

    " Navigation
    if executable('ctags')
        Plug 'majutsushi/tagbar'
    endif

    Plug 'scrooloose/nerdtree'
    Plug 'ctrlpvim/ctrlp.vim'

    " Languages
    Plug 'HerringtonDarkholme/yats.vim'
    Plug 'sheerun/vim-polyglot'

    " Interface
    Plug 'vim-airline/vim-airline'
    Plug 'morhetz/gruvbox'

    " Tools
    Plug 'airblade/vim-gitgutter'
    Plug 'tpope/vim-fugitive'
    Plug 'mbbill/undotree'
    Plug 'w0rp/ale'

    call plug#end()
endif

" ========== Settings ==========
set completeopt=noinsert,noselect,menuone
set completeopt-=preview

set clipboard=unnamedplus
set background=dark
set shortmess+=Ic
set shell=bash

set updatetime=200
set laststatus=0
set pumheight=15

set softtabstop=4
set shiftwidth=4
set tabstop=4

set nocursorcolumn
set nocursorline
set smartindent
set autoindent
set noshowmode
set lazyredraw
set nohlsearch
set noswapfile
set noreadonly
set ignorecase
set noshowcmd
set expandtab
set autowrite
set autoread
set nobackup
set hidden
set nowrap
set number

" ========== Maps ==========
imap <expr><cr> pumvisible() ? '<c-y>' : '<cr>'

nmap <silent><c-q> :bp<cr>:bd#<cr>
nmap <silent><c-s> :w<cr>

nmap <c-right> <c-w>l
nmap <c-down> <c-w>j
nmap <c-left> <c-w>h
nmap <c-up> <c-w>k

nmap <s-right> dw
nmap <s-left> dvb

" ========== GitGutter ==========
if globpath(&runtimepath, 'autoload/gitgutter.vim') !=# ''
    nmap <leader>hv <plug>GitGutterPreviewHunk

    nmap <leader>ha <plug>GitGutterStageHunk
    nmap <leader>hr <plug>GitGutterUndoHunk

    nmap <leader>hj <plug>GitGutterNextHunk
    nmap <leader>hg <plug>GitGutterPrevHunk
endif

" ========== UndoTree ==========
if globpath(&runtimepath, 'autoload/undotree.vim') !=# ''
    if has('persistent_undo')
        set undodir=$HOME/.cache/undodir
        set undofile
    endif

    nmap <silent><f5> :UndotreeToggle<cr>

    let g:undotree_SetFocusWhenToggle = 1
    let g:undotree_WindowLayout = 3
endif

" ========== NerdTree ==========
if globpath(&runtimepath, 'autoload/nerdtree.vim') !=# ''
    nmap <silent><c-n> :NERDTreeToggle<cr>

    let NERDTreeAutoDeleteBuffer = 1
    let NERDTreeMinimalUI = 1
endif

" ========== Fugitive ==========
if globpath(&runtimepath, 'autoload/fugitive.vim') !=# ''
    nmap <silent><leader>gs :Gstatus<cr>
    nmap <silent><leader>gd :Gdiff<cr>
endif

" ========== Polyglot ==========
if globpath(&runtimepath, 'ftdetect/polyglot.vim') !=# ''
    let g:polyglot_disabled = [
        \ 'typescript'
        \ ]
endif

" ========== Gruvbox ==========
if globpath(&runtimepath, 'colors/gruvbox.vim') !=# ''
    let g:gruvbox_contrast_dark = 'hard'

    colorscheme gruvbox
    syntax enable
endif

" ========== AirLine ==========
if globpath(&runtimepath, 'autoload/airline.vim') !=# ''
    let g:airline_powerline_fonts = 1
endif

" ========== Python ==========
if globpath(&runtimepath, 'syntax/python.vim') !=# ''
    let g:python_highlight_all = 1
endif

" ========== Tagbar ==========
if globpath(&runtimepath, 'autoload/tagbar.vim') !=# ''
    nmap <silent><f9> :TagbarToggle<cr>
endif

" ========== Emmet ==========
if globpath(&runtimepath, 'autoload/emmet.vim') !=# ''
    augroup Emmet
        autocmd!
        autocmd FileType html,css,php EmmetInstall
    augroup end

    let g:user_emmet_install_global = 0
    let g:user_emmet_mode = 'i'
endif

" ========== CtrlP ==========
if globpath(&runtimepath, 'autoload/ctrlp.vim') !=# ''
    let g:ctrlp_custom_ignore = {
        \ 'file': '\v\.(tar.gz|tar.xz|tar.bz2|tar|zip|rar|iso|jar|dll|exe|so)$',
        \ 'dir': '\v[\/](node_modules|vendor|target|build)|(\.(vscode|git))$'
        \ }
endif

" ========== Coc ==========
if globpath(&runtimepath, 'autoload/coc.vim') !=# ''
    augroup Coc
        autocmd!
        autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
    augroup end

    nmap <silent><leader>dc <plug>(coc-declaration)
    nmap <silent><leader>df <plug>(coc-definition)
    nmap <silent><leader>re <plug>(coc-rename)

    imap <silent><expr><c-space> coc#refresh()

    let g:coc_snippet_prev = '<s-tab>'
    let g:coc_snippet_next = '<tab>'

    let g:coc_global_extensions = [
        \ 'coc-tsserver',
        \ 'coc-phpls',
        \ 'coc-pyls',
        \ 'coc-json',
        \ 'coc-html',
        \ 'coc-css',
        \ 'coc-rls'
        \ ]
    let g:coc_user_config = {
        \ 'coc.preferences.diagnostic.enable': v:false
        \ }
endif

" ========== Ale ==========
if globpath(&runtimepath, 'autoload/ale.vim') !=# ''
    nmap <silent><c-j> <plug>(ale_previous_wrap)
    nmap <silent><c-k> <plug>(ale_next_wrap)

    let g:ale_javascript_eslint_suppress_missing_config = 1
    let g:ale_javascript_eslint_suppress_eslintignore = 1

    let g:ale_rust_cargo_use_clippy = 1
    let g:ale_rust_cargo_use_check = 1

    let g:ale_lint_on_text_changed = 'never'
    let g:ale_lint_on_enter = 0

    let g:ale_sign_warning = '⚠'
    let g:ale_sign_error = '✖'

    let g:ale_linters = {
        \ 'javascript': ['eslint'],
        \ 'typescript': ['tslint'],
        \ 'python': ['flake8'],
        \ 'rust': ['cargo'],
        \ 'cpp': ['gcc'],
        \ 'c': ['gcc']
        \ }
endif

" ========== PHP ==========
if globpath(&runtimepath, 'syntax/php.vim') !=# ''
    augroup PHP
        autocmd!
        autocmd FileType php setlocal iskeyword+=$
    augroup end

    let g:php_var_selector_is_identifier = 1
endif

" ========== GUI ==========
if !empty($NVIM_GUI)
    augroup GUI
        autocmd!
        autocmd VimEnter * GuiFont! UbuntuMono Nerd Font Mono:h13
        autocmd VimEnter * GuiPopupmenu 0
    augroup end
endif
```

Coc settings
```json
{
    "languageserver": {
        "ccls": {
            "command": "ccls",
            "filetypes": ["cpp", "c"],
            "initializationOptions": {
                "index": {
                    "comments": 0,
                    "threads": 2
                },
                "cache": {
                    "directory": "/tmp/ccls"
                }
            }
        }
    }
}
```
In short, I use it 'coc-phpls' for autocompletion (for now), https://github.com/StanAngeloff/php.vim for better syntax highlighting (PHP). I hope your help will help.

Sorry for my bad English.

**Comment by andersevenrud** [comment]
Have you tried these https://github.com/neoclide/coc.nvim/wiki/Language-servers#php ?

I'm using this one https://www.npmjs.com/package/coc-phpls and it seems to work very well for most projects. Having some timeout issues, but I'm thinking this has something to do with permissions or something like that becuase I have vendor stuff living in a docker volume.

**Comment by tomspeak** [comment]
@andersevenrud - cheers, those have helped, unfortunately it does not seem to play well with Laravel. I am learning the framework so it would be extremely helpful to have intelligent auto complete. 

Do you have any experience with that?

**Comment by andersevenrud** [comment]
I've noticed this as well. It seems that I never can get auto-completion deeper than one or two levels at most.

Slim and Symfony seems to work a lot better, so there must be something in the dependency chain that breaks something. I also get a couple of timeouts every now and then.

A couple of things of note is that type hinting in the sources is critical for things to work properly. You can also add phpdoc:

```
class MyClass
{
  /** @var \Namespace\Some\Other\Class $reference */
  private $reference;
}
```

This is probably one of the reasons why it's a bit of a struggle on Laravel, because there's a lot of "magic methods" and such.

**Comment by jonleopard** [comment]
Has anyone figured out how to properly handle *.blade.php files? I was using prettier for code formatting, but its doing a horrible job. Will [coc-phpls](https://www.npmjs.com/package/coc-phpls) format?

**Comment by andersevenrud** [comment]
@jonleopard I'm using https://github.com/jwalton512/vim-blade with https://github.com/alvan/vim-closetag

```
let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.blade.php"
autocmd BufNewFile,BufRead *.blade.php set ft=blade
```

**Comment by andersevenrud** [comment]
Just expanding on my previous comment

> A couple of things of note is that type hinting in the sources is critical for things to work properly. You can also add phpdoc:

Using the same docblocks that phpStorm generates, autocompletion in models works pretty good.

Example:

```
/**
 * App\Article
 *
 * @property integer $id
 * @property string $type
 * @property string $title
 * @property string $body
 * @property \Illuminate\Database\Eloquent\Collection|\App\Publisher[] $publishers
 * @property \Illuminate\Database\Eloquent\Collection|\App\Tag[] $tag
 * @property-read \Carbon\Carbon $created_at
 * @property-read \Carbon\Carbon $updated_at
 * @property-read \Carbon\Carbon $deleted_at
 * @mixin \Eloquent
 * @package App
 */
class Article extends Model
{
    use SoftDeletes;

    /**
     * @var array
     */
    protected $fillable = [
        'type',
        'title',
        'body'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function publishers()
    {
        return $this->belongsToMany(Publisher::class)
            ->orderBy('order')
            ->withPivot('type');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
}

```

**Comment by tomspeak** [comment]
Is there an easy way to generate these blocks within vim?

**Comment by andersevenrud** [comment]
I found this while researching this subject https://github.com/barryvdh/laravel-ide-helper . Been a bit busy until today, so haven't tested it yet -- but it looks like it will do the job :)

**Comment by andersevenrud** [comment]
The ide-helper can probably be combined with https://github.com/noahfrederick/vim-laravel , but I don't really mind writing `:!php artisan` when doing things, heh.

**Comment by andersevenrud** [comment]
>  Been a bit busy until today, so haven't tested it yet 

I just did and it adds the docblock for the Model Class just as advertised :raised_hands:

**Comment by aareman** [comment]
One issue I had with using the php intelephense with coc was the it would autocomplete an extra $ for variables

example:

```php
$message = "";
$hello = $mes<tab>
// gave me 
$hello = $$message;
```

I fixed this with the following autocommand in my init.nvim
`autocmd BufNewFile,BufRead *.php set iskeyword+=$`

in case its helpful

**Comment by chemzqm** [comment]
Use `autocmd FileType php set iskeyword+=$`

**Comment by codeclem** [comment]
I'm using laravel-ide-helper and coc-phpls but it still complains about relationship methods (like $article->tags()) not existing. Any ideas?

**Comment by andersevenrud** [comment]
@codeclem Are you using docblocks on your class methods ?

**Comment by codeclem** [comment]
Like this?

`/**
 * App\Models\User
 *
 * @property int $id
 * @property string $name
[snip]
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\User whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'api_token'
    ];

    /**
     * Comments
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany|\App\Models\Comment
     */
    public function comments()
    {
        return $this->hasMany('App\Models\Comment');
    }`

Still doesn't work.

**Comment by andersevenrud** [comment]
@codeclem Indeed. That should be enough. Does anything else work ?

Have you tried to [troubleshooting tips](https://github.com/neoclide/coc.nvim#trouble-shooting) ? Might be some errors occurring on the back end.

**Comment by codeclem** [comment]
Seems to have started working now. Not sure why it wasn't before, thank you.

**Comment by codeclem** [comment]
Sorry.. it looks like specifically it's not working when using helpers. Like in this line:
`$tags = auth()->user()->tags()->with('posts', 'posts.user', 'posts.tags')->get();`

It complains about `->tags()`

**Comment by andersevenrud** [comment]
@codeclem 

> It complains about ->tags(). But it works if I replace auth()->user() with Auth::user()

I see. The laravel-ide-helper package should generate documentation to make `auth()`  autocomplete just as using `Auth::` would. The only suggestion I can come up with on top of my head is to try re-generating the phpDoc for Laravel Facades.

**Comment by vivoconunxino** [comment]
> Hi,
> 
> I'm new to PHP and am trying to get my wonderful nvim setup that works with TS, JS & Go to work as well as for PHP.
> 
> Could someone share which LS they are using, and maybe some additional plugins, `.vimrc` config, or `coc.vim` config to get a better experience? Thanks.

Give a try to phpactor, there's also a coc-extension
