### ISSUE TITLE
Popup windows with syntax coloring

### ISSUE THREAD

**Issue by diego898** [neoclide/coc.nvim#591]
I am using the latest neovim built from source, and coc.nvim. Is it possible to have both popup windows syntax colored somehow? 

![image](https://user-images.githubusercontent.com/742407/54926365-2dd2b280-4ede-11e9-88fd-c82d6d3072cd.png)

**Comment by chemzqm** [comment]
Checkout error log, looks like the highlight failed.
Possible reason is neovim throw error when loading syntax files.

**Comment by diego898** [comment]
Hey @chemzqm, I `export NVIM_COC_LOG_LEVEL=debug` and ran nvim and reproduced the above error. Now, there are the following files in `/tmp/coc-*`:

```
-rw-r--r-- 1 182K Mar 25 10:10 /tmp/coc-nvim.log
-rw-r--r-- 1  567 Mar 25 10:08 /tmp/coc-2260.vim
-rw-r--r-- 1 1.1M Mar 25 10:07 /tmp/coc-nvim.log.1
-rw-rw-rw- 1 1.2M Mar 25 10:07 /tmp/coc-nvim.log.2
```

which file should I upload/paste?

**Comment by chemzqm** [comment]
/tmp/coc-nvim.log

**Comment by diego898** [comment]
https://pastebin.com/BCJE1CCZ

**Comment by chemzqm** [comment]
> Error: request nvim_ui_attach - No such UI option: ext_hlstate

Looks like your executable nvim point to old version of neovim.

**Comment by diego898** [comment]
hm - I compiled neovim from source, and put it in my `~/bin/neovim` directory, and alaised `vim=~/bin/neovim/bin/nvim`. The version of neovim Im using to open the file and test coc is that version, verified by running `:version` from with in it

**Comment by chemzqm** [comment]
It use backgournd nvim executable from your $PATH to prevent the block of highlight.

**Comment by diego898** [comment]
I edited my path variable directly by adding this to my `.zshrc`:
```
# Prepend to path
path=('~/bin' $path)
# export to sub-processes (make it inherited by child processes)
export PATH
```

I  verified this works by typing 
```
❯ which nvim
/usr/bin/nvim
```

Then, I tried the test again:
![image](https://user-images.githubusercontent.com/742407/54935981-78105f80-4eef-11e9-9aae-a8ecc5cecab8.png)

Now, I dont see the secondary popup anymore. Here is my `coc-log.vim`: https://pastebin.com/irZnBXM1

**Comment by chemzqm** [comment]
You're using old neovim, checkout https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-make-preview-window-shown-aside-with-pum

**Comment by diego898** [comment]
@chemzqm sorry! I just noticed that above I wasnt setting my path correctly. Now I am, and 

```
❯ which nvim
~/bin/neovim/bin/nvim
```

is correct. Now I see the following:

![image](https://user-images.githubusercontent.com/742407/54940103-0be62980-4ef8-11e9-8fdc-8f61c1f9c27a.png)

the first popup is not colored, and the second one is colored strangely as if it was pure python instead of documentation.

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
Looks like server doesn't claim the filetype of documentation.

**Comment by diego898** [comment]
I believe Im using `pyls` as my language server. Im not sure what to do with the information on that page you linked, so Ill close this issue as its not a coc issue. thanks
