### ISSUE TITLE
Deletion of Controversial Issues (like Underlining) ?! 

### ISSUE THREAD

**Issue by dan-compton** [neoclide/coc.nvim#593]
I recently complained about underlining destroying my process, linking to the relevant code.  My issue was edited, callouts removed, and issue closed.

I would like to reiterate that it's very ugly

**Comment by tomspeak** [comment]
![image](https://user-images.githubusercontent.com/2415569/54957777-ade33180-4f4b-11e9-80ba-59ca277804e1.png)

**Comment by oblitum** [comment]
@dan-compton we can still see what you did there in history, and it's not pretty. If you keep pushing like that I sincerely think you deserve being banned.

**Comment by dan-compton** [comment]
I apologize for the harsh wording, but it took a couple of hours to fix.  I appreciate what you guys are doing here.

**Comment by dan-compton** [comment]
@tomspeak harsh words are one thing, but that is inappropriate.

**Comment by dan-compton** [comment]
> @dan-compton we can still see what you did there in history, and it's not pretty. If you keep pushing like that I sincerely think you deserve being banned.

Do you mind restoring the original text while keeping the issue closed for transparency?
