### ISSUE TITLE
Feature: Don't join diagnostic lines in float

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#595]
Recently floating diagnostics started getting there lines joined. It would be great if there was an option to disable this, since it makes some diagnostics more difficult to read.

**Comment by chemzqm** [comment]
Any example？

**Comment by Avi-D-coder** [comment]
There should be a line break any place that `\` appears in the virtual text
![Screenshot_20190326_025346](https://user-images.githubusercontent.com/29133776/54977018-6e7c0b80-4f72-11e9-9400-91158cb9acc0.png)
