### ISSUE TITLE
Impossible to install extensions

### ISSUE THREAD

**Issue by TheSirC** [neoclide/coc.nvim#599]
**Result from CocInfo**

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.62
term: xterm-256color
platform: linux

**Describe the bug**
After installation of the pluging with `vim-plug` via the provided command `Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}`

**To Reproduce**

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create a minimal mini.vim with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start neovim with command: `nvim -u mini.vim`

- After trying to install the first extension via `CocInstall coc-rls` (for example) yarn will be installed and the install script will stop

- When trying again to install via the same`CocInstall coc-rls`, you will be greated via the following error message :

`[coc.nvim] yarn not found, visit https://yarnpkg.com/en/docs/install for installation.
`

**Comment by chemzqm** [comment]
The install script sometimes failed to add `yarn` and `yarnpkg` to your `$PATH`, it depends on your environment, then you have to install yarn or link it.

Checkout https://yarnpkg.com/en/docs/install for installation on your system, make sure `:echo executable('yarnpkg')` echo `1` in your vim.

**Comment by TheSirC** [comment]
That solved it ! Thank you ! 
I think that if it is a known issue maybe it should be stated somewhere in the README.

**Comment by chemzqm** [comment]
Thanks, will not load vim-node-rpc from npm modules on next version.
