### ISSUE TITLE
place coc-settings.json to .config/nvim doesn't work

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#6]
coc-settings.json
```
{
  "coc.preferences.diagnoctic.enable": false
}
// vim:ft=jsonc
```

**Comment by chemzqm** [comment]
@iamcco Whey you want to disable diagnocsic? 
The features like autofix would not be available if you disable diagnostic

**Comment by iamcco** [comment]
my project has it's own config of eslint.

**Comment by chemzqm** [comment]
I can understand the desire of disable tsserver diagnostic, you need to config the file `jsconfig.json` at the project root to make tsserver understand your code.

**Comment by blkwtkns** [comment]
This works! Issue now is that I think my config is wrong, and while it's enabling definition to work, I can't access references now. Here's the jsconfig.json right, which is sitting in my `js` directory:
```
{
  "compilerOptions": {
    "baseUrl": "."
  },
  "exclude": [
    "node_modules",
    "tmp",
    "compiled",
    "temp"
  ]
}
```
