### ISSUE TITLE
Map custom glyphs to item kinds

### ISSUE THREAD

**Issue by gbrlsnchs** [neoclide/coc.nvim#600]
**Is your feature request related to a problem? Please describe.**
It would be cool (but not necessary) to have icons shown inside the pum (or wherever they appear) instead of single chars like `v`, `f`, etc.

**Describe the solution you'd like**
Use [Vim DevIcons](https://github.com/ryanoasis/vim-devicons) to, when available, substitute the letters. Custom icon remapping would also be nice to have.

**Additional context**
I'm ignorant when it comes to the LSP and how this plugin maps types to each option, so maybe this is not even possible at all. Sorry if that's the case.

**Comment by chemzqm** [comment]
The problem is DevICons only have icons for filetypes, not for complete item kind.

**Comment by gbrlsnchs** [comment]
You're right, sorry. What about mapping kinds directly to a custom string, this way one is able to set whatever glyph or text they want. No DevIcons needed at all.

**Comment by gbrlsnchs** [comment]
@chemzqm I am playing around with this a little:
![image](https://user-images.githubusercontent.com/7577128/55033045-ff91c780-4ff0-11e9-99ea-c10823bc0b0c.png)
![image](https://user-images.githubusercontent.com/7577128/55033081-159f8800-4ff1-11e9-88de-6aaaed818cd1.png)

I think it's just a matter of enabling this in the `coc-settings.json` file and, if not explicitly mapped there, fallback to default values. What do you think?

**Comment by chemzqm** [comment]
Looks great, consider send a PR.

**Comment by gbrlsnchs** [comment]
@chemzqm What's the proper way to retrieve configuration values? I need to get it from inside `src/util/complete.ts`, but I could not grasp how to do so yet.

**Comment by chemzqm** [comment]
You can set the configuration at https://github.com/neoclide/coc.nvim/blob/master/src/completion/index.ts#L147 and use it at https://github.com/neoclide/coc.nvim/blob/master/src/completion/complete.ts#L193

**Comment by gbrlsnchs** [comment]
Should the custom config be under `"suggest"` or `"coc.preferences"`?

**Comment by chemzqm** [comment]
under `"suggest" `

**Comment by gbrlsnchs** [comment]
> https://github.com/neoclide/coc.nvim/blob/master/src/completion/complete.ts#L193

This seems to set an already resolved kind. Isn't it better to retrieve the custom config once in https://github.com/neoclide/coc.nvim/blob/master/src/util/complete.ts by setting
```typescript
import workspace from '../workspace'
const labels = workspace.getConfiguration('suggest.completionItemKindLabels')`
```
and then return something like this in https://github.com/neoclide/coc.nvim/blob/master/src/util/complete.ts#L68:
```typescript
export function completionKindString(kind: CompletionItemKind): string {
  switch (kind) {
    case CompletionItemKind.Text:
      return labels.get('text', 'v')
    case CompletionItemKind.Method:
      return labels.get('method', 'f')
    case CompletionItemKind.Function:
      return labels.get('function', 'f')
    case CompletionItemKind.Constructor:
      return labels.get('constructor', 'f')
    case CompletionItemKind.Field:
      return labels.get('field', 'm')
// and so on...
}
```

What do you think? For the visual examples I showed above, I hard coded the glyphs directly in that function and it seemed to work.
