### ISSUE TITLE
Coc-html doesn't work in htmldjango filetypes

### ISSUE THREAD

**Issue by monkoose** [neoclide/coc.nvim#604]
**Result from CocInfo**
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.62
term: xterm-termite
platform: linux

## Output channel: snippets
[Error 21:51:20] Convert regex error for: (^|(?<=\W))\.$
[Error 21:51:21] Convert regex error for: li(st)? (?<num>\d+)$
[Error 21:51:21] Convert regex error for: ol(st)? (?<num>\d+)$

**Describe the bug**
Seems like coc-html doesn't work in htmldjano filetypes.
I added this to my CocConfig, but nothing happens.
```json
{
  "html.filetypes": [
    "html",
    "htmldjango",
    "handlebars",
    "razor"
  ],
}
```
Am i doing something wrong or it is bug?

**Comment by chemzqm** [comment]
You have to use filetype map, checkout `g:coc_filetype_map`

**Comment by monkoose** [comment]
This actually made coc-html work, but at the same time removed DJANGO TEMPLATES snippets from the completion list.

**Comment by chemzqm** [comment]
Need fix with cco-snippets.
