### ISSUE TITLE
coc-list: It is not possible to remap <tab> or map chooseAction

### ISSUE THREAD

**Issue by BonaBeavis** [neoclide/coc.nvim#608]
As far as I see, `chooseAction()` is missing [here](https://github.com/neoclide/coc.nvim/blob/b4a00e70ac676578f42c4378adc11a5ff7496805/src/list/mappings.ts#L178)

And only way to use `<Tab>` for selecting the next item was:
```
  "list.insertMappings": {
          "<C-i>": "normal:j"
  }
```

**Comment by chemzqm** [comment]
It need to consider `<C-i>` as `<tab>`.

**Comment by BonaBeavis** [comment]
Okay, and thanks for the genius work. I tried all the lsp plugins for nvim and yours is by far the fastest, cleanest and user friendly of them all. This should not disrespect the hard free work of the others, their plugins are already great, but coc is amazing.
