### ISSUE TITLE
Is there a way to scroll the hover pop-up menu?

### ISSUE THREAD

**Issue by comfortablynick** [neoclide/coc.nvim#609]
I notice that the hover menu can be scrolled with my mouse. Is there a way to do it with keyboard shortcuts? I've looked everywhere but can't seem to find it.

If not, is there a way to pop the documentation out into a preview window? Similar to the old-style of "hover".

Thanks for the great plugin! I've pretty much switched from VS Code to nvim full-time because of it.

**Comment by reaysawa** [comment]
Per responses in the Gitter channel:

```
Ole Reifschneider @Tranquility Mar 13 06:24
hi, is it possible to scroll in the float window?
Qiming zhao @chemzqm Mar 13 06:31
Use mouse.
Ole Reifschneider @Tranquility Mar 13 06:41
ah, thanks. can I map this to a keybinding?
Qiming zhao @chemzqm Mar 13 06:55
It's possible, write a function move cursor to floating window and scroll, then move cursor back.
```

As it can be seen here, floating windows have the 'float' variable set as true on them.

https://github.com/neoclide/coc.nvim/blob/1f831599875aa393b423ac071e8dc68014f87f0f/src/model/floatFactory.ts#L189

![image](https://user-images.githubusercontent.com/17429390/55211083-3f130c00-51c9-11e9-93a4-709fef1c74a7.png)

1. `nvim_tabpage_list_wins(tabpagenr())` will list all windows in the current tabpage
2. save the number of your current window
3. loop through all windows until you find the one in which `nvim_get_win_var(winnr, 'float')` is true
4. focus the floating window, scroll by N lines, then jump back to your saved window on step 2

I don't have an actual implementation because I don't use this feature, but maybe this can help you.

**Comment by chemzqm** [comment]
Checkout `:h coc#util#has_float()` and `coc#util#float_scroll()`.

**Comment by comfortablynick** [comment]
Thanks @chemzqm 

That key binding does scroll it forward, but it snaps right back to the top. It scrolls fine with the mouse.

**Comment by chemzqm** [comment]
>  but it snaps right back to the top.

Can't reproduce this behavior.

**Comment by chemzqm** [comment]
Looks that you have CursorHold or CursorMoved autocmds bind to diagnostics.

**Comment by comfortablynick** [comment]
You're right, it does work with minimal vimrc. 

I notice ALE and gitgutter have some autocmds, so I disabled them. However, it's still exhibiting the same behavior with only these autocmds (which are the same autocmds in my minimal vimrc):

``` vim
:au CursorHold
--- Autocommands ---
coc_nvim  CursorHold
    *         call s:Autocmd('CursorHold', +expand('<abuf>'))
LC  CursorHold
    *         call CocActionAsync('doHover') " Hover on cursor hold

```
``` vim
:au CursorMoved
--- Autocommands ---
matchparen  CursorMoved
    *         call s:Highlight_Matching_Pair()
coc_nvim  CursorMoved
    *         call s:Autocmd('CursorMoved', +expand('<abuf>'), [line('.'), col('.')])
```

**Comment by chemzqm** [comment]
Remove that CursorHold autocmd.

**Comment by comfortablynick** [comment]
If I remove that autocmd, I don't get the hover on CursorHold!

I was able to make it work by doing this though:
```vim
autocmd CursorHold * if ! coc#util#has_float() | call CocActionAsync('doHover') | endif 
```

@chemzqm 
Is this the best way to have auto-hovering and being able to scroll the pum?

**Comment by chemzqm** [comment]
You can use `CocAction` instead of `CocActionAsync` to avoid other floating window created when requesting.

**Comment by cherrot** [comment]
Hi, I'm using vim 8.1.1700 on MacOS. I'm not very sure but I suspect `coc#util#has_float()` didn't work as expected.

In the following example, `echo coc#util#has_float()` got a `0`. `coc#util#float_scroll(1)` didn't work neither.

![image](https://user-images.githubusercontent.com/964629/63400729-72b83200-c407-11e9-904c-83d94aefe571.png)

**Comment by chemzqm** [comment]
It's used for floating window which is neovim only, not vim's popup

**Comment by cherrot** [comment]
I got it. Thanks :)

**Comment by ricciolino** [comment]
Sorry, maybe I misunderstood.
Is it possible to use the keyboard to scroll down and up hint pop-ups (such as function documentation) in vim?

**Comment by chemzqm** [comment]
Please checkout #2472

**Comment by ricciolino** [comment]
Ok thanks, so are you working on it?

**Comment by chemzqm** [comment]
It should working fine already

**Comment by ricciolino** [comment]
I config this 4 lines in my vimrc:
```
nnoremap <nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
nnoremap <nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
inoremap <nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
inoremap <nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
```
But I got:
`E117: Unknown function: coc#float#has_scroll`

**Comment by oblitum** [comment]
@ricciolino simply update to latest release or master.

**Comment by ricciolino** [comment]
Oh... thank you so much @oblitum !

**Comment by Mehedi-MHS** [comment]
![Screenshot_20220718-110641_Termux](https://user-images.githubusercontent.com/76158620/179448624-a1133074-49b1-4ff7-9661-8b53d80dd22c.jpg)
hello, i need some help. I can scroll the magenta color menu using arrow key and also using mouse. But i cant scroll the green background menu(containing documentation). Whenever i click on it or try to scroll it, it totally disappears. I reasearched on it but didnot find any way to solve it. Thanks in advance

**Comment by mohamedafify** [comment]
for anyone still with the same problem just add these 2 lines in your vimrc
nnoremap <silent><expr> <C-j> coc#float#has_scroll() ? coc#float#scroll(1, 1) : "\<C-j>"
nnoremap <silent><expr> <C-k> coc#float#has_scroll() ? coc#float#scroll(0, 1) :  "\<C-k>"

**Comment by ulises-castro** [comment]
Hi, 
I'm using LazyVim (neovim) and basically I just press "K" to open the hover popup and again "K" to focus on the popup then you can scroll with  j / k.

**Comment by mrthere3** [comment]
> Hi, 你好 I'm using LazyVim (neovim) and basically I just press "K" to open the hover popup and again "K" to focus on the popup then you can scroll with j / k.我正在使用 LazyVim （neovim），基本上我只需按“K”打开悬停弹出窗口，然后再次按“K”专注于弹出窗口，然后您可以使用 j / k 滚动。

Thanks, it's also working on Astronvim :)

**Comment by mrthere3** [comment]
> Hi, I'm using LazyVim (neovim) and basically I just press "K" to open the hover popup and again "K" to focus on the popup then you can scroll with j / k.

Thanks, it's  working on Astronvim :)
