### ISSUE TITLE
Turn off echoing of error messages

### ISSUE THREAD

**Issue by robertgzr** [neoclide/coc.nvim#61]
Is there already a way to turn off the behavior to echo the error message related to the current line?

If not I would like to request being able to turn that off in the same way I can choose not to see the quicklist with `g:coc_auto_copen`.

I find it particularly distracting when I use `:lopen` showing me all errors, then jumping to one and seeing the same messages twice in the loclist and the statusbar.

**Comment by chemzqm** [comment]
Set `coc.preferences.diagnostic.enableMessage` to false to diable echo message.

**Comment by robertgzr** [comment]
Thanks!

**Comment by baburaoGanpatraoApte123** [comment]
@chemzqm 
`coc.preferences.diagnostic.enableMessage=false` in coc-settings.json, is it crct (it is showing an error as invalid option)

**Comment by fannheyward** [comment]
@baburaoGanpatraoApte123 it's `diagnostic.enableMessage` now.
