### ISSUE TITLE
Non optimal wrapping in floating windows

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#611]
Urls get broken in two lines by Coc, as a result `yiW` will not be able to copy them.
```
 [clippy clippy::type_complexity] [W] very complex type used. Consider        
 factoring parts into `type` definitions                                      
                                                                              
 help: for further information visit https://rust-lang.github.io/rust-clippy/ 
 master/index.html#type_complexity
```

Single tick code blocks also get broken into two lines
```
 [rustc renamed_and_removed_lints] [W] lint name `type_complexity` is 
 deprecated and may not have an effect in the future. Also `cfg_attr( 
 cargo-clippy)` won't be necessary anymore                            
                                                                      
 help: change it to: `clippy::type_complexity`    
```

It would be great if both were treated as words, such that if they don't fit on a line they are moved to the next.

**Comment by chemzqm** [comment]
Could be improved by break the line on whitespace when possible, will not work on this for now, PR welcome.

**Comment by BonaBeavis** [comment]
Additional this breaks concealment of long ugly jdt links.

```
     *  [UnsupportedOperationException](jdt://contents/rt.jar/java.lang/
 UnsupportedOperationException.class?=nifi-sparql-integrate-processors/%5C/usr%
 5C/lib%5C/jvm%5C/java-8-openjdk-amd64%5C/jre%5C/lib%5C/rt.jar%3Cjava.lang%
 28UnsupportedOperationException.class#38)
```
could be:
```
* UnsupportedOperationException
```

**Comment by dbalatero** [comment]
@BonaBeavis 

> Additional this breaks concealment of long ugly jdt links.

Is there a config option that lets you conceal the Markdown links? I can't find one but your comment makes me think there might be :)

**Comment by BonaBeavis** [comment]
@dbalatero 

I think coc sets conceallevel to 2 for its floats. See `:h conceallevel`. What gets concealed depends on your settings and plugins for markdown files.

**Comment by chemzqm** [comment]
> Is there a config option that lets you conceal the Markdown links?

Not yet, need to make the link clickable before conceal them.

**Comment by esn89** [comment]
Thanks for fix.  By the way, I didn't know operations can be done on floating windows.  How do you do a yiW on a floating window?

**Comment by chemzqm** [comment]
Move cursor to float window

**Comment by esn89** [comment]
When I do it, with my mouse, it seems to make it disappear and return me to text editor.  

I even tried it with "W", and "E" movement keys, but that doesn't work.

**Comment by chemzqm** [comment]
use <c-w>p

**Comment by oblitum** [comment]
Just to register, in case anyone else is missing it, 77cbc92 removed the feature of signatureHelp alignment to current parameter.
