### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gstormlee** [neoclide/coc.nvim#612]
I removed the.config and.cache directories and reinstalled the coc.but when nvim started ：

<img width="820" alt="Screen Shot 2019-03-29 at 16 05 19" src="https://user-images.githubusercontent.com/33013161/55219350-aec3de00-523f-11e9-912e-9105fd7c6763.png">

**Result from CocInfo**

![image](https://user-images.githubusercontent.com/33013161/55220034-45dd6580-5241-11e9-8b94-10ef68424561.png)

It was normal before the upgrade

**Comment by chemzqm** [comment]
You can fix it by `mkdir -p ~/.config/coc` in your terminal.
