### ISSUE TITLE
[coc.nvim] Error on TextChangedI: Cannot read property 'filetype' of null

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#616]
**Result from CocInfo**

## versions

vim version: NVIM v0.4.0-466-gdfb7f6b34
node version: v11.13.0
coc.nvim version: 0.0.63
term: tmux-256color
platform: linux

## Output channel: snippets

**Describe the bug**

I'm getting messages like `[coc.nvim] Error on TextChangedI: Cannot read property 'cpp' of null` or `[coc.nvim] Error on TextChangedI: Cannot read property 'rust' of null`.

**To Reproduce**

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create a minimal mini.vim with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start vim with command: `vim -u mini.vim`

- Start neovim with command: `nvim -u mini.vim`

- Just start typing.

**Screenshots**

**Comment by chemzqm** [comment]
It's bug of coc-snippets, try `CocInstall coc-snippets` to fix it.

**Comment by oblitum** [comment]
OK, fixed.
