### ISSUE TITLE
Does coc provide a complete function?

### ISSUE THREAD

**Issue by bgx90** [neoclide/coc.nvim#618]
Does coc provide a function as described in `:h complete-functions` that can be used as the `'completefunc'` or `'omnifunc'` option so that coc can provide completion candidates via [n]vim's builtin completion system?  I realize that i could just create a key mapping to invoke coc#refresh directly via coc's own completion system, but I prefer to use vim's builtin functionality and configuration options whenever possible.

**Comment by chemzqm** [comment]
I have considered about it, but it's not possible to provide full completion support for LSP servers by use `omnifunc`, so not an option.

**Comment by bgx90** [comment]
I see. Thanks.
