### ISSUE TITLE
It doesn't create directory for coc at `/home/.config/coc`

### ISSUE THREAD

**Issue by the1900** [neoclide/coc.nvim#619]
**Result from CocInfo**
## versions
  vim version: NVIM v0.3.4
  node version: v10.15.3
  coc.nvim version: 0.0.63
  term: xterm-256color
  platform: linux

**Describe the bug**
It seems a new release *v0.0.63* uses `memos.json` file on `/home/(user)/.config/coc` but It does not create the directory automatic then, It says *there is no directory or file* and **it won't start coc service.** 

So I typed `mkdir -p /home/the1900/.config/coc` and `touch /home/the1900/.config/coc/memos.json`. It works! 

The reason that I create a issue is I've not seen this message before. I installed coc maybe 4 days ago and I found this situation when I reinstall the coc right now.

**Comment by chemzqm** [comment]
Fixed, sorry for the inconvenience.
