### ISSUE TITLE
[NOTICE] Binary release will be removed.

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#626]
Since you always need yarn which requires nodejs to install extension, it doesn't make too much sense for binary release.

A compiled bundle of javascript file will be provided, it's only about 200kb to download, which is 50x smaller than binary release, it would save you sometime for downloading.

**Comment by gbrlsnchs** [comment]
I think this is a good change. This change renders #568 useless, so I'll close it.
