### ISSUE TITLE
terrafrom language server

### ISSUE THREAD

**Issue by lanox** [neoclide/coc.nvim#631]
Hi, I was wondering if you are planning to support terraform autocompletion.

**Comment by chemzqm** [comment]
If it's language server of LSP, you can configure coc.nvim to use it.

**Comment by Kasama** [comment]
For future reference, it's easy to configure [terraform-lsp][1] to work with coc.nvim. 

You can simply include the following setting to your `coc-settings.json` after installing [terraform-lsp][1] and adding it to you `PATH`. (alternatively, you can set the `command` key to the full path of the executable)

```json
  "languageserver": {
    "terraform": {
      "command": "terraform-lsp",
      "filetypes": ["terraform"],
      "initializationOptions": {}
    }
  }
```

[1]: https://github.com/juliosueiras/terraform-lsp

**Comment by chemzqm** [comment]
Consider add it to wiki page

**Comment by victoruyy** [comment]
Hi, I am having problems installing terraform-lsp, lot of errors when I do the make command 

 ## hyper  | 01:21:01 | -- terraform-lsp --> $ make
go build -ldflags "-X main.GitCommit=$(git rev-list -1 HEAD) -X main.Version=$(git describe --tags) -X main.Date=$(date +%Y-%m-%dT%T%z)"
# golang.org/x/sys/unix
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:136:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:151:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:166:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190804053845-51ab0e2deafa/unix/zsyscall_darwin_arm64.go:166:3: too many errors
make: *** [terraform-lsp] Error 2


Any ideas? I have a M1 Mac OS,

Really would like to have this integrated with my nvim

Thank you
