### ISSUE TITLE
Installation failed, repository not found

### ISSUE THREAD

**Issue by eduardoarandah** [neoclide/coc.nvim#633]
Installing with Vundle, says repository not found, looks like the repository name is different. 

I guess the proper path should be: 
`https://github.com/neoclide/coc.nvim.git`

![imagen](https://user-images.githubusercontent.com/4065733/55355818-942f7600-5486-11e9-9b5d-f7c5b47b8c8d.png)

**Comment by chemzqm** [comment]
Should be bug of Vundle or problem of your configuration.

**Comment by eduardoarandah** [comment]
Maybe I missed the .vim in the package name. 

Don’t remember. Changed to vim plug, copy pasted and worked fine
