### ISSUE TITLE
Workspace folders should prioritize language server rootPatterns

### ISSUE THREAD

**Issue by wbthomason** [neoclide/coc.nvim#636]
**Result from CocInfo**
I believe this is irrelevant but I can add it if requested.

**Describe the bug**
With the new workspace folders change (3ca2e7a), the wrong workspace root is detected for `ccls` because the default value of `coc.preferences.rootPatterns` is prepended to the custom `rootPatterns` defined for `ccls`. It seems like `coc` should use `b:coc_root_patterns` first, then the *custom* `rootPatterns`, then the default `coc.preferences.rootPatterns` - this would break the fewest configurations and allow more precise configuration.

This problem can be worked around by setting `b:coc_root_patterns`, but this should not be necessary if the patterns are already set in the language server configuration and do not need to be changed.

**To Reproduce**
Open a C++ file with the default `ccls` config in a subdirectory of a Git repo (make sure `compile_commands.json` or `.ccls-cache` or one of the other `ccls` custom `rootPatterns` is present in the subdirectory). Run `:CocCommand workspace.workspaceFolders` and note that the only included folder is the root of the Git repo. Run `:echo coc#util#root_patterns()` and note that the list starts with the default `coc.preferences.rootPatterns` values before including the custom `ccls` `rootPatterns` values. Finally, note that this breaks `ccls` as it cannot find included files correctly.

Any minimal config with the default `ccls` setup will work.

**Screenshots**
Not applicable

Thank you, and please let me know if more information/testing would help with this issue.

**Comment by oblitum** [comment]
This seems to relate to [an early question I made](https://github.com/neoclide/coc.nvim/issues/341#issuecomment-470855768):

> Does setting `'rootPatterns'` actually extend instead of overriding the default ``'rootPatterns'`` (`['.vim/', '.git/', '.hg/', '.projections.json']`)?

**Comment by chemzqm** [comment]
Got it, LS requires the file inside root of workspaceFolder, will make it higher priority.

**Comment by chemzqm** [comment]
Should be fixed on master now.

**Comment by wbthomason** [comment]
Can confirm; this fixes the issue I observed. I'll close this for now - @oblitum please reopen if you feel the problem you raised is not fixed yet. Thank you, @chemzqm!

**Comment by chemzqm** [comment]
You can edit workspace folders in `:CocList folders`, coc would send workspaceFolderChange event to server.
