### ISSUE TITLE
Class/namespace/function is underlined and marked "unknown" even if symbol is indexed.

### ISSUE THREAD

**Issue by xvoidee** [neoclide/coc.nvim#637]
Hello,

I use your plugin together with ccls on medium-size C++ project. On some (<1%) lines I see following behaviour:
* even if symbol (class/namespace/function) is indexed and available for "go to definition" call, it is highlighted as "unknown/not defined"

Project compiles without issues using cmake in command line. It is complete and running.

Please guide me what info should I provide in addition (json calls trace to ccls? g++/clang calls? but how?) as posting code not possible.

ps: this issue does not happen on another project, EVERYTHING is indexed completely fine and no false-highlights
ps2: I am not able to reproduce it in my pet-project written from scratch - also works completely fine

**Comment by xvoidee** [comment]
See Screenshots:

ttp://i65.tinypic.com/9k73hz.png
ttp://i67.tinypic.com/21m9jec.png

**Comment by chemzqm** [comment]
Please provide output from ccls, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by xvoidee** [comment]
I think at the moment I will close issue as I found reason. It is in code: wrong use of classes, forward declarations instead of clean coding and includes where they needed.

Not a coc.nvim problem! ;) Please continue your great work!
