### ISSUE TITLE
Some errors...

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#638]
![2019-04-03-101710_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/55464451-73d4f800-55fb-11e9-804e-239343f4811e.png)
![2019-04-03-102906_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/55464452-73d4f800-55fb-11e9-961a-2556bb47a815.png)

**Comment by chemzqm** [comment]
Please paste `:CocInfo`

**Comment by mihaelartz** [comment]
@chemzqm This is log from CocInfo
## versions

vim version: NVIM v0.3.4
node version: v10.15.3
coc.nvim version: 0.0.64
term: screen-256color
platform: linux

## Error messages

**Comment by mihaelartz** [comment]
@chemzqm Any option for check language server status, e.g. is enabled or not for current filetype in buffer?

**Comment by chemzqm** [comment]
Use `:CocList extensions` to get extensions state, for language server status, checkout `:h coc-status` to integrate statusline support.

**Comment by chemzqm** [comment]
Looks like the installation is broken, try reinstall extensions.

**Comment by mihaelartz** [comment]
@chemzqm now when uninstall extension i don't get a error message, maybe problem is in yarn?

For now, closing.
