### ISSUE TITLE
Can I use ctrl-c to close CoC's windows?

### ISSUE THREAD

**Issue by zhou13** [neoclide/coc.nvim#639]
**Is your feature request related to a problem? Please describe.**
I always map `<C-c>` to `<ESC>`.  However, my mapping does not work in `:CocCommand`.

**Describe the solution you'd like**
I tried to map it but I found map does not work.  How could I `imap` in the window popping up after `:CocCommand`?

**Comment by chemzqm** [comment]
It make use of `getchar` from vim, so your keymappings doesn't work, add
``` json
  "list.normalMappings": {
    "<C-c>": "do:exit"
  },
  "list.insertMappings": {
    "<C-c>": "do:exit"
  },
```
in your settings file opened by `:CocConfig`.

**Comment by mwcm** [comment]
ahhhhhh thank you @chemzqm !

**Comment by spiritphyz** [comment]
Using `ctrl-c` to close the floating window will sometimes cause line fragments to permanently remain on the screen, which added a lot of visual clutter to the editor. This fix made all parts of the floating menu to disappear, fixing a long-standing visual bug I experienced, so thank you for this @chemzqm !
