### ISSUE TITLE
Show the diagnostic message when the cursor is at related line rather than at a position

### ISSUE THREAD

**Issue by zhou13** [neoclide/coc.nvim#640]
**Is your feature request related to a problem? Please describe.**
Currently coc.nvim only shows the diagnostic message when you place the cursor at the correct location.  For example, you need to move the cursor under  `M` in order to get the diagnostic message
![image](https://user-images.githubusercontent.com/576382/55467746-c93ae600-55b6-11e9-852d-6af3df5a331b.png)

For ccls, sometimes this is impossible because the error is locate at the end of the line (line 5 only has 18 columns, maybe that is a bug of ccls but anyway...).
![image](https://user-images.githubusercontent.com/576382/55467791-dbb51f80-55b6-11e9-9bc4-4bb9d33a3c3a.png)

**Describe the solution you'd like**
I hope that I can get the diagnose after I move my cursor to the corresponding line.  The column does not need to be in the column of the error.

**Describe alternatives you've considered**
I tried to search through the help file but I cannot find related stuff.

**Comment by iamcco** [comment]
coc-settings.json

``` jsonc
  "diagnostic.checkCurrentLine": true,
```

**Comment by atsepkov-zaius** [comment]
I enabled this as well and prefer it to the default. However, now I have another minor problem. The TS warning/error messages themselves do not mention column number, and for some of the more cryptic ones I sometimes start investigating the wrong symptom. Is it possible to still show all line warnings regardless of cursor position while underlining the atoms responsible (like the default without this setting)?
