### ISSUE TITLE
Add option similar to maxCompleteItemCount but per source

### ISSUE THREAD

**Issue by balta2ar** [neoclide/coc.nvim#642]
**Is your feature request related to a problem? Please describe.**
I'd like to have an option that would limit the number of candidates per source (extension).

**Describe the solution you'd like**
allExtensions.maxCompleteItemCount = 5
extension.`<name>`.maxCompleteItemCount = 10

**Describe alternatives you've considered**
So far there is only a global setting maxCompleteItemCount, so basically no alternatives. Otherwise, each source has to implement such an option individually, which is hardly realistic.

**Additional context**
Ideally, there should be a global option to set the number of candidates per extension with default value, e.g. allExtensions.maxCompleteItemCount = 5, but then you could override it for each source by its name, e.g. extension.dictionary.maxCompleteItemCount = 10. It should work even if the extension itself is not aware of the limitation.

**Comment by chemzqm** [comment]
Could you explain why this feature is needed?
It have influence with performance and I can't see the benefit.

**Comment by balta2ar** [comment]
The reason is that I usually use a number of sources (extensions) that produce many results and only top N from each source individually are actually useful, for example I'd love to have the following sources on: tmux, look (man look), webcomplete, buffer (actually, first three are non-existent for coc just yet, but I can trivially implement them for myself if you land my feature request). Normally, only about 5 items are relevant from such sources, but if they are not limited, they spam the candidate list too much.

On the other hand, there are other "less spammy" sources such coc-python where I'd love to see more candidates (e.g. 10 by default).

By the way, this functionality is present in ncm2 (https://github.com/ncm2/ncm2/issues/38) and deoplete (https://github.com/Shougo/deoplete.nvim/issues/731).

**Comment by chemzqm** [comment]
The problem is coc use match score to sort the all complete items, so it don't makes too much sense for it.

**Comment by balta2ar** [comment]
What if you could apply scoring per each source first, them slice off all but N best candidates, and then present them in groups according to the priorities? Here is how it looks visually in ncm2:
![](https://i.imgur.com/k5xpR05.png)

**Comment by chemzqm** [comment]
Consider there's a complete item like `testUtil` which is out first 5 items, if you're can't see it, you will not know that you can make it first complete item by just type `U`, but wonder your completion engine is broken.

I can't understand how could it help you complete with words.

**Comment by chemzqm** [comment]
>  they spam the candidate list too much.

It's better to filter them out by compare use match score, instead of limit complete items.

**Comment by balta2ar** [comment]
> you will not know that you can make it first complete item by just type U, but wonder your completion engine is broken

Well, I use completion engines with a bit different persperctive. To me, it makes sense to limit those sources where I approximately know what to expect from them. Let me demonstrate you a coulple of my usecases.

1) JIRA completion. I use completion heavily to insert ticket numbers filtering by ticket title (e.g. https://github.com/Shougo/deoplete.nvim/issues/759). For example, there is a ticket with the title "Part of DSP and SSP settings are not displayed in history" and I just know that it exists because I'm currently working on it, but I'm lazy to copy-paste its number (ticket ID) into the text editor. Instead, I type "JIparthist", and I just know that words "part" and "hist" will be in the title. In this case, I never need to see all my 600 candidates (thats the average number of tickets I have in cache), but only top 5-10 usually. 

2) tmux & webcomplete. Same goes for tmux and completion from browser. Imagine I'm coding a python extension, and I have this page opened in my browser side-by-side with the editor: https://docs.python.org/3/c-api/structures.html. There is a lot of long words which I don't want to type, e.g. `PyCFunctionWithKeywords`. Instead, knowing what I want to get (I see it in my browser, right?), I'd just type `pycfunkey`. webcomplete extension will grab words from the currently open web page and will complete my request. This looks like a poor man's semantic completion and yes it is, but it helped me alot when proper language server functionality is not available.

3) Third example is prefixed completion. Sometimes I need to insert mercurial branch names, but I don't want to be suggested all the branches all the time. Instead, I create an extension that would trigger only on a certain prefix, eg. "HGfixhistory". Basically, it's what  you did in coc-emoji. And again: I know in advance what I'm looking for, the point of completion is to get to it blazingly fast.

Thus, completion to me is not only about exploration, but rather a way to quickly filter out what I already know exists.

> It's better to filter them out by compare use match score, instead of limit complete items

Not always, I'm afraid. As I said above, my coc-jira source has about 600 candidates. When my input string is still short and generic or frequently seen (e.g. `JItest`), I get a huge list of candidates on the screen. And I don't need to see them, what's the point of showing them to me if I know exactly what I want to get, I just need a couple of more characters to narrow my range of candidates.

**Comment by chemzqm** [comment]
>  I type "JIparthist", and I just know that words "part" and "hist" will be in the title.

I suggest use something like source of `CocList`, it have support for interactive mode which means you can send request on input change instead of fetch them all at once which could be quite slow, and you can add more actions to it, like mark it completed.

>  e.g. PyCFunctionWithKeywords. Instead, knowing what I want to get (I see it in my browser, right?), I'd just type pycfunkey. 

You'd better type `PCWK` instead since it would have highest fuzzy score most likely.

> , I create an extension that would trigger only on a certain prefix, eg. "HGfixhistory".

Why not create special trigger character for it? like `#`, with trigger character, you only get complete items from the trigger source, instead of all sources. You can make use of TextEdit or `startcol` of CompleteResult to make remove character on complete done.

**Comment by balta2ar** [comment]
> instead of fetch them all at once which could be quite slow

In case with JIRA source it 100% can't be slow since I'm reading from cache on my disk and there are only 600 lines, and it's not a networking request. But that's just specific details. Thanks for the suggestion about `CocList`, I'll look into it, I'm still new with coc, I've been using it for mere couple of days. I fell in love with interactive grep the moment I tried it, now I wish I could bring other missing features I had with deople and ncm2.

> You'd better type PCWK

Yes, but that was just an example. I can easily imaging a case where I only rememer first and last word of a longer compound word.

> Why not create special trigger character for it

That was another question I wanted to ask. Can I use triggers longer than one character? The downsides of one character are that 1) there is only a handlful of various characters on your number row of your keyboard, and not all of them are within a convenient reach from the home row (you need to stretch your fingers too much to reach "^" or "&", for example); 2) special characters are not mnemonic. For me personally, it's easier to remember "JI" and "HG" prefixes, than to use special characters such as "#". That's just me, though, your milage may vary.

> You can make use of TextEdit or startcol of CompleteResult to make remove character on complete done

By the way, I wish such tips and tricks were available on the Wiki. You have a page on how to create basic vim source, but I could find nothing about how to create JavaScript/TypeScript-based extensions. Having several typical "getting started" examples with descriptions of things that could be done would be nice. Of course one can always see the source code of other extensions, but specially crafted docs are usually better at explaining features.

Anyway, I hope I managed to convey the importance of limitation of candidates per source (and perhaps scoring per source as well) so that you could at least consider supporting it.
