### ISSUE TITLE
"$_", "->" Does not trigger completion in PHP

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#644]
I have a problem, like in title when start typing $_ i don't get a completions (i get a completion but in same moment completion popup menu it will be gone) for global variables, i tested with deoplete, language client neovim, this problem not appear, also when trigger with "->" i don't get a completion i must be to refresh or start typing something for get a completions, problem with trigger with "->" i did not have that problem before, i guess :)

**Comment by chemzqm** [comment]
Looks like `$` is not in `iskeyword` option of your php files.

**Comment by mihaelartz** [comment]
@chemzqm Thanks, first problem is solved, any suggestions how to fix second problem "->"?

**Comment by chemzqm** [comment]
Looks like the LS performance is bad.

**Comment by mihaelartz** [comment]
@chemzqm I do not believe it, in VSCode works fine, with deoplete and language client neovim works fine definitely not to a language server

**Comment by chemzqm** [comment]
Should be problem of workspace folder resolve, checkout https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders
