### ISSUE TITLE
Workspace not indexing

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#646]
Hey!

On latest release 0.0.64 (tag) all works fine, but now not working

With: Plug 'neoclide/coc.nvim', { 'tag': '*', 'do': 'yarn install --frozen-lockfile' } working
With: Plug 'neoclide/coc.nvim', { 'do': 'yarn install --frozen-lockfile' } not working

**Comment by sebaLinares** [comment]
Same, just updated with vundle `:PluginUpdate` and now I have no completion for some methods. I still have completion for variables that I've already declared.

**Comment by chemzqm** [comment]
What language server not working? Please provide verbose output from output channel.

**Comment by chemzqm** [comment]
Two options:

* Disable workspaceFolder support for the language server.
* Make coc.nvim find correct workspaceFolder for you.

Checkout https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders
