### ISSUE TITLE
<c-space> insert <Plug>(asyncomplete_force_refresh) 

### ISSUE THREAD

**Issue by yml** [neoclide/coc.nvim#65]
Hitting <ctrl> and <space> in insert mode add the following text under the cusor `<Plug>(asyncomplete_force_refresh) ` .

**Expected behavior**
I would expect the completion menu to popup

My vimrc is available [here](https://github.com/yml/dotfiles/blob/language-server-autocompletion/_vimrc#L51-L113)
Please do not hesitate to let me know if you need anything else.

**Comment by chemzqm** [comment]
@yml you have duplicatd mapped `<c-space>` https://github.com/yml/dotfiles/blob/language-server-autocompletion/_vimrc#L166

**Comment by yml** [comment]
Oups sorry for the noise.
Thank you for this great plugin.
