### ISSUE TITLE
Go to Definitions inside jar/zip files

### ISSUE THREAD

**Issue by snoe** [neoclide/coc.nvim#652]
**Result from CocInfo**

```
## versions

vim version: NVIM v0.4.0-dev
node version: v11.13.0
coc.nvim version: 0.0.64-245f57b845
term: Apple_Terminal
platform: darwin

## Error messages
```

**Describe the bug**
In https://github.com/snoe/clojure-lsp I am reading classpaths, crawling through the jar files and indexing clojure files within.

I use vim's `zipfile:` syntax as the resulting uri of `textDocument/definition`. 

coc seems to get a uri such as:
`zipfile:///Users/case/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar::clojure/core.clj`
but opens it with the `::` escaped:
`zipfile:///Users/case/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar%3A%3Aclojure/core.clj`

This results in opening an empty buffer. If the uri was not escaped, vim would open the file inside the zip. Ideally, coc would open zipfile uris in readonly mode.

See https://github.com/autozimu/LanguageClient-neovim/issues/381 for some background.

**To Reproduce**

Below you can see the output from a trace. And the screenshot showing the file name that was opened.

```
[Trace - 12:20:54 a.m.] Sending request 'textDocument/definition - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/case/dev/lsp/src/clojure_lsp/handlers.clj"
    },
    "position": {
        "line": 24,
        "character": 1
    }
}


[Trace - 12:20:54 a.m.] Received response 'textDocument/definition - (1)' in 15ms.
Result: {
    "uri": "zipfile:///Users/case/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar::clojure/core.clj",
    "range": {
        "start": {
            "line": 4864,
            "character": 10
        },
        "end": {
            "line": 4864,
            "character": 15
        }
    }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/105012/55606729-2c538680-5737-11e9-9e38-757b9927f5ac.png)

**Comment by chemzqm** [comment]
It's expected, I think your should fix it by improve the logic of your scheme handler.

It use vscode-uri to normalize the uri, you can test it by:
``` js
const U = require('vscode-uri')
U.default.parse('zipfile:///Users/case/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar::clojure/core.clj').toString()
// => 'zipfile:/Users/case/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar%3A%3Aclojure/core.clj'
```
