### ISSUE TITLE
How can i use phpcs with coc?

### ISSUE THREAD

**Issue by dementor5** [neoclide/coc.nvim#653]
**Is your feature request related to a problem? Please describe.**

For js style checks i can use a coc-eslint plugin.
How i can connect phpcs to coc.nvim?
https://github.com/squizlabs/PHP_CodeSniffer

**Comment by chemzqm** [comment]
You can use https://github.com/iamcco/diagnostic-languageserver with PHP_CodeSniffer.

**Comment by dementor5** [comment]
> You can use https://github.com/iamcco/diagnostic-languageserver with PHP_CodeSniffer.

Thanks, this plugin works.
There is my config:
```
{
  "languageserver": {
    "dls": {
      "command": "diagnostic-languageserver",
      "args": [ "--stdio" ],
      "filetypes": [ "php" ],
      "initializationOptions": {
        "linters": {
          "phpcs": {
            "command": "./vendor/bin/phpcs",
            "debounce": 100,
            "rootPatterns": [ "composer.json", "composer.lock", "vendor", ".git" ],
            "args": [ "--standard=PSR2", "--report=emacs", "-s", "-" ],
            "offsetLine": 0,
            "offsetColumn": 0,
            "sourceName": "phpcs",
            "formatLines": 1,
            "formatPattern": [
              "^.*:(\\d+):(\\d+):\\s+(.*)\\s+-\\s+(.*)$",
              {
                "line": 1,
                "column": 2,
                "message": 4,
                "security": 3
              }
            ],
            "securities": {
              "error": "error",
              "warning": "warning"
            }
          }
        },
        "filetypes": {
          "php": "phpcs"
        }
      }
    }
  }
}
```
From instruction manual install is:  "yarn global add diagnostic-languageserver"
How i can use vim-plug for it?

**Comment by chemzqm** [comment]
You can make vim-plug install and compile it, then use absolute path as command.

**Comment by dementor5** [comment]
At me earned only with the indication of a full relative way in coc-settings.json:

```
{
  "languageserver": {
    "dls": {
      "command": "/home/user/.vim/plugged/diagnostic-languageserver/bin/index.js"
       another line...

```

and this line in .vimrc:
`Plug 'iamcco/diagnostic-languageserver', { 'do': 'yarn install' }`

There is some opportunity to specify a relative way for example from coc plugin? Something like
"command": "../../diagnostic-languageserver/bin/index.js"?

**Comment by chemzqm** [comment]
> There is some opportunity to specify a relative way for example from coc plugin?

No, but you can use `~` as home directory.

**Comment by dementor5** [comment]
I tried, ~ unfortunately does not work for me, only full absolute path. :(
This plug-in very much lacks more friendly way of connection of third-party plug-ins.

**Comment by chemzqm** [comment]
You can configure by use viml, checkout the doc.

**Comment by chemzqm** [comment]
> This plug-in very much lacks more friendly way of connection of third-party plug-ins.

It exposes many api for other plugin，and you can use other plugin if you like their API.

**Comment by dementor5** [comment]
> You can configure by use viml, checkout the doc.

I tried in my .vimrc this:
```
call coc#config('languageserver', {
\ 'dls': {
\   "command": $HOME . "/.vim/plugged/diagnostic-languageserver/bin/index.js",
\ }
\ })
```
but it fully rewrite .coc-settings.json config.Whether there is a way of partial rewriting of a config?
Whether there is a way of partial rewriting of a config?
Is there way of partial rewriting of config?  As idea: to specify "command" value in .vimrc, and all the rest in coc-setting.json

> It exposes many api for other plugin，and you can use other plugin if you like their API.

I am sorry If i offended you. I ask look at it as the offer to improve this moment in plugin.
