### ISSUE TITLE
Problem when accept completion, special case

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#654]
Hey!

I have a problem, when i have code like this

Correct:
```php
$uri = rawurldecode(
    parse_url(trim(...)) // ... = cursor
)
```

when accept completion for function trim i get one empty line above, e.g.

Wrong:
```php
$uri = rawurldecode(
... // ... = cursor
    parse_url(trim)
)
```

**Comment by chemzqm** [comment]
Provide output of your language server: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by mihaelartz** [comment]
@chemzqm with and without ls same problem

**Comment by mihaelartz** [comment]
@chemzqm https://gist.github.com/mihaelartz/70f763e8d0c703e358802a80fd20353b this is output of LS

**Comment by chemzqm** [comment]
> when accept completion 

Would you try accept completion  by press `<C-y>`?

**Comment by mihaelartz** [comment]
@chemzqm this is my map for accepting completion
imap <expr><cr> pumvisible() ? '<c-y>' : '<cr>'

**Comment by mihaelartz** [comment]
```
imap <expr><cr> pumvisible() ? '<c-y>' : '<cr>'

**Comment by chemzqm** [comment]
It could be changed by your other plugin.

**Comment by chemzqm** [comment]
You should check `:verbose imap <CR>`

**Comment by mihaelartz** [comment]
![2019-04-05-125800_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/55623161-745bc300-57a2-11e9-9dec-6c8b1d6a8b04.png)

**Comment by mihaelartz** [comment]
@chemzqm Yep problem is auto-pairs plugin

**Comment by chemzqm** [comment]
It's problem of the plugin you're using.

**Comment by chemzqm** [comment]
Use `  inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"` if you want format on type by press `enter`.
