### ISSUE TITLE
Can't switch to next parameter

### ISSUE THREAD

**Issue by cipherspec** [neoclide/coc.nvim#658]
**Describe the bug**
I have configured the "Example vim configuration" as proposed in the readme, but I have problems working with coc completions.

When for example opening helloworld.py and typing "class", I get the class body proposed and can expand it via Enter (<cr>) and the cursor jumps to the classes name, but after typing that I have no clue how to switch to the function parameters and enter them - which, as one can see in the demo screencast on repos main page, should be possible.

All other mappings are clean. I'm using iTerm2 on Mac with US ANSI keyboard layout.

Did I miss something in the concept, or just a mapping?

Thanks!

**Comment by chemzqm** [comment]
Be default, you can use `<C-j>` for jump to next placeholder, checkout https://github.com/neoclide/coc.nvim/wiki/Using-snippets
