### ISSUE TITLE
b:coc_diagnostic_info doesn't have eslint diagnostic info

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#66]
**Describe the bug**
`b:coc_diagnostic_info` doesn't have the eslint diagnostic info, i don't know if it's a bug

**Comment by iamcco** [comment]
just have tsserver diagnostic or eslint disgnostic

**Comment by chemzqm** [comment]
I just tested master branch, it's working as expected, it eslint enabled for your file?

**Comment by iamcco** [comment]
```
function test ) { }
test()
```

`b:coc_diagnostic_info` show only one error 

![image](https://user-images.githubusercontent.com/5492542/45172344-9fdff480-b237-11e8-9ad2-5096e8d70da4.png)
lopen:
![image](https://user-images.githubusercontent.com/5492542/45172317-9191d880-b237-11e8-9ded-523728c110ae.png)
