### ISSUE TITLE
:write is slow

### ISSUE THREAD

**Issue by frangio** [neoclide/coc.nvim#661]
<details>
<summary>CocInfo</summary>

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.64
term: xterm-termite
platform: linux

</details>

When I save a file (`:w`) there is a quarter of a second delay until the cursor leaves the command line and is back in the buffer. It's not a lot but it's definitely noticeable. Is there anything that can be done to improve that? There is no noticeable delay when coc.nvim is not used.

**To Reproduce**

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

`nvim -u mini.vim test`
`:w`

**Comment by chemzqm** [comment]
Remove the filetype from `"coc.preferences.formatOnSaveFiletypes"` and disable `autoFixOnSave` provided by extensions.

**Comment by frangio** [comment]
Were you unable to reproduce the delay?

The above steps open an empty file with no filetype, and the delay is there even with no extensions installed. So the fixes you suggested don't seem to apply.

**Comment by chemzqm** [comment]
I can't reproduce, it doesn't do anything on save unless you tell it to.

**Comment by frangio** [comment]
I think the steps above aren't self-contained because it's still picking up the extensions I have installed even with `-u mini.vim`. How can I run an instance of nvim without coc loading any of my extensions?

**Comment by chemzqm** [comment]
Try comment this line https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L177 and see if problem still exists.

**Comment by frangio** [comment]
Commenting that line removes the delay, yeah.

**Comment by chemzqm** [comment]
I've removed document validation on BufWritePre, also add a log for the time cost on save.

**Comment by amsword** [comment]
on my side, i also had this issue and it works by commenting out BufWritePre

**Comment by linrongbin16** [comment]
How to disable coc format ?

**Comment by linrongbin16** [comment]
same issue, comment https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L177 and solved issue.

**Comment by Giatroo** [comment]
I was having the same problem, but just inside .cpp files. Commenting the 177th line worked for me.

**Comment by tony** [comment]
Is anyone still getting this?  I am not sure if I am or not, but after I added `coc-prettier`, I'm getting this really long hangups (like freezing) on saving

It's not predictable when it happens

The only solution I have at the moment is `killall -9 node` which frees up vim so I can type again
