### ISSUE TITLE
File watching

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#663]
Can you implement file watching system (Indexing on workspace change)?

This is not a problem with the LS, the problem is in the client.

**Comment by chemzqm** [comment]
It's implemented https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#optional-install-watchman-for-file-watching

**Comment by mihaelartz** [comment]
@chemzqm Ok, watchman is installed but same problem, i need to configure them or?

**Comment by chemzqm** [comment]
Your language server need to regist files to watch and support https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeWatchedFiles

**Comment by mihaelartz** [comment]
@chemzqm How to see if watchman, watch the project? LS support workspace_didChangeWatchedFiles

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
There's a output channel for watchman.

**Comment by mihaelartz** [comment]
@chemzqm This is output https://gist.github.com/mihaelartz/b64ffd9be3a85fcb61afc980da4a0bd3

When I'm in Neovim, LS is started and i install some packages, i must be to restart server for reindexing, i contact a author from LS and this is answer:
```
This is likely the client you are using. The server doesn't have any file watching capabilities and relies on the client to notify it of changes to the workspace.

**Comment by chemzqm** [comment]
Your language server doesn't regsit file change notification, so client doesn't send event to it.

Please read: https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeWatchedFiles
