### ISSUE TITLE
Help with gopls

### ISSUE THREAD

**Issue by lanox** [neoclide/coc.nvim#664]
Hi 

I am not sure if this is a issue or maybe just me not knowing how to configure it, I am using go1.12.1 darwin/amd64.

I am trying to configure gopls in coc-settings.json

```
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
```

I have also install gopls as per this instructions, https://github.com/golang/go/wiki/gopls
```go get -u golang.org/x/tools/cmd/gopls```

however autocompletion is not working, If i change it to go-langserver it's working fine.

if you could assist would be greatly appreciated.

**Comment by chemzqm** [comment]
It looks like you need to pass extra arguments to the command, but I'm not sure.

**Comment by lanox** [comment]
```
2019/04/08 13:23:57 get package failed: no packages found for /Users/xx/code/go/src/github.com/lanox/lanox.go
2019/04/08 13:23:58 get token failed: no packages found for /Users/xx/code/go/src/github.com/lanox/lanox.go
```

adding  under gopls in coc-settings.json "args": ["-logfile=lano.log"], I get above error messages

**Comment by taigacute** [comment]
@lanox  try this 
```
git clone -b bingo https://github.com/saibing/tools.git
cd tools/cmd/gopls
go install
```

**Comment by lanox** [comment]
@taigacute tried that as well, no luck, that was the first thing I did. 

After digging more through it, it seems that only works if you are in your GOPATH.

**Comment by taigacute** [comment]
@lanox  no it surpport go mod project you should `go mod init `

**Comment by taigacute** [comment]
> @taigacute tried that as well, no luck, that was the first thing I did.
> 
> After digging more through it, it seems that only works if you are in your GOPATH.
> e.g
> if I am in my $HOME, and I do `vi lanox.go` autocompletion will not work.
> 
> If I am navigate to my `$GOPATH` and do same as above, autocompletion works, although I don't get any documentation on floating window like I do with go-langserver.

this is a question  i said to @chemzqm . the `dohover` of gopls works well on vscode. but didnt work with coc

**Comment by chemzqm** [comment]
> the dohover of gopls works well on vscode. but didnt work with coc

Need output of language server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by lanox** [comment]
I am little confused with gopls, if I open my existing project it seems that autocompletion works, however if I start new project and start typing code, autocompletion will not work.

**Comment by taigacute** [comment]
@lanox  if your project is a go mod pro you should `go mod init` first，Known issue, unsaved buffer import third party package auto completion is not working, waiting to be repaired，Gopls are unstable and have many problems.

**Comment by lanox** [comment]
@taigacute that is the interesting part, it is not this is just a normal folder with a .go file in it.

**Comment by chemzqm** [comment]
It might requires a correct workspaceFolder to work ,check out https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

**Comment by lanox** [comment]
ah, I am giving up on gopls, its just pain, and random.

**Comment by alzedd** [comment]
```
    "languageserver": {
        "golang": {
            "command": "gopls",
            "filetypes": ["go"],
        }
    }
```

this is my settings for gopls. 
1. be sure to have $GOPATH correctly set 
2. use go-modules  (You will get an error code 0 otherwise)
3. the go file must exsist, you can't just open a new buffer (eg `:e newfile.go`)

**Comment by Cluas** [comment]
https://github.com/golang/go/issues/29202

**Comment by lanox** [comment]
Has anyone had any luck setting up any of GO language servers. I cant seem to get auto completion working for gopls or go-langserver. Can someone please help me out, or help me troubleshoot it.

**Comment by taigacute** [comment]
works well
![11](https://user-images.githubusercontent.com/41671631/57215509-aff6e080-701f-11e9-868e-f273915686df.png)

**Comment by Akin909** [comment]
I managed to get it working with @alzedd's advice but it doesn't show any completion till you hit `.` so in my case for the screenshot above `log` wouldn't be in the autocompletion only `log.F` would give options

**Comment by taigacute** [comment]
@Akin909   i  use my config not @alzedd 's advice.

**Comment by lanox** [comment]
It seems to be working okay for me, however no floating windows, but I think that is due to gopls issue.

**Comment by taigacute** [comment]
@lanox  not snippets. do you see the `[ls]` that mean the completion from server

**Comment by lanox** [comment]
Yep  I agree, i did not see that, however I did see in your config that your snippets also have stars, so I just assumed. Never assume I guess.

**Comment by taigacute** [comment]
never mind. the `gopls` has some problem  if you are a new golang beginner.maybe try goland.

**Comment by luan** [comment]
@lanox did you get it working with upstream gopls? It'd be great if coc.nvim didn't depend on the fork. Installing from the fork is a pain and it breaks all sorts of things with `golang.org/x/tools`

**Comment by lanox** [comment]
@luan no not really, its sporadic, but I haven't tried it in a while.

**Comment by ucef29** [comment]
workAround: add the full path to your gopls in the cocConfig json... here:

{
  "languageserver": {
    "golang": {
      "command": "[full-path-to-your-gopls-binary]/gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
  }
}

**Comment by LuisPe** [comment]
Thanks @ucef29 your suggestion "command": "[full-path-to-your-gopls-binary]/gopls" working for me.
Than you very much 💯

**Comment by oblitum** [comment]
There's the coc-go extension too, which is even nicer and easier to use.
