### ISSUE TITLE
[Suggestion] add a command to open messages in the Preview window, like :ALEDetail

### ISSUE THREAD

**Issue by JulioJu** [neoclide/coc.nvim#666]
**Is your feature request related to a problem? Please describe.**
It seems it's not possible to show linter messages into a preview window. If the linter error is very long, it's annoying. Actually you simply advise to use `set cmdheight=2` but on small screen it could be not the best, and message could be cut. 

**Describe the solution you'd like**
On ALE, there is a solution. A command `:ALEDetail`: «  Show the full linter message for the  problem nearest to the cursor on the given line in the preview window.  » (see https://github.com/w0rp/ale/blob/master/doc/ale.txt )

Could you add a command like this please?

Thanks in advance ;-)

**Comment by chemzqm** [comment]
See `:h n_coc-diagnostic-info` and `:h coc-action-diagnosticInfo`

If you like command, you can create command by use `CocAction("diagnosticInfo")`

**Comment by chemzqm** [comment]
Or use latest neovim for floating window support.

**Comment by JulioJu** [comment]
@chemzqm  thanks for your answer

Therefore I use 
```vim
        command! -nargs=0 CocDetail :call CocAction('diagnosticInfo')
```

I've installed Neovim 0.4 to have floating window, but for `diagnosticInfo` I don't like it. When there has an error, the message hide the code under the floating window. How can I disable floating window just for `diagnosticInfo` ?

Thanks in advance !

**Comment by chemzqm** [comment]
Set `"diagnostic.messageTarget": "echo"` in settings.json.

**Comment by JulioJu** [comment]
Thanks ! Maybe it could be cool to add it in README.md, because when Neovim 0.4 will be release, maybe lot of persons will don't like the new behaviour ?

**Comment by chemzqm** [comment]
Added to faq.
