### ISSUE TITLE
No symbol highlighting when no language server is used

### ISSUE THREAD

**Issue by gbcreation** [neoclide/coc.nvim#67]
First, a big thank you for this awesome completion plugin! :) 

**Describe the bug**
Highlighting of the symbol under cursor does not work for some filetypes when a language server is not used. For example, for Vim scripts.

**To Reproduce**
1. Open a Vim script
2. Put the text cursor on a variable

**Expected behavior**
The symbol under cursor and other references should be highlighted.

**Desktop (please complete the following information):**
 - Terminal: Konsole on ArchLinux
 - Version: 18.08.0

**Comment by chemzqm** [comment]
There's no vim service, just a neco source for vim script completion, so that feature is not available.

**Comment by gbcreation** [comment]
It would be great that coc.nvim does the word under cursor highlighting itself when no service is available for the current filetype.

**Comment by chemzqm** [comment]
Use https://github.com/neoclide/coc-highlight

**Comment by gbcreation** [comment]
Works perfectly :+1: 
Thank you
