### ISSUE TITLE
coc-python + MPLS + Floating window syntax highlight

### ISSUE THREAD

**Issue by esn89** [neoclide/coc.nvim#672]
**Result from CocInfo**

https://pastebin.com/UJ3frqC4

**Describe the bug**
Looking at the reddit gif of the floating window's documentation, everything is formatted nicely with syntax highlighting: https://i.redd.it/8el52cfz9fm21.png

I am trying to get that to work with my Microsoft Python Language Server

**To Reproduce**

- brew install --HEAD neovim
- Used the NON binary version of coc.nvim

Here are the coc settings I have:
```
" use <tab> for trigger completion and navigate next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"

" Diagnostic navigation
nmap <silent> <Leader>l <Plug>(coc-diagnostic-prev)
nmap <silent> <Leader>n <Plug>(coc-diagnostic-next)

" Highlight symbol under cursor on CursorHold
autocmd CursorHold * silent call CocActionAsync('highlight')

" Smaller updatetime for CursorHold & CursorHoldI
set updatetime=300

" Remap for rename current word
nmap <leader>rn <Plug>(coc-rename)

" Remap for format selected region
vmap <leader>d  <Plug>(coc-format-selected)
nmap <leader>d  <Plug>(coc-format-selected)

" hi default CocHighlightText guibg=#f9f5d7
hi default CocHighlightText guibg=#fbf1c7

let g:coc_force_debug = 1
```

**Screenshots**
![img](https://i.imgur.com/Htg2cmj.png)
Without syntax highlighting nor proper formatting.

**Comment by chemzqm** [comment]
You're using code from 0.0.64 tag, `coc.nvim version: 0.0.64`.
You need remove `'tag': '*'` from Plug command and reinstall coc.nvim.

**Comment by esn89** [comment]
@chemzqm 

Hi, in my vim-plug, I have this line however:
```
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
```

This makes sure that I am doing it via the release method.

**Comment by chemzqm** [comment]
Ok, I get the problem, the documentation is python docstring, so I don't know how to highlight it right now.

**Comment by esn89** [comment]
Aaah I see.

I saw in another issue here https://github.com/neoclide/coc.nvim/issues/511#issuecomment-480861751 that that was the problem.

Now I understand.  Thank you for your reply, @chemzqm

**Comment by esn89** [comment]
One thing I did notice now, with MPLS is this, it *sort of* works with the light theme, but there are some strange parsing problems.  Allow me to demonstrate:

!(image)[https://i.imgur.com/ScuNil6.png]

**Comment by chemzqm** [comment]
> I cannot tell if this is a problem with MPLS, or the failure of parsing on the client side with CoC.

Looks like vscode render it as html, so need a fix for it.

**Comment by esn89** [comment]
Thank you for fix.
