### ISSUE TITLE
Install requires arguments

### ISSUE THREAD

**Issue by JamesApple** [neoclide/coc.nvim#68]
**Describe the bug**
Post install hook fails for vim plug stating that install requires arguments despite it being noted in docs in several place to be used in this fashion

**To Reproduce**
1. Add this line to vimrc
`Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}`

2. Run `:PlugInstall`
```
- Finishing ... Done!
x Post-update hook for coc.nvim ... Vim(return):E119: Not enough arguments for function: coc#util#install
```

**Expected behavior**
No errors :)

**Comment by chemzqm** [comment]
There's a name conflict that I didn't notice.
