### ISSUE TITLE
"suggest.enablePreview": true has no effect

### ISSUE THREAD

**Issue by bgx90** [neoclide/coc.nvim#681]
**Result from CocInfo**
## versions

vim version: NVIM v0.3.4
node version: v10.15.3
coc.nvim version: 0.0.64
term: xterm-256color
platform: linux

## Error messages

**Describe the bug**
Setting `"suggest.enablePreview": true` in `coc-settings.json` is not causing the preview window to appear with information on the currently selected completion option.

**To Reproduce**
Use neovim v0.3.4 with coc-json and coc-java installed
- [init.vim](https://github.com/neoclide/coc.nvim/files/3056495/init.vim.txt)
- [coc-settings.json](https://github.com/neoclide/coc.nvim/files/3056504/coc-settings.json.txt)
- map manual completion with `inoremap <buffer><silent><expr> <C-X><C-O> coc#refresh()` (I do this using filetype-specific vimscripts in `~/.config/nvim/after/ftplugin`)

1. Run `:CocConfig` and try using autocompletion (preview window is not displayed)
2. Try using autocompletion in a Java file (preview window is not displayed)

**Screenshots**
![image](https://user-images.githubusercontent.com/7351168/55762643-55229700-5a29-11e9-8a1c-82ae48065d0a.png)

**Comment by chemzqm** [comment]
For some language server, documentation only exists after completion resolve, so you may not have them.

Consider use latest neovim with floating window support.
