### ISSUE TITLE
[coc.nvim] Error output from phpls: Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by dalingng** [neoclide/coc.nvim#683]
![image](https://user-images.githubusercontent.com/3541321/55771556-2228e380-5abb-11e9-97bb-67b915a9f5b4.png)
![image](https://user-images.githubusercontent.com/3541321/55771628-6b793300-5abb-11e9-941b-564c2d8dcb25.png)
![image](https://user-images.githubusercontent.com/3541321/55771631-6ddb8d00-5abb-11e9-8b01-4f0486defb42.png)

**Comment by dalingng** [comment]
## versions
  
  vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 25 2019 14:23:08)
  node version: v10.15.1
  coc.nvim version: 0.0.64
  term: dumb
  platform: linux
  
  ## Error messages
      
  ## Output channel: phpls
  internal/modules/cjs/loader.js:583
      throw err;
      ^
  
  Error: Cannot find module '/home/dng/.config/coc/extensions/node_modules/coc-phpls/node_modules/intelephense/lib/intelephense.js'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
      at Function.Module._load (internal/modules/cjs/loader.js:507:25)
      at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  [Info  - 11:45:03] Connection to server got closed. Server will restart.
  internal/modules/cjs/loader.js:583
      throw err;

**Comment by dalingng** [comment]
:CocInstall coc-phpls
error:
 ## versions
  
 vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 25 2019 14:23:08)
 node version: v10.15.1
 coc.nvim version: 0.0.64
term: dumb
platform: linux

 ## Error messages
error on notification 'CocInstalled': TypeError: Cannot read property 'deactivate' of undefined

**Comment by chemzqm** [comment]
It's bug of coc-phpls
``` js
        serverModule = context.asAbsolutePath(path.join('node_modules', 'intelephense', 'lib', 'intelephense.js'));
``
it should use file from `require.resolve`.

You can fix it by use vim-plug to install coc-phpls https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension
