### ISSUE TITLE
Possible to jump to symbol under cursor?

### ISSUE THREAD

**Issue by tomspeak** [neoclide/coc.nvim#687]
Trying to get symbols to work with what I am currently hovered on (if anything).

`nnoremap <silent> <c-s> :<C-u>CocList -I symbols expand("<cword>")<CR>`

This works in other remapping for other plugins, but this seems to never be expanded. Any ideas?

**Comment by chemzqm** [comment]
What's problem with goto deifinition?

**Comment by tomspeak** [comment]
For some reason in my PHP/Laravel project, it does not pick up go to definition on any symbol.

![image](https://user-images.githubusercontent.com/2415569/55815617-8c0bb200-5ae8-11e9-9641-7908e747b77f.png)

But manually searching for the symbol works fine:

![image](https://user-images.githubusercontent.com/2415569/55815709-ac3b7100-5ae8-11e9-881a-a034976a627d.png)

**Comment by chemzqm** [comment]
You should use command like:
``` vim
nnoremap <silent> <c-s>  :exe 'CocList -I --normal --input='.expand('<cword>').' symbols'<CR>
```

**Comment by tomspeak** [comment]
Works perfectly. Just improved my workflow massively, thank you.

**Comment by NikosEfthias** [comment]
> You should use command like:
> 
> ```viml
> nnoremap <silent> <c-s>  :exe 'CocList -I --normal --input='.expand('<cword>').' symbols'<CR>
> ```

is there any way to accept the item from the resulting list without hitting <cr> again ?
