### ISSUE TITLE
Display red sing which is before the line number with code error

### ISSUE THREAD

**Issue by dementor5** [neoclide/coc.nvim#688]
Whether there is an opportunity to set  the display of mistakes as in ale: red symbol which is before the line number with a code mistake?
![aleDisplayMistakes](https://user-images.githubusercontent.com/22612354/55820334-912a2a80-5b03-11e9-99c6-07fbfa148e26.png)

**Comment by dementor5** [comment]
You closed a problem without any comment...
There is no built-in opportunity to reach similar visual effect?

**Comment by chemzqm** [comment]
I can't understand your question.
Consider reproduce by use minimal vimrc.

**Comment by dementor5** [comment]
Thanks for the direction for search.
I found a problem - it is the conflict of vim-gitgutter and coc.nvim.
This plug-in works with ale well.
With coc.nvim red arrows just do not appear.: (

**Comment by chemzqm** [comment]
There is priority for sign on vim recently, but not exists with neovim.

**Comment by chemzqm** [comment]
Can't fix for now.

**Comment by iamcco** [comment]
set  `"diagnostic.signOffset": 9999999` to let coc's sign get higher priority.

**Comment by dementor5** [comment]
Yes, in vim of an arrow are shown in itself.
In nvim they appeared too after I added "diagnostic.signOffset": 9999999 in coc-settings.json
Thanks!

**Comment by dementor5** [comment]
> set `"diagnostic.signOffset": 9999999` to let coc's sign get higher priority.

Will you add this value as default  in coc.vim?

**Comment by dementor5** [comment]
I found more interesting solution:
```
if has("autocmd")
 au! BufWritePost .vimrc,init.vim nested so $MYVIMRC
en
```
