### ISSUE TITLE
Question: Is it possible to configure CocInstall?

### ISSUE THREAD

**Issue by LandonSchropp** [neoclide/coc.nvim#691]
**Is your feature request related to a problem? Please describe.**

I'm setting up CoC for the first time. I have a [peronsal dotfiles repo](https://github.com/landonschropp/dotfiles) that I like to add all of my settings to so I can easily apply them to other machines. In looking through the [extensions](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions) and [configuration](https://github.com/neoclide/coc.nvim/wiki/Using-configuration-file) documentation, I didn't see any examples of how to accomplish this.

**Describe the solution you'd like**

It would be great if I could do something like this:

```
// CocConfig
{
  extensions: [
    "coc-json",
    "coc-css",
    "coc-tsserver"
  ]
}
```

I'm really looking for a simple way to configure extensions once and have CoC automatically install them in the future. If this is already possible, I'd really appreciate a pointer to existing documentation or updated docs.

**Describe alternatives you've considered**

Existential dread. 🙂

**Additional context**

Nope. Thanks for taking the time!

**Comment by chemzqm** [comment]
There is a function, and you can install extension by use vim-plug

**Comment by LandonSchropp** [comment]
@chemzqm Thanks for the quick reply! 

In reading through some open issues, I remember reading that you lose some of the niceties of extensions by installing them via vim-plug, such as auto updates. Is that still the case?

**Comment by tamorim** [comment]
@LandonSchropp I just started using coc and bumped into the same problem.
After some digging I noticed that the `coc#utils#install` checked for `g:coc_global_extensions`.
If you define this variable with the extensions you want before `coc#utils#install` is called they will be automatically installed after the setup, example:
```viml
let g:coc_global_extensions = [
\ 'coc-ultisnips',
\ 'coc-json',
\ 'coc-tsserver',
\ 'coc-html',
\ 'coc-css',
\ 'coc-yaml',
\ 'coc-highlight',
\ 'coc-angular'
\ ]

call plug#begin()

Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install() } }

call plug#end()
```

**Comment by chemzqm** [comment]
> extensions by installing them via vim-plug, such as auto updates. Is that still the case?

Since it's controlled by vim's plugin manager, it should be updated by that plugin manager. https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension

**Comment by chemzqm** [comment]
> f you define this variable with the extensions you want before coc#utils#install is called they will be automatically installed after the setup, example:

It's used to notice user install extensions, you don't need define ` g:coc_global_extensions` before `coc#util#install()`, I will remove this notice, it's not necessary.

**Comment by tamorim** [comment]
@chemzqm oh, I see! Thank you for answering so fast :sweat_smile: 
Since using `g:coc_global_extensions` isn't an option anymore, what do you think about calling the `coc#util#install_extensions` after `coc#util#install`?
```viml
function! InitializeCoc()
  call coc#util#install()
  call coc#util#install_extensions([
  \ 'coc-ultisnips',
  \ 'coc-json',
  \ 'coc-tsserver',
  \ 'coc-html',
  \ 'coc-css',
  \ 'coc-yaml',
  \ 'coc-highlight',
  \ 'coc-angular'
  \ ])
endfunction

call plug#begin()

Plug 'neoclide/coc.nvim', {'do': { -> InitializeCoc() } }

call plug#end()
```

**Comment by chemzqm** [comment]
> what do you think about calling the coc#util#install_extensions after coc#util#install?

It's not necessary, since extensions are automatic updated by default.

**Comment by LandonSchropp** [comment]
Thanks for the replies @chemzqm and @tamorim!

I feel like I might have missed something in reading through this thread. Is `g:coc_global_extensions` not recommended then?

@chemzqm I'd like to clarify my goals:

* Install Neovim on a fresh install of macOS.
* Download Plug and my dotfiles.
* Run one command, and have CoC and all of my extensions installed by default.
* Let CoC's native daily updating mechanism do its thing. 

I specifically would like to avoid using Plug to manage my CoC extensions because those language servers are being updated regularly, and I want those updates on a regular basis. So what I'm looking for is exactly what @tamorim suggested, which is a configuration that lets me declare the extensions I want so CoC can manage them for me.

If that currently exists, could you please clarify the way I should go about configuring it? And if it doesn't, I'd like to request that this issue be reopened as a feature request.

Thanks again!

**Comment by chemzqm** [comment]
Use g:coc_global_extensions with extension names.  What I mean is you should define this variable before  VimEnter, not required before coc#util#instal.

**Comment by danielcherubini** [comment]
@chemzqm I see you've moved a few extensions like `coc-gocode` to a monorepo..

This breaks the vim-plug solution.

Reason I would like this is I switch between my work and home machines often and I use a centralised config for both. I see there's a global variable.. is this the direction you want to move forward in?

**Comment by chemzqm** [comment]
`coc-gocode` is not recommended, the monorepo is only for some completion sources.
You can set  vim's `&rtp` to the subfolders after clone that monorepo, or use `g:coc_global_extensions` for them.

**Comment by Nishant-Pall** [comment]
```
> let g:coc_global_extensions = [
> \ 'coc-ultisnips',
> \ 'coc-json',
> \ 'coc-tsserver',
> \ 'coc-html',
> \ 'coc-css',
> \ 'coc-yaml',
> \ 'coc-highlight',
> \ 'coc-angular'
> \ ]
```
Am I correct to say that this function exactly does what :CocInstall does?
If not, please help me out here, what does this exactly signify

**Comment by chemzqm** [comment]
`:h g:coc_global_extensions`

**Comment by Nishant-Pall** [comment]
> `:h g:coc_global_extensions` it's a variable helps define extensions you need in vimrc.

So is it a must to mention all of the extensions here if I need them all?

**Comment by ccddan** [comment]
> @LandonSchropp I just started using coc and bumped into the same problem. After some digging I noticed that the `coc#utils#install` checked for `g:coc_global_extensions`. If you define this variable with the extensions you want before `coc#utils#install` is called they will be automatically installed after the setup, example:
> 
> ```viml
> let g:coc_global_extensions = [
> \ 'coc-ultisnips',
> \ 'coc-json',
> \ 'coc-tsserver',
> \ 'coc-html',
> \ 'coc-css',
> \ 'coc-yaml',
> \ 'coc-highlight',
> \ 'coc-angular'
> \ ]
> 
> call plug#begin()
> 
> Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install() } }
> 
> call plug#end()
> ```

Time saver, Thanks!!
