### ISSUE TITLE
Extend with copy-pastable examples to get a demo running 

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [neoclide/coc.nvim#694]
**Is your feature request related to a problem? Please describe.**

The path from seeing what the module can do to actually testing it in a demo involves a lot of steps.
The complexity of the setup can push people away from something that works ok when set up.

**Describe the solution you'd like**
Instead of overwhelming someone with a lot of new concepts, provide a set of copy-pasteable
commands or scripts so people can spend the time exploring the tool instead of losing motivation while trying to get the thing running. 

**Additional context**
For example, below is a not very clean set of steps how to get things running on a new Ubuntu 18.04 machine. These are just the steps I gathered in the process of trying to get the autocomplete to suggest me `printf` in a c file. 

Once again, it's not a pretty list of steps, can be improved a lot and I just got it to a point where it works for me and results in a working solution. It promises a newcomer not to worry about what is a language server, yarn? from where do I install nodejs?

### Steps

```
# Getting neovim
APPIMAGE_DIR=~/.local/appimages
APPIMAGE_EXECUTABLE=nvim.appimage
LOCAL_BIN=~/.local/bin
echo "export PATH=$PATH:$LOCAL_BIN" >> ~/.bashrc
mkdir $LOCAL_BIN
mkdir $APPIMAGE_DIR

wget https://github.com/neovim/neovim/releases/download/nightly/$APPIMAGE_EXECUTABLE \
     -P $APPIMAGE_DIR
chmod 755 $APPIMAGE_DIR/$APPIMAGE_EXECUTABLE
ln -s $APPIMAGE_DIR/$APPIMAGE_EXECUTABLE $LOCAL_BIN/nvim
source ~/.bashrc
mkdir ~/.config/nvim
```

```
sudo apt-get install cmake libtinfo-dev curl
curl -sL install-node.now.sh/lts | PREFIX=~/.local  bash
source ~/.bashrc
curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
source ~/.bashrc
```

```
# Fetching clang
URL="https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz"
TAR_NAME=$(basename ${URL})
CLANG_DIR=~/clang
mkdir $CLANG_DIR
wget $URL
tar -xf $TAR_NAME --strip-components=1 -C $CLANG_DIR

# Building ccls
git clone --depth=1 --recursive https://github.com/MaskRay/ccls
cd ccls
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$CLANG_DIR
cmake --build Release
cp Release/ccls ~/.local/bin


# Installing coc
ld ~/
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

cat > ~/.config/nvim/init.vim << EOF
call plug#begin('~/.config/nvim/plugin/plugged')
    Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
call plug#end()
EOF

nvim +PlugInstall +qall
# Need to confirm if this actually installs it
nvim +"CocInstall coc-ccls" +qall

cat >> ~/.config/nvim/coc-settings.json << EOF
{
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "cuda", "objc", "objcpp"],
      "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
      "initializationOptions": {
        "cache": {
          "directory": ".ccls-cache"
        }
     }
    }
  }
}
EOF
```

**Comment by chemzqm** [comment]
It works best with neoivm 0.4.0, but it's not stable.
Should be much better if we can provide a link and user could experience coc.nvim just in browser.

**Comment by TheMeaningfulEngineer** [comment]
>  Should be much better if we can provide a link and user could experience coc.nvim just in browser.

Guess that would be great, but I don't see a way how I could contribute to that.
As for the script I could polish that and make a WIP PR if you tell me where it could be located.

**Comment by chemzqm** [comment]
There're many ways for install neovim, ccls and coc.nvim, the user need to decide which way he want to.
