### ISSUE TITLE
Vim error messages disappears

### ISSUE THREAD

**Issue by dohsimpson** [neoclide/coc.nvim#696]
Thanks so much for all the hard work!

**Result from CocInfo**
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 11 2019 17:47:53)
node version: v11.12.0
coc.nvim version: 0.0.65
term: iTerm.app
platform: darwin

## Error messages

## Output channel: snippets
```

**Describe the bug**
When enabled Coc.vim, vim messages panel would only appear for a split second or not appear at all.

**To Reproduce**
1.

- Create a minimal mini.vim with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start vim with command: `vim -u mini.vim`

- Start neovim with command: `nvim -u mini.vim`

- Operate vim.

2. type command `:echo "HI"` so that there are messages
3. type command `:messages` and the dialog would appear for a split second and then disappear.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/5865309/56083180-9af7aa80-5def-11e9-9063-a9c593082b3c.gif)

**Comment by chemzqm** [comment]
It works as expected for me.

**Comment by chemzqm** [comment]
Closed, don't know what problem with your vim or caused by other vim plugin.

**Comment by bachya** [comment]
I'm experiencing the same thing: messages appear for a split second before disappearing; I have to type `:messages` to see them again.

Versions:

```
## versions

vim version: NVIM v0.3.8
node version: v10.14.1
coc.nvim version: 0.0.73-07a84965f1
term: iTerm.app
platform: darwin
```
