### ISSUE TITLE
Stay in workspace when opening non-file uris

### ISSUE THREAD

**Issue by snoe** [neoclide/coc.nvim#698]
**Is your feature request related to a problem? Please describe.**
In [my LSP server](https://github.com/snoe/clojure-lsp) I send clients to urls at a zipfile:// schema and I'm starting to look at following [eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls) in sending a proper uri with a custom scheme and let the language server provide the content. Similar to [jdt:// urls](https://github.com/eclipse/eclipse.jdt.ls) 

However both when using coc-java with jdt:// uri, or in my plugin with zipfile:// or clojure:// schemes, as soon I jump into one of the buffers it seems that coc no longer sends commands to the server. It is very useful to keep exploring these dependencies with go to definition while inside these buffers.

I'm guessing the commands stop because these buffers don't seem to have a project root? It's possible I'm missing something else though.

**Describe the solution you'd like**
Non `file://` uris should continue to send commands to the language server, in the workspace that launched the file.

**Describe alternatives you've considered**
I tried setting `"disableWorkspaceFolders": true` but that didn't work. I assumed it would make any buffer of the supported type talk to the server.

**Additional context**
In this short screen recording, you can see that the first go to def works for `completablefuture` but it does not go into `Future` from within the `jdt://` url

**Comment by chemzqm** [comment]
It's not problem of workspace, it's because only file/untitled scheme allowed for configured language server right now, extension like coc-java can handle jdt uri as excepted:  https://github.com/neoclide/coc-java/blob/baff5246334cabfc5c1d4146864d4a7d09e4d33a/src/index.ts#L107

**Comment by chemzqm** [comment]
I've added `additionalSchemes` for language server configuration section.

**Comment by snoe** [comment]
Works great, thank you!
