### ISSUE TITLE
Service could not be initialized 

### ISSUE THREAD

**Issue by llmdev** [neoclide/coc.nvim#7]
- ERROR: Service could not be initialized 

I run yarn install / npm install in folder coc.nvim

**Comment by chemzqm** [comment]
After the install succeed, you need to run `:UpdateRemotePlugins` in neovim.

https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim

**Comment by chemzqm** [comment]
The next version of coc would run in single process and you don't need install neovim module globally and no need for `:UpdateRemotePlugins `.
