### ISSUE TITLE
Unable to use go-langserver

### ISSUE THREAD

**Issue by robertgzr** [neoclide/coc.nvim#70]
**Describe the bug**
Configuring to use [go-langserver](https://github.com/sourcegraph/go-langserver) leads to errors at startup 

**To Reproduce**
`coc-settings.json`:
```json
{

  "coc.source.gocode.enable": false,

  "languageserver": {
    
    "go-langserver": {
      "command": "go-langserver",
      "args": ["-gocodecompletion", "-func-snippet-enabled"],
      "filetypes": ["go"],
      "enable": true
    },
 
  }
}
```

**Additional context**
`go-langserver` logs
```
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///home/robertgzr/code-1/src") is deprecated. Use rootUri instead.
jsonrpc2 handler: notification "workspace/didChangeConfiguration" handling error: jsonrpc2: code -32601 message: method not supported: workspace/didChangeConfiguration
[3  - 16:59:49] Request textDocument/completion failed.
  Message: invalid position: /home/robertgzr/code-1/src/main.go:1:1 (file only has 2 lines)
  Code: 0 
```

**Comment by chemzqm** [comment]
I can fix the notification problem but I still get
```
2018-09-09T03:58:37.610 ERROR (pid:6249) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/Users/chemzqm/vim-dev/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at Socket.<anonymous> (/Users/chemzqm/vim-dev/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
```
Have no idea with it.

**Comment by chemzqm** [comment]
Should be bug of https://github.com/sourcegraph/go-langserver/issues/313

**Comment by fannheyward** [comment]
https://github.com/sourcegraph/go-langserver/commit/d0a69e92f6bdce74c7acdd59fdca57cca2a9587e has fixed this error.

**Comment by chemzqm** [comment]
When I use gocode 1.11 the gocode of go-langserver get panic, see https://github.com/sourcegraph/go-langserver/issues/316

It's not panic with gocode 1.10 but I still can't get any correct completion in every situation. I think that go-langserver suck at it.

The solution is not to use completion of go-langserver or help them to fix the problem.

**Comment by chemzqm** [comment]
It works as expected on my mac now, try update go-langserver.
