### ISSUE TITLE
Conflict with gitgutter on startup

### ISSUE THREAD

**Issue by JulioJu** [neoclide/coc.nvim#700]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.4.0-608-g987619ddd
node version: v10.15.3
coc.nvim version: 0.0.64-f32014ccd4
term: xterm-256color
platform: linux

## Error messages

## Output channel: java
[Info  - 2:09:47 PM] JDT Language Server started
[object Object]
```

Version on Neovim:  https://github.com/neovim/neovim/commit/987619ddd73e792dc04b1a408b92cef2abb52bef commited on Apr 15, 2019 (last one version of Neovim when the current issue is open)

**Describe the bug**

On startup, when there is already a GitGutter sign on a line where there is an error, coc doesn't display its own error sign

**To Reproduce**

```sh
mkdir /tmp/helloword
cd /tmp/helloword
touch helloword.java
git init 
git add helloword.java
echo "hello" > helloword.java
nvim -u ~/test.vim helloword.java
```

~/test.vim :
```vim
set nocompatible
filetype plugin indent on
syntax on
set hidden
set signcolumn=yes

" VimPlug
call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {
            \ 'do': { -> coc#util#install()}
            \ }

" Vim Gutter
" https://github.com/airblade/vim-gitgutter
" A Vim plugin which shows a git diff in the gutter (sign column) and stages/undoes hunks.
Plug 'airblade/vim-gitgutter'

call plug#end()
```

**Workaround**

A workaround to fix this issue is add in `~/.vim/coc-settings.json` :
```
  "coc.preferences.diagnostic.displayByAle": true
```

**See also**

https://github.com/neoclide/coc.nvim/issues/414 from @taigacute 

add `TextChangedI * GitGutter` as @taigacute  advise in this issue doesn't fix the issue.

**Comment by iamcco** [comment]
https://github.com/neoclide/coc.nvim/issues/688#issuecomment-481704656

**Comment by JulioJu** [comment]
@iamcco  ok thanks ;-)

**Comment by taigacute** [comment]
hmmm like this ?
![go](https://user-images.githubusercontent.com/41671631/56132762-6f2a1f80-5fbd-11e9-8b95-70ef686e80f9.gif)

**Comment by JulioJu** [comment]
@iamcco  tested by add `  "coc.preferences.diagnostic.signOffset": 1000,` in `~/.vim/coc-settings.json` like you advise, without success.

**Comment by JulioJu** [comment]
@taigacute thanks for your cool screenshot, but no it not seems to be that.

Probably you could reproduce thanks the little shell script provide in the first comment. Could you reproduce ?

**Comment by iamcco** [comment]
@JulioJu No, my advise is 9999999

**Comment by chemzqm** [comment]
It can't be fixed since only one sign would be shown in signcolumn, you can use something like `set signcolumn=auto:2` for neovim, but I don't like that personally.

**Comment by JulioJu** [comment]
@iamcco thanks it works !

@chemzqm  maybe you could add this advise in the README.md, because all users of git-gutter should have this problem !

**Comment by JulioJu** [comment]
@chemzqm 
I would say, maybe advise in README.md to add   
`"coc.preferences.diagnostic.signOffset": ,9999999` in ~/.vim/coc-settings.json 

coc signs are much more important than git-gutter signs ! What do you think ?

**Comment by chemzqm** [comment]
Added to readme https://github.com/neoclide/coc.nvim/wiki/F.A.Q#sign-of-diagnostics-not-shown

I prefer gutter signs, since I have statusline integration and highlight enabled, not care about the gutters.

**Comment by JulioJu** [comment]
@chemzqm so cool !

Maybe we could add at the end of https://github.com/neoclide/coc.nvim/wiki/F.A.Q#sign-of-diagnostics-not-shown « (…)  the default value is 1000. Otherwise you could add signcolumn thanks the Vim option `set signcolumn=auto:2` ».  It's a clear and short advise.

Are you ok to add this sentence in the FAQ?

**Comment by chemzqm** [comment]
Sure, you can edit it.

**Comment by JulioJu** [comment]
Done ;-)

**Comment by 0xff91** [comment]
> hmmm like this ?
> ![go](https://user-images.githubusercontent.com/41671631/56132762-6f2a1f80-5fbd-11e9-8b95-70ef686e80f9.gif)

what status line do you use and how to config green line in the side? thank you
