### ISSUE TITLE
can coc-list outline on the right window like tagbar ?

### ISSUE THREAD

**Issue by IndexXuan** [neoclide/coc.nvim#701]
**Is your feature request related to a problem? Please describe.**
coc outline was on the bottom of the window, can it be the right like tagbar

**Describe the solution you'd like**
an option to set the position and layout of coc outline

**Describe alternatives you've considered**
N / A

**Additional context**
Just remove tagbar and vista.vim, but coc outline is on the bottom, please give options to set

**Comment by chemzqm** [comment]
No, it's not designed to work like that, maybe a new component in the future.
You should use other plugin.

**Comment by wimstefan** [comment]
Hmm I have to admit that I'd applaud that new component very much so :)
Not only for the outline list but as a general feature for the list window position. I'm boiling down my vim configuration at the moment to not use too much plugins and do as much as I can with the one of my choice: coc.nvim :)

**Comment by fannheyward** [comment]
@wimstefan Try https://github.com/liuchengxu/vista.vim

**Comment by wimstefan** [comment]
> @wimstefan Try https://github.com/liuchengxu/vista.vim

Thanks a lot for the quick response! But as I said I want to reduce the amount of plugins I use ...
I'm using coc.nvim mostly for completion and lists as buffers, history, colors and grep - some of them with `--auto-preview` ... it would be just a nice feature to have that list window on the right side as the `CocInfo` window is already ;-)
