### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by mandreyel** [neoclide/coc.nvim#708]
**Describe the bug**
Every now and then vim-node-rpc, which I believe is used by coc.nvim, crashes with the following error message:
```
[vim-node-rpc] rpc error: [rpc.vim] rpc error Unexpected token e in JSON at position 0
```
which is printed repeatedly in vim's buffer near the bottom (forget the term), rendering any further use of vim impossible, which usually has to be killed.

**To Reproduce**
Difficult to reproduce as it comes up every few hours and not sure what triggers it. Also, when it's triggered, there is not much I can do (e.g. run `:CocInfo`) because vim becomes unresponsive due to this error.

Thanks for your work on coc.nvim btw, it has been great other than this issue.

**Comment by chemzqm** [comment]
Should be bug of vim-node-rpc.

**Comment by chemzqm** [comment]
I've made some fix to vim-node-rpc, upgrade it by `yarn global add vim-node-rpc`.

If you get the issue next time, please upload the log of vim-node-rpc, get the log by:
```
node -e 'console.log(path.join(os.tmpdir(), "vim-node-rpc.log"))'
```
