### ISSUE TITLE
CocAction('diagnosticInfo') does not work with "diagnostic.enableMessage": "never"

### ISSUE THREAD

**Issue by blahgeek** [neoclide/coc.nvim#711]
**Result from CocInfo**

```
## versions

vim version: NVIM v0.4.0-dev
node version: v11.14.0
coc.nvim version: 0.0.65-79a37ff062
term: iTerm.app
platform: darwin
```

**Describe the bug**
`:CocAction('diagnosticInfo')` does not work with "diagnostic.enableMessage" set to "never".
Setting "diagnostic.enableMessage" to "jump" would work though. I am doing this because I do not want the diagnostic message to automatically popup, however I still want to manually trigger it.

**To Reproduce**

- Set "diagnostic.enableMessage" to "never" in coc-settings.json
- `:CocAction('diagnosticInfo')` on text with diagnostics

**Comment by blahgeek** [comment]
Oh maybe that's what "jump" means... never mind, my bad

**Comment by andys8** [comment]
@chemzqm Is `"enableMessage" "jump"` expected to work with `"messageTarget" "float"`?
