### ISSUE TITLE
suggest give a cmd to diagnostic current file

### ISSUE THREAD

**Issue by pangchol** [neoclide/coc.nvim#712]
diagnostic always  auto run at background, the problem is when I return normal mode from I insert mode, if the file is bigger than 5000 line,  the auto diagnostic action often let the vim block some time. even then the block is only less than 1 second, because the operation is very frequent, I still prefer to turn off the diagnostics in peacetime, and trigger it manually when needed, now seem no manual way to diagnostic current file, the <Plug>(coc-diagnostic-info) seem only diagnostic current line, so I suggest give a cmd  to diagnostic current file and also give a config to let diagnostic is true on but always not auto run check.

**Comment by chemzqm** [comment]
You can't manual trigger diagnostics for language server, but there is `"diagnostic.refreshAfterSave"` settings could help.
