### ISSUE TITLE
<Plug>(coc-definition) doesn't work on first character of symbol

### ISSUE THREAD

**Issue by daturkel** [neoclide/coc.nvim#714]
**Result from CocInfo**

```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.15.3
coc.nvim version: 0.0.65-8d2c1ac210
term: iTerm.app
platform: darwin

## Error messages

```

**Describe the bug**
The (coc-definition) function doesn't seem to work if the cursor is over the first character in a symbol name.

**To Reproduce**

`mini.vim`
  ```vim
set nocompatible
set runtimepath^=~/.config/nvim_plugins/coc.nvim
set runtimepath^=~/.config/nvim_plugins/coc-python
filetype plugin indent on
syntax on
set hidden
nmap <silent> gd <Plug>(coc-definition)
  ```

`test.py`:
```python
def myfunc(ab):
    """
    i am documentation
    """
    print("hello")

myfunc
```
Run:
`nvim -u mini.vim test.py`

Cursor to the `y` in the second instance of `myfunc` and hit `gd`: cursor gets moved to the first line, as expected.

Cursor to the `m` in the second instance of `myfunc` and hit `gd`: get error "`[coc.nvim] Definition not found`"

**Comment by chemzqm** [comment]
It should be server not started, checkout `:h coc-status` for statusline integration.

**Comment by daturkel** [comment]
Hi @chemzqm , thanks for the quick response. However, `coc-python` uses Jedi by default, so I don't think it's a language server issue. Additionally, I know the plugin is online because I can move one character over and the command works.

I've tested and found that the same thing works with the show-documentation command:
It works i the middle of a word, but not on the first character of the word.

Were you not able to reproduce my example above?

**Comment by chemzqm** [comment]
I tried exact code you've provided, it works as expected after server started.

Consider checkout verbose output: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Fixed on coc-python 1.1.16

**Comment by daturkel** [comment]
So quick, thank you!

**Comment by YUNZHONGTAN** [comment]
I have this problem with golang, "[coc.nvim] Definition not found"
