### ISSUE TITLE
Make Language Server for XML like YAML, JSON

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#716]

**Comment by chemzqm** [comment]
Use https://github.com/neoclide/coc-json and https://github.com/neoclide/coc-yaml

**Comment by mihaelartz** [comment]
@chemzqm I prefer json but frameworks like phpunit, maven and others use XML for configuration

**Comment by mihaelartz** [comment]
@chemzqm and the same ones have a lot of options and a good support for XML would be good. Sorry for my bad English!

**Comment by chemzqm** [comment]
Checkout https://microsoft.github.io/language-server-protocol/implementors/servers/ implement language server is not target of coc.nvim.

**Comment by fannheyward** [comment]
@mihaelartz try https://github.com/fannheyward/coc-xml, just fork from vscode-xml, based on the LSP4XML Language Server.
