### ISSUE TITLE
Location of the coc-settings.json file

### ISSUE THREAD

**Issue by nostdm** [neoclide/coc.nvim#718]
**Problem**

At the moment `coc` configuration files can be found in `$HOME/.config/coc` and `$HOME/.config/nvim`. As far as I know there is no option to change the location of the settings file. Since I like to keep my `$HOME/.config/nvim` directory clean and organised, I would like to be able to put all the `coc` related configuration inside `$HOME/.config/coc` and keep `$HOME/.config/nvim` for vimscript configuration only. 

**Feature request**

Provide a way to override the default configuration file location either in the `init.vim` by setting a global variable e.g. `let g:coc_config_file="$HOME/.config/coc/settings.json"` or as a command line flag when running the `coc` server e.g. `--config="$HOME/.config/coc/settings.json"`.

P.S. The name `coc-settings.json` is a bit awkward - IMO it should be called either `coc/settings.json` or `coc.json` ideally, the user could specify the config file name without losing config autocompletion.

**Comment by chemzqm** [comment]
No, you can create a link or use `g:coc_user_config` or `coc#config()` in viml.

**Comment by nostdm** [comment]
When using `coc#config()` I would have to define the JSON configuration inside a vimscript file, which doesn't have linting and syntax support as far as I know. I understand that `coc-settings.json` is used for workspace configuration but having a variable for global user config would not impact this `let g:coc_global_config="$HOME/.config/coc/coc-settings.json"`. Or at least do you mind explaining why you decided to put the file inside the `nvim` directory since that directory is generally used for vimscript configuration. Thanks.

**Comment by yatli** [comment]
@nostdm no it does not imply you have to place the content in vimL.
vimL is capable of file reading, so if you need the capability of dynamic/conditional config you can use vimL to branch `coc-settings.json` in different subfolders, which won't be picked up by default, and you'll still have all the nice linting and auto completion.

**Comment by coldspark29** [comment]
So where is this frigging file now? Can't find it

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file

**Comment by antonwnk** [comment]
@coldspark29 
Behold the glorious `:CocConfig` command.

**Comment by kaungmyathein12** [comment]
@antonwnk Thank you.
