### ISSUE TITLE
Error when trying to install COC Extension

### ISSUE THREAD

**Issue by filipekiss** [neoclide/coc.nvim#72]
**Describe the bug**
When I run `:CocInstall coc-json` I get the error `[coc.nvim] coc-json requires ^0.0.15, current version undefined`

**To Reproduce**
1. Open nvim
2. Type `:CocInstall coc-json`

**Expected behavior**
Actually install `coc-json`

**Desktop (please complete the following information):**
 - Terminal: iTerm2
 - COC Version: 36f43fc 
 - Node Version: 10.9

**Additional context**
Manually installing the extensions under `~/.config/coc/extensions` works but the error persists. Every time I open `:CocConfig` it tries to install again and gives me the error mentioned above. Not sure how to proceed :(

Update: Other extensions, like `coc-html` also give me the same error

**Comment by filipekiss** [comment]
Closing nvim and opening it again worked. Not sure what happened. Sorry for the trouble. :)

**Comment by chemzqm** [comment]
There was a bug of version compare in old version and fixed in new release.
