### ISSUE TITLE
Qt language server 

### ISSUE THREAD

**Issue by LinArcX** [neoclide/coc.nvim#721]
Hi. I'm curious to know is there any way to have qt lsp in coc.nvim?
Currently I'm using ccls for c/c++ projects and it's very nice. But for qt.. Is there at all any lsp for qt?

**Comment by chemzqm** [comment]
https://microsoft.github.io/language-server-protocol/implementors/servers/

**Comment by LinArcX** [comment]
Thank you. Let me more clarify my needs :
We know that we can use lsp implementations to get autocomplete in any editor that support lsp.
But how to get autocomplete for language frameworks?
For examples for Java jsf, or asp.net or qt/c++ or...?

**Comment by chemzqm** [comment]
@LinArcX Don't know, maybe use IDE.

**Comment by PouriDev** [comment]
Is there qt language server ? I really want it

**Comment by See-YouL** [comment]
I need qt language server too

**Comment by vimpostor** [comment]
FYI in Qt 6.4 there is now a QML language server. You can add it with the following snippet to your `:CocConfig`:

```json
{
	"languageserver": {
		"qml": {
			"command": "qmlls6",
			"filetypes": ["qml"]
		}
	}
}
```
