### ISSUE TITLE
Feature: Position floating window at bottom right.

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#722]
It would be great if there were a config option to position floating windows at the bottom right. Currently moving over a large error region obscures the code causing the error.
![Screenshot_20190423_180541](https://user-images.githubusercontent.com/29133776/56619177-b6826280-65f2-11e9-8e57-34bc475e4e25.png)

**Comment by chemzqm** [comment]
I've made it not show same diagnostics on cursor move, so the window would just hidden after cursor moved.
