### ISSUE TITLE
The vim-node-rpc, which should have been removed at Vim startup, is installed

### ISSUE THREAD

**Issue by kashewnuts** [neoclide/coc.nvim#725]
**Result from CocInfo**

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 13 2019
02:53:08)
node version: v8.10.0
coc.nvim version: 0.0.65-f7874ec7d7
term: dumb
platform: linux

## Error messages

## Output channel: snippets
```

**Describe the bug**

The vim-node-rpc, which should have been removed at Vim startup, is installed

**To Reproduce**

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

* Change to the directory where yarn.lock is located (`~/.config/yarn/global`)
* `yarn remove vim-node-rpc`
* Lanch `$ vim`
* Run `:!yarnpkg global add vim-node-rpc` as blow.

  ```sh
  vim
  :!yarnpkg global add vim-node-rpc
  yarn global v1.15.2
  warning package.json: No license field
  [1/4] Resolving packages...
  warning vim-node-rpc > log4js > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
  [2/4] Fetching packages...
  [3/4] Linking dependencies...
  [4/4] Building fresh packages...
  success Installed "vim-node-rpc@0.1.33" with binaries:
        - vim-node-rpc
  Done in 0.73s.
  ```

- Create a minimal mini.vim with：

  ```vim
  set nocompatible
  set runtimepath^=~/.cache/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  ```

None

**Screenshots**

![image](https://user-images.githubusercontent.com/1122795/56691610-52a78900-671b-11e9-91dc-e347b00087d8.png)

**Comment by chemzqm** [comment]
`* f7874ec - (tag: v0.0.65) Release v0.0.65 (2 weeks ago) <chemzqm>`

You're using tag release of coc.nvim, use command:
```
  Plug 'neoclide/coc.nvim', {'do': './install.sh nightly'}
```
to manage coc.nvim is recommended.

**Comment by kashewnuts** [comment]
Thanks for reply!

It was possible to move with the following procedure.

* Install nightly version of coc.nvim
* The node had v8.10.0 installed, but the following message appeared, so I updated to stable (v10.15.3)

  ```
  node >= 8.10.0 required, please upgrade nodejs, or use `let g:coc_node_path = "/path/to/node"` in your vimrc
  ```

The version of the required node may have changed, so it may be better to change the error message as well.
The ticket is closed because the problem was solved.

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 13 2019 02:53:08)
node version: v10.15.3
coc.nvim version: 0.0.65-3bdfdd2a86
term: dumb
platform: linux

## Error messages

## Output channel: snippets
```

**Comment by chemzqm** [comment]
Fixed node version check.
