### ISSUE TITLE
Support TexLab language server

### ISSUE THREAD

**Issue by krishnakumarg1984** [neoclide/coc.nvim#730]
The officially supported language server for LaTeX is [TexLab](https://texlab.netlify.com/) which also supports BibTeX.  I have had a positive experience using it in VSCode for which the same author provides a client plugin bearing the same name. 

Can you please support the `TexLab` language server and provide instructions in the wiki?

**Comment by chemzqm** [comment]
Should be simple: https://github.com/latex-lsp/texlab-vscode/blob/master/src/extension.ts#L27

Feel free to edit the wiki page https://github.com/neoclide/coc.nvim/wiki/Language-servers#example-configuration-for-custom-language-servers if anyone get it working.

**Comment by r-learner** [comment]
I tried registering a LSP for latex, the following mimium coc-settings.json worked.
```
{
	"languageserver": {
		"latex": {
			"command": "java",
			"args": ["-jar", "/FULL/PATH/texlab.jar"],
			"filetypes": ["tex", "bib"]
		}
	}
}
```
* make sure java is in $PATH or use the fully path of java.
* Adjust the texlab.jar path accordingly.
* Add `let g:tex_flavor = "latex"` to nvim config file `init.vim`, or adding "plaintex" and "context" to the above filetypes, `"filetypes": ["tex", "bib", "plaintex", "context"]`
* start editing latex files in a directory dedicated for your latex workspace. If you start edit latex file in your home directory, it will fail

**Comment by oblitum** [comment]
>     * Start editing latex files in a directory dedicated for your latex workspace. If you start edit latex file in your home directory, it will fail

Setting `ignoredRootPaths` can help blowing up on that issue with a sane error message: https://github.com/neoclide/coc.nvim/wiki/Language-servers#bash

**Comment by r-learner** [comment]
@oblitum, thanks. Good to know `"ignoredRootPaths": ["~"]`

**Comment by chemzqm** [comment]
Added to https://github.com/neoclide/coc.nvim/wiki/Language-servers#latex

**Comment by wbthomason** [comment]
@r-learner: With your setup, have you been able to invoke TexLab commands, e.g. to build files?

**Comment by krishnakumarg1984** [comment]
@wbthomason Texlab is being rewritten in Rust currently, and I suspect we will soon need updated instructions.

**Comment by wbthomason** [comment]
@krishnakumarg1984: I think this is actually a separate issue. With the (admittedly in-progress) Rust branch built, I can use the following to run the Rust version with coc.nvim:
```json
    "latex": {
      "command": "/PATH/TO/TEXLAB/REPO/target/release/texlab",
      "ignoredRootPaths": ["~"],
      "filetypes": ["tex", "bib", "plaintex", "context"]
    }
```
However, I think we still need a coc extension to be able to use TexLab fully - i.e. to issue `latex.build` commands, etc. I'm going to see if I can put together a single-file extension that does this, though I'm not really sure how to write a coc extension.

**Comment by r-learner** [comment]
@wbthomason, I am not a frequent Latex user, my workflow is using a seperate cmd terminal (or run command within vim).
one hack would be just define a vim function which could do latex build (I did not try latex.build in vscode to see what the latex.build does, it seems it is just a wrapper of latex worklfow).
To fully mimic the vscode texlab extension, the vs extension has to be forked and rewrite for coc.

**Comment by chemzqm** [comment]
Please open a new issue for request of TextLab extension.
