### ISSUE TITLE
Extension that strips trailing lines and whitespace

### ISSUE THREAD

**Issue by Melkster** [neoclide/coc.nvim#731]
I recently switched to coc.nvim and therefore stopped using [ALE](https://github.com/w0rp/ale), since coc.nvim does linting. Something that coc.nvim doesn't do though is stripping trailing lines and whitespace on save. It would be nice if coc.nvim had an extension that allows this.

**Comment by chemzqm** [comment]
Some language server or extension with format feature can provide format, the feature can be implemented by some simple vim script.

You don't need to stop use ALE, coc is not designed to be a featured lint engine as ale.
