### ISSUE TITLE
[Feature Request]Support qt language server?

### ISSUE THREAD

**Issue by LinArcX** [neoclide/coc.nvim#737]
Hi. recently qt teams create lsp for qt:
https://bugreports.qt.io/browse/QTCREATORBUG-20284

Some guys try it in sublime or vscode. i'm curious to know is there a way to use it through coc.nvim too?

**Comment by chemzqm** [comment]
If it can work with vscode, then you should be able to make it work by configure language server.

**Comment by LinArcX** [comment]
How? Any sample to use vscode extensions inside neovim?

**Comment by chemzqm** [comment]
I mean configure the command for language server.
I don't know how, you can looks at how it work with VSCode yourself.

**Comment by Jomik** [comment]
@LinArcX Seeing as you know my dotfiles and NUR repo, you can see here what I do for the rust language server https://github.com/Jomik/dotfiles/blob/master/.config/nixpkgs/configurations/neovim.nix#L17-L23
(I didn't like the vscode extension for rust)

**Comment by LinArcX** [comment]
@Jomik Hi. thank you for share your experience, but i want to develop qt applications (and need lsp work with it) not rust.

**Comment by Jomik** [comment]
@LinArcX  Is there a nix package for the qt language server?
You should be able to simply register it as in https://github.com/neoclide/coc.nvim/wiki/Language-servers#register-custom-language-servers

**Comment by chemzqm** [comment]
The language server is still WIP, you can try it by register custom language server.
