### ISSUE TITLE
Don't use npx in npm scripts

### ISSUE THREAD

**Issue by Jomik** [neoclide/coc.nvim#738]
i would prefer if you added `npm-run-all` to `devDependencies`, rather than using `npx` in an npm script.

This makes it quite a bit easier to resolve dependencies.

**Comment by chemzqm** [comment]
You have options:

1. Use `:call coc#util#install()` to avoid build javascript which is recommended.
2. Use `npm install -g npm-run-all` to avoid resolve for npm-run-all.
