### ISSUE TITLE
"Searching interpreter" blocks quitting neovim.

### ISSUE THREAD

**Issue by DanCardin** [neoclide/coc.nvim#742]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.4.0-dev
node version: v11.10.0
coc.nvim version: 0.0.65
term: screen-256color
platform: darwin

## Error messages

## Output channel: PythonStarting Jedi Python language engine.

Linter 'pylint' is not installed. Please install it or select another linter".
Error: Module 'pylint' not installed.
```

**Describe the bug**
Basically the title. Opening a file which uses a language server (i've only tested python), blocks a number of things (such as quitting).

**To Reproduce**
Open a python file, immediately try to quit.

**Comment by chemzqm** [comment]
Can't reproduce, need minimal vimrc.

**Comment by DanCardin** [comment]
:/ I can repro with the minimal suggested vimrc, though i **do** have to infer the waiting period for when (my status line would have started reporting (I assume) "Searching interpreter". With the minimal config if i **immediately** close, it's instant.

I can more reliably do this by opening a non-python file (presumably giving time for the plugin to load), then opening a new buffer to a python file and immediately quitting.

**Comment by chemzqm** [comment]
Then you have to profile your neovim to see where it get blocked, coc.nvim runs in separate process and use notification on most cases, so I don't know how could it block your neovim.
