### ISSUE TITLE
Issue when completing a change

### ISSUE THREAD

**Issue by vito-c** [neoclide/coc.nvim#744]
When I have some code 
`import some.class.from.packge.MyClassHasALongNameDTO`
and then let's say I want to change the name of the class so I `fMctD` which gives me
`import some.class.from.packge.|DTO` pretend that `|` is my cursor. Then I want to complete `MyNewClassDifferentNameDTO` so I start typing `MyNewClass` then use tab to select the result I want I get:
`import some.class.from.packge.MyNewClassDifferentNameDTODTO`

I should probably solve this by just doing `cW` but this was just a generic example. I was wondering what the expected behavior is here since I think another plugin acts differently.

Note: I'm not talking about a changing all the references or doing a refactor.

**Comment by chemzqm** [comment]
It looks like the server doesn't return correct textEdit, please checkout channel: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by olafurpg** [comment]
Feel free to open an issue in Metals, this is related to the textEdit returned by Metals, not a coc.nvim issue.

**Comment by olafurpg** [comment]
The textEdit from Metals intentionally does not include the suffix of the identifier except in the case when the completion item suffix is identical to the identifier suffix. This is unlikely to change, a workaround is to use `cW` instead if you intend to replace the entire identifier.

**Comment by chemzqm** [comment]
The language server should fix this, or use extension that use middleware to fix wrong textEdit.
