### ISSUE TITLE
Installation Instructions Wonky?

### ISSUE THREAD

**Issue by jherdman** [neoclide/coc.nvim#745]
**Result from CocInfo**

N/A

**Describe the bug**

I'm installing this plugin using Plug (current) on a Ubuntu machine for NVIM. My entry looks like this:

```
Plug 'neoclide/coc.nvim', {'tag': '*', 'do': './install.sh'}
```

Running `:PlugInstall` I see the following error:

```
- Finishing ... Done!
x coc.nvim:
    fatal: only one reference expected, 20 given.
```

**To Reproduce**

  ```vim
  call plug#begin('~/.vim/plugged')

  Plug 'neoclide/coc.nvim', {'tag': '*', 'do': './install.sh'}

  call plug#end()
  ```

**Comment by chemzqm** [comment]
There's something wrong with your git, remove the downloaded directory of coc.nvim and try again.

**Comment by jherdman** [comment]
I don't believe there's anything wrong, per se. I'm on Ubuntu 14 and thus pinned to Git 1.9.1. Are there more modern requirements for Git with this plugin?

**Comment by chemzqm** [comment]
Don't know, it's error of git, you can try `./install.sh` at the folder of coc.nvim.
