### ISSUE TITLE
[Question] Toggle formatting a file manually

### ISSUE THREAD

**Issue by Guzzii** [neoclide/coc.nvim#746]
Hi there. First, I just wanna say that I really enjoy the plugin. Please keep up the great work.

As for the question, I am aware format on save can be activated by using,  `"coc.preferences.formatOnSaveFiletypes": ["python"]`. I am wondering if there is a way to toggle format file manually?

**Comment by chemzqm** [comment]
If you don't want vim format your file on save, you just run `:noa w` to save current buffer.
