### ISSUE TITLE
[coc.nvim] yarn not found

### ISSUE THREAD

**Issue by kuer131** [neoclide/coc.nvim#75]
When I type 

> :CocInstall coc-html

get error 
> [coc.nvim] yarn not found, visit https://yarnpkg.com/en/docs/install for install
> ation. 

But I have already installed yarn

**Comment by chemzqm** [comment]
It's not in your $PATH, it's checked by `executable('yarn')`

**Comment by kuer131** [comment]
> It's not in your $PATH, it's checked by `executable('yarn')`
