### ISSUE TITLE
backslash escapes shown in coc-json doHover float

### ISSUE THREAD

**Issue by RedBeard0531** [neoclide/coc.nvim#752]
Not sure if this is an issue with coc or coc-json. Not even sure if it is just with `doHover` but that is where I noticed it.

![image](https://user-images.githubusercontent.com/118456/57170003-083ba180-6dd8-11e9-9268-250cf9ea4bbc.png)

**Comment by chemzqm** [comment]
Can't reproduce with minimal vimrc.

**Comment by Congee** [comment]
Actually see it a lot

**Comment by Dreomite** [comment]
@chemzqm In my case, [vim-polyglot](https://github.com/sheerun/vim-polyglot) was the problem.

NVIM v0.4.3
Minimal .vimrc:
```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'sheerun/vim-polyglot'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

" LSPs I have. Both are broken.
let g:coc_global_extensions = ['coc-json', 'coc-omnisharp']

nnoremap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```

**Comment by flw-cn** [comment]
@RedBeard0531 You can try `Plug “flw-cn/vim-markdown”` which is a fork for `plasticboy/vim-markdown` and it automatically hides the backslash. see PR plasticboy/vim-markdown#515 to see exactly what it does.
