### ISSUE TITLE
extra "\" added before "{" when using digestif as latex language server

### ISSUE THREAD

**Issue by alexfanqi** [neoclide/coc.nvim#753]
**result from CocInfo**

[Trace - 9:07:30 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 5190,
    "rootPath": "/media/alexfan/0006EF35000DE384/Downloads",
    "rootUri": "file:///media/alexfan/0006EF35000DE384/Downloads",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "declaration": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            }
        }
    },
    "initializationOptions": {},
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///media/alexfan/0006EF35000DE384/Downloads",
            "name": "Downloads"
        }
    ]
}

[Trace - 9:07:30 PM] Received response 'initialize - (0)' in 10ms.
Result: {
    "capabilities": {
        "completionProvider": {
            "triggerCharacters": [
                "\\",
                "{",
                "["
            ]
        },
        "textDocumentSync": {
            "change": 2,
            "openClose": true
        },
        "signatureHelpProvider": {
            "triggerCharacters": [
                "\\",
                "="
            ]
        },
        "hoverProvider": true
    }
}

[Trace - 9:07:30 PM] Sending notification 'initialized'.
Params: {}

[Trace - 9:07:30 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test.tex",
        "languageId": "tex",
        "version": 1,
        "text": "\n"
    }
}

Request:    0 initialize                                 0.60 ms
Request:    * initialized                                0.06 ms
Request:    * textDocument/didOpen                       0.08 ms
[Trace - 9:07:33 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 2,
        "uri": "file:///tmp/test.tex"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "rangeLength": 0,
            "text": "/"
        }
    ]
}

Request:    * textDocument/didChange                     0.14 ms
[Trace - 9:07:34 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 3,
        "uri": "file:///tmp/test.tex"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 1
                }
            },
            "rangeLength": 1,
            "text": "\\"
        }
    ]
}

Request:    * textDocument/didChange                     0.16 ms
[Trace - 9:07:34 PM] Sending request 'textDocument/completion - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test.tex"
    },
    "position": {
        "line": 0,
        "character": 1
    },
    "context": {
        "triggerKind": 2,
        "triggerCharacter": "\\"
    }
}

[Error  - 9:07:34 PM] Request textDocument/completion failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37705:40)
    at processMessageQueue (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37454:17)
    at Immediate.<anonymous> (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37435:13)
    at processImmediate (internal/timers.js:439:21)
Request:    1 textDocument/completion                    7.10 ms
[Trace - 9:07:35 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 4,
        "uri": "file:///tmp/test.tex"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 1
                }
            },
            "rangeLength": 0,
            "text": "d"
        }
    ]
}

Request:    * textDocument/didChange                     0.18 ms
[Trace - 9:07:35 PM] Sending request 'textDocument/completion - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test.tex"
    },
    "position": {
        "line": 0,
        "character": 2
    },
    "context": {
        "triggerKind": 1
    }
}

[Trace - 9:07:35 PM] Received response 'textDocument/completion - (2)' in 3ms.
Result: [
    {
        "insertTextFormat": 2,
        "documentation": "Today's day",
        "label": "day",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "day$0"
        }
    },
    {
        "insertTextFormat": 2,
        "label": "documentclass",
        "detail": "[options]{class}",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "documentclass[${1:options}]\\{${2:class}\\}$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "diamond suit symbol",
        "label": "diamondsuit",
        "detail": "♢",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "diamondsuit$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "Insert explicit hyphenation with control of hyphen character.",
        "label": "discretionary",
        "detail": "{pre-break-text}{post-break-text}{no-break-text}",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "discretionary\\{${1:pre-break-text}\\}\\{${2:post-break-text}\\}\\{${3:no-break-text}\\}$0"
        }
    },
    {
        "insertTextFormat": 2,
        "label": "date",
        "detail": "{text}",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "date\\{${1:text}\\}$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "dash, vertical",
        "label": "dashv",
        "detail": "⊣",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "dashv$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "small delta, greek",
        "label": "delta",
        "detail": "δ",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "delta$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "dieresis",
        "label": "ddot",
        "detail": "◌̈",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "ddot$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "Stretchable horizontal dots.",
        "label": "dotfill",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "dotfill$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "equals, single dot above",
        "label": "doteq",
        "detail": "≐",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "doteq$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "Draw a dashed box.",
        "label": "dashbox",
        "detail": "{dlen}(rwidth, rheight)[pos]{text}",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "dashbox\\{${1:dlen}\\}(${2:rwidth, rheight})[${3:pos}]\\{${4:text}\\}$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "three dots, descending",
        "label": "ddots",
        "detail": "⋱",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "ddots$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "dot above",
        "label": "dot",
        "detail": "◌̇",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "dot$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "downward arrow",
        "label": "downarrow",
        "detail": "↓",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "downarrow$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "divide sign",
        "label": "div",
        "detail": "÷",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "div$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "double dagger relation",
        "label": "ddagger",
        "detail": "‡",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "ddagger$0"
        }
    },
    {
        "insertTextFormat": 2,
        "documentation": "dagger relation",
        "label": "dagger",
        "detail": "†",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "dagger$0"
        }
    },
    {
        "insertTextFormat": 1,
        "filterText": "document",
        "label": "begin{document}",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "begin{document}"
        }
    },
    {
        "insertTextFormat": 1,
        "filterText": "description",
        "label": "begin{description}",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "begin{description}"
        }
    },
    {
        "insertTextFormat": 1,
        "filterText": "displaymath",
        "label": "begin{displaymath}",
        "textEdit": {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "newText": "begin{displaymath}"
        }
    }
]

Request:    2 textDocument/completion                    2.29 ms
[Trace - 9:07:37 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 5,
        "uri": "file:///tmp/test.tex"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 2
                }
            },
            "rangeLength": 1,
            "text": ""
        }
    ]
}

Request:    * textDocument/didChange                     0.16 ms
[Trace - 9:07:37 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 6,
        "uri": "file:///tmp/test.tex"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 1
                },
                "end": {
                    "line": 0,
                    "character": 1
                }
            },
            "rangeLength": 0,
            "text": "documentclass[options]\\{class}"
        }
    ]
}

Request:    * textDocument/didChange                     0.18 ms
[Trace - 9:07:38 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 7,
        "uri": "file:///tmp/test.tex"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 15
                },
                "end": {
                    "line": 0,
                    "character": 22
                }
            },
            "rangeLength": 7,
            "text": "a"
        }
    ]
}

Request:    * textDocument/didChange                     0.17 ms
[Trace - 9:07:38 PM] Sending request 'textDocument/completion - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test.tex"
    },
    "position": {
        "line": 0,
        "character": 16
    },
    "context": {
        "triggerKind": 1
    }
}

[Error  - 9:07:38 PM] Request textDocument/completion failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37705:40)
    at processMessageQueue (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37454:17)
    at Immediate.<anonymous> (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37435:13)
    at processImmediate (internal/timers.js:439:21)
Request:    3 textDocument/completion                    0.96 ms
[Trace - 9:07:38 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 9,
        "uri": "file:///tmp/test.tex"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 16
                },
                "end": {
                    "line": 0,
                    "character": 16
                }
            },
            "rangeLength": 0,
            "text": "l"
        }
    ]
}

Request:    * textDocument/didChange                     0.16 ms
[Trace - 9:07:38 PM] Sending request 'textDocument/completion - (4)'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test.tex"
    },
    "position": {
        "line": 0,
        "character": 17
    },
    "context": {
        "triggerKind": 1
    }
}

Request:    4 textDocument/completion                    1.58 ms
[Error  - 9:07:38 PM] Request textDocument/completion failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37705:40)
    at processMessageQueue (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37454:17)
    at Immediate.<anonymous> (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37435:13)
    at processImmediate (internal/timers.js:439:21)
[Trace - 9:07:38 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 11,
        "uri": "file:///tmp/test.tex"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 17
                },
                "end": {
                    "line": 0,
                    "character": 17
                }
            },
            "rangeLength": 0,
            "text": "e"
        }
    ]
}

Request:    * textDocument/didChange                     0.17 ms
[Trace - 9:07:38 PM] Sending request 'textDocument/completion - (5)'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test.tex"
    },
    "position": {
        "line": 0,
        "character": 18
    },
    "context": {
        "triggerKind": 1
    }
}

[Error  - 9:07:38 PM] Request textDocument/completion failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37705:40)
    at processMessageQueue (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37454:17)
    at Immediate.<anonymous> (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37435:13)
    at processImmediate (internal/timers.js:439:21)
Request:    5 textDocument/completion                    1.06 ms
[Trace - 9:07:39 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "version": 13,
        "uri": "file:///tmp/test.tex"
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 18
                },
                "end": {
                    "line": 0,
                    "character": 18
                }
            },
            "rangeLength": 0,
            "text": "x"
        }
    ]
}

Request:    * textDocument/didChange                     0.16 ms
[Trace - 9:07:39 PM] Sending request 'textDocument/completion - (6)'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/test.tex"
    },
    "position": {
        "line": 0,
        "character": 19
    },
    "context": {
        "triggerKind": 1
    }
}

[Error  - 9:07:39 PM] Request textDocument/completion failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37705:40)
    at processMessageQueue (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37454:17)
    at Immediate.<anonymous> (/home/alexfan/.vim/bundle/coc.nvim/build/index.js:37435:13)
    at processImmediate (internal/timers.js:439:21)
Request:    6 textDocument/completion                    1.62 ms

**Bug description and reproduction**

When typing \begin and hit the first prompt "\begin~  {environment}, I get "\\begin \\{environment}", an extra \ is added before '{env'. 
My config:
"digestif": {
command : digestif ,
args : [],
filetypes : [
tex ,
plaintex ,
bibtex
],
}

**Comment by chemzqm** [comment]
Please provide verbose output from language server: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by alexfanqi** [comment]
verbose output provided. This issue has been solved by digestif's author.
