### ISSUE TITLE
Some way to register to receive notifications from the LSP server

### ISSUE THREAD

**Issue by RedBeard0531** [neoclide/coc.nvim#759]
**Is your feature request related to a problem? Please describe.**
https://github.com/jackguo380/vim-lsp-cxx-highlight doesn't currently support coc.nvim. It [documents](https://github.com/jackguo380/vim-lsp-cxx-highlight/blob/14b91204f4cce0f68516efbd91fc93288d526543/doc/vim-lsp-cxx-highlight.txt#L271-L314) how to add support for a new LSP client, but it requires a way to receive notifications, and I don't see anything like that in coc.nvim.

**Describe the solution you'd like**
Some way to register to receive notifications. Ideally it would be similar to one of the other vim LSP plugins to avoid the matrix problem.

* vim-lsp version just offers a way to get all notifications like [this](https://github.com/jackguo380/vim-lsp-cxx-highlight/blob/14b91204f4cce0f68516efbd91fc93288d526543/autoload/lsp_cxx_hl/client/vim_lsp.vim#L3-L6)
* LanguageClient offers a way to register callbacks for specific notifications like [this](https://github.com/jackguo380/vim-lsp-cxx-highlight/blob/14b91204f4cce0f68516efbd91fc93288d526543/autoload/lsp_cxx_hl/client/LanguageClient.vim#L3-L14)

**Describe alternatives you've considered**
I considered filing a request with vim-lsp-cxx-highlight, but since it seems like it needs a new (or maybe just undocumented?) feature from coc.nvim, it seemed best to file here.

**Comment by jackguo380** [comment]
Hi @RedBeard0531 @chemzqm 

Thanks for filing and implementing this, coc.nvim was on my list of things to potentially support but I never figured out how, this change makes it easy now. I just pushed support for coc.nvim
jackguo380/vim-lsp-cxx-highlight@24b5d0e.
