### ISSUE TITLE
Disable coc on specific buffer type?

### ISSUE THREAD

**Issue by ahmedelgabri** [neoclide/coc.nvim#76]
I have `fzf` set to show a file preview inside vim when I search for files & coc actually tries to run on those previews it seems. This makes fzf very slow to preview files.

So how can I disable coc on a specific buffer type? I couldn't find any option for this

**Comment by chemzqm** [comment]
It's intended to watch the terminal buffer for changes, but I don't know why that would slow vim since it's async, will look into anyway.

**Comment by deathmaz** [comment]
not sure if this is related but in my case i see also this when i call fzf from `.vue` file
![image](https://user-images.githubusercontent.com/6440135/45551360-521a4c00-b836-11e8-8a49-1aff4ca78f05.png)

Full text of error:
```
Vetur initialized
[3  - 3:51:17 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'template' of undefined
[3  - 3:51:17 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property 'template' of undefined
```
But this happens only when i open the file for the first time in neovim and call FZF, next time i call FZF i don't see this error

**Comment by chemzqm** [comment]
@deathmaz some language server doesn't work with untitled buffers, it's possible for coc-veture to fiter with files.

**Comment by ahmedelgabri** [comment]
> It's intended to watch the terminal buffer for changes, but I don't know why that would slow vim since it's async, will look into anyway.

I'm not sure if `fzf` is actually spinning up a terminal for this 

![fzf](https://user-images.githubusercontent.com/63876/45553784-15018a00-b835-11e8-8a64-bfb6f5e1de8c.gif)

**Comment by chemzqm** [comment]
My fzf is too old, it doesn't support preview file, I'm upgrading it.

**Comment by ahmedelgabri** [comment]
Here are my settings too:

[`$FZF_CTRL_T_OPTS`](https://github.com/ahmedelgabri/dotfiles/blob/cec4c15b09963082d8047007f18d227d829e8bfe/zsh/.zshrc#L131) which is used in my [`fzf.vim`](https://github.com/ahmedelgabri/dotfiles/blob/cec4c15b09963082d8047007f18d227d829e8bfe/vim/.vim/after/plugin/fzf.vim#L2)

**Comment by chemzqm** [comment]
@ahmedelgabri get error with command
```
fzf --preview "(highlight -O ansi -l {} || cat {} || tree -C {}) 2> /dev/null | head -200" --bind "?:toggle-preview"
```
<img width="586" alt="screen shot 2018-09-14 at 10 33 07 pm" src="https://user-images.githubusercontent.com/251450/45556606-3fbc0480-b86e-11e8-9b45-d1ce1360ef52.png">
I have highlight installed with brew.

**Comment by chemzqm** [comment]
Are your sure the slow is caused by coc?
I tried with `fzf --preview 'highlight -O ansi -l {}| head -500'` in my terminal buffer and it doesn't slow at all.
<img width="1109" alt="screen shot 2018-09-14 at 10 43 01 pm" src="https://user-images.githubusercontent.com/251450/45557333-f10f6a00-b86f-11e8-8868-78e0f38c130f.png">

**Comment by ahmedelgabri** [comment]
Ok, you are right. It's a different plugin, sorry for that.

**Comment by chemzqm** [comment]
@deathmaz there's a bug on configuration update, it's fixed in latest release.

**Comment by deathmaz** [comment]
Thank you, it works fine now
