### ISSUE TITLE
Adding new source using CocInstall

### ISSUE THREAD

**Issue by Nelyah** [neoclide/coc.nvim#760]
So, I've been trying for some time to get my completion working for my notmuch addresses, coming from deoplete. However, this wasn't as straight forward as I hoped (probably because I basically never coded nodeJS before).

I have looked at [simpler examples](https://github.com/neoclide/coc-sources/tree/master/packages/word) and tried to get inspired from that. However, I do not manage to get any completion from my source (whereas it works well using others).

I install my source using `:CocInstall https://github.com/Nelyah/coc-notmuch.git`, and I can see the list enabled with `:CocList extensions`. The output from the command `notmuch address "*"` gives me a list of my contacts in the form `{name} {email}`, with one contact per line.

I pasted the code I use below. Is there any obvious thing I'm missing which would explain why this doesn't work? Also, if I uncomment the commented lines, I get the following error. How do I go from there to set this completion type only to mail filetypes and with the given TriggerPattern?

`[coc.nvim] Error on active extension coc-notmuch: TypeError: Cannot set property enable of #<Source> which has only a getter`

Thanks!

    const child_process = require('child_process')
    const { sources } = require('coc.nvim')

    exports.activate = async context => {
      let matches = []

      context.subscriptions.push(
        sources.createSource({
          name: 'notmuch',
          // triggerCharacters: [],
          // enable: true,
          // filetypes: ['mail'],
          // priority: 99,
          // triggerPatterns: [
          //   /^(Bcc|Cc|From|Reply-To|To):\s*/,
          //   /^(Bcc|Cc|From|Reply-To|To):.*,\s*/,
          // ],
          doComplete: async function(opt) {
            if (!opt.input) return null
            const matches = await query()
            return {
              items: matches.map(m => {
                return {
                  word: m,
                }
              }),
            }
          },
        })
      )
    }

    function query() {
      return new Promise(resolve => {
        ret = exec('notmuch address "*"', (error, stdout, stderr) => {
          if (error) {
            console.error(`exec error: ${error}`)
            return
          }
          ret = stdout
          let notmuch_stdout = stdout
            .toString()
            .split('\n')
            .forEach(m => {
              const entry = m.toString()
              matches.push(entry)
            })
          resolve(matches)
        })
      })
    }

**Comment by chemzqm** [comment]
You can use those properties: `'priority' | 'sourceType' | 'triggerPatterns' | 'enable' | 'filetypes' | 'disableSyntaxes' | 'firstMatch'` with API `sources.createSource` since those properties should comes from configuration in package.json, you will get compile error if you use typescript.

You can use API `sources.addSource` for configure those properties with code, checkout https://github.com/zidhuss/coc-lbdbq for example.

**Comment by chemzqm** [comment]
I have improved API `sources.addSource`, it now allows any properties of `ISource`.

**Comment by teto** [comment]
@Nelyah it's not possible to open issues on your tracker but let me say this: Thank you !!
This is the first plugin I have working out of the box for email completion and that is on par with gmail & co. completion.
