### ISSUE TITLE
VSCode Remote Development Extension Pack support

### ISSUE THREAD

**Issue by kwkelly** [neoclide/coc.nvim#761]
Microsoft has released a preview of its [remote development extension pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) for VSCode aimed at allowing VSCode to utilize a development environment remotely or within a docker container. Is it possible (or reasonable) to support this extension? As far as I can tell, there's currently no support for accessing a remote language server.

**Comment by chemzqm** [comment]
It's out of scope, vim can handle file opened with ssh schema.
And you can install vim extensions on remote server then use vim through ssh, which could be much better, since most language server will not work with file opened with ssh prototol.
