### ISSUE TITLE
Support custom coc-settings.json file path in .vimrc?

### ISSUE THREAD

**Issue by StarryLeo** [neoclide/coc.nvim#762]
**Is your feature request related to a problem? Please describe.**

My vim configuration file is placed in a separate directory (not in the `.vim` directory, maybe many people do the same). `coc-settings.json` is very inconvenient to manage in the `.vim` directory. If can customize it in the `.vimrc` file, it's best, just like [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) has an option:

[g:LanguageClient_settingsPath](https://github.com/autozimu/LanguageClient-neovim/blob/6ee4c8994ee84609f8370aa4766b66c7cbad1424/doc/LanguageClient.txt#L203)

**Describe the solution you'd like**

Add an option to customize `coc-settings.json` path, like:
`g:coc_settings_path`

**Describe alternatives you've considered**

I don't understand js

**Additional context**

**Comment by chemzqm** [comment]
Will not support since it's used in different places, but you have options.

* Use link for the file or the folder of file.
* Add coc settings by use `g:coc_user_config`

**Comment by jerry901** [comment]
now supports ```let g:coc_confing_home = '~/path/to/coc-settings.json```
