### ISSUE TITLE
coc-references only works for open buffers

### ISSUE THREAD

**Issue by CharlesConner** [neoclide/coc.nvim#772]
## Result from CocInfo

vim version: NVIM v0.4.0-dev
node version: v10.15.0
coc.nvim version: 0.0.67-61f14d6fd3
term: iTerm.app
platform: darwin

## Describe the bug
When running `coc-references` it only finds references in open buffers. For `coc-definition` and `coc-implementation` it works as expected and searches the entire project and not just my open buffers.

**Comment by chemzqm** [comment]
Can't reproduce

**Comment by CharlesConner** [comment]
Does it search the entire project for you? I tried making a new vimrc just bringing in the coc.nvim plugin but I still cant get it to work

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by peterdolan** [comment]
@CharlesConner did you ever resolve this? I'm running into the same issue

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
