### ISSUE TITLE
Allow hiding completion provider short name in menu

### ISSUE THREAD

**Issue by rliebz** [neoclide/coc.nvim#773]
**Is your feature request related to a problem? Please describe.**
While it is possible to disable the menu field altogether with `suggest.disableMenu`, it is not possible to set `suggest.detailField` to `menu` without also seeing the short-name of the completion source. 

For example, rather than:

```
Foo    string [LS]
Bar    int [LS]
```

I would like to be able to see:
```
Foo   string
Bar   int
```

**Describe the solution you'd like**
A config option to disable the short name from the completion menu. Something like `suggest.hideShortname` or `suggest.disableMenuShortname`, etc.

**Describe alternatives you've considered**
A more robust solution might be to allow formatting strings to let users define the structure of the menu item. That way, a string like `[{{short}}] {{detail}}` could produce a menu like this:
```
Foo  [LS] string
Bar  [LS] int
```

That said, if there aren't more than a couple things that would ever end up in the menu, having a setting like that could be overkill. I personally wouldn't need that level of control.

**Additional context**
I believe this is the relevant section of code:
https://github.com/neoclide/coc.nvim/blob/c65044198f40517d3d3150a9e4409ff4dfa7bea4/src/languages.ts#L705-L725

**Comment by chemzqm** [comment]
There is `suggest.disableMenu` setting

**Comment by rliebz** [comment]
From what I can tell, `suggest.disableMenu` can't work with `suggest.detailField` set to `"menu"`. 

I'm specifically looking to be able to have the menu display only the detail without the short name.

**Comment by chemzqm** [comment]
Nu such support, you have to change the code.
