### ISSUE TITLE
Error after installation: "Unknown function: CocActionAsync"

### ISSUE THREAD

**Issue by andreatulimiero** [neoclide/coc.nvim#775]
### What I did
I installed the plugin with vim `Plug` building from source, thus using
```
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
```
and the installation completed succesfully, and then I added the example [configuration](https://github.com/neoclide/coc.nvim#example-vim-configuration).

### Issue
When I re-open VIM, I get  "Unknown function: CocActionAsync".
Furthermore, commands such as `:CocConfig` don't seem to exist.

Is it a problem with the installation? 

### VIM version
I'm using VIM 8.0 (the `vim-gtk3` package for Ubuntu 18.10)

Cheers

**Comment by chemzqm** [comment]
Try remove this line https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L5.
Some feature may not work as expected.

**Comment by andreatulimiero** [comment]
Looks like is working like a charm

Thanks for your quick reply :+1:

**Comment by EstebanMarin** [comment]
@chemzqm where do I make the change to remove the line in the file?

**Comment by Char-Aznable** [comment]
I have the same problem here. I tried removing that line @chemzqm suggests in my coc.vim but it didn't work

**Comment by chemzqm** [comment]
Check your vim version

**Comment by Char-Aznable** [comment]
I am using vim 8.1.1800. I also tried both the apt install version and build from source. All have the same issue

**Comment by vpeopleonatank** [comment]
Same issue on ubuntu 18.04 with neovim 0.4

**Comment by andrewmpalka** [comment]
I am also having this same issue with vim 8.1.1909 and osx 10.14.06

**Comment by chemzqm** [comment]
Try minimal vimrc, you might have g:did_coc_loaded to be 1 before coc.nvim get loaded

**Comment by sudogroot** [comment]
Same problem could not be solve 
ubuntu 18.04 with neovim 0.3.8

**Comment by thepauljones** [comment]
@sudogroot Also having trouble getting coc to work on ubuntu with vim

**Comment by sudogroot** [comment]
now with nvim 0.4.3 i am having those errors :
E117: Unknown function: coc#status
E117: Unknown function: CocActionAsync

**Comment by chemzqm** [comment]
@sudogroot you don't have coc.nvim configured as vim plugin, checkout `:echo &rtp`

**Comment by diogoneiss** [comment]
@chemzqm same problem here, tried everything I could find on google and on this issue. Here is my init.vim, the problem appears to be on https://github.com/diogoneiss/Vim/blob/master/nvim/init.vim#L167 . My coc seems to not work at all, and i shows on :echo &rtp

**Comment by chemzqm** [comment]
Could be your vim version is too low.

**Comment by diogoneiss** [comment]
> Could be your vim version is too low.

I don't think so, I downloaded nvim yesterday from their repo. Could be this?

**Comment by chemzqm** [comment]
The plugin doesn't load at all, try debug the file https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim

**Comment by asishallab** [comment]
Hello everyone!

I am having the same problem using neovim (v0.2.2) on Ubuntu (18.04).

```
E117: Unknown function: coc#status
Error detected while processing CursorHold Auto commands for "*":
E117: Unknown function: CocActionAsync
```

I used the minimal `.vimrc` as suggested in your GitHub repo's README.

Please help. I'd really like to use coc.

**Comment by chemzqm** [comment]
neovim (v0.2.2) is not supported, read readme

**Comment by asishallab** [comment]
Dear @chemzqm , thank you for your reply.

> neovim (v0.2.2) is not supported, read readme

I downloaded the latest [`nvim.appimage`](https://github.com/neovim/neovim/releases/tag/nightly) and ran it using the minimal `.vimrc` (`init.vim`) as suggested in the [coc's README](https://github.com/neoclide/coc.nvim).

So, now I have `nvim` (v0.5.0-245-g1bfccf028) on Ubuntu 18.04, but
unfortunately, I still get the error:
```
E117: Unknown function: coc#status
Error detected while processing CursorHold Autocommands for "*":
E117: Unknown function: CocActionAsync
```

Is neovim not supported?

Thank you for your help.

**Comment by fannheyward** [comment]
@asishallab How did you install coc.nvim? By vim-plug or anything else?

**Comment by asishallab** [comment]
Dear @fannheyward,

thank you for your help and message. I installed coc.vim using vim-plug as explained in the guide, you provided.

I attach my `init.vim` (as txt-file) and the result of `:checkhealth` to this message, maybe they help to resolve the confusion?

Thank you and kind regards.

Attachments:
* [nvim_checkhealth.txt](https://github.com/neoclide/coc.nvim/files/3982608/nvim_checkhealth.txt)
* [init_vim.txt](https://github.com/neoclide/coc.nvim/files/3982617/init_vim.txt)

**Comment by asishallab** [comment]
Dear @fannheyward and @chemzqm,

I got coc.vim working. Thank you very much for your help.

**Comment by unknownbreaker** [comment]
Not sure if this helps anyone else, but if you're using NeoVim and getting this error, don't forget to run `:PlugInstall` after opening NeoVim. Then reload NeoVim.

**Comment by lotusroot13** [comment]
Not sure if it would help anyone, but I fixed this exact error just by moving coc config to the top of init.vim config file

**Comment by asonedoes** [comment]
I finally managed to fix this by manually sourcing the coc.vim file in my vimrc, i.e. by adding
`source ~/.vim/plugged/coc.nvim/plugin/coc.vim
`

**Comment by juanbrein** [comment]
Make sure you plug begin and plug end:

```
  call plug#begin('~/.vim/plugged')
  
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  
  " Initialize plugin system
  call plug#end()

```

**Comment by asonedoes** [comment]
Embarassingly, I now know why the coc.vim file wasn't being sourced. It was because I was putting all the vim Plug logic in my .gvimrc, and not my .vimrc. Know that I've read what .gvimrc actually does (it gets sourced after .vimrc, not independently!) everything works as expected.

**Comment by foreverLoveWisdom** [comment]
I got this problem when accidentally put `Plug kien/ctrlp.vim` and ` Plug 'neoclide/coc.nvim', {'branch': 'release'}` on the same line. Make sure you don't run into the same mistake.

**Comment by aderchox** [comment]
I have the same problem. Different errors are displayed. I have this line in my ~/.vimrc:
```
Plug 'neoclide/coc.nvim', {'branch': 'release'}
```

**Comment by DZ84** [comment]
In normal Vim 8.2 can also happen if Coc is installed in the wrong folder under Vim Pack (e.g. `.vim/pack/coc-nvim' instead of `vim/pack/mypackages/start/coc-nvim`).

Thus meaning not installed at all, but some configuration already present in .vimrc.

**Comment by hdiogenes** [comment]
I had the same issue and @juanbrein's solution is what solved for me:

> Make sure you plug begin and plug end:
> 
> ```
>   call plug#begin('~/.vim/plugged')
>   
>   Plug 'neoclide/coc.nvim', {'branch': 'release'}
>   
>   " Initialize plugin system
>   call plug#end()
> ```

**Comment by SpiesInOrbit** [comment]
I too had this issue. I install and manage node with [nvm](https://nbanzyme.medium.com/easy-way-to-install-nvm-on-ubuntu-18-04-2cfb19ee5391) on Ubuntu 18.04. I'm running [vim 8.2.x](https://itsfoss.com/vim-8-release-install/) with [vim-plug](https://github.com/junegunn/vim-plug) Upon initial attempt, following the [coc.nvim](https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim) install instructions (including running :PlugInstall) I got the "Unknown function: CocActionAsync" error. I also have the latest version of node installed through nvm as well as yarn installed globally. After some tests and commenting out various lines of config to test where the failure was,  an `:echo &rtp` revealed coc.vim was not installed. I then ran :PlugInstall again with no luck. I tried the other Plug config to install from source, still no dice. I then moved the "Plug 'neoclide/coc.nvim', {'branch': 'release'}" to the top of my Plug install section and reran :PlugInstall. This time it worked and all is right with the world. Not sure what position had to do with it, or why being at the bottom caused it not to be installed resulting in this error.

**Comment by forChin** [comment]
I also had this error, but I updated nodejs to latest version and all is fine.

**Comment by sergeylukin** [comment]
Giving :PlugInstall some more time and closing only when `Finishing...Done!` appeared fixed it for me.

**Comment by Abbyyan** [comment]
Solved by updating vim

**Comment by AntoninSonka** [comment]
> Try remove this line https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L5. Some feature may not work as expected.

Do you know the solution when using lua?

**Comment by eagle-ice** [comment]
Experiencing the same issue:
Error detected while processing CursorHold Autocommands for “*"：
E117： Unknown function: CocActionAsync
Workaround:
```
cd ~/.vim/plugged/coc.nvim
git reset --hard HEAD
```
problem solving

**Comment by michaelteter** [comment]
This is embarrassing, but I'll add it in case others have the same root cause as I did.

I forgot to :PlugInstall

After doing that, it installed the coc plugin.  The unknown function was miraculously now known :).
