### ISSUE TITLE
When I run :CocInstall in normal mode, it exits in insert mode

### ISSUE THREAD

**Issue by snoblenet** [neoclide/coc.nvim#777]
I see nothing when I run `:CocInfo`.

## Describe the bug

When I run `:CocInstall` in normal mode, it exits in insert mode.

## Reproduce the bug

1. Be in normal mode. 
2. Run `:CocInstall`. For example, `:CocInstall coc-json`.
3. Wait for the install to complete.
4. Notice that you are now in insert mode.

When I created and started with a `mini.vim`, I did not experience this problem.

**Comment by chemzqm** [comment]
Looks like some of your plugin change vim to insert mode after enter of terminal.

**Comment by snoblenet** [comment]
Would this do the trick? 

`autocmd TermOpen * :startinsert`

Happy to ditch it as I generally use Tmux not the Neovim terminal.

**Comment by chemzqm** [comment]
That's the reason.
