### ISSUE TITLE
Feature request - Add the possibility to configure the trigger key for sources

### ISSUE THREAD

**Issue by CharlesConner** [neoclide/coc.nvim#778]
Hi,

I think adding the possibility to change the trigger key for sources would be awesome. I love using the emoji source for logging and writing comments but the : character is used so often in other contexts that it becomes a little annoying.

**Comment by chemzqm** [comment]
Fixed for emoji source.

**Comment by CharlesConner** [comment]
That was quick! I made a pull request to the coc-sources repo updating the readme
