### ISSUE TITLE
conflict with coc.nvim and indentLine

### ISSUE THREAD

**Issue by dementor5** [neoclide/coc.nvim#781]
MyConfig: https://github.com/dementor5/myConf

Problem with indentLine plugin.
When i switch on 
let g:indentLine_leadingSpaceEnabled = 1
underlinings to a line with an error are not displayed and also friezes are added
before switching:
![underlines](https://user-images.githubusercontent.com/22612354/57940628-8bc7b900-78d5-11e9-8a10-222af52d44b4.png)

after:
![underlines2](https://user-images.githubusercontent.com/22612354/57940631-8c604f80-78d5-11e9-9cf7-47cab3be5fcf.png)

**Comment by chemzqm** [comment]
The error is expected.

**Comment by dementor5** [comment]
Ok. How can i fix it?

**Comment by chemzqm** [comment]
Wrong comment, I don't have issue with `let g:indentLine_leadingSpaceEnabled = 1` enabled or not.
Please provide minimal vimrc to reproduce.

You can profile vim to figure out what happended, https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-could-i-profile-vim

**Comment by dementor5** [comment]
Minimal config is:
```
coc-settings.json:
{
  "diagnostic.signOffset": 9999999,
  "eslint.filetypes": ["javascript", "javascriptreact", "typescript", "vue"],
}
```

.vimrc
```
call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
  Plug 'Yggdroot/indentLine'
  Plug 'sheerun/vim-polyglot'
cal plug#end()
let g:coc_global_extensions = ['coc-eslint']
let g:indentLine_leadingSpaceEnabled = 1

```

code for testing Header.vue;
```
<template>
  <header>
      <div class="navbar navbar-default">
        <div class="navbar-header">
          <h1><router-link :to="{name: 'iMain'}">{{ siteName }}</router-link></h1>
        </div>
        <div class="nav navbar-nav navbar-right cart">
          <button class="btn btn-default btn-lg" type="button" @click="chowCheckout">
            <span class="glyphicon glyphicon-shopping-cart">{{ cartItemCount }}</span> Checkout
          </button>
        </div>
      </div>
    </header>
</template>

<script>
export default {
  name: `my-header`,
  data() {
    return {
      siteName: `Test Name`,
      };
    },
    props: [`cartItemCount`],
    methods: {
      showCheckout() {
        this.$router.push({name: `Form`});
      },
    }
};
</script>
```

**Comment by chemzqm** [comment]
The problem is the highlight of error is overwrite by indentLine plugin, you can use 
` "diagnostic.checkCurrentLine": ture` in settings file to make coc check current line.

**Comment by dementor5** [comment]
`"diagnostic.checkCurrentLine": true`
This line doesn't solve my problem. :(
Is there any other way to solve it?
Maybe there is any hack like this: 
"diagnostic.signOfset": 9999999` from #688?

**Comment by dementor5** [comment]
Is there any news about this problem?
