### ISSUE TITLE
ERROR: ENOENT: no such file or directory, unlink '/tmp/coc-nvim.log'

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#785]
![2019-05-18-165538_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/57971407-e7557d80-798d-11e9-860e-03590058c9b4.png)

**Comment by pavilesjose** [comment]
Got the same issue. Commit  https://github.com/neoclide/coc.nvim/commit/dfc8dc22777e4109ce2f4830c1088aad40caa392 doesn't fix it for me at least.

**Comment by masaeedu** [comment]
Is there already a different issue tracking the failure to build after plugin update?

I have:

```js
  Plug 'neoclide/coc.nvim', { 'do': './install.sh nightly' }
```

and apparently it didn't build for me either.
