### ISSUE TITLE
<C-o> not staying in normal mode

### ISSUE THREAD

**Issue by SicariusNoctis** [neoclide/coc.nvim#786]
## Describe the bug

Pressing `<C-o>` in insert mode switches to normal mode for approximately the length of `&updatetime`, then automatically switches back to insert mode.

For instance, if `&updatetime=10`, typing:

```vim
iDEF<C-o>bABC<Esc>
```

Produces:

```
DEFbABC
```

Instead of:

```
ABCDEF
```

## Reproduce the bug

Minimal `.vimrc`:

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'neoclide/'        . 'coc.nvim', {
    \ 'tag': '*',
    \ 'do': { -> coc#util#install()}
    \ }
call plug#end()

set updatetime=10
```

(I suggest setting `&updatetime` to `1000` so it's more clear what's going on.)

**Comment by chemzqm** [comment]
You can decide, coc doesn't set it for you.

**Comment by SicariusNoctis** [comment]
I'm not sure I understand. Neovim behaves correctly regardless of `updatetime` if `coc.nvim` is entirely disabled.

**Comment by chemzqm** [comment]
@SicariusNoctis I can't see any difference with coc.nvim enabled or not, please describe the problem more precisely.

**Comment by SicariusNoctis** [comment]
I think these things are best shown in video. :P

https://asciinema.org/a/KJOIuZ7YngPn1oqM7DD3cAMpY

**Comment by chemzqm** [comment]
It's problem of vim/neovim. It work like this when your have CursorHold autocmd.
So instead of `set updatetime=10`, use `set updatetime=300` could be better.

**Comment by SicariusNoctis** [comment]
Ah, I see, thanks. Looks like someone just opened an issue about this: https://github.com/neovim/neovim/issues/10035

**Comment by bfredl** [comment]
Fixed on latest neovim master.
