### ISSUE TITLE
set custom ALE or Statusline highlight groups breaks floating window highlighting

### ISSUE THREAD

**Issue by ahmedelgabri** [neoclide/coc.nvim#788]
## Result from CocInfo

```

## versions

vim version: NVIM v0.4.0-1809-gda3c0e496
node version: v12.1.0
coc.nvim version: 0.0.67-8741e930c9
term: tmux-256color
platform: darwin

## Error messages

```

## Describe the bug

I have a custom `autocmd` to set `ALEInfoLine`, `ALEWarningLine` & `ALEErrorLine`

```vim
  autocmd ColorScheme * execute "hi! ALEInfoLine guifg=".(&background=='light'?'#808000':'#ffff00')." guibg=".(&background=='light'?'#ffff00':'#555500')
        \| execute "hi! ALEWarningLine guifg=".(&background=='light'?'#808000':'#ffff00')." guibg=".(&background=='light'?'#ffff00':'#555500')
        \| execute "hi! ALEErrorLine guifg=".(&background=='light'?'#ff0000':'#ff0000')." guibg=".(&background=='light'?'#ffcccc':'#550000')
```

When I do this the highlighting inside the floating window gets messed up

<img width="426" alt="Screen Shot 2019-05-19 at 19 32 57" src="https://user-images.githubusercontent.com/63876/57985798-b9476a80-7a6d-11e9-892c-a3387c3245e2.png">

Removing the above `autocmd` fixes the issue _partially_ but then I get two different colors sometimes. Which seems to be affected by my custom StatusLine setup…

<img width="440" alt="Screen Shot 2019-05-19 at 19 34 07" src="https://user-images.githubusercontent.com/63876/57985807-c8c6b380-7a6d-11e9-86f2-94e66f109747.png">
<img width="445" alt="Screen Shot 2019-05-19 at 19 34 33" src="https://user-images.githubusercontent.com/63876/57985808-c8c6b380-7a6d-11e9-8a85-5537916b3c00.png">

I tried multiple colorschemes too _including gruvbox_ & all of them have the same issues.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=~/.vim/pack/minpac/start/coc.nvim
filetype plugin indent on
syntax on
set hidden
set termguicolors
```

**Comment by chemzqm** [comment]
Can't reproduce, the neovim used for highlight doesn't use your vimrc so I don't know how could this affect your highlight.

**Comment by ahmedelgabri** [comment]
I can't really figure out what is wrong, and `nvim -u mini.vim` will still load all my config from `~/.vim/pack`, `~/.vim/plugins`, etc…

I tried removing some folders from my config to see if this will fix the issue, I noticed that if I delete [`synatx` folder](https://github.com/ahmedelgabri/dotfiles/tree/master/files/.vim/after/syntax) it works, but even if I have an empty `syntax` folder it breaks...

Not sure where to start to debug this properly now.

**Comment by chemzqm** [comment]
Then you should guard your code with check of ale existence.

**Comment by ahmedelgabri** [comment]
> Then you should guard your code with check of ale existence. Or use vimrc instead.

I do guard my code for ale existence & using `.vim` startup directory structure is fine too, no need for putting everything inside `.vimrc`
