### ISSUE TITLE
edit jsx fie doesn't trigger ttserver

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#79]
**Describe the bug**
- `nvim test.jsx` doesn't trigger ttserver and filetype is `javascript.jsx` set by vim-jsx plugin
- `e test.jsx` will trigger ttserver

**To Reproduce**
1. `nvim test.jsx`

**Expected behavior**

the ttserver start when `nvim test.jsx`

**Desktop (please complete the following information):**
 - Terminal: [e.g. iTerm2]
 - Version: [e.g. v3.1.0]

**Comment by chemzqm** [comment]
The `activationEvents` of `coc-tsserver` is copied from VSCode, so it's not respect `javascript.jsx`, fixed in latest `coc-tsserver`
