### ISSUE TITLE
Change language server backend for dart

### ISSUE THREAD

**Issue by ram535** [neoclide/coc.nvim#790]
I saw a [request in the repository of lsp-mode](https://github.com/emacs-lsp/lsp-mode/pull/841) for emacs where they suggest to change the from **dart_language_server** to **analysis_server**.

Since **analysis_server** is the official language server from Dart sdk.
https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md

**Comment by iamcco** [comment]
coc have no dart extension now, so it's no need to change anything. If you want to use the analysis_server all you have to do is change the languageserver config in coc-settings.json to use it.
