### ISSUE TITLE
Floating windows closes instantly

### ISSUE THREAD

**Issue by pLesur** [neoclide/coc.nvim#793]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.0-460-g2470c8829
node version: v10.15.3
coc.nvim version: 0.0.67-727982667e
term: xterm-kitty
platform: linux

## Error messages

## Log of coc.nvim
2019-05-20T11:11:59.953 INFO (pid:22093) [services] - registed service "languageserver.clangd"
2019-05-20T11:11:59.955 INFO (pid:22093) [plugin] - coc 0.0.67-727982667e initialized with node: v10.15.3
```

## Describe the bug

When moving the cursor to an error, the floating window closes almost instantly.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Create file `CMakeLists.txt` with：

```CmakeLists.txt
project(ok)
add_executable(main main.cpp)
```

- CocConfig file:
```json
{
  "languageserver": {
    "clangd": {
      "command": "clangd",
      "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"],
      "filetypes": ["c", "cpp", "h", "hpp", "objc", "objcpp"]
    }
  }
}
```

- Start (neo)vim with command: `vim -u mini.vim main.cpp`

## Screenshots (optional)

![optimised](https://user-images.githubusercontent.com/12513150/58010248-4af7bc00-7af0-11e9-98ba-bc468a7fa64c.gif)

**Comment by chemzqm** [comment]
Please provide minimal vimrc to reproduce.

**Comment by pLesur** [comment]
I used the one given in the issue template:

```
set nocompatible
set runtimepath^=/home/lesur/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

**Comment by pLesur** [comment]
The version I'm using is: 7279826 (current master)

**Comment by kornosaurus** [comment]
I'm getting the same problem using coc-tsserver

**Comment by chemzqm** [comment]
Can't reproduce, try remove package bundles in `~/.local/share/nvim/site/` and use minimal vimrc.

**Comment by kornosaurus** [comment]
Removing the package bundles doesn't help sadly

**Comment by kornosaurus** [comment]
I installed the latest neovim and it started working

**Comment by chemzqm** [comment]
Fixed, bug with old version of neovim.
