### ISSUE TITLE
Support completion within command-line-window

### ISSUE THREAD

**Issue by mwcz** [neoclide/coc.nvim#797]
**Is your feature request related to a problem? Please describe.**
Hello, I'm really loving the plugin, but there's one thing I'm really missing: local file path autocomplete inside cmdwin (`help cmdwin`).  

Here's a brief recording of the current behavior, first with nvim+coc.nvim (autocomplete is only available via vim's default `<Tab>` behavior which is very awkward) and then with vim+deoplete which does support streamlined autocomplete inside a cmdwin.

![nvim-coc-then-vim-deoplete](https://user-images.githubusercontent.com/364615/58118374-a9936780-7bce-11e9-9ecb-68a344e333e7.gif)

**Describe the solution you'd like**
Autocomplete for local file paths works fantastically well inside regular buffers.  I would love to see that extended to cmdwin buffers too.

**Describe alternatives you've considered**
Autocomplete is one of my primary methods for finding and opening files, so I can't think of any alternatives.

**Additional context**
Here's a reproducer:

Using this `minimal-init.vim`:

```vim
set rtp+=~/projects/coc.nvim/
```

```
nvim -u minimal-init.vim
```

Once inside, press `q:` to open the cmdwin.  Press `i` to enter insert mode.  Type `e ./`.  No autocompletion menu will appear.

**Comment by mwcz** [comment]
@chemzqm Hello, may I ask why this was closed?  Is it a duplicate?

**Comment by chemzqm** [comment]
@mwcz it's fixed by https://github.com/neoclide/coc.nvim/commit/454e0dec07faaebf093181d06a8236f2bb07d8ae

**Comment by mwcz** [comment]
Wonderful thank you!

**Comment by mwcz** [comment]
Posting this in case this helps any other cmdwin users.  When I first tried out the patch (454e0de) it didn't work for me.  I traced it back to my vimrc which included some code to make cmdwins start up in insert mode.

```vim
augroup command_window
    autocmd CmdwinEnter * startinsert " this line is messing up coc.nvim completion inside cmdwin
augroup END
```

I had a hunch that coc.nvim might be listening for startinsert and my config could be causing a race condition somehow.  I tried adding a delay to the `startinsert` and it worked.  Even a zero millisecond delay works consistently.  If you're having the same problem (no autocomplete inside cmdwin with patch 454e0de), try replacing the startinsert line:

```vim
autocmd CmdwinEnter * startinsert
```

With this:

```vim
autocmd CmdwinEnter * call timer_start(0, { tid -> execute('startinsert')})
```

**Comment by chemzqm** [comment]
You can use nested in your autocmd.

**Comment by mwcz** [comment]
I tried:

```vim
autocmd CmdwinEnter * nested startinsert
```

then I tried:

```vim
autocmd CmdwinEnter * ++nested startinsert
```

(`:help autocmd-nested` has an example with `++nested`)

But neither worked. :(

**Comment by mwcz** [comment]
I'm probably the only one, but if anyone else has the same problem, here's my hacky workaround.  In the command window, it puts you into insert mode immediately, and also turns Coc off and on again, so that it will be enabled in the command window.

```vim
augroup command_window
    function! ReInitCoc()
        execute("CocDisable")
        execute("CocEnable")
    endfunction
    autocmd CmdwinEnter * startinsert
    autocmd CmdwinEnter * call timer_start(0, { tid -> execute("call ReInitCoc()")})
augroup END
```

Demo:

![cmdwin-coc](https://user-images.githubusercontent.com/364615/64638656-33607e00-d3d4-11e9-88cb-43abadb9e212.gif)
