### ISSUE TITLE
Adapt Code Spell Check extension to coc-vim

### ISSUE THREAD

**Issue by albertorestifo** [neoclide/coc.nvim#798]
**Is your feature request related to a problem? Please describe.**
The spell-check built into vim is incredibly basic: it's meant for prose, not for coding.

I make a **ton** of typos while programming and one of my favourite extensions for vscode is [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker). It works really well and has a fairly large dictionary out of the box.

**Describe the solution you'd like**
I would love to have that extension adapted to work with coc-vim.

**Describe alternatives you've considered**
I tried adapting the extension myself but there isn't good documentation of how to do that yet, so I wonder if some maintainer has the goodwill to help with that.

**Comment by voldikss** [comment]
Checkout [coc-diagnostic](https://github.com/iamcco/coc-diagnostic) with [language linters](https://github.com/iamcco/diagnostic-languageserver/wiki/Linters)

**Comment by albertorestifo** [comment]
The problem is that currently it doesn't support any code spell checker: tools like `languagetool` are only mean for prose and don't understand code, which is where Code Spell Checker shines

**Comment by chemzqm** [comment]
I have it installed with VSCode, but don't really like it because of too much noise.
Maybe someone else will be interested in migrate it to coc.nvim.

**Comment by iamcco** [comment]
coc extension is similar to vscode extension, so if you want to port the extension have a look at https://code.visualstudio.com/api/get-started/your-first-extension

**Comment by iamcco** [comment]
I have ported to coc 

https://github.com/iamcco/coc-spell-checker
