### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by ovidius72** [neoclide/coc.nvim#799]
Is there a way to show a better error message in typescript files ?
I know that recently typescript since the 3.0 version ships with an improved error message.
However although I'm using the 3.4 version I can't see any improvement.
this is the error:

![AddNewKeypadScreen_tsx___Volumes_BACKUP_Projects_piosoft_BlackStar_BlackStar_src_screen__-_NVIM](https://user-images.githubusercontent.com/3592928/58132921-dd987800-7c22-11e9-9469-8b757f1fe108.png)

In vscode the error is the same but you can hover over with the mouse and scroll down until you can understand what the error is. In the above picture I can't really understand at the first sight what is happening and apparently there is no way to expand that message.

**Comment by chemzqm** [comment]
You can scroll the floating window by use mouse, but in your case it's all message so no need to scroll.
So what's your suggestion to make it more readable?

**Comment by ovidius72** [comment]
Thanks. Mouse was not working because I was using nvim inside a tmux session. Tried outside tmux and I can scroll the message as I do in vscode. The message in the screenshot is not the whole message, part of the text is at the very bottom and it contains the relevant issue giving me the name of the wrong property.
I'm not sure what to suggest but something that doesn't require the mouse would be better, maybe a shortcut that show the message in the classic vim  QuickList  without truncating it, or a new window at the bottom that you can focus and scroll ?

**Comment by chemzqm** [comment]
> but something that doesn't require the mouse would be better

Sure, there is `coc#util#float_jump()` can be used for jump to floating window, mostly I use `<C-w>p` for jump to last opened window then `<C-f>` to scroll.

**Comment by ovidius72** [comment]
Wow, I didn't know about that. Amazing. Works like a charm. Thank you very much.
Closing.

**Comment by hamza-tm** [comment]
> > but something that doesn't require the mouse would be better
> 
> Sure, there is `coc#util#float_jump()` can be used for jump to floating window, mostly I use `<C-w>p` for jump to last opened window then `<C-f>` to scroll.

@chemzqm When I try `<C-w>p` it jumps to the window correctly, but it only lasts for a split second before disappearing. Any ideas what could be going on?

I suspect the window is being removed because I am no longer hovering over the affected code.

**Comment by chemzqm** [comment]
@hamza-tm Can't reproduce, try minimal vimrc.
