### ISSUE TITLE
Can't uninstall coc

### ISSUE THREAD

**Issue by 0x113** [neoclide/coc.nvim#8]
I tried to remove it by `PlugClean` but it didn't work, also I remove `.vim/plugged` directory but without results. So how can I remove it ?

**Comment by chemzqm** [comment]
Remove the directory of coc plugin should just works.
You can run command `:echo &runtimepath` to find out there the directory is,.

**Comment by chemzqm** [comment]
Would you mind to let me know the reason of uninstall this plugin?

**Comment by 0x113** [comment]
I removed all folders from `:echo &runtimepath` and I remove neovim and vim, then I installed neovim back and I pasted my `init.vim` back, installed all plugins and I have still autocomplete for css. The reason of uninstalling: I just wanted to test this plugin and I don't really need it, but it's great and really easy to use.

**Comment by chemzqm** [comment]
Ok, I think the problem is your `PlugClean` command not works as expected for some reason.

**Comment by 0x113** [comment]
I find out that problems shows after doing `UpdateRemotePlugins`. Do you know how to fix it ?

**Comment by chemzqm** [comment]
I can't without knowing what the problem is.

**Comment by PneumaOfficial** [comment]
I'm also unable to remove coc. I removed the directories manually and still I see this error every time I open a file, I have to click enter 3 times every time I see it in order to continue on with my day.

![image](https://user-images.githubusercontent.com/39502544/204982309-6dd19696-34e6-45c3-86fc-ae17779941fa.png)

**Comment by chemzqm** [comment]
It should be installed by your plugin manager, check it’s documentation
