### ISSUE TITLE
Syntax highlighting in documentation displayed by hovering

### ISSUE THREAD

**Issue by gbcreation** [neoclide/coc.nvim#80]
**Is your feature request related to a problem? Please describe.**
Compared to VSCode, the result of CocAction('doHover') displayed in the Preview window has no syntax highlighting.

![screenshot_20180918_140608](https://user-images.githubusercontent.com/454315/45686190-0a543700-bb4c-11e8-93d9-6f562ac558fd.png)

**Describe the solution you'd like**
It would be useful to have syntax highlighting in the Preview window in a similar way as what is displayed by VSCode when the mouse cursor is over JS variable for example:

![screenshot_20180918_140154](https://user-images.githubusercontent.com/454315/45686061-b2b5cb80-bb4b-11e8-8f47-c6297375afe4.png)

**Comment by chemzqm** [comment]
You can have the highlight by using https://github.com/tpope/vim-markdown and add something like:
```
  let g:markdown_fenced_languages = ['css', 'javascript', 'js=javascript', 'typescript']
```
to your .vimrc

**Comment by gbcreation** [comment]
Works like a charm. Thank you! :+1:
