### ISSUE TITLE
Coc error after last update

### ISSUE THREAD

**Issue by bigardone** [neoclide/coc.nvim#803]
## Result from CocInfo

`:CocInfo` does not work. If I run `:messages` here is the output.

```
client coc abnormal exit with: 1

[coc] server connection lost
[coc.nvim] error: /Users/ricardogarciavega/.local/share/nvim/plugged/coc.nvim/build/index.js:1
Command failed (exit code 22): ^[[34mcurl --fail -L https://raw.githubusercontent.com/neoclide/coc.nvim/release/index.js^[(B^[[m
        ^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:749:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
```

## Describe the bug

Coc stops working and throws the described error.

## Reproduce the bug

- Updated Coc to version `86f938db42dd071257a16c6f500c7d7a8dd8f34d`.
- Open nvim.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with the command: `vim -u mini.vim`

- Operate vim.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/1090272/58307445-f198d100-7dfe-11e9-9ad7-556733b32b57.png)

**Comment by chemzqm** [comment]
Have not idea since the curl command should only invoked by `./install.sh` not nodejs.

**Comment by chemzqm** [comment]
I think you have download a invalid index.js bundle, checkout content of `/Users/ricardogarciavega/.local/share/nvim/plugged/coc.nvim/build/index.js`

**Comment by bigardone** [comment]
I just updated Coc this morning and it’s working fine again 😁
