### ISSUE TITLE
Add more options to fund the project

### ISSUE THREAD

**Issue by vlad-timofeev** [neoclide/coc.nvim#804]
The project is so amazing you should make sure it keeps going by adding more options to financially support it.
Github has recently introduced a sponsor button:
https://twitter.com/github/status/1131477404843741184
I'm a Patreon user, and I'd be glad to enroll to monthly funding.

**Comment by chemzqm** [comment]
There's a sponsor button at top now.

**Comment by vlad-timofeev** [comment]
@chemzqm the patreon link seems to be leading to 404 page.

**Comment by chemzqm** [comment]
Thanks, fixed now.
