### ISSUE TITLE
ALE diagnostic signs don't appear

### ISSUE THREAD

**Issue by artemave** [neoclide/coc.nvim#805]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled May 07 2019 09:49:41)
node version: v11.12.0
coc.nvim version: 0.0.67-727982667e
term: dumb
platform: linux

## Error messages

## Log of coc.nvim
2019-05-24T11:00:14.117 INFO (pid:23732) [services] - registed service "tsserver"
2019-05-24T11:00:14.127 INFO (pid:23732) [plugin] - coc 0.0.67-727982667e initialized with node: v11.12.0
2019-05-24T11:00:14.225 INFO (pid:23732) [services] - service tsserver started

## Output channel: snippets


## Output channel: tsserver

[Info  - 11:00:14 AM] Forking TSServer
PATH: /home/artem/.rbenv/shims:/home/artem/projects/vetpost/bin:/home/artem/.nvm/versions/node/v11.12.0/bin:/home/artem/.rbenv/shims:/home/artem/.yarn/bin:/home/artem/.config/yarn/global/node_modules/.bin:/home/artem/bin:/home/linuxbrew/.linuxbrew/bin:/home/artem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/artem/.rbenv/bin:/home/artem/android-sdk/tools/bin:/home/artem/android-sdk/platform-tools:/home/artem/.fzf/bin 
[Info  - 11:00:14 AM] Started TSServer
{
  "path": "/home/artem/projects/coc-ale-test/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.4.5",
    "version": "3.4.5"
  }
}
```

## CocConfig:
```json
{
  "diagnostic.displayByAle": true
}
```

## Describe the bug

ALE diagnostic signs don't appear.

Note, that I disabled `tsserver` ALE linter - because I am execting coc to do that. If that `tsserver` is _not_ disabled, then I can see diagnostic signs appear for a brief second and then disappear. But I don't want ALE to run `tsserver` anyway.

## Reproduce the bug

Clone this repo https://github.com/artemave/coc-ale-test and run:

`vim -u mini.vim test.ts`

## Screenshots (optional)

eslint error appears, but not the typescript one:
![image](https://user-images.githubusercontent.com/23721/58322068-2ec18b00-7e20-11e9-8305-8611d3f38320.png)

coc is aware of typescript errors:
![image](https://user-images.githubusercontent.com/23721/58322085-400a9780-7e20-11e9-9a9f-136480f4b99a.png)

**Comment by artemave** [comment]
@chemzqm all works as expected on that linked repo?

**Comment by chemzqm** [comment]
Reproduced, but it's ale's issue, coc send the diagnostics to ale as expected and doesn't display them.

**Comment by artemave** [comment]
I found the bit of code where coc calls into ALE https://github.com/neoclide/coc.nvim/blob/536565f52d93579ea68a65ee3b9d92fe0688c8cb/src/diagnostic/manager.ts#L513

Then I added debug output to `ale#other_source#ShowResults`:
![image](https://user-images.githubusercontent.com/23721/58329548-1b6cea80-7e35-11e9-92d0-c98506433a53.png)


And here is what it prints when vim starts:
![image](https://user-images.githubusercontent.com/23721/58329524-1019bf00-7e35-11e9-9f7a-d9ec9ae70254.png)

The last message call is an empty array which, according to that helpful comment right above the `ale#other_source#ShowResults` definition, should empty the list.

coc seems to be iteration over some collections. Looks like the last one is empty and that clears the list?

https://github.com/neoclide/coc.nvim/blob/536565f52d93579ea68a65ee3b9d92fe0688c8cb/src/diagnostic/manager.ts#L499-L514

**Comment by chemzqm** [comment]
It's because there're two tsserver collection for typescript and javascript.

**Comment by artemave** [comment]
Thank you - fixed!
