### ISSUE TITLE
Option to disable ultisnips-not-loaded warning

### ISSUE THREAD

**Issue by astier** [neoclide/coc.nvim#806]
## Problem

I like to use ultisnipets only for certain filetypes. I load it in my vimrc like this:

```
Plug 'SirVer/ultisnips', { 'for': [ 'tex' ] }
```

However, when I work with a non tex-file coc shows me a warning that ultisnips is not loaded the first time I try to autocomplete something.

![2019-05-24-143500_261x23_scrot](https://user-images.githubusercontent.com/36510152/58327939-2d4c8e80-7e31-11e9-9535-0965759a44ab.png)

## Solution

Add a possibility to disable snippet-support for certain filetypes or an option to disable this warning.

**Comment by chemzqm** [comment]
You can use `"coc.source.ultisnips.filetypes": ["tex"]` in your settings.json.
