### ISSUE TITLE
In nvim, argument preview window gets lost when current argument wraps to second line

### ISSUE THREAD

**Issue by jamespharvey20** [neoclide/coc.nvim#807]
## Result from CocInfo

````
## versions

vim version: NVIM v0.4.0-dev
node version: v11.15.0
coc.nvim version: 0.0.67-ce102d528c
term: st-256color
platform: linux

## Error messages

## Log of coc.nvim
2019-05-24T21:15:51.136 INFO (pid:22082) [services] - registed service "languageserver.clangd"
2019-05-24T21:15:51.139 INFO (pid:22082) [services] - clangd state change: stopped => starting
2019-05-24T21:15:51.141 INFO (pid:22082) [plugin] - coc 0.0.67-ce102d528c initialized with node: v11.15.0
2019-05-24T21:15:51.216 INFO (pid:22082) [services] - clangd state change: starting => running
2019-05-24T21:15:51.224 INFO (pid:22082) [services] - service languageserver.clangd started
2019-05-24T21:15:52.432 INFO (pid:22082) [completion-complete] - Results from: around,languageserver.clangd
````

For full output, including `Output channel`, see: http://ix.io/1H5Q

## Describe the bug

When showing arguments on a function call being made, if the current argument wraps to the next line, the underlined argument will either jump back to the beginning then or on the second argument wrapped to the second line.

## Reproduce the bug

- Start `nvim` with an `init.vim` that only loads coc through pathogen.

- Create a horrible function that probably needs to be refactored:

````
void foo(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j, int k, int l, int m, int n, int o, int p, int q, int r, i  nt s, int t, int u, int v, int w, int x, int y, int z) {
}
````

- Start to write code that calls that function:

````
foo(1, 2, 3, ...
````

## Screenshots (optional)

See this screencast: https://asciinema.org/a/QmVxmFBHC1bhl2FjbHNcVN0Sv

In it, you'll see everything goes as expected through setting 'int k' to `11`.  But, after that next comma when it should start underlining `int l`, it jumps back to highlight `int a`.  You'll see after it gets through `int k` again, when it should be on `int w`, it jumps back to `int a` again.

You'll also see after the comma after `26`, when it's past the number of arguments it takes, it properly hides the window.  So, part of it must be knowing where it's at, and part of it isn't.

As a side note, perhaps after the comma after `26`, there is an opportunity to indicate the user is typing too many arguments.  (Don't know if it's worth adding a feature for this, because as soon as they escape, they'll get an error to show.)

I had other times fail where it wasn't as clean as this screencast shows.  Sometimes after wrapping back to the first argument, it would semi-randomly forget arguments were being typed, and come in and out of showing them.  (Not due to a timeout.)  Sometimes it would stay previewing the same argument when I typed 2 values.

I had other times where it wouldn't underline `int k` like it shows here, but immediately after `int j` would wrap back to `int a`.  So, sometimes it wraps once part of the current argument is on the second line, sometimes it waits until the current argument is entirely on the second line.

**Comment by chemzqm** [comment]
Could be bug of coc.nvim or your language server.
