### ISSUE TITLE
Compiler error/warning window flashes previous contents

### ISSUE THREAD

**Issue by jamespharvey20** [neoclide/coc.nvim#808]
## Result from CocInfo

````
## versions

vim version: NVIM v0.4.0-dev
node version: v11.15.0
coc.nvim version: 0.0.67-ce102d528c
term: st-256color
platform: linux

## Error messages

## Log of coc.nvim
2019-05-24T21:35:04.745 INFO (pid:29423) [services] - registed service "languageserver.clangd"
2019-05-24T21:35:04.748 INFO (pid:29423) [services] - clangd state change: stopped => starting
2019-05-24T21:35:04.750 INFO (pid:29423) [plugin] - coc 0.0.67-ce102d528c initialized with node: v11.15.0
2019-05-24T21:35:04.809 INFO (pid:29423) [services] - clangd state change: starting => running
2019-05-24T21:35:04.818 INFO (pid:29423) [services] - service languageserver.clangd started

## Output channel: languageserver.clangd

I[21:35:04.806] <-- initialize(0)
I[21:35:04.806] --> reply:initialize(0) 0 ms
I[21:35:04.810] <-- initialized
I[21:35:04.810] unhandled notification initialized
I[21:35:04.812] <-- textDocument/didOpen
I[21:35:04.812] Updating file /home/jamespharvey20/code/coctest/foo.cpp with command [/home/jamespharvey20/code/coctest/build] /usr/share/perl5/vendor_perl/auto/share/dist/Cope/g++ -o CMakeFiles/foo.dir/foo.cpp.o -c /home/jamespharvey20/code/coctest/foo.cpp -resource-dir=/usr/bin/../lib/clang/8.0.0
I[21:35:04.823] --> textDocument/publishDiagnostics
````

## Describe the bug

When going to a compiler error/warning to show a window with the message, it slightly flashes the previous window's contents, if any.

## Reproduce the bug

- Start `nvim` with an `init.vim` that only loads coc through pathogen, and sets different background colors on errors and warnings:

````
highlight CocErrorSign ctermfg=0 ctermbg=9
highlight CocWarningSign ctermfg=0 ctermbg=11
````

- Create code that causes a compiler error.

- Create code that causes a compiler warning.

- Switch between showing the error and warning messages.

## Screenshots (optional)

Asciinema doesn't quite pick up the flash.  See this crappy out of focus (it's the background color that matters) cell phone video that catches it: https://youtu.be/vDGLbf0w5JA

The flash is only a split second, but quite noticeable every time.  When I change lines, the previous window disappears as it should, and the new window appears.  But, when it appears, I can see a flash of the last window.  This is most noticeable when the colors are different, as I have them.  It happens the same way, regardless of if I:
* Move between window-causing areas quickly or leave a while between them.
* Have a blank line between the window-causing areas, and rest on it for a while.
* Use `st` (Suckless Terminal) or `xterm`.

Note the alignment issue caused by the extra-wide warning symbol is only in the screencast.  I don't actually see that.

## Best Guess on a Fix

I don't know if this is a coc or nvim bug.  I don't know if coc has the ability to set window contents independently of showing or hiding the window.

If it does, I think the current coc code sets the window to display then updates its contents.  If that's the case and were reversed, so it sets the window contents then sets it to display, I think the flash would go away.

If it doesn't, then maybe it would require nvim allowing coc to do these independently.

**Comment by chemzqm** [comment]
Should be bug of your neovim, I can't notice that flash which different background color.
It's recommended to use different text color which should be better for the flash.

**Comment by chemzqm** [comment]
I've made a fix, should be no flash any more.

**Comment by jamespharvey20** [comment]
Unfortunately, it still happens.  I talked in #neovim primarily with BjrnLinseGitter[.  Also JustinMKeyesGitt.  I noticed c3c5b2a8 during the discussion, and BjrnLinseGitter[ said it affects the completions popup, but didn't think it would affect diagnostics which uses `model/floatFactory.js`.  I updated, compiled, and tried it, and unfortunately it still flashes.  (Without a `build/` so it uses the fresh compilation.)

I compiled a debug version of neovim with `MIN_LOG_LEVEL=0` which logs everything.  It's a log of a session where I just displayed an error window, warning window, and the error window again.  I noted the times while making the log, and separated it into different sections with lots of newlines between them and a header, to easily see when I went to the line above the error, went to the line with the error causing it to show, went to the line above the warning, went to the warning, went to the line above the error, and went to the error a second time.  You can see the log here: http://ix.io/1K0J

In it, it shows that `nvim_open_win()` was called at `05:02:23.979` and `nvim_call_atomic()` is called at `05:02:23.980` with a bunch of things including `nvim_win_set_var()`, `nvim_buf_set_lines()`, and `nvim_buf_add_highlight()`.  For some reason that's registering as a noticeable flash on my system but not yours.

BjrnLinseGitter[ confirmed that if the `nvim_open_win()` becomes part of the `nvim_call_atomic()`, he expects that to fix the issue because a redraw only occurs after the atomic batch, so the actual order of `nvim_open_win()` versus the buffer updates shouldn't matter then.

So, it looks like `.pauseNotification()` needs to be called just a tad earlier.

I tried this change: (with re-running `yarn`)

````
diff --git a/src/model/floatFactory.ts b/src/model/floatFactory.ts
index c3992cc5..5c3c5e2a 100644
--- a/src/model/floatFactory.ts
+++ b/src/model/floatFactory.ts
@@ -180,14 +180,15 @@ export default class FloatFactory implements Disposable {
       if (mode == 's') await nvim.call('feedkeys', ['\x1b', 'in'])
       // helps to fix undo issue, don't know why.
       if (mode.startsWith('i')) await nvim.eval('feedkeys("\\<C-g>u")')
+      nvim.pauseNotification()
       let window = await this.nvim.openFloatWindow(this.buffer, false, config)
       if (token.isCancellationRequested) {
         this.closeWindow(window)
         return
       }
       this.window = window
       this._onWindowCreate.fire(window)
-      nvim.pauseNotification()
       window.setVar('float', 1, true)
       window.setCursor([1, 1], true)
       window.setOption('spell', false, true)
````

But, I still see the flash, and more importantly, a new neovim log still shows `nvim_open_win()` isn't part of the atomic call.  I don't know enough about the situation to know if the `await` could be forcing it to happen immediately.  I tried removing the `await`, but that causes all the `window.set...(...)` code to fail on an unfulfilled promise.

**Comment by chemzqm** [comment]
Just made a new fix, should be fixed now.

**Comment by jamespharvey20** [comment]
Completely fixed, thank you so much!
