### ISSUE TITLE
CocAction to display diagnostic messages under cursor

### ISSUE THREAD

**Issue by peterhorne** [neoclide/coc.nvim#81]
**Is your feature request related to a problem? Please describe.**
I can't see the full diagnostic message when I hold the cursor over a piece of code with an error because it is truncated.

**Describe the solution you'd like**
An action that echos the full diagnostic message (including line breaks) so that I can set up a custom mapping for it.

**Describe alternatives you've considered**
Viewing the diagnostics in the location list instead. This is not populated though - perhaps because I only have a single diagnostic to display? However the location list can't include line breaks so this wouldn't be a viable solution for lengthy diagnostic messages anyway.

**Comment by chemzqm** [comment]
Fixed at bce4e358f58b6c38cdbc3aad9b86d72f2073c5b2
