### ISSUE TITLE
Flicker effect advancing through arguments, from opening new windows

### ISSUE THREAD

**Issue by jamespharvey20** [neoclide/coc.nvim#811]
## Result from CocInfo

````
## versions

vim version: NVIM v0.4.0-dev
node version: v11.15.0
coc.nvim version: 0.0.67
term: st-256color
platform: linux

## Error messages

## Log of coc.nvim
2019-05-25T17:29:11.827 INFO (pid:6303) [services] - registed service "languageserver.clangd"
2019-05-25T17:29:11.830 INFO (pid:6303) [plugin] - coc 0.0.67 initialized with node: v11.15.0
````

## Describe the bug

When advancing through arguments, the floating window is closed and reopened causing a flickering effect, when the comma is pressed, as it advances to the next argument.

I manually made calls in nvim, and found that if the window isn't closed, but only `nvim_buf_set_lines()` and `nvim_win_set_config()` (if needed to move), there's no such flickering.

Since at the comma it knows if the window will be closed (past the last argument) or redrawn (to another argument), I hope in the latter situation, it would be possible to update the existing window like this.  Probably in an atomic call.

Maybe it would be worthwhile to expand when this is done, to not just advancing through arguments, so if a single movement would trigger what would now be an unrelated floating window, that it would re-use an existing window.  Like in the situation of an error and a warning window, so there would be no redraw with there being no floating window.

Appreciate your work on the different flashes/flickers.  I'm one of those people that are affected by them more than many.

## Reproduce the bug

- Type arguments to a function.

## Screenshots (optional)

https://asciinema.org/a/1g6jrx39IqxaHCfz8jPtJaDqD

**Comment by chemzqm** [comment]
It's expected, since float window is not reused for signature help.

**Comment by jamespharvey20** [comment]
Definitely expected from not reusing the float window.  Couldn't it reuse the float window though, if upon a move it needed a float window there too?  Or, if that's too complicated, at least in the situation of advancing through arguments in signature help?

**Comment by chemzqm** [comment]
Should be not too complicated, just remove this line https://github.com/neoclide/coc.nvim/blob/master/src/model/floatFactory.ts#L139, and reuse window when possible at https://github.com/neoclide/coc.nvim/blob/master/src/model/floatFactory.ts#L184
