### ISSUE TITLE
jumpy action list(:normal "ac") + ubuntu 18.04

### ISSUE THREAD

**Issue by Shandun** [neoclide/coc.nvim#814]
Hi,chemzqm,
The coc.nvim is really great plugin! Thank you for your hard work! I recently found when I use action list(:normal "ac"), the list shown will jumped back so I can not see the option. Is there some set that I can overcome it? Thanks a lot!

My .vimrc is like:

"modify the tab key as 4 space
set expandtab
set softtabstop=4
set tabstop=4
"do not consider forward compatible
set nocompatible
" Search & display
set ignorecase
set incsearch
set nohls
set number
set relativenumber
set showmatch
set smartcase

"this is fix for chinese character show 
set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1
set enc=utf8
set fencs=utf8,gbk,gb2312,gb18030

comm! Pr3 ! python3 %

" Vertical diff
set diffopt=filler,vertical

" Space for page up/down
"noremap <SPACE> <C-F>

" Use system clipboard
set clipboard=unnamedplus

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Multiple Plug commands can be written in a single line using | separators
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
"nerdtree git plugin intall
Plug 'Xuyuanp/nerdtree-git-plugin'

"Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Comment/uncomment code 
Plug 'tpope/vim-commentary'

" use for the substitude due to the case
Plug 'tpope/vim-abolish'

" Install nightly build, replace ./install.sh with install.cmd on windows
Plug 'neoclide/coc.nvim', {'do': './install.sh'}

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Unmanaged plugin (manually installed and updated)
Plug '~/my-prototype-plugin'

"liquibase rollback tool
Plug 'ryanhhtan/vim-helpers' 

"ag text serch globally
Plug 'rking/ag.vim'

" Initialize plugin system
call plug#end()

let g:coc_global_extensions = ['coc-java', 'coc-json', 'coc-python', 'coc-snippets', 'coc-yaml', 'coc-highlight']

"auto open and hot key map
autocmd vimenter * NERDTree
map <C-n> :NERDTreeToggle<CR>

"go to definition
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use `[c` and `]c` to navigate diagnostics
nmap <silent> [c <Plug>(coc-diagnostic-prev)
nmap <silent> ]c <Plug>(coc-diagnostic-next)

" Remap for do codeAction of current line
nmap <leader>ac  <Plug>(coc-codeaction)
" Fix autofix problem of current line
nmap <leader>qf  <Plug>(coc-fix-current)

Best Regards,
Charles

**Comment by chemzqm** [comment]
> I use action list(:normal "ac"), the list shown will jumped back so I can not see the option.

Can't understand what is your action list.

**Comment by Shandun** [comment]
Sorry, I mean press backslash key and key a and key c( \ + ac ) ,the pop out list will be gone immediately after it show.

**Comment by chemzqm** [comment]
What does `pop out list` means?

Please provide detail steps to reproduce.

**Comment by Shandun** [comment]
I made a gif file to illustrate it, thank you for your patient.
![631537db-b347-4b81-8b6f-892544175194](https://user-images.githubusercontent.com/32905893/58575452-ea0a6b00-81f6-11e9-8f01-59b84b0245db.gif)

**Comment by Shandun** [comment]
What I use is 
coc extension "coc -java" ,
What I set is 
nmap ac (coc-codeaction)
Then press \ + ac
and what happened is shown above.

**Comment by chemzqm** [comment]
What does `\` means since you mapped for `ac`?

**Comment by Shandun** [comment]
this is the default leader key of my vim .  The command ac need to be invoked with the leader key +ac.

**Comment by chemzqm** [comment]
Some of your plugin or configuration makes prompt unusable, you need to figure it out yourself.
