### ISSUE TITLE
Add new API for running specific CodeAction

### ISSUE THREAD

**Issue by jackielii** [neoclide/coc.nvim#817]
**Is your feature request related to a problem? Please describe.**
A specific CodeAction can only be triggered by bring up the menu first: [code](https://github.com/neoclide/coc.nvim/blob/b03c2bbc7263a1fa89163c2594dce09389a61efe/src/handler/index.ts#L466). This makes binding a key to a specific action impossible.

**Describe the solution you'd like**
Either make `doCodeAction` accept string that'll match "title" of an action, or create an new API `doCodeActionWithTitle` and/or `doFirstCodeActionOfType`. They should operate on a range just like current behaviour of `doCodeAction`

**Describe alternatives you've considered**
No alternatives I can think of

**Additional context**
N/A

**Comment by chemzqm** [comment]
Title is not unique, it has to be id.

**Comment by jackielii** [comment]
@chemzqm I wanted to use `id` but seems it's not in the `CodeAction` type. I think we should be fine with using `kind`
