### ISSUE TITLE
Coc won't start. Returns: `Reason: image not found`

### ISSUE THREAD

**Issue by hojberg** [neoclide/coc.nvim#818]
## Result from CocInfo
N/A - There is not output

## Describe the bug
Coc won't start. Returns: `Reason: image not found`

## Reproduce the bug
I feel terrible for submitting this without proper steps. It started happening after I attempted to uninstall `coc-highlight` which resulted in no output.

I've since uninstalled `coc` and installed it again, but I'm not sure if that removes any extensions installed or where those even are located on my filesystem.

Any help would be appreciated, thank you.

**Comment by Avi-D-coder** [comment]
@hojberg What is  your OS?

**Comment by hojberg** [comment]
I'm on macOS.

**Comment by Avi-D-coder** [comment]
I imagine it will be `~/.config/coc/extensions`

**Comment by hojberg** [comment]
Removing that did not work, however it made me realize that this might be an issue with nvm running the wrong thing and sure enough if I use the proper node it works. Thank you.
