### ISSUE TITLE
Floating windows jumping due to documentation floating window getting focus

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#819]
## versions

vim version: NVIM v0.4.0-884-gc6cd6081b
node version: v11.15.0
coc.nvim version: 0.0.67
term: tmux-256color
platform: linux

## Output channel: Python

Starting Jedi Python language engine.
##########Linting Output - pylint##########

## Describe the bug

Documentation floating window getting cursor focus cause floating windows to jump around to new cursor position. This happens only with specific completions, like after typing "int" in a python file with coc-python enabled.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start neovim with command: `nvim -u mini.vim`

- `:CocInstall coc-python`

- `:e test.py`

- Type "int"

- Use `<c-n>` to select first completion option

## Screenshots (optional)

![screencast](https://user-images.githubusercontent.com/1269815/58577134-3320e600-821c-11e9-8c5a-ab18d743391d.gif)

**Comment by chemzqm** [comment]
Should be bug of your neovim, there's no c6cd6081b on master of neovim

**Comment by chemzqm** [comment]
Tried neovim c6cd6081b, can't reproduce.

**Comment by Avi-D-coder** [comment]
I can reproduce with coc-rls.

vim version: NVIM v0.4.0-889-gf8f63393c
node version: v11.15.0
coc.nvim version: 0.0.67
term: xterm-256color
platform: linux

Worse somehow I started typing in the floating doc window?
And documentation flickers when typing.
![ezgif-4-9d39f048415e](https://user-images.githubusercontent.com/29133776/58598604-089a5180-824b-11e9-9564-d32cd763a5fb.gif)

**Comment by Avi-D-coder** [comment]
NVIM v0.4.0-892-gc6cd6081b built a minute ago.

Look where the cursor is.
 
![Screenshot_20190529_195409](https://user-images.githubusercontent.com/29133776/58598860-f967d380-824b-11e9-8d91-b89c612651da.png)

**Comment by chemzqm** [comment]
Should be bug of neovim on linux, old version of coc.nvim should have same issue, use older version of neovim should help.

It have to jump window for highlights, so need fix by neovim.

**Comment by Avi-D-coder** [comment]
What neovim introduced the error?

**Comment by chemzqm** [comment]
I don't know, no such issue on my mac.

**Comment by Avi-D-coder** [comment]
I tested back 24 days to https://github.com/neovim/neovim/commit/9c6476d81e47f886e448579261192db6c9a92135.

I'm pretty sure it's coc

**Comment by Avi-D-coder** [comment]
coc   master~24 7d9618bc969a13b8b6d5a1ec173fc2a5addded19 is known to work. Bisecting now

**Comment by Avi-D-coder** [comment]
8b8eae9ec1edd7190c6e751e64a0e55be49f911c is the first bad commit
commit 8b8eae9ec1edd7190c6e751e64a0e55be49f911c
Author: chemzqm <chemzqm@gmail.com>
Date:   Sat May 25 20:51:37 2019 +0800

    feat(float): use matchaddpos for highlights

:040000 040000 4e6f5e2675495189780bad973d0d43b4668a55fb a6e6b546bc06b8d338c0d437674dffd6b3b85dc5 M      src

**Comment by chemzqm** [comment]
@Avi-D-coder I've made it to catch errors on call_atomic.

**Comment by Avi-D-coder** [comment]
@chemzqm That fixed it for me. Thanks as always

**Comment by oblitum** [comment]
OK, this got fixed for me as well. I'm not sure which commit fixed it. A commit reference would be good.

**Comment by jerry901** [comment]
i set jedi.enable to false and it went off, works fine
