### ISSUE TITLE
Double/Duplicate autocomplete suggestions

### ISSUE THREAD

**Issue by esn89** [neoclide/coc.nvim#822]
## Result from CocInfo

https://pastebin.com/cG97gG8S

## Describe the bug

Autocomplete shows the same suggestion 2 times.  The only difference I see is in the floating windows.  Either the formatting is different, or no description at all.

## Reproduce the bug

Here is a snippet from my coc.vim settings:
https://pastebin.com/aXFCSWBG
And here is my coc-settings.json:
https://pastebin.com/yz0jqWLz

## Screenshots (optional)
https://i.imgur.com/DYBNpua.png

**Comment by chemzqm** [comment]
It's your problem, you should remove MPLS configuration if you're using coc-python.

**Comment by esn89** [comment]
You are right.  Thank you!
