### ISSUE TITLE
PageUp/PageDown in CocList

### ISSUE THREAD

**Issue by SicariusNoctis** [neoclide/coc.nvim#825]
`<Up>` and `<Down>` can currently be used to scroll through a `CocList`.

`<PageUp>` and `<PageDown>` would make it faster to browse through a large list.

**Comment by chemzqm** [comment]
I think you should use `<C-f>` `<C-b>` `<C-u>` `<C-d>` in vim.

**Comment by chemzqm** [comment]
There's no `<PageUp>` and `<PageDown>` with my keyboard, so I don't if it works or not.

**Comment by SicariusNoctis** [comment]
Ah, looks like I can use  `<C-u>` and `<C-d>`, but only if I switch to Normal mode first via `<C-o>`.

Is it possible to make it work in insert/fuzzy mode?

**Comment by chemzqm** [comment]
There's support for `<C-f>` and `<C-b>`, support for `<C-u>` and `<C-d>` can be added.

**Comment by SicariusNoctis** [comment]
I took a look in [`src/list/mappings.ts`](https://github.com/neoclide/coc.nvim/blob/747a8ae000ddc8344b4cbc40c02fdfa1325074ae/src/list/mappings.ts#L70-L72):

```typescript
    this.add('insert', '<C-u>', () => {
      prompt.removeAhead()
    })
```

Looks like `<C-u>` is currently already used to clear the line.

**Comment by chemzqm** [comment]
It's used for simulate shell behavior, `<C-d>` support can be added.
