### ISSUE TITLE
Message: ignored auto-triggered completion, preceding char did not match

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#826]
![2019-05-31-125056_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/58701326-e3b8f200-83a2-11e9-9c1e-632a82d46081.png)

## CocInfo
https://gist.github.com/mihaelartz/1087ee766786af64a407f490111188b7

## LS Output
https://gist.github.com/mihaelartz/1de4b48d338dda8c8d0192d86807ce5d

**Comment by chemzqm** [comment]
Should be issue of clangd, the request send to server is expected.

**Comment by chemzqm** [comment]
It should silent fail, instead of throw an error.
