### ISSUE TITLE
Document conditional extension install

### ISSUE THREAD

**Issue by fatso83** [neoclide/coc.nvim#827]
**Describe the solution you'd like**
It currently says we should install extensions like this: `:CocInstall coc-tsserver`. I can't put this in a `.vimrc` file, as each install slows down the startup. I'd like the docs to provide an example of conditionally loading extensions (or better, make the check to see if an extension is installed take less than the 1-2 secs it currently does).

**Describe alternatives you've considered**
```
if !coc-installs('coc-tsserver'); CocInstall coc-tsserver; fi
```
(or something - don't know vimscript)

**Comment by Avi-D-coder** [comment]
`CocInstall` is imperative not declarative. You use it once and coc auto updates for you. The declarative equivalent is:
https://github.com/neoclide/coc.nvim/blob/4fee42c30c03d51b8cb213b9651ea996b4d842a9/doc/coc.txt#L756

**Comment by fatso83** [comment]
Well, this issue still holds, I guess. Add this to the docs:
```
let g:coc_global_extensions = ['coc-tsserver','coc-json']
```

I can supply a PR?

**Comment by Avi-D-coder** [comment]
It's in the docs see above `doc/coc.txt`.

Run `help coc`

**Comment by fatso83** [comment]
There's a difference between "it's available" and "this is how to use it". I'd bet that half the people with their own dotfiles repo don't really know how Vim configures its shit, but know that "if I put this line in here it works". But well, this issue at least serves as documentation for that, so Mission Accomplished, I guess :man_shrugging:

**Comment by SkyWriter** [comment]
Just to serve the documentation purpose and to add extra Google keywords: this is how I did that in my NixOS / Nix installation which favors declarative functional approach instead of imperative.

**Comment by chemzqm** [comment]
Another way is use some shell script which mentioned in wiki.
It would be easier if we can provide GUI like other editor, but we can't.
