### ISSUE TITLE
Hightlight on cursor hold does not respect colorscheme

### ISSUE THREAD

**Issue by xulongwu4** [neoclide/coc.nvim#829]
The highlight color of coc.nvim does not respect the selected color scheme. The following is a screenshot of a simple cpp code with highlight by coc.nvim:
![Screenshot from 2019-05-31 16:40:10](https://user-images.githubusercontent.com/16892446/58734843-8f276e00-83c6-11e9-88e6-4232e3159122.png)

The same code highlighted by vim-lsc:
![Screenshot from 2019-05-31 16:38:54](https://user-images.githubusercontent.com/16892446/58734867-aa927900-83c6-11e9-81c5-84b1be0932bc.png)

**Comment by chemzqm** [comment]
It's just different color, you can overwrite by use `highlight` command, checkout `:h coc-highlights`
