### ISSUE TITLE
E315: ml_get : invalid lnum error in nvim, after starting to use coc.nvim with other plugins

### ISSUE THREAD

**Issue by yedhink** [neoclide/coc.nvim#833]
## System Info
OS:        Ubuntu 18.04.2 LTS
KERNEL:    Linux 4.15.0-50-generic
Desktop Env : Kde Plasma

## versions

vim version: NVIM v0.4.0-dev
node version: v8.10.0
coc.nvim version: 0.0.67-ce102d528c
term: xterm-256color
platform: linux

Im attaching along a psatebin for the rest, since the info is pretty big.  https://pastebin.com/x2qLSm7m  

## Describe the bug

I'm getting a weird `E315: ml_get : invalid lnum` after i started using coc.nvim along with some ot the previously used plugins. I had never experienced the same error using nvim without coc.nvim.   
The error was noticeable when i quickly type `ciw` in normal mode over a word  which had a linting error(since it was a undefined word) created by clangd 6.0 as language server, then undo the change using `u`, then accidentally typing `ciu` instead of `ciw` again.

After debugging a bit by commenting out plugins in different combinations and order, i have come to find out that using  [targets.vim](https://github.com/wellle/targets.vim) along with coc.nvim, and typing the above mentioned keystrokes on the same word in the same document has consistently given me the error.

## Reproduce the bug
some points that you have to note here:  
1) I cant produce the same error while using nvim -u NORC <filename>
2) I cant produce the same error while using targets.vim alone.
3) I cant produce the same error while using coc.nvim alone.  
**The error is produced only when using both coc.nvim and targets together.**  

I don't know whether these steps would reproduce the bug again, but in my system, it certainly does. Watch the gif at end.  

1. Download the same test case that i used. https://pastebin.com/WSHsXx3Z
2. Use the following minimal nvim configuration and create the mini.vim file, with [vim-plug](https://github.com/junegunn/vim-plug#unix-1) as plugin manager:  
```bash
call plug#begin('~/.local/share/nvim/plugged')
Plug 'wellle/targets.vim'
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
call plug#end()
```  
3. Open the downloaded test case, using mini.vim as config, like `nvim -u mini.vim <filename.c>`  
4. Do the following keystrokes:  
```bash
22G
fm
ciw
ESC
u
ciu
```   
The following produces the same error persistenly. This often happens when i quickly perform keystrokes starting from `ciw` to `ciu` and repeat them. So try to repeat keystrokes from ciw to ciu very fast, while testing so as to reproduce error.  

## Screenshots (optional)
Im attaching along a gif to show what's happening.  
https://i.imgur.com/qGBjSxY.gif

**Comment by chemzqm** [comment]
It's internal error of vim, upgrade your neovim to use code of master branch might help.

**Comment by diegosomar** [comment]
Hello @chemzqm, I'm facing this issue now.
Frequently this error happens. It's hard to reproduce, because after press many keys to alert dismiss, completion works. And after a while, in another word, happens again. See my print below:

![Screen Shot 2020-05-30 at 16 36 34](https://user-images.githubusercontent.com/11670836/83337777-7f21c300-a294-11ea-86e1-650cacc78320.png)

After press ESC, `neovim` breaks and I got this screen:

![Screen Shot 2020-05-30 at 16 43 34](https://user-images.githubusercontent.com/11670836/83337816-cad46c80-a294-11ea-9121-ee8df5fee1c4.png)

In that case, I'm typed `<tou` and press `TAB` to complete to `<TouchableOpacity`. After press `TAB`, I got the error.

After reopen `neovim` and do the same action, works.

Sometimes `neovim` don't crashes and a pum remains in the window. I just navigate to that pum with `CTRL + w` and, with cursor within pum, I press `CTRL + w` and `q`. The pum goes out.

**CocInfo**

```
## versions

vim version: NVIM v0.4.3
node version: v12.16.2
coc.nvim version: 0.0.78-95e7ca8324
coc.nivm directory: /Users/vimuser/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Output channel: snippets

[Info 4:49:22 PM] Using ultisnips directories: /Users/vimuser/.dotfiles/ultisnips/snippets /Users/vimuser/.config/coc/ultisnips
[Info 4:49:22 PM] Using ultisnips python command: pyx

## Output channel: tsserver

[Info  - 4:49:59 PM] Forking TSServer
PATH: /usr/local/opt/libxml2/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/libiconv/bin:/usr/local/opt/openldap/sbin:/usr/local/opt/openldap/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/ncurses/bin:/Users/vimuser/.nvm/versions/node/v12.16.2/bin:/usr/local/opt/imagemagick@6/bin:/Users/vimuser/.rvm/gems/ruby-2.2.2/bin:/Users/vimuser/.rvm/gems/ruby-2.2.2@global/bin:/Users/vimuser/.rvm/rubies/ruby-2.2.2/bin:/Users/vimuser/.npm-global/bin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/gettext/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/libxml2/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/libiconv/bin:/usr/local/opt/openldap/sbin:/usr/local/opt/openldap/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/ncurses/bin:/Users/vimuser/.nvm/versions/node/v12.16.2/bin:/usr/local/opt/imagemagick@6/bin:/Users/vimuser/.rvm/gems/ruby-2.2.2/bin:/Users/vimuser/.rvm/gems/ruby-2.2.2@global/bin:/Users/vimuser/.rvm/rubies/ruby-2.2.2/bin:/Users/vimuser/.npm-global/bin:/usr/local/opt/python/libexec/bin:/usr/local/opt/gettext/bin:/Users/vimuser/.rvm/bin:/Users/vimuser/Library/Android/sdk/tools:/Users/vimuser/Library/Android/sdk/platform-tools:/Users/vimuser/.fzf/bin:/Users/vimuser/.rvm/bin:/Users/vimuser/.rvm/bin:/Users/vimuser/Library/Android/sdk/tools:/Users/vimuser/Library/Android/sdk/platform-tools 
[Info  - 4:50:00 PM] Started TSServer
{
  "path": "/Users/vimuser/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.8.3",
    "version": "3.8.3"
  }
}
```

[checkhealth.txt](https://github.com/neoclide/coc.nvim/files/4706328/checkhealth.txt)

**Comment by chemzqm** [comment]
We can't help, try neovim 0.5.0, at least I can't reproduce it on latest neovim

**Comment by chemzqm** [comment]
95e7ca8324
