### ISSUE TITLE
How to automatically call codeaction when saving a file

### ISSUE THREAD

**Issue by saibing** [neoclide/coc.nvim#835]
## Result from CocInfo

```vim
vim version: NVIM v0.4.0-753-gfbf2c414a 
node version: v10.15.3    
coc.nvim version: 0.0.68    
term: xterm-color    
platform: linux    

```

## Describe the bug

I add follow vim script into init.vim.

```vim
  " Fix autofix problem of current buffer    
  function! CocUpdateQuickFixes(error, actions) abort    
      for action in a:actions    
          echo action.kind    
          call CocAction('doCodeAction', action)    
      endfor    
  endfunction    
      
  command! -nargs=0 Fix :call CocActionAsync('quickfixes', function('CocUpdateQuickFixes'))    
  autocmd BufWritePre *.go :Fix  
```

## Reproduce the bug

I want to automate the codeaction when I save the file, but it doesn't actually work.

Maybe the code I wrote has a problem. Can coc.nvim implement my function above?

## Screenshots (optional)

There is no any output.

**Comment by chemzqm** [comment]
Your code works as expected for me.
The codeActionKind must be `quickfix` for this to work, checkout output from your language server.

**Comment by saibing** [comment]
@chemzqm 

thank you.
