### ISSUE TITLE
Use Denite for selecting code actions

### ISSUE THREAD

**Issue by idanarye** [neoclide/coc.nvim#836]
`<Plug>(coc-codeaction)` uses Vim's `inputlist` for picking a code action, but (as far as I've seen) everywhere else where Coc needs the user to pick a choice it uses Denite, which is much more comfortable. Can we have Denite for code actions as well?

Also, I haven't got to use codelens yet, but it seems like they also use `inputlist` (they call `workspace.showQuickpick`) so I think they should also be using Denite.

**Comment by chemzqm** [comment]
No, coc.nvim doesn't require denite any more, and inputlist is better than denite for this case IMO.

**Comment by idanarye** [comment]
@chemzqm But Coc still uses a fuzzy matcher for other things. Now that I look at it really isn't Denite (no idea what it is - is it your own implementation?) but couldn't we use it for code actions?

**Comment by chemzqm** [comment]
What's problem with inputlist? I think it's not necessary, it just make things more complicated.

**Comment by idanarye** [comment]
When the list of options gets long, I find it easier to fuzzy-match than to type a number.

But I've poked around the API and I think I can implement it myself by calling `quickfixes`, picking one with FZF, and passing the result to `doCodeAction` - so I'll just do that.

**Comment by chemzqm** [comment]
Yes, you can. 
I recommend to use `<Plug>(coc-fix-current)` for run quickfix action of current line, it now supports prefered codeAction now.
