### ISSUE TITLE
[feature request]Show list of all available actions

### ISSUE THREAD

**Issue by yutakatay** [neoclide/coc.nvim#837]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chemzqm** [comment]
I don't know is your available actions means, you can use APIs provided to make the list yourself.

**Comment by yutakatay** [comment]
I'm sorry :cry:   I was sent on the way because I was sending by mobile phone.

**Comment by yutakatay** [comment]
https://github.com/iamcco/coc-actions
