### ISSUE TITLE
Is there a way to paste from registers in CocList?

### ISSUE THREAD

**Issue by jeroen-dhollander** [neoclide/coc.nvim#839]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I try to copy/paste register content in the CocList windows.
For example to find a symbol that I've copied from somewhere else I'd open the `:CocList symbols` and then I'd type `<ctrl+r>*`, which ends up simply inserting a '*' instead of the copied text.

**Describe the solution you'd like**

A way to paste registers content using `<ctrl+r><register-name>`in the CocList windows.

**Describe alternatives you've considered**

I've tried getting this to work with keybindings, but none of these work:

```
        // This gives an error 'At timer.processTimers' when typing <ctrl+r>*
        "<C-r>": "feedkeys:\\<C-r>",
        // This is an attempt to hard-coded copy from register '*' when typing ctrl+r.
       // It gives the same error as the attempt above.
        "<C-r>": "feedkeys:\\<C-r>*",
        // This feeds the data into the list window, which is immutable (for good reason)
        "<C-r>": "normal:\"*p",
```

**Comment by chemzqm** [comment]
You can use system clipboard.

**Comment by jeroen-dhollander** [comment]
Sweet thanks for adding the `paste` option
