### ISSUE TITLE
[Feature Request] Add text width limit for completion item, truncate rest

### ISSUE THREAD

**Issue by FeatureIssueRequester** [neoclide/coc.nvim#841]
**Is your feature request related to a problem? Please describe.**
If I program in C++ the completion items provided by ccls can get really long. **coc.nvim** just uses the whole completion item even if the text is too long for the pmenu and the neovim window. This make a lot of things unreadable / unavailable for the user e.g. the menu / detail field / source shortcut.

**Describe the solution you'd like**
In [deoplete](https://github.com/Shougo/deoplete.nvim) and [ncm2](https://github.com/ncm2/ncm2) exists an option to define the maximum text width limit for completion item and the rest is truncated. It would be cool if we can get something similar in **coc.nvim**.

**Screenshot**
Problem in coc.nvim:
![coc_completion](https://user-images.githubusercontent.com/51378896/58900268-25c59900-86ff-11e9-83cb-9524b1a81f52.png)

Solution in deoplete:
![deoplete_completion](https://user-images.githubusercontent.com/51378896/58900287-2fe79780-86ff-11e9-8524-1e3ecc2c5d86.png)

**Comment by FeatureIssueRequester** [comment]
@chemzqm Thank you very much for the work.

Would it be possible to indicate the truncation with a string for example with three dots "..."

coc.nvim from current master:
![coc_truncate_without_indicator](https://user-images.githubusercontent.com/51378896/58932539-6c011380-8764-11e9-8692-ac85062bd3d1.png)

ncm2 with truncation indicator:
![truncate_with_indicator](https://user-images.githubusercontent.com/51378896/58932549-76231200-8764-11e9-82a4-2c23ecaad4cb.png)

This helps to identify if an completion item is really truncated or if the completion item ended at the defined length.

**Comment by chemzqm** [comment]
I don't want to add that option, you can change the code at https://github.com/neoclide/coc.nvim/blob/master/src/completion/index.ts#L230
