### ISSUE TITLE
[Feature Request] Add floating window minimum width for suggestion help/documentation

### ISSUE THREAD

**Issue by FeatureIssueRequester** [neoclide/coc.nvim#843]
**Is your feature request related to a problem? Please describe.**
If the neovim window is to small and the completion item list takes the whole space the floating window with the suggestion/documentation is too small and unreadable.

**Describe the solution you'd like**
It would be great if we could have an option to define a minimum width for floating windows and if this width is not achievable the floating window should not be shown.

**Screenshots**
Problem if neovim is to small:
![coc_suggestion_floating_bad](https://user-images.githubusercontent.com/51378896/58900783-1b57cf00-8700-11e9-899d-b375c546025b.png)

If neovim is large enough:
![coc_suggestion_floating_normal](https://user-images.githubusercontent.com/51378896/58900800-2579cd80-8700-11e9-9251-7631eedea060.png)

**Comment by oblitum** [comment]
Just for sake of mention, another solution is to show function names only at completion, delaying display of overloads to signatureHelp. It was commented before on [this locked discussion](https://github.com/neoclide/coc.nvim/issues/305).  This solves two issues: 1. popup width without truncation, 2. less overloads on completion, which means less repeated results and a more useful result set (unique results for completion). But this question also relates with server response data, and whether to handle it smartly or not.

**Comment by oblitum** [comment]
Also, from your screenshots, you're talking about pum width, not the new floating windows.

**Comment by FeatureIssueRequester** [comment]
> Also, from your screenshots, you're talking about pum width, not the new floating windows.

The first screenshot shows the new floating window on the left side of the pum because on the right side has no space left. The main problem here is that the new floating window width is to small (8 charachter width) and the text is not really readable. 

Here the same problem if the pum width has enough space but the floating window has not enough space and the text gets unreadable:
![coc_suggestion_floating_bad_rigth_side](https://user-images.githubusercontent.com/51378896/58904581-18f97300-8708-11e9-8f5d-298865b23198.png)

In such cases it would be cool to disable the floating window for the suggestion.

**Comment by oblitum** [comment]
Ah OK. Now I get your request.

**Comment by chemzqm** [comment]
If there's minimal width of floating window, a preview window with short text would be hidden, which is bad. So

* Use `suggest.labelMaxLength` to truncate label of complete items.
* Use `suggest.floatEnable` to enable/disable falot of documenation.

Instead.

**Comment by FeatureIssueRequester** [comment]
Thank you very much for your work.
