### ISSUE TITLE
[Feature Request] Allow source shortcuts to be lowercase, do not convert them to upper case

### ISSUE THREAD

**Issue by FeatureIssueRequester** [neoclide/coc.nvim#844]
**Is your feature request related to a problem? Please describe.**
Source shortcuts are always converted to uppercase even if the string only contains lowercase characters.

Example:
`"coc.source.around.shortcut": "around"` -> Results to [AROUND]

**Describe the solution you'd like**
Just take the string content from the source shortcut configuration and don't convert them to uppercase and take them as is.

**Comment by FeatureIssueRequester** [comment]
@chemzqm Thank you very much. It works as expected.

I have one question. How can I change the shortcut for the languageclient source? I can not figure out how to change the [LS] shortcut.

**Comment by chemzqm** [comment]
@FeatureIssueRequester no such option, you can change to code at https://github.com/neoclide/coc.nvim/blob/master/src/language-client/client.ts#L1772
