### ISSUE TITLE
help on configuring coc for fortran, python and latex

### ISSUE THREAD

**Issue by rudrab** [neoclide/coc.nvim#845]
Dear all,
I am trying to configure fortran, python3 and latex using coc's completion. https://paste.fedoraproject.org/paste/p8C5356fnBg4stjCSYq2Yw is my .vimrc.

But, for fortran, it is not showing any completion.

I am in `vim8`, and already install `nodejs` and `yarn`.

`fortls` and `digestif` is also installed, and available from `commandline`.

Kindly help.

**Comment by chemzqm** [comment]
For fortran:
https://github.com/neoclide/coc.nvim/wiki/Language-servers#fortran

For python:  it's recommended to install https://github.com/neoclide/coc-python

For latex: https://github.com/neoclide/coc.nvim/wiki/Language-servers#latex

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel when you have issue with a language server.
