### ISSUE TITLE
Problems with Running Coc Functions from Ex Mode

### ISSUE THREAD

**Issue by Teknitix** [neoclide/coc.nvim#847]
I have a vimrc that I try to make cross-platform compatible since I have to work on different systems. When I use this .vimrc on WSL, for some reason none of the `:Coc*` functions work after installing coc.nvim, such as `:CocConfig`. They're not recognized by Vim. It previously worked just fine on WSL but when I install a fresh instance on the same machine it doesn't work.
For `:CocConfig` I get `E492: Not an editor command: CocConfig`.

I reinstalled my configuration with the vimrc.

* I installed the plugin via Vundle.
* I ran the yarnpkg function and it installed successfully.
* When these did not fix the problem, I used the `:call coc#util#install()` and `:call coc#util#build()` methods to install the binaries. They processed without error. Neither method fixed the problem.

What can I do to fix this??

**Comment by chemzqm** [comment]
Check `:version` in your vim, if it's >= 8.1, check `:CocInfo`.

**Comment by Teknitix** [comment]
Thanks for the response. I'm using the version of Vim that's in the Ubuntu repositories, which is `sudo apt-get install vim-gtk`, which is version 8.0
Actually `:CocInfo` doesn't work and gives me the same error E492 described above unfortunately.

**Comment by chemzqm** [comment]
The plugin won't load on vim 8.0, it's documented.

**Comment by Teknitix** [comment]
That's strange, it loaded before just fine. I'm not sure what happened. What can I do? I suspect I can build Vim from source directly, correct? If so, how can I get all the same options that come with the vim-gtk package?

**Comment by chemzqm** [comment]
>  it loaded before just fine.

It should be different version of vim.
What is exact vim version from vim-gtk package? 
You can try remove this line https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L5

**Comment by Teknitix** [comment]
As far as I can see, it says 8.0.1453:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    +tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua               +ruby              +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       +xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
...
```
After commenting out that line it works fine and auto-completes. Thanks for the tip. I haven't encountered any idiosyncrasies. However, I'm sure that since you built it for >8.0, I'm bound to encounter some problems. Do you recommend I figure out how to build 8.1 and above from the source code?

**Comment by chemzqm** [comment]
I think it's better to lower the limitation to 8.0.1453, since it's quite close to vim 8.1.

**Comment by chemzqm** [comment]
> I didn't encounter any [LS] entries in the completion menu, it seems. Only [A]

Seems that you don't have a working language server.

**Comment by Teknitix** [comment]
Oh I see - thank you! That would help, since it would then work out of the box on those version of Vim. I wish the package maintainer would update it to 8.1, it appears that it hasn't been updated since 2016, unfortunately.

**Comment by Teknitix** [comment]
> > I didn't encounter any [LS] entries in the completion menu, it seems. Only [A]
> 
> Seems that you don't have a working language server.

I see, I must still have more setup/customizations to do. I tried to read the documentation and follow what it says but I suppose I still haven't quite figured it out. I have a coc-settings.json file setup as follows:
```
{
  "languageserver": {
    "bash": {
      "command": "bash-language-server",
      "args": ["start"],
      "filetypes": ["sh"],
      "ignoredRootPaths": ["~"]
    },
    "dockerfile": {
      "command": "docker-langserver",
      "filetypes": ["dockerfile"],
      "args": ["--stdio"]
    },
    "intelephense": {
      "command": "intelephense",
      "args": ["--stdio"],
      "filetypes": ["php"]
    },
    "golang": {
      "command": "gopls",
      "args": [],
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    },
	"ccls": {
	  "command": "ccls",
	  "filetypes": ["c", "cpp", "objc", "objcpp"],
	  "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
	  "initializationOptions": {
		 "cache": {
		   "directory": "/tmp/ccls"
		 }
	   }
	},
	"clangd": {
	  "enable": true,
      "command": "clangd",
      "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"],
      "filetypes": ["c", "cpp", "objc", "objcpp"]
    },
	"rustls":{
		"enable": true,
		"command": "rls",
		"filetypes": ["rust"],
		"revealOutputChannelOn": "error",
		"trace.server": "off"
	},
...
```

**Comment by chemzqm** [comment]
Try not use wsl, it's not tested with wsl.

**Comment by Teknitix** [comment]
Ah I see, thank you -- I'll have to come back to this and test it out on WSL later on.
On the host Windows machine upon which I was testing out WSL, which also has the same coc-settings.json, it seems as though there is then a problem with language server support with my coc-settings.json file.
When I do CocInfo, it lists normal processes, then errors start as follows:
```
...
2019-06-05T10:50:24.779 ERROR (pid:12892) [server] - uncaughtException Error: spawn bash-language-server ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

...

## Output channel: highlight

[Info  - 10:50:18] Highlight server running in node v8.12.0

## Output channel: vimlsp

(node:13784) UnhandledPromiseRejectionWarning: Error: no parsers registered for: "
C:/P"
    at parse (C:\Users\user\AppData\Local\coc\extensions\node_modules\snapdragon\lib\parser.js:473:15)
    at Parser.parse (C:\Users\user\AppData\Local\coc\extensions\node_modules\snapdragon\lib\parser.js:477:24)
    at Snapdragon.parse (C:\Users\user\AppData\Local\coc\extensions\node_modules\snapdragon\index.js:122:28)
    at Snapdragon.<anonymous> (C:\Users\user\AppData\Local\coc\extensions\node_modules\micromatch\lib\utils.js:47:45)
    at parse (C:\Users\user\AppData\Local\coc\extensions\node_modules\micromatch\index.js:739:26)
    at memoize (C:\Users\user\AppData\Local\coc\extensions\node_modules\micromatch\index.js:859:13)
    at Function.micromatch.parse (C:\Users\user\AppData\Local\coc\extensions\node_modules\micromatch\index.js:745:10)
    at create (C:\Users\user\AppData\Local\coc\extensions\node_modules\micromatch\index.js:686:44)
    at C:\Users\user\AppData\Local\coc\extensions\node_modules\micromatch\index.js:695:16
    at memoize (C:\Users\user\AppData\Local\coc\extensions\node_modules\micromatch\index.js:859:13)
(node:13784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
C:\Users\user\AppData\Local\coc\extensions\node_modules\vim-language-server\out\server\parser.js:26

        log.info("child_log: " + mess.log);
...
```
And on and on it goes with lots of errors for the rest of the document...

**Comment by chemzqm** [comment]
Looks like you don't have some of the dependencies installed.

**Comment by Teknitix** [comment]
I see: where can I get dependencies? For some reason I suppose I'm not understanding the documentation -- so for each language server, what else should I do besides the configuration I need in coc-settings.json?

**Comment by chemzqm** [comment]
Read the documentation of language server you're using, it's not part of coc.nvim.

You can get the output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Or maybe they have bugs on windows.
