### ISSUE TITLE
Confirm completion without pressing (Enter or any) key

### ISSUE THREAD

**Issue by Arghnews** [neoclide/coc.nvim#852]
The [Completion with Sources](https://github.com/neoclide/coc.nvim/wiki/Completion-with-sources#improve-the-completion-experience) and [Example vim configuration](https://github.com/neoclide/coc.nvim#example-vim-configuration) pages both show examples of how to enable completion using tab to move around the completion menu and \<CR\> to accept the completion.

The part of the [Example vim configuration](https://github.com/neoclide/coc.nvim#example-vim-configuration) for using \<CR\> to confirm completion I'm referring to is:

```vimscript
" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current position.
" Coc only does snippet and additional edit on confirm.
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```

Is there a way to confirm completions **without** pressing \<CR\> (or any other key) and still get the additional things like snippets and additional edits (like YouCompleteMe's default)? Ie. the opposite of the 2nd line of the comment above.

I am using neovim v0.4.0-944-g3305769ea on Ubuntu.

For example when writing C++ if I wanted to write `std::basic_string<char>` in coc.nvim using an LSP I would:

1. Type "std::basic"
2. Press tab until the correct entry for std::basic_string in the completion list is selected
3. Press \<CR\> (Enter)
4. The missing include line (#include \<string\>) will be inserted at the top of the file, the cursor will be moved to the "t" of "typename _CharT" which will be highlighted and the line changed to `std::basic_string<typename _CharT>`
5. Type "char"

Resulting in the line `std::basic_string<char>`.

I would like to be able to remove step 3.

**Comment by oblitum** [comment]
Just a correction, that's not the default behavior of YouCompleteMe if I recall correctly, currently it's not providing signature help, with or without snippets. There's a long standing issue open on that.

**Comment by oblitum** [comment]
What YouCompleteMe has always done, is what coc.nvim does already, for completion, not snippets, once you select whatever text in the completion menu, you don't need to confirm anything, since what's selected is already inserted, so you can opt to just keep typing.

**Comment by Arghnews** [comment]
@oblitum my apologies, ignore the mention of YCM then.

I am aware I can press or hold tab until I reach the right completion option and then keep typing and the completion will be inserted *without* pressing the Enter (or whatever key).

If I do this it does not seem to "count" as a completion event (apologies my coc and vimscript understanding are poor). For example things like the automatic inclusion of the correct missing header will not happen. Or the moving of my cursor to the middle of the template type etc.

I am asking if this is possible **with** it "counting" as a completion event and therefore the missing header gets inserted, the cursor moved to the type and the type inserted, etc.

Apologies if I was unclear. I am trying to remove what I list as step 3 from the [original question](https://github.com/neoclide/coc.nvim/issues/852#issue-453211692) whilst maintaining the extra things (inserted header, snippets behaviour etc.).

**Comment by oblitum** [comment]
I'm not sure about thing, don't you think it would be rather complex and strange to have extra edits applied and reverted while you browse popup completions. Say for one item you have one given header inclusion, and for another you have a different one, then when you browse the menu coc.nvim would be automatically change your buffer adding theses headers, or if you browse next it remove the last changeset to apply another one?

**Comment by Arghnews** [comment]
The changes are not applied whilst you browse through the menu. They are only applied after you have settled on a completion option and then press another key that isn't Tab or Shift-Tab. They would only be applied for the option chosen.

**Comment by oblitum** [comment]
OK. Maybe it's doable on popup close event, if there's such event, but sounds tricky, specially for snippets. Notice you don't need the "Enter" setup for confirmation, personally I just stick to [neo]vim default `<c-y>`, to make sure <kbd>Enter</kbd> is saved to produce newlines anytime.

**Comment by chemzqm** [comment]
No, it is by design,you can use other key.
