### ISSUE TITLE
Question: how to go to definition with absolute paths?

### ISSUE THREAD

**Issue by vlad-timofeev** [neoclide/coc.nvim#853]
I'm using `coc.nvim` together with `coc-tsserver` for javascript project. `coc-definition` works fine when imports are relative like this:
`import { calculate } from './Balances.helpers'`

But it doesn't work with absolute imports for example 
`import Panel from 'ui/Panel'`

Based on the latter example the directory structure of the project is like this:
```
root
->src
->->ui
->->->Panel
```
And the project is set up via Babel in such way that absolute imports are supposed to be resolved relative to `root/src` folder.

Is there a way to make the plugin to resolve them while doing `coc-definition`, `coc-references`, etc? Apologies if that's something mentioned somewhere, I couldn't find it, an example for my specific case would be helpful.

**Comment by chemzqm** [comment]
You should use `map` in jsconfig.json https://code.visualstudio.com/docs/languages/jsconfig

**Comment by nseptier** [comment]
@vlad-timofeev I'm having a similar problem, but I can't figure out what to modify in my jsconfig.json. Could you share what you did please?

**Comment by vlad-timofeev** [comment]
@nseptier this was the `jsconfig.js` I ended up with located in the root of that project:

```
{
  "exclude": [
    "node_modules"
  ],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "src/*": ["./src/*"],
      "actions/*": ["./src/actions/*"],
      "config/*": ["./src/config/*"],
      "components/*": ["./src/components/*"],
      "containers/*": ["./src/containers/*"],
      "errors/*": ["./src/errors/*"],
      "format/*": ["./src/format/*"],
      "helpers/*": ["./src/helpers/*"],
      "icons/*": ["./src/icons/*"],
      "locale/*": ["./src/locale/*"],
      "navigation/*": ["./src/navigation/*"],
      "reducers/*": ["./src/reducers/*"],
      "sagas/*": ["./src/sagas/*"],
      "selectors/*": ["./src/selectors/*"],
      "ui/*": ["./src/ui/*"],
      "var/*": ["./src/var/*"],
      "views/*": ["./src/views/*"],
      "HOC/*": ["./src/HOC/*"]
    }
  }
}
```
