### ISSUE TITLE
Add a command that returns the full list of available code actions

### ISSUE THREAD

**Issue by idanarye** [neoclide/coc.nvim#854]
Following the refusal of #836

I want to get a list of all possible code actions, so I can use FZF to pick one and run it with `CocActionAsync('doCodeAction', '...')`. The closest command I found is `CocAction('quickfixes')`, but it only returns actions marked as `CodeActionKind.QuickFix` - not the full range of actions seen in `CocAction('codeAction')`.

Can we have a command that returns the entire list?

**Comment by chemzqm** [comment]
Use CocAction command

**Comment by idanarye** [comment]
Actually, `CocList actions` works better because it also goes into insert mode.
