### ISSUE TITLE
[coc.nvim] node is not executable (node installed by nvm)

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc.nvim#856]
## Describe the bug

When installed with nvm, `node` when we first started the shell is a function defined in nvm scripts. So if we use `executable` to check, the error will be shown as above

## Reproduce the bug
```
# lazy load nvm zsh plugin
NVM_LAZY_LOAD=true
zplugin ice wait"0" lucid
zplugin light lukechilds/zsh-nvm
```

open the shell, execute `nvim`, the error above will show up
run `which node`:

```sh
node () {
        unset -f node npm npx yarn nvm > /dev/null 2>&1
        _zsh_nvm_load
        node "$@"
}
```

run `node -v && nvim`, the error will no longer show 

I think We should change the `executable('node')` check to something else, because most of node users is using nvm to install node

**Comment by chemzqm** [comment]
> because most of node users is using nvm to install node

I can't agree, since nvm sucks most of time.

Use `let g:coc_node_path = '/path/to/node'` when you can't use node in your $PATH.

**Comment by Muzietto** [comment]
>> because most of node users is using nvm to install node

> I can't agree, since nvm sucks on many cases.

This personal opinion regarding nvm is irrelevant to the true fact mentioned by the OP.

Please reconsider providing a user-friendly feature for solving this annoying issue.

**Comment by LukeAI** [comment]
So how do I resolve this? I have just installed neovim and coc.nvim on a fresh ubuntu 16.04 system. Do I have to install nodejs?

**Comment by oblitum** [comment]
just set the variable as suggested. nvm will have the node executable somewhere.

**Comment by chemzqm** [comment]
@LukeAI Make `node` in your $PATH

**Comment by lucasdf** [comment]
Cool! Had this same problem after removing the system's node and replacing it by `n` node installation.

At the end, the problem happened when my i3 shortcuts were launching NVIM with `/bin/sh` instead of bash. When using `sh` my custom node's bin location was not in the path, since my export command is in `bashrc` and `sh` sources `.profile` instead.

You can debug it by using `echo executable('node')` which will return 1 if it exists and is executable, and by using `echo $PATH` to print the environment variables considered by NVIM context.

As mentioned by people above, setting the path by using `let g:coc_node_path = '/path/to/node'` works. However, you must use the full path `/home/xxx/path/to/node`.

**Comment by yujinyuz** [comment]
I also had the same problem. I'm using Fish shell with nvm (https://github.com/FabioAntunes/fish-nvm)

Luckily, fish-nvm provides `nvm_alias_command` that creates binaries under `/usr/local/bin`.

So, what I did was I just executed `nvm_alias_command node` and coc is working again

**Comment by kirbygit** [comment]
May linux pc got corrupted and decided to install ubuntu and had to re-install everything. As I download zsh I encountered this problem. May I ask where can I put this single line?
`let g:coc_node_path = '/path/to/node'`
do I just put that somewhere in coc.vim or am I wrong.
![Screenshot from 2020-03-20 17-36-29](https://user-images.githubusercontent.com/20747057/77215463-69906000-6ad1-11ea-9390-d6f98990f1c5.png)

**Comment by yujinyuz** [comment]
@kirbygit What's the result of `which node` ?

**Comment by fannheyward** [comment]
> do I just put that somewhere in coc.vim or am I wrong.

put into your vimrc

**Comment by kirbygit** [comment]
ah I see @fannheyward thanks

**Comment by dagadbm** [comment]
make it work always: `let g:coc_node_path = trim(system('which node'))`

**Comment by chemzqm** [comment]
> make it work always: `let g:coc_node_path = trim(system('which node'))`

`system` command would slow down your vim on startup **significantly**

**Comment by dagadbm** [comment]
I did it and I find very little slow down actually but yes I figured it
would be a trade off.

**Comment by 5ilvers** [comment]
Just add a zsh function to lazy load nvm before starting nvim/vim
```
nvim () {
    unset -f nvim
    _zsh_nvm_load
    nvim "$@"
}
```
worked out alright for me

**Comment by dagadbm** [comment]
save yourself some pain.
install asdf,

**Comment by ShiromMakkad** [comment]
Add this to your .vimrc:
```
" https://github.com/neoclide/coc.nvim/issues/856
if $NVM_BIN != ""
  let g:coc_node_path = '$NVM_BIN/node'
endif
```
NVM can't be lazy loaded with this.

**Comment by tmpm697** [comment]
> Just add a zsh function to lazy load nvm before starting nvim/vim
> 
> ```
> nvim () {
>     unset -f nvim
>     _zsh_nvm_load
>     nvim "$@"
> }
> ```
> 
> worked out alright for me

This works but start nvim will freeze for 1-2s, but I think we don't have another good solutions here. (anyway why load up node took so long?)

Either have fast prompt or fast nvim startup. I chose fast prompt.

**Comment by GeekByte** [comment]
you can add code ```source ~/.bash_profile``` to your .zshrc

**Comment by g6ai** [comment]
@GeekByte In what way does that solve the problem?

**Comment by GeekByte** [comment]
@g6ai You can put the contents of .bash_profile in .zshrc, essentially because the environment variables you configured were not found in .zshrc when you started zsh, and .bash_profile is the information that you read when bash started.

**Comment by g6ai** [comment]
@GeekByte I see what you mean now. Though from the discussion above, it's not that trivial.

**Comment by krivonos28** [comment]
looks like you installed nodejs from snap. Try to delete them and install from apt-get.

**Comment by artvi** [comment]
Sometimes `nvm` doesn't load `node` properly, this might help: 

- check if node is available outside of vim: `node --version`
- if it's not found, just run `nvm alias default node_version_you_want_to_use`

**Comment by gregorywaynepower** [comment]
> Sometimes `nvm` doesn't load `node` properly and this might help:
> 
>     * check if node is available outside of **vim**: `node --version`
> 
>     * if it's not found, just run the following command with node version you want to use, for example:
>       `nvm alias default 16.13.1`
> 
>     * restart your terminal

I was able to fix this annoying error without having to edit my .zshrc file. :+1:

**Comment by luobinlin987** [comment]
> Add this to your .vimrc:
> 
> ```
> " https://github.com/neoclide/coc.nvim/issues/856
> if $NVM_BIN != ""
>   let g:coc_node_path = '$NVM_BIN/node'
> endif
> ```
> 
> NVM can't be lazy loaded with this because `NVM_BIN` is unset until nvm is loaded
> 
> I still get a warning message when I open a new shell, but everything works.

works well for me in Gvim

**Comment by brandonsturgeon** [comment]
I wrestled with this for a bit but got fed up.
I remember having to do some stupid hacks to get nvm to load async or lazily literally 5 years ago.

Same problem today.

Decided to swap to https://volta.sh/ and it couldn't have been easier. Completely painless transition.
Literally just:
```
rm -rf $NVM_DIR ~/.npm ~/.bower;
curl https://get.volta.sh | bash;

# (new terminal)

volta install node@18;
```

And that was it! Coc / Copilot loaded without any problems.
The longest part of the process was deleting the existing node versions managed by NVM 🤭


Anyway: tl;dr: nvm isn't worth the hassle. There are many better alternatives out there and swapping takes less than a minute.
Save yourself the time and headache 💅

**Comment by thieleju** [comment]
If someone stumbles across this as a neovim beginner (like me), do this in your init.lua:
```lua
vim.g.coc_node_path = '/path/to/node'
```

**Comment by Abir-Tx** [comment]
I had the exact same problem and also had `let g:coc_node_path = trim(system('which node'))` in my config but still when neovim was launched from the rofi or ranger or else then the error occured. So I am currently solving the problem by softlinking the `nvm` `node` bin to the `/bin` 


```bash
 sudo ln -s ~/.nvm/versions/node/v19.4.0/bin/node /bin/node -v
 ```

**Comment by f0nzie** [comment]
> 
> As mentioned by people above, setting the path by using `let g:coc_node_path = '/path/to/node'` works. However, you must use the full path `/home/xxx/path/to/node`.

Thanks.
This tip fixed it when I was calling `nvim` as an AppImage and a Gnome desktop application, and even installing `node` with _homebrew_ in Fedora Silverblue 40.
```
let g:coc_node_path = '/home/linuxbrew/.linuxbrew/bin/node'
```
