### ISSUE TITLE
CocInstall wait until completion

### ISSUE THREAD

**Issue by budimanjojo** [neoclide/coc.nvim#858]
Hello, I'm trying to write a script that will install all the coc extensions I listed inside the vimrc file. 
In my vimrc, I have something like this:
`
let g:coc_global_extensions = ['coc-json', 'coc-html']
`
This will install the listed extensions whenever I open vim. But now I want to automate the process using a bash script to install them. I do this:
`
vim "+CocInstall - sync" +qall
`
The problem is vim doesn't wait for the command to finish before quiting itself. Maybe because CocInstall command is designed to do installation in the background without waiting it to finish? If so, what is my workaround for this? Thanks.

**Comment by chemzqm** [comment]
You should use `CocInstall -sync`

**Comment by budimanjojo** [comment]
Sorry mistyped. I did use
`CocInstall -sync`
The problem is, it doesn't wait for the command to finish. It just exit me out to the terminal immediately

**Comment by chemzqm** [comment]
You need to specify extension names for this command.

**Comment by juxuny** [comment]
Maybe `vim +'CocInstall -sync coc-json coc-html' +qall` will work well. But it occurs some errors in latest checkout from `https://github.com/neoclide/coc.nvim.git`

```text
Error detected while processing command line..function coc#util#install_extension[4]..coc#rpc#request[4]..<SNR>20_request[34]..command line..function coc#util#install_extension[4]..coc#rpc#request[4]..<SNR>20_request:
line   29:
E605: Exception not caught: Error on "installExtensions" request: call_atomic request error on "nvim_call_function": Vim(return):E28: No such highlight group name: CocListFgCyan on function "call_function"
Press ENTER or type command to continue
```
