### ISSUE TITLE
References are displayed only for the current buffer

### ISSUE THREAD

**Issue by gbcreation** [neoclide/coc.nvim#86]
**Is your feature request related to a problem? Please describe.**

Consider the following JavaScript files:

```javascript

// file main.js

import a from "./lib.js"
a()

// file lib.js

function a() {}
export default a
```

When the text cursor is on the "a" function name at line 1 of lib.js, and the gr mapping is used (`nmap <silent> gr <Plug>(coc-references)`), the cursor jump to the "a" of the same file at line 2. It does not open the quicklist to show that a() is also used at line 2 of file main.js.

**Describe the solution you'd like**
The quicklist should be displayed to show that a() is referenced at line 2 of lib.js and line 2 of main.js

**Comment by chemzqm** [comment]
Looks like you need to upgrade your global/local typescript module, it works as expected for me:

<img width="330" alt="screen shot 2018-09-21 at 9 52 33 pm" src="https://user-images.githubusercontent.com/251450/45885414-f842f480-bde8-11e8-93ce-6ebe6dfa086c.png">

**Comment by gbcreation** [comment]
Indeed, upgrading the typescript module fixes the issue.
Thank you!

**Comment by CharlesConner** [comment]
I'm having the same issue, how did you solve this? I've ran `npm install -g typescript@latest` but it still only works for open buffers.
