### ISSUE TITLE
Single instance of language server for multiple nvim instances

### ISSUE THREAD

**Issue by hexdigest** [neoclide/coc.nvim#861]
**Is your feature request related to a problem? Please describe.**

I have multiple instances of nvim. Every instance has one or more *.go files open which results in having multiple instances of gopls (go language server) running. Some language servers like sourcegraph's go-langserver or gopls consume tons of memory.

**Describe the solution you'd like**
It would be nice if multiple nvim instances would be able to communicate with the single instance of language server.

**Comment by chemzqm** [comment]
There is support socket language server https://github.com/neoclide/coc.nvim/wiki/Language-servers.

I think go-langserver or gopls should be optimized.

**Comment by hexdigest** [comment]
Thanks, @chemzqm !
