### ISSUE TITLE
Is there a way to ignore hover errors when using autocmd?

### ISSUE THREAD

**Issue by comfortablynick** [neoclide/coc.nvim#863]
I use an autocmd to hover on CursorHold:

```vim
autocmd CursorHold * if ! coc#util#has_float() | call CocActionAsync('doHover') | endif
```

I realize that this may be a languageserver problem, but it would be great if there was some way to control what is reported on the client side. I would like to ignore any error messages regarding hover. Other servers also have this issue but they haven't been as annoying as gopls.

## versions

vim version: NVIM v0.4.0-999-g6c96c3b3f
node version: v10.15.3
coc.nvim version: 0.0.69
term: screen-256color
platform: linux

## Messages
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[coc.nvim] Error output from languageserver.golang: Request textDocument/hover failed.
  Code: 0
## Output channel: languageserver.golang

[Info  - 11:16:37 AM] load /path/to/main.go successfully! elapsed time: 0 seconds.
[Info  - 11:16:37 AM] Build info

golang.org/x/tools/cmd/gopls
    golang.org/x/tools@(devel)
    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=

Go info
-------
go version go1.12.5 linux/amd64

GOARCH="amd64"
GOBIN="/home/nick/go/bin"
GOCACHE="/home/nick/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nick/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build132664935=/tmp/go-build -gno-record-gcc-switches"

[Error  - 11:16:38 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:16:41 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:16:42 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:16:43 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:16:44 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:16:49 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:16:51 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:16:51 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:16:54 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:16:55 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:16:55 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:17:04 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:17:05 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:17:13 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:17:19 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0
[Error  - 11:17:22 AM] Request textDocument/hover failed.
  Message: no identifier found
  Code: 0

**Comment by chemzqm** [comment]
Use hover with autocmd is not a good idea.
I would not add option to disable errer message, fork the repo if you want to.

**Comment by comfortablynick** [comment]
Yes, I could always fork any repo at any time but I try to avoid it. The autocmd used to be in the wiki here, but I can't find it now. I guess it's no longer a recommended practice?

This is a great project, it's a shame if the awesome floating windows should only be triggered manually. Is there any way to get hovering, instead of using a keystroke to simulate hovering?

**Comment by chemzqm** [comment]
The language server could be silent with invalid hover position.
There could be mousr hover event.
