### ISSUE TITLE
coc-definition fials with jumpDefinition too many arguments coc#util#jump

### ISSUE THREAD

**Issue by dlants** [neoclide/coc.nvim#866]
## Result from CocInfo
```
## versions

vim version: NVIM v0.3.7
node version: v8.11.1
coc.nvim version: 0.0.69-f1ca182ebe
term: iTerm.app
platform: darwin

## Messages
[coc.nvim] Error on 'jumpDefinition': request error nvim_call_function - Vim:E118: Too many arguments for function: coc#util#jump

## Output channel: prettier


## Output channel: tsserver

[Info  - 15:33:45] Forking TSServer
PATH: ...
[Info  - 15:33:45] Started TSServer
{
  "path": "/Users/dlants/src/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.2.4",
    "version": "3.2.4"
  }
}

## Output channel: tslint
```
## Describe the bug
Using `coc-definition` fails with:

```
[coc.nvim] Error on 'jumpDefinition': request error nvim_call_function - Vim:E118: Too many arguments for function: coc#util#jump
```

## Reproduce the bug
I tried getting a minimal configuration, but I get stuck on configuring nvim to actually do the definition command.

I set up `:CocInstall coc-tsserver`, but I don't see it starting when I open a ts file.

When I try to run the `coc-definition` plug, I get "Definition provider not found for current document". Happy to try to repro with minimal config if I can get some help there.

**Comment by chemzqm** [comment]
It happens because you're using `tag: *` but installed latest master javascript bundle, please configure Plug command according to readme.

**Comment by dlants** [comment]
Ah, that fixed it. For other people's reference, I had a Plug install command that was stale, and updating it to

```
Plug 'neoclide/coc.nvim', {'tag': '*', 'do': './install.sh'}
```

(as in the current readme), and then reinstalling CoC fixed the issue.
