### ISSUE TITLE
Obtain type under cursor

### ISSUE THREAD

**Issue by SamHH** [neoclide/coc.nvim#869]
**Is your feature request related to a problem? Please describe.**
I want to know what type is under the cursor at any given time, either automatically or by pressing a hotkey.

**Describe the solution you'd like**
In VSCode for example you hover and get the type from Intellisense that way - I'm not sure what the Nvim analog to that is. Ideally this information would be exposed in some manner that would allow me to insert it into my status bar, but failing that a hotkey that popped up this info in a manner similar to the diagnostics window would still be helpful.

**Describe alternatives you've considered**
I've looked to see if this already exists, couldn't find it. There's a good chance it exists and I just don't know the correct Vim terminology to find it... my apologies if that's the case :stuck_out_tongue:

**Comment by Avi-D-coder** [comment]
[example-vim-configuration]https://github.com/neoclide/coc.nvim#example-vim-configuration
```vim
" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```

**Comment by T0maas** [comment]
Ok, this works when I press K, but how to make it work on cursor hover?

**Comment by Avi-D-coder** [comment]
> Ok, this works when I press K, but how to make it work on cursor hover?

@T0maas Do you mean mouse cursor or vim normal mode cursor?

**Comment by T0maas** [comment]
I mean the normal cursor

**Comment by T0maas** [comment]
I mean the normal cursor.

**Comment by T0maas** [comment]
For example if I place cursor in normal mode on some variable, after 2sec I want to exec show_documentation().

**Comment by Avi-D-coder** [comment]
@T0maas 

Just replace highlight with hover.
From the readme:
```
" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')
```

**Comment by T0maas** [comment]
@Avi-D-coder
Thanks.
This is also ok:
```
autocmd CursorHold * silent call <SID>show_documentation()
```

**Comment by Arian-p1** [comment]
> ```viml
> 
> ```

I added this but when I use k it opens and closes so fast
I mean it doesn't stay open

**Comment by Arian-p1** [comment]
> ```viml
> 
> ```

I added this but when I use k it opens and closes so fast
I mean it doesn't stay open

**Comment by chemzqm** [comment]
It's already fixed, please upgrade to the latest release branch of coc.nvim.
