### ISSUE TITLE
How should coc-action-openlink be used?

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#873]
I am trying to open links in my browser, but I can't even get echo to work.

This code has no observable effect when called.

```vim
:map <leader>o :call CocActionAsync('openLink', ["!echo test > ~/LOG"])<cr>
```

**Comment by chemzqm** [comment]
`:h coc-action-openlink`

**Comment by Avi-D-coder** [comment]
@chemzqm That's where I'm coming from. There are no examples, and even `echo CocActionAsync('openLink')`  does not seem to ever return `v:false` or edit the file? I was hoping you could shed some light on proper usage. I asked here rather than gitter so it would show up in future searches.

**Comment by chemzqm** [comment]
To get result from CocActionAsync, you have to use callback function as last argument,  it's documented.

**Comment by Avi-D-coder** [comment]
The problem was `Note: it needs language server support documentLink feature to work.`
Thanks for clarifying the docs.

For anyone looking for a more general solution see the [vim wiki](https://vim.fandom.com/wiki/Open_a_web-browser_with_the_URL_in_the_current_line).

On linux `nnoremap <leader>o :silent !xdg-open <C-R>=escape("<C-R><C-F>", "#?&;\|%")<CR><CR><CR>` does the trick nicely.
