### ISSUE TITLE
[BREAK CHANGE] location of javascript bundle will be changed

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#876]
Release branch would contains full code for running coc.nvim, the bundled javascript file location would be changed from `index.js` to `build/index.js`.

Make sure upgrade to master code of coc.nvim before use `./install.sh` or `coc#util#install()` to download latest javascript bundle.

Using release branch to have this plugin just work would be recommended.

**Note** release branch not working for now.

**Comment by budimanjojo** [comment]
I just broke mine. Coc did an auto update on my system, and then now I can not run any Coc command and all the autocompletions are gone. What should I do?

**Comment by chemzqm** [comment]
> Coc did an auto update on my system

How could that happen? It doesn't auto update itself, and I haven't made change to release branch yet.

**Comment by budimanjojo** [comment]
Sorry, I meant auto update extensions, it shows me something like this:
```
:!yarnpkg upgrade --latest --ignore-engines --ignore-scripts

yarn upgrade v1.16.0
warning package.json: No license field
warning No license field
warning No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
warning Ignored scripts due to flag.
success Saved lockfile.
warning No license field
success Saved 431 new dependencies.
```
After that, my Coc is not working anymore

**Comment by chemzqm** [comment]
Please provide result of `:CocInfo`

**Comment by budimanjojo** [comment]
I cannot run any Coc command at all, it shows me `E492: Not an editor command: CocInfo` but Coc is still installed if I do `:PlugStatus`
```
Finished. 0 error(s).
[===============]

- fzf: OK
- ale: OK
- fzf.vim: OK
- vim-snippets: OK
- coc.nvim: OK
- nerdtree: OK
- base16-vim: OK
- nerdtree-git-plugin: OK
- vim-fugitive: OK
- tcomment_vim: OK
- emmet-vim: OK
- vim-airline-themes: OK
- vim-colorschemes: OK
- vim-airline: OK
- vim-easy-align: OK
```

**Comment by chemzqm** [comment]
Are you using release branch with `Plug` command?
You can do that that for now.

**Comment by budimanjojo** [comment]
I'm using this in my vimrc:
`Plug 'neoclide/coc.nvim', {'tag': '*', 'do': './install.sh'}`

**Comment by chemzqm** [comment]
Checkout git branch in folder of coc.nvim, you should have switched to wrong branch which doesn't have plugin folder.

**Comment by budimanjojo** [comment]
I'm in master branch. These are the inside my coc.nvim folder:
```
ls -la ~/.vim/plugged/coc.nvim 
total 352
drwxr-xr-x 12 budiman budiman   4096 Jun 15 17:05 .
drwxr-xr-x 16 budiman budiman   4096 Jun 15 17:04 ..
drwxr-xr-x  4 budiman budiman   4096 Jun 15 17:04 autoload
-rw-r--r--  1 budiman budiman    150 Jun 15 17:04 Backers.md
drwxr-xr-x  2 budiman budiman   4096 Jun 15 17:04 bin
drwxr-xr-x  2 budiman budiman   4096 Jun 15 18:03 build
-rw-r--r--  1 budiman budiman  13757 Jun 15 17:04 CONTRIBUTING.md
drwxr-xr-x  2 budiman budiman   4096 Jun 15 17:04 data
drwxr-xr-x  2 budiman budiman   4096 Jun 15 17:05 doc
drwxr-xr-x  8 budiman budiman   4096 Jun 15 18:04 .git
drwxr-xr-x  3 budiman budiman   4096 Jun 15 17:04 .github
-rw-r--r--  1 budiman budiman    134 Jun 15 17:04 .gitignore
-rw-r--r--  1 budiman budiman  39525 Jun 15 17:04 history.md
-rw-r--r--  1 budiman budiman      4 Jun 15 17:04 .ignore
-rw-r--r--  1 budiman budiman   1157 Jun 15 17:04 install.cmd
-rwxr-xr-x  1 budiman budiman   1484 Jun 15 17:04 install.sh
-rw-r--r--  1 budiman budiman    186 Jun 15 17:04 jest.js
-rw-r--r--  1 budiman budiman   1079 Jun 15 17:04 LICENSE.md
-rw-r--r--  1 budiman budiman    132 Jun 15 17:04 .npmignore
-rw-r--r--  1 budiman budiman   2577 Jun 15 17:05 package.json
drwxr-xr-x  2 budiman budiman   4096 Jun 15 17:04 plugin
-rwxr-xr-x  1 budiman budiman    256 Jun 15 17:05 publish.sh
-rw-r--r--  1 budiman budiman  20646 Jun 15 17:05 Readme.md
-rwxr-xr-x  1 budiman budiman   1516 Jun 15 17:04 release.sh
drwxr-xr-x 14 budiman budiman   4096 Jun 15 17:05 src
-rw-r--r--  1 budiman budiman   1221 Jun 15 17:04 .travis.yml
-rw-r--r--  1 budiman budiman    702 Jun 15 17:04 tsconfig.json
-rw-r--r--  1 budiman budiman    231 Jun 15 17:05 tslint.json
drwxr-xr-x  2 budiman budiman   4096 Jun 15 17:04 .vim
-rw-r--r--  1 budiman budiman    581 Jun 15 17:04 webpack.config.js
-rw-r--r--  1 budiman budiman 166731 Jun 15 17:05 yarn.lock
```
This is so weird. I do have .yarn folder inside ~/.yarn too. Also, this is a fresh install. I have a server that uses coc too and it's working fine.

**Comment by chemzqm** [comment]
The plugin folder is missing, something removed it, download coc.nvim again.

**Comment by budimanjojo** [comment]
The plugin folder is there. You can see it in my previous command, inside `~/.vim/plugged/coc.nvim` folder. I already did reinstall it 3 times using vim-plug by removing the entire ~/.vim folder and reinstall vim-plug and do :PlugInstall inside vim. This is the line inside my vimrc `Plug 'neoclide/coc.nvim', {'tag': '*', 'do': './install.sh'}`. And it installed without error.

**Comment by chemzqm** [comment]
Use `:version` to check your vim version.

**Comment by budimanjojo** [comment]
Sorry I'll check tomorrow, I'm using neovim not vim. I just turned off my work pc which is the one with problem. I'll check my home pc when I arrive at home. But my server is working fine. Maybe I forgot add the latest neovim ppa. I just checked Ubuntu 18.04 still has neovim version 0.2.2-3, maybe that's the one I'm using.

**Comment by chemzqm** [comment]
It only works on neovim >= 0.3.0

**Comment by budimanjojo** [comment]
Maybe that's the problem (I hope). I'm using neovim nighty on all my systems, maybe I forgot to do that in my work pc. Thanks for the fast reply :D
