### ISSUE TITLE
Disable installing yarn. 

### ISSUE THREAD

**Issue by ahmedelgabri** [neoclide/coc.nvim#878]
The `coc#util#yarn_cmd()` check sometimes returns empty & this lead to CoC installing `yarn` which I already have installed using homebrew. I want to be able to skip the `yarn` checks because I know for sure that I will have it.

https://github.com/neoclide/coc.nvim/blob/c8b0d21231abcf56c913fb6991e3da32340b9785/autoload/coc/util.vim#L746-L756

I use [`minpac`](https://github.com/k-takata/minpac) as plugin manager & this is how I run the [update hook](https://github.com/ahmedelgabri/dotfiles/blob/80ae63ebc066f55aae5536341d2e6c7458612226/files/.vim/autoload/plugins.vim#L61-L86) where sometimes it works fine & sometimes not.

I run the update command like this `nvim -c "PlugUpdate"` but if I do it from inside a neovim instance it always works fine `:PlugUpdate`. 

It doesn't seem to be a `$PATH` issues since I have another update hook that runs `yarn` & works fine. https://github.com/ahmedelgabri/dotfiles/blob/80ae63ebc066f55aae5536341d2e6c7458612226/files/.vim/autoload/plugins.vim#L104

**Comment by chemzqm** [comment]
It's removed, but extension install won't work when it doesn't exist.

**Comment by ahmedelgabri** [comment]
> It's removed, but extension install won't work when it doesn't exist.

I'm aware of this, but I don't want checks anywhere. Can I skip this for extensions too?

**Comment by chemzqm** [comment]
> Can I skip this for extensions too?

Skip what? There's no code for install yarn.

**Comment by ahmedelgabri** [comment]
This line installs yarn https://github.com/neoclide/coc.nvim/blob/c8b0d21231abcf56c913fb6991e3da32340b9785/autoload/coc/util.vim#L751

**Comment by chemzqm** [comment]
It's removed from master and release branch.

**Comment by ahmedelgabri** [comment]
Thank you
