### ISSUE TITLE
C++ with clangd does not work if ccls && cquery definitions are present in coc-settings.json.json

### ISSUE THREAD

**Issue by zokrezyl** [neoclide/coc.nvim#879]
## versions                                                                                                              

vim version: NVIM v0.3.4
node version: v10.15.2
coc.nvim version: 0.0.71-fa429d0bbc
term: xterm
platform: linux

## Describe the bug
Added all the three lang servers description for C++ as described on https://github.com/neoclide/coc.nvim/wiki/Language-servers. I intended to try the state of the art one by one by disabling with "enable": false, but it seems that the plugin is picking up the last one. I could activate "clangd" only if I removed the definition of the other two. cquery && ccls)

## Reproduce the bug

Add the three LS's in the following order: clangd, cquery, ccls, set "enabled" to false for "ccls" and "cquery". Expect clangd to get fired (monitored with bcc/execsnoop).

Remove all but clangd definitions. Now clangd will be fired. (Obviously when opening *.cpp/*.c etc.)

**Comment by chemzqm** [comment]
You need restart coc.nvim by `:CocRestart`

**Comment by zokrezyl** [comment]
sorry, was typo... I have "enable" not enabled in my coc-json
```
     "languageserver": {
          "cquery": {
              "enable": false,
              "command": "cquery",
              "args": ["--log-file=/tmp/cq.log"],
              "filetypes": ["c", "cpp"],
              "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"],
              "initializationOptions": {
                  "cacheDirectory": "/tmp/cquery"
              }
          }
      },
     "languageserver": {
          "ccls": {
              "enable": false,
              "command": "ccls",
              "filetypes": ["c", "cpp", "objc", "objcpp"],
              "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
              "initializationOptions": {
                  "cache": {
                      "directory": "/tmp/ccls"
                  }
              }
          }
      },
     "languageserver": {
          "clangd": {
              "enable": true,
              "command": "clangd",
              "rootPatterns": ["compile_commands.json", ".vim/", ".git/", ".hg/"],
              "filetypes": ["c", "cpp", "objc", "objcpp"],
              "args": ["-background-index"]
          }
      }

```

If I declare clangd the last one it works. If I declare the first or second it does not.

**Comment by chemzqm** [comment]
@zokrezyl it's json, you should have only one `"languageserver"` defined.

**Comment by zokrezyl** [comment]
You are right, it's a map/dictionary. Is this then the correct definition? Unfortunately not clear from the schema file. Or it is possible to have only one language server... Which would be a sad limitation


```
"languageserver": {
          "cquery": {
              "enable": false,
              "command": "cquery",
              "args": ["--log-file=/tmp/cq.log"],
              "filetypes": ["c", "cpp"],
              "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"],
              "initializationOptions": {
                  "cacheDirectory": "/tmp/cquery"
              }
          },
          "ccls": {
              "enable": false,
              "command": "ccls",
              "filetypes": ["c", "cpp", "objc", "objcpp"],
              "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
              "initializationOptions": {
                  "cache": {
                      "directory": "/tmp/ccls"
                  }
              }
          },
          "clangd": {
              "enable": true,
              "command": "clangd",
              "rootPatterns": ["compile_commands.json", ".vim/", ".git/", ".hg/"],
              "filetypes": ["c", "cpp", "objc", "objcpp"],
              "args": ["-background-index"]
          }
      }
```

**Comment by chemzqm** [comment]
What limitation? You can't use same key multiple times in json, that's how json works.

**Comment by zokrezyl** [comment]
The statement was "Or it is possible to have only one language server... Which would be a sad limitation"... I was not talking about the limitation of json. I precisely mean that would be sad to have the number of language servers limited to one. 

As mentioned from the documentation this is not clear.

**Comment by chemzqm** [comment]
> I precisely mean that would be sad to have the number of language servers limited to one.

It's a map, you can define as many language servers as you want, and even many language servers for same filetype.

**Comment by gil-air-may** [comment]
Ideally, we would have a `languageServers` array, which would allow multiple language server configs. Then, Coc would run the server according to the file extension.

**Comment by chemzqm** [comment]
> Ideally, we would have a `languageServers` array, which would allow multiple language server configs. Then, Coc would run the server according to the file extension.

Multiple language server is allowed, you have to give them different id, it's a map.
