### ISSUE TITLE
[Feature Request] Symbol Text Objects

### ISSUE THREAD

**Issue by gbcreation** [neoclide/coc.nvim#88]
**Is your feature request related to a problem? Please describe.**

It would be very useful to create new Vim Text Objects based on information returned by Language Servers about symbols found in source code. It could be a single generic text object _s_ (for _symbol)_ that represents any kind of symbols (variable, property, class, function, method...) or multiple text objects that represents specific symbols. For example, _v_ for a variable, _p_ for a property, _f_ for a function, _m_ for a method and so on.

Doing so, it would be possible to use Vim operators on these text objects. For example:
- `das`: delete a symbol under cursor (whatever its kind)
- `vaf`: visual selection of a function under cursor
- `yav`: yank a variable under cursor
- ...

**Describe the solution you'd like**

The [vim-text-object](https://github.com/kana/vim-textobj-user) plugin could be used to define new text objects based on information returned by `getDocumentSymbols()`. Currently, `getDocumentSymbols()` returns only the line and column of the start position of symbols. It would be necessary to also return the line and column of the end position of symbols. Maybe `lnum` and `col` could be renamed to `s_lnum` and `s_col` for the start position, and `e_lnum` and `e_col` could be added for the end position.

**Comment by gbcreation** [comment]
Thank you for your answer.

I understand that the usefulness of those text objects would fully depend on the capacity of the various language servers to return accurate data about the start and the end positions of symbols, and it should be specified in the README file and the help file of coc.nvim.

If those data are not correct, I think that the issue should be reported directly to the concerned language server projects by the users. I don't think coc.nvim should implement workarounds for bad data, as they could work with some versions of the language servers but not future versions. It could be hard to maintain.

I would be glad to help you implementing those text objects once the API will be updated if you wish.

**Comment by chemzqm** [comment]
I've make `documentSymbols` and `workspaceSymbols` request to return `Range` and `selectionRange`, the `Range` should be used for what you proposed. 

The `Range` is optional according to protocol specification and could be incorrect for text object. For example: document symbols from tsserver only contains the range for symbol name.

**Comment by tydra-wang** [comment]
symbol text object provided now?
