### ISSUE TITLE
Info Messages Showing Up when using Ctrl-P

### ISSUE THREAD

**Issue by vito-c** [neoclide/coc.nvim#881]
I'm using Ctrl-P plugin and when there are info messages being returned from coc.nvim it overwrites my typing area.

**Comment by chemzqm** [comment]
Use `  "coc.preferences.messageLevel": "error"` in coc-settings.json

**Comment by chemzqm** [comment]
Or use https://github.com/neoclide/coc-lists which doesn't have this kind of issue.
