### ISSUE TITLE
signature.enable: false not working?

### ISSUE THREAD

**Issue by edgard** [neoclide/coc.nvim#883]
## Result from CocInfo

vim version: NVIM v0.3.7
node version: v11.15.0
coc.nvim version: 0.0.71-4991469f1f
term: st-256color
platform: linux

## Describe the bug

I'm trying to disable 'echo' signature help, but it seems that it's not working. From what I understand, "signature.help": false, should disable it. Right?

## Screenshots (optional)
https://asciinema.org/a/ehpgHl3aqPX1ltO3lEgnl3QNs

**Comment by chemzqm** [comment]
Wrong option name, please read doc or install coc-json.

**Comment by edgard** [comment]
Yeah, sorry, I meant "signature.enable".

Thats the coc-settings.json i have:

```
{
  "coc.preferences.snippets.enable": false,
  "diagnostic.enable": false,
  "signature.enable": false,
  "suggest.preferCompleteThanJumpPlaceholder": true
}
```

**Comment by chemzqm** [comment]
I can't reproduce, it only affected signature help triggered by type character, you may have autocmd which also trigger signature help.

**Comment by chemzqm** [comment]
Read the doc or use neovim with floating window support to get the documentaion.

**Comment by chemzqm** [comment]
Oh, found the bug.

**Comment by edgard** [comment]
Still same result here, I've updated to the last commit (97dad97) and I'm using a mini.vim like this:

```
set nocompatible
set noshowmode
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

**set noshowmode** has to be set in order for the message to appear.

Here: https://asciinema.org/a/AldEoLgaBgFh4LZlRlRCRS4mB

**Comment by chemzqm** [comment]
Maybe you forget to build it or not using latest bundle, use `:CocInfo` to check it.

**Comment by edgard** [comment]
Not sure what I'm doing wrong, trying to build from source:

https://asciinema.org/a/af5acojRb9Nt6eeyJJhQ1pcUM

**Comment by chemzqm** [comment]
Please use release branch.
