### ISSUE TITLE
Add option for hide "Code: XXXXX" errors in cmd

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#884]
### Hello!

- It would be great if you had the option to hide "Code" errors in cmd, as in VSCode, VSCode displays errors only in the LS Output section, so in coc.nvim it would be :CocInfo?

Quite often some servers throw out errors, which in some ways are not necessary (I want to say, the server still works properly, and errors appear). It would be really good if this option is added.

Thanks!

**Comment by chemzqm** [comment]
What language server?

**Comment by chemzqm** [comment]
It could be comes from show message request, try comment out this line : https://github.com/neoclide/coc.nvim/blob/master/src/language-client/client.ts#L3509

**Comment by mihaelartz** [comment]
@chemzqm Works fine, Thanks!
