### ISSUE TITLE
Test if a filetype is handled by a coc source

### ISSUE THREAD

**Issue by pLesur** [neoclide/coc.nvim#885]
Hi,
Many of my coc bindings are mimicking  the default vim behavior (or other usual shortcuts of mine), however those shortcuts do not work anymore if the given file is not supported by any coc provider.

Is it possible to test if the current buffer is handled by a coc provider?
For example, I woudl like to do something like this:
```vimscript
nnoremap <expr> <leader>ff coc#is_handled() ?
    \ ":call CocAction('format')<CR>" : 
    \ "gg=G''"
```

Otherwise, if it doesn't exist, some pointers as to where it should be implemented are welcome :)

**Comment by chemzqm** [comment]
You have to check the return value, `v:false` means not handled.
Function like `coc#is_handled()` would never works, since even if language server declare it has support doesn't always mean it would work.
