### ISSUE TITLE
Organize Imports on save?

### ISSUE THREAD

**Issue by luan** [neoclide/coc.nvim#888]
**Is your feature request related to a problem? Please describe.**
I use coc.nvim for Go and the recommended (and as far as I can tell the only one that works properly) server is a fork of gopls ([here](https://github.com/saibing/tools)). That tool supports `organizeImports` through something other than the `format` action (for now at least?).
I'd like to be able to run the `organizeImports` command on save.

**Describe the solution you'd like**
Either something similar to `coc.preferences.formatOnSaveFiletypes` or a simple way to run the `organizeImport` command that doesn't pollute the screen. More generally, a way to silence commands properly (or to respect `:silent`) would be really nice.

**Describe alternatives you've considered**
I've done:

```viml
" use `:OR` for organize import of current buffer
command! -nargs=0 OR :call CocAction('runCommand', 'editor.action.organizeImport')
autocmd BufWritePre *.go :OR
```

But there's no good way to silence that command, and it will error with `[coc.nvim] Orgnize import action not found.` when there are no actions to be taken, additionally, it always prints out `[coc.nvim] 1 buffers changed.` even when `coc.preferences.messageLevel` is set to error.

**Comment by luan** [comment]
I managed to silence those messages with the config file. `coc#config()` didn't serve to silence those for some reason.

**Comment by chemzqm** [comment]
It's neovim's bug that silent doesn't work for echo during rpc request

**Comment by luan** [comment]
Makes sense, I managed to get around the issue by using the config file. Not sure why `coc#config()` doesn't do it for `coc.preferences.messageLevel`.

I think what's really left of this "request" at this point is maybe a feature equivalent to `codeActionsOnSave` that VSCode has where we could put `organizeImport` instead of setting up our own hooks.

**Comment by chemzqm** [comment]
I tried 
```
  call coc#config('coc.preferences', {
    \ 'messageLevel': 'error',
    \})
```
works as expected.

**Comment by chemzqm** [comment]
>  think what's really left of this "request" at this point is maybe a feature equivalent to codeActionsOnSave that VSCode

Will not add `codeActionsOnSave`, because you can't configure it according to filetype and some extensions already provide some kind of on save support.

Use organize import on save is a bad practice IMO, since it will remove unused import you have just added.

**Comment by luan** [comment]
`call coc#config('coc.preferences.messageLevel', 'error')` did not work for me. I can try your way later on and debug why that's the case.
What about `codeActionsOnSave` is not configurable by filetype? we already have a per file type `languageserver` configuration block, VSCode seems to have a [per-filetype general configuration block as well](https://github.com/golang/go/wiki/gopls#vscode) although I haven't really used it to see how well it works.

As for "bad practice" that's very dependent on language/process. In Go, most of the developers I've seen will use the package before the import line is added, and rely on the `organizeImports` action to add the missing import. Up until `gopls` I've relied solely on `goimports` to do *both* formatting and importing at the same time (this is easily doable through `vim-go`, but that plugin has a few issues with resetting folds when auto formatting). I think this is a common process for Go developers and not *at all* bad practice.

**Comment by chemzqm** [comment]
But there's no per-filetype configuration support with coc.nvim.
It's just my opinion, you can use `BufWritePre` of cause.

**Comment by chemzqm** [comment]
I've created the issue report: https://github.com/neovim/neovim/issues/10310

**Comment by luisdavim** [comment]
How about providing `coc.preferences.organizeImports OnSave` and `coc.preferences.organizeImports OnSaveFiletypes` like we have for `formatOnSave`?

**Comment by chemzqm** [comment]
No, because I think organize import is a bad idea, it might remove import you have just added which is not using.

**Comment by luisdavim** [comment]
I understand that's your opinion @chemzqm but this is pretty common for go developers, for example, I almost never add imports manually and rely on `goimports` or `gopls` to do that for me.
I'm not asking to make it the default, I'm asking to make it available with  `coc.preferences.organizeImports` OnSave and `coc.preferences.organizeImportsOnSaveFiletypes` we can choose to turn it on and specify for which file types to turn it on for.

I think coc should enable developers to choose their workflow.

**Comment by oblitum** [comment]
Isn't it just a simple configuration you can do with `autocmd`? Besides agreeing with @ chemzqm, I think it seems trivial to setup yourself, and too specific of gopls, which should be provided, if ever, in a coc-go extension? If coc.nvim does anything it should do as @ luan suggested, which is to provide a generic `codeActionsOnSave`, then you can put `organizeImports` yourself, but it wouldn't be that much simpler then setting up an autocmd.

**Comment by luisdavim** [comment]
That's a valid point but in that case why is format on save provided and why not use an autocmd for that as well?

**Comment by oblitum** [comment]
Can't state why, but personally I've always viewed formatting as a more general task and command to have, hence many other tools/clients provide it, and not some random action.

**Comment by chemzqm** [comment]
> That's a valid point but in that case why is format on save provided and why not use an autocmd for that as well?

Organize imports have side effect and different extensions could have different code actions names for organize imports. You can use autocmd for format on save as well.

**Comment by ooesili** [comment]
I'm still stuck on this. I'm trying to get the same setup as the original poster where the `organizeImports` action is run on save. I understand that @chemzqm does not personally use this workflow and I'm not here to argue about which workflow is better or which should be supported out of the box by coc.nvim.

However, I cannot find _any_ way at make this setup work with autocmds. The [gopls vim docs](https://github.com/golang/tools/blob/master/gopls/doc/vim.md#cocnvim) recommend using this line
```vim
autocmd BufWritePre *.go :call CocAction('runCommand', 'editor.action.organizeImport')
```
But I get an error message every time I save a go file where the imports are already organized, which is most the time.
```
Error on request (runCommand): Vim(return):Error invoking 'runCommand' on channel 3 (coc):
```
The workaround implement in https://github.com/luan/nvim/commit/14eefca99037b16a36fe0793d33d706a3b237235
 does not work for me, I still see the error message on save when there is nothing to organize.

I saw the issue raised here https://github.com/neovim/neovim/issues/10310 but it is closed and didn't actually result in anything being changed afiak. I'm not a savvy vim plugin author so I apologize that I don't have any suggestions for a solution. I'm happy to raise an issue with rust-analyzer or neovim if this should error should not be happening, but I'm not sure why this error is occurring.

Any help would be greatly appreciated.

**Comment by chemzqm** [comment]
You should not expect organize import does fix import for you, although some LS does fix

**Comment by VasiliyS** [comment]
@ooesili  

If you add silent in front of the 'call' then the error will not be reported but the imports will be created when needed.

so:

`autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')`
and
`command! -nargs=0 OR   :silent call CocAction('runCommand', 'editor.action.organizeImport')`
