### ISSUE TITLE
Error highlighting not updated on file reload with checktime

### ISSUE THREAD

**Issue by gbcreation** [neoclide/coc.nvim#89]
**Describe the bug**
Highlighting of errors is not updated when a file is reloaded by the `:checktime` command.

**To Reproduce**
1. open Neovim to create a new `index.js` file: `nvim index.js`
2. add the following content to the buffer: `window.unknownProperty`. COC reports `[tsserver 2339] [E] Property ''unknownProperty'' does not exist on type ''Window''.` which is correct, and `unknownProperty` is underlined to show the error.
3. run the following Vim command: `:au FocusGained,BufEnter,CursorHold *  checktime %`
4. Modify the index.js file outside of Neovim. For example: `echo "window.alert('test')" > index.js`
5. Return to Neovim. The autocommand should run checktime which detects that file changed on disk, and offers to reload it. Accept by pressing key `L`
6. Neovim reloads the file, but the error highlighting has not been updated. It is still visible and relates to the previous error about `unknownProperty`. The following message is also displayed: `[coc.nvim] Failed to load the ESLint library for the document /home/user/test/index.js`

**Expected behavior**
COC should detect that the file has been reloaded and update symbol diagnostics.

**Comment by chemzqm** [comment]
What's result of `:version` from neovim?
It works as expected in my case, the related diagnostic info is cleared after `:checktime`

**Comment by gbcreation** [comment]
```
:version                                                                                                                                                                                        
NVIM v0.3.1                                                                                                                                                                                     
Build type: Release                                                                                                                                                                             
LuaJIT 2.0.5                                                                                                                                                                                    
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wst
rict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FL
OAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include  
Compilé par builduser                                                                                                                                                                           
                                                                                                                                                                                                
Features: +acl +iconv +jemalloc +tui                                                                                                                                                            
See ":help feature-compile"                                                                                                                                                                     
                                                                                                                                                                                                
         fichier vimrc système : "$VIM/sysinit.vim"                                                                                                                                             
               $VIM par défaut : "/usr/share/nvim"                                                                                                                                              
                                                                                                                                                                                                
Run :checkhealth for more info
```

**Comment by gbcreation** [comment]
Curiously enough, the diagnostic info is cleared if I use `au FocusGained,BufEnter,CursorHold * checktime` instead of `au FocusGained,BufEnter,CursorHold * checktime %`, that is without the `%` character at the end.

**Comment by chemzqm** [comment]
I can reproduce it, it only happens with `autocmd` but not by use command `:checktime %`.
I can't receive any event in this situation, so I think it's a bug of vim/neoivm.

**Comment by gbcreation** [comment]
OK, I'm going to open an issue in Neovim. What kind of events do you expect?

**Comment by chemzqm** [comment]
The `BufReadPost` should be fired like use command `:checktime %`.

**Comment by gbcreation** [comment]
Thank you for opening issues for vim & neovim.

I read the answers. Using `au FocusGained,BufEnter,CursorHold * nested checktime %` fixes the problem.
