### ISSUE TITLE
Can not find tsserver - when tsserver is installed

### ISSUE THREAD

**Issue by Ja-rek** [neoclide/coc.nvim#891]
## Result from CocInfo

 vim version: NVIM v0.4.0-999-g6c96c3b3f
 node version: v11.15.0
 coc.nvim version: 0.0.71
 term: st-256color
 platform: linux

 ### Messages
 [coc.nvim] Bundled typescript module not found
 [coc.nvim] Can not find tsserver, run ':CocInstall coc-tsserver' to fix it!

### CocList extensions
1 * coc-word 1.2.2 ~/.config/coc/extensions/node_modules/coc-word
    2 * coc-tsserver 1.3.8 ~/.config/coc/extensions/node_modules/coc-tsserver
    3 * coc-tslint-plugin 1.0.5 ~/.config/coc/extensions/node_modules/coc-tslint-plugin
    4 * coc-syntax 1.2.3 ~/.config/coc/extensions/node_modules/coc-syntax
    5 * coc-snippets 2.1.0 ~/.config/coc/extensions/node_modules/coc-snippets
    6 * coc-omni 1.2.2 ~/.config/coc/extensions/node_modules/coc-omni
    7 + coc-vimlsp 0.1.9 ~/.config/coc/extensions/node_modules/coc-vimlsp
    8 + coc-json 1.2.1 ~/.config/coc/extensions/node_modules/coc-json
    9 + coc-html 1.2.1 ~/.config/coc/extensions/node_modules/coc-html
   10 + coc-css 1.2.1 ~/.config/coc/extensions/node_modules/coc-css

I always see the warning ``coc.nvim] Can not find tsserver, run ':Coc Install coc-tsserver' to fix it!`` and some functionality doesn't work.

**Comment by chemzqm** [comment]
Fixed on coc-tsserver 1.3.9.

**Comment by Ja-rek** [comment]
Thx.

**Comment by tvallois** [comment]
Hello,

Don't know if it's related but i've an error Skipped extension "path_to_tscserver", please uninstall "coc-tsserver" by :Cocunstall coc-tsserver. The other autocompletion tools are working fine.

**Comment by chemzqm** [comment]
It's not related, you need remove "path_to_tscserver" from you `&rtp` when you have coc-tsserver installed by `:CocInstall`
