### ISSUE TITLE
Jump to next error - and ignore warnings

### ISSUE THREAD

**Issue by andys8** [neoclide/coc.nvim#893]
**Is your feature request related to a problem? Please describe.**
If there are several warning but one error, I'd want `coc-diagnostic-next` to jump to the **error**.

**Describe the solution you'd like**
Either change the jump order depending on the level (warning vs error) or add a separate command `coc-diagnostic-next-error`.

**Describe alternatives you've considered**
`w0rp/ale` supports this.

```
  <Plug>(ale_previous) - ALEPrevious
  <Plug>(ale_previous_wrap) - ALEPreviousWrap
  <Plug>(ale_previous_error) - ALEPrevious -error
  <Plug>(ale_previous_wrap_error) - ALEPrevious -wrap -error
  <Plug>(ale_previous_warning) - ALEPrevious -warning
  <Plug>(ale_previous_wrap_warning) - ALEPrevious -wrap -warning
  <Plug>(ale_next) - ALENext
  <Plug>(ale_next_wrap) - ALENextWrap
  <Plug>(ale_next_error) - ALENext -error
  <Plug>(ale_next_wrap_error) - ALENext -wrap -error
  <Plug>(ale_next_warning) - ALENext -warning
  <Plug>(ale_next_wrap_warning) - ALENext -wrap -warning
```
https://github.com/w0rp/ale/blob/9ad8fd6a1bdff5f0c80cf921df5628d1d322cf82/doc/ale.txt#L2507-L2519

**Comment by chemzqm** [comment]
`:h coc-diagnostic-prev`, there's also example in Readme.

**Comment by andys8** [comment]
@chemzqm Is there maybe a misunderstanding? I updated the headline. Ale supports options to navigate to error's directly and ignoring warnings. I can't see anything related in the README or help for `coc-diagnostic-prev`/`coc-diagnostic-next`

**Comment by andys8** [comment]
Thanks @chemzqm :)
