### ISSUE TITLE
Install instructions for NeoBundle

### ISSUE THREAD

**Issue by HaleTom** [neoclide/coc.nvim#894]
For other Googlers:

Following the install instructions given, (ie using `release` branch) with Neobundle:

`NeoBundle 'neoclide/coc.nvim', 'release'`

When I start neovim, I see:

`[coc.nvim] compiled javascript file not found!`

----

Workaround:

```
let $coc_install = fnamemodify($VIM, ":t") . ' -e -c "silent call coc#util#install() | qall!"'
NeoBundle 'neoclide/coc.nvim', 'release', { 'build': { 'others': $coc_install } }
```

This is ugly as it runs another (n)vim instance just to call the install function. I don't know how to tell NeoBundle to run a non-shell command.

But it works.

I'm a VimL noob, improvements welcome.

**Comment by chemzqm** [comment]
It's NeoBundle's issue of something else, it should just work if you're using release branch.

**Comment by chemzqm** [comment]
I think it doesn't have branch support but only revision of master branch, so you're not using release branch.

**Comment by HaleTom** [comment]
`git branch` says:

`* (HEAD detached at v0.0.71)`

Doesn't this mean I'm on `release` branch?

**Comment by chemzqm** [comment]
No, it's master, you should use `git checkout release`

**Comment by HaleTom** [comment]
Thank you for your excellent responsiveness! 

To actually get `release` checked out, I did:

`NeoBundle 'neoclide/coc.nvim', 'release', { 'build': { 'others': 'git checkout release' } }`

Then all worked fine.

I raised the issue with NeoBundle at: [Checkout branch not tag #530](https://github.com/Shougo/neobundle.vim/issues/530)
