### ISSUE TITLE
Window appearance of Coc-nvim with Neovim-QT

### ISSUE THREAD

**Issue by hartigann** [neoclide/coc.nvim#903]
Hello, my autocomplete window currently looks like this - https://imgur.com/9sunjty. Is it possible to change the formatting to match the colorscheme, or at least help it blend in more?

I've tried changing colorschemes/init.vim settings/other plugins to no avail. I'm using the clangd language server and neovim-qt GUI. My CocConfig only contains the clangd example settings from the readme. I am on Windows 10.

Help/directions to the right documentation would be appreciated. Thanks.

**Comment by voldikss** [comment]
Turn off the GUI popup menu in NvimQt
```
GuiPopupmenu 0
```

**Comment by chemzqm** [comment]
It's issue of neovim-qt.
