### ISSUE TITLE
Error on load snippets: EACCES: permission denied, open '/tmp/coc-ultisnips.py'

### ISSUE THREAD

**Issue by uzvermode** [neoclide/coc.nvim#904]
## Result from CocInfo

vim version: NVIM v0.3.7
node version: v11.15.0
coc.nvim version: 0.0.71
term: xterm-256color
platform: linux

## Describe the bug

Getting error message on file opening:
`[coc.nvim] Error on load snippets: EACCES: permission denied, open '/tmp/coc-ultisnips.py'`

## Reproduce the bug

1. Clean /tmp from coc files
2. Open any file with sudo
`-rw-r--r--  1 root  root  7927 Jun 23 08:04  coc-ultisnips.py`
3. Open any file with your regular user and getting error message

Getting same error message when opening first with regular user and then with sudo
`-rw-r--r--  1 coder users 7927 Jun 23 08:08  coc-ultisnips.py`

**Comment by chemzqm** [comment]
Fixed on latest coc-snippets extension.
