### ISSUE TITLE
Configurable filter for workspace symbols

### ISSUE THREAD

**Issue by darsto** [neoclide/coc.nvim#906]
Hi! First of all, thank you for making this plugin - I really like it. I'm trying to set it up for C development and I stumbled upon some problems. I was able to tweak coc.nvim for my needs, but I lack javascript skills to upstream any changes.

I was surprised to see that `CocList -I symbols` doesn't show any global variables, e.g.:
```c
static struct my_struct g_my_global;
```

I'm using ccls as the LSP server and I see this symbol sent over the socket, but coc.nvim filters it out for some reason.

Apparently SymbolKind.Variable is not a "validWorkspaceSymbol":
https://github.com/neoclide/coc.nvim/blob/a2098b819cdcd11e3b0ef4451cc56e403c4ce73e/src/list/source/symbols.ts#L79-L91

Is there any specific reason for not allowing it?

I can see some other symbols filtered out as well - e.g. SymbolKind.Struct. Was it overlooked? Would it better to explicitly specify which symbols should be excluded (like File)? I think it's always better to print more rather than less.

Another idea is to allow users to specify which symbols should be shown. Maybe via CocList parameter, so that users could say "show me functions only".

Thanks,
D.

**Comment by iamcco** [comment]
You have to type charactres to show symbols.
