### ISSUE TITLE
Allow whitespaces in `triggerCharacters`

### ISSUE THREAD

**Issue by darsto** [neoclide/coc.nvim#907]
Let's assume I'm typing the following:
```c
rc = my_function(some_argument,
```

At this point I have the signature popup visible and everything is perfect, but after I insert a whitespace after the last comma, the signature window goes away. My goal was just to separate subsequent arguments with a whitespace and I would expect the signature to be visible while I'm still thinking what to type. In fact, I'm used to typing that whitespace immediately after the comma, which right now makes me almost never see the signature.

There is a `triggerCharacters` setting which I could put a whitespace into, but coc.nvim ignores all whitespaces in there:

https://github.com/neoclide/coc.nvim/blob/b592841b7221eb45f8f83cdcacc82c701440d260/src/provider/signatureManager.ts#L9-L10

String " " gets evaluated into ["", ""] (two empty strings)

Could we allow whitespaces in there, somehow?

Thanks,
D.

**Comment by chemzqm** [comment]
Will not support, while space can't be trigger character of signature help, you can enable formatOnType feature to avoid type whitespace.

**Comment by oblitum** [comment]
@darsto while personally I'm not moving back to YCM, [it's set to support this much better than coc.nvim](https://github.com/Valloric/YouCompleteMe/pull/3412). I think it goes beyond regex and implements one recommendation to ignore whitespace after triggers, both horizontal and vertical, making triggers whitespace agnostic, you may check what they're doing in [these gifs](https://github.com/Valloric/YouCompleteMe/issues/234#issuecomment-500130951). As can be seen they may also support better [signatureHelp for languages with overloads than coc](https://github.com/neoclide/coc.nvim/issues/305). So if this is a must for you, you may experiment with their pull.

**Comment by chemzqm** [comment]
It's feature to autoclose the popup on character type or timeout, since that's how signature help works in VSCode and I like it.

**Comment by chemzqm** [comment]
I've add `signature.floatTimeout`, you may want to change it to higher value.

**Comment by oblitum** [comment]
@chemzqm I've increased my `signature.floatTimeout` to `10000` but it's not having any effect.

**Comment by oblitum** [comment]
@chemzqm I think it's due to value being passed optional parameter here?

https://github.com/neoclide/coc.nvim/blob/3cd87976f91e9d2f700790706902d7f6fe7fd64d/src/model/floatFactory.ts#L37
