### ISSUE TITLE
Use local project configs

### ISSUE THREAD

**Issue by aareman** [neoclide/coc.nvim#909]
**Is your feature request related to a problem? Please describe.**
To add project based config files. 

**Describe the solution you'd like**
for example, In one project i want prettier to format on save, in another (legacy project where things could break) i want it to not do anything. so just to have a coc-settings.json in a project that overrides the global configs. maybe in a .vim folder in the root of the project.

**Describe alternatives you've considered**
I have none currently and couldn't find out how to get this working if it does exist already.

**Comment by iamcco** [comment]
https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file#configuration-file-resolve

**Comment by chemzqm** [comment]
It's supported, add `.vim/coc-settings.json` to your project root or parent folder of project root.

**Comment by aareman** [comment]
I have .vim/coc-settings.json in my project root.

inside it has 

```json
{
    "coc.preferences.formatOnSaveFiletypes": ["javascript", "javascriptreact", "css"]
}
```

i also have coc-prettier installed. And a prettierrc in the project root as well.

When i put that config in my global config `CocConfig` it works.

![image](https://user-images.githubusercontent.com/10500823/60104384-5bbed180-972f-11e9-9f1e-96321e8e2801.png)
