### ISSUE TITLE
Add support for TabNine

### ISSUE THREAD

**Issue by marekdedic** [neoclide/coc.nvim#910]
**Is your feature request related to a problem? Please describe.**
Add support for using TabNine together with CoC.

**Describe the solution you'd like**
Support TabNine as another completion source.

**Describe alternatives you've considered**
Using deoplete instead of CoC :D

**Additional context**
zxqfl/TabNine#71

**Comment by chemzqm** [comment]
There is https://github.com/neoclide/coc-tabnine now.

**Comment by marekdedic** [comment]
Thank you very much, I've tried it and it works perfectly.

**Comment by chasote** [comment]
Hmmm, the autocompletion works fine but I no longer see the documentation for things with the floating windows as I tab through the autosuggestion options. Are you experiencing the same @marekdedic or do you not use that functionality?

**Comment by chemzqm** [comment]
tabnine have to use it's own language server, so you need follow it's documentation to enable semantic  completion.

**Comment by marekdedic** [comment]
Hi, I can't confirm or not confirm the issue right now, I am going offline for 2 weeks.

**Comment by marekdedic** [comment]
Hi, I don't use the documentation feature. @chemzqm I think the issue reported by @chasote is not that there is no documentation for TabNine, but rather that documentation for other completion sources stopped working after adding TabNine.

**Comment by chemzqm** [comment]
It was fixed.
