### ISSUE TITLE
[BREAK CHANGE] Use npm instead of yarn for extensions

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#916]
Like VSCode, most extensions have been bundled by webpack, so no need for install dependencies most of the time.

New logic will make `node_modules` contains extension's folder only, which means extensions works independently.

Yarn is not required for coc extensions, `npm` or `yarn` in $PATH will work by default, or use `"npm.binPath"` configuration for configure the path of npm or yarn.

Functions `coc#util#yarn_cmd` and `coc#util#build` are removed.

No change with commands.

**Comment by chemzqm** [comment]
**Update** when npm not found in $PATH, it will use yarn.

**Comment by cvlmtg** [comment]
Hi, since npm is full of bugs I'd like to continue using yarn, but if I change `npm.binPath` it doesn't work. I've tried to set it to "yarn" and to the full path of yarn, but I keep getting the same error:

<img width="646" alt="Schermata 2019-06-29 alle 07 40 36" src="https://user-images.githubusercontent.com/6401008/60380191-93848c80-9a41-11e9-8cb9-d1df5f1ff04e.png">

So I decided to try to reinstall extensions from scratch. I erased `~/.config/coc` and run `:CocInstall  coc-eslint` but it doesn't work:

<img width="652" alt="Schermata 2019-06-29 alle 07 44 42" src="https://user-images.githubusercontent.com/6401008/60380204-ca5aa280-9a41-11e9-9e28-38f132c5df3f.png">

**Comment by chemzqm** [comment]
@cvlmtg should be fixed on master.

**Comment by cvlmtg** [comment]
yes it works now, thanks

**Comment by mnrce** [comment]
I get these errors when running `:CocUpdate`, is this normal?

![image](https://user-images.githubusercontent.com/13317164/60502992-04010700-9ce9-11e9-97f7-723ae06efa18.png)

**Comment by chemzqm** [comment]
@mnrce looks like you have a broken npm in your $PATH which doesn't support `npm view`

**Comment by mnrce** [comment]
@chemzqm I can run the command normally in shell:
![image](https://user-images.githubusercontent.com/13317164/60504038-09f7e780-9ceb-11e9-9293-e977ee1c6b91.png)

**Comment by chemzqm** [comment]
No idea, possible network error.

**Comment by hamza0867** [comment]
Hi @chemzqm  when I use yarn I get the error:

`[coc.nvim] Install https://github.com/andys8/vscode-jest-snippets.git#master error: exited with 1
Error: Command failed: /home/hamza/.yarn/bin/yarn install https://github.com/andys8/vscode-jest-snippets.git#master --global-style --ignore-scripts --no-bin-links --no-package-lock --production --no-audit
warning package.json: No license field`

`error install has been replaced with add to add new dependencies. Run "yarn add https://github.com/andys8/vscode-jest-snippets.git#master" instead.
warning package.json: No license field`

`error install has been replaced with add to add new dependencies. Run "yarn add https://github.com/andys8/vscode-jest-snippets.git#master" instead.`

I only get the error when trying to install a github repo directly.

It works as expected when installing something like coc-css, coc-vetur ... etc

**Comment by chemzqm** [comment]
@hamza0867 you have to upgrade to latest release branch and use `https://github.com/andys8/vscode-jest-snippets` as extension id.

**Comment by hamza0867** [comment]
@chemzqm Thank you so much man for everything you are giving this community <3

**Comment by mnrce** [comment]
> No idea, possible network error.

I tested on my home and work network though, still got same error.

> Consider use yarn instead.

I can't update or install new coc extension anymore even after having switched to yarn:
![image](https://user-images.githubusercontent.com/13317164/61105055-e4b16900-a4a2-11e9-8c34-a95d9e0335f4.png)

I can run the command normally in shell: 
![image](https://user-images.githubusercontent.com/13317164/61105073-f98dfc80-a4a2-11e9-86ad-5432a5534502.png)

I will test on my other machine next week.

**Comment by chemzqm** [comment]
@mnrce looks resolved yarn is wrong, try use `yarnpkg` as `"npm.binPath"`

**Comment by mnrce** [comment]
> @mnrce looks resolved yarn is wrong, try use `yarnpkg` as `"npm.binPath"`

![image](https://user-images.githubusercontent.com/13317164/61114072-c30fac00-a4b9-11e9-8bfb-371ed9bdaba7.png)
I still get that error. Is there any way I can debug this? I never debug js code before.

**Comment by chemzqm** [comment]
It's not bug of javascript I think, it's bug of your yarn command, you can use npm or cnpm instead.

**Comment by mnrce** [comment]
> It's not bug of javascript I think, it's bug of your yarn command, you can use `npm` or `cnpm` instead.

I also got error when using `npm` as [commented before](https://github.com/neoclide/coc.nvim/issues/916#issuecomment-507604355), that's why I'm testing `yarn`.

**Comment by chemzqm** [comment]
What is `/snap/bin/npm` on your system?

**Comment by mnrce** [comment]
> What is `/snap/bin/npm` on your system?

it's the `npm` come with [`node` snap package](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions-2)

But I don't think this is a snap issue though. IIRC, my archlinux home laptop also gets this error (`node` is installed via pacman), I don't have that laptop with me now so I can't check.

**Comment by chemzqm** [comment]
Try create javascript file:
``` javascript
const { exec } = require('child_process');
exec('yarn info coc-tabnine engines.coc --json', (err, stdout, stderr) => {
  if (err) {
    console.error(err);
    return;
  }
  console.log(stdout);
});
```
run it by `node tmp.js`

**Comment by mnrce** [comment]
> Try create javascript file:
> 
> ```js
> const { exec } = require('child_process');
> exec('yarn info coc-tabnine engines.coc --json', (err, stdout, stderr) => {
>   if (err) {
>     console.error(err);
>     return;
>   }
>   console.log(stdout);
> });
> ```
> 
> run it by `node tmp.js`

I got this error:
![image](https://user-images.githubusercontent.com/13317164/61120062-49ca8600-a4c6-11e9-8fcd-61579c99a42a.png)

The error doesn't look useful to me.

**Comment by chemzqm** [comment]
That's what got with node, it means node can't run that command by use default shell `/bin/sh`, try use full path of yarn or add `shell` option to `exec` to see if it helps.

**Comment by chemzqm** [comment]
Another possible reason is node doesn't have network access, so it won't work for send network request.

**Comment by rollschild** [comment]
Hi, I noticed this issue right after I found out my Coc was behaving weird. 

I did a `PluginUpdate` on my `Vundle` and nothing special occurred. Then I started working but noticed somehow code **auto-completion** stopped working, so I started troubleshooting.

I did a `:CocUpdate` but nothing happened. No errors, nothing. I tried to uninstall `coc-tsserver` but got the following: `[coc.nvim] Error on 'uninstallExtension': request error nvim_call_function - Vim:E117: Unknown function: coc#util#yarn_cmd`.
 
I tried `CocInstall coc-tsserver` but nothing happened either.

Screenshot of `CocInfo` is here:
![Screenshot 2019-07-15 13 50 09](https://user-images.githubusercontent.com/6456628/61240815-b8e2ed00-a707-11e9-8ccb-e7bb72645ab0.png)

and also `CocOpenLog`
![Screenshot 2019-07-15 13 59 21](https://user-images.githubusercontent.com/6456628/61241247-cb115b00-a708-11e9-947f-820f3d3bd823.png)

So I'm a bit confused about this issue. The breaking change definitely has something to do with `yarn` but as an end user I should not change anything. But how exactly do I eliminate this error? Please help! I do have both `npm` and `yarn` and explicitly setting `npm.binPath` in `CocConfig` did not seem to help.

Please help. Thanks a lot.

**Comment by chemzqm** [comment]
Sorry we don't have any support for vundle, which is not maintained for years.
The function `coc#util#yarn_cmd` is totally removed, so I have no idea how it gets called.

**Comment by rollschild** [comment]
> The function `coc#util#yarn_cmd` is totally removed, so I have no idea how it gets called.

That's exactly what I was confused about. But I've switched to `vim-plug` and everything is working fine right now. Thanks for the explanation.
