### ISSUE TITLE
Floating window support CocList

### ISSUE THREAD

**Issue by rcarriga** [neoclide/coc.nvim#926]
I find it quite distracting when typing into a list window and the window changes size. This causes other windows to resize and so then the text jumps around a lot.

It would be fantastic if you could open a floating window for the list to enter in your query, similar to how denite allows.

Obviously I know I could use denite but as you say it is slower and I'd also like to not use two different plugins when does the job great.

Thank you so much for all your hard work by the way!

**Comment by chemzqm** [comment]
Floating window can't have statusline, have to use another floating window for input, and hard to implement auto preview feature.
It's not an option for CocList, but there will be floating list works on floating window only.
