### ISSUE TITLE
Install failed on Windows with release branch

### ISSUE THREAD

**Issue by rickywu** [neoclide/coc.nvim#939]
`Plug 'neoclide/coc.nvim', {'branch': 'release', 'do': { -> coc#util#install()}}
`

After run :PlugInstall got this error

> C:\Windows\system32\cmd.exe /c (install.cmd nightly)
> install.cmd not found

:CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 30 2019 22:01:56)
node version: v10.16.0
coc.nvim version: 0.0.72-ede278185a
term: undefined
platform: win32

```

**Comment by chemzqm** [comment]
You don't need ` coc#util#install` with release branch.

**Comment by rickywu** [comment]
@chemzqm How to verify install OK, 
I use Plug 'neoclide/coc.nvim', {'branch': 'release'} no errors but :CocConfig open blank config file and complete not work

**Comment by chemzqm** [comment]
Use `:CocInfo`
