### ISSUE TITLE
trigger code format when typing

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#94]
**Describe the bug**
trigger format when editing

**To Reproduce**

test.js:
```
function test() {
return 0$
}
```
`$` is the cursor，when type `;` the cod format to:

```
function test() {
  retur$n 0;
}
```
`$` is the cursor.

**Expected behavior**

doesn't trigger code format when it's in insert mode.

**Screenshots**
screen record: https://asciinema.org/a/CEOGeAZgPEP0VPlEahLEWSihT

**Comment by chemzqm** [comment]
It's expected behavior, coc just need to adjust cursor position like VSCode.
