### ISSUE TITLE
Better commit messages in release branch

### ISSUE THREAD

**Issue by ruifm** [neoclide/coc.nvim#942]
**Is your feature request related to a problem? Please describe.**
Ever since I followed README's recommendation to use the release branch due to master instability, I get a little bit frustrated with its commit messages.

I use vim-plug as my plugin manager, and one of its amazing features is that it shows commit messages when updating plugins with :PlugUpdate. For me, those commit messages are very important since it allows me to be informed about outstanding bug fixes, new features, breaking changes and documentation updates.

Release branch commit messages just refer to a particular commit hash and are not very useful like the ones in master.

**Describe the solution you'd like**
I would like for the commit branch to either have the same commit messages as master (for example by rebasing instead of merging) or even higher quality ones that would resemble a changelog.

**Describe alternatives you've considered**
I have considered:

* going back to the master branch but I had some problems with instability in the past
* visiting coc.nvim's github page to check for master's commit messages once a week. That is not an ideal solution because it involves manual work and we are in the age of automation. Hence this feature request.

**Additional context**
I do not want this to sound picky or make it seem like most of the user base are spoiled brats who cannot appreciate quality free work. I love coc.nvim, use it every day and could not live without it. Thank you for your outstanding work!

**Comment by chemzqm** [comment]
You can compile from master, it's also easier to debug.

**Comment by ruifm** [comment]
> You can compile from master, it's also easier to debug.

I'm not following, how does that address the issue?

**Comment by ruifm** [comment]
Thanks @chemzqm, much appreciated!

**Comment by smhc** [comment]
I'd also really like to see this - compiling from master isn't an ideal solution for me as I re-install the plugin frequently in new containers and don't want the dependencies and lag. Having the release branch contain readable 'release notes' seems like a reasonable ask - it previously did. Would be good to see a solution to this some day.
