### ISSUE TITLE
Terminal cursor is messed up

### ISSUE THREAD

**Issue by VincentCordobes** [neoclide/coc.nvim#943]
## Describe the bug

It looks like 2124281 is messing up with the terminal cursor.
I am using iterm2 and neovim v0.4.0-dev

## Reproduce the bug

Open any cocList

## Screenshots (optional)

**Before:**
![Screenshot 2019-07-04 at 18 01 43](https://user-images.githubusercontent.com/7091110/60678883-2b410b00-9e86-11e9-9fd0-4d8fdc433bde.png)

**After:**
![Screenshot 2019-07-04 at 18 02 02](https://user-images.githubusercontent.com/7091110/60678893-385dfa00-9e86-11e9-900d-33235623c2b3.png)

**Comment by chemzqm** [comment]
Checkout https://github.com/neovim/neovim/issues/3688
The cursor should be restored by https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/list.vim#L170, but I don't know what happened with your vim.

**Comment by VincentCordobes** [comment]
@chemzqm I have set `set guicursor=    ` to tell neovim not to change the cursor type in insert mode like suggested in neovim's wiki.

Is there another solution than just sticking to commit `2124281^`?
Btw why changing that behaviour in 2124281?
