### ISSUE TITLE
g:coc_global_extensions doesn't seem to install if no existing extensions

### ISSUE THREAD

**Issue by morgsmccauley** [neoclide/coc.nvim#945]
## Result from CocInfo

vim version: NVIM v0.4.0-dev
node version: v10.5.0
coc.nvim version: 0.0.72-f7cd062403
term: iTerm.app
platform: darwin

## Describe the bug

Extensions are not installed if none exist. If I have no extensions, and I have `g:coc_global_extensions` defined, the extensions are not installed.
However the extensions are installed if I already have other extensions installed.

## Reproduce the bug

1. Remove `node_modules` from `coc/extensions`
2. Clear `package.json` dependencies from `coc/extensions/`
3. Make sure `g:coc_global_extensions` is defined
4. Open neovim

Current Behaviour:
* No extensions are installed
* If I manually install an extension, then all other missing extensions in `g:coc_global_extensions` are installed automatically

Expected behaviour:
* Extensions are installed automatically regardless of current extensions state ?

**Comment by morgsmccauley** [comment]
I have a suspicion that this is to do with `node_modules` not being defined.. 
https://github.com/neoclide/coc.nvim/blob/14d1a129af950a8bb4b1c0ea2c9363d0dec2ebd0/src/extensions.ts#L161-L173
I'll dig a little deeper and try raise a PR for this :)

**Comment by dkwl93** [comment]
Solid Issue guys!
