### ISSUE TITLE
Unknown function: coc#terminal#start in coc.nvim version: 0.0.72-eed5413bc6

### ISSUE THREAD

**Issue by corbob** [neoclide/coc.nvim#949]
## Result from CocInfo

First computer:
```
vim version: NVIM v0.3.7
node version: v12.4.0
coc.nvim version: 0.0.72-eed5413bc6
term: undefined
platform: win32
```
Second computer:
```
vim version: NVIM v0.3.8
node version: v12.6.0
coc.nvim version: 0.0.72-eed5413bc6
term: undefined
platform: win32
```

## Describe the bug

Using [coc-powershell](https://github.com/yatli/coc-powershell) under coc.nvim 0.0.72-ede278185a on the first computer, the PowerShell Integrated Console loaded just fine. Attempted to work on the extension on the second computer and ran into issues, realized was on coc.nvim 0.0.71, so updated to latest (0.0.72-eed5413bc6) and then started getting error about coc#terminal#start being unknown. Tested back on original system, it was working. Updated coc.nvim only on that system and started getting the error.

## Reproduce the bug

**Note**, you will need PowerShell installed on the system if it is not Windows.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  filetype plugin indent on
  syntax on
  set hidden
  source c:/Users/corbob/repos/configs/nvim/autoload/plug.vim
  let s:this_dir = expand('<sfile>:p:h')
  call plug#begin(s:this_dir.'/plugins')
  Plug 'neoclide/coc.nvim', {'tag':'*','do':{-> coc#util#install()}}
  " vim-polyglot is used to easily switch language mode to PowerShell. You likely don't need this, but it works nicely for me.
  Plug 'sheerun/vim-polyglot'
  call plug#end()

  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Do `:CocInstall coc-powershell`

- Close (neo)vim (or activate the extension, but the `CocList` menu appears that it broke today on master)

- Start  (neo)vim with command: `vim -u mini.vim test.ps1` (give it up to a minute or so to download PowerShell Editor Services)

Error along bottom of screen:
`[coc.nvim] Error on active extension coc-powershell: Error: ...all_function - Vim:E117: Unknown function: coc#terminal#start`

@yatli or @TylerLeonhardt can hopefully provide further details as to how the terminal is trying to be called.

**Comment by chemzqm** [comment]
Plug 'neoclide/coc.nvim', {'tag':'*','do':{-> coc#util#install()}}

it's buggy because you're using tagged vim code with lastest javascript, please follow readme.

**Comment by corbob** [comment]
So using this mini.vim:

```vim
  set nocompatible
  filetype plugin indent on
  syntax on
  set hidden
  source c:/Users/corbob/repos/configs/nvim/autoload/plug.vim
  let s:this_dir = expand('<sfile>:p:h')
  call plug#begin(s:this_dir.'/plugins')
  Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
  Plug 'sheerun/vim-polyglot'
  call plug#end()
```

I get `[coc.nvim] Error on active extension coc-powershell: TypeError: this.consoleTerminal.processId.then is not a function`. I believe this is (partly) why we were using the tagged one to download nightly.

**Comment by chemzqm** [comment]
The processId was changed to `number` from `Promise<number>`, should works if you use `await` instead of then method.
I've changed it back.
