### ISSUE TITLE
[New extension request] Support for `texLab` for latex code

### ISSUE THREAD

**Issue by krishnakumarg1984** [neoclide/coc.nvim#952]
The [texlab](https://github.com/latex-lsp/texlab) language server is now ready, having being fully re-written in `rust`. 

Can `coc.nvim` please provide an extension to support this? This is a continuation of #730

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/wiki/Language-servers#latex

**Comment by oblitum** [comment]
@krishnakumarg1984, the wiki section pointed by @fannheyward should be now outdated according to your information. If the rust rewrite is now ready and can replace the java one could you please update the wiki?

**Comment by oblitum** [comment]
I also agree that a texlab extension would be great to have, though there's a coc-vimtex extension that's great already, so I'm not sure about having an alternative extension for latex, or merging the idea into a single coc-tex extension putting texlab and vimtex under the same belt.

**Comment by fannheyward** [comment]
@krishnakumarg1984 I just make a fork of texlab-vscode for coc.nvim, https://github.com/fannheyward/coc-texlab, give it a try.

I'm not a long-term user of LaTex, so maybe there is something wrong or features missing, you can post an issue for that.

**Comment by rudrab** [comment]
I don't think, there is much to do, except updating the readme.
```
     \     'latex': {
      \       'command': '/usr/local/bin/texlab',
      \       'ignoredRootPaths':['~'],
      \       'filetypes': ['tex', 'bib', 'plaintex', 'context'],
      \     },
```
This, as `g:coc_usr_config` is working for me. 

I am in vim8 thiugh.

**Comment by oblitum** [comment]
@rudrab ok, thanks, I'll update.

**Comment by fannheyward** [comment]
`coc-texlab` has ported _almost_ full features of vscode-texlab:

Commands:

- `latex.Build`, build current file
- `latex.ForwardSearch`, PDF preview

Configuration:

- `latex.build.executable`
- `latex.build.args`
- `latex.build.onSave`
- `latex.forwardSearch.executable`
- `latex.forwardSearch.args`
- `latex.lint.onSave`
- `latex.lint.onChange`

**Comment by oblitum** [comment]
Thanks for that @fannheyward, I guess this issue can be closed now :)
