### ISSUE TITLE
coc-rename can't change all code file in a same project for golang

### ISSUE THREAD

**Issue by vacheli** [neoclide/coc.nvim#954]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vacheli** [comment]
Require describe
------------------------
  coc-rename just only work in the same file.Other code in the other directory don't be changed.

CocInfo follow as:
-------------------------
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 20 2019 13:42:04)
node version: v10.16.0
coc.nvim version: 0.0.72-89a83c1d29
term: dumb
platform: linux

**Comment by chemzqm** [comment]
Please provide output from your language server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by vacheli** [comment]
> Please provide output from your language server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

[Trace - 上午10:51:34] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/vachel/work/code/go/nodeclear/m/m01.go",
    "diagnostics": []
}


Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/m/m01.go"
    },
    "position": {
        "line": 0,
        "character": 0
    }
}

Result: []

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/m/m01.go"
    },
    "position": {
        "line": 0,
        "character": 0
    }
}

Result: []

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/n/n01.go",
        "languageId": "go",
        "version": 1,
        "text": "package n\n\nimport \"nodeclear/m\"\n\nfunc N01() {\n\tm.M01()\n}\n"
    }
}

Params: {
    "uri": "file:///home/vachel/work/code/go/nodeclear/n/n01.go",
    "diagnostics": []
}

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/n/n01.go"
    },
    "position": {
        "line": 0,
        "character": 0
    }
}

Result: []

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/n/n01.go"
    },
    "position": {
        "line": 0,
        "character": 8
    }
}

Result: []

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/n/n01.go"
    },
    "position": {
        "line": 0,
        "character": 8
    }
}

Result: []

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/n/n01.go"
    },
    "position": {
        "line": 0,
        "character": 8
    }
}

Result: []

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/m/m01.go"
    },
    "position": {
        "line": 4,
        "character": 0
    }
}

Result: []

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/m/m01.go"
    },
    "position": {
        "line": 4,
        "character": 0
    }
}

Result: []

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/m/m01.go"
    },
    "position": {
        "line": 4,
        "character": 1
    }
}

Result: []

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/m/m01.go"
    },
    "position": {
        "line": 4,
        "character": 5
    }
}

Result: [
    {
        "range": {
            "start": {
                "line": 4,
                "character": 5
            },
            "end": {
                "line": 4,
                "character": 8
            }
        },
        "kind": 1
    },
    {
        "range": {
            "start": {
                "line": 9,
                "character": 1
            },
            "end": {
                "line": 9,
                "character": 4
            }
        },
        "kind": 1
    }
]

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/m/m01.go",
        "version": 2
    },
    "contentChanges": [
        {
            "text": "package m\n\nimport \"fmt\"\n\nfunc Hello() {\n\tfmt.Println(\"m\")\n}\n\nfunc M02() {\n\tHello()\n}\n"
        }
    ]
}

Params: {
    "uri": "file:///home/vachel/work/code/go/nodeclear/m/m01.go",
    "diagnostics": []
}

Params: {
    "uri": "file:///home/vachel/work/code/go/nodeclear/n/n01.go",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 5,
                    "character": 3
                },
                "end": {
                    "line": 5,
                    "character": 6
                }
            },
            "severity": 1,
            "source": "LSP",
            "message": "M01 not declared by package m"
        }
    ]
}

Params: {
    "textDocument": {
        "uri": "file:///home/vachel/work/code/go/nodeclear/m/m01.go"
    },
    "position": {
        "line": 4,
        "character": 5
    }
}

Result: [
    {
        "range": {
            "start": {
                "line": 4,
                "character": 5
            },
            "end": {
                "line": 4,
                "character": 10
            }
        },
        "kind": 1
    },
    {
        "range": {
            "start": {
                "line": 9,
                "character": 1
            },
            "end": {
                "line": 9,
                "character": 6
            }
        },
        "kind": 1
    }
]

**Comment by vacheli** [comment]
> coc-settings.json  configuration folloing as:
---
{
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": [
        "go.mod",
        ".vim/",
        ".git/",
        ".hg/"
      ],
      "filetypes": [
        "go"
      ],
      "trace.server": "verbose"
    }
  }
}

**Comment by chemzqm** [comment]
Your language server doesn't have rename feature, so it use builtin rename feature which rename current buffer only.
