### ISSUE TITLE
coc-implementation (gi hotkey) returns "Implementation provider not found for current document"

### ISSUE THREAD

**Issue by esn89** [neoclide/coc.nvim#955]
## Result from CocInfo

https://pastebin.com/08rUxi09

## Describe the bug

Using coc.nvim, neovim, coc-python (MPLS), when I use the "gi" hotkey from:
```
nmap <silent> gi <Plug>(coc-implementation)
```

I get this error:

```[coc.nvim] Implementation provider not found for current document```

## Reproduce the bug

Here is a mini vimrc which only contains the coc settings.
https://pastebin.com/jSNQWdsW

## Screenshots (optional)

[img](https://i.imgur.com/h5gVsra.png)

**Comment by chemzqm** [comment]
It's expected since that feature not supported by MPLS.

**Comment by esn89** [comment]
Oops, sorry!
