### ISSUE TITLE
coc.nvim causes vim to delay on a certain command

### ISSUE THREAD

**Issue by theniceboy** [neoclide/coc.nvim#957]
Hi, I just started to use `coc.nvim` and this plugin works really well with my python code. However, there's a tiny issue that I have no idea how to solve and I could not find a solution on the internet.
With `coc.nvim` enabled (there's no issue when it's not enabled or installed), whenever I pressed the `ci` key combination, (which I have previously mapped to another command), Vim delay for a few hundred milliseconds instead of executing my command straight away. I found this in the `:help coc` page:
```
ci    Command-line Insert mode
```

However, I cannot find a way to unmap this. Is this the `Command-line Insert mode` key-combo the problem, or is it something else?

**Comment by chemzqm** [comment]
Checkout your keymap by `verbose nmap ci`, it's vim's feature to delay for key combination.
