### ISSUE TITLE
Does coc support gnu global?

### ISSUE THREAD

**Issue by latiaoxia** [neoclide/coc.nvim#958]
As titled.

**Comment by chemzqm** [comment]
I don't know what is gnu global, but it should be possible for coc.nvim to support it when there is language server build for gnu global.

**Comment by latiaoxia** [comment]
Gnu global is gtag.

**Comment by chemzqm** [comment]
No, there's no support for gtag, what's your suggestion?

**Comment by latiaoxia** [comment]
I know that vscode intellisense plugin takes gtags for indexing, would it be easy to refer to that?
