### ISSUE TITLE
No syntax highlights in popup for Vim

### ISSUE THREAD

**Issue by saaguero** [neoclide/coc.nvim#959]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  8 2019 15:03:57)
node version: v11.14.0
coc.nvim version: 0.0.72-8c7241d7e3
term: dumb
platform: linux

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"test.py" 2L, 29C
missing-docstring: Missing module docstring


E464: Ambiguous use of user-defined command
## Output channel: snippets


## Output channel: Python

Starting Jedi Python language engine.
##########Linting Output - pylint##########

-------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 5.00/10, +5.00)


## Output channel: highlight

[Info  - 3:17:38 PM] Highlight server running in node v11.14.0
```

## Describe the bug

No syntax highlights in popup for Vim with coc-python (in Neovim it works fine). See screenshots, left side Vim, right side Neovim.

## Screenshots (optional)

![2019-07-08_15h45_46](https://user-images.githubusercontent.com/2459621/60834723-b3315880-a197-11e9-8e2f-ea26e9952b88.png)

![2019-07-08_15h46_26](https://user-images.githubusercontent.com/2459621/60834726-b88ea300-a197-11e9-979e-12b2bd553a08.png)

**Comment by chemzqm** [comment]
It's expected since the popup is not a single filetype and it's not possible to parse the highlight in background by use vim8.

**Comment by saaguero** [comment]
I've just read a little bit the Vim documentation and the following seems to allow setting a filetype to the popup buffer:

```vim
let winid = popup_create("import os", {'moved': 'WORD'})
let bufnr = winbufnr(winid)
call setbufvar(bufnr, '&filetype', 'python')
```
Is this something coc.nvim can use to fix this issue?

![image](https://user-images.githubusercontent.com/2459621/60836887-27bac600-a19d-11e9-8b85-af3f42f981cf.png)

**Comment by chemzqm** [comment]
No, the buffer contains lines of different filetypes.

**Comment by saaguero** [comment]
I see. Thanks!

**Comment by chemzqm** [comment]
I've made the popup to have filetype of first document, it could be broken, but should be better than no highlight at all.
