### ISSUE TITLE
Hotkeys to cycle through references without opening a list

### ISSUE THREAD

**Issue by aravind2612krishna** [neoclide/coc.nvim#963]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem as such, but a new feature which makes life easier when navigating code. 

**Describe the solution you'd like**
Coc-highlight already helps me by highlighting all the references of the variable my cursor is on. My request is for abilities to cycle between those highlighted references so that I can assign hotkeys to it. In short my request is for something along the lines of <Plug>(coc-reference-next)  (and prev), just like <Plug>(coc-diagnostic-next) (and prev)

**Describe alternatives you've considered**
The alternative is to find all references and navigate through coc-list, which by itself is not a hassle but overkill when I just want to cycle through all the occurences of local variables within a large function.
The current alternative I use is to find keyword within function scope.

**Additional context**
https://github.com/natebosch/vim-lsc is another plugin I use that has the feature I'm describing above.
Thanks for creating this awesome plugin.

**Comment by chemzqm** [comment]
It's good to have, but not high priority for now.

**Comment by chemzqm** [comment]
Use keymap like:
```
nmap <silent> <C-a> :call CocAction('runCommand', 'document.renameCurrentWord')<CR>
```
to start cursors session, then you can navigate by `<C-n>` and `<C-p>`
