### ISSUE TITLE
[BREAK CHANGE] release tag now use release branch.

### ISSUE THREAD

**Issue by chemzqm** [neoclide/coc.nvim#969]
If you're getting error like `install.sh` not found, it's because release tag now contains bundled javascript code instead of code from master, install scripts are not needed for release code.

Remove `coc#util#install` or `./install.sh` from Plug command to avoid possible error/warning. Or simply ignore that error.

**Comment by jsatk** [comment]
> Remove coc#util#install or ./install.sh from Plug command

How do I do that?

**Comment by chemzqm** [comment]
You don't know how to change vimrc?

**Comment by jsatk** [comment]
@chemzqm 🤦‍♂ I didn't realize this was set in my .vimrc. I thought it was in Plug's code.
