### ISSUE TITLE
Selecting text in diagnostics

### ISSUE THREAD

**Issue by Avi-D-coder** [neoclide/coc.nvim#970]
## Result from CocInfo
vim version: NVIM v0.4.0-1256-g564d415d2
node version: v11.15.0
coc.nvim version: 0.0.73
term: xterm-256color
platform: linux

## Describe the bug
Clicking in floating diagnostic closes the diagnostic. This makes it difficult to scroll diagnostics with key bindings and make selections in them.

## Feature Request
- Clicking in diagnostic should not close the buffer.
- A keybinding that focuses Coc Floating windows

**Comment by chemzqm** [comment]
use <c-w>

**Comment by Avi-D-coder** [comment]
@chemzqm That no longer works. It closes the window after less then a second, same as mouse.

**Comment by Avi-D-coder** [comment]
@chemzqm This should likely be a different issue, but it worth noting as I think the bugs are related.
Scrolling with mouse wheel works over long diagnostics works, but resets back to the top after a fraction of a second.

**Comment by Avi-D-coder** [comment]
@chemzqm Same issue is back.
