### ISSUE TITLE
doHover issue

### ISSUE THREAD

**Issue by ArseniD** [neoclide/coc.nvim#971]
Hi Qiming,

according to documentation I use the following setting in my **~/.vimrc** file in order to get documentation (method description) in a preview window, however each time when I push **"shift + K"** I receive the description and **immediately** go forward to the next word. Could you please kindly look into this issue and clarify what I do wrong or what can impact on such behaviour? FYI, I tried to turn off all plugins and use minimal configuration. Also I tried to use **"coc.preferences.hoverTarget": "echo"** in my coc config file but results the same (show and skip immediately). 

```
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
        execute 'h '.expand('<cword>')
    else
        call CocAction('doHover')
    endif
endfunction
```

**Comment by chemzqm** [comment]
Checkout `:verbose nmap K`
