### ISSUE TITLE
Cursor shape flickers

### ISSUE THREAD

**Issue by ranebrown** [neoclide/coc.nvim#972]
CocInfo:
```
vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 12 2019 19:31:20)
node version: v12.5.0
coc.nvim version: 0.0.72-b24601e6af
term: iTerm.app
platform: darwin
```

When typing in insert mode the cursor shape flickers.
![coc](https://user-images.githubusercontent.com/10778249/61065952-f2db8880-a3c1-11e9-872f-eff17c718cb6.gif)

This is somehow caused by using these settings:

```vim
let &t_SI = "\e[5 q" " insert mode vertical line
let &t_EI = "\e[1 q" " command mode block
```

I have not seen this behavior with other completion engines such as YCM.

**Comment by chemzqm** [comment]
It's because YCM doesn't support TextChangedP event, it's problem of vim.
