### ISSUE TITLE
Settings `rust-client.rlsPath`, `rust-client.disableRustup` ignored if specified in a workspace `coc-settings.json`

### ISSUE THREAD

**Issue by filmil** [neoclide/coc.nvim#981]
## Result from CocInfo

```
## versions

vim version: NVIM v0.3.7
node version: v8.16.0
coc.nvim version: 0.0.73-ca3e389259
term: screen-256color
platform: linux

## Messages
[coc.nvim] Unexpected error initialising RLS - error running rustup
## Output channel: rust-client

[Error  - 01:52:59] Starting client failed: 
Error: Command failed: rustup component list --toolchain fuchsia
error: toolchain 'fuchsia' does not support components
info: caused by: invalid toolchain name: 'fuchsia'

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
```

## Describe the bug

I notice that if `rust-client.rlsPath` is specified in a workspace configuration (`$WORKSPACE/.vim/coc-settings.json`) then it is ignored.  If I specified in the user settings file, it is used.
Now the issue is that for this project I must use a custom `rls` and must not use `rustup`.  But it is not possible to express that.

## Reproduce the bug

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
You have to start edit your project in your `$WORKSPACE`, coc-rls can't support workspaceFolders since rls doesn't support that feature.

**Comment by filmil** [comment]
Sorry, but I don't understand.  What is preventing coc-rls from taking the value of `rlsPath` from this file?

**Comment by chemzqm** [comment]
Don't know, but the first rust file opened by vim must inside your `$WORKSPACE`, so that the file can be resolved.

**Comment by filmil** [comment]
The first rust file is indeed in the workspace.

To compare, if I set up a dart languageserver in a per-workspace manner and repeat the same exercise, the languageserver settings *are* acknowledged.

**Comment by chemzqm** [comment]
Should be problem of you folder, try create a new folder

**Comment by filmil** [comment]
I'm going to try and make a repro case. I don't think there is any problem
with the folders.

**Comment by chemzqm** [comment]
I've tested, that configuration work as expected, in .vim/coc-settings.json

**Comment by filmil** [comment]
Could you describe your setup so I could try to replicate, please?

**Comment by oblitum** [comment]
@filmil one alternative solution for your problem is to `call coc#config('rust-client', { 'rlsPath': '/some/path' })` from a [local vimrc](https://github.com/embear/vim-localvimrc) solution.
