### ISSUE TITLE
"text property info corrupted" when editing go files (using gopls langserver)

### ISSUE THREAD

**Issue by avahe-kellenberger** [neoclide/coc.nvim#983]
## Result from CocInfo
https://0x0.st/z9Tb.txt
(Full output is 6500+ lines from logging langserver)

## Describe the bug

While editing *.go files, vim starts spamming "text property info corrupted" and I'm unable to do anything. Happens very shortly after I begin editing code.

## Reproduce the bug

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create file `mini.vim` with：

  ```vim
filetype off
set nocompatible
call vundle#begin()
Plugin 'fatih/vim-go'
Plugin 'neoclide/coc.nvim', {'branch': 'release'}
call vundle#end()
  ```

- Start vim with command: `vim`

- Attempt editing a *.go file (pressing tab seems to trigger it every time, but isn't the only thing that triggers the error)

**Comment by chemzqm** [comment]
Try update to latest version

**Comment by avahe-kellenberger** [comment]
I ended up fixing it, perhaps not in the intended way. This is what I did:

1. cd $HOME/.config/coc/extensions
2. rm -rf node_modules yarn.lock
3. yarn install

I tried previously to update my extensions through Vundle, and to run :CocUpdate from within vim, but neither of those actions fixed my issue.

**Comment by chemzqm** [comment]
@avahe-kellenberger but it should be a vim issue, did you upgraded your vim as well?

**Comment by avahe-kellenberger** [comment]
Nope, I was already on the latest version.
