### ISSUE TITLE
Showing the method signature as a tooltip

### ISSUE THREAD

**Issue by sameera207** [neoclide/coc.nvim#985]
Hi all, First off hats off to this amazing plugin,   This is the one I've been searching for for the last 1 week. My current project needs some react and as a backend developer (ruby + neovim), with coc, I can still use the same editor without moving to VSCode. 

Now the question :), I have the plugin working, however, the method signatures are showing up in the bottom status line. What I want is to have them in the same line as I type. How can I get it to work?

**This is how it displays currently**
![Screen Shot 2019-07-16 at 4 51 59 pm](https://user-images.githubusercontent.com/98407/61273517-143adb00-a7ed-11e9-9185-fda537a95ce2.png)

**How I want it to show (is as per the README)**
https://user-images.githubusercontent.com/251450/55285193-400a9000-53b9-11e9-8cff-ffe4983c5947.gif

Following is my CocConfig settings 

```
{
  "suggest.echodocSupport": true,
  "suggest.maxCompleteItemCount": 20,
  "coc.preferences.formatOnSaveFiletypes": [
    "javascript",
    "typescript",
    "typescriptreact",
    "json",
    "javascriptreact"
  ],
  "eslint.filetypes": [
    "javascript",
    "typescript",
    "typescriptreact",
    "javascriptreact"
  ],
  "diagnostic.errorSign": "•",
  "diagnostic.warningSign": "•",
  "diagnostic.infoSign": "•"
}
```

Interms of the neovim config, I've copy and paste all the config from the [Example vim configuration](https://github.com/neoclide/coc.nvim#example-vim-configuration)

Pardon me if I've missed out any required info, Let me know if I need to provide with any more details. 

Thanks in advance

cheers,
Sam

**Comment by iamcco** [comment]
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#how-to-make-preview-window-shown-aside-with-pum

**Comment by sameera207** [comment]
Thanks @iamcco, Got the latest version  `NVIM v0.4.0-1285-g519382646` (nightly build) and works perfectly 

<img width="598" alt="Screen Shot 2019-07-16 at 11 51 30 pm" src="https://user-images.githubusercontent.com/98407/61300479-613aa380-a825-11e9-9fcd-32f54b5a630d.png">

**Comment by mogwai** [comment]
Do we need neovim for it to display like this?

**Comment by oblitum** [comment]
@mogwai no, it also works on recent vim version.
