### ISSUE TITLE
Improve plugin update experience with human commit messages

### ISSUE THREAD

**Issue by bugeats** [neoclide/coc.nvim#988]
When using the release branch with vim-plug:

    Plug 'neoclide/coc.nvim', {'branch': 'release'}

My :PlugUpdate` experience looks something like this:

![DeepinScreenshot_select-area_20190717093817](https://user-images.githubusercontent.com/33055/61393987-0762c980-a877-11e9-9895-f9fcdc8026a9.png)

The release commits are just a hash that means nothing to me. It would be nice if updates provided some actual info about what changed. This is especially true for potential breaking changes.

**Comment by chemzqm** [comment]
Fixed

**Comment by bugeats** [comment]
Damn that was fast. Thx!
