### ISSUE TITLE
No completion popup for completion sources not based on language servers (?)

### ISSUE THREAD

**Issue by gbcreation** [neoclide/coc.nvim#99]
**Describe the bug**
Start editing a new JS file (`nvim index.js`) and typing the following code:

```javascript
/**
 * Completion test
 */
function myFunc() {
    console.log("Comp|")
}
```

(`|` is the position of the cursor. Pairs like `()`, `{}` and `""` are auto-closed)

While typing, I got auto-completion for `function`, `console` and `log`. But the completion popup does not automatically appear for the `Comp` word I'm currently typing as argument for `log()`. I have to hit `<Ctrl-p>` to make it appear.

**Expected behavior**
The completion popup should automatically appears for completion sources like "around" and "buffer".

**Comment by chemzqm** [comment]
Can't reproduce it, it works as expected on my Mac, it should popup after just type `C`.
Try update coc to latest version.

**Comment by gbcreation** [comment]
Found out that it is this option in my `init.vim` that causes the issue:
```vim
set iskeyword=a-z,A-Z,48-57,_
```
After commenting it, the completion popup appears correctly.

**Comment by gbcreation** [comment]
OK, waiting for next version :relaxed:
