### ISSUE TITLE
Option to make pum and signatureHelp floating window mutually exclusive

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#990]
**Is your feature request related to a problem? Please describe.**

I don't like too many floating windows covering big part of surrounding code.

**Describe the solution you'd like**

My wish is that I can have at a time only one of the windows open: pum for completion XOR signatureHelp window. I'm not sure this can be accomplished but the idea is that for when one of the two is going to be shown, it will call a command to hide the other.

Another thing to consider too in this context of options for how and which windows may be displayed regards the documentation window that's shown besides signatureHelp. Is there an option to disable it?

**Describe alternatives you've considered**

I'm currently using `call coc#config('signature', {'preferShownAbove': v:false})` to great effect, since the side effect of showing signatureHelp bellow is that it causes most of time the pum to be hidden (because it also prefers to shown bellow), and vice-versa, making them mutually exclusive. But this does not work always, if I'm typing at the bottom of the window, pum most certainly will be shown above (because there's no room for it bellow), but signatureHelp will stay open bellow (because there was room for it), besides that, in fact, preferring signatureHelp bellow or above is a feature of its own which should not be confused with window hiding (reason why this happens).

**Comment by oblitum** [comment]
Was this fixed?

![screencast](https://user-images.githubusercontent.com/1269815/61485661-0cf40880-a978-11e9-8bf6-7fc001865b57.gif)

Also, it's a feature request new options for controlling amount of windows open, not sure it can be fixed without an option.

**Comment by oblitum** [comment]
It seems like these last changes are also causing signatureHelp fail to display on `,`.

**Comment by oblitum** [comment]
This hasn't been fixed at all... :-(

**Comment by chemzqm** [comment]
You can use autocmd `User CocOpenFloat` to hide the popup, check `w:popup` for float window aside with pum and `w:float` for all float window.

**Comment by oblitum** [comment]
Sounds cool, I tried this to check how it works but I never get any message:

```vim
autocmd vimrc User CocOpenFloat if exists('w:popup') | echom 'popup' | else | echo 'no popup' | endif | if exists('w:float') | echom 'float' | else | echo 'no float' | endif
```

I'm trying to understand when `w:popup` and `w:float` should be used, because I dunno any docs about them, but it seems `CocOpenFloat` is never being triggered.

**Comment by chemzqm** [comment]
It's a silent autocmd, can be improved.

**Comment by oblitum** [comment]
No idea how to close (`nvim_win_close`) a previous floating window when `w:popup` exists since I don't have a window id. Besides that, I'm expecting this event is triggered before current popups/windows are displayed, to avoid any confusion on hiding the current ones (doesn't make sense to hide something that just got displayed imediatelly).

**Comment by chemzqm** [comment]
> I don't have a window id.

You can iterate all windows

> I'm expecting this event is triggered before current popups/windows are displayed

No, it's triggered just after float window displayed, it's neovim only, the current window id would be the opened float window, you can just check it.

**Comment by chemzqm** [comment]
> doesn't make sense to immediately hide something that just got displayed

It's possible signature help shown after preview window of pum, so you might want to hide it.

**Comment by oblitum** [comment]
OK, I'll try iterate.

> it's neovim only

I think that could be put in `CocOpenFloat` docs. I was thinking of having to write two implementations until now.

**Comment by oblitum** [comment]
I think `CocOpenFloat` needs to be triggered when pum will be shown, otherwise it seems not useful to fix the issue in the previous gif. I tried this:

```vim
autocmd vimrc User CocOpenFloat
\  if exists('g:previous_window')
\|   try | nvim_win_close(g:previous_window, v:false) | catch | endtry
\| endif
\| let g:previous_window = win_getid()
```

It doesn't work because in the gif I was left with a signature floating window open and when started typing after it, completion pum shows up, without hiding signature, but pum display doesn't trigger `CocOpenFloat`, only floating windows do, so I can't hide that floating window with it.

**Comment by chemzqm** [comment]
> I think CocOpenFloat needs to be triggered when pum will be shown,

No, it's fired on preview window open, all you need is check `w:popup` and close other window that has `w:float` and not current window.

**Comment by oblitum** [comment]
The former problem is having signature floating window closed when a pum window gets open, for not having code covered both bellow and down. It was not about the preview window that's shown on completion selection, in the gif and didn't select anything, but that's indeed an additional scenery I didn't think of, like the following:

![18:38:42_19-07-2019](https://user-images.githubusercontent.com/1269815/61567067-9da01680-aa54-11e9-94f6-0696dcb776a5.png)

But it's not what I mentioned first. Here there's 3 windows floating, 1 pum + 2 floating window, which can be reduced from 3 to 2, but initially I talked about reducing from 2 (1 floating + 1 pum) to 1 (pum XOR floating).

**Comment by chemzqm** [comment]
Use `CompleteChanged` autocmd.

**Comment by oblitum** [comment]
oh, I didn't know about that event, it's not yet in my nvim docs. Finally, I think this is doing what I wanted:

```vim
autocmd vimrc CompleteChanged *
\  if exists('g:previous_window') && nvim_win_is_valid(g:previous_window)
\|   call nvim_win_close(g:previous_window, v:false)
\| endif

autocmd vimrc User CocOpenFloat
\  if exists('w:float')
\|   let g:previous_window = win_getid()
\| endif
```

**Comment by oblitum** [comment]
It works, but if you have any idea of something more simple or clean, I'd like to know about :)

**Comment by oblitum** [comment]
Above solution won't work after https://github.com/neoclide/coc.nvim/commit/4e72e5be04b94fd37f0eae9a9d91db3e28beab1b.

**Comment by oblitum** [comment]
@chemzqm any tip how to achieve the same as above after the latest changes?

**Comment by chemzqm** [comment]
```

function! CloseOthers() abort
  if win_getid() == get(g:, 'coc_popup_id', 0)
    for i in range(1, winnr('$'))
      if getwinvar(i, 'float')
        let winid = win_getid(i)
        if winid != g:coc_popup_id
          call coc#util#close_win(winid)
        endif
      endif
    endfor
  endif
endfunction
```

**Comment by oblitum** [comment]
@chemzqm thx. I'm calling that function at `autocmd vimrc CompleteChanged * call CloseOthers()` but it's not producing the desired effect, actually I'm not seeing any effect and I'm getting completion and float together as in the previous screenshot:

![](https://user-images.githubusercontent.com/1269815/61567067-9da01680-aa54-11e9-94f6-0696dcb776a5.png)

**Comment by chemzqm** [comment]
Use it with CocOpenFloat autocmd

**Comment by oblitum** [comment]
@chemzqm Like as `autocmd vimrc User CocOpenFloat call CloseOthers()` ?

Still no effect.

**Comment by oblitum** [comment]
Not sure whether you're following me here but I don't want both completion pum and signature help float open, that's why `CompleteChanged` was used before, because pum isn't a float window and hence doesn't trigger `CocOpenFloat`.

**Comment by oblitum** [comment]
This fix the problem and does what I'm requesting on this issue, but I'm afraid it's not the best approach because of the loop that will always run on every `CompleteChanged`:

```vim
function! s:coc_close_floats() abort
  for i in range(1, winnr('$'))
    if getwinvar(i, 'float')
      call coc#util#close_win(win_getid(i))
    endif
  endfor
endfunction
autocmd vimrc CompleteChanged * call s:coc_close_floats()
```

Wish I could simply have a command to close all coc floats without having to loop all windows.

**Comment by hantaotaohan** [comment]
> @chemzqm thx. I'm calling that function at `autocmd vimrc CompleteChanged * call CloseOthers()` but it's not producing the desired effect, actually I'm not seeing any effect and I'm getting completion and float together as in the previous screenshot:
> 
> ![](https://user-images.githubusercontent.com/1269815/61567067-9da01680-aa54-11e9-94f6-0696dcb776a5.png)

Could you tell me what your vim color theme ????????

**Comment by hantaotaohan** [comment]
> The former problem is having signature floating window closed when a pum window gets open, for not having code covered both bellow and down. It was not about the preview window that's shown on completion selection, in the gif I didn't select anything at the end, but that's indeed an additional scenery I didn't think of, like the following:
> 
> ![18:38:42_19-07-2019](https://user-images.githubusercontent.com/1269815/61567067-9da01680-aa54-11e9-94f6-0696dcb776a5.png)
> 
> But it's not what I mentioned first. Here there's 3 windows floating (1 pum + 2 floating window), which can be reduced from 3 to 2, but initially I talked about reducing from 2 (1 floating down + 1 pum up) to 1 (pum XOR floating).

Could you tell me what your vim color theme ????????

**Comment by oblitum** [comment]
@hantaotaohan https://github.com/tyrannicaltoucan/vim-deep-space

**Comment by hantaotaohan** [comment]
> @hantaotaohan https://github.com/tyrannicaltoucan/vim-deep-space

thanks!!!

**Comment by jacobsandlund** [comment]
For anyone coming to this issue, the api has changed so you need to call:

```vim
autocmd CompleteChanged * call coc#float#close_all()
```
