### ISSUE TITLE
Better error hint position will not hide code below conflict marks

### ISSUE THREAD

**Issue by maple-leaf** [neoclide/coc.nvim#991]
**Is your feature request related to a problem? Please describe.**
when deal with git conflict, the error message will hide code below conflict mark

Like below screenshot, JSON error hide the code below `<<<<` mark, which make it un-convenient. Is there's some way to prevent this?

![image](https://user-images.githubusercontent.com/3980995/61424243-74dd2b80-a945-11e9-819e-a7d0bff7683e.png)

**Comment by oblitum** [comment]
I'd call `:CocDisable` while editing that, but I'm not sure, at the moment, whether the command will ensure any open floating window is closed, it should. Then after editing it, I'd call back `:CocEnable`.

**Comment by chemzqm** [comment]
No, you can configure diagnostic target to echo or use `:CocDisable` when you have conflict.
