### ISSUE TITLE
Autocompletion - uses fuzzy search vs normal

### ISSUE THREAD

**Issue by mikeTWC1984** [neoclide/coc.nvim#992]
## versions

vim version: NVIM v0.3.7
node version: v10.16.0
coc.nvim version: 0.0.73-56825890dc
term: xterm-256color
platform: linux

## Describe the bug

I'm using coc-powershell extension. In many case when I'm typing commands, the proper match appears somewhere in the middle or end of  suggestion list. Looks like some fuzzy search is used and then results are sorted alphabetically. For example when I'm trying to type "Get-Content" I see this:
![Screenshot from 2019-07-17 23-34-51](https://user-images.githubusercontent.com/31977106/61427258-82fe5e00-a8eb-11e9-83d4-fdc488328d23.png)

As extension author suggested it's an upstream problem of coc. Is there a way to configure this?

**Comment by chemzqm** [comment]
> Is there a way to configure this?

It's sorted by match score, looks like the algorithm can be improved.
